<?php

// City package for Brazil 

$city_name = 'Brazil';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'BRXX0001', 'name' => 'Adamantina');
$city_data[] = array('accid' => 'BRXX0002', 'name' => 'Alagoinhas');
$city_data[] = array('accid' => 'BRXX0003', 'name' => 'Alegrete');
$city_data[] = array('accid' => 'BRXX0005', 'name' => 'Altamira');
$city_data[] = array('accid' => 'BRXX0006', 'name' => 'Americana');
$city_data[] = array('accid' => 'BRXX0007', 'name' => 'Anapolis');
$city_data[] = array('accid' => 'BRXX0008', 'name' => 'Anastacio');
$city_data[] = array('accid' => 'BRXX0009', 'name' => 'Andradina');
$city_data[] = array('accid' => 'BRXX0010', 'name' => 'Apucarana');
$city_data[] = array('accid' => 'BRXX0011', 'name' => 'Aracaju');
$city_data[] = array('accid' => 'BRXX0012', 'name' => 'Aracati');
$city_data[] = array('accid' => 'BRXX0013', 'name' => 'Aracatuba');
$city_data[] = array('accid' => 'BRXX0014', 'name' => 'Aracruz');
$city_data[] = array('accid' => 'BRXX0015', 'name' => 'Arapiraca');
$city_data[] = array('accid' => 'BRXX0016', 'name' => 'Arapongas');
$city_data[] = array('accid' => 'BRXX0017', 'name' => 'Araucaria');
$city_data[] = array('accid' => 'BRXX0018', 'name' => 'Araxa');
$city_data[] = array('accid' => 'BRXX0019', 'name' => 'Aripuana');
$city_data[] = array('accid' => 'BRXX0020', 'name' => 'Auriflama');
$city_data[] = array('accid' => 'BRXX0021', 'name' => 'Avare');
$city_data[] = array('accid' => 'BRXX0022', 'name' => 'Bage');
$city_data[] = array('accid' => 'BRXX0023', 'name' => 'Balsamo');
$city_data[] = array('accid' => 'BRXX0024', 'name' => 'Balsas');
$city_data[] = array('accid' => 'BRXX0025', 'name' => 'Bandeirantes');
$city_data[] = array('accid' => 'BRXX0026', 'name' => 'Barbacena');
$city_data[] = array('accid' => 'BRXX0027', 'name' => 'Barcelos');
$city_data[] = array('accid' => 'BRXX0028', 'name' => 'Barra do Garcas');
$city_data[] = array('accid' => 'BRXX0029', 'name' => 'Barra Mansa');
$city_data[] = array('accid' => 'BRXX0030', 'name' => 'Barreiras');
$city_data[] = array('accid' => 'BRXX0031', 'name' => 'Bauru');
$city_data[] = array('accid' => 'BRXX0032', 'name' => 'Belem');
$city_data[] = array('accid' => 'BRXX0033', 'name' => 'Belo Horizonte');
$city_data[] = array('accid' => 'BRXX0034', 'name' => 'Bento Goncalves');
$city_data[] = array('accid' => 'BRXX0035', 'name' => 'Biguacu');
$city_data[] = array('accid' => 'BRXX0036', 'name' => 'Birigui');
$city_data[] = array('accid' => 'BRXX0037', 'name' => 'Blumenau');
$city_data[] = array('accid' => 'BRXX0038', 'name' => 'Boa Vista');
$city_data[] = array('accid' => 'BRXX0039', 'name' => 'Bom Despacho');
$city_data[] = array('accid' => 'BRXX0040', 'name' => 'Bom Jesus da Lapa');
$city_data[] = array('accid' => 'BRXX0041', 'name' => 'Botucatu');
$city_data[] = array('accid' => 'BRXX0042', 'name' => 'Braganca Paulista');
$city_data[] = array('accid' => 'BRXX0043', 'name' => 'Brasilia');
$city_data[] = array('accid' => 'BRXX0044', 'name' => 'Brusque');
$city_data[] = array('accid' => 'BRXX0045', 'name' => 'Cabo Frio');
$city_data[] = array('accid' => 'BRXX0046', 'name' => 'Caceres');
$city_data[] = array('accid' => 'BRXX0048', 'name' => 'Cachoeiro de Itap');
$city_data[] = array('accid' => 'BRXX0049', 'name' => 'Campina Grande');
$city_data[] = array('accid' => 'BRXX0050', 'name' => 'Campinas');
$city_data[] = array('accid' => 'BRXX0051', 'name' => 'Campo Grande');
$city_data[] = array('accid' => 'BRXX0052', 'name' => 'Campo Largo');
$city_data[] = array('accid' => 'BRXX0053', 'name' => 'Campo Mourao');
$city_data[] = array('accid' => 'BRXX0054', 'name' => 'Campos');
$city_data[] = array('accid' => 'BRXX0055', 'name' => 'Campos do Jordao');
$city_data[] = array('accid' => 'BRXX0056', 'name' => 'Canoas');
$city_data[] = array('accid' => 'BRXX0057', 'name' => 'Canoinhas');
$city_data[] = array('accid' => 'BRXX0058', 'name' => 'Canto do Buriti');
$city_data[] = array('accid' => 'BRXX0059', 'name' => 'Caraguatatuba');
$city_data[] = array('accid' => 'BRXX0060', 'name' => 'Carapina');
$city_data[] = array('accid' => 'BRXX0061', 'name' => 'Caratinga');
$city_data[] = array('accid' => 'BRXX0062', 'name' => 'Caravelas');
$city_data[] = array('accid' => 'BRXX0063', 'name' => 'Cascavel');
$city_data[] = array('accid' => 'BRXX0064', 'name' => 'Castro');
$city_data[] = array('accid' => 'BRXX0065', 'name' => 'Catalao');
$city_data[] = array('accid' => 'BRXX0066', 'name' => 'Catanduva');
$city_data[] = array('accid' => 'BRXX0067', 'name' => 'Caxias');
$city_data[] = array('accid' => 'BRXX0068', 'name' => 'Caxias do Sul');
$city_data[] = array('accid' => 'BRXX0069', 'name' => 'Chapeco');
$city_data[] = array('accid' => 'BRXX0070', 'name' => 'Colatina');
$city_data[] = array('accid' => 'BRXX0071', 'name' => 'Colombo');
$city_data[] = array('accid' => 'BRXX0072', 'name' => 'Conselheiro Lafai');
$city_data[] = array('accid' => 'BRXX0073', 'name' => 'Cornelio Procopio');
$city_data[] = array('accid' => 'BRXX0074', 'name' => 'Corumba');
$city_data[] = array('accid' => 'BRXX0075', 'name' => 'Coxim');
$city_data[] = array('accid' => 'BRXX0076', 'name' => 'Criciuma');
$city_data[] = array('accid' => 'BRXX0077', 'name' => 'Cruzeta');
$city_data[] = array('accid' => 'BRXX0078', 'name' => 'Cuiaba');
$city_data[] = array('accid' => 'BRXX0079', 'name' => 'Curitiba');
$city_data[] = array('accid' => 'BRXX0080', 'name' => 'Curitibanos');
$city_data[] = array('accid' => 'BRXX0081', 'name' => 'Curvelo');
$city_data[] = array('accid' => 'BRXX0082', 'name' => 'Diadema');
$city_data[] = array('accid' => 'BRXX0083', 'name' => 'Diamantina');
$city_data[] = array('accid' => 'BRXX0084', 'name' => 'Divinopolis');
$city_data[] = array('accid' => 'BRXX0085', 'name' => 'Dourados');
$city_data[] = array('accid' => 'BRXX0086', 'name' => 'Dracena');
$city_data[] = array('accid' => 'BRXX0087', 'name' => 'Duque de Caxias');
$city_data[] = array('accid' => 'BRXX0088', 'name' => 'Farroupilha');
$city_data[] = array('accid' => 'BRXX0089', 'name' => 'Feira de Santana');
$city_data[] = array('accid' => 'BRXX0090', 'name' => 'Fernandopolis');
$city_data[] = array('accid' => 'BRXX0091', 'name' => 'Florianopolis');
$city_data[] = array('accid' => 'BRXX0092', 'name' => 'Formosa');
$city_data[] = array('accid' => 'BRXX0093', 'name' => 'Fortaleza');
$city_data[] = array('accid' => 'BRXX0094', 'name' => 'Foz do Iguacu');
$city_data[] = array('accid' => 'BRXX0095', 'name' => 'Franca');
$city_data[] = array('accid' => 'BRXX0096', 'name' => 'Garanhuns');
$city_data[] = array('accid' => 'BRXX0097', 'name' => 'Garopaba');
$city_data[] = array('accid' => 'BRXX0098', 'name' => 'Gaspar');
$city_data[] = array('accid' => 'BRXX0099', 'name' => 'Goiania');
$city_data[] = array('accid' => 'BRXX0100', 'name' => 'Governador Valada');
$city_data[] = array('accid' => 'BRXX0101', 'name' => 'Gramado');
$city_data[] = array('accid' => 'BRXX0102', 'name' => 'Guaiba');
$city_data[] = array('accid' => 'BRXX0103', 'name' => 'Guarapari');
$city_data[] = array('accid' => 'BRXX0104', 'name' => 'Guarapuava');
$city_data[] = array('accid' => 'BRXX0105', 'name' => 'Guararapes');
$city_data[] = array('accid' => 'BRXX0106', 'name' => 'Guaratuba');
$city_data[] = array('accid' => 'BRXX0107', 'name' => 'Guarulhos');
$city_data[] = array('accid' => 'BRXX0108', 'name' => 'Hidrolandia');
$city_data[] = array('accid' => 'BRXX0109', 'name' => 'Iguape');
$city_data[] = array('accid' => 'BRXX0110', 'name' => 'Indaial');
$city_data[] = array('accid' => 'BRXX0111', 'name' => 'Inhumas');
$city_data[] = array('accid' => 'BRXX0112', 'name' => 'Ipatinga');
$city_data[] = array('accid' => 'BRXX0113', 'name' => 'Irati');
$city_data[] = array('accid' => 'BRXX0114', 'name' => 'Itaberaba');
$city_data[] = array('accid' => 'BRXX0115', 'name' => 'Itajai');
$city_data[] = array('accid' => 'BRXX0116', 'name' => 'Itaperuna');
$city_data[] = array('accid' => 'BRXX0117', 'name' => 'Itapeva');
$city_data[] = array('accid' => 'BRXX0118', 'name' => 'Itaquari');
$city_data[] = array('accid' => 'BRXX0119', 'name' => 'Itaqui');
$city_data[] = array('accid' => 'BRXX0120', 'name' => 'Itauna');
$city_data[] = array('accid' => 'BRXX0121', 'name' => 'Itu');
$city_data[] = array('accid' => 'BRXX0122', 'name' => 'Ituiutaba');
$city_data[] = array('accid' => 'BRXX0123', 'name' => 'Jacareacanga');
$city_data[] = array('accid' => 'BRXX0124', 'name' => 'Jaciara');
$city_data[] = array('accid' => 'BRXX0125', 'name' => 'Janauba');
$city_data[] = array('accid' => 'BRXX0126', 'name' => 'Jaragua do Sul');
$city_data[] = array('accid' => 'BRXX0127', 'name' => 'Ji-Parana');
$city_data[] = array('accid' => 'BRXX0128', 'name' => 'Joao Pessoa');
$city_data[] = array('accid' => 'BRXX0130', 'name' => 'Joinville');
$city_data[] = array('accid' => 'BRXX0131', 'name' => 'Juiz de Fora');
$city_data[] = array('accid' => 'BRXX0133', 'name' => 'Labrea');
$city_data[] = array('accid' => 'BRXX0134', 'name' => 'Limeira');
$city_data[] = array('accid' => 'BRXX0135', 'name' => 'Linhares');
$city_data[] = array('accid' => 'BRXX0136', 'name' => 'Santana do Livram');
$city_data[] = array('accid' => 'BRXX0137', 'name' => 'Londrina');
$city_data[] = array('accid' => 'BRXX0138', 'name' => 'Lorena');
$city_data[] = array('accid' => 'BRXX0139', 'name' => 'Lourenco');
$city_data[] = array('accid' => 'BRXX0140', 'name' => 'Luziania');
$city_data[] = array('accid' => 'BRXX0141', 'name' => 'Barra de Macae');
$city_data[] = array('accid' => 'BRXX0142', 'name' => 'Macapa');
$city_data[] = array('accid' => 'BRXX0143', 'name' => 'Maceio');
$city_data[] = array('accid' => 'BRXX0144', 'name' => 'Mafra');
$city_data[] = array('accid' => 'BRXX0145', 'name' => 'Mage');
$city_data[] = array('accid' => 'BRXX0146', 'name' => 'Manaus');
$city_data[] = array('accid' => 'BRXX0147', 'name' => 'Manhuacu');
$city_data[] = array('accid' => 'BRXX0148', 'name' => 'Manicore');
$city_data[] = array('accid' => 'BRXX0149', 'name' => 'Maraba');
$city_data[] = array('accid' => 'BRXX0150', 'name' => 'Marilia');
$city_data[] = array('accid' => 'BRXX0151', 'name' => 'Maringa');
$city_data[] = array('accid' => 'BRXX0152', 'name' => 'Maua');
$city_data[] = array('accid' => 'BRXX0153', 'name' => 'Mazagao');
$city_data[] = array('accid' => 'BRXX0154', 'name' => 'Medianeira');
$city_data[] = array('accid' => 'BRXX0155', 'name' => 'Montes Claros');
$city_data[] = array('accid' => 'BRXX0156', 'name' => 'Morrinhos');
$city_data[] = array('accid' => 'BRXX0157', 'name' => 'Mossoro');
$city_data[] = array('accid' => 'BRXX0158', 'name' => 'Natal');
$city_data[] = array('accid' => 'BRXX0159', 'name' => 'Niteroi');
$city_data[] = array('accid' => 'BRXX0161', 'name' => 'Nova Iguacu');
$city_data[] = array('accid' => 'BRXX0162', 'name' => 'Nova Lima');
$city_data[] = array('accid' => 'BRXX0163', 'name' => 'Novo Hamburgo');
$city_data[] = array('accid' => 'BRXX0164', 'name' => 'Olinda');
$city_data[] = array('accid' => 'BRXX0165', 'name' => 'Osasco');
$city_data[] = array('accid' => 'BRXX0166', 'name' => 'Ourinhos');
$city_data[] = array('accid' => 'BRXX0167', 'name' => 'Pacajus');
$city_data[] = array('accid' => 'BRXX0168', 'name' => 'Palmares');
$city_data[] = array('accid' => 'BRXX0169', 'name' => 'Palmas');
$city_data[] = array('accid' => 'BRXX0170', 'name' => 'Paracatu');
$city_data[] = array('accid' => 'BRXX0171', 'name' => 'Paraguacu Paulist');
$city_data[] = array('accid' => 'BRXX0172', 'name' => 'Paranagua');
$city_data[] = array('accid' => 'BRXX0173', 'name' => 'Parintins');
$city_data[] = array('accid' => 'BRXX0174', 'name' => 'Passo Fundo');
$city_data[] = array('accid' => 'BRXX0175', 'name' => 'Pauini');
$city_data[] = array('accid' => 'BRXX0176', 'name' => 'Pelotas');
$city_data[] = array('accid' => 'BRXX0177', 'name' => 'Penapolis');
$city_data[] = array('accid' => 'BRXX0178', 'name' => 'Peruibe');
$city_data[] = array('accid' => 'BRXX0179', 'name' => 'Petrolina');
$city_data[] = array('accid' => 'BRXX0180', 'name' => 'Petropolis');
$city_data[] = array('accid' => 'BRXX0181', 'name' => 'Piracicaba');
$city_data[] = array('accid' => 'BRXX0182', 'name' => 'Pirapora');
$city_data[] = array('accid' => 'BRXX0183', 'name' => 'Pocos de Caldas');
$city_data[] = array('accid' => 'BRXX0184', 'name' => 'Ponta Grossa');
$city_data[] = array('accid' => 'BRXX0185', 'name' => 'Ponta Pora');
$city_data[] = array('accid' => 'BRXX0186', 'name' => 'Porto Alegre');
$city_data[] = array('accid' => 'BRXX0187', 'name' => 'Porto Artur');
$city_data[] = array('accid' => 'BRXX0188', 'name' => 'Porto Feliz');
$city_data[] = array('accid' => 'BRXX0189', 'name' => 'Porto Nacional');
$city_data[] = array('accid' => 'BRXX0190', 'name' => 'Porto Velho');
$city_data[] = array('accid' => 'BRXX0192', 'name' => 'Presidente Pruden');
$city_data[] = array('accid' => 'BRXX0193', 'name' => 'Primavera do Lest');
$city_data[] = array('accid' => 'BRXX0194', 'name' => 'Quixeramobim');
$city_data[] = array('accid' => 'BRXX0195', 'name' => 'Recife');
$city_data[] = array('accid' => 'BRXX0196', 'name' => 'Registro');
$city_data[] = array('accid' => 'BRXX0197', 'name' => 'Resende');
$city_data[] = array('accid' => 'BRXX0198', 'name' => 'Ribeirao Preto');
$city_data[] = array('accid' => 'BRXX0199', 'name' => 'Rio Branco');
$city_data[] = array('accid' => 'BRXX0201', 'name' => 'Rio de Janeiro');
$city_data[] = array('accid' => 'BRXX0202', 'name' => 'Rio Grande');
$city_data[] = array('accid' => 'BRXX0203', 'name' => 'Rio Grande da Ser');
$city_data[] = array('accid' => 'BRXX0204', 'name' => 'Rio Largo');
$city_data[] = array('accid' => 'BRXX0205', 'name' => 'Rio Verde');
$city_data[] = array('accid' => 'BRXX0206', 'name' => 'Rolandia');
$city_data[] = array('accid' => 'BRXX0207', 'name' => 'Rondonopolis');
$city_data[] = array('accid' => 'BRXX0208', 'name' => 'Rosairo');
$city_data[] = array('accid' => 'BRXX0209', 'name' => 'Rosario Oeste');
$city_data[] = array('accid' => 'BRXX0210', 'name' => 'Rozendo');
$city_data[] = array('accid' => 'BRXX0211', 'name' => 'Sabara');
$city_data[] = array('accid' => 'BRXX0212', 'name' => 'Salto do Urubupun');
$city_data[] = array('accid' => 'BRXX0214', 'name' => 'Santa Isabel');
$city_data[] = array('accid' => 'BRXX0215', 'name' => 'Santa Maria');
$city_data[] = array('accid' => 'BRXX0216', 'name' => 'Santarem');
$city_data[] = array('accid' => 'BRXX0217', 'name' => 'Santo Andre');
$city_data[] = array('accid' => 'BRXX0219', 'name' => 'Santos Dumont');
$city_data[] = array('accid' => 'BRXX0220', 'name' => 'Sao Bernardo do C');
$city_data[] = array('accid' => 'BRXX0221', 'name' => 'Sao Caetano');
$city_data[] = array('accid' => 'BRXX0222', 'name' => 'Sao Carlos');
$city_data[] = array('accid' => 'BRXX0223', 'name' => 'Sao Felix do Xing');
$city_data[] = array('accid' => 'BRXX0224', 'name' => 'Sao Gabriel da Ca');
$city_data[] = array('accid' => 'BRXX0225', 'name' => 'Sao Joao de Barra');
$city_data[] = array('accid' => 'BRXX0226', 'name' => 'Sao Joaquim');
$city_data[] = array('accid' => 'BRXX0227', 'name' => 'Sao Jose do Rio P');
$city_data[] = array('accid' => 'BRXX0228', 'name' => 'Sao Jose Dos Camp');
$city_data[] = array('accid' => 'BRXX0229', 'name' => 'Sao Jose dos Pinh');
$city_data[] = array('accid' => 'BRXX0230', 'name' => 'Sao Leopoldo');
$city_data[] = array('accid' => 'BRXX0231', 'name' => 'Sao Luis');
$city_data[] = array('accid' => 'BRXX0232', 'name' => 'Sao Paulo');
$city_data[] = array('accid' => 'BRXX0233', 'name' => 'Sao Vicente');
$city_data[] = array('accid' => 'BRXX0234', 'name' => 'Serra');
$city_data[] = array('accid' => 'BRXX0235', 'name' => 'Sete Lagoas');
$city_data[] = array('accid' => 'BRXX0236', 'name' => 'Sinop');
$city_data[] = array('accid' => 'BRXX0237', 'name' => 'Sorocaba');
$city_data[] = array('accid' => 'BRXX0238', 'name' => 'Tabatinga');
$city_data[] = array('accid' => 'BRXX0239', 'name' => 'Tangara');
$city_data[] = array('accid' => 'BRXX0240', 'name' => 'Tarauaca');
$city_data[] = array('accid' => 'BRXX0241', 'name' => 'Tatui');
$city_data[] = array('accid' => 'BRXX0242', 'name' => 'Taubate');
$city_data[] = array('accid' => 'BRXX0243', 'name' => 'Tefe');
$city_data[] = array('accid' => 'BRXX0244', 'name' => 'Terenos');
$city_data[] = array('accid' => 'BRXX0245', 'name' => 'Teresina');
$city_data[] = array('accid' => 'BRXX0246', 'name' => 'Tijucas');
$city_data[] = array('accid' => 'BRXX0247', 'name' => 'Tres Lagoas');
$city_data[] = array('accid' => 'BRXX0248', 'name' => 'Trindade');
$city_data[] = array('accid' => 'BRXX0249', 'name' => 'Tubarao');
$city_data[] = array('accid' => 'BRXX0250', 'name' => 'Tupa');
$city_data[] = array('accid' => 'BRXX0251', 'name' => 'Ubatuba');
$city_data[] = array('accid' => 'BRXX0252', 'name' => 'Uberaba');
$city_data[] = array('accid' => 'BRXX0253', 'name' => 'Uberlandia');
$city_data[] = array('accid' => 'BRXX0254', 'name' => 'Uruguaiana');
$city_data[] = array('accid' => 'BRXX0255', 'name' => 'Varzea Grande');
$city_data[] = array('accid' => 'BRXX0256', 'name' => 'Vera Cruz');
$city_data[] = array('accid' => 'BRXX0257', 'name' => 'Viamao');
$city_data[] = array('accid' => 'BRXX0258', 'name' => 'Vilhena');
$city_data[] = array('accid' => 'BRXX0259', 'name' => 'Vitoria');
$city_data[] = array('accid' => 'BRXX0260', 'name' => 'Vitoria da Conqui');
$city_data[] = array('accid' => 'BRXX0261', 'name' => 'Votuporanga');
$city_data[] = array('accid' => 'BRXX0263', 'name' => 'Angra dos Reis');
$city_data[] = array('accid' => 'BRXX0264', 'name' => 'Araguari');
$city_data[] = array('accid' => 'BRXX0265', 'name' => 'Araraquara');
$city_data[] = array('accid' => 'BRXX0266', 'name' => 'Arvoredo');
$city_data[] = array('accid' => 'BRXX0267', 'name' => 'Assis');
$city_data[] = array('accid' => 'BRXX0268', 'name' => 'Bertioga');
$city_data[] = array('accid' => 'BRXX0269', 'name' => 'Buzios');
$city_data[] = array('accid' => 'BRXX0270', 'name' => 'Cacapava');
$city_data[] = array('accid' => 'BRXX0271', 'name' => 'Camboriu');
$city_data[] = array('accid' => 'BRXX0272', 'name' => 'Carapicuiba');
$city_data[] = array('accid' => 'BRXX0273', 'name' => 'Caruaru');
$city_data[] = array('accid' => 'BRXX0274', 'name' => 'Castanhal');
$city_data[] = array('accid' => 'BRXX0275', 'name' => 'Cianorte');
$city_data[] = array('accid' => 'BRXX0276', 'name' => 'Concordia');
$city_data[] = array('accid' => 'BRXX0277', 'name' => 'Cruz Alta');
$city_data[] = array('accid' => 'BRXX0278', 'name' => 'Currais Novos');
$city_data[] = array('accid' => 'BRXX0279', 'name' => 'Erexim');
$city_data[] = array('accid' => 'BRXX0280', 'name' => 'Gravatai');
$city_data[] = array('accid' => 'BRXX0281', 'name' => 'Guaruja');
$city_data[] = array('accid' => 'BRXX0282', 'name' => 'Ilhabela');
$city_data[] = array('accid' => 'BRXX0283', 'name' => 'Ilheus');
$city_data[] = array('accid' => 'BRXX0284', 'name' => 'Itabaiana');
$city_data[] = array('accid' => 'BRXX0285', 'name' => 'Itabuna');
$city_data[] = array('accid' => 'BRXX0286', 'name' => 'Itanhaem');
$city_data[] = array('accid' => 'BRXX0287', 'name' => 'Itapetininga');
$city_data[] = array('accid' => 'BRXX0288', 'name' => 'Muribeca dos Guar');
$city_data[] = array('accid' => 'BRXX0289', 'name' => 'Jequie');
$city_data[] = array('accid' => 'BRXX0290', 'name' => 'Juazeiro do Norte');
$city_data[] = array('accid' => 'BRXX0291', 'name' => 'Lages');
$city_data[] = array('accid' => 'BRXX0292', 'name' => 'Laguna');
$city_data[] = array('accid' => 'BRXX0293', 'name' => 'Lins');
$city_data[] = array('accid' => 'BRXX0294', 'name' => 'Maracanau');
$city_data[] = array('accid' => 'BRXX0295', 'name' => 'Maresias');
$city_data[] = array('accid' => 'BRXX0296', 'name' => 'Mogi Das Cruzes');
$city_data[] = array('accid' => 'BRXX0297', 'name' => 'Mogi-Guacu');
$city_data[] = array('accid' => 'BRXX0298', 'name' => 'Mongagua');
$city_data[] = array('accid' => 'BRXX0299', 'name' => 'Nilopolis');
$city_data[] = array('accid' => 'BRXX0300', 'name' => 'Parati');
$city_data[] = array('accid' => 'BRXX0302', 'name' => 'Patos de Minas');
$city_data[] = array('accid' => 'BRXX0303', 'name' => 'Patrocinio');
$city_data[] = array('accid' => 'BRXX0304', 'name' => 'Paulista');
$city_data[] = array('accid' => 'BRXX0305', 'name' => 'Pedra Azul');
$city_data[] = array('accid' => 'BRXX0306', 'name' => 'Porto Seguro');
$city_data[] = array('accid' => 'BRXX0307', 'name' => 'Santa Branca');
$city_data[] = array('accid' => 'BRXX0308', 'name' => 'Santa Cruz do Sul');
$city_data[] = array('accid' => 'BRXX0309', 'name' => 'Sao Joao del Rei');
$city_data[] = array('accid' => 'BRXX0310', 'name' => 'Sao Mateus');
$city_data[] = array('accid' => 'BRXX0311', 'name' => 'Sao Sebastiao');
$city_data[] = array('accid' => 'BRXX0312', 'name' => 'Sobral');
$city_data[] = array('accid' => 'BRXX0313', 'name' => 'Sumare');
$city_data[] = array('accid' => 'BRXX0314', 'name' => 'Teofilo Otoni');
$city_data[] = array('accid' => 'BRXX0315', 'name' => 'Teresopolis');
$city_data[] = array('accid' => 'BRXX0316', 'name' => 'Timon');
$city_data[] = array('accid' => 'BRXX0317', 'name' => 'Umuarama');
$city_data[] = array('accid' => 'BRXX0318', 'name' => 'Varginha');
$city_data[] = array('accid' => 'BRXX0319', 'name' => 'Vila Velha');
$city_data[] = array('accid' => 'BRXX0320', 'name' => 'Volta Redonda');
$city_data[] = array('accid' => 'BRXX0323', 'name' => 'Ilheus Aeroporto');
$city_data[] = array('accid' => 'BRXX0327', 'name' => 'Santa Marta');
$city_data[] = array('accid' => 'BRXX0333', 'name' => 'Boraciia');
$city_data[] = array('accid' => 'BRXX0336', 'name' => 'Juquia');
$city_data[] = array('accid' => 'BRXX0339', 'name' => 'Alta Floresta');
$city_data[] = array('accid' => 'BRXX0340', 'name' => 'Imperatriz');
$city_data[] = array('accid' => 'BRXX0341', 'name' => 'Santana do Piragu');
$city_data[] = array('accid' => 'BRXX0342', 'name' => 'Poa');
$city_data[] = array('accid' => 'BRXX0343', 'name' => 'Paulinia');
$city_data[] = array('accid' => 'BRXX0344', 'name' => 'Sao Roque');
$city_data[] = array('accid' => 'BRXX0345', 'name' => 'Cabreuva');
$city_data[] = array('accid' => 'BRXX0346', 'name' => 'Abaete');
$city_data[] = array('accid' => 'BRXX0347', 'name' => 'Afua');
$city_data[] = array('accid' => 'BRXX0348', 'name' => 'Aguai');
$city_data[] = array('accid' => 'BRXX0349', 'name' => 'Aguas de Sao Pedr');
$city_data[] = array('accid' => 'BRXX0350', 'name' => 'Aguas Formosas');
$city_data[] = array('accid' => 'BRXX0351', 'name' => 'Aimores');
$city_data[] = array('accid' => 'BRXX0352', 'name' => 'Alpinopolis');
$city_data[] = array('accid' => 'BRXX0353', 'name' => 'Alvaraes');
$city_data[] = array('accid' => 'BRXX0354', 'name' => 'Alvares Machado');
$city_data[] = array('accid' => 'BRXX0355', 'name' => 'Andira');
$city_data[] = array('accid' => 'BRXX0356', 'name' => 'Apiai');
$city_data[] = array('accid' => 'BRXX0357', 'name' => 'Araguaina');
$city_data[] = array('accid' => 'BRXX0358', 'name' => 'Aruja');
$city_data[] = array('accid' => 'BRXX0359', 'name' => 'Bambui');
$city_data[] = array('accid' => 'BRXX0360', 'name' => 'Barra de Sao Fran');
$city_data[] = array('accid' => 'BRXX0361', 'name' => 'Barra do Pirai');
$city_data[] = array('accid' => 'BRXX0362', 'name' => 'Boa Esperanca');
$city_data[] = array('accid' => 'BRXX0363', 'name' => 'Bocaiuva');
$city_data[] = array('accid' => 'BRXX0364', 'name' => 'Jau');
$city_data[] = array('accid' => 'BRXX0365', 'name' => 'Caete');
$city_data[] = array('accid' => 'BRXX0366', 'name' => 'Capao Bonito');
$city_data[] = array('accid' => 'BRXX0367', 'name' => 'Capao da Canoa');
$city_data[] = array('accid' => 'BRXX0368', 'name' => 'Caparao');
$city_data[] = array('accid' => 'BRXX0369', 'name' => 'Caracarai');
$city_data[] = array('accid' => 'BRXX0370', 'name' => 'Cerqueira Cesar');
$city_data[] = array('accid' => 'BRXX0371', 'name' => 'Cesario Lange');
$city_data[] = array('accid' => 'BRXX0372', 'name' => 'Cipo');
$city_data[] = array('accid' => 'BRXX0373', 'name' => 'Codajas');
$city_data[] = array('accid' => 'BRXX0374', 'name' => 'Cristalandia');
$city_data[] = array('accid' => 'BRXX0375', 'name' => 'Cubatao');
$city_data[] = array('accid' => 'BRXX0376', 'name' => 'Curuca');
$city_data[] = array('accid' => 'BRXX0377', 'name' => 'Espirito Santo do');
$city_data[] = array('accid' => 'BRXX0378', 'name' => 'Feijo');
$city_data[] = array('accid' => 'BRXX0379', 'name' => 'Filadelfia');
$city_data[] = array('accid' => 'BRXX0380', 'name' => 'Francisco Sa');
$city_data[] = array('accid' => 'BRXX0381', 'name' => 'Grao Mogol');
$city_data[] = array('accid' => 'BRXX0382', 'name' => 'Guaira');
$city_data[] = array('accid' => 'BRXX0383', 'name' => 'Guaratingueta');
$city_data[] = array('accid' => 'BRXX0384', 'name' => 'Gurupa');
$city_data[] = array('accid' => 'BRXX0385', 'name' => 'Humaita');
$city_data[] = array('accid' => 'BRXX0386', 'name' => 'Ibiai');
$city_data[] = array('accid' => 'BRXX0387', 'name' => 'Ibiuna');
$city_data[] = array('accid' => 'BRXX0388', 'name' => 'Iepe');
$city_data[] = array('accid' => 'BRXX0389', 'name' => 'Ipero');
$city_data[] = array('accid' => 'BRXX0390', 'name' => 'Ipiiba');
$city_data[] = array('accid' => 'BRXX0391', 'name' => 'Irai');
$city_data[] = array('accid' => 'BRXX0392', 'name' => 'Irece');
$city_data[] = array('accid' => 'BRXX0393', 'name' => 'Itaborai');
$city_data[] = array('accid' => 'BRXX0394', 'name' => 'Itaguai');
$city_data[] = array('accid' => 'BRXX0395', 'name' => 'Itai');
$city_data[] = array('accid' => 'BRXX0396', 'name' => 'Itapolis');
$city_data[] = array('accid' => 'BRXX0397', 'name' => 'Ivai');
$city_data[] = array('accid' => 'BRXX0398', 'name' => 'Jacarei');
$city_data[] = array('accid' => 'BRXX0399', 'name' => 'Januaria');
$city_data[] = array('accid' => 'BRXX0400', 'name' => 'Joao Neiva');
$city_data[] = array('accid' => 'BRXX0402', 'name' => 'Jose Bonifacio');
$city_data[] = array('accid' => 'BRXX0403', 'name' => 'Jurua');
$city_data[] = array('accid' => 'BRXX0404', 'name' => 'Lindoia');
$city_data[] = array('accid' => 'BRXX0405', 'name' => 'Lucelia');
$city_data[] = array('accid' => 'BRXX0406', 'name' => 'Morro do Chapeu');
$city_data[] = array('accid' => 'BRXX0407', 'name' => 'Mairipora');
$city_data[] = array('accid' => 'BRXX0408', 'name' => 'Mancio Lima');
$city_data[] = array('accid' => 'BRXX0409', 'name' => 'Marataizes');
$city_data[] = array('accid' => 'BRXX0410', 'name' => 'Marica');
$city_data[] = array('accid' => 'BRXX0411', 'name' => 'Martinopolis');
$city_data[] = array('accid' => 'BRXX0412', 'name' => 'Matao');
$city_data[] = array('accid' => 'BRXX0413', 'name' => 'Maues');
$city_data[] = array('accid' => 'BRXX0414', 'name' => 'Mirandopolis');
$city_data[] = array('accid' => 'BRXX0415', 'name' => 'Muriae');
$city_data[] = array('accid' => 'BRXX0416', 'name' => 'Nazare Paulista');
$city_data[] = array('accid' => 'BRXX0417', 'name' => 'Nova Venecia');
$city_data[] = array('accid' => 'BRXX0418', 'name' => 'Novo Airao');
$city_data[] = array('accid' => 'BRXX0419', 'name' => 'Obidos');
$city_data[] = array('accid' => 'BRXX0420', 'name' => 'Olimpia');
$city_data[] = array('accid' => 'BRXX0421', 'name' => 'Oriximina');
$city_data[] = array('accid' => 'BRXX0422', 'name' => 'Orlandia');
$city_data[] = array('accid' => 'BRXX0423', 'name' => 'Para de Minas');
$city_data[] = array('accid' => 'BRXX0424', 'name' => 'Parana');
$city_data[] = array('accid' => 'BRXX0425', 'name' => 'Paulinia');
$city_data[] = array('accid' => 'BRXX0426', 'name' => 'Pirajai');
$city_data[] = array('accid' => 'BRXX0427', 'name' => 'Pirajui');
$city_data[] = array('accid' => 'BRXX0428', 'name' => 'Poco Fundo');
$city_data[] = array('accid' => 'BRXX0429', 'name' => 'Pompeia');
$city_data[] = array('accid' => 'BRXX0430', 'name' => 'Pompeu');
$city_data[] = array('accid' => 'BRXX0431', 'name' => 'Ponte Alta do Bom');
$city_data[] = array('accid' => 'BRXX0432', 'name' => 'Presidente Medici');
$city_data[] = array('accid' => 'BRXX0433', 'name' => 'Propria');
$city_data[] = array('accid' => 'BRXX0434', 'name' => 'Regente Feijo');
$city_data[] = array('accid' => 'BRXX0436', 'name' => 'Ribeirao Pires');
$city_data[] = array('accid' => 'BRXX0437', 'name' => 'Santo Antonio de ');
$city_data[] = array('accid' => 'BRXX0438', 'name' => 'Sao Caetano de Od');
$city_data[] = array('accid' => 'BRXX0439', 'name' => 'Sao Luiz Gonzaga');
$city_data[] = array('accid' => 'BRXX0440', 'name' => 'Sao Jose do Rio P');
$city_data[] = array('accid' => 'BRXX0441', 'name' => 'Sao Joao da Boa V');
$city_data[] = array('accid' => 'BRXX0442', 'name' => 'Salesopolis');
$city_data[] = array('accid' => 'BRXX0443', 'name' => 'Santa Barbara');
$city_data[] = array('accid' => 'BRXX0444', 'name' => 'Santo Anastacio');
$city_data[] = array('accid' => 'BRXX0445', 'name' => 'Sao Fidelis');
$city_data[] = array('accid' => 'BRXX0446', 'name' => 'Sao Francisco');
$city_data[] = array('accid' => 'BRXX0447', 'name' => 'Sao Goncalo');
$city_data[] = array('accid' => 'BRXX0448', 'name' => 'Sao Joao da Barra');
$city_data[] = array('accid' => 'BRXX0449', 'name' => 'Sao Joao da Ponte');
$city_data[] = array('accid' => 'BRXX0450', 'name' => 'Sao Joaquim da Ba');
$city_data[] = array('accid' => 'BRXX0451', 'name' => 'Sao Luis do Parai');
$city_data[] = array('accid' => 'BRXX0452', 'name' => 'Sao Miguel Arcanj');
$city_data[] = array('accid' => 'BRXX0453', 'name' => 'Sao Pedro da Alde');
$city_data[] = array('accid' => 'BRXX0454', 'name' => 'Sao Romao');
$city_data[] = array('accid' => 'BRXX0455', 'name' => 'Sao Roque');
$city_data[] = array('accid' => 'BRXX0456', 'name' => 'Sao Simao');
$city_data[] = array('accid' => 'BRXX0457', 'name' => 'Sarapui');
$city_data[] = array('accid' => 'BRXX0458', 'name' => 'Senador Jose Porf');
$city_data[] = array('accid' => 'BRXX0459', 'name' => 'Sertaozinho');
$city_data[] = array('accid' => 'BRXX0460', 'name' => 'Silvianopolis');
$city_data[] = array('accid' => 'BRXX0461', 'name' => 'Senhor do Bonfim');
$city_data[] = array('accid' => 'BRXX0462', 'name' => 'Santo Antonio da ');
$city_data[] = array('accid' => 'BRXX0463', 'name' => 'Taboao da Serra');
$city_data[] = array('accid' => 'BRXX0464', 'name' => 'Tapaua');
$city_data[] = array('accid' => 'BRXX0465', 'name' => 'Tapirai');
$city_data[] = array('accid' => 'BRXX0466', 'name' => 'Tiete');
$city_data[] = array('accid' => 'BRXX0467', 'name' => 'Timoteo');
$city_data[] = array('accid' => 'BRXX0468', 'name' => 'Tocantinopolis');
$city_data[] = array('accid' => 'BRXX0469', 'name' => 'Tres Marias');
$city_data[] = array('accid' => 'BRXX0470', 'name' => 'Tres Pontas');
$city_data[] = array('accid' => 'BRXX0471', 'name' => 'Tres Rios');
$city_data[] = array('accid' => 'BRXX0472', 'name' => 'Uba');
$city_data[] = array('accid' => 'BRXX0473', 'name' => 'Unai');
$city_data[] = array('accid' => 'BRXX0474', 'name' => 'Urupes');
$city_data[] = array('accid' => 'BRXX0475', 'name' => 'Vargem Grande do ');
$city_data[] = array('accid' => 'BRXX0476', 'name' => 'Varzea Paulista');
$city_data[] = array('accid' => 'BRXX0477', 'name' => 'Vicosa');
$city_data[] = array('accid' => 'BRXX0478', 'name' => 'Visconde do Rio B');
$city_data[] = array('accid' => 'BRXX0479', 'name' => 'Agudos');
$city_data[] = array('accid' => 'BRXX0480', 'name' => 'Alegre');
$city_data[] = array('accid' => 'BRXX0481', 'name' => 'Alenquer');
$city_data[] = array('accid' => 'BRXX0482', 'name' => 'Alfenas');
$city_data[] = array('accid' => 'BRXX0483', 'name' => 'Almeirim');
$city_data[] = array('accid' => 'BRXX0484', 'name' => 'Almenara');
$city_data[] = array('accid' => 'BRXX0485', 'name' => 'Amparo');
$city_data[] = array('accid' => 'BRXX0486', 'name' => 'Ananindeua');
$city_data[] = array('accid' => 'BRXX0487', 'name' => 'Angatuba');
$city_data[] = array('accid' => 'BRXX0488', 'name' => 'Aparecida');
$city_data[] = array('accid' => 'BRXX0489', 'name' => 'Araguatins');
$city_data[] = array('accid' => 'BRXX0490', 'name' => 'Araruama');
$city_data[] = array('accid' => 'BRXX0491', 'name' => 'Arinos');
$city_data[] = array('accid' => 'BRXX0492', 'name' => 'Ariquemes');
$city_data[] = array('accid' => 'BRXX0493', 'name' => 'Atibaia');
$city_data[] = array('accid' => 'BRXX0494', 'name' => 'Baixo Guandu');
$city_data[] = array('accid' => 'BRXX0495', 'name' => 'Barra do Corda');
$city_data[] = array('accid' => 'BRXX0496', 'name' => 'Barretos');
$city_data[] = array('accid' => 'BRXX0497', 'name' => 'Barueri');
$city_data[] = array('accid' => 'BRXX0498', 'name' => 'Bebedouro');
$city_data[] = array('accid' => 'BRXX0499', 'name' => 'Belford Roxo');
$city_data[] = array('accid' => 'BRXX0500', 'name' => 'Belo Monte');
$city_data[] = array('accid' => 'BRXX0502', 'name' => 'Benjamin Constant');
$city_data[] = array('accid' => 'BRXX0503', 'name' => 'Betim');
$city_data[] = array('accid' => 'BRXX0504', 'name' => 'Boca do Acre');
$city_data[] = array('accid' => 'BRXX0505', 'name' => 'Boituva');
$city_data[] = array('accid' => 'BRXX0506', 'name' => 'Bom Jardim');
$city_data[] = array('accid' => 'BRXX0508', 'name' => 'Bom Jesus');
$city_data[] = array('accid' => 'BRXX0509', 'name' => 'Bom Jesus');
$city_data[] = array('accid' => 'BRXX0510', 'name' => 'Borba');
$city_data[] = array('accid' => 'BRXX0511', 'name' => 'Botelhos');
$city_data[] = array('accid' => 'BRXX0512', 'name' => 'Brotas');
$city_data[] = array('accid' => 'BRXX0513', 'name' => 'Buri');
$city_data[] = array('accid' => 'BRXX0514', 'name' => 'Buritis');
$city_data[] = array('accid' => 'BRXX0515', 'name' => 'Buritizeiro');
$city_data[] = array('accid' => 'BRXX0516', 'name' => 'Caapiranga');
$city_data[] = array('accid' => 'BRXX0517', 'name' => 'Cacoal');
$city_data[] = array('accid' => 'BRXX0518', 'name' => 'Caetite');
$city_data[] = array('accid' => 'BRXX0519', 'name' => 'Caieiras');
$city_data[] = array('accid' => 'BRXX0520', 'name' => 'Campestre');
$city_data[] = array('accid' => 'BRXX0521', 'name' => 'Campo Belo');
$city_data[] = array('accid' => 'BRXX0522', 'name' => 'Campos Novos');
$city_data[] = array('accid' => 'BRXX0523', 'name' => 'Canavieiras');
$city_data[] = array('accid' => 'BRXX0524', 'name' => 'Cantagalo');
$city_data[] = array('accid' => 'BRXX0525', 'name' => 'Canutama');
$city_data[] = array('accid' => 'BRXX0526', 'name' => 'Capanema');
$city_data[] = array('accid' => 'BRXX0527', 'name' => 'Capela do Alto');
$city_data[] = array('accid' => 'BRXX0528', 'name' => 'Capelinha');
$city_data[] = array('accid' => 'BRXX0529', 'name' => 'Capivari');
$city_data[] = array('accid' => 'BRXX0530', 'name' => 'Carangola');
$city_data[] = array('accid' => 'BRXX0531', 'name' => 'Carbonita');
$city_data[] = array('accid' => 'BRXX0532', 'name' => 'Carinhanha');
$city_data[] = array('accid' => 'BRXX0533', 'name' => 'Carmo da Cachoeir');
$city_data[] = array('accid' => 'BRXX0534', 'name' => 'Carmo do Rio Clar');
$city_data[] = array('accid' => 'BRXX0535', 'name' => 'Carolina');
$city_data[] = array('accid' => 'BRXX0536', 'name' => 'Carvoeiro');
$city_data[] = array('accid' => 'BRXX0537', 'name' => 'Casa Branca');
$city_data[] = array('accid' => 'BRXX0538', 'name' => 'Castelo');
$city_data[] = array('accid' => 'BRXX0539', 'name' => 'Cataguases');
$city_data[] = array('accid' => 'BRXX0540', 'name' => 'Cerquilho');
$city_data[] = array('accid' => 'BRXX0541', 'name' => 'Coelho da Rocha');
$city_data[] = array('accid' => 'BRXX0542', 'name' => 'Congonhas');
$city_data[] = array('accid' => 'BRXX0543', 'name' => 'Contagem');
$city_data[] = array('accid' => 'BRXX0544', 'name' => 'Cordeiro');
$city_data[] = array('accid' => 'BRXX0545', 'name' => 'Corinto');
$city_data[] = array('accid' => 'BRXX0546', 'name' => 'Coronel Fabrician');
$city_data[] = array('accid' => 'BRXX0547', 'name' => 'Cotia');
$city_data[] = array('accid' => 'BRXX0548', 'name' => 'Cruzeiro');
$city_data[] = array('accid' => 'BRXX0549', 'name' => 'Cruzeiro do Sul');
$city_data[] = array('accid' => 'BRXX0550', 'name' => 'Diamantino');
$city_data[] = array('accid' => 'BRXX0551', 'name' => 'Duartina');
$city_data[] = array('accid' => 'BRXX0552', 'name' => 'Ecoporanga');
$city_data[] = array('accid' => 'BRXX0553', 'name' => 'Embu');
$city_data[] = array('accid' => 'BRXX0554', 'name' => 'Encruzilhada do S');
$city_data[] = array('accid' => 'BRXX0555', 'name' => 'Espinosa');
$city_data[] = array('accid' => 'BRXX0556', 'name' => 'Floriano');
$city_data[] = array('accid' => 'BRXX0557', 'name' => 'Fonte Boa');
$city_data[] = array('accid' => 'BRXX0558', 'name' => 'Formoso');
$city_data[] = array('accid' => 'BRXX0559', 'name' => 'Francisco Morato');
$city_data[] = array('accid' => 'BRXX0560', 'name' => 'Franco da Rocha');
$city_data[] = array('accid' => 'BRXX0561', 'name' => 'General Salgado');
$city_data[] = array('accid' => 'BRXX0562', 'name' => 'Guapiara');
$city_data[] = array('accid' => 'BRXX0563', 'name' => 'Guarus');
$city_data[] = array('accid' => 'BRXX0564', 'name' => 'Gurupi');
$city_data[] = array('accid' => 'BRXX0565', 'name' => 'Ibitinga');
$city_data[] = array('accid' => 'BRXX0566', 'name' => 'Imperatriz');
$city_data[] = array('accid' => 'BRXX0567', 'name' => 'Indaiatuba');
$city_data[] = array('accid' => 'BRXX0568', 'name' => 'Inhapim');
$city_data[] = array('accid' => 'BRXX0569', 'name' => 'Ipameri');
$city_data[] = array('accid' => 'BRXX0570', 'name' => 'Itabaianinha');
$city_data[] = array('accid' => 'BRXX0571', 'name' => 'Itabira');
$city_data[] = array('accid' => 'BRXX0572', 'name' => 'Itacoatiara');
$city_data[] = array('accid' => 'BRXX0573', 'name' => 'Itaituba');
$city_data[] = array('accid' => 'BRXX0574', 'name' => 'Itamarandiba');
$city_data[] = array('accid' => 'BRXX0576', 'name' => 'Itapecerica da Se');
$city_data[] = array('accid' => 'BRXX0577', 'name' => 'Itapiranga');
$city_data[] = array('accid' => 'BRXX0578', 'name' => 'Itatiaia');
$city_data[] = array('accid' => 'BRXX0579', 'name' => 'Itatiba');
$city_data[] = array('accid' => 'BRXX0580', 'name' => 'Itupeva');
$city_data[] = array('accid' => 'BRXX0581', 'name' => 'Ituverava');
$city_data[] = array('accid' => 'BRXX0582', 'name' => 'Jaboticabal');
$city_data[] = array('accid' => 'BRXX0583', 'name' => 'Jacarezinho');
$city_data[] = array('accid' => 'BRXX0585', 'name' => 'Jales');
$city_data[] = array('accid' => 'BRXX0586', 'name' => 'Jaru');
$city_data[] = array('accid' => 'BRXX0587', 'name' => 'Jequitinhonha');
$city_data[] = array('accid' => 'BRXX0588', 'name' => 'Jumirim');
$city_data[] = array('accid' => 'BRXX0589', 'name' => 'Juquitiba');
$city_data[] = array('accid' => 'BRXX0590', 'name' => 'Juruti');
$city_data[] = array('accid' => 'BRXX0591', 'name' => 'Lagoa Santa');
$city_data[] = array('accid' => 'BRXX0592', 'name' => 'Lagoa Vermelha');
$city_data[] = array('accid' => 'BRXX0593', 'name' => 'Laranjal Paulista');
$city_data[] = array('accid' => 'BRXX0594', 'name' => 'Lavras');
$city_data[] = array('accid' => 'BRXX0595', 'name' => 'Leme');
$city_data[] = array('accid' => 'BRXX0596', 'name' => 'Machado');
$city_data[] = array('accid' => 'BRXX0597', 'name' => 'Macuco');
$city_data[] = array('accid' => 'BRXX0598', 'name' => 'Mairinque');
$city_data[] = array('accid' => 'BRXX0599', 'name' => 'Malacacheta');
$city_data[] = array('accid' => 'BRXX0600', 'name' => 'Manacapuru');
$city_data[] = array('accid' => 'BRXX0601', 'name' => 'Manga');
$city_data[] = array('accid' => 'BRXX0602', 'name' => 'Mangaratiba');
$city_data[] = array('accid' => 'BRXX0603', 'name' => 'Mantena');
$city_data[] = array('accid' => 'BRXX0604', 'name' => 'Marambaia');
$city_data[] = array('accid' => 'BRXX0605', 'name' => 'Mariana');
$city_data[] = array('accid' => 'BRXX0606', 'name' => 'Medina');
$city_data[] = array('accid' => 'BRXX0607', 'name' => 'Mesquita');
$city_data[] = array('accid' => 'BRXX0608', 'name' => 'Minas Novas');
$city_data[] = array('accid' => 'BRXX0609', 'name' => 'Mirassol');
$city_data[] = array('accid' => 'BRXX0610', 'name' => 'Mococa');
$city_data[] = array('accid' => 'BRXX0611', 'name' => 'Monte Alegre');
$city_data[] = array('accid' => 'BRXX0612', 'name' => 'Monte Azul');
$city_data[] = array('accid' => 'BRXX0613', 'name' => 'Moura');
$city_data[] = array('accid' => 'BRXX0614', 'name' => 'Mutum');
$city_data[] = array('accid' => 'BRXX0615', 'name' => 'Nanuque');
$city_data[] = array('accid' => 'BRXX0616', 'name' => 'Natividade');
$city_data[] = array('accid' => 'BRXX0617', 'name' => 'Neves');
$city_data[] = array('accid' => 'BRXX0618', 'name' => 'Xavantina');
$city_data[] = array('accid' => 'BRXX0619', 'name' => 'Novo Cruzeiro');
$city_data[] = array('accid' => 'BRXX0620', 'name' => 'Novo Horizonte');
$city_data[] = array('accid' => 'BRXX0621', 'name' => 'Oiapoque');
$city_data[] = array('accid' => 'BRXX0622', 'name' => 'Oswaldo Cruz');
$city_data[] = array('accid' => 'BRXX0623', 'name' => 'Ouro Preto');
$city_data[] = array('accid' => 'BRXX0624', 'name' => 'Ouro Preto do Oes');
$city_data[] = array('accid' => 'BRXX0625', 'name' => 'Paraibuna');
$city_data[] = array('accid' => 'BRXX0626', 'name' => 'Paulistana');
$city_data[] = array('accid' => 'BRXX0627', 'name' => 'Paulo Afonso');
$city_data[] = array('accid' => 'BRXX0628', 'name' => 'Pederneiras');
$city_data[] = array('accid' => 'BRXX0629', 'name' => 'Pedro Afonso');
$city_data[] = array('accid' => 'BRXX0631', 'name' => 'Penedo');
$city_data[] = array('accid' => 'BRXX0632', 'name' => 'Pereira Barreto');
$city_data[] = array('accid' => 'BRXX0633', 'name' => 'Perus');
$city_data[] = array('accid' => 'BRXX0634', 'name' => 'Picos');
$city_data[] = array('accid' => 'BRXX0635', 'name' => 'Piedade');
$city_data[] = array('accid' => 'BRXX0636', 'name' => 'Piedade do Rio Gr');
$city_data[] = array('accid' => 'BRXX0637', 'name' => 'Pilar do Sul');
$city_data[] = array('accid' => 'BRXX0638', 'name' => 'Pimenta Bueno');
$city_data[] = array('accid' => 'BRXX0639', 'name' => 'Pindamonhangaba');
$city_data[] = array('accid' => 'BRXX0640', 'name' => 'Pirapozinho');
$city_data[] = array('accid' => 'BRXX0641', 'name' => 'Pirassununga');
$city_data[] = array('accid' => 'BRXX0642', 'name' => 'Pirituba');
$city_data[] = array('accid' => 'BRXX0643', 'name' => 'Pitangui');
$city_data[] = array('accid' => 'BRXX0644', 'name' => 'Ponte Nova');
$city_data[] = array('accid' => 'BRXX0645', 'name' => 'Porangaba');
$city_data[] = array('accid' => 'BRXX0646', 'name' => 'Porteirinha');
$city_data[] = array('accid' => 'BRXX0647', 'name' => 'Porto Acre');
$city_data[] = array('accid' => 'BRXX0648', 'name' => 'Porto de Moz');
$city_data[] = array('accid' => 'BRXX0649', 'name' => 'Porto Ferreira');
$city_data[] = array('accid' => 'BRXX0650', 'name' => 'Prainha');
$city_data[] = array('accid' => 'BRXX0651', 'name' => 'Presidente Vences');
$city_data[] = array('accid' => 'BRXX0652', 'name' => 'Queimados');
$city_data[] = array('accid' => 'BRXX0653', 'name' => 'Rancharia');
$city_data[] = array('accid' => 'BRXX0654', 'name' => 'Raul Soares');
$city_data[] = array('accid' => 'BRXX0655', 'name' => 'Remanso');
$city_data[] = array('accid' => 'BRXX0656', 'name' => 'Rio Bananal');
$city_data[] = array('accid' => 'BRXX0657', 'name' => 'Rio das Ostras');
$city_data[] = array('accid' => 'BRXX0658', 'name' => 'Rio Pardo de Mina');
$city_data[] = array('accid' => 'BRXX0659', 'name' => 'Rolim de Moura');
$city_data[] = array('accid' => 'BRXX0660', 'name' => 'Salinas');
$city_data[] = array('accid' => 'BRXX0661', 'name' => 'Salto');
$city_data[] = array('accid' => 'BRXX0662', 'name' => 'Salto de Pirapora');
$city_data[] = array('accid' => 'BRXX0663', 'name' => 'Salvaterra');
$city_data[] = array('accid' => 'BRXX0664', 'name' => 'Santa Cruz');
$city_data[] = array('accid' => 'BRXX0665', 'name' => 'Santa Leopoldina');
$city_data[] = array('accid' => 'BRXX0666', 'name' => 'Santa Luzia');
$city_data[] = array('accid' => 'BRXX0667', 'name' => 'Saquarema');
$city_data[] = array('accid' => 'BRXX0668', 'name' => 'Serra Negra');
$city_data[] = array('accid' => 'BRXX0669', 'name' => 'Soure');
$city_data[] = array('accid' => 'BRXX0670', 'name' => 'Suzano');
$city_data[] = array('accid' => 'BRXX0671', 'name' => 'Taguatinga');
$city_data[] = array('accid' => 'BRXX0672', 'name' => 'Taquarituba');
$city_data[] = array('accid' => 'BRXX0673', 'name' => 'Teodoro Sampaio');
$city_data[] = array('accid' => 'BRXX0674', 'name' => 'Tiradentes');
$city_data[] = array('accid' => 'BRXX0675', 'name' => 'Torres');
$city_data[] = array('accid' => 'BRXX0676', 'name' => 'Tracuateua');
$city_data[] = array('accid' => 'BRXX0677', 'name' => 'Trancoso');
$city_data[] = array('accid' => 'BRXX0678', 'name' => 'Turmalina');
$city_data[] = array('accid' => 'BRXX0679', 'name' => 'Valinhos');
$city_data[] = array('accid' => 'BRXX0680', 'name' => 'Vassouras');
$city_data[] = array('accid' => 'BRXX0681', 'name' => 'Vespasiano');
$city_data[] = array('accid' => 'BRXX0682', 'name' => 'Vinhedo');
$city_data[] = array('accid' => 'BRXX0683', 'name' => 'Viseu');
$city_data[] = array('accid' => 'BRXX0684', 'name' => 'Votorantim');
$city_data[] = array('accid' => 'BRXX0685', 'name' => 'New Xavantina');
$city_data[] = array('accid' => 'BRXX0686', 'name' => 'Acucena');
$city_data[] = array('accid' => 'BRXX0687', 'name' => 'Aeroporto de Conf');
$city_data[] = array('accid' => 'BRXX0688', 'name' => 'Aeroporto do Gale');
$city_data[] = array('accid' => 'BRXX0689', 'name' => 'Aluminio');
$city_data[] = array('accid' => 'BRXX0690', 'name' => 'Aracoiaba da Serr');
$city_data[] = array('accid' => 'BRXX0691', 'name' => 'Aracuai');
$city_data[] = array('accid' => 'BRXX0692', 'name' => 'Aragarcas');
$city_data[] = array('accid' => 'BRXX0693', 'name' => 'Araguacu');
$city_data[] = array('accid' => 'BRXX0694', 'name' => 'Augustinopolis');
$city_data[] = array('accid' => 'BRXX0695', 'name' => 'Bom Jesus de Itab');
$city_data[] = array('accid' => 'BRXX0696', 'name' => 'Brasilia de Minas');
$city_data[] = array('accid' => 'BRXX0697', 'name' => 'Calcoene');
$city_data[] = array('accid' => 'BRXX0698', 'name' => 'Campina do Monte ');
$city_data[] = array('accid' => 'BRXX0699', 'name' => 'Campo Limpo Pauli');
$city_data[] = array('accid' => 'BRXX0700', 'name' => 'Codisburgo');
$city_data[] = array('accid' => 'BRXX0701', 'name' => 'Colorado do Oeste');
$city_data[] = array('accid' => 'BRXX0702', 'name' => 'Conceicao do Arag');
$city_data[] = array('accid' => 'BRXX0703', 'name' => 'Coracao de Jesus');
$city_data[] = array('accid' => 'BRXX0704', 'name' => 'Embu-Guacu');
$city_data[] = array('accid' => 'BRXX0705', 'name' => 'Ferraz de Vasconc');
$city_data[] = array('accid' => 'BRXX0706', 'name' => 'Figueiropolis');
$city_data[] = array('accid' => 'BRXX0707', 'name' => 'Formoso do Aragua');
$city_data[] = array('accid' => 'BRXX0708', 'name' => 'Garca');
$city_data[] = array('accid' => 'BRXX0709', 'name' => 'Igarape-Acu');
$city_data[] = array('accid' => 'BRXX0710', 'name' => 'Itaguacu');
$city_data[] = array('accid' => 'BRXX0711', 'name' => 'Ivinhema');
$city_data[] = array('accid' => 'BRXX0712', 'name' => 'Joacaba');
$city_data[] = array('accid' => 'BRXX0713', 'name' => 'Lencois Paulista');
$city_data[] = array('accid' => 'BRXX0714', 'name' => 'Miracema do Tocan');
$city_data[] = array('accid' => 'BRXX0715', 'name' => 'Miranorte');
$city_data[] = array('accid' => 'BRXX0716', 'name' => 'Moji-Mirim');
$city_data[] = array('accid' => 'BRXX0717', 'name' => 'Novo Aripuana');
$city_data[] = array('accid' => 'BRXX0718', 'name' => 'Placido Castro');
$city_data[] = array('accid' => 'BRXX0719', 'name' => 'Santa Vitoria do ');
$city_data[] = array('accid' => 'BRXX0720', 'name' => 'Santana do Parnai');
$city_data[] = array('accid' => 'BRXX0721', 'name' => 'Sao Gabriel da Pa');
$city_data[] = array('accid' => 'BRXX0722', 'name' => 'Sao Joao de Merit');
$city_data[] = array('accid' => 'BRXX0723', 'name' => 'Sao Lourenco da S');
$city_data[] = array('accid' => 'BRXX0724', 'name' => 'Tangara da Serra');
$city_data[] = array('accid' => 'BRXX0725', 'name' => 'Tres Coracoes');
$city_data[] = array('accid' => 'BRXX0726', 'name' => 'Vera');
$city_data[] = array('accid' => 'BRXX0727', 'name' => 'Cariacica');
$city_data[] = array('accid' => 'BRXX0728', 'name' => 'Iuna');
$city_data[] = array('accid' => 'BRXX0729', 'name' => 'Santa Teresa');
$city_data[] = array('accid' => 'BRXX0730', 'name' => 'Amapa');
$city_data[] = array('accid' => 'BRXX0731', 'name' => 'Icoraci');
$city_data[] = array('accid' => 'BRXX0732', 'name' => 'Guanambi');
$city_data[] = array('accid' => 'BRXX0733', 'name' => 'Itaparica');
$city_data[] = array('accid' => 'BRXX0734', 'name' => 'Santa Cruz Cabral');
$city_data[] = array('accid' => 'BRXX0735', 'name' => 'Abreu e Lima');
$city_data[] = array('accid' => 'BRXX0736', 'name' => 'Camaragibe');

?>
