<?php

// City package for Canada

$city_name = 'Canada';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'CAXX0001', 'name' => 'Abbotsford');
$city_data[] = array('accid' => 'CAXX0002', 'name' => 'Agassiz');
$city_data[] = array('accid' => 'CAXX0003', 'name' => 'Ahousat');
$city_data[] = array('accid' => 'CAXX0004', 'name' => 'Airdrie');
$city_data[] = array('accid' => 'CAXX0005', 'name' => 'Ajax');
$city_data[] = array('accid' => 'CAXX0007', 'name' => 'Albertville');
$city_data[] = array('accid' => 'CAXX0008', 'name' => 'Amherst');
$city_data[] = array('accid' => 'CAXX0009', 'name' => 'Amherstburg');
$city_data[] = array('accid' => 'CAXX0010', 'name' => 'Anzac');
$city_data[] = array('accid' => 'CAXX0011', 'name' => 'Arborg');
$city_data[] = array('accid' => 'CAXX0596', 'name' => 'Argentia');
$city_data[] = array('accid' => 'CAXX0012', 'name' => 'Ascot Corner');
$city_data[] = array('accid' => 'CAXX0013', 'name' => 'Ashville');
$city_data[] = array('accid' => 'CAXX0014', 'name' => 'Atikokan');
$city_data[] = array('accid' => 'CAXX0015', 'name' => 'Aylesford');
$city_data[] = array('accid' => 'CAXX0016', 'name' => 'Aylmer');
$city_data[] = array('accid' => 'CAXX0017', 'name' => 'Baden');
$city_data[] = array('accid' => 'CAXX0580', 'name' => 'Badger');
$city_data[] = array('accid' => 'CAXX0018', 'name' => 'Bagotville');
$city_data[] = array('accid' => 'CAXX0019', 'name' => 'Baie-Comeau');
$city_data[] = array('accid' => 'CAXX0020', 'name' => 'Baie-Saint-Paul');
$city_data[] = array('accid' => 'CAXX0021', 'name' => 'Baker Lake');
$city_data[] = array('accid' => 'CAXX0022', 'name' => 'Bala');
$city_data[] = array('accid' => 'CAXX0023', 'name' => 'Banff');
$city_data[] = array('accid' => 'CAXX0024', 'name' => 'Barachois');
$city_data[] = array('accid' => 'CAXX0025', 'name' => 'Barrie');
$city_data[] = array('accid' => 'CAXX0026', 'name' => 'Bayfield');
$city_data[] = array('accid' => 'CAXX0027', 'name' => 'Beamsville');
$city_data[] = array('accid' => 'CAXX0028', 'name' => 'Beauport');
$city_data[] = array('accid' => 'CAXX0029', 'name' => 'Beausejour');
$city_data[] = array('accid' => 'CAXX0030', 'name' => 'Beaver Cove');
$city_data[] = array('accid' => 'CAXX0031', 'name' => 'Becancour');
$city_data[] = array('accid' => 'CAXX0032', 'name' => 'Bedford');
$city_data[] = array('accid' => 'CAXX0033', 'name' => 'Belcourt');
$city_data[] = array('accid' => 'CAXX0034', 'name' => 'Belleville');
$city_data[] = array('accid' => 'CAXX0035', 'name' => 'Belmont');
$city_data[] = array('accid' => 'CAXX0036', 'name' => 'Big Brook');
$city_data[] = array('accid' => 'CAXX0604', 'name' => 'Big Trout Lake');
$city_data[] = array('accid' => 'CAXX0037', 'name' => 'Birch Hills');
$city_data[] = array('accid' => 'CAXX0038', 'name' => 'Birken');
$city_data[] = array('accid' => 'CAXX0597', 'name' => 'Blanc Sablon');
$city_data[] = array('accid' => 'CAXX0039', 'name' => 'Bloedel');
$city_data[] = array('accid' => 'CAXX0576', 'name' => 'Bonavista');
$city_data[] = array('accid' => 'CAXX0040', 'name' => 'Boucherville');
$city_data[] = array('accid' => 'CAXX0041', 'name' => 'Bowmanville');
$city_data[] = array('accid' => 'CAXX0042', 'name' => 'Bracebridge');
$city_data[] = array('accid' => 'CAXX0043', 'name' => 'Brampton');
$city_data[] = array('accid' => 'CAXX0044', 'name' => 'Brandon');
$city_data[] = array('accid' => 'CAXX0045', 'name' => 'Brantford');
$city_data[] = array('accid' => 'CAXX0046', 'name' => 'Brighton');
$city_data[] = array('accid' => 'CAXX0607', 'name' => 'Broadview');
$city_data[] = array('accid' => 'CAXX0047', 'name' => 'Bromptonville');
$city_data[] = array('accid' => 'CAXX0048', 'name' => 'Bruce Mines');
$city_data[] = array('accid' => 'CAXX0561', 'name' => 'Buffalo Narrows');
$city_data[] = array('accid' => 'CAXX0575', 'name' => 'Burgeo');
$city_data[] = array('accid' => 'CAXX0049', 'name' => 'Burin');
$city_data[] = array('accid' => 'CAXX0050', 'name' => 'Burlington');
$city_data[] = array('accid' => 'CAXX0051', 'name' => 'Burnaby');
$city_data[] = array('accid' => 'CAXX0052', 'name' => 'Bylot');
$city_data[] = array('accid' => 'CAXX0053', 'name' => 'Cacouna');
$city_data[] = array('accid' => 'CAXX0054', 'name' => 'Calgary');
$city_data[] = array('accid' => 'CAXX0055', 'name' => 'Callander');
$city_data[] = array('accid' => 'CAXX0056', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'CAXX0057', 'name' => 'Campbell River');
$city_data[] = array('accid' => 'CAXX0058', 'name' => 'Campbellton');
$city_data[] = array('accid' => 'CAXX0059', 'name' => 'Canmore');
$city_data[] = array('accid' => 'CAXX0060', 'name' => 'Cap Chat');
$city_data[] = array('accid' => 'CAXX0061', 'name' => 'Cap-de-la-Madeleine');
$city_data[] = array('accid' => 'CAXX0062', 'name' => 'Cap-des-Rosiers');
$city_data[] = array('accid' => 'CAXX0617', 'name' => 'Cape Dorset');
$city_data[] = array('accid' => 'CAXX0063', 'name' => 'Carcross');
$city_data[] = array('accid' => 'CAXX0064', 'name' => 'Caronport');
$city_data[] = array('accid' => 'CAXX0065', 'name' => 'Carp');
$city_data[] = array('accid' => 'CAXX0601', 'name' => 'Cartwright');
$city_data[] = array('accid' => 'CAXX0066', 'name' => 'Castlegar');
$city_data[] = array('accid' => 'CAXX0067', 'name' => 'Castor');
$city_data[] = array('accid' => 'CAXX0068', 'name' => 'Chambord');
$city_data[] = array('accid' => 'CAXX0069', 'name' => 'Champagne');
$city_data[] = array('accid' => 'CAXX0070', 'name' => 'Chapais');
$city_data[] = array('accid' => 'CAXX0071', 'name' => 'Charlesbourg');
$city_data[] = array('accid' => 'CAXX0072', 'name' => 'Charlie Lake');
$city_data[] = array('accid' => 'CAXX0073', 'name' => 'Charlottetown');
$city_data[] = array('accid' => 'CAXX0074', 'name' => 'Chatham');
$city_data[] = array('accid' => 'CAXX0075', 'name' => 'Chibougamau');
$city_data[] = array('accid' => 'CAXX0076', 'name' => 'Chicoutimi');
$city_data[] = array('accid' => 'CAXX0077', 'name' => 'Chilliwack');
$city_data[] = array('accid' => 'CAXX0078', 'name' => 'Churchill');
$city_data[] = array('accid' => 'CAXX0574', 'name' => 'Churchill Falls');
$city_data[] = array('accid' => 'CAXX0079', 'name' => 'Chute-aux-Outardes');
$city_data[] = array('accid' => 'CAXX0080', 'name' => 'Clairmont');
$city_data[] = array('accid' => 'CAXX0081', 'name' => 'Clarke City');
$city_data[] = array('accid' => 'CAXX0082', 'name' => 'Clinton');
$city_data[] = array('accid' => 'CAXX0083', 'name' => 'Coal Harbour');
$city_data[] = array('accid' => 'CAXX0084', 'name' => 'Coaldale');
$city_data[] = array('accid' => 'CAXX0085', 'name' => 'Cobden');
$city_data[] = array('accid' => 'CAXX0086', 'name' => 'Cochrane');
$city_data[] = array('accid' => 'CAXX0087', 'name' => 'Codroy');
$city_data[] = array('accid' => 'CAXX0088', 'name' => 'Colborne');
$city_data[] = array('accid' => 'CAXX0089', 'name' => 'Cold Lake');
$city_data[] = array('accid' => 'CAXX0090', 'name' => 'Collingwood');
$city_data[] = array('accid' => 'CAXX0091', 'name' => 'Collins Bay');
$city_data[] = array('accid' => 'CAXX0092', 'name' => 'Comox');
$city_data[] = array('accid' => 'CAXX0093', 'name' => 'Coniston');
$city_data[] = array('accid' => 'CAXX0094', 'name' => 'Copper Cliff');
$city_data[] = array('accid' => 'CAXX0095', 'name' => 'Copper Creek');
$city_data[] = array('accid' => 'CAXX0618', 'name' => 'Coral Harbour');
$city_data[] = array('accid' => 'CAXX0096', 'name' => 'Cormorant');
$city_data[] = array('accid' => 'CAXX0097', 'name' => 'Corner Brook');
$city_data[] = array('accid' => 'CAXX0098', 'name' => 'Coronation');
$city_data[] = array('accid' => 'CAXX0099', 'name' => 'Courtenay');
$city_data[] = array('accid' => 'CAXX0100', 'name' => 'Courtright');
$city_data[] = array('accid' => 'CAXX0101', 'name' => 'Cranberry Portage');
$city_data[] = array('accid' => 'CAXX0102', 'name' => 'Cranbrook');
$city_data[] = array('accid' => 'CAXX0103', 'name' => 'Cumberland');
$city_data[] = array('accid' => 'CAXX0104', 'name' => 'Cut Knife');
$city_data[] = array('accid' => 'CAXX0105', 'name' => 'Dafoe');
$city_data[] = array('accid' => 'CAXX0106', 'name' => 'Dalhousie');
$city_data[] = array('accid' => 'CAXX0107', 'name' => 'Dartmouth');
$city_data[] = array('accid' => 'CAXX0108', 'name' => 'Dauphin');
$city_data[] = array('accid' => 'CAXX0109', 'name' => 'Dawson');
$city_data[] = array('accid' => 'CAXX0110', 'name' => 'Dawson Creek');
$city_data[] = array('accid' => 'CAXX0111', 'name' => 'Debert');
$city_data[] = array('accid' => 'CAXX0112', 'name' => 'Deer Lake');
$city_data[] = array('accid' => 'CAXX0113', 'name' => 'Delhi');
$city_data[] = array('accid' => 'CAXX0114', 'name' => 'Denfield');
$city_data[] = array('accid' => 'CAXX0115', 'name' => 'Denholm');
$city_data[] = array('accid' => 'CAXX0116', 'name' => 'Deroche');
$city_data[] = array('accid' => 'CAXX0117', 'name' => 'Devon');
$city_data[] = array('accid' => 'CAXX0118', 'name' => 'Dieppe');
$city_data[] = array('accid' => 'CAXX0119', 'name' => 'Digges');
$city_data[] = array('accid' => 'CAXX0120', 'name' => 'Dominion');
$city_data[] = array('accid' => 'CAXX0121', 'name' => 'Douglastown');
$city_data[] = array('accid' => 'CAXX0122', 'name' => 'Dundas');
$city_data[] = array('accid' => 'CAXX0123', 'name' => 'Dunmore');
$city_data[] = array('accid' => 'CAXX0628', 'name' => 'Earlton');
$city_data[] = array('accid' => 'CAXX0124', 'name' => 'East Point');
$city_data[] = array('accid' => 'CAXX0569', 'name' => 'Eastend Cypress');
$city_data[] = array('accid' => 'CAXX0125', 'name' => 'Echo Bay');
$city_data[] = array('accid' => 'CAXX0126', 'name' => 'Edmonton');
$city_data[] = array('accid' => 'CAXX0567', 'name' => 'Edmonton International');
$city_data[] = array('accid' => 'CAXX0565', 'name' => 'Edmonton Namao Alta.');
$city_data[] = array('accid' => 'CAXX0564', 'name' => 'Edmonton Stony Plain Alta.');
$city_data[] = array('accid' => 'CAXX0127', 'name' => 'Edmundston');
$city_data[] = array('accid' => 'CAXX0128', 'name' => 'Edson');
$city_data[] = array('accid' => 'CAXX0129', 'name' => 'Elliot Lake');
$city_data[] = array('accid' => 'CAXX0130', 'name' => 'Elmsdale');
$city_data[] = array('accid' => 'CAXX0131', 'name' => 'Enderby');
$city_data[] = array('accid' => 'CAXX0132', 'name' => 'Esquimalt');
$city_data[] = array('accid' => 'CAXX0133', 'name' => 'Essex');
$city_data[] = array('accid' => 'CAXX0134', 'name' => 'Estevan');
$city_data[] = array('accid' => 'CAXX0612', 'name' => 'Estevan Point');
$city_data[] = array('accid' => 'CAXX0135', 'name' => 'Ethelbert');
$city_data[] = array('accid' => 'CAXX0136', 'name' => 'Etobicoke');
$city_data[] = array('accid' => 'CAXX0137', 'name' => 'Fairmont Hot Springs');
$city_data[] = array('accid' => 'CAXX0138', 'name' => 'Falconbridge');
$city_data[] = array('accid' => 'CAXX0139', 'name' => 'Fiske');
$city_data[] = array('accid' => 'CAXX0140', 'name' => 'Flaxcombe');
$city_data[] = array('accid' => 'CAXX0141', 'name' => 'Flin Flon');
$city_data[] = array('accid' => 'CAXX0142', 'name' => 'Floral');
$city_data[] = array('accid' => 'CAXX0620', 'name' => 'Fort Chipewyan');
$city_data[] = array('accid' => 'CAXX0143', 'name' => 'Fort Erie');
$city_data[] = array('accid' => 'CAXX0144', 'name' => 'Fort Frances');
$city_data[] = array('accid' => 'CAXX0145', 'name' => 'Fort MacKay');
$city_data[] = array('accid' => 'CAXX0146', 'name' => 'Fort McMurray');
$city_data[] = array('accid' => 'CAXX0147', 'name' => 'Fort Nelson');
$city_data[] = array('accid' => 'CAXX0560', 'name' => 'Fort Reliance');
$city_data[] = array('accid' => 'CAXX0148', 'name' => 'Fort Saint John');
$city_data[] = array('accid' => 'CAXX0149', 'name' => 'Fort Saskatchewan');
$city_data[] = array('accid' => 'CAXX0624', 'name' => 'Fort Simpson');
$city_data[] = array('accid' => 'CAXX0621', 'name' => 'Fort Smith');
$city_data[] = array('accid' => 'CAXX0150', 'name' => 'Fort Steele');
$city_data[] = array('accid' => 'CAXX0151', 'name' => 'Fredericton');
$city_data[] = array('accid' => 'CAXX0152', 'name' => 'Freshford');
$city_data[] = array('accid' => 'CAXX0153', 'name' => 'Gambo');
$city_data[] = array('accid' => 'CAXX0154', 'name' => 'Gananoque');
$city_data[] = array('accid' => 'CAXX0155', 'name' => 'Gander');
$city_data[] = array('accid' => 'CAXX0156', 'name' => 'Garibaldi');
$city_data[] = array('accid' => 'CAXX0157', 'name' => 'Gaspe');
$city_data[] = array('accid' => 'CAXX0158', 'name' => 'Gatineau');
$city_data[] = array('accid' => 'CAXX0159', 'name' => 'Geraldton');
$city_data[] = array('accid' => 'CAXX0160', 'name' => 'Gillam');
$city_data[] = array('accid' => 'CAXX0161', 'name' => 'Gimli');
$city_data[] = array('accid' => 'CAXX0162', 'name' => 'Glace Bay');
$city_data[] = array('accid' => 'CAXX0163', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'CAXX0164', 'name' => 'Godbout');
$city_data[] = array('accid' => 'CAXX0165', 'name' => 'Goderich');
$city_data[] = array('accid' => 'CAXX0166', 'name' => 'Godreau');
$city_data[] = array('accid' => 'CAXX0167', 'name' => 'Golden');
$city_data[] = array('accid' => 'CAXX0168', 'name' => 'Goose Bay');
$city_data[] = array('accid' => 'CAXX0595', 'name' => 'Gore Bay');
$city_data[] = array('accid' => 'CAXX0169', 'name' => 'Gracefield');
$city_data[] = array('accid' => 'CAXX0170', 'name' => 'Grand Bay');
$city_data[] = array('accid' => 'CAXX0171', 'name' => 'Grand Centre');
$city_data[] = array('accid' => 'CAXX0172', 'name' => 'Grand Coulee');
$city_data[] = array('accid' => 'CAXX0173', 'name' => 'Grand Falls');
$city_data[] = array('accid' => 'CAXX0174', 'name' => 'Grand View');
$city_data[] = array('accid' => 'CAXX0175', 'name' => 'Grande Prairie');
$city_data[] = array('accid' => 'CAXX0176', 'name' => 'Gravenhurst');
$city_data[] = array('accid' => 'CAXX0177', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'CAXX0178', 'name' => 'Grimsby');
$city_data[] = array('accid' => 'CAXX0179', 'name' => 'Grindrod');
$city_data[] = array('accid' => 'CAXX0180', 'name' => 'Grosse Isle');
$city_data[] = array('accid' => 'CAXX0181', 'name' => 'Guelph');
$city_data[] = array('accid' => 'CAXX0182', 'name' => 'Hague');
$city_data[] = array('accid' => 'CAXX0183', 'name' => 'Halifax');
$city_data[] = array('accid' => 'CAXX0184', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'CAXX0185', 'name' => 'Hampden');
$city_data[] = array('accid' => 'CAXX0186', 'name' => 'Hampton');
$city_data[] = array('accid' => 'CAXX0187', 'name' => 'Hanna');
$city_data[] = array('accid' => 'CAXX0188', 'name' => 'Hare Bay');
$city_data[] = array('accid' => 'CAXX0189', 'name' => 'Hawk Junction');
$city_data[] = array('accid' => 'CAXX0190', 'name' => 'Hawk Lake');
$city_data[] = array('accid' => 'CAXX0622', 'name' => 'Hay River');
$city_data[] = array('accid' => 'CAXX0191', 'name' => 'Hebron');
$city_data[] = array('accid' => 'CAXX0630', 'name' => 'High Level');
$city_data[] = array('accid' => 'CAXX0192', 'name' => 'Hope');
$city_data[] = array('accid' => 'CAXX0193', 'name' => 'Howley');
$city_data[] = array('accid' => 'CAXX0609', 'name' => 'Hudson Bay');
$city_data[] = array('accid' => 'CAXX0194', 'name' => 'Hull');
$city_data[] = array('accid' => 'CAXX0195', 'name' => 'Ignace');
$city_data[] = array('accid' => 'CAXX0196', 'name' => 'Iles-de-la-Madeleine');
$city_data[] = array('accid' => 'CAXX0197', 'name' => 'Ilford');
$city_data[] = array('accid' => 'CAXX0198', 'name' => 'Ingersoll');
$city_data[] = array('accid' => 'CAXX0199', 'name' => 'Innisfail');
$city_data[] = array('accid' => 'CAXX0616', 'name' => 'Inukjuak');
$city_data[] = array('accid' => 'CAXX0632', 'name' => 'Inuvick');
$city_data[] = array('accid' => 'CAXX0201', 'name' => 'Invermere');
$city_data[] = array('accid' => 'CAXX0202', 'name' => 'Iqaluit');
$city_data[] = array('accid' => 'CAXX0203', 'name' => 'Irvine');
$city_data[] = array('accid' => 'CAXX0573', 'name' => 'Island Lake');
$city_data[] = array('accid' => 'CAXX0204', 'name' => 'Isle aux Morts');
$city_data[] = array('accid' => 'CAXX0205', 'name' => 'Jasper');
$city_data[] = array('accid' => 'CAXX0206', 'name' => 'Jellicoe');
$city_data[] = array('accid' => 'CAXX0207', 'name' => 'Joliette');
$city_data[] = array('accid' => 'CAXX0208', 'name' => 'Jonquiere');
$city_data[] = array('accid' => 'CAXX0209', 'name' => 'Kakabeka Falls');
$city_data[] = array('accid' => 'CAXX0210', 'name' => 'Kakawis');
$city_data[] = array('accid' => 'CAXX0211', 'name' => 'Kamloops');
$city_data[] = array('accid' => 'CAXX0212', 'name' => 'Kanata');
$city_data[] = array('accid' => 'CAXX0213', 'name' => 'Kapuskasing');
$city_data[] = array('accid' => 'CAXX0214', 'name' => 'Keene');
$city_data[] = array('accid' => 'CAXX0215', 'name' => 'Keewatin');
$city_data[] = array('accid' => 'CAXX0216', 'name' => 'Kelowna');
$city_data[] = array('accid' => 'CAXX0217', 'name' => 'Kemnay');
$city_data[] = array('accid' => 'CAXX0218', 'name' => 'Kenora');
$city_data[] = array('accid' => 'CAXX0219', 'name' => 'Kentville');
$city_data[] = array('accid' => 'CAXX0220', 'name' => 'Keswick');
$city_data[] = array('accid' => 'CAXX0221', 'name' => 'Kildonan');
$city_data[] = array('accid' => 'CAXX0222', 'name' => 'Kimberley');
$city_data[] = array('accid' => 'CAXX0223', 'name' => 'Kincardine');
$city_data[] = array('accid' => 'CAXX0587', 'name' => 'Kindakun Rocks');
$city_data[] = array('accid' => 'CAXX0224', 'name' => 'Kindersley');
$city_data[] = array('accid' => 'CAXX0225', 'name' => 'Kingston');
$city_data[] = array('accid' => 'CAXX0226', 'name' => 'Kinuso');
$city_data[] = array('accid' => 'CAXX0227', 'name' => 'Kitchener');
$city_data[] = array('accid' => 'CAXX0228', 'name' => 'Kitscoty');
$city_data[] = array('accid' => 'CAXX0615', 'name' => 'Kuujjuaq');
$city_data[] = array('accid' => 'CAXX0614', 'name' => 'Kuujjuarapik');
$city_data[] = array('accid' => 'CAXX0249', 'name' => 'L\'Isle-Verte');
$city_data[] = array('accid' => 'CAXX0229', 'name' => 'La Baie');
$city_data[] = array('accid' => 'CAXX0230', 'name' => 'La Corey');
$city_data[] = array('accid' => 'CAXX0231', 'name' => 'La Grande');
$city_data[] = array('accid' => 'CAXX0232', 'name' => 'La Malbaie');
$city_data[] = array('accid' => 'CAXX0233', 'name' => 'La Ronge');
$city_data[] = array('accid' => 'CAXX0234', 'name' => 'La Salle');
$city_data[] = array('accid' => 'CAXX0235', 'name' => 'Labrador City');
$city_data[] = array('accid' => 'CAXX0619', 'name' => 'Lac La Biche');
$city_data[] = array('accid' => 'CAXX0577', 'name' => 'Lac St. Pierre');
$city_data[] = array('accid' => 'CAXX0236', 'name' => 'Lachine');
$city_data[] = array('accid' => 'CAXX0237', 'name' => 'Lacombe');
$city_data[] = array('accid' => 'CAXX0238', 'name' => 'Lake Louise');
$city_data[] = array('accid' => 'CAXX0239', 'name' => 'Lakefield');
$city_data[] = array('accid' => 'CAXX0240', 'name' => 'Lamaline');
$city_data[] = array('accid' => 'CAXX0613', 'name' => 'Langara');
$city_data[] = array('accid' => 'CAXX0241', 'name' => 'Langham');
$city_data[] = array('accid' => 'CAXX0605', 'name' => 'Lansdowne House');
$city_data[] = array('accid' => 'CAXX0242', 'name' => 'Lashburn');
$city_data[] = array('accid' => 'CAXX0243', 'name' => 'Laval');
$city_data[] = array('accid' => 'CAXX0244', 'name' => 'Lawn');
$city_data[] = array('accid' => 'CAXX0245', 'name' => 'Lennoxville');
$city_data[] = array('accid' => 'CAXX0246', 'name' => 'Lethbridge');
$city_data[] = array('accid' => 'CAXX0247', 'name' => 'Levis');
$city_data[] = array('accid' => 'CAXX0248', 'name' => 'Lions Head');
$city_data[] = array('accid' => 'CAXX0250', 'name' => 'Lively');
$city_data[] = array('accid' => 'CAXX0610', 'name' => 'Lloydminister');
$city_data[] = array('accid' => 'CAXX0251', 'name' => 'Lloydminster');
$city_data[] = array('accid' => 'CAXX0252', 'name' => 'Lochalsh');
$city_data[] = array('accid' => 'CAXX0253', 'name' => 'Loggieville');
$city_data[] = array('accid' => 'CAXX0254', 'name' => 'Lomond');
$city_data[] = array('accid' => 'CAXX0255', 'name' => 'London');
$city_data[] = array('accid' => 'CAXX0256', 'name' => 'Longlac');
$city_data[] = array('accid' => 'CAXX0257', 'name' => 'Longueuil');
$city_data[] = array('accid' => 'CAXX0258', 'name' => 'Loretteville');
$city_data[] = array('accid' => 'CAXX0259', 'name' => 'Lucan');
$city_data[] = array('accid' => 'CAXX0260', 'name' => 'Luceville');
$city_data[] = array('accid' => 'CAXX0261', 'name' => 'Lumsden');
$city_data[] = array('accid' => 'CAXX0262', 'name' => 'Lund');
$city_data[] = array('accid' => 'CAXX0562', 'name' => 'Lynn Lake');
$city_data[] = array('accid' => 'CAXX0611', 'name' => 'Lytton');
$city_data[] = array('accid' => 'CAXX0263', 'name' => 'MacAlister');
$city_data[] = array('accid' => 'CAXX0264', 'name' => 'MacCan');
$city_data[] = array('accid' => 'CAXX0265', 'name' => 'MacDowall');
$city_data[] = array('accid' => 'CAXX0266', 'name' => 'MacKenzie');
$city_data[] = array('accid' => 'CAXX0267', 'name' => 'Magog');
$city_data[] = array('accid' => 'CAXX0268', 'name' => 'Magrath');
$city_data[] = array('accid' => 'CAXX0269', 'name' => 'Maitland');
$city_data[] = array('accid' => 'CAXX0270', 'name' => 'Malartic');
$city_data[] = array('accid' => 'CAXX0271', 'name' => 'Malton');
$city_data[] = array('accid' => 'CAXX0272', 'name' => 'Maniwaki');
$city_data[] = array('accid' => 'CAXX0273', 'name' => 'Markham');
$city_data[] = array('accid' => 'CAXX0274', 'name' => 'Marlboro');
$city_data[] = array('accid' => 'CAXX0600', 'name' => 'Mary\'s Harbour');
$city_data[] = array('accid' => 'CAXX0275', 'name' => 'Marysville');
$city_data[] = array('accid' => 'CAXX0276', 'name' => 'Massey');
$city_data[] = array('accid' => 'CAXX0602', 'name' => 'Matagami');
$city_data[] = array('accid' => 'CAXX0277', 'name' => 'Matane');
$city_data[] = array('accid' => 'CAXX0278', 'name' => 'Matapedia');
$city_data[] = array('accid' => 'CAXX0279', 'name' => 'Mattice');
$city_data[] = array('accid' => 'CAXX0280', 'name' => 'McGregor');
$city_data[] = array('accid' => 'CAXX0568', 'name' => 'Meadow Lake');
$city_data[] = array('accid' => 'CAXX0281', 'name' => 'Meaford');
$city_data[] = array('accid' => 'CAXX0282', 'name' => 'Medicine Hat');
$city_data[] = array('accid' => 'CAXX0586', 'name' => 'Melita');
$city_data[] = array('accid' => 'CAXX0283', 'name' => 'Memramcook');
$city_data[] = array('accid' => 'CAXX0284', 'name' => 'Merville');
$city_data[] = array('accid' => 'CAXX0285', 'name' => 'Messines');
$city_data[] = array('accid' => 'CAXX0286', 'name' => 'Midale');
$city_data[] = array('accid' => 'CAXX0287', 'name' => 'Middleton');
$city_data[] = array('accid' => 'CAXX0288', 'name' => 'Midhurst');
$city_data[] = array('accid' => 'CAXX0289', 'name' => 'Milton');
$city_data[] = array('accid' => 'CAXX0290', 'name' => 'Minaki');
$city_data[] = array('accid' => 'CAXX0291', 'name' => 'Mine Centre');
$city_data[] = array('accid' => 'CAXX0292', 'name' => 'Minnedosa');
$city_data[] = array('accid' => 'CAXX0293', 'name' => 'Miramichi');
$city_data[] = array('accid' => 'CAXX0594', 'name' => 'Miscou Island');
$city_data[] = array('accid' => 'CAXX0294', 'name' => 'Mission');
$city_data[] = array('accid' => 'CAXX0295', 'name' => 'Mississauga');
$city_data[] = array('accid' => 'CAXX0296', 'name' => 'Moisie');
$city_data[] = array('accid' => 'CAXX0297', 'name' => 'Moncton');
$city_data[] = array('accid' => 'CAXX0299', 'name' => 'Mont-Joli');
$city_data[] = array('accid' => 'CAXX0300', 'name' => 'Mont-Laurier');
$city_data[] = array('accid' => 'CAXX0298', 'name' => 'Monte Creek');
$city_data[] = array('accid' => 'CAXX0301', 'name' => 'Montreal');
$city_data[] = array('accid' => 'CAXX0302', 'name' => 'Moonbeam');
$city_data[] = array('accid' => 'CAXX0303', 'name' => 'Mooretown');
$city_data[] = array('accid' => 'CAXX0304', 'name' => 'Moose Factory');
$city_data[] = array('accid' => 'CAXX0305', 'name' => 'Moose Jaw');
$city_data[] = array('accid' => 'CAXX0306', 'name' => 'Moose Lake');
$city_data[] = array('accid' => 'CAXX0307', 'name' => 'Moose River');
$city_data[] = array('accid' => 'CAXX0308', 'name' => 'Moosonee');
$city_data[] = array('accid' => 'CAXX0309', 'name' => 'Morinville');
$city_data[] = array('accid' => 'CAXX0310', 'name' => 'Mount Pearl');
$city_data[] = array('accid' => 'CAXX0311', 'name' => 'Mount Stewart');
$city_data[] = array('accid' => 'CAXX0312', 'name' => 'Mud River');
$city_data[] = array('accid' => 'CAXX0313', 'name' => 'Nanaimo');
$city_data[] = array('accid' => 'CAXX0314', 'name' => 'Nanticoke');
$city_data[] = array('accid' => 'CAXX0598', 'name' => 'Natashquan');
$city_data[] = array('accid' => 'CAXX0315', 'name' => 'Nelson');
$city_data[] = array('accid' => 'CAXX0316', 'name' => 'Nelson House');
$city_data[] = array('accid' => 'CAXX0317', 'name' => 'New Waterford');
$city_data[] = array('accid' => 'CAXX0318', 'name' => 'New Westminster');
$city_data[] = array('accid' => 'CAXX0319', 'name' => 'Newcastle');
$city_data[] = array('accid' => 'CAXX0320', 'name' => 'Nezah');
$city_data[] = array('accid' => 'CAXX0321', 'name' => 'Niagara Falls');
$city_data[] = array('accid' => 'CAXX0322', 'name' => 'Nicolet');
$city_data[] = array('accid' => 'CAXX0323', 'name' => 'Nipigon');
$city_data[] = array('accid' => 'CAXX0324', 'name' => 'Nobel');
$city_data[] = array('accid' => 'CAXX0325', 'name' => 'North Battleford');
$city_data[] = array('accid' => 'CAXX0326', 'name' => 'North Bay');
$city_data[] = array('accid' => 'CAXX0327', 'name' => 'North Sydney');
$city_data[] = array('accid' => 'CAXX0328', 'name' => 'North Vancouver');
$city_data[] = array('accid' => 'CAXX0329', 'name' => 'North West River');
$city_data[] = array('accid' => 'CAXX0330', 'name' => 'North York');
$city_data[] = array('accid' => 'CAXX0572', 'name' => 'Norway House');
$city_data[] = array('accid' => 'CAXX0331', 'name' => 'Notre-Dame-du-Portage');
$city_data[] = array('accid' => 'CAXX0332', 'name' => 'Oak Bay');
$city_data[] = array('accid' => 'CAXX0333', 'name' => 'Oakville');
$city_data[] = array('accid' => 'CAXX0334', 'name' => 'Okanagan Landing');
$city_data[] = array('accid' => 'CAXX0335', 'name' => 'Okotoks');
$city_data[] = array('accid' => 'CAXX0336', 'name' => 'Oliver');
$city_data[] = array('accid' => 'CAXX0337', 'name' => 'Omemee');
$city_data[] = array('accid' => 'CAXX0338', 'name' => 'One Hundred Fifty Mile House');
$city_data[] = array('accid' => 'CAXX0339', 'name' => 'Opasatika');
$city_data[] = array('accid' => 'CAXX0340', 'name' => 'Orillia');
$city_data[] = array('accid' => 'CAXX0341', 'name' => 'Oromocto');
$city_data[] = array('accid' => 'CAXX0342', 'name' => 'Oshawa');
$city_data[] = array('accid' => 'CAXX0343', 'name' => 'Ottawa');
$city_data[] = array('accid' => 'CAXX0344', 'name' => 'Outremont');
$city_data[] = array('accid' => 'CAXX0345', 'name' => 'Owen Sound');
$city_data[] = array('accid' => 'CAXX0346', 'name' => 'Oyama');
$city_data[] = array('accid' => 'CAXX0347', 'name' => 'Parksville');
$city_data[] = array('accid' => 'CAXX0348', 'name' => 'Parry Sound');
$city_data[] = array('accid' => 'CAXX0349', 'name' => 'Parson');
$city_data[] = array('accid' => 'CAXX0350', 'name' => 'Pasqua');
$city_data[] = array('accid' => 'CAXX0631', 'name' => 'Peace River');
$city_data[] = array('accid' => 'CAXX0351', 'name' => 'Peachland');
$city_data[] = array('accid' => 'CAXX0352', 'name' => 'Peers');
$city_data[] = array('accid' => 'CAXX0353', 'name' => 'Pemberton');
$city_data[] = array('accid' => 'CAXX0354', 'name' => 'Pembroke');
$city_data[] = array('accid' => 'CAXX0355', 'name' => 'Penticton');
$city_data[] = array('accid' => 'CAXX0356', 'name' => 'Petawawa');
$city_data[] = array('accid' => 'CAXX0357', 'name' => 'Peterborough');
$city_data[] = array('accid' => 'CAXX0358', 'name' => 'Pickering');
$city_data[] = array('accid' => 'CAXX0359', 'name' => 'Pilot Butte');
$city_data[] = array('accid' => 'CAXX0360', 'name' => 'Point Edward');
$city_data[] = array('accid' => 'CAXX0361', 'name' => 'Pointe-Lebel');
$city_data[] = array('accid' => 'CAXX0362', 'name' => 'Port Alberni');
$city_data[] = array('accid' => 'CAXX0363', 'name' => 'Port Colborne');
$city_data[] = array('accid' => 'CAXX0364', 'name' => 'Port Coquitlam');
$city_data[] = array('accid' => 'CAXX0365', 'name' => 'Port Dover');
$city_data[] = array('accid' => 'CAXX0366', 'name' => 'Port Edward');
$city_data[] = array('accid' => 'CAXX0367', 'name' => 'Port Essington');
$city_data[] = array('accid' => 'CAXX0368', 'name' => 'Port Hardy');
$city_data[] = array('accid' => 'CAXX0369', 'name' => 'Port McNeill');
$city_data[] = array('accid' => 'CAXX0370', 'name' => 'Port Moody');
$city_data[] = array('accid' => 'CAXX0371', 'name' => 'Port Simpson');
$city_data[] = array('accid' => 'CAXX0582', 'name' => 'Port Weller');
$city_data[] = array('accid' => 'CAXX0372', 'name' => 'Port-aux-Basques');
$city_data[] = array('accid' => 'CAXX0373', 'name' => 'Port-Cartier');
$city_data[] = array('accid' => 'CAXX0374', 'name' => 'Pouch Cove');
$city_data[] = array('accid' => 'CAXX0375', 'name' => 'Powassan');
$city_data[] = array('accid' => 'CAXX0376', 'name' => 'Powell River');
$city_data[] = array('accid' => 'CAXX0377', 'name' => 'Preston');
$city_data[] = array('accid' => 'CAXX0378', 'name' => 'Price');
$city_data[] = array('accid' => 'CAXX0379', 'name' => 'Prince');
$city_data[] = array('accid' => 'CAXX0380', 'name' => 'Prince Albert');
$city_data[] = array('accid' => 'CAXX0381', 'name' => 'Prince George');
$city_data[] = array('accid' => 'CAXX0382', 'name' => 'Prince Rupert');
$city_data[] = array('accid' => 'CAXX0383', 'name' => 'Prospector');
$city_data[] = array('accid' => 'CAXX0629', 'name' => 'Puntzi Mountain');
$city_data[] = array('accid' => 'CAXX0384', 'name' => 'Qualicum Beach');
$city_data[] = array('accid' => 'CAXX0385', 'name' => 'Quebec');
$city_data[] = array('accid' => 'CAXX0386', 'name' => 'Queen Charlotte');
$city_data[] = array('accid' => 'CAXX0387', 'name' => 'Quinsam');
$city_data[] = array('accid' => 'CAXX0388', 'name' => 'Radisson');
$city_data[] = array('accid' => 'CAXX0389', 'name' => 'Radium Hot Springs');
$city_data[] = array('accid' => 'CAXX0390', 'name' => 'Rae');
$city_data[] = array('accid' => 'CAXX0391', 'name' => 'Raleigh');
$city_data[] = array('accid' => 'CAXX0563', 'name' => 'Rankin Inlet');
$city_data[] = array('accid' => 'CAXX0392', 'name' => 'Raymond');
$city_data[] = array('accid' => 'CAXX0393', 'name' => 'Read Island');
$city_data[] = array('accid' => 'CAXX0394', 'name' => 'Red Deer');
$city_data[] = array('accid' => 'CAXX0606', 'name' => 'Red Lake');
$city_data[] = array('accid' => 'CAXX0395', 'name' => 'Red Rock');
$city_data[] = array('accid' => 'CAXX0396', 'name' => 'Redcliff');
$city_data[] = array('accid' => 'CAXX0397', 'name' => 'Regina');
$city_data[] = array('accid' => 'CAXX0398', 'name' => 'Revelstoke');
$city_data[] = array('accid' => 'CAXX0399', 'name' => 'Rhein');
$city_data[] = array('accid' => 'CAXX0400', 'name' => 'Richmond');
$city_data[] = array('accid' => 'CAXX0401', 'name' => 'Richmond Hill');
$city_data[] = array('accid' => 'CAXX0402', 'name' => 'Rimouski');
$city_data[] = array('accid' => 'CAXX0403', 'name' => 'Riverton');
$city_data[] = array('accid' => 'CAXX0404', 'name' => 'Riviere-a-Claude');
$city_data[] = array('accid' => 'CAXX0405', 'name' => 'Riviere-du-Loup');
$city_data[] = array('accid' => 'CAXX0406', 'name' => 'Roberval');
$city_data[] = array('accid' => 'CAXX0570', 'name' => 'Rockglen');
$city_data[] = array('accid' => 'CAXX0407', 'name' => 'Rolla');
$city_data[] = array('accid' => 'CAXX0408', 'name' => 'Rose Blanche');
$city_data[] = array('accid' => 'CAXX0409', 'name' => 'Rosetown');
$city_data[] = array('accid' => 'CAXX0590', 'name' => 'Rosetown East');
$city_data[] = array('accid' => 'CAXX0410', 'name' => 'Rossland');
$city_data[] = array('accid' => 'CAXX0411', 'name' => 'Rothesay');
$city_data[] = array('accid' => 'CAXX0412', 'name' => 'Saanich');
$city_data[] = array('accid' => 'CAXX0591', 'name' => 'Sable Island');
$city_data[] = array('accid' => 'CAXX0413', 'name' => 'Sackville');
$city_data[] = array('accid' => 'CAXX0414', 'name' => 'Saint Albert');
$city_data[] = array('accid' => 'CAXX0415', 'name' => 'Saint Anthony');
$city_data[] = array('accid' => 'CAXX0416', 'name' => 'Saint Catharines');
$city_data[] = array('accid' => 'CAXX0417', 'name' => 'Saint Catharines Arpt');
$city_data[] = array('accid' => 'CAXX0418', 'name' => 'Saint Eleanors');
$city_data[] = array('accid' => 'CAXX0419', 'name' => 'Saint John');
$city_data[] = array('accid' => 'CAXX0421', 'name' => 'Saint Lawrence');
$city_data[] = array('accid' => 'CAXX0422', 'name' => 'Saint Leonard');
$city_data[] = array('accid' => 'CAXX0423', 'name' => 'Saint Louis');
$city_data[] = array('accid' => 'CAXX0424', 'name' => 'Saint Marys');
$city_data[] = array('accid' => 'CAXX0428', 'name' => 'Saint-Eustache');
$city_data[] = array('accid' => 'CAXX0429', 'name' => 'Saint-Felicien');
$city_data[] = array('accid' => 'CAXX0430', 'name' => 'Saint-Hubert');
$city_data[] = array('accid' => 'CAXX0431', 'name' => 'Saint-Irenee');
$city_data[] = array('accid' => 'CAXX0432', 'name' => 'Saint-Jacques');
$city_data[] = array('accid' => 'CAXX0433', 'name' => 'Saint-Jovite');
$city_data[] = array('accid' => 'CAXX0434', 'name' => 'Saint-Prime');
$city_data[] = array('accid' => 'CAXX0435', 'name' => 'Saint-Simeon');
$city_data[] = array('accid' => 'CAXX0425', 'name' => 'Sainte-Catherine');
$city_data[] = array('accid' => 'CAXX0426', 'name' => 'Sainte-Felicite');
$city_data[] = array('accid' => 'CAXX0427', 'name' => 'Sainte-Foy');
$city_data[] = array('accid' => 'CAXX0437', 'name' => 'Salmon Arm');
$city_data[] = array('accid' => 'CAXX0438', 'name' => 'Salmon Valley');
$city_data[] = array('accid' => 'CAXX0439', 'name' => 'Saltcoats');
$city_data[] = array('accid' => 'CAXX0440', 'name' => 'Sandspit');
$city_data[] = array('accid' => 'CAXX0441', 'name' => 'Sarnia');
$city_data[] = array('accid' => 'CAXX0442', 'name' => 'Saskatoon');
$city_data[] = array('accid' => 'CAXX0443', 'name' => 'Sault Ste Marie');
$city_data[] = array('accid' => 'CAXX0444', 'name' => 'Savona');
$city_data[] = array('accid' => 'CAXX0445', 'name' => 'Scarborough');
$city_data[] = array('accid' => 'CAXX0446', 'name' => 'Schefferville');
$city_data[] = array('accid' => 'CAXX0447', 'name' => 'Schumacher');
$city_data[] = array('accid' => 'CAXX0448', 'name' => 'Selkirk');
$city_data[] = array('accid' => 'CAXX0449', 'name' => 'Sept-Iles');
$city_data[] = array('accid' => 'CAXX0450', 'name' => 'Sevenpersons');
$city_data[] = array('accid' => 'CAXX0451', 'name' => 'Sexsmith');
$city_data[] = array('accid' => 'CAXX0452', 'name' => 'Shawanga');
$city_data[] = array('accid' => 'CAXX0592', 'name' => 'Shearwater');
$city_data[] = array('accid' => 'CAXX0453', 'name' => 'Shediac');
$city_data[] = array('accid' => 'CAXX0454', 'name' => 'Sherbrooke');
$city_data[] = array('accid' => 'CAXX0455', 'name' => 'Sidney');
$city_data[] = array('accid' => 'CAXX0456', 'name' => 'Sillery');
$city_data[] = array('accid' => 'CAXX0457', 'name' => 'Simcoe');
$city_data[] = array('accid' => 'CAXX0603', 'name' => 'Sioux Lookout');
$city_data[] = array('accid' => 'CAXX0458', 'name' => 'Sipiwesk');
$city_data[] = array('accid' => 'CAXX0459', 'name' => 'Skidegate');
$city_data[] = array('accid' => 'CAXX0460', 'name' => 'Slave Lake');
$city_data[] = array('accid' => 'CAXX0461', 'name' => 'Smithers');
$city_data[] = array('accid' => 'CAXX0462', 'name' => 'Snake River');
$city_data[] = array('accid' => 'CAXX0463', 'name' => 'Soda Creek');
$city_data[] = array('accid' => 'CAXX0464', 'name' => 'Sorel');
$city_data[] = array('accid' => 'CAXX0465', 'name' => 'Sorrento');
$city_data[] = array('accid' => 'CAXX0466', 'name' => 'Souris');
$city_data[] = array('accid' => 'CAXX0467', 'name' => 'South Porcupine');
$city_data[] = array('accid' => 'CAXX0468', 'name' => 'Spanish');
$city_data[] = array('accid' => 'CAXX0469', 'name' => 'Spragge');
$city_data[] = array('accid' => 'CAXX0470', 'name' => 'Springhill');
$city_data[] = array('accid' => 'CAXX0471', 'name' => 'Spruce Grove');
$city_data[] = array('accid' => 'CAXX0472', 'name' => 'Spurfield');
$city_data[] = array('accid' => 'CAXX0579', 'name' => 'Squamish Airport');
$city_data[] = array('accid' => 'CAXX0420', 'name' => 'St. John\'s');
$city_data[] = array('accid' => 'CAXX0593', 'name' => 'St. Stephen');
$city_data[] = array('accid' => 'CAXX0473', 'name' => 'Stanley Mission');
$city_data[] = array('accid' => 'CAXX0474', 'name' => 'Stayner');
$city_data[] = array('accid' => 'CAXX0475', 'name' => 'Stephenville');
$city_data[] = array('accid' => 'CAXX0476', 'name' => 'Stillwater');
$city_data[] = array('accid' => 'CAXX0477', 'name' => 'Stonewall');
$city_data[] = array('accid' => 'CAXX0478', 'name' => 'Stoney Creek');
$city_data[] = array('accid' => 'CAXX0479', 'name' => 'Stony Plain');
$city_data[] = array('accid' => 'CAXX0480', 'name' => 'Strathroy');
$city_data[] = array('accid' => 'CAXX0481', 'name' => 'Sturgeon Falls');
$city_data[] = array('accid' => 'CAXX0482', 'name' => 'Sudbury');
$city_data[] = array('accid' => 'CAXX0483', 'name' => 'Summerland');
$city_data[] = array('accid' => 'CAXX0484', 'name' => 'Summerside');
$city_data[] = array('accid' => 'CAXX0485', 'name' => 'Surrey');
$city_data[] = array('accid' => 'CAXX0584', 'name' => 'Swan River');
$city_data[] = array('accid' => 'CAXX0486', 'name' => 'Swift Current');
$city_data[] = array('accid' => 'CAXX0487', 'name' => 'Sydney');
$city_data[] = array('accid' => 'CAXX0488', 'name' => 'Sydney Mines');
$city_data[] = array('accid' => 'CAXX0489', 'name' => 'Sylvan Lake');
$city_data[] = array('accid' => 'CAXX0490', 'name' => 'Taber');
$city_data[] = array('accid' => 'CAXX0491', 'name' => 'Taylor');
$city_data[] = array('accid' => 'CAXX0492', 'name' => 'Tecumseh');
$city_data[] = array('accid' => 'CAXX0493', 'name' => 'Terrace');
$city_data[] = array('accid' => 'CAXX0494', 'name' => 'The Pas');
$city_data[] = array('accid' => 'CAXX0495', 'name' => 'Thompson');
$city_data[] = array('accid' => 'CAXX0496', 'name' => 'Thornbury');
$city_data[] = array('accid' => 'CAXX0497', 'name' => 'Thorold');
$city_data[] = array('accid' => 'CAXX0498', 'name' => 'Thunder Bay');
$city_data[] = array('accid' => 'CAXX0499', 'name' => 'Tidehead');
$city_data[] = array('accid' => 'CAXX0500', 'name' => 'Tillsonburg');
$city_data[] = array('accid' => 'CAXX0501', 'name' => 'Timmins');
$city_data[] = array('accid' => 'CAXX0502', 'name' => 'Tofino');
$city_data[] = array('accid' => 'CAXX0503', 'name' => 'Torbay');
$city_data[] = array('accid' => 'CAXX0504', 'name' => 'Toronto');
$city_data[] = array('accid' => 'CAXX0505', 'name' => 'Torquay');
$city_data[] = array('accid' => 'CAXX0506', 'name' => 'Tracy');
$city_data[] = array('accid' => 'CAXX0507', 'name' => 'Trail');
$city_data[] = array('accid' => 'CAXX0508', 'name' => 'Trenton');
$city_data[] = array('accid' => 'CAXX0509', 'name' => 'Trois-Rivieres');
$city_data[] = array('accid' => 'CAXX0510', 'name' => 'Truro');
$city_data[] = array('accid' => 'CAXX0511', 'name' => 'Tusket');
$city_data[] = array('accid' => 'CAXX0512', 'name' => 'Tuxford');
$city_data[] = array('accid' => 'CAXX0513', 'name' => 'Tyrone');
$city_data[] = array('accid' => 'CAXX0514', 'name' => 'Ucluelet');
$city_data[] = array('accid' => 'CAXX0583', 'name' => 'Upsala');
$city_data[] = array('accid' => 'CAXX0625', 'name' => 'Uranium City');
$city_data[] = array('accid' => 'CAXX0515', 'name' => 'Usk');
$city_data[] = array('accid' => 'CAXX0571', 'name' => 'Val Marie Southeast');
$city_data[] = array('accid' => 'CAXX0516', 'name' => 'Val-d\'Or');
$city_data[] = array('accid' => 'CAXX0517', 'name' => 'Vananda');
$city_data[] = array('accid' => 'CAXX0518', 'name' => 'Vancouver');
$city_data[] = array('accid' => 'CAXX0519', 'name' => 'Vassan');
$city_data[] = array('accid' => 'CAXX0520', 'name' => 'Verdun');
$city_data[] = array('accid' => 'CAXX0521', 'name' => 'Vermilion');
$city_data[] = array('accid' => 'CAXX0522', 'name' => 'Veteran');
$city_data[] = array('accid' => 'CAXX0523', 'name' => 'Victoria');
$city_data[] = array('accid' => 'CAXX0524', 'name' => 'Virden');
$city_data[] = array('accid' => 'CAXX0525', 'name' => 'Waasis');
$city_data[] = array('accid' => 'CAXX0526', 'name' => 'Wabush');
$city_data[] = array('accid' => 'CAXX0527', 'name' => 'Walcott');
$city_data[] = array('accid' => 'CAXX0528', 'name' => 'Waldeck');
$city_data[] = array('accid' => 'CAXX0529', 'name' => 'Waltham Station');
$city_data[] = array('accid' => 'CAXX0530', 'name' => 'Warman');
$city_data[] = array('accid' => 'CAXX0585', 'name' => 'Wasagaming');
$city_data[] = array('accid' => 'CAXX0626', 'name' => 'Waskaganish');
$city_data[] = array('accid' => 'CAXX0531', 'name' => 'Waterloo');
$city_data[] = array('accid' => 'CAXX0627', 'name' => 'Watson Lake');
$city_data[] = array('accid' => 'CAXX0532', 'name' => 'Wawa');
$city_data[] = array('accid' => 'CAXX0533', 'name' => 'Webb');
$city_data[] = array('accid' => 'CAXX0534', 'name' => 'Wedgeport');
$city_data[] = array('accid' => 'CAXX0535', 'name' => 'Welland');
$city_data[] = array('accid' => 'CAXX0536', 'name' => 'Wembley');
$city_data[] = array('accid' => 'CAXX0581', 'name' => 'Western Head');
$city_data[] = array('accid' => 'CAXX0537', 'name' => 'Weyburn');
$city_data[] = array('accid' => 'CAXX0538', 'name' => 'Whistler');
$city_data[] = array('accid' => 'CAXX0539', 'name' => 'Whitby');
$city_data[] = array('accid' => 'CAXX0540', 'name' => 'Whitehorse');
$city_data[] = array('accid' => 'CAXX0541', 'name' => 'Wiarton');
$city_data[] = array('accid' => 'CAXX0542', 'name' => 'Williams Lake');
$city_data[] = array('accid' => 'CAXX0543', 'name' => 'Willow River');
$city_data[] = array('accid' => 'CAXX0544', 'name' => 'Willowbrook');
$city_data[] = array('accid' => 'CAXX0545', 'name' => 'Windermere');
$city_data[] = array('accid' => 'CAXX0546', 'name' => 'Windsor');
$city_data[] = array('accid' => 'CAXX0547', 'name' => 'Winnipeg');
$city_data[] = array('accid' => 'CAXX0548', 'name' => 'Wishart');
$city_data[] = array('accid' => 'CAXX0549', 'name' => 'Witless Bay');
$city_data[] = array('accid' => 'CAXX0550', 'name' => 'Wolfe Island');
$city_data[] = array('accid' => 'CAXX0551', 'name' => 'Woodbridge');
$city_data[] = array('accid' => 'CAXX0552', 'name' => 'Woodstock');
$city_data[] = array('accid' => 'CAXX0553', 'name' => 'Wymark');
$city_data[] = array('accid' => 'CAXX0554', 'name' => 'Wynyard');
$city_data[] = array('accid' => 'CAXX0555', 'name' => 'Yale');
$city_data[] = array('accid' => 'CAXX0556', 'name' => 'Yarmouth');
$city_data[] = array('accid' => 'CAXX0557', 'name' => 'Yellowknife');
$city_data[] = array('accid' => 'CAXX0558', 'name' => 'Yorkton');
$city_data[] = array('accid' => 'CAXX0559', 'name' => 'Zehner');

?>