<?php

// City package for Ireland 

$city_name = 'Ireland';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'EIXX0001', 'name' => 'Arklow');
$city_data[] = array('accid' => 'EIXX0002', 'name' => 'Ballincollig');
$city_data[] = array('accid' => 'EIXX0003', 'name' => 'Carlow');
$city_data[] = array('accid' => 'EIXX0004', 'name' => 'Carrick on Shanno');
$city_data[] = array('accid' => 'EIXX0005', 'name' => 'Carrigaline');
$city_data[] = array('accid' => 'EIXX0006', 'name' => 'Castlebar');
$city_data[] = array('accid' => 'EIXX0007', 'name' => 'Castleconnell');
$city_data[] = array('accid' => 'EIXX0008', 'name' => 'Castlemartyr');
$city_data[] = array('accid' => 'EIXX0009', 'name' => 'Cavan');
$city_data[] = array('accid' => 'EIXX0010', 'name' => 'Clifden');
$city_data[] = array('accid' => 'EIXX0011', 'name' => 'Cork');
$city_data[] = array('accid' => 'EIXX0012', 'name' => 'Crookstown');
$city_data[] = array('accid' => 'EIXX0013', 'name' => 'Drogheda');
$city_data[] = array('accid' => 'EIXX0014', 'name' => 'Dublin');
$city_data[] = array('accid' => 'EIXX0015', 'name' => 'Dun Laoghaire');
$city_data[] = array('accid' => 'EIXX0016', 'name' => 'Ennis');
$city_data[] = array('accid' => 'EIXX0017', 'name' => 'Galway');
$city_data[] = array('accid' => 'EIXX0018', 'name' => 'Greystones');
$city_data[] = array('accid' => 'EIXX0019', 'name' => 'Kilcolgan');
$city_data[] = array('accid' => 'EIXX0020', 'name' => 'Kildare');
$city_data[] = array('accid' => 'EIXX0021', 'name' => 'Kilkenny');
$city_data[] = array('accid' => 'EIXX0022', 'name' => 'Killadysert');
$city_data[] = array('accid' => 'EIXX0023', 'name' => 'Killarney');
$city_data[] = array('accid' => 'EIXX0024', 'name' => 'Leixlip');
$city_data[] = array('accid' => 'EIXX0025', 'name' => 'Letterkenny');
$city_data[] = array('accid' => 'EIXX0026', 'name' => 'Limerick');
$city_data[] = array('accid' => 'EIXX0027', 'name' => 'Longford');
$city_data[] = array('accid' => 'EIXX0028', 'name' => 'Mallow');
$city_data[] = array('accid' => 'EIXX0029', 'name' => 'Midleton');
$city_data[] = array('accid' => 'EIXX0030', 'name' => 'Monaghan');
$city_data[] = array('accid' => 'EIXX0031', 'name' => 'Moycullen');
$city_data[] = array('accid' => 'EIXX0032', 'name' => 'Mullingar');
$city_data[] = array('accid' => 'EIXX0033', 'name' => 'Naas');
$city_data[] = array('accid' => 'EIXX0034', 'name' => 'Navan');
$city_data[] = array('accid' => 'EIXX0035', 'name' => 'Newmarket on Ferg');
$city_data[] = array('accid' => 'EIXX0036', 'name' => 'Oranmore');
$city_data[] = array('accid' => 'EIXX0037', 'name' => 'Pallaskenry');
$city_data[] = array('accid' => 'EIXX0038', 'name' => 'Portlaoise');
$city_data[] = array('accid' => 'EIXX0039', 'name' => 'Portmarnock');
$city_data[] = array('accid' => 'EIXX0040', 'name' => 'Ringaskiddy');
$city_data[] = array('accid' => 'EIXX0041', 'name' => 'Roscommon');
$city_data[] = array('accid' => 'EIXX0042', 'name' => 'Sligo');
$city_data[] = array('accid' => 'EIXX0043', 'name' => 'Swords');
$city_data[] = array('accid' => 'EIXX0044', 'name' => 'Tallaght');
$city_data[] = array('accid' => 'EIXX0045', 'name' => 'Tipperary');
$city_data[] = array('accid' => 'EIXX0046', 'name' => 'Tullamore');
$city_data[] = array('accid' => 'EIXX0047', 'name' => 'Waterford');
$city_data[] = array('accid' => 'EIXX0048', 'name' => 'Wexford');
$city_data[] = array('accid' => 'EIXX0049', 'name' => 'Wicklow');
$city_data[] = array('accid' => 'EIXX0050', 'name' => 'Belmullet');
$city_data[] = array('accid' => 'EIXX0052', 'name' => 'Aasleagh');
$city_data[] = array('accid' => 'EIXX0053', 'name' => 'Valentia Observat');
$city_data[] = array('accid' => 'EIXX0054', 'name' => 'Rosslare');
$city_data[] = array('accid' => 'EIXX0055', 'name' => 'Athlone');
$city_data[] = array('accid' => 'EIXX0056', 'name' => 'Ballina/Mayo');
$city_data[] = array('accid' => 'EIXX0057', 'name' => 'Ballycanew');
$city_data[] = array('accid' => 'EIXX0058', 'name' => 'Ballinasloe');
$city_data[] = array('accid' => 'EIXX0059', 'name' => 'Blackhead');
$city_data[] = array('accid' => 'EIXX0060', 'name' => 'Claremorris');
$city_data[] = array('accid' => 'EIXX0061', 'name' => 'Crookhaven');
$city_data[] = array('accid' => 'EIXX0062', 'name' => 'Connaught Airport');
$city_data[] = array('accid' => 'EIXX0063', 'name' => 'Ballymahon');
$city_data[] = array('accid' => 'EIXX0064', 'name' => 'Carrickmacross');
$city_data[] = array('accid' => 'EIXX0065', 'name' => 'Edenderry');
$city_data[] = array('accid' => 'EIXX0066', 'name' => 'Dunmore');
$city_data[] = array('accid' => 'EIXX0067', 'name' => 'Dromond');
$city_data[] = array('accid' => 'EIXX0069', 'name' => 'Greenslough');
$city_data[] = array('accid' => 'EIXX0070', 'name' => 'Gorunna');
$city_data[] = array('accid' => 'EIXX0071', 'name' => 'Kilrush');
$city_data[] = array('accid' => 'EIXX0072', 'name' => 'Loughrea');
$city_data[] = array('accid' => 'EIXX0073', 'name' => 'Milestone');
$city_data[] = array('accid' => 'EIXX0074', 'name' => 'Oldcastle');
$city_data[] = array('accid' => 'EIXX0075', 'name' => 'Portlaw');
$city_data[] = array('accid' => 'EIXX0076', 'name' => 'Roscrea');
$city_data[] = array('accid' => 'EIXX0077', 'name' => 'Shercock');
$city_data[] = array('accid' => 'EIXX0078', 'name' => 'Tralee');
$city_data[] = array('accid' => 'EIXX0079', 'name' => 'Thurles');
$city_data[] = array('accid' => 'EIXX0080', 'name' => 'Tuam');
$city_data[] = array('accid' => 'EIXX0081', 'name' => 'West Arran');
$city_data[] = array('accid' => 'EIXX0082', 'name' => 'Youghal');
$city_data[] = array('accid' => 'EIXX0083', 'name' => 'Sea Blackhead');
$city_data[] = array('accid' => 'EIXX0084', 'name' => 'Irish Sea');
$city_data[] = array('accid' => 'EIXX0085', 'name' => 'Sea Malinhead');
$city_data[] = array('accid' => 'EIXX0086', 'name' => 'St Georges Chan');
$city_data[] = array('accid' => 'EIXX0087', 'name' => 'Sea Valentia');
$city_data[] = array('accid' => 'EIXX0090', 'name' => 'Clones');
$city_data[] = array('accid' => 'EIXX0091', 'name' => 'Malin Head');
$city_data[] = array('accid' => 'EIXX0092', 'name' => 'Carrick On Suir');
$city_data[] = array('accid' => 'EIXX0094', 'name' => 'Clonakilty');
$city_data[] = array('accid' => 'EIXX0100', 'name' => 'Ballinafad');
$city_data[] = array('accid' => 'EIXX0101', 'name' => 'Tramore');

?>
