<?php

// City package for France

$city_name = 'France';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'FRXX0001', 'name' => 'Aix-en-Provence');
$city_data[] = array('accid' => 'FRXX0002', 'name' => 'Albi');
$city_data[] = array('accid' => 'FRXX0003', 'name' => 'Annemasse');
$city_data[] = array('accid' => 'FRXX0004', 'name' => 'Antibes');
$city_data[] = array('accid' => 'FRXX0005', 'name' => 'Arnage');
$city_data[] = array('accid' => 'FRXX0006', 'name' => 'Aubagne');
$city_data[] = array('accid' => 'FRXX0007', 'name' => 'Aubervilliers');
$city_data[] = array('accid' => 'FRXX0008', 'name' => 'Auxerre');
$city_data[] = array('accid' => 'FRXX0009', 'name' => 'Aytre');
$city_data[] = array('accid' => 'FRXX0010', 'name' => 'Bayeux');
$city_data[] = array('accid' => 'FRXX0011', 'name' => 'Beauvais');
$city_data[] = array('accid' => 'FRXX0012', 'name' => 'Belfort');
$city_data[] = array('accid' => 'FRXX0013', 'name' => 'Beziers');
$city_data[] = array('accid' => 'FRXX0014', 'name' => 'Blois');
$city_data[] = array('accid' => 'FRXX0015', 'name' => 'Bobigny');
$city_data[] = array('accid' => 'FRXX0016', 'name' => 'Bordeaux');
$city_data[] = array('accid' => 'FRXX0017', 'name' => 'Bourg-en-Bresse');
$city_data[] = array('accid' => 'FRXX0018', 'name' => 'Bourges');
$city_data[] = array('accid' => 'FRXX0019', 'name' => 'Brest');
$city_data[] = array('accid' => 'FRXX0020', 'name' => 'Caen');
$city_data[] = array('accid' => 'FRXX0021', 'name' => 'Cagnes-sur-Mer');
$city_data[] = array('accid' => 'FRXX0022', 'name' => 'Cahors');
$city_data[] = array('accid' => 'FRXX0023', 'name' => 'Cannes');
$city_data[] = array('accid' => 'FRXX0024', 'name' => 'Carbon-Blanc');
$city_data[] = array('accid' => 'FRXX0025', 'name' => 'Carcassonne');
$city_data[] = array('accid' => 'FRXX0026', 'name' => 'Carquefou');
$city_data[] = array('accid' => 'FRXX0027', 'name' => 'Castelnau-de-Medoc');
$city_data[] = array('accid' => 'FRXX0028', 'name' => 'Chantilly');
$city_data[] = array('accid' => 'FRXX0029', 'name' => 'Chartres');
$city_data[] = array('accid' => 'FRXX0030', 'name' => 'Chateauroux');
$city_data[] = array('accid' => 'FRXX0031', 'name' => 'Chatelaillon');
$city_data[] = array('accid' => 'FRXX0032', 'name' => 'Cherbourg');
$city_data[] = array('accid' => 'FRXX0033', 'name' => 'Cholet');
$city_data[] = array('accid' => 'FRXX0034', 'name' => 'Colmar');
$city_data[] = array('accid' => 'FRXX0035', 'name' => 'Coulans');
$city_data[] = array('accid' => 'FRXX0036', 'name' => 'Dijon');
$city_data[] = array('accid' => 'FRXX0037', 'name' => 'Dreux');
$city_data[] = array('accid' => 'FRXX0038', 'name' => 'Evreux');
$city_data[] = array('accid' => 'FRXX0039', 'name' => 'Fabregues');
$city_data[] = array('accid' => 'FRXX0040', 'name' => 'Frejus');
$city_data[] = array('accid' => 'FRXX0041', 'name' => 'Grasse');
$city_data[] = array('accid' => 'FRXX0042', 'name' => 'Haguenau');
$city_data[] = array('accid' => 'FRXX0043', 'name' => 'La Bazoge');
$city_data[] = array('accid' => 'FRXX0044', 'name' => 'La Rochelle');
$city_data[] = array('accid' => 'FRXX0045', 'name' => 'Landerneau');
$city_data[] = array('accid' => 'FRXX0046', 'name' => 'Le Grand-Quevilly');
$city_data[] = array('accid' => 'FRXX0047', 'name' => 'Le Havre');
$city_data[] = array('accid' => 'FRXX0048', 'name' => 'Le Mans');
$city_data[] = array('accid' => 'FRXX0049', 'name' => 'Lens');
$city_data[] = array('accid' => 'FRXX0050', 'name' => 'Les Sables-d\'Olonne');
$city_data[] = array('accid' => 'FRXX0051', 'name' => 'Libourne');
$city_data[] = array('accid' => 'FRXX0052', 'name' => 'Lille');
$city_data[] = array('accid' => 'FRXX0053', 'name' => 'Lisieux');
$city_data[] = array('accid' => 'FRXX0054', 'name' => 'Lorient');
$city_data[] = array('accid' => 'FRXX0055', 'name' => 'Lyon');
$city_data[] = array('accid' => 'FRXX0056', 'name' => 'Macon');
$city_data[] = array('accid' => 'FRXX0057', 'name' => 'Malicorne');
$city_data[] = array('accid' => 'FRXX0058', 'name' => 'Marignane');
$city_data[] = array('accid' => 'FRXX0059', 'name' => 'Marseille');
$city_data[] = array('accid' => 'FRXX0060', 'name' => 'Meaux');
$city_data[] = array('accid' => 'FRXX0061', 'name' => 'Melun');
$city_data[] = array('accid' => 'FRXX0062', 'name' => 'Menton');
$city_data[] = array('accid' => 'FRXX0063', 'name' => 'Merignac');
$city_data[] = array('accid' => 'FRXX0064', 'name' => 'Metz');
$city_data[] = array('accid' => 'FRXX0065', 'name' => 'Mondeville');
$city_data[] = array('accid' => 'FRXX0066', 'name' => 'Montargis');
$city_data[] = array('accid' => 'FRXX0067', 'name' => 'Montauban');
$city_data[] = array('accid' => 'FRXX0068', 'name' => 'Montpellier');
$city_data[] = array('accid' => 'FRXX0069', 'name' => 'Mont-Saint-Aignan');
$city_data[] = array('accid' => 'FRXX0070', 'name' => 'Morlaix');
$city_data[] = array('accid' => 'FRXX0071', 'name' => 'Mulhouse');
$city_data[] = array('accid' => 'FRXX0072', 'name' => 'Nantes');
$city_data[] = array('accid' => 'FRXX0073', 'name' => 'Nice');
$city_data[] = array('accid' => 'FRXX0074', 'name' => 'Orleans');
$city_data[] = array('accid' => 'FRXX0075', 'name' => 'Orvault');
$city_data[] = array('accid' => 'FRXX0076', 'name' => 'Paris');
$city_data[] = array('accid' => 'FRXX0077', 'name' => 'Paris/Charles De Gaulle');
$city_data[] = array('accid' => 'FRXX0078', 'name' => 'Pessac');
$city_data[] = array('accid' => 'FRXX0079', 'name' => 'Quimper');
$city_data[] = array('accid' => 'FRXX0080', 'name' => 'Reims');
$city_data[] = array('accid' => 'FRXX0081', 'name' => 'Reze');
$city_data[] = array('accid' => 'FRXX0082', 'name' => 'Roanne');
$city_data[] = array('accid' => 'FRXX0083', 'name' => 'Rochefort');
$city_data[] = array('accid' => 'FRXX0084', 'name' => 'Roubaix');
$city_data[] = array('accid' => 'FRXX0085', 'name' => 'Rouen');
$city_data[] = array('accid' => 'FRXX0086', 'name' => 'Saint-Brieuc');
$city_data[] = array('accid' => 'FRXX0087', 'name' => 'Saint-Denis');
$city_data[] = array('accid' => 'FRXX0088', 'name' => 'Saint-Die');
$city_data[] = array('accid' => 'FRXX0089', 'name' => 'Saint-Etienne-du-Rouvray');
$city_data[] = array('accid' => 'FRXX0090', 'name' => 'Saint-Lo');
$city_data[] = array('accid' => 'FRXX0091', 'name' => 'Saint-Nazaire');
$city_data[] = array('accid' => 'FRXX0092', 'name' => 'Saint-Raphael');
$city_data[] = array('accid' => 'FRXX0093', 'name' => 'Salon-de-Provence');
$city_data[] = array('accid' => 'FRXX0094', 'name' => 'Sete');
$city_data[] = array('accid' => 'FRXX0095', 'name' => 'Strasbourg');
$city_data[] = array('accid' => 'FRXX0096', 'name' => 'Talence');
$city_data[] = array('accid' => 'FRXX0097', 'name' => 'Tarbes');
$city_data[] = array('accid' => 'FRXX0098', 'name' => 'Toulon');
$city_data[] = array('accid' => 'FRXX0099', 'name' => 'Toulouse');
$city_data[] = array('accid' => 'FRXX0100', 'name' => 'Tours');
$city_data[] = array('accid' => 'FRXX0101', 'name' => 'Troyes');
$city_data[] = array('accid' => 'FRXX0102', 'name' => 'Valence');
$city_data[] = array('accid' => 'FRXX0103', 'name' => 'Valognes');
$city_data[] = array('accid' => 'FRXX0104', 'name' => 'Vendargues');
$city_data[] = array('accid' => 'FRXX0105', 'name' => 'Venissieux');
$city_data[] = array('accid' => 'FRXX0106', 'name' => 'Versailles');
$city_data[] = array('accid' => 'FRXX0107', 'name' => 'Vienne');
$city_data[] = array('accid' => 'FRXX0108', 'name' => 'Vierzon');
$city_data[] = array('accid' => 'FRXX0109', 'name' => 'Villefranche-sur-Saone');
$city_data[] = array('accid' => 'FRXX0110', 'name' => 'Villeurbanne');
$city_data[] = array('accid' => 'FRXX0111', 'name' => 'Abbeville');
$city_data[] = array('accid' => 'FRXX0112', 'name' => 'La Hague');
$city_data[] = array('accid' => 'FRXX0113', 'name' => 'Ouessant');
$city_data[] = array('accid' => 'FRXX0114', 'name' => 'Rennes');
$city_data[] = array('accid' => 'FRXX0115', 'name' => 'Nancy/Essey');
$city_data[] = array('accid' => 'FRXX0116', 'name' => 'Le Talut');
$city_data[] = array('accid' => 'FRXX0118', 'name' => 'Chassiron');
$city_data[] = array('accid' => 'FRXX0119', 'name' => 'Limoges');
$city_data[] = array('accid' => 'FRXX0120', 'name' => 'Clermont-Ferrand');
$city_data[] = array('accid' => 'FRXX0121', 'name' => 'Gourdon');
$city_data[] = array('accid' => 'FRXX0122', 'name' => 'Millau');
$city_data[] = array('accid' => 'FRXX0123', 'name' => 'Montelimar');
$city_data[] = array('accid' => 'FRXX0124', 'name' => 'Embrun');
$city_data[] = array('accid' => 'FRXX0125', 'name' => 'Biarritz');
$city_data[] = array('accid' => 'FRXX0126', 'name' => 'Saint-Girons');
$city_data[] = array('accid' => 'FRXX0127', 'name' => 'Cap Cepet');
$city_data[] = array('accid' => 'FRXX0128', 'name' => 'Perpignan');
$city_data[] = array('accid' => 'FRXX0129', 'name' => 'Ajaccio');
$city_data[] = array('accid' => 'FRXX0130', 'name' => 'Bastia');
$city_data[] = array('accid' => 'FRXX0131', 'name' => 'Medoc');
$city_data[] = array('accid' => 'FRXX0132', 'name' => 'Biscay');
$city_data[] = array('accid' => 'FRXX0134', 'name' => 'Topla');
$city_data[] = array('accid' => 'FRXX0135', 'name' => 'Agen');
$city_data[] = array('accid' => 'FRXX0137', 'name' => 'Angers');
$city_data[] = array('accid' => 'FRXX0138', 'name' => 'Auch');
$city_data[] = array('accid' => 'FRXX0139', 'name' => 'Aurillac');
$city_data[] = array('accid' => 'FRXX0140', 'name' => 'Bergerac');
$city_data[] = array('accid' => 'FRXX0141', 'name' => 'Besancon');
$city_data[] = array('accid' => 'FRXX0142', 'name' => 'Bourg-Saint-Maurice');
$city_data[] = array('accid' => 'FRXX0143', 'name' => 'Briancon');
$city_data[] = array('accid' => 'FRXX0144', 'name' => 'Brive');
$city_data[] = array('accid' => 'FRXX0145', 'name' => 'Cambrai');
$city_data[] = array('accid' => 'FRXX0146', 'name' => 'Carpentras');
$city_data[] = array('accid' => 'FRXX0147', 'name' => 'Chambery');
$city_data[] = array('accid' => 'FRXX0148', 'name' => 'Cognac');
$city_data[] = array('accid' => 'FRXX0149', 'name' => 'Dax');
$city_data[] = array('accid' => 'FRXX0150', 'name' => 'Deauville');
$city_data[] = array('accid' => 'FRXX0151', 'name' => 'Dunkerque');
$city_data[] = array('accid' => 'FRXX0152', 'name' => 'Epinal');
$city_data[] = array('accid' => 'FRXX0153', 'name' => 'Grenoble');
$city_data[] = array('accid' => 'FRXX0154', 'name' => 'Hyeres');
$city_data[] = array('accid' => 'FRXX0155', 'name' => 'Ile De Batz');
$city_data[] = array('accid' => 'FRXX0156', 'name' => 'Ile Rousse');
$city_data[] = array('accid' => 'FRXX0157', 'name' => 'Istres');
$city_data[] = array('accid' => 'FRXX0158', 'name' => 'La Roche-sur-Yon');
$city_data[] = array('accid' => 'FRXX0159', 'name' => 'Laval');
$city_data[] = array('accid' => 'FRXX0160', 'name' => 'Le Touquet');
$city_data[] = array('accid' => 'FRXX0161', 'name' => 'Lons-le-Saunier');
$city_data[] = array('accid' => 'FRXX0162', 'name' => 'Mende');
$city_data[] = array('accid' => 'FRXX0163', 'name' => 'Mont-de-Marsan');
$city_data[] = array('accid' => 'FRXX0164', 'name' => 'Nevers');
$city_data[] = array('accid' => 'FRXX0165', 'name' => 'Nimes');
$city_data[] = array('accid' => 'FRXX0166', 'name' => 'Niort');
$city_data[] = array('accid' => 'FRXX0167', 'name' => 'Orange');
$city_data[] = array('accid' => 'FRXX0168', 'name' => 'Pau');
$city_data[] = array('accid' => 'FRXX0169', 'name' => 'Perigueux');
$city_data[] = array('accid' => 'FRXX0170', 'name' => 'Poitiers');
$city_data[] = array('accid' => 'FRXX0171', 'name' => 'Rodez');
$city_data[] = array('accid' => 'FRXX0172', 'name' => 'Solenzara');
$city_data[] = array('accid' => 'FRXX0173', 'name' => 'Saint-Dizier');
$city_data[] = array('accid' => 'FRXX0174', 'name' => 'Toul / Rosieres');
$city_data[] = array('accid' => 'FRXX0175', 'name' => 'Trappes');
$city_data[] = array('accid' => 'FRXX0176', 'name' => 'Vannes');
$city_data[] = array('accid' => 'FRXX0177', 'name' => 'Vichy');
$city_data[] = array('accid' => 'FRXX0178', 'name' => 'La Chiappa');
$city_data[] = array('accid' => 'FRXX0179', 'name' => 'La Coudre');
$city_data[] = array('accid' => 'FRXX0180', 'name' => 'Porquerolles');
$city_data[] = array('accid' => 'FRXX0181', 'name' => 'Landes');
$city_data[] = array('accid' => 'FRXX0200', 'name' => 'Creuse');
$city_data[] = array('accid' => 'FRXX0201', 'name' => 'Evry');
$city_data[] = array('accid' => 'FRXX0202', 'name' => 'Nanterre');
$city_data[] = array('accid' => 'FRXX0203', 'name' => 'Bar-le-Duc');
$city_data[] = array('accid' => 'FRXX0204', 'name' => 'Foix');
$city_data[] = array('accid' => 'FRXX0205', 'name' => 'Charleville-Mezieres');
$city_data[] = array('accid' => 'FRXX0206', 'name' => 'Laon');
$city_data[] = array('accid' => 'FRXX0207', 'name' => 'Alencon');
$city_data[] = array('accid' => 'FRXX0208', 'name' => 'Privas');
$city_data[] = array('accid' => 'FRXX0209', 'name' => 'Le Puy-en-Velay');
$city_data[] = array('accid' => 'FRXX0210', 'name' => 'Vesoul');
$city_data[] = array('accid' => 'FRXX0211', 'name' => 'Digne-les-Bains');
$city_data[] = array('accid' => 'FRXX0212', 'name' => 'Chamonix');
$city_data[] = array('accid' => 'FRXX0213', 'name' => 'Brides-les-Bains');
$city_data[] = array('accid' => 'FRXX0214', 'name' => 'La Grave');
$city_data[] = array('accid' => 'FRXX0215', 'name' => 'Saint-Tropez');
$city_data[] = array('accid' => 'FRXX0216', 'name' => 'Ancette');
$city_data[] = array('accid' => 'FRXX0217', 'name' => 'Bareges');
$city_data[] = array('accid' => 'FRXX0218', 'name' => 'Bois des Seignus');
$city_data[] = array('accid' => 'FRXX0219', 'name' => 'Bonneval-sur-Arc');
$city_data[] = array('accid' => 'FRXX0220', 'name' => 'Cauterets');
$city_data[] = array('accid' => 'FRXX0221', 'name' => 'Chedde');
$city_data[] = array('accid' => 'FRXX0222', 'name' => 'Clot Meyran');
$city_data[] = array('accid' => 'FRXX0223', 'name' => 'Crey-Rond');
$city_data[] = array('accid' => 'FRXX0224', 'name' => 'Dieppe');
$city_data[] = array('accid' => 'FRXX0225', 'name' => 'Favray');
$city_data[] = array('accid' => 'FRXX0226', 'name' => 'Foret de Risoul');
$city_data[] = array('accid' => 'FRXX0227', 'name' => 'Serre Chevalier');
$city_data[] = array('accid' => 'FRXX0228', 'name' => 'Hauteluce');
$city_data[] = array('accid' => 'FRXX0229', 'name' => 'Isola');
$city_data[] = array('accid' => 'FRXX0230', 'name' => 'L\'Alpe-d\'Huez');
$city_data[] = array('accid' => 'FRXX0231', 'name' => 'La Clusaz');
$city_data[] = array('accid' => 'FRXX0232', 'name' => 'La Gurraz');
$city_data[] = array('accid' => 'FRXX0233', 'name' => 'La Plagne');
$city_data[] = array('accid' => 'FRXX0234', 'name' => 'Lavalette');
$city_data[] = array('accid' => 'FRXX0235', 'name' => 'La Calvaire');
$city_data[] = array('accid' => 'FRXX0236', 'name' => 'Le Cugnon');
$city_data[] = array('accid' => 'FRXX0237', 'name' => 'Le Fey');
$city_data[] = array('accid' => 'FRXX0238', 'name' => 'Le Manchet');
$city_data[] = array('accid' => 'FRXX0239', 'name' => 'Le Peyrou');
$city_data[] = array('accid' => 'FRXX0240', 'name' => 'Le Truc');
$city_data[] = array('accid' => 'FRXX0241', 'name' => 'Les Freaux');
$city_data[] = array('accid' => 'FRXX0242', 'name' => 'Les Geymonds');
$city_data[] = array('accid' => 'FRXX0243', 'name' => 'Les Grands Vans');
$city_data[] = array('accid' => 'FRXX0244', 'name' => 'Les Ougiers');
$city_data[] = array('accid' => 'FRXX0245', 'name' => 'Megeve');
$city_data[] = array('accid' => 'FRXX0246', 'name' => 'Meribel');
$city_data[] = array('accid' => 'FRXX0247', 'name' => 'Montagne de Cherferie');
$city_data[] = array('accid' => 'FRXX0248', 'name' => 'Montagne de Mazeliere');
$city_data[] = array('accid' => 'FRXX0249', 'name' => 'Montgesin');
$city_data[] = array('accid' => 'FRXX0250', 'name' => 'Montvalezan-sur-Seez');
$city_data[] = array('accid' => 'FRXX0251', 'name' => 'Morzine');
$city_data[] = array('accid' => 'FRXX0252', 'name' => 'Orcieres');
$city_data[] = array('accid' => 'FRXX0253', 'name' => 'Pied Aigu');
$city_data[] = array('accid' => 'FRXX0254', 'name' => 'Pierre Besse');
$city_data[] = array('accid' => 'FRXX0255', 'name' => 'Pointe Turra');
$city_data[] = array('accid' => 'FRXX0256', 'name' => 'Pointe de Corbier');
$city_data[] = array('accid' => 'FRXX0257', 'name' => 'Pointe de l\' Eygliere');
$city_data[] = array('accid' => 'FRXX0258', 'name' => 'Roche');
$city_data[] = array('accid' => 'FRXX0259', 'name' => 'Rocher de l\' Homme');
$city_data[] = array('accid' => 'FRXX0260', 'name' => 'Roussis');
$city_data[] = array('accid' => 'FRXX0261', 'name' => 'Samoens');
$city_data[] = array('accid' => 'FRXX0262', 'name' => 'Seez');
$city_data[] = array('accid' => 'FRXX0263', 'name' => 'Tete de Viraysse');
$city_data[] = array('accid' => 'FRXX0264', 'name' => 'Torrent des Encombres');
$city_data[] = array('accid' => 'FRXX0265', 'name' => 'Tougnete');
$city_data[] = array('accid' => 'FRXX0266', 'name' => 'Vancroit');
$city_data[] = array('accid' => 'FRXX0267', 'name' => 'Vars');
$city_data[] = array('accid' => 'FRXX0268', 'name' => 'les Chozalets');
$city_data[] = array('accid' => 'FRXX0269', 'name' => 'Amiens');
$city_data[] = array('accid' => 'FRXX0270', 'name' => 'Avignon');
$city_data[] = array('accid' => 'FRXX0271', 'name' => 'Boulogne');
$city_data[] = array('accid' => 'FRXX0272', 'name' => 'Calais');
$city_data[] = array('accid' => 'FRXX0273', 'name' => 'La Seyne-sur-Mer');
$city_data[] = array('accid' => 'FRXX0274', 'name' => 'Saint-Etienne');
$city_data[] = array('accid' => 'FRXX0275', 'name' => 'Saint-Malo');
$city_data[] = array('accid' => 'FRXX0276', 'name' => 'Saint-Quentin');
$city_data[] = array('accid' => 'FRXX0277', 'name' => 'Tourcoing');
$city_data[] = array('accid' => 'FRXX0278', 'name' => 'Villeneuve-d\'Ascq');
$city_data[] = array('accid' => 'FRXX0279', 'name' => 'Marne-la-Vallee');
$city_data[] = array('accid' => 'FRXX0280', 'name' => 'Saint-Quentin-en-Yvelines');
$city_data[] = array('accid' => 'FRXX0281', 'name' => 'Boulogne-Billancourt');
$city_data[] = array('accid' => 'FRXX0282', 'name' => 'Argenteuil');
$city_data[] = array('accid' => 'FRXX0283', 'name' => 'Montreuil-sous-Bois');
$city_data[] = array('accid' => 'FRXX0284', 'name' => 'Creteil');
$city_data[] = array('accid' => 'FRXX0285', 'name' => 'Aulnay-sous-Bois');
$city_data[] = array('accid' => 'FRXX0286', 'name' => 'Vitry-sur-Seine');
$city_data[] = array('accid' => 'FRXX0287', 'name' => 'Colombes');
$city_data[] = array('accid' => 'FRXX0288', 'name' => 'Asnieres-sur-Seine');
$city_data[] = array('accid' => 'FRXX0289', 'name' => 'Rueil-Malmaison');
$city_data[] = array('accid' => 'FRXX0290', 'name' => 'Champigny-sur-Marne');
$city_data[] = array('accid' => 'FRXX0291', 'name' => 'Saint-Maur-des-Fosses');
$city_data[] = array('accid' => 'FRXX0292', 'name' => 'Courbevoie');
$city_data[] = array('accid' => 'FRXX0293', 'name' => 'Drancy');
$city_data[] = array('accid' => 'FRXX0294', 'name' => 'Antony');
$city_data[] = array('accid' => 'FRXX0295', 'name' => 'Neuilly-sur-Seine');
$city_data[] = array('accid' => 'FRXX0296', 'name' => 'Sarcelles');
$city_data[] = array('accid' => 'FRXX0297', 'name' => 'Cergy');
$city_data[] = array('accid' => 'FRXX0298', 'name' => 'Levallois-Perret');
$city_data[] = array('accid' => 'FRXX0299', 'name' => 'Evian');

?>