<?php

// City package for Italy

$city_name = 'Italy';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'ITXX0001', 'name' => 'Alcamo');
$city_data[] = array('accid' => 'ITXX0002', 'name' => 'Aversa');
$city_data[] = array('accid' => 'ITXX0003', 'name' => 'Bari');
$city_data[] = array('accid' => 'ITXX0004', 'name' => 'Barletta');
$city_data[] = array('accid' => 'ITXX0005', 'name' => 'Bergamo');
$city_data[] = array('accid' => 'ITXX0006', 'name' => 'Bologna');
$city_data[] = array('accid' => 'ITXX0007', 'name' => 'Bolzano');
$city_data[] = array('accid' => 'ITXX0008', 'name' => 'Brescia');
$city_data[] = array('accid' => 'ITXX0009', 'name' => 'Bronzolo');
$city_data[] = array('accid' => 'ITXX0010', 'name' => 'Cagliari');
$city_data[] = array('accid' => 'ITXX0011', 'name' => 'Carbonia');
$city_data[] = array('accid' => 'ITXX0012', 'name' => 'Carmagnola');
$city_data[] = array('accid' => 'ITXX0013', 'name' => 'Carpi');
$city_data[] = array('accid' => 'ITXX0014', 'name' => 'Caserta');
$city_data[] = array('accid' => 'ITXX0015', 'name' => 'Cassino');
$city_data[] = array('accid' => 'ITXX0016', 'name' => 'Castenaso');
$city_data[] = array('accid' => 'ITXX0017', 'name' => 'Catania');
$city_data[] = array('accid' => 'ITXX0018', 'name' => 'Chieti');
$city_data[] = array('accid' => 'ITXX0019', 'name' => 'Chioggia');
$city_data[] = array('accid' => 'ITXX0020', 'name' => 'Chivasso');
$city_data[] = array('accid' => 'ITXX0021', 'name' => 'Ciampino');
$city_data[] = array('accid' => 'ITXX0022', 'name' => 'Civitavecchia');
$city_data[] = array('accid' => 'ITXX0023', 'name' => 'Collegno');
$city_data[] = array('accid' => 'ITXX0024', 'name' => 'Como');
$city_data[] = array('accid' => 'ITXX0025', 'name' => 'Cremona');
$city_data[] = array('accid' => 'ITXX0026', 'name' => 'Empoli');
$city_data[] = array('accid' => 'ITXX0027', 'name' => 'Ferrara');
$city_data[] = array('accid' => 'ITXX0028', 'name' => 'Florence');
$city_data[] = array('accid' => 'ITXX0029', 'name' => 'Formia');
$city_data[] = array('accid' => 'ITXX0030', 'name' => 'Frosinone');
$city_data[] = array('accid' => 'ITXX0031', 'name' => 'Genoa');
$city_data[] = array('accid' => 'ITXX0032', 'name' => 'Imola');
$city_data[] = array('accid' => 'ITXX0033', 'name' => 'La Spezia');
$city_data[] = array('accid' => 'ITXX0034', 'name' => 'Laives');
$city_data[] = array('accid' => 'ITXX0035', 'name' => 'Lanciano');
$city_data[] = array('accid' => 'ITXX0036', 'name' => 'Livorno');
$city_data[] = array('accid' => 'ITXX0037', 'name' => 'Lucca');
$city_data[] = array('accid' => 'ITXX0038', 'name' => 'Marsala');
$city_data[] = array('accid' => 'ITXX0039', 'name' => 'Merano');
$city_data[] = array('accid' => 'ITXX0040', 'name' => 'Messina');
$city_data[] = array('accid' => 'ITXX0041', 'name' => 'Mestre');
$city_data[] = array('accid' => 'ITXX0042', 'name' => 'Milan');
$city_data[] = array('accid' => 'ITXX0043', 'name' => 'Modena');
$city_data[] = array('accid' => 'ITXX0044', 'name' => 'Mola di Bari');
$city_data[] = array('accid' => 'ITXX0045', 'name' => 'Molfetta');
$city_data[] = array('accid' => 'ITXX0046', 'name' => 'Moncalieri');
$city_data[] = array('accid' => 'ITXX0047', 'name' => 'Monopoli');
$city_data[] = array('accid' => 'ITXX0048', 'name' => 'Montesilvano');
$city_data[] = array('accid' => 'ITXX0049', 'name' => 'Monza');
$city_data[] = array('accid' => 'ITXX0050', 'name' => 'Moscufo');
$city_data[] = array('accid' => 'ITXX0051', 'name' => 'Muravera');
$city_data[] = array('accid' => 'ITXX0052', 'name' => 'Naples');
$city_data[] = array('accid' => 'ITXX0053', 'name' => 'Novara');
$city_data[] = array('accid' => 'ITXX0054', 'name' => 'Padova');
$city_data[] = array('accid' => 'ITXX0055', 'name' => 'Palermo');
$city_data[] = array('accid' => 'ITXX0056', 'name' => 'Palidoro');
$city_data[] = array('accid' => 'ITXX0057', 'name' => 'Pescara');
$city_data[] = array('accid' => 'ITXX0058', 'name' => 'Piacenza');
$city_data[] = array('accid' => 'ITXX0059', 'name' => 'Pisa');
$city_data[] = array('accid' => 'ITXX0060', 'name' => 'Poggibonsi');
$city_data[] = array('accid' => 'ITXX0061', 'name' => 'Pompei');
$city_data[] = array('accid' => 'ITXX0062', 'name' => 'Prato');
$city_data[] = array('accid' => 'ITXX0063', 'name' => 'Quartu Sant\'Elena');
$city_data[] = array('accid' => 'ITXX0064', 'name' => 'Rapallo');
$city_data[] = array('accid' => 'ITXX0065', 'name' => 'Reggio nell\'Emilia');
$city_data[] = array('accid' => 'ITXX0066', 'name' => 'Rivoli');
$city_data[] = array('accid' => 'ITXX0067', 'name' => 'Rome');
$city_data[] = array('accid' => 'ITXX0068', 'name' => 'Rovigo');
$city_data[] = array('accid' => 'ITXX0069', 'name' => 'Salerno');
$city_data[] = array('accid' => 'ITXX0070', 'name' => 'San Remo');
$city_data[] = array('accid' => 'ITXX0071', 'name' => 'Savona');
$city_data[] = array('accid' => 'ITXX0072', 'name' => 'Siena');
$city_data[] = array('accid' => 'ITXX0073', 'name' => 'Sorrento');
$city_data[] = array('accid' => 'ITXX0074', 'name' => 'Terni');
$city_data[] = array('accid' => 'ITXX0075', 'name' => 'Tivoli');
$city_data[] = array('accid' => 'ITXX0076', 'name' => 'Torre del Greco');
$city_data[] = array('accid' => 'ITXX0077', 'name' => 'Trapani');
$city_data[] = array('accid' => 'ITXX0078', 'name' => 'Trento');
$city_data[] = array('accid' => 'ITXX0079', 'name' => 'Treviso');
$city_data[] = array('accid' => 'ITXX0080', 'name' => 'Trieste');
$city_data[] = array('accid' => 'ITXX0081', 'name' => 'Turin');
$city_data[] = array('accid' => 'ITXX0082', 'name' => 'Varese');
$city_data[] = array('accid' => 'ITXX0083', 'name' => 'Vatican City');
$city_data[] = array('accid' => 'ITXX0084', 'name' => 'Venaria');
$city_data[] = array('accid' => 'ITXX0085', 'name' => 'Venice');
$city_data[] = array('accid' => 'ITXX0086', 'name' => 'Ventimiglia');
$city_data[] = array('accid' => 'ITXX0087', 'name' => 'Verona');
$city_data[] = array('accid' => 'ITXX0088', 'name' => 'Vicenza');
$city_data[] = array('accid' => 'ITXX0089', 'name' => 'Viterbo');
$city_data[] = array('accid' => 'ITXX0090', 'name' => 'Milano/Linate');
$city_data[] = array('accid' => 'ITXX0091', 'name' => 'Verona/Villafranca');
$city_data[] = array('accid' => 'ITXX0092', 'name' => 'Capo Mele');
$city_data[] = array('accid' => 'ITXX0093', 'name' => 'Grosseto');
$city_data[] = array('accid' => 'ITXX0094', 'name' => 'Amendola');
$city_data[] = array('accid' => 'ITXX0095', 'name' => 'Capo Palinuro');
$city_data[] = array('accid' => 'ITXX0096', 'name' => 'Brindisi');
$city_data[] = array('accid' => 'ITXX0097', 'name' => 'Reggio Calabria');
$city_data[] = array('accid' => 'ITXX0100', 'name' => 'Agnone');
$city_data[] = array('accid' => 'ITXX0101', 'name' => 'Alghero');
$city_data[] = array('accid' => 'ITXX0102', 'name' => 'Ancona/Falconara');
$city_data[] = array('accid' => 'ITXX0103', 'name' => 'Aosta');
$city_data[] = array('accid' => 'ITXX0104', 'name' => 'Ascoli Piceno');
$city_data[] = array('accid' => 'ITXX0105', 'name' => 'L\'Aquila');
$city_data[] = array('accid' => 'ITXX0106', 'name' => 'Alessandria');
$city_data[] = array('accid' => 'ITXX0107', 'name' => 'Breuil-cervina');
$city_data[] = array('accid' => 'ITXX0108', 'name' => 'Boiano');
$city_data[] = array('accid' => 'ITXX0109', 'name' => 'Broni');
$city_data[] = array('accid' => 'ITXX0110', 'name' => 'Brunico');
$city_data[] = array('accid' => 'ITXX0111', 'name' => 'Caltanissetta');
$city_data[] = array('accid' => 'ITXX0112', 'name' => 'Campobasso');
$city_data[] = array('accid' => 'ITXX0113', 'name' => 'Coni');
$city_data[] = array('accid' => 'ITXX0114', 'name' => 'Castelvetrano');
$city_data[] = array('accid' => 'ITXX0115', 'name' => 'Cortina d\'Ampezzo');
$city_data[] = array('accid' => 'ITXX0116', 'name' => 'Cantanzaro');
$city_data[] = array('accid' => 'ITXX0117', 'name' => 'Domodossola');
$city_data[] = array('accid' => 'ITXX0118', 'name' => 'Donnaz');
$city_data[] = array('accid' => 'ITXX0119', 'name' => 'Foggia');
$city_data[] = array('accid' => 'ITXX0120', 'name' => 'Frontone');
$city_data[] = array('accid' => 'ITXX0121', 'name' => 'Gorizia');
$city_data[] = array('accid' => 'ITXX0122', 'name' => 'Gualdo Tadino');
$city_data[] = array('accid' => 'ITXX0123', 'name' => 'Laurino');
$city_data[] = array('accid' => 'ITXX0124', 'name' => 'Lecce');
$city_data[] = array('accid' => 'ITXX0125', 'name' => 'Liante/Novi Ligu');
$city_data[] = array('accid' => 'ITXX0126', 'name' => 'Loano');
$city_data[] = array('accid' => 'ITXX0127', 'name' => 'Lavello');
$city_data[] = array('accid' => 'ITXX0128', 'name' => 'Marina Di Leuca');
$city_data[] = array('accid' => 'ITXX0129', 'name' => 'Matelica');
$city_data[] = array('accid' => 'ITXX0130', 'name' => 'Monte St Angelo');
$city_data[] = array('accid' => 'ITXX0131', 'name' => 'Nuoro');
$city_data[] = array('accid' => 'ITXX0132', 'name' => 'Orvieto');
$city_data[] = array('accid' => 'ITXX0133', 'name' => 'Oulx');
$city_data[] = array('accid' => 'ITXX0134', 'name' => 'Passo Della Cisa');
$city_data[] = array('accid' => 'ITXX0135', 'name' => 'Pordenone');
$city_data[] = array('accid' => 'ITXX0136', 'name' => 'Perugia');
$city_data[] = array('accid' => 'ITXX0137', 'name' => 'Prato Allo Stelv');
$city_data[] = array('accid' => 'ITXX0138', 'name' => 'Pescina');
$city_data[] = array('accid' => 'ITXX0139', 'name' => 'Potenza');
$city_data[] = array('accid' => 'ITXX0140', 'name' => 'Parma');
$city_data[] = array('accid' => 'ITXX0141', 'name' => 'Pesaro');
$city_data[] = array('accid' => 'ITXX0142', 'name' => 'Porto Civitanova');
$city_data[] = array('accid' => 'ITXX0143', 'name' => 'Policoro');
$city_data[] = array('accid' => 'ITXX0144', 'name' => 'Porassey');
$city_data[] = array('accid' => 'ITXX0145', 'name' => 'Pizzoferrato');
$city_data[] = array('accid' => 'ITXX0146', 'name' => 'Riccia');
$city_data[] = array('accid' => 'ITXX0147', 'name' => 'Reggio Di Calabr');
$city_data[] = array('accid' => 'ITXX0148', 'name' => 'Rimini');
$city_data[] = array('accid' => 'ITXX0149', 'name' => 'Rieti');
$city_data[] = array('accid' => 'ITXX0150', 'name' => 'Ravenna');
$city_data[] = array('accid' => 'ITXX0151', 'name' => 'San Marco Dei Ca');
$city_data[] = array('accid' => 'ITXX0152', 'name' => 'Santa Caterina');
$city_data[] = array('accid' => 'ITXX0153', 'name' => 'Spoleto');
$city_data[] = array('accid' => 'ITXX0155', 'name' => 'Sassari');
$city_data[] = array('accid' => 'ITXX0156', 'name' => 'Syrakus');
$city_data[] = array('accid' => 'ITXX0157', 'name' => 'Spezzano');
$city_data[] = array('accid' => 'ITXX0158', 'name' => 'Taranto');
$city_data[] = array('accid' => 'ITXX0159', 'name' => 'Terracina');
$city_data[] = array('accid' => 'ITXX0160', 'name' => 'Teramo');
$city_data[] = array('accid' => 'ITXX0161', 'name' => 'Tirano');
$city_data[] = array('accid' => 'ITXX0162', 'name' => 'Termoli');
$city_data[] = array('accid' => 'ITXX0163', 'name' => 'Udine');
$city_data[] = array('accid' => 'ITXX0164', 'name' => 'Urbania');
$city_data[] = array('accid' => 'ITXX0165', 'name' => 'Vasto');
$city_data[] = array('accid' => 'ITXX0166', 'name' => 'Vibo Valentia');
$city_data[] = array('accid' => 'ITXX0167', 'name' => 'Varese Ligure');
$city_data[] = array('accid' => 'ITXX0168', 'name' => 'Villa Santina');
$city_data[] = array('accid' => 'ITXX0169', 'name' => 'Vitoria Veneto');

?>