<?php

// City package for Spain

$city_name = 'Spain';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'SPXX0001', 'name' => 'Alcala de Guadaira');
$city_data[] = array('accid' => 'SPXX0002', 'name' => 'Alcala de Henares');
$city_data[] = array('accid' => 'SPXX0003', 'name' => 'Alcazar de San Juan');
$city_data[] = array('accid' => 'SPXX0004', 'name' => 'Alcira');
$city_data[] = array('accid' => 'SPXX0005', 'name' => 'Alcobendas');
$city_data[] = array('accid' => 'SPXX0006', 'name' => 'Alcorcon');
$city_data[] = array('accid' => 'SPXX0007', 'name' => 'Alcudia');
$city_data[] = array('accid' => 'SPXX0008', 'name' => 'Alicante');
$city_data[] = array('accid' => 'SPXX0009', 'name' => 'Almeria');
$city_data[] = array('accid' => 'SPXX0010', 'name' => 'Aranjuez');
$city_data[] = array('accid' => 'SPXX0011', 'name' => 'Arizgoiti');
$city_data[] = array('accid' => 'SPXX0012', 'name' => 'Arrecife');
$city_data[] = array('accid' => 'SPXX0013', 'name' => 'Badalona');
$city_data[] = array('accid' => 'SPXX0014', 'name' => 'Baracaldo');
$city_data[] = array('accid' => 'SPXX0015', 'name' => 'Barcelona');
$city_data[] = array('accid' => 'SPXX0016', 'name' => 'Bilbao');
$city_data[] = array('accid' => 'SPXX0017', 'name' => 'Cadiz');
$city_data[] = array('accid' => 'SPXX0018', 'name' => 'Camas');
$city_data[] = array('accid' => 'SPXX0019', 'name' => 'Cartagena');
$city_data[] = array('accid' => 'SPXX0020', 'name' => 'Castelldefels');
$city_data[] = array('accid' => 'SPXX0021', 'name' => 'Castellon de la Plana');
$city_data[] = array('accid' => 'SPXX0022', 'name' => 'Ceuta');
$city_data[] = array('accid' => 'SPXX0023', 'name' => 'Ciudad Real');
$city_data[] = array('accid' => 'SPXX0024', 'name' => 'Cordova');
$city_data[] = array('accid' => 'SPXX0025', 'name' => 'Cuarte de Huerva');
$city_data[] = array('accid' => 'SPXX0026', 'name' => 'Donostia-San Sebastian');
$city_data[] = array('accid' => 'SPXX0027', 'name' => 'Dos Hermanas');
$city_data[] = array('accid' => 'SPXX0028', 'name' => 'Ecija');
$city_data[] = array('accid' => 'SPXX0029', 'name' => 'Eibar');
$city_data[] = array('accid' => 'SPXX0030', 'name' => 'El Alquian');
$city_data[] = array('accid' => 'SPXX0031', 'name' => 'El Astillero');
$city_data[] = array('accid' => 'SPXX0032', 'name' => 'El Ejido');
$city_data[] = array('accid' => 'SPXX0033', 'name' => 'El Prat de Llobregat');
$city_data[] = array('accid' => 'SPXX0034', 'name' => 'El Puerto de Santa Maria');
$city_data[] = array('accid' => 'SPXX0035', 'name' => 'Elche');
$city_data[] = array('accid' => 'SPXX0036', 'name' => 'Fuenlabrada');
$city_data[] = array('accid' => 'SPXX0037', 'name' => 'Gandia');
$city_data[] = array('accid' => 'SPXX0038', 'name' => 'Gerona');
$city_data[] = array('accid' => 'SPXX0039', 'name' => 'Getafe');
$city_data[] = array('accid' => 'SPXX0040', 'name' => 'Granada');
$city_data[] = array('accid' => 'SPXX0041', 'name' => 'Guadalajara');
$city_data[] = array('accid' => 'SPXX0042', 'name' => 'Guadix');
$city_data[] = array('accid' => 'SPXX0043', 'name' => 'Huesca');
$city_data[] = array('accid' => 'SPXX0044', 'name' => 'Ibiza');
$city_data[] = array('accid' => 'SPXX0045', 'name' => 'Jaen');
$city_data[] = array('accid' => 'SPXX0046', 'name' => 'Jerez de la Frontera');
$city_data[] = array('accid' => 'SPXX0047', 'name' => 'Las Palmas');
$city_data[] = array('accid' => 'SPXX0048', 'name' => 'Leganes');
$city_data[] = array('accid' => 'SPXX0049', 'name' => 'L\'Hospitalet de Llobregat');
$city_data[] = array('accid' => 'SPXX0050', 'name' => 'Madrid');
$city_data[] = array('accid' => 'SPXX0051', 'name' => 'Mahon');
$city_data[] = array('accid' => 'SPXX0052', 'name' => 'Malaga');
$city_data[] = array('accid' => 'SPXX0053', 'name' => 'Manacor');
$city_data[] = array('accid' => 'SPXX0054', 'name' => 'Marbella');
$city_data[] = array('accid' => 'SPXX0055', 'name' => 'Mataro');
$city_data[] = array('accid' => 'SPXX0056', 'name' => 'Moron de la Frontera');
$city_data[] = array('accid' => 'SPXX0057', 'name' => 'Mostoles');
$city_data[] = array('accid' => 'SPXX0058', 'name' => 'Motril');
$city_data[] = array('accid' => 'SPXX0059', 'name' => 'Murcia');
$city_data[] = array('accid' => 'SPXX0060', 'name' => 'Muriedas');
$city_data[] = array('accid' => 'SPXX0061', 'name' => 'Palma de Mallorca');
$city_data[] = array('accid' => 'SPXX0062', 'name' => 'Paterna');
$city_data[] = array('accid' => 'SPXX0063', 'name' => 'Pozuelo de Alarcon');
$city_data[] = array('accid' => 'SPXX0064', 'name' => 'Premia de Mar');
$city_data[] = array('accid' => 'SPXX0065', 'name' => 'Puerto del Rosario');
$city_data[] = array('accid' => 'SPXX0066', 'name' => 'Sabadell');
$city_data[] = array('accid' => 'SPXX0067', 'name' => 'San Antonio Abad');
$city_data[] = array('accid' => 'SPXX0068', 'name' => 'Sanlucar de Barrameda');
$city_data[] = array('accid' => 'SPXX0069', 'name' => 'Santa Coloma de Gramanet');
$city_data[] = array('accid' => 'SPXX0070', 'name' => 'Santa Cruz de Tenerife');
$city_data[] = array('accid' => 'SPXX0071', 'name' => 'Santa Pola');
$city_data[] = array('accid' => 'SPXX0072', 'name' => 'Santander');
$city_data[] = array('accid' => 'SPXX0073', 'name' => 'Sestao');
$city_data[] = array('accid' => 'SPXX0074', 'name' => 'Seville');
$city_data[] = array('accid' => 'SPXX0075', 'name' => 'Talavera de la Reina');
$city_data[] = array('accid' => 'SPXX0076', 'name' => 'Tarragona');
$city_data[] = array('accid' => 'SPXX0077', 'name' => 'Toledo');
$city_data[] = array('accid' => 'SPXX0078', 'name' => 'Torrelavega');
$city_data[] = array('accid' => 'SPXX0079', 'name' => 'Tudela');
$city_data[] = array('accid' => 'SPXX0080', 'name' => 'Utebo');
$city_data[] = array('accid' => 'SPXX0081', 'name' => 'Utrera');
$city_data[] = array('accid' => 'SPXX0082', 'name' => 'Valencia');
$city_data[] = array('accid' => 'SPXX0083', 'name' => 'Vicar');
$city_data[] = array('accid' => 'SPXX0084', 'name' => 'Vigo');
$city_data[] = array('accid' => 'SPXX0085', 'name' => 'Vilanova I La Geltru');
$city_data[] = array('accid' => 'SPXX0086', 'name' => 'Zaragoza');
$city_data[] = array('accid' => 'SPXX0087', 'name' => 'Agreda');
$city_data[] = array('accid' => 'SPXX0088', 'name' => 'Algeciras');
$city_data[] = array('accid' => 'SPXX0089', 'name' => 'Antequera');
$city_data[] = array('accid' => 'SPXX0090', 'name' => 'Aracena');
$city_data[] = array('accid' => 'SPXX0091', 'name' => 'Armilla');
$city_data[] = array('accid' => 'SPXX0092', 'name' => 'Ayamonte');
$city_data[] = array('accid' => 'SPXX0093', 'name' => 'Benasque');
$city_data[] = array('accid' => 'SPXX0094', 'name' => 'Buitrago');
$city_data[] = array('accid' => 'SPXX0095', 'name' => 'Calatayud');
$city_data[] = array('accid' => 'SPXX0098', 'name' => 'Cazorla');
$city_data[] = array('accid' => 'SPXX0100', 'name' => 'Cuenca');
$city_data[] = array('accid' => 'SPXX0101', 'name' => 'Durango');
$city_data[] = array('accid' => 'SPXX0102', 'name' => 'Elizondo');
$city_data[] = array('accid' => 'SPXX0104', 'name' => 'Huescar');
$city_data[] = array('accid' => 'SPXX0105', 'name' => 'Jerez');
$city_data[] = array('accid' => 'SPXX0106', 'name' => 'Laguardia');
$city_data[] = array('accid' => 'SPXX0109', 'name' => 'Lorca');
$city_data[] = array('accid' => 'SPXX0110', 'name' => 'Lugo');
$city_data[] = array('accid' => 'SPXX0111', 'name' => 'Merida');
$city_data[] = array('accid' => 'SPXX0112', 'name' => 'Montalban');
$city_data[] = array('accid' => 'SPXX0113', 'name' => 'Navacerrada');
$city_data[] = array('accid' => 'SPXX0114', 'name' => 'Pamplona');
$city_data[] = array('accid' => 'SPXX0115', 'name' => 'Pontevedra');
$city_data[] = array('accid' => 'SPXX0116', 'name' => 'Priego');
$city_data[] = array('accid' => 'SPXX0117', 'name' => 'Requena');
$city_data[] = array('accid' => 'SPXX0118', 'name' => 'Reus');
$city_data[] = array('accid' => 'SPXX0119', 'name' => 'Riano');
$city_data[] = array('accid' => 'SPXX0120', 'name' => 'Riaza');
$city_data[] = array('accid' => 'SPXX0121', 'name' => 'Ronda');
$city_data[] = array('accid' => 'SPXX0122', 'name' => 'Sahagun');
$city_data[] = array('accid' => 'SPXX0126', 'name' => 'Tordesillas');
$city_data[] = array('accid' => 'SPXX0133', 'name' => 'Alcoi');
$city_data[] = array('accid' => 'SPXX0135', 'name' => 'Arenas De San Pedro');
$city_data[] = array('accid' => 'SPXX0137', 'name' => 'Blanes');
$city_data[] = array('accid' => 'SPXX0138', 'name' => 'Calahorra');
$city_data[] = array('accid' => 'SPXX0139', 'name' => 'Cazalla De La Sierra');
$city_data[] = array('accid' => 'SPXX0140', 'name' => 'Ciudad Rodrigo');
$city_data[] = array('accid' => 'SPXX0141', 'name' => 'Figueras');
$city_data[] = array('accid' => 'SPXX0142', 'name' => 'Fuerteventura (La Oliva)');
$city_data[] = array('accid' => 'SPXX0143', 'name' => 'Girona');
$city_data[] = array('accid' => 'SPXX0144', 'name' => 'Gomera (San Sebastian)');
$city_data[] = array('accid' => 'SPXX0145', 'name' => 'Hellin');
$city_data[] = array('accid' => 'SPXX0146', 'name' => 'Hinojosa Del Duque');
$city_data[] = array('accid' => 'SPXX0147', 'name' => 'Lalin');
$city_data[] = array('accid' => 'SPXX0152', 'name' => 'Miranda De Ebro');
$city_data[] = array('accid' => 'SPXX0153', 'name' => 'Molina De Aragon');
$city_data[] = array('accid' => 'SPXX0154', 'name' => 'Morforte De Lemos');
$city_data[] = array('accid' => 'SPXX0157', 'name' => 'Pollensa');
$city_data[] = array('accid' => 'SPXX0158', 'name' => 'Puerto De La Cruz');
$city_data[] = array('accid' => 'SPXX0165', 'name' => 'Benidorm');
$city_data[] = array('accid' => 'SPXX0166', 'name' => 'Covadonga');
$city_data[] = array('accid' => 'SPXX0171', 'name' => 'Gran Canaria Sur');
$city_data[] = array('accid' => 'SPXX0172', 'name' => 'Isla de Alboran');
$city_data[] = array('accid' => 'SPXX0173', 'name' => 'Langreo');
$city_data[] = array('accid' => 'SPXX0175', 'name' => 'Lleida');
$city_data[] = array('accid' => 'SPXX0176', 'name' => 'Manzaneda');
$city_data[] = array('accid' => 'SPXX0177', 'name' => 'Pajares');
$city_data[] = array('accid' => 'SPXX0178', 'name' => 'Potocolom');
$city_data[] = array('accid' => 'SPXX0180', 'name' => 'Reinosa');
$city_data[] = array('accid' => 'SPXX0181', 'name' => 'Renteria');
$city_data[] = array('accid' => 'SPXX0182', 'name' => 'Salas De Los Infantes');
$city_data[] = array('accid' => 'SPXX0183', 'name' => 'Salou');
$city_data[] = array('accid' => 'SPXX0187', 'name' => 'Urbion-Ventrosa');
$city_data[] = array('accid' => 'SPXX0188', 'name' => 'Xativa');
$city_data[] = array('accid' => 'SPXX0189', 'name' => 'La Coruna');
$city_data[] = array('accid' => 'SPXX0190', 'name' => 'Oviedo');
$city_data[] = array('accid' => 'SPXX0191', 'name' => 'San Sebastian');
$city_data[] = array('accid' => 'SPXX0192', 'name' => 'Leon/Virgen Del Camino');
$city_data[] = array('accid' => 'SPXX0193', 'name' => 'Burgos');
$city_data[] = array('accid' => 'SPXX0194', 'name' => 'Logrono/Agoncillo');
$city_data[] = array('accid' => 'SPXX0195', 'name' => 'Valladolid');
$city_data[] = array('accid' => 'SPXX0196', 'name' => 'Salamanca');
$city_data[] = array('accid' => 'SPXX0197', 'name' => 'Albacete/Los Llanos');
$city_data[] = array('accid' => 'SPXX0198', 'name' => 'Badajoz/Talavera La Real');
$city_data[] = array('accid' => 'SPXX0200', 'name' => 'Granada/Aeropuerto');
$city_data[] = array('accid' => 'SPXX0201', 'name' => 'Las Palmas De Gran Canaria/Gando');
$city_data[] = array('accid' => 'SPXX0202', 'name' => 'Asturias/Aviles');
$city_data[] = array('accid' => 'SPXX0203', 'name' => 'Badajoz');
$city_data[] = array('accid' => 'SPXX0204', 'name' => 'Caceres');
$city_data[] = array('accid' => 'SPXX0205', 'name' => 'Calamocha');
$city_data[] = array('accid' => 'SPXX0206', 'name' => 'Hierro Island');
$city_data[] = array('accid' => 'SPXX0207', 'name' => 'La Palma Islan');
$city_data[] = array('accid' => 'SPXX0208', 'name' => 'Santiago Compost');
$city_data[] = array('accid' => 'SPXX0209', 'name' => 'Tortosa');
$city_data[] = array('accid' => 'SPXX0210', 'name' => 'Tenerife/Sur Re');
$city_data[] = array('accid' => 'SPXX0211', 'name' => 'Viso Del Marques');
$city_data[] = array('accid' => 'SPXX0220', 'name' => 'Cordoba');
$city_data[] = array('accid' => 'SPXX0222', 'name' => 'Gijon');
$city_data[] = array('accid' => 'SPXX0223', 'name' => 'Orense');
$city_data[] = array('accid' => 'SPXX0224', 'name' => 'Vitoria');
$city_data[] = array('accid' => 'SPXX0225', 'name' => 'Huelva');
$city_data[] = array('accid' => 'SPXX0226', 'name' => 'Melilla');
$city_data[] = array('accid' => 'SPXX0227', 'name' => 'Segovia');
$city_data[] = array('accid' => 'SPXX0228', 'name' => 'Palencia');
$city_data[] = array('accid' => 'SPXX0229', 'name' => 'Zamora');
$city_data[] = array('accid' => 'SPXX0230', 'name' => 'Teruel');
$city_data[] = array('accid' => 'SPXX0231', 'name' => 'Avila');
$city_data[] = array('accid' => 'SPXX0233', 'name' => 'Sierra Nevada');
$city_data[] = array('accid' => 'SPXX0234', 'name' => 'Montmelo');
$city_data[] = array('accid' => 'SPXX0235', 'name' => 'Galdar');
$city_data[] = array('accid' => 'SPXX0236', 'name' => 'Boi Taull');
$city_data[] = array('accid' => 'SPXX0237', 'name' => 'Tarifa');
$city_data[] = array('accid' => 'SPXX0238', 'name' => 'Gran Canaria');
$city_data[] = array('accid' => 'SPXX0239', 'name' => 'Lanzarote');

?>