<?php

// City package for United Kingdom

$city_name = 'United Kingdom';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'UKXX0001', 'name' => 'Aberdeen');
$city_data[] = array('accid' => 'UKXX0002', 'name' => 'Abingdon');
$city_data[] = array('accid' => 'UKXX0003', 'name' => 'Airdrie');
$city_data[] = array('accid' => 'UKXX0004', 'name' => 'Altrincham');
$city_data[] = array('accid' => 'UKXX0005', 'name' => 'Ashford');
$city_data[] = array('accid' => 'UKXX0006', 'name' => 'Ayr');
$city_data[] = array('accid' => 'UKXX0007', 'name' => 'Banchory');
$city_data[] = array('accid' => 'UKXX0008', 'name' => 'Bangor');
$city_data[] = array('accid' => 'UKXX0009', 'name' => 'Barnsley');
$city_data[] = array('accid' => 'UKXX0010', 'name' => 'Barry');
$city_data[] = array('accid' => 'UKXX0011', 'name' => 'Basingstoke');
$city_data[] = array('accid' => 'UKXX0012', 'name' => 'Bath');
$city_data[] = array('accid' => 'UKXX0013', 'name' => 'Batley');
$city_data[] = array('accid' => 'UKXX0014', 'name' => 'Bedford');
$city_data[] = array('accid' => 'UKXX0015', 'name' => 'Belfast');
$city_data[] = array('accid' => 'UKXX0016', 'name' => 'Bellshill');
$city_data[] = array('accid' => 'UKXX0017', 'name' => 'Birkenhead');
$city_data[] = array('accid' => 'UKXX0018', 'name' => 'Birmingham');
$city_data[] = array('accid' => 'UKXX0019', 'name' => 'Blackpool');
$city_data[] = array('accid' => 'UKXX0020', 'name' => 'Bolton');
$city_data[] = array('accid' => 'UKXX0021', 'name' => 'Bournemouth');
$city_data[] = array('accid' => 'UKXX0022', 'name' => 'Bracknell');
$city_data[] = array('accid' => 'UKXX0023', 'name' => 'Bradford');
$city_data[] = array('accid' => 'UKXX0024', 'name' => 'Bridlington');
$city_data[] = array('accid' => 'UKXX0025', 'name' => 'Bristol');
$city_data[] = array('accid' => 'UKXX0026', 'name' => 'Bromsgrove');
$city_data[] = array('accid' => 'UKXX0027', 'name' => 'Burton upon Trent');
$city_data[] = array('accid' => 'UKXX0028', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'UKXX0029', 'name' => 'Canterbury');
$city_data[] = array('accid' => 'UKXX0030', 'name' => 'Cardiff');
$city_data[] = array('accid' => 'UKXX0031', 'name' => 'Chelmsford');
$city_data[] = array('accid' => 'UKXX0032', 'name' => 'Cheltenham');
$city_data[] = array('accid' => 'UKXX0033', 'name' => 'Chester');
$city_data[] = array('accid' => 'UKXX0034', 'name' => 'Chesterfield');
$city_data[] = array('accid' => 'UKXX0035', 'name' => 'Clydebank');
$city_data[] = array('accid' => 'UKXX0036', 'name' => 'Coatbridge');
$city_data[] = array('accid' => 'UKXX0037', 'name' => 'Colchester');
$city_data[] = array('accid' => 'UKXX0038', 'name' => 'Coventry');
$city_data[] = array('accid' => 'UKXX0039', 'name' => 'Dalkeith');
$city_data[] = array('accid' => 'UKXX0040', 'name' => 'Derby');
$city_data[] = array('accid' => 'UKXX0041', 'name' => 'Doncaster');
$city_data[] = array('accid' => 'UKXX0042', 'name' => 'Dover');
$city_data[] = array('accid' => 'UKXX0043', 'name' => 'Dronfield');
$city_data[] = array('accid' => 'UKXX0044', 'name' => 'Dudley');
$city_data[] = array('accid' => 'UKXX0045', 'name' => 'Dundee');
$city_data[] = array('accid' => 'UKXX0046', 'name' => 'Dunfermline');
$city_data[] = array('accid' => 'UKXX0047', 'name' => 'Durham');
$city_data[] = array('accid' => 'UKXX0048', 'name' => 'Dyce');
$city_data[] = array('accid' => 'UKXX0049', 'name' => 'East Kilbride');
$city_data[] = array('accid' => 'UKXX0050', 'name' => 'East Midlands');
$city_data[] = array('accid' => 'UKXX0051', 'name' => 'Eastleigh');
$city_data[] = array('accid' => 'UKXX0052', 'name' => 'Edinburgh');
$city_data[] = array('accid' => 'UKXX0053', 'name' => 'Ellon');
$city_data[] = array('accid' => 'UKXX0054', 'name' => 'Exeter');
$city_data[] = array('accid' => 'UKXX0055', 'name' => 'Falkirk');
$city_data[] = array('accid' => 'UKXX0056', 'name' => 'Fareham');
$city_data[] = array('accid' => 'UKXX0057', 'name' => 'Farnborough');
$city_data[] = array('accid' => 'UKXX0058', 'name' => 'Folkestone');
$city_data[] = array('accid' => 'UKXX0059', 'name' => 'Foveran');
$city_data[] = array('accid' => 'UKXX0060', 'name' => 'Gateshead');
$city_data[] = array('accid' => 'UKXX0061', 'name' => 'Glasgow');
$city_data[] = array('accid' => 'UKXX0062', 'name' => 'Gloucester');
$city_data[] = array('accid' => 'UKXX0063', 'name' => 'Great Yarmouth');
$city_data[] = array('accid' => 'UKXX0064', 'name' => 'Grimsby');
$city_data[] = array('accid' => 'UKXX0065', 'name' => 'Guernsey Island');
$city_data[] = array('accid' => 'UKXX0066', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'UKXX0067', 'name' => 'Hartlepool');
$city_data[] = array('accid' => 'UKXX0068', 'name' => 'Havant');
$city_data[] = array('accid' => 'UKXX0069', 'name' => 'Hounslow');
$city_data[] = array('accid' => 'UKXX0070', 'name' => 'Huddersfield');
$city_data[] = array('accid' => 'UKXX0071', 'name' => 'Inverurie');
$city_data[] = array('accid' => 'UKXX0072', 'name' => 'Ipswich');
$city_data[] = array('accid' => 'UKXX0073', 'name' => 'Kidderminster');
$city_data[] = array('accid' => 'UKXX0074', 'name' => 'Kilmarnock');
$city_data[] = array('accid' => 'UKXX0075', 'name' => 'Kingston upon Hull');
$city_data[] = array('accid' => 'UKXX0076', 'name' => 'Kingswood');
$city_data[] = array('accid' => 'UKXX0077', 'name' => 'Larne');
$city_data[] = array('accid' => 'UKXX0078', 'name' => 'Leeds');
$city_data[] = array('accid' => 'UKXX0079', 'name' => 'Leicester');
$city_data[] = array('accid' => 'UKXX0080', 'name' => 'Leith');
$city_data[] = array('accid' => 'UKXX0081', 'name' => 'Lerwick');
$city_data[] = array('accid' => 'UKXX0082', 'name' => 'Lisburn');
$city_data[] = array('accid' => 'UKXX0083', 'name' => 'Liverpool');
$city_data[] = array('accid' => 'UKXX0084', 'name' => 'Livingston');
$city_data[] = array('accid' => 'UKXX0085', 'name' => 'London');
$city_data[] = array('accid' => 'UKXX0086', 'name' => 'Londonderry');
$city_data[] = array('accid' => 'UKXX0087', 'name' => 'Long Eaton');
$city_data[] = array('accid' => 'UKXX0088', 'name' => 'Luton');
$city_data[] = array('accid' => 'UKXX0089', 'name' => 'MacClesfield');
$city_data[] = array('accid' => 'UKXX0090', 'name' => 'Maidenhead');
$city_data[] = array('accid' => 'UKXX0091', 'name' => 'Maidstone');
$city_data[] = array('accid' => 'UKXX0092', 'name' => 'Manchester');
$city_data[] = array('accid' => 'UKXX0093', 'name' => 'Middlesbrough');
$city_data[] = array('accid' => 'UKXX0094', 'name' => 'Mildenhall');
$city_data[] = array('accid' => 'UKXX0095', 'name' => 'Motherwell');
$city_data[] = array('accid' => 'UKXX0096', 'name' => 'Musselburgh');
$city_data[] = array('accid' => 'UKXX0097', 'name' => 'Newbury');
$city_data[] = array('accid' => 'UKXX0098', 'name' => 'Newcastle');
$city_data[] = array('accid' => 'UKXX0099', 'name' => 'Newport');
$city_data[] = array('accid' => 'UKXX0100', 'name' => 'Newtownabbey');
$city_data[] = array('accid' => 'UKXX0101', 'name' => 'North Berwick');
$city_data[] = array('accid' => 'UKXX0102', 'name' => 'Northampton');
$city_data[] = array('accid' => 'UKXX0103', 'name' => 'Norwich');
$city_data[] = array('accid' => 'UKXX0104', 'name' => 'Nottingham');
$city_data[] = array('accid' => 'UKXX0105', 'name' => 'Oldham');
$city_data[] = array('accid' => 'UKXX0106', 'name' => 'Oxford');
$city_data[] = array('accid' => 'UKXX0107', 'name' => 'Paisley');
$city_data[] = array('accid' => 'UKXX0108', 'name' => 'Penarth');
$city_data[] = array('accid' => 'UKXX0109', 'name' => 'Penicuik');
$city_data[] = array('accid' => 'UKXX0110', 'name' => 'Peterborough');
$city_data[] = array('accid' => 'UKXX0111', 'name' => 'Peterhead');
$city_data[] = array('accid' => 'UKXX0112', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'UKXX0113', 'name' => 'Poole');
$city_data[] = array('accid' => 'UKXX0114', 'name' => 'Port Talbot');
$city_data[] = array('accid' => 'UKXX0115', 'name' => 'Portsmouth');
$city_data[] = array('accid' => 'UKXX0116', 'name' => 'Ramsgate');
$city_data[] = array('accid' => 'UKXX0117', 'name' => 'Reading');
$city_data[] = array('accid' => 'UKXX0118', 'name' => 'Reigate');
$city_data[] = array('accid' => 'UKXX0119', 'name' => 'Rickmansworth');
$city_data[] = array('accid' => 'UKXX0120', 'name' => 'Rochdale');
$city_data[] = array('accid' => 'UKXX0121', 'name' => 'Rotherham');
$city_data[] = array('accid' => 'UKXX0122', 'name' => 'Rumney');
$city_data[] = array('accid' => 'UKXX0123', 'name' => 'Rutherglen');
$city_data[] = array('accid' => 'UKXX0124', 'name' => 'Saint Anne/Alderney Island');
$city_data[] = array('accid' => 'UKXX0125', 'name' => 'Saint Aubin/Jersey Island');
$city_data[] = array('accid' => 'UKXX0126', 'name' => 'Saint Austell');
$city_data[] = array('accid' => 'UKXX0127', 'name' => 'Saint Helens');
$city_data[] = array('accid' => 'UKXX0128', 'name' => 'Saint Peter Port');
$city_data[] = array('accid' => 'UKXX0129', 'name' => 'Salford');
$city_data[] = array('accid' => 'UKXX0130', 'name' => 'Saltash');
$city_data[] = array('accid' => 'UKXX0131', 'name' => 'Scarborough');
$city_data[] = array('accid' => 'UKXX0132', 'name' => 'Scunthorpe');
$city_data[] = array('accid' => 'UKXX0133', 'name' => 'Sheffield');
$city_data[] = array('accid' => 'UKXX0134', 'name' => 'Shipley');
$city_data[] = array('accid' => 'UKXX0135', 'name' => 'Slough');
$city_data[] = array('accid' => 'UKXX0136', 'name' => 'Smethwick');
$city_data[] = array('accid' => 'UKXX0137', 'name' => 'South Shields');
$city_data[] = array('accid' => 'UKXX0138', 'name' => 'Southampton');
$city_data[] = array('accid' => 'UKXX0139', 'name' => 'Southport');
$city_data[] = array('accid' => 'UKXX0140', 'name' => 'Stockport');
$city_data[] = array('accid' => 'UKXX0141', 'name' => 'Stockton-on-Tees');
$city_data[] = array('accid' => 'UKXX0142', 'name' => 'Stoke on Trent');
$city_data[] = array('accid' => 'UKXX0143', 'name' => 'Stonehaven');
$city_data[] = array('accid' => 'UKXX0144', 'name' => 'Sumburgh');
$city_data[] = array('accid' => 'UKXX0145', 'name' => 'Sunderland');
$city_data[] = array('accid' => 'UKXX0146', 'name' => 'Swansea');
$city_data[] = array('accid' => 'UKXX0147', 'name' => 'Swindon');
$city_data[] = array('accid' => 'UKXX0148', 'name' => 'Tamworth');
$city_data[] = array('accid' => 'UKXX0149', 'name' => 'Tavistock');
$city_data[] = array('accid' => 'UKXX0150', 'name' => 'Torquay');
$city_data[] = array('accid' => 'UKXX0151', 'name' => 'Trowbridge');
$city_data[] = array('accid' => 'UKXX0152', 'name' => 'Wakefield');
$city_data[] = array('accid' => 'UKXX0153', 'name' => 'Warrington');
$city_data[] = array('accid' => 'UKXX0154', 'name' => 'Weybridge');
$city_data[] = array('accid' => 'UKXX0155', 'name' => 'Whitstable');
$city_data[] = array('accid' => 'UKXX0156', 'name' => 'Widnes');
$city_data[] = array('accid' => 'UKXX0157', 'name' => 'Winchester');
$city_data[] = array('accid' => 'UKXX0158', 'name' => 'Windsor');
$city_data[] = array('accid' => 'UKXX0159', 'name' => 'Wolverhampton');
$city_data[] = array('accid' => 'UKXX0160', 'name' => 'Woodbridge');
$city_data[] = array('accid' => 'UKXX0161', 'name' => 'Worcester');
$city_data[] = array('accid' => 'UKXX0162', 'name' => 'York');
$city_data[] = array('accid' => 'UKXX0164', 'name' => 'Kirkwall Airport');
$city_data[] = array('accid' => 'UKXX0165', 'name' => 'Stornoway');
$city_data[] = array('accid' => 'UKXX0166', 'name' => 'Aviemore');
$city_data[] = array('accid' => 'UKXX0167', 'name' => 'Kinloss');
$city_data[] = array('accid' => 'UKXX0168', 'name' => 'Tiree');
$city_data[] = array('accid' => 'UKXX0169', 'name' => 'Eskdalemuir');
$city_data[] = array('accid' => 'UKXX0170', 'name' => 'Leuchars');
$city_data[] = array('accid' => 'UKXX0172', 'name' => 'Boulmer');
$city_data[] = array('accid' => 'UKXX0173', 'name' => 'Leeming');
$city_data[] = array('accid' => 'UKXX0174', 'name' => 'Bridlington Mrsc');
$city_data[] = array('accid' => 'UKXX0175', 'name' => 'Valley');
$city_data[] = array('accid' => 'UKXX0176', 'name' => 'Waddington');
$city_data[] = array('accid' => 'UKXX0177', 'name' => 'Shawbury');
$city_data[] = array('accid' => 'UKXX0178', 'name' => 'Wittering');
$city_data[] = array('accid' => 'UKXX0179', 'name' => 'Hemsby');
$city_data[] = array('accid' => 'UKXX0180', 'name' => 'Aberporth');
$city_data[] = array('accid' => 'UKXX0181', 'name' => 'Wattisham');
$city_data[] = array('accid' => 'UKXX0182', 'name' => 'Brize Norton');
$city_data[] = array('accid' => 'UKXX0183', 'name' => 'Lyneham');
$city_data[] = array('accid' => 'UKXX0184', 'name' => 'Manston');
$city_data[] = array('accid' => 'UKXX0185', 'name' => 'Camborne');
$city_data[] = array('accid' => 'UKXX0186', 'name' => 'Culdrose');
$city_data[] = array('accid' => 'UKXX0187', 'name' => 'Saint Mawgan');
$city_data[] = array('accid' => 'UKXX0188', 'name' => 'Yeovilton');
$city_data[] = array('accid' => 'UKXX0189', 'name' => 'Herstmonceux');
$city_data[] = array('accid' => 'UKXX0190', 'name' => 'Hillsborough');
$city_data[] = array('accid' => 'UKXX0191', 'name' => 'Saint Helena Island');
$city_data[] = array('accid' => 'UKXX0193', 'name' => 'Abersoch');
$city_data[] = array('accid' => 'UKXX0194', 'name' => 'Acharn');
$city_data[] = array('accid' => 'UKXX0195', 'name' => 'Amesbury');
$city_data[] = array('accid' => 'UKXX0196', 'name' => 'Abergwesyn');
$city_data[] = array('accid' => 'UKXX0197', 'name' => 'Amlwch');
$city_data[] = array('accid' => 'UKXX0198', 'name' => 'Altnaharra');
$city_data[] = array('accid' => 'UKXX0199', 'name' => 'Alston');
$city_data[] = array('accid' => 'UKXX0200', 'name' => 'Andover');
$city_data[] = array('accid' => 'UKXX0201', 'name' => 'Abbotsbury');
$city_data[] = array('accid' => 'UKXX0203', 'name' => 'Aberystwyth');
$city_data[] = array('accid' => 'UKXX0204', 'name' => 'Aylesbury');
$city_data[] = array('accid' => 'UKXX0205', 'name' => 'Bala');
$city_data[] = array('accid' => 'UKXX0206', 'name' => 'Brecon');
$city_data[] = array('accid' => 'UKXX0207', 'name' => 'Bude');
$city_data[] = array('accid' => 'UKXX0208', 'name' => 'Bruton');
$city_data[] = array('accid' => 'UKXX0209', 'name' => 'Banbury');
$city_data[] = array('accid' => 'UKXX0210', 'name' => 'Bodenham');
$city_data[] = array('accid' => 'UKXX0211', 'name' => 'Butter Tubs Pass');
$city_data[] = array('accid' => 'UKXX0212', 'name' => 'Bourne');
$city_data[] = array('accid' => 'UKXX0213', 'name' => 'Bury St Edmunds');
$city_data[] = array('accid' => 'UKXX0214', 'name' => 'Buxton');
$city_data[] = array('accid' => 'UKXX0215', 'name' => 'Brighton');
$city_data[] = array('accid' => 'UKXX0216', 'name' => 'Bexhill');
$city_data[] = array('accid' => 'UKXX0217', 'name' => 'Cairnryan');
$city_data[] = array('accid' => 'UKXX0218', 'name' => 'Colwyn Bay');
$city_data[] = array('accid' => 'UKXX0219', 'name' => 'Clacton');
$city_data[] = array('accid' => 'UKXX0220', 'name' => 'Crew Green');
$city_data[] = array('accid' => 'UKXX0221', 'name' => 'Craigencallie');
$city_data[] = array('accid' => 'UKXX0222', 'name' => 'Cromer');
$city_data[] = array('accid' => 'UKXX0223', 'name' => 'Crewkerne');
$city_data[] = array('accid' => 'UKXX0224', 'name' => 'Coleraine');
$city_data[] = array('accid' => 'UKXX0225', 'name' => 'Copplestone');
$city_data[] = array('accid' => 'UKXX0226', 'name' => 'Carlisle');
$city_data[] = array('accid' => 'UKXX0227', 'name' => 'Chivenor');
$city_data[] = array('accid' => 'UKXX0228', 'name' => 'Crewe');
$city_data[] = array('accid' => 'UKXX0229', 'name' => 'Brawdy');
$city_data[] = array('accid' => 'UKXX0230', 'name' => 'Devauden');
$city_data[] = array('accid' => 'UKXX0231', 'name' => 'Dunkeswell Arpt');
$city_data[] = array('accid' => 'UKXX0232', 'name' => 'Easington');
$city_data[] = array('accid' => 'UKXX0233', 'name' => 'Eskmeals');
$city_data[] = array('accid' => 'UKXX0234', 'name' => 'Exton');
$city_data[] = array('accid' => 'UKXX0235', 'name' => 'Fairlight');
$city_data[] = array('accid' => 'UKXX0236', 'name' => 'Ffestiniog');
$city_data[] = array('accid' => 'UKXX0237', 'name' => 'Freshwater');
$city_data[] = array('accid' => 'UKXX0238', 'name' => 'Glenanne');
$city_data[] = array('accid' => 'UKXX0239', 'name' => 'Godalming');
$city_data[] = array('accid' => 'UKXX0240', 'name' => 'Glen Orrin');
$city_data[] = array('accid' => 'UKXX0241', 'name' => 'Grassington');
$city_data[] = array('accid' => 'UKXX0242', 'name' => 'Great Wakering');
$city_data[] = array('accid' => 'UKXX0243', 'name' => 'Garvagh');
$city_data[] = array('accid' => 'UKXX0244', 'name' => 'Harlow');
$city_data[] = array('accid' => 'UKXX0245', 'name' => 'Hereford');
$city_data[] = array('accid' => 'UKXX0246', 'name' => 'Holywell');
$city_data[] = array('accid' => 'UKXX0247', 'name' => 'Horst Green');
$city_data[] = array('accid' => 'UKXX0248', 'name' => 'Hunstanton');
$city_data[] = array('accid' => 'UKXX0249', 'name' => 'Hay-On-Wye');
$city_data[] = array('accid' => 'UKXX0250', 'name' => 'Inverness');
$city_data[] = array('accid' => 'UKXX0251', 'name' => 'Jersey');
$city_data[] = array('accid' => 'UKXX0252', 'name' => 'Kirkstone Pass');
$city_data[] = array('accid' => 'UKXX0253', 'name' => 'Knighton');
$city_data[] = array('accid' => 'UKXX0254', 'name' => 'Kettering');
$city_data[] = array('accid' => 'UKXX0255', 'name' => 'Llanidloes');
$city_data[] = array('accid' => 'UKXX0256', 'name' => 'Llandudno');
$city_data[] = array('accid' => 'UKXX0257', 'name' => 'Leighton Buzzard');
$city_data[] = array('accid' => 'UKXX0258', 'name' => 'Lynmouth');
$city_data[] = array('accid' => 'UKXX0259', 'name' => 'Llandrindod Wells');
$city_data[] = array('accid' => 'UKXX0260', 'name' => 'Littlehampton');
$city_data[] = array('accid' => 'UKXX0261', 'name' => 'Lulworth');
$city_data[] = array('accid' => 'UKXX0262', 'name' => 'Llanwrtyd Wells');
$city_data[] = array('accid' => 'UKXX0263', 'name' => 'Llangadog');
$city_data[] = array('accid' => 'UKXX0264', 'name' => 'Llangoed');
$city_data[] = array('accid' => 'UKXX0266', 'name' => 'Minehead');
$city_data[] = array('accid' => 'UKXX0267', 'name' => 'Milnthorpe');
$city_data[] = array('accid' => 'UKXX0268', 'name' => 'Milton Keynes');
$city_data[] = array('accid' => 'UKXX0269', 'name' => 'Malvern');
$city_data[] = array('accid' => 'UKXX0270', 'name' => 'Monmouth');
$city_data[] = array('accid' => 'UKXX0271', 'name' => 'Marham');
$city_data[] = array('accid' => 'UKXX0272', 'name' => 'Mablethorpe');
$city_data[] = array('accid' => 'UKXX0273', 'name' => 'Merthyr');
$city_data[] = array('accid' => 'UKXX0274', 'name' => 'Newhaven');
$city_data[] = array('accid' => 'UKXX0275', 'name' => 'North Downs');
$city_data[] = array('accid' => 'UKXX0276', 'name' => 'Newark On Trent');
$city_data[] = array('accid' => 'UKXX0278', 'name' => 'New Quay');
$city_data[] = array('accid' => 'UKXX0279', 'name' => 'Orford');
$city_data[] = array('accid' => 'UKXX0280', 'name' => 'Okehampton');
$city_data[] = array('accid' => 'UKXX0281', 'name' => 'Ormskirk');
$city_data[] = array('accid' => 'UKXX0282', 'name' => 'Preston');
$city_data[] = array('accid' => 'UKXX0283', 'name' => 'Princetown');
$city_data[] = array('accid' => 'UKXX0284', 'name' => 'Presteigne');
$city_data[] = array('accid' => 'UKXX0285', 'name' => 'Perth');
$city_data[] = array('accid' => 'UKXX0286', 'name' => 'Penzance');
$city_data[] = array('accid' => 'UKXX0287', 'name' => 'Bardesy');
$city_data[] = array('accid' => 'UKXX0288', 'name' => 'Raglan');
$city_data[] = array('accid' => 'UKXX0289', 'name' => 'Barmouth');
$city_data[] = array('accid' => 'UKXX0290', 'name' => 'Redesdale');
$city_data[] = array('accid' => 'UKXX0291', 'name' => 'Rhyll');
$city_data[] = array('accid' => 'UKXX0292', 'name' => 'Rayleigh');
$city_data[] = array('accid' => 'UKXX0294', 'name' => 'Stratford On Avo');
$city_data[] = array('accid' => 'UKXX0295', 'name' => 'Snowdon');
$city_data[] = array('accid' => 'UKXX0296', 'name' => 'Shrewsbury');
$city_data[] = array('accid' => 'UKXX0297', 'name' => 'Shipton');
$city_data[] = array('accid' => 'UKXX0298', 'name' => 'Skipton');
$city_data[] = array('accid' => 'UKXX0299', 'name' => 'Sandbach');
$city_data[] = array('accid' => 'UKXX0300', 'name' => 'Spalding');
$city_data[] = array('accid' => 'UKXX0301', 'name' => 'Salisbury');
$city_data[] = array('accid' => 'UKXX0302', 'name' => 'Stocks Resvr');
$city_data[] = array('accid' => 'UKXX0303', 'name' => 'Scilly');
$city_data[] = array('accid' => 'UKXX0304', 'name' => 'Tenby');
$city_data[] = array('accid' => 'UKXX0305', 'name' => 'Telford');
$city_data[] = array('accid' => 'UKXX0306', 'name' => 'Tunbridge Wells');
$city_data[] = array('accid' => 'UKXX0307', 'name' => 'Tonbridge');
$city_data[] = array('accid' => 'UKXX0308', 'name' => 'Trostan');
$city_data[] = array('accid' => 'UKXX0309', 'name' => 'Taunton');
$city_data[] = array('accid' => 'UKXX0310', 'name' => 'Tywyn');
$city_data[] = array('accid' => 'UKXX0311', 'name' => 'Wainfleet');
$city_data[] = array('accid' => 'UKXX0312', 'name' => 'Whitby');
$city_data[] = array('accid' => 'UKXX0313', 'name' => 'Wick');
$city_data[] = array('accid' => 'UKXX0314', 'name' => 'Wellington');
$city_data[] = array('accid' => 'UKXX0315', 'name' => 'Whitland');
$city_data[] = array('accid' => 'UKXX0316', 'name' => 'Welshpool');
$city_data[] = array('accid' => 'UKXX0317', 'name' => 'Weymouth');
$city_data[] = array('accid' => 'UKXX0318', 'name' => 'Whitehall');
$city_data[] = array('accid' => 'UKXX0319', 'name' => 'Warslow');
$city_data[] = array('accid' => 'UKXX0320', 'name' => 'Weston-Spr-Mare');
$city_data[] = array('accid' => 'UKXX0321', 'name' => 'Weybourne');
$city_data[] = array('accid' => 'UKXX0322', 'name' => 'Cottesmore');
$city_data[] = array('accid' => 'UKXX0323', 'name' => 'Brighstone');
$city_data[] = array('accid' => 'UKXX0324', 'name' => 'Chale');
$city_data[] = array('accid' => 'UKXX0325', 'name' => 'Skomer');
$city_data[] = array('accid' => 'UKXX0326', 'name' => 'Cardigan Bay');
$city_data[] = array('accid' => 'UKXX0327', 'name' => 'Cape Wrath');
$city_data[] = array('accid' => 'UKXX0330', 'name' => 'The Little Minch');
$city_data[] = array('accid' => 'UKXX0332', 'name' => 'Strait Of Dover');
$city_data[] = array('accid' => 'UKXX0341', 'name' => 'Newtownards');
$city_data[] = array('accid' => 'UKXX0345', 'name' => 'Carrickfergus');
$city_data[] = array('accid' => 'UKXX0357', 'name' => 'Wallasey');
$city_data[] = array('accid' => 'UKXX0359', 'name' => 'Broadstairs');
$city_data[] = array('accid' => 'UKXX0360', 'name' => 'Dumfries');
$city_data[] = array('accid' => 'UKXX0373', 'name' => 'Cleethorpes');
$city_data[] = array('accid' => 'UKXX0390', 'name' => 'Morecambe');
$city_data[] = array('accid' => 'UKXX0392', 'name' => 'Rhyl');
$city_data[] = array('accid' => 'UKXX0399', 'name' => 'Lowestoft');
$city_data[] = array('accid' => 'UKXX0413', 'name' => 'Gosport');
$city_data[] = array('accid' => 'UKXX0416', 'name' => 'Canvey Island');
$city_data[] = array('accid' => 'UKXX0429', 'name' => 'St Albans');
$city_data[] = array('accid' => 'UKXX0430', 'name' => 'Radcliffe');
$city_data[] = array('accid' => 'UKXX0431', 'name' => 'St Helier');
$city_data[] = array('accid' => 'UKXX0456', 'name' => 'Heanor');
$city_data[] = array('accid' => 'UKXX0474', 'name' => 'High Wycombe');
$city_data[] = array('accid' => 'UKXX0482', 'name' => 'Esher');
$city_data[] = array('accid' => 'UKXX0486', 'name' => 'Pudsey');
$city_data[] = array('accid' => 'UKXX0488', 'name' => 'Whitefield');
$city_data[] = array('accid' => 'UKXX0493', 'name' => 'Cramlington');
$city_data[] = array('accid' => 'UKXX0498', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'UKXX0500', 'name' => 'Heywood');
$city_data[] = array('accid' => 'UKXX0504', 'name' => 'King\'s Lynn');
$city_data[] = array('accid' => 'UKXX0513', 'name' => 'Stevenage');
$city_data[] = array('accid' => 'UKXX0518', 'name' => 'Basildon');
$city_data[] = array('accid' => 'UKXX0526', 'name' => 'Havering');
$city_data[] = array('accid' => 'UKXX0527', 'name' => 'Hemel Hempstead');
$city_data[] = array('accid' => 'UKXX0528', 'name' => 'Burton-on-Trent');
$city_data[] = array('accid' => 'UKXX0529', 'name' => 'Newburn');
$city_data[] = array('accid' => 'UKXX0530', 'name' => 'Tyldesley');
$city_data[] = array('accid' => 'UKXX0531', 'name' => 'Fleet');
$city_data[] = array('accid' => 'UKXX0532', 'name' => 'Kidsgrove');
$city_data[] = array('accid' => 'UKXX0534', 'name' => 'Welwyn Garden City');
$city_data[] = array('accid' => 'UKXX0552', 'name' => 'Nuneaton');
$city_data[] = array('accid' => 'UKXX0556', 'name' => 'Newton Aycliffe');
$city_data[] = array('accid' => 'UKXX0563', 'name' => 'Barnet');
$city_data[] = array('accid' => 'UKXX0573', 'name' => 'Felixstowe');
$city_data[] = array('accid' => 'UKXX0576', 'name' => 'Irvine');
$city_data[] = array('accid' => 'UKXX0581', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'UKXX0586', 'name' => 'Wallsend');
$city_data[] = array('accid' => 'UKXX0589', 'name' => 'Ashington');
$city_data[] = array('accid' => 'UKXX0605', 'name' => 'Leyland');
$city_data[] = array('accid' => 'UKXX0606', 'name' => 'Redhill');
$city_data[] = array('accid' => 'UKXX0616', 'name' => 'Paignton');
$city_data[] = array('accid' => 'UKXX0623', 'name' => 'The Potteries');
$city_data[] = array('accid' => 'UKXX0624', 'name' => 'Brent');
$city_data[] = array('accid' => 'UKXX0625', 'name' => 'Gillingham');
$city_data[] = array('accid' => 'UKXX0626', 'name' => 'Bury');
$city_data[] = array('accid' => 'UKXX0627', 'name' => 'Telford Dawley');
$city_data[] = array('accid' => 'UKXX0628', 'name' => 'Great Sankey');
$city_data[] = array('accid' => 'UKXX0629', 'name' => 'Chipping Sodbury');
$city_data[] = array('accid' => 'UKXX0630', 'name' => 'Ecclesfield');
$city_data[] = array('accid' => 'UKXX0631', 'name' => 'Haywards Heath');
$city_data[] = array('accid' => 'UKXX0632', 'name' => 'Ashton-in-Makerfield');
$city_data[] = array('accid' => 'UKXX0634', 'name' => 'Harpenden');
$city_data[] = array('accid' => 'UKXX0639', 'name' => 'Worthing');
$city_data[] = array('accid' => 'UKXX0648', 'name' => 'Clacton-on-Sea');
$city_data[] = array('accid' => 'UKXX0651', 'name' => 'Herne Bay');
$city_data[] = array('accid' => 'UKXX0655', 'name' => 'Swadlincote');
$city_data[] = array('accid' => 'UKXX0661', 'name' => 'Fleetwood');
$city_data[] = array('accid' => 'UKXX0663', 'name' => 'Dumbarton');
$city_data[] = array('accid' => 'UKXX0670', 'name' => 'Camberley');
$city_data[] = array('accid' => 'UKXX0679', 'name' => 'Formby');
$city_data[] = array('accid' => 'UKXX0680', 'name' => 'Loughborough');
$city_data[] = array('accid' => 'UKXX0681', 'name' => 'Coalville');
$city_data[] = array('accid' => 'UKXX0689', 'name' => 'Blyth');
$city_data[] = array('accid' => 'UKXX0690', 'name' => 'Jarrow');
$city_data[] = array('accid' => 'UKXX0710', 'name' => 'Worksop');
$city_data[] = array('accid' => 'UKXX0712', 'name' => 'Letchworth');
$city_data[] = array('accid' => 'UKXX0714', 'name' => 'Glossop');
$city_data[] = array('accid' => 'UKXX0726', 'name' => 'Bebington');
$city_data[] = array('accid' => 'UKXX0727', 'name' => 'Dewsbury');
$city_data[] = array('accid' => 'UKXX0728', 'name' => 'Felling');
$city_data[] = array('accid' => 'UKXX0729', 'name' => 'Grantham');
$city_data[] = array('accid' => 'UKXX0730', 'name' => 'Shirley');
$city_data[] = array('accid' => 'UKXX0731', 'name' => 'Staveley');
$city_data[] = array('accid' => 'UKXX0732', 'name' => 'Kirkby-in-Ashfield');
$city_data[] = array('accid' => 'UKXX0738', 'name' => 'Caerphilly');
$city_data[] = array('accid' => 'UKXX0739', 'name' => 'Bishop\'s Stortford');
$city_data[] = array('accid' => 'UKXX0742', 'name' => 'Kenilworth');
$city_data[] = array('accid' => 'UKXX0745', 'name' => 'Dartford');
$city_data[] = array('accid' => 'UKXX0770', 'name' => 'Kingston upon Thames');
$city_data[] = array('accid' => 'UKXX0775', 'name' => 'Glenrothes');
$city_data[] = array('accid' => 'UKXX0780', 'name' => 'Chatham');
$city_data[] = array('accid' => 'UKXX0787', 'name' => 'Sutton-in-Ashfield');
$city_data[] = array('accid' => 'UKXX0790', 'name' => 'Ashton-under-Lyne');
$city_data[] = array('accid' => 'UKXX0797', 'name' => 'Romford');
$city_data[] = array('accid' => 'UKXX0810', 'name' => 'Borehamwood');
$city_data[] = array('accid' => 'UKXX0812', 'name' => 'Walsall');
$city_data[] = array('accid' => 'UKXX0814', 'name' => 'Hillingdon');
$city_data[] = array('accid' => 'UKXX0815', 'name' => 'Westminster');
$city_data[] = array('accid' => 'UKXX0816', 'name' => 'Crawley');
$city_data[] = array('accid' => 'UKXX0817', 'name' => 'Darlington');
$city_data[] = array('accid' => 'UKXX0818', 'name' => 'Newcastle-under-Lyme');
$city_data[] = array('accid' => 'UKXX0819', 'name' => 'Greasby');
$city_data[] = array('accid' => 'UKXX0820', 'name' => 'Cumbernauld');
$city_data[] = array('accid' => 'UKXX0821', 'name' => 'Wrexham');
$city_data[] = array('accid' => 'UKXX0822', 'name' => 'Eccles');
$city_data[] = array('accid' => 'UKXX0823', 'name' => 'Chester-le-Street');
$city_data[] = array('accid' => 'UKXX0824', 'name' => 'Chadderton');
$city_data[] = array('accid' => 'UKXX0825', 'name' => 'Chorley');
$city_data[] = array('accid' => 'UKXX0826', 'name' => 'Bentley');
$city_data[] = array('accid' => 'UKXX0827', 'name' => 'Bramhall');
$city_data[] = array('accid' => 'UKXX0828', 'name' => 'Bromborough');
$city_data[] = array('accid' => 'UKXX0829', 'name' => 'Bearsden');
$city_data[] = array('accid' => 'UKXX0830', 'name' => 'Newry');
$city_data[] = array('accid' => 'UKXX0831', 'name' => 'Maghull');
$city_data[] = array('accid' => 'UKXX0832', 'name' => 'Rawtenstall');
$city_data[] = array('accid' => 'UKXX0849', 'name' => 'Congleton');
$city_data[] = array('accid' => 'UKXX0850', 'name' => 'Bexley');
$city_data[] = array('accid' => 'UKXX0858', 'name' => 'Aldershot');
$city_data[] = array('accid' => 'UKXX0873', 'name' => 'Kirkby');
$city_data[] = array('accid' => 'UKXX0887', 'name' => 'Newark');
$city_data[] = array('accid' => 'UKXX0889', 'name' => 'Pontypool');
$city_data[] = array('accid' => 'UKXX0899', 'name' => 'Chichester');
$city_data[] = array('accid' => 'UKXX0903', 'name' => 'Wokingham');
$city_data[] = array('accid' => 'UKXX0904', 'name' => 'East Grinstead');
$city_data[] = array('accid' => 'UKXX0913', 'name' => 'Banstead');
$city_data[] = array('accid' => 'UKXX0914', 'name' => 'Benfleet');
$city_data[] = array('accid' => 'UKXX0921', 'name' => 'Redcar');
$city_data[] = array('accid' => 'UKXX0924', 'name' => 'Watford');
$city_data[] = array('accid' => 'UKXX0925', 'name' => 'Wigan');
$city_data[] = array('accid' => 'UKXX0926', 'name' => 'Lambeth');
$city_data[] = array('accid' => 'UKXX0927', 'name' => 'Waltham Forest');
$city_data[] = array('accid' => 'UKXX0928', 'name' => 'Richmond-upon-Thames');
$city_data[] = array('accid' => 'UKXX0929', 'name' => 'Hastings');
$city_data[] = array('accid' => 'UKXX0930', 'name' => 'Huyton-with-Roby');
$city_data[] = array('accid' => 'UKXX0931', 'name' => 'Pontefract');
$city_data[] = array('accid' => 'UKXX0932', 'name' => 'Droylsden');
$city_data[] = array('accid' => 'UKXX0939', 'name' => 'Keighley');
$city_data[] = array('accid' => 'UKXX0943', 'name' => 'Pontypridd');
$city_data[] = array('accid' => 'UKXX0946', 'name' => 'Witham');
$city_data[] = array('accid' => 'UKXX0948', 'name' => 'Bedworth');
$city_data[] = array('accid' => 'UKXX0949', 'name' => 'Winsford');
$city_data[] = array('accid' => 'UKXX0959', 'name' => 'Potters Bar');
$city_data[] = array('accid' => 'UKXX0974', 'name' => 'Surbiton');
$city_data[] = array('accid' => 'UKXX0980', 'name' => 'Hinckley');
$city_data[] = array('accid' => 'UKXX1024', 'name' => 'Teesside');
$city_data[] = array('accid' => 'UKXX1025', 'name' => 'Cannock');
$city_data[] = array('accid' => 'UKXX1026', 'name' => 'Carlton');
$city_data[] = array('accid' => 'UKXX1027', 'name' => 'Stretford');
$city_data[] = array('accid' => 'UKXX1028', 'name' => 'Farnham');
$city_data[] = array('accid' => 'UKXX1029', 'name' => 'West Bridgford');
$city_data[] = array('accid' => 'UKXX1030', 'name' => 'Heswall');
$city_data[] = array('accid' => 'UKXX1031', 'name' => 'Mangotsfield');
$city_data[] = array('accid' => 'UKXX1032', 'name' => 'Penwortham');
$city_data[] = array('accid' => 'UKXX1036', 'name' => 'Blackburn');
$city_data[] = array('accid' => 'UKXX1037', 'name' => 'Darwen');
$city_data[] = array('accid' => 'UKXX1045', 'name' => 'Whitehaven');
$city_data[] = array('accid' => 'UKXX1046', 'name' => 'Merthyr Tydfil');
$city_data[] = array('accid' => 'UKXX1051', 'name' => 'Margate');
$city_data[] = array('accid' => 'UKXX1053', 'name' => 'Arbroath');
$city_data[] = array('accid' => 'UKXX1066', 'name' => 'Stroud');
$city_data[] = array('accid' => 'UKXX1067', 'name' => 'Woking');
$city_data[] = array('accid' => 'UKXX1079', 'name' => 'Melton Mowbray');
$city_data[] = array('accid' => 'UKXX1087', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'UKXX1089', 'name' => 'Walkden');
$city_data[] = array('accid' => 'UKXX1093', 'name' => 'Whitley Bay');
$city_data[] = array('accid' => 'UKXX1099', 'name' => 'Bicester');
$city_data[] = array('accid' => 'UKXX1105', 'name' => 'Bognor Regis');
$city_data[] = array('accid' => 'UKXX1110', 'name' => 'Sutton');
$city_data[] = array('accid' => 'UKXX1112', 'name' => 'Seaham');
$city_data[] = array('accid' => 'UKXX1113', 'name' => 'Peterlee');
$city_data[] = array('accid' => 'UKXX1114', 'name' => 'Wickford');
$city_data[] = array('accid' => 'UKXX1115', 'name' => 'Stoke-on-Trent');
$city_data[] = array('accid' => 'UKXX1123', 'name' => 'Billingham');
$city_data[] = array('accid' => 'UKXX1124', 'name' => 'Egham');
$city_data[] = array('accid' => 'UKXX1126', 'name' => 'Leigh');
$city_data[] = array('accid' => 'UKXX1127', 'name' => 'Camden');
$city_data[] = array('accid' => 'UKXX1128', 'name' => 'Merton');
$city_data[] = array('accid' => 'UKXX1129', 'name' => 'Arnold');
$city_data[] = array('accid' => 'UKXX1130', 'name' => 'Thornton/Cleveleys');
$city_data[] = array('accid' => 'UKXX1131', 'name' => 'Totton');
$city_data[] = array('accid' => 'UKXX1132', 'name' => 'Farnworth');
$city_data[] = array('accid' => 'UKXX1134', 'name' => 'Solihull');
$city_data[] = array('accid' => 'UKXX1137', 'name' => 'Burnley');
$city_data[] = array('accid' => 'UKXX1138', 'name' => 'Christchurch');
$city_data[] = array('accid' => 'UKXX1139', 'name' => 'Eastbourne');
$city_data[] = array('accid' => 'UKXX1146', 'name' => 'Billericay');
$city_data[] = array('accid' => 'UKXX1150', 'name' => 'Bishop Auckland');
$city_data[] = array('accid' => 'UKXX1154', 'name' => 'Hoddesdon');
$city_data[] = array('accid' => 'UKXX1158', 'name' => 'Wembley');
$city_data[] = array('accid' => 'UKXX1159', 'name' => 'Brighouse');
$city_data[] = array('accid' => 'UKXX1161', 'name' => 'Beverley');
$city_data[] = array('accid' => 'UKXX1164', 'name' => 'Ilford');
$city_data[] = array('accid' => 'UKXX1177', 'name' => 'Kendal');
$city_data[] = array('accid' => 'UKXX1186', 'name' => 'Wishaw');
$city_data[] = array('accid' => 'UKXX1205', 'name' => 'Grays');
$city_data[] = array('accid' => 'UKXX1212', 'name' => 'Stalybridge');
$city_data[] = array('accid' => 'UKXX1216', 'name' => 'Bridgwater');
$city_data[] = array('accid' => 'UKXX1221', 'name' => 'Staines');
$city_data[] = array('accid' => 'UKXX1226', 'name' => 'Wandsworth');
$city_data[] = array('accid' => 'UKXX1227', 'name' => 'Haringey');
$city_data[] = array('accid' => 'UKXX1228', 'name' => 'Epsom');
$city_data[] = array('accid' => 'UKXX1229', 'name' => 'Halesowen');
$city_data[] = array('accid' => 'UKXX1230', 'name' => 'Crosby');
$city_data[] = array('accid' => 'UKXX1231', 'name' => 'Hoylake');
$city_data[] = array('accid' => 'UKXX1232', 'name' => 'Bishopbriggs');
$city_data[] = array('accid' => 'UKXX1241', 'name' => 'Accrington');
$city_data[] = array('accid' => 'UKXX1252', 'name' => 'Rugby');
$city_data[] = array('accid' => 'UKXX1269', 'name' => 'Loughton');
$city_data[] = array('accid' => 'UKXX1275', 'name' => 'Leatherhead');
$city_data[] = array('accid' => 'UKXX1279', 'name' => 'Kirkcaldy');
$city_data[] = array('accid' => 'UKXX1289', 'name' => 'Sittingbourne');
$city_data[] = array('accid' => 'UKXX1300', 'name' => 'Waterlooville');
$city_data[] = array('accid' => 'UKXX1303', 'name' => 'Horsham');
$city_data[] = array('accid' => 'UKXX1305', 'name' => 'Llanelli');
$city_data[] = array('accid' => 'UKXX1314', 'name' => 'Southend-on-Sea');
$city_data[] = array('accid' => 'UKXX1323', 'name' => 'Rugeley');
$city_data[] = array('accid' => 'UKXX1324', 'name' => 'Redbridge');
$city_data[] = array('accid' => 'UKXX1325', 'name' => 'The Medway Towns');
$city_data[] = array('accid' => 'UKXX1326', 'name' => 'Southwark');
$city_data[] = array('accid' => 'UKXX1327', 'name' => 'Newham');
$city_data[] = array('accid' => 'UKXX1328', 'name' => 'Harrogate');
$city_data[] = array('accid' => 'UKXX1329', 'name' => 'Beeston');
$city_data[] = array('accid' => 'UKXX1330', 'name' => 'Cheshunt');
$city_data[] = array('accid' => 'UKXX1331', 'name' => 'Bletchley');
$city_data[] = array('accid' => 'UKXX1332', 'name' => 'Hucknall');
$city_data[] = array('accid' => 'UKXX1338', 'name' => 'Ferndown');
$city_data[] = array('accid' => 'UKXX1343', 'name' => 'Braintree');
$city_data[] = array('accid' => 'UKXX1344', 'name' => 'Brentwood');
$city_data[] = array('accid' => 'UKXX1347', 'name' => 'Warwick');
$city_data[] = array('accid' => 'UKXX1349', 'name' => 'Alfreton');
$city_data[] = array('accid' => 'UKXX1354', 'name' => 'Exmouth');
$city_data[] = array('accid' => 'UKXX1362', 'name' => 'Halifax');
$city_data[] = array('accid' => 'UKXX1376', 'name' => 'Wigston');
$city_data[] = array('accid' => 'UKXX1384', 'name' => 'Rochester');
$city_data[] = array('accid' => 'UKXX1388', 'name' => 'Wellingborough');
$city_data[] = array('accid' => 'UKXX1389', 'name' => 'Rushden');
$city_data[] = array('accid' => 'UKXX1413', 'name' => 'Wilmslow');
$city_data[] = array('accid' => 'UKXX1418', 'name' => 'Sevenoaks');
$city_data[] = array('accid' => 'UKXX1423', 'name' => 'Lichfield');
$city_data[] = array('accid' => 'UKXX1425', 'name' => 'Croydon');
$city_data[] = array('accid' => 'UKXX1426', 'name' => 'Ealing');
$city_data[] = array('accid' => 'UKXX1427', 'name' => 'Lewisham');
$city_data[] = array('accid' => 'UKXX1428', 'name' => 'Greenwich');
$city_data[] = array('accid' => 'UKXX1429', 'name' => 'Rhondda');
$city_data[] = array('accid' => 'UKXX1430', 'name' => 'Gravesend');
$city_data[] = array('accid' => 'UKXX1431', 'name' => 'Middleton');
$city_data[] = array('accid' => 'UKXX1432', 'name' => 'Lurgan');
$city_data[] = array('accid' => 'UKXX1435', 'name' => 'Yeovil');
$city_data[] = array('accid' => 'UKXX1445', 'name' => 'Deal');
$city_data[] = array('accid' => 'UKXX1449', 'name' => 'Ilkeston');
$city_data[] = array('accid' => 'UKXX1453', 'name' => 'Stourbridge');
$city_data[] = array('accid' => 'UKXX1463', 'name' => 'Barnstaple');
$city_data[] = array('accid' => 'UKXX1471', 'name' => 'Harrow');
$city_data[] = array('accid' => 'UKXX1484', 'name' => 'Sale');
$city_data[] = array('accid' => 'UKXX1490', 'name' => 'Corby');
$city_data[] = array('accid' => 'UKXX1516', 'name' => 'Newton Abbot');
$city_data[] = array('accid' => 'UKXX1523', 'name' => 'Tyneside');
$city_data[] = array('accid' => 'UKXX1524', 'name' => 'Royal Tunbridge Wells');
$city_data[] = array('accid' => 'UKXX1525', 'name' => 'Royal Leamington Spa');
$city_data[] = array('accid' => 'UKXX1526', 'name' => 'Worsley');
$city_data[] = array('accid' => 'UKXX1527', 'name' => 'Morley');
$city_data[] = array('accid' => 'UKXX1528', 'name' => 'Urmston');
$city_data[] = array('accid' => 'UKXX1529', 'name' => 'Leighton-Linslade');
$city_data[] = array('accid' => 'UKXX1530', 'name' => 'Hatfield');
$city_data[] = array('accid' => 'UKXX1531', 'name' => 'Chapeltown');
$city_data[] = array('accid' => 'UKXX1532', 'name' => 'Gosforth');
$city_data[] = array('accid' => 'UKXX1540', 'name' => 'Ballymena');
$city_data[] = array('accid' => 'UKXX1546', 'name' => 'Ellesmere Port');
$city_data[] = array('accid' => 'UKXX1549', 'name' => 'Stratford-upon-Avon');
$city_data[] = array('accid' => 'UKXX1551', 'name' => 'Northwich');
$city_data[] = array('accid' => 'UKXX1561', 'name' => 'Enfield');
$city_data[] = array('accid' => 'UKXX1565', 'name' => 'Stirling');
$city_data[] = array('accid' => 'UKXX1575', 'name' => 'Bootle');
$city_data[] = array('accid' => 'UKXX1577', 'name' => 'Barrow-in-Furness');
$city_data[] = array('accid' => 'UKXX1586', 'name' => 'North Shields');
$city_data[] = array('accid' => 'UKXX1590', 'name' => 'Cwmbran');
$city_data[] = array('accid' => 'UKXX1608', 'name' => 'Hyde');
$city_data[] = array('accid' => 'UKXX1611', 'name' => 'Stafford');
$city_data[] = array('accid' => 'UKXX1624', 'name' => 'Castleford');
$city_data[] = array('accid' => 'UKXX1628', 'name' => 'Weston-super-Mare');
$city_data[] = array('accid' => 'UKXX1629', 'name' => 'Strood');
$city_data[] = array('accid' => 'UKXX1630', 'name' => 'Locks Heath');
$city_data[] = array('accid' => 'UKXX1631', 'name' => 'Thornaby-on-Tees');
$city_data[] = array('accid' => 'UKXX1632', 'name' => 'Hawarden');
$city_data[] = array('accid' => 'UKXX1638', 'name' => 'Sutton Coldfield');
$city_data[] = array('accid' => 'UKXX1640', 'name' => 'Redditch');
$city_data[] = array('accid' => 'UKXX1642', 'name' => 'Frome');
$city_data[] = array('accid' => 'UKXX1649', 'name' => 'Bromley');
$city_data[] = array('accid' => 'UKXX1654', 'name' => 'Aberdare');
$city_data[] = array('accid' => 'UKXX1679', 'name' => 'Prescot');
$city_data[] = array('accid' => 'UKXX1695', 'name' => 'Newcastle upon Tyne');
$city_data[] = array('accid' => 'UKXX1696', 'name' => 'Washington');
$city_data[] = array('accid' => 'UKXX1701', 'name' => 'Boston');
$city_data[] = array('accid' => 'UKXX1707', 'name' => 'Neath');
$city_data[] = array('accid' => 'UKXX1715', 'name' => 'Chippenham');
$city_data[] = array('accid' => 'UKXX1719', 'name' => 'Bexhill-on-Sea');
$city_data[] = array('accid' => 'UKXX1725', 'name' => 'Hackney');
$city_data[] = array('accid' => 'UKXX1726', 'name' => 'Hammersmith');
$city_data[] = array('accid' => 'UKXX1727', 'name' => 'Guildford');
$city_data[] = array('accid' => 'UKXX1728', 'name' => 'Greenock');
$city_data[] = array('accid' => 'UKXX1729', 'name' => 'Frimley');
$city_data[] = array('accid' => 'UKXX1730', 'name' => 'Bridgend');
$city_data[] = array('accid' => 'UKXX1731', 'name' => 'Thornaby');
$city_data[] = array('accid' => 'UKXX1732', 'name' => 'Hindley');
$city_data[] = array('accid' => 'UKXX1733', 'name' => 'West Bromwich');
$city_data[] = array('accid' => 'UKXX1737', 'name' => 'Nelson');
$city_data[] = array('accid' => 'UKXX1738', 'name' => 'Hove');
$city_data[] = array('accid' => 'UKXX1741', 'name' => 'Workington');
$city_data[] = array('accid' => 'UKXX1762', 'name' => 'Dunstable');
$city_data[] = array('accid' => 'UKXX1764', 'name' => 'Islington');
$city_data[] = array('accid' => 'UKXX1767', 'name' => 'Wisbech');
$city_data[] = array('accid' => 'UKXX1770', 'name' => 'Burgess Hill');
$city_data[] = array('accid' => 'UKXX1783', 'name' => 'Runcorn');
$city_data[] = array('accid' => 'UKXX1785', 'name' => 'Skelmersdale');
$city_data[] = array('accid' => 'UKXX1786', 'name' => 'Burntwood');
$city_data[] = array('accid' => 'UKXX1787', 'name' => 'Tower Hamlets');
$city_data[] = array('accid' => 'UKXX1788', 'name' => 'Denton');
$city_data[] = array('accid' => 'UKXX1789', 'name' => 'Hitchin');
$city_data[] = array('accid' => 'UKXX1790', 'name' => 'Central Milton Keynes');
$city_data[] = array('accid' => 'UKXX1792', 'name' => 'Newport (Isle of Wight)');
$city_data[] = array('accid' => 'UKXX1794', 'name' => 'Newport (Dyfed)');
$city_data[] = array('accid' => 'UKXX1797', 'name' => 'Newport (Shropshire)');
$city_data[] = array('accid' => 'UKXX1844', 'name' => 'Kensington');
$city_data[] = array('accid' => 'UKXX1894', 'name' => 'Kent');
$city_data[] = array('accid' => 'UKXX1915', 'name' => 'Castle Combe');
$city_data[] = array('accid' => 'UKXX1916', 'name' => 'Silverstone');
$city_data[] = array('accid' => 'UKXX1917', 'name' => 'Rockingham');

?>