<?php

// City package for USA: Alaska 

$city_name = 'USA: Alaska';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USAK0001', 'name' => 'Adak');
$city_data[] = array('accid' => 'USAK0003', 'name' => 'Akiachak');
$city_data[] = array('accid' => 'USAK0004', 'name' => 'Akiak');
$city_data[] = array('accid' => 'USAK0005', 'name' => 'Akutan');
$city_data[] = array('accid' => 'USAK0006', 'name' => 'Alakanuk');
$city_data[] = array('accid' => 'USAK0007', 'name' => 'Aleknagik');
$city_data[] = array('accid' => 'USAK0008', 'name' => 'Allakaket');
$city_data[] = array('accid' => 'USAK0009', 'name' => 'Ambler');
$city_data[] = array('accid' => 'USAK0010', 'name' => 'Anaktuvuk Pass');
$city_data[] = array('accid' => 'USAK0011', 'name' => 'Anchor Point');
$city_data[] = array('accid' => 'USAK0012', 'name' => 'Anchorage');
$city_data[] = array('accid' => 'USAK0016', 'name' => 'Anderson');
$city_data[] = array('accid' => 'USAK0017', 'name' => 'Angoon');
$city_data[] = array('accid' => 'USAK0018', 'name' => 'Aniak');
$city_data[] = array('accid' => 'USAK0019', 'name' => 'Anvik');
$city_data[] = array('accid' => 'USAK0021', 'name' => 'Arctic Village');
$city_data[] = array('accid' => 'USAK0022', 'name' => 'Atka');
$city_data[] = array('accid' => 'USAK0023', 'name' => 'Atqasuk');
$city_data[] = array('accid' => 'USAK0024', 'name' => 'Auke Bay');
$city_data[] = array('accid' => 'USAK0025', 'name' => 'Barrow');
$city_data[] = array('accid' => 'USAK0027', 'name' => 'Beaver');
$city_data[] = array('accid' => 'USAK0028', 'name' => 'Bethel');
$city_data[] = array('accid' => 'USAK0030', 'name' => 'Bettles Field');
$city_data[] = array('accid' => 'USAK0032', 'name' => 'Big Lake');
$city_data[] = array('accid' => 'USAK0035', 'name' => 'Brevig Mission');
$city_data[] = array('accid' => 'USAK0036', 'name' => 'Buckland');
$city_data[] = array('accid' => 'USAK0037', 'name' => 'Cantwell');
$city_data[] = array('accid' => 'USAK0041', 'name' => 'Central');
$city_data[] = array('accid' => 'USAK0042', 'name' => 'Chalkyitsik');
$city_data[] = array('accid' => 'USAK0044', 'name' => 'Chefornak');
$city_data[] = array('accid' => 'USAK0045', 'name' => 'Chevak');
$city_data[] = array('accid' => 'USAK0046', 'name' => 'Chicken');
$city_data[] = array('accid' => 'USAK0047', 'name' => 'Chignik');
$city_data[] = array('accid' => 'USAK0048', 'name' => 'Chignik Lagoon');
$city_data[] = array('accid' => 'USAK0050', 'name' => 'Chitina');
$city_data[] = array('accid' => 'USAK0051', 'name' => 'Chugiak');
$city_data[] = array('accid' => 'USAK0053', 'name' => 'Circle');
$city_data[] = array('accid' => 'USAK0054', 'name' => 'Clam Gulch');
$city_data[] = array('accid' => 'USAK0055', 'name' => 'Clarks Point');
$city_data[] = array('accid' => 'USAK0056', 'name' => 'Clear');
$city_data[] = array('accid' => 'USAK0057', 'name' => 'Coffman Cove');
$city_data[] = array('accid' => 'USAK0058', 'name' => 'Cold Bay');
$city_data[] = array('accid' => 'USAK0059', 'name' => 'Cooper Landing');
$city_data[] = array('accid' => 'USAK0060', 'name' => 'Copper Center');
$city_data[] = array('accid' => 'USAK0061', 'name' => 'Cordova');
$city_data[] = array('accid' => 'USAK0062', 'name' => 'Craig');
$city_data[] = array('accid' => 'USAK0063', 'name' => 'Crooked Creek');
$city_data[] = array('accid' => 'USAK0065', 'name' => 'Deering');
$city_data[] = array('accid' => 'USAK0066', 'name' => 'Delta Junction');
$city_data[] = array('accid' => 'USAK0067', 'name' => 'Denali National Park');
$city_data[] = array('accid' => 'USAK0068', 'name' => 'Dillingham');
$city_data[] = array('accid' => 'USAK0069', 'name' => 'Douglas');
$city_data[] = array('accid' => 'USAK0070', 'name' => 'Dutch Harbor');
$city_data[] = array('accid' => 'USAK0071', 'name' => 'Eagle');
$city_data[] = array('accid' => 'USAK0072', 'name' => 'Eagle River');
$city_data[] = array('accid' => 'USAK0073', 'name' => 'Eek');
$city_data[] = array('accid' => 'USAK0074', 'name' => 'Egegik');
$city_data[] = array('accid' => 'USAK0075', 'name' => 'Eielson AFB');
$city_data[] = array('accid' => 'USAK0076', 'name' => 'Ekwok');
$city_data[] = array('accid' => 'USAK0077', 'name' => 'Elfin Cove');
$city_data[] = array('accid' => 'USAK0078', 'name' => 'Elim');
$city_data[] = array('accid' => 'USAK0079', 'name' => 'Elmendorf AFB');
$city_data[] = array('accid' => 'USAK0080', 'name' => 'Emmonak');
$city_data[] = array('accid' => 'USAK0081', 'name' => 'Ester');
$city_data[] = array('accid' => 'USAK0083', 'name' => 'Fairbanks');
$city_data[] = array('accid' => 'USAK0085', 'name' => 'False Pass');
$city_data[] = array('accid' => 'USAK0087', 'name' => 'Flat');
$city_data[] = array('accid' => 'USAK0088', 'name' => 'Fort Richardson');
$city_data[] = array('accid' => 'USAK0089', 'name' => 'Fort Wainwright');
$city_data[] = array('accid' => 'USAK0090', 'name' => 'Fort Yukon');
$city_data[] = array('accid' => 'USAK0091', 'name' => 'Gakona');
$city_data[] = array('accid' => 'USAK0092', 'name' => 'Galena');
$city_data[] = array('accid' => 'USAK0093', 'name' => 'Gambell');
$city_data[] = array('accid' => 'USAK0094', 'name' => 'Girdwood');
$city_data[] = array('accid' => 'USAK0095', 'name' => 'Glennallen');
$city_data[] = array('accid' => 'USAK0097', 'name' => 'Goodnews Bay');
$city_data[] = array('accid' => 'USAK0098', 'name' => 'Grayling');
$city_data[] = array('accid' => 'USAK0100', 'name' => 'Gustavus');
$city_data[] = array('accid' => 'USAK0101', 'name' => 'Haines');
$city_data[] = array('accid' => 'USAK0103', 'name' => 'Healy');
$city_data[] = array('accid' => 'USAK0104', 'name' => 'Holy Cross');
$city_data[] = array('accid' => 'USAK0105', 'name' => 'Homer');
$city_data[] = array('accid' => 'USAK0106', 'name' => 'Hoonah');
$city_data[] = array('accid' => 'USAK0107', 'name' => 'Hooper Bay');
$city_data[] = array('accid' => 'USAK0108', 'name' => 'Hope');
$city_data[] = array('accid' => 'USAK0109', 'name' => 'Houston');
$city_data[] = array('accid' => 'USAK0110', 'name' => 'Hughes');
$city_data[] = array('accid' => 'USAK0111', 'name' => 'Huslia');
$city_data[] = array('accid' => 'USAK0112', 'name' => 'Hydaburg');
$city_data[] = array('accid' => 'USAK0113', 'name' => 'Hyder');
$city_data[] = array('accid' => 'USAK0114', 'name' => 'Iliamna');
$city_data[] = array('accid' => 'USAK0115', 'name' => 'Indian');
$city_data[] = array('accid' => 'USAK0116', 'name' => 'Juneau');
$city_data[] = array('accid' => 'USAK0117', 'name' => 'Kake');
$city_data[] = array('accid' => 'USAK0118', 'name' => 'Kaktovik');
$city_data[] = array('accid' => 'USAK0119', 'name' => 'Kalskag');
$city_data[] = array('accid' => 'USAK0120', 'name' => 'Kaltag');
$city_data[] = array('accid' => 'USAK0121', 'name' => 'Karluk');
$city_data[] = array('accid' => 'USAK0122', 'name' => 'Kasigluk');
$city_data[] = array('accid' => 'USAK0123', 'name' => 'Kasilof');
$city_data[] = array('accid' => 'USAK0124', 'name' => 'Kenai');
$city_data[] = array('accid' => 'USAK0125', 'name' => 'Ketchikan');
$city_data[] = array('accid' => 'USAK0126', 'name' => 'Kiana');
$city_data[] = array('accid' => 'USAK0127', 'name' => 'King Cove');
$city_data[] = array('accid' => 'USAK0128', 'name' => 'King Salmon');
$city_data[] = array('accid' => 'USAK0129', 'name' => 'Kipnuk');
$city_data[] = array('accid' => 'USAK0130', 'name' => 'Kivalina');
$city_data[] = array('accid' => 'USAK0131', 'name' => 'Klawock');
$city_data[] = array('accid' => 'USAK0132', 'name' => 'Kobuk');
$city_data[] = array('accid' => 'USAK0133', 'name' => 'Kodiak');
$city_data[] = array('accid' => 'USAK0134', 'name' => 'Kotlik');
$city_data[] = array('accid' => 'USAK0135', 'name' => 'Kotzebue');
$city_data[] = array('accid' => 'USAK0136', 'name' => 'Koyuk');
$city_data[] = array('accid' => 'USAK0137', 'name' => 'Koyukuk');
$city_data[] = array('accid' => 'USAK0139', 'name' => 'Kwethluk');
$city_data[] = array('accid' => 'USAK0140', 'name' => 'Kwigillingok');
$city_data[] = array('accid' => 'USAK0141', 'name' => 'Lake Minchumina');
$city_data[] = array('accid' => 'USAK0142', 'name' => 'Larsen Bay');
$city_data[] = array('accid' => 'USAK0143', 'name' => 'Levelock');
$city_data[] = array('accid' => 'USAK0144', 'name' => 'Lower Kalskag');
$city_data[] = array('accid' => 'USAK0145', 'name' => 'Manley Hot Springs');
$city_data[] = array('accid' => 'USAK0146', 'name' => 'Manokotak');
$city_data[] = array('accid' => 'USAK0147', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USAK0149', 'name' => 'McGrath');
$city_data[] = array('accid' => 'USAK0151', 'name' => 'Mekoryuk');
$city_data[] = array('accid' => 'USAK0152', 'name' => 'Metlakatla');
$city_data[] = array('accid' => 'USAK0153', 'name' => 'Meyers Chuck');
$city_data[] = array('accid' => 'USAK0156', 'name' => 'Minto');
$city_data[] = array('accid' => 'USAK0157', 'name' => 'Moose Pass');
$city_data[] = array('accid' => 'USAK0158', 'name' => 'Mountain Village');
$city_data[] = array('accid' => 'USAK0160', 'name' => 'Naknek');
$city_data[] = array('accid' => 'USAK0161', 'name' => 'Napakiak');
$city_data[] = array('accid' => 'USAK0162', 'name' => 'Nenana');
$city_data[] = array('accid' => 'USAK0163', 'name' => 'New Stuyahok');
$city_data[] = array('accid' => 'USAK0164', 'name' => 'Nightmute');
$city_data[] = array('accid' => 'USAK0165', 'name' => 'Nikiski');
$city_data[] = array('accid' => 'USAK0166', 'name' => 'Nikolai');
$city_data[] = array('accid' => 'USAK0167', 'name' => 'Nikolski');
$city_data[] = array('accid' => 'USAK0168', 'name' => 'Ninilchik');
$city_data[] = array('accid' => 'USAK0169', 'name' => 'Noatak');
$city_data[] = array('accid' => 'USAK0170', 'name' => 'Nome');
$city_data[] = array('accid' => 'USAK0171', 'name' => 'Nondalton');
$city_data[] = array('accid' => 'USAK0172', 'name' => 'Noorvik');
$city_data[] = array('accid' => 'USAK0173', 'name' => 'North Pole');
$city_data[] = array('accid' => 'USAK0174', 'name' => 'Northway');
$city_data[] = array('accid' => 'USAK0175', 'name' => 'Nuiqsut');
$city_data[] = array('accid' => 'USAK0176', 'name' => 'Nulato');
$city_data[] = array('accid' => 'USAK0177', 'name' => 'Nunapitchuk');
$city_data[] = array('accid' => 'USAK0178', 'name' => 'Old Harbor');
$city_data[] = array('accid' => 'USAK0179', 'name' => 'Ouzinkie');
$city_data[] = array('accid' => 'USAK0180', 'name' => 'Palmer');
$city_data[] = array('accid' => 'USAK0182', 'name' => 'Pedro Bay');
$city_data[] = array('accid' => 'USAK0183', 'name' => 'Pelican');
$city_data[] = array('accid' => 'USAK0184', 'name' => 'Perryville');
$city_data[] = array('accid' => 'USAK0185', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USAK0186', 'name' => 'Pilot Point');
$city_data[] = array('accid' => 'USAK0187', 'name' => 'Pilot Station');
$city_data[] = array('accid' => 'USAK0188', 'name' => 'Platinum');
$city_data[] = array('accid' => 'USAK0189', 'name' => 'Point Baker');
$city_data[] = array('accid' => 'USAK0190', 'name' => 'Point Hope');
$city_data[] = array('accid' => 'USAK0191', 'name' => 'Point Lay');
$city_data[] = array('accid' => 'USAK0193', 'name' => 'Port Alsworth');
$city_data[] = array('accid' => 'USAK0194', 'name' => 'Port Heiden');
$city_data[] = array('accid' => 'USAK0195', 'name' => 'Port Lions');
$city_data[] = array('accid' => 'USAK0197', 'name' => 'Prudhoe Bay');
$city_data[] = array('accid' => 'USAK0199', 'name' => 'Quinhagak');
$city_data[] = array('accid' => 'USAK0200', 'name' => 'Rampart');
$city_data[] = array('accid' => 'USAK0201', 'name' => 'Red Devil');
$city_data[] = array('accid' => 'USAK0203', 'name' => 'Ruby');
$city_data[] = array('accid' => 'USAK0204', 'name' => 'Russian Mission');
$city_data[] = array('accid' => 'USAK0206', 'name' => 'Saint George Island');
$city_data[] = array('accid' => 'USAK0207', 'name' => 'Saint Marys');
$city_data[] = array('accid' => 'USAK0208', 'name' => 'Saint Michael');
$city_data[] = array('accid' => 'USAK0209', 'name' => 'Saint Paul Island');
$city_data[] = array('accid' => 'USAK0210', 'name' => 'Salcha');
$city_data[] = array('accid' => 'USAK0211', 'name' => 'Sand Point');
$city_data[] = array('accid' => 'USAK0212', 'name' => 'Savoonga');
$city_data[] = array('accid' => 'USAK0213', 'name' => 'Scammon Bay');
$city_data[] = array('accid' => 'USAK0214', 'name' => 'Selawik');
$city_data[] = array('accid' => 'USAK0215', 'name' => 'Seldovia');
$city_data[] = array('accid' => 'USAK0216', 'name' => 'Seward');
$city_data[] = array('accid' => 'USAK0217', 'name' => 'Shageluk');
$city_data[] = array('accid' => 'USAK0218', 'name' => 'Shaktoolik');
$city_data[] = array('accid' => 'USAK0220', 'name' => 'Sheldon Point');
$city_data[] = array('accid' => 'USAK0222', 'name' => 'Shishmaref');
$city_data[] = array('accid' => 'USAK0223', 'name' => 'Shungnak');
$city_data[] = array('accid' => 'USAK0224', 'name' => 'Sitka');
$city_data[] = array('accid' => 'USAK0225', 'name' => 'Skagway');
$city_data[] = array('accid' => 'USAK0226', 'name' => 'Skwentna');
$city_data[] = array('accid' => 'USAK0228', 'name' => 'Sleetmute');
$city_data[] = array('accid' => 'USAK0229', 'name' => 'Soldotna');
$city_data[] = array('accid' => 'USAK0230', 'name' => 'South Naknek');
$city_data[] = array('accid' => 'USAK0231', 'name' => 'Stebbins');
$city_data[] = array('accid' => 'USAK0232', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USAK0233', 'name' => 'Stevens Village');
$city_data[] = array('accid' => 'USAK0234', 'name' => 'Sutton');
$city_data[] = array('accid' => 'USAK0235', 'name' => 'Takotna');
$city_data[] = array('accid' => 'USAK0236', 'name' => 'Talkeetna');
$city_data[] = array('accid' => 'USAK0237', 'name' => 'Tanacross');
$city_data[] = array('accid' => 'USAK0238', 'name' => 'Tanana');
$city_data[] = array('accid' => 'USAK0239', 'name' => 'Tatitlek');
$city_data[] = array('accid' => 'USAK0240', 'name' => 'Teller');
$city_data[] = array('accid' => 'USAK0241', 'name' => 'Tenakee Springs');
$city_data[] = array('accid' => 'USAK0242', 'name' => 'Tetlin');
$city_data[] = array('accid' => 'USAK0243', 'name' => 'Thorne Bay');
$city_data[] = array('accid' => 'USAK0245', 'name' => 'Togiak');
$city_data[] = array('accid' => 'USAK0246', 'name' => 'Tok');
$city_data[] = array('accid' => 'USAK0247', 'name' => 'Toksook Bay');
$city_data[] = array('accid' => 'USAK0248', 'name' => 'Trapper Creek');
$city_data[] = array('accid' => 'USAK0249', 'name' => 'Tuluksak');
$city_data[] = array('accid' => 'USAK0250', 'name' => 'Tuntutuliak');
$city_data[] = array('accid' => 'USAK0251', 'name' => 'Tununak');
$city_data[] = array('accid' => 'USAK0252', 'name' => 'Two Rivers');
$city_data[] = array('accid' => 'USAK0253', 'name' => 'Tyonek');
$city_data[] = array('accid' => 'USAK0255', 'name' => 'Unalakleet');
$city_data[] = array('accid' => 'USAK0256', 'name' => 'Unalaska');
$city_data[] = array('accid' => 'USAK0258', 'name' => 'Valdez');
$city_data[] = array('accid' => 'USAK0260', 'name' => 'Venetie');
$city_data[] = array('accid' => 'USAK0261', 'name' => 'Wainwright');
$city_data[] = array('accid' => 'USAK0262', 'name' => 'Wales');
$city_data[] = array('accid' => 'USAK0263', 'name' => 'Ward Cove');
$city_data[] = array('accid' => 'USAK0264', 'name' => 'Wasilla');
$city_data[] = array('accid' => 'USAK0265', 'name' => 'White Mountain');
$city_data[] = array('accid' => 'USAK0266', 'name' => 'Whittier');
$city_data[] = array('accid' => 'USAK0267', 'name' => 'Willow');
$city_data[] = array('accid' => 'USAK0268', 'name' => 'Wrangell');
$city_data[] = array('accid' => 'USAK0269', 'name' => 'Yakutat');

?>
