<?php

// City package for USA: Alabama 

$city_name = 'USA: Alabama';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USAL0001', 'name' => 'Abbeville');
$city_data[] = array('accid' => 'USAL0002', 'name' => 'Abernant');
$city_data[] = array('accid' => 'USAL0003', 'name' => 'Adamsville');
$city_data[] = array('accid' => 'USAL0004', 'name' => 'Addison');
$city_data[] = array('accid' => 'USAL0005', 'name' => 'Adger');
$city_data[] = array('accid' => 'USAL0006', 'name' => 'Akron');
$city_data[] = array('accid' => 'USAL0007', 'name' => 'Alabaster');
$city_data[] = array('accid' => 'USAL0008', 'name' => 'Alberta');
$city_data[] = array('accid' => 'USAL0009', 'name' => 'Albertville');
$city_data[] = array('accid' => 'USAL0010', 'name' => 'Alexander City');
$city_data[] = array('accid' => 'USAL0011', 'name' => 'Alexandria');
$city_data[] = array('accid' => 'USAL0012', 'name' => 'Aliceville');
$city_data[] = array('accid' => 'USAL0013', 'name' => 'Allen');
$city_data[] = array('accid' => 'USAL0014', 'name' => 'Allgood');
$city_data[] = array('accid' => 'USAL0015', 'name' => 'Alma');
$city_data[] = array('accid' => 'USAL0016', 'name' => 'Alpine');
$city_data[] = array('accid' => 'USAL0017', 'name' => 'Alton');
$city_data[] = array('accid' => 'USAL0018', 'name' => 'Altoona');
$city_data[] = array('accid' => 'USAL0019', 'name' => 'Andalusia');
$city_data[] = array('accid' => 'USAL0021', 'name' => 'Anderson');
$city_data[] = array('accid' => 'USAL0022', 'name' => 'Annemanie');
$city_data[] = array('accid' => 'USAL0023', 'name' => 'Anniston');
$city_data[] = array('accid' => 'USAL0024', 'name' => 'Arab');
$city_data[] = array('accid' => 'USAL0025', 'name' => 'Ardmore');
$city_data[] = array('accid' => 'USAL0026', 'name' => 'Ariton');
$city_data[] = array('accid' => 'USAL0027', 'name' => 'Arley');
$city_data[] = array('accid' => 'USAL0028', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USAL0029', 'name' => 'Ashford');
$city_data[] = array('accid' => 'USAL0030', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USAL0031', 'name' => 'Ashville');
$city_data[] = array('accid' => 'USAL0032', 'name' => 'Athens');
$city_data[] = array('accid' => 'USAL0033', 'name' => 'Atmore');
$city_data[] = array('accid' => 'USAL0034', 'name' => 'Attalla');
$city_data[] = array('accid' => 'USAL0035', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USAL0036', 'name' => 'Auburn University');
$city_data[] = array('accid' => 'USAL0037', 'name' => 'Autaugaville');
$city_data[] = array('accid' => 'USAL0038', 'name' => 'Axis');
$city_data[] = array('accid' => 'USAL0039', 'name' => 'Baileyton');
$city_data[] = array('accid' => 'USAL0040', 'name' => 'Banks');
$city_data[] = array('accid' => 'USAL0041', 'name' => 'Bankston');
$city_data[] = array('accid' => 'USAL0042', 'name' => 'Bay Minette');
$city_data[] = array('accid' => 'USAL0043', 'name' => 'Bayou la Batre');
$city_data[] = array('accid' => 'USAL0044', 'name' => 'Bear Creek');
$city_data[] = array('accid' => 'USAL0045', 'name' => 'Beatrice');
$city_data[] = array('accid' => 'USAL0046', 'name' => 'Beaverton');
$city_data[] = array('accid' => 'USAL0047', 'name' => 'Belk');
$city_data[] = array('accid' => 'USAL0048', 'name' => 'Bellamy');
$city_data[] = array('accid' => 'USAL0049', 'name' => 'Belle Mina');
$city_data[] = array('accid' => 'USAL0050', 'name' => 'Bellwood');
$city_data[] = array('accid' => 'USAL0051', 'name' => 'Berry');
$city_data[] = array('accid' => 'USAL0052', 'name' => 'Bessemer');
$city_data[] = array('accid' => 'USAL0053', 'name' => 'Billingsley');
$city_data[] = array('accid' => 'USAL0054', 'name' => 'Birmingham');
$city_data[] = array('accid' => 'USAL0055', 'name' => 'Black');
$city_data[] = array('accid' => 'USAL0056', 'name' => 'Blountsville');
$city_data[] = array('accid' => 'USAL0057', 'name' => 'Boaz');
$city_data[] = array('accid' => 'USAL0058', 'name' => 'Boligee');
$city_data[] = array('accid' => 'USAL0059', 'name' => 'Bon Air');
$city_data[] = array('accid' => 'USAL0060', 'name' => 'Bon Secour');
$city_data[] = array('accid' => 'USAL0061', 'name' => 'Booth');
$city_data[] = array('accid' => 'USAL0062', 'name' => 'Boykin');
$city_data[] = array('accid' => 'USAL0063', 'name' => 'Brantley');
$city_data[] = array('accid' => 'USAL0064', 'name' => 'Bremen');
$city_data[] = array('accid' => 'USAL0065', 'name' => 'Brent');
$city_data[] = array('accid' => 'USAL0066', 'name' => 'Brewton');
$city_data[] = array('accid' => 'USAL0067', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USAL0068', 'name' => 'Brierfield');
$city_data[] = array('accid' => 'USAL0069', 'name' => 'Brilliant');
$city_data[] = array('accid' => 'USAL0070', 'name' => 'Brooklyn');
$city_data[] = array('accid' => 'USAL0071', 'name' => 'Brookside');
$city_data[] = array('accid' => 'USAL0072', 'name' => 'Brookwood');
$city_data[] = array('accid' => 'USAL0073', 'name' => 'Brownsboro');
$city_data[] = array('accid' => 'USAL0074', 'name' => 'Brundidge');
$city_data[] = array('accid' => 'USAL0075', 'name' => 'Bryant');
$city_data[] = array('accid' => 'USAL0076', 'name' => 'Bucks');
$city_data[] = array('accid' => 'USAL0077', 'name' => 'Buhl');
$city_data[] = array('accid' => 'USAL0078', 'name' => 'Burnt Corn');
$city_data[] = array('accid' => 'USAL0079', 'name' => 'Burnwell');
$city_data[] = array('accid' => 'USAL0080', 'name' => 'Butler');
$city_data[] = array('accid' => 'USAL0081', 'name' => 'Bynum');
$city_data[] = array('accid' => 'USAL0082', 'name' => 'Calera');
$city_data[] = array('accid' => 'USAL0083', 'name' => 'Calvert');
$city_data[] = array('accid' => 'USAL0084', 'name' => 'Camden');
$city_data[] = array('accid' => 'USAL0085', 'name' => 'Camp Hill');
$city_data[] = array('accid' => 'USAL0086', 'name' => 'Campbell');
$city_data[] = array('accid' => 'USAL0087', 'name' => 'Capshaw');
$city_data[] = array('accid' => 'USAL0088', 'name' => 'Carbon Hill');
$city_data[] = array('accid' => 'USAL0089', 'name' => 'Cardiff');
$city_data[] = array('accid' => 'USAL0090', 'name' => 'Carlton');
$city_data[] = array('accid' => 'USAL0091', 'name' => 'Carrollton');
$city_data[] = array('accid' => 'USAL0092', 'name' => 'Castleberry');
$city_data[] = array('accid' => 'USAL0093', 'name' => 'Catherine');
$city_data[] = array('accid' => 'USAL0094', 'name' => 'Cecil');
$city_data[] = array('accid' => 'USAL0095', 'name' => 'Cedar Bluff');
$city_data[] = array('accid' => 'USAL0096', 'name' => 'Centre');
$city_data[] = array('accid' => 'USAL0097', 'name' => 'Centreville');
$city_data[] = array('accid' => 'USAL0098', 'name' => 'Chancellor');
$city_data[] = array('accid' => 'USAL0099', 'name' => 'Chapman');
$city_data[] = array('accid' => 'USAL0100', 'name' => 'Chatom');
$city_data[] = array('accid' => 'USAL0101', 'name' => 'Chelsea');
$city_data[] = array('accid' => 'USAL0102', 'name' => 'Cherokee');
$city_data[] = array('accid' => 'USAL0103', 'name' => 'Childersburg');
$city_data[] = array('accid' => 'USAL0104', 'name' => 'Choccolocco');
$city_data[] = array('accid' => 'USAL0105', 'name' => 'Chunchula');
$city_data[] = array('accid' => 'USAL0106', 'name' => 'Citronelle');
$city_data[] = array('accid' => 'USAL0107', 'name' => 'Clanton');
$city_data[] = array('accid' => 'USAL0108', 'name' => 'Clay');
$city_data[] = array('accid' => 'USAL0109', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USAL0110', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USAL0111', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USAL0112', 'name' => 'Clio');
$city_data[] = array('accid' => 'USAL0113', 'name' => 'Clopton');
$city_data[] = array('accid' => 'USAL0115', 'name' => 'Cloverdale');
$city_data[] = array('accid' => 'USAL0116', 'name' => 'Coaling');
$city_data[] = array('accid' => 'USAL0117', 'name' => 'Coden');
$city_data[] = array('accid' => 'USAL0118', 'name' => 'Coffee Springs');
$city_data[] = array('accid' => 'USAL0119', 'name' => 'Coffeeville');
$city_data[] = array('accid' => 'USAL0120', 'name' => 'Coker');
$city_data[] = array('accid' => 'USAL0121', 'name' => 'Collinsville');
$city_data[] = array('accid' => 'USAL0122', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USAL0123', 'name' => 'Columbiana');
$city_data[] = array('accid' => 'USAL0124', 'name' => 'Cook Springs');
$city_data[] = array('accid' => 'USAL0125', 'name' => 'Coosada');
$city_data[] = array('accid' => 'USAL0126', 'name' => 'Cordova');
$city_data[] = array('accid' => 'USAL0127', 'name' => 'Cottondale');
$city_data[] = array('accid' => 'USAL0128', 'name' => 'Cottonton');
$city_data[] = array('accid' => 'USAL0129', 'name' => 'Cottonwood');
$city_data[] = array('accid' => 'USAL0130', 'name' => 'Courtland');
$city_data[] = array('accid' => 'USAL0131', 'name' => 'Cowarts');
$city_data[] = array('accid' => 'USAL0132', 'name' => 'Coy');
$city_data[] = array('accid' => 'USAL0133', 'name' => 'Cragford');
$city_data[] = array('accid' => 'USAL0134', 'name' => 'Crane Hill');
$city_data[] = array('accid' => 'USAL0135', 'name' => 'Creola');
$city_data[] = array('accid' => 'USAL0136', 'name' => 'Cromwell');
$city_data[] = array('accid' => 'USAL0137', 'name' => 'Cropwell');
$city_data[] = array('accid' => 'USAL0138', 'name' => 'Crossville');
$city_data[] = array('accid' => 'USAL0139', 'name' => 'Cuba');
$city_data[] = array('accid' => 'USAL0140', 'name' => 'Cullman');
$city_data[] = array('accid' => 'USAL0141', 'name' => 'Cusseta');
$city_data[] = array('accid' => 'USAL0142', 'name' => 'Dadeville');
$city_data[] = array('accid' => 'USAL0143', 'name' => 'Daleville');
$city_data[] = array('accid' => 'USAL0144', 'name' => 'Danville');
$city_data[] = array('accid' => 'USAL0145', 'name' => 'Daphne');
$city_data[] = array('accid' => 'USAL0146', 'name' => 'Dauphin Island');
$city_data[] = array('accid' => 'USAL0147', 'name' => 'Daviston');
$city_data[] = array('accid' => 'USAL0148', 'name' => 'Dawson');
$city_data[] = array('accid' => 'USAL0149', 'name' => 'De Armanville');
$city_data[] = array('accid' => 'USAL0150', 'name' => 'Deatsville');
$city_data[] = array('accid' => 'USAL0151', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USAL0152', 'name' => 'Deer Park');
$city_data[] = array('accid' => 'USAL0153', 'name' => 'Delmar');
$city_data[] = array('accid' => 'USAL0154', 'name' => 'Delta');
$city_data[] = array('accid' => 'USAL0155', 'name' => 'Demopolis');
$city_data[] = array('accid' => 'USAL0156', 'name' => 'Detroit');
$city_data[] = array('accid' => 'USAL0157', 'name' => 'Dickinson');
$city_data[] = array('accid' => 'USAL0158', 'name' => 'Dixons Mills');
$city_data[] = array('accid' => 'USAL0159', 'name' => 'Docena');
$city_data[] = array('accid' => 'USAL0160', 'name' => 'Dolomite');
$city_data[] = array('accid' => 'USAL0161', 'name' => 'Dora');
$city_data[] = array('accid' => 'USAL0162', 'name' => 'Dothan');
$city_data[] = array('accid' => 'USAL0163', 'name' => 'Double Springs');
$city_data[] = array('accid' => 'USAL0164', 'name' => 'Douglas');
$city_data[] = array('accid' => 'USAL0165', 'name' => 'Dozier');
$city_data[] = array('accid' => 'USAL0166', 'name' => 'Duncanville');
$city_data[] = array('accid' => 'USAL0167', 'name' => 'Dutton');
$city_data[] = array('accid' => 'USAL0168', 'name' => 'East Tallassee');
$city_data[] = array('accid' => 'USAL0169', 'name' => 'Eastaboga');
$city_data[] = array('accid' => 'USAL0170', 'name' => 'Echola');
$city_data[] = array('accid' => 'USAL0171', 'name' => 'Eclectic');
$city_data[] = array('accid' => 'USAL0172', 'name' => 'Edwardsville');
$city_data[] = array('accid' => 'USAL0173', 'name' => 'Eight Mile');
$city_data[] = array('accid' => 'USAL0174', 'name' => 'Elba');
$city_data[] = array('accid' => 'USAL0175', 'name' => 'Elberta');
$city_data[] = array('accid' => 'USAL0176', 'name' => 'Eldridge');
$city_data[] = array('accid' => 'USAL0177', 'name' => 'Elkmont');
$city_data[] = array('accid' => 'USAL0178', 'name' => 'Elmore');
$city_data[] = array('accid' => 'USAL0179', 'name' => 'Elrod');
$city_data[] = array('accid' => 'USAL0180', 'name' => 'Emelle');
$city_data[] = array('accid' => 'USAL0181', 'name' => 'Empire');
$city_data[] = array('accid' => 'USAL0182', 'name' => 'Enterprise');
$city_data[] = array('accid' => 'USAL0183', 'name' => 'Epes');
$city_data[] = array('accid' => 'USAL0184', 'name' => 'Equality');
$city_data[] = array('accid' => 'USAL0185', 'name' => 'Estillfork');
$city_data[] = array('accid' => 'USAL0186', 'name' => 'Ethelsville');
$city_data[] = array('accid' => 'USAL0187', 'name' => 'Eufaula');
$city_data[] = array('accid' => 'USAL0188', 'name' => 'Eutaw');
$city_data[] = array('accid' => 'USAL0189', 'name' => 'Eva');
$city_data[] = array('accid' => 'USAL0190', 'name' => 'Evergreen');
$city_data[] = array('accid' => 'USAL0191', 'name' => 'Excel');
$city_data[] = array('accid' => 'USAL0192', 'name' => 'Fackler');
$city_data[] = array('accid' => 'USAL0193', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USAL0194', 'name' => 'Fairhope');
$city_data[] = array('accid' => 'USAL0195', 'name' => 'Falkville');
$city_data[] = array('accid' => 'USAL0196', 'name' => 'Faunsdale');
$city_data[] = array('accid' => 'USAL0197', 'name' => 'Fayette');
$city_data[] = array('accid' => 'USAL0198', 'name' => 'Fitzpatrick');
$city_data[] = array('accid' => 'USAL0199', 'name' => 'Five Points');
$city_data[] = array('accid' => 'USAL0200', 'name' => 'Flat Rock');
$city_data[] = array('accid' => 'USAL0201', 'name' => 'Flomaton');
$city_data[] = array('accid' => 'USAL0202', 'name' => 'Florala');
$city_data[] = array('accid' => 'USAL0203', 'name' => 'Florence');
$city_data[] = array('accid' => 'USAL0204', 'name' => 'Foley');
$city_data[] = array('accid' => 'USAL0205', 'name' => 'Forest Home');
$city_data[] = array('accid' => 'USAL0206', 'name' => 'Forkland');
$city_data[] = array('accid' => 'USAL0207', 'name' => 'Fort Davis');
$city_data[] = array('accid' => 'USAL0208', 'name' => 'Fort Deposit');
$city_data[] = array('accid' => 'USAL0209', 'name' => 'Fort Mitchell');
$city_data[] = array('accid' => 'USAL0210', 'name' => 'Fort Payne');
$city_data[] = array('accid' => 'USAL0211', 'name' => 'Fort Rucker');
$city_data[] = array('accid' => 'USAL0212', 'name' => 'Fosters');
$city_data[] = array('accid' => 'USAL0213', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USAL0214', 'name' => 'Frankville');
$city_data[] = array('accid' => 'USAL0215', 'name' => 'Frisco City');
$city_data[] = array('accid' => 'USAL0216', 'name' => 'Fruitdale');
$city_data[] = array('accid' => 'USAL0217', 'name' => 'Fruithurst');
$city_data[] = array('accid' => 'USAL0218', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USAL0219', 'name' => 'Fultondale');
$city_data[] = array('accid' => 'USAL0220', 'name' => 'Furman');
$city_data[] = array('accid' => 'USAL0221', 'name' => 'Fyffe');
$city_data[] = array('accid' => 'USAL0222', 'name' => 'Gadsden');
$city_data[] = array('accid' => 'USAL0223', 'name' => 'Gainestown');
$city_data[] = array('accid' => 'USAL0224', 'name' => 'Gainesville');
$city_data[] = array('accid' => 'USAL0225', 'name' => 'Gallant');
$city_data[] = array('accid' => 'USAL0226', 'name' => 'Gallion');
$city_data[] = array('accid' => 'USAL0227', 'name' => 'Gantt');
$city_data[] = array('accid' => 'USAL0228', 'name' => 'Garden City');
$city_data[] = array('accid' => 'USAL0229', 'name' => 'Gardendale');
$city_data[] = array('accid' => 'USAL0230', 'name' => 'Gaylesville');
$city_data[] = array('accid' => 'USAL0231', 'name' => 'Geneva');
$city_data[] = array('accid' => 'USAL0232', 'name' => 'Georgiana');
$city_data[] = array('accid' => 'USAL0233', 'name' => 'Geraldine');
$city_data[] = array('accid' => 'USAL0234', 'name' => 'Gilbertown');
$city_data[] = array('accid' => 'USAL0235', 'name' => 'Glen Allen');
$city_data[] = array('accid' => 'USAL0236', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USAL0237', 'name' => 'Goodsprings');
$city_data[] = array('accid' => 'USAL0238', 'name' => 'Goodwater');
$city_data[] = array('accid' => 'USAL0239', 'name' => 'Goodway');
$city_data[] = array('accid' => 'USAL0240', 'name' => 'Gordo');
$city_data[] = array('accid' => 'USAL0241', 'name' => 'Gordon');
$city_data[] = array('accid' => 'USAL0242', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USAL0243', 'name' => 'Grady');
$city_data[] = array('accid' => 'USAL0244', 'name' => 'Graham');
$city_data[] = array('accid' => 'USAL0245', 'name' => 'Grand Bay');
$city_data[] = array('accid' => 'USAL0246', 'name' => 'Grant');
$city_data[] = array('accid' => 'USAL0247', 'name' => 'Graysville');
$city_data[] = array('accid' => 'USAL0248', 'name' => 'Green Pond');
$city_data[] = array('accid' => 'USAL0249', 'name' => 'Greensboro');
$city_data[] = array('accid' => 'USAL0250', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USAL0251', 'name' => 'Grove Hill');
$city_data[] = array('accid' => 'USAL0252', 'name' => 'Groveoak');
$city_data[] = array('accid' => 'USAL0253', 'name' => 'Guin');
$city_data[] = array('accid' => 'USAL0254', 'name' => 'Gulf Shores');
$city_data[] = array('accid' => 'USAL0255', 'name' => 'Guntersville');
$city_data[] = array('accid' => 'USAL0256', 'name' => 'Gurley');
$city_data[] = array('accid' => 'USAL0257', 'name' => 'Hackleburg');
$city_data[] = array('accid' => 'USAL0258', 'name' => 'Haleyville');
$city_data[] = array('accid' => 'USAL0259', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USAL0260', 'name' => 'Hanceville');
$city_data[] = array('accid' => 'USAL0261', 'name' => 'Hardaway');
$city_data[] = array('accid' => 'USAL0262', 'name' => 'Harpersville');
$city_data[] = array('accid' => 'USAL0263', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USAL0264', 'name' => 'Hartselle');
$city_data[] = array('accid' => 'USAL0265', 'name' => 'Harvest');
$city_data[] = array('accid' => 'USAL0266', 'name' => 'Hatchechubbee');
$city_data[] = array('accid' => 'USAL0267', 'name' => 'Hayden');
$city_data[] = array('accid' => 'USAL0268', 'name' => 'Hayneville');
$city_data[] = array('accid' => 'USAL0269', 'name' => 'Hazel Green');
$city_data[] = array('accid' => 'USAL0270', 'name' => 'Headland');
$city_data[] = array('accid' => 'USAL0271', 'name' => 'Heflin');
$city_data[] = array('accid' => 'USAL0272', 'name' => 'Helena');
$city_data[] = array('accid' => 'USAL0273', 'name' => 'Henagar');
$city_data[] = array('accid' => 'USAL0274', 'name' => 'Higdon');
$city_data[] = array('accid' => 'USAL0275', 'name' => 'Highland Home');
$city_data[] = array('accid' => 'USAL0276', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USAL0277', 'name' => 'Hodges');
$city_data[] = array('accid' => 'USAL0278', 'name' => 'Hollins');
$city_data[] = array('accid' => 'USAL0279', 'name' => 'Holly Pond');
$city_data[] = array('accid' => 'USAL0280', 'name' => 'Hollytree');
$city_data[] = array('accid' => 'USAL0281', 'name' => 'Hollywood');
$city_data[] = array('accid' => 'USAL0282', 'name' => 'Holy Trinity');
$city_data[] = array('accid' => 'USAL0283', 'name' => 'Honoraville');
$city_data[] = array('accid' => 'USAL0284', 'name' => 'Hope Hull');
$city_data[] = array('accid' => 'USAL0285', 'name' => 'Horton');
$city_data[] = array('accid' => 'USAL0286', 'name' => 'Houston');
$city_data[] = array('accid' => 'USAL0287', 'name' => 'Huntsville');
$city_data[] = array('accid' => 'USAL0288', 'name' => 'Hurtsboro');
$city_data[] = array('accid' => 'USAL0289', 'name' => 'Huxford');
$city_data[] = array('accid' => 'USAL0290', 'name' => 'Ider');
$city_data[] = array('accid' => 'USAL0291', 'name' => 'Irvington');
$city_data[] = array('accid' => 'USAL0292', 'name' => 'Jachin');
$city_data[] = array('accid' => 'USAL0293', 'name' => 'Jack');
$city_data[] = array('accid' => 'USAL0294', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USAL0295', 'name' => 'Jacksons Gap');
$city_data[] = array('accid' => 'USAL0296', 'name' => 'Jacksonville');
$city_data[] = array('accid' => 'USAL0297', 'name' => 'Jasper');
$city_data[] = array('accid' => 'USAL0298', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USAL0299', 'name' => 'Jemison');
$city_data[] = array('accid' => 'USAL0300', 'name' => 'Jones');
$city_data[] = array('accid' => 'USAL0301', 'name' => 'Joppa');
$city_data[] = array('accid' => 'USAL0302', 'name' => 'Kansas');
$city_data[] = array('accid' => 'USAL0303', 'name' => 'Kellerman');
$city_data[] = array('accid' => 'USAL0304', 'name' => 'Kellyton');
$city_data[] = array('accid' => 'USAL0305', 'name' => 'Kennedy');
$city_data[] = array('accid' => 'USAL0306', 'name' => 'Kent');
$city_data[] = array('accid' => 'USAL0307', 'name' => 'Killen');
$city_data[] = array('accid' => 'USAL0308', 'name' => 'Kimberly');
$city_data[] = array('accid' => 'USAL0309', 'name' => 'Kinston');
$city_data[] = array('accid' => 'USAL0310', 'name' => 'Knoxville');
$city_data[] = array('accid' => 'USAL0311', 'name' => 'Laceys Spring');
$city_data[] = array('accid' => 'USAL0312', 'name' => 'Lafayette');
$city_data[] = array('accid' => 'USAL0313', 'name' => 'Lanett');
$city_data[] = array('accid' => 'USAL0314', 'name' => 'Langston');
$city_data[] = array('accid' => 'USAL0315', 'name' => 'Lapine');
$city_data[] = array('accid' => 'USAL0316', 'name' => 'Lawley');
$city_data[] = array('accid' => 'USAL0317', 'name' => 'Leeds');
$city_data[] = array('accid' => 'USAL0318', 'name' => 'Leesburg');
$city_data[] = array('accid' => 'USAL0319', 'name' => 'Leighton');
$city_data[] = array('accid' => 'USAL0320', 'name' => 'Lenox');
$city_data[] = array('accid' => 'USAL0321', 'name' => 'Leroy');
$city_data[] = array('accid' => 'USAL0322', 'name' => 'Lester');
$city_data[] = array('accid' => 'USAL0323', 'name' => 'Letohatchee');
$city_data[] = array('accid' => 'USAL0324', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USAL0325', 'name' => 'Lillian');
$city_data[] = array('accid' => 'USAL0326', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USAL0327', 'name' => 'Linden');
$city_data[] = array('accid' => 'USAL0328', 'name' => 'Lineville');
$city_data[] = array('accid' => 'USAL0329', 'name' => 'Lisman');
$city_data[] = array('accid' => 'USAL0330', 'name' => 'Little River');
$city_data[] = array('accid' => 'USAL0331', 'name' => 'Livingston');
$city_data[] = array('accid' => 'USAL0332', 'name' => 'Loachapoka');
$city_data[] = array('accid' => 'USAL0333', 'name' => 'Lockhart');
$city_data[] = array('accid' => 'USAL0334', 'name' => 'Locust Fork');
$city_data[] = array('accid' => 'USAL0335', 'name' => 'Logan');
$city_data[] = array('accid' => 'USAL0336', 'name' => 'Louisville');
$city_data[] = array('accid' => 'USAL0337', 'name' => 'Lower Peach Tree');
$city_data[] = array('accid' => 'USAL0338', 'name' => 'Lowndesboro');
$city_data[] = array('accid' => 'USAL0339', 'name' => 'Loxley');
$city_data[] = array('accid' => 'USAL0340', 'name' => 'Luverne');
$city_data[] = array('accid' => 'USAL0341', 'name' => 'Lynn');
$city_data[] = array('accid' => 'USAL0342', 'name' => 'Madison');
$city_data[] = array('accid' => 'USAL0343', 'name' => 'Magnolia');
$city_data[] = array('accid' => 'USAL0344', 'name' => 'Magnolia Springs');
$city_data[] = array('accid' => 'USAL0345', 'name' => 'Malcolm');
$city_data[] = array('accid' => 'USAL0346', 'name' => 'Malvern');
$city_data[] = array('accid' => 'USAL0347', 'name' => 'Maplesville');
$city_data[] = array('accid' => 'USAL0348', 'name' => 'Marbury');
$city_data[] = array('accid' => 'USAL0349', 'name' => 'Margaret');
$city_data[] = array('accid' => 'USAL0350', 'name' => 'Marion');
$city_data[] = array('accid' => 'USAL0351', 'name' => 'Marion Junction');
$city_data[] = array('accid' => 'USAL0352', 'name' => 'Mathews');
$city_data[] = array('accid' => 'USAL0353', 'name' => 'Maylene');
$city_data[] = array('accid' => 'USAL0354', 'name' => 'McCalla');
$city_data[] = array('accid' => 'USAL0355', 'name' => 'McIntosh');
$city_data[] = array('accid' => 'USAL0356', 'name' => 'McKenzie');
$city_data[] = array('accid' => 'USAL0357', 'name' => 'McShan');
$city_data[] = array('accid' => 'USAL0358', 'name' => 'McWilliams');
$city_data[] = array('accid' => 'USAL0359', 'name' => 'Megargel');
$city_data[] = array('accid' => 'USAL0360', 'name' => 'Melvin');
$city_data[] = array('accid' => 'USAL0361', 'name' => 'Mentone');
$city_data[] = array('accid' => 'USAL0362', 'name' => 'Meridianville');
$city_data[] = array('accid' => 'USAL0363', 'name' => 'Mexia');
$city_data[] = array('accid' => 'USAL0364', 'name' => 'Midland City');
$city_data[] = array('accid' => 'USAL0365', 'name' => 'Midway');
$city_data[] = array('accid' => 'USAL0366', 'name' => 'Millbrook');
$city_data[] = array('accid' => 'USAL0367', 'name' => 'Millerville');
$city_data[] = array('accid' => 'USAL0368', 'name' => 'Millport');
$city_data[] = array('accid' => 'USAL0369', 'name' => 'Millry');
$city_data[] = array('accid' => 'USAL0370', 'name' => 'Minter');
$city_data[] = array('accid' => 'USAL0371', 'name' => 'Mobile');
$city_data[] = array('accid' => 'USAL0373', 'name' => 'Monroeville');
$city_data[] = array('accid' => 'USAL0374', 'name' => 'Montevallo');
$city_data[] = array('accid' => 'USAL0375', 'name' => 'Montgomery');
$city_data[] = array('accid' => 'USAL0377', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USAL0378', 'name' => 'Moody');
$city_data[] = array('accid' => 'USAL0379', 'name' => 'Mooresville');
$city_data[] = array('accid' => 'USAL0380', 'name' => 'Morris');
$city_data[] = array('accid' => 'USAL0381', 'name' => 'Morvin');
$city_data[] = array('accid' => 'USAL0382', 'name' => 'Moulton');
$city_data[] = array('accid' => 'USAL0383', 'name' => 'Moundville');
$city_data[] = array('accid' => 'USAL0384', 'name' => 'Mount Hope');
$city_data[] = array('accid' => 'USAL0385', 'name' => 'Mount Meigs');
$city_data[] = array('accid' => 'USAL0386', 'name' => 'Mount Olive');
$city_data[] = array('accid' => 'USAL0387', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USAL0388', 'name' => 'Mulga');
$city_data[] = array('accid' => 'USAL0389', 'name' => 'Munford');
$city_data[] = array('accid' => 'USAL0390', 'name' => 'Muscadine');
$city_data[] = array('accid' => 'USAL0391', 'name' => 'Muscle Shoals');
$city_data[] = array('accid' => 'USAL0392', 'name' => 'Myrtlewood');
$city_data[] = array('accid' => 'USAL0393', 'name' => 'Nanafalia');
$city_data[] = array('accid' => 'USAL0394', 'name' => 'Natural Bridge');
$city_data[] = array('accid' => 'USAL0395', 'name' => 'Nauvoo');
$city_data[] = array('accid' => 'USAL0396', 'name' => 'Needham');
$city_data[] = array('accid' => 'USAL0397', 'name' => 'New Brockton');
$city_data[] = array('accid' => 'USAL0398', 'name' => 'New Castle');
$city_data[] = array('accid' => 'USAL0399', 'name' => 'New Hope');
$city_data[] = array('accid' => 'USAL0400', 'name' => 'New Market');
$city_data[] = array('accid' => 'USAL0401', 'name' => 'Newbern');
$city_data[] = array('accid' => 'USAL0402', 'name' => 'Newell');
$city_data[] = array('accid' => 'USAL0403', 'name' => 'Newton');
$city_data[] = array('accid' => 'USAL0404', 'name' => 'Newville');
$city_data[] = array('accid' => 'USAL0405', 'name' => 'Normal');
$city_data[] = array('accid' => 'USAL0406', 'name' => 'Northport');
$city_data[] = array('accid' => 'USAL0407', 'name' => 'Notasulga');
$city_data[] = array('accid' => 'USAL0408', 'name' => 'Oak Hill');
$city_data[] = array('accid' => 'USAL0409', 'name' => 'Oakman');
$city_data[] = array('accid' => 'USAL0410', 'name' => 'Odenville');
$city_data[] = array('accid' => 'USAL0411', 'name' => 'Ohatchee');
$city_data[] = array('accid' => 'USAL0412', 'name' => 'Oneonta');
$city_data[] = array('accid' => 'USAL0413', 'name' => 'Opelika');
$city_data[] = array('accid' => 'USAL0414', 'name' => 'Opp');
$city_data[] = array('accid' => 'USAL0415', 'name' => 'Orange Beach');
$city_data[] = array('accid' => 'USAL0416', 'name' => 'Orrville');
$city_data[] = array('accid' => 'USAL0417', 'name' => 'Owens Cross Roads');
$city_data[] = array('accid' => 'USAL0418', 'name' => 'Ozark');
$city_data[] = array('accid' => 'USAL0419', 'name' => 'Paint Rock');
$city_data[] = array('accid' => 'USAL0420', 'name' => 'Palmerdale');
$city_data[] = array('accid' => 'USAL0421', 'name' => 'Panola');
$city_data[] = array('accid' => 'USAL0422', 'name' => 'Pansey');
$city_data[] = array('accid' => 'USAL0423', 'name' => 'Parrish');
$city_data[] = array('accid' => 'USAL0424', 'name' => 'Pelham');
$city_data[] = array('accid' => 'USAL0425', 'name' => 'Pell City');
$city_data[] = array('accid' => 'USAL0426', 'name' => 'Pennington');
$city_data[] = array('accid' => 'USAL0427', 'name' => 'Perdido');
$city_data[] = array('accid' => 'USAL0428', 'name' => 'Perdue Hill');
$city_data[] = array('accid' => 'USAL0429', 'name' => 'Perote');
$city_data[] = array('accid' => 'USAL0430', 'name' => 'Peterman');
$city_data[] = array('accid' => 'USAL0431', 'name' => 'Peterson');
$city_data[] = array('accid' => 'USAL0432', 'name' => 'Petrey');
$city_data[] = array('accid' => 'USAL0433', 'name' => 'Phenix City');
$city_data[] = array('accid' => 'USAL0434', 'name' => 'Phil Campbell');
$city_data[] = array('accid' => 'USAL0435', 'name' => 'Piedmont');
$city_data[] = array('accid' => 'USAL0436', 'name' => 'Pike Road');
$city_data[] = array('accid' => 'USAL0437', 'name' => 'Pinckard');
$city_data[] = array('accid' => 'USAL0438', 'name' => 'Pine Apple');
$city_data[] = array('accid' => 'USAL0439', 'name' => 'Pine Hill');
$city_data[] = array('accid' => 'USAL0440', 'name' => 'Pine Level');
$city_data[] = array('accid' => 'USAL0441', 'name' => 'Pinson');
$city_data[] = array('accid' => 'USAL0442', 'name' => 'Pisgah');
$city_data[] = array('accid' => 'USAL0443', 'name' => 'Pittsview');
$city_data[] = array('accid' => 'USAL0444', 'name' => 'Plantersville');
$city_data[] = array('accid' => 'USAL0445', 'name' => 'Pleasant Grove');
$city_data[] = array('accid' => 'USAL0446', 'name' => 'Point Clear');
$city_data[] = array('accid' => 'USAL0447', 'name' => 'Prattville');
$city_data[] = array('accid' => 'USAL0448', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USAL0449', 'name' => 'Quinton');
$city_data[] = array('accid' => 'USAL0450', 'name' => 'Ragland');
$city_data[] = array('accid' => 'USAL0451', 'name' => 'Rainbow City');
$city_data[] = array('accid' => 'USAL0452', 'name' => 'Rainsville');
$city_data[] = array('accid' => 'USAL0453', 'name' => 'Ralph');
$city_data[] = array('accid' => 'USAL0454', 'name' => 'Ramer');
$city_data[] = array('accid' => 'USAL0455', 'name' => 'Ranburne');
$city_data[] = array('accid' => 'USAL0456', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USAL0457', 'name' => 'Range');
$city_data[] = array('accid' => 'USAL0458', 'name' => 'Red Bay');
$city_data[] = array('accid' => 'USAL0459', 'name' => 'Red Level');
$city_data[] = array('accid' => 'USAL0460', 'name' => 'Reform');
$city_data[] = array('accid' => 'USAL0461', 'name' => 'Remlap');
$city_data[] = array('accid' => 'USAL0462', 'name' => 'Repton');
$city_data[] = array('accid' => 'USAL0463', 'name' => 'River Falls');
$city_data[] = array('accid' => 'USAL0464', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USAL0465', 'name' => 'Roanoke');
$city_data[] = array('accid' => 'USAL0466', 'name' => 'Robertsdale');
$city_data[] = array('accid' => 'USAL0467', 'name' => 'Rockford');
$city_data[] = array('accid' => 'USAL0468', 'name' => 'Rogersville');
$city_data[] = array('accid' => 'USAL0469', 'name' => 'Russellville');
$city_data[] = array('accid' => 'USAL0470', 'name' => 'Rutledge');
$city_data[] = array('accid' => 'USAL0471', 'name' => 'Ryland');
$city_data[] = array('accid' => 'USAL0472', 'name' => 'Safford');
$city_data[] = array('accid' => 'USAL0473', 'name' => 'Saginaw');
$city_data[] = array('accid' => 'USAL0474', 'name' => 'Saint Elmo');
$city_data[] = array('accid' => 'USAL0475', 'name' => 'Saint Stephens');
$city_data[] = array('accid' => 'USAL0476', 'name' => 'Salem');
$city_data[] = array('accid' => 'USAL0477', 'name' => 'Salitpa');
$city_data[] = array('accid' => 'USAL0478', 'name' => 'Samantha');
$city_data[] = array('accid' => 'USAL0479', 'name' => 'Samson');
$city_data[] = array('accid' => 'USAL0480', 'name' => 'Saraland');
$city_data[] = array('accid' => 'USAL0481', 'name' => 'Sardis');
$city_data[] = array('accid' => 'USAL0482', 'name' => 'Satsuma');
$city_data[] = array('accid' => 'USAL0483', 'name' => 'Sawyerville');
$city_data[] = array('accid' => 'USAL0484', 'name' => 'Sayre');
$city_data[] = array('accid' => 'USAL0485', 'name' => 'Scottsboro');
$city_data[] = array('accid' => 'USAL0486', 'name' => 'Seale');
$city_data[] = array('accid' => 'USAL0487', 'name' => 'Section');
$city_data[] = array('accid' => 'USAL0488', 'name' => 'Selma');
$city_data[] = array('accid' => 'USAL0489', 'name' => 'Seminole');
$city_data[] = array('accid' => 'USAL0490', 'name' => 'Semmes');
$city_data[] = array('accid' => 'USAL0491', 'name' => 'Shannon');
$city_data[] = array('accid' => 'USAL0492', 'name' => 'Sheffield');
$city_data[] = array('accid' => 'USAL0493', 'name' => 'Shelby');
$city_data[] = array('accid' => 'USAL0494', 'name' => 'Shorter');
$city_data[] = array('accid' => 'USAL0495', 'name' => 'Shorterville');
$city_data[] = array('accid' => 'USAL0496', 'name' => 'Silas');
$city_data[] = array('accid' => 'USAL0497', 'name' => 'Siluria');
$city_data[] = array('accid' => 'USAL0498', 'name' => 'Silverhill');
$city_data[] = array('accid' => 'USAL0499', 'name' => 'Sipsey');
$city_data[] = array('accid' => 'USAL0500', 'name' => 'Skipperville');
$city_data[] = array('accid' => 'USAL0501', 'name' => 'Slocomb');
$city_data[] = array('accid' => 'USAL0502', 'name' => 'Smiths');
$city_data[] = array('accid' => 'USAL0503', 'name' => 'Snow Hill');
$city_data[] = array('accid' => 'USAL0504', 'name' => 'Somerville');
$city_data[] = array('accid' => 'USAL0505', 'name' => 'Spanish Fort');
$city_data[] = array('accid' => 'USAL0506', 'name' => 'Spring Garden');
$city_data[] = array('accid' => 'USAL0507', 'name' => 'Springville');
$city_data[] = array('accid' => 'USAL0508', 'name' => 'Sprott');
$city_data[] = array('accid' => 'USAL0509', 'name' => 'Spruce Pine');
$city_data[] = array('accid' => 'USAL0510', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USAL0511', 'name' => 'Stapleton');
$city_data[] = array('accid' => 'USAL0512', 'name' => 'Steele');
$city_data[] = array('accid' => 'USAL0513', 'name' => 'Sterrett');
$city_data[] = array('accid' => 'USAL0514', 'name' => 'Stevenson');
$city_data[] = array('accid' => 'USAL0515', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USAL0516', 'name' => 'Sulligent');
$city_data[] = array('accid' => 'USAL0517', 'name' => 'Sumiton');
$city_data[] = array('accid' => 'USAL0518', 'name' => 'Summerdale');
$city_data[] = array('accid' => 'USAL0519', 'name' => 'Sunflower');
$city_data[] = array('accid' => 'USAL0520', 'name' => 'Sweet Water');
$city_data[] = array('accid' => 'USAL0521', 'name' => 'Sycamore');
$city_data[] = array('accid' => 'USAL0522', 'name' => 'Sylacauga');
$city_data[] = array('accid' => 'USAL0523', 'name' => 'Sylvania');
$city_data[] = array('accid' => 'USAL0524', 'name' => 'Talladega');
$city_data[] = array('accid' => 'USAL0525', 'name' => 'Tallassee');
$city_data[] = array('accid' => 'USAL0526', 'name' => 'Tanner');
$city_data[] = array('accid' => 'USAL0527', 'name' => 'Theodore');
$city_data[] = array('accid' => 'USAL0528', 'name' => 'Thomaston');
$city_data[] = array('accid' => 'USAL0529', 'name' => 'Thomasville');
$city_data[] = array('accid' => 'USAL0530', 'name' => 'Thorsby');
$city_data[] = array('accid' => 'USAL0531', 'name' => 'Tibbie');
$city_data[] = array('accid' => 'USAL0532', 'name' => 'Titus');
$city_data[] = array('accid' => 'USAL0533', 'name' => 'Toney');
$city_data[] = array('accid' => 'USAL0534', 'name' => 'Town Creek');
$city_data[] = array('accid' => 'USAL0535', 'name' => 'Townley');
$city_data[] = array('accid' => 'USAL0536', 'name' => 'Toxey');
$city_data[] = array('accid' => 'USAL0537', 'name' => 'Trafford');
$city_data[] = array('accid' => 'USAL0538', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USAL0539', 'name' => 'Trinity');
$city_data[] = array('accid' => 'USAL0540', 'name' => 'Troy');
$city_data[] = array('accid' => 'USAL0541', 'name' => 'Trussville');
$city_data[] = array('accid' => 'USAL0542', 'name' => 'Tuscaloosa');
$city_data[] = array('accid' => 'USAL0543', 'name' => 'Tuscumbia');
$city_data[] = array('accid' => 'USAL0544', 'name' => 'Tuskegee');
$city_data[] = array('accid' => 'USAL0545', 'name' => 'Tuskegee Institute');
$city_data[] = array('accid' => 'USAL0546', 'name' => 'Tyler');
$city_data[] = array('accid' => 'USAL0547', 'name' => 'Union Grove');
$city_data[] = array('accid' => 'USAL0548', 'name' => 'Union Springs');
$city_data[] = array('accid' => 'USAL0549', 'name' => 'Uniontown');
$city_data[] = array('accid' => 'USAL0550', 'name' => 'Uriah');
$city_data[] = array('accid' => 'USAL0551', 'name' => 'Valhermoso Springs');
$city_data[] = array('accid' => 'USAL0552', 'name' => 'Valley');
$city_data[] = array('accid' => 'USAL0553', 'name' => 'Valley Head');
$city_data[] = array('accid' => 'USAL0554', 'name' => 'Vance');
$city_data[] = array('accid' => 'USAL0555', 'name' => 'Vandiver');
$city_data[] = array('accid' => 'USAL0556', 'name' => 'Verbena');
$city_data[] = array('accid' => 'USAL0557', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USAL0558', 'name' => 'Vina');
$city_data[] = array('accid' => 'USAL0559', 'name' => 'Vincent');
$city_data[] = array('accid' => 'USAL0560', 'name' => 'Vinegar Bend');
$city_data[] = array('accid' => 'USAL0561', 'name' => 'Vinemont');
$city_data[] = array('accid' => 'USAL0562', 'name' => 'Vredenburgh');
$city_data[] = array('accid' => 'USAL0563', 'name' => 'Wadley');
$city_data[] = array('accid' => 'USAL0564', 'name' => 'Wagarville');
$city_data[] = array('accid' => 'USAL0565', 'name' => 'Walker Springs');
$city_data[] = array('accid' => 'USAL0566', 'name' => 'Walnut Grove');
$city_data[] = array('accid' => 'USAL0567', 'name' => 'Ward');
$city_data[] = array('accid' => 'USAL0568', 'name' => 'Warrior');
$city_data[] = array('accid' => 'USAL0569', 'name' => 'Waterloo');
$city_data[] = array('accid' => 'USAL0570', 'name' => 'Watson');
$city_data[] = array('accid' => 'USAL0571', 'name' => 'Wattsville');
$city_data[] = array('accid' => 'USAL0572', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USAL0573', 'name' => 'Weaver');
$city_data[] = array('accid' => 'USAL0574', 'name' => 'Webb');
$city_data[] = array('accid' => 'USAL0575', 'name' => 'Wedowee');
$city_data[] = array('accid' => 'USAL0576', 'name' => 'Wellington');
$city_data[] = array('accid' => 'USAL0577', 'name' => 'Weogufka');
$city_data[] = array('accid' => 'USAL0578', 'name' => 'West Blocton');
$city_data[] = array('accid' => 'USAL0579', 'name' => 'West Greene');
$city_data[] = array('accid' => 'USAL0580', 'name' => 'Westover');
$city_data[] = array('accid' => 'USAL0581', 'name' => 'Wetumpka');
$city_data[] = array('accid' => 'USAL0582', 'name' => 'Whatley');
$city_data[] = array('accid' => 'USAL0583', 'name' => 'Wilmer');
$city_data[] = array('accid' => 'USAL0584', 'name' => 'Wilsonville');
$city_data[] = array('accid' => 'USAL0585', 'name' => 'Wilton');
$city_data[] = array('accid' => 'USAL0586', 'name' => 'Winfield');
$city_data[] = array('accid' => 'USAL0587', 'name' => 'Wing');
$city_data[] = array('accid' => 'USAL0588', 'name' => 'Woodland');
$city_data[] = array('accid' => 'USAL0589', 'name' => 'Woodstock');
$city_data[] = array('accid' => 'USAL0590', 'name' => 'Woodville');
$city_data[] = array('accid' => 'USAL0591', 'name' => 'York');

?>
