<?php

// City package for USA: Arkansas

$city_name = 'USA: Arkansas';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USAR0001', 'name' => 'Adona');
$city_data[] = array('accid' => 'USAR0002', 'name' => 'Alco');
$city_data[] = array('accid' => 'USAR0003', 'name' => 'Alexander');
$city_data[] = array('accid' => 'USAR0004', 'name' => 'Alicia');
$city_data[] = array('accid' => 'USAR0005', 'name' => 'Alix');
$city_data[] = array('accid' => 'USAR0006', 'name' => 'Alleene');
$city_data[] = array('accid' => 'USAR0007', 'name' => 'Alma');
$city_data[] = array('accid' => 'USAR0008', 'name' => 'Almyra');
$city_data[] = array('accid' => 'USAR0009', 'name' => 'Alpena');
$city_data[] = array('accid' => 'USAR0010', 'name' => 'Alpine');
$city_data[] = array('accid' => 'USAR0011', 'name' => 'Altheimer');
$city_data[] = array('accid' => 'USAR0012', 'name' => 'Altus');
$city_data[] = array('accid' => 'USAR0013', 'name' => 'Amagon');
$city_data[] = array('accid' => 'USAR0014', 'name' => 'Amity');
$city_data[] = array('accid' => 'USAR0015', 'name' => 'Antoine');
$city_data[] = array('accid' => 'USAR0016', 'name' => 'Arkadelphia');
$city_data[] = array('accid' => 'USAR0017', 'name' => 'Arkansas City');
$city_data[] = array('accid' => 'USAR0018', 'name' => 'Armorel');
$city_data[] = array('accid' => 'USAR0019', 'name' => 'Ash Flat');
$city_data[] = array('accid' => 'USAR0020', 'name' => 'Ashdown');
$city_data[] = array('accid' => 'USAR0021', 'name' => 'Atkins');
$city_data[] = array('accid' => 'USAR0022', 'name' => 'Aubrey');
$city_data[] = array('accid' => 'USAR0023', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USAR0024', 'name' => 'Austin');
$city_data[] = array('accid' => 'USAR0025', 'name' => 'Avoca');
$city_data[] = array('accid' => 'USAR0026', 'name' => 'Bald Knob');
$city_data[] = array('accid' => 'USAR0027', 'name' => 'Banks');
$city_data[] = array('accid' => 'USAR0028', 'name' => 'Barling');
$city_data[] = array('accid' => 'USAR0029', 'name' => 'Barton');
$city_data[] = array('accid' => 'USAR0031', 'name' => 'Bassett');
$city_data[] = array('accid' => 'USAR0032', 'name' => 'Bates');
$city_data[] = array('accid' => 'USAR0033', 'name' => 'Batesville');
$city_data[] = array('accid' => 'USAR0034', 'name' => 'Bauxite');
$city_data[] = array('accid' => 'USAR0035', 'name' => 'Bay');
$city_data[] = array('accid' => 'USAR0036', 'name' => 'Bearden');
$city_data[] = array('accid' => 'USAR0037', 'name' => 'Beaver');
$city_data[] = array('accid' => 'USAR0038', 'name' => 'Bee Branch');
$city_data[] = array('accid' => 'USAR0039', 'name' => 'Beebe');
$city_data[] = array('accid' => 'USAR0040', 'name' => 'Beech Grove');
$city_data[] = array('accid' => 'USAR0041', 'name' => 'Beedeville');
$city_data[] = array('accid' => 'USAR0042', 'name' => 'Beirne');
$city_data[] = array('accid' => 'USAR0043', 'name' => 'Bella Vista');
$city_data[] = array('accid' => 'USAR0044', 'name' => 'Belleville');
$city_data[] = array('accid' => 'USAR0045', 'name' => 'Ben Lomond');
$city_data[] = array('accid' => 'USAR0046', 'name' => 'Benton');
$city_data[] = array('accid' => 'USAR0047', 'name' => 'Bentonville');
$city_data[] = array('accid' => 'USAR0048', 'name' => 'Bergman');
$city_data[] = array('accid' => 'USAR0049', 'name' => 'Berryville');
$city_data[] = array('accid' => 'USAR0050', 'name' => 'Bexar');
$city_data[] = array('accid' => 'USAR0051', 'name' => 'Big Flat');
$city_data[] = array('accid' => 'USAR0052', 'name' => 'Bigelow');
$city_data[] = array('accid' => 'USAR0053', 'name' => 'Biggers');
$city_data[] = array('accid' => 'USAR0054', 'name' => 'Birdeye');
$city_data[] = array('accid' => 'USAR0055', 'name' => 'Biscoe');
$city_data[] = array('accid' => 'USAR0056', 'name' => 'Bismarck');
$city_data[] = array('accid' => 'USAR0057', 'name' => 'Black Oak');
$city_data[] = array('accid' => 'USAR0058', 'name' => 'Black Rock');
$city_data[] = array('accid' => 'USAR0059', 'name' => 'Blevins');
$city_data[] = array('accid' => 'USAR0060', 'name' => 'Blue Mountain');
$city_data[] = array('accid' => 'USAR0061', 'name' => 'Bluff City');
$city_data[] = array('accid' => 'USAR0062', 'name' => 'Bluffton');
$city_data[] = array('accid' => 'USAR0063', 'name' => 'Blytheville');
$city_data[] = array('accid' => 'USAR0064', 'name' => 'Board Camp');
$city_data[] = array('accid' => 'USAR0065', 'name' => 'Boles');
$city_data[] = array('accid' => 'USAR0066', 'name' => 'Bonnerdale');
$city_data[] = array('accid' => 'USAR0067', 'name' => 'Bono');
$city_data[] = array('accid' => 'USAR0068', 'name' => 'Booneville');
$city_data[] = array('accid' => 'USAR0069', 'name' => 'Boswell');
$city_data[] = array('accid' => 'USAR0070', 'name' => 'Bradford');
$city_data[] = array('accid' => 'USAR0071', 'name' => 'Bradley');
$city_data[] = array('accid' => 'USAR0072', 'name' => 'Branch');
$city_data[] = array('accid' => 'USAR0073', 'name' => 'Brickeys');
$city_data[] = array('accid' => 'USAR0074', 'name' => 'Briggsville');
$city_data[] = array('accid' => 'USAR0075', 'name' => 'Brinkley');
$city_data[] = array('accid' => 'USAR0076', 'name' => 'Brockwell');
$city_data[] = array('accid' => 'USAR0077', 'name' => 'Brookland');
$city_data[] = array('accid' => 'USAR0078', 'name' => 'Bryant');
$city_data[] = array('accid' => 'USAR0079', 'name' => 'Buckner');
$city_data[] = array('accid' => 'USAR0080', 'name' => 'Bull Shoals');
$city_data[] = array('accid' => 'USAR0081', 'name' => 'Burdette');
$city_data[] = array('accid' => 'USAR0082', 'name' => 'Cabot');
$city_data[] = array('accid' => 'USAR0083', 'name' => 'Caddo Gap');
$city_data[] = array('accid' => 'USAR0084', 'name' => 'Caldwell');
$city_data[] = array('accid' => 'USAR0085', 'name' => 'Cale');
$city_data[] = array('accid' => 'USAR0086', 'name' => 'Calico Rock');
$city_data[] = array('accid' => 'USAR0087', 'name' => 'Calion');
$city_data[] = array('accid' => 'USAR0088', 'name' => 'Camden');
$city_data[] = array('accid' => 'USAR0089', 'name' => 'Camp');
$city_data[] = array('accid' => 'USAR0090', 'name' => 'Canehill');
$city_data[] = array('accid' => 'USAR0091', 'name' => 'Caraway');
$city_data[] = array('accid' => 'USAR0092', 'name' => 'Carlisle');
$city_data[] = array('accid' => 'USAR0093', 'name' => 'Carthage');
$city_data[] = array('accid' => 'USAR0094', 'name' => 'Casa');
$city_data[] = array('accid' => 'USAR0095', 'name' => 'Cash');
$city_data[] = array('accid' => 'USAR0096', 'name' => 'Casscoe');
$city_data[] = array('accid' => 'USAR0097', 'name' => 'Cave City');
$city_data[] = array('accid' => 'USAR0098', 'name' => 'Cave Springs');
$city_data[] = array('accid' => 'USAR0099', 'name' => 'Cecil');
$city_data[] = array('accid' => 'USAR0100', 'name' => 'Cedarville');
$city_data[] = array('accid' => 'USAR0101', 'name' => 'Center Ridge');
$city_data[] = array('accid' => 'USAR0102', 'name' => 'Centerton');
$city_data[] = array('accid' => 'USAR0103', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USAR0104', 'name' => 'Charleston');
$city_data[] = array('accid' => 'USAR0105', 'name' => 'Charlotte');
$city_data[] = array('accid' => 'USAR0106', 'name' => 'Cherokee Village');
$city_data[] = array('accid' => 'USAR0107', 'name' => 'Cherry Valley');
$city_data[] = array('accid' => 'USAR0108', 'name' => 'Chester');
$city_data[] = array('accid' => 'USAR0109', 'name' => 'Chidester');
$city_data[] = array('accid' => 'USAR0110', 'name' => 'Choctaw');
$city_data[] = array('accid' => 'USAR0111', 'name' => 'Clarendon');
$city_data[] = array('accid' => 'USAR0112', 'name' => 'Clarkedale');
$city_data[] = array('accid' => 'USAR0113', 'name' => 'Clarkridge');
$city_data[] = array('accid' => 'USAR0114', 'name' => 'Clarksville');
$city_data[] = array('accid' => 'USAR0115', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USAR0116', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USAR0117', 'name' => 'Coal Hill');
$city_data[] = array('accid' => 'USAR0118', 'name' => 'College Station');
$city_data[] = array('accid' => 'USAR0119', 'name' => 'Colt');
$city_data[] = array('accid' => 'USAR0120', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USAR0121', 'name' => 'Combs');
$city_data[] = array('accid' => 'USAR0122', 'name' => 'Compton');
$city_data[] = array('accid' => 'USAR0123', 'name' => 'Concord');
$city_data[] = array('accid' => 'USAR0124', 'name' => 'Conway');
$city_data[] = array('accid' => 'USAR0125', 'name' => 'Cord');
$city_data[] = array('accid' => 'USAR0126', 'name' => 'Corning');
$city_data[] = array('accid' => 'USAR0127', 'name' => 'Cotter');
$city_data[] = array('accid' => 'USAR0128', 'name' => 'Cotton Plant');
$city_data[] = array('accid' => 'USAR0129', 'name' => 'Cove');
$city_data[] = array('accid' => 'USAR0130', 'name' => 'Coy');
$city_data[] = array('accid' => 'USAR0131', 'name' => 'Crawfordsville');
$city_data[] = array('accid' => 'USAR0132', 'name' => 'Crocketts Bluff');
$city_data[] = array('accid' => 'USAR0133', 'name' => 'Crossett');
$city_data[] = array('accid' => 'USAR0134', 'name' => 'Crumrod');
$city_data[] = array('accid' => 'USAR0135', 'name' => 'Curtis');
$city_data[] = array('accid' => 'USAR0136', 'name' => 'Cushman');
$city_data[] = array('accid' => 'USAR0137', 'name' => 'Damascus');
$city_data[] = array('accid' => 'USAR0138', 'name' => 'Danville');
$city_data[] = array('accid' => 'USAR0139', 'name' => 'Dardanelle');
$city_data[] = array('accid' => 'USAR0140', 'name' => 'Datto');
$city_data[] = array('accid' => 'USAR0141', 'name' => 'De Queen');
$city_data[] = array('accid' => 'USAR0142', 'name' => 'De Valls Bluff');
$city_data[] = array('accid' => 'USAR0143', 'name' => 'De Witt');
$city_data[] = array('accid' => 'USAR0144', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USAR0145', 'name' => 'Deer');
$city_data[] = array('accid' => 'USAR0146', 'name' => 'Delaplaine');
$city_data[] = array('accid' => 'USAR0147', 'name' => 'Delaware');
$city_data[] = array('accid' => 'USAR0148', 'name' => 'Delight');
$city_data[] = array('accid' => 'USAR0149', 'name' => 'Dell');
$city_data[] = array('accid' => 'USAR0150', 'name' => 'Dennard');
$city_data[] = array('accid' => 'USAR0151', 'name' => 'Dermott');
$city_data[] = array('accid' => 'USAR0152', 'name' => 'Des Arc');
$city_data[] = array('accid' => 'USAR0153', 'name' => 'Desha');
$city_data[] = array('accid' => 'USAR0154', 'name' => 'Diamond City');
$city_data[] = array('accid' => 'USAR0155', 'name' => 'Diaz');
$city_data[] = array('accid' => 'USAR0156', 'name' => 'Dierks');
$city_data[] = array('accid' => 'USAR0157', 'name' => 'Doddridge');
$city_data[] = array('accid' => 'USAR0158', 'name' => 'Dolph');
$city_data[] = array('accid' => 'USAR0159', 'name' => 'Donaldson');
$city_data[] = array('accid' => 'USAR0160', 'name' => 'Dover');
$city_data[] = array('accid' => 'USAR0161', 'name' => 'Drasco');
$city_data[] = array('accid' => 'USAR0162', 'name' => 'Driver');
$city_data[] = array('accid' => 'USAR0163', 'name' => 'Dumas');
$city_data[] = array('accid' => 'USAR0164', 'name' => 'Dyer');
$city_data[] = array('accid' => 'USAR0165', 'name' => 'Dyess');
$city_data[] = array('accid' => 'USAR0166', 'name' => 'Earle');
$city_data[] = array('accid' => 'USAR0167', 'name' => 'Edgemont');
$city_data[] = array('accid' => 'USAR0168', 'name' => 'Edmondson');
$city_data[] = array('accid' => 'USAR0169', 'name' => 'Egypt');
$city_data[] = array('accid' => 'USAR0170', 'name' => 'El Dorado');
$city_data[] = array('accid' => 'USAR0171', 'name' => 'El Paso');
$city_data[] = array('accid' => 'USAR0172', 'name' => 'Elaine');
$city_data[] = array('accid' => 'USAR0173', 'name' => 'Elizabeth');
$city_data[] = array('accid' => 'USAR0174', 'name' => 'Elkins');
$city_data[] = array('accid' => 'USAR0175', 'name' => 'Elm Springs');
$city_data[] = array('accid' => 'USAR0176', 'name' => 'Emerson');
$city_data[] = array('accid' => 'USAR0177', 'name' => 'Emmet');
$city_data[] = array('accid' => 'USAR0178', 'name' => 'England');
$city_data[] = array('accid' => 'USAR0179', 'name' => 'Enola');
$city_data[] = array('accid' => 'USAR0180', 'name' => 'Ethel');
$city_data[] = array('accid' => 'USAR0181', 'name' => 'Etowah');
$city_data[] = array('accid' => 'USAR0182', 'name' => 'Eudora');
$city_data[] = array('accid' => 'USAR0183', 'name' => 'Eureka Springs');
$city_data[] = array('accid' => 'USAR0184', 'name' => 'Evansville');
$city_data[] = array('accid' => 'USAR0185', 'name' => 'Evening Shade');
$city_data[] = array('accid' => 'USAR0186', 'name' => 'Everton');
$city_data[] = array('accid' => 'USAR0187', 'name' => 'Fairfield Bay');
$city_data[] = array('accid' => 'USAR0188', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USAR0189', 'name' => 'Fayetteville');
$city_data[] = array('accid' => 'USAR0190', 'name' => 'Fifty Six');
$city_data[] = array('accid' => 'USAR0191', 'name' => 'Fisher');
$city_data[] = array('accid' => 'USAR0192', 'name' => 'Flippin');
$city_data[] = array('accid' => 'USAR0193', 'name' => 'Floral');
$city_data[] = array('accid' => 'USAR0194', 'name' => 'Fordyce');
$city_data[] = array('accid' => 'USAR0195', 'name' => 'Foreman');
$city_data[] = array('accid' => 'USAR0196', 'name' => 'Forrest City');
$city_data[] = array('accid' => 'USAR0197', 'name' => 'Fort Smith');
$city_data[] = array('accid' => 'USAR0198', 'name' => 'Fouke');
$city_data[] = array('accid' => 'USAR0199', 'name' => 'Fountain Hill');
$city_data[] = array('accid' => 'USAR0200', 'name' => 'Fox');
$city_data[] = array('accid' => 'USAR0201', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USAR0202', 'name' => 'Frenchmans Bayou');
$city_data[] = array('accid' => 'USAR0203', 'name' => 'Friendship');
$city_data[] = array('accid' => 'USAR0204', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USAR0205', 'name' => 'Gamaliel');
$city_data[] = array('accid' => 'USAR0206', 'name' => 'Garfield');
$city_data[] = array('accid' => 'USAR0207', 'name' => 'Garland City');
$city_data[] = array('accid' => 'USAR0208', 'name' => 'Garner');
$city_data[] = array('accid' => 'USAR0209', 'name' => 'Gassville');
$city_data[] = array('accid' => 'USAR0210', 'name' => 'Gateway');
$city_data[] = array('accid' => 'USAR0211', 'name' => 'Genoa');
$city_data[] = array('accid' => 'USAR0212', 'name' => 'Gentry');
$city_data[] = array('accid' => 'USAR0213', 'name' => 'Gepp');
$city_data[] = array('accid' => 'USAR0214', 'name' => 'Gilbert');
$city_data[] = array('accid' => 'USAR0215', 'name' => 'Gillett');
$city_data[] = array('accid' => 'USAR0216', 'name' => 'Gillham');
$city_data[] = array('accid' => 'USAR0217', 'name' => 'Gilmore');
$city_data[] = array('accid' => 'USAR0218', 'name' => 'Glencoe');
$city_data[] = array('accid' => 'USAR0219', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USAR0220', 'name' => 'Goodwin');
$city_data[] = array('accid' => 'USAR0221', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USAR0222', 'name' => 'Gosnell');
$city_data[] = array('accid' => 'USAR0223', 'name' => 'Gould');
$city_data[] = array('accid' => 'USAR0224', 'name' => 'Grady');
$city_data[] = array('accid' => 'USAR0225', 'name' => 'Grannis');
$city_data[] = array('accid' => 'USAR0226', 'name' => 'Grapevine');
$city_data[] = array('accid' => 'USAR0227', 'name' => 'Gravelly');
$city_data[] = array('accid' => 'USAR0228', 'name' => 'Gravette');
$city_data[] = array('accid' => 'USAR0229', 'name' => 'Green Forest');
$city_data[] = array('accid' => 'USAR0230', 'name' => 'Greenbrier');
$city_data[] = array('accid' => 'USAR0231', 'name' => 'Greenland');
$city_data[] = array('accid' => 'USAR0232', 'name' => 'Greenway');
$city_data[] = array('accid' => 'USAR0233', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USAR0234', 'name' => 'Gregory');
$city_data[] = array('accid' => 'USAR0235', 'name' => 'Griffithville');
$city_data[] = array('accid' => 'USAR0236', 'name' => 'Grubbs');
$city_data[] = array('accid' => 'USAR0237', 'name' => 'Guion');
$city_data[] = array('accid' => 'USAR0238', 'name' => 'Gurdon');
$city_data[] = array('accid' => 'USAR0239', 'name' => 'Guy');
$city_data[] = array('accid' => 'USAR0240', 'name' => 'Hackett');
$city_data[] = array('accid' => 'USAR0241', 'name' => 'Hagarville');
$city_data[] = array('accid' => 'USAR0242', 'name' => 'Hamburg');
$city_data[] = array('accid' => 'USAR0243', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USAR0244', 'name' => 'Hardy');
$city_data[] = array('accid' => 'USAR0245', 'name' => 'Harrell');
$city_data[] = array('accid' => 'USAR0246', 'name' => 'Harriet');
$city_data[] = array('accid' => 'USAR0247', 'name' => 'Harrisburg');
$city_data[] = array('accid' => 'USAR0248', 'name' => 'Harrison');
$city_data[] = array('accid' => 'USAR0249', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USAR0250', 'name' => 'Hartman');
$city_data[] = array('accid' => 'USAR0251', 'name' => 'Harvey');
$city_data[] = array('accid' => 'USAR0252', 'name' => 'Hasty');
$city_data[] = array('accid' => 'USAR0253', 'name' => 'Hatfield');
$city_data[] = array('accid' => 'USAR0254', 'name' => 'Hattieville');
$city_data[] = array('accid' => 'USAR0255', 'name' => 'Hatton');
$city_data[] = array('accid' => 'USAR0256', 'name' => 'Havana');
$city_data[] = array('accid' => 'USAR0257', 'name' => 'Haynes');
$city_data[] = array('accid' => 'USAR0258', 'name' => 'Hazen');
$city_data[] = array('accid' => 'USAR0259', 'name' => 'Heber Springs');
$city_data[] = array('accid' => 'USAR0260', 'name' => 'Hector');
$city_data[] = array('accid' => 'USAR0261', 'name' => 'Helena');
$city_data[] = array('accid' => 'USAR0262', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USAR0263', 'name' => 'Hensley');
$city_data[] = array('accid' => 'USAR0264', 'name' => 'Hermitage');
$city_data[] = array('accid' => 'USAR0265', 'name' => 'Heth');
$city_data[] = array('accid' => 'USAR0266', 'name' => 'Hickory Plains');
$city_data[] = array('accid' => 'USAR0267', 'name' => 'Hickory Ridge');
$city_data[] = array('accid' => 'USAR0268', 'name' => 'Higden');
$city_data[] = array('accid' => 'USAR0269', 'name' => 'Higginson');
$city_data[] = array('accid' => 'USAR0270', 'name' => 'Hindsville');
$city_data[] = array('accid' => 'USAR0271', 'name' => 'Hiwasse');
$city_data[] = array('accid' => 'USAR0272', 'name' => 'Holly Grove');
$city_data[] = array('accid' => 'USAR0273', 'name' => 'Hope');
$city_data[] = array('accid' => 'USAR0274', 'name' => 'Horatio');
$city_data[] = array('accid' => 'USAR0275', 'name' => 'Horseshoe Bend');
$city_data[] = array('accid' => 'USAR0277', 'name' => 'Hot Springs Natl Park');
$city_data[] = array('accid' => 'USAR0278', 'name' => 'Hot Springs Village');
$city_data[] = array('accid' => 'USAR0279', 'name' => 'Houston');
$city_data[] = array('accid' => 'USAR0280', 'name' => 'Howell');
$city_data[] = array('accid' => 'USAR0281', 'name' => 'Hoxie');
$city_data[] = array('accid' => 'USAR0282', 'name' => 'Hughes');
$city_data[] = array('accid' => 'USAR0283', 'name' => 'Humnoke');
$city_data[] = array('accid' => 'USAR0284', 'name' => 'Humphrey');
$city_data[] = array('accid' => 'USAR0285', 'name' => 'Hunter');
$city_data[] = array('accid' => 'USAR0286', 'name' => 'Huntington');
$city_data[] = array('accid' => 'USAR0287', 'name' => 'Huntsville');
$city_data[] = array('accid' => 'USAR0288', 'name' => 'Huttig');
$city_data[] = array('accid' => 'USAR0289', 'name' => 'Ida');
$city_data[] = array('accid' => 'USAR0290', 'name' => 'Imboden');
$city_data[] = array('accid' => 'USAR0291', 'name' => 'Ivan');
$city_data[] = array('accid' => 'USAR0292', 'name' => 'Jacksonport');
$city_data[] = array('accid' => 'USAR0293', 'name' => 'Jacksonville');
$city_data[] = array('accid' => 'USAR0294', 'name' => 'Jasper');
$city_data[] = array('accid' => 'USAR0295', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USAR0296', 'name' => 'Jennie');
$city_data[] = array('accid' => 'USAR0297', 'name' => 'Jerome');
$city_data[] = array('accid' => 'USAR0298', 'name' => 'Jersey');
$city_data[] = array('accid' => 'USAR0299', 'name' => 'Jerusalem');
$city_data[] = array('accid' => 'USAR0300', 'name' => 'Jessieville');
$city_data[] = array('accid' => 'USAR0301', 'name' => 'Johnson');
$city_data[] = array('accid' => 'USAR0302', 'name' => 'Joiner');
$city_data[] = array('accid' => 'USAR0303', 'name' => 'Jones Mill');
$city_data[] = array('accid' => 'USAR0304', 'name' => 'Jonesboro');
$city_data[] = array('accid' => 'USAR0305', 'name' => 'Judsonia');
$city_data[] = array('accid' => 'USAR0306', 'name' => 'Junction City');
$city_data[] = array('accid' => 'USAR0307', 'name' => 'Keiser');
$city_data[] = array('accid' => 'USAR0308', 'name' => 'Kensett');
$city_data[] = array('accid' => 'USAR0309', 'name' => 'Keo');
$city_data[] = array('accid' => 'USAR0310', 'name' => 'Kingsland');
$city_data[] = array('accid' => 'USAR0311', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USAR0312', 'name' => 'Kirby');
$city_data[] = array('accid' => 'USAR0313', 'name' => 'Knobel');
$city_data[] = array('accid' => 'USAR0314', 'name' => 'Knoxville');
$city_data[] = array('accid' => 'USAR0315', 'name' => 'La Grange');
$city_data[] = array('accid' => 'USAR0316', 'name' => 'Lafe');
$city_data[] = array('accid' => 'USAR0317', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USAR0318', 'name' => 'Lake Village');
$city_data[] = array('accid' => 'USAR0319', 'name' => 'Lakeview');
$city_data[] = array('accid' => 'USAR0320', 'name' => 'Lamar');
$city_data[] = array('accid' => 'USAR0321', 'name' => 'Lambrook');
$city_data[] = array('accid' => 'USAR0322', 'name' => 'Laneburg');
$city_data[] = array('accid' => 'USAR0323', 'name' => 'Langley');
$city_data[] = array('accid' => 'USAR0324', 'name' => 'Lavaca');
$city_data[] = array('accid' => 'USAR0325', 'name' => 'Lawson');
$city_data[] = array('accid' => 'USAR0326', 'name' => 'Leachville');
$city_data[] = array('accid' => 'USAR0327', 'name' => 'Lead Hill');
$city_data[] = array('accid' => 'USAR0328', 'name' => 'Leola');
$city_data[] = array('accid' => 'USAR0329', 'name' => 'Lepanto');
$city_data[] = array('accid' => 'USAR0330', 'name' => 'Leslie');
$city_data[] = array('accid' => 'USAR0331', 'name' => 'Letona');
$city_data[] = array('accid' => 'USAR0332', 'name' => 'Lewisville');
$city_data[] = array('accid' => 'USAR0333', 'name' => 'Lexa');
$city_data[] = array('accid' => 'USAR0334', 'name' => 'Light');
$city_data[] = array('accid' => 'USAR0335', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USAR0336', 'name' => 'Little Rock');
$city_data[] = array('accid' => 'USAR0337', 'name' => 'Little Rock AFB');
$city_data[] = array('accid' => 'USAR0338', 'name' => 'Lockesburg');
$city_data[] = array('accid' => 'USAR0339', 'name' => 'Locust Grove');
$city_data[] = array('accid' => 'USAR0340', 'name' => 'London');
$city_data[] = array('accid' => 'USAR0341', 'name' => 'Lonoke');
$city_data[] = array('accid' => 'USAR0342', 'name' => 'Lonsdale');
$city_data[] = array('accid' => 'USAR0343', 'name' => 'Louann');
$city_data[] = array('accid' => 'USAR0344', 'name' => 'Lowell');
$city_data[] = array('accid' => 'USAR0345', 'name' => 'Luxora');
$city_data[] = array('accid' => 'USAR0346', 'name' => 'Lynn');
$city_data[] = array('accid' => 'USAR0347', 'name' => 'Mabelvale');
$city_data[] = array('accid' => 'USAR0348', 'name' => 'Madison');
$city_data[] = array('accid' => 'USAR0349', 'name' => 'Magazine');
$city_data[] = array('accid' => 'USAR0350', 'name' => 'Magness');
$city_data[] = array('accid' => 'USAR0351', 'name' => 'Magnolia');
$city_data[] = array('accid' => 'USAR0352', 'name' => 'Malvern');
$city_data[] = array('accid' => 'USAR0353', 'name' => 'Mammoth Spring');
$city_data[] = array('accid' => 'USAR0354', 'name' => 'Manila');
$city_data[] = array('accid' => 'USAR0355', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'USAR0356', 'name' => 'Marble Falls');
$city_data[] = array('accid' => 'USAR0357', 'name' => 'Marcella');
$city_data[] = array('accid' => 'USAR0358', 'name' => 'Marianna');
$city_data[] = array('accid' => 'USAR0359', 'name' => 'Marion');
$city_data[] = array('accid' => 'USAR0360', 'name' => 'Marked Tree');
$city_data[] = array('accid' => 'USAR0361', 'name' => 'Marmaduke');
$city_data[] = array('accid' => 'USAR0362', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USAR0363', 'name' => 'Marvell');
$city_data[] = array('accid' => 'USAR0364', 'name' => 'Maumelle');
$city_data[] = array('accid' => 'USAR0365', 'name' => 'Mayflower');
$city_data[] = array('accid' => 'USAR0366', 'name' => 'Maynard');
$city_data[] = array('accid' => 'USAR0367', 'name' => 'Maysville');
$city_data[] = array('accid' => 'USAR0368', 'name' => 'McCaskill');
$city_data[] = array('accid' => 'USAR0369', 'name' => 'McCrory');
$city_data[] = array('accid' => 'USAR0370', 'name' => 'McDougal');
$city_data[] = array('accid' => 'USAR0371', 'name' => 'McGehee');
$city_data[] = array('accid' => 'USAR0372', 'name' => 'McNeil');
$city_data[] = array('accid' => 'USAR0373', 'name' => 'McRae');
$city_data[] = array('accid' => 'USAR0374', 'name' => 'Melbourne');
$city_data[] = array('accid' => 'USAR0375', 'name' => 'Mellwood');
$city_data[] = array('accid' => 'USAR0376', 'name' => 'Mena');
$city_data[] = array('accid' => 'USAR0377', 'name' => 'Menifee');
$city_data[] = array('accid' => 'USAR0378', 'name' => 'Midland');
$city_data[] = array('accid' => 'USAR0379', 'name' => 'Midway');
$city_data[] = array('accid' => 'USAR0380', 'name' => 'Mineral Springs');
$city_data[] = array('accid' => 'USAR0381', 'name' => 'Minturn');
$city_data[] = array('accid' => 'USAR0382', 'name' => 'Moko');
$city_data[] = array('accid' => 'USAR0383', 'name' => 'Monette');
$city_data[] = array('accid' => 'USAR0384', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USAR0385', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USAR0386', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USAR0387', 'name' => 'Moro');
$city_data[] = array('accid' => 'USAR0388', 'name' => 'Morrilton');
$city_data[] = array('accid' => 'USAR0389', 'name' => 'Morrow');
$city_data[] = array('accid' => 'USAR0390', 'name' => 'Moscow');
$city_data[] = array('accid' => 'USAR0391', 'name' => 'Mount Holly');
$city_data[] = array('accid' => 'USAR0392', 'name' => 'Mount Ida');
$city_data[] = array('accid' => 'USAR0393', 'name' => 'Mount Judea');
$city_data[] = array('accid' => 'USAR0394', 'name' => 'Mount Pleasant');
$city_data[] = array('accid' => 'USAR0395', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USAR0396', 'name' => 'Mountain Home');
$city_data[] = array('accid' => 'USAR0397', 'name' => 'Mountain Pine');
$city_data[] = array('accid' => 'USAR0398', 'name' => 'Mountain View');
$city_data[] = array('accid' => 'USAR0399', 'name' => 'Mountainburg');
$city_data[] = array('accid' => 'USAR0400', 'name' => 'Mulberry');
$city_data[] = array('accid' => 'USAR0401', 'name' => 'Murfreesboro');
$city_data[] = array('accid' => 'USAR0402', 'name' => 'Nashville');
$city_data[] = array('accid' => 'USAR0403', 'name' => 'Natural Dam');
$city_data[] = array('accid' => 'USAR0404', 'name' => 'New Blaine');
$city_data[] = array('accid' => 'USAR0405', 'name' => 'New Edinburg');
$city_data[] = array('accid' => 'USAR0406', 'name' => 'Newark');
$city_data[] = array('accid' => 'USAR0407', 'name' => 'Newhope');
$city_data[] = array('accid' => 'USAR0408', 'name' => 'Newport');
$city_data[] = array('accid' => 'USAR0409', 'name' => 'Norfork');
$city_data[] = array('accid' => 'USAR0410', 'name' => 'Norman');
$city_data[] = array('accid' => 'USAR0411', 'name' => 'Norphlet');
$city_data[] = array('accid' => 'USAR0412', 'name' => 'North Little Rock');
$city_data[] = array('accid' => 'USAR0419', 'name' => 'O\'kean');
$city_data[] = array('accid' => 'USAR0413', 'name' => 'Oak Grove');
$city_data[] = array('accid' => 'USAR0414', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USAR0415', 'name' => 'Oark');
$city_data[] = array('accid' => 'USAR0416', 'name' => 'Oden');
$city_data[] = array('accid' => 'USAR0417', 'name' => 'Ogden');
$city_data[] = array('accid' => 'USAR0418', 'name' => 'Oil Trough');
$city_data[] = array('accid' => 'USAR0420', 'name' => 'Okolona');
$city_data[] = array('accid' => 'USAR0421', 'name' => 'Ola');
$city_data[] = array('accid' => 'USAR0422', 'name' => 'Omaha');
$city_data[] = array('accid' => 'USAR0423', 'name' => 'Oneida');
$city_data[] = array('accid' => 'USAR0424', 'name' => 'Onia');
$city_data[] = array('accid' => 'USAR0425', 'name' => 'Osceola');
$city_data[] = array('accid' => 'USAR0426', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USAR0427', 'name' => 'Ozan');
$city_data[] = array('accid' => 'USAR0428', 'name' => 'Ozark');
$city_data[] = array('accid' => 'USAR0429', 'name' => 'Ozone');
$city_data[] = array('accid' => 'USAR0430', 'name' => 'Palestine');
$city_data[] = array('accid' => 'USAR0431', 'name' => 'Pangburn');
$city_data[] = array('accid' => 'USAR0432', 'name' => 'Paragould');
$city_data[] = array('accid' => 'USAR0433', 'name' => 'Paris');
$city_data[] = array('accid' => 'USAR0434', 'name' => 'Parkdale');
$city_data[] = array('accid' => 'USAR0435', 'name' => 'Parkin');
$city_data[] = array('accid' => 'USAR0436', 'name' => 'Parks');
$city_data[] = array('accid' => 'USAR0437', 'name' => 'Paron');
$city_data[] = array('accid' => 'USAR0438', 'name' => 'Parthenon');
$city_data[] = array('accid' => 'USAR0439', 'name' => 'Patterson');
$city_data[] = array('accid' => 'USAR0440', 'name' => 'Pea Ridge');
$city_data[] = array('accid' => 'USAR0441', 'name' => 'Peach Orchard');
$city_data[] = array('accid' => 'USAR0442', 'name' => 'Pearcy');
$city_data[] = array('accid' => 'USAR0443', 'name' => 'Peel');
$city_data[] = array('accid' => 'USAR0444', 'name' => 'Pelsor');
$city_data[] = array('accid' => 'USAR0445', 'name' => 'Pencil Bluff');
$city_data[] = array('accid' => 'USAR0446', 'name' => 'Perry');
$city_data[] = array('accid' => 'USAR0447', 'name' => 'Perryville');
$city_data[] = array('accid' => 'USAR0448', 'name' => 'Pettigrew');
$city_data[] = array('accid' => 'USAR0449', 'name' => 'Pickens');
$city_data[] = array('accid' => 'USAR0450', 'name' => 'Piggott');
$city_data[] = array('accid' => 'USAR0451', 'name' => 'Pindall');
$city_data[] = array('accid' => 'USAR0452', 'name' => 'Pine Bluff');
$city_data[] = array('accid' => 'USAR0453', 'name' => 'Pineville');
$city_data[] = array('accid' => 'USAR0454', 'name' => 'Plainview');
$city_data[] = array('accid' => 'USAR0455', 'name' => 'Pleasant Grove');
$city_data[] = array('accid' => 'USAR0456', 'name' => 'Pleasant Plains');
$city_data[] = array('accid' => 'USAR0457', 'name' => 'Plumerville');
$city_data[] = array('accid' => 'USAR0458', 'name' => 'Pocahontas');
$city_data[] = array('accid' => 'USAR0459', 'name' => 'Pollard');
$city_data[] = array('accid' => 'USAR0460', 'name' => 'Ponca');
$city_data[] = array('accid' => 'USAR0461', 'name' => 'Poplar Grove');
$city_data[] = array('accid' => 'USAR0462', 'name' => 'Portia');
$city_data[] = array('accid' => 'USAR0463', 'name' => 'Portland');
$city_data[] = array('accid' => 'USAR0464', 'name' => 'Pottsville');
$city_data[] = array('accid' => 'USAR0465', 'name' => 'Poughkeepsie');
$city_data[] = array('accid' => 'USAR0466', 'name' => 'Powhatan');
$city_data[] = array('accid' => 'USAR0467', 'name' => 'Poyen');
$city_data[] = array('accid' => 'USAR0468', 'name' => 'Prairie Grove');
$city_data[] = array('accid' => 'USAR0469', 'name' => 'Prattsville');
$city_data[] = array('accid' => 'USAR0470', 'name' => 'Prescott');
$city_data[] = array('accid' => 'USAR0471', 'name' => 'Prim');
$city_data[] = array('accid' => 'USAR0472', 'name' => 'Proctor');
$city_data[] = array('accid' => 'USAR0473', 'name' => 'Pyatt');
$city_data[] = array('accid' => 'USAR0474', 'name' => 'Quitman');
$city_data[] = array('accid' => 'USAR0475', 'name' => 'Ratcliff');
$city_data[] = array('accid' => 'USAR0476', 'name' => 'Ravenden');
$city_data[] = array('accid' => 'USAR0477', 'name' => 'Ravenden Springs');
$city_data[] = array('accid' => 'USAR0478', 'name' => 'Rector');
$city_data[] = array('accid' => 'USAR0479', 'name' => 'Redfield');
$city_data[] = array('accid' => 'USAR0480', 'name' => 'Reydell');
$city_data[] = array('accid' => 'USAR0481', 'name' => 'Reyno');
$city_data[] = array('accid' => 'USAR0482', 'name' => 'Rison');
$city_data[] = array('accid' => 'USAR0483', 'name' => 'Rivervale');
$city_data[] = array('accid' => 'USAR0484', 'name' => 'Roe');
$city_data[] = array('accid' => 'USAR0485', 'name' => 'Rogers');
$city_data[] = array('accid' => 'USAR0486', 'name' => 'Roland');
$city_data[] = array('accid' => 'USAR0487', 'name' => 'Romance');
$city_data[] = array('accid' => 'USAR0488', 'name' => 'Rose Bud');
$city_data[] = array('accid' => 'USAR0489', 'name' => 'Rosie');
$city_data[] = array('accid' => 'USAR0490', 'name' => 'Rosston');
$city_data[] = array('accid' => 'USAR0491', 'name' => 'Rover');
$city_data[] = array('accid' => 'USAR0492', 'name' => 'Royal');
$city_data[] = array('accid' => 'USAR0493', 'name' => 'Rudy');
$city_data[] = array('accid' => 'USAR0494', 'name' => 'Russell');
$city_data[] = array('accid' => 'USAR0495', 'name' => 'Russellville');
$city_data[] = array('accid' => 'USAR0496', 'name' => 'Saffell');
$city_data[] = array('accid' => 'USAR0497', 'name' => 'Sage');
$city_data[] = array('accid' => 'USAR0498', 'name' => 'Saint Charles');
$city_data[] = array('accid' => 'USAR0499', 'name' => 'Saint Francis');
$city_data[] = array('accid' => 'USAR0500', 'name' => 'Saint Joe');
$city_data[] = array('accid' => 'USAR0501', 'name' => 'Saint Paul');
$city_data[] = array('accid' => 'USAR0502', 'name' => 'Salado');
$city_data[] = array('accid' => 'USAR0503', 'name' => 'Salem');
$city_data[] = array('accid' => 'USAR0504', 'name' => 'Saratoga');
$city_data[] = array('accid' => 'USAR0505', 'name' => 'Scotland');
$city_data[] = array('accid' => 'USAR0506', 'name' => 'Scott');
$city_data[] = array('accid' => 'USAR0507', 'name' => 'Scranton');
$city_data[] = array('accid' => 'USAR0508', 'name' => 'Searcy');
$city_data[] = array('accid' => 'USAR0509', 'name' => 'Sedgwick');
$city_data[] = array('accid' => 'USAR0510', 'name' => 'Sheridan');
$city_data[] = array('accid' => 'USAR0511', 'name' => 'Sherrill');
$city_data[] = array('accid' => 'USAR0512', 'name' => 'Sherwood');
$city_data[] = array('accid' => 'USAR0513', 'name' => 'Shirley');
$city_data[] = array('accid' => 'USAR0514', 'name' => 'Sidney');
$city_data[] = array('accid' => 'USAR0515', 'name' => 'Siloam Springs');
$city_data[] = array('accid' => 'USAR0516', 'name' => 'Sims');
$city_data[] = array('accid' => 'USAR0517', 'name' => 'Smackover');
$city_data[] = array('accid' => 'USAR0518', 'name' => 'Smithville');
$city_data[] = array('accid' => 'USAR0519', 'name' => 'Snow Lake');
$city_data[] = array('accid' => 'USAR0520', 'name' => 'Solgohachia');
$city_data[] = array('accid' => 'USAR0521', 'name' => 'Sparkman');
$city_data[] = array('accid' => 'USAR0522', 'name' => 'Springdale');
$city_data[] = array('accid' => 'USAR0523', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USAR0524', 'name' => 'Stamps');
$city_data[] = array('accid' => 'USAR0525', 'name' => 'Star City');
$city_data[] = array('accid' => 'USAR0526', 'name' => 'State University');
$city_data[] = array('accid' => 'USAR0527', 'name' => 'Stephens');
$city_data[] = array('accid' => 'USAR0529', 'name' => 'Story');
$city_data[] = array('accid' => 'USAR0530', 'name' => 'Strawberry');
$city_data[] = array('accid' => 'USAR0531', 'name' => 'Strong');
$city_data[] = array('accid' => 'USAR0532', 'name' => 'Sturkie');
$city_data[] = array('accid' => 'USAR0533', 'name' => 'Stuttgart');
$city_data[] = array('accid' => 'USAR0534', 'name' => 'Subiaco');
$city_data[] = array('accid' => 'USAR0535', 'name' => 'Success');
$city_data[] = array('accid' => 'USAR0536', 'name' => 'Sulphur Rock');
$city_data[] = array('accid' => 'USAR0537', 'name' => 'Sulphur Springs');
$city_data[] = array('accid' => 'USAR0538', 'name' => 'Summers');
$city_data[] = array('accid' => 'USAR0539', 'name' => 'Summit');
$city_data[] = array('accid' => 'USAR0540', 'name' => 'Sweet Home');
$city_data[] = array('accid' => 'USAR0541', 'name' => 'Swifton');
$city_data[] = array('accid' => 'USAR0542', 'name' => 'Taylor');
$city_data[] = array('accid' => 'USAR0543', 'name' => 'Texarkana');
$city_data[] = array('accid' => 'USAR0544', 'name' => 'Thida');
$city_data[] = array('accid' => 'USAR0545', 'name' => 'Thornton');
$city_data[] = array('accid' => 'USAR0546', 'name' => 'Tichnor');
$city_data[] = array('accid' => 'USAR0547', 'name' => 'Tillar');
$city_data[] = array('accid' => 'USAR0548', 'name' => 'Tilly');
$city_data[] = array('accid' => 'USAR0549', 'name' => 'Timbo');
$city_data[] = array('accid' => 'USAR0550', 'name' => 'Tomato');
$city_data[] = array('accid' => 'USAR0551', 'name' => 'Tontitown');
$city_data[] = array('accid' => 'USAR0552', 'name' => 'Traskwood');
$city_data[] = array('accid' => 'USAR0553', 'name' => 'Trumann');
$city_data[] = array('accid' => 'USAR0554', 'name' => 'Tucker');
$city_data[] = array('accid' => 'USAR0555', 'name' => 'Tuckerman');
$city_data[] = array('accid' => 'USAR0556', 'name' => 'Tumbling Shoals');
$city_data[] = array('accid' => 'USAR0557', 'name' => 'Tupelo');
$city_data[] = array('accid' => 'USAR0558', 'name' => 'Turner');
$city_data[] = array('accid' => 'USAR0559', 'name' => 'Turrell');
$city_data[] = array('accid' => 'USAR0560', 'name' => 'Twist');
$city_data[] = array('accid' => 'USAR0561', 'name' => 'Tyronza');
$city_data[] = array('accid' => 'USAR0562', 'name' => 'Ulm');
$city_data[] = array('accid' => 'USAR0563', 'name' => 'Umpire');
$city_data[] = array('accid' => 'USAR0564', 'name' => 'Uniontown');
$city_data[] = array('accid' => 'USAR0565', 'name' => 'Urbana');
$city_data[] = array('accid' => 'USAR0566', 'name' => 'Valley Springs');
$city_data[] = array('accid' => 'USAR0567', 'name' => 'Van Buren');
$city_data[] = array('accid' => 'USAR0568', 'name' => 'Vandervoort');
$city_data[] = array('accid' => 'USAR0569', 'name' => 'Vanndale');
$city_data[] = array('accid' => 'USAR0570', 'name' => 'Vendor');
$city_data[] = array('accid' => 'USAR0571', 'name' => 'Village');
$city_data[] = array('accid' => 'USAR0572', 'name' => 'Vilonia');
$city_data[] = array('accid' => 'USAR0573', 'name' => 'Viola');
$city_data[] = array('accid' => 'USAR0574', 'name' => 'Violet Hill');
$city_data[] = array('accid' => 'USAR0575', 'name' => 'Wabash');
$city_data[] = array('accid' => 'USAR0576', 'name' => 'Wabbaseka');
$city_data[] = array('accid' => 'USAR0577', 'name' => 'Walcott');
$city_data[] = array('accid' => 'USAR0578', 'name' => 'Waldenburg');
$city_data[] = array('accid' => 'USAR0579', 'name' => 'Waldo');
$city_data[] = array('accid' => 'USAR0580', 'name' => 'Waldron');
$city_data[] = array('accid' => 'USAR0581', 'name' => 'Walnut Ridge');
$city_data[] = array('accid' => 'USAR0582', 'name' => 'Ward');
$city_data[] = array('accid' => 'USAR0583', 'name' => 'Warm Springs');
$city_data[] = array('accid' => 'USAR0584', 'name' => 'Warren');
$city_data[] = array('accid' => 'USAR0585', 'name' => 'Washington');
$city_data[] = array('accid' => 'USAR0586', 'name' => 'Watson');
$city_data[] = array('accid' => 'USAR0587', 'name' => 'Weiner');
$city_data[] = array('accid' => 'USAR0588', 'name' => 'Wesley');
$city_data[] = array('accid' => 'USAR0589', 'name' => 'West Fork');
$city_data[] = array('accid' => 'USAR0590', 'name' => 'West Helena');
$city_data[] = array('accid' => 'USAR0591', 'name' => 'West Memphis');
$city_data[] = array('accid' => 'USAR0592', 'name' => 'West Point');
$city_data[] = array('accid' => 'USAR0593', 'name' => 'West Ridge');
$city_data[] = array('accid' => 'USAR0594', 'name' => 'Western Grove');
$city_data[] = array('accid' => 'USAR0595', 'name' => 'Wheatley');
$city_data[] = array('accid' => 'USAR0596', 'name' => 'Whelen Springs');
$city_data[] = array('accid' => 'USAR0597', 'name' => 'White Hall');
$city_data[] = array('accid' => 'USAR0598', 'name' => 'Wickes');
$city_data[] = array('accid' => 'USAR0599', 'name' => 'Wideman');
$city_data[] = array('accid' => 'USAR0600', 'name' => 'Widener');
$city_data[] = array('accid' => 'USAR0601', 'name' => 'Wilburn');
$city_data[] = array('accid' => 'USAR0602', 'name' => 'Williford');
$city_data[] = array('accid' => 'USAR0603', 'name' => 'Willisville');
$city_data[] = array('accid' => 'USAR0604', 'name' => 'Wilmar');
$city_data[] = array('accid' => 'USAR0605', 'name' => 'Wilmot');
$city_data[] = array('accid' => 'USAR0606', 'name' => 'Wilson');
$city_data[] = array('accid' => 'USAR0607', 'name' => 'Wilton');
$city_data[] = array('accid' => 'USAR0608', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USAR0609', 'name' => 'Winslow');
$city_data[] = array('accid' => 'USAR0610', 'name' => 'Winthrop');
$city_data[] = array('accid' => 'USAR0611', 'name' => 'Wiseman');
$city_data[] = array('accid' => 'USAR0612', 'name' => 'Witter');
$city_data[] = array('accid' => 'USAR0613', 'name' => 'Witts Springs');
$city_data[] = array('accid' => 'USAR0614', 'name' => 'Woodson');
$city_data[] = array('accid' => 'USAR0615', 'name' => 'Wooster');
$city_data[] = array('accid' => 'USAR0616', 'name' => 'Wright');
$city_data[] = array('accid' => 'USAR0617', 'name' => 'Wrightsville');
$city_data[] = array('accid' => 'USAR0618', 'name' => 'Wynne');
$city_data[] = array('accid' => 'USAR0619', 'name' => 'Yellville');
$city_data[] = array('accid' => 'USAR0620', 'name' => 'Yorktown');

?>