<?php

// City package for USA: Arizona 

$city_name = 'USA: Arizona';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USAZ0001', 'name' => 'Aguila');
$city_data[] = array('accid' => 'USAZ0002', 'name' => 'Ajo');
$city_data[] = array('accid' => 'USAZ0003', 'name' => 'Alpine');
$city_data[] = array('accid' => 'USAZ0004', 'name' => 'Amado');
$city_data[] = array('accid' => 'USAZ0005', 'name' => 'Apache Junction');
$city_data[] = array('accid' => 'USAZ0006', 'name' => 'Arivaca');
$city_data[] = array('accid' => 'USAZ0007', 'name' => 'Arizona City');
$city_data[] = array('accid' => 'USAZ0009', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USAZ0010', 'name' => 'Ash Fork');
$city_data[] = array('accid' => 'USAZ0011', 'name' => 'Avondale');
$city_data[] = array('accid' => 'USAZ0012', 'name' => 'Bagdad');
$city_data[] = array('accid' => 'USAZ0013', 'name' => 'Bapchule');
$city_data[] = array('accid' => 'USAZ0014', 'name' => 'Bellemont');
$city_data[] = array('accid' => 'USAZ0015', 'name' => 'Benson');
$city_data[] = array('accid' => 'USAZ0016', 'name' => 'Bisbee');
$city_data[] = array('accid' => 'USAZ0017', 'name' => 'Black Canyon City');
$city_data[] = array('accid' => 'USAZ0018', 'name' => 'Blue');
$city_data[] = array('accid' => 'USAZ0019', 'name' => 'Blue Gap');
$city_data[] = array('accid' => 'USAZ0020', 'name' => 'Bouse');
$city_data[] = array('accid' => 'USAZ0021', 'name' => 'Bowie');
$city_data[] = array('accid' => 'USAZ0022', 'name' => 'Buckeye');
$city_data[] = array('accid' => 'USAZ0023', 'name' => 'Bullhead City');
$city_data[] = array('accid' => 'USAZ0024', 'name' => 'Bylas');
$city_data[] = array('accid' => 'USAZ0025', 'name' => 'Cameron');
$city_data[] = array('accid' => 'USAZ0026', 'name' => 'Camp Verde');
$city_data[] = array('accid' => 'USAZ0027', 'name' => 'Carefree');
$city_data[] = array('accid' => 'USAZ0028', 'name' => 'Casa Grande');
$city_data[] = array('accid' => 'USAZ0029', 'name' => 'Cashion');
$city_data[] = array('accid' => 'USAZ0030', 'name' => 'Catalina');
$city_data[] = array('accid' => 'USAZ0031', 'name' => 'Cave Creek');
$city_data[] = array('accid' => 'USAZ0032', 'name' => 'Central');
$city_data[] = array('accid' => 'USAZ0033', 'name' => 'Chambers');
$city_data[] = array('accid' => 'USAZ0034', 'name' => 'Chandler');
$city_data[] = array('accid' => 'USAZ0035', 'name' => 'Chandler Heights');
$city_data[] = array('accid' => 'USAZ0036', 'name' => 'Chinle');
$city_data[] = array('accid' => 'USAZ0037', 'name' => 'Chino Valley');
$city_data[] = array('accid' => 'USAZ0038', 'name' => 'Chloride');
$city_data[] = array('accid' => 'USAZ0039', 'name' => 'Cibecue');
$city_data[] = array('accid' => 'USAZ0040', 'name' => 'Cibola');
$city_data[] = array('accid' => 'USAZ0041', 'name' => 'Clarkdale');
$city_data[] = array('accid' => 'USAZ0042', 'name' => 'Clay Springs');
$city_data[] = array('accid' => 'USAZ0043', 'name' => 'Claypool');
$city_data[] = array('accid' => 'USAZ0044', 'name' => 'Clifton');
$city_data[] = array('accid' => 'USAZ0045', 'name' => 'Cochise');
$city_data[] = array('accid' => 'USAZ0046', 'name' => 'Colorado City');
$city_data[] = array('accid' => 'USAZ0047', 'name' => 'Concho');
$city_data[] = array('accid' => 'USAZ0048', 'name' => 'Congress');
$city_data[] = array('accid' => 'USAZ0049', 'name' => 'Coolidge');
$city_data[] = array('accid' => 'USAZ0050', 'name' => 'Cornville');
$city_data[] = array('accid' => 'USAZ0051', 'name' => 'Cortaro');
$city_data[] = array('accid' => 'USAZ0052', 'name' => 'Cottonwood');
$city_data[] = array('accid' => 'USAZ0053', 'name' => 'Crown King');
$city_data[] = array('accid' => 'USAZ0054', 'name' => 'Dateland');
$city_data[] = array('accid' => 'USAZ0055', 'name' => 'Dennehotso');
$city_data[] = array('accid' => 'USAZ0056', 'name' => 'Dewey');
$city_data[] = array('accid' => 'USAZ0057', 'name' => 'Dolan Springs');
$city_data[] = array('accid' => 'USAZ0058', 'name' => 'Douglas');
$city_data[] = array('accid' => 'USAZ0059', 'name' => 'Dragoon');
$city_data[] = array('accid' => 'USAZ0060', 'name' => 'Duncan');
$city_data[] = array('accid' => 'USAZ0061', 'name' => 'Eagar');
$city_data[] = array('accid' => 'USAZ0062', 'name' => 'Eden');
$city_data[] = array('accid' => 'USAZ0063', 'name' => 'Ehrenberg');
$city_data[] = array('accid' => 'USAZ0064', 'name' => 'El Mirage');
$city_data[] = array('accid' => 'USAZ0065', 'name' => 'Elfrida');
$city_data[] = array('accid' => 'USAZ0066', 'name' => 'Elgin');
$city_data[] = array('accid' => 'USAZ0067', 'name' => 'Eloy');
$city_data[] = array('accid' => 'USAZ0068', 'name' => 'Flagstaff');
$city_data[] = array('accid' => 'USAZ0069', 'name' => 'Florence');
$city_data[] = array('accid' => 'USAZ0070', 'name' => 'Forest Lakes');
$city_data[] = array('accid' => 'USAZ0071', 'name' => 'Fort Apache');
$city_data[] = array('accid' => 'USAZ0072', 'name' => 'Fort Defiance');
$city_data[] = array('accid' => 'USAZ0073', 'name' => 'Fort Huachuca');
$city_data[] = array('accid' => 'USAZ0074', 'name' => 'Fort Mcdowell');
$city_data[] = array('accid' => 'USAZ0076', 'name' => 'Fort Thomas');
$city_data[] = array('accid' => 'USAZ0077', 'name' => 'Fountain Hills');
$city_data[] = array('accid' => 'USAZ0078', 'name' => 'Fredonia');
$city_data[] = array('accid' => 'USAZ0079', 'name' => 'Gadsden');
$city_data[] = array('accid' => 'USAZ0080', 'name' => 'Ganado');
$city_data[] = array('accid' => 'USAZ0081', 'name' => 'Gila Bend');
$city_data[] = array('accid' => 'USAZ0082', 'name' => 'Gilbert');
$city_data[] = array('accid' => 'USAZ0083', 'name' => 'Glendale');
$city_data[] = array('accid' => 'USAZ0085', 'name' => 'Globe');
$city_data[] = array('accid' => 'USAZ0086', 'name' => 'Golden Valley');
$city_data[] = array('accid' => 'USAZ0087', 'name' => 'Goodyear');
$city_data[] = array('accid' => 'USAZ0088', 'name' => 'Grand Canyon');
$city_data[] = array('accid' => 'USAZ0090', 'name' => 'Gray Mountain');
$city_data[] = array('accid' => 'USAZ0091', 'name' => 'Green Valley');
$city_data[] = array('accid' => 'USAZ0092', 'name' => 'Greer');
$city_data[] = array('accid' => 'USAZ0093', 'name' => 'Hackberry');
$city_data[] = array('accid' => 'USAZ0094', 'name' => 'Happy Jack');
$city_data[] = array('accid' => 'USAZ0095', 'name' => 'Hayden');
$city_data[] = array('accid' => 'USAZ0096', 'name' => 'Heber');
$city_data[] = array('accid' => 'USAZ0097', 'name' => 'Hereford');
$city_data[] = array('accid' => 'USAZ0098', 'name' => 'Higley');
$city_data[] = array('accid' => 'USAZ0099', 'name' => 'Holbrook');
$city_data[] = array('accid' => 'USAZ0100', 'name' => 'Hotevilla');
$city_data[] = array('accid' => 'USAZ0101', 'name' => 'Houck');
$city_data[] = array('accid' => 'USAZ0102', 'name' => 'Huachuca City');
$city_data[] = array('accid' => 'USAZ0103', 'name' => 'Hualapai');
$city_data[] = array('accid' => 'USAZ0104', 'name' => 'Humboldt');
$city_data[] = array('accid' => 'USAZ0105', 'name' => 'Indian Wells');
$city_data[] = array('accid' => 'USAZ0106', 'name' => 'Iron Springs');
$city_data[] = array('accid' => 'USAZ0107', 'name' => 'Jerome');
$city_data[] = array('accid' => 'USAZ0108', 'name' => 'Joseph City');
$city_data[] = array('accid' => 'USAZ0109', 'name' => 'Kaibito');
$city_data[] = array('accid' => 'USAZ0110', 'name' => 'Kayenta');
$city_data[] = array('accid' => 'USAZ0111', 'name' => 'Keams Canyon');
$city_data[] = array('accid' => 'USAZ0112', 'name' => 'Kearny');
$city_data[] = array('accid' => 'USAZ0113', 'name' => 'Kingman');
$city_data[] = array('accid' => 'USAZ0114', 'name' => 'Kirkland');
$city_data[] = array('accid' => 'USAZ0115', 'name' => 'Kykotsmovi Village');
$city_data[] = array('accid' => 'USAZ0116', 'name' => 'Lake Havasu City');
$city_data[] = array('accid' => 'USAZ0117', 'name' => 'Lake Montezuma');
$city_data[] = array('accid' => 'USAZ0118', 'name' => 'Lakeside');
$city_data[] = array('accid' => 'USAZ0119', 'name' => 'Laveen');
$city_data[] = array('accid' => 'USAZ0120', 'name' => 'Leupp');
$city_data[] = array('accid' => 'USAZ0121', 'name' => 'Litchfield Park');
$city_data[] = array('accid' => 'USAZ0122', 'name' => 'Littlefield');
$city_data[] = array('accid' => 'USAZ0123', 'name' => 'Lukachukai');
$city_data[] = array('accid' => 'USAZ0124', 'name' => 'Luke AFB');
$city_data[] = array('accid' => 'USAZ0125', 'name' => 'Lukeville');
$city_data[] = array('accid' => 'USAZ0126', 'name' => 'Lupton');
$city_data[] = array('accid' => 'USAZ0127', 'name' => 'Mammoth');
$city_data[] = array('accid' => 'USAZ0128', 'name' => 'Many Farms');
$city_data[] = array('accid' => 'USAZ0129', 'name' => 'Marana');
$city_data[] = array('accid' => 'USAZ0130', 'name' => 'Marble Canyon');
$city_data[] = array('accid' => 'USAZ0131', 'name' => 'Maricopa');
$city_data[] = array('accid' => 'USAZ0132', 'name' => 'Mayer');
$city_data[] = array('accid' => 'USAZ0133', 'name' => 'McNary');
$city_data[] = array('accid' => 'USAZ0134', 'name' => 'McNeal');
$city_data[] = array('accid' => 'USAZ0135', 'name' => 'Meadview');
$city_data[] = array('accid' => 'USAZ0136', 'name' => 'Mesa');
$city_data[] = array('accid' => 'USAZ0137', 'name' => 'Miami');
$city_data[] = array('accid' => 'USAZ0138', 'name' => 'Mohave Valley');
$city_data[] = array('accid' => 'USAZ0139', 'name' => 'Morenci');
$city_data[] = array('accid' => 'USAZ0140', 'name' => 'Mormon Lake');
$city_data[] = array('accid' => 'USAZ0141', 'name' => 'Morristown');
$city_data[] = array('accid' => 'USAZ0142', 'name' => 'Mount Lemmon');
$city_data[] = array('accid' => 'USAZ0143', 'name' => 'Munds Park');
$city_data[] = array('accid' => 'USAZ0144', 'name' => 'Naco');
$city_data[] = array('accid' => 'USAZ0145', 'name' => 'Nazlini');
$city_data[] = array('accid' => 'USAZ0277', 'name' => 'New River');
$city_data[] = array('accid' => 'USAZ0146', 'name' => 'Nogales');
$city_data[] = array('accid' => 'USAZ0147', 'name' => 'North Rim');
$city_data[] = array('accid' => 'USAZ0148', 'name' => 'Nutrioso');
$city_data[] = array('accid' => 'USAZ0149', 'name' => 'Oatman');
$city_data[] = array('accid' => 'USAZ0150', 'name' => 'Oracle');
$city_data[] = array('accid' => 'USAZ0151', 'name' => 'Overgaard');
$city_data[] = array('accid' => 'USAZ0152', 'name' => 'Page');
$city_data[] = array('accid' => 'USAZ0153', 'name' => 'Palo Verde');
$city_data[] = array('accid' => 'USAZ0154', 'name' => 'Paradise Valley');
$city_data[] = array('accid' => 'USAZ0155', 'name' => 'Parker');
$city_data[] = array('accid' => 'USAZ0156', 'name' => 'Parks');
$city_data[] = array('accid' => 'USAZ0157', 'name' => 'Patagonia');
$city_data[] = array('accid' => 'USAZ0158', 'name' => 'Paulden');
$city_data[] = array('accid' => 'USAZ0159', 'name' => 'Payson');
$city_data[] = array('accid' => 'USAZ0160', 'name' => 'Peach Springs');
$city_data[] = array('accid' => 'USAZ0161', 'name' => 'Pearce');
$city_data[] = array('accid' => 'USAZ0162', 'name' => 'Peoria');
$city_data[] = array('accid' => 'USAZ0163', 'name' => 'Peridot');
$city_data[] = array('accid' => 'USAZ0164', 'name' => 'Petrified Forest');
$city_data[] = array('accid' => 'USAZ0166', 'name' => 'Phoenix');
$city_data[] = array('accid' => 'USAZ0168', 'name' => 'Picacho');
$city_data[] = array('accid' => 'USAZ0169', 'name' => 'Pima');
$city_data[] = array('accid' => 'USAZ0170', 'name' => 'Pine');
$city_data[] = array('accid' => 'USAZ0171', 'name' => 'Pinedale');
$city_data[] = array('accid' => 'USAZ0172', 'name' => 'Pinetop');
$city_data[] = array('accid' => 'USAZ0173', 'name' => 'Pinon');
$city_data[] = array('accid' => 'USAZ0174', 'name' => 'Pirtleville');
$city_data[] = array('accid' => 'USAZ0175', 'name' => 'Polacca');
$city_data[] = array('accid' => 'USAZ0176', 'name' => 'Pomerene');
$city_data[] = array('accid' => 'USAZ0177', 'name' => 'Poston');
$city_data[] = array('accid' => 'USAZ0178', 'name' => 'Prescott');
$city_data[] = array('accid' => 'USAZ0179', 'name' => 'Prescott Valley');
$city_data[] = array('accid' => 'USAZ0180', 'name' => 'Quartzsite');
$city_data[] = array('accid' => 'USAZ0181', 'name' => 'Queen Creek');
$city_data[] = array('accid' => 'USAZ0182', 'name' => 'Red Rock');
$city_data[] = array('accid' => 'USAZ0183', 'name' => 'Red Valley');
$city_data[] = array('accid' => 'USAZ0184', 'name' => 'Rillito');
$city_data[] = array('accid' => 'USAZ0185', 'name' => 'Rimrock');
$city_data[] = array('accid' => 'USAZ0186', 'name' => 'Rio Rico');
$city_data[] = array('accid' => 'USAZ0187', 'name' => 'Rio Verde');
$city_data[] = array('accid' => 'USAZ0188', 'name' => 'Rock Point');
$city_data[] = array('accid' => 'USAZ0189', 'name' => 'Roll');
$city_data[] = array('accid' => 'USAZ0190', 'name' => 'Roosevelt');
$city_data[] = array('accid' => 'USAZ0191', 'name' => 'Round Rock');
$city_data[] = array('accid' => 'USAZ0192', 'name' => 'Sacaton');
$city_data[] = array('accid' => 'USAZ0193', 'name' => 'Safford');
$city_data[] = array('accid' => 'USAZ0195', 'name' => 'Sahuarita');
$city_data[] = array('accid' => 'USAZ0196', 'name' => 'Saint David');
$city_data[] = array('accid' => 'USAZ0197', 'name' => 'Saint Johns');
$city_data[] = array('accid' => 'USAZ0198', 'name' => 'Saint Michaels');
$city_data[] = array('accid' => 'USAZ0199', 'name' => 'Salome');
$city_data[] = array('accid' => 'USAZ0200', 'name' => 'San Carlos');
$city_data[] = array('accid' => 'USAZ0201', 'name' => 'San Luis');
$city_data[] = array('accid' => 'USAZ0202', 'name' => 'San Manuel');
$city_data[] = array('accid' => 'USAZ0203', 'name' => 'San Simon');
$city_data[] = array('accid' => 'USAZ0204', 'name' => 'Sanders');
$city_data[] = array('accid' => 'USAZ0205', 'name' => 'Sasabe');
$city_data[] = array('accid' => 'USAZ0206', 'name' => 'Sawmill');
$city_data[] = array('accid' => 'USAZ0207', 'name' => 'Scottsdale');
$city_data[] = array('accid' => 'USAZ0208', 'name' => 'Second Mesa');
$city_data[] = array('accid' => 'USAZ0209', 'name' => 'Sedona');
$city_data[] = array('accid' => 'USAZ0210', 'name' => 'Seligman');
$city_data[] = array('accid' => 'USAZ0211', 'name' => 'Sells');
$city_data[] = array('accid' => 'USAZ0212', 'name' => 'Shonto');
$city_data[] = array('accid' => 'USAZ0213', 'name' => 'Show Low');
$city_data[] = array('accid' => 'USAZ0214', 'name' => 'Sierra Vista');
$city_data[] = array('accid' => 'USAZ0215', 'name' => 'Skull Valley');
$city_data[] = array('accid' => 'USAZ0216', 'name' => 'Snowflake');
$city_data[] = array('accid' => 'USAZ0217', 'name' => 'Solomon');
$city_data[] = array('accid' => 'USAZ0218', 'name' => 'Somerton');
$city_data[] = array('accid' => 'USAZ0219', 'name' => 'Sonoita');
$city_data[] = array('accid' => 'USAZ0220', 'name' => 'Springerville');
$city_data[] = array('accid' => 'USAZ0221', 'name' => 'Stanfield');
$city_data[] = array('accid' => 'USAZ0222', 'name' => 'Sun City');
$city_data[] = array('accid' => 'USAZ0223', 'name' => 'Sun City West');
$city_data[] = array('accid' => 'USAZ0225', 'name' => 'Sun Valley');
$city_data[] = array('accid' => 'USAZ0227', 'name' => 'Supai');
$city_data[] = array('accid' => 'USAZ0228', 'name' => 'Superior');
$city_data[] = array('accid' => 'USAZ0229', 'name' => 'Surprise');
$city_data[] = array('accid' => 'USAZ0230', 'name' => 'Tacna');
$city_data[] = array('accid' => 'USAZ0231', 'name' => 'Taylor');
$city_data[] = array('accid' => 'USAZ0232', 'name' => 'Teec Nos Pos');
$city_data[] = array('accid' => 'USAZ0233', 'name' => 'Tempe');
$city_data[] = array('accid' => 'USAZ0234', 'name' => 'Temple Bar Marina');
$city_data[] = array('accid' => 'USAZ0235', 'name' => 'Thatcher');
$city_data[] = array('accid' => 'USAZ0236', 'name' => 'Tolleson');
$city_data[] = array('accid' => 'USAZ0237', 'name' => 'Tombstone');
$city_data[] = array('accid' => 'USAZ0238', 'name' => 'Tonalea');
$city_data[] = array('accid' => 'USAZ0239', 'name' => 'Tonopah');
$city_data[] = array('accid' => 'USAZ0240', 'name' => 'Tonto Basin');
$city_data[] = array('accid' => 'USAZ0241', 'name' => 'Topawa');
$city_data[] = array('accid' => 'USAZ0242', 'name' => 'Topock');
$city_data[] = array('accid' => 'USAZ0243', 'name' => 'Tortilla Flat');
$city_data[] = array('accid' => 'USAZ0244', 'name' => 'Tsaile');
$city_data[] = array('accid' => 'USAZ0245', 'name' => 'Tuba City');
$city_data[] = array('accid' => 'USAZ0246', 'name' => 'Tubac');
$city_data[] = array('accid' => 'USAZ0247', 'name' => 'Tucson');
$city_data[] = array('accid' => 'USAZ0249', 'name' => 'Tumacacori');
$city_data[] = array('accid' => 'USAZ0251', 'name' => 'Vail');
$city_data[] = array('accid' => 'USAZ0252', 'name' => 'Valentine');
$city_data[] = array('accid' => 'USAZ0254', 'name' => 'Valley Farms');
$city_data[] = array('accid' => 'USAZ0255', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USAZ0256', 'name' => 'Waddell');
$city_data[] = array('accid' => 'USAZ0257', 'name' => 'Wellton');
$city_data[] = array('accid' => 'USAZ0258', 'name' => 'Wenden');
$city_data[] = array('accid' => 'USAZ0259', 'name' => 'White Mountain Lake');
$city_data[] = array('accid' => 'USAZ0260', 'name' => 'Whiteriver');
$city_data[] = array('accid' => 'USAZ0261', 'name' => 'Wickenburg');
$city_data[] = array('accid' => 'USAZ0262', 'name' => 'Wikieup');
$city_data[] = array('accid' => 'USAZ0263', 'name' => 'Willcox');
$city_data[] = array('accid' => 'USAZ0264', 'name' => 'Williams');
$city_data[] = array('accid' => 'USAZ0265', 'name' => 'Willow Beach');
$city_data[] = array('accid' => 'USAZ0266', 'name' => 'Window Rock');
$city_data[] = array('accid' => 'USAZ0267', 'name' => 'Winkelman');
$city_data[] = array('accid' => 'USAZ0268', 'name' => 'Winslow');
$city_data[] = array('accid' => 'USAZ0269', 'name' => 'Wittmann');
$city_data[] = array('accid' => 'USAZ0270', 'name' => 'Woodruff');
$city_data[] = array('accid' => 'USAZ0271', 'name' => 'Yarnell');
$city_data[] = array('accid' => 'USAZ0272', 'name' => 'Young');
$city_data[] = array('accid' => 'USAZ0273', 'name' => 'Youngtown');
$city_data[] = array('accid' => 'USAZ0274', 'name' => 'Yucca');
$city_data[] = array('accid' => 'USAZ0275', 'name' => 'Yuma');

?>
