<?php

// City package for USA: California

$city_name = 'USA: California';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USCA0001', 'name' => 'Acampo');
$city_data[] = array('accid' => 'USCA0002', 'name' => 'Acton');
$city_data[] = array('accid' => 'USCA0003', 'name' => 'Adelanto');
$city_data[] = array('accid' => 'USCA0004', 'name' => 'Adin');
$city_data[] = array('accid' => 'USCA0005', 'name' => 'Agoura Hills');
$city_data[] = array('accid' => 'USCA0006', 'name' => 'Aguanga');
$city_data[] = array('accid' => 'USCA0007', 'name' => 'Ahwahnee');
$city_data[] = array('accid' => 'USCA0008', 'name' => 'Alameda');
$city_data[] = array('accid' => 'USCA0009', 'name' => 'Alamo');
$city_data[] = array('accid' => 'USCA0010', 'name' => 'Albany');
$city_data[] = array('accid' => 'USCA0011', 'name' => 'Albion');
$city_data[] = array('accid' => 'USCA0012', 'name' => 'Alderpoint');
$city_data[] = array('accid' => 'USCA0013', 'name' => 'Alhambra');
$city_data[] = array('accid' => 'USCA0014', 'name' => 'Aliso Viejo');
$city_data[] = array('accid' => 'USCA0015', 'name' => 'Alleghany');
$city_data[] = array('accid' => 'USCA0016', 'name' => 'Alpaugh');
$city_data[] = array('accid' => 'USCA0017', 'name' => 'Alpine');
$city_data[] = array('accid' => 'USCA0019', 'name' => 'Alta');
$city_data[] = array('accid' => 'USCA0020', 'name' => 'Alta Loma');
$city_data[] = array('accid' => 'USCA0021', 'name' => 'Altadena');
$city_data[] = array('accid' => 'USCA0022', 'name' => 'Altaville');
$city_data[] = array('accid' => 'USCA0023', 'name' => 'Alturas');
$city_data[] = array('accid' => 'USCA0024', 'name' => 'Alviso');
$city_data[] = array('accid' => 'USCA0025', 'name' => 'Amador City');
$city_data[] = array('accid' => 'USCA0026', 'name' => 'Amboy');
$city_data[] = array('accid' => 'USCA1290', 'name' => 'American Canyon');
$city_data[] = array('accid' => 'USCA0027', 'name' => 'Anaheim');
$city_data[] = array('accid' => 'USCA0028', 'name' => 'Anderson');
$city_data[] = array('accid' => 'USCA0029', 'name' => 'Angels Camp');
$city_data[] = array('accid' => 'USCA0030', 'name' => 'Angelus Oaks');
$city_data[] = array('accid' => 'USCA0031', 'name' => 'Angwin');
$city_data[] = array('accid' => 'USCA0032', 'name' => 'Annapolis');
$city_data[] = array('accid' => 'USCA0033', 'name' => 'Antelope');
$city_data[] = array('accid' => 'USCA0034', 'name' => 'Antioch');
$city_data[] = array('accid' => 'USCA0035', 'name' => 'Anza');
$city_data[] = array('accid' => 'USCA0036', 'name' => 'Apple Valley');
$city_data[] = array('accid' => 'USCA0037', 'name' => 'Applegate');
$city_data[] = array('accid' => 'USCA0038', 'name' => 'Aptos');
$city_data[] = array('accid' => 'USCA0039', 'name' => 'Arbuckle');
$city_data[] = array('accid' => 'USCA0040', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USCA0041', 'name' => 'Arcata');
$city_data[] = array('accid' => 'USCA0042', 'name' => 'Armona');
$city_data[] = array('accid' => 'USCA0043', 'name' => 'Arnold');
$city_data[] = array('accid' => 'USCA0044', 'name' => 'Aromas');
$city_data[] = array('accid' => 'USCA0045', 'name' => 'Arroyo Grande');
$city_data[] = array('accid' => 'USCA0046', 'name' => 'Artesia');
$city_data[] = array('accid' => 'USCA0047', 'name' => 'Artois');
$city_data[] = array('accid' => 'USCA0048', 'name' => 'Arvin');
$city_data[] = array('accid' => 'USCA0049', 'name' => 'Atascadero');
$city_data[] = array('accid' => 'USCA0050', 'name' => 'Atherton');
$city_data[] = array('accid' => 'USCA0051', 'name' => 'Atwater');
$city_data[] = array('accid' => 'USCA0052', 'name' => 'Atwood');
$city_data[] = array('accid' => 'USCA0053', 'name' => 'Auberry');
$city_data[] = array('accid' => 'USCA0054', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USCA0055', 'name' => 'Avalon');
$city_data[] = array('accid' => 'USCA0056', 'name' => 'Avenal');
$city_data[] = array('accid' => 'USCA0057', 'name' => 'Avery');
$city_data[] = array('accid' => 'USCA0058', 'name' => 'Avila Beach');
$city_data[] = array('accid' => 'USCA0059', 'name' => 'Azusa');
$city_data[] = array('accid' => 'USCA0060', 'name' => 'Badger');
$city_data[] = array('accid' => 'USCA0061', 'name' => 'Baker');
$city_data[] = array('accid' => 'USCA0062', 'name' => 'Bakersfield');
$city_data[] = array('accid' => 'USCA0063', 'name' => 'Baldwin Park');
$city_data[] = array('accid' => 'USCA0064', 'name' => 'Ballico');
$city_data[] = array('accid' => 'USCA0065', 'name' => 'Bangor');
$city_data[] = array('accid' => 'USCA0066', 'name' => 'Banning');
$city_data[] = array('accid' => 'USCA0067', 'name' => 'Banta');
$city_data[] = array('accid' => 'USCA0068', 'name' => 'Bard');
$city_data[] = array('accid' => 'USCA0069', 'name' => 'Barstow');
$city_data[] = array('accid' => 'USCA0070', 'name' => 'Bass Lake');
$city_data[] = array('accid' => 'USCA0071', 'name' => 'Bayside');
$city_data[] = array('accid' => 'USCA0072', 'name' => 'Beale AFB');
$city_data[] = array('accid' => 'USCA0075', 'name' => 'Beaumont');
$city_data[] = array('accid' => 'USCA0076', 'name' => 'Beckwourth');
$city_data[] = array('accid' => 'USCA0077', 'name' => 'Belden');
$city_data[] = array('accid' => 'USCA0078', 'name' => 'Bell');
$city_data[] = array('accid' => 'USCA0079', 'name' => 'Bell Gardens');
$city_data[] = array('accid' => 'USCA0080', 'name' => 'Bella Vista');
$city_data[] = array('accid' => 'USCA0081', 'name' => 'Bellflower');
$city_data[] = array('accid' => 'USCA0082', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USCA0083', 'name' => 'Belvedere Tiburon');
$city_data[] = array('accid' => 'USCA0084', 'name' => 'Ben Lomond');
$city_data[] = array('accid' => 'USCA0085', 'name' => 'Benicia');
$city_data[] = array('accid' => 'USCA0086', 'name' => 'Benton');
$city_data[] = array('accid' => 'USCA0087', 'name' => 'Berkeley');
$city_data[] = array('accid' => 'USCA0088', 'name' => 'Berry Creek');
$city_data[] = array('accid' => 'USCA0089', 'name' => 'Bethel Island');
$city_data[] = array('accid' => 'USCA0090', 'name' => 'Beverly Hills');
$city_data[] = array('accid' => 'USCA0091', 'name' => 'Bieber');
$city_data[] = array('accid' => 'USCA0092', 'name' => 'Big Bar');
$city_data[] = array('accid' => 'USCA0093', 'name' => 'Big Bear City');
$city_data[] = array('accid' => 'USCA0094', 'name' => 'Big Bear Lake');
$city_data[] = array('accid' => 'USCA0095', 'name' => 'Big Bend');
$city_data[] = array('accid' => 'USCA0096', 'name' => 'Big Creek');
$city_data[] = array('accid' => 'USCA0097', 'name' => 'Big Oak Flat');
$city_data[] = array('accid' => 'USCA0098', 'name' => 'Big Pine');
$city_data[] = array('accid' => 'USCA0099', 'name' => 'Big Sur');
$city_data[] = array('accid' => 'USCA0100', 'name' => 'Biggs');
$city_data[] = array('accid' => 'USCA0101', 'name' => 'Biola');
$city_data[] = array('accid' => 'USCA0102', 'name' => 'Birds Landing');
$city_data[] = array('accid' => 'USCA0103', 'name' => 'Bishop');
$city_data[] = array('accid' => 'USCA0104', 'name' => 'Blairsden-graeagle');
$city_data[] = array('accid' => 'USCA0105', 'name' => 'Blocksburg');
$city_data[] = array('accid' => 'USCA0106', 'name' => 'Bloomington');
$city_data[] = array('accid' => 'USCA0108', 'name' => 'Blue Jay');
$city_data[] = array('accid' => 'USCA0109', 'name' => 'Blue Lake');
$city_data[] = array('accid' => 'USCA0110', 'name' => 'Blythe');
$city_data[] = array('accid' => 'USCA0111', 'name' => 'Bodega');
$city_data[] = array('accid' => 'USCA0112', 'name' => 'Bodega Bay');
$city_data[] = array('accid' => 'USCA0113', 'name' => 'Bodfish');
$city_data[] = array('accid' => 'USCA0114', 'name' => 'Bolinas');
$city_data[] = array('accid' => 'USCA0115', 'name' => 'Bonita');
$city_data[] = array('accid' => 'USCA0116', 'name' => 'Bonsall');
$city_data[] = array('accid' => 'USCA0117', 'name' => 'Boonville');
$city_data[] = array('accid' => 'USCA0118', 'name' => 'Boron');
$city_data[] = array('accid' => 'USCA0119', 'name' => 'Borrego Springs');
$city_data[] = array('accid' => 'USCA0120', 'name' => 'Boulder Creek');
$city_data[] = array('accid' => 'USCA0121', 'name' => 'Boulevard');
$city_data[] = array('accid' => 'USCA0122', 'name' => 'Boyes Hot Springs');
$city_data[] = array('accid' => 'USCA0123', 'name' => 'Bradley');
$city_data[] = array('accid' => 'USCA0124', 'name' => 'Brandeis');
$city_data[] = array('accid' => 'USCA0125', 'name' => 'Branscomb');
$city_data[] = array('accid' => 'USCA0126', 'name' => 'Brawley');
$city_data[] = array('accid' => 'USCA0127', 'name' => 'Brea');
$city_data[] = array('accid' => 'USCA0128', 'name' => 'Brentwood');
$city_data[] = array('accid' => 'USCA0129', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USCA0130', 'name' => 'Bridgeville');
$city_data[] = array('accid' => 'USCA0131', 'name' => 'Brisbane');
$city_data[] = array('accid' => 'USCA0132', 'name' => 'Brookdale');
$city_data[] = array('accid' => 'USCA0133', 'name' => 'Brooks');
$city_data[] = array('accid' => 'USCA0134', 'name' => 'Browns Valley');
$city_data[] = array('accid' => 'USCA0135', 'name' => 'Brownsville');
$city_data[] = array('accid' => 'USCA0136', 'name' => 'Bryn Mawr');
$city_data[] = array('accid' => 'USCA0137', 'name' => 'Buellton');
$city_data[] = array('accid' => 'USCA0138', 'name' => 'Buena Park');
$city_data[] = array('accid' => 'USCA0139', 'name' => 'Burbank');
$city_data[] = array('accid' => 'USCA0140', 'name' => 'Burlingame');
$city_data[] = array('accid' => 'USCA0141', 'name' => 'Burney');
$city_data[] = array('accid' => 'USCA0142', 'name' => 'Burnt Ranch');
$city_data[] = array('accid' => 'USCA0143', 'name' => 'Burrel');
$city_data[] = array('accid' => 'USCA0144', 'name' => 'Burson');
$city_data[] = array('accid' => 'USCA0145', 'name' => 'Butte City');
$city_data[] = array('accid' => 'USCA0146', 'name' => 'Buttonwillow');
$city_data[] = array('accid' => 'USCA0147', 'name' => 'Byron');
$city_data[] = array('accid' => 'USCA0148', 'name' => 'Cabazon');
$city_data[] = array('accid' => 'USCA0149', 'name' => 'Calabasas');
$city_data[] = array('accid' => 'USCA0150', 'name' => 'Calexico');
$city_data[] = array('accid' => 'USCA0151', 'name' => 'Caliente');
$city_data[] = array('accid' => 'USCA0152', 'name' => 'California City');
$city_data[] = array('accid' => 'USCA0153', 'name' => 'California Hot Springs');
$city_data[] = array('accid' => 'USCA0154', 'name' => 'Calimesa');
$city_data[] = array('accid' => 'USCA0155', 'name' => 'Calipatria');
$city_data[] = array('accid' => 'USCA0156', 'name' => 'Calistoga');
$city_data[] = array('accid' => 'USCA0157', 'name' => 'Callahan');
$city_data[] = array('accid' => 'USCA0158', 'name' => 'Calpella');
$city_data[] = array('accid' => 'USCA0159', 'name' => 'Calpine');
$city_data[] = array('accid' => 'USCA0160', 'name' => 'Camarillo');
$city_data[] = array('accid' => 'USCA0161', 'name' => 'Cambria');
$city_data[] = array('accid' => 'USCA0162', 'name' => 'Camino');
$city_data[] = array('accid' => 'USCA0163', 'name' => 'Camp Meeker');
$city_data[] = array('accid' => 'USCA0164', 'name' => 'Camp Nelson');
$city_data[] = array('accid' => 'USCA0165', 'name' => 'Camp Pendleton');
$city_data[] = array('accid' => 'USCA0166', 'name' => 'Campbell');
$city_data[] = array('accid' => 'USCA0167', 'name' => 'Campo');
$city_data[] = array('accid' => 'USCA0168', 'name' => 'Campo Seco');
$city_data[] = array('accid' => 'USCA0169', 'name' => 'Camptonville');
$city_data[] = array('accid' => 'USCA0170', 'name' => 'Canby');
$city_data[] = array('accid' => 'USCA0171', 'name' => 'Canoga Park');
$city_data[] = array('accid' => 'USCA0172', 'name' => 'Cantil');
$city_data[] = array('accid' => 'USCA0173', 'name' => 'Cantua Creek');
$city_data[] = array('accid' => 'USCA0174', 'name' => 'Canyon');
$city_data[] = array('accid' => 'USCA0175', 'name' => 'Canyon Country');
$city_data[] = array('accid' => 'USCA0176', 'name' => 'Canyondam');
$city_data[] = array('accid' => 'USCA0177', 'name' => 'Capay');
$city_data[] = array('accid' => 'USCA0178', 'name' => 'Capistrano Beach');
$city_data[] = array('accid' => 'USCA0179', 'name' => 'Capitola');
$city_data[] = array('accid' => 'USCA0180', 'name' => 'Cardiff By The Sea');
$city_data[] = array('accid' => 'USCA0181', 'name' => 'Carlotta');
$city_data[] = array('accid' => 'USCA0182', 'name' => 'Carlsbad');
$city_data[] = array('accid' => 'USCA0183', 'name' => 'Carmel');
$city_data[] = array('accid' => 'USCA0184', 'name' => 'Carmel Valley');
$city_data[] = array('accid' => 'USCA0185', 'name' => 'Carmichael');
$city_data[] = array('accid' => 'USCA0186', 'name' => 'Carnelian Bay');
$city_data[] = array('accid' => 'USCA0187', 'name' => 'Carpinteria');
$city_data[] = array('accid' => 'USCA0188', 'name' => 'Carson');
$city_data[] = array('accid' => 'USCA0189', 'name' => 'Caruthers');
$city_data[] = array('accid' => 'USCA0190', 'name' => 'Casmalia');
$city_data[] = array('accid' => 'USCA0191', 'name' => 'Caspar');
$city_data[] = array('accid' => 'USCA0192', 'name' => 'Cassel');
$city_data[] = array('accid' => 'USCA0193', 'name' => 'Castaic');
$city_data[] = array('accid' => 'USCA0194', 'name' => 'Castella');
$city_data[] = array('accid' => 'USCA0195', 'name' => 'Castro Valley');
$city_data[] = array('accid' => 'USCA0196', 'name' => 'Castroville');
$city_data[] = array('accid' => 'USCA0197', 'name' => 'Cathedral City');
$city_data[] = array('accid' => 'USCA0198', 'name' => 'Catheys Valley');
$city_data[] = array('accid' => 'USCA0199', 'name' => 'Cayucos');
$city_data[] = array('accid' => 'USCA0200', 'name' => 'Cazadero');
$city_data[] = array('accid' => 'USCA0201', 'name' => 'Cedar Glen');
$city_data[] = array('accid' => 'USCA0202', 'name' => 'Cedar Ridge');
$city_data[] = array('accid' => 'USCA0203', 'name' => 'Cedarpines Park');
$city_data[] = array('accid' => 'USCA0204', 'name' => 'Cedarville');
$city_data[] = array('accid' => 'USCA0205', 'name' => 'Ceres');
$city_data[] = array('accid' => 'USCA0206', 'name' => 'Cerritos');
$city_data[] = array('accid' => 'USCA0207', 'name' => 'Challenge');
$city_data[] = array('accid' => 'USCA0208', 'name' => 'Chatsworth');
$city_data[] = array('accid' => 'USCA0209', 'name' => 'Chester');
$city_data[] = array('accid' => 'USCA0210', 'name' => 'Chicago Park');
$city_data[] = array('accid' => 'USCA0211', 'name' => 'Chico');
$city_data[] = array('accid' => 'USCA0212', 'name' => 'Chilcoot');
$city_data[] = array('accid' => 'USCA0214', 'name' => 'Chinese Camp');
$city_data[] = array('accid' => 'USCA0215', 'name' => 'Chino');
$city_data[] = array('accid' => 'USCA0216', 'name' => 'Chino Hills');
$city_data[] = array('accid' => 'USCA0217', 'name' => 'Chowchilla');
$city_data[] = array('accid' => 'USCA0218', 'name' => 'Chualar');
$city_data[] = array('accid' => 'USCA0219', 'name' => 'Chula Vista');
$city_data[] = array('accid' => 'USCA0220', 'name' => 'Cima');
$city_data[] = array('accid' => 'USCA0221', 'name' => 'Citrus Heights');
$city_data[] = array('accid' => 'USCA0222', 'name' => 'City of Industry');
$city_data[] = array('accid' => 'USCA0223', 'name' => 'Claremont');
$city_data[] = array('accid' => 'USCA0224', 'name' => 'Clarksburg');
$city_data[] = array('accid' => 'USCA0225', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USCA0226', 'name' => 'Clearlake');
$city_data[] = array('accid' => 'USCA0227', 'name' => 'Clearlake Oaks');
$city_data[] = array('accid' => 'USCA0228', 'name' => 'Clearlake Park');
$city_data[] = array('accid' => 'USCA0229', 'name' => 'Clements');
$city_data[] = array('accid' => 'USCA0230', 'name' => 'Clio');
$city_data[] = array('accid' => 'USCA0231', 'name' => 'Clipper Mills');
$city_data[] = array('accid' => 'USCA0232', 'name' => 'Cloverdale');
$city_data[] = array('accid' => 'USCA0233', 'name' => 'Clovis');
$city_data[] = array('accid' => 'USCA0234', 'name' => 'Coachella');
$city_data[] = array('accid' => 'USCA0235', 'name' => 'Coalinga');
$city_data[] = array('accid' => 'USCA0236', 'name' => 'Coarsegold');
$city_data[] = array('accid' => 'USCA0237', 'name' => 'Cobb');
$city_data[] = array('accid' => 'USCA0238', 'name' => 'Coleville');
$city_data[] = array('accid' => 'USCA0239', 'name' => 'Colfax');
$city_data[] = array('accid' => 'USCA0240', 'name' => 'College City');
$city_data[] = array('accid' => 'USCA0241', 'name' => 'Coloma');
$city_data[] = array('accid' => 'USCA0242', 'name' => 'Colton');
$city_data[] = array('accid' => 'USCA0243', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USCA0244', 'name' => 'Colusa');
$city_data[] = array('accid' => 'USCA0245', 'name' => 'Comptche');
$city_data[] = array('accid' => 'USCA0246', 'name' => 'Compton');
$city_data[] = array('accid' => 'USCA0247', 'name' => 'Concord');
$city_data[] = array('accid' => 'USCA0248', 'name' => 'Cool');
$city_data[] = array('accid' => 'USCA0249', 'name' => 'Copperopolis');
$city_data[] = array('accid' => 'USCA0250', 'name' => 'Corcoran');
$city_data[] = array('accid' => 'USCA0251', 'name' => 'Corning');
$city_data[] = array('accid' => 'USCA0252', 'name' => 'Corona');
$city_data[] = array('accid' => 'USCA0253', 'name' => 'Corona Del Mar');
$city_data[] = array('accid' => 'USCA0254', 'name' => 'Coronado');
$city_data[] = array('accid' => 'USCA0255', 'name' => 'Corte Madera');
$city_data[] = array('accid' => 'USCA0256', 'name' => 'Costa Mesa');
$city_data[] = array('accid' => 'USCA0257', 'name' => 'Cotati');
$city_data[] = array('accid' => 'USCA0258', 'name' => 'Cottonwood');
$city_data[] = array('accid' => 'USCA0259', 'name' => 'Coulterville');
$city_data[] = array('accid' => 'USCA0260', 'name' => 'Courtland');
$city_data[] = array('accid' => 'USCA0261', 'name' => 'Covelo');
$city_data[] = array('accid' => 'USCA0262', 'name' => 'Covina');
$city_data[] = array('accid' => 'USCA0263', 'name' => 'Coyote');
$city_data[] = array('accid' => 'USCA0264', 'name' => 'Crescent City');
$city_data[] = array('accid' => 'USCA0265', 'name' => 'Crescent Mills');
$city_data[] = array('accid' => 'USCA0266', 'name' => 'Cressey');
$city_data[] = array('accid' => 'USCA0267', 'name' => 'Crest Park');
$city_data[] = array('accid' => 'USCA0268', 'name' => 'Crestline');
$city_data[] = array('accid' => 'USCA0269', 'name' => 'Creston');
$city_data[] = array('accid' => 'USCA0270', 'name' => 'Crockett');
$city_data[] = array('accid' => 'USCA0271', 'name' => 'Crows Landing');
$city_data[] = array('accid' => 'USCA0272', 'name' => 'Culver City');
$city_data[] = array('accid' => 'USCA0273', 'name' => 'Cupertino');
$city_data[] = array('accid' => 'USCA0274', 'name' => 'Cutler');
$city_data[] = array('accid' => 'USCA0275', 'name' => 'Cutten');
$city_data[] = array('accid' => 'USCA0276', 'name' => 'Cypress');
$city_data[] = array('accid' => 'USCA0277', 'name' => 'Daggett');
$city_data[] = array('accid' => 'USCA0278', 'name' => 'Daly City');
$city_data[] = array('accid' => 'USCA0279', 'name' => 'Dana Point');
$city_data[] = array('accid' => 'USCA0280', 'name' => 'Danville');
$city_data[] = array('accid' => 'USCA0281', 'name' => 'Dardanelle');
$city_data[] = array('accid' => 'USCA0282', 'name' => 'Darwin');
$city_data[] = array('accid' => 'USCA0283', 'name' => 'Davenport');
$city_data[] = array('accid' => 'USCA0284', 'name' => 'Davis');
$city_data[] = array('accid' => 'USCA0285', 'name' => 'Davis Creek');
$city_data[] = array('accid' => 'USCA0286', 'name' => 'Death Valley');
$city_data[] = array('accid' => 'USCA0287', 'name' => 'Deer Park');
$city_data[] = array('accid' => 'USCA0288', 'name' => 'Del Mar');
$city_data[] = array('accid' => 'USCA0289', 'name' => 'Del Rey');
$city_data[] = array('accid' => 'USCA0290', 'name' => 'Delano');
$city_data[] = array('accid' => 'USCA0291', 'name' => 'Delhi');
$city_data[] = array('accid' => 'USCA0292', 'name' => 'Denair');
$city_data[] = array('accid' => 'USCA0293', 'name' => 'Descanso');
$city_data[] = array('accid' => 'USCA0294', 'name' => 'Desert Center');
$city_data[] = array('accid' => 'USCA0295', 'name' => 'Desert Hot Springs');
$city_data[] = array('accid' => 'USCA0296', 'name' => 'Diablo');
$city_data[] = array('accid' => 'USCA0297', 'name' => 'Diamond Bar');
$city_data[] = array('accid' => 'USCA0298', 'name' => 'Diamond Springs');
$city_data[] = array('accid' => 'USCA0299', 'name' => 'Dillon Beach');
$city_data[] = array('accid' => 'USCA0300', 'name' => 'Dinuba');
$city_data[] = array('accid' => 'USCA0301', 'name' => 'Dixon');
$city_data[] = array('accid' => 'USCA0302', 'name' => 'Dobbins');
$city_data[] = array('accid' => 'USCA0304', 'name' => 'Dorris');
$city_data[] = array('accid' => 'USCA0305', 'name' => 'Dos Palos');
$city_data[] = array('accid' => 'USCA0306', 'name' => 'Dos Rios');
$city_data[] = array('accid' => 'USCA0307', 'name' => 'Douglas City');
$city_data[] = array('accid' => 'USCA0308', 'name' => 'Douglas Flat');
$city_data[] = array('accid' => 'USCA0309', 'name' => 'Downey');
$city_data[] = array('accid' => 'USCA0310', 'name' => 'Downieville');
$city_data[] = array('accid' => 'USCA0311', 'name' => 'Doyle');
$city_data[] = array('accid' => 'USCA0312', 'name' => 'Drytown');
$city_data[] = array('accid' => 'USCA0313', 'name' => 'Duarte');
$city_data[] = array('accid' => 'USCA0314', 'name' => 'Dublin');
$city_data[] = array('accid' => 'USCA0315', 'name' => 'Ducor');
$city_data[] = array('accid' => 'USCA0316', 'name' => 'Dulzura');
$city_data[] = array('accid' => 'USCA0317', 'name' => 'Duncans Mills');
$city_data[] = array('accid' => 'USCA0318', 'name' => 'Dunlap');
$city_data[] = array('accid' => 'USCA0319', 'name' => 'Dunnigan');
$city_data[] = array('accid' => 'USCA0320', 'name' => 'Dunsmuir');
$city_data[] = array('accid' => 'USCA0321', 'name' => 'Durham');
$city_data[] = array('accid' => 'USCA0322', 'name' => 'Dutch Flat');
$city_data[] = array('accid' => 'USCA0323', 'name' => 'Eagleville');
$city_data[] = array('accid' => 'USCA0324', 'name' => 'Earlimart');
$city_data[] = array('accid' => 'USCA0325', 'name' => 'Earp');
$city_data[] = array('accid' => 'USCA0326', 'name' => 'East Irvine');
$city_data[] = array('accid' => 'USCA0327', 'name' => 'Echo Lake');
$city_data[] = array('accid' => 'USCA0328', 'name' => 'Edison');
$city_data[] = array('accid' => 'USCA0329', 'name' => 'Edwards');
$city_data[] = array('accid' => 'USCA0331', 'name' => 'El Cajon');
$city_data[] = array('accid' => 'USCA0332', 'name' => 'El Centro');
$city_data[] = array('accid' => 'USCA0333', 'name' => 'El Cerrito');
$city_data[] = array('accid' => 'USCA0334', 'name' => 'El Dorado');
$city_data[] = array('accid' => 'USCA0335', 'name' => 'El Dorado Hills');
$city_data[] = array('accid' => 'USCA0336', 'name' => 'El Granada');
$city_data[] = array('accid' => 'USCA0337', 'name' => 'El Macero');
$city_data[] = array('accid' => 'USCA0338', 'name' => 'El Monte');
$city_data[] = array('accid' => 'USCA0339', 'name' => 'El Nido');
$city_data[] = array('accid' => 'USCA0340', 'name' => 'El Portal');
$city_data[] = array('accid' => 'USCA0341', 'name' => 'El Segundo');
$city_data[] = array('accid' => 'USCA0342', 'name' => 'El Sobrante');
$city_data[] = array('accid' => 'USCA1292', 'name' => 'El Toro');
$city_data[] = array('accid' => 'USCA0343', 'name' => 'El Verano');
$city_data[] = array('accid' => 'USCA0344', 'name' => 'Eldridge');
$city_data[] = array('accid' => 'USCA0345', 'name' => 'Elk');
$city_data[] = array('accid' => 'USCA0346', 'name' => 'Elk Creek');
$city_data[] = array('accid' => 'USCA0347', 'name' => 'Elk Grove');
$city_data[] = array('accid' => 'USCA0348', 'name' => 'Elmira');
$city_data[] = array('accid' => 'USCA0349', 'name' => 'Elverta');
$city_data[] = array('accid' => 'USCA0350', 'name' => 'Emeryville');
$city_data[] = array('accid' => 'USCA0351', 'name' => 'Emigrant Gap');
$city_data[] = array('accid' => 'USCA0352', 'name' => 'Empire');
$city_data[] = array('accid' => 'USCA0353', 'name' => 'Encinitas');
$city_data[] = array('accid' => 'USCA0354', 'name' => 'Encino');
$city_data[] = array('accid' => 'USCA0355', 'name' => 'Escalon');
$city_data[] = array('accid' => 'USCA0356', 'name' => 'Escondido');
$city_data[] = array('accid' => 'USCA0357', 'name' => 'Esparto');
$city_data[] = array('accid' => 'USCA0358', 'name' => 'Essex');
$city_data[] = array('accid' => 'USCA0359', 'name' => 'Etna');
$city_data[] = array('accid' => 'USCA0360', 'name' => 'Eureka');
$city_data[] = array('accid' => 'USCA0361', 'name' => 'Exeter');
$city_data[] = array('accid' => 'USCA0362', 'name' => 'Fair Oaks');
$city_data[] = array('accid' => 'USCA0363', 'name' => 'Fairfax');
$city_data[] = array('accid' => 'USCA0364', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USCA0365', 'name' => 'Fall River Mills');
$city_data[] = array('accid' => 'USCA0366', 'name' => 'Fallbrook');
$city_data[] = array('accid' => 'USCA0367', 'name' => 'Farmersville');
$city_data[] = array('accid' => 'USCA0368', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USCA0369', 'name' => 'Fawnskin');
$city_data[] = array('accid' => 'USCA0370', 'name' => 'Feather Falls');
$city_data[] = array('accid' => 'USCA0371', 'name' => 'Fellows');
$city_data[] = array('accid' => 'USCA0372', 'name' => 'Felton');
$city_data[] = array('accid' => 'USCA0373', 'name' => 'Ferndale');
$city_data[] = array('accid' => 'USCA0374', 'name' => 'Fiddletown');
$city_data[] = array('accid' => 'USCA0375', 'name' => 'Fields Landing');
$city_data[] = array('accid' => 'USCA0376', 'name' => 'Fillmore');
$city_data[] = array('accid' => 'USCA0377', 'name' => 'Finley');
$city_data[] = array('accid' => 'USCA0378', 'name' => 'Firebaugh');
$city_data[] = array('accid' => 'USCA0379', 'name' => 'Fish Camp');
$city_data[] = array('accid' => 'USCA0380', 'name' => 'Five Points');
$city_data[] = array('accid' => 'USCA0381', 'name' => 'Floriston');
$city_data[] = array('accid' => 'USCA0382', 'name' => 'Flournoy');
$city_data[] = array('accid' => 'USCA0383', 'name' => 'Folsom');
$city_data[] = array('accid' => 'USCA0384', 'name' => 'Fontana');
$city_data[] = array('accid' => 'USCA0385', 'name' => 'Foothill Ranch');
$city_data[] = array('accid' => 'USCA0386', 'name' => 'Forbestown');
$city_data[] = array('accid' => 'USCA0387', 'name' => 'Forest Falls');
$city_data[] = array('accid' => 'USCA0388', 'name' => 'Forest Knolls');
$city_data[] = array('accid' => 'USCA0389', 'name' => 'Forest Ranch');
$city_data[] = array('accid' => 'USCA0390', 'name' => 'Foresthill');
$city_data[] = array('accid' => 'USCA0391', 'name' => 'Forestville');
$city_data[] = array('accid' => 'USCA0392', 'name' => 'Forks Of Salmon');
$city_data[] = array('accid' => 'USCA0393', 'name' => 'Fort Bidwell');
$city_data[] = array('accid' => 'USCA0394', 'name' => 'Fort Bragg');
$city_data[] = array('accid' => 'USCA0395', 'name' => 'Fort Dick');
$city_data[] = array('accid' => 'USCA0396', 'name' => 'Fort Irwin');
$city_data[] = array('accid' => 'USCA0397', 'name' => 'Fort Jones');
$city_data[] = array('accid' => 'USCA0398', 'name' => 'Fortuna');
$city_data[] = array('accid' => 'USCA0399', 'name' => 'Fountain Valley');
$city_data[] = array('accid' => 'USCA0400', 'name' => 'Fowler');
$city_data[] = array('accid' => 'USCA0401', 'name' => 'Frazier Park');
$city_data[] = array('accid' => 'USCA0402', 'name' => 'Freedom');
$city_data[] = array('accid' => 'USCA0403', 'name' => 'Fremont');
$city_data[] = array('accid' => 'USCA0404', 'name' => 'French Camp');
$city_data[] = array('accid' => 'USCA0405', 'name' => 'French Gulch');
$city_data[] = array('accid' => 'USCA0406', 'name' => 'Fresno');
$city_data[] = array('accid' => 'USCA0407', 'name' => 'Friant');
$city_data[] = array('accid' => 'USCA0408', 'name' => 'Fullerton');
$city_data[] = array('accid' => 'USCA0409', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USCA0410', 'name' => 'Galt');
$city_data[] = array('accid' => 'USCA0411', 'name' => 'Garberville');
$city_data[] = array('accid' => 'USCA0412', 'name' => 'Garden Grove');
$city_data[] = array('accid' => 'USCA0413', 'name' => 'Garden Valley');
$city_data[] = array('accid' => 'USCA0414', 'name' => 'Gardena');
$city_data[] = array('accid' => 'USCA0415', 'name' => 'Gasquet');
$city_data[] = array('accid' => 'USCA0416', 'name' => 'Gazelle');
$city_data[] = array('accid' => 'USCA0417', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USCA0418', 'name' => 'Gerber');
$city_data[] = array('accid' => 'USCA0419', 'name' => 'Geyserville');
$city_data[] = array('accid' => 'USCA0420', 'name' => 'Gilroy');
$city_data[] = array('accid' => 'USCA0421', 'name' => 'Glen Ellen');
$city_data[] = array('accid' => 'USCA0422', 'name' => 'Glencoe');
$city_data[] = array('accid' => 'USCA0423', 'name' => 'Glendale');
$city_data[] = array('accid' => 'USCA0424', 'name' => 'Glendora');
$city_data[] = array('accid' => 'USCA0425', 'name' => 'Glenhaven');
$city_data[] = array('accid' => 'USCA0426', 'name' => 'Glenn');
$city_data[] = array('accid' => 'USCA0427', 'name' => 'Glennville');
$city_data[] = array('accid' => 'USCA0428', 'name' => 'Gold Run');
$city_data[] = array('accid' => 'USCA0429', 'name' => 'Goleta');
$city_data[] = array('accid' => 'USCA0430', 'name' => 'Gonzales');
$city_data[] = array('accid' => 'USCA0431', 'name' => 'Goodyears Bar');
$city_data[] = array('accid' => 'USCA0433', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USCA0434', 'name' => 'Granada Hills');
$city_data[] = array('accid' => 'USCA0435', 'name' => 'Grand Terrace');
$city_data[] = array('accid' => 'USCA0436', 'name' => 'Granite Bay');
$city_data[] = array('accid' => 'USCA0437', 'name' => 'Grass Valley');
$city_data[] = array('accid' => 'USCA0438', 'name' => 'Graton');
$city_data[] = array('accid' => 'USCA0439', 'name' => 'Green Valley Lake');
$city_data[] = array('accid' => 'USCA0440', 'name' => 'Greenbrae');
$city_data[] = array('accid' => 'USCA0441', 'name' => 'Greenfield');
$city_data[] = array('accid' => 'USCA0442', 'name' => 'Greenview');
$city_data[] = array('accid' => 'USCA0443', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USCA0444', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USCA0445', 'name' => 'Grenada');
$city_data[] = array('accid' => 'USCA0446', 'name' => 'Gridley');
$city_data[] = array('accid' => 'USCA0447', 'name' => 'Grimes');
$city_data[] = array('accid' => 'USCA0448', 'name' => 'Grizzly Flats');
$city_data[] = array('accid' => 'USCA0449', 'name' => 'Groveland');
$city_data[] = array('accid' => 'USCA0450', 'name' => 'Grover Beach');
$city_data[] = array('accid' => 'USCA0451', 'name' => 'Guadalupe');
$city_data[] = array('accid' => 'USCA0452', 'name' => 'Gualala');
$city_data[] = array('accid' => 'USCA0453', 'name' => 'Guasti');
$city_data[] = array('accid' => 'USCA0454', 'name' => 'Guatay');
$city_data[] = array('accid' => 'USCA0455', 'name' => 'Guerneville');
$city_data[] = array('accid' => 'USCA0456', 'name' => 'Guinda');
$city_data[] = array('accid' => 'USCA0457', 'name' => 'Gustine');
$city_data[] = array('accid' => 'USCA0458', 'name' => 'Hacienda Heights');
$city_data[] = array('accid' => 'USCA0459', 'name' => 'Half Moon Bay');
$city_data[] = array('accid' => 'USCA0460', 'name' => 'Hamilton City');
$city_data[] = array('accid' => 'USCA0461', 'name' => 'Hanford');
$city_data[] = array('accid' => 'USCA0462', 'name' => 'Happy Camp');
$city_data[] = array('accid' => 'USCA0463', 'name' => 'Harbor City');
$city_data[] = array('accid' => 'USCA0464', 'name' => 'Harmony');
$city_data[] = array('accid' => 'USCA0465', 'name' => 'Hat Creek');
$city_data[] = array('accid' => 'USCA0466', 'name' => 'Hathaway Pines');
$city_data[] = array('accid' => 'USCA0467', 'name' => 'Hawaiian Gardens');
$city_data[] = array('accid' => 'USCA0468', 'name' => 'Hawthorne');
$city_data[] = array('accid' => 'USCA0469', 'name' => 'Hayfork');
$city_data[] = array('accid' => 'USCA0470', 'name' => 'Hayward');
$city_data[] = array('accid' => 'USCA0471', 'name' => 'Healdsburg');
$city_data[] = array('accid' => 'USCA0473', 'name' => 'Heber');
$city_data[] = array('accid' => 'USCA0474', 'name' => 'Helendale');
$city_data[] = array('accid' => 'USCA0475', 'name' => 'Helm');
$city_data[] = array('accid' => 'USCA0476', 'name' => 'Hemet');
$city_data[] = array('accid' => 'USCA0477', 'name' => 'Herald');
$city_data[] = array('accid' => 'USCA0478', 'name' => 'Hercules');
$city_data[] = array('accid' => 'USCA0479', 'name' => 'Herlong');
$city_data[] = array('accid' => 'USCA0480', 'name' => 'Hermosa Beach');
$city_data[] = array('accid' => 'USCA0481', 'name' => 'Hesperia');
$city_data[] = array('accid' => 'USCA0482', 'name' => 'Hickman');
$city_data[] = array('accid' => 'USCA0483', 'name' => 'Highland');
$city_data[] = array('accid' => 'USCA0484', 'name' => 'Hilmar');
$city_data[] = array('accid' => 'USCA0485', 'name' => 'Hinkley');
$city_data[] = array('accid' => 'USCA0486', 'name' => 'Hollister');
$city_data[] = array('accid' => 'USCA0487', 'name' => 'Holt');
$city_data[] = array('accid' => 'USCA0488', 'name' => 'Holtville');
$city_data[] = array('accid' => 'USCA0489', 'name' => 'Holy City');
$city_data[] = array('accid' => 'USCA0490', 'name' => 'Homeland');
$city_data[] = array('accid' => 'USCA0491', 'name' => 'Homewood');
$city_data[] = array('accid' => 'USCA0492', 'name' => 'Honeydew');
$city_data[] = array('accid' => 'USCA0493', 'name' => 'Hood');
$city_data[] = array('accid' => 'USCA0494', 'name' => 'Hoopa');
$city_data[] = array('accid' => 'USCA0495', 'name' => 'Hopland');
$city_data[] = array('accid' => 'USCA0496', 'name' => 'Hornbrook');
$city_data[] = array('accid' => 'USCA0497', 'name' => 'Hornitos');
$city_data[] = array('accid' => 'USCA0498', 'name' => 'Hughson');
$city_data[] = array('accid' => 'USCA0499', 'name' => 'Hume');
$city_data[] = array('accid' => 'USCA0500', 'name' => 'Huntington Beach');
$city_data[] = array('accid' => 'USCA0502', 'name' => 'Huntington Park');
$city_data[] = array('accid' => 'USCA0503', 'name' => 'Huron');
$city_data[] = array('accid' => 'USCA0504', 'name' => 'Hyampom');
$city_data[] = array('accid' => 'USCA0505', 'name' => 'Hydesville');
$city_data[] = array('accid' => 'USCA0506', 'name' => 'Idyllwild');
$city_data[] = array('accid' => 'USCA0507', 'name' => 'Igo');
$city_data[] = array('accid' => 'USCA0508', 'name' => 'Imperial');
$city_data[] = array('accid' => 'USCA0509', 'name' => 'Imperial Beach');
$city_data[] = array('accid' => 'USCA0510', 'name' => 'Independence');
$city_data[] = array('accid' => 'USCA0511', 'name' => 'Indian Wells');
$city_data[] = array('accid' => 'USCA0512', 'name' => 'Indio');
$city_data[] = array('accid' => 'USCA0513', 'name' => 'Inglewood');
$city_data[] = array('accid' => 'USCA0514', 'name' => 'Inverness');
$city_data[] = array('accid' => 'USCA0515', 'name' => 'Inyokern');
$city_data[] = array('accid' => 'USCA0516', 'name' => 'Ione');
$city_data[] = array('accid' => 'USCA0517', 'name' => 'Irvine');
$city_data[] = array('accid' => 'USCA0518', 'name' => 'Isleton');
$city_data[] = array('accid' => 'USCA0519', 'name' => 'Ivanhoe');
$city_data[] = array('accid' => 'USCA0520', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USCA0521', 'name' => 'Jacumba');
$city_data[] = array('accid' => 'USCA0522', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USCA0523', 'name' => 'Jamul');
$city_data[] = array('accid' => 'USCA0524', 'name' => 'Janesville');
$city_data[] = array('accid' => 'USCA0525', 'name' => 'Jenner');
$city_data[] = array('accid' => 'USCA0526', 'name' => 'Johannesburg');
$city_data[] = array('accid' => 'USCA0527', 'name' => 'Jolon');
$city_data[] = array('accid' => 'USCA0528', 'name' => 'Joshua Tree');
$city_data[] = array('accid' => 'USCA0530', 'name' => 'Julian');
$city_data[] = array('accid' => 'USCA0531', 'name' => 'Junction City');
$city_data[] = array('accid' => 'USCA0532', 'name' => 'June Lake');
$city_data[] = array('accid' => 'USCA0534', 'name' => 'Kaweah');
$city_data[] = array('accid' => 'USCA0535', 'name' => 'Keeler');
$city_data[] = array('accid' => 'USCA0536', 'name' => 'Keene');
$city_data[] = array('accid' => 'USCA0537', 'name' => 'Kelseyville');
$city_data[] = array('accid' => 'USCA0538', 'name' => 'Kentfield');
$city_data[] = array('accid' => 'USCA0539', 'name' => 'Kenwood');
$city_data[] = array('accid' => 'USCA0540', 'name' => 'Kerman');
$city_data[] = array('accid' => 'USCA0541', 'name' => 'Kernville');
$city_data[] = array('accid' => 'USCA0542', 'name' => 'Kettleman City');
$city_data[] = array('accid' => 'USCA0543', 'name' => 'Keyes');
$city_data[] = array('accid' => 'USCA0544', 'name' => 'King City');
$city_data[] = array('accid' => 'USCA0545', 'name' => 'Kings Beach');
$city_data[] = array('accid' => 'USCA0549', 'name' => 'Kingsburg');
$city_data[] = array('accid' => 'USCA0550', 'name' => 'Kirkwood');
$city_data[] = array('accid' => 'USCA0552', 'name' => 'Kit Carson');
$city_data[] = array('accid' => 'USCA0553', 'name' => 'Klamath');
$city_data[] = array('accid' => 'USCA0554', 'name' => 'Klamath River');
$city_data[] = array('accid' => 'USCA0555', 'name' => 'Kneeland');
$city_data[] = array('accid' => 'USCA0556', 'name' => 'Knights Landing');
$city_data[] = array('accid' => 'USCA0557', 'name' => 'Knightsen');
$city_data[] = array('accid' => 'USCA0558', 'name' => 'Korbel');
$city_data[] = array('accid' => 'USCA0559', 'name' => 'Kyburz');
$city_data[] = array('accid' => 'USCA0560', 'name' => 'La Canada Flintridge');
$city_data[] = array('accid' => 'USCA0561', 'name' => 'La Crescenta');
$city_data[] = array('accid' => 'USCA0562', 'name' => 'La Grange');
$city_data[] = array('accid' => 'USCA0563', 'name' => 'La Habra');
$city_data[] = array('accid' => 'USCA0564', 'name' => 'La Honda');
$city_data[] = array('accid' => 'USCA0565', 'name' => 'La Jolla');
$city_data[] = array('accid' => 'USCA0566', 'name' => 'La Mesa');
$city_data[] = array('accid' => 'USCA0567', 'name' => 'La Mirada');
$city_data[] = array('accid' => 'USCA0568', 'name' => 'La Palma');
$city_data[] = array('accid' => 'USCA0569', 'name' => 'La Puente');
$city_data[] = array('accid' => 'USCA0570', 'name' => 'La Quinta');
$city_data[] = array('accid' => 'USCA0571', 'name' => 'La Verne');
$city_data[] = array('accid' => 'USCA0572', 'name' => 'Lafayette');
$city_data[] = array('accid' => 'USCA0573', 'name' => 'Laguna Beach');
$city_data[] = array('accid' => 'USCA0574', 'name' => 'Laguna Hills');
$city_data[] = array('accid' => 'USCA0575', 'name' => 'Laguna Niguel');
$city_data[] = array('accid' => 'USCA0576', 'name' => 'Lagunitas');
$city_data[] = array('accid' => 'USCA0578', 'name' => 'Lake Arrowhead');
$city_data[] = array('accid' => 'USCA0579', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USCA0580', 'name' => 'Lake Elsinore');
$city_data[] = array('accid' => 'USCA0581', 'name' => 'Lake Forest');
$city_data[] = array('accid' => 'USCA0582', 'name' => 'Lake Hughes');
$city_data[] = array('accid' => 'USCA0583', 'name' => 'Lake Isabella');
$city_data[] = array('accid' => 'USCA0585', 'name' => 'Lakehead');
$city_data[] = array('accid' => 'USCA0586', 'name' => 'Lakeport');
$city_data[] = array('accid' => 'USCA0587', 'name' => 'Lakeshore');
$city_data[] = array('accid' => 'USCA0588', 'name' => 'Lakeside');
$city_data[] = array('accid' => 'USCA0589', 'name' => 'Lakewood');
$city_data[] = array('accid' => 'USCA0590', 'name' => 'Lamont');
$city_data[] = array('accid' => 'USCA0591', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USCA0592', 'name' => 'Landers');
$city_data[] = array('accid' => 'USCA0593', 'name' => 'Larkspur');
$city_data[] = array('accid' => 'USCA0595', 'name' => 'Lathrop');
$city_data[] = array('accid' => 'USCA0596', 'name' => 'Laton');
$city_data[] = array('accid' => 'USCA0597', 'name' => 'Lawndale');
$city_data[] = array('accid' => 'USCA0598', 'name' => 'Laytonville');
$city_data[] = array('accid' => 'USCA0599', 'name' => 'Le Grand');
$city_data[] = array('accid' => 'USCA0600', 'name' => 'Lebec');
$city_data[] = array('accid' => 'USCA0601', 'name' => 'Lee Vining');
$city_data[] = array('accid' => 'USCA0602', 'name' => 'Leggett');
$city_data[] = array('accid' => 'USCA0603', 'name' => 'Lemon Cove');
$city_data[] = array('accid' => 'USCA0604', 'name' => 'Lemon Grove');
$city_data[] = array('accid' => 'USCA0605', 'name' => 'Lemoore');
$city_data[] = array('accid' => 'USCA0606', 'name' => 'Lewiston');
$city_data[] = array('accid' => 'USCA0607', 'name' => 'Likely');
$city_data[] = array('accid' => 'USCA0608', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USCA0609', 'name' => 'Lincoln Acres');
$city_data[] = array('accid' => 'USCA0610', 'name' => 'Linden');
$city_data[] = array('accid' => 'USCA0611', 'name' => 'Lindsay');
$city_data[] = array('accid' => 'USCA0612', 'name' => 'Litchfield');
$city_data[] = array('accid' => 'USCA0613', 'name' => 'Little Lake');
$city_data[] = array('accid' => 'USCA0615', 'name' => 'Littleriver');
$city_data[] = array('accid' => 'USCA0616', 'name' => 'Littlerock');
$city_data[] = array('accid' => 'USCA0617', 'name' => 'Live Oak');
$city_data[] = array('accid' => 'USCA0618', 'name' => 'Livermore');
$city_data[] = array('accid' => 'USCA0619', 'name' => 'Livingston');
$city_data[] = array('accid' => 'USCA0620', 'name' => 'Llano');
$city_data[] = array('accid' => 'USCA0621', 'name' => 'Lockeford');
$city_data[] = array('accid' => 'USCA0622', 'name' => 'Lockwood');
$city_data[] = array('accid' => 'USCA0623', 'name' => 'Lodi');
$city_data[] = array('accid' => 'USCA0624', 'name' => 'Loleta');
$city_data[] = array('accid' => 'USCA0625', 'name' => 'Loma Linda');
$city_data[] = array('accid' => 'USCA0626', 'name' => 'Loma Mar');
$city_data[] = array('accid' => 'USCA0627', 'name' => 'Lomita');
$city_data[] = array('accid' => 'USCA0628', 'name' => 'Lompoc');
$city_data[] = array('accid' => 'USCA0630', 'name' => 'Lone Pine');
$city_data[] = array('accid' => 'USCA0631', 'name' => 'Long Barn');
$city_data[] = array('accid' => 'USCA0632', 'name' => 'Long Beach');
$city_data[] = array('accid' => 'USCA0633', 'name' => 'Lookout');
$city_data[] = array('accid' => 'USCA0634', 'name' => 'Loomis');
$city_data[] = array('accid' => 'USCA0635', 'name' => 'Los Alamitos');
$city_data[] = array('accid' => 'USCA0636', 'name' => 'Los Alamos');
$city_data[] = array('accid' => 'USCA0637', 'name' => 'Los Altos');
$city_data[] = array('accid' => 'USCA0638', 'name' => 'Los Angeles');
$city_data[] = array('accid' => 'USCA0640', 'name' => 'Los Banos');
$city_data[] = array('accid' => 'USCA0641', 'name' => 'Los Gatos');
$city_data[] = array('accid' => 'USCA0642', 'name' => 'Los Molinos');
$city_data[] = array('accid' => 'USCA0643', 'name' => 'Los Olivos');
$city_data[] = array('accid' => 'USCA0644', 'name' => 'Los Osos');
$city_data[] = array('accid' => 'USCA0645', 'name' => 'Lost Hills');
$city_data[] = array('accid' => 'USCA0646', 'name' => 'Lotus');
$city_data[] = array('accid' => 'USCA0647', 'name' => 'Lower Lake');
$city_data[] = array('accid' => 'USCA0648', 'name' => 'Loyalton');
$city_data[] = array('accid' => 'USCA0649', 'name' => 'Lucerne');
$city_data[] = array('accid' => 'USCA0650', 'name' => 'Lucerne Valley');
$city_data[] = array('accid' => 'USCA0651', 'name' => 'Ludlow');
$city_data[] = array('accid' => 'USCA0652', 'name' => 'Lynwood');
$city_data[] = array('accid' => 'USCA0653', 'name' => 'Lytle Creek');
$city_data[] = array('accid' => 'USCA0654', 'name' => 'MacDoel');
$city_data[] = array('accid' => 'USCA0655', 'name' => 'Mad River');
$city_data[] = array('accid' => 'USCA0656', 'name' => 'Madeline');
$city_data[] = array('accid' => 'USCA0657', 'name' => 'Madera');
$city_data[] = array('accid' => 'USCA0658', 'name' => 'Madison');
$city_data[] = array('accid' => 'USCA0659', 'name' => 'Magalia');
$city_data[] = array('accid' => 'USCA0660', 'name' => 'Malibu');
$city_data[] = array('accid' => 'USCA0661', 'name' => 'Mammoth Lakes');
$city_data[] = array('accid' => 'USCA0663', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USCA0664', 'name' => 'Manhattan Beach');
$city_data[] = array('accid' => 'USCA0665', 'name' => 'Manteca');
$city_data[] = array('accid' => 'USCA0666', 'name' => 'Manton');
$city_data[] = array('accid' => 'USCA0667', 'name' => 'March AFB');
$city_data[] = array('accid' => 'USCA0668', 'name' => 'Maricopa');
$city_data[] = array('accid' => 'USCA0669', 'name' => 'Marina');
$city_data[] = array('accid' => 'USCA0670', 'name' => 'Marina Del Rey');
$city_data[] = array('accid' => 'USCA0671', 'name' => 'Mariposa');
$city_data[] = array('accid' => 'USCA0672', 'name' => 'Markleeville');
$city_data[] = array('accid' => 'USCA0673', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USCA0674', 'name' => 'Martell');
$city_data[] = array('accid' => 'USCA0675', 'name' => 'Martinez');
$city_data[] = array('accid' => 'USCA0676', 'name' => 'Marysville');
$city_data[] = array('accid' => 'USCA0678', 'name' => 'Mather');
$city_data[] = array('accid' => 'USCA0679', 'name' => 'Maxwell');
$city_data[] = array('accid' => 'USCA0680', 'name' => 'Maywood');
$city_data[] = array('accid' => 'USCA0681', 'name' => 'McArthur');
$city_data[] = array('accid' => 'USCA0682', 'name' => 'McClellan AFB');
$city_data[] = array('accid' => 'USCA0683', 'name' => 'McCloud');
$city_data[] = array('accid' => 'USCA0684', 'name' => 'McFarland');
$city_data[] = array('accid' => 'USCA0685', 'name' => 'McKinleyville');
$city_data[] = array('accid' => 'USCA0686', 'name' => 'McKittrick');
$city_data[] = array('accid' => 'USCA0687', 'name' => 'Meadow Valley');
$city_data[] = array('accid' => 'USCA0688', 'name' => 'Meadow Vista');
$city_data[] = array('accid' => 'USCA0689', 'name' => 'Mecca');
$city_data[] = array('accid' => 'USCA0690', 'name' => 'Mendocino');
$city_data[] = array('accid' => 'USCA0691', 'name' => 'Mendota');
$city_data[] = array('accid' => 'USCA0692', 'name' => 'Menifee');
$city_data[] = array('accid' => 'USCA0693', 'name' => 'Menlo Park');
$city_data[] = array('accid' => 'USCA0694', 'name' => 'Mentone');
$city_data[] = array('accid' => 'USCA0695', 'name' => 'Merced');
$city_data[] = array('accid' => 'USCA0696', 'name' => 'Meridian');
$city_data[] = array('accid' => 'USCA0697', 'name' => 'Mi Wuk Village');
$city_data[] = array('accid' => 'USCA0698', 'name' => 'Middletown');
$city_data[] = array('accid' => 'USCA0699', 'name' => 'Midpines');
$city_data[] = array('accid' => 'USCA0700', 'name' => 'Midway City');
$city_data[] = array('accid' => 'USCA0701', 'name' => 'Milford');
$city_data[] = array('accid' => 'USCA0702', 'name' => 'Mill Creek');
$city_data[] = array('accid' => 'USCA0703', 'name' => 'Mill Valley');
$city_data[] = array('accid' => 'USCA0704', 'name' => 'Millbrae');
$city_data[] = array('accid' => 'USCA0705', 'name' => 'Millville');
$city_data[] = array('accid' => 'USCA0706', 'name' => 'Milpitas');
$city_data[] = array('accid' => 'USCA0707', 'name' => 'Mineral');
$city_data[] = array('accid' => 'USCA0708', 'name' => 'Mira Loma');
$city_data[] = array('accid' => 'USCA0709', 'name' => 'Miramonte');
$city_data[] = array('accid' => 'USCA0710', 'name' => 'Miranda');
$city_data[] = array('accid' => 'USCA0711', 'name' => 'Mission Hills');
$city_data[] = array('accid' => 'USCA0712', 'name' => 'Mission Viejo');
$city_data[] = array('accid' => 'USCA0713', 'name' => 'Moccasin');
$city_data[] = array('accid' => 'USCA0714', 'name' => 'Modesto');
$city_data[] = array('accid' => 'USCA0715', 'name' => 'Mojave');
$city_data[] = array('accid' => 'USCA0716', 'name' => 'Mokelumne Hill');
$city_data[] = array('accid' => 'USCA0717', 'name' => 'Mono Hot Springs');
$city_data[] = array('accid' => 'USCA0718', 'name' => 'Monrovia');
$city_data[] = array('accid' => 'USCA0719', 'name' => 'Montague');
$city_data[] = array('accid' => 'USCA0720', 'name' => 'Montara');
$city_data[] = array('accid' => 'USCA0721', 'name' => 'Montclair');
$city_data[] = array('accid' => 'USCA0722', 'name' => 'Monte Rio');
$city_data[] = array('accid' => 'USCA0723', 'name' => 'Montebello');
$city_data[] = array('accid' => 'USCA0724', 'name' => 'Monterey');
$city_data[] = array('accid' => 'USCA0725', 'name' => 'Monterey Park');
$city_data[] = array('accid' => 'USCA0726', 'name' => 'Montgomery Creek');
$city_data[] = array('accid' => 'USCA0727', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USCA0728', 'name' => 'Moorpark');
$city_data[] = array('accid' => 'USCA0729', 'name' => 'Moraga');
$city_data[] = array('accid' => 'USCA0730', 'name' => 'Moreno Valley');
$city_data[] = array('accid' => 'USCA0731', 'name' => 'Morgan Hill');
$city_data[] = array('accid' => 'USCA0732', 'name' => 'Morongo Valley');
$city_data[] = array('accid' => 'USCA0733', 'name' => 'Morro Bay');
$city_data[] = array('accid' => 'USCA0734', 'name' => 'Moss Beach');
$city_data[] = array('accid' => 'USCA0735', 'name' => 'Moss Landing');
$city_data[] = array('accid' => 'USCA0736', 'name' => 'Mount Aukum');
$city_data[] = array('accid' => 'USCA0737', 'name' => 'Mount Baldy');
$city_data[] = array('accid' => 'USCA0738', 'name' => 'Mount Hamilton');
$city_data[] = array('accid' => 'USCA0739', 'name' => 'Mount Hermon');
$city_data[] = array('accid' => 'USCA0740', 'name' => 'Mount Laguna');
$city_data[] = array('accid' => 'USCA0741', 'name' => 'Mount Shasta');
$city_data[] = array('accid' => 'USCA0742', 'name' => 'Mount Wilson');
$city_data[] = array('accid' => 'USCA0743', 'name' => 'Mountain Center');
$city_data[] = array('accid' => 'USCA0744', 'name' => 'Mountain Pass');
$city_data[] = array('accid' => 'USCA0745', 'name' => 'Mountain Ranch');
$city_data[] = array('accid' => 'USCA0746', 'name' => 'Mountain View');
$city_data[] = array('accid' => 'USCA0747', 'name' => 'Murphys');
$city_data[] = array('accid' => 'USCA0748', 'name' => 'Murrieta');
$city_data[] = array('accid' => 'USCA0749', 'name' => 'Myers Flat');
$city_data[] = array('accid' => 'USCA0750', 'name' => 'Napa');
$city_data[] = array('accid' => 'USCA0751', 'name' => 'National City');
$city_data[] = array('accid' => 'USCA0752', 'name' => 'Navarro');
$city_data[] = array('accid' => 'USCA0753', 'name' => 'Needles');
$city_data[] = array('accid' => 'USCA0754', 'name' => 'Nelson');
$city_data[] = array('accid' => 'USCA0755', 'name' => 'Nevada City');
$city_data[] = array('accid' => 'USCA0756', 'name' => 'New Almaden');
$city_data[] = array('accid' => 'USCA0757', 'name' => 'New Cuyama');
$city_data[] = array('accid' => 'USCA0758', 'name' => 'Newark');
$city_data[] = array('accid' => 'USCA0759', 'name' => 'Newberry Springs');
$city_data[] = array('accid' => 'USCA0760', 'name' => 'Newbury Park');
$city_data[] = array('accid' => 'USCA0761', 'name' => 'Newcastle');
$city_data[] = array('accid' => 'USCA0762', 'name' => 'Newhall');
$city_data[] = array('accid' => 'USCA0763', 'name' => 'Newman');
$city_data[] = array('accid' => 'USCA0764', 'name' => 'Newport Beach');
$city_data[] = array('accid' => 'USCA0765', 'name' => 'Newport Coast');
$city_data[] = array('accid' => 'USCA0766', 'name' => 'Nicasio');
$city_data[] = array('accid' => 'USCA0767', 'name' => 'Nice');
$city_data[] = array('accid' => 'USCA0768', 'name' => 'Nicolaus');
$city_data[] = array('accid' => 'USCA0769', 'name' => 'Niland');
$city_data[] = array('accid' => 'USCA0770', 'name' => 'Nipomo');
$city_data[] = array('accid' => 'USCA0771', 'name' => 'Nipton');
$city_data[] = array('accid' => 'USCA0772', 'name' => 'Norco');
$city_data[] = array('accid' => 'USCA0773', 'name' => 'Norden');
$city_data[] = array('accid' => 'USCA0774', 'name' => 'North Fork');
$city_data[] = array('accid' => 'USCA0775', 'name' => 'North Highlands');
$city_data[] = array('accid' => 'USCA0776', 'name' => 'North Hills');
$city_data[] = array('accid' => 'USCA0777', 'name' => 'North Hollywood');
$city_data[] = array('accid' => 'USCA0778', 'name' => 'North Palm Springs');
$city_data[] = array('accid' => 'USCA0779', 'name' => 'North San Juan');
$city_data[] = array('accid' => 'USCA0780', 'name' => 'Northridge');
$city_data[] = array('accid' => 'USCA0782', 'name' => 'Norwalk');
$city_data[] = array('accid' => 'USCA0783', 'name' => 'Novato');
$city_data[] = array('accid' => 'USCA0784', 'name' => 'Nubieber');
$city_data[] = array('accid' => 'USCA0785', 'name' => 'Nuevo');
$city_data[] = array('accid' => 'USCA0805', 'name' => 'O\'neals');
$city_data[] = array('accid' => 'USCA0786', 'name' => 'Oak Park');
$city_data[] = array('accid' => 'USCA0787', 'name' => 'Oak Run');
$city_data[] = array('accid' => 'USCA0788', 'name' => 'Oak View');
$city_data[] = array('accid' => 'USCA0789', 'name' => 'Oakdale');
$city_data[] = array('accid' => 'USCA0790', 'name' => 'Oakhurst');
$city_data[] = array('accid' => 'USCA0791', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USCA0792', 'name' => 'Oakley');
$city_data[] = array('accid' => 'USCA0793', 'name' => 'Oakville');
$city_data[] = array('accid' => 'USCA0794', 'name' => 'Obrien');
$city_data[] = array('accid' => 'USCA0795', 'name' => 'Occidental');
$city_data[] = array('accid' => 'USCA0796', 'name' => 'Oceano');
$city_data[] = array('accid' => 'USCA0797', 'name' => 'Oceanside');
$city_data[] = array('accid' => 'USCA0798', 'name' => 'Ocotillo');
$city_data[] = array('accid' => 'USCA0799', 'name' => 'Ojai');
$city_data[] = array('accid' => 'USCA0800', 'name' => 'Olancha');
$city_data[] = array('accid' => 'USCA0801', 'name' => 'Old Station');
$city_data[] = array('accid' => 'USCA0802', 'name' => 'Olema');
$city_data[] = array('accid' => 'USCA0803', 'name' => 'Olivehurst');
$city_data[] = array('accid' => 'USCA0804', 'name' => 'Olympic Valley');
$city_data[] = array('accid' => 'USCA0806', 'name' => 'Ontario');
$city_data[] = array('accid' => 'USCA0807', 'name' => 'Onyx');
$city_data[] = array('accid' => 'USCA0808', 'name' => 'Orange');
$city_data[] = array('accid' => 'USCA0809', 'name' => 'Orange Cove');
$city_data[] = array('accid' => 'USCA0810', 'name' => 'Orangevale');
$city_data[] = array('accid' => 'USCA0811', 'name' => 'Oregon House');
$city_data[] = array('accid' => 'USCA0812', 'name' => 'Orick');
$city_data[] = array('accid' => 'USCA0813', 'name' => 'Orinda');
$city_data[] = array('accid' => 'USCA0814', 'name' => 'Orland');
$city_data[] = array('accid' => 'USCA0815', 'name' => 'Orleans');
$city_data[] = array('accid' => 'USCA0816', 'name' => 'Oro Grande');
$city_data[] = array('accid' => 'USCA0817', 'name' => 'Orosi');
$city_data[] = array('accid' => 'USCA0818', 'name' => 'Oroville');
$city_data[] = array('accid' => 'USCA0819', 'name' => 'Oxnard');
$city_data[] = array('accid' => 'USCA0820', 'name' => 'Pacific Grove');
$city_data[] = array('accid' => 'USCA0821', 'name' => 'Pacific Palisades');
$city_data[] = array('accid' => 'USCA0822', 'name' => 'Pacifica');
$city_data[] = array('accid' => 'USCA0823', 'name' => 'Pacoima');
$city_data[] = array('accid' => 'USCA0824', 'name' => 'Paicines');
$city_data[] = array('accid' => 'USCA0825', 'name' => 'Pala');
$city_data[] = array('accid' => 'USCA0826', 'name' => 'Palermo');
$city_data[] = array('accid' => 'USCA0827', 'name' => 'Palm Desert');
$city_data[] = array('accid' => 'USCA0828', 'name' => 'Palm Springs');
$city_data[] = array('accid' => 'USCA0829', 'name' => 'Palmdale');
$city_data[] = array('accid' => 'USCA0830', 'name' => 'Palo Alto');
$city_data[] = array('accid' => 'USCA0831', 'name' => 'Palo Cedro');
$city_data[] = array('accid' => 'USCA0832', 'name' => 'Palo Verde');
$city_data[] = array('accid' => 'USCA0833', 'name' => 'Palomar Mountain');
$city_data[] = array('accid' => 'USCA0835', 'name' => 'Panorama City');
$city_data[] = array('accid' => 'USCA0836', 'name' => 'Paradise');
$city_data[] = array('accid' => 'USCA0837', 'name' => 'Paramount');
$city_data[] = array('accid' => 'USCA0838', 'name' => 'Parker Dam');
$city_data[] = array('accid' => 'USCA0839', 'name' => 'Parlier');
$city_data[] = array('accid' => 'USCA0840', 'name' => 'Pasadena');
$city_data[] = array('accid' => 'USCA0841', 'name' => 'Paskenta');
$city_data[] = array('accid' => 'USCA0842', 'name' => 'Paso Robles');
$city_data[] = array('accid' => 'USCA0843', 'name' => 'Patterson');
$city_data[] = array('accid' => 'USCA0844', 'name' => 'Patton');
$city_data[] = array('accid' => 'USCA0845', 'name' => 'Pauma Valley');
$city_data[] = array('accid' => 'USCA0846', 'name' => 'Paynes Creek');
$city_data[] = array('accid' => 'USCA0847', 'name' => 'Pearblossom');
$city_data[] = array('accid' => 'USCA0848', 'name' => 'Pebble Beach');
$city_data[] = array('accid' => 'USCA0849', 'name' => 'Penn Valley');
$city_data[] = array('accid' => 'USCA0850', 'name' => 'Penngrove');
$city_data[] = array('accid' => 'USCA0851', 'name' => 'Penryn');
$city_data[] = array('accid' => 'USCA0852', 'name' => 'Perris');
$city_data[] = array('accid' => 'USCA0853', 'name' => 'Pescadero');
$city_data[] = array('accid' => 'USCA0854', 'name' => 'Petaluma');
$city_data[] = array('accid' => 'USCA0855', 'name' => 'Petrolia');
$city_data[] = array('accid' => 'USCA0856', 'name' => 'Phelan');
$city_data[] = array('accid' => 'USCA0857', 'name' => 'Phillipsville');
$city_data[] = array('accid' => 'USCA0858', 'name' => 'Philo');
$city_data[] = array('accid' => 'USCA0859', 'name' => 'Pico Rivera');
$city_data[] = array('accid' => 'USCA0860', 'name' => 'Piedmont');
$city_data[] = array('accid' => 'USCA0861', 'name' => 'Piedra');
$city_data[] = array('accid' => 'USCA0862', 'name' => 'Piercy');
$city_data[] = array('accid' => 'USCA0863', 'name' => 'Pilot Hill');
$city_data[] = array('accid' => 'USCA0864', 'name' => 'Pine Grove');
$city_data[] = array('accid' => 'USCA0865', 'name' => 'Pine Valley');
$city_data[] = array('accid' => 'USCA0866', 'name' => 'Pinecrest');
$city_data[] = array('accid' => 'USCA0867', 'name' => 'Pinole');
$city_data[] = array('accid' => 'USCA0868', 'name' => 'Pinon Hills');
$city_data[] = array('accid' => 'USCA0869', 'name' => 'Pioneer');
$city_data[] = array('accid' => 'USCA0870', 'name' => 'Pioneertown');
$city_data[] = array('accid' => 'USCA0871', 'name' => 'Piru');
$city_data[] = array('accid' => 'USCA0872', 'name' => 'Pismo Beach');
$city_data[] = array('accid' => 'USCA0873', 'name' => 'Pittsburg');
$city_data[] = array('accid' => 'USCA0874', 'name' => 'Pixley');
$city_data[] = array('accid' => 'USCA0875', 'name' => 'Placentia');
$city_data[] = array('accid' => 'USCA0876', 'name' => 'Placerville');
$city_data[] = array('accid' => 'USCA0877', 'name' => 'Planada');
$city_data[] = array('accid' => 'USCA0878', 'name' => 'Platina');
$city_data[] = array('accid' => 'USCA0879', 'name' => 'Playa Del Rey');
$city_data[] = array('accid' => 'USCA0880', 'name' => 'Pleasant Grove');
$city_data[] = array('accid' => 'USCA0881', 'name' => 'Pleasant Hill');
$city_data[] = array('accid' => 'USCA0882', 'name' => 'Pleasanton');
$city_data[] = array('accid' => 'USCA0883', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USCA0884', 'name' => 'Point Arena');
$city_data[] = array('accid' => 'USCA0886', 'name' => 'Point Mugu NAWC');
$city_data[] = array('accid' => 'USCA0887', 'name' => 'Point Reyes Station');
$city_data[] = array('accid' => 'USCA0888', 'name' => 'Pollock Pines');
$city_data[] = array('accid' => 'USCA0889', 'name' => 'Pomona');
$city_data[] = array('accid' => 'USCA0890', 'name' => 'Pope Valley');
$city_data[] = array('accid' => 'USCA0891', 'name' => 'Port Costa');
$city_data[] = array('accid' => 'USCA0892', 'name' => 'Port Hueneme');
$city_data[] = array('accid' => 'USCA0893', 'name' => 'Port Hueneme CBC Base');
$city_data[] = array('accid' => 'USCA0894', 'name' => 'Porterville');
$city_data[] = array('accid' => 'USCA0895', 'name' => 'Portola');
$city_data[] = array('accid' => 'USCA0896', 'name' => 'Portola Valley');
$city_data[] = array('accid' => 'USCA0897', 'name' => 'Posey');
$city_data[] = array('accid' => 'USCA0898', 'name' => 'Potrero');
$city_data[] = array('accid' => 'USCA0899', 'name' => 'Potter Valley');
$city_data[] = array('accid' => 'USCA0900', 'name' => 'Poway');
$city_data[] = array('accid' => 'USCA0901', 'name' => 'Prather');
$city_data[] = array('accid' => 'USCA0902', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USCA0903', 'name' => 'Proberta');
$city_data[] = array('accid' => 'USCA0904', 'name' => 'Quincy');
$city_data[] = array('accid' => 'USCA0905', 'name' => 'Rackerby');
$city_data[] = array('accid' => 'USCA0906', 'name' => 'Rail Road Flat');
$city_data[] = array('accid' => 'USCA0907', 'name' => 'Raisin');
$city_data[] = array('accid' => 'USCA0908', 'name' => 'Ramona');
$city_data[] = array('accid' => 'USCA0909', 'name' => 'Ranchita');
$city_data[] = array('accid' => 'USCA0910', 'name' => 'Rancho Cordova');
$city_data[] = array('accid' => 'USCA0911', 'name' => 'Rancho Cucamonga');
$city_data[] = array('accid' => 'USCA0912', 'name' => 'Rancho Mirage');
$city_data[] = array('accid' => 'USCA0913', 'name' => 'Rancho Palos Verdes');
$city_data[] = array('accid' => 'USCA0914', 'name' => 'Rancho Santa Fe');
$city_data[] = array('accid' => 'USCA0915', 'name' => 'Rancho Santa Margarita');
$city_data[] = array('accid' => 'USCA0916', 'name' => 'Randsburg');
$city_data[] = array('accid' => 'USCA0917', 'name' => 'Ravendale');
$city_data[] = array('accid' => 'USCA0918', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USCA0919', 'name' => 'Red Bluff');
$city_data[] = array('accid' => 'USCA0920', 'name' => 'Red Mountain');
$city_data[] = array('accid' => 'USCA0921', 'name' => 'Redcrest');
$city_data[] = array('accid' => 'USCA0922', 'name' => 'Redding');
$city_data[] = array('accid' => 'USCA0923', 'name' => 'Redlands');
$city_data[] = array('accid' => 'USCA0924', 'name' => 'Redondo Beach');
$city_data[] = array('accid' => 'USCA0925', 'name' => 'Redway');
$city_data[] = array('accid' => 'USCA0926', 'name' => 'Redwood City');
$city_data[] = array('accid' => 'USCA0927', 'name' => 'Redwood Estates');
$city_data[] = array('accid' => 'USCA0929', 'name' => 'Redwood Valley');
$city_data[] = array('accid' => 'USCA0930', 'name' => 'Reedley');
$city_data[] = array('accid' => 'USCA0931', 'name' => 'Represa');
$city_data[] = array('accid' => 'USCA0932', 'name' => 'Rescue');
$city_data[] = array('accid' => 'USCA0933', 'name' => 'Reseda');
$city_data[] = array('accid' => 'USCA0934', 'name' => 'Rialto');
$city_data[] = array('accid' => 'USCA0935', 'name' => 'Richgrove');
$city_data[] = array('accid' => 'USCA0936', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USCA0937', 'name' => 'Richvale');
$city_data[] = array('accid' => 'USCA0938', 'name' => 'Ridgecrest');
$city_data[] = array('accid' => 'USCA0939', 'name' => 'Rimforest');
$city_data[] = array('accid' => 'USCA0940', 'name' => 'Rio Dell');
$city_data[] = array('accid' => 'USCA0941', 'name' => 'Rio Linda');
$city_data[] = array('accid' => 'USCA0942', 'name' => 'Rio Nido');
$city_data[] = array('accid' => 'USCA0943', 'name' => 'Rio Oso');
$city_data[] = array('accid' => 'USCA0944', 'name' => 'Rio Vista');
$city_data[] = array('accid' => 'USCA0945', 'name' => 'Ripon');
$city_data[] = array('accid' => 'USCA0946', 'name' => 'River Pines');
$city_data[] = array('accid' => 'USCA0947', 'name' => 'Riverbank');
$city_data[] = array('accid' => 'USCA0948', 'name' => 'Riverdale');
$city_data[] = array('accid' => 'USCA0949', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USCA0951', 'name' => 'Robbins');
$city_data[] = array('accid' => 'USCA0952', 'name' => 'Rocklin');
$city_data[] = array('accid' => 'USCA0953', 'name' => 'Rodeo');
$city_data[] = array('accid' => 'USCA0954', 'name' => 'Rohnert Park');
$city_data[] = array('accid' => 'USCA0955', 'name' => 'Rosamond');
$city_data[] = array('accid' => 'USCA0956', 'name' => 'Rosemead');
$city_data[] = array('accid' => 'USCA0957', 'name' => 'Roseville');
$city_data[] = array('accid' => 'USCA0958', 'name' => 'Ross');
$city_data[] = array('accid' => 'USCA0959', 'name' => 'Rough And Ready');
$city_data[] = array('accid' => 'USCA0960', 'name' => 'Round Mountain');
$city_data[] = array('accid' => 'USCA0961', 'name' => 'Rowland Heights');
$city_data[] = array('accid' => 'USCA0963', 'name' => 'Rumsey');
$city_data[] = array('accid' => 'USCA0964', 'name' => 'Running Springs');
$city_data[] = array('accid' => 'USCA0965', 'name' => 'Rutherford');
$city_data[] = array('accid' => 'USCA0966', 'name' => 'Ryde');
$city_data[] = array('accid' => 'USCA0967', 'name' => 'Sacramento');
$city_data[] = array('accid' => 'USCA0969', 'name' => 'Saint Helena');
$city_data[] = array('accid' => 'USCA0970', 'name' => 'Salida');
$city_data[] = array('accid' => 'USCA0971', 'name' => 'Salinas');
$city_data[] = array('accid' => 'USCA0972', 'name' => 'Salton City');
$city_data[] = array('accid' => 'USCA0973', 'name' => 'Salyer');
$city_data[] = array('accid' => 'USCA0974', 'name' => 'Samoa');
$city_data[] = array('accid' => 'USCA0975', 'name' => 'San Andreas');
$city_data[] = array('accid' => 'USCA0976', 'name' => 'San Anselmo');
$city_data[] = array('accid' => 'USCA0977', 'name' => 'San Ardo');
$city_data[] = array('accid' => 'USCA0978', 'name' => 'San Bernardino');
$city_data[] = array('accid' => 'USCA0979', 'name' => 'San Bruno');
$city_data[] = array('accid' => 'USCA0980', 'name' => 'San Carlos');
$city_data[] = array('accid' => 'USCA0981', 'name' => 'San Clemente');
$city_data[] = array('accid' => 'USCA0982', 'name' => 'San Diego');
$city_data[] = array('accid' => 'USCA0985', 'name' => 'San Dimas');
$city_data[] = array('accid' => 'USCA0986', 'name' => 'San Fernando');
$city_data[] = array('accid' => 'USCA0987', 'name' => 'San Francisco');
$city_data[] = array('accid' => 'USCA0988', 'name' => 'San Gabriel');
$city_data[] = array('accid' => 'USCA0989', 'name' => 'San Geronimo');
$city_data[] = array('accid' => 'USCA0990', 'name' => 'San Gregorio');
$city_data[] = array('accid' => 'USCA0991', 'name' => 'San Jacinto');
$city_data[] = array('accid' => 'USCA0992', 'name' => 'San Joaquin');
$city_data[] = array('accid' => 'USCA0993', 'name' => 'San Jose');
$city_data[] = array('accid' => 'USCA0995', 'name' => 'San Juan Bautista');
$city_data[] = array('accid' => 'USCA0996', 'name' => 'San Juan Capistrano');
$city_data[] = array('accid' => 'USCA0997', 'name' => 'San Leandro');
$city_data[] = array('accid' => 'USCA0998', 'name' => 'San Lorenzo');
$city_data[] = array('accid' => 'USCA0999', 'name' => 'San Lucas');
$city_data[] = array('accid' => 'USCA1000', 'name' => 'San Luis Obispo');
$city_data[] = array('accid' => 'USCA1001', 'name' => 'San Luis Rey');
$city_data[] = array('accid' => 'USCA1002', 'name' => 'San Marcos');
$city_data[] = array('accid' => 'USCA1003', 'name' => 'San Marino');
$city_data[] = array('accid' => 'USCA1004', 'name' => 'San Martin');
$city_data[] = array('accid' => 'USCA1005', 'name' => 'San Mateo');
$city_data[] = array('accid' => 'USCA1006', 'name' => 'San Miguel');
$city_data[] = array('accid' => 'USCA1008', 'name' => 'San Pablo');
$city_data[] = array('accid' => 'USCA1009', 'name' => 'San Pedro');
$city_data[] = array('accid' => 'USCA1010', 'name' => 'San Quentin');
$city_data[] = array('accid' => 'USCA1011', 'name' => 'San Rafael');
$city_data[] = array('accid' => 'USCA1012', 'name' => 'San Ramon');
$city_data[] = array('accid' => 'USCA1013', 'name' => 'San Simeon');
$city_data[] = array('accid' => 'USCA1014', 'name' => 'San Ysidro');
$city_data[] = array('accid' => 'USCA1015', 'name' => 'Sanger');
$city_data[] = array('accid' => 'USCA1016', 'name' => 'Santa Ana');
$city_data[] = array('accid' => 'USCA1017', 'name' => 'Santa Barbara');
$city_data[] = array('accid' => 'USCA1018', 'name' => 'Santa Clara');
$city_data[] = array('accid' => 'USCA1019', 'name' => 'Santa Clarita');
$city_data[] = array('accid' => 'USCA1020', 'name' => 'Santa Cruz');
$city_data[] = array('accid' => 'USCA1021', 'name' => 'Santa Fe Springs');
$city_data[] = array('accid' => 'USCA1022', 'name' => 'Santa Margarita');
$city_data[] = array('accid' => 'USCA1023', 'name' => 'Santa Maria');
$city_data[] = array('accid' => 'USCA1024', 'name' => 'Santa Monica');
$city_data[] = array('accid' => 'USCA1025', 'name' => 'Santa Paula');
$city_data[] = array('accid' => 'USCA1026', 'name' => 'Santa Rita Park');
$city_data[] = array('accid' => 'USCA1027', 'name' => 'Santa Rosa');
$city_data[] = array('accid' => 'USCA1028', 'name' => 'Santa Ynez');
$city_data[] = array('accid' => 'USCA1029', 'name' => 'Santa Ysabel');
$city_data[] = array('accid' => 'USCA1030', 'name' => 'Santee');
$city_data[] = array('accid' => 'USCA1031', 'name' => 'Saratoga');
$city_data[] = array('accid' => 'USCA1032', 'name' => 'Sausalito');
$city_data[] = array('accid' => 'USCA1033', 'name' => 'Scotia');
$city_data[] = array('accid' => 'USCA1034', 'name' => 'Scott Bar');
$city_data[] = array('accid' => 'USCA1035', 'name' => 'Scotts Valley');
$city_data[] = array('accid' => 'USCA1036', 'name' => 'Seal Beach');
$city_data[] = array('accid' => 'USCA1037', 'name' => 'Seaside');
$city_data[] = array('accid' => 'USCA1038', 'name' => 'Sebastopol');
$city_data[] = array('accid' => 'USCA1039', 'name' => 'Seeley');
$city_data[] = array('accid' => 'USCA1040', 'name' => 'Seiad Valley');
$city_data[] = array('accid' => 'USCA1041', 'name' => 'Selma');
$city_data[] = array('accid' => 'USCA1042', 'name' => 'Sequoia Natl Park');
$city_data[] = array('accid' => 'USCA1043', 'name' => 'Shafter');
$city_data[] = array('accid' => 'USCA1044', 'name' => 'Shandon');
$city_data[] = array('accid' => 'USCA1045', 'name' => 'Shasta');
$city_data[] = array('accid' => 'USCA1046', 'name' => 'Shasta Lake');
$city_data[] = array('accid' => 'USCA1047', 'name' => 'Shaver Lake');
$city_data[] = array('accid' => 'USCA1048', 'name' => 'Sheep Ranch');
$city_data[] = array('accid' => 'USCA1050', 'name' => 'Sheridan');
$city_data[] = array('accid' => 'USCA1051', 'name' => 'Sherman Oaks');
$city_data[] = array('accid' => 'USCA1052', 'name' => 'Shingle Springs');
$city_data[] = array('accid' => 'USCA1053', 'name' => 'Shingletown');
$city_data[] = array('accid' => 'USCA1054', 'name' => 'Shoshone');
$city_data[] = array('accid' => 'USCA1055', 'name' => 'Sierra City');
$city_data[] = array('accid' => 'USCA1056', 'name' => 'Sierra Madre');
$city_data[] = array('accid' => 'USCA1058', 'name' => 'Sierraville');
$city_data[] = array('accid' => 'USCA1301', 'name' => 'Signal Hill');
$city_data[] = array('accid' => 'USCA1059', 'name' => 'Silverado');
$city_data[] = array('accid' => 'USCA1060', 'name' => 'Simi Valley');
$city_data[] = array('accid' => 'USCA1062', 'name' => 'Skyforest');
$city_data[] = array('accid' => 'USCA1063', 'name' => 'Sloughhouse');
$city_data[] = array('accid' => 'USCA1064', 'name' => 'Smartville');
$city_data[] = array('accid' => 'USCA1065', 'name' => 'Smith River');
$city_data[] = array('accid' => 'USCA1066', 'name' => 'Snelling');
$city_data[] = array('accid' => 'USCA1069', 'name' => 'Soda Springs');
$city_data[] = array('accid' => 'USCA1070', 'name' => 'Solana Beach');
$city_data[] = array('accid' => 'USCA1071', 'name' => 'Soledad');
$city_data[] = array('accid' => 'USCA1072', 'name' => 'Solvang');
$city_data[] = array('accid' => 'USCA1073', 'name' => 'Somerset');
$city_data[] = array('accid' => 'USCA1074', 'name' => 'Somes Bar');
$city_data[] = array('accid' => 'USCA1075', 'name' => 'Somis');
$city_data[] = array('accid' => 'USCA1076', 'name' => 'Sonoma');
$city_data[] = array('accid' => 'USCA1077', 'name' => 'Sonora');
$city_data[] = array('accid' => 'USCA1078', 'name' => 'Soquel');
$city_data[] = array('accid' => 'USCA1079', 'name' => 'Soulsbyville');
$city_data[] = array('accid' => 'USCA1080', 'name' => 'South Dos Palos');
$city_data[] = array('accid' => 'USCA1081', 'name' => 'South El Monte');
$city_data[] = array('accid' => 'USCA1082', 'name' => 'South Gate');
$city_data[] = array('accid' => 'USCA1083', 'name' => 'South Lake Tahoe');
$city_data[] = array('accid' => 'USCA1084', 'name' => 'South Pasadena');
$city_data[] = array('accid' => 'USCA1085', 'name' => 'South San Francisco');
$city_data[] = array('accid' => 'USCA1086', 'name' => 'Spreckels');
$city_data[] = array('accid' => 'USCA1087', 'name' => 'Spring Valley');
$city_data[] = array('accid' => 'USCA1088', 'name' => 'Springville');
$city_data[] = array('accid' => 'USCA1089', 'name' => 'Squaw Valley');
$city_data[] = array('accid' => 'USCA1091', 'name' => 'Standard');
$city_data[] = array('accid' => 'USCA1092', 'name' => 'Standish');
$city_data[] = array('accid' => 'USCA1093', 'name' => 'Stanford');
$city_data[] = array('accid' => 'USCA1094', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USCA1095', 'name' => 'Stevenson Ranch');
$city_data[] = array('accid' => 'USCA1096', 'name' => 'Stevinson');
$city_data[] = array('accid' => 'USCA1097', 'name' => 'Stewarts Point');
$city_data[] = array('accid' => 'USCA1098', 'name' => 'Stinson Beach');
$city_data[] = array('accid' => 'USCA1099', 'name' => 'Stirling City');
$city_data[] = array('accid' => 'USCA1100', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USCA1101', 'name' => 'Stonyford');
$city_data[] = array('accid' => 'USCA1102', 'name' => 'Storrie');
$city_data[] = array('accid' => 'USCA1103', 'name' => 'Stratford');
$city_data[] = array('accid' => 'USCA1104', 'name' => 'Strathmore');
$city_data[] = array('accid' => 'USCA1105', 'name' => 'Strawberry');
$city_data[] = array('accid' => 'USCA1106', 'name' => 'Strawberry Valley');
$city_data[] = array('accid' => 'USCA1107', 'name' => 'Studio City');
$city_data[] = array('accid' => 'USCA1109', 'name' => 'Sugarloaf');
$city_data[] = array('accid' => 'USCA1110', 'name' => 'Suisun City');
$city_data[] = array('accid' => 'USCA1111', 'name' => 'Sultana');
$city_data[] = array('accid' => 'USCA1112', 'name' => 'Summerland');
$city_data[] = array('accid' => 'USCA1113', 'name' => 'Sun City');
$city_data[] = array('accid' => 'USCA1114', 'name' => 'Sun Valley');
$city_data[] = array('accid' => 'USCA1115', 'name' => 'Sunland');
$city_data[] = array('accid' => 'USCA1116', 'name' => 'Sunnyvale');
$city_data[] = array('accid' => 'USCA1117', 'name' => 'Sunol');
$city_data[] = array('accid' => 'USCA1118', 'name' => 'Sunset Beach');
$city_data[] = array('accid' => 'USCA1119', 'name' => 'Surfside');
$city_data[] = array('accid' => 'USCA1120', 'name' => 'Susanville');
$city_data[] = array('accid' => 'USCA1121', 'name' => 'Sutter');
$city_data[] = array('accid' => 'USCA1122', 'name' => 'Sutter Creek');
$city_data[] = array('accid' => 'USCA1123', 'name' => 'Sylmar');
$city_data[] = array('accid' => 'USCA1124', 'name' => 'Taft');
$city_data[] = array('accid' => 'USCA1125', 'name' => 'Tahoe City');
$city_data[] = array('accid' => 'USCA1127', 'name' => 'Tahoe Vista');
$city_data[] = array('accid' => 'USCA1128', 'name' => 'Tahoma');
$city_data[] = array('accid' => 'USCA1129', 'name' => 'Talmage');
$city_data[] = array('accid' => 'USCA1130', 'name' => 'Tarzana');
$city_data[] = array('accid' => 'USCA1131', 'name' => 'Taylorsville');
$city_data[] = array('accid' => 'USCA1132', 'name' => 'Tecate');
$city_data[] = array('accid' => 'USCA1133', 'name' => 'Tecopa');
$city_data[] = array('accid' => 'USCA1134', 'name' => 'Tehachapi');
$city_data[] = array('accid' => 'USCA1135', 'name' => 'Tehama');
$city_data[] = array('accid' => 'USCA1136', 'name' => 'Temecula');
$city_data[] = array('accid' => 'USCA1137', 'name' => 'Temple City');
$city_data[] = array('accid' => 'USCA1138', 'name' => 'Templeton');
$city_data[] = array('accid' => 'USCA1139', 'name' => 'Termo');
$city_data[] = array('accid' => 'USCA1140', 'name' => 'Terra Bella');
$city_data[] = array('accid' => 'USCA1141', 'name' => 'The Sea Ranch');
$city_data[] = array('accid' => 'USCA1142', 'name' => 'Thermal');
$city_data[] = array('accid' => 'USCA1143', 'name' => 'Thornton');
$city_data[] = array('accid' => 'USCA1144', 'name' => 'Thousand Oaks');
$city_data[] = array('accid' => 'USCA1145', 'name' => 'Thousand Palms');
$city_data[] = array('accid' => 'USCA1146', 'name' => 'Three Rivers');
$city_data[] = array('accid' => 'USCA1147', 'name' => 'Tipton');
$city_data[] = array('accid' => 'USCA1148', 'name' => 'Tollhouse');
$city_data[] = array('accid' => 'USCA1149', 'name' => 'Toluca Lake');
$city_data[] = array('accid' => 'USCA1150', 'name' => 'Tomales');
$city_data[] = array('accid' => 'USCA1151', 'name' => 'Topanga');
$city_data[] = array('accid' => 'USCA1152', 'name' => 'Topaz');
$city_data[] = array('accid' => 'USCA1153', 'name' => 'Torrance');
$city_data[] = array('accid' => 'USCA1154', 'name' => 'Trabuco Canyon');
$city_data[] = array('accid' => 'USCA1155', 'name' => 'Tracy');
$city_data[] = array('accid' => 'USCA1156', 'name' => 'Tranquillity');
$city_data[] = array('accid' => 'USCA1157', 'name' => 'Traver');
$city_data[] = array('accid' => 'USCA1158', 'name' => 'Travis AFB');
$city_data[] = array('accid' => 'USCA1159', 'name' => 'Tres Pinos');
$city_data[] = array('accid' => 'USCA1160', 'name' => 'Trinidad');
$city_data[] = array('accid' => 'USCA1161', 'name' => 'Trinity Center');
$city_data[] = array('accid' => 'USCA1162', 'name' => 'Trona');
$city_data[] = array('accid' => 'USCA1163', 'name' => 'Truckee');
$city_data[] = array('accid' => 'USCA1164', 'name' => 'Tujunga');
$city_data[] = array('accid' => 'USCA1165', 'name' => 'Tulare');
$city_data[] = array('accid' => 'USCA1166', 'name' => 'Tulelake');
$city_data[] = array('accid' => 'USCA1167', 'name' => 'Tuolumne');
$city_data[] = array('accid' => 'USCA1168', 'name' => 'Tupman');
$city_data[] = array('accid' => 'USCA1169', 'name' => 'Turlock');
$city_data[] = array('accid' => 'USCA1170', 'name' => 'Tustin');
$city_data[] = array('accid' => 'USCA1171', 'name' => 'Twain');
$city_data[] = array('accid' => 'USCA1172', 'name' => 'Twain Harte');
$city_data[] = array('accid' => 'USCA1173', 'name' => 'Twentynine Palms');
$city_data[] = array('accid' => 'USCA1174', 'name' => 'Twin Bridges');
$city_data[] = array('accid' => 'USCA1175', 'name' => 'Twin Peaks');
$city_data[] = array('accid' => 'USCA1176', 'name' => 'Ukiah');
$city_data[] = array('accid' => 'USCA1177', 'name' => 'Union City');
$city_data[] = array('accid' => 'USCA1178', 'name' => 'Universal City');
$city_data[] = array('accid' => 'USCA1179', 'name' => 'Upland');
$city_data[] = array('accid' => 'USCA1180', 'name' => 'Upper Lake');
$city_data[] = array('accid' => 'USCA1181', 'name' => 'Vacaville');
$city_data[] = array('accid' => 'USCA1182', 'name' => 'Valencia');
$city_data[] = array('accid' => 'USCA1183', 'name' => 'Vallecito');
$city_data[] = array('accid' => 'USCA1184', 'name' => 'Vallejo');
$city_data[] = array('accid' => 'USCA1185', 'name' => 'Valley Center');
$city_data[] = array('accid' => 'USCA1186', 'name' => 'Valley Ford');
$city_data[] = array('accid' => 'USCA1187', 'name' => 'Valley Springs');
$city_data[] = array('accid' => 'USCA1188', 'name' => 'Valley Village');
$city_data[] = array('accid' => 'USCA1189', 'name' => 'Valyermo');
$city_data[] = array('accid' => 'USCA1190', 'name' => 'Van Nuys');
$city_data[] = array('accid' => 'USCA1192', 'name' => 'Venice');
$city_data[] = array('accid' => 'USCA1193', 'name' => 'Ventura');
$city_data[] = array('accid' => 'USCA1194', 'name' => 'Verdugo City');
$city_data[] = array('accid' => 'USCA1195', 'name' => 'Vernalis');
$city_data[] = array('accid' => 'USCA1196', 'name' => 'Victor');
$city_data[] = array('accid' => 'USCA1197', 'name' => 'Victorville');
$city_data[] = array('accid' => 'USCA1198', 'name' => 'Vidal');
$city_data[] = array('accid' => 'USCA1199', 'name' => 'Villa Grande');
$city_data[] = array('accid' => 'USCA1200', 'name' => 'Villa Park');
$city_data[] = array('accid' => 'USCA1201', 'name' => 'Vina');
$city_data[] = array('accid' => 'USCA1202', 'name' => 'Vineburg');
$city_data[] = array('accid' => 'USCA1203', 'name' => 'Vinton');
$city_data[] = array('accid' => 'USCA1204', 'name' => 'Visalia');
$city_data[] = array('accid' => 'USCA1205', 'name' => 'Vista');
$city_data[] = array('accid' => 'USCA1206', 'name' => 'Volcano');
$city_data[] = array('accid' => 'USCA1207', 'name' => 'Wallace');
$city_data[] = array('accid' => 'USCA1208', 'name' => 'Walnut');
$city_data[] = array('accid' => 'USCA1209', 'name' => 'Walnut Creek');
$city_data[] = array('accid' => 'USCA1210', 'name' => 'Walnut Grove');
$city_data[] = array('accid' => 'USCA1211', 'name' => 'Warner Springs');
$city_data[] = array('accid' => 'USCA1212', 'name' => 'Wasco');
$city_data[] = array('accid' => 'USCA1213', 'name' => 'Washington');
$city_data[] = array('accid' => 'USCA1214', 'name' => 'Waterford');
$city_data[] = array('accid' => 'USCA1215', 'name' => 'Watsonville');
$city_data[] = array('accid' => 'USCA1216', 'name' => 'Waukena');
$city_data[] = array('accid' => 'USCA1217', 'name' => 'Weaverville');
$city_data[] = array('accid' => 'USCA1218', 'name' => 'Weed');
$city_data[] = array('accid' => 'USCA1219', 'name' => 'Weimar');
$city_data[] = array('accid' => 'USCA1220', 'name' => 'Weldon');
$city_data[] = array('accid' => 'USCA1221', 'name' => 'Wendel');
$city_data[] = array('accid' => 'USCA1222', 'name' => 'Weott');
$city_data[] = array('accid' => 'USCA1223', 'name' => 'West Covina');
$city_data[] = array('accid' => 'USCA1224', 'name' => 'West Hills');
$city_data[] = array('accid' => 'USCA1225', 'name' => 'West Hollywood');
$city_data[] = array('accid' => 'USCA1226', 'name' => 'West Point');
$city_data[] = array('accid' => 'USCA1227', 'name' => 'West Sacramento');
$city_data[] = array('accid' => 'USCA1228', 'name' => 'Westlake Village');
$city_data[] = array('accid' => 'USCA1229', 'name' => 'Westley');
$city_data[] = array('accid' => 'USCA1230', 'name' => 'Westminster');
$city_data[] = array('accid' => 'USCA1231', 'name' => 'Westmorland');
$city_data[] = array('accid' => 'USCA1232', 'name' => 'Westport');
$city_data[] = array('accid' => 'USCA1233', 'name' => 'Westwood');
$city_data[] = array('accid' => 'USCA1234', 'name' => 'Wheatland');
$city_data[] = array('accid' => 'USCA1235', 'name' => 'Whiskeytown');
$city_data[] = array('accid' => 'USCA1236', 'name' => 'White Water');
$city_data[] = array('accid' => 'USCA1237', 'name' => 'Whitethorn');
$city_data[] = array('accid' => 'USCA1238', 'name' => 'Whitmore');
$city_data[] = array('accid' => 'USCA1239', 'name' => 'Whittier');
$city_data[] = array('accid' => 'USCA1240', 'name' => 'Wildomar');
$city_data[] = array('accid' => 'USCA1241', 'name' => 'Williams');
$city_data[] = array('accid' => 'USCA1242', 'name' => 'Willits');
$city_data[] = array('accid' => 'USCA1243', 'name' => 'Willow Creek');
$city_data[] = array('accid' => 'USCA1244', 'name' => 'Willows');
$city_data[] = array('accid' => 'USCA1245', 'name' => 'Wilmington');
$city_data[] = array('accid' => 'USCA1246', 'name' => 'Wilseyville');
$city_data[] = array('accid' => 'USCA1247', 'name' => 'Wilton');
$city_data[] = array('accid' => 'USCA1248', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USCA1249', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USCA1250', 'name' => 'Winnetka');
$city_data[] = array('accid' => 'USCA1251', 'name' => 'Winterhaven');
$city_data[] = array('accid' => 'USCA1252', 'name' => 'Winters');
$city_data[] = array('accid' => 'USCA1253', 'name' => 'Winton');
$city_data[] = array('accid' => 'USCA1254', 'name' => 'Wishon');
$city_data[] = array('accid' => 'USCA1255', 'name' => 'Witter Springs');
$city_data[] = array('accid' => 'USCA1256', 'name' => 'Wofford Heights');
$city_data[] = array('accid' => 'USCA1257', 'name' => 'Woodacre');
$city_data[] = array('accid' => 'USCA1258', 'name' => 'Woodbridge');
$city_data[] = array('accid' => 'USCA1259', 'name' => 'Woodlake');
$city_data[] = array('accid' => 'USCA1260', 'name' => 'Woodland');
$city_data[] = array('accid' => 'USCA1261', 'name' => 'Woodland Hills');
$city_data[] = array('accid' => 'USCA1262', 'name' => 'Woody');
$city_data[] = array('accid' => 'USCA1263', 'name' => 'Wrightwood');
$city_data[] = array('accid' => 'USCA1264', 'name' => 'Yermo');
$city_data[] = array('accid' => 'USCA1265', 'name' => 'Yettem');
$city_data[] = array('accid' => 'USCA1266', 'name' => 'Yolo');
$city_data[] = array('accid' => 'USCA1267', 'name' => 'Yorba Linda');
$city_data[] = array('accid' => 'USCA1268', 'name' => 'Yorkville');
$city_data[] = array('accid' => 'USCA1269', 'name' => 'Yosemite Natl Park');
$city_data[] = array('accid' => 'USCA1270', 'name' => 'Yountville');
$city_data[] = array('accid' => 'USCA1271', 'name' => 'Yreka');
$city_data[] = array('accid' => 'USCA1272', 'name' => 'Yuba City');
$city_data[] = array('accid' => 'USCA1273', 'name' => 'Yucaipa');
$city_data[] = array('accid' => 'USCA1274', 'name' => 'Yucca Valley');
$city_data[] = array('accid' => 'USCA1275', 'name' => 'Zamora');
$city_data[] = array('accid' => 'USCA1276', 'name' => 'Zenia');

?>