<?php

// City package for USA: Colorado 

$city_name = 'USA: Colorado';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USCO0001', 'name' => 'Agate');
$city_data[] = array('accid' => 'USCO0002', 'name' => 'Aguilar');
$city_data[] = array('accid' => 'USCO0003', 'name' => 'Akron');
$city_data[] = array('accid' => 'USCO0004', 'name' => 'Alamosa');
$city_data[] = array('accid' => 'USCO0005', 'name' => 'Allenspark');
$city_data[] = array('accid' => 'USCO0006', 'name' => 'Alma');
$city_data[] = array('accid' => 'USCO0007', 'name' => 'Almont');
$city_data[] = array('accid' => 'USCO0008', 'name' => 'Amherst');
$city_data[] = array('accid' => 'USCO0009', 'name' => 'Anton');
$city_data[] = array('accid' => 'USCO0010', 'name' => 'Antonito');
$city_data[] = array('accid' => 'USCO0011', 'name' => 'Arapahoe');
$city_data[] = array('accid' => 'USCO0012', 'name' => 'Arboles');
$city_data[] = array('accid' => 'USCO0013', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USCO0014', 'name' => 'Arriba');
$city_data[] = array('accid' => 'USCO0015', 'name' => 'Arvada');
$city_data[] = array('accid' => 'USCO0016', 'name' => 'Aspen');
$city_data[] = array('accid' => 'USCO0017', 'name' => 'Atwood');
$city_data[] = array('accid' => 'USCO0018', 'name' => 'Ault');
$city_data[] = array('accid' => 'USCO0019', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USCO0020', 'name' => 'Austin');
$city_data[] = array('accid' => 'USCO0021', 'name' => 'Avon');
$city_data[] = array('accid' => 'USCO0022', 'name' => 'Avondale');
$city_data[] = array('accid' => 'USCO0023', 'name' => 'Bailey');
$city_data[] = array('accid' => 'USCO0024', 'name' => 'Basalt');
$city_data[] = array('accid' => 'USCO0025', 'name' => 'Battlement Mesa');
$city_data[] = array('accid' => 'USCO0026', 'name' => 'Bayfield');
$city_data[] = array('accid' => 'USCO0027', 'name' => 'Bedrock');
$city_data[] = array('accid' => 'USCO0028', 'name' => 'Bellvue');
$city_data[] = array('accid' => 'USCO0029', 'name' => 'Bennett');
$city_data[] = array('accid' => 'USCO0030', 'name' => 'Berthoud');
$city_data[] = array('accid' => 'USCO0031', 'name' => 'Bethune');
$city_data[] = array('accid' => 'USCO0032', 'name' => 'Beulah');
$city_data[] = array('accid' => 'USCO0033', 'name' => 'Black Hawk');
$city_data[] = array('accid' => 'USCO0034', 'name' => 'Blanca');
$city_data[] = array('accid' => 'USCO0035', 'name' => 'Boncarbo');
$city_data[] = array('accid' => 'USCO0036', 'name' => 'Bond');
$city_data[] = array('accid' => 'USCO0037', 'name' => 'Boone');
$city_data[] = array('accid' => 'USCO0038', 'name' => 'Boulder');
$city_data[] = array('accid' => 'USCO0039', 'name' => 'Branson');
$city_data[] = array('accid' => 'USCO0040', 'name' => 'Breckenridge');
$city_data[] = array('accid' => 'USCO0042', 'name' => 'Briggsdale');
$city_data[] = array('accid' => 'USCO0043', 'name' => 'Brighton');
$city_data[] = array('accid' => 'USCO0044', 'name' => 'Broomfield');
$city_data[] = array('accid' => 'USCO0045', 'name' => 'Brush');
$city_data[] = array('accid' => 'USCO0046', 'name' => 'Buena Vista');
$city_data[] = array('accid' => 'USCO0047', 'name' => 'Buffalo Creek');
$city_data[] = array('accid' => 'USCO0048', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USCO0049', 'name' => 'Burns');
$city_data[] = array('accid' => 'USCO0050', 'name' => 'Byers');
$city_data[] = array('accid' => 'USCO0051', 'name' => 'Cahone');
$city_data[] = array('accid' => 'USCO0052', 'name' => 'Calhan');
$city_data[] = array('accid' => 'USCO0053', 'name' => 'Campo');
$city_data[] = array('accid' => 'USCO0054', 'name' => 'Canon City');
$city_data[] = array('accid' => 'USCO0055', 'name' => 'Capulin');
$city_data[] = array('accid' => 'USCO0056', 'name' => 'Carbondale');
$city_data[] = array('accid' => 'USCO0057', 'name' => 'Carr');
$city_data[] = array('accid' => 'USCO0058', 'name' => 'Cascade');
$city_data[] = array('accid' => 'USCO0059', 'name' => 'Castle Rock');
$city_data[] = array('accid' => 'USCO0060', 'name' => 'Cedaredge');
$city_data[] = array('accid' => 'USCO0061', 'name' => 'Center');
$city_data[] = array('accid' => 'USCO0062', 'name' => 'Central City');
$city_data[] = array('accid' => 'USCO0063', 'name' => 'Chama');
$city_data[] = array('accid' => 'USCO0064', 'name' => 'Cheraw');
$city_data[] = array('accid' => 'USCO0066', 'name' => 'Cheyenne Wells');
$city_data[] = array('accid' => 'USCO0067', 'name' => 'Chimney Rock');
$city_data[] = array('accid' => 'USCO0068', 'name' => 'Chromo');
$city_data[] = array('accid' => 'USCO0069', 'name' => 'Cimarron');
$city_data[] = array('accid' => 'USCO0070', 'name' => 'Clark');
$city_data[] = array('accid' => 'USCO0071', 'name' => 'Clifton');
$city_data[] = array('accid' => 'USCO0072', 'name' => 'Climax');
$city_data[] = array('accid' => 'USCO0073', 'name' => 'Coal Creek');
$city_data[] = array('accid' => 'USCO0074', 'name' => 'Coaldale');
$city_data[] = array('accid' => 'USCO0075', 'name' => 'Coalmont');
$city_data[] = array('accid' => 'USCO0076', 'name' => 'Collbran');
$city_data[] = array('accid' => 'USCO0077', 'name' => 'Colorado City');
$city_data[] = array('accid' => 'USCO0078', 'name' => 'Colorado Springs');
$city_data[] = array('accid' => 'USCO0080', 'name' => 'Commerce City');
$city_data[] = array('accid' => 'USCO0081', 'name' => 'Como');
$city_data[] = array('accid' => 'USCO0082', 'name' => 'Conejos');
$city_data[] = array('accid' => 'USCO0083', 'name' => 'Conifer');
$city_data[] = array('accid' => 'USCO0084', 'name' => 'Cope');
$city_data[] = array('accid' => 'USCO0086', 'name' => 'Cortez');
$city_data[] = array('accid' => 'USCO0087', 'name' => 'Cory');
$city_data[] = array('accid' => 'USCO0088', 'name' => 'Cotopaxi');
$city_data[] = array('accid' => 'USCO0089', 'name' => 'Cowdrey');
$city_data[] = array('accid' => 'USCO0090', 'name' => 'Craig');
$city_data[] = array('accid' => 'USCO0091', 'name' => 'Crawford');
$city_data[] = array('accid' => 'USCO0092', 'name' => 'Creede');
$city_data[] = array('accid' => 'USCO0093', 'name' => 'Crested Butte');
$city_data[] = array('accid' => 'USCO0095', 'name' => 'Crestone');
$city_data[] = array('accid' => 'USCO0096', 'name' => 'Cripple Creek');
$city_data[] = array('accid' => 'USCO0097', 'name' => 'Crook');
$city_data[] = array('accid' => 'USCO0098', 'name' => 'Crowley');
$city_data[] = array('accid' => 'USCO0100', 'name' => 'Dacono');
$city_data[] = array('accid' => 'USCO0101', 'name' => 'De Beque');
$city_data[] = array('accid' => 'USCO0102', 'name' => 'Deer Trail');
$city_data[] = array('accid' => 'USCO0103', 'name' => 'Del Norte');
$city_data[] = array('accid' => 'USCO0104', 'name' => 'Delta');
$city_data[] = array('accid' => 'USCO0105', 'name' => 'Denver');
$city_data[] = array('accid' => 'USCO0106', 'name' => 'Dillon');
$city_data[] = array('accid' => 'USCO0107', 'name' => 'Dinosaur');
$city_data[] = array('accid' => 'USCO0108', 'name' => 'Divide');
$city_data[] = array('accid' => 'USCO0109', 'name' => 'Dolores');
$city_data[] = array('accid' => 'USCO0110', 'name' => 'Dove Creek');
$city_data[] = array('accid' => 'USCO0111', 'name' => 'Drake');
$city_data[] = array('accid' => 'USCO0112', 'name' => 'Dumont');
$city_data[] = array('accid' => 'USCO0113', 'name' => 'Dupont');
$city_data[] = array('accid' => 'USCO0114', 'name' => 'Durango');
$city_data[] = array('accid' => 'USCO0115', 'name' => 'Eads');
$city_data[] = array('accid' => 'USCO0116', 'name' => 'Eagle');
$city_data[] = array('accid' => 'USCO0117', 'name' => 'Eastlake');
$city_data[] = array('accid' => 'USCO0118', 'name' => 'Eaton');
$city_data[] = array('accid' => 'USCO0119', 'name' => 'Eckert');
$city_data[] = array('accid' => 'USCO0120', 'name' => 'Eckley');
$city_data[] = array('accid' => 'USCO0121', 'name' => 'Edwards');
$city_data[] = array('accid' => 'USCO0122', 'name' => 'Egnar');
$city_data[] = array('accid' => 'USCO0123', 'name' => 'El Jebel');
$city_data[] = array('accid' => 'USCO0124', 'name' => 'Elbert');
$city_data[] = array('accid' => 'USCO0125', 'name' => 'Eldorado Springs');
$city_data[] = array('accid' => 'USCO0126', 'name' => 'Elizabeth');
$city_data[] = array('accid' => 'USCO0127', 'name' => 'Empire');
$city_data[] = array('accid' => 'USCO0128', 'name' => 'Englewood');
$city_data[] = array('accid' => 'USCO0129', 'name' => 'Erie');
$city_data[] = array('accid' => 'USCO0130', 'name' => 'Estes Park');
$city_data[] = array('accid' => 'USCO0131', 'name' => 'Evans');
$city_data[] = array('accid' => 'USCO0132', 'name' => 'Evergreen');
$city_data[] = array('accid' => 'USCO0133', 'name' => 'Fairplay');
$city_data[] = array('accid' => 'USCO0134', 'name' => 'Firestone');
$city_data[] = array('accid' => 'USCO0135', 'name' => 'Flagler');
$city_data[] = array('accid' => 'USCO0136', 'name' => 'Fleming');
$city_data[] = array('accid' => 'USCO0137', 'name' => 'Florence');
$city_data[] = array('accid' => 'USCO0138', 'name' => 'Florissant');
$city_data[] = array('accid' => 'USCO0140', 'name' => 'Fort Collins');
$city_data[] = array('accid' => 'USCO0141', 'name' => 'Fort Garland');
$city_data[] = array('accid' => 'USCO0142', 'name' => 'Fort Lupton');
$city_data[] = array('accid' => 'USCO0143', 'name' => 'Fort Lyon');
$city_data[] = array('accid' => 'USCO0144', 'name' => 'Fort Morgan');
$city_data[] = array('accid' => 'USCO0145', 'name' => 'Fountain');
$city_data[] = array('accid' => 'USCO0146', 'name' => 'Fowler');
$city_data[] = array('accid' => 'USCO0147', 'name' => 'Franktown');
$city_data[] = array('accid' => 'USCO0148', 'name' => 'Fraser');
$city_data[] = array('accid' => 'USCO0149', 'name' => 'Frederick');
$city_data[] = array('accid' => 'USCO0150', 'name' => 'Frisco');
$city_data[] = array('accid' => 'USCO0151', 'name' => 'Fruita');
$city_data[] = array('accid' => 'USCO0152', 'name' => 'Galeton');
$city_data[] = array('accid' => 'USCO0153', 'name' => 'Garcia');
$city_data[] = array('accid' => 'USCO0154', 'name' => 'Gardner');
$city_data[] = array('accid' => 'USCO0155', 'name' => 'Gateway');
$city_data[] = array('accid' => 'USCO0156', 'name' => 'Genoa');
$city_data[] = array('accid' => 'USCO0157', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USCO0158', 'name' => 'Gilcrest');
$city_data[] = array('accid' => 'USCO0159', 'name' => 'Gill');
$city_data[] = array('accid' => 'USCO0160', 'name' => 'Glade Park');
$city_data[] = array('accid' => 'USCO0161', 'name' => 'Glen Haven');
$city_data[] = array('accid' => 'USCO0162', 'name' => 'Glenwood Springs');
$city_data[] = array('accid' => 'USCO0163', 'name' => 'Golden');
$city_data[] = array('accid' => 'USCO0164', 'name' => 'Granada');
$city_data[] = array('accid' => 'USCO0165', 'name' => 'Granby');
$city_data[] = array('accid' => 'USCO0166', 'name' => 'Grand Junction');
$city_data[] = array('accid' => 'USCO0167', 'name' => 'Grand Lake');
$city_data[] = array('accid' => 'USCO0168', 'name' => 'Granite');
$city_data[] = array('accid' => 'USCO0169', 'name' => 'Grant');
$city_data[] = array('accid' => 'USCO0170', 'name' => 'Greeley');
$city_data[] = array('accid' => 'USCO0171', 'name' => 'Green Mountain Falls');
$city_data[] = array('accid' => 'USCO0172', 'name' => 'Grover');
$city_data[] = array('accid' => 'USCO0173', 'name' => 'Guffey');
$city_data[] = array('accid' => 'USCO0174', 'name' => 'Gulnare');
$city_data[] = array('accid' => 'USCO0175', 'name' => 'Gunnison');
$city_data[] = array('accid' => 'USCO0176', 'name' => 'Gypsum');
$city_data[] = array('accid' => 'USCO0177', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USCO0178', 'name' => 'Hartman');
$city_data[] = array('accid' => 'USCO0179', 'name' => 'Hartsel');
$city_data[] = array('accid' => 'USCO0180', 'name' => 'Hasty');
$city_data[] = array('accid' => 'USCO0181', 'name' => 'Haswell');
$city_data[] = array('accid' => 'USCO0182', 'name' => 'Haxtun');
$city_data[] = array('accid' => 'USCO0183', 'name' => 'Hayden');
$city_data[] = array('accid' => 'USCO0184', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USCO0185', 'name' => 'Hereford');
$city_data[] = array('accid' => 'USCO0186', 'name' => 'Hesperus');
$city_data[] = array('accid' => 'USCO0187', 'name' => 'Hillrose');
$city_data[] = array('accid' => 'USCO0188', 'name' => 'Hillside');
$city_data[] = array('accid' => 'USCO0189', 'name' => 'Hoehne');
$city_data[] = array('accid' => 'USCO0190', 'name' => 'Holly');
$city_data[] = array('accid' => 'USCO0191', 'name' => 'Holyoke');
$city_data[] = array('accid' => 'USCO0192', 'name' => 'Homelake');
$city_data[] = array('accid' => 'USCO0193', 'name' => 'Hooper');
$city_data[] = array('accid' => 'USCO0194', 'name' => 'Hot Sulphur Springs');
$city_data[] = array('accid' => 'USCO0195', 'name' => 'Hotchkiss');
$city_data[] = array('accid' => 'USCO0196', 'name' => 'Howard');
$city_data[] = array('accid' => 'USCO0197', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USCO0198', 'name' => 'Hugo');
$city_data[] = array('accid' => 'USCO0199', 'name' => 'Hygiene');
$city_data[] = array('accid' => 'USCO0200', 'name' => 'Idaho Springs');
$city_data[] = array('accid' => 'USCO0201', 'name' => 'Idalia');
$city_data[] = array('accid' => 'USCO0202', 'name' => 'Idledale');
$city_data[] = array('accid' => 'USCO0203', 'name' => 'Ignacio');
$city_data[] = array('accid' => 'USCO0204', 'name' => 'Iliff');
$city_data[] = array('accid' => 'USCO0205', 'name' => 'Indian Hills');
$city_data[] = array('accid' => 'USCO0206', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USCO0207', 'name' => 'Jaroso');
$city_data[] = array('accid' => 'USCO0208', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USCO0209', 'name' => 'Joes');
$city_data[] = array('accid' => 'USCO0210', 'name' => 'Johnstown');
$city_data[] = array('accid' => 'USCO0211', 'name' => 'Julesburg');
$city_data[] = array('accid' => 'USCO0212', 'name' => 'Karval');
$city_data[] = array('accid' => 'USCO0213', 'name' => 'Keenesburg');
$city_data[] = array('accid' => 'USCO0214', 'name' => 'Kersey');
$city_data[] = array('accid' => 'USCO0216', 'name' => 'Kim');
$city_data[] = array('accid' => 'USCO0217', 'name' => 'Kiowa');
$city_data[] = array('accid' => 'USCO0218', 'name' => 'Kirk');
$city_data[] = array('accid' => 'USCO0219', 'name' => 'Kit Carson');
$city_data[] = array('accid' => 'USCO0220', 'name' => 'Kittredge');
$city_data[] = array('accid' => 'USCO0221', 'name' => 'Kremmling');
$city_data[] = array('accid' => 'USCO0222', 'name' => 'La Jara');
$city_data[] = array('accid' => 'USCO0223', 'name' => 'La Junta');
$city_data[] = array('accid' => 'USCO0224', 'name' => 'La Salle');
$city_data[] = array('accid' => 'USCO0225', 'name' => 'La Veta');
$city_data[] = array('accid' => 'USCO0226', 'name' => 'Lafayette');
$city_data[] = array('accid' => 'USCO0227', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USCO0228', 'name' => 'Lake George');
$city_data[] = array('accid' => 'USCO0230', 'name' => 'Lamar');
$city_data[] = array('accid' => 'USCO0231', 'name' => 'Laporte');
$city_data[] = array('accid' => 'USCO0232', 'name' => 'Larkspur');
$city_data[] = array('accid' => 'USCO0233', 'name' => 'Las Animas');
$city_data[] = array('accid' => 'USCO0234', 'name' => 'Lazear');
$city_data[] = array('accid' => 'USCO0235', 'name' => 'Leadville');
$city_data[] = array('accid' => 'USCO0236', 'name' => 'Lewis');
$city_data[] = array('accid' => 'USCO0237', 'name' => 'Limon');
$city_data[] = array('accid' => 'USCO0238', 'name' => 'Lindon');
$city_data[] = array('accid' => 'USCO0239', 'name' => 'Littleton');
$city_data[] = array('accid' => 'USCO0240', 'name' => 'Livermore');
$city_data[] = array('accid' => 'USCO0241', 'name' => 'Log Lane Village');
$city_data[] = array('accid' => 'USCO0242', 'name' => 'Loma');
$city_data[] = array('accid' => 'USCO0243', 'name' => 'Longmont');
$city_data[] = array('accid' => 'USCO0244', 'name' => 'Louisville');
$city_data[] = array('accid' => 'USCO0245', 'name' => 'Louviers');
$city_data[] = array('accid' => 'USCO0246', 'name' => 'Loveland');
$city_data[] = array('accid' => 'USCO0247', 'name' => 'Lucerne');
$city_data[] = array('accid' => 'USCO0248', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USCO0249', 'name' => 'Mack');
$city_data[] = array('accid' => 'USCO0250', 'name' => 'Maher');
$city_data[] = array('accid' => 'USCO0251', 'name' => 'Manassa');
$city_data[] = array('accid' => 'USCO0252', 'name' => 'Mancos');
$city_data[] = array('accid' => 'USCO0253', 'name' => 'Manitou Springs');
$city_data[] = array('accid' => 'USCO0254', 'name' => 'Manzanola');
$city_data[] = array('accid' => 'USCO0255', 'name' => 'Marvel');
$city_data[] = array('accid' => 'USCO0256', 'name' => 'Masonville');
$city_data[] = array('accid' => 'USCO0257', 'name' => 'Matheson');
$city_data[] = array('accid' => 'USCO0258', 'name' => 'Maybell');
$city_data[] = array('accid' => 'USCO0259', 'name' => 'McClave');
$city_data[] = array('accid' => 'USCO0260', 'name' => 'McCoy');
$city_data[] = array('accid' => 'USCO0261', 'name' => 'Mead');
$city_data[] = array('accid' => 'USCO0262', 'name' => 'Meeker');
$city_data[] = array('accid' => 'USCO0263', 'name' => 'Meredith');
$city_data[] = array('accid' => 'USCO0264', 'name' => 'Merino');
$city_data[] = array('accid' => 'USCO0265', 'name' => 'Mesa');
$city_data[] = array('accid' => 'USCO0266', 'name' => 'Mesa Verde Natl Park');
$city_data[] = array('accid' => 'USCO0267', 'name' => 'Milliken');
$city_data[] = array('accid' => 'USCO0268', 'name' => 'Minturn');
$city_data[] = array('accid' => 'USCO0269', 'name' => 'Model');
$city_data[] = array('accid' => 'USCO0270', 'name' => 'Moffat');
$city_data[] = array('accid' => 'USCO0271', 'name' => 'Molina');
$city_data[] = array('accid' => 'USCO0272', 'name' => 'Monarch');
$city_data[] = array('accid' => 'USCO0274', 'name' => 'Monte Vista');
$city_data[] = array('accid' => 'USCO0275', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USCO0276', 'name' => 'Monument');
$city_data[] = array('accid' => 'USCO0277', 'name' => 'Morrison');
$city_data[] = array('accid' => 'USCO0278', 'name' => 'Mosca');
$city_data[] = array('accid' => 'USCO0279', 'name' => 'Nathrop');
$city_data[] = array('accid' => 'USCO0280', 'name' => 'Naturita');
$city_data[] = array('accid' => 'USCO0281', 'name' => 'Nederland');
$city_data[] = array('accid' => 'USCO0282', 'name' => 'New Castle');
$city_data[] = array('accid' => 'USCO0283', 'name' => 'New Raymer');
$city_data[] = array('accid' => 'USCO0284', 'name' => 'Niwot');
$city_data[] = array('accid' => 'USCO0285', 'name' => 'Norwood');
$city_data[] = array('accid' => 'USCO0286', 'name' => 'Nucla');
$city_data[] = array('accid' => 'USCO0287', 'name' => 'Nunn');
$city_data[] = array('accid' => 'USCO0288', 'name' => 'Oak Creek');
$city_data[] = array('accid' => 'USCO0289', 'name' => 'Ohio City');
$city_data[] = array('accid' => 'USCO0290', 'name' => 'Olathe');
$city_data[] = array('accid' => 'USCO0291', 'name' => 'Olney Springs');
$city_data[] = array('accid' => 'USCO0292', 'name' => 'Ophir');
$city_data[] = array('accid' => 'USCO0293', 'name' => 'Orchard');
$city_data[] = array('accid' => 'USCO0294', 'name' => 'Ordway');
$city_data[] = array('accid' => 'USCO0295', 'name' => 'Otis');
$city_data[] = array('accid' => 'USCO0296', 'name' => 'Ouray');
$city_data[] = array('accid' => 'USCO0297', 'name' => 'Ovid');
$city_data[] = array('accid' => 'USCO0298', 'name' => 'Padroni');
$city_data[] = array('accid' => 'USCO0299', 'name' => 'Pagosa Springs');
$city_data[] = array('accid' => 'USCO0300', 'name' => 'Palisade');
$city_data[] = array('accid' => 'USCO0301', 'name' => 'Palmer Lake');
$city_data[] = array('accid' => 'USCO0302', 'name' => 'Paoli');
$city_data[] = array('accid' => 'USCO0303', 'name' => 'Paonia');
$city_data[] = array('accid' => 'USCO0304', 'name' => 'Parachute');
$city_data[] = array('accid' => 'USCO0305', 'name' => 'Paradox');
$city_data[] = array('accid' => 'USCO0306', 'name' => 'Parker');
$city_data[] = array('accid' => 'USCO0307', 'name' => 'Parlin');
$city_data[] = array('accid' => 'USCO0308', 'name' => 'Parshall');
$city_data[] = array('accid' => 'USCO0309', 'name' => 'Peetz');
$city_data[] = array('accid' => 'USCO0310', 'name' => 'Penrose');
$city_data[] = array('accid' => 'USCO0311', 'name' => 'Peyton');
$city_data[] = array('accid' => 'USCO0312', 'name' => 'Phippsburg');
$city_data[] = array('accid' => 'USCO0313', 'name' => 'Pierce');
$city_data[] = array('accid' => 'USCO0314', 'name' => 'Pine');
$city_data[] = array('accid' => 'USCO0315', 'name' => 'Pinecliffe');
$city_data[] = array('accid' => 'USCO0316', 'name' => 'Pitkin');
$city_data[] = array('accid' => 'USCO0317', 'name' => 'Placerville');
$city_data[] = array('accid' => 'USCO0318', 'name' => 'Platteville');
$city_data[] = array('accid' => 'USCO0319', 'name' => 'Pleasant View');
$city_data[] = array('accid' => 'USCO0320', 'name' => 'Poncha Springs');
$city_data[] = array('accid' => 'USCO0321', 'name' => 'Powderhorn');
$city_data[] = array('accid' => 'USCO0322', 'name' => 'Pritchett');
$city_data[] = array('accid' => 'USCO0323', 'name' => 'Pueblo');
$city_data[] = array('accid' => 'USCO0325', 'name' => 'Ramah');
$city_data[] = array('accid' => 'USCO0326', 'name' => 'Rand');
$city_data[] = array('accid' => 'USCO0327', 'name' => 'Rangely');
$city_data[] = array('accid' => 'USCO0328', 'name' => 'Red Cliff');
$city_data[] = array('accid' => 'USCO0329', 'name' => 'Red Feather Lakes');
$city_data[] = array('accid' => 'USCO0330', 'name' => 'Red Wing');
$city_data[] = array('accid' => 'USCO0331', 'name' => 'Redvale');
$city_data[] = array('accid' => 'USCO0332', 'name' => 'Rico');
$city_data[] = array('accid' => 'USCO0333', 'name' => 'Ridgway');
$city_data[] = array('accid' => 'USCO0334', 'name' => 'Rifle');
$city_data[] = array('accid' => 'USCO0335', 'name' => 'Rockvale');
$city_data[] = array('accid' => 'USCO0336', 'name' => 'Rocky Ford');
$city_data[] = array('accid' => 'USCO0338', 'name' => 'Roggen');
$city_data[] = array('accid' => 'USCO0339', 'name' => 'Rollinsville');
$city_data[] = array('accid' => 'USCO0340', 'name' => 'Romeo');
$city_data[] = array('accid' => 'USCO0341', 'name' => 'Rush');
$city_data[] = array('accid' => 'USCO0342', 'name' => 'Rye');
$city_data[] = array('accid' => 'USCO0343', 'name' => 'Saguache');
$city_data[] = array('accid' => 'USCO0344', 'name' => 'Salida');
$city_data[] = array('accid' => 'USCO0345', 'name' => 'San Luis');
$city_data[] = array('accid' => 'USCO0346', 'name' => 'San Pablo');
$city_data[] = array('accid' => 'USCO0347', 'name' => 'Sanford');
$city_data[] = array('accid' => 'USCO0348', 'name' => 'Sargents');
$city_data[] = array('accid' => 'USCO0424', 'name' => 'Sedalia');
$city_data[] = array('accid' => 'USCO0350', 'name' => 'Sedgwick');
$city_data[] = array('accid' => 'USCO0351', 'name' => 'Seibert');
$city_data[] = array('accid' => 'USCO0352', 'name' => 'Severance');
$city_data[] = array('accid' => 'USCO0353', 'name' => 'Shawnee');
$city_data[] = array('accid' => 'USCO0354', 'name' => 'Sheridan Lake');
$city_data[] = array('accid' => 'USCO0355', 'name' => 'Silt');
$city_data[] = array('accid' => 'USCO0356', 'name' => 'Silver Plume');
$city_data[] = array('accid' => 'USCO0357', 'name' => 'Silverthorne');
$city_data[] = array('accid' => 'USCO0358', 'name' => 'Silverton');
$city_data[] = array('accid' => 'USCO0359', 'name' => 'Simla');
$city_data[] = array('accid' => 'USCO0360', 'name' => 'Slater');
$city_data[] = array('accid' => 'USCO0361', 'name' => 'Snowmass');
$city_data[] = array('accid' => 'USCO0363', 'name' => 'Snowmass Village');
$city_data[] = array('accid' => 'USCO0364', 'name' => 'Snyder');
$city_data[] = array('accid' => 'USCO0365', 'name' => 'Somerset');
$city_data[] = array('accid' => 'USCO0366', 'name' => 'South Fork');
$city_data[] = array('accid' => 'USCO0367', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USCO0368', 'name' => 'Starkville');
$city_data[] = array('accid' => 'USCO0370', 'name' => 'Steamboat Springs');
$city_data[] = array('accid' => 'USCO0371', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USCO0372', 'name' => 'Stoneham');
$city_data[] = array('accid' => 'USCO0373', 'name' => 'Strasburg');
$city_data[] = array('accid' => 'USCO0374', 'name' => 'Stratton');
$city_data[] = array('accid' => 'USCO0375', 'name' => 'Sugar City');
$city_data[] = array('accid' => 'USCO0376', 'name' => 'Swink');
$city_data[] = array('accid' => 'USCO0377', 'name' => 'Tabernash');
$city_data[] = array('accid' => 'USCO0378', 'name' => 'Telluride');
$city_data[] = array('accid' => 'USCO0380', 'name' => 'Timnath');
$city_data[] = array('accid' => 'USCO0381', 'name' => 'Toponas');
$city_data[] = array('accid' => 'USCO0382', 'name' => 'Towaoc');
$city_data[] = array('accid' => 'USCO0383', 'name' => 'Trinchera');
$city_data[] = array('accid' => 'USCO0384', 'name' => 'Trinidad');
$city_data[] = array('accid' => 'USCO0385', 'name' => 'Twin Lakes');
$city_data[] = array('accid' => 'USCO0386', 'name' => 'Two Buttes');
$city_data[] = array('accid' => 'USCO0387', 'name' => 'USAF Academy');
$city_data[] = array('accid' => 'USCO0388', 'name' => 'Vail');
$city_data[] = array('accid' => 'USCO0390', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USCO0391', 'name' => 'Victor');
$city_data[] = array('accid' => 'USCO0392', 'name' => 'Vilas');
$city_data[] = array('accid' => 'USCO0393', 'name' => 'Villa Grove');
$city_data[] = array('accid' => 'USCO0394', 'name' => 'Vona');
$city_data[] = array('accid' => 'USCO0395', 'name' => 'Walden');
$city_data[] = array('accid' => 'USCO0396', 'name' => 'Walsenburg');
$city_data[] = array('accid' => 'USCO0397', 'name' => 'Walsh');
$city_data[] = array('accid' => 'USCO0398', 'name' => 'Ward');
$city_data[] = array('accid' => 'USCO0399', 'name' => 'Watkins');
$city_data[] = array('accid' => 'USCO0400', 'name' => 'Weldona');
$city_data[] = array('accid' => 'USCO0401', 'name' => 'Wellington');
$city_data[] = array('accid' => 'USCO0402', 'name' => 'Westcliffe');
$city_data[] = array('accid' => 'USCO0403', 'name' => 'Westminster');
$city_data[] = array('accid' => 'USCO0404', 'name' => 'Weston');
$city_data[] = array('accid' => 'USCO0405', 'name' => 'Wetmore');
$city_data[] = array('accid' => 'USCO0406', 'name' => 'Wheat Ridge');
$city_data[] = array('accid' => 'USCO0407', 'name' => 'Whitewater');
$city_data[] = array('accid' => 'USCO0408', 'name' => 'Wiggins');
$city_data[] = array('accid' => 'USCO0409', 'name' => 'Wild Horse');
$city_data[] = array('accid' => 'USCO0410', 'name' => 'Wiley');
$city_data[] = array('accid' => 'USCO0411', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USCO0412', 'name' => 'Winter Park');
$city_data[] = array('accid' => 'USCO0414', 'name' => 'Wolcott');
$city_data[] = array('accid' => 'USCO0416', 'name' => 'Woodland Park');
$city_data[] = array('accid' => 'USCO0417', 'name' => 'Woodrow');
$city_data[] = array('accid' => 'USCO0418', 'name' => 'Woody Creek');
$city_data[] = array('accid' => 'USCO0419', 'name' => 'Wray');
$city_data[] = array('accid' => 'USCO0420', 'name' => 'Yampa');
$city_data[] = array('accid' => 'USCO0421', 'name' => 'Yellow Jacket');
$city_data[] = array('accid' => 'USCO0422', 'name' => 'Yoder');
$city_data[] = array('accid' => 'USCO0423', 'name' => 'Yuma');

?>
