<?php

// City package for USA: Connecticut 

$city_name = 'USA: Connecticut';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USCT0001', 'name' => 'Abington');
$city_data[] = array('accid' => 'USCT0002', 'name' => 'Amston');
$city_data[] = array('accid' => 'USCT0003', 'name' => 'Andover');
$city_data[] = array('accid' => 'USCT0004', 'name' => 'Ansonia');
$city_data[] = array('accid' => 'USCT0005', 'name' => 'Ashford');
$city_data[] = array('accid' => 'USCT0006', 'name' => 'Avon');
$city_data[] = array('accid' => 'USCT0007', 'name' => 'Ballouville');
$city_data[] = array('accid' => 'USCT0008', 'name' => 'Baltic');
$city_data[] = array('accid' => 'USCT0009', 'name' => 'Bantam');
$city_data[] = array('accid' => 'USCT0010', 'name' => 'Beacon Falls');
$city_data[] = array('accid' => 'USCT0011', 'name' => 'Bethany');
$city_data[] = array('accid' => 'USCT0012', 'name' => 'Bethel');
$city_data[] = array('accid' => 'USCT0013', 'name' => 'Bethlehem');
$city_data[] = array('accid' => 'USCT0014', 'name' => 'Bloomfield');
$city_data[] = array('accid' => 'USCT0015', 'name' => 'Bolton');
$city_data[] = array('accid' => 'USCT0016', 'name' => 'Botsford');
$city_data[] = array('accid' => 'USCT0017', 'name' => 'Bozrah');
$city_data[] = array('accid' => 'USCT0018', 'name' => 'Branford');
$city_data[] = array('accid' => 'USCT0019', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USCT0020', 'name' => 'Bridgewater');
$city_data[] = array('accid' => 'USCT0021', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USCT0022', 'name' => 'Broad Brook');
$city_data[] = array('accid' => 'USCT0023', 'name' => 'Brookfield');
$city_data[] = array('accid' => 'USCT0024', 'name' => 'Brooklyn');
$city_data[] = array('accid' => 'USCT0025', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USCT0026', 'name' => 'Canaan');
$city_data[] = array('accid' => 'USCT0027', 'name' => 'Canterbury');
$city_data[] = array('accid' => 'USCT0028', 'name' => 'Canton');
$city_data[] = array('accid' => 'USCT0029', 'name' => 'Canton Center');
$city_data[] = array('accid' => 'USCT0030', 'name' => 'Centerbrook');
$city_data[] = array('accid' => 'USCT0031', 'name' => 'Central Village');
$city_data[] = array('accid' => 'USCT0032', 'name' => 'Chaplin');
$city_data[] = array('accid' => 'USCT0033', 'name' => 'Cheshire');
$city_data[] = array('accid' => 'USCT0034', 'name' => 'Chester');
$city_data[] = array('accid' => 'USCT0035', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USCT0036', 'name' => 'Cobalt');
$city_data[] = array('accid' => 'USCT0037', 'name' => 'Colchester');
$city_data[] = array('accid' => 'USCT0038', 'name' => 'Colebrook');
$city_data[] = array('accid' => 'USCT0039', 'name' => 'Collinsville');
$city_data[] = array('accid' => 'USCT0040', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USCT0041', 'name' => 'Cornwall');
$city_data[] = array('accid' => 'USCT0042', 'name' => 'Cornwall Bridge');
$city_data[] = array('accid' => 'USCT0043', 'name' => 'Cos Cob');
$city_data[] = array('accid' => 'USCT0044', 'name' => 'Coventry');
$city_data[] = array('accid' => 'USCT0045', 'name' => 'Cromwell');
$city_data[] = array('accid' => 'USCT0046', 'name' => 'Danbury');
$city_data[] = array('accid' => 'USCT0047', 'name' => 'Danielson');
$city_data[] = array('accid' => 'USCT0048', 'name' => 'Darien');
$city_data[] = array('accid' => 'USCT0049', 'name' => 'Dayville');
$city_data[] = array('accid' => 'USCT0050', 'name' => 'Deep River');
$city_data[] = array('accid' => 'USCT0051', 'name' => 'Derby');
$city_data[] = array('accid' => 'USCT0052', 'name' => 'Durham');
$city_data[] = array('accid' => 'USCT0053', 'name' => 'East Berlin');
$city_data[] = array('accid' => 'USCT0054', 'name' => 'East Canaan');
$city_data[] = array('accid' => 'USCT0055', 'name' => 'East Glastonbury');
$city_data[] = array('accid' => 'USCT0056', 'name' => 'East Granby');
$city_data[] = array('accid' => 'USCT0057', 'name' => 'East Haddam');
$city_data[] = array('accid' => 'USCT0058', 'name' => 'East Hampton');
$city_data[] = array('accid' => 'USCT0059', 'name' => 'East Hartford');
$city_data[] = array('accid' => 'USCT0060', 'name' => 'East Hartland');
$city_data[] = array('accid' => 'USCT0061', 'name' => 'East Haven');
$city_data[] = array('accid' => 'USCT0062', 'name' => 'East Killingly');
$city_data[] = array('accid' => 'USCT0063', 'name' => 'East Lyme');
$city_data[] = array('accid' => 'USCT0064', 'name' => 'East Windsor');
$city_data[] = array('accid' => 'USCT0065', 'name' => 'East Windsor Hill');
$city_data[] = array('accid' => 'USCT0066', 'name' => 'East Woodstock');
$city_data[] = array('accid' => 'USCT0067', 'name' => 'Eastford');
$city_data[] = array('accid' => 'USCT0068', 'name' => 'Easton');
$city_data[] = array('accid' => 'USCT0069', 'name' => 'Ellington');
$city_data[] = array('accid' => 'USCT0070', 'name' => 'Enfield');
$city_data[] = array('accid' => 'USCT0071', 'name' => 'Essex');
$city_data[] = array('accid' => 'USCT0072', 'name' => 'Fabyan');
$city_data[] = array('accid' => 'USCT0073', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USCT0074', 'name' => 'Falls Village');
$city_data[] = array('accid' => 'USCT0075', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USCT0076', 'name' => 'Gales Ferry');
$city_data[] = array('accid' => 'USCT0077', 'name' => 'Gaylordsville');
$city_data[] = array('accid' => 'USCT0078', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USCT0079', 'name' => 'Gilman');
$city_data[] = array('accid' => 'USCT0080', 'name' => 'Glasgo');
$city_data[] = array('accid' => 'USCT0081', 'name' => 'Glastonbury');
$city_data[] = array('accid' => 'USCT0082', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USCT0083', 'name' => 'Granby');
$city_data[] = array('accid' => 'USCT0084', 'name' => 'Greens Farms');
$city_data[] = array('accid' => 'USCT0085', 'name' => 'Greenwich');
$city_data[] = array('accid' => 'USCT0086', 'name' => 'Grosvenor Dale');
$city_data[] = array('accid' => 'USCT0087', 'name' => 'Groton');
$city_data[] = array('accid' => 'USCT0088', 'name' => 'Guilford');
$city_data[] = array('accid' => 'USCT0089', 'name' => 'Haddam');
$city_data[] = array('accid' => 'USCT0090', 'name' => 'Hadlyme');
$city_data[] = array('accid' => 'USCT0091', 'name' => 'Hamden');
$city_data[] = array('accid' => 'USCT0092', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USCT0093', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USCT0094', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USCT0095', 'name' => 'Harwinton');
$city_data[] = array('accid' => 'USCT0096', 'name' => 'Hawleyville');
$city_data[] = array('accid' => 'USCT0097', 'name' => 'Hebron');
$city_data[] = array('accid' => 'USCT0098', 'name' => 'Higganum');
$city_data[] = array('accid' => 'USCT0099', 'name' => 'Ivoryton');
$city_data[] = array('accid' => 'USCT0100', 'name' => 'Jewett City');
$city_data[] = array('accid' => 'USCT0101', 'name' => 'Kensington');
$city_data[] = array('accid' => 'USCT0102', 'name' => 'Kent');
$city_data[] = array('accid' => 'USCT0103', 'name' => 'Killingworth');
$city_data[] = array('accid' => 'USCT0104', 'name' => 'Lakeside');
$city_data[] = array('accid' => 'USCT0105', 'name' => 'Lakeville');
$city_data[] = array('accid' => 'USCT0106', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USCT0107', 'name' => 'Ledyard');
$city_data[] = array('accid' => 'USCT0108', 'name' => 'Litchfield');
$city_data[] = array('accid' => 'USCT0109', 'name' => 'Madison');
$city_data[] = array('accid' => 'USCT0110', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USCT0111', 'name' => 'Mansfield Center');
$city_data[] = array('accid' => 'USCT0112', 'name' => 'Mansfield Depot');
$city_data[] = array('accid' => 'USCT0113', 'name' => 'Marion');
$city_data[] = array('accid' => 'USCT0114', 'name' => 'Marlborough');
$city_data[] = array('accid' => 'USCT0115', 'name' => 'Melrose');
$city_data[] = array('accid' => 'USCT0116', 'name' => 'Meriden');
$city_data[] = array('accid' => 'USCT0117', 'name' => 'Middle Haddam');
$city_data[] = array('accid' => 'USCT0118', 'name' => 'Middlebury');
$city_data[] = array('accid' => 'USCT0119', 'name' => 'Middlefield');
$city_data[] = array('accid' => 'USCT0120', 'name' => 'Middletown');
$city_data[] = array('accid' => 'USCT0121', 'name' => 'Milford');
$city_data[] = array('accid' => 'USCT0122', 'name' => 'Milldale');
$city_data[] = array('accid' => 'USCT0124', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USCT0125', 'name' => 'Montville');
$city_data[] = array('accid' => 'USCT0126', 'name' => 'Moodus');
$city_data[] = array('accid' => 'USCT0127', 'name' => 'Moosup');
$city_data[] = array('accid' => 'USCT0128', 'name' => 'Morris');
$city_data[] = array('accid' => 'USCT0129', 'name' => 'Mystic');
$city_data[] = array('accid' => 'USCT0130', 'name' => 'Naugatuck');
$city_data[] = array('accid' => 'USCT0131', 'name' => 'New Britain');
$city_data[] = array('accid' => 'USCT0132', 'name' => 'New Canaan');
$city_data[] = array('accid' => 'USCT0133', 'name' => 'New Fairfield');
$city_data[] = array('accid' => 'USCT0134', 'name' => 'New Hartford');
$city_data[] = array('accid' => 'USCT0135', 'name' => 'New Haven');
$city_data[] = array('accid' => 'USCT0136', 'name' => 'New London');
$city_data[] = array('accid' => 'USCT0137', 'name' => 'New Milford');
$city_data[] = array('accid' => 'USCT0138', 'name' => 'New Preston Marble Dale');
$city_data[] = array('accid' => 'USCT0139', 'name' => 'Newington');
$city_data[] = array('accid' => 'USCT0140', 'name' => 'Newtown');
$city_data[] = array('accid' => 'USCT0141', 'name' => 'Niantic');
$city_data[] = array('accid' => 'USCT0142', 'name' => 'Norfolk');
$city_data[] = array('accid' => 'USCT0143', 'name' => 'North Branford');
$city_data[] = array('accid' => 'USCT0144', 'name' => 'North Canton');
$city_data[] = array('accid' => 'USCT0145', 'name' => 'North Franklin');
$city_data[] = array('accid' => 'USCT0146', 'name' => 'North Granby');
$city_data[] = array('accid' => 'USCT0147', 'name' => 'North Grosvenordale');
$city_data[] = array('accid' => 'USCT0148', 'name' => 'North Haven');
$city_data[] = array('accid' => 'USCT0149', 'name' => 'North Stonington');
$city_data[] = array('accid' => 'USCT0150', 'name' => 'North Westchester');
$city_data[] = array('accid' => 'USCT0151', 'name' => 'North Windham');
$city_data[] = array('accid' => 'USCT0152', 'name' => 'Northfield');
$city_data[] = array('accid' => 'USCT0153', 'name' => 'Northford');
$city_data[] = array('accid' => 'USCT0154', 'name' => 'Norwalk');
$city_data[] = array('accid' => 'USCT0155', 'name' => 'Norwich');
$city_data[] = array('accid' => 'USCT0156', 'name' => 'Oakdale');
$city_data[] = array('accid' => 'USCT0157', 'name' => 'Oakville');
$city_data[] = array('accid' => 'USCT0158', 'name' => 'Old Greenwich');
$city_data[] = array('accid' => 'USCT0159', 'name' => 'Old Lyme');
$city_data[] = array('accid' => 'USCT0160', 'name' => 'Old Mystic');
$city_data[] = array('accid' => 'USCT0161', 'name' => 'Old Saybrook');
$city_data[] = array('accid' => 'USCT0162', 'name' => 'Oneco');
$city_data[] = array('accid' => 'USCT0163', 'name' => 'Orange');
$city_data[] = array('accid' => 'USCT0164', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USCT0165', 'name' => 'Pawcatuck');
$city_data[] = array('accid' => 'USCT0166', 'name' => 'Pequabuck');
$city_data[] = array('accid' => 'USCT0167', 'name' => 'Pine Meadow');
$city_data[] = array('accid' => 'USCT0168', 'name' => 'Plainfield');
$city_data[] = array('accid' => 'USCT0169', 'name' => 'Plainville');
$city_data[] = array('accid' => 'USCT0170', 'name' => 'Plantsville');
$city_data[] = array('accid' => 'USCT0171', 'name' => 'Pleasant Valley');
$city_data[] = array('accid' => 'USCT0172', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USCT0173', 'name' => 'Pomfret');
$city_data[] = array('accid' => 'USCT0174', 'name' => 'Pomfret Center');
$city_data[] = array('accid' => 'USCT0175', 'name' => 'Poquonock');
$city_data[] = array('accid' => 'USCT0176', 'name' => 'Portland');
$city_data[] = array('accid' => 'USCT0178', 'name' => 'Preston');
$city_data[] = array('accid' => 'USCT0179', 'name' => 'Prospect');
$city_data[] = array('accid' => 'USCT0180', 'name' => 'Putnam');
$city_data[] = array('accid' => 'USCT0181', 'name' => 'Quaker Hill');
$city_data[] = array('accid' => 'USCT0182', 'name' => 'Quinebaug');
$city_data[] = array('accid' => 'USCT0253', 'name' => 'Redding');
$city_data[] = array('accid' => 'USCT0183', 'name' => 'Redding Center');
$city_data[] = array('accid' => 'USCT0184', 'name' => 'Redding Ridge');
$city_data[] = array('accid' => 'USCT0185', 'name' => 'Ridgefield');
$city_data[] = array('accid' => 'USCT0186', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USCT0187', 'name' => 'Riverton');
$city_data[] = array('accid' => 'USCT0188', 'name' => 'Rockfall');
$city_data[] = array('accid' => 'USCT0189', 'name' => 'Rocky Hill');
$city_data[] = array('accid' => 'USCT0190', 'name' => 'Rogers');
$city_data[] = array('accid' => 'USCT0191', 'name' => 'Roxbury');
$city_data[] = array('accid' => 'USCT0192', 'name' => 'Salem');
$city_data[] = array('accid' => 'USCT0193', 'name' => 'Salisbury');
$city_data[] = array('accid' => 'USCT0194', 'name' => 'Sandy Hook');
$city_data[] = array('accid' => 'USCT0195', 'name' => 'Scotland');
$city_data[] = array('accid' => 'USCT0196', 'name' => 'Seymour');
$city_data[] = array('accid' => 'USCT0197', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USCT0198', 'name' => 'Shelton');
$city_data[] = array('accid' => 'USCT0199', 'name' => 'Sherman');
$city_data[] = array('accid' => 'USCT0200', 'name' => 'Simsbury');
$city_data[] = array('accid' => 'USCT0202', 'name' => 'Somers');
$city_data[] = array('accid' => 'USCT0203', 'name' => 'Somersville');
$city_data[] = array('accid' => 'USCT0204', 'name' => 'South Britain');
$city_data[] = array('accid' => 'USCT0205', 'name' => 'South Glastonbury');
$city_data[] = array('accid' => 'USCT0206', 'name' => 'South Kent');
$city_data[] = array('accid' => 'USCT0207', 'name' => 'South Lyme');
$city_data[] = array('accid' => 'USCT0208', 'name' => 'South Willington');
$city_data[] = array('accid' => 'USCT0209', 'name' => 'South Windham');
$city_data[] = array('accid' => 'USCT0210', 'name' => 'South Windsor');
$city_data[] = array('accid' => 'USCT0211', 'name' => 'South Woodstock');
$city_data[] = array('accid' => 'USCT0212', 'name' => 'Southbury');
$city_data[] = array('accid' => 'USCT0213', 'name' => 'Southington');
$city_data[] = array('accid' => 'USCT0214', 'name' => 'Southport');
$city_data[] = array('accid' => 'USCT0215', 'name' => 'Stafford');
$city_data[] = array('accid' => 'USCT0216', 'name' => 'Stafford Springs');
$city_data[] = array('accid' => 'USCT0217', 'name' => 'Staffordville');
$city_data[] = array('accid' => 'USCT0218', 'name' => 'Stamford');
$city_data[] = array('accid' => 'USCT0219', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USCT0220', 'name' => 'Stevenson');
$city_data[] = array('accid' => 'USCT0221', 'name' => 'Stonington');
$city_data[] = array('accid' => 'USCT0222', 'name' => 'Storrs');
$city_data[] = array('accid' => 'USCT0223', 'name' => 'Stratford');
$city_data[] = array('accid' => 'USCT0224', 'name' => 'Suffield');
$city_data[] = array('accid' => 'USCT0225', 'name' => 'Taconic');
$city_data[] = array('accid' => 'USCT0226', 'name' => 'Taftville');
$city_data[] = array('accid' => 'USCT0227', 'name' => 'Tariffville');
$city_data[] = array('accid' => 'USCT0228', 'name' => 'Terryville');
$city_data[] = array('accid' => 'USCT0229', 'name' => 'Thomaston');
$city_data[] = array('accid' => 'USCT0230', 'name' => 'Thompson');
$city_data[] = array('accid' => 'USCT0231', 'name' => 'Tolland');
$city_data[] = array('accid' => 'USCT0232', 'name' => 'Torrington');
$city_data[] = array('accid' => 'USCT0233', 'name' => 'Trumbull');
$city_data[] = array('accid' => 'USCT0234', 'name' => 'Uncasville');
$city_data[] = array('accid' => 'USCT0235', 'name' => 'Unionville');
$city_data[] = array('accid' => 'USCT0236', 'name' => 'Vernon Rockville');
$city_data[] = array('accid' => 'USCT0237', 'name' => 'Versailles');
$city_data[] = array('accid' => 'USCT0238', 'name' => 'Voluntown');
$city_data[] = array('accid' => 'USCT0239', 'name' => 'Wallingford');
$city_data[] = array('accid' => 'USCT0240', 'name' => 'Washington');
$city_data[] = array('accid' => 'USCT0241', 'name' => 'Washington Depot');
$city_data[] = array('accid' => 'USCT0242', 'name' => 'Waterbury');
$city_data[] = array('accid' => 'USCT0243', 'name' => 'Waterford');
$city_data[] = array('accid' => 'USCT0244', 'name' => 'Watertown');
$city_data[] = array('accid' => 'USCT0245', 'name' => 'Wauregan');
$city_data[] = array('accid' => 'USCT0246', 'name' => 'Weatogue');
$city_data[] = array('accid' => 'USCT0247', 'name' => 'West Cornwall');
$city_data[] = array('accid' => 'USCT0248', 'name' => 'West Granby');
$city_data[] = array('accid' => 'USCT0249', 'name' => 'West Hartford');
$city_data[] = array('accid' => 'USCT0250', 'name' => 'West Hartland');
$city_data[] = array('accid' => 'USCT0251', 'name' => 'West Haven');
$city_data[] = array('accid' => 'USCT0252', 'name' => 'West Mystic');
$city_data[] = array('accid' => 'USCT0254', 'name' => 'West Simsbury');
$city_data[] = array('accid' => 'USCT0255', 'name' => 'West Suffield');
$city_data[] = array('accid' => 'USCT0256', 'name' => 'Westbrook');
$city_data[] = array('accid' => 'USCT0257', 'name' => 'Weston');
$city_data[] = array('accid' => 'USCT0258', 'name' => 'Westport');
$city_data[] = array('accid' => 'USCT0259', 'name' => 'Wethersfield');
$city_data[] = array('accid' => 'USCT0260', 'name' => 'Willimantic');
$city_data[] = array('accid' => 'USCT0261', 'name' => 'Willington');
$city_data[] = array('accid' => 'USCT0262', 'name' => 'Wilton');
$city_data[] = array('accid' => 'USCT0263', 'name' => 'Winchester Center');
$city_data[] = array('accid' => 'USCT0264', 'name' => 'Windham');
$city_data[] = array('accid' => 'USCT0265', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USCT0266', 'name' => 'Windsor Locks');
$city_data[] = array('accid' => 'USCT0267', 'name' => 'Winsted');
$city_data[] = array('accid' => 'USCT0268', 'name' => 'Wolcott');
$city_data[] = array('accid' => 'USCT0269', 'name' => 'Woodbridge');
$city_data[] = array('accid' => 'USCT0270', 'name' => 'Woodbury');
$city_data[] = array('accid' => 'USCT0272', 'name' => 'Woodstock');
$city_data[] = array('accid' => 'USCT0273', 'name' => 'Woodstock Valley');
$city_data[] = array('accid' => 'USCT0274', 'name' => 'Yantic');

?>
