<?php

// City package for USA: Florida

$city_name = 'USA: Florida';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USFL0001', 'name' => 'Alachua');
$city_data[] = array('accid' => 'USFL0002', 'name' => 'Alford');
$city_data[] = array('accid' => 'USFL0003', 'name' => 'Altamonte Springs');
$city_data[] = array('accid' => 'USFL0004', 'name' => 'Altha');
$city_data[] = array('accid' => 'USFL0005', 'name' => 'Altoona');
$city_data[] = array('accid' => 'USFL0006', 'name' => 'Alturas');
$city_data[] = array('accid' => 'USFL0007', 'name' => 'Alva');
$city_data[] = array('accid' => 'USFL0008', 'name' => 'Anna Maria');
$city_data[] = array('accid' => 'USFL0009', 'name' => 'Anthony');
$city_data[] = array('accid' => 'USFL0010', 'name' => 'Apalachicola');
$city_data[] = array('accid' => 'USFL0011', 'name' => 'Apollo Beach');
$city_data[] = array('accid' => 'USFL0012', 'name' => 'Apopka');
$city_data[] = array('accid' => 'USFL0013', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USFL0014', 'name' => 'Archer');
$city_data[] = array('accid' => 'USFL0015', 'name' => 'Argyle');
$city_data[] = array('accid' => 'USFL0016', 'name' => 'Aripeka');
$city_data[] = array('accid' => 'USFL0017', 'name' => 'Astatula');
$city_data[] = array('accid' => 'USFL0018', 'name' => 'Astor');
$city_data[] = array('accid' => 'USFL0019', 'name' => 'Atlantic Beach');
$city_data[] = array('accid' => 'USFL0020', 'name' => 'Auburndale');
$city_data[] = array('accid' => 'USFL0021', 'name' => 'Avon Park');
$city_data[] = array('accid' => 'USFL0022', 'name' => 'Babson Park');
$city_data[] = array('accid' => 'USFL0023', 'name' => 'Bagdad');
$city_data[] = array('accid' => 'USFL0536', 'name' => 'Baker');
$city_data[] = array('accid' => 'USFL0025', 'name' => 'Balm');
$city_data[] = array('accid' => 'USFL0026', 'name' => 'Barberville');
$city_data[] = array('accid' => 'USFL0027', 'name' => 'Bartow');
$city_data[] = array('accid' => 'USFL0028', 'name' => 'Bascom');
$city_data[] = array('accid' => 'USFL0029', 'name' => 'Bay Pines');
$city_data[] = array('accid' => 'USFL0030', 'name' => 'Bell');
$city_data[] = array('accid' => 'USFL0031', 'name' => 'Belle Glade');
$city_data[] = array('accid' => 'USFL0032', 'name' => 'Belleair Beach');
$city_data[] = array('accid' => 'USFL0033', 'name' => 'Belleview');
$city_data[] = array('accid' => 'USFL0034', 'name' => 'Beverly Hills');
$city_data[] = array('accid' => 'USFL0036', 'name' => 'Big Pine Key');
$city_data[] = array('accid' => 'USFL0038', 'name' => 'Blountstown');
$city_data[] = array('accid' => 'USFL0039', 'name' => 'Boca Grande');
$city_data[] = array('accid' => 'USFL0040', 'name' => 'Boca Raton');
$city_data[] = array('accid' => 'USFL0041', 'name' => 'Bokeelia');
$city_data[] = array('accid' => 'USFL0042', 'name' => 'Bonifay');
$city_data[] = array('accid' => 'USFL0043', 'name' => 'Bonita Springs');
$city_data[] = array('accid' => 'USFL0044', 'name' => 'Bostwick');
$city_data[] = array('accid' => 'USFL0045', 'name' => 'Bowling Green');
$city_data[] = array('accid' => 'USFL0046', 'name' => 'Boynton Beach');
$city_data[] = array('accid' => 'USFL0047', 'name' => 'Bradenton');
$city_data[] = array('accid' => 'USFL0048', 'name' => 'Bradenton Beach');
$city_data[] = array('accid' => 'USFL0049', 'name' => 'Bradley');
$city_data[] = array('accid' => 'USFL0050', 'name' => 'Brandon');
$city_data[] = array('accid' => 'USFL0051', 'name' => 'Branford');
$city_data[] = array('accid' => 'USFL0052', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USFL0053', 'name' => 'Bronson');
$city_data[] = array('accid' => 'USFL0054', 'name' => 'Brooker');
$city_data[] = array('accid' => 'USFL0055', 'name' => 'Brooksville');
$city_data[] = array('accid' => 'USFL0056', 'name' => 'Bryant');
$city_data[] = array('accid' => 'USFL0057', 'name' => 'Bryceville');
$city_data[] = array('accid' => 'USFL0058', 'name' => 'Bunnell');
$city_data[] = array('accid' => 'USFL0059', 'name' => 'Bushnell');
$city_data[] = array('accid' => 'USFL0060', 'name' => 'Callahan');
$city_data[] = array('accid' => 'USFL0061', 'name' => 'Campbellton');
$city_data[] = array('accid' => 'USFL0062', 'name' => 'Canal Point');
$city_data[] = array('accid' => 'USFL0064', 'name' => 'Candler');
$city_data[] = array('accid' => 'USFL0065', 'name' => 'Cantonment');
$city_data[] = array('accid' => 'USFL0066', 'name' => 'Cape Canaveral');
$city_data[] = array('accid' => 'USFL0067', 'name' => 'Cape Coral');
$city_data[] = array('accid' => 'USFL0068', 'name' => 'Captiva');
$city_data[] = array('accid' => 'USFL0069', 'name' => 'Carrabelle');
$city_data[] = array('accid' => 'USFL0070', 'name' => 'Caryville');
$city_data[] = array('accid' => 'USFL0071', 'name' => 'Cassadaga');
$city_data[] = array('accid' => 'USFL0072', 'name' => 'Casselberry');
$city_data[] = array('accid' => 'USFL0073', 'name' => 'Cedar Key');
$city_data[] = array('accid' => 'USFL0074', 'name' => 'Center Hill');
$city_data[] = array('accid' => 'USFL0075', 'name' => 'Century');
$city_data[] = array('accid' => 'USFL0076', 'name' => 'Chattahoochee');
$city_data[] = array('accid' => 'USFL0077', 'name' => 'Chiefland');
$city_data[] = array('accid' => 'USFL0078', 'name' => 'Chipley');
$city_data[] = array('accid' => 'USFL0079', 'name' => 'Chokoloskee');
$city_data[] = array('accid' => 'USFL0080', 'name' => 'Christmas');
$city_data[] = array('accid' => 'USFL0081', 'name' => 'Citra');
$city_data[] = array('accid' => 'USFL0082', 'name' => 'Clarcona');
$city_data[] = array('accid' => 'USFL0084', 'name' => 'Clearwater');
$city_data[] = array('accid' => 'USFL0085', 'name' => 'Clearwater Beach');
$city_data[] = array('accid' => 'USFL0086', 'name' => 'Clermont');
$city_data[] = array('accid' => 'USFL0087', 'name' => 'Clewiston');
$city_data[] = array('accid' => 'USFL0088', 'name' => 'Cocoa');
$city_data[] = array('accid' => 'USFL0089', 'name' => 'Cocoa Beach');
$city_data[] = array('accid' => 'USFL0090', 'name' => 'Coleman');
$city_data[] = array('accid' => 'USFL0091', 'name' => 'Copeland');
$city_data[] = array('accid' => 'USFL0092', 'name' => 'Cortez');
$city_data[] = array('accid' => 'USFL0093', 'name' => 'Cottondale');
$city_data[] = array('accid' => 'USFL0094', 'name' => 'Crawfordville');
$city_data[] = array('accid' => 'USFL0095', 'name' => 'Crescent City');
$city_data[] = array('accid' => 'USFL0096', 'name' => 'Crestview');
$city_data[] = array('accid' => 'USFL0097', 'name' => 'Cross City');
$city_data[] = array('accid' => 'USFL0098', 'name' => 'Crystal Beach');
$city_data[] = array('accid' => 'USFL0099', 'name' => 'Crystal River');
$city_data[] = array('accid' => 'USFL0100', 'name' => 'Crystal Springs');
$city_data[] = array('accid' => 'USFL0101', 'name' => 'Cypress');
$city_data[] = array('accid' => 'USFL0102', 'name' => 'Dade City');
$city_data[] = array('accid' => 'USFL0103', 'name' => 'Dania');
$city_data[] = array('accid' => 'USFL0104', 'name' => 'Davenport');
$city_data[] = array('accid' => 'USFL0105', 'name' => 'Day');
$city_data[] = array('accid' => 'USFL0106', 'name' => 'Daytona Beach');
$city_data[] = array('accid' => 'USFL0107', 'name' => 'De Leon Springs');
$city_data[] = array('accid' => 'USFL0108', 'name' => 'Debary');
$city_data[] = array('accid' => 'USFL0109', 'name' => 'Deerfield Beach');
$city_data[] = array('accid' => 'USFL0168', 'name' => 'DeFuniak Springs');
$city_data[] = array('accid' => 'USFL0111', 'name' => 'Deland');
$city_data[] = array('accid' => 'USFL0112', 'name' => 'Delray Beach');
$city_data[] = array('accid' => 'USFL0113', 'name' => 'Deltona');
$city_data[] = array('accid' => 'USFL0114', 'name' => 'Destin');
$city_data[] = array('accid' => 'USFL0115', 'name' => 'Doctors Inlet');
$city_data[] = array('accid' => 'USFL0116', 'name' => 'Dover');
$city_data[] = array('accid' => 'USFL0118', 'name' => 'Dundee');
$city_data[] = array('accid' => 'USFL0119', 'name' => 'Dunedin');
$city_data[] = array('accid' => 'USFL0120', 'name' => 'Dunnellon');
$city_data[] = array('accid' => 'USFL0121', 'name' => 'Durant');
$city_data[] = array('accid' => 'USFL0122', 'name' => 'Eagle Lake');
$city_data[] = array('accid' => 'USFL0123', 'name' => 'Earleton');
$city_data[] = array('accid' => 'USFL0124', 'name' => 'East Palatka');
$city_data[] = array('accid' => 'USFL0125', 'name' => 'Eastlake Weir');
$city_data[] = array('accid' => 'USFL0126', 'name' => 'Eastpoint');
$city_data[] = array('accid' => 'USFL0127', 'name' => 'Eaton Park');
$city_data[] = array('accid' => 'USFL0128', 'name' => 'Ebro');
$city_data[] = array('accid' => 'USFL0129', 'name' => 'Edgewater');
$city_data[] = array('accid' => 'USFL0130', 'name' => 'Eglin AFB');
$city_data[] = array('accid' => 'USFL0131', 'name' => 'Elfers');
$city_data[] = array('accid' => 'USFL0132', 'name' => 'Elkton');
$city_data[] = array('accid' => 'USFL0133', 'name' => 'Ellenton');
$city_data[] = array('accid' => 'USFL0134', 'name' => 'Englewood');
$city_data[] = array('accid' => 'USFL0135', 'name' => 'Estero');
$city_data[] = array('accid' => 'USFL0136', 'name' => 'Eustis');
$city_data[] = array('accid' => 'USFL0137', 'name' => 'Everglades City');
$city_data[] = array('accid' => 'USFL0139', 'name' => 'Evinston');
$city_data[] = array('accid' => 'USFL0140', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USFL0141', 'name' => 'Fedhaven');
$city_data[] = array('accid' => 'USFL0142', 'name' => 'Felda');
$city_data[] = array('accid' => 'USFL0143', 'name' => 'Fellsmere');
$city_data[] = array('accid' => 'USFL0144', 'name' => 'Fernandina Beach');
$city_data[] = array('accid' => 'USFL0145', 'name' => 'Ferndale');
$city_data[] = array('accid' => 'USFL0146', 'name' => 'Flagler Beach');
$city_data[] = array('accid' => 'USFL0591', 'name' => 'Fleming Island');
$city_data[] = array('accid' => 'USFL0147', 'name' => 'Florahome');
$city_data[] = array('accid' => 'USFL0148', 'name' => 'Floral City');
$city_data[] = array('accid' => 'USFL0149', 'name' => 'Fort Lauderdale');
$city_data[] = array('accid' => 'USFL0150', 'name' => 'Fort McCoy');
$city_data[] = array('accid' => 'USFL0151', 'name' => 'Fort Meade');
$city_data[] = array('accid' => 'USFL0152', 'name' => 'Fort Myers');
$city_data[] = array('accid' => 'USFL0153', 'name' => 'Fort Myers Beach');
$city_data[] = array('accid' => 'USFL0155', 'name' => 'Fort Ogden');
$city_data[] = array('accid' => 'USFL0156', 'name' => 'Fort Pierce');
$city_data[] = array('accid' => 'USFL0157', 'name' => 'Fort Walton Beach');
$city_data[] = array('accid' => 'USFL0158', 'name' => 'Fort White');
$city_data[] = array('accid' => 'USFL0159', 'name' => 'Fountain');
$city_data[] = array('accid' => 'USFL0160', 'name' => 'Freeport');
$city_data[] = array('accid' => 'USFL0161', 'name' => 'Frostproof');
$city_data[] = array('accid' => 'USFL0162', 'name' => 'Fruitland Park');
$city_data[] = array('accid' => 'USFL0163', 'name' => 'Gainesville');
$city_data[] = array('accid' => 'USFL0164', 'name' => 'Geneva');
$city_data[] = array('accid' => 'USFL0165', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USFL0166', 'name' => 'Gibsonton');
$city_data[] = array('accid' => 'USFL0167', 'name' => 'Glen Saint Mary');
$city_data[] = array('accid' => 'USFL0169', 'name' => 'Goldenrod');
$city_data[] = array('accid' => 'USFL0170', 'name' => 'Gonzalez');
$city_data[] = array('accid' => 'USFL0171', 'name' => 'Goodland');
$city_data[] = array('accid' => 'USFL0172', 'name' => 'Gotha');
$city_data[] = array('accid' => 'USFL0173', 'name' => 'Graceville');
$city_data[] = array('accid' => 'USFL0174', 'name' => 'Graham');
$city_data[] = array('accid' => 'USFL0175', 'name' => 'Grand Island');
$city_data[] = array('accid' => 'USFL0176', 'name' => 'Grand Ridge');
$city_data[] = array('accid' => 'USFL0177', 'name' => 'Grandin');
$city_data[] = array('accid' => 'USFL0178', 'name' => 'Grant');
$city_data[] = array('accid' => 'USFL0179', 'name' => 'Green Cove Springs');
$city_data[] = array('accid' => 'USFL0180', 'name' => 'Greensboro');
$city_data[] = array('accid' => 'USFL0181', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USFL0182', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USFL0183', 'name' => 'Gretna');
$city_data[] = array('accid' => 'USFL0184', 'name' => 'Groveland');
$city_data[] = array('accid' => 'USFL0185', 'name' => 'Gulf Breeze');
$city_data[] = array('accid' => 'USFL0186', 'name' => 'Gulf Hammock');
$city_data[] = array('accid' => 'USFL0188', 'name' => 'Haines City');
$city_data[] = array('accid' => 'USFL0189', 'name' => 'Hallandale');
$city_data[] = array('accid' => 'USFL0190', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USFL0191', 'name' => 'Harold');
$city_data[] = array('accid' => 'USFL0192', 'name' => 'Hastings');
$city_data[] = array('accid' => 'USFL0193', 'name' => 'Havana');
$city_data[] = array('accid' => 'USFL0195', 'name' => 'Hernando');
$city_data[] = array('accid' => 'USFL0196', 'name' => 'Hialeah');
$city_data[] = array('accid' => 'USFL0197', 'name' => 'High Springs');
$city_data[] = array('accid' => 'USFL0198', 'name' => 'Highland City');
$city_data[] = array('accid' => 'USFL0199', 'name' => 'Hilliard');
$city_data[] = array('accid' => 'USFL0200', 'name' => 'Hobe Sound');
$city_data[] = array('accid' => 'USFL0201', 'name' => 'Holder');
$city_data[] = array('accid' => 'USFL0202', 'name' => 'Holiday');
$city_data[] = array('accid' => 'USFL0203', 'name' => 'Hollister');
$city_data[] = array('accid' => 'USFL0204', 'name' => 'Hollywood');
$city_data[] = array('accid' => 'USFL0205', 'name' => 'Holmes Beach');
$city_data[] = array('accid' => 'USFL0206', 'name' => 'Holt');
$city_data[] = array('accid' => 'USFL0207', 'name' => 'Homeland');
$city_data[] = array('accid' => 'USFL0208', 'name' => 'Homestead');
$city_data[] = array('accid' => 'USFL0209', 'name' => 'Homosassa');
$city_data[] = array('accid' => 'USFL0210', 'name' => 'Homosassa Springs');
$city_data[] = array('accid' => 'USFL0211', 'name' => 'Horseshoe Beach');
$city_data[] = array('accid' => 'USFL0212', 'name' => 'Hosford');
$city_data[] = array('accid' => 'USFL0213', 'name' => 'Howey In The Hills');
$city_data[] = array('accid' => 'USFL0214', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USFL0215', 'name' => 'Hurlburt Field');
$city_data[] = array('accid' => 'USFL0216', 'name' => 'Immokalee');
$city_data[] = array('accid' => 'USFL0217', 'name' => 'Indialantic');
$city_data[] = array('accid' => 'USFL0218', 'name' => 'Indian Lake Estates');
$city_data[] = array('accid' => 'USFL0219', 'name' => 'Indian Rocks Beach');
$city_data[] = array('accid' => 'USFL0220', 'name' => 'Indiantown');
$city_data[] = array('accid' => 'USFL0221', 'name' => 'Inglis');
$city_data[] = array('accid' => 'USFL0222', 'name' => 'Intercession City');
$city_data[] = array('accid' => 'USFL0223', 'name' => 'Interlachen');
$city_data[] = array('accid' => 'USFL0224', 'name' => 'Inverness');
$city_data[] = array('accid' => 'USFL0225', 'name' => 'Islamorada');
$city_data[] = array('accid' => 'USFL0226', 'name' => 'Island Grove');
$city_data[] = array('accid' => 'USFL0227', 'name' => 'Istachatta');
$city_data[] = array('accid' => 'USFL0228', 'name' => 'Jacksonville');
$city_data[] = array('accid' => 'USFL0229', 'name' => 'Jacksonville Beach');
$city_data[] = array('accid' => 'USFL0230', 'name' => 'Jacksonville NAS');
$city_data[] = array('accid' => 'USFL0233', 'name' => 'Jasper');
$city_data[] = array('accid' => 'USFL0234', 'name' => 'Jay');
$city_data[] = array('accid' => 'USFL0235', 'name' => 'Jennings');
$city_data[] = array('accid' => 'USFL0236', 'name' => 'Jensen Beach');
$city_data[] = array('accid' => 'USFL0237', 'name' => 'Jupiter');
$city_data[] = array('accid' => 'USFL0238', 'name' => 'Kathleen');
$city_data[] = array('accid' => 'USFL0239', 'name' => 'Kenansville');
$city_data[] = array('accid' => 'USFL0241', 'name' => 'Key Biscayne');
$city_data[] = array('accid' => 'USFL0242', 'name' => 'Key Colony Beach');
$city_data[] = array('accid' => 'USFL0243', 'name' => 'Key Largo');
$city_data[] = array('accid' => 'USFL0244', 'name' => 'Key West');
$city_data[] = array('accid' => 'USFL0245', 'name' => 'Keystone Heights');
$city_data[] = array('accid' => 'USFL0246', 'name' => 'Killarney');
$city_data[] = array('accid' => 'USFL0247', 'name' => 'Kinard');
$city_data[] = array('accid' => 'USFL0248', 'name' => 'Kissimmee');
$city_data[] = array('accid' => 'USFL0250', 'name' => 'La Belle');
$city_data[] = array('accid' => 'USFL0249', 'name' => 'La Crosse');
$city_data[] = array('accid' => 'USFL0251', 'name' => 'Lacoochee');
$city_data[] = array('accid' => 'USFL0252', 'name' => 'Lady Lake');
$city_data[] = array('accid' => 'USFL0253', 'name' => 'Lake Alfred');
$city_data[] = array('accid' => 'USFL0254', 'name' => 'Lake Butler');
$city_data[] = array('accid' => 'USFL0255', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USFL0256', 'name' => 'Lake Como');
$city_data[] = array('accid' => 'USFL0257', 'name' => 'Lake Geneva');
$city_data[] = array('accid' => 'USFL0258', 'name' => 'Lake Hamilton');
$city_data[] = array('accid' => 'USFL0259', 'name' => 'Lake Harbor');
$city_data[] = array('accid' => 'USFL0260', 'name' => 'Lake Helen');
$city_data[] = array('accid' => 'USFL0261', 'name' => 'Lake Mary');
$city_data[] = array('accid' => 'USFL0262', 'name' => 'Lake Monroe');
$city_data[] = array('accid' => 'USFL0263', 'name' => 'Lake Panasoffkee');
$city_data[] = array('accid' => 'USFL0264', 'name' => 'Lake Placid');
$city_data[] = array('accid' => 'USFL0265', 'name' => 'Lake Wales');
$city_data[] = array('accid' => 'USFL0266', 'name' => 'Lake Worth');
$city_data[] = array('accid' => 'USFL0267', 'name' => 'Lakeland');
$city_data[] = array('accid' => 'USFL0268', 'name' => 'Lamont');
$city_data[] = array('accid' => 'USFL0269', 'name' => 'Lanark Village');
$city_data[] = array('accid' => 'USFL0539', 'name' => 'Land O Lakes');
$city_data[] = array('accid' => 'USFL0271', 'name' => 'Largo');
$city_data[] = array('accid' => 'USFL0272', 'name' => 'Laurel');
$city_data[] = array('accid' => 'USFL0273', 'name' => 'Laurel Hill');
$city_data[] = array('accid' => 'USFL0274', 'name' => 'Lawtey');
$city_data[] = array('accid' => 'USFL0275', 'name' => 'Lecanto');
$city_data[] = array('accid' => 'USFL0276', 'name' => 'Lee');
$city_data[] = array('accid' => 'USFL0277', 'name' => 'Leesburg');
$city_data[] = array('accid' => 'USFL0278', 'name' => 'Lehigh Acres');
$city_data[] = array('accid' => 'USFL0279', 'name' => 'Lithia');
$city_data[] = array('accid' => 'USFL0280', 'name' => 'Live Oak');
$city_data[] = array('accid' => 'USFL0281', 'name' => 'Lloyd');
$city_data[] = array('accid' => 'USFL0282', 'name' => 'Lochloosa');
$city_data[] = array('accid' => 'USFL0283', 'name' => 'Long Key');
$city_data[] = array('accid' => 'USFL0284', 'name' => 'Longboat Key');
$city_data[] = array('accid' => 'USFL0285', 'name' => 'Longwood');
$city_data[] = array('accid' => 'USFL0286', 'name' => 'Lorida');
$city_data[] = array('accid' => 'USFL0287', 'name' => 'Loughman');
$city_data[] = array('accid' => 'USFL0288', 'name' => 'Lowell');
$city_data[] = array('accid' => 'USFL0289', 'name' => 'Loxahatchee');
$city_data[] = array('accid' => 'USFL0290', 'name' => 'Lulu');
$city_data[] = array('accid' => 'USFL0291', 'name' => 'Lutz');
$city_data[] = array('accid' => 'USFL0292', 'name' => 'Lynn Haven');
$city_data[] = array('accid' => 'USFL0293', 'name' => 'MacClenny');
$city_data[] = array('accid' => 'USFL0294', 'name' => 'Madison');
$city_data[] = array('accid' => 'USFL0295', 'name' => 'Maitland');
$city_data[] = array('accid' => 'USFL0296', 'name' => 'Malabar');
$city_data[] = array('accid' => 'USFL0297', 'name' => 'Malone');
$city_data[] = array('accid' => 'USFL0298', 'name' => 'Manasota');
$city_data[] = array('accid' => 'USFL0299', 'name' => 'Mango');
$city_data[] = array('accid' => 'USFL0300', 'name' => 'Marathon');
$city_data[] = array('accid' => 'USFL0301', 'name' => 'Marathon Shores');
$city_data[] = array('accid' => 'USFL0302', 'name' => 'Marco Island');
$city_data[] = array('accid' => 'USFL0303', 'name' => 'Marianna');
$city_data[] = array('accid' => 'USFL0304', 'name' => 'Mary Esther');
$city_data[] = array('accid' => 'USFL0305', 'name' => 'Mascotte');
$city_data[] = array('accid' => 'USFL0306', 'name' => 'Mayo');
$city_data[] = array('accid' => 'USFL0308', 'name' => 'McAlpin');
$city_data[] = array('accid' => 'USFL0309', 'name' => 'McDavid');
$city_data[] = array('accid' => 'USFL0310', 'name' => 'McIntosh');
$city_data[] = array('accid' => 'USFL0311', 'name' => 'Melbourne');
$city_data[] = array('accid' => 'USFL0312', 'name' => 'Melbourne Beach');
$city_data[] = array('accid' => 'USFL0313', 'name' => 'Melrose');
$city_data[] = array('accid' => 'USFL0314', 'name' => 'Merritt Island');
$city_data[] = array('accid' => 'USFL0315', 'name' => 'Mexico Beach');
$city_data[] = array('accid' => 'USFL0316', 'name' => 'Miami');
$city_data[] = array('accid' => 'USFL0317', 'name' => 'Micanopy');
$city_data[] = array('accid' => 'USFL0318', 'name' => 'Miccosukee Cpo');
$city_data[] = array('accid' => 'USFL0319', 'name' => 'Mid Florida');
$city_data[] = array('accid' => 'USFL0320', 'name' => 'Middleburg');
$city_data[] = array('accid' => 'USFL0321', 'name' => 'Midway');
$city_data[] = array('accid' => 'USFL0322', 'name' => 'Milligan');
$city_data[] = array('accid' => 'USFL0323', 'name' => 'Milton');
$city_data[] = array('accid' => 'USFL0324', 'name' => 'Mims');
$city_data[] = array('accid' => 'USFL0325', 'name' => 'Minneola');
$city_data[] = array('accid' => 'USFL0326', 'name' => 'Molino');
$city_data[] = array('accid' => 'USFL0327', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USFL0328', 'name' => 'Montverde');
$city_data[] = array('accid' => 'USFL0329', 'name' => 'Moore Haven');
$city_data[] = array('accid' => 'USFL0330', 'name' => 'Morriston');
$city_data[] = array('accid' => 'USFL0331', 'name' => 'Mossy Head');
$city_data[] = array('accid' => 'USFL0332', 'name' => 'Mount Dora');
$city_data[] = array('accid' => 'USFL0333', 'name' => 'Mount Pleasant');
$city_data[] = array('accid' => 'USFL0334', 'name' => 'Mulberry');
$city_data[] = array('accid' => 'USFL0335', 'name' => 'Murdock');
$city_data[] = array('accid' => 'USFL0336', 'name' => 'Myakka City');
$city_data[] = array('accid' => 'USFL0337', 'name' => 'Nalcrest');
$city_data[] = array('accid' => 'USFL0338', 'name' => 'Naples');
$city_data[] = array('accid' => 'USFL0340', 'name' => 'Neptune Beach');
$city_data[] = array('accid' => 'USFL0341', 'name' => 'New Port Richey');
$city_data[] = array('accid' => 'USFL0342', 'name' => 'New Smyrna Beach');
$city_data[] = array('accid' => 'USFL0343', 'name' => 'Newberry');
$city_data[] = array('accid' => 'USFL0344', 'name' => 'Niceville');
$city_data[] = array('accid' => 'USFL0345', 'name' => 'Nichols');
$city_data[] = array('accid' => 'USFL0346', 'name' => 'Nobleton');
$city_data[] = array('accid' => 'USFL0347', 'name' => 'Nocatee');
$city_data[] = array('accid' => 'USFL0348', 'name' => 'Nokomis');
$city_data[] = array('accid' => 'USFL0349', 'name' => 'Noma');
$city_data[] = array('accid' => 'USFL0350', 'name' => 'North Palm Beach');
$city_data[] = array('accid' => 'USFL0351', 'name' => 'North Port');
$city_data[] = array('accid' => 'USFL0354', 'name' => 'O\'brien');
$city_data[] = array('accid' => 'USFL0352', 'name' => 'Oak Hill');
$city_data[] = array('accid' => 'USFL0353', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USFL0355', 'name' => 'Ocala');
$city_data[] = array('accid' => 'USFL0356', 'name' => 'Ochopee');
$city_data[] = array('accid' => 'USFL0537', 'name' => 'Ocklawaha');
$city_data[] = array('accid' => 'USFL0358', 'name' => 'Ocoee');
$city_data[] = array('accid' => 'USFL0359', 'name' => 'Odessa');
$city_data[] = array('accid' => 'USFL0360', 'name' => 'Okahumpka');
$city_data[] = array('accid' => 'USFL0361', 'name' => 'Okeechobee');
$city_data[] = array('accid' => 'USFL0362', 'name' => 'Old Town');
$city_data[] = array('accid' => 'USFL0363', 'name' => 'Oldsmar');
$city_data[] = array('accid' => 'USFL0364', 'name' => 'Olustee');
$city_data[] = array('accid' => 'USFL0365', 'name' => 'Ona');
$city_data[] = array('accid' => 'USFL0366', 'name' => 'Oneco');
$city_data[] = array('accid' => 'USFL0367', 'name' => 'Opa Locka');
$city_data[] = array('accid' => 'USFL0368', 'name' => 'Orange City');
$city_data[] = array('accid' => 'USFL0369', 'name' => 'Orange Lake');
$city_data[] = array('accid' => 'USFL0370', 'name' => 'Orange Park');
$city_data[] = array('accid' => 'USFL0371', 'name' => 'Orange Springs');
$city_data[] = array('accid' => 'USFL0372', 'name' => 'Orlando');
$city_data[] = array('accid' => 'USFL0373', 'name' => 'Orlando$city_data[]Executive Arpt');
$city_data[] = array('accid' => 'USFL0374', 'name' => 'Ormond Beach');
$city_data[] = array('accid' => 'USFL0375', 'name' => 'Osprey');
$city_data[] = array('accid' => 'USFL0376', 'name' => 'Osteen');
$city_data[] = array('accid' => 'USFL0377', 'name' => 'Otter Creek');
$city_data[] = array('accid' => 'USFL0378', 'name' => 'Oviedo');
$city_data[] = array('accid' => 'USFL0379', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USFL0380', 'name' => 'Ozona');
$city_data[] = array('accid' => 'USFL0381', 'name' => 'Pahokee');
$city_data[] = array('accid' => 'USFL0382', 'name' => 'Paisley');
$city_data[] = array('accid' => 'USFL0383', 'name' => 'Palatka');
$city_data[] = array('accid' => 'USFL0384', 'name' => 'Palm Bay');
$city_data[] = array('accid' => 'USFL0385', 'name' => 'Palm Beach');
$city_data[] = array('accid' => 'USFL0386', 'name' => 'Palm City');
$city_data[] = array('accid' => 'USFL0387', 'name' => 'Palm Coast');
$city_data[] = array('accid' => 'USFL0388', 'name' => 'Palm Harbor');
$city_data[] = array('accid' => 'USFL0389', 'name' => 'Palmdale');
$city_data[] = array('accid' => 'USFL0390', 'name' => 'Palmetto');
$city_data[] = array('accid' => 'USFL0391', 'name' => 'Panacea');
$city_data[] = array('accid' => 'USFL0392', 'name' => 'Panama City');
$city_data[] = array('accid' => 'USFL0393', 'name' => 'Panama City Beach');
$city_data[] = array('accid' => 'USFL0395', 'name' => 'Parrish');
$city_data[] = array('accid' => 'USFL0396', 'name' => 'Patrick AFB');
$city_data[] = array('accid' => 'USFL0397', 'name' => 'Paxton');
$city_data[] = array('accid' => 'USFL0398', 'name' => 'Penney Farms');
$city_data[] = array('accid' => 'USFL0399', 'name' => 'Pensacola');
$city_data[] = array('accid' => 'USFL0401', 'name' => 'Perry');
$city_data[] = array('accid' => 'USFL0402', 'name' => 'Pierson');
$city_data[] = array('accid' => 'USFL0403', 'name' => 'Pineland');
$city_data[] = array('accid' => 'USFL0404', 'name' => 'Pinellas Park');
$city_data[] = array('accid' => 'USFL0405', 'name' => 'Pinetta');
$city_data[] = array('accid' => 'USFL0406', 'name' => 'Placida');
$city_data[] = array('accid' => 'USFL0407', 'name' => 'Plant City');
$city_data[] = array('accid' => 'USFL0408', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USFL0409', 'name' => 'Point Washington');
$city_data[] = array('accid' => 'USFL0410', 'name' => 'Polk City');
$city_data[] = array('accid' => 'USFL0411', 'name' => 'Pomona Park');
$city_data[] = array('accid' => 'USFL0412', 'name' => 'Pompano Beach');
$city_data[] = array('accid' => 'USFL0413', 'name' => 'Ponce de Leon');
$city_data[] = array('accid' => 'USFL0414', 'name' => 'Ponte Vedra Beach');
$city_data[] = array('accid' => 'USFL0415', 'name' => 'Port Charlotte');
$city_data[] = array('accid' => 'USFL0416', 'name' => 'Port Orange');
$city_data[] = array('accid' => 'USFL0417', 'name' => 'Port Richey');
$city_data[] = array('accid' => 'USFL0418', 'name' => 'Port Saint Joe');
$city_data[] = array('accid' => 'USFL0419', 'name' => 'Port Saint Lucie');
$city_data[] = array('accid' => 'USFL0420', 'name' => 'Port Salerno');
$city_data[] = array('accid' => 'USFL0421', 'name' => 'Punta Gorda');
$city_data[] = array('accid' => 'USFL0422', 'name' => 'Putnam Hall');
$city_data[] = array('accid' => 'USFL0423', 'name' => 'Quincy');
$city_data[] = array('accid' => 'USFL0424', 'name' => 'Raiford');
$city_data[] = array('accid' => 'USFL0425', 'name' => 'Reddick');
$city_data[] = array('accid' => 'USFL0426', 'name' => 'River Ranch');
$city_data[] = array('accid' => 'USFL0427', 'name' => 'Riverview');
$city_data[] = array('accid' => 'USFL0428', 'name' => 'Rockledge');
$city_data[] = array('accid' => 'USFL0429', 'name' => 'Roseland');
$city_data[] = array('accid' => 'USFL0430', 'name' => 'Rotonda West');
$city_data[] = array('accid' => 'USFL0431', 'name' => 'Ruskin');
$city_data[] = array('accid' => 'USFL0432', 'name' => 'Safety Harbor');
$city_data[] = array('accid' => 'USFL0433', 'name' => 'Saint Augustine');
$city_data[] = array('accid' => 'USFL0434', 'name' => 'Saint Cloud');
$city_data[] = array('accid' => 'USFL0435', 'name' => 'Saint James City');
$city_data[] = array('accid' => 'USFL0436', 'name' => 'Saint Leo');
$city_data[] = array('accid' => 'USFL0437', 'name' => 'Saint Marks');
$city_data[] = array('accid' => 'USFL0438', 'name' => 'Saint Petersburg');
$city_data[] = array('accid' => 'USFL0439', 'name' => 'Salem');
$city_data[] = array('accid' => 'USFL0440', 'name' => 'San Antonio');
$city_data[] = array('accid' => 'USFL0538', 'name' => 'San Mateo');
$city_data[] = array('accid' => 'USFL0442', 'name' => 'Sanderson');
$city_data[] = array('accid' => 'USFL0443', 'name' => 'Sanford');
$city_data[] = array('accid' => 'USFL0444', 'name' => 'Sanibel');
$city_data[] = array('accid' => 'USFL0445', 'name' => 'Santa Rosa Beach');
$city_data[] = array('accid' => 'USFL0446', 'name' => 'Sarasota');
$city_data[] = array('accid' => 'USFL0447', 'name' => 'Satellite Beach');
$city_data[] = array('accid' => 'USFL0448', 'name' => 'Satsuma');
$city_data[] = array('accid' => 'USFL0449', 'name' => 'Scottsmoor');
$city_data[] = array('accid' => 'USFL0450', 'name' => 'Sebastian');
$city_data[] = array('accid' => 'USFL0451', 'name' => 'Sebring');
$city_data[] = array('accid' => 'USFL0452', 'name' => 'Seffner');
$city_data[] = array('accid' => 'USFL0453', 'name' => 'Seminole');
$city_data[] = array('accid' => 'USFL0454', 'name' => 'Seville');
$city_data[] = array('accid' => 'USFL0455', 'name' => 'Shady Grove');
$city_data[] = array('accid' => 'USFL0456', 'name' => 'Shalimar');
$city_data[] = array('accid' => 'USFL0457', 'name' => 'Sharpes');
$city_data[] = array('accid' => 'USFL0458', 'name' => 'Silver Springs');
$city_data[] = array('accid' => 'USFL0459', 'name' => 'Sneads');
$city_data[] = array('accid' => 'USFL0460', 'name' => 'Sopchoppy');
$city_data[] = array('accid' => 'USFL0461', 'name' => 'Sorrento');
$city_data[] = array('accid' => 'USFL0462', 'name' => 'South Bay');
$city_data[] = array('accid' => 'USFL0463', 'name' => 'South Florida');
$city_data[] = array('accid' => 'USFL0464', 'name' => 'Sparr');
$city_data[] = array('accid' => 'USFL0465', 'name' => 'Spring Hill');
$city_data[] = array('accid' => 'USFL0466', 'name' => 'Starke');
$city_data[] = array('accid' => 'USFL0467', 'name' => 'Steinhatchee');
$city_data[] = array('accid' => 'USFL0468', 'name' => 'Stuart');
$city_data[] = array('accid' => 'USFL0469', 'name' => 'Sugarloaf Shores');
$city_data[] = array('accid' => 'USFL0470', 'name' => 'Sumatra');
$city_data[] = array('accid' => 'USFL0471', 'name' => 'Summerfield');
$city_data[] = array('accid' => 'USFL0546', 'name' => 'Summerland Key');
$city_data[] = array('accid' => 'USFL0473', 'name' => 'Sumterville');
$city_data[] = array('accid' => 'USFL0474', 'name' => 'Sun City');
$city_data[] = array('accid' => 'USFL0475', 'name' => 'Sun City Center');
$city_data[] = array('accid' => 'USFL0476', 'name' => 'Sunnyside');
$city_data[] = array('accid' => 'USFL0477', 'name' => 'Suwannee');
$city_data[] = array('accid' => 'USFL0478', 'name' => 'Sydney');
$city_data[] = array('accid' => 'USFL0479', 'name' => 'Tallahassee');
$city_data[] = array('accid' => 'USFL0480', 'name' => 'Tallevast');
$city_data[] = array('accid' => 'USFL0481', 'name' => 'Tampa');
$city_data[] = array('accid' => 'USFL0483', 'name' => 'Tangerine');
$city_data[] = array('accid' => 'USFL0484', 'name' => 'Tarpon Springs');
$city_data[] = array('accid' => 'USFL0485', 'name' => 'Tavares');
$city_data[] = array('accid' => 'USFL0486', 'name' => 'Tavernier');
$city_data[] = array('accid' => 'USFL0487', 'name' => 'Telogia');
$city_data[] = array('accid' => 'USFL0488', 'name' => 'Terra Ceia');
$city_data[] = array('accid' => 'USFL0489', 'name' => 'Thonotosassa');
$city_data[] = array('accid' => 'USFL0490', 'name' => 'Titusville');
$city_data[] = array('accid' => 'USFL0491', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USFL0492', 'name' => 'Trilby');
$city_data[] = array('accid' => 'USFL0493', 'name' => 'Umatilla');
$city_data[] = array('accid' => 'USFL0494', 'name' => 'Valparaiso');
$city_data[] = array('accid' => 'USFL0495', 'name' => 'Valrico');
$city_data[] = array('accid' => 'USFL0496', 'name' => 'Vanderbilt Beach');
$city_data[] = array('accid' => 'USFL0497', 'name' => 'Venice');
$city_data[] = array('accid' => 'USFL0498', 'name' => 'Venus');
$city_data[] = array('accid' => 'USFL0499', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USFL0500', 'name' => 'Vero Beach');
$city_data[] = array('accid' => 'USFL0501', 'name' => 'Wabasso');
$city_data[] = array('accid' => 'USFL0502', 'name' => 'Wacissa');
$city_data[] = array('accid' => 'USFL0503', 'name' => 'Wakulla Springs');
$city_data[] = array('accid' => 'USFL0504', 'name' => 'Waldo');
$city_data[] = array('accid' => 'USFL0505', 'name' => 'Wauchula');
$city_data[] = array('accid' => 'USFL0506', 'name' => 'Wausau');
$city_data[] = array('accid' => 'USFL0507', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USFL0508', 'name' => 'Webster');
$city_data[] = array('accid' => 'USFL0509', 'name' => 'Weirsdale');
$city_data[] = array('accid' => 'USFL0510', 'name' => 'Welaka');
$city_data[] = array('accid' => 'USFL0511', 'name' => 'Wellborn');
$city_data[] = array('accid' => 'USFL0512', 'name' => 'West Palm Beach');
$city_data[] = array('accid' => 'USFL0514', 'name' => 'Westville');
$city_data[] = array('accid' => 'USFL0515', 'name' => 'Westwood Lakes');
$city_data[] = array('accid' => 'USFL0516', 'name' => 'Wewahitchka');
$city_data[] = array('accid' => 'USFL0517', 'name' => 'White Springs');
$city_data[] = array('accid' => 'USFL0518', 'name' => 'Wildwood');
$city_data[] = array('accid' => 'USFL0519', 'name' => 'Williston');
$city_data[] = array('accid' => 'USFL0520', 'name' => 'Wimauma');
$city_data[] = array('accid' => 'USFL0521', 'name' => 'Windermere');
$city_data[] = array('accid' => 'USFL0522', 'name' => 'Winter Beach');
$city_data[] = array('accid' => 'USFL0523', 'name' => 'Winter Garden');
$city_data[] = array('accid' => 'USFL0524', 'name' => 'Winter Haven');
$city_data[] = array('accid' => 'USFL0525', 'name' => 'Winter Park');
$city_data[] = array('accid' => 'USFL0526', 'name' => 'Winter Springs');
$city_data[] = array('accid' => 'USFL0527', 'name' => 'Woodville');
$city_data[] = array('accid' => 'USFL0528', 'name' => 'Worthington Springs');
$city_data[] = array('accid' => 'USFL0529', 'name' => 'Yalaha');
$city_data[] = array('accid' => 'USFL0530', 'name' => 'Yankeetown');
$city_data[] = array('accid' => 'USFL0531', 'name' => 'Youngstown');
$city_data[] = array('accid' => 'USFL0532', 'name' => 'Yulee');
$city_data[] = array('accid' => 'USFL0533', 'name' => 'Zellwood');
$city_data[] = array('accid' => 'USFL0534', 'name' => 'Zephyr Hills');
$city_data[] = array('accid' => 'USFL0535', 'name' => 'Zolfo Springs');

?>