<?php

// City package for USA: Georgia 

$city_name = 'USA: Georgia';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USGA0001', 'name' => 'Abbeville');
$city_data[] = array('accid' => 'USGA0002', 'name' => 'Acworth');
$city_data[] = array('accid' => 'USGA0003', 'name' => 'Adairsville');
$city_data[] = array('accid' => 'USGA0004', 'name' => 'Adel');
$city_data[] = array('accid' => 'USGA0005', 'name' => 'Adrian');
$city_data[] = array('accid' => 'USGA0006', 'name' => 'Ailey');
$city_data[] = array('accid' => 'USGA0007', 'name' => 'Alamo');
$city_data[] = array('accid' => 'USGA0008', 'name' => 'Alapaha');
$city_data[] = array('accid' => 'USGA0009', 'name' => 'Albany');
$city_data[] = array('accid' => 'USGA0010', 'name' => 'Allenhurst');
$city_data[] = array('accid' => 'USGA0011', 'name' => 'Allentown');
$city_data[] = array('accid' => 'USGA0012', 'name' => 'Alma');
$city_data[] = array('accid' => 'USGA0013', 'name' => 'Alpharetta');
$city_data[] = array('accid' => 'USGA0014', 'name' => 'Alston');
$city_data[] = array('accid' => 'USGA0015', 'name' => 'Alto');
$city_data[] = array('accid' => 'USGA0016', 'name' => 'Ambrose');
$city_data[] = array('accid' => 'USGA0017', 'name' => 'Americus');
$city_data[] = array('accid' => 'USGA0018', 'name' => 'Andersonville');
$city_data[] = array('accid' => 'USGA0019', 'name' => 'Appling');
$city_data[] = array('accid' => 'USGA0020', 'name' => 'Arabi');
$city_data[] = array('accid' => 'USGA0021', 'name' => 'Aragon');
$city_data[] = array('accid' => 'USGA0022', 'name' => 'Argyle');
$city_data[] = array('accid' => 'USGA0023', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USGA0024', 'name' => 'Armuchee');
$city_data[] = array('accid' => 'USGA0025', 'name' => 'Arnoldsville');
$city_data[] = array('accid' => 'USGA0026', 'name' => 'Ashburn');
$city_data[] = array('accid' => 'USGA0027', 'name' => 'Athens');
$city_data[] = array('accid' => 'USGA0028', 'name' => 'Atlanta');
$city_data[] = array('accid' => 'USGA0030', 'name' => 'Attapulgus');
$city_data[] = array('accid' => 'USGA0031', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USGA0032', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USGA0034', 'name' => 'Austell');
$city_data[] = array('accid' => 'USGA0035', 'name' => 'Avera');
$city_data[] = array('accid' => 'USGA0036', 'name' => 'Avondale Estates');
$city_data[] = array('accid' => 'USGA0037', 'name' => 'Axson');
$city_data[] = array('accid' => 'USGA0038', 'name' => 'Baconton');
$city_data[] = array('accid' => 'USGA0039', 'name' => 'Bainbridge');
$city_data[] = array('accid' => 'USGA0040', 'name' => 'Baldwin');
$city_data[] = array('accid' => 'USGA0041', 'name' => 'Ball Ground');
$city_data[] = array('accid' => 'USGA0042', 'name' => 'Barnesville');
$city_data[] = array('accid' => 'USGA0043', 'name' => 'Barney');
$city_data[] = array('accid' => 'USGA0044', 'name' => 'Bartow');
$city_data[] = array('accid' => 'USGA0045', 'name' => 'Barwick');
$city_data[] = array('accid' => 'USGA0046', 'name' => 'Baxley');
$city_data[] = array('accid' => 'USGA0047', 'name' => 'Bellville');
$city_data[] = array('accid' => 'USGA0048', 'name' => 'Berlin');
$city_data[] = array('accid' => 'USGA0049', 'name' => 'Bethlehem');
$city_data[] = array('accid' => 'USGA0050', 'name' => 'Bishop');
$city_data[] = array('accid' => 'USGA0051', 'name' => 'Blackshear');
$city_data[] = array('accid' => 'USGA0052', 'name' => 'Blairsville');
$city_data[] = array('accid' => 'USGA0053', 'name' => 'Blakely');
$city_data[] = array('accid' => 'USGA0054', 'name' => 'Bloomingdale');
$city_data[] = array('accid' => 'USGA0055', 'name' => 'Blue Ridge');
$city_data[] = array('accid' => 'USGA0056', 'name' => 'Bluffton');
$city_data[] = array('accid' => 'USGA0057', 'name' => 'Blythe');
$city_data[] = array('accid' => 'USGA0058', 'name' => 'Bogart');
$city_data[] = array('accid' => 'USGA0059', 'name' => 'Bolingbroke');
$city_data[] = array('accid' => 'USGA0060', 'name' => 'Bonaire');
$city_data[] = array('accid' => 'USGA0061', 'name' => 'Boneville');
$city_data[] = array('accid' => 'USGA0062', 'name' => 'Boston');
$city_data[] = array('accid' => 'USGA0063', 'name' => 'Bostwick');
$city_data[] = array('accid' => 'USGA0064', 'name' => 'Bowdon');
$city_data[] = array('accid' => 'USGA0065', 'name' => 'Bowdon Junction');
$city_data[] = array('accid' => 'USGA0066', 'name' => 'Bowersville');
$city_data[] = array('accid' => 'USGA0067', 'name' => 'Bowman');
$city_data[] = array('accid' => 'USGA0068', 'name' => 'Box Springs');
$city_data[] = array('accid' => 'USGA0069', 'name' => 'Braselton');
$city_data[] = array('accid' => 'USGA0070', 'name' => 'Bremen');
$city_data[] = array('accid' => 'USGA0071', 'name' => 'Brinson');
$city_data[] = array('accid' => 'USGA0072', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USGA0073', 'name' => 'Bronwood');
$city_data[] = array('accid' => 'USGA0074', 'name' => 'Brookfield');
$city_data[] = array('accid' => 'USGA0075', 'name' => 'Brooklet');
$city_data[] = array('accid' => 'USGA0076', 'name' => 'Brooks');
$city_data[] = array('accid' => 'USGA0077', 'name' => 'Broxton');
$city_data[] = array('accid' => 'USGA0078', 'name' => 'Brunswick');
$city_data[] = array('accid' => 'USGA0079', 'name' => 'Buchanan');
$city_data[] = array('accid' => 'USGA0080', 'name' => 'Buckhead');
$city_data[] = array('accid' => 'USGA0081', 'name' => 'Buena Vista');
$city_data[] = array('accid' => 'USGA0082', 'name' => 'Buford');
$city_data[] = array('accid' => 'USGA0083', 'name' => 'Butler');
$city_data[] = array('accid' => 'USGA0084', 'name' => 'Byromville');
$city_data[] = array('accid' => 'USGA0085', 'name' => 'Byron');
$city_data[] = array('accid' => 'USGA0086', 'name' => 'Cadwell');
$city_data[] = array('accid' => 'USGA0087', 'name' => 'Cairo');
$city_data[] = array('accid' => 'USGA0088', 'name' => 'Calhoun');
$city_data[] = array('accid' => 'USGA0089', 'name' => 'Calvary');
$city_data[] = array('accid' => 'USGA0090', 'name' => 'Camak');
$city_data[] = array('accid' => 'USGA0091', 'name' => 'Camilla');
$city_data[] = array('accid' => 'USGA0092', 'name' => 'Canon');
$city_data[] = array('accid' => 'USGA0093', 'name' => 'Canton');
$city_data[] = array('accid' => 'USGA0094', 'name' => 'Carlton');
$city_data[] = array('accid' => 'USGA0095', 'name' => 'Carnesville');
$city_data[] = array('accid' => 'USGA0096', 'name' => 'Carrollton');
$city_data[] = array('accid' => 'USGA0097', 'name' => 'Cartersville');
$city_data[] = array('accid' => 'USGA0098', 'name' => 'Cassville');
$city_data[] = array('accid' => 'USGA0099', 'name' => 'Cataula');
$city_data[] = array('accid' => 'USGA0100', 'name' => 'Cave Spring');
$city_data[] = array('accid' => 'USGA0101', 'name' => 'Cecil');
$city_data[] = array('accid' => 'USGA0102', 'name' => 'Cedar Springs');
$city_data[] = array('accid' => 'USGA0103', 'name' => 'Cedartown');
$city_data[] = array('accid' => 'USGA0104', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USGA0106', 'name' => 'Chatsworth');
$city_data[] = array('accid' => 'USGA0107', 'name' => 'Chauncey');
$city_data[] = array('accid' => 'USGA0108', 'name' => 'Cherrylog');
$city_data[] = array('accid' => 'USGA0109', 'name' => 'Chester');
$city_data[] = array('accid' => 'USGA0110', 'name' => 'Chestnut Mountain');
$city_data[] = array('accid' => 'USGA0111', 'name' => 'Chickamauga');
$city_data[] = array('accid' => 'USGA0112', 'name' => 'Chula');
$city_data[] = array('accid' => 'USGA0113', 'name' => 'Cisco');
$city_data[] = array('accid' => 'USGA0114', 'name' => 'Clarkdale');
$city_data[] = array('accid' => 'USGA0115', 'name' => 'Clarkesville');
$city_data[] = array('accid' => 'USGA0116', 'name' => 'Clarkston');
$city_data[] = array('accid' => 'USGA0117', 'name' => 'Claxton');
$city_data[] = array('accid' => 'USGA0118', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USGA0119', 'name' => 'Clermont');
$city_data[] = array('accid' => 'USGA0120', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USGA0121', 'name' => 'Climax');
$city_data[] = array('accid' => 'USGA0122', 'name' => 'Clinchfield');
$city_data[] = array('accid' => 'USGA0123', 'name' => 'Clyo');
$city_data[] = array('accid' => 'USGA0124', 'name' => 'Cobb');
$city_data[] = array('accid' => 'USGA0125', 'name' => 'Cobbtown');
$city_data[] = array('accid' => 'USGA0126', 'name' => 'Cochran');
$city_data[] = array('accid' => 'USGA0127', 'name' => 'Cohutta');
$city_data[] = array('accid' => 'USGA0128', 'name' => 'Colbert');
$city_data[] = array('accid' => 'USGA0129', 'name' => 'Coleman');
$city_data[] = array('accid' => 'USGA0130', 'name' => 'Collins');
$city_data[] = array('accid' => 'USGA0131', 'name' => 'Colquitt');
$city_data[] = array('accid' => 'USGA0132', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USGA0134', 'name' => 'Comer');
$city_data[] = array('accid' => 'USGA0135', 'name' => 'Commerce');
$city_data[] = array('accid' => 'USGA0136', 'name' => 'Concord');
$city_data[] = array('accid' => 'USGA0137', 'name' => 'Conley');
$city_data[] = array('accid' => 'USGA0138', 'name' => 'Conyers');
$city_data[] = array('accid' => 'USGA0139', 'name' => 'Coolidge');
$city_data[] = array('accid' => 'USGA0140', 'name' => 'Coosa');
$city_data[] = array('accid' => 'USGA0141', 'name' => 'Cordele');
$city_data[] = array('accid' => 'USGA0142', 'name' => 'Cornelia');
$city_data[] = array('accid' => 'USGA0143', 'name' => 'Cotton');
$city_data[] = array('accid' => 'USGA0144', 'name' => 'Covington');
$city_data[] = array('accid' => 'USGA0145', 'name' => 'Crandall');
$city_data[] = array('accid' => 'USGA0146', 'name' => 'Crawford');
$city_data[] = array('accid' => 'USGA0147', 'name' => 'Crawfordville');
$city_data[] = array('accid' => 'USGA0148', 'name' => 'Crescent');
$city_data[] = array('accid' => 'USGA0149', 'name' => 'Culloden');
$city_data[] = array('accid' => 'USGA0151', 'name' => 'Cumming');
$city_data[] = array('accid' => 'USGA0152', 'name' => 'Cusseta');
$city_data[] = array('accid' => 'USGA0153', 'name' => 'Cuthbert');
$city_data[] = array('accid' => 'USGA0154', 'name' => 'Dacula');
$city_data[] = array('accid' => 'USGA0155', 'name' => 'Dahlonega');
$city_data[] = array('accid' => 'USGA0156', 'name' => 'Daisy');
$city_data[] = array('accid' => 'USGA0157', 'name' => 'Dallas');
$city_data[] = array('accid' => 'USGA0158', 'name' => 'Dalton');
$city_data[] = array('accid' => 'USGA0159', 'name' => 'Damascus');
$city_data[] = array('accid' => 'USGA0160', 'name' => 'Danielsville');
$city_data[] = array('accid' => 'USGA0161', 'name' => 'Danville');
$city_data[] = array('accid' => 'USGA0162', 'name' => 'Darien');
$city_data[] = array('accid' => 'USGA0163', 'name' => 'Davisboro');
$city_data[] = array('accid' => 'USGA0164', 'name' => 'Dawson');
$city_data[] = array('accid' => 'USGA0165', 'name' => 'Dawsonville');
$city_data[] = array('accid' => 'USGA0166', 'name' => 'De Soto');
$city_data[] = array('accid' => 'USGA0167', 'name' => 'Dearing');
$city_data[] = array('accid' => 'USGA0168', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USGA0169', 'name' => 'Demorest');
$city_data[] = array('accid' => 'USGA0170', 'name' => 'Denton');
$city_data[] = array('accid' => 'USGA0171', 'name' => 'Dewy Rose');
$city_data[] = array('accid' => 'USGA0172', 'name' => 'Dexter');
$city_data[] = array('accid' => 'USGA0173', 'name' => 'Dillard');
$city_data[] = array('accid' => 'USGA0174', 'name' => 'Dixie');
$city_data[] = array('accid' => 'USGA0175', 'name' => 'Doerun');
$city_data[] = array('accid' => 'USGA0176', 'name' => 'Donalsonville');
$city_data[] = array('accid' => 'USGA0177', 'name' => 'Douglas');
$city_data[] = array('accid' => 'USGA0178', 'name' => 'Douglasville');
$city_data[] = array('accid' => 'USGA0179', 'name' => 'Dover');
$city_data[] = array('accid' => 'USGA0180', 'name' => 'Dry Branch');
$city_data[] = array('accid' => 'USGA0181', 'name' => 'Du Pont');
$city_data[] = array('accid' => 'USGA0182', 'name' => 'Dublin');
$city_data[] = array('accid' => 'USGA0183', 'name' => 'Dudley');
$city_data[] = array('accid' => 'USGA0184', 'name' => 'Duluth');
$city_data[] = array('accid' => 'USGA0185', 'name' => 'East Ellijay');
$city_data[] = array('accid' => 'USGA0186', 'name' => 'Eastanollee');
$city_data[] = array('accid' => 'USGA0187', 'name' => 'Eastman');
$city_data[] = array('accid' => 'USGA0188', 'name' => 'Eatonton');
$city_data[] = array('accid' => 'USGA0189', 'name' => 'Eden');
$city_data[] = array('accid' => 'USGA0190', 'name' => 'Edison');
$city_data[] = array('accid' => 'USGA0191', 'name' => 'Elberton');
$city_data[] = array('accid' => 'USGA0192', 'name' => 'Elko');
$city_data[] = array('accid' => 'USGA0193', 'name' => 'Ellabell');
$city_data[] = array('accid' => 'USGA0194', 'name' => 'Ellaville');
$city_data[] = array('accid' => 'USGA0195', 'name' => 'Ellenton');
$city_data[] = array('accid' => 'USGA0196', 'name' => 'Ellenwood');
$city_data[] = array('accid' => 'USGA0197', 'name' => 'Ellerslie');
$city_data[] = array('accid' => 'USGA0198', 'name' => 'Ellijay');
$city_data[] = array('accid' => 'USGA0199', 'name' => 'Emerson');
$city_data[] = array('accid' => 'USGA0200', 'name' => 'Enigma');
$city_data[] = array('accid' => 'USGA0201', 'name' => 'Epworth');
$city_data[] = array('accid' => 'USGA0202', 'name' => 'Esom Hill');
$city_data[] = array('accid' => 'USGA0203', 'name' => 'Eton');
$city_data[] = array('accid' => 'USGA0204', 'name' => 'Evans');
$city_data[] = array('accid' => 'USGA0205', 'name' => 'Experiment');
$city_data[] = array('accid' => 'USGA0206', 'name' => 'Fairburn');
$city_data[] = array('accid' => 'USGA0207', 'name' => 'Fairmount');
$city_data[] = array('accid' => 'USGA0208', 'name' => 'Fargo');
$city_data[] = array('accid' => 'USGA0209', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USGA0210', 'name' => 'Fayetteville');
$city_data[] = array('accid' => 'USGA0211', 'name' => 'Felton');
$city_data[] = array('accid' => 'USGA0212', 'name' => 'Fitzgerald');
$city_data[] = array('accid' => 'USGA0213', 'name' => 'Fleming');
$city_data[] = array('accid' => 'USGA0214', 'name' => 'Flintstone');
$city_data[] = array('accid' => 'USGA0215', 'name' => 'Flovilla');
$city_data[] = array('accid' => 'USGA0216', 'name' => 'Flowery Branch');
$city_data[] = array('accid' => 'USGA0217', 'name' => 'Folkston');
$city_data[] = array('accid' => 'USGA0218', 'name' => 'Forest Park');
$city_data[] = array('accid' => 'USGA0219', 'name' => 'Forsyth');
$city_data[] = array('accid' => 'USGA0220', 'name' => 'Fort Benning');
$city_data[] = array('accid' => 'USGA0221', 'name' => 'Fort Gaines');
$city_data[] = array('accid' => 'USGA0222', 'name' => 'Fort Oglethorpe');
$city_data[] = array('accid' => 'USGA0223', 'name' => 'Fort Stewart');
$city_data[] = array('accid' => 'USGA0224', 'name' => 'Fort Valley');
$city_data[] = array('accid' => 'USGA0225', 'name' => 'Fortson');
$city_data[] = array('accid' => 'USGA0644', 'name' => 'Fowlston');
$city_data[] = array('accid' => 'USGA0226', 'name' => 'Fowlstown');
$city_data[] = array('accid' => 'USGA0227', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USGA0228', 'name' => 'Franklin Springs');
$city_data[] = array('accid' => 'USGA0229', 'name' => 'Funston');
$city_data[] = array('accid' => 'USGA0230', 'name' => 'Gainesville');
$city_data[] = array('accid' => 'USGA0231', 'name' => 'Garfield');
$city_data[] = array('accid' => 'USGA0232', 'name' => 'Gay');
$city_data[] = array('accid' => 'USGA0233', 'name' => 'Geneva');
$city_data[] = array('accid' => 'USGA0234', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USGA0235', 'name' => 'Gibson');
$city_data[] = array('accid' => 'USGA0236', 'name' => 'Gillsville');
$city_data[] = array('accid' => 'USGA0237', 'name' => 'Girard');
$city_data[] = array('accid' => 'USGA0238', 'name' => 'Glenn');
$city_data[] = array('accid' => 'USGA0239', 'name' => 'Glennville');
$city_data[] = array('accid' => 'USGA0240', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USGA0241', 'name' => 'Good Hope');
$city_data[] = array('accid' => 'USGA0242', 'name' => 'Gordon');
$city_data[] = array('accid' => 'USGA0243', 'name' => 'Gough');
$city_data[] = array('accid' => 'USGA0244', 'name' => 'Gracewood');
$city_data[] = array('accid' => 'USGA0245', 'name' => 'Grantville');
$city_data[] = array('accid' => 'USGA0246', 'name' => 'Gray');
$city_data[] = array('accid' => 'USGA0247', 'name' => 'Grayson');
$city_data[] = array('accid' => 'USGA0248', 'name' => 'Graysville');
$city_data[] = array('accid' => 'USGA0249', 'name' => 'Greensboro');
$city_data[] = array('accid' => 'USGA0250', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USGA0251', 'name' => 'Griffin');
$city_data[] = array('accid' => 'USGA0252', 'name' => 'Grovetown');
$city_data[] = array('accid' => 'USGA0253', 'name' => 'Guyton');
$city_data[] = array('accid' => 'USGA0254', 'name' => 'Haddock');
$city_data[] = array('accid' => 'USGA0255', 'name' => 'Hagan');
$city_data[] = array('accid' => 'USGA0256', 'name' => 'Hahira');
$city_data[] = array('accid' => 'USGA0257', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USGA0258', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USGA0259', 'name' => 'Haralson');
$city_data[] = array('accid' => 'USGA0260', 'name' => 'Hardwick');
$city_data[] = array('accid' => 'USGA0261', 'name' => 'Harlem');
$city_data[] = array('accid' => 'USGA0262', 'name' => 'Harrison');
$city_data[] = array('accid' => 'USGA0263', 'name' => 'Hartsfield');
$city_data[] = array('accid' => 'USGA0264', 'name' => 'Hartwell');
$city_data[] = array('accid' => 'USGA0265', 'name' => 'Hawkinsville');
$city_data[] = array('accid' => 'USGA0266', 'name' => 'Hazlehurst');
$city_data[] = array('accid' => 'USGA0267', 'name' => 'Helen');
$city_data[] = array('accid' => 'USGA0268', 'name' => 'Helena');
$city_data[] = array('accid' => 'USGA0269', 'name' => 'Hephzibah');
$city_data[] = array('accid' => 'USGA0270', 'name' => 'Hiawassee');
$city_data[] = array('accid' => 'USGA0271', 'name' => 'High Shoals');
$city_data[] = array('accid' => 'USGA0272', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USGA0273', 'name' => 'Hinesville');
$city_data[] = array('accid' => 'USGA0274', 'name' => 'Hiram');
$city_data[] = array('accid' => 'USGA0275', 'name' => 'Hoboken');
$city_data[] = array('accid' => 'USGA0276', 'name' => 'Hogansville');
$city_data[] = array('accid' => 'USGA0277', 'name' => 'Holly Springs');
$city_data[] = array('accid' => 'USGA0278', 'name' => 'Homer');
$city_data[] = array('accid' => 'USGA0279', 'name' => 'Homerville');
$city_data[] = array('accid' => 'USGA0280', 'name' => 'Hortense');
$city_data[] = array('accid' => 'USGA0281', 'name' => 'Hoschton');
$city_data[] = array('accid' => 'USGA0282', 'name' => 'Howard');
$city_data[] = array('accid' => 'USGA0283', 'name' => 'Hull');
$city_data[] = array('accid' => 'USGA0284', 'name' => 'Ideal');
$city_data[] = array('accid' => 'USGA0285', 'name' => 'Ila');
$city_data[] = array('accid' => 'USGA0286', 'name' => 'Inman');
$city_data[] = array('accid' => 'USGA0287', 'name' => 'Iron City');
$city_data[] = array('accid' => 'USGA0288', 'name' => 'Irwinton');
$city_data[] = array('accid' => 'USGA0289', 'name' => 'Irwinville');
$city_data[] = array('accid' => 'USGA0290', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USGA0291', 'name' => 'Jacksonville');
$city_data[] = array('accid' => 'USGA0292', 'name' => 'Jakin');
$city_data[] = array('accid' => 'USGA0293', 'name' => 'Jasper');
$city_data[] = array('accid' => 'USGA0294', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USGA0295', 'name' => 'Jeffersonville');
$city_data[] = array('accid' => 'USGA0296', 'name' => 'Jekyll Island');
$city_data[] = array('accid' => 'USGA0297', 'name' => 'Jenkinsburg');
$city_data[] = array('accid' => 'USGA0298', 'name' => 'Jersey');
$city_data[] = array('accid' => 'USGA0299', 'name' => 'Jesup');
$city_data[] = array('accid' => 'USGA0300', 'name' => 'Jewell');
$city_data[] = array('accid' => 'USGA0301', 'name' => 'Jonesboro');
$city_data[] = array('accid' => 'USGA0302', 'name' => 'Juliette');
$city_data[] = array('accid' => 'USGA0303', 'name' => 'Junction City');
$city_data[] = array('accid' => 'USGA0304', 'name' => 'Kathleen');
$city_data[] = array('accid' => 'USGA0305', 'name' => 'Kennesaw');
$city_data[] = array('accid' => 'USGA0306', 'name' => 'Keysville');
$city_data[] = array('accid' => 'USGA0307', 'name' => 'Kings Bay');
$city_data[] = array('accid' => 'USGA0308', 'name' => 'Kingsland');
$city_data[] = array('accid' => 'USGA0309', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USGA0310', 'name' => 'Kite');
$city_data[] = array('accid' => 'USGA0311', 'name' => 'Knoxville');
$city_data[] = array('accid' => 'USGA0312', 'name' => 'La Fayette');
$city_data[] = array('accid' => 'USGA0313', 'name' => 'Lagrange');
$city_data[] = array('accid' => 'USGA0314', 'name' => 'Lake Park');
$city_data[] = array('accid' => 'USGA0315', 'name' => 'Lakeland');
$city_data[] = array('accid' => 'USGA0316', 'name' => 'Lakemont');
$city_data[] = array('accid' => 'USGA0317', 'name' => 'Lavonia');
$city_data[] = array('accid' => 'USGA0318', 'name' => 'Lawrenceville');
$city_data[] = array('accid' => 'USGA0319', 'name' => 'Leary');
$city_data[] = array('accid' => 'USGA0320', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USGA0321', 'name' => 'Leesburg');
$city_data[] = array('accid' => 'USGA0322', 'name' => 'Lenox');
$city_data[] = array('accid' => 'USGA0323', 'name' => 'Leslie');
$city_data[] = array('accid' => 'USGA0324', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USGA0325', 'name' => 'Lilburn');
$city_data[] = array('accid' => 'USGA0326', 'name' => 'Lilly');
$city_data[] = array('accid' => 'USGA0327', 'name' => 'Lincolnton');
$city_data[] = array('accid' => 'USGA0328', 'name' => 'Lindale');
$city_data[] = array('accid' => 'USGA0329', 'name' => 'Lithia Springs');
$city_data[] = array('accid' => 'USGA0330', 'name' => 'Lithonia');
$city_data[] = array('accid' => 'USGA0331', 'name' => 'Lizella');
$city_data[] = array('accid' => 'USGA0332', 'name' => 'Locust Grove');
$city_data[] = array('accid' => 'USGA0333', 'name' => 'Loganville');
$city_data[] = array('accid' => 'USGA0334', 'name' => 'Lookout Mountain');
$city_data[] = array('accid' => 'USGA0335', 'name' => 'Louisville');
$city_data[] = array('accid' => 'USGA0336', 'name' => 'Louvale');
$city_data[] = array('accid' => 'USGA0337', 'name' => 'Lovejoy');
$city_data[] = array('accid' => 'USGA0338', 'name' => 'Ludowici');
$city_data[] = array('accid' => 'USGA0339', 'name' => 'Lula');
$city_data[] = array('accid' => 'USGA0340', 'name' => 'Lumber City');
$city_data[] = array('accid' => 'USGA0341', 'name' => 'Lumpkin');
$city_data[] = array('accid' => 'USGA0342', 'name' => 'Luthersville');
$city_data[] = array('accid' => 'USGA0343', 'name' => 'Lyerly');
$city_data[] = array('accid' => 'USGA0344', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USGA0345', 'name' => 'Mableton');
$city_data[] = array('accid' => 'USGA0346', 'name' => 'Macon');
$city_data[] = array('accid' => 'USGA0347', 'name' => 'Madison');
$city_data[] = array('accid' => 'USGA0348', 'name' => 'Manassas');
$city_data[] = array('accid' => 'USGA0349', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USGA0350', 'name' => 'Manor');
$city_data[] = array('accid' => 'USGA0351', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'USGA0352', 'name' => 'Marble Hill');
$city_data[] = array('accid' => 'USGA0353', 'name' => 'Marietta');
$city_data[] = array('accid' => 'USGA0354', 'name' => 'Marshallville');
$city_data[] = array('accid' => 'USGA0355', 'name' => 'Martin');
$city_data[] = array('accid' => 'USGA0356', 'name' => 'Matthews');
$city_data[] = array('accid' => 'USGA0357', 'name' => 'Mauk');
$city_data[] = array('accid' => 'USGA0358', 'name' => 'Maxeys');
$city_data[] = array('accid' => 'USGA0359', 'name' => 'Maysville');
$city_data[] = array('accid' => 'USGA0360', 'name' => 'McCaysville');
$city_data[] = array('accid' => 'USGA0361', 'name' => 'McDonough');
$city_data[] = array('accid' => 'USGA0362', 'name' => 'McIntyre');
$city_data[] = array('accid' => 'USGA0363', 'name' => 'McRae');
$city_data[] = array('accid' => 'USGA0364', 'name' => 'Meansville');
$city_data[] = array('accid' => 'USGA0365', 'name' => 'Meigs');
$city_data[] = array('accid' => 'USGA0366', 'name' => 'Meldrim');
$city_data[] = array('accid' => 'USGA0367', 'name' => 'Menlo');
$city_data[] = array('accid' => 'USGA0368', 'name' => 'Meridian');
$city_data[] = array('accid' => 'USGA0369', 'name' => 'Mershon');
$city_data[] = array('accid' => 'USGA0370', 'name' => 'Mesena');
$city_data[] = array('accid' => 'USGA0371', 'name' => 'Metter');
$city_data[] = array('accid' => 'USGA0372', 'name' => 'Midland');
$city_data[] = array('accid' => 'USGA0373', 'name' => 'Midville');
$city_data[] = array('accid' => 'USGA0374', 'name' => 'Midway');
$city_data[] = array('accid' => 'USGA0375', 'name' => 'Milan');
$city_data[] = array('accid' => 'USGA0376', 'name' => 'Milledgeville');
$city_data[] = array('accid' => 'USGA0377', 'name' => 'Millen');
$city_data[] = array('accid' => 'USGA0378', 'name' => 'Millwood');
$city_data[] = array('accid' => 'USGA0379', 'name' => 'Milner');
$city_data[] = array('accid' => 'USGA0380', 'name' => 'Mineral Bluff');
$city_data[] = array('accid' => 'USGA0381', 'name' => 'Mitchell');
$city_data[] = array('accid' => 'USGA0382', 'name' => 'Molena');
$city_data[] = array('accid' => 'USGA0383', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USGA0384', 'name' => 'Montezuma');
$city_data[] = array('accid' => 'USGA0385', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USGA0386', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USGA0387', 'name' => 'Moreland');
$city_data[] = array('accid' => 'USGA0388', 'name' => 'Morgan');
$city_data[] = array('accid' => 'USGA0389', 'name' => 'Morganton');
$city_data[] = array('accid' => 'USGA0390', 'name' => 'Morris');
$city_data[] = array('accid' => 'USGA0391', 'name' => 'Morrow');
$city_data[] = array('accid' => 'USGA0392', 'name' => 'Morven');
$city_data[] = array('accid' => 'USGA0393', 'name' => 'Moultrie');
$city_data[] = array('accid' => 'USGA0394', 'name' => 'Mount Airy');
$city_data[] = array('accid' => 'USGA0395', 'name' => 'Mount Berry');
$city_data[] = array('accid' => 'USGA0396', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USGA0397', 'name' => 'Mount Zion');
$city_data[] = array('accid' => 'USGA0398', 'name' => 'Mountain City');
$city_data[] = array('accid' => 'USGA0399', 'name' => 'Murrayville');
$city_data[] = array('accid' => 'USGA0400', 'name' => 'Musella');
$city_data[] = array('accid' => 'USGA0401', 'name' => 'Mystic');
$city_data[] = array('accid' => 'USGA0402', 'name' => 'Nahunta');
$city_data[] = array('accid' => 'USGA0403', 'name' => 'Nashville');
$city_data[] = array('accid' => 'USGA0404', 'name' => 'Naylor');
$city_data[] = array('accid' => 'USGA0405', 'name' => 'Nelson');
$city_data[] = array('accid' => 'USGA0406', 'name' => 'Newborn');
$city_data[] = array('accid' => 'USGA0407', 'name' => 'Newington');
$city_data[] = array('accid' => 'USGA0408', 'name' => 'Newnan');
$city_data[] = array('accid' => 'USGA0409', 'name' => 'Newton');
$city_data[] = array('accid' => 'USGA0410', 'name' => 'Nicholls');
$city_data[] = array('accid' => 'USGA0411', 'name' => 'Nicholson');
$city_data[] = array('accid' => 'USGA0412', 'name' => 'Norcross');
$city_data[] = array('accid' => 'USGA0413', 'name' => 'Norman Park');
$city_data[] = array('accid' => 'USGA0414', 'name' => 'Norristown');
$city_data[] = array('accid' => 'USGA0415', 'name' => 'Norwood');
$city_data[] = array('accid' => 'USGA0416', 'name' => 'Nunez');
$city_data[] = array('accid' => 'USGA0417', 'name' => 'Oakfield');
$city_data[] = array('accid' => 'USGA0418', 'name' => 'Oakman');
$city_data[] = array('accid' => 'USGA0419', 'name' => 'Oakwood');
$city_data[] = array('accid' => 'USGA0420', 'name' => 'Ochlocknee');
$city_data[] = array('accid' => 'USGA0421', 'name' => 'Ocilla');
$city_data[] = array('accid' => 'USGA0422', 'name' => 'Oconee');
$city_data[] = array('accid' => 'USGA0423', 'name' => 'Odum');
$city_data[] = array('accid' => 'USGA0424', 'name' => 'Offerman');
$city_data[] = array('accid' => 'USGA0425', 'name' => 'Oglethorpe');
$city_data[] = array('accid' => 'USGA0426', 'name' => 'Oliver');
$city_data[] = array('accid' => 'USGA0427', 'name' => 'Omaha');
$city_data[] = array('accid' => 'USGA0428', 'name' => 'Omega');
$city_data[] = array('accid' => 'USGA0429', 'name' => 'Orchard Hill');
$city_data[] = array('accid' => 'USGA0430', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USGA0431', 'name' => 'Palmetto');
$city_data[] = array('accid' => 'USGA0432', 'name' => 'Parrott');
$city_data[] = array('accid' => 'USGA0433', 'name' => 'Patterson');
$city_data[] = array('accid' => 'USGA0434', 'name' => 'Pavo');
$city_data[] = array('accid' => 'USGA0435', 'name' => 'Peachtree City');
$city_data[] = array('accid' => 'USGA0436', 'name' => 'Pearson');
$city_data[] = array('accid' => 'USGA0437', 'name' => 'Pelham');
$city_data[] = array('accid' => 'USGA0438', 'name' => 'Pembroke');
$city_data[] = array('accid' => 'USGA0439', 'name' => 'Pendergrass');
$city_data[] = array('accid' => 'USGA0440', 'name' => 'Perkins');
$city_data[] = array('accid' => 'USGA0441', 'name' => 'Perry');
$city_data[] = array('accid' => 'USGA0442', 'name' => 'Pine Lake');
$city_data[] = array('accid' => 'USGA0443', 'name' => 'Pine Mountain');
$city_data[] = array('accid' => 'USGA0444', 'name' => 'Pine Mountain Valley');
$city_data[] = array('accid' => 'USGA0445', 'name' => 'Pinehurst');
$city_data[] = array('accid' => 'USGA0446', 'name' => 'Pineview');
$city_data[] = array('accid' => 'USGA0447', 'name' => 'Pitts');
$city_data[] = array('accid' => 'USGA0448', 'name' => 'Plainfield');
$city_data[] = array('accid' => 'USGA0449', 'name' => 'Plains');
$city_data[] = array('accid' => 'USGA0450', 'name' => 'Plainville');
$city_data[] = array('accid' => 'USGA0451', 'name' => 'Pooler');
$city_data[] = array('accid' => 'USGA0452', 'name' => 'Portal');
$city_data[] = array('accid' => 'USGA0453', 'name' => 'Porterdale');
$city_data[] = array('accid' => 'USGA0454', 'name' => 'Poulan');
$city_data[] = array('accid' => 'USGA0455', 'name' => 'Powder Springs');
$city_data[] = array('accid' => 'USGA0456', 'name' => 'Preston');
$city_data[] = array('accid' => 'USGA0457', 'name' => 'Pulaski');
$city_data[] = array('accid' => 'USGA0458', 'name' => 'Putney');
$city_data[] = array('accid' => 'USGA0459', 'name' => 'Quitman');
$city_data[] = array('accid' => 'USGA0460', 'name' => 'Rabun Gap');
$city_data[] = array('accid' => 'USGA0461', 'name' => 'Ranger');
$city_data[] = array('accid' => 'USGA0462', 'name' => 'Ray City');
$city_data[] = array('accid' => 'USGA0463', 'name' => 'Rayle');
$city_data[] = array('accid' => 'USGA0464', 'name' => 'Rebecca');
$city_data[] = array('accid' => 'USGA0465', 'name' => 'Red Oak');
$city_data[] = array('accid' => 'USGA0466', 'name' => 'Redan');
$city_data[] = array('accid' => 'USGA0467', 'name' => 'Register');
$city_data[] = array('accid' => 'USGA0468', 'name' => 'Reidsville');
$city_data[] = array('accid' => 'USGA0469', 'name' => 'Rentz');
$city_data[] = array('accid' => 'USGA0470', 'name' => 'Resaca');
$city_data[] = array('accid' => 'USGA0471', 'name' => 'Rex');
$city_data[] = array('accid' => 'USGA0472', 'name' => 'Reynolds');
$city_data[] = array('accid' => 'USGA0473', 'name' => 'Rhine');
$city_data[] = array('accid' => 'USGA0474', 'name' => 'Riceboro');
$city_data[] = array('accid' => 'USGA0475', 'name' => 'Richland');
$city_data[] = array('accid' => 'USGA0476', 'name' => 'Richmond Hill');
$city_data[] = array('accid' => 'USGA0477', 'name' => 'Rincon');
$city_data[] = array('accid' => 'USGA0478', 'name' => 'Ringgold');
$city_data[] = array('accid' => 'USGA0479', 'name' => 'Rising Fawn');
$city_data[] = array('accid' => 'USGA0480', 'name' => 'Riverdale');
$city_data[] = array('accid' => 'USGA0481', 'name' => 'Roberta');
$city_data[] = array('accid' => 'USGA0482', 'name' => 'Rochelle');
$city_data[] = array('accid' => 'USGA0483', 'name' => 'Rock Spring');
$city_data[] = array('accid' => 'USGA0484', 'name' => 'Rockledge');
$city_data[] = array('accid' => 'USGA0485', 'name' => 'Rockmart');
$city_data[] = array('accid' => 'USGA0486', 'name' => 'Rocky Face');
$city_data[] = array('accid' => 'USGA0487', 'name' => 'Rocky Ford');
$city_data[] = array('accid' => 'USGA0488', 'name' => 'Rome');
$city_data[] = array('accid' => 'USGA0489', 'name' => 'Roopville');
$city_data[] = array('accid' => 'USGA0490', 'name' => 'Rossville');
$city_data[] = array('accid' => 'USGA0491', 'name' => 'Roswell');
$city_data[] = array('accid' => 'USGA0492', 'name' => 'Royston');
$city_data[] = array('accid' => 'USGA0493', 'name' => 'Rupert');
$city_data[] = array('accid' => 'USGA0494', 'name' => 'Rutledge');
$city_data[] = array('accid' => 'USGA0495', 'name' => 'Rydal');
$city_data[] = array('accid' => 'USGA0496', 'name' => 'Saint George');
$city_data[] = array('accid' => 'USGA0497', 'name' => 'Saint Marys');
$city_data[] = array('accid' => 'USGA0498', 'name' => 'Saint Simons Island');
$city_data[] = array('accid' => 'USGA0499', 'name' => 'Sale City');
$city_data[] = array('accid' => 'USGA0500', 'name' => 'Sandersville');
$city_data[] = array('accid' => 'USGA0501', 'name' => 'Sapelo Island');
$city_data[] = array('accid' => 'USGA0502', 'name' => 'Sardis');
$city_data[] = array('accid' => 'USGA0503', 'name' => 'Sargent');
$city_data[] = array('accid' => 'USGA0504', 'name' => 'Sasser');
$city_data[] = array('accid' => 'USGA0505', 'name' => 'Sautee Nacoochee');
$city_data[] = array('accid' => 'USGA0506', 'name' => 'Savannah');
$city_data[] = array('accid' => 'USGA0508', 'name' => 'Scotland');
$city_data[] = array('accid' => 'USGA0509', 'name' => 'Scottdale');
$city_data[] = array('accid' => 'USGA0510', 'name' => 'Screven');
$city_data[] = array('accid' => 'USGA0511', 'name' => 'Sea Island');
$city_data[] = array('accid' => 'USGA0512', 'name' => 'Senoia');
$city_data[] = array('accid' => 'USGA0513', 'name' => 'Seville');
$city_data[] = array('accid' => 'USGA0514', 'name' => 'Shady Dale');
$city_data[] = array('accid' => 'USGA0515', 'name' => 'Shannon');
$city_data[] = array('accid' => 'USGA0516', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USGA0517', 'name' => 'Sharpsburg');
$city_data[] = array('accid' => 'USGA0518', 'name' => 'Shellman');
$city_data[] = array('accid' => 'USGA0519', 'name' => 'Shiloh');
$city_data[] = array('accid' => 'USGA0520', 'name' => 'Siloam');
$city_data[] = array('accid' => 'USGA0521', 'name' => 'Silver Creek');
$city_data[] = array('accid' => 'USGA0523', 'name' => 'Smarr');
$city_data[] = array('accid' => 'USGA0524', 'name' => 'Smithville');
$city_data[] = array('accid' => 'USGA0525', 'name' => 'Smyrna');
$city_data[] = array('accid' => 'USGA0526', 'name' => 'Snellville');
$city_data[] = array('accid' => 'USGA0527', 'name' => 'Social Circle');
$city_data[] = array('accid' => 'USGA0528', 'name' => 'Soperton');
$city_data[] = array('accid' => 'USGA0529', 'name' => 'Sparks');
$city_data[] = array('accid' => 'USGA0530', 'name' => 'Sparta');
$city_data[] = array('accid' => 'USGA0531', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USGA0532', 'name' => 'Stapleton');
$city_data[] = array('accid' => 'USGA0533', 'name' => 'Statenville');
$city_data[] = array('accid' => 'USGA0534', 'name' => 'Statesboro');
$city_data[] = array('accid' => 'USGA0535', 'name' => 'Statham');
$city_data[] = array('accid' => 'USGA0536', 'name' => 'Stephens');
$city_data[] = array('accid' => 'USGA0537', 'name' => 'Stillmore');
$city_data[] = array('accid' => 'USGA0538', 'name' => 'Stockbridge');
$city_data[] = array('accid' => 'USGA0539', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USGA0540', 'name' => 'Stone Mountain');
$city_data[] = array('accid' => 'USGA0541', 'name' => 'Suches');
$city_data[] = array('accid' => 'USGA0542', 'name' => 'Sugar Valley');
$city_data[] = array('accid' => 'USGA0543', 'name' => 'Summertown');
$city_data[] = array('accid' => 'USGA0544', 'name' => 'Summerville');
$city_data[] = array('accid' => 'USGA0545', 'name' => 'Sumner');
$city_data[] = array('accid' => 'USGA0546', 'name' => 'Sunny Side');
$city_data[] = array('accid' => 'USGA0547', 'name' => 'Surrency');
$city_data[] = array('accid' => 'USGA0548', 'name' => 'Suwanee');
$city_data[] = array('accid' => 'USGA0549', 'name' => 'Swainsboro');
$city_data[] = array('accid' => 'USGA0550', 'name' => 'Sycamore');
$city_data[] = array('accid' => 'USGA0551', 'name' => 'Sylvania');
$city_data[] = array('accid' => 'USGA0552', 'name' => 'Sylvester');
$city_data[] = array('accid' => 'USGA0553', 'name' => 'Talbotton');
$city_data[] = array('accid' => 'USGA0554', 'name' => 'Talking Rock');
$city_data[] = array('accid' => 'USGA0555', 'name' => 'Tallapoosa');
$city_data[] = array('accid' => 'USGA0556', 'name' => 'Tallulah Falls');
$city_data[] = array('accid' => 'USGA0557', 'name' => 'Talmo');
$city_data[] = array('accid' => 'USGA0558', 'name' => 'Tarrytown');
$city_data[] = array('accid' => 'USGA0559', 'name' => 'Tate');
$city_data[] = array('accid' => 'USGA0560', 'name' => 'Taylorsville');
$city_data[] = array('accid' => 'USGA0561', 'name' => 'Temple');
$city_data[] = array('accid' => 'USGA0562', 'name' => 'Tennga');
$city_data[] = array('accid' => 'USGA0563', 'name' => 'Tennille');
$city_data[] = array('accid' => 'USGA0564', 'name' => 'The Rock');
$city_data[] = array('accid' => 'USGA0565', 'name' => 'Thomaston');
$city_data[] = array('accid' => 'USGA0566', 'name' => 'Thomasville');
$city_data[] = array('accid' => 'USGA0567', 'name' => 'Thomson');
$city_data[] = array('accid' => 'USGA0568', 'name' => 'Tifton');
$city_data[] = array('accid' => 'USGA0569', 'name' => 'Tiger');
$city_data[] = array('accid' => 'USGA0570', 'name' => 'Tignall');
$city_data[] = array('accid' => 'USGA0571', 'name' => 'Toccoa');
$city_data[] = array('accid' => 'USGA0572', 'name' => 'Toomsboro');
$city_data[] = array('accid' => 'USGA0573', 'name' => 'Townsend');
$city_data[] = array('accid' => 'USGA0574', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USGA0575', 'name' => 'Trion');
$city_data[] = array('accid' => 'USGA0576', 'name' => 'Tucker');
$city_data[] = array('accid' => 'USGA0577', 'name' => 'Tunnel Hill');
$city_data[] = array('accid' => 'USGA0578', 'name' => 'Turin');
$city_data[] = array('accid' => 'USGA0579', 'name' => 'Turnerville');
$city_data[] = array('accid' => 'USGA0580', 'name' => 'Twin City');
$city_data[] = array('accid' => 'USGA0581', 'name' => 'Ty Ty');
$city_data[] = array('accid' => 'USGA0582', 'name' => 'Tybee Island');
$city_data[] = array('accid' => 'USGA0583', 'name' => 'Tyrone');
$city_data[] = array('accid' => 'USGA0584', 'name' => 'Unadilla');
$city_data[] = array('accid' => 'USGA0585', 'name' => 'Union City');
$city_data[] = array('accid' => 'USGA0586', 'name' => 'Union Point');
$city_data[] = array('accid' => 'USGA0587', 'name' => 'Upatoi');
$city_data[] = array('accid' => 'USGA0588', 'name' => 'Uvalda');
$city_data[] = array('accid' => 'USGA0589', 'name' => 'Valdosta');
$city_data[] = array('accid' => 'USGA0591', 'name' => 'Valona');
$city_data[] = array('accid' => 'USGA0592', 'name' => 'Varnell');
$city_data[] = array('accid' => 'USGA0593', 'name' => 'Vidalia');
$city_data[] = array('accid' => 'USGA0594', 'name' => 'Vienna');
$city_data[] = array('accid' => 'USGA0595', 'name' => 'Villa Rica');
$city_data[] = array('accid' => 'USGA0596', 'name' => 'Waco');
$city_data[] = array('accid' => 'USGA0597', 'name' => 'Wadley');
$city_data[] = array('accid' => 'USGA0598', 'name' => 'Waleska');
$city_data[] = array('accid' => 'USGA0599', 'name' => 'Walthourville');
$city_data[] = array('accid' => 'USGA0600', 'name' => 'Waresboro');
$city_data[] = array('accid' => 'USGA0601', 'name' => 'Warm Springs');
$city_data[] = array('accid' => 'USGA0602', 'name' => 'Warner Robins');
$city_data[] = array('accid' => 'USGA0603', 'name' => 'Warrenton');
$city_data[] = array('accid' => 'USGA0604', 'name' => 'Warthen');
$city_data[] = array('accid' => 'USGA0605', 'name' => 'Warwick');
$city_data[] = array('accid' => 'USGA0606', 'name' => 'Washington');
$city_data[] = array('accid' => 'USGA0607', 'name' => 'Watkinsville');
$city_data[] = array('accid' => 'USGA0608', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USGA0609', 'name' => 'Waverly Hall');
$city_data[] = array('accid' => 'USGA0610', 'name' => 'Waycross');
$city_data[] = array('accid' => 'USGA0611', 'name' => 'Waynesboro');
$city_data[] = array('accid' => 'USGA0612', 'name' => 'Waynesville');
$city_data[] = array('accid' => 'USGA0613', 'name' => 'West Green');
$city_data[] = array('accid' => 'USGA0614', 'name' => 'West Point');
$city_data[] = array('accid' => 'USGA0615', 'name' => 'Weston');
$city_data[] = array('accid' => 'USGA0616', 'name' => 'Whigham');
$city_data[] = array('accid' => 'USGA0617', 'name' => 'White');
$city_data[] = array('accid' => 'USGA0618', 'name' => 'White Oak');
$city_data[] = array('accid' => 'USGA0619', 'name' => 'White Plains');
$city_data[] = array('accid' => 'USGA0620', 'name' => 'Whitesburg');
$city_data[] = array('accid' => 'USGA0621', 'name' => 'Wildwood');
$city_data[] = array('accid' => 'USGA0622', 'name' => 'Wiley');
$city_data[] = array('accid' => 'USGA0623', 'name' => 'Willacoochee');
$city_data[] = array('accid' => 'USGA0624', 'name' => 'Williamson');
$city_data[] = array('accid' => 'USGA0625', 'name' => 'Winder');
$city_data[] = array('accid' => 'USGA0626', 'name' => 'Winston');
$city_data[] = array('accid' => 'USGA0627', 'name' => 'Winterville');
$city_data[] = array('accid' => 'USGA0628', 'name' => 'Woodbine');
$city_data[] = array('accid' => 'USGA0629', 'name' => 'Woodbury');
$city_data[] = array('accid' => 'USGA0630', 'name' => 'Woodland');
$city_data[] = array('accid' => 'USGA0631', 'name' => 'Woodstock');
$city_data[] = array('accid' => 'USGA0632', 'name' => 'Wray');
$city_data[] = array('accid' => 'USGA0633', 'name' => 'Wrens');
$city_data[] = array('accid' => 'USGA0634', 'name' => 'Wrightsville');
$city_data[] = array('accid' => 'USGA0635', 'name' => 'Yatesville');
$city_data[] = array('accid' => 'USGA0636', 'name' => 'Young Harris');
$city_data[] = array('accid' => 'USGA0637', 'name' => 'Zebulon');

?>
