<?php

// City package for USA: Hawaii 

$city_name = 'USA: Hawaii';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USHI0001', 'name' => 'Aiea');
$city_data[] = array('accid' => 'USHI0002', 'name' => 'Anahola');
$city_data[] = array('accid' => 'USHI0004', 'name' => 'Camp H M Smith');
$city_data[] = array('accid' => 'USHI0006', 'name' => 'Captain Cook');
$city_data[] = array('accid' => 'USHI0007', 'name' => 'Eleele');
$city_data[] = array('accid' => 'USHI0009', 'name' => 'Ewa Beach');
$city_data[] = array('accid' => 'USHI0010', 'name' => 'Fort Shafter');
$city_data[] = array('accid' => 'USHI0011', 'name' => 'Haiku');
$city_data[] = array('accid' => 'USHI0012', 'name' => 'Hakalau');
$city_data[] = array('accid' => 'USHI0013', 'name' => 'Haleiwa');
$city_data[] = array('accid' => 'USHI0014', 'name' => 'Hana');
$city_data[] = array('accid' => 'USHI0015', 'name' => 'Hanalei');
$city_data[] = array('accid' => 'USHI0016', 'name' => 'Hanamaulu');
$city_data[] = array('accid' => 'USHI0017', 'name' => 'Hanapepe');
$city_data[] = array('accid' => 'USHI0018', 'name' => 'Hauula');
$city_data[] = array('accid' => 'USHI0019', 'name' => 'Hawaii Natl Park');
$city_data[] = array('accid' => 'USHI0020', 'name' => 'Hawi');
$city_data[] = array('accid' => 'USHI0021', 'name' => 'Hickam AFB');
$city_data[] = array('accid' => 'USHI0022', 'name' => 'Hilo');
$city_data[] = array('accid' => 'USHI0023', 'name' => 'Holualoa');
$city_data[] = array('accid' => 'USHI0024', 'name' => 'Honaunau');
$city_data[] = array('accid' => 'USHI0025', 'name' => 'Honokaa');
$city_data[] = array('accid' => 'USHI0026', 'name' => 'Honolulu');
$city_data[] = array('accid' => 'USHI0027', 'name' => 'Honomu');
$city_data[] = array('accid' => 'USHI0028', 'name' => 'Hoolehua');
$city_data[] = array('accid' => 'USHI0029', 'name' => 'Kaaawa');
$city_data[] = array('accid' => 'USHI0030', 'name' => 'Kahuku');
$city_data[] = array('accid' => 'USHI0031', 'name' => 'Kahului');
$city_data[] = array('accid' => 'USHI0032', 'name' => 'Kailua');
$city_data[] = array('accid' => 'USHI0034', 'name' => 'Kalaheo');
$city_data[] = array('accid' => 'USHI0035', 'name' => 'Kalaupapa');
$city_data[] = array('accid' => 'USHI0036', 'name' => 'Kamuela');
$city_data[] = array('accid' => 'USHI0037', 'name' => 'Kaneohe');
$city_data[] = array('accid' => 'USHI0038', 'name' => 'Kapaa');
$city_data[] = array('accid' => 'USHI0039', 'name' => 'Kapaau');
$city_data[] = array('accid' => 'USHI0040', 'name' => 'Kapolei');
$city_data[] = array('accid' => 'USHI0041', 'name' => 'Kaumakani');
$city_data[] = array('accid' => 'USHI0042', 'name' => 'Kaunakakai');
$city_data[] = array('accid' => 'USHI0043', 'name' => 'Keaau');
$city_data[] = array('accid' => 'USHI0044', 'name' => 'Kealakekua');
$city_data[] = array('accid' => 'USHI0045', 'name' => 'Kealia');
$city_data[] = array('accid' => 'USHI0046', 'name' => 'Keauhou');
$city_data[] = array('accid' => 'USHI0047', 'name' => 'Kekaha');
$city_data[] = array('accid' => 'USHI0048', 'name' => 'Kihei');
$city_data[] = array('accid' => 'USHI0049', 'name' => 'Kilauea');
$city_data[] = array('accid' => 'USHI0050', 'name' => 'Koloa');
$city_data[] = array('accid' => 'USHI0051', 'name' => 'Kualapuu');
$city_data[] = array('accid' => 'USHI0052', 'name' => 'Kula');
$city_data[] = array('accid' => 'USHI0053', 'name' => 'Kunia');
$city_data[] = array('accid' => 'USHI0054', 'name' => 'Kurtistown');
$city_data[] = array('accid' => 'USHI0055', 'name' => 'Lahaina');
$city_data[] = array('accid' => 'USHI0056', 'name' => 'Laie');
$city_data[] = array('accid' => 'USHI0057', 'name' => 'Lanai City');
$city_data[] = array('accid' => 'USHI0058', 'name' => 'Laupahoehoe');
$city_data[] = array('accid' => 'USHI0059', 'name' => 'Lawai');
$city_data[] = array('accid' => 'USHI0060', 'name' => 'Lihue');
$city_data[] = array('accid' => 'USHI0061', 'name' => 'Makawao');
$city_data[] = array('accid' => 'USHI0063', 'name' => 'Maunaloa');
$city_data[] = array('accid' => 'USHI0065', 'name' => 'Mililani');
$city_data[] = array('accid' => 'USHI0066', 'name' => 'Mountain View');
$city_data[] = array('accid' => 'USHI0067', 'name' => 'Naalehu');
$city_data[] = array('accid' => 'USHI0068', 'name' => 'Ninole');
$city_data[] = array('accid' => 'USHI0069', 'name' => 'Ocean View');
$city_data[] = array('accid' => 'USHI0070', 'name' => 'Ookala');
$city_data[] = array('accid' => 'USHI0071', 'name' => 'Paauhau');
$city_data[] = array('accid' => 'USHI0072', 'name' => 'Paauilo');
$city_data[] = array('accid' => 'USHI0073', 'name' => 'Pahala');
$city_data[] = array('accid' => 'USHI0074', 'name' => 'Pahoa');
$city_data[] = array('accid' => 'USHI0075', 'name' => 'Paia');
$city_data[] = array('accid' => 'USHI0076', 'name' => 'Papaaloa');
$city_data[] = array('accid' => 'USHI0077', 'name' => 'Papaikou');
$city_data[] = array('accid' => 'USHI0078', 'name' => 'Pearl City');
$city_data[] = array('accid' => 'USHI0079', 'name' => 'Pearl Harbor');
$city_data[] = array('accid' => 'USHI0080', 'name' => 'Pepeekeo');
$city_data[] = array('accid' => 'USHI0081', 'name' => 'Princeville');
$city_data[] = array('accid' => 'USHI0082', 'name' => 'Pukalani');
$city_data[] = array('accid' => 'USHI0083', 'name' => 'Puunene');
$city_data[] = array('accid' => 'USHI0084', 'name' => 'Schofield Barracks');
$city_data[] = array('accid' => 'USHI0086', 'name' => 'Volcano');
$city_data[] = array('accid' => 'USHI0087', 'name' => 'Wahiawa');
$city_data[] = array('accid' => 'USHI0088', 'name' => 'Waialua');
$city_data[] = array('accid' => 'USHI0089', 'name' => 'Waianae');
$city_data[] = array('accid' => 'USHI0090', 'name' => 'Waikoloa');
$city_data[] = array('accid' => 'USHI0091', 'name' => 'Wailuku');
$city_data[] = array('accid' => 'USHI0092', 'name' => 'Waimanalo');
$city_data[] = array('accid' => 'USHI0093', 'name' => 'Waimea');
$city_data[] = array('accid' => 'USHI0094', 'name' => 'Waipahu');
$city_data[] = array('accid' => 'USHI0096', 'name' => 'Wheeler AAF');

?>
