<?php

// City package for USA: Iowa 

$city_name = 'USA: Iowa';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USIA0001', 'name' => 'Ackley');
$city_data[] = array('accid' => 'USIA0002', 'name' => 'Ackworth');
$city_data[] = array('accid' => 'USIA0003', 'name' => 'Adair');
$city_data[] = array('accid' => 'USIA0004', 'name' => 'Adel');
$city_data[] = array('accid' => 'USIA0005', 'name' => 'Afton');
$city_data[] = array('accid' => 'USIA0006', 'name' => 'Agency');
$city_data[] = array('accid' => 'USIA0007', 'name' => 'Ainsworth');
$city_data[] = array('accid' => 'USIA0008', 'name' => 'Akron');
$city_data[] = array('accid' => 'USIA0009', 'name' => 'Albert City');
$city_data[] = array('accid' => 'USIA0010', 'name' => 'Albia');
$city_data[] = array('accid' => 'USIA0011', 'name' => 'Albion');
$city_data[] = array('accid' => 'USIA0012', 'name' => 'Alburnett');
$city_data[] = array('accid' => 'USIA0013', 'name' => 'Alden');
$city_data[] = array('accid' => 'USIA0014', 'name' => 'Alexander');
$city_data[] = array('accid' => 'USIA0015', 'name' => 'Algona');
$city_data[] = array('accid' => 'USIA0016', 'name' => 'Alleman');
$city_data[] = array('accid' => 'USIA0017', 'name' => 'Allendorf');
$city_data[] = array('accid' => 'USIA0018', 'name' => 'Allerton');
$city_data[] = array('accid' => 'USIA0019', 'name' => 'Allison');
$city_data[] = array('accid' => 'USIA0020', 'name' => 'Alta');
$city_data[] = array('accid' => 'USIA0021', 'name' => 'Alta Vista');
$city_data[] = array('accid' => 'USIA0022', 'name' => 'Alton');
$city_data[] = array('accid' => 'USIA0023', 'name' => 'Altoona');
$city_data[] = array('accid' => 'USIA0024', 'name' => 'Alvord');
$city_data[] = array('accid' => 'USIA0025', 'name' => 'Amana');
$city_data[] = array('accid' => 'USIA0026', 'name' => 'Ames');
$city_data[] = array('accid' => 'USIA0027', 'name' => 'Anamosa');
$city_data[] = array('accid' => 'USIA0028', 'name' => 'Andover');
$city_data[] = array('accid' => 'USIA0029', 'name' => 'Andrew');
$city_data[] = array('accid' => 'USIA0030', 'name' => 'Anita');
$city_data[] = array('accid' => 'USIA0031', 'name' => 'Ankeny');
$city_data[] = array('accid' => 'USIA0032', 'name' => 'Anthon');
$city_data[] = array('accid' => 'USIA0033', 'name' => 'Aplington');
$city_data[] = array('accid' => 'USIA0034', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USIA0035', 'name' => 'Archer');
$city_data[] = array('accid' => 'USIA0036', 'name' => 'Aredale');
$city_data[] = array('accid' => 'USIA0037', 'name' => 'Argyle');
$city_data[] = array('accid' => 'USIA0038', 'name' => 'Arion');
$city_data[] = array('accid' => 'USIA0039', 'name' => 'Arispe');
$city_data[] = array('accid' => 'USIA0040', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USIA0041', 'name' => 'Armstrong');
$city_data[] = array('accid' => 'USIA0042', 'name' => 'Arnolds Park');
$city_data[] = array('accid' => 'USIA0043', 'name' => 'Arthur');
$city_data[] = array('accid' => 'USIA0044', 'name' => 'Ashton');
$city_data[] = array('accid' => 'USIA0045', 'name' => 'Aspinwall');
$city_data[] = array('accid' => 'USIA0046', 'name' => 'Atalissa');
$city_data[] = array('accid' => 'USIA0047', 'name' => 'Atkins');
$city_data[] = array('accid' => 'USIA0048', 'name' => 'Atlantic');
$city_data[] = array('accid' => 'USIA0049', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USIA0050', 'name' => 'Audubon');
$city_data[] = array('accid' => 'USIA0051', 'name' => 'Aurelia');
$city_data[] = array('accid' => 'USIA0052', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USIA0053', 'name' => 'Austinville');
$city_data[] = array('accid' => 'USIA0054', 'name' => 'Avoca');
$city_data[] = array('accid' => 'USIA0055', 'name' => 'Ayrshire');
$city_data[] = array('accid' => 'USIA0056', 'name' => 'Badger');
$city_data[] = array('accid' => 'USIA0057', 'name' => 'Bagley');
$city_data[] = array('accid' => 'USIA0058', 'name' => 'Baldwin');
$city_data[] = array('accid' => 'USIA0059', 'name' => 'Bancroft');
$city_data[] = array('accid' => 'USIA0060', 'name' => 'Barnes City');
$city_data[] = array('accid' => 'USIA0061', 'name' => 'Barnum');
$city_data[] = array('accid' => 'USIA0062', 'name' => 'Batavia');
$city_data[] = array('accid' => 'USIA0063', 'name' => 'Battle Creek');
$city_data[] = array('accid' => 'USIA0064', 'name' => 'Baxter');
$city_data[] = array('accid' => 'USIA0065', 'name' => 'Bayard');
$city_data[] = array('accid' => 'USIA0066', 'name' => 'Beacon');
$city_data[] = array('accid' => 'USIA0067', 'name' => 'Beaman');
$city_data[] = array('accid' => 'USIA0068', 'name' => 'Beaver');
$city_data[] = array('accid' => 'USIA0069', 'name' => 'Bedford');
$city_data[] = array('accid' => 'USIA0070', 'name' => 'Belle Plaine');
$city_data[] = array('accid' => 'USIA0071', 'name' => 'Bellevue');
$city_data[] = array('accid' => 'USIA0072', 'name' => 'Belmond');
$city_data[] = array('accid' => 'USIA0073', 'name' => 'Bennett');
$city_data[] = array('accid' => 'USIA0074', 'name' => 'Benton');
$city_data[] = array('accid' => 'USIA0075', 'name' => 'Bernard');
$city_data[] = array('accid' => 'USIA0076', 'name' => 'Berwick');
$city_data[] = array('accid' => 'USIA0077', 'name' => 'Bettendorf');
$city_data[] = array('accid' => 'USIA0078', 'name' => 'Bevington');
$city_data[] = array('accid' => 'USIA0079', 'name' => 'Birmingham');
$city_data[] = array('accid' => 'USIA0080', 'name' => 'Blairsburg');
$city_data[] = array('accid' => 'USIA0081', 'name' => 'Blairstown');
$city_data[] = array('accid' => 'USIA0082', 'name' => 'Blakesburg');
$city_data[] = array('accid' => 'USIA0083', 'name' => 'Blanchard');
$city_data[] = array('accid' => 'USIA0084', 'name' => 'Blencoe');
$city_data[] = array('accid' => 'USIA0085', 'name' => 'Blockton');
$city_data[] = array('accid' => 'USIA0086', 'name' => 'Bloomfield');
$city_data[] = array('accid' => 'USIA0087', 'name' => 'Blue Grass');
$city_data[] = array('accid' => 'USIA0088', 'name' => 'Bode');
$city_data[] = array('accid' => 'USIA0089', 'name' => 'Bonaparte');
$city_data[] = array('accid' => 'USIA0090', 'name' => 'Bondurant');
$city_data[] = array('accid' => 'USIA0091', 'name' => 'Boone');
$city_data[] = array('accid' => 'USIA0092', 'name' => 'Booneville');
$city_data[] = array('accid' => 'USIA0093', 'name' => 'Bouton');
$city_data[] = array('accid' => 'USIA0094', 'name' => 'Boxholm');
$city_data[] = array('accid' => 'USIA0095', 'name' => 'Boyden');
$city_data[] = array('accid' => 'USIA0096', 'name' => 'Braddyville');
$city_data[] = array('accid' => 'USIA0097', 'name' => 'Bradford');
$city_data[] = array('accid' => 'USIA0098', 'name' => 'Bradgate');
$city_data[] = array('accid' => 'USIA0099', 'name' => 'Brandon');
$city_data[] = array('accid' => 'USIA0100', 'name' => 'Brayton');
$city_data[] = array('accid' => 'USIA0101', 'name' => 'Breda');
$city_data[] = array('accid' => 'USIA0102', 'name' => 'Bridgewater');
$city_data[] = array('accid' => 'USIA0103', 'name' => 'Brighton');
$city_data[] = array('accid' => 'USIA0104', 'name' => 'Bristow');
$city_data[] = array('accid' => 'USIA0105', 'name' => 'Britt');
$city_data[] = array('accid' => 'USIA0106', 'name' => 'Bronson');
$city_data[] = array('accid' => 'USIA0107', 'name' => 'Brooklyn');
$city_data[] = array('accid' => 'USIA0108', 'name' => 'Brunsville');
$city_data[] = array('accid' => 'USIA0109', 'name' => 'Bryant');
$city_data[] = array('accid' => 'USIA0110', 'name' => 'Buckeye');
$city_data[] = array('accid' => 'USIA0111', 'name' => 'Buckingham');
$city_data[] = array('accid' => 'USIA0112', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USIA0113', 'name' => 'Buffalo Center');
$city_data[] = array('accid' => 'USIA0114', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USIA0115', 'name' => 'Burnside');
$city_data[] = array('accid' => 'USIA0116', 'name' => 'Burr Oak');
$city_data[] = array('accid' => 'USIA0117', 'name' => 'Burt');
$city_data[] = array('accid' => 'USIA0118', 'name' => 'Bussey');
$city_data[] = array('accid' => 'USIA0119', 'name' => 'Calamus');
$city_data[] = array('accid' => 'USIA0120', 'name' => 'Callender');
$city_data[] = array('accid' => 'USIA0121', 'name' => 'Calmar');
$city_data[] = array('accid' => 'USIA0122', 'name' => 'Calumet');
$city_data[] = array('accid' => 'USIA0123', 'name' => 'Camanche');
$city_data[] = array('accid' => 'USIA0124', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'USIA0125', 'name' => 'Cantril');
$city_data[] = array('accid' => 'USIA0126', 'name' => 'Carbon');
$city_data[] = array('accid' => 'USIA0127', 'name' => 'Carlisle');
$city_data[] = array('accid' => 'USIA0128', 'name' => 'Carpenter');
$city_data[] = array('accid' => 'USIA0129', 'name' => 'Carroll');
$city_data[] = array('accid' => 'USIA0130', 'name' => 'Carson');
$city_data[] = array('accid' => 'USIA0131', 'name' => 'Carter Lake');
$city_data[] = array('accid' => 'USIA0132', 'name' => 'Cascade');
$city_data[] = array('accid' => 'USIA0133', 'name' => 'Casey');
$city_data[] = array('accid' => 'USIA0134', 'name' => 'Castalia');
$city_data[] = array('accid' => 'USIA0135', 'name' => 'Castana');
$city_data[] = array('accid' => 'USIA0136', 'name' => 'Cedar');
$city_data[] = array('accid' => 'USIA0137', 'name' => 'Cedar Falls');
$city_data[] = array('accid' => 'USIA0138', 'name' => 'Cedar Rapids');
$city_data[] = array('accid' => 'USIA0139', 'name' => 'Center Junction');
$city_data[] = array('accid' => 'USIA0140', 'name' => 'Center Point');
$city_data[] = array('accid' => 'USIA0141', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USIA0142', 'name' => 'Central City');
$city_data[] = array('accid' => 'USIA0143', 'name' => 'Chapin');
$city_data[] = array('accid' => 'USIA0144', 'name' => 'Chariton');
$city_data[] = array('accid' => 'USIA0145', 'name' => 'Charles City');
$city_data[] = array('accid' => 'USIA0146', 'name' => 'Charlotte');
$city_data[] = array('accid' => 'USIA0147', 'name' => 'Charter Oak');
$city_data[] = array('accid' => 'USIA0148', 'name' => 'Chatsworth');
$city_data[] = array('accid' => 'USIA0149', 'name' => 'Chelsea');
$city_data[] = array('accid' => 'USIA0150', 'name' => 'Cherokee');
$city_data[] = array('accid' => 'USIA0151', 'name' => 'Chester');
$city_data[] = array('accid' => 'USIA0152', 'name' => 'Chillicothe');
$city_data[] = array('accid' => 'USIA0153', 'name' => 'Churdan');
$city_data[] = array('accid' => 'USIA0154', 'name' => 'Cincinnati');
$city_data[] = array('accid' => 'USIA0155', 'name' => 'Clare');
$city_data[] = array('accid' => 'USIA0156', 'name' => 'Clarence');
$city_data[] = array('accid' => 'USIA0157', 'name' => 'Clarinda');
$city_data[] = array('accid' => 'USIA0158', 'name' => 'Clarion');
$city_data[] = array('accid' => 'USIA0159', 'name' => 'Clarksville');
$city_data[] = array('accid' => 'USIA0160', 'name' => 'Clear Lake');
$city_data[] = array('accid' => 'USIA0161', 'name' => 'Clearfield');
$city_data[] = array('accid' => 'USIA0162', 'name' => 'Cleghorn');
$city_data[] = array('accid' => 'USIA0163', 'name' => 'Clemons');
$city_data[] = array('accid' => 'USIA0164', 'name' => 'Clermont');
$city_data[] = array('accid' => 'USIA0165', 'name' => 'Climbing Hill');
$city_data[] = array('accid' => 'USIA0166', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USIA0167', 'name' => 'Clio');
$city_data[] = array('accid' => 'USIA0168', 'name' => 'Clive');
$city_data[] = array('accid' => 'USIA0169', 'name' => 'Clutier');
$city_data[] = array('accid' => 'USIA0170', 'name' => 'Coggon');
$city_data[] = array('accid' => 'USIA0171', 'name' => 'Coin');
$city_data[] = array('accid' => 'USIA0172', 'name' => 'Colesburg');
$city_data[] = array('accid' => 'USIA0173', 'name' => 'Colfax');
$city_data[] = array('accid' => 'USIA0174', 'name' => 'College Springs');
$city_data[] = array('accid' => 'USIA0175', 'name' => 'Collins');
$city_data[] = array('accid' => 'USIA0176', 'name' => 'Colo');
$city_data[] = array('accid' => 'USIA0177', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USIA0178', 'name' => 'Columbus City');
$city_data[] = array('accid' => 'USIA0179', 'name' => 'Columbus Junction');
$city_data[] = array('accid' => 'USIA0180', 'name' => 'Colwell');
$city_data[] = array('accid' => 'USIA0181', 'name' => 'Conesville');
$city_data[] = array('accid' => 'USIA0182', 'name' => 'Conrad');
$city_data[] = array('accid' => 'USIA0183', 'name' => 'Conroy');
$city_data[] = array('accid' => 'USIA0184', 'name' => 'Coon Rapids');
$city_data[] = array('accid' => 'USIA0185', 'name' => 'Cooper');
$city_data[] = array('accid' => 'USIA0186', 'name' => 'Coralville');
$city_data[] = array('accid' => 'USIA0187', 'name' => 'Corning');
$city_data[] = array('accid' => 'USIA0188', 'name' => 'Correctionville');
$city_data[] = array('accid' => 'USIA0189', 'name' => 'Corwith');
$city_data[] = array('accid' => 'USIA0190', 'name' => 'Corydon');
$city_data[] = array('accid' => 'USIA0191', 'name' => 'Coulter');
$city_data[] = array('accid' => 'USIA0192', 'name' => 'Council Bluffs');
$city_data[] = array('accid' => 'USIA0193', 'name' => 'Craig');
$city_data[] = array('accid' => 'USIA0194', 'name' => 'Crawfordsville');
$city_data[] = array('accid' => 'USIA0195', 'name' => 'Crescent');
$city_data[] = array('accid' => 'USIA0196', 'name' => 'Cresco');
$city_data[] = array('accid' => 'USIA0197', 'name' => 'Creston');
$city_data[] = array('accid' => 'USIA0198', 'name' => 'Cromwell');
$city_data[] = array('accid' => 'USIA0199', 'name' => 'Crystal Lake');
$city_data[] = array('accid' => 'USIA0200', 'name' => 'Cumberland');
$city_data[] = array('accid' => 'USIA0201', 'name' => 'Cumming');
$city_data[] = array('accid' => 'USIA0202', 'name' => 'Curlew');
$city_data[] = array('accid' => 'USIA0203', 'name' => 'Cushing');
$city_data[] = array('accid' => 'USIA0204', 'name' => 'Cylinder');
$city_data[] = array('accid' => 'USIA0205', 'name' => 'Dakota City');
$city_data[] = array('accid' => 'USIA0206', 'name' => 'Dallas');
$city_data[] = array('accid' => 'USIA0207', 'name' => 'Dallas Center');
$city_data[] = array('accid' => 'USIA0208', 'name' => 'Dana');
$city_data[] = array('accid' => 'USIA0209', 'name' => 'Danbury');
$city_data[] = array('accid' => 'USIA0210', 'name' => 'Danville');
$city_data[] = array('accid' => 'USIA0211', 'name' => 'Davenport');
$city_data[] = array('accid' => 'USIA0212', 'name' => 'Davis City');
$city_data[] = array('accid' => 'USIA0213', 'name' => 'Dawson');
$city_data[] = array('accid' => 'USIA0214', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USIA0215', 'name' => 'De Soto');
$city_data[] = array('accid' => 'USIA0216', 'name' => 'De Witt');
$city_data[] = array('accid' => 'USIA0217', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USIA0218', 'name' => 'Decorah');
$city_data[] = array('accid' => 'USIA0219', 'name' => 'Dedham');
$city_data[] = array('accid' => 'USIA0220', 'name' => 'Deep River');
$city_data[] = array('accid' => 'USIA0221', 'name' => 'Defiance');
$city_data[] = array('accid' => 'USIA0222', 'name' => 'Delaware');
$city_data[] = array('accid' => 'USIA0223', 'name' => 'Delhi');
$city_data[] = array('accid' => 'USIA0224', 'name' => 'Delmar');
$city_data[] = array('accid' => 'USIA0225', 'name' => 'Deloit');
$city_data[] = array('accid' => 'USIA0226', 'name' => 'Delta');
$city_data[] = array('accid' => 'USIA0227', 'name' => 'Denison');
$city_data[] = array('accid' => 'USIA0228', 'name' => 'Denmark');
$city_data[] = array('accid' => 'USIA0229', 'name' => 'Denver');
$city_data[] = array('accid' => 'USIA0230', 'name' => 'Derby');
$city_data[] = array('accid' => 'USIA0231', 'name' => 'Des Moines');
$city_data[] = array('accid' => 'USIA0232', 'name' => 'Dewar');
$city_data[] = array('accid' => 'USIA0233', 'name' => 'Dexter');
$city_data[] = array('accid' => 'USIA0234', 'name' => 'Diagonal');
$city_data[] = array('accid' => 'USIA0235', 'name' => 'Dickens');
$city_data[] = array('accid' => 'USIA0236', 'name' => 'Dike');
$city_data[] = array('accid' => 'USIA0237', 'name' => 'Dixon');
$city_data[] = array('accid' => 'USIA0238', 'name' => 'Dolliver');
$city_data[] = array('accid' => 'USIA0239', 'name' => 'Donahue');
$city_data[] = array('accid' => 'USIA0240', 'name' => 'Donnellson');
$city_data[] = array('accid' => 'USIA0241', 'name' => 'Doon');
$city_data[] = array('accid' => 'USIA0242', 'name' => 'Dorchester');
$city_data[] = array('accid' => 'USIA0243', 'name' => 'Douds');
$city_data[] = array('accid' => 'USIA0244', 'name' => 'Dougherty');
$city_data[] = array('accid' => 'USIA0245', 'name' => 'Dow City');
$city_data[] = array('accid' => 'USIA0246', 'name' => 'Dows');
$city_data[] = array('accid' => 'USIA0247', 'name' => 'Drakesville');
$city_data[] = array('accid' => 'USIA0248', 'name' => 'Dubuque');
$city_data[] = array('accid' => 'USIA0249', 'name' => 'Dumont');
$city_data[] = array('accid' => 'USIA0250', 'name' => 'Duncombe');
$city_data[] = array('accid' => 'USIA0251', 'name' => 'Dundee');
$city_data[] = array('accid' => 'USIA0252', 'name' => 'Dunkerton');
$city_data[] = array('accid' => 'USIA0253', 'name' => 'Dunlap');
$city_data[] = array('accid' => 'USIA0254', 'name' => 'Durango');
$city_data[] = array('accid' => 'USIA0255', 'name' => 'Durant');
$city_data[] = array('accid' => 'USIA0256', 'name' => 'Dyersville');
$city_data[] = array('accid' => 'USIA0257', 'name' => 'Dysart');
$city_data[] = array('accid' => 'USIA0258', 'name' => 'Eagle Grove');
$city_data[] = array('accid' => 'USIA0259', 'name' => 'Earlham');
$city_data[] = array('accid' => 'USIA0260', 'name' => 'Earling');
$city_data[] = array('accid' => 'USIA0261', 'name' => 'Earlville');
$city_data[] = array('accid' => 'USIA0262', 'name' => 'Early');
$city_data[] = array('accid' => 'USIA0263', 'name' => 'Eddyville');
$city_data[] = array('accid' => 'USIA0264', 'name' => 'Edgewood');
$city_data[] = array('accid' => 'USIA0265', 'name' => 'Elberon');
$city_data[] = array('accid' => 'USIA0266', 'name' => 'Eldon');
$city_data[] = array('accid' => 'USIA0267', 'name' => 'Eldora');
$city_data[] = array('accid' => 'USIA0268', 'name' => 'Eldridge');
$city_data[] = array('accid' => 'USIA0269', 'name' => 'Elgin');
$city_data[] = array('accid' => 'USIA0270', 'name' => 'Elk Horn');
$city_data[] = array('accid' => 'USIA0271', 'name' => 'Elkader');
$city_data[] = array('accid' => 'USIA0272', 'name' => 'Elkhart');
$city_data[] = array('accid' => 'USIA0273', 'name' => 'Elkport');
$city_data[] = array('accid' => 'USIA0274', 'name' => 'Elliott');
$city_data[] = array('accid' => 'USIA0275', 'name' => 'Ellston');
$city_data[] = array('accid' => 'USIA0276', 'name' => 'Ellsworth');
$city_data[] = array('accid' => 'USIA0277', 'name' => 'Elma');
$city_data[] = array('accid' => 'USIA0278', 'name' => 'Elwood');
$city_data[] = array('accid' => 'USIA0279', 'name' => 'Ely');
$city_data[] = array('accid' => 'USIA0280', 'name' => 'Emerson');
$city_data[] = array('accid' => 'USIA0281', 'name' => 'Emmetsburg');
$city_data[] = array('accid' => 'USIA0282', 'name' => 'Epworth');
$city_data[] = array('accid' => 'USIA0283', 'name' => 'Essex');
$city_data[] = array('accid' => 'USIA0284', 'name' => 'Estherville');
$city_data[] = array('accid' => 'USIA0285', 'name' => 'Evansdale');
$city_data[] = array('accid' => 'USIA0286', 'name' => 'Everly');
$city_data[] = array('accid' => 'USIA0287', 'name' => 'Exira');
$city_data[] = array('accid' => 'USIA0288', 'name' => 'Exline');
$city_data[] = array('accid' => 'USIA0289', 'name' => 'Fairbank');
$city_data[] = array('accid' => 'USIA0290', 'name' => 'Fairfax');
$city_data[] = array('accid' => 'USIA0291', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USIA0292', 'name' => 'Farley');
$city_data[] = array('accid' => 'USIA0293', 'name' => 'Farmersburg');
$city_data[] = array('accid' => 'USIA0294', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USIA0295', 'name' => 'Farnhamville');
$city_data[] = array('accid' => 'USIA0296', 'name' => 'Farragut');
$city_data[] = array('accid' => 'USIA0297', 'name' => 'Fayette');
$city_data[] = array('accid' => 'USIA0298', 'name' => 'Fenton');
$city_data[] = array('accid' => 'USIA0299', 'name' => 'Ferguson');
$city_data[] = array('accid' => 'USIA0300', 'name' => 'Fertile');
$city_data[] = array('accid' => 'USIA0301', 'name' => 'Floris');
$city_data[] = array('accid' => 'USIA0302', 'name' => 'Floyd');
$city_data[] = array('accid' => 'USIA0303', 'name' => 'Fonda');
$city_data[] = array('accid' => 'USIA0304', 'name' => 'Fontanelle');
$city_data[] = array('accid' => 'USIA0305', 'name' => 'Forest City');
$city_data[] = array('accid' => 'USIA0306', 'name' => 'Fort Atkinson');
$city_data[] = array('accid' => 'USIA0307', 'name' => 'Fort Dodge');
$city_data[] = array('accid' => 'USIA0308', 'name' => 'Fort Madison');
$city_data[] = array('accid' => 'USIA0309', 'name' => 'Fostoria');
$city_data[] = array('accid' => 'USIA0310', 'name' => 'Fredericksburg');
$city_data[] = array('accid' => 'USIA0311', 'name' => 'Frederika');
$city_data[] = array('accid' => 'USIA0312', 'name' => 'Fremont');
$city_data[] = array('accid' => 'USIA0313', 'name' => 'Fruitland');
$city_data[] = array('accid' => 'USIA0314', 'name' => 'Galt');
$city_data[] = array('accid' => 'USIA0315', 'name' => 'Galva');
$city_data[] = array('accid' => 'USIA0316', 'name' => 'Garber');
$city_data[] = array('accid' => 'USIA0317', 'name' => 'Garden City');
$city_data[] = array('accid' => 'USIA0318', 'name' => 'Garden Grove');
$city_data[] = array('accid' => 'USIA0319', 'name' => 'Garnavillo');
$city_data[] = array('accid' => 'USIA0320', 'name' => 'Garner');
$city_data[] = array('accid' => 'USIA0321', 'name' => 'Garrison');
$city_data[] = array('accid' => 'USIA0322', 'name' => 'Garwin');
$city_data[] = array('accid' => 'USIA0323', 'name' => 'Geneva');
$city_data[] = array('accid' => 'USIA0324', 'name' => 'George');
$city_data[] = array('accid' => 'USIA0325', 'name' => 'Gibson');
$city_data[] = array('accid' => 'USIA0326', 'name' => 'Gifford');
$city_data[] = array('accid' => 'USIA0327', 'name' => 'Gilbert');
$city_data[] = array('accid' => 'USIA0328', 'name' => 'Gilbertville');
$city_data[] = array('accid' => 'USIA0329', 'name' => 'Gillett Grove');
$city_data[] = array('accid' => 'USIA0330', 'name' => 'Gilman');
$city_data[] = array('accid' => 'USIA0331', 'name' => 'Gilmore City');
$city_data[] = array('accid' => 'USIA0332', 'name' => 'Gladbrook');
$city_data[] = array('accid' => 'USIA0333', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USIA0334', 'name' => 'Glidden');
$city_data[] = array('accid' => 'USIA0335', 'name' => 'Goldfield');
$city_data[] = array('accid' => 'USIA0336', 'name' => 'Goodell');
$city_data[] = array('accid' => 'USIA0337', 'name' => 'Goose Lake');
$city_data[] = array('accid' => 'USIA0338', 'name' => 'Gowrie');
$city_data[] = array('accid' => 'USIA0339', 'name' => 'Graettinger');
$city_data[] = array('accid' => 'USIA0340', 'name' => 'Grafton');
$city_data[] = array('accid' => 'USIA0341', 'name' => 'Grand Junction');
$city_data[] = array('accid' => 'USIA0342', 'name' => 'Grand Mound');
$city_data[] = array('accid' => 'USIA0343', 'name' => 'Grand River');
$city_data[] = array('accid' => 'USIA0344', 'name' => 'Grandview');
$city_data[] = array('accid' => 'USIA0345', 'name' => 'Granger');
$city_data[] = array('accid' => 'USIA0346', 'name' => 'Grant');
$city_data[] = array('accid' => 'USIA0347', 'name' => 'Granville');
$city_data[] = array('accid' => 'USIA0348', 'name' => 'Gravity');
$city_data[] = array('accid' => 'USIA0349', 'name' => 'Gray');
$city_data[] = array('accid' => 'USIA0350', 'name' => 'Greeley');
$city_data[] = array('accid' => 'USIA0351', 'name' => 'Greene');
$city_data[] = array('accid' => 'USIA0352', 'name' => 'Greenfield');
$city_data[] = array('accid' => 'USIA0353', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USIA0354', 'name' => 'Grimes');
$city_data[] = array('accid' => 'USIA0355', 'name' => 'Grinnell');
$city_data[] = array('accid' => 'USIA0356', 'name' => 'Griswold');
$city_data[] = array('accid' => 'USIA0357', 'name' => 'Grundy Center');
$city_data[] = array('accid' => 'USIA0358', 'name' => 'Gruver');
$city_data[] = array('accid' => 'USIA0359', 'name' => 'Guernsey');
$city_data[] = array('accid' => 'USIA0360', 'name' => 'Guthrie Center');
$city_data[] = array('accid' => 'USIA0361', 'name' => 'Guttenberg');
$city_data[] = array('accid' => 'USIA0362', 'name' => 'Halbur');
$city_data[] = array('accid' => 'USIA0363', 'name' => 'Hamburg');
$city_data[] = array('accid' => 'USIA0364', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USIA0365', 'name' => 'Hamlin');
$city_data[] = array('accid' => 'USIA0366', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USIA0367', 'name' => 'Hancock');
$city_data[] = array('accid' => 'USIA0368', 'name' => 'Hanlontown');
$city_data[] = array('accid' => 'USIA0369', 'name' => 'Harcourt');
$city_data[] = array('accid' => 'USIA0370', 'name' => 'Hardy');
$city_data[] = array('accid' => 'USIA0371', 'name' => 'Harlan');
$city_data[] = array('accid' => 'USIA0372', 'name' => 'Harper');
$city_data[] = array('accid' => 'USIA0373', 'name' => 'Harpers Ferry');
$city_data[] = array('accid' => 'USIA0374', 'name' => 'Harris');
$city_data[] = array('accid' => 'USIA0375', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USIA0376', 'name' => 'Hartley');
$city_data[] = array('accid' => 'USIA0377', 'name' => 'Hartwick');
$city_data[] = array('accid' => 'USIA0378', 'name' => 'Harvey');
$city_data[] = array('accid' => 'USIA0379', 'name' => 'Hastings');
$city_data[] = array('accid' => 'USIA0380', 'name' => 'Havelock');
$city_data[] = array('accid' => 'USIA0381', 'name' => 'Haverhill');
$city_data[] = array('accid' => 'USIA0382', 'name' => 'Hawarden');
$city_data[] = array('accid' => 'USIA0383', 'name' => 'Hawkeye');
$city_data[] = array('accid' => 'USIA0384', 'name' => 'Hayesville');
$city_data[] = array('accid' => 'USIA0385', 'name' => 'Hazleton');
$city_data[] = array('accid' => 'USIA0386', 'name' => 'Hedrick');
$city_data[] = array('accid' => 'USIA0387', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USIA0388', 'name' => 'Hiawatha');
$city_data[] = array('accid' => 'USIA0389', 'name' => 'Highlandville');
$city_data[] = array('accid' => 'USIA0390', 'name' => 'Hills');
$city_data[] = array('accid' => 'USIA0391', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USIA0392', 'name' => 'Hinton');
$city_data[] = array('accid' => 'USIA0393', 'name' => 'Holland');
$city_data[] = array('accid' => 'USIA0394', 'name' => 'Holstein');
$city_data[] = array('accid' => 'USIA0395', 'name' => 'Holy Cross');
$city_data[] = array('accid' => 'USIA0396', 'name' => 'Homestead');
$city_data[] = array('accid' => 'USIA0397', 'name' => 'Honey Creek');
$city_data[] = array('accid' => 'USIA0398', 'name' => 'Hopkinton');
$city_data[] = array('accid' => 'USIA0399', 'name' => 'Hornick');
$city_data[] = array('accid' => 'USIA0400', 'name' => 'Hospers');
$city_data[] = array('accid' => 'USIA0401', 'name' => 'Houghton');
$city_data[] = array('accid' => 'USIA0402', 'name' => 'Hubbard');
$city_data[] = array('accid' => 'USIA0403', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USIA0404', 'name' => 'Hull');
$city_data[] = array('accid' => 'USIA0405', 'name' => 'Humboldt');
$city_data[] = array('accid' => 'USIA0406', 'name' => 'Humeston');
$city_data[] = array('accid' => 'USIA0407', 'name' => 'Huxley');
$city_data[] = array('accid' => 'USIA0408', 'name' => 'Ida Grove');
$city_data[] = array('accid' => 'USIA0409', 'name' => 'Imogene');
$city_data[] = array('accid' => 'USIA0410', 'name' => 'Independence');
$city_data[] = array('accid' => 'USIA0411', 'name' => 'Indianola');
$city_data[] = array('accid' => 'USIA0412', 'name' => 'Inwood');
$city_data[] = array('accid' => 'USIA0413', 'name' => 'Ionia');
$city_data[] = array('accid' => 'USIA0414', 'name' => 'Iowa City');
$city_data[] = array('accid' => 'USIA0415', 'name' => 'Iowa Falls');
$city_data[] = array('accid' => 'USIA0416', 'name' => 'Ira');
$city_data[] = array('accid' => 'USIA0417', 'name' => 'Ireton');
$city_data[] = array('accid' => 'USIA0418', 'name' => 'Irwin');
$city_data[] = array('accid' => 'USIA0419', 'name' => 'Jamaica');
$city_data[] = array('accid' => 'USIA0420', 'name' => 'Janesville');
$city_data[] = array('accid' => 'USIA0421', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USIA0422', 'name' => 'Jesup');
$city_data[] = array('accid' => 'USIA0423', 'name' => 'Jewell');
$city_data[] = array('accid' => 'USIA0424', 'name' => 'Johnston');
$city_data[] = array('accid' => 'USIA0425', 'name' => 'Joice');
$city_data[] = array('accid' => 'USIA0426', 'name' => 'Jolley');
$city_data[] = array('accid' => 'USIA0427', 'name' => 'Kalona');
$city_data[] = array('accid' => 'USIA0428', 'name' => 'Kamrar');
$city_data[] = array('accid' => 'USIA0429', 'name' => 'Kanawha');
$city_data[] = array('accid' => 'USIA0430', 'name' => 'Kellerton');
$city_data[] = array('accid' => 'USIA0431', 'name' => 'Kelley');
$city_data[] = array('accid' => 'USIA0432', 'name' => 'Kellogg');
$city_data[] = array('accid' => 'USIA0433', 'name' => 'Kensett');
$city_data[] = array('accid' => 'USIA0434', 'name' => 'Keokuk');
$city_data[] = array('accid' => 'USIA0435', 'name' => 'Keosauqua');
$city_data[] = array('accid' => 'USIA0436', 'name' => 'Keota');
$city_data[] = array('accid' => 'USIA0437', 'name' => 'Kesley');
$city_data[] = array('accid' => 'USIA0438', 'name' => 'Keswick');
$city_data[] = array('accid' => 'USIA0439', 'name' => 'Keystone');
$city_data[] = array('accid' => 'USIA0440', 'name' => 'Killduff');
$city_data[] = array('accid' => 'USIA0441', 'name' => 'Kimballton');
$city_data[] = array('accid' => 'USIA0442', 'name' => 'Kingsley');
$city_data[] = array('accid' => 'USIA0443', 'name' => 'Kirkman');
$city_data[] = array('accid' => 'USIA0444', 'name' => 'Kirkville');
$city_data[] = array('accid' => 'USIA0445', 'name' => 'Kiron');
$city_data[] = array('accid' => 'USIA0446', 'name' => 'Klemme');
$city_data[] = array('accid' => 'USIA0447', 'name' => 'Knierim');
$city_data[] = array('accid' => 'USIA0448', 'name' => 'Knoxville');
$city_data[] = array('accid' => 'USIA0449', 'name' => 'La Motte');
$city_data[] = array('accid' => 'USIA0450', 'name' => 'La Porte City');
$city_data[] = array('accid' => 'USIA0451', 'name' => 'Lacona');
$city_data[] = array('accid' => 'USIA0452', 'name' => 'Ladora');
$city_data[] = array('accid' => 'USIA0453', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USIA0454', 'name' => 'Lake Mills');
$city_data[] = array('accid' => 'USIA0455', 'name' => 'Lake Park');
$city_data[] = array('accid' => 'USIA0456', 'name' => 'Lake View');
$city_data[] = array('accid' => 'USIA0457', 'name' => 'Lakota');
$city_data[] = array('accid' => 'USIA0458', 'name' => 'Lamoni');
$city_data[] = array('accid' => 'USIA0459', 'name' => 'Lamont');
$city_data[] = array('accid' => 'USIA0460', 'name' => 'Lanesboro');
$city_data[] = array('accid' => 'USIA0461', 'name' => 'Langworthy');
$city_data[] = array('accid' => 'USIA0462', 'name' => 'Lansing');
$city_data[] = array('accid' => 'USIA0463', 'name' => 'Larchwood');
$city_data[] = array('accid' => 'USIA0464', 'name' => 'Larrabee');
$city_data[] = array('accid' => 'USIA0465', 'name' => 'Latimer');
$city_data[] = array('accid' => 'USIA0466', 'name' => 'Laurel');
$city_data[] = array('accid' => 'USIA0467', 'name' => 'Laurens');
$city_data[] = array('accid' => 'USIA0468', 'name' => 'Lawler');
$city_data[] = array('accid' => 'USIA0469', 'name' => 'Lawton');
$city_data[] = array('accid' => 'USIA0470', 'name' => 'Le Claire');
$city_data[] = array('accid' => 'USIA0471', 'name' => 'Le Grand');
$city_data[] = array('accid' => 'USIA0472', 'name' => 'Le Mars');
$city_data[] = array('accid' => 'USIA0473', 'name' => 'Ledyard');
$city_data[] = array('accid' => 'USIA0474', 'name' => 'Lehigh');
$city_data[] = array('accid' => 'USIA0475', 'name' => 'Leighton');
$city_data[] = array('accid' => 'USIA0476', 'name' => 'Leland');
$city_data[] = array('accid' => 'USIA0477', 'name' => 'Lenox');
$city_data[] = array('accid' => 'USIA0478', 'name' => 'Leon');
$city_data[] = array('accid' => 'USIA0479', 'name' => 'Lester');
$city_data[] = array('accid' => 'USIA0480', 'name' => 'Letts');
$city_data[] = array('accid' => 'USIA0481', 'name' => 'Lewis');
$city_data[] = array('accid' => 'USIA0482', 'name' => 'Liberty Center');
$city_data[] = array('accid' => 'USIA0483', 'name' => 'Libertyville');
$city_data[] = array('accid' => 'USIA0484', 'name' => 'Lidderdale');
$city_data[] = array('accid' => 'USIA0485', 'name' => 'Lime Springs');
$city_data[] = array('accid' => 'USIA0486', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USIA0487', 'name' => 'Linden');
$city_data[] = array('accid' => 'USIA0488', 'name' => 'Lineville');
$city_data[] = array('accid' => 'USIA0489', 'name' => 'Linn Grove');
$city_data[] = array('accid' => 'USIA0490', 'name' => 'Lisbon');
$city_data[] = array('accid' => 'USIA0491', 'name' => 'Liscomb');
$city_data[] = array('accid' => 'USIA0492', 'name' => 'Little Cedar');
$city_data[] = array('accid' => 'USIA0493', 'name' => 'Little Rock');
$city_data[] = array('accid' => 'USIA0494', 'name' => 'Little Sioux');
$city_data[] = array('accid' => 'USIA0495', 'name' => 'Littleport');
$city_data[] = array('accid' => 'USIA0496', 'name' => 'Livermore');
$city_data[] = array('accid' => 'USIA0497', 'name' => 'Lockridge');
$city_data[] = array('accid' => 'USIA0498', 'name' => 'Logan');
$city_data[] = array('accid' => 'USIA0499', 'name' => 'Lohrville');
$city_data[] = array('accid' => 'USIA0500', 'name' => 'Lone Rock');
$city_data[] = array('accid' => 'USIA0501', 'name' => 'Lone Tree');
$city_data[] = array('accid' => 'USIA0502', 'name' => 'Long Grove');
$city_data[] = array('accid' => 'USIA0503', 'name' => 'Lorimor');
$city_data[] = array('accid' => 'USIA0504', 'name' => 'Lost Nation');
$city_data[] = array('accid' => 'USIA0505', 'name' => 'Lovilia');
$city_data[] = array('accid' => 'USIA0506', 'name' => 'Low Moor');
$city_data[] = array('accid' => 'USIA0507', 'name' => 'Lowden');
$city_data[] = array('accid' => 'USIA0508', 'name' => 'Lu Verne');
$city_data[] = array('accid' => 'USIA0509', 'name' => 'Luana');
$city_data[] = array('accid' => 'USIA0510', 'name' => 'Lucas');
$city_data[] = array('accid' => 'USIA0511', 'name' => 'Luther');
$city_data[] = array('accid' => 'USIA0512', 'name' => 'Luxemburg');
$city_data[] = array('accid' => 'USIA0513', 'name' => 'Luzerne');
$city_data[] = array('accid' => 'USIA0514', 'name' => 'Lynnville');
$city_data[] = array('accid' => 'USIA0515', 'name' => 'Lytton');
$city_data[] = array('accid' => 'USIA0516', 'name' => 'Macedonia');
$city_data[] = array('accid' => 'USIA0517', 'name' => 'Macksburg');
$city_data[] = array('accid' => 'USIA0518', 'name' => 'Madrid');
$city_data[] = array('accid' => 'USIA0519', 'name' => 'Magnolia');
$city_data[] = array('accid' => 'USIA0520', 'name' => 'Malcom');
$city_data[] = array('accid' => 'USIA0521', 'name' => 'Mallard');
$city_data[] = array('accid' => 'USIA0522', 'name' => 'Malvern');
$city_data[] = array('accid' => 'USIA0523', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USIA0524', 'name' => 'Manilla');
$city_data[] = array('accid' => 'USIA0525', 'name' => 'Manly');
$city_data[] = array('accid' => 'USIA0526', 'name' => 'Manning');
$city_data[] = array('accid' => 'USIA0527', 'name' => 'Manson');
$city_data[] = array('accid' => 'USIA0528', 'name' => 'Mapleton');
$city_data[] = array('accid' => 'USIA0529', 'name' => 'Maquoketa');
$city_data[] = array('accid' => 'USIA0530', 'name' => 'Marathon');
$city_data[] = array('accid' => 'USIA0531', 'name' => 'Marble Rock');
$city_data[] = array('accid' => 'USIA0532', 'name' => 'Marcus');
$city_data[] = array('accid' => 'USIA0533', 'name' => 'Marengo');
$city_data[] = array('accid' => 'USIA0534', 'name' => 'Marion');
$city_data[] = array('accid' => 'USIA0535', 'name' => 'Marne');
$city_data[] = array('accid' => 'USIA0536', 'name' => 'Marquette');
$city_data[] = array('accid' => 'USIA0537', 'name' => 'Marshalltown');
$city_data[] = array('accid' => 'USIA0538', 'name' => 'Martelle');
$city_data[] = array('accid' => 'USIA0539', 'name' => 'Martensdale');
$city_data[] = array('accid' => 'USIA0540', 'name' => 'Martinsburg');
$city_data[] = array('accid' => 'USIA0541', 'name' => 'Mason City');
$city_data[] = array('accid' => 'USIA0542', 'name' => 'Masonville');
$city_data[] = array('accid' => 'USIA0543', 'name' => 'Massena');
$city_data[] = array('accid' => 'USIA0544', 'name' => 'Matlock');
$city_data[] = array('accid' => 'USIA0545', 'name' => 'Maurice');
$city_data[] = array('accid' => 'USIA0546', 'name' => 'Maxwell');
$city_data[] = array('accid' => 'USIA0547', 'name' => 'May City');
$city_data[] = array('accid' => 'USIA0548', 'name' => 'Maynard');
$city_data[] = array('accid' => 'USIA0549', 'name' => 'McCallsburg');
$city_data[] = array('accid' => 'USIA0550', 'name' => 'McCausland');
$city_data[] = array('accid' => 'USIA0551', 'name' => 'McClelland');
$city_data[] = array('accid' => 'USIA0552', 'name' => 'McGregor');
$city_data[] = array('accid' => 'USIA0553', 'name' => 'McIntire');
$city_data[] = array('accid' => 'USIA0554', 'name' => 'Mechanicsville');
$city_data[] = array('accid' => 'USIA0555', 'name' => 'Mediapolis');
$city_data[] = array('accid' => 'USIA0556', 'name' => 'Melbourne');
$city_data[] = array('accid' => 'USIA0557', 'name' => 'Melcher');
$city_data[] = array('accid' => 'USIA0558', 'name' => 'Melrose');
$city_data[] = array('accid' => 'USIA0559', 'name' => 'Melvin');
$city_data[] = array('accid' => 'USIA0560', 'name' => 'Menlo');
$city_data[] = array('accid' => 'USIA0561', 'name' => 'Meriden');
$city_data[] = array('accid' => 'USIA0562', 'name' => 'Merrill');
$city_data[] = array('accid' => 'USIA0563', 'name' => 'Meservey');
$city_data[] = array('accid' => 'USIA0564', 'name' => 'Middle Amana');
$city_data[] = array('accid' => 'USIA0565', 'name' => 'Middletown');
$city_data[] = array('accid' => 'USIA0566', 'name' => 'Miles');
$city_data[] = array('accid' => 'USIA0567', 'name' => 'Milford');
$city_data[] = array('accid' => 'USIA0568', 'name' => 'Millersburg');
$city_data[] = array('accid' => 'USIA0569', 'name' => 'Millerton');
$city_data[] = array('accid' => 'USIA0570', 'name' => 'Milo');
$city_data[] = array('accid' => 'USIA0571', 'name' => 'Milton');
$city_data[] = array('accid' => 'USIA0572', 'name' => 'Minburn');
$city_data[] = array('accid' => 'USIA0573', 'name' => 'Minden');
$city_data[] = array('accid' => 'USIA0574', 'name' => 'Mineola');
$city_data[] = array('accid' => 'USIA0575', 'name' => 'Mingo');
$city_data[] = array('accid' => 'USIA0576', 'name' => 'Missouri Valley');
$city_data[] = array('accid' => 'USIA0577', 'name' => 'Mitchellville');
$city_data[] = array('accid' => 'USIA0578', 'name' => 'Modale');
$city_data[] = array('accid' => 'USIA0579', 'name' => 'Mondamin');
$city_data[] = array('accid' => 'USIA0580', 'name' => 'Monmouth');
$city_data[] = array('accid' => 'USIA0581', 'name' => 'Monona');
$city_data[] = array('accid' => 'USIA0582', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USIA0583', 'name' => 'Montezuma');
$city_data[] = array('accid' => 'USIA0584', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USIA0585', 'name' => 'Montour');
$city_data[] = array('accid' => 'USIA0586', 'name' => 'Montpelier');
$city_data[] = array('accid' => 'USIA0587', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USIA0588', 'name' => 'Moorhead');
$city_data[] = array('accid' => 'USIA0589', 'name' => 'Moorland');
$city_data[] = array('accid' => 'USIA0590', 'name' => 'Moravia');
$city_data[] = array('accid' => 'USIA0591', 'name' => 'Morley');
$city_data[] = array('accid' => 'USIA0592', 'name' => 'Morning Sun');
$city_data[] = array('accid' => 'USIA0593', 'name' => 'Morrison');
$city_data[] = array('accid' => 'USIA0594', 'name' => 'Moscow');
$city_data[] = array('accid' => 'USIA0595', 'name' => 'Moulton');
$city_data[] = array('accid' => 'USIA0596', 'name' => 'Mount Auburn');
$city_data[] = array('accid' => 'USIA0597', 'name' => 'Mount Ayr');
$city_data[] = array('accid' => 'USIA0598', 'name' => 'Mount Pleasant');
$city_data[] = array('accid' => 'USIA0599', 'name' => 'Mount Sterling');
$city_data[] = array('accid' => 'USIA0600', 'name' => 'Mount Union');
$city_data[] = array('accid' => 'USIA0601', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USIA0602', 'name' => 'Moville');
$city_data[] = array('accid' => 'USIA0603', 'name' => 'Murray');
$city_data[] = array('accid' => 'USIA0604', 'name' => 'Muscatine');
$city_data[] = array('accid' => 'USIA0605', 'name' => 'Mystic');
$city_data[] = array('accid' => 'USIA0606', 'name' => 'Nashua');
$city_data[] = array('accid' => 'USIA0607', 'name' => 'Nemaha');
$city_data[] = array('accid' => 'USIA0608', 'name' => 'Neola');
$city_data[] = array('accid' => 'USIA0609', 'name' => 'Nevada');
$city_data[] = array('accid' => 'USIA0610', 'name' => 'New Albin');
$city_data[] = array('accid' => 'USIA0611', 'name' => 'New Hampton');
$city_data[] = array('accid' => 'USIA0612', 'name' => 'New Hartford');
$city_data[] = array('accid' => 'USIA0613', 'name' => 'New Liberty');
$city_data[] = array('accid' => 'USIA0614', 'name' => 'New London');
$city_data[] = array('accid' => 'USIA0615', 'name' => 'New Market');
$city_data[] = array('accid' => 'USIA0616', 'name' => 'New Providence');
$city_data[] = array('accid' => 'USIA0617', 'name' => 'New Sharon');
$city_data[] = array('accid' => 'USIA0618', 'name' => 'New Vienna');
$city_data[] = array('accid' => 'USIA0619', 'name' => 'New Virginia');
$city_data[] = array('accid' => 'USIA0620', 'name' => 'Newell');
$city_data[] = array('accid' => 'USIA0621', 'name' => 'Newhall');
$city_data[] = array('accid' => 'USIA0622', 'name' => 'Newton');
$city_data[] = array('accid' => 'USIA0623', 'name' => 'Nichols');
$city_data[] = array('accid' => 'USIA0624', 'name' => 'Nodaway');
$city_data[] = array('accid' => 'USIA0625', 'name' => 'Nora Springs');
$city_data[] = array('accid' => 'USIA0626', 'name' => 'North Buena Vista');
$city_data[] = array('accid' => 'USIA0627', 'name' => 'North English');
$city_data[] = array('accid' => 'USIA0628', 'name' => 'North Liberty');
$city_data[] = array('accid' => 'USIA0629', 'name' => 'North Washington');
$city_data[] = array('accid' => 'USIA0630', 'name' => 'Northboro');
$city_data[] = array('accid' => 'USIA0631', 'name' => 'Northwood');
$city_data[] = array('accid' => 'USIA0632', 'name' => 'Norwalk');
$city_data[] = array('accid' => 'USIA0633', 'name' => 'Norway');
$city_data[] = array('accid' => 'USIA0634', 'name' => 'Oakdale');
$city_data[] = array('accid' => 'USIA0635', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USIA0636', 'name' => 'Oakville');
$city_data[] = array('accid' => 'USIA0637', 'name' => 'Ocheyedan');
$city_data[] = array('accid' => 'USIA0638', 'name' => 'Odebolt');
$city_data[] = array('accid' => 'USIA0639', 'name' => 'Oelwein');
$city_data[] = array('accid' => 'USIA0640', 'name' => 'Ogden');
$city_data[] = array('accid' => 'USIA0641', 'name' => 'Okoboji');
$city_data[] = array('accid' => 'USIA0642', 'name' => 'Olds');
$city_data[] = array('accid' => 'USIA0643', 'name' => 'Olin');
$city_data[] = array('accid' => 'USIA0644', 'name' => 'Ollie');
$city_data[] = array('accid' => 'USIA0645', 'name' => 'Onawa');
$city_data[] = array('accid' => 'USIA0646', 'name' => 'Onslow');
$city_data[] = array('accid' => 'USIA0647', 'name' => 'Oran');
$city_data[] = array('accid' => 'USIA0648', 'name' => 'Orange City');
$city_data[] = array('accid' => 'USIA0649', 'name' => 'Orchard');
$city_data[] = array('accid' => 'USIA0650', 'name' => 'Orient');
$city_data[] = array('accid' => 'USIA0651', 'name' => 'Osage');
$city_data[] = array('accid' => 'USIA0652', 'name' => 'Osceola');
$city_data[] = array('accid' => 'USIA0653', 'name' => 'Oskaloosa');
$city_data[] = array('accid' => 'USIA0654', 'name' => 'Ossian');
$city_data[] = array('accid' => 'USIA0655', 'name' => 'Otho');
$city_data[] = array('accid' => 'USIA0656', 'name' => 'Otley');
$city_data[] = array('accid' => 'USIA0657', 'name' => 'Oto');
$city_data[] = array('accid' => 'USIA0658', 'name' => 'Ottosen');
$city_data[] = array('accid' => 'USIA0659', 'name' => 'Ottumwa');
$city_data[] = array('accid' => 'USIA0660', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USIA0661', 'name' => 'Oxford Junction');
$city_data[] = array('accid' => 'USIA0662', 'name' => 'Oyens');
$city_data[] = array('accid' => 'USIA0663', 'name' => 'Pacific Junction');
$city_data[] = array('accid' => 'USIA0664', 'name' => 'Packwood');
$city_data[] = array('accid' => 'USIA0665', 'name' => 'Palmer');
$city_data[] = array('accid' => 'USIA0666', 'name' => 'Palo');
$city_data[] = array('accid' => 'USIA0667', 'name' => 'Panama');
$city_data[] = array('accid' => 'USIA0668', 'name' => 'Panora');
$city_data[] = array('accid' => 'USIA0669', 'name' => 'Parkersburg');
$city_data[] = array('accid' => 'USIA0670', 'name' => 'Parnell');
$city_data[] = array('accid' => 'USIA0671', 'name' => 'Paton');
$city_data[] = array('accid' => 'USIA0672', 'name' => 'Patterson');
$city_data[] = array('accid' => 'USIA0673', 'name' => 'Paullina');
$city_data[] = array('accid' => 'USIA0674', 'name' => 'Pella');
$city_data[] = array('accid' => 'USIA0675', 'name' => 'Peosta');
$city_data[] = array('accid' => 'USIA0676', 'name' => 'Percival');
$city_data[] = array('accid' => 'USIA0677', 'name' => 'Perry');
$city_data[] = array('accid' => 'USIA0678', 'name' => 'Persia');
$city_data[] = array('accid' => 'USIA0679', 'name' => 'Peru');
$city_data[] = array('accid' => 'USIA0680', 'name' => 'Peterson');
$city_data[] = array('accid' => 'USIA0681', 'name' => 'Pierson');
$city_data[] = array('accid' => 'USIA0682', 'name' => 'Pilot Grove');
$city_data[] = array('accid' => 'USIA0683', 'name' => 'Pilot Mound');
$city_data[] = array('accid' => 'USIA0684', 'name' => 'Pisgah');
$city_data[] = array('accid' => 'USIA0685', 'name' => 'Plainfield');
$city_data[] = array('accid' => 'USIA0686', 'name' => 'Plano');
$city_data[] = array('accid' => 'USIA0687', 'name' => 'Pleasant Valley');
$city_data[] = array('accid' => 'USIA0688', 'name' => 'Pleasantville');
$city_data[] = array('accid' => 'USIA0689', 'name' => 'Plover');
$city_data[] = array('accid' => 'USIA0690', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USIA0691', 'name' => 'Pocahontas');
$city_data[] = array('accid' => 'USIA0692', 'name' => 'Polk City');
$city_data[] = array('accid' => 'USIA0693', 'name' => 'Pomeroy');
$city_data[] = array('accid' => 'USIA0694', 'name' => 'Popejoy');
$city_data[] = array('accid' => 'USIA0695', 'name' => 'Portsmouth');
$city_data[] = array('accid' => 'USIA0696', 'name' => 'Postville');
$city_data[] = array('accid' => 'USIA0697', 'name' => 'Prairie City');
$city_data[] = array('accid' => 'USIA0698', 'name' => 'Prairieburg');
$city_data[] = array('accid' => 'USIA0699', 'name' => 'Prescott');
$city_data[] = array('accid' => 'USIA0700', 'name' => 'Preston');
$city_data[] = array('accid' => 'USIA0701', 'name' => 'Primghar');
$city_data[] = array('accid' => 'USIA0702', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USIA0703', 'name' => 'Prole');
$city_data[] = array('accid' => 'USIA0704', 'name' => 'Promise City');
$city_data[] = array('accid' => 'USIA0705', 'name' => 'Protivin');
$city_data[] = array('accid' => 'USIA0706', 'name' => 'Pulaski');
$city_data[] = array('accid' => 'USIA0707', 'name' => 'Quasqueton');
$city_data[] = array('accid' => 'USIA0708', 'name' => 'Quimby');
$city_data[] = array('accid' => 'USIA0709', 'name' => 'Radcliffe');
$city_data[] = array('accid' => 'USIA0710', 'name' => 'Rake');
$city_data[] = array('accid' => 'USIA0711', 'name' => 'Ralston');
$city_data[] = array('accid' => 'USIA0712', 'name' => 'Randalia');
$city_data[] = array('accid' => 'USIA0713', 'name' => 'Randall');
$city_data[] = array('accid' => 'USIA0714', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USIA0715', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USIA0716', 'name' => 'Readlyn');
$city_data[] = array('accid' => 'USIA0717', 'name' => 'Reasnor');
$city_data[] = array('accid' => 'USIA0718', 'name' => 'Red Oak');
$city_data[] = array('accid' => 'USIA0719', 'name' => 'Redding');
$city_data[] = array('accid' => 'USIA0720', 'name' => 'Redfield');
$city_data[] = array('accid' => 'USIA0721', 'name' => 'Reinbeck');
$city_data[] = array('accid' => 'USIA0722', 'name' => 'Rembrandt');
$city_data[] = array('accid' => 'USIA0723', 'name' => 'Remsen');
$city_data[] = array('accid' => 'USIA0724', 'name' => 'Renwick');
$city_data[] = array('accid' => 'USIA0725', 'name' => 'Rhodes');
$city_data[] = array('accid' => 'USIA0726', 'name' => 'Riceville');
$city_data[] = array('accid' => 'USIA0727', 'name' => 'Richland');
$city_data[] = array('accid' => 'USIA0728', 'name' => 'Ricketts');
$city_data[] = array('accid' => 'USIA0729', 'name' => 'Ridgeway');
$city_data[] = array('accid' => 'USIA0730', 'name' => 'Rinard');
$city_data[] = array('accid' => 'USIA0731', 'name' => 'Ringsted');
$city_data[] = array('accid' => 'USIA0732', 'name' => 'Rippey');
$city_data[] = array('accid' => 'USIA0733', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USIA0734', 'name' => 'Riverton');
$city_data[] = array('accid' => 'USIA0735', 'name' => 'Robins');
$city_data[] = array('accid' => 'USIA0736', 'name' => 'Rock Falls');
$city_data[] = array('accid' => 'USIA0737', 'name' => 'Rock Rapids');
$city_data[] = array('accid' => 'USIA0738', 'name' => 'Rock Valley');
$city_data[] = array('accid' => 'USIA0739', 'name' => 'Rockford');
$city_data[] = array('accid' => 'USIA0740', 'name' => 'Rockwell');
$city_data[] = array('accid' => 'USIA0741', 'name' => 'Rockwell City');
$city_data[] = array('accid' => 'USIA0742', 'name' => 'Rodney');
$city_data[] = array('accid' => 'USIA0743', 'name' => 'Roland');
$city_data[] = array('accid' => 'USIA0744', 'name' => 'Rolfe');
$city_data[] = array('accid' => 'USIA0745', 'name' => 'Rome');
$city_data[] = array('accid' => 'USIA0746', 'name' => 'Rose Hill');
$city_data[] = array('accid' => 'USIA0747', 'name' => 'Rowan');
$city_data[] = array('accid' => 'USIA0748', 'name' => 'Rowley');
$city_data[] = array('accid' => 'USIA0749', 'name' => 'Royal');
$city_data[] = array('accid' => 'USIA0750', 'name' => 'Rudd');
$city_data[] = array('accid' => 'USIA0751', 'name' => 'Runnells');
$city_data[] = array('accid' => 'USIA0752', 'name' => 'Russell');
$city_data[] = array('accid' => 'USIA0753', 'name' => 'Ruthven');
$city_data[] = array('accid' => 'USIA0754', 'name' => 'Rutland');
$city_data[] = array('accid' => 'USIA0755', 'name' => 'Ryan');
$city_data[] = array('accid' => 'USIA0756', 'name' => 'Sabula');
$city_data[] = array('accid' => 'USIA0757', 'name' => 'Sac City');
$city_data[] = array('accid' => 'USIA0758', 'name' => 'Saint Ansgar');
$city_data[] = array('accid' => 'USIA0759', 'name' => 'Saint Anthony');
$city_data[] = array('accid' => 'USIA0760', 'name' => 'Saint Charles');
$city_data[] = array('accid' => 'USIA0761', 'name' => 'Saint Donatus');
$city_data[] = array('accid' => 'USIA0762', 'name' => 'Saint Lucas');
$city_data[] = array('accid' => 'USIA0763', 'name' => 'Saint Marys');
$city_data[] = array('accid' => 'USIA0764', 'name' => 'Saint Olaf');
$city_data[] = array('accid' => 'USIA0765', 'name' => 'Saint Paul');
$city_data[] = array('accid' => 'USIA0766', 'name' => 'Salem');
$city_data[] = array('accid' => 'USIA0767', 'name' => 'Salix');
$city_data[] = array('accid' => 'USIA0768', 'name' => 'Sanborn');
$city_data[] = array('accid' => 'USIA0769', 'name' => 'Scarville');
$city_data[] = array('accid' => 'USIA0770', 'name' => 'Schaller');
$city_data[] = array('accid' => 'USIA0771', 'name' => 'Schleswig');
$city_data[] = array('accid' => 'USIA0772', 'name' => 'Scranton');
$city_data[] = array('accid' => 'USIA0773', 'name' => 'Searsboro');
$city_data[] = array('accid' => 'USIA0774', 'name' => 'Selma');
$city_data[] = array('accid' => 'USIA0775', 'name' => 'Sergeant Bluff');
$city_data[] = array('accid' => 'USIA0776', 'name' => 'Seymour');
$city_data[] = array('accid' => 'USIA0777', 'name' => 'Shambaugh');
$city_data[] = array('accid' => 'USIA0778', 'name' => 'Shannon City');
$city_data[] = array('accid' => 'USIA0779', 'name' => 'Sharpsburg');
$city_data[] = array('accid' => 'USIA0780', 'name' => 'Sheffield');
$city_data[] = array('accid' => 'USIA0781', 'name' => 'Shelby');
$city_data[] = array('accid' => 'USIA0782', 'name' => 'Sheldahl');
$city_data[] = array('accid' => 'USIA0783', 'name' => 'Sheldon');
$city_data[] = array('accid' => 'USIA0784', 'name' => 'Shell Rock');
$city_data[] = array('accid' => 'USIA0785', 'name' => 'Shellsburg');
$city_data[] = array('accid' => 'USIA0786', 'name' => 'Shenandoah');
$city_data[] = array('accid' => 'USIA0787', 'name' => 'Sherrill');
$city_data[] = array('accid' => 'USIA0788', 'name' => 'Sibley');
$city_data[] = array('accid' => 'USIA0789', 'name' => 'Sidney');
$city_data[] = array('accid' => 'USIA0790', 'name' => 'Sigourney');
$city_data[] = array('accid' => 'USIA0791', 'name' => 'Silver City');
$city_data[] = array('accid' => 'USIA0792', 'name' => 'Sioux Center');
$city_data[] = array('accid' => 'USIA0793', 'name' => 'Sioux City');
$city_data[] = array('accid' => 'USIA0794', 'name' => 'Sioux Rapids');
$city_data[] = array('accid' => 'USIA0795', 'name' => 'Slater');
$city_data[] = array('accid' => 'USIA0796', 'name' => 'Sloan');
$city_data[] = array('accid' => 'USIA0797', 'name' => 'Smithland');
$city_data[] = array('accid' => 'USIA0798', 'name' => 'Soldier');
$city_data[] = array('accid' => 'USIA0799', 'name' => 'Solon');
$city_data[] = array('accid' => 'USIA0800', 'name' => 'Somers');
$city_data[] = array('accid' => 'USIA0801', 'name' => 'South Amana');
$city_data[] = array('accid' => 'USIA0802', 'name' => 'South English');
$city_data[] = array('accid' => 'USIA0803', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USIA0804', 'name' => 'Sperry');
$city_data[] = array('accid' => 'USIA0805', 'name' => 'Spillville');
$city_data[] = array('accid' => 'USIA0806', 'name' => 'Spirit Lake');
$city_data[] = array('accid' => 'USIA0807', 'name' => 'Spragueville');
$city_data[] = array('accid' => 'USIA0808', 'name' => 'Springbrook');
$city_data[] = array('accid' => 'USIA0809', 'name' => 'Springville');
$city_data[] = array('accid' => 'USIA0810', 'name' => 'Stacyville');
$city_data[] = array('accid' => 'USIA0811', 'name' => 'Stanhope');
$city_data[] = array('accid' => 'USIA0812', 'name' => 'Stanley');
$city_data[] = array('accid' => 'USIA0813', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USIA0814', 'name' => 'Stanwood');
$city_data[] = array('accid' => 'USIA0815', 'name' => 'State Center');
$city_data[] = array('accid' => 'USIA0816', 'name' => 'Steamboat Rock');
$city_data[] = array('accid' => 'USIA0817', 'name' => 'Stockport');
$city_data[] = array('accid' => 'USIA0818', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USIA0819', 'name' => 'Storm Lake');
$city_data[] = array('accid' => 'USIA0820', 'name' => 'Story City');
$city_data[] = array('accid' => 'USIA0821', 'name' => 'Stout');
$city_data[] = array('accid' => 'USIA0822', 'name' => 'Stratford');
$city_data[] = array('accid' => 'USIA0823', 'name' => 'Strawberry Point');
$city_data[] = array('accid' => 'USIA0824', 'name' => 'Struble');
$city_data[] = array('accid' => 'USIA0825', 'name' => 'Stuart');
$city_data[] = array('accid' => 'USIA0826', 'name' => 'Sully');
$city_data[] = array('accid' => 'USIA0827', 'name' => 'Sumner');
$city_data[] = array('accid' => 'USIA0829', 'name' => 'Superior');
$city_data[] = array('accid' => 'USIA0830', 'name' => 'Sutherland');
$city_data[] = array('accid' => 'USIA0831', 'name' => 'Swaledale');
$city_data[] = array('accid' => 'USIA0832', 'name' => 'Swan');
$city_data[] = array('accid' => 'USIA0833', 'name' => 'Swea City');
$city_data[] = array('accid' => 'USIA0834', 'name' => 'Swedesburg');
$city_data[] = array('accid' => 'USIA0835', 'name' => 'Swisher');
$city_data[] = array('accid' => 'USIA0836', 'name' => 'Tabor');
$city_data[] = array('accid' => 'USIA0837', 'name' => 'Tama');
$city_data[] = array('accid' => 'USIA0838', 'name' => 'Teeds Grove');
$city_data[] = array('accid' => 'USIA0839', 'name' => 'Templeton');
$city_data[] = array('accid' => 'USIA0840', 'name' => 'Tennant');
$city_data[] = array('accid' => 'USIA0841', 'name' => 'Terril');
$city_data[] = array('accid' => 'USIA0842', 'name' => 'Thayer');
$city_data[] = array('accid' => 'USIA0843', 'name' => 'Thompson');
$city_data[] = array('accid' => 'USIA0844', 'name' => 'Thor');
$city_data[] = array('accid' => 'USIA0845', 'name' => 'Thornburg');
$city_data[] = array('accid' => 'USIA0846', 'name' => 'Thornton');
$city_data[] = array('accid' => 'USIA0847', 'name' => 'Thurman');
$city_data[] = array('accid' => 'USIA0848', 'name' => 'Tiffin');
$city_data[] = array('accid' => 'USIA0849', 'name' => 'Tingley');
$city_data[] = array('accid' => 'USIA0850', 'name' => 'Tipton');
$city_data[] = array('accid' => 'USIA0851', 'name' => 'Titonka');
$city_data[] = array('accid' => 'USIA0852', 'name' => 'Toddville');
$city_data[] = array('accid' => 'USIA0853', 'name' => 'Toeterville');
$city_data[] = array('accid' => 'USIA0854', 'name' => 'Toledo');
$city_data[] = array('accid' => 'USIA0855', 'name' => 'Tracy');
$city_data[] = array('accid' => 'USIA0856', 'name' => 'Traer');
$city_data[] = array('accid' => 'USIA0857', 'name' => 'Treynor');
$city_data[] = array('accid' => 'USIA0858', 'name' => 'Tripoli');
$city_data[] = array('accid' => 'USIA0859', 'name' => 'Troy Mills');
$city_data[] = array('accid' => 'USIA0860', 'name' => 'Truesdale');
$city_data[] = array('accid' => 'USIA0861', 'name' => 'Truro');
$city_data[] = array('accid' => 'USIA0862', 'name' => 'Turin');
$city_data[] = array('accid' => 'USIA0863', 'name' => 'Udell');
$city_data[] = array('accid' => 'USIA0864', 'name' => 'Underwood');
$city_data[] = array('accid' => 'USIA0865', 'name' => 'Union');
$city_data[] = array('accid' => 'USIA0866', 'name' => 'Unionville');
$city_data[] = array('accid' => 'USIA0867', 'name' => 'University Park');
$city_data[] = array('accid' => 'USIA0868', 'name' => 'Urbana');
$city_data[] = array('accid' => 'USIA0869', 'name' => 'Urbandale');
$city_data[] = array('accid' => 'USIA0870', 'name' => 'Ute');
$city_data[] = array('accid' => 'USIA0871', 'name' => 'Vail');
$city_data[] = array('accid' => 'USIA0872', 'name' => 'Van Horne');
$city_data[] = array('accid' => 'USIA0873', 'name' => 'Van Meter');
$city_data[] = array('accid' => 'USIA0874', 'name' => 'Van Wert');
$city_data[] = array('accid' => 'USIA0875', 'name' => 'Varina');
$city_data[] = array('accid' => 'USIA0876', 'name' => 'Ventura');
$city_data[] = array('accid' => 'USIA0877', 'name' => 'Victor');
$city_data[] = array('accid' => 'USIA0878', 'name' => 'Villisca');
$city_data[] = array('accid' => 'USIA0879', 'name' => 'Vincent');
$city_data[] = array('accid' => 'USIA0880', 'name' => 'Vining');
$city_data[] = array('accid' => 'USIA0881', 'name' => 'Vinton');
$city_data[] = array('accid' => 'USIA0882', 'name' => 'Viola');
$city_data[] = array('accid' => 'USIA0883', 'name' => 'Volga');
$city_data[] = array('accid' => 'USIA0884', 'name' => 'Wadena');
$city_data[] = array('accid' => 'USIA0885', 'name' => 'Walcott');
$city_data[] = array('accid' => 'USIA0886', 'name' => 'Walford');
$city_data[] = array('accid' => 'USIA0887', 'name' => 'Walker');
$city_data[] = array('accid' => 'USIA0888', 'name' => 'Wall Lake');
$city_data[] = array('accid' => 'USIA0889', 'name' => 'Wallingford');
$city_data[] = array('accid' => 'USIA0890', 'name' => 'Walnut');
$city_data[] = array('accid' => 'USIA0891', 'name' => 'Wapello');
$city_data[] = array('accid' => 'USIA0892', 'name' => 'Washington');
$city_data[] = array('accid' => 'USIA0893', 'name' => 'Washta');
$city_data[] = array('accid' => 'USIA0894', 'name' => 'Waterloo');
$city_data[] = array('accid' => 'USIA0895', 'name' => 'Waterville');
$city_data[] = array('accid' => 'USIA0896', 'name' => 'Watkins');
$city_data[] = array('accid' => 'USIA0897', 'name' => 'Waucoma');
$city_data[] = array('accid' => 'USIA0898', 'name' => 'Waukee');
$city_data[] = array('accid' => 'USIA0899', 'name' => 'Waukon');
$city_data[] = array('accid' => 'USIA0900', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USIA0901', 'name' => 'Wayland');
$city_data[] = array('accid' => 'USIA0902', 'name' => 'Webb');
$city_data[] = array('accid' => 'USIA0903', 'name' => 'Webster');
$city_data[] = array('accid' => 'USIA0904', 'name' => 'Webster City');
$city_data[] = array('accid' => 'USIA0905', 'name' => 'Weldon');
$city_data[] = array('accid' => 'USIA0906', 'name' => 'Wellman');
$city_data[] = array('accid' => 'USIA0907', 'name' => 'Wellsburg');
$city_data[] = array('accid' => 'USIA0908', 'name' => 'Welton');
$city_data[] = array('accid' => 'USIA0909', 'name' => 'Wesley');
$city_data[] = array('accid' => 'USIA0910', 'name' => 'West Bend');
$city_data[] = array('accid' => 'USIA0911', 'name' => 'West Branch');
$city_data[] = array('accid' => 'USIA0912', 'name' => 'West Burlington');
$city_data[] = array('accid' => 'USIA0913', 'name' => 'West Chester');
$city_data[] = array('accid' => 'USIA0914', 'name' => 'West Des Moines');
$city_data[] = array('accid' => 'USIA0915', 'name' => 'West Grove');
$city_data[] = array('accid' => 'USIA0916', 'name' => 'West Liberty');
$city_data[] = array('accid' => 'USIA0917', 'name' => 'West Point');
$city_data[] = array('accid' => 'USIA0918', 'name' => 'West Union');
$city_data[] = array('accid' => 'USIA0919', 'name' => 'Westfield');
$city_data[] = array('accid' => 'USIA0920', 'name' => 'Westgate');
$city_data[] = array('accid' => 'USIA0921', 'name' => 'Westphalia');
$city_data[] = array('accid' => 'USIA0922', 'name' => 'Westside');
$city_data[] = array('accid' => 'USIA0923', 'name' => 'Wever');
$city_data[] = array('accid' => 'USIA0924', 'name' => 'What Cheer');
$city_data[] = array('accid' => 'USIA0925', 'name' => 'Wheatland');
$city_data[] = array('accid' => 'USIA0926', 'name' => 'Whiting');
$city_data[] = array('accid' => 'USIA0927', 'name' => 'Whittemore');
$city_data[] = array('accid' => 'USIA0928', 'name' => 'Whitten');
$city_data[] = array('accid' => 'USIA0929', 'name' => 'Williams');
$city_data[] = array('accid' => 'USIA0930', 'name' => 'Williamsburg');
$city_data[] = array('accid' => 'USIA0931', 'name' => 'Williamson');
$city_data[] = array('accid' => 'USIA0932', 'name' => 'Wilton');
$city_data[] = array('accid' => 'USIA0933', 'name' => 'Winfield');
$city_data[] = array('accid' => 'USIA0934', 'name' => 'Winterset');
$city_data[] = array('accid' => 'USIA0935', 'name' => 'Winthrop');
$city_data[] = array('accid' => 'USIA0936', 'name' => 'Wiota');
$city_data[] = array('accid' => 'USIA0937', 'name' => 'Woden');
$city_data[] = array('accid' => 'USIA0938', 'name' => 'Woodbine');
$city_data[] = array('accid' => 'USIA0939', 'name' => 'Woodburn');
$city_data[] = array('accid' => 'USIA0940', 'name' => 'Woodward');
$city_data[] = array('accid' => 'USIA0941', 'name' => 'Woolstock');
$city_data[] = array('accid' => 'USIA0942', 'name' => 'Worthington');
$city_data[] = array('accid' => 'USIA0943', 'name' => 'Wyoming');
$city_data[] = array('accid' => 'USIA0944', 'name' => 'Yale');
$city_data[] = array('accid' => 'USIA0945', 'name' => 'Yarmouth');
$city_data[] = array('accid' => 'USIA0946', 'name' => 'Yorktown');
$city_data[] = array('accid' => 'USIA0947', 'name' => 'Zearing');
$city_data[] = array('accid' => 'USIA0948', 'name' => 'Zwingle');

?>
