<?php

// City package for USA: Idaho 

$city_name = 'USA: Idaho';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USID0001', 'name' => 'Aberdeen');
$city_data[] = array('accid' => 'USID0002', 'name' => 'Ahsahka');
$city_data[] = array('accid' => 'USID0003', 'name' => 'Albion');
$city_data[] = array('accid' => 'USID0004', 'name' => 'Almo');
$city_data[] = array('accid' => 'USID0005', 'name' => 'American Falls');
$city_data[] = array('accid' => 'USID0006', 'name' => 'Arbon');
$city_data[] = array('accid' => 'USID0007', 'name' => 'Arco');
$city_data[] = array('accid' => 'USID0008', 'name' => 'Arimo');
$city_data[] = array('accid' => 'USID0009', 'name' => 'Ashton');
$city_data[] = array('accid' => 'USID0010', 'name' => 'Athol');
$city_data[] = array('accid' => 'USID0011', 'name' => 'Atlanta');
$city_data[] = array('accid' => 'USID0012', 'name' => 'Atomic City');
$city_data[] = array('accid' => 'USID0013', 'name' => 'Avery');
$city_data[] = array('accid' => 'USID0014', 'name' => 'Bancroft');
$city_data[] = array('accid' => 'USID0015', 'name' => 'Banks');
$city_data[] = array('accid' => 'USID0016', 'name' => 'Basalt');
$city_data[] = array('accid' => 'USID0017', 'name' => 'Bayview');
$city_data[] = array('accid' => 'USID0018', 'name' => 'Bellevue');
$city_data[] = array('accid' => 'USID0019', 'name' => 'Bern');
$city_data[] = array('accid' => 'USID0020', 'name' => 'Blackfoot');
$city_data[] = array('accid' => 'USID0021', 'name' => 'Blanchard');
$city_data[] = array('accid' => 'USID0022', 'name' => 'Bliss');
$city_data[] = array('accid' => 'USID0023', 'name' => 'Bloomington');
$city_data[] = array('accid' => 'USID0025', 'name' => 'Boise');
$city_data[] = array('accid' => 'USID0026', 'name' => 'Bonners Ferry');
$city_data[] = array('accid' => 'USID0027', 'name' => 'Bovill');
$city_data[] = array('accid' => 'USID0028', 'name' => 'Bruneau');
$city_data[] = array('accid' => 'USID0029', 'name' => 'Buhl');
$city_data[] = array('accid' => 'USID0030', 'name' => 'Burley');
$city_data[] = array('accid' => 'USID0031', 'name' => 'Calder');
$city_data[] = array('accid' => 'USID0032', 'name' => 'Caldwell');
$city_data[] = array('accid' => 'USID0033', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'USID0034', 'name' => 'Carey');
$city_data[] = array('accid' => 'USID0035', 'name' => 'Careywood');
$city_data[] = array('accid' => 'USID0036', 'name' => 'Carmen');
$city_data[] = array('accid' => 'USID0037', 'name' => 'Cascade');
$city_data[] = array('accid' => 'USID0038', 'name' => 'Castleford');
$city_data[] = array('accid' => 'USID0039', 'name' => 'Cataldo');
$city_data[] = array('accid' => 'USID0040', 'name' => 'Challis');
$city_data[] = array('accid' => 'USID0041', 'name' => 'Chester');
$city_data[] = array('accid' => 'USID0042', 'name' => 'Clark Fork');
$city_data[] = array('accid' => 'USID0043', 'name' => 'Clarkia');
$city_data[] = array('accid' => 'USID0044', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USID0045', 'name' => 'Clifton');
$city_data[] = array('accid' => 'USID0046', 'name' => 'Cobalt');
$city_data[] = array('accid' => 'USID0047', 'name' => 'Cocolalla');
$city_data[] = array('accid' => 'USID0049', 'name' => 'Colburn');
$city_data[] = array('accid' => 'USID0050', 'name' => 'Conda');
$city_data[] = array('accid' => 'USID0051', 'name' => 'Coolin');
$city_data[] = array('accid' => 'USID0052', 'name' => 'Corral');
$city_data[] = array('accid' => 'USID0053', 'name' => 'Cottonwood');
$city_data[] = array('accid' => 'USID0054', 'name' => 'Council');
$city_data[] = array('accid' => 'USID0055', 'name' => 'Craigmont');
$city_data[] = array('accid' => 'USID0056', 'name' => 'Culdesac');
$city_data[] = array('accid' => 'USID0057', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USID0058', 'name' => 'Deary');
$city_data[] = array('accid' => 'USID0059', 'name' => 'Declo');
$city_data[] = array('accid' => 'USID0060', 'name' => 'Desmet');
$city_data[] = array('accid' => 'USID0061', 'name' => 'Dietrich');
$city_data[] = array('accid' => 'USID0062', 'name' => 'Dingle');
$city_data[] = array('accid' => 'USID0063', 'name' => 'Donnelly');
$city_data[] = array('accid' => 'USID0064', 'name' => 'Dover');
$city_data[] = array('accid' => 'USID0065', 'name' => 'Downey');
$city_data[] = array('accid' => 'USID0066', 'name' => 'Driggs');
$city_data[] = array('accid' => 'USID0067', 'name' => 'Dubois');
$city_data[] = array('accid' => 'USID0068', 'name' => 'Eagle');
$city_data[] = array('accid' => 'USID0069', 'name' => 'Eastport');
$city_data[] = array('accid' => 'USID0070', 'name' => 'Eden');
$city_data[] = array('accid' => 'USID0072', 'name' => 'Elk City-Golden');
$city_data[] = array('accid' => 'USID0073', 'name' => 'Elk River');
$city_data[] = array('accid' => 'USID0074', 'name' => 'Ellis');
$city_data[] = array('accid' => 'USID0075', 'name' => 'Emmett');
$city_data[] = array('accid' => 'USID0076', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USID0077', 'name' => 'Felt');
$city_data[] = array('accid' => 'USID0078', 'name' => 'Fenn');
$city_data[] = array('accid' => 'USID0079', 'name' => 'Ferdinand');
$city_data[] = array('accid' => 'USID0080', 'name' => 'Fernwood');
$city_data[] = array('accid' => 'USID0081', 'name' => 'Filer');
$city_data[] = array('accid' => 'USID0082', 'name' => 'Firth');
$city_data[] = array('accid' => 'USID0083', 'name' => 'Fish Haven');
$city_data[] = array('accid' => 'USID0084', 'name' => 'Fort Hall');
$city_data[] = array('accid' => 'USID0085', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USID0086', 'name' => 'Fruitland');
$city_data[] = array('accid' => 'USID0087', 'name' => 'Fruitvale');
$city_data[] = array('accid' => 'USID0088', 'name' => 'Garden Valley');
$city_data[] = array('accid' => 'USID0089', 'name' => 'Genesee');
$city_data[] = array('accid' => 'USID0090', 'name' => 'Geneva');
$city_data[] = array('accid' => 'USID0091', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USID0092', 'name' => 'Gibbonsville');
$city_data[] = array('accid' => 'USID0093', 'name' => 'Glenns Ferry');
$city_data[] = array('accid' => 'USID0094', 'name' => 'Gooding');
$city_data[] = array('accid' => 'USID0096', 'name' => 'Grace');
$city_data[] = array('accid' => 'USID0097', 'name' => 'Grand View');
$city_data[] = array('accid' => 'USID0098', 'name' => 'Grangeville');
$city_data[] = array('accid' => 'USID0100', 'name' => 'Greencreek');
$city_data[] = array('accid' => 'USID0101', 'name' => 'Greenleaf');
$city_data[] = array('accid' => 'USID0102', 'name' => 'Hagerman');
$city_data[] = array('accid' => 'USID0103', 'name' => 'Hailey');
$city_data[] = array('accid' => 'USID0104', 'name' => 'Hamer');
$city_data[] = array('accid' => 'USID0105', 'name' => 'Hammett');
$city_data[] = array('accid' => 'USID0106', 'name' => 'Hansen');
$city_data[] = array('accid' => 'USID0107', 'name' => 'Harrison');
$city_data[] = array('accid' => 'USID0108', 'name' => 'Harvard');
$city_data[] = array('accid' => 'USID0109', 'name' => 'Hayden');
$city_data[] = array('accid' => 'USID0110', 'name' => 'Hazelton');
$city_data[] = array('accid' => 'USID0111', 'name' => 'Heyburn');
$city_data[] = array('accid' => 'USID0112', 'name' => 'Hill City');
$city_data[] = array('accid' => 'USID0113', 'name' => 'Holbrook');
$city_data[] = array('accid' => 'USID0114', 'name' => 'Homedale');
$city_data[] = array('accid' => 'USID0115', 'name' => 'Hope');
$city_data[] = array('accid' => 'USID0116', 'name' => 'Horseshoe Bend');
$city_data[] = array('accid' => 'USID0117', 'name' => 'Howe');
$city_data[] = array('accid' => 'USID0118', 'name' => 'Huston');
$city_data[] = array('accid' => 'USID0119', 'name' => 'Idaho City');
$city_data[] = array('accid' => 'USID0120', 'name' => 'Idaho Falls');
$city_data[] = array('accid' => 'USID0121', 'name' => 'Indian Valley');
$city_data[] = array('accid' => 'USID0122', 'name' => 'Inkom');
$city_data[] = array('accid' => 'USID0123', 'name' => 'Iona');
$city_data[] = array('accid' => 'USID0124', 'name' => 'Irwin');
$city_data[] = array('accid' => 'USID0125', 'name' => 'Island Park');
$city_data[] = array('accid' => 'USID0126', 'name' => 'Jerome');
$city_data[] = array('accid' => 'USID0127', 'name' => 'Juliaetta');
$city_data[] = array('accid' => 'USID0128', 'name' => 'Kamiah');
$city_data[] = array('accid' => 'USID0129', 'name' => 'Kellogg');
$city_data[] = array('accid' => 'USID0130', 'name' => 'Kendrick');
$city_data[] = array('accid' => 'USID0131', 'name' => 'Ketchum');
$city_data[] = array('accid' => 'USID0132', 'name' => 'Kimberly');
$city_data[] = array('accid' => 'USID0133', 'name' => 'King Hill');
$city_data[] = array('accid' => 'USID0134', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USID0135', 'name' => 'Kooskia');
$city_data[] = array('accid' => 'USID0136', 'name' => 'Kootenai');
$city_data[] = array('accid' => 'USID0137', 'name' => 'Kuna');
$city_data[] = array('accid' => 'USID0138', 'name' => 'Laclede');
$city_data[] = array('accid' => 'USID0139', 'name' => 'Lake Fork');
$city_data[] = array('accid' => 'USID0140', 'name' => 'Lapwai');
$city_data[] = array('accid' => 'USID0141', 'name' => 'Lava Hot Springs');
$city_data[] = array('accid' => 'USID0142', 'name' => 'Leadore');
$city_data[] = array('accid' => 'USID0143', 'name' => 'Lemhi');
$city_data[] = array('accid' => 'USID0144', 'name' => 'Lenore');
$city_data[] = array('accid' => 'USID0145', 'name' => 'Letha');
$city_data[] = array('accid' => 'USID0146', 'name' => 'Lewiston');
$city_data[] = array('accid' => 'USID0147', 'name' => 'Lewisville');
$city_data[] = array('accid' => 'USID0148', 'name' => 'Lowman');
$city_data[] = array('accid' => 'USID0149', 'name' => 'Lucile');
$city_data[] = array('accid' => 'USID0150', 'name' => 'MacKay');
$city_data[] = array('accid' => 'USID0151', 'name' => 'Macks Inn');
$city_data[] = array('accid' => 'USID0152', 'name' => 'Malad City');
$city_data[] = array('accid' => 'USID0153', 'name' => 'Malta');
$city_data[] = array('accid' => 'USID0154', 'name' => 'Marsing');
$city_data[] = array('accid' => 'USID0155', 'name' => 'May');
$city_data[] = array('accid' => 'USID0156', 'name' => 'McCall');
$city_data[] = array('accid' => 'USID0157', 'name' => 'McCammon');
$city_data[] = array('accid' => 'USID0158', 'name' => 'Medimont');
$city_data[] = array('accid' => 'USID0159', 'name' => 'Melba');
$city_data[] = array('accid' => 'USID0160', 'name' => 'Menan');
$city_data[] = array('accid' => 'USID0161', 'name' => 'Meridian');
$city_data[] = array('accid' => 'USID0162', 'name' => 'Mesa');
$city_data[] = array('accid' => 'USID0163', 'name' => 'Middleton');
$city_data[] = array('accid' => 'USID0164', 'name' => 'Midvale');
$city_data[] = array('accid' => 'USID0165', 'name' => 'Minidoka');
$city_data[] = array('accid' => 'USID0166', 'name' => 'Monteview');
$city_data[] = array('accid' => 'USID0167', 'name' => 'Montpelier');
$city_data[] = array('accid' => 'USID0168', 'name' => 'Moore');
$city_data[] = array('accid' => 'USID0169', 'name' => 'Moreland');
$city_data[] = array('accid' => 'USID0170', 'name' => 'Moscow');
$city_data[] = array('accid' => 'USID0171', 'name' => 'Mountain Home');
$city_data[] = array('accid' => 'USID0173', 'name' => 'Moyie Springs');
$city_data[] = array('accid' => 'USID0174', 'name' => 'Mullan');
$city_data[] = array('accid' => 'USID0175', 'name' => 'Murphy');
$city_data[] = array('accid' => 'USID0176', 'name' => 'Murray');
$city_data[] = array('accid' => 'USID0177', 'name' => 'Murtaugh');
$city_data[] = array('accid' => 'USID0178', 'name' => 'Nampa');
$city_data[] = array('accid' => 'USID0179', 'name' => 'Naples');
$city_data[] = array('accid' => 'USID0180', 'name' => 'New Meadows');
$city_data[] = array('accid' => 'USID0181', 'name' => 'New Plymouth');
$city_data[] = array('accid' => 'USID0182', 'name' => 'Newdale');
$city_data[] = array('accid' => 'USID0183', 'name' => 'Nezperce');
$city_data[] = array('accid' => 'USID0184', 'name' => 'Nordman');
$city_data[] = array('accid' => 'USID0185', 'name' => 'North Fork');
$city_data[] = array('accid' => 'USID0186', 'name' => 'Notus');
$city_data[] = array('accid' => 'USID0187', 'name' => 'Oakley');
$city_data[] = array('accid' => 'USID0188', 'name' => 'Ola');
$city_data[] = array('accid' => 'USID0189', 'name' => 'Oldtown');
$city_data[] = array('accid' => 'USID0190', 'name' => 'Orofino');
$city_data[] = array('accid' => 'USID0191', 'name' => 'Osburn');
$city_data[] = array('accid' => 'USID0192', 'name' => 'Paris');
$city_data[] = array('accid' => 'USID0193', 'name' => 'Parker');
$city_data[] = array('accid' => 'USID0194', 'name' => 'Parma');
$city_data[] = array('accid' => 'USID0195', 'name' => 'Paul');
$city_data[] = array('accid' => 'USID0196', 'name' => 'Payette');
$city_data[] = array('accid' => 'USID0197', 'name' => 'Peck');
$city_data[] = array('accid' => 'USID0198', 'name' => 'Picabo');
$city_data[] = array('accid' => 'USID0199', 'name' => 'Pierce');
$city_data[] = array('accid' => 'USID0200', 'name' => 'Pinehurst');
$city_data[] = array('accid' => 'USID0201', 'name' => 'Pingree');
$city_data[] = array('accid' => 'USID0202', 'name' => 'Placerville');
$city_data[] = array('accid' => 'USID0203', 'name' => 'Plummer');
$city_data[] = array('accid' => 'USID0204', 'name' => 'Pocatello');
$city_data[] = array('accid' => 'USID0205', 'name' => 'Pollock');
$city_data[] = array('accid' => 'USID0206', 'name' => 'Ponderay');
$city_data[] = array('accid' => 'USID0207', 'name' => 'Porthill');
$city_data[] = array('accid' => 'USID0208', 'name' => 'Post Falls');
$city_data[] = array('accid' => 'USID0209', 'name' => 'Potlatch');
$city_data[] = array('accid' => 'USID0210', 'name' => 'Preston');
$city_data[] = array('accid' => 'USID0211', 'name' => 'Priest River');
$city_data[] = array('accid' => 'USID0212', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USID0213', 'name' => 'Rathdrum');
$city_data[] = array('accid' => 'USID0214', 'name' => 'Reubens');
$city_data[] = array('accid' => 'USID0215', 'name' => 'Rexburg');
$city_data[] = array('accid' => 'USID0216', 'name' => 'Richfield');
$city_data[] = array('accid' => 'USID0217', 'name' => 'Rigby');
$city_data[] = array('accid' => 'USID0218', 'name' => 'Riggins');
$city_data[] = array('accid' => 'USID0219', 'name' => 'Ririe');
$city_data[] = array('accid' => 'USID0220', 'name' => 'Roberts');
$city_data[] = array('accid' => 'USID0221', 'name' => 'Rockland');
$city_data[] = array('accid' => 'USID0222', 'name' => 'Rogerson');
$city_data[] = array('accid' => 'USID0223', 'name' => 'Rupert');
$city_data[] = array('accid' => 'USID0224', 'name' => 'Sagle');
$city_data[] = array('accid' => 'USID0225', 'name' => 'Saint Anthony');
$city_data[] = array('accid' => 'USID0226', 'name' => 'Saint Charles');
$city_data[] = array('accid' => 'USID0227', 'name' => 'Saint Maries');
$city_data[] = array('accid' => 'USID0228', 'name' => 'Salmon');
$city_data[] = array('accid' => 'USID0229', 'name' => 'Samuels');
$city_data[] = array('accid' => 'USID0230', 'name' => 'Sandpoint');
$city_data[] = array('accid' => 'USID0231', 'name' => 'Santa');
$city_data[] = array('accid' => 'USID0233', 'name' => 'Shelley');
$city_data[] = array('accid' => 'USID0234', 'name' => 'Shoshone');
$city_data[] = array('accid' => 'USID0235', 'name' => 'Shoup');
$city_data[] = array('accid' => 'USID0237', 'name' => 'Silverton');
$city_data[] = array('accid' => 'USID0238', 'name' => 'Smelterville');
$city_data[] = array('accid' => 'USID0240', 'name' => 'Soda Springs');
$city_data[] = array('accid' => 'USID0241', 'name' => 'Spalding');
$city_data[] = array('accid' => 'USID0242', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USID0243', 'name' => 'Spirit Lake');
$city_data[] = array('accid' => 'USID0244', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USID0245', 'name' => 'Squirrel');
$city_data[] = array('accid' => 'USID0246', 'name' => 'Stanley');
$city_data[] = array('accid' => 'USID0247', 'name' => 'Star');
$city_data[] = array('accid' => 'USID0248', 'name' => 'Stites');
$city_data[] = array('accid' => 'USID0249', 'name' => 'Stone');
$city_data[] = array('accid' => 'USID0250', 'name' => 'Sugar City');
$city_data[] = array('accid' => 'USID0251', 'name' => 'Sun Valley');
$city_data[] = array('accid' => 'USID0253', 'name' => 'Swan Valley');
$city_data[] = array('accid' => 'USID0254', 'name' => 'Swanlake');
$city_data[] = array('accid' => 'USID0255', 'name' => 'Sweet');
$city_data[] = array('accid' => 'USID0256', 'name' => 'Tendoy');
$city_data[] = array('accid' => 'USID0257', 'name' => 'Tensed');
$city_data[] = array('accid' => 'USID0258', 'name' => 'Terreton');
$city_data[] = array('accid' => 'USID0259', 'name' => 'Teton');
$city_data[] = array('accid' => 'USID0260', 'name' => 'Tetonia');
$city_data[] = array('accid' => 'USID0261', 'name' => 'Thatcher');
$city_data[] = array('accid' => 'USID0262', 'name' => 'Troy');
$city_data[] = array('accid' => 'USID0263', 'name' => 'Twin Falls');
$city_data[] = array('accid' => 'USID0264', 'name' => 'Ucon');
$city_data[] = array('accid' => 'USID0265', 'name' => 'Victor');
$city_data[] = array('accid' => 'USID0266', 'name' => 'Viola');
$city_data[] = array('accid' => 'USID0267', 'name' => 'Wallace');
$city_data[] = array('accid' => 'USID0268', 'name' => 'Warren');
$city_data[] = array('accid' => 'USID0269', 'name' => 'Wayan');
$city_data[] = array('accid' => 'USID0270', 'name' => 'Weippe');
$city_data[] = array('accid' => 'USID0271', 'name' => 'Weiser');
$city_data[] = array('accid' => 'USID0272', 'name' => 'Wendell');
$city_data[] = array('accid' => 'USID0273', 'name' => 'Weston');
$city_data[] = array('accid' => 'USID0274', 'name' => 'White Bird');
$city_data[] = array('accid' => 'USID0275', 'name' => 'Wilder');
$city_data[] = array('accid' => 'USID0276', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USID0277', 'name' => 'Worley');
$city_data[] = array('accid' => 'USID0278', 'name' => 'Yellow Pine');

?>
