<?php

// City package for USA: Illinois

$city_name = 'USA: Illinois';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USIL0001', 'name' => 'Abingdon');
$city_data[] = array('accid' => 'USIL0002', 'name' => 'Adair');
$city_data[] = array('accid' => 'USIL0003', 'name' => 'Addieville');
$city_data[] = array('accid' => 'USIL0004', 'name' => 'Addison');
$city_data[] = array('accid' => 'USIL0005', 'name' => 'Adrian');
$city_data[] = array('accid' => 'USIL0006', 'name' => 'Akin');
$city_data[] = array('accid' => 'USIL0007', 'name' => 'Albany');
$city_data[] = array('accid' => 'USIL0008', 'name' => 'Albers');
$city_data[] = array('accid' => 'USIL0009', 'name' => 'Albion');
$city_data[] = array('accid' => 'USIL0010', 'name' => 'Alden');
$city_data[] = array('accid' => 'USIL0011', 'name' => 'Aledo');
$city_data[] = array('accid' => 'USIL0012', 'name' => 'Alexander');
$city_data[] = array('accid' => 'USIL0013', 'name' => 'Alexis');
$city_data[] = array('accid' => 'USIL0014', 'name' => 'Algonquin');
$city_data[] = array('accid' => 'USIL0015', 'name' => 'Alhambra');
$city_data[] = array('accid' => 'USIL0016', 'name' => 'Allendale');
$city_data[] = array('accid' => 'USIL0017', 'name' => 'Allerton');
$city_data[] = array('accid' => 'USIL0018', 'name' => 'Alma');
$city_data[] = array('accid' => 'USIL0019', 'name' => 'Alpha');
$city_data[] = array('accid' => 'USIL0020', 'name' => 'Alsey');
$city_data[] = array('accid' => 'USIL0021', 'name' => 'Alsip');
$city_data[] = array('accid' => 'USIL0022', 'name' => 'Altamont');
$city_data[] = array('accid' => 'USIL0023', 'name' => 'Alto Pass');
$city_data[] = array('accid' => 'USIL0024', 'name' => 'Alton');
$city_data[] = array('accid' => 'USIL0025', 'name' => 'Altona');
$city_data[] = array('accid' => 'USIL0026', 'name' => 'Alvin');
$city_data[] = array('accid' => 'USIL0027', 'name' => 'Amboy');
$city_data[] = array('accid' => 'USIL0029', 'name' => 'Anchor');
$city_data[] = array('accid' => 'USIL0030', 'name' => 'Ancona');
$city_data[] = array('accid' => 'USIL0031', 'name' => 'Andalusia');
$city_data[] = array('accid' => 'USIL0032', 'name' => 'Andover');
$city_data[] = array('accid' => 'USIL0033', 'name' => 'Anna');
$city_data[] = array('accid' => 'USIL0034', 'name' => 'Annapolis');
$city_data[] = array('accid' => 'USIL0035', 'name' => 'Annawan');
$city_data[] = array('accid' => 'USIL0036', 'name' => 'Antioch');
$city_data[] = array('accid' => 'USIL0037', 'name' => 'Apple River');
$city_data[] = array('accid' => 'USIL0038', 'name' => 'Arcola');
$city_data[] = array('accid' => 'USIL0039', 'name' => 'Arenzville');
$city_data[] = array('accid' => 'USIL0040', 'name' => 'Argenta');
$city_data[] = array('accid' => 'USIL0041', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USIL0042', 'name' => 'Arlington Heights');
$city_data[] = array('accid' => 'USIL0043', 'name' => 'Armington');
$city_data[] = array('accid' => 'USIL0044', 'name' => 'Armstrong');
$city_data[] = array('accid' => 'USIL0045', 'name' => 'Aroma Park');
$city_data[] = array('accid' => 'USIL0046', 'name' => 'Arrowsmith');
$city_data[] = array('accid' => 'USIL0047', 'name' => 'Arthur');
$city_data[] = array('accid' => 'USIL0048', 'name' => 'Ashkum');
$city_data[] = array('accid' => 'USIL0049', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USIL0050', 'name' => 'Ashley');
$city_data[] = array('accid' => 'USIL0051', 'name' => 'Ashmore');
$city_data[] = array('accid' => 'USIL0052', 'name' => 'Ashton');
$city_data[] = array('accid' => 'USIL0053', 'name' => 'Assumption');
$city_data[] = array('accid' => 'USIL0054', 'name' => 'Astoria');
$city_data[] = array('accid' => 'USIL0055', 'name' => 'Athens');
$city_data[] = array('accid' => 'USIL0056', 'name' => 'Atkinson');
$city_data[] = array('accid' => 'USIL0057', 'name' => 'Atlanta');
$city_data[] = array('accid' => 'USIL0058', 'name' => 'Atwater');
$city_data[] = array('accid' => 'USIL0059', 'name' => 'Atwood');
$city_data[] = array('accid' => 'USIL0060', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USIL0061', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USIL0062', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USIL0063', 'name' => 'Ava');
$city_data[] = array('accid' => 'USIL0064', 'name' => 'Aviston');
$city_data[] = array('accid' => 'USIL0065', 'name' => 'Avon');
$city_data[] = array('accid' => 'USIL0066', 'name' => 'Baileyville');
$city_data[] = array('accid' => 'USIL0067', 'name' => 'Baldwin');
$city_data[] = array('accid' => 'USIL0068', 'name' => 'Bardolph');
$city_data[] = array('accid' => 'USIL0069', 'name' => 'Barnhill');
$city_data[] = array('accid' => 'USIL0070', 'name' => 'Barrington');
$city_data[] = array('accid' => 'USIL0071', 'name' => 'Barry');
$city_data[] = array('accid' => 'USIL0072', 'name' => 'Barstow');
$city_data[] = array('accid' => 'USIL0073', 'name' => 'Bartelso');
$city_data[] = array('accid' => 'USIL0074', 'name' => 'Bartlett');
$city_data[] = array('accid' => 'USIL0075', 'name' => 'Basco');
$city_data[] = array('accid' => 'USIL0076', 'name' => 'Batavia');
$city_data[] = array('accid' => 'USIL0077', 'name' => 'Batchtown');
$city_data[] = array('accid' => 'USIL0078', 'name' => 'Bath');
$city_data[] = array('accid' => 'USIL0079', 'name' => 'Baylis');
$city_data[] = array('accid' => 'USIL0080', 'name' => 'Beardstown');
$city_data[] = array('accid' => 'USIL0081', 'name' => 'Beason');
$city_data[] = array('accid' => 'USIL0082', 'name' => 'Beaverville');
$city_data[] = array('accid' => 'USIL0083', 'name' => 'Beckemeyer');
$city_data[] = array('accid' => 'USIL0084', 'name' => 'Bedford Park');
$city_data[] = array('accid' => 'USIL0085', 'name' => 'Beecher');
$city_data[] = array('accid' => 'USIL0086', 'name' => 'Beecher City');
$city_data[] = array('accid' => 'USIL0087', 'name' => 'Belknap');
$city_data[] = array('accid' => 'USIL0088', 'name' => 'Belle Rive');
$city_data[] = array('accid' => 'USIL0089', 'name' => 'Belleville');
$city_data[] = array('accid' => 'USIL0090', 'name' => 'Bellflower');
$city_data[] = array('accid' => 'USIL0091', 'name' => 'Bellmont');
$city_data[] = array('accid' => 'USIL0092', 'name' => 'Bellwood');
$city_data[] = array('accid' => 'USIL0093', 'name' => 'Belvidere');
$city_data[] = array('accid' => 'USIL0094', 'name' => 'Bement');
$city_data[] = array('accid' => 'USIL0095', 'name' => 'Benld');
$city_data[] = array('accid' => 'USIL0096', 'name' => 'Bensenville');
$city_data[] = array('accid' => 'USIL0097', 'name' => 'Benson');
$city_data[] = array('accid' => 'USIL0098', 'name' => 'Benton');
$city_data[] = array('accid' => 'USIL0099', 'name' => 'Berkeley');
$city_data[] = array('accid' => 'USIL0100', 'name' => 'Berwick');
$city_data[] = array('accid' => 'USIL0101', 'name' => 'Berwyn');
$city_data[] = array('accid' => 'USIL0102', 'name' => 'Bethalto');
$city_data[] = array('accid' => 'USIL0103', 'name' => 'Bethany');
$city_data[] = array('accid' => 'USIL0104', 'name' => 'Big Rock');
$city_data[] = array('accid' => 'USIL0105', 'name' => 'Biggsville');
$city_data[] = array('accid' => 'USIL0106', 'name' => 'Bingham');
$city_data[] = array('accid' => 'USIL0107', 'name' => 'Birds');
$city_data[] = array('accid' => 'USIL0108', 'name' => 'Bishop Hill');
$city_data[] = array('accid' => 'USIL0109', 'name' => 'Bismarck');
$city_data[] = array('accid' => 'USIL0110', 'name' => 'Blackstone');
$city_data[] = array('accid' => 'USIL0111', 'name' => 'Blandinsville');
$city_data[] = array('accid' => 'USIL0112', 'name' => 'Bloomingdale');
$city_data[] = array('accid' => 'USIL0113', 'name' => 'Bloomington');
$city_data[] = array('accid' => 'USIL0114', 'name' => 'Blue Island');
$city_data[] = array('accid' => 'USIL0115', 'name' => 'Blue Mound');
$city_data[] = array('accid' => 'USIL0116', 'name' => 'Bluff Springs');
$city_data[] = array('accid' => 'USIL0117', 'name' => 'Bluffs');
$city_data[] = array('accid' => 'USIL0118', 'name' => 'Bluford');
$city_data[] = array('accid' => 'USIL0119', 'name' => 'Boles');
$city_data[] = array('accid' => 'USIL0120', 'name' => 'Bolingbrook');
$city_data[] = array('accid' => 'USIL0121', 'name' => 'Bondville');
$city_data[] = array('accid' => 'USIL0122', 'name' => 'Bone Gap');
$city_data[] = array('accid' => 'USIL0123', 'name' => 'Bonfield');
$city_data[] = array('accid' => 'USIL0124', 'name' => 'Bonnie');
$city_data[] = array('accid' => 'USIL0125', 'name' => 'Boody');
$city_data[] = array('accid' => 'USIL0126', 'name' => 'Bourbonnais');
$city_data[] = array('accid' => 'USIL0127', 'name' => 'Bowen');
$city_data[] = array('accid' => 'USIL0128', 'name' => 'Braceville');
$city_data[] = array('accid' => 'USIL0129', 'name' => 'Bradford');
$city_data[] = array('accid' => 'USIL0130', 'name' => 'Bradley');
$city_data[] = array('accid' => 'USIL0131', 'name' => 'Braidwood');
$city_data[] = array('accid' => 'USIL0132', 'name' => 'Breese');
$city_data[] = array('accid' => 'USIL0133', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USIL0134', 'name' => 'Bridgeview');
$city_data[] = array('accid' => 'USIL0135', 'name' => 'Brighton');
$city_data[] = array('accid' => 'USIL0136', 'name' => 'Brimfield');
$city_data[] = array('accid' => 'USIL0137', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USIL0138', 'name' => 'Broadlands');
$city_data[] = array('accid' => 'USIL0139', 'name' => 'Brocton');
$city_data[] = array('accid' => 'USIL0140', 'name' => 'Brookfield');
$city_data[] = array('accid' => 'USIL0141', 'name' => 'Brookport');
$city_data[] = array('accid' => 'USIL0142', 'name' => 'Broughton');
$city_data[] = array('accid' => 'USIL0143', 'name' => 'Browning');
$city_data[] = array('accid' => 'USIL0144', 'name' => 'Browns');
$city_data[] = array('accid' => 'USIL0145', 'name' => 'Brownstown');
$city_data[] = array('accid' => 'USIL0146', 'name' => 'Brussels');
$city_data[] = array('accid' => 'USIL0147', 'name' => 'Bryant');
$city_data[] = array('accid' => 'USIL0148', 'name' => 'Buckingham');
$city_data[] = array('accid' => 'USIL0149', 'name' => 'Buckley');
$city_data[] = array('accid' => 'USIL0150', 'name' => 'Buckner');
$city_data[] = array('accid' => 'USIL0151', 'name' => 'Buda');
$city_data[] = array('accid' => 'USIL0152', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USIL0153', 'name' => 'Buffalo Grove');
$city_data[] = array('accid' => 'USIL0154', 'name' => 'Buffalo Prairie');
$city_data[] = array('accid' => 'USIL0155', 'name' => 'Bulpitt');
$city_data[] = array('accid' => 'USIL0156', 'name' => 'Buncombe');
$city_data[] = array('accid' => 'USIL0157', 'name' => 'Bunker Hill');
$city_data[] = array('accid' => 'USIL0158', 'name' => 'Burbank');
$city_data[] = array('accid' => 'USIL0159', 'name' => 'Bureau');
$city_data[] = array('accid' => 'USIL0160', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USIL0161', 'name' => 'Burnside');
$city_data[] = array('accid' => 'USIL0162', 'name' => 'Burnt Prairie');
$city_data[] = array('accid' => 'USIL0163', 'name' => 'Bushnell');
$city_data[] = array('accid' => 'USIL0164', 'name' => 'Butler');
$city_data[] = array('accid' => 'USIL0165', 'name' => 'Byron');
$city_data[] = array('accid' => 'USIL0166', 'name' => 'Cabery');
$city_data[] = array('accid' => 'USIL0167', 'name' => 'Cache');
$city_data[] = array('accid' => 'USIL0168', 'name' => 'Cairo');
$city_data[] = array('accid' => 'USIL0169', 'name' => 'Caledonia');
$city_data[] = array('accid' => 'USIL0170', 'name' => 'Calhoun');
$city_data[] = array('accid' => 'USIL0171', 'name' => 'Calumet City');
$city_data[] = array('accid' => 'USIL0172', 'name' => 'Camargo');
$city_data[] = array('accid' => 'USIL0173', 'name' => 'Cambria');
$city_data[] = array('accid' => 'USIL0174', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'USIL0175', 'name' => 'Camden');
$city_data[] = array('accid' => 'USIL0176', 'name' => 'Cameron');
$city_data[] = array('accid' => 'USIL0177', 'name' => 'Camp Grove');
$city_data[] = array('accid' => 'USIL0178', 'name' => 'Camp Point');
$city_data[] = array('accid' => 'USIL0179', 'name' => 'Campbell Hill');
$city_data[] = array('accid' => 'USIL0180', 'name' => 'Campus');
$city_data[] = array('accid' => 'USIL0181', 'name' => 'Canton');
$city_data[] = array('accid' => 'USIL0182', 'name' => 'Cantrall');
$city_data[] = array('accid' => 'USIL0183', 'name' => 'Capron');
$city_data[] = array('accid' => 'USIL0184', 'name' => 'Carbon Cliff');
$city_data[] = array('accid' => 'USIL0185', 'name' => 'Carbondale');
$city_data[] = array('accid' => 'USIL0186', 'name' => 'Carlinville');
$city_data[] = array('accid' => 'USIL0187', 'name' => 'Carlock');
$city_data[] = array('accid' => 'USIL0188', 'name' => 'Carlyle');
$city_data[] = array('accid' => 'USIL0189', 'name' => 'Carman');
$city_data[] = array('accid' => 'USIL0190', 'name' => 'Carmi');
$city_data[] = array('accid' => 'USIL0191', 'name' => 'Carol Stream');
$city_data[] = array('accid' => 'USIL0192', 'name' => 'Carpentersville');
$city_data[] = array('accid' => 'USIL0193', 'name' => 'Carrier Mills');
$city_data[] = array('accid' => 'USIL0194', 'name' => 'Carrollton');
$city_data[] = array('accid' => 'USIL0195', 'name' => 'Carterville');
$city_data[] = array('accid' => 'USIL0196', 'name' => 'Carthage');
$city_data[] = array('accid' => 'USIL0197', 'name' => 'Cary');
$city_data[] = array('accid' => 'USIL0198', 'name' => 'Casey');
$city_data[] = array('accid' => 'USIL0199', 'name' => 'Caseyville');
$city_data[] = array('accid' => 'USIL0200', 'name' => 'Castleton');
$city_data[] = array('accid' => 'USIL0201', 'name' => 'Catlin');
$city_data[] = array('accid' => 'USIL0202', 'name' => 'Cave In Rock');
$city_data[] = array('accid' => 'USIL0203', 'name' => 'Cedar Point');
$city_data[] = array('accid' => 'USIL0204', 'name' => 'Cedarville');
$city_data[] = array('accid' => 'USIL0205', 'name' => 'Centralia');
$city_data[] = array('accid' => 'USIL0206', 'name' => 'Cerro Gordo');
$city_data[] = array('accid' => 'USIL0207', 'name' => 'Chadwick');
$city_data[] = array('accid' => 'USIL0208', 'name' => 'Chambersburg');
$city_data[] = array('accid' => 'USIL0209', 'name' => 'Champaign');
$city_data[] = array('accid' => 'USIL0210', 'name' => 'Chana');
$city_data[] = array('accid' => 'USIL0211', 'name' => 'Chandlerville');
$city_data[] = array('accid' => 'USIL0212', 'name' => 'Channahon');
$city_data[] = array('accid' => 'USIL0213', 'name' => 'Chapin');
$city_data[] = array('accid' => 'USIL0214', 'name' => 'Charleston');
$city_data[] = array('accid' => 'USIL0215', 'name' => 'Chatham');
$city_data[] = array('accid' => 'USIL0216', 'name' => 'Chatsworth');
$city_data[] = array('accid' => 'USIL0217', 'name' => 'Chebanse');
$city_data[] = array('accid' => 'USIL0218', 'name' => 'Chenoa');
$city_data[] = array('accid' => 'USIL0219', 'name' => 'Cherry');
$city_data[] = array('accid' => 'USIL0220', 'name' => 'Cherry Valley');
$city_data[] = array('accid' => 'USIL0221', 'name' => 'Chester');
$city_data[] = array('accid' => 'USIL0222', 'name' => 'Chesterfield');
$city_data[] = array('accid' => 'USIL0223', 'name' => 'Chestnut');
$city_data[] = array('accid' => 'USIL0225', 'name' => 'Chicago');
$city_data[] = array('accid' => 'USIL0226', 'name' => 'Chicago Heights');
$city_data[] = array('accid' => 'USIL0227', 'name' => 'Chicago Ridge');
$city_data[] = array('accid' => 'USIL0230', 'name' => 'Chicago O\'Hare International Airport');
$city_data[] = array('accid' => 'USIL0231', 'name' => 'Chillicothe');
$city_data[] = array('accid' => 'USIL0232', 'name' => 'Chrisman');
$city_data[] = array('accid' => 'USIL0233', 'name' => 'Christopher');
$city_data[] = array('accid' => 'USIL0234', 'name' => 'Cicero');
$city_data[] = array('accid' => 'USIL0235', 'name' => 'Cisco');
$city_data[] = array('accid' => 'USIL0236', 'name' => 'Cisne');
$city_data[] = array('accid' => 'USIL0237', 'name' => 'Cissna Park');
$city_data[] = array('accid' => 'USIL0238', 'name' => 'Clare');
$city_data[] = array('accid' => 'USIL0239', 'name' => 'Claremont');
$city_data[] = array('accid' => 'USIL0240', 'name' => 'Clarendon Hills');
$city_data[] = array('accid' => 'USIL0241', 'name' => 'Clay City');
$city_data[] = array('accid' => 'USIL0242', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USIL0243', 'name' => 'Claytonville');
$city_data[] = array('accid' => 'USIL0244', 'name' => 'Clifton');
$city_data[] = array('accid' => 'USIL0245', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USIL0246', 'name' => 'Coal City');
$city_data[] = array('accid' => 'USIL0247', 'name' => 'Coal Valley');
$city_data[] = array('accid' => 'USIL0248', 'name' => 'Coatsburg');
$city_data[] = array('accid' => 'USIL0249', 'name' => 'Cobden');
$city_data[] = array('accid' => 'USIL0250', 'name' => 'Coello');
$city_data[] = array('accid' => 'USIL0251', 'name' => 'Coffeen');
$city_data[] = array('accid' => 'USIL0252', 'name' => 'Colchester');
$city_data[] = array('accid' => 'USIL0253', 'name' => 'Coleta');
$city_data[] = array('accid' => 'USIL0254', 'name' => 'Colfax');
$city_data[] = array('accid' => 'USIL0255', 'name' => 'Collinsville');
$city_data[] = array('accid' => 'USIL0256', 'name' => 'Collison');
$city_data[] = array('accid' => 'USIL0257', 'name' => 'Colona');
$city_data[] = array('accid' => 'USIL0258', 'name' => 'Colp');
$city_data[] = array('accid' => 'USIL0259', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USIL0260', 'name' => 'Colusa');
$city_data[] = array('accid' => 'USIL0261', 'name' => 'Compton');
$city_data[] = array('accid' => 'USIL0262', 'name' => 'Concord');
$city_data[] = array('accid' => 'USIL0263', 'name' => 'Congerville');
$city_data[] = array('accid' => 'USIL0264', 'name' => 'Cooksville');
$city_data[] = array('accid' => 'USIL0265', 'name' => 'Cordova');
$city_data[] = array('accid' => 'USIL0266', 'name' => 'Cornell');
$city_data[] = array('accid' => 'USIL0267', 'name' => 'Cornland');
$city_data[] = array('accid' => 'USIL0268', 'name' => 'Cortland');
$city_data[] = array('accid' => 'USIL0269', 'name' => 'Cottage Hills');
$city_data[] = array('accid' => 'USIL0270', 'name' => 'Coulterville');
$city_data[] = array('accid' => 'USIL0271', 'name' => 'Country Club Hills');
$city_data[] = array('accid' => 'USIL0272', 'name' => 'Cowden');
$city_data[] = array('accid' => 'USIL0273', 'name' => 'Creal Springs');
$city_data[] = array('accid' => 'USIL0274', 'name' => 'Crescent City');
$city_data[] = array('accid' => 'USIL0275', 'name' => 'Creston');
$city_data[] = array('accid' => 'USIL0276', 'name' => 'Crete');
$city_data[] = array('accid' => 'USIL0277', 'name' => 'Creve Coeur');
$city_data[] = array('accid' => 'USIL0278', 'name' => 'Cropsey');
$city_data[] = array('accid' => 'USIL0279', 'name' => 'Crossville');
$city_data[] = array('accid' => 'USIL0280', 'name' => 'Crystal Lake');
$city_data[] = array('accid' => 'USIL0281', 'name' => 'Cuba');
$city_data[] = array('accid' => 'USIL0282', 'name' => 'Cullom');
$city_data[] = array('accid' => 'USIL0283', 'name' => 'Cutler');
$city_data[] = array('accid' => 'USIL0284', 'name' => 'Cypress');
$city_data[] = array('accid' => 'USIL0285', 'name' => 'Dahinda');
$city_data[] = array('accid' => 'USIL0286', 'name' => 'Dahlgren');
$city_data[] = array('accid' => 'USIL0287', 'name' => 'Dakota');
$city_data[] = array('accid' => 'USIL0288', 'name' => 'Dale');
$city_data[] = array('accid' => 'USIL0289', 'name' => 'Dallas City');
$city_data[] = array('accid' => 'USIL0290', 'name' => 'Dalton City');
$city_data[] = array('accid' => 'USIL0291', 'name' => 'Dalzell');
$city_data[] = array('accid' => 'USIL0292', 'name' => 'Dana');
$city_data[] = array('accid' => 'USIL0293', 'name' => 'Danforth');
$city_data[] = array('accid' => 'USIL0294', 'name' => 'Danvers');
$city_data[] = array('accid' => 'USIL0295', 'name' => 'Danville');
$city_data[] = array('accid' => 'USIL0296', 'name' => 'Darien');
$city_data[] = array('accid' => 'USIL0297', 'name' => 'Davis');
$city_data[] = array('accid' => 'USIL0298', 'name' => 'Davis Junction');
$city_data[] = array('accid' => 'USIL0299', 'name' => 'Dawson');
$city_data[] = array('accid' => 'USIL0300', 'name' => 'De Land');
$city_data[] = array('accid' => 'USIL0301', 'name' => 'De Soto');
$city_data[] = array('accid' => 'USIL0302', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USIL0303', 'name' => 'Deer Creek');
$city_data[] = array('accid' => 'USIL0304', 'name' => 'Deer Grove');
$city_data[] = array('accid' => 'USIL0305', 'name' => 'Deerfield');
$city_data[] = array('accid' => 'USIL0306', 'name' => 'DeKalb');
$city_data[] = array('accid' => 'USIL0307', 'name' => 'Delavan');
$city_data[] = array('accid' => 'USIL0308', 'name' => 'Dennison');
$city_data[] = array('accid' => 'USIL0309', 'name' => 'Depue');
$city_data[] = array('accid' => 'USIL0310', 'name' => 'Des Plaines');
$city_data[] = array('accid' => 'USIL0311', 'name' => 'Dewey');
$city_data[] = array('accid' => 'USIL0312', 'name' => 'Dewitt');
$city_data[] = array('accid' => 'USIL0313', 'name' => 'Dieterich');
$city_data[] = array('accid' => 'USIL0314', 'name' => 'Divernon');
$city_data[] = array('accid' => 'USIL0315', 'name' => 'Dix');
$city_data[] = array('accid' => 'USIL0316', 'name' => 'Dixon');
$city_data[] = array('accid' => 'USIL0317', 'name' => 'Dolton');
$city_data[] = array('accid' => 'USIL0318', 'name' => 'Dongola');
$city_data[] = array('accid' => 'USIL0319', 'name' => 'Donnellson');
$city_data[] = array('accid' => 'USIL0320', 'name' => 'Donovan');
$city_data[] = array('accid' => 'USIL0321', 'name' => 'Dorsey');
$city_data[] = array('accid' => 'USIL0322', 'name' => 'Dover');
$city_data[] = array('accid' => 'USIL0323', 'name' => 'Dow');
$city_data[] = array('accid' => 'USIL0324', 'name' => 'Dowell');
$city_data[] = array('accid' => 'USIL0325', 'name' => 'Downers Grove');
$city_data[] = array('accid' => 'USIL0326', 'name' => 'Downs');
$city_data[] = array('accid' => 'USIL0327', 'name' => 'Du Bois');
$city_data[] = array('accid' => 'USIL0328', 'name' => 'Du Quoin');
$city_data[] = array('accid' => 'USIL0329', 'name' => 'Dundas');
$city_data[] = array('accid' => 'USIL0330', 'name' => 'Dundee');
$city_data[] = array('accid' => 'USIL0331', 'name' => 'Dunfermline');
$city_data[] = array('accid' => 'USIL0332', 'name' => 'Dunlap');
$city_data[] = array('accid' => 'USIL0333', 'name' => 'Dupo');
$city_data[] = array('accid' => 'USIL0334', 'name' => 'Durand');
$city_data[] = array('accid' => 'USIL0335', 'name' => 'Dwight');
$city_data[] = array('accid' => 'USIL0336', 'name' => 'Eagarville');
$city_data[] = array('accid' => 'USIL0337', 'name' => 'Earlville');
$city_data[] = array('accid' => 'USIL0338', 'name' => 'East Alton');
$city_data[] = array('accid' => 'USIL0339', 'name' => 'East Carondelet');
$city_data[] = array('accid' => 'USIL0340', 'name' => 'East Dubuque');
$city_data[] = array('accid' => 'USIL0341', 'name' => 'East Galesburg');
$city_data[] = array('accid' => 'USIL0342', 'name' => 'East Lynn');
$city_data[] = array('accid' => 'USIL0343', 'name' => 'East Moline');
$city_data[] = array('accid' => 'USIL0344', 'name' => 'East Peoria');
$city_data[] = array('accid' => 'USIL0345', 'name' => 'East Saint Louis');
$city_data[] = array('accid' => 'USIL0346', 'name' => 'Easton');
$city_data[] = array('accid' => 'USIL0347', 'name' => 'Eddyville');
$city_data[] = array('accid' => 'USIL0348', 'name' => 'Edelstein');
$city_data[] = array('accid' => 'USIL0349', 'name' => 'Edgewood');
$city_data[] = array('accid' => 'USIL0350', 'name' => 'Edinburg');
$city_data[] = array('accid' => 'USIL0351', 'name' => 'Edwards');
$city_data[] = array('accid' => 'USIL0352', 'name' => 'Edwardsville');
$city_data[] = array('accid' => 'USIL0353', 'name' => 'Effingham');
$city_data[] = array('accid' => 'USIL0354', 'name' => 'El Paso');
$city_data[] = array('accid' => 'USIL0355', 'name' => 'Elburn');
$city_data[] = array('accid' => 'USIL0356', 'name' => 'Eldena');
$city_data[] = array('accid' => 'USIL0357', 'name' => 'Eldorado');
$city_data[] = array('accid' => 'USIL0358', 'name' => 'Eldred');
$city_data[] = array('accid' => 'USIL0359', 'name' => 'Eleroy');
$city_data[] = array('accid' => 'USIL0360', 'name' => 'Elgin');
$city_data[] = array('accid' => 'USIL0361', 'name' => 'Elizabeth');
$city_data[] = array('accid' => 'USIL0362', 'name' => 'Elizabethtown');
$city_data[] = array('accid' => 'USIL0363', 'name' => 'Elk Grove Village');
$city_data[] = array('accid' => 'USIL0364', 'name' => 'Elkhart');
$city_data[] = array('accid' => 'USIL0365', 'name' => 'Elkville');
$city_data[] = array('accid' => 'USIL0366', 'name' => 'Ellery');
$city_data[] = array('accid' => 'USIL0367', 'name' => 'Elliott');
$city_data[] = array('accid' => 'USIL0368', 'name' => 'Ellis Grove');
$city_data[] = array('accid' => 'USIL0369', 'name' => 'Ellisville');
$city_data[] = array('accid' => 'USIL0370', 'name' => 'Ellsworth');
$city_data[] = array('accid' => 'USIL0371', 'name' => 'Elmhurst');
$city_data[] = array('accid' => 'USIL0372', 'name' => 'Elmwood');
$city_data[] = array('accid' => 'USIL0373', 'name' => 'Elmwood Park');
$city_data[] = array('accid' => 'USIL0374', 'name' => 'Elsah');
$city_data[] = array('accid' => 'USIL0375', 'name' => 'Elvaston');
$city_data[] = array('accid' => 'USIL0376', 'name' => 'Elwin');
$city_data[] = array('accid' => 'USIL0377', 'name' => 'Elwood');
$city_data[] = array('accid' => 'USIL0378', 'name' => 'Emden');
$city_data[] = array('accid' => 'USIL0379', 'name' => 'Emington');
$city_data[] = array('accid' => 'USIL0380', 'name' => 'Emma');
$city_data[] = array('accid' => 'USIL0381', 'name' => 'Energy');
$city_data[] = array('accid' => 'USIL0382', 'name' => 'Enfield');
$city_data[] = array('accid' => 'USIL0383', 'name' => 'Eola');
$city_data[] = array('accid' => 'USIL0384', 'name' => 'Equality');
$city_data[] = array('accid' => 'USIL0385', 'name' => 'Erie');
$city_data[] = array('accid' => 'USIL0386', 'name' => 'Esmond');
$city_data[] = array('accid' => 'USIL0387', 'name' => 'Essex');
$city_data[] = array('accid' => 'USIL0388', 'name' => 'Eureka');
$city_data[] = array('accid' => 'USIL0389', 'name' => 'Evanston');
$city_data[] = array('accid' => 'USIL0390', 'name' => 'Evansville');
$city_data[] = array('accid' => 'USIL0391', 'name' => 'Evergreen Park');
$city_data[] = array('accid' => 'USIL0392', 'name' => 'Ewing');
$city_data[] = array('accid' => 'USIL0393', 'name' => 'Fairbury');
$city_data[] = array('accid' => 'USIL0394', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USIL0395', 'name' => 'Fairmount');
$city_data[] = array('accid' => 'USIL0396', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USIL0397', 'name' => 'Fairview Heights');
$city_data[] = array('accid' => 'USIL0398', 'name' => 'Farina');
$city_data[] = array('accid' => 'USIL0399', 'name' => 'Farmer City');
$city_data[] = array('accid' => 'USIL0400', 'name' => 'Farmersville');
$city_data[] = array('accid' => 'USIL0401', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USIL0402', 'name' => 'Fenton');
$city_data[] = array('accid' => 'USIL0403', 'name' => 'Ferris');
$city_data[] = array('accid' => 'USIL0404', 'name' => 'Fiatt');
$city_data[] = array('accid' => 'USIL0405', 'name' => 'Fidelity');
$city_data[] = array('accid' => 'USIL0406', 'name' => 'Fieldon');
$city_data[] = array('accid' => 'USIL0407', 'name' => 'Fillmore');
$city_data[] = array('accid' => 'USIL0408', 'name' => 'Findlay');
$city_data[] = array('accid' => 'USIL0409', 'name' => 'Fisher');
$city_data[] = array('accid' => 'USIL0410', 'name' => 'Fithian');
$city_data[] = array('accid' => 'USIL0411', 'name' => 'Flanagan');
$city_data[] = array('accid' => 'USIL0412', 'name' => 'Flat Rock');
$city_data[] = array('accid' => 'USIL0413', 'name' => 'Flora');
$city_data[] = array('accid' => 'USIL0414', 'name' => 'Flossmoor');
$city_data[] = array('accid' => 'USIL0415', 'name' => 'Foosland');
$city_data[] = array('accid' => 'USIL0416', 'name' => 'Forest City');
$city_data[] = array('accid' => 'USIL0417', 'name' => 'Forest Park');
$city_data[] = array('accid' => 'USIL0418', 'name' => 'Forrest');
$city_data[] = array('accid' => 'USIL0419', 'name' => 'Forreston');
$city_data[] = array('accid' => 'USIL0420', 'name' => 'Forsyth');
$city_data[] = array('accid' => 'USIL0421', 'name' => 'Fort Sheridan');
$city_data[] = array('accid' => 'USIL0422', 'name' => 'Fowler');
$city_data[] = array('accid' => 'USIL0423', 'name' => 'Fox Lake');
$city_data[] = array('accid' => 'USIL0424', 'name' => 'Fox River Grove');
$city_data[] = array('accid' => 'USIL0425', 'name' => 'Fox Valley');
$city_data[] = array('accid' => 'USIL0426', 'name' => 'Frankfort');
$city_data[] = array('accid' => 'USIL0427', 'name' => 'Frankfort Heights');
$city_data[] = array('accid' => 'USIL0428', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USIL0429', 'name' => 'Franklin Grove');
$city_data[] = array('accid' => 'USIL0430', 'name' => 'Franklin Park');
$city_data[] = array('accid' => 'USIL0431', 'name' => 'Frederick');
$city_data[] = array('accid' => 'USIL0432', 'name' => 'Freeburg');
$city_data[] = array('accid' => 'USIL0433', 'name' => 'Freeman Spur');
$city_data[] = array('accid' => 'USIL0434', 'name' => 'Freeport');
$city_data[] = array('accid' => 'USIL0435', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USIL0436', 'name' => 'Fults');
$city_data[] = array('accid' => 'USIL0437', 'name' => 'Galatia');
$city_data[] = array('accid' => 'USIL0438', 'name' => 'Galena');
$city_data[] = array('accid' => 'USIL0439', 'name' => 'Galesburg');
$city_data[] = array('accid' => 'USIL0440', 'name' => 'Galt');
$city_data[] = array('accid' => 'USIL0441', 'name' => 'Galva');
$city_data[] = array('accid' => 'USIL0442', 'name' => 'Garden Prairie');
$city_data[] = array('accid' => 'USIL0443', 'name' => 'Gardner');
$city_data[] = array('accid' => 'USIL0444', 'name' => 'Gays');
$city_data[] = array('accid' => 'USIL0445', 'name' => 'Geff');
$city_data[] = array('accid' => 'USIL0446', 'name' => 'Geneseo');
$city_data[] = array('accid' => 'USIL0447', 'name' => 'Geneva');
$city_data[] = array('accid' => 'USIL0448', 'name' => 'Genoa');
$city_data[] = array('accid' => 'USIL0449', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USIL0450', 'name' => 'Gerlaw');
$city_data[] = array('accid' => 'USIL0451', 'name' => 'German Valley');
$city_data[] = array('accid' => 'USIL0452', 'name' => 'Germantown');
$city_data[] = array('accid' => 'USIL0453', 'name' => 'Gibson City');
$city_data[] = array('accid' => 'USIL0454', 'name' => 'Gifford');
$city_data[] = array('accid' => 'USIL0455', 'name' => 'Gilberts');
$city_data[] = array('accid' => 'USIL0456', 'name' => 'Gillespie');
$city_data[] = array('accid' => 'USIL0457', 'name' => 'Gilman');
$city_data[] = array('accid' => 'USIL0458', 'name' => 'Gilson');
$city_data[] = array('accid' => 'USIL0459', 'name' => 'Girard');
$city_data[] = array('accid' => 'USIL0460', 'name' => 'Gladstone');
$city_data[] = array('accid' => 'USIL0461', 'name' => 'Glasford');
$city_data[] = array('accid' => 'USIL0462', 'name' => 'Glen Carbon');
$city_data[] = array('accid' => 'USIL0463', 'name' => 'Glen Ellyn');
$city_data[] = array('accid' => 'USIL0464', 'name' => 'Glenarm');
$city_data[] = array('accid' => 'USIL0465', 'name' => 'Glencoe');
$city_data[] = array('accid' => 'USIL0466', 'name' => 'Glendale Heights');
$city_data[] = array('accid' => 'USIL0467', 'name' => 'Glenview');
$city_data[] = array('accid' => 'USIL0468', 'name' => 'Glenview NAS');
$city_data[] = array('accid' => 'USIL0469', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USIL0470', 'name' => 'Godfrey');
$city_data[] = array('accid' => 'USIL0471', 'name' => 'Golconda');
$city_data[] = array('accid' => 'USIL0472', 'name' => 'Golden');
$city_data[] = array('accid' => 'USIL0473', 'name' => 'Golden Eagle');
$city_data[] = array('accid' => 'USIL0474', 'name' => 'Golden Gate');
$city_data[] = array('accid' => 'USIL0475', 'name' => 'Golf');
$city_data[] = array('accid' => 'USIL0476', 'name' => 'Good Hope');
$city_data[] = array('accid' => 'USIL0477', 'name' => 'Goodfield');
$city_data[] = array('accid' => 'USIL0478', 'name' => 'Goodwine');
$city_data[] = array('accid' => 'USIL0479', 'name' => 'Goreville');
$city_data[] = array('accid' => 'USIL0480', 'name' => 'Gorham');
$city_data[] = array('accid' => 'USIL0481', 'name' => 'Grafton');
$city_data[] = array('accid' => 'USIL0482', 'name' => 'Grand Chain');
$city_data[] = array('accid' => 'USIL0483', 'name' => 'Grand Ridge');
$city_data[] = array('accid' => 'USIL0484', 'name' => 'Grand Tower');
$city_data[] = array('accid' => 'USIL0485', 'name' => 'Granite City');
$city_data[] = array('accid' => 'USIL0486', 'name' => 'Grant Park');
$city_data[] = array('accid' => 'USIL0487', 'name' => 'Grantsburg');
$city_data[] = array('accid' => 'USIL0488', 'name' => 'Granville');
$city_data[] = array('accid' => 'USIL0489', 'name' => 'Graymont');
$city_data[] = array('accid' => 'USIL0490', 'name' => 'Grayslake');
$city_data[] = array('accid' => 'USIL0491', 'name' => 'Grayville');
$city_data[] = array('accid' => 'USIL0492', 'name' => 'Great Lakes');
$city_data[] = array('accid' => 'USIL0493', 'name' => 'Green Valley');
$city_data[] = array('accid' => 'USIL0494', 'name' => 'Greenfield');
$city_data[] = array('accid' => 'USIL0495', 'name' => 'Greenup');
$city_data[] = array('accid' => 'USIL0496', 'name' => 'Greenview');
$city_data[] = array('accid' => 'USIL0497', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USIL0498', 'name' => 'Gridley');
$city_data[] = array('accid' => 'USIL0499', 'name' => 'Griggsville');
$city_data[] = array('accid' => 'USIL0500', 'name' => 'Groveland');
$city_data[] = array('accid' => 'USIL0501', 'name' => 'Gurnee');
$city_data[] = array('accid' => 'USIL0502', 'name' => 'Hagarstown');
$city_data[] = array('accid' => 'USIL0503', 'name' => 'Hamburg');
$city_data[] = array('accid' => 'USIL0504', 'name' => 'Hamel');
$city_data[] = array('accid' => 'USIL0505', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USIL0506', 'name' => 'Hamletsburg');
$city_data[] = array('accid' => 'USIL0507', 'name' => 'Hammond');
$city_data[] = array('accid' => 'USIL0508', 'name' => 'Hampshire');
$city_data[] = array('accid' => 'USIL0509', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USIL0510', 'name' => 'Hanna City');
$city_data[] = array('accid' => 'USIL0511', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USIL1313', 'name' => 'Hanover Park');
$city_data[] = array('accid' => 'USIL0512', 'name' => 'Hardin');
$city_data[] = array('accid' => 'USIL0513', 'name' => 'Harmon');
$city_data[] = array('accid' => 'USIL0514', 'name' => 'Harrisburg');
$city_data[] = array('accid' => 'USIL0515', 'name' => 'Harristown');
$city_data[] = array('accid' => 'USIL0516', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USIL0517', 'name' => 'Hartsburg');
$city_data[] = array('accid' => 'USIL0518', 'name' => 'Harvard');
$city_data[] = array('accid' => 'USIL0519', 'name' => 'Harvel');
$city_data[] = array('accid' => 'USIL0520', 'name' => 'Harvey');
$city_data[] = array('accid' => 'USIL0521', 'name' => 'Havana');
$city_data[] = array('accid' => 'USIL0522', 'name' => 'Hazel Crest');
$city_data[] = array('accid' => 'USIL0523', 'name' => 'Hebron');
$city_data[] = array('accid' => 'USIL0524', 'name' => 'Hecker');
$city_data[] = array('accid' => 'USIL0525', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USIL0526', 'name' => 'Hennepin');
$city_data[] = array('accid' => 'USIL0527', 'name' => 'Henning');
$city_data[] = array('accid' => 'USIL0528', 'name' => 'Henry');
$city_data[] = array('accid' => 'USIL0529', 'name' => 'Herald');
$city_data[] = array('accid' => 'USIL0530', 'name' => 'Herod');
$city_data[] = array('accid' => 'USIL0531', 'name' => 'Herrick');
$city_data[] = array('accid' => 'USIL0532', 'name' => 'Herrin');
$city_data[] = array('accid' => 'USIL0533', 'name' => 'Herscher');
$city_data[] = array('accid' => 'USIL0534', 'name' => 'Hettick');
$city_data[] = array('accid' => 'USIL0535', 'name' => 'Heyworth');
$city_data[] = array('accid' => 'USIL0536', 'name' => 'Hickory Hills');
$city_data[] = array('accid' => 'USIL0537', 'name' => 'Hidalgo');
$city_data[] = array('accid' => 'USIL0538', 'name' => 'Highland');
$city_data[] = array('accid' => 'USIL0539', 'name' => 'Highland Park');
$city_data[] = array('accid' => 'USIL0540', 'name' => 'Highwood');
$city_data[] = array('accid' => 'USIL0541', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USIL0542', 'name' => 'Hillsdale');
$city_data[] = array('accid' => 'USIL0543', 'name' => 'Hillside');
$city_data[] = array('accid' => 'USIL0544', 'name' => 'Hillview');
$city_data[] = array('accid' => 'USIL0545', 'name' => 'Hinckley');
$city_data[] = array('accid' => 'USIL0546', 'name' => 'Hindsboro');
$city_data[] = array('accid' => 'USIL0547', 'name' => 'Hines');
$city_data[] = array('accid' => 'USIL0548', 'name' => 'Hinsdale');
$city_data[] = array('accid' => 'USIL0549', 'name' => 'Hoffman');
$city_data[] = array('accid' => 'USIL0550', 'name' => 'Hoffman Estates');
$city_data[] = array('accid' => 'USIL0551', 'name' => 'Holcomb');
$city_data[] = array('accid' => 'USIL0552', 'name' => 'Homer');
$city_data[] = array('accid' => 'USIL0553', 'name' => 'Hometown');
$city_data[] = array('accid' => 'USIL0554', 'name' => 'Homewood');
$city_data[] = array('accid' => 'USIL0555', 'name' => 'Hoopeston');
$city_data[] = array('accid' => 'USIL0556', 'name' => 'Hooppole');
$city_data[] = array('accid' => 'USIL0557', 'name' => 'Hopedale');
$city_data[] = array('accid' => 'USIL0558', 'name' => 'Hopkins Park');
$city_data[] = array('accid' => 'USIL0559', 'name' => 'Hoyleton');
$city_data[] = array('accid' => 'USIL0560', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USIL0561', 'name' => 'Huey');
$city_data[] = array('accid' => 'USIL0562', 'name' => 'Hull');
$city_data[] = array('accid' => 'USIL0563', 'name' => 'Humboldt');
$city_data[] = array('accid' => 'USIL0564', 'name' => 'Hume');
$city_data[] = array('accid' => 'USIL0565', 'name' => 'Huntley');
$city_data[] = array('accid' => 'USIL0566', 'name' => 'Huntsville');
$city_data[] = array('accid' => 'USIL0567', 'name' => 'Hurst');
$city_data[] = array('accid' => 'USIL0568', 'name' => 'Hutsonville');
$city_data[] = array('accid' => 'USIL0569', 'name' => 'Illinois City');
$city_data[] = array('accid' => 'USIL0570', 'name' => 'Illiopolis');
$city_data[] = array('accid' => 'USIL0571', 'name' => 'Ina');
$city_data[] = array('accid' => 'USIL0572', 'name' => 'Indianola');
$city_data[] = array('accid' => 'USIL0573', 'name' => 'Industry');
$city_data[] = array('accid' => 'USIL0574', 'name' => 'Ingleside');
$city_data[] = array('accid' => 'USIL0575', 'name' => 'Ingraham');
$city_data[] = array('accid' => 'USIL0576', 'name' => 'Iola');
$city_data[] = array('accid' => 'USIL0577', 'name' => 'Ipava');
$city_data[] = array('accid' => 'USIL0578', 'name' => 'Iroquois');
$city_data[] = array('accid' => 'USIL0579', 'name' => 'Irving');
$city_data[] = array('accid' => 'USIL0580', 'name' => 'Irvington');
$city_data[] = array('accid' => 'USIL0581', 'name' => 'Island Lake');
$city_data[] = array('accid' => 'USIL0582', 'name' => 'Itasca');
$city_data[] = array('accid' => 'USIL0583', 'name' => 'Iuka');
$city_data[] = array('accid' => 'USIL0584', 'name' => 'Ivesdale');
$city_data[] = array('accid' => 'USIL0585', 'name' => 'Jacksonville');
$city_data[] = array('accid' => 'USIL0586', 'name' => 'Jacob');
$city_data[] = array('accid' => 'USIL0587', 'name' => 'Janesville');
$city_data[] = array('accid' => 'USIL0588', 'name' => 'Jerseyville');
$city_data[] = array('accid' => 'USIL0589', 'name' => 'Jewett');
$city_data[] = array('accid' => 'USIL0590', 'name' => 'Johnsonville');
$city_data[] = array('accid' => 'USIL0591', 'name' => 'Johnston City');
$city_data[] = array('accid' => 'USIL0592', 'name' => 'Joliet');
$city_data[] = array('accid' => 'USIL0593', 'name' => 'Jonesboro');
$city_data[] = array('accid' => 'USIL0594', 'name' => 'Joppa');
$city_data[] = array('accid' => 'USIL0595', 'name' => 'Joy');
$city_data[] = array('accid' => 'USIL0596', 'name' => 'Junction');
$city_data[] = array('accid' => 'USIL0597', 'name' => 'Justice');
$city_data[] = array('accid' => 'USIL0598', 'name' => 'Kampsville');
$city_data[] = array('accid' => 'USIL0599', 'name' => 'Kane');
$city_data[] = array('accid' => 'USIL0600', 'name' => 'Kaneville');
$city_data[] = array('accid' => 'USIL0601', 'name' => 'Kankakee');
$city_data[] = array('accid' => 'USIL0602', 'name' => 'Kansas');
$city_data[] = array('accid' => 'USIL0603', 'name' => 'Karbers Ridge');
$city_data[] = array('accid' => 'USIL0604', 'name' => 'Karnak');
$city_data[] = array('accid' => 'USIL0605', 'name' => 'Kasbeer');
$city_data[] = array('accid' => 'USIL0606', 'name' => 'Keenes');
$city_data[] = array('accid' => 'USIL0607', 'name' => 'Keensburg');
$city_data[] = array('accid' => 'USIL0608', 'name' => 'Keithsburg');
$city_data[] = array('accid' => 'USIL0609', 'name' => 'Kell');
$city_data[] = array('accid' => 'USIL0610', 'name' => 'Kempton');
$city_data[] = array('accid' => 'USIL0611', 'name' => 'Kenilworth');
$city_data[] = array('accid' => 'USIL0612', 'name' => 'Kenney');
$city_data[] = array('accid' => 'USIL0613', 'name' => 'Kent');
$city_data[] = array('accid' => 'USIL0614', 'name' => 'Kewanee');
$city_data[] = array('accid' => 'USIL0615', 'name' => 'Keyesport');
$city_data[] = array('accid' => 'USIL0616', 'name' => 'Kilbourne');
$city_data[] = array('accid' => 'USIL0617', 'name' => 'Kincaid');
$city_data[] = array('accid' => 'USIL0618', 'name' => 'Kinderhook');
$city_data[] = array('accid' => 'USIL0619', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USIL0620', 'name' => 'Kingston Mines');
$city_data[] = array('accid' => 'USIL0621', 'name' => 'Kinmundy');
$city_data[] = array('accid' => 'USIL0622', 'name' => 'Kinsman');
$city_data[] = array('accid' => 'USIL0623', 'name' => 'Kirkland');
$city_data[] = array('accid' => 'USIL0624', 'name' => 'Kirkwood');
$city_data[] = array('accid' => 'USIL0625', 'name' => 'Knoxville');
$city_data[] = array('accid' => 'USIL0626', 'name' => 'La Fayette');
$city_data[] = array('accid' => 'USIL0627', 'name' => 'La Grange');
$city_data[] = array('accid' => 'USIL0628', 'name' => 'La Grange Park');
$city_data[] = array('accid' => 'USIL0629', 'name' => 'La Harpe');
$city_data[] = array('accid' => 'USIL0630', 'name' => 'La Moille');
$city_data[] = array('accid' => 'USIL0631', 'name' => 'La Place');
$city_data[] = array('accid' => 'USIL0632', 'name' => 'La Prairie');
$city_data[] = array('accid' => 'USIL0633', 'name' => 'La Rose');
$city_data[] = array('accid' => 'USIL0634', 'name' => 'La Salle');
$city_data[] = array('accid' => 'USIL0636', 'name' => 'Lacon');
$city_data[] = array('accid' => 'USIL0637', 'name' => 'Ladd');
$city_data[] = array('accid' => 'USIL0638', 'name' => 'Lafox');
$city_data[] = array('accid' => 'USIL0639', 'name' => 'Lake Bluff');
$city_data[] = array('accid' => 'USIL0640', 'name' => 'Lake Forest');
$city_data[] = array('accid' => 'USIL0641', 'name' => 'Lake Fork');
$city_data[] = array('accid' => 'USIL1310', 'name' => 'Lake In The Hills');
$city_data[] = array('accid' => 'USIL0642', 'name' => 'Lake Villa');
$city_data[] = array('accid' => 'USIL0643', 'name' => 'Lake Zurich');
$city_data[] = array('accid' => 'USIL0644', 'name' => 'Lakewood');
$city_data[] = array('accid' => 'USIL0645', 'name' => 'Lanark');
$city_data[] = array('accid' => 'USIL0646', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USIL0647', 'name' => 'Lane');
$city_data[] = array('accid' => 'USIL0648', 'name' => 'Lansing');
$city_data[] = array('accid' => 'USIL0649', 'name' => 'Latham');
$city_data[] = array('accid' => 'USIL0650', 'name' => 'Laura');
$city_data[] = array('accid' => 'USIL0651', 'name' => 'Lawndale');
$city_data[] = array('accid' => 'USIL0652', 'name' => 'Lawrenceville');
$city_data[] = array('accid' => 'USIL0653', 'name' => 'Le Roy');
$city_data[] = array('accid' => 'USIL0654', 'name' => 'Leaf River');
$city_data[] = array('accid' => 'USIL0655', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USIL0656', 'name' => 'Lee');
$city_data[] = array('accid' => 'USIL0657', 'name' => 'Lee Center');
$city_data[] = array('accid' => 'USIL0658', 'name' => 'Leland');
$city_data[] = array('accid' => 'USIL0659', 'name' => 'Lemont');
$city_data[] = array('accid' => 'USIL0660', 'name' => 'Lena');
$city_data[] = array('accid' => 'USIL0661', 'name' => 'Lenzburg');
$city_data[] = array('accid' => 'USIL0662', 'name' => 'Leonore');
$city_data[] = array('accid' => 'USIL0663', 'name' => 'Lerna');
$city_data[] = array('accid' => 'USIL0664', 'name' => 'Lewistown');
$city_data[] = array('accid' => 'USIL0665', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USIL0666', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USIL0667', 'name' => 'Libertyville');
$city_data[] = array('accid' => 'USIL0668', 'name' => 'Lima');
$city_data[] = array('accid' => 'USIL0669', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USIL0670', 'name' => 'Lincoln\'s New Salem');
$city_data[] = array('accid' => 'USIL0671', 'name' => 'Lincolnshire');
$city_data[] = array('accid' => 'USIL0672', 'name' => 'Lindenwood');
$city_data[] = array('accid' => 'USIL0673', 'name' => 'Lisle');
$city_data[] = array('accid' => 'USIL0674', 'name' => 'Litchfield');
$city_data[] = array('accid' => 'USIL0675', 'name' => 'Literberry');
$city_data[] = array('accid' => 'USIL0676', 'name' => 'Little York');
$city_data[] = array('accid' => 'USIL0677', 'name' => 'Littleton');
$city_data[] = array('accid' => 'USIL0678', 'name' => 'Liverpool');
$city_data[] = array('accid' => 'USIL0679', 'name' => 'Livingston');
$city_data[] = array('accid' => 'USIL0680', 'name' => 'Loami');
$city_data[] = array('accid' => 'USIL0681', 'name' => 'Lockport');
$city_data[] = array('accid' => 'USIL0682', 'name' => 'Loda');
$city_data[] = array('accid' => 'USIL0683', 'name' => 'Logan');
$city_data[] = array('accid' => 'USIL0684', 'name' => 'Lomax');
$city_data[] = array('accid' => 'USIL0685', 'name' => 'Lombard');
$city_data[] = array('accid' => 'USIL0686', 'name' => 'London Mills');
$city_data[] = array('accid' => 'USIL0687', 'name' => 'Long Grove');
$city_data[] = array('accid' => 'USIL0688', 'name' => 'Long Point');
$city_data[] = array('accid' => 'USIL0689', 'name' => 'Longview');
$city_data[] = array('accid' => 'USIL0690', 'name' => 'Loogootee');
$city_data[] = array('accid' => 'USIL0691', 'name' => 'Loraine');
$city_data[] = array('accid' => 'USIL0692', 'name' => 'Lostant');
$city_data[] = array('accid' => 'USIL0693', 'name' => 'Louisville');
$city_data[] = array('accid' => 'USIL0694', 'name' => 'Lovejoy');
$city_data[] = array('accid' => 'USIL0695', 'name' => 'Loves Park');
$city_data[] = array('accid' => 'USIL0696', 'name' => 'Lovington');
$city_data[] = array('accid' => 'USIL0697', 'name' => 'Lowder');
$city_data[] = array('accid' => 'USIL0698', 'name' => 'Lowpoint');
$city_data[] = array('accid' => 'USIL0699', 'name' => 'Ludlow');
$city_data[] = array('accid' => 'USIL0700', 'name' => 'Lyndon');
$city_data[] = array('accid' => 'USIL0701', 'name' => 'Lynn Center');
$city_data[] = array('accid' => 'USIL0702', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USIL0703', 'name' => 'Macedonia');
$city_data[] = array('accid' => 'USIL0704', 'name' => 'Machesney Park');
$city_data[] = array('accid' => 'USIL0705', 'name' => 'Mackinaw');
$city_data[] = array('accid' => 'USIL0706', 'name' => 'Macomb');
$city_data[] = array('accid' => 'USIL0707', 'name' => 'Macon');
$city_data[] = array('accid' => 'USIL0708', 'name' => 'Madison');
$city_data[] = array('accid' => 'USIL0709', 'name' => 'Maeystown');
$city_data[] = array('accid' => 'USIL0710', 'name' => 'Magnolia');
$city_data[] = array('accid' => 'USIL0711', 'name' => 'Mahomet');
$city_data[] = array('accid' => 'USIL0712', 'name' => 'Makanda');
$city_data[] = array('accid' => 'USIL0713', 'name' => 'Malden');
$city_data[] = array('accid' => 'USIL0714', 'name' => 'Malta');
$city_data[] = array('accid' => 'USIL0715', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USIL0716', 'name' => 'Manhattan');
$city_data[] = array('accid' => 'USIL0717', 'name' => 'Manito');
$city_data[] = array('accid' => 'USIL0718', 'name' => 'Manlius');
$city_data[] = array('accid' => 'USIL0719', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'USIL0720', 'name' => 'Manteno');
$city_data[] = array('accid' => 'USIL0721', 'name' => 'Maple Park');
$city_data[] = array('accid' => 'USIL0722', 'name' => 'Mapleton');
$city_data[] = array('accid' => 'USIL0723', 'name' => 'Maquon');
$city_data[] = array('accid' => 'USIL0724', 'name' => 'Marengo');
$city_data[] = array('accid' => 'USIL0725', 'name' => 'Marietta');
$city_data[] = array('accid' => 'USIL0726', 'name' => 'Marine');
$city_data[] = array('accid' => 'USIL0727', 'name' => 'Marion');
$city_data[] = array('accid' => 'USIL0728', 'name' => 'Marissa');
$city_data[] = array('accid' => 'USIL0729', 'name' => 'Mark');
$city_data[] = array('accid' => 'USIL0730', 'name' => 'Maroa');
$city_data[] = array('accid' => 'USIL0731', 'name' => 'Marseilles');
$city_data[] = array('accid' => 'USIL0732', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USIL0733', 'name' => 'Martinsville');
$city_data[] = array('accid' => 'USIL0734', 'name' => 'Martinton');
$city_data[] = array('accid' => 'USIL0735', 'name' => 'Maryville');
$city_data[] = array('accid' => 'USIL0736', 'name' => 'Mascoutah');
$city_data[] = array('accid' => 'USIL0737', 'name' => 'Mason');
$city_data[] = array('accid' => 'USIL0738', 'name' => 'Mason City');
$city_data[] = array('accid' => 'USIL0739', 'name' => 'Matherville');
$city_data[] = array('accid' => 'USIL0740', 'name' => 'Matteson');
$city_data[] = array('accid' => 'USIL0741', 'name' => 'Mattoon');
$city_data[] = array('accid' => 'USIL0742', 'name' => 'Maunie');
$city_data[] = array('accid' => 'USIL0743', 'name' => 'Maywood');
$city_data[] = array('accid' => 'USIL0744', 'name' => 'Mazon');
$city_data[] = array('accid' => 'USIL0745', 'name' => 'McClure');
$city_data[] = array('accid' => 'USIL0746', 'name' => 'McConnell');
$city_data[] = array('accid' => 'USIL0747', 'name' => 'McHenry');
$city_data[] = array('accid' => 'USIL0748', 'name' => 'McLean');
$city_data[] = array('accid' => 'USIL0749', 'name' => 'McLeansboro');
$city_data[] = array('accid' => 'USIL0750', 'name' => 'McNabb');
$city_data[] = array('accid' => 'USIL0751', 'name' => 'Mechanicsburg');
$city_data[] = array('accid' => 'USIL0752', 'name' => 'Media');
$city_data[] = array('accid' => 'USIL0753', 'name' => 'Medinah');
$city_data[] = array('accid' => 'USIL0754', 'name' => 'Medora');
$city_data[] = array('accid' => 'USIL0755', 'name' => 'Melrose Park');
$city_data[] = array('accid' => 'USIL0756', 'name' => 'Melvin');
$city_data[] = array('accid' => 'USIL0757', 'name' => 'Menard');
$city_data[] = array('accid' => 'USIL0758', 'name' => 'Mendon');
$city_data[] = array('accid' => 'USIL0759', 'name' => 'Mendota');
$city_data[] = array('accid' => 'USIL0760', 'name' => 'Meredosia');
$city_data[] = array('accid' => 'USIL0761', 'name' => 'Merna');
$city_data[] = array('accid' => 'USIL0762', 'name' => 'Metamora');
$city_data[] = array('accid' => 'USIL0763', 'name' => 'Metcalf');
$city_data[] = array('accid' => 'USIL0764', 'name' => 'Metropolis');
$city_data[] = array('accid' => 'USIL0765', 'name' => 'Michael');
$city_data[] = array('accid' => 'USIL0766', 'name' => 'Middletown');
$city_data[] = array('accid' => 'USIL0767', 'name' => 'Midlothian');
$city_data[] = array('accid' => 'USIL0768', 'name' => 'Milan');
$city_data[] = array('accid' => 'USIL0769', 'name' => 'Milford');
$city_data[] = array('accid' => 'USIL0770', 'name' => 'Mill Shoals');
$city_data[] = array('accid' => 'USIL0771', 'name' => 'Millbrook');
$city_data[] = array('accid' => 'USIL0772', 'name' => 'Millcreek');
$city_data[] = array('accid' => 'USIL0773', 'name' => 'Milledgeville');
$city_data[] = array('accid' => 'USIL0774', 'name' => 'Miller City');
$city_data[] = array('accid' => 'USIL0775', 'name' => 'Millington');
$city_data[] = array('accid' => 'USIL0776', 'name' => 'Millstadt');
$city_data[] = array('accid' => 'USIL0777', 'name' => 'Milmine');
$city_data[] = array('accid' => 'USIL0778', 'name' => 'Milton');
$city_data[] = array('accid' => 'USIL0779', 'name' => 'Mineral');
$city_data[] = array('accid' => 'USIL0780', 'name' => 'Minier');
$city_data[] = array('accid' => 'USIL0781', 'name' => 'Minonk');
$city_data[] = array('accid' => 'USIL0782', 'name' => 'Minooka');
$city_data[] = array('accid' => 'USIL0783', 'name' => 'Mode');
$city_data[] = array('accid' => 'USIL0784', 'name' => 'Modesto');
$city_data[] = array('accid' => 'USIL0785', 'name' => 'Modoc');
$city_data[] = array('accid' => 'USIL0786', 'name' => 'Mokena');
$city_data[] = array('accid' => 'USIL0787', 'name' => 'Moline');
$city_data[] = array('accid' => 'USIL0789', 'name' => 'Momence');
$city_data[] = array('accid' => 'USIL0790', 'name' => 'Monee');
$city_data[] = array('accid' => 'USIL0791', 'name' => 'Monmouth');
$city_data[] = array('accid' => 'USIL0792', 'name' => 'Monroe Center');
$city_data[] = array('accid' => 'USIL0793', 'name' => 'Montgomery');
$city_data[] = array('accid' => 'USIL0794', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USIL0795', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USIL0796', 'name' => 'Mooseheart');
$city_data[] = array('accid' => 'USIL0797', 'name' => 'Moro');
$city_data[] = array('accid' => 'USIL0798', 'name' => 'Morris');
$city_data[] = array('accid' => 'USIL0799', 'name' => 'Morrison');
$city_data[] = array('accid' => 'USIL0800', 'name' => 'Morrisonville');
$city_data[] = array('accid' => 'USIL0801', 'name' => 'Morton');
$city_data[] = array('accid' => 'USIL0802', 'name' => 'Morton Grove');
$city_data[] = array('accid' => 'USIL0803', 'name' => 'Mossville');
$city_data[] = array('accid' => 'USIL0804', 'name' => 'Mound City');
$city_data[] = array('accid' => 'USIL0805', 'name' => 'Mounds');
$city_data[] = array('accid' => 'USIL0806', 'name' => 'Mount Auburn');
$city_data[] = array('accid' => 'USIL0807', 'name' => 'Mount Carmel');
$city_data[] = array('accid' => 'USIL0808', 'name' => 'Mount Carroll');
$city_data[] = array('accid' => 'USIL0809', 'name' => 'Mount Erie');
$city_data[] = array('accid' => 'USIL0810', 'name' => 'Mount Morris');
$city_data[] = array('accid' => 'USIL0811', 'name' => 'Mount Olive');
$city_data[] = array('accid' => 'USIL0812', 'name' => 'Mount Prospect');
$city_data[] = array('accid' => 'USIL0813', 'name' => 'Mount Pulaski');
$city_data[] = array('accid' => 'USIL0814', 'name' => 'Mount Sterling');
$city_data[] = array('accid' => 'USIL0815', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USIL0816', 'name' => 'Mount Zion');
$city_data[] = array('accid' => 'USIL0817', 'name' => 'Moweaqua');
$city_data[] = array('accid' => 'USIL0818', 'name' => 'Mozier');
$city_data[] = array('accid' => 'USIL0819', 'name' => 'Muddy');
$city_data[] = array('accid' => 'USIL0820', 'name' => 'Mulberry Grove');
$city_data[] = array('accid' => 'USIL0821', 'name' => 'Mulkeytown');
$city_data[] = array('accid' => 'USIL0822', 'name' => 'Muncie');
$city_data[] = array('accid' => 'USIL0823', 'name' => 'Mundelein');
$city_data[] = array('accid' => 'USIL0824', 'name' => 'Murdock');
$city_data[] = array('accid' => 'USIL0825', 'name' => 'Murphysboro');
$city_data[] = array('accid' => 'USIL0826', 'name' => 'Murrayville');
$city_data[] = array('accid' => 'USIL0827', 'name' => 'Nachusa');
$city_data[] = array('accid' => 'USIL0828', 'name' => 'Naperville');
$city_data[] = array('accid' => 'USIL0829', 'name' => 'Nashville');
$city_data[] = array('accid' => 'USIL0830', 'name' => 'Nason');
$city_data[] = array('accid' => 'USIL0831', 'name' => 'National Stock Yards');
$city_data[] = array('accid' => 'USIL0832', 'name' => 'Nauvoo');
$city_data[] = array('accid' => 'USIL0833', 'name' => 'Nebo');
$city_data[] = array('accid' => 'USIL0834', 'name' => 'Nelson');
$city_data[] = array('accid' => 'USIL0835', 'name' => 'Neoga');
$city_data[] = array('accid' => 'USIL0836', 'name' => 'Neponset');
$city_data[] = array('accid' => 'USIL0837', 'name' => 'New Athens');
$city_data[] = array('accid' => 'USIL0838', 'name' => 'New Baden');
$city_data[] = array('accid' => 'USIL0839', 'name' => 'New Bedford');
$city_data[] = array('accid' => 'USIL0840', 'name' => 'New Berlin');
$city_data[] = array('accid' => 'USIL0841', 'name' => 'New Boston');
$city_data[] = array('accid' => 'USIL0842', 'name' => 'New Burnside');
$city_data[] = array('accid' => 'USIL0843', 'name' => 'New Canton');
$city_data[] = array('accid' => 'USIL0844', 'name' => 'New Douglas');
$city_data[] = array('accid' => 'USIL0845', 'name' => 'New Haven');
$city_data[] = array('accid' => 'USIL0846', 'name' => 'New Holland');
$city_data[] = array('accid' => 'USIL0847', 'name' => 'New Lenox');
$city_data[] = array('accid' => 'USIL0848', 'name' => 'New Memphis');
$city_data[] = array('accid' => 'USIL0849', 'name' => 'New Salem');
$city_data[] = array('accid' => 'USIL0850', 'name' => 'New Windsor');
$city_data[] = array('accid' => 'USIL0851', 'name' => 'Newark');
$city_data[] = array('accid' => 'USIL0852', 'name' => 'Newman');
$city_data[] = array('accid' => 'USIL0853', 'name' => 'Newton');
$city_data[] = array('accid' => 'USIL0854', 'name' => 'Niantic');
$city_data[] = array('accid' => 'USIL0855', 'name' => 'Niles');
$city_data[] = array('accid' => 'USIL0856', 'name' => 'Nilwood');
$city_data[] = array('accid' => 'USIL0857', 'name' => 'Niota');
$city_data[] = array('accid' => 'USIL0858', 'name' => 'Noble');
$city_data[] = array('accid' => 'USIL0859', 'name' => 'Nokomis');
$city_data[] = array('accid' => 'USIL0860', 'name' => 'Nora');
$city_data[] = array('accid' => 'USIL0861', 'name' => 'Normal');
$city_data[] = array('accid' => 'USIL0862', 'name' => 'Norris');
$city_data[] = array('accid' => 'USIL0863', 'name' => 'Norris City');
$city_data[] = array('accid' => 'USIL0864', 'name' => 'North Aurora');
$city_data[] = array('accid' => 'USIL0865', 'name' => 'North Chicago');
$city_data[] = array('accid' => 'USIL0866', 'name' => 'North Henderson');
$city_data[] = array('accid' => 'USIL0867', 'name' => 'Northbrook');
$city_data[] = array('accid' => 'USIL0881', 'name' => 'O\'fallon');
$city_data[] = array('accid' => 'USIL0868', 'name' => 'Oak Brook');
$city_data[] = array('accid' => 'USIL0869', 'name' => 'Oak Forest');
$city_data[] = array('accid' => 'USIL0870', 'name' => 'Oak Lawn');
$city_data[] = array('accid' => 'USIL0871', 'name' => 'Oak Park');
$city_data[] = array('accid' => 'USIL0872', 'name' => 'Oakdale');
$city_data[] = array('accid' => 'USIL0873', 'name' => 'Oakford');
$city_data[] = array('accid' => 'USIL0874', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USIL0875', 'name' => 'Oakley');
$city_data[] = array('accid' => 'USIL0876', 'name' => 'Oakwood');
$city_data[] = array('accid' => 'USIL0877', 'name' => 'Oblong');
$city_data[] = array('accid' => 'USIL0878', 'name' => 'Oconee');
$city_data[] = array('accid' => 'USIL0879', 'name' => 'Odell');
$city_data[] = array('accid' => 'USIL0880', 'name' => 'Odin');
$city_data[] = array('accid' => 'USIL0882', 'name' => 'Ogden');
$city_data[] = array('accid' => 'USIL0883', 'name' => 'Oglesby');
$city_data[] = array('accid' => 'USIL0884', 'name' => 'Ohio');
$city_data[] = array('accid' => 'USIL0885', 'name' => 'Ohlman');
$city_data[] = array('accid' => 'USIL0886', 'name' => 'Okawville');
$city_data[] = array('accid' => 'USIL0887', 'name' => 'Olive Branch');
$city_data[] = array('accid' => 'USIL0888', 'name' => 'Olmsted');
$city_data[] = array('accid' => 'USIL0889', 'name' => 'Olney');
$city_data[] = array('accid' => 'USIL0890', 'name' => 'Olympia Fields');
$city_data[] = array('accid' => 'USIL0891', 'name' => 'Omaha');
$city_data[] = array('accid' => 'USIL0892', 'name' => 'Onarga');
$city_data[] = array('accid' => 'USIL0893', 'name' => 'Oneida');
$city_data[] = array('accid' => 'USIL0894', 'name' => 'Opdyke');
$city_data[] = array('accid' => 'USIL0895', 'name' => 'Opheim');
$city_data[] = array('accid' => 'USIL0896', 'name' => 'Oquawka');
$city_data[] = array('accid' => 'USIL0897', 'name' => 'Orangeville');
$city_data[] = array('accid' => 'USIL0898', 'name' => 'Oraville');
$city_data[] = array('accid' => 'USIL0899', 'name' => 'Oreana');
$city_data[] = array('accid' => 'USIL0900', 'name' => 'Oregon');
$city_data[] = array('accid' => 'USIL0901', 'name' => 'Orient');
$city_data[] = array('accid' => 'USIL0902', 'name' => 'Orion');
$city_data[] = array('accid' => 'USIL0903', 'name' => 'Orland Park');
$city_data[] = array('accid' => 'USIL0904', 'name' => 'Osco');
$city_data[] = array('accid' => 'USIL0905', 'name' => 'Oswego');
$city_data[] = array('accid' => 'USIL0906', 'name' => 'Ottawa');
$city_data[] = array('accid' => 'USIL0907', 'name' => 'Owaneco');
$city_data[] = array('accid' => 'USIL0908', 'name' => 'Ozark');
$city_data[] = array('accid' => 'USIL0909', 'name' => 'Palatine');
$city_data[] = array('accid' => 'USIL0910', 'name' => 'Palestine');
$city_data[] = array('accid' => 'USIL0911', 'name' => 'Palmer');
$city_data[] = array('accid' => 'USIL0912', 'name' => 'Palmyra');
$city_data[] = array('accid' => 'USIL0913', 'name' => 'Paloma');
$city_data[] = array('accid' => 'USIL0914', 'name' => 'Palos Heights');
$city_data[] = array('accid' => 'USIL0915', 'name' => 'Palos Hills');
$city_data[] = array('accid' => 'USIL0916', 'name' => 'Palos Park');
$city_data[] = array('accid' => 'USIL0917', 'name' => 'Pana');
$city_data[] = array('accid' => 'USIL0918', 'name' => 'Panama');
$city_data[] = array('accid' => 'USIL0919', 'name' => 'Papineau');
$city_data[] = array('accid' => 'USIL0920', 'name' => 'Paris');
$city_data[] = array('accid' => 'USIL0921', 'name' => 'Park Forest');
$city_data[] = array('accid' => 'USIL0922', 'name' => 'Park Ridge');
$city_data[] = array('accid' => 'USIL0923', 'name' => 'Parkersburg');
$city_data[] = array('accid' => 'USIL0924', 'name' => 'Patoka');
$city_data[] = array('accid' => 'USIL0925', 'name' => 'Patterson');
$city_data[] = array('accid' => 'USIL0926', 'name' => 'Paw Paw');
$city_data[] = array('accid' => 'USIL0927', 'name' => 'Pawnee');
$city_data[] = array('accid' => 'USIL0928', 'name' => 'Paxton');
$city_data[] = array('accid' => 'USIL0929', 'name' => 'Payson');
$city_data[] = array('accid' => 'USIL0930', 'name' => 'Pearl');
$city_data[] = array('accid' => 'USIL0931', 'name' => 'Pearl City');
$city_data[] = array('accid' => 'USIL0932', 'name' => 'Pecatonica');
$city_data[] = array('accid' => 'USIL0933', 'name' => 'Pekin');
$city_data[] = array('accid' => 'USIL0934', 'name' => 'Penfield');
$city_data[] = array('accid' => 'USIL0935', 'name' => 'Peoria');
$city_data[] = array('accid' => 'USIL0936', 'name' => 'Peotone');
$city_data[] = array('accid' => 'USIL0937', 'name' => 'Percy');
$city_data[] = array('accid' => 'USIL0938', 'name' => 'Perks');
$city_data[] = array('accid' => 'USIL0939', 'name' => 'Perry');
$city_data[] = array('accid' => 'USIL0940', 'name' => 'Peru');
$city_data[] = array('accid' => 'USIL0941', 'name' => 'Pesotum');
$city_data[] = array('accid' => 'USIL0942', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USIL0943', 'name' => 'Philo');
$city_data[] = array('accid' => 'USIL0944', 'name' => 'Piasa');
$city_data[] = array('accid' => 'USIL0945', 'name' => 'Pierron');
$city_data[] = array('accid' => 'USIL0946', 'name' => 'Pinckneyville');
$city_data[] = array('accid' => 'USIL0947', 'name' => 'Piper City');
$city_data[] = array('accid' => 'USIL0948', 'name' => 'Pittsburg');
$city_data[] = array('accid' => 'USIL0949', 'name' => 'Pittsfield');
$city_data[] = array('accid' => 'USIL0950', 'name' => 'Plainfield');
$city_data[] = array('accid' => 'USIL0951', 'name' => 'Plainville');
$city_data[] = array('accid' => 'USIL0952', 'name' => 'Plano');
$city_data[] = array('accid' => 'USIL0953', 'name' => 'Plato Center');
$city_data[] = array('accid' => 'USIL0954', 'name' => 'Pleasant Hill');
$city_data[] = array('accid' => 'USIL0955', 'name' => 'Pleasant Plains');
$city_data[] = array('accid' => 'USIL0956', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USIL0957', 'name' => 'Pocahontas');
$city_data[] = array('accid' => 'USIL0958', 'name' => 'Polo');
$city_data[] = array('accid' => 'USIL0959', 'name' => 'Pomona');
$city_data[] = array('accid' => 'USIL0960', 'name' => 'Pontiac');
$city_data[] = array('accid' => 'USIL0961', 'name' => 'Poplar Grove');
$city_data[] = array('accid' => 'USIL0962', 'name' => 'Port Byron');
$city_data[] = array('accid' => 'USIL0963', 'name' => 'Posen');
$city_data[] = array('accid' => 'USIL0964', 'name' => 'Potomac');
$city_data[] = array('accid' => 'USIL0965', 'name' => 'Prairie City');
$city_data[] = array('accid' => 'USIL0966', 'name' => 'Prairie Du Rocher');
$city_data[] = array('accid' => 'USIL0967', 'name' => 'Preemption');
$city_data[] = array('accid' => 'USIL0968', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USIL0969', 'name' => 'Princeville');
$city_data[] = array('accid' => 'USIL0970', 'name' => 'Prophetstown');
$city_data[] = array('accid' => 'USIL0971', 'name' => 'Prospect Heights');
$city_data[] = array('accid' => 'USIL0972', 'name' => 'Pulaski');
$city_data[] = array('accid' => 'USIL0973', 'name' => 'Putnam');
$city_data[] = array('accid' => 'USIL0974', 'name' => 'Quincy');
$city_data[] = array('accid' => 'USIL0975', 'name' => 'Radom');
$city_data[] = array('accid' => 'USIL0976', 'name' => 'Raleigh');
$city_data[] = array('accid' => 'USIL0977', 'name' => 'Ramsey');
$city_data[] = array('accid' => 'USIL0978', 'name' => 'Rankin');
$city_data[] = array('accid' => 'USIL0979', 'name' => 'Ransom');
$city_data[] = array('accid' => 'USIL0980', 'name' => 'Rantoul');
$city_data[] = array('accid' => 'USIL0981', 'name' => 'Rapids City');
$city_data[] = array('accid' => 'USIL0982', 'name' => 'Raritan');
$city_data[] = array('accid' => 'USIL0983', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USIL0984', 'name' => 'Red Bud');
$city_data[] = array('accid' => 'USIL0985', 'name' => 'Reddick');
$city_data[] = array('accid' => 'USIL0986', 'name' => 'Redmon');
$city_data[] = array('accid' => 'USIL0987', 'name' => 'Renault');
$city_data[] = array('accid' => 'USIL0988', 'name' => 'Reynolds');
$city_data[] = array('accid' => 'USIL0989', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USIL0990', 'name' => 'Richton Park');
$city_data[] = array('accid' => 'USIL0991', 'name' => 'Richview');
$city_data[] = array('accid' => 'USIL0992', 'name' => 'Ridge Farm');
$city_data[] = array('accid' => 'USIL0993', 'name' => 'Ridgway');
$city_data[] = array('accid' => 'USIL0994', 'name' => 'Ridott');
$city_data[] = array('accid' => 'USIL0995', 'name' => 'Rinard');
$city_data[] = array('accid' => 'USIL0996', 'name' => 'Ringwood');
$city_data[] = array('accid' => 'USIL0997', 'name' => 'Rio');
$city_data[] = array('accid' => 'USIL0998', 'name' => 'River Forest');
$city_data[] = array('accid' => 'USIL0999', 'name' => 'River Grove');
$city_data[] = array('accid' => 'USIL1000', 'name' => 'Riverdale');
$city_data[] = array('accid' => 'USIL1001', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USIL1002', 'name' => 'Riverton');
$city_data[] = array('accid' => 'USIL1003', 'name' => 'Roanoke');
$city_data[] = array('accid' => 'USIL1004', 'name' => 'Robbins');
$city_data[] = array('accid' => 'USIL1005', 'name' => 'Roberts');
$city_data[] = array('accid' => 'USIL1006', 'name' => 'Robinson');
$city_data[] = array('accid' => 'USIL1007', 'name' => 'Rochelle');
$city_data[] = array('accid' => 'USIL1008', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USIL1009', 'name' => 'Rock City');
$city_data[] = array('accid' => 'USIL1010', 'name' => 'Rock Falls');
$city_data[] = array('accid' => 'USIL1011', 'name' => 'Rock Island');
$city_data[] = array('accid' => 'USIL1012', 'name' => 'Rockbridge');
$city_data[] = array('accid' => 'USIL1013', 'name' => 'Rockford');
$city_data[] = array('accid' => 'USIL1014', 'name' => 'Rockport');
$city_data[] = array('accid' => 'USIL1015', 'name' => 'Rockton');
$city_data[] = array('accid' => 'USIL1016', 'name' => 'Rockwood');
$city_data[] = array('accid' => 'USIL1017', 'name' => 'Rolling Meadows');
$city_data[] = array('accid' => 'USIL1018', 'name' => 'Rome');
$city_data[] = array('accid' => 'USIL1019', 'name' => 'Romeoville');
$city_data[] = array('accid' => 'USIL1020', 'name' => 'Roodhouse');
$city_data[] = array('accid' => 'USIL1021', 'name' => 'Rosamond');
$city_data[] = array('accid' => 'USIL1022', 'name' => 'Roscoe');
$city_data[] = array('accid' => 'USIL1023', 'name' => 'Roselle');
$city_data[] = array('accid' => 'USIL1024', 'name' => 'Roseville');
$city_data[] = array('accid' => 'USIL1025', 'name' => 'Rosiclare');
$city_data[] = array('accid' => 'USIL1026', 'name' => 'Rossville');
$city_data[] = array('accid' => 'USIL1027', 'name' => 'Round Lake');
$city_data[] = array('accid' => 'USIL1028', 'name' => 'Roxana');
$city_data[] = array('accid' => 'USIL1029', 'name' => 'Royal');
$city_data[] = array('accid' => 'USIL1030', 'name' => 'Royalton');
$city_data[] = array('accid' => 'USIL1031', 'name' => 'Rushville');
$city_data[] = array('accid' => 'USIL1032', 'name' => 'Russell');
$city_data[] = array('accid' => 'USIL1033', 'name' => 'Rutland');
$city_data[] = array('accid' => 'USIL1034', 'name' => 'Sadorus');
$city_data[] = array('accid' => 'USIL1035', 'name' => 'Sailor Springs');
$city_data[] = array('accid' => 'USIL1036', 'name' => 'Saint Anne');
$city_data[] = array('accid' => 'USIL1037', 'name' => 'Saint Augustine');
$city_data[] = array('accid' => 'USIL1038', 'name' => 'Saint Charles');
$city_data[] = array('accid' => 'USIL1039', 'name' => 'Saint David');
$city_data[] = array('accid' => 'USIL1040', 'name' => 'Saint Elmo');
$city_data[] = array('accid' => 'USIL1041', 'name' => 'Saint Francisville');
$city_data[] = array('accid' => 'USIL1042', 'name' => 'Saint Jacob');
$city_data[] = array('accid' => 'USIL1043', 'name' => 'Saint Joseph');
$city_data[] = array('accid' => 'USIL1044', 'name' => 'Saint Libory');
$city_data[] = array('accid' => 'USIL1045', 'name' => 'Saint Peter');
$city_data[] = array('accid' => 'USIL1046', 'name' => 'Sainte Marie');
$city_data[] = array('accid' => 'USIL1047', 'name' => 'Salem');
$city_data[] = array('accid' => 'USIL1048', 'name' => 'San Jose');
$city_data[] = array('accid' => 'USIL1049', 'name' => 'Sandoval');
$city_data[] = array('accid' => 'USIL1050', 'name' => 'Sandwich');
$city_data[] = array('accid' => 'USIL1051', 'name' => 'Saunemin');
$city_data[] = array('accid' => 'USIL1052', 'name' => 'Savanna');
$city_data[] = array('accid' => 'USIL1053', 'name' => 'Savoy');
$city_data[] = array('accid' => 'USIL1054', 'name' => 'Sawyerville');
$city_data[] = array('accid' => 'USIL1055', 'name' => 'Saybrook');
$city_data[] = array('accid' => 'USIL1056', 'name' => 'Scales Mound');
$city_data[] = array('accid' => 'USIL1057', 'name' => 'Schaumburg');
$city_data[] = array('accid' => 'USIL1058', 'name' => 'Scheller');
$city_data[] = array('accid' => 'USIL1059', 'name' => 'Schiller Park');
$city_data[] = array('accid' => 'USIL1060', 'name' => 'Sciota');
$city_data[] = array('accid' => 'USIL1061', 'name' => 'Scioto Mills');
$city_data[] = array('accid' => 'USIL1062', 'name' => 'Scott AFB');
$city_data[] = array('accid' => 'USIL1063', 'name' => 'Scottville');
$city_data[] = array('accid' => 'USIL1064', 'name' => 'Seaton');
$city_data[] = array('accid' => 'USIL1065', 'name' => 'Seatonville');
$city_data[] = array('accid' => 'USIL1066', 'name' => 'Secor');
$city_data[] = array('accid' => 'USIL1067', 'name' => 'Seneca');
$city_data[] = array('accid' => 'USIL1068', 'name' => 'Serena');
$city_data[] = array('accid' => 'USIL1069', 'name' => 'Sesser');
$city_data[] = array('accid' => 'USIL1070', 'name' => 'Seward');
$city_data[] = array('accid' => 'USIL1071', 'name' => 'Seymour');
$city_data[] = array('accid' => 'USIL1072', 'name' => 'Shabbona');
$city_data[] = array('accid' => 'USIL1073', 'name' => 'Shannon');
$city_data[] = array('accid' => 'USIL1074', 'name' => 'Shattuc');
$city_data[] = array('accid' => 'USIL1075', 'name' => 'Shawneetown');
$city_data[] = array('accid' => 'USIL1076', 'name' => 'Sheffield');
$city_data[] = array('accid' => 'USIL1077', 'name' => 'Shelbyville');
$city_data[] = array('accid' => 'USIL1078', 'name' => 'Sheldon');
$city_data[] = array('accid' => 'USIL1079', 'name' => 'Sheridan');
$city_data[] = array('accid' => 'USIL1080', 'name' => 'Sherman');
$city_data[] = array('accid' => 'USIL1081', 'name' => 'Sherrard');
$city_data[] = array('accid' => 'USIL1082', 'name' => 'Shipman');
$city_data[] = array('accid' => 'USIL1083', 'name' => 'Shirland');
$city_data[] = array('accid' => 'USIL1084', 'name' => 'Shirley');
$city_data[] = array('accid' => 'USIL1085', 'name' => 'Shobonier');
$city_data[] = array('accid' => 'USIL1086', 'name' => 'Shumway');
$city_data[] = array('accid' => 'USIL1087', 'name' => 'Sibley');
$city_data[] = array('accid' => 'USIL1088', 'name' => 'Sidell');
$city_data[] = array('accid' => 'USIL1089', 'name' => 'Sidney');
$city_data[] = array('accid' => 'USIL1090', 'name' => 'Sigel');
$city_data[] = array('accid' => 'USIL1091', 'name' => 'Silvis');
$city_data[] = array('accid' => 'USIL1092', 'name' => 'Simpson');
$city_data[] = array('accid' => 'USIL1093', 'name' => 'Sims');
$city_data[] = array('accid' => 'USIL1094', 'name' => 'Skokie');
$city_data[] = array('accid' => 'USIL1095', 'name' => 'Smithboro');
$city_data[] = array('accid' => 'USIL1096', 'name' => 'Smithfield');
$city_data[] = array('accid' => 'USIL1097', 'name' => 'Smithshire');
$city_data[] = array('accid' => 'USIL1098', 'name' => 'Smithton');
$city_data[] = array('accid' => 'USIL1099', 'name' => 'Solon Mills');
$city_data[] = array('accid' => 'USIL1100', 'name' => 'Somonauk');
$city_data[] = array('accid' => 'USIL1101', 'name' => 'Sorento');
$city_data[] = array('accid' => 'USIL1102', 'name' => 'South Beloit');
$city_data[] = array('accid' => 'USIL1103', 'name' => 'South Elgin');
$city_data[] = array('accid' => 'USIL1104', 'name' => 'South Holland');
$city_data[] = array('accid' => 'USIL1105', 'name' => 'South Pekin');
$city_data[] = array('accid' => 'USIL1106', 'name' => 'South Roxana');
$city_data[] = array('accid' => 'USIL1107', 'name' => 'South Wilmington');
$city_data[] = array('accid' => 'USIL1108', 'name' => 'Sparland');
$city_data[] = array('accid' => 'USIL1109', 'name' => 'Sparta');
$city_data[] = array('accid' => 'USIL1110', 'name' => 'Speer');
$city_data[] = array('accid' => 'USIL1111', 'name' => 'Spring Grove');
$city_data[] = array('accid' => 'USIL1112', 'name' => 'Spring Valley');
$city_data[] = array('accid' => 'USIL1113', 'name' => 'Springerton');
$city_data[] = array('accid' => 'USIL1114', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USIL1115', 'name' => 'Standard');
$city_data[] = array('accid' => 'USIL1116', 'name' => 'Standard City');
$city_data[] = array('accid' => 'USIL1117', 'name' => 'Stanford');
$city_data[] = array('accid' => 'USIL1118', 'name' => 'Staunton');
$city_data[] = array('accid' => 'USIL1119', 'name' => 'Steeleville');
$city_data[] = array('accid' => 'USIL1120', 'name' => 'Steger');
$city_data[] = array('accid' => 'USIL1121', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USIL1123', 'name' => 'Steward');
$city_data[] = array('accid' => 'USIL1124', 'name' => 'Stewardson');
$city_data[] = array('accid' => 'USIL1125', 'name' => 'Stillman Valley');
$city_data[] = array('accid' => 'USIL1126', 'name' => 'Stockland');
$city_data[] = array('accid' => 'USIL1127', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USIL1128', 'name' => 'Stone Park');
$city_data[] = array('accid' => 'USIL1129', 'name' => 'Stonefort');
$city_data[] = array('accid' => 'USIL1130', 'name' => 'Stonington');
$city_data[] = array('accid' => 'USIL1131', 'name' => 'Stoy');
$city_data[] = array('accid' => 'USIL1132', 'name' => 'Strasburg');
$city_data[] = array('accid' => 'USIL1133', 'name' => 'Strawn');
$city_data[] = array('accid' => 'USIL1134', 'name' => 'Streamwood');
$city_data[] = array('accid' => 'USIL1135', 'name' => 'Streator');
$city_data[] = array('accid' => 'USIL1136', 'name' => 'Stronghurst');
$city_data[] = array('accid' => 'USIL1137', 'name' => 'Sublette');
$city_data[] = array('accid' => 'USIL1138', 'name' => 'Sugar Grove');
$city_data[] = array('accid' => 'USIL1139', 'name' => 'Sullivan');
$city_data[] = array('accid' => 'USIL1140', 'name' => 'Summerfield');
$city_data[] = array('accid' => 'USIL1141', 'name' => 'Summit Argo');
$city_data[] = array('accid' => 'USIL1142', 'name' => 'Sumner');
$city_data[] = array('accid' => 'USIL1143', 'name' => 'Sutter');
$city_data[] = array('accid' => 'USIL1144', 'name' => 'Sycamore');
$city_data[] = array('accid' => 'USIL1145', 'name' => 'Table Grove');
$city_data[] = array('accid' => 'USIL1146', 'name' => 'Tallula');
$city_data[] = array('accid' => 'USIL1147', 'name' => 'Tamaroa');
$city_data[] = array('accid' => 'USIL1148', 'name' => 'Tamms');
$city_data[] = array('accid' => 'USIL1149', 'name' => 'Tampico');
$city_data[] = array('accid' => 'USIL1150', 'name' => 'Taylor Ridge');
$city_data[] = array('accid' => 'USIL1151', 'name' => 'Taylor Springs');
$city_data[] = array('accid' => 'USIL1152', 'name' => 'Taylorville');
$city_data[] = array('accid' => 'USIL1153', 'name' => 'Techny');
$city_data[] = array('accid' => 'USIL1154', 'name' => 'Tennessee');
$city_data[] = array('accid' => 'USIL1155', 'name' => 'Teutopolis');
$city_data[] = array('accid' => 'USIL1156', 'name' => 'Texico');
$city_data[] = array('accid' => 'USIL1157', 'name' => 'Thawville');
$city_data[] = array('accid' => 'USIL1158', 'name' => 'Thayer');
$city_data[] = array('accid' => 'USIL1159', 'name' => 'Thebes');
$city_data[] = array('accid' => 'USIL1160', 'name' => 'Thomasboro');
$city_data[] = array('accid' => 'USIL1161', 'name' => 'Thompsonville');
$city_data[] = array('accid' => 'USIL1162', 'name' => 'Thomson');
$city_data[] = array('accid' => 'USIL1163', 'name' => 'Thornton');
$city_data[] = array('accid' => 'USIL1164', 'name' => 'Tilden');
$city_data[] = array('accid' => 'USIL1165', 'name' => 'Tilton');
$city_data[] = array('accid' => 'USIL1166', 'name' => 'Timewell');
$city_data[] = array('accid' => 'USIL1167', 'name' => 'Tinley Park');
$city_data[] = array('accid' => 'USIL1168', 'name' => 'Tiskilwa');
$city_data[] = array('accid' => 'USIL1169', 'name' => 'Toledo');
$city_data[] = array('accid' => 'USIL1170', 'name' => 'Tolono');
$city_data[] = array('accid' => 'USIL1171', 'name' => 'Toluca');
$city_data[] = array('accid' => 'USIL1172', 'name' => 'Tonica');
$city_data[] = array('accid' => 'USIL1173', 'name' => 'Topeka');
$city_data[] = array('accid' => 'USIL1174', 'name' => 'Toulon');
$city_data[] = array('accid' => 'USIL1175', 'name' => 'Tovey');
$city_data[] = array('accid' => 'USIL1176', 'name' => 'Towanda');
$city_data[] = array('accid' => 'USIL1177', 'name' => 'Tower Hill');
$city_data[] = array('accid' => 'USIL1178', 'name' => 'Tremont');
$city_data[] = array('accid' => 'USIL1179', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USIL1180', 'name' => 'Trilla');
$city_data[] = array('accid' => 'USIL1181', 'name' => 'Triumph');
$city_data[] = array('accid' => 'USIL1182', 'name' => 'Trivoli');
$city_data[] = array('accid' => 'USIL1183', 'name' => 'Troy');
$city_data[] = array('accid' => 'USIL1184', 'name' => 'Troy Grove');
$city_data[] = array('accid' => 'USIL1185', 'name' => 'Tunnel Hill');
$city_data[] = array('accid' => 'USIL1186', 'name' => 'Tuscola');
$city_data[] = array('accid' => 'USIL1187', 'name' => 'Ullin');
$city_data[] = array('accid' => 'USIL1188', 'name' => 'Union');
$city_data[] = array('accid' => 'USIL1189', 'name' => 'Union Hill');
$city_data[] = array('accid' => 'USIL1190', 'name' => 'Unity');
$city_data[] = array('accid' => 'USIL1191', 'name' => 'Urbana');
$city_data[] = array('accid' => 'USIL1192', 'name' => 'Ursa');
$city_data[] = array('accid' => 'USIL1193', 'name' => 'Utica');
$city_data[] = array('accid' => 'USIL1194', 'name' => 'Valier');
$city_data[] = array('accid' => 'USIL1195', 'name' => 'Valmeyer');
$city_data[] = array('accid' => 'USIL1196', 'name' => 'Van Orin');
$city_data[] = array('accid' => 'USIL1197', 'name' => 'Vandalia');
$city_data[] = array('accid' => 'USIL1198', 'name' => 'Varna');
$city_data[] = array('accid' => 'USIL1199', 'name' => 'Venice');
$city_data[] = array('accid' => 'USIL1200', 'name' => 'Vergennes');
$city_data[] = array('accid' => 'USIL1201', 'name' => 'Vermilion');
$city_data[] = array('accid' => 'USIL1202', 'name' => 'Vermont');
$city_data[] = array('accid' => 'USIL1203', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USIL1204', 'name' => 'Vernon Hills');
$city_data[] = array('accid' => 'USIL1205', 'name' => 'Verona');
$city_data[] = array('accid' => 'USIL1206', 'name' => 'Versailles');
$city_data[] = array('accid' => 'USIL1207', 'name' => 'Victoria');
$city_data[] = array('accid' => 'USIL1208', 'name' => 'Vienna');
$city_data[] = array('accid' => 'USIL1209', 'name' => 'Villa Grove');
$city_data[] = array('accid' => 'USIL1210', 'name' => 'Villa Park');
$city_data[] = array('accid' => 'USIL1211', 'name' => 'Villa Ridge');
$city_data[] = array('accid' => 'USIL1212', 'name' => 'Viola');
$city_data[] = array('accid' => 'USIL1213', 'name' => 'Virden');
$city_data[] = array('accid' => 'USIL1214', 'name' => 'Virgil');
$city_data[] = array('accid' => 'USIL1215', 'name' => 'Virginia');
$city_data[] = array('accid' => 'USIL1216', 'name' => 'Wadsworth');
$city_data[] = array('accid' => 'USIL1217', 'name' => 'Waggoner');
$city_data[] = array('accid' => 'USIL1218', 'name' => 'Walnut');
$city_data[] = array('accid' => 'USIL1219', 'name' => 'Walnut Hill');
$city_data[] = array('accid' => 'USIL1220', 'name' => 'Walsh');
$city_data[] = array('accid' => 'USIL1221', 'name' => 'Walshville');
$city_data[] = array('accid' => 'USIL1222', 'name' => 'Waltonville');
$city_data[] = array('accid' => 'USIL1223', 'name' => 'Wapella');
$city_data[] = array('accid' => 'USIL1224', 'name' => 'Warren');
$city_data[] = array('accid' => 'USIL1225', 'name' => 'Warrensburg');
$city_data[] = array('accid' => 'USIL1226', 'name' => 'Warrenville');
$city_data[] = array('accid' => 'USIL1227', 'name' => 'Warsaw');
$city_data[] = array('accid' => 'USIL1228', 'name' => 'Wasco');
$city_data[] = array('accid' => 'USIL1229', 'name' => 'Washburn');
$city_data[] = array('accid' => 'USIL1230', 'name' => 'Washington');
$city_data[] = array('accid' => 'USIL1231', 'name' => 'Wataga');
$city_data[] = array('accid' => 'USIL1232', 'name' => 'Waterloo');
$city_data[] = array('accid' => 'USIL1233', 'name' => 'Waterman');
$city_data[] = array('accid' => 'USIL1234', 'name' => 'Watseka');
$city_data[] = array('accid' => 'USIL1235', 'name' => 'Watson');
$city_data[] = array('accid' => 'USIL1236', 'name' => 'Wauconda');
$city_data[] = array('accid' => 'USIL1237', 'name' => 'Waukegan');
$city_data[] = array('accid' => 'USIL1238', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USIL1239', 'name' => 'Wayne');
$city_data[] = array('accid' => 'USIL1240', 'name' => 'Wayne City');
$city_data[] = array('accid' => 'USIL1241', 'name' => 'Waynesville');
$city_data[] = array('accid' => 'USIL1242', 'name' => 'Wedron');
$city_data[] = array('accid' => 'USIL1243', 'name' => 'Weldon');
$city_data[] = array('accid' => 'USIL1244', 'name' => 'Wellington');
$city_data[] = array('accid' => 'USIL1245', 'name' => 'Wenona');
$city_data[] = array('accid' => 'USIL1246', 'name' => 'West Brooklyn');
$city_data[] = array('accid' => 'USIL1247', 'name' => 'West Chicago');
$city_data[] = array('accid' => 'USIL1248', 'name' => 'West Frankfort');
$city_data[] = array('accid' => 'USIL1249', 'name' => 'West Liberty');
$city_data[] = array('accid' => 'USIL1250', 'name' => 'West Point');
$city_data[] = array('accid' => 'USIL1251', 'name' => 'West Salem');
$city_data[] = array('accid' => 'USIL1252', 'name' => 'West Union');
$city_data[] = array('accid' => 'USIL1253', 'name' => 'West York');
$city_data[] = array('accid' => 'USIL1254', 'name' => 'Westchester');
$city_data[] = array('accid' => 'USIL1255', 'name' => 'Western Springs');
$city_data[] = array('accid' => 'USIL1256', 'name' => 'Westfield');
$city_data[] = array('accid' => 'USIL1257', 'name' => 'Westmont');
$city_data[] = array('accid' => 'USIL1258', 'name' => 'Westville');
$city_data[] = array('accid' => 'USIL1259', 'name' => 'Wheaton');
$city_data[] = array('accid' => 'USIL1260', 'name' => 'Wheeler');
$city_data[] = array('accid' => 'USIL1261', 'name' => 'Wheeling');
$city_data[] = array('accid' => 'USIL1262', 'name' => 'White Hall');
$city_data[] = array('accid' => 'USIL1263', 'name' => 'White Heath');
$city_data[] = array('accid' => 'USIL1264', 'name' => 'Whittington');
$city_data[] = array('accid' => 'USIL1265', 'name' => 'Williamsfield');
$city_data[] = array('accid' => 'USIL1266', 'name' => 'Williamsville');
$city_data[] = array('accid' => 'USIL1267', 'name' => 'Willisville');
$city_data[] = array('accid' => 'USIL1268', 'name' => 'Willow Hill');
$city_data[] = array('accid' => 'USIL1269', 'name' => 'Willow Springs');
$city_data[] = array('accid' => 'USIL1270', 'name' => 'Wilmette');
$city_data[] = array('accid' => 'USIL1271', 'name' => 'Wilmington');
$city_data[] = array('accid' => 'USIL1272', 'name' => 'Wilsonville');
$city_data[] = array('accid' => 'USIL1273', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USIL1274', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USIL1275', 'name' => 'Winfield');
$city_data[] = array('accid' => 'USIL1276', 'name' => 'Winnebago');
$city_data[] = array('accid' => 'USIL1277', 'name' => 'Winnetka');
$city_data[] = array('accid' => 'USIL1278', 'name' => 'Winslow');
$city_data[] = array('accid' => 'USIL1279', 'name' => 'Winthrop Harbor');
$city_data[] = array('accid' => 'USIL1280', 'name' => 'Witt');
$city_data[] = array('accid' => 'USIL1281', 'name' => 'Wolf Lake');
$city_data[] = array('accid' => 'USIL1282', 'name' => 'Wonder Lake');
$city_data[] = array('accid' => 'USIL1283', 'name' => 'Wood Dale');
$city_data[] = array('accid' => 'USIL1284', 'name' => 'Wood River');
$city_data[] = array('accid' => 'USIL1285', 'name' => 'Woodhull');
$city_data[] = array('accid' => 'USIL1286', 'name' => 'Woodland');
$city_data[] = array('accid' => 'USIL1287', 'name' => 'Woodlawn');
$city_data[] = array('accid' => 'USIL1288', 'name' => 'Woodridge');
$city_data[] = array('accid' => 'USIL1289', 'name' => 'Woodson');
$city_data[] = array('accid' => 'USIL1290', 'name' => 'Woodstock');
$city_data[] = array('accid' => 'USIL1291', 'name' => 'Woosung');
$city_data[] = array('accid' => 'USIL1292', 'name' => 'Worden');
$city_data[] = array('accid' => 'USIL1293', 'name' => 'Worth');
$city_data[] = array('accid' => 'USIL1294', 'name' => 'Wrights');
$city_data[] = array('accid' => 'USIL1295', 'name' => 'Wyanet');
$city_data[] = array('accid' => 'USIL1296', 'name' => 'Wyoming');
$city_data[] = array('accid' => 'USIL1297', 'name' => 'Xenia');
$city_data[] = array('accid' => 'USIL1298', 'name' => 'Yale');
$city_data[] = array('accid' => 'USIL1299', 'name' => 'Yates City');
$city_data[] = array('accid' => 'USIL1300', 'name' => 'Yorkville');
$city_data[] = array('accid' => 'USIL1301', 'name' => 'Zeigler');
$city_data[] = array('accid' => 'USIL1302', 'name' => 'Zion');

?>