<?php

// City package for USA: Indiana 

$city_name = 'USA: Indiana';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USIN0001', 'name' => 'Advance');
$city_data[] = array('accid' => 'USIN0002', 'name' => 'Akron');
$city_data[] = array('accid' => 'USIN0003', 'name' => 'Alamo');
$city_data[] = array('accid' => 'USIN0004', 'name' => 'Albany');
$city_data[] = array('accid' => 'USIN0005', 'name' => 'Albion');
$city_data[] = array('accid' => 'USIN0006', 'name' => 'Alexandria');
$city_data[] = array('accid' => 'USIN0007', 'name' => 'Ambia');
$city_data[] = array('accid' => 'USIN0008', 'name' => 'Amboy');
$city_data[] = array('accid' => 'USIN0009', 'name' => 'Amo');
$city_data[] = array('accid' => 'USIN0010', 'name' => 'Anderson');
$city_data[] = array('accid' => 'USIN0011', 'name' => 'Andrews');
$city_data[] = array('accid' => 'USIN0012', 'name' => 'Angola');
$city_data[] = array('accid' => 'USIN0013', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USIN0014', 'name' => 'Arcola');
$city_data[] = array('accid' => 'USIN0015', 'name' => 'Argos');
$city_data[] = array('accid' => 'USIN0016', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USIN0017', 'name' => 'Ashley');
$city_data[] = array('accid' => 'USIN0018', 'name' => 'Athens');
$city_data[] = array('accid' => 'USIN0019', 'name' => 'Atlanta');
$city_data[] = array('accid' => 'USIN0020', 'name' => 'Attica');
$city_data[] = array('accid' => 'USIN0021', 'name' => 'Atwood');
$city_data[] = array('accid' => 'USIN0022', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USIN0023', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USIN0024', 'name' => 'Austin');
$city_data[] = array('accid' => 'USIN0025', 'name' => 'Avilla');
$city_data[] = array('accid' => 'USIN0026', 'name' => 'Avoca');
$city_data[] = array('accid' => 'USIN0027', 'name' => 'Bainbridge');
$city_data[] = array('accid' => 'USIN0028', 'name' => 'Bargersville');
$city_data[] = array('accid' => 'USIN0029', 'name' => 'Batesville');
$city_data[] = array('accid' => 'USIN0030', 'name' => 'Bath');
$city_data[] = array('accid' => 'USIN0031', 'name' => 'Battle Ground');
$city_data[] = array('accid' => 'USIN0032', 'name' => 'Bedford');
$city_data[] = array('accid' => 'USIN0033', 'name' => 'Beech Grove');
$city_data[] = array('accid' => 'USIN0034', 'name' => 'Bellmore');
$city_data[] = array('accid' => 'USIN0035', 'name' => 'Bennington');
$city_data[] = array('accid' => 'USIN0036', 'name' => 'Bentonville');
$city_data[] = array('accid' => 'USIN0037', 'name' => 'Berne');
$city_data[] = array('accid' => 'USIN0038', 'name' => 'Bethlehem');
$city_data[] = array('accid' => 'USIN0039', 'name' => 'Beverly Shores');
$city_data[] = array('accid' => 'USIN0040', 'name' => 'Bicknell');
$city_data[] = array('accid' => 'USIN0041', 'name' => 'Bippus');
$city_data[] = array('accid' => 'USIN0042', 'name' => 'Birdseye');
$city_data[] = array('accid' => 'USIN0043', 'name' => 'Blanford');
$city_data[] = array('accid' => 'USIN0044', 'name' => 'Bloomfield');
$city_data[] = array('accid' => 'USIN0045', 'name' => 'Bloomingdale');
$city_data[] = array('accid' => 'USIN0046', 'name' => 'Bloomington');
$city_data[] = array('accid' => 'USIN0047', 'name' => 'Bluffton');
$city_data[] = array('accid' => 'USIN0048', 'name' => 'Boggstown');
$city_data[] = array('accid' => 'USIN0049', 'name' => 'Boone Grove');
$city_data[] = array('accid' => 'USIN0050', 'name' => 'Boonville');
$city_data[] = array('accid' => 'USIN0051', 'name' => 'Borden');
$city_data[] = array('accid' => 'USIN0052', 'name' => 'Boston');
$city_data[] = array('accid' => 'USIN0053', 'name' => 'Boswell');
$city_data[] = array('accid' => 'USIN0054', 'name' => 'Bourbon');
$city_data[] = array('accid' => 'USIN0055', 'name' => 'Bowling Green');
$city_data[] = array('accid' => 'USIN0056', 'name' => 'Bradford');
$city_data[] = array('accid' => 'USIN0057', 'name' => 'Branchville');
$city_data[] = array('accid' => 'USIN0058', 'name' => 'Brazil');
$city_data[] = array('accid' => 'USIN0059', 'name' => 'Bremen');
$city_data[] = array('accid' => 'USIN0060', 'name' => 'Bridgeton');
$city_data[] = array('accid' => 'USIN0061', 'name' => 'Brimfield');
$city_data[] = array('accid' => 'USIN0062', 'name' => 'Bringhurst');
$city_data[] = array('accid' => 'USIN0063', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USIN0064', 'name' => 'Bristow');
$city_data[] = array('accid' => 'USIN0065', 'name' => 'Brook');
$city_data[] = array('accid' => 'USIN0066', 'name' => 'Brooklyn');
$city_data[] = array('accid' => 'USIN0067', 'name' => 'Brookston');
$city_data[] = array('accid' => 'USIN0068', 'name' => 'Brookville');
$city_data[] = array('accid' => 'USIN0069', 'name' => 'Brownsburg');
$city_data[] = array('accid' => 'USIN0070', 'name' => 'Brownstown');
$city_data[] = array('accid' => 'USIN0071', 'name' => 'Brownsville');
$city_data[] = array('accid' => 'USIN0072', 'name' => 'Bruceville');
$city_data[] = array('accid' => 'USIN0073', 'name' => 'Bryant');
$city_data[] = array('accid' => 'USIN0074', 'name' => 'Buck Creek');
$city_data[] = array('accid' => 'USIN0075', 'name' => 'Buckskin');
$city_data[] = array('accid' => 'USIN0076', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USIN0077', 'name' => 'Bunker Hill');
$city_data[] = array('accid' => 'USIN0078', 'name' => 'Burket');
$city_data[] = array('accid' => 'USIN0079', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USIN0080', 'name' => 'Burnettsville');
$city_data[] = array('accid' => 'USIN0081', 'name' => 'Burrows');
$city_data[] = array('accid' => 'USIN0082', 'name' => 'Butler');
$city_data[] = array('accid' => 'USIN0083', 'name' => 'Butlerville');
$city_data[] = array('accid' => 'USIN0084', 'name' => 'Cambridge City');
$city_data[] = array('accid' => 'USIN0085', 'name' => 'Camby');
$city_data[] = array('accid' => 'USIN0086', 'name' => 'Camden');
$city_data[] = array('accid' => 'USIN0087', 'name' => 'Campbellsburg');
$city_data[] = array('accid' => 'USIN0088', 'name' => 'Canaan');
$city_data[] = array('accid' => 'USIN0089', 'name' => 'Cannelburg');
$city_data[] = array('accid' => 'USIN0090', 'name' => 'Cannelton');
$city_data[] = array('accid' => 'USIN0091', 'name' => 'Carbon');
$city_data[] = array('accid' => 'USIN0092', 'name' => 'Carlisle');
$city_data[] = array('accid' => 'USIN0093', 'name' => 'Carmel');
$city_data[] = array('accid' => 'USIN0094', 'name' => 'Cartersburg');
$city_data[] = array('accid' => 'USIN0095', 'name' => 'Carthage');
$city_data[] = array('accid' => 'USIN0096', 'name' => 'Cayuga');
$city_data[] = array('accid' => 'USIN0097', 'name' => 'Cedar Grove');
$city_data[] = array('accid' => 'USIN0098', 'name' => 'Cedar Lake');
$city_data[] = array('accid' => 'USIN0099', 'name' => 'Celestine');
$city_data[] = array('accid' => 'USIN0100', 'name' => 'Centerpoint');
$city_data[] = array('accid' => 'USIN0101', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USIN0102', 'name' => 'Central');
$city_data[] = array('accid' => 'USIN0103', 'name' => 'Chalmers');
$city_data[] = array('accid' => 'USIN0104', 'name' => 'Chandler');
$city_data[] = array('accid' => 'USIN0105', 'name' => 'Charlestown');
$city_data[] = array('accid' => 'USIN0106', 'name' => 'Charlottesville');
$city_data[] = array('accid' => 'USIN0107', 'name' => 'Chesterton');
$city_data[] = array('accid' => 'USIN0108', 'name' => 'Chrisney');
$city_data[] = array('accid' => 'USIN0109', 'name' => 'Churubusco');
$city_data[] = array('accid' => 'USIN0110', 'name' => 'Cicero');
$city_data[] = array('accid' => 'USIN0111', 'name' => 'Clarks Hill');
$city_data[] = array('accid' => 'USIN0112', 'name' => 'Clarksburg');
$city_data[] = array('accid' => 'USIN0113', 'name' => 'Clarksville');
$city_data[] = array('accid' => 'USIN0114', 'name' => 'Clay City');
$city_data[] = array('accid' => 'USIN0115', 'name' => 'Claypool');
$city_data[] = array('accid' => 'USIN0116', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USIN0117', 'name' => 'Clear Creek');
$city_data[] = array('accid' => 'USIN0118', 'name' => 'Clifford');
$city_data[] = array('accid' => 'USIN0119', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USIN0120', 'name' => 'Cloverdale');
$city_data[] = array('accid' => 'USIN0121', 'name' => 'Coal City');
$city_data[] = array('accid' => 'USIN0122', 'name' => 'Coalmont');
$city_data[] = array('accid' => 'USIN0123', 'name' => 'Coatesville');
$city_data[] = array('accid' => 'USIN0124', 'name' => 'Colfax');
$city_data[] = array('accid' => 'USIN0125', 'name' => 'Columbia City');
$city_data[] = array('accid' => 'USIN0126', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USIN0127', 'name' => 'Commiskey');
$city_data[] = array('accid' => 'USIN0128', 'name' => 'Connersville');
$city_data[] = array('accid' => 'USIN0129', 'name' => 'Converse');
$city_data[] = array('accid' => 'USIN0130', 'name' => 'Cortland');
$city_data[] = array('accid' => 'USIN0131', 'name' => 'Corunna');
$city_data[] = array('accid' => 'USIN0132', 'name' => 'Cory');
$city_data[] = array('accid' => 'USIN0133', 'name' => 'Corydon');
$city_data[] = array('accid' => 'USIN0134', 'name' => 'Covington');
$city_data[] = array('accid' => 'USIN0135', 'name' => 'Craigville');
$city_data[] = array('accid' => 'USIN0136', 'name' => 'Crandall');
$city_data[] = array('accid' => 'USIN0137', 'name' => 'Crane');
$city_data[] = array('accid' => 'USIN0138', 'name' => 'Crawfordsville');
$city_data[] = array('accid' => 'USIN0139', 'name' => 'Cromwell');
$city_data[] = array('accid' => 'USIN0140', 'name' => 'Cross Plains');
$city_data[] = array('accid' => 'USIN0141', 'name' => 'Crothersville');
$city_data[] = array('accid' => 'USIN0142', 'name' => 'Crown Point');
$city_data[] = array('accid' => 'USIN0143', 'name' => 'Culver');
$city_data[] = array('accid' => 'USIN0144', 'name' => 'Cutler');
$city_data[] = array('accid' => 'USIN0145', 'name' => 'Cynthiana');
$city_data[] = array('accid' => 'USIN0146', 'name' => 'Dale');
$city_data[] = array('accid' => 'USIN0147', 'name' => 'Daleville');
$city_data[] = array('accid' => 'USIN0148', 'name' => 'Dana');
$city_data[] = array('accid' => 'USIN0149', 'name' => 'Danville');
$city_data[] = array('accid' => 'USIN0150', 'name' => 'Darlington');
$city_data[] = array('accid' => 'USIN0151', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USIN0152', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USIN0153', 'name' => 'Decker');
$city_data[] = array('accid' => 'USIN0154', 'name' => 'Deedsville');
$city_data[] = array('accid' => 'USIN0155', 'name' => 'Delong');
$city_data[] = array('accid' => 'USIN0156', 'name' => 'Delphi');
$city_data[] = array('accid' => 'USIN0157', 'name' => 'Demotte');
$city_data[] = array('accid' => 'USIN0158', 'name' => 'Denver');
$city_data[] = array('accid' => 'USIN0159', 'name' => 'Depauw');
$city_data[] = array('accid' => 'USIN0160', 'name' => 'Deputy');
$city_data[] = array('accid' => 'USIN0161', 'name' => 'Derby');
$city_data[] = array('accid' => 'USIN0162', 'name' => 'Dillsboro');
$city_data[] = array('accid' => 'USIN0163', 'name' => 'Donaldson');
$city_data[] = array('accid' => 'USIN0164', 'name' => 'Dublin');
$city_data[] = array('accid' => 'USIN0165', 'name' => 'Dubois');
$city_data[] = array('accid' => 'USIN0166', 'name' => 'Dugger');
$city_data[] = array('accid' => 'USIN0167', 'name' => 'Dunkirk');
$city_data[] = array('accid' => 'USIN0168', 'name' => 'Dunreith');
$city_data[] = array('accid' => 'USIN0169', 'name' => 'Dupont');
$city_data[] = array('accid' => 'USIN0170', 'name' => 'Dyer');
$city_data[] = array('accid' => 'USIN0171', 'name' => 'Earl Park');
$city_data[] = array('accid' => 'USIN0172', 'name' => 'East Chicago');
$city_data[] = array('accid' => 'USIN0173', 'name' => 'East Enterprise');
$city_data[] = array('accid' => 'USIN0174', 'name' => 'Eaton');
$city_data[] = array('accid' => 'USIN0175', 'name' => 'Eckerty');
$city_data[] = array('accid' => 'USIN0176', 'name' => 'Economy');
$city_data[] = array('accid' => 'USIN0177', 'name' => 'Edinburgh');
$city_data[] = array('accid' => 'USIN0178', 'name' => 'Edwardsport');
$city_data[] = array('accid' => 'USIN0179', 'name' => 'Elberfeld');
$city_data[] = array('accid' => 'USIN0180', 'name' => 'Elizabeth');
$city_data[] = array('accid' => 'USIN0181', 'name' => 'Elizabethtown');
$city_data[] = array('accid' => 'USIN0182', 'name' => 'Elkhart');
$city_data[] = array('accid' => 'USIN0183', 'name' => 'Ellettsville');
$city_data[] = array('accid' => 'USIN0184', 'name' => 'Elnora');
$city_data[] = array('accid' => 'USIN0185', 'name' => 'Elwood');
$city_data[] = array('accid' => 'USIN0186', 'name' => 'Eminence');
$city_data[] = array('accid' => 'USIN0187', 'name' => 'English');
$city_data[] = array('accid' => 'USIN0188', 'name' => 'Etna Green');
$city_data[] = array('accid' => 'USIN0189', 'name' => 'Evanston');
$city_data[] = array('accid' => 'USIN0190', 'name' => 'Evansville');
$city_data[] = array('accid' => 'USIN0191', 'name' => 'Fair Oaks');
$city_data[] = array('accid' => 'USIN0192', 'name' => 'Fairbanks');
$city_data[] = array('accid' => 'USIN0193', 'name' => 'Fairland');
$city_data[] = array('accid' => 'USIN0194', 'name' => 'Fairmount');
$city_data[] = array('accid' => 'USIN0195', 'name' => 'Falmouth');
$city_data[] = array('accid' => 'USIN0196', 'name' => 'Farmersburg');
$city_data[] = array('accid' => 'USIN0197', 'name' => 'Farmland');
$city_data[] = array('accid' => 'USIN0198', 'name' => 'Ferdinand');
$city_data[] = array('accid' => 'USIN0199', 'name' => 'Fillmore');
$city_data[] = array('accid' => 'USIN0200', 'name' => 'Finly');
$city_data[] = array('accid' => 'USIN0201', 'name' => 'Fishers');
$city_data[] = array('accid' => 'USIN0202', 'name' => 'Flat Rock');
$city_data[] = array('accid' => 'USIN0203', 'name' => 'Flora');
$city_data[] = array('accid' => 'USIN0204', 'name' => 'Florence');
$city_data[] = array('accid' => 'USIN0205', 'name' => 'Floyds Knobs');
$city_data[] = array('accid' => 'USIN0206', 'name' => 'Folsomville');
$city_data[] = array('accid' => 'USIN0207', 'name' => 'Fontanet');
$city_data[] = array('accid' => 'USIN0208', 'name' => 'Forest');
$city_data[] = array('accid' => 'USIN0209', 'name' => 'Fort Branch');
$city_data[] = array('accid' => 'USIN0210', 'name' => 'Fort Ritner');
$city_data[] = array('accid' => 'USIN0211', 'name' => 'Fort Wayne');
$city_data[] = array('accid' => 'USIN0212', 'name' => 'Fortville');
$city_data[] = array('accid' => 'USIN0213', 'name' => 'Fountain City');
$city_data[] = array('accid' => 'USIN0214', 'name' => 'Fountaintown');
$city_data[] = array('accid' => 'USIN0215', 'name' => 'Fowler');
$city_data[] = array('accid' => 'USIN0216', 'name' => 'Fowlerton');
$city_data[] = array('accid' => 'USIN0217', 'name' => 'Francesville');
$city_data[] = array('accid' => 'USIN0218', 'name' => 'Francisco');
$city_data[] = array('accid' => 'USIN0219', 'name' => 'Frankfort');
$city_data[] = array('accid' => 'USIN0220', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USIN0221', 'name' => 'Frankton');
$city_data[] = array('accid' => 'USIN0222', 'name' => 'Fredericksburg');
$city_data[] = array('accid' => 'USIN0223', 'name' => 'Freedom');
$city_data[] = array('accid' => 'USIN0224', 'name' => 'Freelandville');
$city_data[] = array('accid' => 'USIN0225', 'name' => 'Freetown');
$city_data[] = array('accid' => 'USIN0226', 'name' => 'Fremont');
$city_data[] = array('accid' => 'USIN0227', 'name' => 'French Lick');
$city_data[] = array('accid' => 'USIN0228', 'name' => 'Friendship');
$city_data[] = array('accid' => 'USIN0229', 'name' => 'Fulda');
$city_data[] = array('accid' => 'USIN0230', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USIN0231', 'name' => 'Galveston');
$city_data[] = array('accid' => 'USIN0232', 'name' => 'Garrett');
$city_data[] = array('accid' => 'USIN0233', 'name' => 'Gary');
$city_data[] = array('accid' => 'USIN0234', 'name' => 'Gas City');
$city_data[] = array('accid' => 'USIN0235', 'name' => 'Gaston');
$city_data[] = array('accid' => 'USIN0236', 'name' => 'Geneva');
$city_data[] = array('accid' => 'USIN0237', 'name' => 'Gentryville');
$city_data[] = array('accid' => 'USIN0238', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USIN0239', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USIN0240', 'name' => 'Goldsmith');
$city_data[] = array('accid' => 'USIN0241', 'name' => 'Goodland');
$city_data[] = array('accid' => 'USIN0242', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USIN0243', 'name' => 'Gosport');
$city_data[] = array('accid' => 'USIN0244', 'name' => 'Grabill');
$city_data[] = array('accid' => 'USIN0245', 'name' => 'Grammer');
$city_data[] = array('accid' => 'USIN0246', 'name' => 'Grandview');
$city_data[] = array('accid' => 'USIN0247', 'name' => 'Granger');
$city_data[] = array('accid' => 'USIN0248', 'name' => 'Grantsburg');
$city_data[] = array('accid' => 'USIN0249', 'name' => 'Grass Creek');
$city_data[] = array('accid' => 'USIN0250', 'name' => 'Graysville');
$city_data[] = array('accid' => 'USIN0251', 'name' => 'Greencastle');
$city_data[] = array('accid' => 'USIN0252', 'name' => 'Greenfield');
$city_data[] = array('accid' => 'USIN0253', 'name' => 'Greens Fork');
$city_data[] = array('accid' => 'USIN0254', 'name' => 'Greensboro');
$city_data[] = array('accid' => 'USIN0255', 'name' => 'Greensburg');
$city_data[] = array('accid' => 'USIN0256', 'name' => 'Greentown');
$city_data[] = array('accid' => 'USIN0257', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USIN0258', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USIN0259', 'name' => 'Griffin');
$city_data[] = array('accid' => 'USIN0260', 'name' => 'Griffith');
$city_data[] = array('accid' => 'USIN0261', 'name' => 'Grissom AFB');
$city_data[] = array('accid' => 'USIN0262', 'name' => 'Grovertown');
$city_data[] = array('accid' => 'USIN0263', 'name' => 'Guilford');
$city_data[] = array('accid' => 'USIN0264', 'name' => 'Gwynneville');
$city_data[] = array('accid' => 'USIN0265', 'name' => 'Hagerstown');
$city_data[] = array('accid' => 'USIN0266', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USIN0267', 'name' => 'Hamlet');
$city_data[] = array('accid' => 'USIN0268', 'name' => 'Hammond');
$city_data[] = array('accid' => 'USIN0269', 'name' => 'Hanna');
$city_data[] = array('accid' => 'USIN0270', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USIN0271', 'name' => 'Hardinsburg');
$city_data[] = array('accid' => 'USIN0272', 'name' => 'Harlan');
$city_data[] = array('accid' => 'USIN0273', 'name' => 'Harmony');
$city_data[] = array('accid' => 'USIN0274', 'name' => 'Harrodsburg');
$city_data[] = array('accid' => 'USIN0275', 'name' => 'Hartford City');
$city_data[] = array('accid' => 'USIN0276', 'name' => 'Hartsville');
$city_data[] = array('accid' => 'USIN0277', 'name' => 'Hatfield');
$city_data[] = array('accid' => 'USIN0278', 'name' => 'Haubstadt');
$city_data[] = array('accid' => 'USIN0279', 'name' => 'Hayden');
$city_data[] = array('accid' => 'USIN0280', 'name' => 'Hazleton');
$city_data[] = array('accid' => 'USIN0281', 'name' => 'Hebron');
$city_data[] = array('accid' => 'USIN0282', 'name' => 'Helmsburg');
$city_data[] = array('accid' => 'USIN0283', 'name' => 'Heltonville');
$city_data[] = array('accid' => 'USIN0284', 'name' => 'Hemlock');
$city_data[] = array('accid' => 'USIN0285', 'name' => 'Henryville');
$city_data[] = array('accid' => 'USIN0286', 'name' => 'Highland');
$city_data[] = array('accid' => 'USIN0287', 'name' => 'Hillisburg');
$city_data[] = array('accid' => 'USIN0288', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USIN0289', 'name' => 'Hillsdale');
$city_data[] = array('accid' => 'USIN0290', 'name' => 'Hoagland');
$city_data[] = array('accid' => 'USIN0291', 'name' => 'Hobart');
$city_data[] = array('accid' => 'USIN0292', 'name' => 'Hobbs');
$city_data[] = array('accid' => 'USIN0293', 'name' => 'Holland');
$city_data[] = array('accid' => 'USIN0294', 'name' => 'Holton');
$city_data[] = array('accid' => 'USIN0295', 'name' => 'Homer');
$city_data[] = array('accid' => 'USIN0296', 'name' => 'Hope');
$city_data[] = array('accid' => 'USIN0297', 'name' => 'Howe');
$city_data[] = array('accid' => 'USIN0298', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USIN0299', 'name' => 'Huntertown');
$city_data[] = array('accid' => 'USIN0300', 'name' => 'Huntingburg');
$city_data[] = array('accid' => 'USIN0301', 'name' => 'Huntington');
$city_data[] = array('accid' => 'USIN0302', 'name' => 'Huron');
$city_data[] = array('accid' => 'USIN0303', 'name' => 'Hymera');
$city_data[] = array('accid' => 'USIN0304', 'name' => 'Idaville');
$city_data[] = array('accid' => 'USIN0305', 'name' => 'Indianapolis');
$city_data[] = array('accid' => 'USIN0307', 'name' => 'Ingalls');
$city_data[] = array('accid' => 'USIN0308', 'name' => 'Inglefield');
$city_data[] = array('accid' => 'USIN0309', 'name' => 'Ireland');
$city_data[] = array('accid' => 'USIN0310', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USIN0311', 'name' => 'Jasonville');
$city_data[] = array('accid' => 'USIN0312', 'name' => 'Jasper');
$city_data[] = array('accid' => 'USIN0313', 'name' => 'Jeffersonville');
$city_data[] = array('accid' => 'USIN0314', 'name' => 'Jonesboro');
$city_data[] = array('accid' => 'USIN0315', 'name' => 'Jonesville');
$city_data[] = array('accid' => 'USIN0316', 'name' => 'Judson');
$city_data[] = array('accid' => 'USIN0317', 'name' => 'Kempton');
$city_data[] = array('accid' => 'USIN0318', 'name' => 'Kendallville');
$city_data[] = array('accid' => 'USIN0319', 'name' => 'Kennard');
$city_data[] = array('accid' => 'USIN0320', 'name' => 'Kentland');
$city_data[] = array('accid' => 'USIN0321', 'name' => 'Kewanna');
$city_data[] = array('accid' => 'USIN0322', 'name' => 'Keystone');
$city_data[] = array('accid' => 'USIN0323', 'name' => 'Kimmell');
$city_data[] = array('accid' => 'USIN0324', 'name' => 'Kingman');
$city_data[] = array('accid' => 'USIN0325', 'name' => 'Kingsbury');
$city_data[] = array('accid' => 'USIN0326', 'name' => 'Kingsford Heights');
$city_data[] = array('accid' => 'USIN0327', 'name' => 'Kirklin');
$city_data[] = array('accid' => 'USIN0328', 'name' => 'Knightstown');
$city_data[] = array('accid' => 'USIN0329', 'name' => 'Knightsville');
$city_data[] = array('accid' => 'USIN0330', 'name' => 'Knox');
$city_data[] = array('accid' => 'USIN0331', 'name' => 'Kokomo');
$city_data[] = array('accid' => 'USIN0332', 'name' => 'Koleen');
$city_data[] = array('accid' => 'USIN0333', 'name' => 'Kouts');
$city_data[] = array('accid' => 'USIN0334', 'name' => 'Kurtz');
$city_data[] = array('accid' => 'USIN0335', 'name' => 'La Crosse');
$city_data[] = array('accid' => 'USIN0336', 'name' => 'La Fontaine');
$city_data[] = array('accid' => 'USIN0337', 'name' => 'La Porte');
$city_data[] = array('accid' => 'USIN0338', 'name' => 'Laconia');
$city_data[] = array('accid' => 'USIN0339', 'name' => 'Ladoga');
$city_data[] = array('accid' => 'USIN0340', 'name' => 'Lafayette');
$city_data[] = array('accid' => 'USIN0341', 'name' => 'Lagrange');
$city_data[] = array('accid' => 'USIN0342', 'name' => 'Lagro');
$city_data[] = array('accid' => 'USIN0343', 'name' => 'Lake Cicott');
$city_data[] = array('accid' => 'USIN0344', 'name' => 'Lake Station');
$city_data[] = array('accid' => 'USIN0345', 'name' => 'Lake Village');
$city_data[] = array('accid' => 'USIN0346', 'name' => 'Laketon');
$city_data[] = array('accid' => 'USIN0347', 'name' => 'Lakeville');
$city_data[] = array('accid' => 'USIN0348', 'name' => 'Lamar');
$city_data[] = array('accid' => 'USIN0349', 'name' => 'Lanesville');
$city_data[] = array('accid' => 'USIN0350', 'name' => 'Laotto');
$city_data[] = array('accid' => 'USIN0351', 'name' => 'Lapaz');
$city_data[] = array('accid' => 'USIN0352', 'name' => 'Lapel');
$city_data[] = array('accid' => 'USIN0353', 'name' => 'Larwill');
$city_data[] = array('accid' => 'USIN0354', 'name' => 'Laurel');
$city_data[] = array('accid' => 'USIN0355', 'name' => 'Lawrenceburg');
$city_data[] = array('accid' => 'USIN0356', 'name' => 'Leavenworth');
$city_data[] = array('accid' => 'USIN0357', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USIN0358', 'name' => 'Leesburg');
$city_data[] = array('accid' => 'USIN0359', 'name' => 'Leiters Ford');
$city_data[] = array('accid' => 'USIN0360', 'name' => 'Leo');
$city_data[] = array('accid' => 'USIN0361', 'name' => 'Leopold');
$city_data[] = array('accid' => 'USIN0362', 'name' => 'Leroy');
$city_data[] = array('accid' => 'USIN0363', 'name' => 'Lewis');
$city_data[] = array('accid' => 'USIN0364', 'name' => 'Lewisville');
$city_data[] = array('accid' => 'USIN0365', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USIN0366', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USIN0367', 'name' => 'Liberty Center');
$city_data[] = array('accid' => 'USIN0368', 'name' => 'Liberty Mills');
$city_data[] = array('accid' => 'USIN0369', 'name' => 'Ligonier');
$city_data[] = array('accid' => 'USIN0370', 'name' => 'Lincoln City');
$city_data[] = array('accid' => 'USIN0371', 'name' => 'Linden');
$city_data[] = array('accid' => 'USIN0372', 'name' => 'Linn Grove');
$city_data[] = array('accid' => 'USIN0373', 'name' => 'Linton');
$city_data[] = array('accid' => 'USIN0374', 'name' => 'Little York');
$city_data[] = array('accid' => 'USIN0375', 'name' => 'Lizton');
$city_data[] = array('accid' => 'USIN0376', 'name' => 'Logansport');
$city_data[] = array('accid' => 'USIN0377', 'name' => 'Loogootee');
$city_data[] = array('accid' => 'USIN0378', 'name' => 'Losantville');
$city_data[] = array('accid' => 'USIN0379', 'name' => 'Lowell');
$city_data[] = array('accid' => 'USIN0380', 'name' => 'Lucerne');
$city_data[] = array('accid' => 'USIN0381', 'name' => 'Lynn');
$city_data[] = array('accid' => 'USIN0382', 'name' => 'Lynnville');
$city_data[] = array('accid' => 'USIN0383', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USIN0384', 'name' => 'Mackey');
$city_data[] = array('accid' => 'USIN0385', 'name' => 'Macy');
$city_data[] = array('accid' => 'USIN0386', 'name' => 'Madison');
$city_data[] = array('accid' => 'USIN0387', 'name' => 'Manilla');
$city_data[] = array('accid' => 'USIN0388', 'name' => 'Marengo');
$city_data[] = array('accid' => 'USIN0389', 'name' => 'Mariah Hill');
$city_data[] = array('accid' => 'USIN0390', 'name' => 'Marion');
$city_data[] = array('accid' => 'USIN0391', 'name' => 'Markle');
$city_data[] = array('accid' => 'USIN0392', 'name' => 'Markleville');
$city_data[] = array('accid' => 'USIN0393', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USIN0394', 'name' => 'Martinsville');
$city_data[] = array('accid' => 'USIN0395', 'name' => 'Marysville');
$city_data[] = array('accid' => 'USIN0396', 'name' => 'Matthews');
$city_data[] = array('accid' => 'USIN0397', 'name' => 'Mauckport');
$city_data[] = array('accid' => 'USIN0398', 'name' => 'Maxwell');
$city_data[] = array('accid' => 'USIN0399', 'name' => 'Mays');
$city_data[] = array('accid' => 'USIN0400', 'name' => 'McCordsville');
$city_data[] = array('accid' => 'USIN0401', 'name' => 'Mecca');
$city_data[] = array('accid' => 'USIN0402', 'name' => 'Medaryville');
$city_data[] = array('accid' => 'USIN0403', 'name' => 'Medora');
$city_data[] = array('accid' => 'USIN0404', 'name' => 'Mellott');
$city_data[] = array('accid' => 'USIN0405', 'name' => 'Memphis');
$city_data[] = array('accid' => 'USIN0406', 'name' => 'Mentone');
$city_data[] = array('accid' => 'USIN0407', 'name' => 'Merom');
$city_data[] = array('accid' => 'USIN0408', 'name' => 'Merrillville');
$city_data[] = array('accid' => 'USIN0409', 'name' => 'Metamora');
$city_data[] = array('accid' => 'USIN0410', 'name' => 'Mexico');
$city_data[] = array('accid' => 'USIN0411', 'name' => 'Miami');
$city_data[] = array('accid' => 'USIN0412', 'name' => 'Michigan City');
$city_data[] = array('accid' => 'USIN0413', 'name' => 'Michigantown');
$city_data[] = array('accid' => 'USIN0414', 'name' => 'Middlebury');
$city_data[] = array('accid' => 'USIN0415', 'name' => 'Middletown');
$city_data[] = array('accid' => 'USIN0416', 'name' => 'Midland');
$city_data[] = array('accid' => 'USIN0417', 'name' => 'Milan');
$city_data[] = array('accid' => 'USIN0418', 'name' => 'Milford');
$city_data[] = array('accid' => 'USIN0419', 'name' => 'Mill Creek');
$city_data[] = array('accid' => 'USIN0420', 'name' => 'Millersburg');
$city_data[] = array('accid' => 'USIN0421', 'name' => 'Millhousen');
$city_data[] = array('accid' => 'USIN0422', 'name' => 'Milltown');
$city_data[] = array('accid' => 'USIN0423', 'name' => 'Milroy');
$city_data[] = array('accid' => 'USIN0424', 'name' => 'Milton');
$city_data[] = array('accid' => 'USIN0425', 'name' => 'Mishawaka');
$city_data[] = array('accid' => 'USIN0426', 'name' => 'Mitchell');
$city_data[] = array('accid' => 'USIN0427', 'name' => 'Modoc');
$city_data[] = array('accid' => 'USIN0428', 'name' => 'Mongo');
$city_data[] = array('accid' => 'USIN0429', 'name' => 'Monon');
$city_data[] = array('accid' => 'USIN0430', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USIN0431', 'name' => 'Monroe City');
$city_data[] = array('accid' => 'USIN0432', 'name' => 'Monroeville');
$city_data[] = array('accid' => 'USIN0433', 'name' => 'Monrovia');
$city_data[] = array('accid' => 'USIN0434', 'name' => 'Monterey');
$city_data[] = array('accid' => 'USIN0435', 'name' => 'Montezuma');
$city_data[] = array('accid' => 'USIN0436', 'name' => 'Montgomery');
$city_data[] = array('accid' => 'USIN0437', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USIN0438', 'name' => 'Montmorenci');
$city_data[] = array('accid' => 'USIN0439', 'name' => 'Montpelier');
$city_data[] = array('accid' => 'USIN0440', 'name' => 'Mooreland');
$city_data[] = array('accid' => 'USIN0441', 'name' => 'Moores Hill');
$city_data[] = array('accid' => 'USIN0442', 'name' => 'Mooresville');
$city_data[] = array('accid' => 'USIN0443', 'name' => 'Morgantown');
$city_data[] = array('accid' => 'USIN0444', 'name' => 'Morocco');
$city_data[] = array('accid' => 'USIN0445', 'name' => 'Morris');
$city_data[] = array('accid' => 'USIN0446', 'name' => 'Morristown');
$city_data[] = array('accid' => 'USIN0447', 'name' => 'Mount Ayr');
$city_data[] = array('accid' => 'USIN0448', 'name' => 'Mount Saint Francis');
$city_data[] = array('accid' => 'USIN0449', 'name' => 'Mount Summit');
$city_data[] = array('accid' => 'USIN0450', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USIN0451', 'name' => 'Mulberry');
$city_data[] = array('accid' => 'USIN0452', 'name' => 'Muncie');
$city_data[] = array('accid' => 'USIN0453', 'name' => 'Munster');
$city_data[] = array('accid' => 'USIN0454', 'name' => 'Nabb');
$city_data[] = array('accid' => 'USIN0455', 'name' => 'Napoleon');
$city_data[] = array('accid' => 'USIN0456', 'name' => 'Nappanee');
$city_data[] = array('accid' => 'USIN0457', 'name' => 'Nashville');
$city_data[] = array('accid' => 'USIN0458', 'name' => 'Nebraska');
$city_data[] = array('accid' => 'USIN0459', 'name' => 'Needham');
$city_data[] = array('accid' => 'USIN0460', 'name' => 'New Albany');
$city_data[] = array('accid' => 'USIN0461', 'name' => 'New Carlisle');
$city_data[] = array('accid' => 'USIN0462', 'name' => 'New Castle');
$city_data[] = array('accid' => 'USIN0463', 'name' => 'New Goshen');
$city_data[] = array('accid' => 'USIN0464', 'name' => 'New Harmony');
$city_data[] = array('accid' => 'USIN0465', 'name' => 'New Haven');
$city_data[] = array('accid' => 'USIN0466', 'name' => 'New Lebanon');
$city_data[] = array('accid' => 'USIN0467', 'name' => 'New Lisbon');
$city_data[] = array('accid' => 'USIN0468', 'name' => 'New Market');
$city_data[] = array('accid' => 'USIN0469', 'name' => 'New Middletown');
$city_data[] = array('accid' => 'USIN0470', 'name' => 'New Palestine');
$city_data[] = array('accid' => 'USIN0471', 'name' => 'New Paris');
$city_data[] = array('accid' => 'USIN0472', 'name' => 'New Point');
$city_data[] = array('accid' => 'USIN0473', 'name' => 'New Richmond');
$city_data[] = array('accid' => 'USIN0474', 'name' => 'New Ross');
$city_data[] = array('accid' => 'USIN0475', 'name' => 'New Salisbury');
$city_data[] = array('accid' => 'USIN0476', 'name' => 'New Trenton');
$city_data[] = array('accid' => 'USIN0477', 'name' => 'New Washington');
$city_data[] = array('accid' => 'USIN0478', 'name' => 'New Waverly');
$city_data[] = array('accid' => 'USIN0479', 'name' => 'Newberry');
$city_data[] = array('accid' => 'USIN0480', 'name' => 'Newburgh');
$city_data[] = array('accid' => 'USIN0481', 'name' => 'Newport');
$city_data[] = array('accid' => 'USIN0482', 'name' => 'Newtown');
$city_data[] = array('accid' => 'USIN0483', 'name' => 'Nineveh');
$city_data[] = array('accid' => 'USIN0484', 'name' => 'Noblesville');
$city_data[] = array('accid' => 'USIN0485', 'name' => 'Norman');
$city_data[] = array('accid' => 'USIN0486', 'name' => 'North Judson');
$city_data[] = array('accid' => 'USIN0487', 'name' => 'North Liberty');
$city_data[] = array('accid' => 'USIN0488', 'name' => 'North Manchester');
$city_data[] = array('accid' => 'USIN0489', 'name' => 'North Salem');
$city_data[] = array('accid' => 'USIN0490', 'name' => 'North Vernon');
$city_data[] = array('accid' => 'USIN0491', 'name' => 'North Webster');
$city_data[] = array('accid' => 'USIN0492', 'name' => 'Notre Dame');
$city_data[] = array('accid' => 'USIN0493', 'name' => 'Oakford');
$city_data[] = array('accid' => 'USIN0494', 'name' => 'Oakland City');
$city_data[] = array('accid' => 'USIN0495', 'name' => 'Oaktown');
$city_data[] = array('accid' => 'USIN0496', 'name' => 'Oakville');
$city_data[] = array('accid' => 'USIN0497', 'name' => 'Odon');
$city_data[] = array('accid' => 'USIN0498', 'name' => 'Oldenburg');
$city_data[] = array('accid' => 'USIN0499', 'name' => 'Onward');
$city_data[] = array('accid' => 'USIN0500', 'name' => 'Oolitic');
$city_data[] = array('accid' => 'USIN0501', 'name' => 'Ora');
$city_data[] = array('accid' => 'USIN0502', 'name' => 'Orestes');
$city_data[] = array('accid' => 'USIN0503', 'name' => 'Orland');
$city_data[] = array('accid' => 'USIN0504', 'name' => 'Orleans');
$city_data[] = array('accid' => 'USIN0505', 'name' => 'Osceola');
$city_data[] = array('accid' => 'USIN0506', 'name' => 'Osgood');
$city_data[] = array('accid' => 'USIN0507', 'name' => 'Ossian');
$city_data[] = array('accid' => 'USIN0508', 'name' => 'Otisco');
$city_data[] = array('accid' => 'USIN0509', 'name' => 'Otterbein');
$city_data[] = array('accid' => 'USIN0510', 'name' => 'Otwell');
$city_data[] = array('accid' => 'USIN0511', 'name' => 'Owensburg');
$city_data[] = array('accid' => 'USIN0512', 'name' => 'Owensville');
$city_data[] = array('accid' => 'USIN0513', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USIN0514', 'name' => 'Palmyra');
$city_data[] = array('accid' => 'USIN0515', 'name' => 'Paoli');
$city_data[] = array('accid' => 'USIN0516', 'name' => 'Paragon');
$city_data[] = array('accid' => 'USIN0517', 'name' => 'Paris Crossing');
$city_data[] = array('accid' => 'USIN0518', 'name' => 'Parker City');
$city_data[] = array('accid' => 'USIN0519', 'name' => 'Patoka');
$city_data[] = array('accid' => 'USIN0520', 'name' => 'Patricksburg');
$city_data[] = array('accid' => 'USIN0521', 'name' => 'Patriot');
$city_data[] = array('accid' => 'USIN0522', 'name' => 'Paxton');
$city_data[] = array('accid' => 'USIN0523', 'name' => 'Pekin');
$city_data[] = array('accid' => 'USIN0524', 'name' => 'Pendleton');
$city_data[] = array('accid' => 'USIN0525', 'name' => 'Pennville');
$city_data[] = array('accid' => 'USIN0526', 'name' => 'Perrysville');
$city_data[] = array('accid' => 'USIN0527', 'name' => 'Pershing');
$city_data[] = array('accid' => 'USIN0528', 'name' => 'Peru');
$city_data[] = array('accid' => 'USIN0529', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USIN0530', 'name' => 'Petroleum');
$city_data[] = array('accid' => 'USIN0531', 'name' => 'Pierceton');
$city_data[] = array('accid' => 'USIN0532', 'name' => 'Pierceville');
$city_data[] = array('accid' => 'USIN0533', 'name' => 'Pimento');
$city_data[] = array('accid' => 'USIN0534', 'name' => 'Pine Village');
$city_data[] = array('accid' => 'USIN0535', 'name' => 'Pittsboro');
$city_data[] = array('accid' => 'USIN0536', 'name' => 'Plainfield');
$city_data[] = array('accid' => 'USIN0537', 'name' => 'Plainville');
$city_data[] = array('accid' => 'USIN0538', 'name' => 'Pleasant Lake');
$city_data[] = array('accid' => 'USIN0539', 'name' => 'Pleasant Mills');
$city_data[] = array('accid' => 'USIN0540', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USIN0541', 'name' => 'Poland');
$city_data[] = array('accid' => 'USIN0542', 'name' => 'Poneto');
$city_data[] = array('accid' => 'USIN0543', 'name' => 'Portage');
$city_data[] = array('accid' => 'USIN0544', 'name' => 'Portland');
$city_data[] = array('accid' => 'USIN0545', 'name' => 'Poseyville');
$city_data[] = array('accid' => 'USIN0546', 'name' => 'Prairie Creek');
$city_data[] = array('accid' => 'USIN0547', 'name' => 'Prairieton');
$city_data[] = array('accid' => 'USIN0548', 'name' => 'Preble');
$city_data[] = array('accid' => 'USIN0549', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USIN0550', 'name' => 'Putnamville');
$city_data[] = array('accid' => 'USIN0551', 'name' => 'Quincy');
$city_data[] = array('accid' => 'USIN0552', 'name' => 'Ragsdale');
$city_data[] = array('accid' => 'USIN0553', 'name' => 'Ramsey');
$city_data[] = array('accid' => 'USIN0554', 'name' => 'Redkey');
$city_data[] = array('accid' => 'USIN0555', 'name' => 'Reelsville');
$city_data[] = array('accid' => 'USIN0556', 'name' => 'Remington');
$city_data[] = array('accid' => 'USIN0557', 'name' => 'Rensselaer');
$city_data[] = array('accid' => 'USIN0558', 'name' => 'Reynolds');
$city_data[] = array('accid' => 'USIN0559', 'name' => 'Richland');
$city_data[] = array('accid' => 'USIN0560', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USIN0561', 'name' => 'Ridgeville');
$city_data[] = array('accid' => 'USIN0562', 'name' => 'Riley');
$city_data[] = array('accid' => 'USIN0563', 'name' => 'Rising Sun');
$city_data[] = array('accid' => 'USIN0564', 'name' => 'Roachdale');
$city_data[] = array('accid' => 'USIN0565', 'name' => 'Roann');
$city_data[] = array('accid' => 'USIN0566', 'name' => 'Roanoke');
$city_data[] = array('accid' => 'USIN0567', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USIN0568', 'name' => 'Rockfield');
$city_data[] = array('accid' => 'USIN0569', 'name' => 'Rockport');
$city_data[] = array('accid' => 'USIN0570', 'name' => 'Rockville');
$city_data[] = array('accid' => 'USIN0571', 'name' => 'Rolling Prairie');
$city_data[] = array('accid' => 'USIN0572', 'name' => 'Rome');
$city_data[] = array('accid' => 'USIN0573', 'name' => 'Rome City');
$city_data[] = array('accid' => 'USIN0574', 'name' => 'Romney');
$city_data[] = array('accid' => 'USIN0575', 'name' => 'Rosedale');
$city_data[] = array('accid' => 'USIN0576', 'name' => 'Roselawn');
$city_data[] = array('accid' => 'USIN0577', 'name' => 'Rossville');
$city_data[] = array('accid' => 'USIN0578', 'name' => 'Royal Center');
$city_data[] = array('accid' => 'USIN0579', 'name' => 'Rushville');
$city_data[] = array('accid' => 'USIN0580', 'name' => 'Russellville');
$city_data[] = array('accid' => 'USIN0581', 'name' => 'Russiaville');
$city_data[] = array('accid' => 'USIN0582', 'name' => 'Saint Anthony');
$city_data[] = array('accid' => 'USIN0583', 'name' => 'Saint Bernice');
$city_data[] = array('accid' => 'USIN0584', 'name' => 'Saint Croix');
$city_data[] = array('accid' => 'USIN0585', 'name' => 'Saint Joe');
$city_data[] = array('accid' => 'USIN0586', 'name' => 'Saint John');
$city_data[] = array('accid' => 'USIN0587', 'name' => 'Saint Mary Of The Woods');
$city_data[] = array('accid' => 'USIN0588', 'name' => 'Saint Meinrad');
$city_data[] = array('accid' => 'USIN0589', 'name' => 'Saint Paul');
$city_data[] = array('accid' => 'USIN0590', 'name' => 'Salamonia');
$city_data[] = array('accid' => 'USIN0591', 'name' => 'Salem');
$city_data[] = array('accid' => 'USIN0592', 'name' => 'San Pierre');
$city_data[] = array('accid' => 'USIN0593', 'name' => 'Sandborn');
$city_data[] = array('accid' => 'USIN0594', 'name' => 'Santa Claus');
$city_data[] = array('accid' => 'USIN0595', 'name' => 'Saratoga');
$city_data[] = array('accid' => 'USIN0596', 'name' => 'Schererville');
$city_data[] = array('accid' => 'USIN0597', 'name' => 'Schneider');
$city_data[] = array('accid' => 'USIN0598', 'name' => 'Schnellville');
$city_data[] = array('accid' => 'USIN0599', 'name' => 'Scipio');
$city_data[] = array('accid' => 'USIN0600', 'name' => 'Scotland');
$city_data[] = array('accid' => 'USIN0601', 'name' => 'Scottsburg');
$city_data[] = array('accid' => 'USIN0602', 'name' => 'Sedalia');
$city_data[] = array('accid' => 'USIN0603', 'name' => 'Seelyville');
$city_data[] = array('accid' => 'USIN0604', 'name' => 'Sellersburg');
$city_data[] = array('accid' => 'USIN0605', 'name' => 'Selma');
$city_data[] = array('accid' => 'USIN0606', 'name' => 'Servia');
$city_data[] = array('accid' => 'USIN0607', 'name' => 'Seymour');
$city_data[] = array('accid' => 'USIN0608', 'name' => 'Sharpsville');
$city_data[] = array('accid' => 'USIN0609', 'name' => 'Shelburn');
$city_data[] = array('accid' => 'USIN0610', 'name' => 'Shelby');
$city_data[] = array('accid' => 'USIN0611', 'name' => 'Shelbyville');
$city_data[] = array('accid' => 'USIN0612', 'name' => 'Shepardsville');
$city_data[] = array('accid' => 'USIN0613', 'name' => 'Sheridan');
$city_data[] = array('accid' => 'USIN0614', 'name' => 'Shipshewana');
$city_data[] = array('accid' => 'USIN0615', 'name' => 'Shirley');
$city_data[] = array('accid' => 'USIN0616', 'name' => 'Shoals');
$city_data[] = array('accid' => 'USIN0617', 'name' => 'Sidney');
$city_data[] = array('accid' => 'USIN0618', 'name' => 'Silver Lake');
$city_data[] = array('accid' => 'USIN0620', 'name' => 'Smithville');
$city_data[] = array('accid' => 'USIN0621', 'name' => 'Solsberry');
$city_data[] = array('accid' => 'USIN0622', 'name' => 'Somerset');
$city_data[] = array('accid' => 'USIN0623', 'name' => 'Somerville');
$city_data[] = array('accid' => 'USIN0624', 'name' => 'South Bend');
$city_data[] = array('accid' => 'USIN0625', 'name' => 'South Milford');
$city_data[] = array('accid' => 'USIN0626', 'name' => 'South Whitley');
$city_data[] = array('accid' => 'USIN0627', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USIN0628', 'name' => 'Spencerville');
$city_data[] = array('accid' => 'USIN0629', 'name' => 'Spiceland');
$city_data[] = array('accid' => 'USIN0630', 'name' => 'Springport');
$city_data[] = array('accid' => 'USIN0631', 'name' => 'Springville');
$city_data[] = array('accid' => 'USIN0632', 'name' => 'Spurgeon');
$city_data[] = array('accid' => 'USIN0633', 'name' => 'Stanford');
$city_data[] = array('accid' => 'USIN0634', 'name' => 'Star City');
$city_data[] = array('accid' => 'USIN0635', 'name' => 'State Line');
$city_data[] = array('accid' => 'USIN0636', 'name' => 'Staunton');
$city_data[] = array('accid' => 'USIN0637', 'name' => 'Stendal');
$city_data[] = array('accid' => 'USIN0638', 'name' => 'Stilesville');
$city_data[] = array('accid' => 'USIN0639', 'name' => 'Stinesville');
$city_data[] = array('accid' => 'USIN0640', 'name' => 'Stockwell');
$city_data[] = array('accid' => 'USIN0641', 'name' => 'Straughn');
$city_data[] = array('accid' => 'USIN0642', 'name' => 'Stroh');
$city_data[] = array('accid' => 'USIN0643', 'name' => 'Sullivan');
$city_data[] = array('accid' => 'USIN0644', 'name' => 'Sulphur');
$city_data[] = array('accid' => 'USIN0645', 'name' => 'Sulphur Springs');
$city_data[] = array('accid' => 'USIN0646', 'name' => 'Sumava Resorts');
$city_data[] = array('accid' => 'USIN0647', 'name' => 'Summitville');
$city_data[] = array('accid' => 'USIN0648', 'name' => 'Sunman');
$city_data[] = array('accid' => 'USIN0649', 'name' => 'Swayzee');
$city_data[] = array('accid' => 'USIN0650', 'name' => 'Sweetser');
$city_data[] = array('accid' => 'USIN0651', 'name' => 'Switz City');
$city_data[] = array('accid' => 'USIN0652', 'name' => 'Syracuse');
$city_data[] = array('accid' => 'USIN0653', 'name' => 'Talbot');
$city_data[] = array('accid' => 'USIN0654', 'name' => 'Taswell');
$city_data[] = array('accid' => 'USIN0655', 'name' => 'Taylorsville');
$city_data[] = array('accid' => 'USIN0656', 'name' => 'Tefft');
$city_data[] = array('accid' => 'USIN0657', 'name' => 'Tell City');
$city_data[] = array('accid' => 'USIN0658', 'name' => 'Templeton');
$city_data[] = array('accid' => 'USIN0659', 'name' => 'Tennyson');
$city_data[] = array('accid' => 'USIN0660', 'name' => 'Terre Haute');
$city_data[] = array('accid' => 'USIN0661', 'name' => 'Thayer');
$city_data[] = array('accid' => 'USIN0662', 'name' => 'Thorntown');
$city_data[] = array('accid' => 'USIN0663', 'name' => 'Tippecanoe');
$city_data[] = array('accid' => 'USIN0664', 'name' => 'Tipton');
$city_data[] = array('accid' => 'USIN0665', 'name' => 'Topeka');
$city_data[] = array('accid' => 'USIN0666', 'name' => 'Trafalgar');
$city_data[] = array('accid' => 'USIN0667', 'name' => 'Troy');
$city_data[] = array('accid' => 'USIN0668', 'name' => 'Tunnelton');
$city_data[] = array('accid' => 'USIN0669', 'name' => 'Twelve Mile');
$city_data[] = array('accid' => 'USIN0670', 'name' => 'Tyner');
$city_data[] = array('accid' => 'USIN0671', 'name' => 'Underwood');
$city_data[] = array('accid' => 'USIN0672', 'name' => 'Union City');
$city_data[] = array('accid' => 'USIN0673', 'name' => 'Union Mills');
$city_data[] = array('accid' => 'USIN0674', 'name' => 'Uniondale');
$city_data[] = array('accid' => 'USIN0675', 'name' => 'Unionville');
$city_data[] = array('accid' => 'USIN0676', 'name' => 'Universal');
$city_data[] = array('accid' => 'USIN0677', 'name' => 'Upland');
$city_data[] = array('accid' => 'USIN0678', 'name' => 'Urbana');
$city_data[] = array('accid' => 'USIN0679', 'name' => 'Vallonia');
$city_data[] = array('accid' => 'USIN0680', 'name' => 'Valparaiso');
$city_data[] = array('accid' => 'USIN0681', 'name' => 'Van Buren');
$city_data[] = array('accid' => 'USIN0682', 'name' => 'Veedersburg');
$city_data[] = array('accid' => 'USIN0683', 'name' => 'Velpen');
$city_data[] = array('accid' => 'USIN0684', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USIN0685', 'name' => 'Versailles');
$city_data[] = array('accid' => 'USIN0686', 'name' => 'Vevay');
$city_data[] = array('accid' => 'USIN0687', 'name' => 'Vincennes');
$city_data[] = array('accid' => 'USIN0688', 'name' => 'Wabash');
$city_data[] = array('accid' => 'USIN0689', 'name' => 'Wadesville');
$city_data[] = array('accid' => 'USIN0690', 'name' => 'Wakarusa');
$city_data[] = array('accid' => 'USIN0691', 'name' => 'Waldron');
$city_data[] = array('accid' => 'USIN0692', 'name' => 'Walkerton');
$city_data[] = array('accid' => 'USIN0693', 'name' => 'Wallace');
$city_data[] = array('accid' => 'USIN0694', 'name' => 'Walton');
$city_data[] = array('accid' => 'USIN0695', 'name' => 'Wanatah');
$city_data[] = array('accid' => 'USIN0696', 'name' => 'Warren');
$city_data[] = array('accid' => 'USIN0697', 'name' => 'Warsaw');
$city_data[] = array('accid' => 'USIN0698', 'name' => 'Washington');
$city_data[] = array('accid' => 'USIN0699', 'name' => 'Waterloo');
$city_data[] = array('accid' => 'USIN0700', 'name' => 'Waveland');
$city_data[] = array('accid' => 'USIN0701', 'name' => 'Wawaka');
$city_data[] = array('accid' => 'USIN0702', 'name' => 'Waynetown');
$city_data[] = array('accid' => 'USIN0703', 'name' => 'Webster');
$city_data[] = array('accid' => 'USIN0704', 'name' => 'West Baden Springs');
$city_data[] = array('accid' => 'USIN0706', 'name' => 'West Harrison');
$city_data[] = array('accid' => 'USIN0707', 'name' => 'West Lafayette');
$city_data[] = array('accid' => 'USIN0708', 'name' => 'West Lebanon');
$city_data[] = array('accid' => 'USIN0709', 'name' => 'West Middleton');
$city_data[] = array('accid' => 'USIN0710', 'name' => 'West Newton');
$city_data[] = array('accid' => 'USIN0711', 'name' => 'West Terre Haute');
$city_data[] = array('accid' => 'USIN0712', 'name' => 'Westfield');
$city_data[] = array('accid' => 'USIN0713', 'name' => 'Westphalia');
$city_data[] = array('accid' => 'USIN0714', 'name' => 'Westpoint');
$city_data[] = array('accid' => 'USIN0715', 'name' => 'Westport');
$city_data[] = array('accid' => 'USIN0716', 'name' => 'Westville');
$city_data[] = array('accid' => 'USIN0717', 'name' => 'Wheatfield');
$city_data[] = array('accid' => 'USIN0718', 'name' => 'Wheatland');
$city_data[] = array('accid' => 'USIN0719', 'name' => 'Wheeler');
$city_data[] = array('accid' => 'USIN0720', 'name' => 'Whiteland');
$city_data[] = array('accid' => 'USIN0721', 'name' => 'Whitestown');
$city_data[] = array('accid' => 'USIN0722', 'name' => 'Whiting');
$city_data[] = array('accid' => 'USIN0723', 'name' => 'Wilkinson');
$city_data[] = array('accid' => 'USIN0724', 'name' => 'Williams');
$city_data[] = array('accid' => 'USIN0725', 'name' => 'Williamsburg');
$city_data[] = array('accid' => 'USIN0726', 'name' => 'Williamsport');
$city_data[] = array('accid' => 'USIN0727', 'name' => 'Winamac');
$city_data[] = array('accid' => 'USIN0728', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USIN0729', 'name' => 'Windfall');
$city_data[] = array('accid' => 'USIN0730', 'name' => 'Wingate');
$city_data[] = array('accid' => 'USIN0731', 'name' => 'Winona Lake');
$city_data[] = array('accid' => 'USIN0732', 'name' => 'Winslow');
$city_data[] = array('accid' => 'USIN0733', 'name' => 'Wolcott');
$city_data[] = array('accid' => 'USIN0734', 'name' => 'Wolcottville');
$city_data[] = array('accid' => 'USIN0735', 'name' => 'Wolflake');
$city_data[] = array('accid' => 'USIN0736', 'name' => 'Woodburn');
$city_data[] = array('accid' => 'USIN0737', 'name' => 'Worthington');
$city_data[] = array('accid' => 'USIN0738', 'name' => 'Wyatt');
$city_data[] = array('accid' => 'USIN0739', 'name' => 'Yeoman');
$city_data[] = array('accid' => 'USIN0740', 'name' => 'Yoder');
$city_data[] = array('accid' => 'USIN0741', 'name' => 'Yorktown');
$city_data[] = array('accid' => 'USIN0742', 'name' => 'Young America');
$city_data[] = array('accid' => 'USIN0743', 'name' => 'Zanesville');
$city_data[] = array('accid' => 'USIN0744', 'name' => 'Zionsville');

?>
