<?php

// City package for USA: Kansas 

$city_name = 'USA: Kansas';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USKS0001', 'name' => 'Abbyville');
$city_data[] = array('accid' => 'USKS0002', 'name' => 'Abilene');
$city_data[] = array('accid' => 'USKS0003', 'name' => 'Admire');
$city_data[] = array('accid' => 'USKS0004', 'name' => 'Agenda');
$city_data[] = array('accid' => 'USKS0005', 'name' => 'Agra');
$city_data[] = array('accid' => 'USKS0006', 'name' => 'Albert');
$city_data[] = array('accid' => 'USKS0007', 'name' => 'Alden');
$city_data[] = array('accid' => 'USKS0008', 'name' => 'Alexander');
$city_data[] = array('accid' => 'USKS0009', 'name' => 'Allen');
$city_data[] = array('accid' => 'USKS0010', 'name' => 'Alma');
$city_data[] = array('accid' => 'USKS0011', 'name' => 'Almena');
$city_data[] = array('accid' => 'USKS0012', 'name' => 'Alta Vista');
$city_data[] = array('accid' => 'USKS0013', 'name' => 'Altamont');
$city_data[] = array('accid' => 'USKS0014', 'name' => 'Alton');
$city_data[] = array('accid' => 'USKS0015', 'name' => 'Altoona');
$city_data[] = array('accid' => 'USKS0016', 'name' => 'Americus');
$city_data[] = array('accid' => 'USKS0017', 'name' => 'Andale');
$city_data[] = array('accid' => 'USKS0018', 'name' => 'Andover');
$city_data[] = array('accid' => 'USKS0019', 'name' => 'Anthony');
$city_data[] = array('accid' => 'USKS0020', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USKS0021', 'name' => 'Argonia');
$city_data[] = array('accid' => 'USKS0022', 'name' => 'Arkansas City');
$city_data[] = array('accid' => 'USKS0023', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USKS0024', 'name' => 'Arma');
$city_data[] = array('accid' => 'USKS0025', 'name' => 'Arnold');
$city_data[] = array('accid' => 'USKS0026', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USKS0027', 'name' => 'Assaria');
$city_data[] = array('accid' => 'USKS0028', 'name' => 'Atchison');
$city_data[] = array('accid' => 'USKS0029', 'name' => 'Athol');
$city_data[] = array('accid' => 'USKS0030', 'name' => 'Atlanta');
$city_data[] = array('accid' => 'USKS0031', 'name' => 'Attica');
$city_data[] = array('accid' => 'USKS0032', 'name' => 'Atwood');
$city_data[] = array('accid' => 'USKS0033', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USKS0034', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USKS0035', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USKS0036', 'name' => 'Axtell');
$city_data[] = array('accid' => 'USKS0037', 'name' => 'Baileyville');
$city_data[] = array('accid' => 'USKS0038', 'name' => 'Baldwin City');
$city_data[] = array('accid' => 'USKS0039', 'name' => 'Barnard');
$city_data[] = array('accid' => 'USKS0040', 'name' => 'Barnes');
$city_data[] = array('accid' => 'USKS0041', 'name' => 'Bartlett');
$city_data[] = array('accid' => 'USKS0042', 'name' => 'Basehor');
$city_data[] = array('accid' => 'USKS0043', 'name' => 'Baxter Springs');
$city_data[] = array('accid' => 'USKS0044', 'name' => 'Bazine');
$city_data[] = array('accid' => 'USKS0045', 'name' => 'Beattie');
$city_data[] = array('accid' => 'USKS0046', 'name' => 'Beaumont');
$city_data[] = array('accid' => 'USKS0047', 'name' => 'Beeler');
$city_data[] = array('accid' => 'USKS0048', 'name' => 'Belle Plaine');
$city_data[] = array('accid' => 'USKS0049', 'name' => 'Belleville');
$city_data[] = array('accid' => 'USKS0050', 'name' => 'Beloit');
$city_data[] = array('accid' => 'USKS0051', 'name' => 'Belpre');
$city_data[] = array('accid' => 'USKS0052', 'name' => 'Belvue');
$city_data[] = array('accid' => 'USKS0053', 'name' => 'Bendena');
$city_data[] = array('accid' => 'USKS0054', 'name' => 'Benedict');
$city_data[] = array('accid' => 'USKS0055', 'name' => 'Bennington');
$city_data[] = array('accid' => 'USKS0056', 'name' => 'Bentley');
$city_data[] = array('accid' => 'USKS0057', 'name' => 'Benton');
$city_data[] = array('accid' => 'USKS0058', 'name' => 'Bern');
$city_data[] = array('accid' => 'USKS0059', 'name' => 'Berryton');
$city_data[] = array('accid' => 'USKS0060', 'name' => 'Beverly');
$city_data[] = array('accid' => 'USKS0061', 'name' => 'Bird City');
$city_data[] = array('accid' => 'USKS0062', 'name' => 'Bison');
$city_data[] = array('accid' => 'USKS0063', 'name' => 'Blue Mound');
$city_data[] = array('accid' => 'USKS0064', 'name' => 'Blue Rapids');
$city_data[] = array('accid' => 'USKS0065', 'name' => 'Bluff City');
$city_data[] = array('accid' => 'USKS0066', 'name' => 'Bogue');
$city_data[] = array('accid' => 'USKS0067', 'name' => 'Bonner Springs');
$city_data[] = array('accid' => 'USKS0068', 'name' => 'Bremen');
$city_data[] = array('accid' => 'USKS0069', 'name' => 'Brewster');
$city_data[] = array('accid' => 'USKS0070', 'name' => 'Bronson');
$city_data[] = array('accid' => 'USKS0071', 'name' => 'Brookville');
$city_data[] = array('accid' => 'USKS0072', 'name' => 'Brownell');
$city_data[] = array('accid' => 'USKS0073', 'name' => 'Bucklin');
$city_data[] = array('accid' => 'USKS0074', 'name' => 'Bucyrus');
$city_data[] = array('accid' => 'USKS0075', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USKS0076', 'name' => 'Buhler');
$city_data[] = array('accid' => 'USKS0077', 'name' => 'Bunker Hill');
$city_data[] = array('accid' => 'USKS0078', 'name' => 'Burden');
$city_data[] = array('accid' => 'USKS0079', 'name' => 'Burdett');
$city_data[] = array('accid' => 'USKS0080', 'name' => 'Burdick');
$city_data[] = array('accid' => 'USKS0081', 'name' => 'Burlingame');
$city_data[] = array('accid' => 'USKS0082', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USKS0083', 'name' => 'Burns');
$city_data[] = array('accid' => 'USKS0084', 'name' => 'Burr Oak');
$city_data[] = array('accid' => 'USKS0085', 'name' => 'Burrton');
$city_data[] = array('accid' => 'USKS0086', 'name' => 'Bushton');
$city_data[] = array('accid' => 'USKS0087', 'name' => 'Byers');
$city_data[] = array('accid' => 'USKS0088', 'name' => 'Caldwell');
$city_data[] = array('accid' => 'USKS0089', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'USKS0090', 'name' => 'Caney');
$city_data[] = array('accid' => 'USKS0091', 'name' => 'Canton');
$city_data[] = array('accid' => 'USKS0092', 'name' => 'Carbondale');
$city_data[] = array('accid' => 'USKS0093', 'name' => 'Cassoday');
$city_data[] = array('accid' => 'USKS0094', 'name' => 'Catharine');
$city_data[] = array('accid' => 'USKS0095', 'name' => 'Cawker City');
$city_data[] = array('accid' => 'USKS0096', 'name' => 'Cedar');
$city_data[] = array('accid' => 'USKS0097', 'name' => 'Cedar Point');
$city_data[] = array('accid' => 'USKS0098', 'name' => 'Cedar Vale');
$city_data[] = array('accid' => 'USKS0099', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USKS0100', 'name' => 'Centralia');
$city_data[] = array('accid' => 'USKS0101', 'name' => 'Chanute');
$city_data[] = array('accid' => 'USKS0102', 'name' => 'Chapman');
$city_data[] = array('accid' => 'USKS0103', 'name' => 'Chase');
$city_data[] = array('accid' => 'USKS0104', 'name' => 'Chautauqua');
$city_data[] = array('accid' => 'USKS0105', 'name' => 'Cheney');
$city_data[] = array('accid' => 'USKS0106', 'name' => 'Cherokee');
$city_data[] = array('accid' => 'USKS0107', 'name' => 'Cherryvale');
$city_data[] = array('accid' => 'USKS0108', 'name' => 'Chetopa');
$city_data[] = array('accid' => 'USKS0109', 'name' => 'Cimarron');
$city_data[] = array('accid' => 'USKS0110', 'name' => 'Circleville');
$city_data[] = array('accid' => 'USKS0111', 'name' => 'Claflin');
$city_data[] = array('accid' => 'USKS0112', 'name' => 'Clay Center');
$city_data[] = array('accid' => 'USKS0113', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USKS0114', 'name' => 'Clearview City');
$city_data[] = array('accid' => 'USKS0115', 'name' => 'Clearwater');
$city_data[] = array('accid' => 'USKS0116', 'name' => 'Clifton');
$city_data[] = array('accid' => 'USKS0117', 'name' => 'Clyde');
$city_data[] = array('accid' => 'USKS0118', 'name' => 'Coats');
$city_data[] = array('accid' => 'USKS0119', 'name' => 'Coffeyville');
$city_data[] = array('accid' => 'USKS0120', 'name' => 'Colby');
$city_data[] = array('accid' => 'USKS0121', 'name' => 'Coldwater');
$city_data[] = array('accid' => 'USKS0122', 'name' => 'Collyer');
$city_data[] = array('accid' => 'USKS0123', 'name' => 'Colony');
$city_data[] = array('accid' => 'USKS0124', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USKS0125', 'name' => 'Colwich');
$city_data[] = array('accid' => 'USKS0126', 'name' => 'Concordia');
$city_data[] = array('accid' => 'USKS0127', 'name' => 'Conway Springs');
$city_data[] = array('accid' => 'USKS0128', 'name' => 'Coolidge');
$city_data[] = array('accid' => 'USKS0129', 'name' => 'Copeland');
$city_data[] = array('accid' => 'USKS0130', 'name' => 'Corning');
$city_data[] = array('accid' => 'USKS0131', 'name' => 'Cottonwood Falls');
$city_data[] = array('accid' => 'USKS0132', 'name' => 'Council Grove');
$city_data[] = array('accid' => 'USKS0133', 'name' => 'Courtland');
$city_data[] = array('accid' => 'USKS0134', 'name' => 'Coyville');
$city_data[] = array('accid' => 'USKS0135', 'name' => 'Crestline');
$city_data[] = array('accid' => 'USKS0136', 'name' => 'Cuba');
$city_data[] = array('accid' => 'USKS0137', 'name' => 'Cummings');
$city_data[] = array('accid' => 'USKS0138', 'name' => 'Cunningham');
$city_data[] = array('accid' => 'USKS0139', 'name' => 'Damar');
$city_data[] = array('accid' => 'USKS0140', 'name' => 'Danville');
$city_data[] = array('accid' => 'USKS0141', 'name' => 'De Soto');
$city_data[] = array('accid' => 'USKS0142', 'name' => 'Dearing');
$city_data[] = array('accid' => 'USKS0143', 'name' => 'Deerfield');
$city_data[] = array('accid' => 'USKS0144', 'name' => 'Delia');
$city_data[] = array('accid' => 'USKS0145', 'name' => 'Delphos');
$city_data[] = array('accid' => 'USKS0146', 'name' => 'Denison');
$city_data[] = array('accid' => 'USKS0147', 'name' => 'Dennis');
$city_data[] = array('accid' => 'USKS0148', 'name' => 'Denton');
$city_data[] = array('accid' => 'USKS0149', 'name' => 'Derby');
$city_data[] = array('accid' => 'USKS0150', 'name' => 'Dexter');
$city_data[] = array('accid' => 'USKS0151', 'name' => 'Dighton');
$city_data[] = array('accid' => 'USKS0152', 'name' => 'Dodge City');
$city_data[] = array('accid' => 'USKS0153', 'name' => 'Dorrance');
$city_data[] = array('accid' => 'USKS0154', 'name' => 'Douglass');
$city_data[] = array('accid' => 'USKS0155', 'name' => 'Dover');
$city_data[] = array('accid' => 'USKS0156', 'name' => 'Downs');
$city_data[] = array('accid' => 'USKS0157', 'name' => 'Dresden');
$city_data[] = array('accid' => 'USKS0158', 'name' => 'Durham');
$city_data[] = array('accid' => 'USKS0159', 'name' => 'Dwight');
$city_data[] = array('accid' => 'USKS0160', 'name' => 'Easton');
$city_data[] = array('accid' => 'USKS0161', 'name' => 'Edgerton');
$city_data[] = array('accid' => 'USKS0162', 'name' => 'Edna');
$city_data[] = array('accid' => 'USKS0163', 'name' => 'Edson');
$city_data[] = array('accid' => 'USKS0164', 'name' => 'Edwardsville');
$city_data[] = array('accid' => 'USKS0165', 'name' => 'Effingham');
$city_data[] = array('accid' => 'USKS0166', 'name' => 'El Dorado');
$city_data[] = array('accid' => 'USKS0167', 'name' => 'Elbing');
$city_data[] = array('accid' => 'USKS0168', 'name' => 'Elk City');
$city_data[] = array('accid' => 'USKS0169', 'name' => 'Elk Falls');
$city_data[] = array('accid' => 'USKS0170', 'name' => 'Elkhart');
$city_data[] = array('accid' => 'USKS0171', 'name' => 'Ellinwood');
$city_data[] = array('accid' => 'USKS0172', 'name' => 'Ellis');
$city_data[] = array('accid' => 'USKS0173', 'name' => 'Ellsworth');
$city_data[] = array('accid' => 'USKS0174', 'name' => 'Elmdale');
$city_data[] = array('accid' => 'USKS0175', 'name' => 'Elsmore');
$city_data[] = array('accid' => 'USKS0176', 'name' => 'Elwood');
$city_data[] = array('accid' => 'USKS0177', 'name' => 'Emmett');
$city_data[] = array('accid' => 'USKS0178', 'name' => 'Emporia');
$city_data[] = array('accid' => 'USKS0179', 'name' => 'Englewood');
$city_data[] = array('accid' => 'USKS0180', 'name' => 'Ensign');
$city_data[] = array('accid' => 'USKS0181', 'name' => 'Enterprise');
$city_data[] = array('accid' => 'USKS0182', 'name' => 'Erie');
$city_data[] = array('accid' => 'USKS0183', 'name' => 'Esbon');
$city_data[] = array('accid' => 'USKS0184', 'name' => 'Eskridge');
$city_data[] = array('accid' => 'USKS0185', 'name' => 'Eudora');
$city_data[] = array('accid' => 'USKS0186', 'name' => 'Eureka');
$city_data[] = array('accid' => 'USKS0187', 'name' => 'Everest');
$city_data[] = array('accid' => 'USKS0188', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USKS0189', 'name' => 'Fall River');
$city_data[] = array('accid' => 'USKS0190', 'name' => 'Falun');
$city_data[] = array('accid' => 'USKS0191', 'name' => 'Farlington');
$city_data[] = array('accid' => 'USKS0192', 'name' => 'Florence');
$city_data[] = array('accid' => 'USKS0193', 'name' => 'Fontana');
$city_data[] = array('accid' => 'USKS0194', 'name' => 'Ford');
$city_data[] = array('accid' => 'USKS0195', 'name' => 'Formoso');
$city_data[] = array('accid' => 'USKS0640', 'name' => 'Fort Dodge');
$city_data[] = array('accid' => 'USKS0196', 'name' => 'Fort Leavenworth');
$city_data[] = array('accid' => 'USKS0197', 'name' => 'Fort Riley');
$city_data[] = array('accid' => 'USKS0198', 'name' => 'Fort Scott');
$city_data[] = array('accid' => 'USKS0199', 'name' => 'Fostoria');
$city_data[] = array('accid' => 'USKS0200', 'name' => 'Fowler');
$city_data[] = array('accid' => 'USKS0201', 'name' => 'Frankfort');
$city_data[] = array('accid' => 'USKS0202', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USKS0203', 'name' => 'Fredonia');
$city_data[] = array('accid' => 'USKS0204', 'name' => 'Freeport');
$city_data[] = array('accid' => 'USKS0205', 'name' => 'Frontenac');
$city_data[] = array('accid' => 'USKS0206', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USKS0207', 'name' => 'Galena');
$city_data[] = array('accid' => 'USKS0208', 'name' => 'Galesburg');
$city_data[] = array('accid' => 'USKS0209', 'name' => 'Galva');
$city_data[] = array('accid' => 'USKS0210', 'name' => 'Garden City');
$city_data[] = array('accid' => 'USKS0211', 'name' => 'Garden Plain');
$city_data[] = array('accid' => 'USKS0212', 'name' => 'Gardner');
$city_data[] = array('accid' => 'USKS0213', 'name' => 'Garfield');
$city_data[] = array('accid' => 'USKS0214', 'name' => 'Garnett');
$city_data[] = array('accid' => 'USKS0215', 'name' => 'Gas');
$city_data[] = array('accid' => 'USKS0216', 'name' => 'Gaylord');
$city_data[] = array('accid' => 'USKS0217', 'name' => 'Gem');
$city_data[] = array('accid' => 'USKS0218', 'name' => 'Geneseo');
$city_data[] = array('accid' => 'USKS0219', 'name' => 'Geuda Springs');
$city_data[] = array('accid' => 'USKS0220', 'name' => 'Girard');
$city_data[] = array('accid' => 'USKS0221', 'name' => 'Glade');
$city_data[] = array('accid' => 'USKS0222', 'name' => 'Glasco');
$city_data[] = array('accid' => 'USKS0223', 'name' => 'Glen Elder');
$city_data[] = array('accid' => 'USKS0224', 'name' => 'Goddard');
$city_data[] = array('accid' => 'USKS0225', 'name' => 'Goessel');
$city_data[] = array('accid' => 'USKS0226', 'name' => 'Goff');
$city_data[] = array('accid' => 'USKS0227', 'name' => 'Goodland');
$city_data[] = array('accid' => 'USKS0228', 'name' => 'Gorham');
$city_data[] = array('accid' => 'USKS0229', 'name' => 'Gove');
$city_data[] = array('accid' => 'USKS0230', 'name' => 'Grainfield');
$city_data[] = array('accid' => 'USKS0231', 'name' => 'Grantville');
$city_data[] = array('accid' => 'USKS0232', 'name' => 'Great Bend');
$city_data[] = array('accid' => 'USKS0233', 'name' => 'Greeley');
$city_data[] = array('accid' => 'USKS0234', 'name' => 'Green');
$city_data[] = array('accid' => 'USKS0235', 'name' => 'Greenleaf');
$city_data[] = array('accid' => 'USKS0236', 'name' => 'Greensburg');
$city_data[] = array('accid' => 'USKS0237', 'name' => 'Greenwich');
$city_data[] = array('accid' => 'USKS0238', 'name' => 'Grenola');
$city_data[] = array('accid' => 'USKS0239', 'name' => 'Gridley');
$city_data[] = array('accid' => 'USKS0240', 'name' => 'Grinnell');
$city_data[] = array('accid' => 'USKS0241', 'name' => 'Gypsum');
$city_data[] = array('accid' => 'USKS0242', 'name' => 'Haddam');
$city_data[] = array('accid' => 'USKS0243', 'name' => 'Halstead');
$city_data[] = array('accid' => 'USKS0244', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USKS0245', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USKS0246', 'name' => 'Hanston');
$city_data[] = array('accid' => 'USKS0247', 'name' => 'Hardtner');
$city_data[] = array('accid' => 'USKS0248', 'name' => 'Harper');
$city_data[] = array('accid' => 'USKS0249', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USKS0250', 'name' => 'Harveyville');
$city_data[] = array('accid' => 'USKS0251', 'name' => 'Havana');
$city_data[] = array('accid' => 'USKS0252', 'name' => 'Haven');
$city_data[] = array('accid' => 'USKS0253', 'name' => 'Havensville');
$city_data[] = array('accid' => 'USKS0254', 'name' => 'Haviland');
$city_data[] = array('accid' => 'USKS0255', 'name' => 'Hays');
$city_data[] = array('accid' => 'USKS0256', 'name' => 'Haysville');
$city_data[] = array('accid' => 'USKS0257', 'name' => 'Hazelton');
$city_data[] = array('accid' => 'USKS0258', 'name' => 'Healy');
$city_data[] = array('accid' => 'USKS0259', 'name' => 'Hepler');
$city_data[] = array('accid' => 'USKS0260', 'name' => 'Herington');
$city_data[] = array('accid' => 'USKS0261', 'name' => 'Herndon');
$city_data[] = array('accid' => 'USKS0262', 'name' => 'Hesston');
$city_data[] = array('accid' => 'USKS0263', 'name' => 'Hiawatha');
$city_data[] = array('accid' => 'USKS0264', 'name' => 'Highland');
$city_data[] = array('accid' => 'USKS0265', 'name' => 'Hill City');
$city_data[] = array('accid' => 'USKS0266', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USKS0267', 'name' => 'Hillsdale');
$city_data[] = array('accid' => 'USKS0268', 'name' => 'Hoisington');
$city_data[] = array('accid' => 'USKS0269', 'name' => 'Holcomb');
$city_data[] = array('accid' => 'USKS0270', 'name' => 'Hollenberg');
$city_data[] = array('accid' => 'USKS0271', 'name' => 'Holton');
$city_data[] = array('accid' => 'USKS0272', 'name' => 'Holyrood');
$city_data[] = array('accid' => 'USKS0273', 'name' => 'Home');
$city_data[] = array('accid' => 'USKS0274', 'name' => 'Hope');
$city_data[] = array('accid' => 'USKS0275', 'name' => 'Horton');
$city_data[] = array('accid' => 'USKS0276', 'name' => 'Howard');
$city_data[] = array('accid' => 'USKS0277', 'name' => 'Hoxie');
$city_data[] = array('accid' => 'USKS0278', 'name' => 'Hoyt');
$city_data[] = array('accid' => 'USKS0279', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USKS0280', 'name' => 'Hugoton');
$city_data[] = array('accid' => 'USKS0281', 'name' => 'Humboldt');
$city_data[] = array('accid' => 'USKS0282', 'name' => 'Hunter');
$city_data[] = array('accid' => 'USKS0283', 'name' => 'Hutchinson');
$city_data[] = array('accid' => 'USKS0284', 'name' => 'Independence');
$city_data[] = array('accid' => 'USKS0285', 'name' => 'Ingalls');
$city_data[] = array('accid' => 'USKS0286', 'name' => 'Inman');
$city_data[] = array('accid' => 'USKS0287', 'name' => 'Iola');
$city_data[] = array('accid' => 'USKS0288', 'name' => 'Isabel');
$city_data[] = array('accid' => 'USKS0289', 'name' => 'Iuka');
$city_data[] = array('accid' => 'USKS0290', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USKS0291', 'name' => 'Jennings');
$city_data[] = array('accid' => 'USKS0292', 'name' => 'Jetmore');
$city_data[] = array('accid' => 'USKS0293', 'name' => 'Jewell');
$city_data[] = array('accid' => 'USKS0294', 'name' => 'Johnson');
$city_data[] = array('accid' => 'USKS0295', 'name' => 'Junction City');
$city_data[] = array('accid' => 'USKS0296', 'name' => 'Kanopolis');
$city_data[] = array('accid' => 'USKS0297', 'name' => 'Kanorado');
$city_data[] = array('accid' => 'USKS0298', 'name' => 'Kansas City');
$city_data[] = array('accid' => 'USKS0299', 'name' => 'Kechi');
$city_data[] = array('accid' => 'USKS0300', 'name' => 'Kendall');
$city_data[] = array('accid' => 'USKS0301', 'name' => 'Kensington');
$city_data[] = array('accid' => 'USKS0302', 'name' => 'Kincaid');
$city_data[] = array('accid' => 'USKS0303', 'name' => 'Kingman');
$city_data[] = array('accid' => 'USKS0304', 'name' => 'Kinsley');
$city_data[] = array('accid' => 'USKS0305', 'name' => 'Kiowa');
$city_data[] = array('accid' => 'USKS0306', 'name' => 'Kirwin');
$city_data[] = array('accid' => 'USKS0307', 'name' => 'Kismet');
$city_data[] = array('accid' => 'USKS0308', 'name' => 'La Crosse');
$city_data[] = array('accid' => 'USKS0309', 'name' => 'La Cygne');
$city_data[] = array('accid' => 'USKS0310', 'name' => 'La Harpe');
$city_data[] = array('accid' => 'USKS0311', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USKS0312', 'name' => 'Lakin');
$city_data[] = array('accid' => 'USKS0313', 'name' => 'Lamont');
$city_data[] = array('accid' => 'USKS0314', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USKS0315', 'name' => 'Lane');
$city_data[] = array('accid' => 'USKS0316', 'name' => 'Lansing');
$city_data[] = array('accid' => 'USKS0317', 'name' => 'Larned');
$city_data[] = array('accid' => 'USKS0318', 'name' => 'Latham');
$city_data[] = array('accid' => 'USKS0319', 'name' => 'Lawrence');
$city_data[] = array('accid' => 'USKS0320', 'name' => 'Le Roy');
$city_data[] = array('accid' => 'USKS0321', 'name' => 'Leavenworth');
$city_data[] = array('accid' => 'USKS0322', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USKS0323', 'name' => 'Lebo');
$city_data[] = array('accid' => 'USKS0324', 'name' => 'Lecompton');
$city_data[] = array('accid' => 'USKS0325', 'name' => 'Lehigh');
$city_data[] = array('accid' => 'USKS0326', 'name' => 'Lenora');
$city_data[] = array('accid' => 'USKS0327', 'name' => 'Leon');
$city_data[] = array('accid' => 'USKS0328', 'name' => 'Leonardville');
$city_data[] = array('accid' => 'USKS0329', 'name' => 'Leoti');
$city_data[] = array('accid' => 'USKS0330', 'name' => 'Levant');
$city_data[] = array('accid' => 'USKS0331', 'name' => 'Lewis');
$city_data[] = array('accid' => 'USKS0332', 'name' => 'Liberal');
$city_data[] = array('accid' => 'USKS0333', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USKS0334', 'name' => 'Liebenthal');
$city_data[] = array('accid' => 'USKS0335', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USKS0336', 'name' => 'Lincolnville');
$city_data[] = array('accid' => 'USKS0337', 'name' => 'Lindsborg');
$city_data[] = array('accid' => 'USKS0338', 'name' => 'Linn');
$city_data[] = array('accid' => 'USKS0339', 'name' => 'Linwood');
$city_data[] = array('accid' => 'USKS0340', 'name' => 'Little River');
$city_data[] = array('accid' => 'USKS0341', 'name' => 'Logan');
$city_data[] = array('accid' => 'USKS0342', 'name' => 'Long Island');
$city_data[] = array('accid' => 'USKS0343', 'name' => 'Longford');
$city_data[] = array('accid' => 'USKS0344', 'name' => 'Longton');
$city_data[] = array('accid' => 'USKS0345', 'name' => 'Lorraine');
$city_data[] = array('accid' => 'USKS0346', 'name' => 'Lost Springs');
$city_data[] = array('accid' => 'USKS0347', 'name' => 'Louisburg');
$city_data[] = array('accid' => 'USKS0348', 'name' => 'Louisville');
$city_data[] = array('accid' => 'USKS0349', 'name' => 'Lucas');
$city_data[] = array('accid' => 'USKS0350', 'name' => 'Ludell');
$city_data[] = array('accid' => 'USKS0351', 'name' => 'Luray');
$city_data[] = array('accid' => 'USKS0352', 'name' => 'Lyndon');
$city_data[] = array('accid' => 'USKS0353', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USKS0354', 'name' => 'Macksville');
$city_data[] = array('accid' => 'USKS0355', 'name' => 'Madison');
$city_data[] = array('accid' => 'USKS0356', 'name' => 'Mahaska');
$city_data[] = array('accid' => 'USKS0357', 'name' => 'Maize');
$city_data[] = array('accid' => 'USKS0358', 'name' => 'Manhattan');
$city_data[] = array('accid' => 'USKS0359', 'name' => 'Mankato');
$city_data[] = array('accid' => 'USKS0360', 'name' => 'Manter');
$city_data[] = array('accid' => 'USKS0361', 'name' => 'Maple City');
$city_data[] = array('accid' => 'USKS0362', 'name' => 'Maple Hill');
$city_data[] = array('accid' => 'USKS0363', 'name' => 'Mapleton');
$city_data[] = array('accid' => 'USKS0364', 'name' => 'Marienthal');
$city_data[] = array('accid' => 'USKS0365', 'name' => 'Marion');
$city_data[] = array('accid' => 'USKS0366', 'name' => 'Marquette');
$city_data[] = array('accid' => 'USKS0367', 'name' => 'Marysville');
$city_data[] = array('accid' => 'USKS0368', 'name' => 'Matfield Green');
$city_data[] = array('accid' => 'USKS0369', 'name' => 'Mayetta');
$city_data[] = array('accid' => 'USKS0370', 'name' => 'Mayfield');
$city_data[] = array('accid' => 'USKS0371', 'name' => 'McConnell AFB');
$city_data[] = array('accid' => 'USKS0372', 'name' => 'McCracken');
$city_data[] = array('accid' => 'USKS0373', 'name' => 'McCune');
$city_data[] = array('accid' => 'USKS0374', 'name' => 'McDonald');
$city_data[] = array('accid' => 'USKS0375', 'name' => 'McFarland');
$city_data[] = array('accid' => 'USKS0376', 'name' => 'McLouth');
$city_data[] = array('accid' => 'USKS0377', 'name' => 'McPherson');
$city_data[] = array('accid' => 'USKS0378', 'name' => 'Meade');
$city_data[] = array('accid' => 'USKS0379', 'name' => 'Medicine Lodge');
$city_data[] = array('accid' => 'USKS0380', 'name' => 'Melvern');
$city_data[] = array('accid' => 'USKS0381', 'name' => 'Meriden');
$city_data[] = array('accid' => 'USKS0382', 'name' => 'Milan');
$city_data[] = array('accid' => 'USKS0383', 'name' => 'Milford');
$city_data[] = array('accid' => 'USKS0384', 'name' => 'Milton');
$city_data[] = array('accid' => 'USKS0385', 'name' => 'Miltonvale');
$city_data[] = array('accid' => 'USKS0386', 'name' => 'Minneapolis');
$city_data[] = array('accid' => 'USKS0387', 'name' => 'Minneola');
$city_data[] = array('accid' => 'USKS0388', 'name' => 'Moline');
$city_data[] = array('accid' => 'USKS0389', 'name' => 'Montezuma');
$city_data[] = array('accid' => 'USKS0390', 'name' => 'Monument');
$city_data[] = array('accid' => 'USKS0391', 'name' => 'Moran');
$city_data[] = array('accid' => 'USKS0392', 'name' => 'Morganville');
$city_data[] = array('accid' => 'USKS0393', 'name' => 'Morland');
$city_data[] = array('accid' => 'USKS0394', 'name' => 'Morrill');
$city_data[] = array('accid' => 'USKS0395', 'name' => 'Morrowville');
$city_data[] = array('accid' => 'USKS0396', 'name' => 'Moscow');
$city_data[] = array('accid' => 'USKS0397', 'name' => 'Mound City');
$city_data[] = array('accid' => 'USKS0398', 'name' => 'Mound Valley');
$city_data[] = array('accid' => 'USKS0399', 'name' => 'Moundridge');
$city_data[] = array('accid' => 'USKS0400', 'name' => 'Mount Hope');
$city_data[] = array('accid' => 'USKS0401', 'name' => 'Mulberry');
$city_data[] = array('accid' => 'USKS0402', 'name' => 'Mullinville');
$city_data[] = array('accid' => 'USKS0403', 'name' => 'Mulvane');
$city_data[] = array('accid' => 'USKS0404', 'name' => 'Munden');
$city_data[] = array('accid' => 'USKS0405', 'name' => 'Murdock');
$city_data[] = array('accid' => 'USKS0406', 'name' => 'Muscotah');
$city_data[] = array('accid' => 'USKS0407', 'name' => 'Narka');
$city_data[] = array('accid' => 'USKS0408', 'name' => 'Nashville');
$city_data[] = array('accid' => 'USKS0409', 'name' => 'Natoma');
$city_data[] = array('accid' => 'USKS0410', 'name' => 'Neal');
$city_data[] = array('accid' => 'USKS0411', 'name' => 'Nekoma');
$city_data[] = array('accid' => 'USKS0412', 'name' => 'Neodesha');
$city_data[] = array('accid' => 'USKS0413', 'name' => 'Neosho Falls');
$city_data[] = array('accid' => 'USKS0414', 'name' => 'Neosho Rapids');
$city_data[] = array('accid' => 'USKS0415', 'name' => 'Ness City');
$city_data[] = array('accid' => 'USKS0416', 'name' => 'Netawaka');
$city_data[] = array('accid' => 'USKS0417', 'name' => 'New Albany');
$city_data[] = array('accid' => 'USKS0418', 'name' => 'New Cambria');
$city_data[] = array('accid' => 'USKS0419', 'name' => 'New Century');
$city_data[] = array('accid' => 'USKS0420', 'name' => 'Newton');
$city_data[] = array('accid' => 'USKS0421', 'name' => 'Nickerson');
$city_data[] = array('accid' => 'USKS0422', 'name' => 'Niotaze');
$city_data[] = array('accid' => 'USKS0423', 'name' => 'Norcatur');
$city_data[] = array('accid' => 'USKS0424', 'name' => 'North Newton');
$city_data[] = array('accid' => 'USKS0425', 'name' => 'Norton');
$city_data[] = array('accid' => 'USKS0426', 'name' => 'Nortonville');
$city_data[] = array('accid' => 'USKS0427', 'name' => 'Norway');
$city_data[] = array('accid' => 'USKS0428', 'name' => 'Norwich');
$city_data[] = array('accid' => 'USKS0429', 'name' => 'Oakley');
$city_data[] = array('accid' => 'USKS0430', 'name' => 'Oberlin');
$city_data[] = array('accid' => 'USKS0431', 'name' => 'Offerle');
$city_data[] = array('accid' => 'USKS0432', 'name' => 'Ogallah');
$city_data[] = array('accid' => 'USKS0433', 'name' => 'Ogden');
$city_data[] = array('accid' => 'USKS0434', 'name' => 'Oketo');
$city_data[] = array('accid' => 'USKS0435', 'name' => 'Olathe');
$city_data[] = array('accid' => 'USKS0436', 'name' => 'Olmitz');
$city_data[] = array('accid' => 'USKS0437', 'name' => 'Olpe');
$city_data[] = array('accid' => 'USKS0438', 'name' => 'Olsburg');
$city_data[] = array('accid' => 'USKS0439', 'name' => 'Onaga');
$city_data[] = array('accid' => 'USKS0440', 'name' => 'Oneida');
$city_data[] = array('accid' => 'USKS0441', 'name' => 'Opolis');
$city_data[] = array('accid' => 'USKS0442', 'name' => 'Osage City');
$city_data[] = array('accid' => 'USKS0443', 'name' => 'Osawatomie');
$city_data[] = array('accid' => 'USKS0444', 'name' => 'Osborne');
$city_data[] = array('accid' => 'USKS0445', 'name' => 'Oskaloosa');
$city_data[] = array('accid' => 'USKS0446', 'name' => 'Oswego');
$city_data[] = array('accid' => 'USKS0447', 'name' => 'Otis');
$city_data[] = array('accid' => 'USKS0448', 'name' => 'Ottawa');
$city_data[] = array('accid' => 'USKS0449', 'name' => 'Overbrook');
$city_data[] = array('accid' => 'USKS0451', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USKS0452', 'name' => 'Ozawkie');
$city_data[] = array('accid' => 'USKS0453', 'name' => 'Palco');
$city_data[] = array('accid' => 'USKS0454', 'name' => 'Palmer');
$city_data[] = array('accid' => 'USKS0455', 'name' => 'Paola');
$city_data[] = array('accid' => 'USKS0456', 'name' => 'Paradise');
$city_data[] = array('accid' => 'USKS0457', 'name' => 'Park');
$city_data[] = array('accid' => 'USKS0458', 'name' => 'Parker');
$city_data[] = array('accid' => 'USKS0459', 'name' => 'Parsons');
$city_data[] = array('accid' => 'USKS0460', 'name' => 'Partridge');
$city_data[] = array('accid' => 'USKS0461', 'name' => 'Pawnee Rock');
$city_data[] = array('accid' => 'USKS0462', 'name' => 'Paxico');
$city_data[] = array('accid' => 'USKS0463', 'name' => 'Peabody');
$city_data[] = array('accid' => 'USKS0464', 'name' => 'Peck');
$city_data[] = array('accid' => 'USKS0465', 'name' => 'Penokee');
$city_data[] = array('accid' => 'USKS0466', 'name' => 'Perry');
$city_data[] = array('accid' => 'USKS0467', 'name' => 'Peru');
$city_data[] = array('accid' => 'USKS0468', 'name' => 'Pfeifer');
$city_data[] = array('accid' => 'USKS0469', 'name' => 'Phillipsburg');
$city_data[] = array('accid' => 'USKS0470', 'name' => 'Piedmont');
$city_data[] = array('accid' => 'USKS0471', 'name' => 'Pierceville');
$city_data[] = array('accid' => 'USKS0472', 'name' => 'Piqua');
$city_data[] = array('accid' => 'USKS0473', 'name' => 'Pittsburg');
$city_data[] = array('accid' => 'USKS0474', 'name' => 'Plains');
$city_data[] = array('accid' => 'USKS0475', 'name' => 'Plainville');
$city_data[] = array('accid' => 'USKS0476', 'name' => 'Pleasanton');
$city_data[] = array('accid' => 'USKS0477', 'name' => 'Plevna');
$city_data[] = array('accid' => 'USKS0478', 'name' => 'Pomona');
$city_data[] = array('accid' => 'USKS0479', 'name' => 'Portis');
$city_data[] = array('accid' => 'USKS0480', 'name' => 'Potter');
$city_data[] = array('accid' => 'USKS0481', 'name' => 'Potwin');
$city_data[] = array('accid' => 'USKS0482', 'name' => 'Powhattan');
$city_data[] = array('accid' => 'USKS0483', 'name' => 'Prairie View');
$city_data[] = array('accid' => 'USKS0484', 'name' => 'Pratt');
$city_data[] = array('accid' => 'USKS0485', 'name' => 'Prescott');
$city_data[] = array('accid' => 'USKS0486', 'name' => 'Pretty Prairie');
$city_data[] = array('accid' => 'USKS0487', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USKS0488', 'name' => 'Protection');
$city_data[] = array('accid' => 'USKS0489', 'name' => 'Quenemo');
$city_data[] = array('accid' => 'USKS0490', 'name' => 'Quinter');
$city_data[] = array('accid' => 'USKS0491', 'name' => 'Rago');
$city_data[] = array('accid' => 'USKS0492', 'name' => 'Ramona');
$city_data[] = array('accid' => 'USKS0493', 'name' => 'Randall');
$city_data[] = array('accid' => 'USKS0494', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USKS0495', 'name' => 'Ransom');
$city_data[] = array('accid' => 'USKS0496', 'name' => 'Rantoul');
$city_data[] = array('accid' => 'USKS0497', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USKS0498', 'name' => 'Reading');
$city_data[] = array('accid' => 'USKS0499', 'name' => 'Redfield');
$city_data[] = array('accid' => 'USKS0500', 'name' => 'Republic');
$city_data[] = array('accid' => 'USKS0501', 'name' => 'Rexford');
$city_data[] = array('accid' => 'USKS0502', 'name' => 'Richfield');
$city_data[] = array('accid' => 'USKS0503', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USKS0504', 'name' => 'Riley');
$city_data[] = array('accid' => 'USKS0505', 'name' => 'Riverton');
$city_data[] = array('accid' => 'USKS0506', 'name' => 'Robinson');
$city_data[] = array('accid' => 'USKS0507', 'name' => 'Rock');
$city_data[] = array('accid' => 'USKS0508', 'name' => 'Rolla');
$city_data[] = array('accid' => 'USKS0509', 'name' => 'Rosalia');
$city_data[] = array('accid' => 'USKS0510', 'name' => 'Rose Hill');
$city_data[] = array('accid' => 'USKS0511', 'name' => 'Rossville');
$city_data[] = array('accid' => 'USKS0512', 'name' => 'Roxbury');
$city_data[] = array('accid' => 'USKS0513', 'name' => 'Rozel');
$city_data[] = array('accid' => 'USKS0514', 'name' => 'Rush Center');
$city_data[] = array('accid' => 'USKS0515', 'name' => 'Russell');
$city_data[] = array('accid' => 'USKS0516', 'name' => 'Russell Springs');
$city_data[] = array('accid' => 'USKS0517', 'name' => 'Sabetha');
$city_data[] = array('accid' => 'USKS0518', 'name' => 'Saint Francis');
$city_data[] = array('accid' => 'USKS0519', 'name' => 'Saint George');
$city_data[] = array('accid' => 'USKS0520', 'name' => 'Saint John');
$city_data[] = array('accid' => 'USKS0521', 'name' => 'Saint Marys');
$city_data[] = array('accid' => 'USKS0522', 'name' => 'Saint Paul');
$city_data[] = array('accid' => 'USKS0523', 'name' => 'Salina');
$city_data[] = array('accid' => 'USKS0524', 'name' => 'Satanta');
$city_data[] = array('accid' => 'USKS0525', 'name' => 'Savonburg');
$city_data[] = array('accid' => 'USKS0526', 'name' => 'Sawyer');
$city_data[] = array('accid' => 'USKS0527', 'name' => 'Scammon');
$city_data[] = array('accid' => 'USKS0528', 'name' => 'Scandia');
$city_data[] = array('accid' => 'USKS0529', 'name' => 'Schoenchen');
$city_data[] = array('accid' => 'USKS0530', 'name' => 'Scott City');
$city_data[] = array('accid' => 'USKS0531', 'name' => 'Scranton');
$city_data[] = array('accid' => 'USKS0532', 'name' => 'Sedan');
$city_data[] = array('accid' => 'USKS0533', 'name' => 'Sedgwick');
$city_data[] = array('accid' => 'USKS0534', 'name' => 'Selden');
$city_data[] = array('accid' => 'USKS0535', 'name' => 'Seneca');
$city_data[] = array('accid' => 'USKS0536', 'name' => 'Severy');
$city_data[] = array('accid' => 'USKS0537', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USKS0538', 'name' => 'Sharon Springs');
$city_data[] = array('accid' => 'USKS0637', 'name' => 'Shawnee Mission');
$city_data[] = array('accid' => 'USKS0540', 'name' => 'Silver Lake');
$city_data[] = array('accid' => 'USKS0541', 'name' => 'Simpson');
$city_data[] = array('accid' => 'USKS0542', 'name' => 'Smith Center');
$city_data[] = array('accid' => 'USKS0543', 'name' => 'Soldier');
$city_data[] = array('accid' => 'USKS0544', 'name' => 'Solomon');
$city_data[] = array('accid' => 'USKS0545', 'name' => 'South Haven');
$city_data[] = array('accid' => 'USKS0546', 'name' => 'South Hutchinson');
$city_data[] = array('accid' => 'USKS0547', 'name' => 'Spearville');
$city_data[] = array('accid' => 'USKS0548', 'name' => 'Spivey');
$city_data[] = array('accid' => 'USKS0549', 'name' => 'Spring Hill');
$city_data[] = array('accid' => 'USKS0550', 'name' => 'Stafford');
$city_data[] = array('accid' => 'USKS0551', 'name' => 'Stark');
$city_data[] = array('accid' => 'USKS0552', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USKS0553', 'name' => 'Stilwell');
$city_data[] = array('accid' => 'USKS0554', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USKS0555', 'name' => 'Strong City');
$city_data[] = array('accid' => 'USKS0556', 'name' => 'Stuttgart');
$city_data[] = array('accid' => 'USKS0557', 'name' => 'Sublette');
$city_data[] = array('accid' => 'USKS0558', 'name' => 'Summerfield');
$city_data[] = array('accid' => 'USKS0559', 'name' => 'Sun City');
$city_data[] = array('accid' => 'USKS0560', 'name' => 'Sycamore');
$city_data[] = array('accid' => 'USKS0561', 'name' => 'Sylvan Grove');
$city_data[] = array('accid' => 'USKS0562', 'name' => 'Sylvia');
$city_data[] = array('accid' => 'USKS0563', 'name' => 'Syracuse');
$city_data[] = array('accid' => 'USKS0564', 'name' => 'Talmage');
$city_data[] = array('accid' => 'USKS0565', 'name' => 'Tampa');
$city_data[] = array('accid' => 'USKS0566', 'name' => 'Tecumseh');
$city_data[] = array('accid' => 'USKS0567', 'name' => 'Tescott');
$city_data[] = array('accid' => 'USKS0568', 'name' => 'Thayer');
$city_data[] = array('accid' => 'USKS0569', 'name' => 'Tipton');
$city_data[] = array('accid' => 'USKS0570', 'name' => 'Tonganoxie');
$city_data[] = array('accid' => 'USKS0571', 'name' => 'Topeka');
$city_data[] = array('accid' => 'USKS0573', 'name' => 'Toronto');
$city_data[] = array('accid' => 'USKS0574', 'name' => 'Towanda');
$city_data[] = array('accid' => 'USKS0575', 'name' => 'Treece');
$city_data[] = array('accid' => 'USKS0576', 'name' => 'Tribune');
$city_data[] = array('accid' => 'USKS0577', 'name' => 'Troy');
$city_data[] = array('accid' => 'USKS0578', 'name' => 'Turon');
$city_data[] = array('accid' => 'USKS0579', 'name' => 'Tyro');
$city_data[] = array('accid' => 'USKS0580', 'name' => 'Udall');
$city_data[] = array('accid' => 'USKS0581', 'name' => 'Ulysses');
$city_data[] = array('accid' => 'USKS0582', 'name' => 'Uniontown');
$city_data[] = array('accid' => 'USKS0583', 'name' => 'Utica');
$city_data[] = array('accid' => 'USKS0584', 'name' => 'Valley Center');
$city_data[] = array('accid' => 'USKS0585', 'name' => 'Valley Falls');
$city_data[] = array('accid' => 'USKS0586', 'name' => 'Vassar');
$city_data[] = array('accid' => 'USKS0587', 'name' => 'Vermillion');
$city_data[] = array('accid' => 'USKS0588', 'name' => 'Victoria');
$city_data[] = array('accid' => 'USKS0589', 'name' => 'Viola');
$city_data[] = array('accid' => 'USKS0590', 'name' => 'Virgil');
$city_data[] = array('accid' => 'USKS0591', 'name' => 'Wa Keeney');
$city_data[] = array('accid' => 'USKS0592', 'name' => 'Wakarusa');
$city_data[] = array('accid' => 'USKS0593', 'name' => 'Wakefield');
$city_data[] = array('accid' => 'USKS0594', 'name' => 'Waldo');
$city_data[] = array('accid' => 'USKS0595', 'name' => 'Waldron');
$city_data[] = array('accid' => 'USKS0596', 'name' => 'Walker');
$city_data[] = array('accid' => 'USKS0597', 'name' => 'Wallace');
$city_data[] = array('accid' => 'USKS0598', 'name' => 'Walnut');
$city_data[] = array('accid' => 'USKS0599', 'name' => 'Walton');
$city_data[] = array('accid' => 'USKS0600', 'name' => 'Wamego');
$city_data[] = array('accid' => 'USKS0601', 'name' => 'Washington');
$city_data[] = array('accid' => 'USKS0602', 'name' => 'Waterville');
$city_data[] = array('accid' => 'USKS0603', 'name' => 'Wathena');
$city_data[] = array('accid' => 'USKS0604', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USKS0605', 'name' => 'Webber');
$city_data[] = array('accid' => 'USKS0606', 'name' => 'Weir');
$city_data[] = array('accid' => 'USKS0607', 'name' => 'Welda');
$city_data[] = array('accid' => 'USKS0608', 'name' => 'Wellington');
$city_data[] = array('accid' => 'USKS0609', 'name' => 'Wellsville');
$city_data[] = array('accid' => 'USKS0610', 'name' => 'Weskan');
$city_data[] = array('accid' => 'USKS0611', 'name' => 'West Mineral');
$city_data[] = array('accid' => 'USKS0612', 'name' => 'Westmoreland');
$city_data[] = array('accid' => 'USKS0613', 'name' => 'Westphalia');
$city_data[] = array('accid' => 'USKS0614', 'name' => 'Wetmore');
$city_data[] = array('accid' => 'USKS0615', 'name' => 'Wheaton');
$city_data[] = array('accid' => 'USKS0616', 'name' => 'White City');
$city_data[] = array('accid' => 'USKS0617', 'name' => 'White Cloud');
$city_data[] = array('accid' => 'USKS0618', 'name' => 'Whitewater');
$city_data[] = array('accid' => 'USKS0619', 'name' => 'Whiting');
$city_data[] = array('accid' => 'USKS0620', 'name' => 'Wichita');
$city_data[] = array('accid' => 'USKS0623', 'name' => 'Williamsburg');
$city_data[] = array('accid' => 'USKS0624', 'name' => 'Wilmore');
$city_data[] = array('accid' => 'USKS0625', 'name' => 'Wilsey');
$city_data[] = array('accid' => 'USKS0626', 'name' => 'Wilson');
$city_data[] = array('accid' => 'USKS0627', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USKS0628', 'name' => 'Windom');
$city_data[] = array('accid' => 'USKS0629', 'name' => 'Winfield');
$city_data[] = array('accid' => 'USKS0630', 'name' => 'Winona');
$city_data[] = array('accid' => 'USKS0631', 'name' => 'Woodbine');
$city_data[] = array('accid' => 'USKS0632', 'name' => 'Woodston');
$city_data[] = array('accid' => 'USKS0633', 'name' => 'Wright');
$city_data[] = array('accid' => 'USKS0634', 'name' => 'Yates Center');
$city_data[] = array('accid' => 'USKS0635', 'name' => 'Yoder');
$city_data[] = array('accid' => 'USKS0636', 'name' => 'Zenda');

?>
