<?php

// City package for USA: Kentucky 

$city_name = 'USA: Kentucky';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USKY0637', 'name' => 'Aberdeen');
$city_data[] = array('accid' => 'USKY0638', 'name' => 'Adairville');
$city_data[] = array('accid' => 'USKY0639', 'name' => 'Adams');
$city_data[] = array('accid' => 'USKY0640', 'name' => 'Adolphus');
$city_data[] = array('accid' => 'USKY0641', 'name' => 'Ages Brookside');
$city_data[] = array('accid' => 'USKY0642', 'name' => 'Albany');
$city_data[] = array('accid' => 'USKY0643', 'name' => 'Alexandria');
$city_data[] = array('accid' => 'USKY0644', 'name' => 'Allegre');
$city_data[] = array('accid' => 'USKY0645', 'name' => 'Allen');
$city_data[] = array('accid' => 'USKY0646', 'name' => 'Allensville');
$city_data[] = array('accid' => 'USKY0647', 'name' => 'Almo');
$city_data[] = array('accid' => 'USKY0648', 'name' => 'Alpha');
$city_data[] = array('accid' => 'USKY0649', 'name' => 'Alvaton');
$city_data[] = array('accid' => 'USKY0650', 'name' => 'Annville');
$city_data[] = array('accid' => 'USKY0651', 'name' => 'Argillite');
$city_data[] = array('accid' => 'USKY0652', 'name' => 'Arjay');
$city_data[] = array('accid' => 'USKY0653', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USKY0654', 'name' => 'Artemus');
$city_data[] = array('accid' => 'USKY0655', 'name' => 'Ary');
$city_data[] = array('accid' => 'USKY0656', 'name' => 'Ashcamp');
$city_data[] = array('accid' => 'USKY0657', 'name' => 'Asher');
$city_data[] = array('accid' => 'USKY0658', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USKY0659', 'name' => 'Athol');
$city_data[] = array('accid' => 'USKY0660', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USKY0661', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USKY0662', 'name' => 'Austin');
$city_data[] = array('accid' => 'USKY0663', 'name' => 'Auxier');
$city_data[] = array('accid' => 'USKY0664', 'name' => 'Avawam');
$city_data[] = array('accid' => 'USKY0665', 'name' => 'Bagdad');
$city_data[] = array('accid' => 'USKY0666', 'name' => 'Bakerton');
$city_data[] = array('accid' => 'USKY0667', 'name' => 'Bandana');
$city_data[] = array('accid' => 'USKY0668', 'name' => 'Banner');
$city_data[] = array('accid' => 'USKY0669', 'name' => 'Barbourville');
$city_data[] = array('accid' => 'USKY0670', 'name' => 'Bardstown');
$city_data[] = array('accid' => 'USKY0671', 'name' => 'Bardwell');
$city_data[] = array('accid' => 'USKY0672', 'name' => 'Barlow');
$city_data[] = array('accid' => 'USKY0673', 'name' => 'Baskett');
$city_data[] = array('accid' => 'USKY0674', 'name' => 'Battletown');
$city_data[] = array('accid' => 'USKY0675', 'name' => 'Baxter');
$city_data[] = array('accid' => 'USKY0676', 'name' => 'Bays');
$city_data[] = array('accid' => 'USKY0677', 'name' => 'Bear Branch');
$city_data[] = array('accid' => 'USKY0678', 'name' => 'Beattyville');
$city_data[] = array('accid' => 'USKY0679', 'name' => 'Beaumont');
$city_data[] = array('accid' => 'USKY0680', 'name' => 'Beauty');
$city_data[] = array('accid' => 'USKY0681', 'name' => 'Beaver');
$city_data[] = array('accid' => 'USKY0682', 'name' => 'Beaver Dam');
$city_data[] = array('accid' => 'USKY0683', 'name' => 'Bedford');
$city_data[] = array('accid' => 'USKY0684', 'name' => 'Bee Spring');
$city_data[] = array('accid' => 'USKY0685', 'name' => 'Beech Creek');
$city_data[] = array('accid' => 'USKY0686', 'name' => 'Beech Grove');
$city_data[] = array('accid' => 'USKY0687', 'name' => 'Beechmont');
$city_data[] = array('accid' => 'USKY0688', 'name' => 'Belcher');
$city_data[] = array('accid' => 'USKY0689', 'name' => 'Belfry');
$city_data[] = array('accid' => 'USKY0690', 'name' => 'Bellevue');
$city_data[] = array('accid' => 'USKY0691', 'name' => 'Belton');
$city_data[] = array('accid' => 'USKY0692', 'name' => 'Benham');
$city_data[] = array('accid' => 'USKY0693', 'name' => 'Benton');
$city_data[] = array('accid' => 'USKY0694', 'name' => 'Berea');
$city_data[] = array('accid' => 'USKY0695', 'name' => 'Berry');
$city_data[] = array('accid' => 'USKY0696', 'name' => 'Bethany');
$city_data[] = array('accid' => 'USKY0697', 'name' => 'Bethelridge');
$city_data[] = array('accid' => 'USKY0698', 'name' => 'Bethlehem');
$city_data[] = array('accid' => 'USKY0699', 'name' => 'Betsy Layne');
$city_data[] = array('accid' => 'USKY0700', 'name' => 'Beverly');
$city_data[] = array('accid' => 'USKY0701', 'name' => 'Bevinsville');
$city_data[] = array('accid' => 'USKY0702', 'name' => 'Big Clifty');
$city_data[] = array('accid' => 'USKY0703', 'name' => 'Big Creek');
$city_data[] = array('accid' => 'USKY0704', 'name' => 'Big Laurel');
$city_data[] = array('accid' => 'USKY0705', 'name' => 'Big Spring');
$city_data[] = array('accid' => 'USKY0706', 'name' => 'Bighill');
$city_data[] = array('accid' => 'USKY0707', 'name' => 'Bimble');
$city_data[] = array('accid' => 'USKY0708', 'name' => 'Blackey');
$city_data[] = array('accid' => 'USKY0709', 'name' => 'Blackford');
$city_data[] = array('accid' => 'USKY0710', 'name' => 'Blaine');
$city_data[] = array('accid' => 'USKY0711', 'name' => 'Bledsoe');
$city_data[] = array('accid' => 'USKY0712', 'name' => 'Bloomfield');
$city_data[] = array('accid' => 'USKY0713', 'name' => 'Blue River');
$city_data[] = array('accid' => 'USKY0714', 'name' => 'Boaz');
$city_data[] = array('accid' => 'USKY0715', 'name' => 'Bonnieville');
$city_data[] = array('accid' => 'USKY0716', 'name' => 'Bonnyman');
$city_data[] = array('accid' => 'USKY0717', 'name' => 'Booneville');
$city_data[] = array('accid' => 'USKY0718', 'name' => 'Boons Camp');
$city_data[] = array('accid' => 'USKY0719', 'name' => 'Boston');
$city_data[] = array('accid' => 'USKY0721', 'name' => 'Bowling Green');
$city_data[] = array('accid' => 'USKY0722', 'name' => 'Bradfordsville');
$city_data[] = array('accid' => 'USKY0723', 'name' => 'Brandenburg');
$city_data[] = array('accid' => 'USKY0724', 'name' => 'Breeding');
$city_data[] = array('accid' => 'USKY0725', 'name' => 'Bremen');
$city_data[] = array('accid' => 'USKY0726', 'name' => 'Brodhead');
$city_data[] = array('accid' => 'USKY0727', 'name' => 'Bronston');
$city_data[] = array('accid' => 'USKY0728', 'name' => 'Brooklyn');
$city_data[] = array('accid' => 'USKY0729', 'name' => 'Brooks');
$city_data[] = array('accid' => 'USKY0730', 'name' => 'Brooksville');
$city_data[] = array('accid' => 'USKY0731', 'name' => 'Browder');
$city_data[] = array('accid' => 'USKY0732', 'name' => 'Brownsville');
$city_data[] = array('accid' => 'USKY0733', 'name' => 'Bryants Store');
$city_data[] = array('accid' => 'USKY0734', 'name' => 'Bryantsville');
$city_data[] = array('accid' => 'USKY0735', 'name' => 'Buckhorn');
$city_data[] = array('accid' => 'USKY0736', 'name' => 'Buckner');
$city_data[] = array('accid' => 'USKY0737', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USKY0738', 'name' => 'Bulan');
$city_data[] = array('accid' => 'USKY0739', 'name' => 'Burdine');
$city_data[] = array('accid' => 'USKY0740', 'name' => 'Burgin');
$city_data[] = array('accid' => 'USKY0741', 'name' => 'Burkesville');
$city_data[] = array('accid' => 'USKY0742', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USKY0743', 'name' => 'Burna');
$city_data[] = array('accid' => 'USKY0744', 'name' => 'Burnside');
$city_data[] = array('accid' => 'USKY0745', 'name' => 'Bush');
$city_data[] = array('accid' => 'USKY0746', 'name' => 'Busy');
$city_data[] = array('accid' => 'USKY0747', 'name' => 'Butler');
$city_data[] = array('accid' => 'USKY0748', 'name' => 'Bypro');
$city_data[] = array('accid' => 'USKY0749', 'name' => 'Cadiz');
$city_data[] = array('accid' => 'USKY0750', 'name' => 'Calhoun');
$city_data[] = array('accid' => 'USKY0751', 'name' => 'California');
$city_data[] = array('accid' => 'USKY0752', 'name' => 'Calvert City');
$city_data[] = array('accid' => 'USKY0753', 'name' => 'Calvin');
$city_data[] = array('accid' => 'USKY0754', 'name' => 'Camp Dix');
$city_data[] = array('accid' => 'USKY0755', 'name' => 'Campbellsburg');
$city_data[] = array('accid' => 'USKY0756', 'name' => 'Campbellsville');
$city_data[] = array('accid' => 'USKY0757', 'name' => 'Campton');
$city_data[] = array('accid' => 'USKY0758', 'name' => 'Canada');
$city_data[] = array('accid' => 'USKY0759', 'name' => 'Cane Valley');
$city_data[] = array('accid' => 'USKY0760', 'name' => 'Caneyville');
$city_data[] = array('accid' => 'USKY0761', 'name' => 'Canmer');
$city_data[] = array('accid' => 'USKY0762', 'name' => 'Cannel City');
$city_data[] = array('accid' => 'USKY0763', 'name' => 'Cannon');
$city_data[] = array('accid' => 'USKY0764', 'name' => 'Carlisle');
$city_data[] = array('accid' => 'USKY0765', 'name' => 'Carrie');
$city_data[] = array('accid' => 'USKY0766', 'name' => 'Carrollton');
$city_data[] = array('accid' => 'USKY0767', 'name' => 'Carter');
$city_data[] = array('accid' => 'USKY0768', 'name' => 'Catlettsburg');
$city_data[] = array('accid' => 'USKY0769', 'name' => 'Cave City');
$city_data[] = array('accid' => 'USKY0770', 'name' => 'Cawood');
$city_data[] = array('accid' => 'USKY0771', 'name' => 'Cecilia');
$city_data[] = array('accid' => 'USKY0772', 'name' => 'Center');
$city_data[] = array('accid' => 'USKY0773', 'name' => 'Centertown');
$city_data[] = array('accid' => 'USKY0774', 'name' => 'Central City');
$city_data[] = array('accid' => 'USKY0775', 'name' => 'Cerulean');
$city_data[] = array('accid' => 'USKY0776', 'name' => 'Chaplin');
$city_data[] = array('accid' => 'USKY0777', 'name' => 'Chappell');
$city_data[] = array('accid' => 'USKY0778', 'name' => 'Chavies');
$city_data[] = array('accid' => 'USKY0779', 'name' => 'Cisco');
$city_data[] = array('accid' => 'USKY0780', 'name' => 'Clarkson');
$city_data[] = array('accid' => 'USKY0781', 'name' => 'Clay');
$city_data[] = array('accid' => 'USKY0782', 'name' => 'Clay City');
$city_data[] = array('accid' => 'USKY0783', 'name' => 'Clayhole');
$city_data[] = array('accid' => 'USKY0784', 'name' => 'Clearfield');
$city_data[] = array('accid' => 'USKY0785', 'name' => 'Cleaton');
$city_data[] = array('accid' => 'USKY0786', 'name' => 'Clermont');
$city_data[] = array('accid' => 'USKY0787', 'name' => 'Clifty');
$city_data[] = array('accid' => 'USKY0788', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USKY0789', 'name' => 'Closplint');
$city_data[] = array('accid' => 'USKY0790', 'name' => 'Cloverport');
$city_data[] = array('accid' => 'USKY0791', 'name' => 'Coalgood');
$city_data[] = array('accid' => 'USKY0792', 'name' => 'Coldiron');
$city_data[] = array('accid' => 'USKY0793', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USKY0794', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USKY0795', 'name' => 'Combs');
$city_data[] = array('accid' => 'USKY0796', 'name' => 'Confluence');
$city_data[] = array('accid' => 'USKY0797', 'name' => 'Corbin');
$city_data[] = array('accid' => 'USKY0798', 'name' => 'Corinth');
$city_data[] = array('accid' => 'USKY0799', 'name' => 'Cornettsville');
$city_data[] = array('accid' => 'USKY0800', 'name' => 'Corydon');
$city_data[] = array('accid' => 'USKY0801', 'name' => 'Covington');
$city_data[] = array('accid' => 'USKY0802', 'name' => 'Coxs Creek');
$city_data[] = array('accid' => 'USKY0803', 'name' => 'Crab Orchard');
$city_data[] = array('accid' => 'USKY0804', 'name' => 'Cranks');
$city_data[] = array('accid' => 'USKY0805', 'name' => 'Crayne');
$city_data[] = array('accid' => 'USKY0806', 'name' => 'Crestwood');
$city_data[] = array('accid' => 'USKY0807', 'name' => 'Crittenden');
$city_data[] = array('accid' => 'USKY0808', 'name' => 'Crockett');
$city_data[] = array('accid' => 'USKY0809', 'name' => 'Crofton');
$city_data[] = array('accid' => 'USKY0810', 'name' => 'Cromona');
$city_data[] = array('accid' => 'USKY0811', 'name' => 'Cromwell');
$city_data[] = array('accid' => 'USKY0812', 'name' => 'Cub Run');
$city_data[] = array('accid' => 'USKY0813', 'name' => 'Cumberland');
$city_data[] = array('accid' => 'USKY0814', 'name' => 'Cunningham');
$city_data[] = array('accid' => 'USKY0815', 'name' => 'Curdsville');
$city_data[] = array('accid' => 'USKY0816', 'name' => 'Custer');
$city_data[] = array('accid' => 'USKY0817', 'name' => 'Cynthiana');
$city_data[] = array('accid' => 'USKY0818', 'name' => 'Dabolt');
$city_data[] = array('accid' => 'USKY0819', 'name' => 'Dana');
$city_data[] = array('accid' => 'USKY0820', 'name' => 'Danville');
$city_data[] = array('accid' => 'USKY0821', 'name' => 'David');
$city_data[] = array('accid' => 'USKY0822', 'name' => 'Dawson Springs');
$city_data[] = array('accid' => 'USKY0823', 'name' => 'Dayhoit');
$city_data[] = array('accid' => 'USKY0824', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USKY0825', 'name' => 'De Mossville');
$city_data[] = array('accid' => 'USKY0826', 'name' => 'Deane');
$city_data[] = array('accid' => 'USKY0827', 'name' => 'Debord');
$city_data[] = array('accid' => 'USKY0828', 'name' => 'Delphia');
$city_data[] = array('accid' => 'USKY0829', 'name' => 'Dema');
$city_data[] = array('accid' => 'USKY0830', 'name' => 'Denniston');
$city_data[] = array('accid' => 'USKY0831', 'name' => 'Denton');
$city_data[] = array('accid' => 'USKY0832', 'name' => 'Denver');
$city_data[] = array('accid' => 'USKY0833', 'name' => 'Dewitt');
$city_data[] = array('accid' => 'USKY0834', 'name' => 'Dexter');
$city_data[] = array('accid' => 'USKY0835', 'name' => 'Dice');
$city_data[] = array('accid' => 'USKY0836', 'name' => 'Dixon');
$city_data[] = array('accid' => 'USKY0837', 'name' => 'Dorton');
$city_data[] = array('accid' => 'USKY0838', 'name' => 'Dover');
$city_data[] = array('accid' => 'USKY0839', 'name' => 'Drake');
$city_data[] = array('accid' => 'USKY0840', 'name' => 'Drakesboro');
$city_data[] = array('accid' => 'USKY0841', 'name' => 'Drift');
$city_data[] = array('accid' => 'USKY0842', 'name' => 'Dry Ridge');
$city_data[] = array('accid' => 'USKY0843', 'name' => 'Dubre');
$city_data[] = array('accid' => 'USKY0844', 'name' => 'Dunbar');
$city_data[] = array('accid' => 'USKY0845', 'name' => 'Dundee');
$city_data[] = array('accid' => 'USKY0846', 'name' => 'Dunmor');
$city_data[] = array('accid' => 'USKY0847', 'name' => 'Dunnville');
$city_data[] = array('accid' => 'USKY0848', 'name' => 'Dwale');
$city_data[] = array('accid' => 'USKY0849', 'name' => 'Dwarf');
$city_data[] = array('accid' => 'USKY0850', 'name' => 'Dycusburg');
$city_data[] = array('accid' => 'USKY0851', 'name' => 'Earlington');
$city_data[] = array('accid' => 'USKY0852', 'name' => 'East Bernstadt');
$city_data[] = array('accid' => 'USKY0853', 'name' => 'East Point');
$city_data[] = array('accid' => 'USKY0854', 'name' => 'Eastern');
$city_data[] = array('accid' => 'USKY0855', 'name' => 'Eastview');
$city_data[] = array('accid' => 'USKY0856', 'name' => 'Eastwood');
$city_data[] = array('accid' => 'USKY0857', 'name' => 'Eddyville');
$city_data[] = array('accid' => 'USKY0858', 'name' => 'Edmonton');
$city_data[] = array('accid' => 'USKY0859', 'name' => 'Edna');
$city_data[] = array('accid' => 'USKY0860', 'name' => 'Eighty Eight');
$city_data[] = array('accid' => 'USKY0861', 'name' => 'Ekron');
$city_data[] = array('accid' => 'USKY0862', 'name' => 'Elizabethtown');
$city_data[] = array('accid' => 'USKY0863', 'name' => 'Elizaville');
$city_data[] = array('accid' => 'USKY0864', 'name' => 'Elk Horn');
$city_data[] = array('accid' => 'USKY0865', 'name' => 'Elkfork');
$city_data[] = array('accid' => 'USKY0866', 'name' => 'Elkhorn City');
$city_data[] = array('accid' => 'USKY0867', 'name' => 'Elkton');
$city_data[] = array('accid' => 'USKY0868', 'name' => 'Elliottville');
$city_data[] = array('accid' => 'USKY0869', 'name' => 'Elsie');
$city_data[] = array('accid' => 'USKY0870', 'name' => 'Emerson');
$city_data[] = array('accid' => 'USKY0871', 'name' => 'Eminence');
$city_data[] = array('accid' => 'USKY0872', 'name' => 'Emlyn');
$city_data[] = array('accid' => 'USKY0873', 'name' => 'Emmalena');
$city_data[] = array('accid' => 'USKY0874', 'name' => 'Eolia');
$city_data[] = array('accid' => 'USKY0875', 'name' => 'Eriline');
$city_data[] = array('accid' => 'USKY0876', 'name' => 'Erlanger');
$city_data[] = array('accid' => 'USKY0877', 'name' => 'Ermine');
$city_data[] = array('accid' => 'USKY0878', 'name' => 'Essie');
$city_data[] = array('accid' => 'USKY0879', 'name' => 'Etoile');
$city_data[] = array('accid' => 'USKY0880', 'name' => 'Eubank');
$city_data[] = array('accid' => 'USKY0881', 'name' => 'Evarts');
$city_data[] = array('accid' => 'USKY0882', 'name' => 'Ewing');
$city_data[] = array('accid' => 'USKY0883', 'name' => 'Ezel');
$city_data[] = array('accid' => 'USKY0884', 'name' => 'Fairdale');
$city_data[] = array('accid' => 'USKY0885', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USKY0886', 'name' => 'Fairplay');
$city_data[] = array('accid' => 'USKY0888', 'name' => 'Falcon');
$city_data[] = array('accid' => 'USKY0889', 'name' => 'Fall Rock');
$city_data[] = array('accid' => 'USKY0890', 'name' => 'Falls Of Rough');
$city_data[] = array('accid' => 'USKY0891', 'name' => 'Falmouth');
$city_data[] = array('accid' => 'USKY0892', 'name' => 'Fancy Farm');
$city_data[] = array('accid' => 'USKY0893', 'name' => 'Farmers');
$city_data[] = array('accid' => 'USKY0894', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USKY0895', 'name' => 'Fedscreek');
$city_data[] = array('accid' => 'USKY0896', 'name' => 'Ferguson');
$city_data[] = array('accid' => 'USKY0897', 'name' => 'Finchville');
$city_data[] = array('accid' => 'USKY0898', 'name' => 'Firebrick');
$city_data[] = array('accid' => 'USKY0899', 'name' => 'Fisherville');
$city_data[] = array('accid' => 'USKY0900', 'name' => 'Fisty');
$city_data[] = array('accid' => 'USKY0902', 'name' => 'Flat Lick');
$city_data[] = array('accid' => 'USKY0903', 'name' => 'Flatgap');
$city_data[] = array('accid' => 'USKY0904', 'name' => 'Flatwoods');
$city_data[] = array('accid' => 'USKY0905', 'name' => 'Flemingsburg');
$city_data[] = array('accid' => 'USKY0906', 'name' => 'Florence');
$city_data[] = array('accid' => 'USKY0907', 'name' => 'Ford');
$city_data[] = array('accid' => 'USKY0908', 'name' => 'Fords Branch');
$city_data[] = array('accid' => 'USKY0909', 'name' => 'Fordsville');
$city_data[] = array('accid' => 'USKY0910', 'name' => 'Forest Hills');
$city_data[] = array('accid' => 'USKY0911', 'name' => 'Fort Campbell');
$city_data[] = array('accid' => 'USKY0912', 'name' => 'Fort Knox');
$city_data[] = array('accid' => 'USKY0913', 'name' => 'Fort Mitchell');
$city_data[] = array('accid' => 'USKY0914', 'name' => 'Fort Thomas');
$city_data[] = array('accid' => 'USKY0915', 'name' => 'Foster');
$city_data[] = array('accid' => 'USKY0916', 'name' => 'Fountain Run');
$city_data[] = array('accid' => 'USKY0917', 'name' => 'Fourmile');
$city_data[] = array('accid' => 'USKY0918', 'name' => 'Frakes');
$city_data[] = array('accid' => 'USKY0919', 'name' => 'Frankfort');
$city_data[] = array('accid' => 'USKY0920', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USKY0921', 'name' => 'Fredonia');
$city_data[] = array('accid' => 'USKY0922', 'name' => 'Freeburn');
$city_data[] = array('accid' => 'USKY0923', 'name' => 'Frenchburg');
$city_data[] = array('accid' => 'USKY0924', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USKY0925', 'name' => 'Gamaliel');
$city_data[] = array('accid' => 'USKY0926', 'name' => 'Gapville');
$city_data[] = array('accid' => 'USKY0927', 'name' => 'Garfield');
$city_data[] = array('accid' => 'USKY0928', 'name' => 'Garner');
$city_data[] = array('accid' => 'USKY0929', 'name' => 'Garrard');
$city_data[] = array('accid' => 'USKY0930', 'name' => 'Garrett');
$city_data[] = array('accid' => 'USKY0931', 'name' => 'Garrison');
$city_data[] = array('accid' => 'USKY0932', 'name' => 'Gays Creek');
$city_data[] = array('accid' => 'USKY0933', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USKY0934', 'name' => 'Germantown');
$city_data[] = array('accid' => 'USKY0935', 'name' => 'Ghent');
$city_data[] = array('accid' => 'USKY0936', 'name' => 'Gilbertsville');
$city_data[] = array('accid' => 'USKY0937', 'name' => 'Girdler');
$city_data[] = array('accid' => 'USKY0938', 'name' => 'Glasgow');
$city_data[] = array('accid' => 'USKY0939', 'name' => 'Glencoe');
$city_data[] = array('accid' => 'USKY0940', 'name' => 'Glendale');
$city_data[] = array('accid' => 'USKY0941', 'name' => 'Glens Fork');
$city_data[] = array('accid' => 'USKY0942', 'name' => 'Glenview');
$city_data[] = array('accid' => 'USKY0943', 'name' => 'Goose Rock');
$city_data[] = array('accid' => 'USKY0944', 'name' => 'Gordon');
$city_data[] = array('accid' => 'USKY0945', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USKY0946', 'name' => 'Gracey');
$city_data[] = array('accid' => 'USKY0947', 'name' => 'Gradyville');
$city_data[] = array('accid' => 'USKY0948', 'name' => 'Graham');
$city_data[] = array('accid' => 'USKY0949', 'name' => 'Grahn');
$city_data[] = array('accid' => 'USKY0950', 'name' => 'Grand Rivers');
$city_data[] = array('accid' => 'USKY0951', 'name' => 'Gravel Switch');
$city_data[] = array('accid' => 'USKY0952', 'name' => 'Gray');
$city_data[] = array('accid' => 'USKY0953', 'name' => 'Gray Hawk');
$city_data[] = array('accid' => 'USKY0954', 'name' => 'Grays Knob');
$city_data[] = array('accid' => 'USKY0955', 'name' => 'Grayson');
$city_data[] = array('accid' => 'USKY0956', 'name' => 'Green Road');
$city_data[] = array('accid' => 'USKY0957', 'name' => 'Greensburg');
$city_data[] = array('accid' => 'USKY0958', 'name' => 'Greenup');
$city_data[] = array('accid' => 'USKY0959', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USKY0960', 'name' => 'Grethel');
$city_data[] = array('accid' => 'USKY0961', 'name' => 'Gulston');
$city_data[] = array('accid' => 'USKY0962', 'name' => 'Gunlock');
$city_data[] = array('accid' => 'USKY0963', 'name' => 'Guston');
$city_data[] = array('accid' => 'USKY0964', 'name' => 'Guthrie');
$city_data[] = array('accid' => 'USKY0965', 'name' => 'Hadley');
$city_data[] = array('accid' => 'USKY0966', 'name' => 'Hagerhill');
$city_data[] = array('accid' => 'USKY0967', 'name' => 'Haldeman');
$city_data[] = array('accid' => 'USKY0968', 'name' => 'Halfway');
$city_data[] = array('accid' => 'USKY0969', 'name' => 'Hallie');
$city_data[] = array('accid' => 'USKY0970', 'name' => 'Hamlin');
$city_data[] = array('accid' => 'USKY0971', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USKY0972', 'name' => 'Hanson');
$city_data[] = array('accid' => 'USKY0973', 'name' => 'Happy');
$city_data[] = array('accid' => 'USKY0974', 'name' => 'Hardburly');
$city_data[] = array('accid' => 'USKY0975', 'name' => 'Hardin');
$city_data[] = array('accid' => 'USKY0976', 'name' => 'Hardinsburg');
$city_data[] = array('accid' => 'USKY0977', 'name' => 'Hardy');
$city_data[] = array('accid' => 'USKY0978', 'name' => 'Hardyville');
$city_data[] = array('accid' => 'USKY0979', 'name' => 'Harlan');
$city_data[] = array('accid' => 'USKY0980', 'name' => 'Harned');
$city_data[] = array('accid' => 'USKY0981', 'name' => 'Harold');
$city_data[] = array('accid' => 'USKY0982', 'name' => 'Harrods Creek');
$city_data[] = array('accid' => 'USKY0983', 'name' => 'Harrodsburg');
$city_data[] = array('accid' => 'USKY0984', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USKY0985', 'name' => 'Hawesville');
$city_data[] = array('accid' => 'USKY0986', 'name' => 'Hazard');
$city_data[] = array('accid' => 'USKY0987', 'name' => 'Hazel');
$city_data[] = array('accid' => 'USKY0988', 'name' => 'Hazel Green');
$city_data[] = array('accid' => 'USKY0989', 'name' => 'Hebron');
$city_data[] = array('accid' => 'USKY0990', 'name' => 'Heidelberg');
$city_data[] = array('accid' => 'USKY0991', 'name' => 'Heidrick');
$city_data[] = array('accid' => 'USKY0992', 'name' => 'Hellier');
$city_data[] = array('accid' => 'USKY0993', 'name' => 'Helton');
$city_data[] = array('accid' => 'USKY0994', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USKY0995', 'name' => 'Herndon');
$city_data[] = array('accid' => 'USKY0996', 'name' => 'Hestand');
$city_data[] = array('accid' => 'USKY0997', 'name' => 'Hi Hat');
$city_data[] = array('accid' => 'USKY0998', 'name' => 'Hickman');
$city_data[] = array('accid' => 'USKY0999', 'name' => 'Hickory');
$city_data[] = array('accid' => 'USKY1000', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USKY0490', 'name' => 'Hillview');
$city_data[] = array('accid' => 'USKY1001', 'name' => 'Hima');
$city_data[] = array('accid' => 'USKY1002', 'name' => 'Hindman');
$city_data[] = array('accid' => 'USKY1003', 'name' => 'Hinkle');
$city_data[] = array('accid' => 'USKY1004', 'name' => 'Hiseville');
$city_data[] = array('accid' => 'USKY1005', 'name' => 'Hitchins');
$city_data[] = array('accid' => 'USKY1006', 'name' => 'Hodgenville');
$city_data[] = array('accid' => 'USKY1007', 'name' => 'Holland');
$city_data[] = array('accid' => 'USKY1008', 'name' => 'Holmes Mill');
$city_data[] = array('accid' => 'USKY1009', 'name' => 'Hope');
$city_data[] = array('accid' => 'USKY1010', 'name' => 'Hopkinsville');
$city_data[] = array('accid' => 'USKY1011', 'name' => 'Horse Branch');
$city_data[] = array('accid' => 'USKY1012', 'name' => 'Horse Cave');
$city_data[] = array('accid' => 'USKY1013', 'name' => 'Hoskinston');
$city_data[] = array('accid' => 'USKY1014', 'name' => 'Huddy');
$city_data[] = array('accid' => 'USKY1015', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USKY1016', 'name' => 'Hueysville');
$city_data[] = array('accid' => 'USKY1017', 'name' => 'Hulen');
$city_data[] = array('accid' => 'USKY1018', 'name' => 'Huntsville');
$city_data[] = array('accid' => 'USKY1019', 'name' => 'Hustonville');
$city_data[] = array('accid' => 'USKY1020', 'name' => 'Hyden');
$city_data[] = array('accid' => 'USKY1021', 'name' => 'Independence');
$city_data[] = array('accid' => 'USKY1022', 'name' => 'Inez');
$city_data[] = array('accid' => 'USKY1023', 'name' => 'Ingram');
$city_data[] = array('accid' => 'USKY1024', 'name' => 'Irvine');
$city_data[] = array('accid' => 'USKY1025', 'name' => 'Irvington');
$city_data[] = array('accid' => 'USKY1026', 'name' => 'Island');
$city_data[] = array('accid' => 'USKY1027', 'name' => 'Island City');
$city_data[] = array('accid' => 'USKY1028', 'name' => 'Isom');
$city_data[] = array('accid' => 'USKY1029', 'name' => 'Isonville');
$city_data[] = array('accid' => 'USKY1030', 'name' => 'Ivel');
$city_data[] = array('accid' => 'USKY1031', 'name' => 'Ivyton');
$city_data[] = array('accid' => 'USKY1032', 'name' => 'Jackhorn');
$city_data[] = array('accid' => 'USKY1033', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USKY1034', 'name' => 'Jacobs');
$city_data[] = array('accid' => 'USKY1035', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USKY1036', 'name' => 'Jeff');
$city_data[] = array('accid' => 'USKY1037', 'name' => 'Jeffersonville');
$city_data[] = array('accid' => 'USKY1038', 'name' => 'Jenkins');
$city_data[] = array('accid' => 'USKY1039', 'name' => 'Jeremiah');
$city_data[] = array('accid' => 'USKY1040', 'name' => 'Jetson');
$city_data[] = array('accid' => 'USKY1041', 'name' => 'Jonancy');
$city_data[] = array('accid' => 'USKY1042', 'name' => 'Jonesville');
$city_data[] = array('accid' => 'USKY1043', 'name' => 'Junction City');
$city_data[] = array('accid' => 'USKY1044', 'name' => 'Keaton');
$city_data[] = array('accid' => 'USKY1045', 'name' => 'Keavy');
$city_data[] = array('accid' => 'USKY1046', 'name' => 'Keene');
$city_data[] = array('accid' => 'USKY1047', 'name' => 'Kenton');
$city_data[] = array('accid' => 'USKY1048', 'name' => 'Kenvir');
$city_data[] = array('accid' => 'USKY1049', 'name' => 'Kettle Island');
$city_data[] = array('accid' => 'USKY1050', 'name' => 'Kevil');
$city_data[] = array('accid' => 'USKY1051', 'name' => 'Kimper');
$city_data[] = array('accid' => 'USKY1052', 'name' => 'Kings Mountain');
$city_data[] = array('accid' => 'USKY1053', 'name' => 'Kirksey');
$city_data[] = array('accid' => 'USKY1054', 'name' => 'Kite');
$city_data[] = array('accid' => 'USKY1055', 'name' => 'Knifley');
$city_data[] = array('accid' => 'USKY1056', 'name' => 'Knob Lick');
$city_data[] = array('accid' => 'USKY1057', 'name' => 'Krypton');
$city_data[] = array('accid' => 'USKY1058', 'name' => 'Kuttawa');
$city_data[] = array('accid' => 'USKY1059', 'name' => 'La Center');
$city_data[] = array('accid' => 'USKY1060', 'name' => 'La Fayette');
$city_data[] = array('accid' => 'USKY1061', 'name' => 'La Grange');
$city_data[] = array('accid' => 'USKY1062', 'name' => 'Lackey');
$city_data[] = array('accid' => 'USKY1063', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USKY1064', 'name' => 'Langley');
$city_data[] = array('accid' => 'USKY1065', 'name' => 'Latonia');
$city_data[] = array('accid' => 'USKY1066', 'name' => 'Lawrenceburg');
$city_data[] = array('accid' => 'USKY1067', 'name' => 'Leander');
$city_data[] = array('accid' => 'USKY1068', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USKY1069', 'name' => 'Lebanon Junction');
$city_data[] = array('accid' => 'USKY1070', 'name' => 'Leburn');
$city_data[] = array('accid' => 'USKY1071', 'name' => 'Ledbetter');
$city_data[] = array('accid' => 'USKY1072', 'name' => 'Lee City');
$city_data[] = array('accid' => 'USKY1073', 'name' => 'Leitchfield');
$city_data[] = array('accid' => 'USKY1074', 'name' => 'Lejunior');
$city_data[] = array('accid' => 'USKY1075', 'name' => 'Lerose');
$city_data[] = array('accid' => 'USKY1076', 'name' => 'Letcher');
$city_data[] = array('accid' => 'USKY1077', 'name' => 'Lewisburg');
$city_data[] = array('accid' => 'USKY1078', 'name' => 'Lewisport');
$city_data[] = array('accid' => 'USKY1079', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USKY1080', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USKY1081', 'name' => 'Lick Creek');
$city_data[] = array('accid' => 'USKY1082', 'name' => 'Lily');
$city_data[] = array('accid' => 'USKY1083', 'name' => 'Lindseyville');
$city_data[] = array('accid' => 'USKY1084', 'name' => 'Linefork');
$city_data[] = array('accid' => 'USKY1085', 'name' => 'Littcarr');
$city_data[] = array('accid' => 'USKY1086', 'name' => 'Livermore');
$city_data[] = array('accid' => 'USKY1087', 'name' => 'Livingston');
$city_data[] = array('accid' => 'USKY1088', 'name' => 'Lloyd');
$city_data[] = array('accid' => 'USKY1089', 'name' => 'Lockport');
$city_data[] = array('accid' => 'USKY1090', 'name' => 'London');
$city_data[] = array('accid' => 'USKY1091', 'name' => 'Lone');
$city_data[] = array('accid' => 'USKY1092', 'name' => 'Lookout');
$city_data[] = array('accid' => 'USKY1093', 'name' => 'Loretto');
$city_data[] = array('accid' => 'USKY1094', 'name' => 'Lost Creek');
$city_data[] = array('accid' => 'USKY1095', 'name' => 'Louisa');
$city_data[] = array('accid' => 'USKY1096', 'name' => 'Louisville');
$city_data[] = array('accid' => 'USKY1098', 'name' => 'Lovelaceville');
$city_data[] = array('accid' => 'USKY1099', 'name' => 'Lovely');
$city_data[] = array('accid' => 'USKY1100', 'name' => 'Lowes');
$city_data[] = array('accid' => 'USKY1101', 'name' => 'Lowmansville');
$city_data[] = array('accid' => 'USKY1102', 'name' => 'Loyall');
$city_data[] = array('accid' => 'USKY1103', 'name' => 'Lucas');
$city_data[] = array('accid' => 'USKY1104', 'name' => 'Lynch');
$city_data[] = array('accid' => 'USKY1105', 'name' => 'Lynnville');
$city_data[] = array('accid' => 'USKY1106', 'name' => 'Maceo');
$city_data[] = array('accid' => 'USKY1107', 'name' => 'Mackville');
$city_data[] = array('accid' => 'USKY1108', 'name' => 'Madisonville');
$city_data[] = array('accid' => 'USKY1109', 'name' => 'Magnolia');
$city_data[] = array('accid' => 'USKY1110', 'name' => 'Majestic');
$city_data[] = array('accid' => 'USKY1111', 'name' => 'Mallie');
$city_data[] = array('accid' => 'USKY1112', 'name' => 'Malone');
$city_data[] = array('accid' => 'USKY1113', 'name' => 'Mammoth Cave');
$city_data[] = array('accid' => 'USKY1114', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USKY1115', 'name' => 'Manitou');
$city_data[] = array('accid' => 'USKY1116', 'name' => 'Mannsville');
$city_data[] = array('accid' => 'USKY1117', 'name' => 'Maple Mount');
$city_data[] = array('accid' => 'USKY1118', 'name' => 'Marion');
$city_data[] = array('accid' => 'USKY1119', 'name' => 'Marrowbone');
$city_data[] = array('accid' => 'USKY1121', 'name' => 'Marshes Siding');
$city_data[] = array('accid' => 'USKY1122', 'name' => 'Martha');
$city_data[] = array('accid' => 'USKY1123', 'name' => 'Martin');
$city_data[] = array('accid' => 'USKY1124', 'name' => 'Mary Alice');
$city_data[] = array('accid' => 'USKY1125', 'name' => 'Marydell');
$city_data[] = array('accid' => 'USKY1126', 'name' => 'Mason');
$city_data[] = array('accid' => 'USKY1127', 'name' => 'Masonic Home');
$city_data[] = array('accid' => 'USKY1128', 'name' => 'Mayfield');
$city_data[] = array('accid' => 'USKY1129', 'name' => 'Mayking');
$city_data[] = array('accid' => 'USKY1130', 'name' => 'Mayslick');
$city_data[] = array('accid' => 'USKY1131', 'name' => 'Maysville');
$city_data[] = array('accid' => 'USKY1132', 'name' => 'Mazie');
$city_data[] = array('accid' => 'USKY1133', 'name' => 'McAndrews');
$city_data[] = array('accid' => 'USKY1134', 'name' => 'McCarr');
$city_data[] = array('accid' => 'USKY1135', 'name' => 'McDaniels');
$city_data[] = array('accid' => 'USKY1136', 'name' => 'McDowell');
$city_data[] = array('accid' => 'USKY1137', 'name' => 'McHenry');
$city_data[] = array('accid' => 'USKY1138', 'name' => 'McKee');
$city_data[] = array('accid' => 'USKY1139', 'name' => 'McKinney');
$city_data[] = array('accid' => 'USKY1140', 'name' => 'McQuady');
$city_data[] = array('accid' => 'USKY1141', 'name' => 'McRoberts');
$city_data[] = array('accid' => 'USKY1142', 'name' => 'McVeigh');
$city_data[] = array('accid' => 'USKY1143', 'name' => 'Meally');
$city_data[] = array('accid' => 'USKY1144', 'name' => 'Means');
$city_data[] = array('accid' => 'USKY1145', 'name' => 'Melber');
$city_data[] = array('accid' => 'USKY1146', 'name' => 'Melbourne');
$city_data[] = array('accid' => 'USKY1147', 'name' => 'Melvin');
$city_data[] = array('accid' => 'USKY1148', 'name' => 'Middleburg');
$city_data[] = array('accid' => 'USKY1149', 'name' => 'Middlesboro');
$city_data[] = array('accid' => 'USKY1150', 'name' => 'Midway');
$city_data[] = array('accid' => 'USKY1151', 'name' => 'Milburn');
$city_data[] = array('accid' => 'USKY1152', 'name' => 'Milford');
$city_data[] = array('accid' => 'USKY1153', 'name' => 'Mill Springs');
$city_data[] = array('accid' => 'USKY1154', 'name' => 'Millersburg');
$city_data[] = array('accid' => 'USKY1155', 'name' => 'Millstone');
$city_data[] = array('accid' => 'USKY1156', 'name' => 'Milltown');
$city_data[] = array('accid' => 'USKY1157', 'name' => 'Millwood');
$city_data[] = array('accid' => 'USKY1158', 'name' => 'Milton');
$city_data[] = array('accid' => 'USKY1159', 'name' => 'Minerva');
$city_data[] = array('accid' => 'USKY1160', 'name' => 'Minnie');
$city_data[] = array('accid' => 'USKY1161', 'name' => 'Miracle');
$city_data[] = array('accid' => 'USKY1162', 'name' => 'Mistletoe');
$city_data[] = array('accid' => 'USKY1163', 'name' => 'Mitchellsburg');
$city_data[] = array('accid' => 'USKY1164', 'name' => 'Mize');
$city_data[] = array('accid' => 'USKY1165', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USKY1166', 'name' => 'Moorefield');
$city_data[] = array('accid' => 'USKY1167', 'name' => 'Morehead');
$city_data[] = array('accid' => 'USKY1168', 'name' => 'Morganfield');
$city_data[] = array('accid' => 'USKY1169', 'name' => 'Morgantown');
$city_data[] = array('accid' => 'USKY1170', 'name' => 'Morning View');
$city_data[] = array('accid' => 'USKY1171', 'name' => 'Mortons Gap');
$city_data[] = array('accid' => 'USKY1172', 'name' => 'Mount Eden');
$city_data[] = array('accid' => 'USKY1173', 'name' => 'Mount Hermon');
$city_data[] = array('accid' => 'USKY1174', 'name' => 'Mount Olivet');
$city_data[] = array('accid' => 'USKY1175', 'name' => 'Mount Sherman');
$city_data[] = array('accid' => 'USKY1176', 'name' => 'Mount Sterling');
$city_data[] = array('accid' => 'USKY1177', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USKY1178', 'name' => 'Mount Washington');
$city_data[] = array('accid' => 'USKY1179', 'name' => 'Mousie');
$city_data[] = array('accid' => 'USKY1180', 'name' => 'Mouthcard');
$city_data[] = array('accid' => 'USKY1181', 'name' => 'Mozelle');
$city_data[] = array('accid' => 'USKY1182', 'name' => 'Muldraugh');
$city_data[] = array('accid' => 'USKY1183', 'name' => 'Munfordville');
$city_data[] = array('accid' => 'USKY1184', 'name' => 'Murray');
$city_data[] = array('accid' => 'USKY1185', 'name' => 'Muses Mills');
$city_data[] = array('accid' => 'USKY1186', 'name' => 'Myra');
$city_data[] = array('accid' => 'USKY1187', 'name' => 'Nancy');
$city_data[] = array('accid' => 'USKY1188', 'name' => 'Nazareth');
$city_data[] = array('accid' => 'USKY1189', 'name' => 'Nebo');
$city_data[] = array('accid' => 'USKY1190', 'name' => 'Neon');
$city_data[] = array('accid' => 'USKY1191', 'name' => 'Nerinx');
$city_data[] = array('accid' => 'USKY1192', 'name' => 'Nevisdale');
$city_data[] = array('accid' => 'USKY1193', 'name' => 'New Castle');
$city_data[] = array('accid' => 'USKY1194', 'name' => 'New Concord');
$city_data[] = array('accid' => 'USKY1195', 'name' => 'New Haven');
$city_data[] = array('accid' => 'USKY1196', 'name' => 'New Hope');
$city_data[] = array('accid' => 'USKY1197', 'name' => 'New Liberty');
$city_data[] = array('accid' => 'USKY1198', 'name' => 'Newport');
$city_data[] = array('accid' => 'USKY1199', 'name' => 'Nicholasville');
$city_data[] = array('accid' => 'USKY1200', 'name' => 'North Middletown');
$city_data[] = array('accid' => 'USKY1201', 'name' => 'Nortonville');
$city_data[] = array('accid' => 'USKY1202', 'name' => 'Oak Grove');
$city_data[] = array('accid' => 'USKY1203', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USKY1204', 'name' => 'Oil Springs');
$city_data[] = array('accid' => 'USKY1205', 'name' => 'Olaton');
$city_data[] = array('accid' => 'USKY1206', 'name' => 'Olive Hill');
$city_data[] = array('accid' => 'USKY1207', 'name' => 'Olmstead');
$city_data[] = array('accid' => 'USKY1208', 'name' => 'Olympia');
$city_data[] = array('accid' => 'USKY1209', 'name' => 'Oneida');
$city_data[] = array('accid' => 'USKY1210', 'name' => 'Ophir');
$city_data[] = array('accid' => 'USKY1211', 'name' => 'Orlando');
$city_data[] = array('accid' => 'USKY1212', 'name' => 'Owensboro');
$city_data[] = array('accid' => 'USKY1213', 'name' => 'Owenton');
$city_data[] = array('accid' => 'USKY1214', 'name' => 'Owingsville');
$city_data[] = array('accid' => 'USKY1215', 'name' => 'Paducah');
$city_data[] = array('accid' => 'USKY1216', 'name' => 'Paint Lick');
$city_data[] = array('accid' => 'USKY1217', 'name' => 'Paintsville');
$city_data[] = array('accid' => 'USKY1218', 'name' => 'Paris');
$city_data[] = array('accid' => 'USKY1219', 'name' => 'Park City');
$city_data[] = array('accid' => 'USKY1220', 'name' => 'Parkers Lake');
$city_data[] = array('accid' => 'USKY1221', 'name' => 'Parksville');
$city_data[] = array('accid' => 'USKY1222', 'name' => 'Partridge');
$city_data[] = array('accid' => 'USKY1223', 'name' => 'Pathfork');
$city_data[] = array('accid' => 'USKY1224', 'name' => 'Payneville');
$city_data[] = array('accid' => 'USKY1225', 'name' => 'Pellville');
$city_data[] = array('accid' => 'USKY1226', 'name' => 'Pembroke');
$city_data[] = array('accid' => 'USKY1227', 'name' => 'Pendleton');
$city_data[] = array('accid' => 'USKY1228', 'name' => 'Penrod');
$city_data[] = array('accid' => 'USKY1229', 'name' => 'Peoples');
$city_data[] = array('accid' => 'USKY1230', 'name' => 'Perry Park');
$city_data[] = array('accid' => 'USKY1231', 'name' => 'Perryville');
$city_data[] = array('accid' => 'USKY1232', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USKY1233', 'name' => 'Pewee Valley');
$city_data[] = array('accid' => 'USKY1234', 'name' => 'Phelps');
$city_data[] = array('accid' => 'USKY1235', 'name' => 'Philpot');
$city_data[] = array('accid' => 'USKY1236', 'name' => 'Phyllis');
$city_data[] = array('accid' => 'USKY1237', 'name' => 'Pikeville');
$city_data[] = array('accid' => 'USKY1238', 'name' => 'Pilgrim');
$city_data[] = array('accid' => 'USKY1239', 'name' => 'Pine Knot');
$city_data[] = array('accid' => 'USKY1240', 'name' => 'Pine Ridge');
$city_data[] = array('accid' => 'USKY1241', 'name' => 'Pine Top');
$city_data[] = array('accid' => 'USKY1242', 'name' => 'Pineville');
$city_data[] = array('accid' => 'USKY1243', 'name' => 'Pinsonfork');
$city_data[] = array('accid' => 'USKY1244', 'name' => 'Pippa Passes');
$city_data[] = array('accid' => 'USKY1245', 'name' => 'Pittsburg');
$city_data[] = array('accid' => 'USKY1246', 'name' => 'Pleasureville');
$city_data[] = array('accid' => 'USKY1247', 'name' => 'Plummers Landing');
$city_data[] = array('accid' => 'USKY1248', 'name' => 'Poole');
$city_data[] = array('accid' => 'USKY1249', 'name' => 'Port Royal');
$city_data[] = array('accid' => 'USKY1250', 'name' => 'Powderly');
$city_data[] = array('accid' => 'USKY1251', 'name' => 'Premium');
$city_data[] = array('accid' => 'USKY1252', 'name' => 'Preston');
$city_data[] = array('accid' => 'USKY1253', 'name' => 'Prestonsburg');
$city_data[] = array('accid' => 'USKY1254', 'name' => 'Primrose');
$city_data[] = array('accid' => 'USKY1255', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USKY1256', 'name' => 'Printer');
$city_data[] = array('accid' => 'USKY1257', 'name' => 'Prospect');
$city_data[] = array('accid' => 'USKY1258', 'name' => 'Providence');
$city_data[] = array('accid' => 'USKY1259', 'name' => 'Provo');
$city_data[] = array('accid' => 'USKY1260', 'name' => 'Putney');
$city_data[] = array('accid' => 'USKY1261', 'name' => 'Quincy');
$city_data[] = array('accid' => 'USKY1262', 'name' => 'Raccoon');
$city_data[] = array('accid' => 'USKY1263', 'name' => 'Radcliff');
$city_data[] = array('accid' => 'USKY1264', 'name' => 'Ransom');
$city_data[] = array('accid' => 'USKY1265', 'name' => 'Raven');
$city_data[] = array('accid' => 'USKY1266', 'name' => 'Ravenna');
$city_data[] = array('accid' => 'USKY1267', 'name' => 'Raywick');
$city_data[] = array('accid' => 'USKY1268', 'name' => 'Redfox');
$city_data[] = array('accid' => 'USKY1269', 'name' => 'Reed');
$city_data[] = array('accid' => 'USKY1270', 'name' => 'Regina');
$city_data[] = array('accid' => 'USKY1271', 'name' => 'Renfro Valley');
$city_data[] = array('accid' => 'USKY1272', 'name' => 'Revelo');
$city_data[] = array('accid' => 'USKY1273', 'name' => 'Reynolds Station');
$city_data[] = array('accid' => 'USKY1274', 'name' => 'Rhodelia');
$city_data[] = array('accid' => 'USKY1275', 'name' => 'Ricetown');
$city_data[] = array('accid' => 'USKY1276', 'name' => 'Richardsville');
$city_data[] = array('accid' => 'USKY1277', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USKY1278', 'name' => 'Rineyville');
$city_data[] = array('accid' => 'USKY1279', 'name' => 'River');
$city_data[] = array('accid' => 'USKY1280', 'name' => 'Roark');
$city_data[] = array('accid' => 'USKY1281', 'name' => 'Robards');
$city_data[] = array('accid' => 'USKY1282', 'name' => 'Robinson Creek');
$city_data[] = array('accid' => 'USKY1283', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USKY1284', 'name' => 'Rockfield');
$city_data[] = array('accid' => 'USKY1285', 'name' => 'Rockholds');
$city_data[] = array('accid' => 'USKY1286', 'name' => 'Rockhouse');
$city_data[] = array('accid' => 'USKY1287', 'name' => 'Rockport');
$city_data[] = array('accid' => 'USKY1288', 'name' => 'Rocky Hill');
$city_data[] = array('accid' => 'USKY1289', 'name' => 'Rogers');
$city_data[] = array('accid' => 'USKY1290', 'name' => 'Rosine');
$city_data[] = array('accid' => 'USKY1291', 'name' => 'Roundhill');
$city_data[] = array('accid' => 'USKY1292', 'name' => 'Rousseau');
$city_data[] = array('accid' => 'USKY1293', 'name' => 'Rowdy');
$city_data[] = array('accid' => 'USKY1294', 'name' => 'Roxana');
$city_data[] = array('accid' => 'USKY1295', 'name' => 'Royalton');
$city_data[] = array('accid' => 'USKY1296', 'name' => 'Rumsey');
$city_data[] = array('accid' => 'USKY1297', 'name' => 'Rush');
$city_data[] = array('accid' => 'USKY1298', 'name' => 'Russell');
$city_data[] = array('accid' => 'USKY1299', 'name' => 'Russell Springs');
$city_data[] = array('accid' => 'USKY1300', 'name' => 'Russellville');
$city_data[] = array('accid' => 'USKY1301', 'name' => 'Sacramento');
$city_data[] = array('accid' => 'USKY1302', 'name' => 'Sadieville');
$city_data[] = array('accid' => 'USKY1303', 'name' => 'Saint Catharine');
$city_data[] = array('accid' => 'USKY1304', 'name' => 'Saint Charles');
$city_data[] = array('accid' => 'USKY1305', 'name' => 'Saint Francis');
$city_data[] = array('accid' => 'USKY1306', 'name' => 'Saint Helens');
$city_data[] = array('accid' => 'USKY1307', 'name' => 'Saint Mary');
$city_data[] = array('accid' => 'USKY1308', 'name' => 'Saint Paul');
$city_data[] = array('accid' => 'USKY1309', 'name' => 'Salem');
$city_data[] = array('accid' => 'USKY1310', 'name' => 'Salt Lick');
$city_data[] = array('accid' => 'USKY1311', 'name' => 'Salvisa');
$city_data[] = array('accid' => 'USKY1312', 'name' => 'Salyersville');
$city_data[] = array('accid' => 'USKY1313', 'name' => 'Sanders');
$city_data[] = array('accid' => 'USKY1314', 'name' => 'Sandgap');
$city_data[] = array('accid' => 'USKY1315', 'name' => 'Sandy Hook');
$city_data[] = array('accid' => 'USKY1316', 'name' => 'Sassafras');
$city_data[] = array('accid' => 'USKY1317', 'name' => 'Saul');
$city_data[] = array('accid' => 'USKY1318', 'name' => 'Scalf');
$city_data[] = array('accid' => 'USKY1319', 'name' => 'Science Hill');
$city_data[] = array('accid' => 'USKY1320', 'name' => 'Scottsville');
$city_data[] = array('accid' => 'USKY1321', 'name' => 'Scuddy');
$city_data[] = array('accid' => 'USKY1322', 'name' => 'Se Ree');
$city_data[] = array('accid' => 'USKY1323', 'name' => 'Sebree');
$city_data[] = array('accid' => 'USKY1324', 'name' => 'Seco');
$city_data[] = array('accid' => 'USKY1325', 'name' => 'Sedalia');
$city_data[] = array('accid' => 'USKY1326', 'name' => 'Sextons Creek');
$city_data[] = array('accid' => 'USKY1327', 'name' => 'Sharon Grove');
$city_data[] = array('accid' => 'USKY1328', 'name' => 'Sharpsburg');
$city_data[] = array('accid' => 'USKY1329', 'name' => 'Shelbiana');
$city_data[] = array('accid' => 'USKY1330', 'name' => 'Shelby Gap');
$city_data[] = array('accid' => 'USKY1331', 'name' => 'Shelbyville');
$city_data[] = array('accid' => 'USKY1332', 'name' => 'Shepherdsville');
$city_data[] = array('accid' => 'USKY1333', 'name' => 'Sidney');
$city_data[] = array('accid' => 'USKY1334', 'name' => 'Siler');
$city_data[] = array('accid' => 'USKY1335', 'name' => 'Silver Grove');
$city_data[] = array('accid' => 'USKY1336', 'name' => 'Simpsonville');
$city_data[] = array('accid' => 'USKY1337', 'name' => 'Sitka');
$city_data[] = array('accid' => 'USKY1338', 'name' => 'Sizerock');
$city_data[] = array('accid' => 'USKY1339', 'name' => 'Slade');
$city_data[] = array('accid' => 'USKY1340', 'name' => 'Slaughters');
$city_data[] = array('accid' => 'USKY1341', 'name' => 'Slemp');
$city_data[] = array('accid' => 'USKY1342', 'name' => 'Sloans Valley');
$city_data[] = array('accid' => 'USKY1343', 'name' => 'Smilax');
$city_data[] = array('accid' => 'USKY1344', 'name' => 'Smith');
$city_data[] = array('accid' => 'USKY1345', 'name' => 'Smith Mills');
$city_data[] = array('accid' => 'USKY1346', 'name' => 'Smithfield');
$city_data[] = array('accid' => 'USKY1347', 'name' => 'Smithland');
$city_data[] = array('accid' => 'USKY1348', 'name' => 'Smiths Grove');
$city_data[] = array('accid' => 'USKY1349', 'name' => 'Soldier');
$city_data[] = array('accid' => 'USKY1350', 'name' => 'Somerset');
$city_data[] = array('accid' => 'USKY1351', 'name' => 'Sonora');
$city_data[] = array('accid' => 'USKY1352', 'name' => 'South Carrollton');
$city_data[] = array('accid' => 'USKY1353', 'name' => 'South Portsmouth');
$city_data[] = array('accid' => 'USKY1354', 'name' => 'South Shore');
$city_data[] = array('accid' => 'USKY1355', 'name' => 'South Union');
$city_data[] = array('accid' => 'USKY1356', 'name' => 'South Williamson');
$city_data[] = array('accid' => 'USKY1357', 'name' => 'Sparta');
$city_data[] = array('accid' => 'USKY1358', 'name' => 'Spottsville');
$city_data[] = array('accid' => 'USKY1359', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USKY1360', 'name' => 'Staffordsville');
$city_data[] = array('accid' => 'USKY1361', 'name' => 'Stambaugh');
$city_data[] = array('accid' => 'USKY1362', 'name' => 'Stamping Ground');
$city_data[] = array('accid' => 'USKY1363', 'name' => 'Stanford');
$city_data[] = array('accid' => 'USKY1364', 'name' => 'Stanley');
$city_data[] = array('accid' => 'USKY1365', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USKY1366', 'name' => 'Stanville');
$city_data[] = array('accid' => 'USKY1367', 'name' => 'Stearns');
$city_data[] = array('accid' => 'USKY1368', 'name' => 'Steele');
$city_data[] = array('accid' => 'USKY1369', 'name' => 'Stephensport');
$city_data[] = array('accid' => 'USKY1370', 'name' => 'Stinnett');
$city_data[] = array('accid' => 'USKY1371', 'name' => 'Stone');
$city_data[] = array('accid' => 'USKY1372', 'name' => 'Stoney Fork');
$city_data[] = array('accid' => 'USKY1373', 'name' => 'Stopover');
$city_data[] = array('accid' => 'USKY1374', 'name' => 'Strunk');
$city_data[] = array('accid' => 'USKY1375', 'name' => 'Sturgis');
$city_data[] = array('accid' => 'USKY1376', 'name' => 'Sullivan');
$city_data[] = array('accid' => 'USKY1377', 'name' => 'Sulphur');
$city_data[] = array('accid' => 'USKY1378', 'name' => 'Summer Shade');
$city_data[] = array('accid' => 'USKY1379', 'name' => 'Summersville');
$city_data[] = array('accid' => 'USKY1380', 'name' => 'Summit');
$city_data[] = array('accid' => 'USKY1381', 'name' => 'Sweeden');
$city_data[] = array('accid' => 'USKY1382', 'name' => 'Symsonia');
$city_data[] = array('accid' => 'USKY1383', 'name' => 'Talbert');
$city_data[] = array('accid' => 'USKY1384', 'name' => 'Tateville');
$city_data[] = array('accid' => 'USKY1385', 'name' => 'Taylorsville');
$city_data[] = array('accid' => 'USKY1386', 'name' => 'Teaberry');
$city_data[] = array('accid' => 'USKY1387', 'name' => 'Thelma');
$city_data[] = array('accid' => 'USKY1388', 'name' => 'Thornton');
$city_data[] = array('accid' => 'USKY1389', 'name' => 'Thousandsticks');
$city_data[] = array('accid' => 'USKY1390', 'name' => 'Tiline');
$city_data[] = array('accid' => 'USKY1391', 'name' => 'Toler');
$city_data[] = array('accid' => 'USKY1392', 'name' => 'Tollesboro');
$city_data[] = array('accid' => 'USKY1393', 'name' => 'Tolu');
$city_data[] = array('accid' => 'USKY1394', 'name' => 'Tomahawk');
$city_data[] = array('accid' => 'USKY1395', 'name' => 'Tompkinsville');
$city_data[] = array('accid' => 'USKY1396', 'name' => 'Topmost');
$city_data[] = array('accid' => 'USKY1397', 'name' => 'Totz');
$city_data[] = array('accid' => 'USKY1398', 'name' => 'Tram');
$city_data[] = array('accid' => 'USKY1399', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USKY1400', 'name' => 'Trosper');
$city_data[] = array('accid' => 'USKY1401', 'name' => 'Turners Station');
$city_data[] = array('accid' => 'USKY1402', 'name' => 'Tutor Key');
$city_data[] = array('accid' => 'USKY1403', 'name' => 'Tyner');
$city_data[] = array('accid' => 'USKY1404', 'name' => 'Ulysses');
$city_data[] = array('accid' => 'USKY1405', 'name' => 'Union');
$city_data[] = array('accid' => 'USKY1406', 'name' => 'Union Star');
$city_data[] = array('accid' => 'USKY1407', 'name' => 'Uniontown');
$city_data[] = array('accid' => 'USKY1408', 'name' => 'Upton');
$city_data[] = array('accid' => 'USKY1409', 'name' => 'Utica');
$city_data[] = array('accid' => 'USKY1410', 'name' => 'Van Lear');
$city_data[] = array('accid' => 'USKY1411', 'name' => 'Vanceburg');
$city_data[] = array('accid' => 'USKY1412', 'name' => 'Vancleve');
$city_data[] = array('accid' => 'USKY1413', 'name' => 'Varney');
$city_data[] = array('accid' => 'USKY1414', 'name' => 'Verona');
$city_data[] = array('accid' => 'USKY1415', 'name' => 'Versailles');
$city_data[] = array('accid' => 'USKY1416', 'name' => 'Vest');
$city_data[] = array('accid' => 'USKY1417', 'name' => 'Vicco');
$city_data[] = array('accid' => 'USKY1418', 'name' => 'Vincent');
$city_data[] = array('accid' => 'USKY1419', 'name' => 'Vine Grove');
$city_data[] = array('accid' => 'USKY1420', 'name' => 'Viper');
$city_data[] = array('accid' => 'USKY1421', 'name' => 'Virgie');
$city_data[] = array('accid' => 'USKY1422', 'name' => 'Waco');
$city_data[] = array('accid' => 'USKY1423', 'name' => 'Waddy');
$city_data[] = array('accid' => 'USKY1424', 'name' => 'Walker');
$city_data[] = array('accid' => 'USKY1425', 'name' => 'Wallingford');
$city_data[] = array('accid' => 'USKY1426', 'name' => 'Wallins Creek');
$city_data[] = array('accid' => 'USKY1427', 'name' => 'Walton');
$city_data[] = array('accid' => 'USKY1428', 'name' => 'Waneta');
$city_data[] = array('accid' => 'USKY1429', 'name' => 'Warbranch');
$city_data[] = array('accid' => 'USKY1430', 'name' => 'Warfield');
$city_data[] = array('accid' => 'USKY1431', 'name' => 'Warsaw');
$city_data[] = array('accid' => 'USKY1432', 'name' => 'Washington');
$city_data[] = array('accid' => 'USKY1433', 'name' => 'Water Valley');
$city_data[] = array('accid' => 'USKY1434', 'name' => 'Waterview');
$city_data[] = array('accid' => 'USKY1435', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USKY1436', 'name' => 'Wayland');
$city_data[] = array('accid' => 'USKY1437', 'name' => 'Waynesburg');
$city_data[] = array('accid' => 'USKY1438', 'name' => 'Webbville');
$city_data[] = array('accid' => 'USKY1439', 'name' => 'Webster');
$city_data[] = array('accid' => 'USKY1440', 'name' => 'Weeksbury');
$city_data[] = array('accid' => 'USKY1441', 'name' => 'Welchs Creek');
$city_data[] = array('accid' => 'USKY1443', 'name' => 'Wendover');
$city_data[] = array('accid' => 'USKY1444', 'name' => 'West Liberty');
$city_data[] = array('accid' => 'USKY1445', 'name' => 'West Louisville');
$city_data[] = array('accid' => 'USKY1446', 'name' => 'West Paducah');
$city_data[] = array('accid' => 'USKY1447', 'name' => 'West Point');
$city_data[] = array('accid' => 'USKY1448', 'name' => 'West Prestonsburg');
$city_data[] = array('accid' => 'USKY1449', 'name' => 'West Somerset');
$city_data[] = array('accid' => 'USKY1450', 'name' => 'West Van Lear');
$city_data[] = array('accid' => 'USKY1451', 'name' => 'Westport');
$city_data[] = array('accid' => 'USKY1452', 'name' => 'Westview');
$city_data[] = array('accid' => 'USKY1453', 'name' => 'Wheatcroft');
$city_data[] = array('accid' => 'USKY1454', 'name' => 'Wheelwright');
$city_data[] = array('accid' => 'USKY1455', 'name' => 'Whick');
$city_data[] = array('accid' => 'USKY1456', 'name' => 'White Mills');
$city_data[] = array('accid' => 'USKY1457', 'name' => 'White Plains');
$city_data[] = array('accid' => 'USKY1458', 'name' => 'Whitesburg');
$city_data[] = array('accid' => 'USKY1459', 'name' => 'Whitesville');
$city_data[] = array('accid' => 'USKY1460', 'name' => 'Whitley City');
$city_data[] = array('accid' => 'USKY1461', 'name' => 'Wickliffe');
$city_data[] = array('accid' => 'USKY1462', 'name' => 'Wildie');
$city_data[] = array('accid' => 'USKY1463', 'name' => 'Willard');
$city_data[] = array('accid' => 'USKY1464', 'name' => 'Williamsburg');
$city_data[] = array('accid' => 'USKY1465', 'name' => 'Williamsport');
$city_data[] = array('accid' => 'USKY1466', 'name' => 'Williamstown');
$city_data[] = array('accid' => 'USKY1467', 'name' => 'Willisburg');
$city_data[] = array('accid' => 'USKY1468', 'name' => 'Wilmore');
$city_data[] = array('accid' => 'USKY1469', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USKY1470', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USKY1471', 'name' => 'Wingo');
$city_data[] = array('accid' => 'USKY1472', 'name' => 'Winston');
$city_data[] = array('accid' => 'USKY1473', 'name' => 'Wittensville');
$city_data[] = array('accid' => 'USKY1474', 'name' => 'Woodbine');
$city_data[] = array('accid' => 'USKY1475', 'name' => 'Woodburn');
$city_data[] = array('accid' => 'USKY1476', 'name' => 'Woodbury');
$city_data[] = array('accid' => 'USKY1477', 'name' => 'Woollum');
$city_data[] = array('accid' => 'USKY1478', 'name' => 'Wooton');
$city_data[] = array('accid' => 'USKY1479', 'name' => 'Worthington');
$city_data[] = array('accid' => 'USKY1480', 'name' => 'Worthville');
$city_data[] = array('accid' => 'USKY1481', 'name' => 'Wrigley');
$city_data[] = array('accid' => 'USKY1482', 'name' => 'Yeaddiss');
$city_data[] = array('accid' => 'USKY1483', 'name' => 'Yerkes');
$city_data[] = array('accid' => 'USKY1484', 'name' => 'Yosemite');
$city_data[] = array('accid' => 'USKY1485', 'name' => 'Zoe');

?>
