<?php

// City package for USA: Louisiana 

$city_name = 'USA: Louisiana';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USLA0001', 'name' => 'Abbeville');
$city_data[] = array('accid' => 'USLA0002', 'name' => 'Abita Springs');
$city_data[] = array('accid' => 'USLA0003', 'name' => 'Acme');
$city_data[] = array('accid' => 'USLA0004', 'name' => 'Addis');
$city_data[] = array('accid' => 'USLA0005', 'name' => 'Aimwell');
$city_data[] = array('accid' => 'USLA0006', 'name' => 'Akers');
$city_data[] = array('accid' => 'USLA0007', 'name' => 'Albany');
$city_data[] = array('accid' => 'USLA0008', 'name' => 'Alexandria');
$city_data[] = array('accid' => 'USLA0010', 'name' => 'Ama');
$city_data[] = array('accid' => 'USLA0011', 'name' => 'Amelia');
$city_data[] = array('accid' => 'USLA0012', 'name' => 'Amite');
$city_data[] = array('accid' => 'USLA0013', 'name' => 'Anacoco');
$city_data[] = array('accid' => 'USLA0014', 'name' => 'Angie');
$city_data[] = array('accid' => 'USLA0015', 'name' => 'Angola');
$city_data[] = array('accid' => 'USLA0016', 'name' => 'Arabi');
$city_data[] = array('accid' => 'USLA0017', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USLA0018', 'name' => 'Archibald');
$city_data[] = array('accid' => 'USLA0019', 'name' => 'Arnaudville');
$city_data[] = array('accid' => 'USLA0020', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USLA0021', 'name' => 'Athens');
$city_data[] = array('accid' => 'USLA0022', 'name' => 'Atlanta');
$city_data[] = array('accid' => 'USLA0023', 'name' => 'Avery Island');
$city_data[] = array('accid' => 'USLA0024', 'name' => 'Baker');
$city_data[] = array('accid' => 'USLA0025', 'name' => 'Baldwin');
$city_data[] = array('accid' => 'USLA0026', 'name' => 'Ball');
$city_data[] = array('accid' => 'USLA0027', 'name' => 'Barataria');
$city_data[] = array('accid' => 'USLA0028', 'name' => 'Barksdale AFB');
$city_data[] = array('accid' => 'USLA0029', 'name' => 'Basile');
$city_data[] = array('accid' => 'USLA0030', 'name' => 'Baskin');
$city_data[] = array('accid' => 'USLA0031', 'name' => 'Bastrop');
$city_data[] = array('accid' => 'USLA0032', 'name' => 'Batchelor');
$city_data[] = array('accid' => 'USLA0033', 'name' => 'Baton Rouge');
$city_data[] = array('accid' => 'USLA0034', 'name' => 'Bayou Goula');
$city_data[] = array('accid' => 'USLA0035', 'name' => 'Belcher');
$city_data[] = array('accid' => 'USLA0036', 'name' => 'Bell City');
$city_data[] = array('accid' => 'USLA0037', 'name' => 'Belle Chasse');
$city_data[] = array('accid' => 'USLA0038', 'name' => 'Belle Rose');
$city_data[] = array('accid' => 'USLA0039', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USLA0040', 'name' => 'Bentley');
$city_data[] = array('accid' => 'USLA0041', 'name' => 'Benton');
$city_data[] = array('accid' => 'USLA0042', 'name' => 'Bernice');
$city_data[] = array('accid' => 'USLA0043', 'name' => 'Berwick');
$city_data[] = array('accid' => 'USLA0044', 'name' => 'Bethany');
$city_data[] = array('accid' => 'USLA0045', 'name' => 'Bienville');
$city_data[] = array('accid' => 'USLA0046', 'name' => 'Blanchard');
$city_data[] = array('accid' => 'USLA0047', 'name' => 'Blanks');
$city_data[] = array('accid' => 'USLA0048', 'name' => 'Bogalusa');
$city_data[] = array('accid' => 'USLA0049', 'name' => 'Bonita');
$city_data[] = array('accid' => 'USLA0050', 'name' => 'Boothville');
$city_data[] = array('accid' => 'USLA0051', 'name' => 'Bordelonville');
$city_data[] = array('accid' => 'USLA0052', 'name' => 'Bossier City');
$city_data[] = array('accid' => 'USLA0053', 'name' => 'Bourg');
$city_data[] = array('accid' => 'USLA0054', 'name' => 'Boutte');
$city_data[] = array('accid' => 'USLA0055', 'name' => 'Boyce');
$city_data[] = array('accid' => 'USLA0056', 'name' => 'Braithwaite');
$city_data[] = array('accid' => 'USLA0057', 'name' => 'Branch');
$city_data[] = array('accid' => 'USLA0058', 'name' => 'Breaux Bridge');
$city_data[] = array('accid' => 'USLA0059', 'name' => 'Brittany');
$city_data[] = array('accid' => 'USLA0060', 'name' => 'Broussard');
$city_data[] = array('accid' => 'USLA0061', 'name' => 'Brusly');
$city_data[] = array('accid' => 'USLA0062', 'name' => 'Bueche');
$city_data[] = array('accid' => 'USLA0063', 'name' => 'Bunkie');
$city_data[] = array('accid' => 'USLA0064', 'name' => 'Buras');
$city_data[] = array('accid' => 'USLA0065', 'name' => 'Burnside');
$city_data[] = array('accid' => 'USLA0066', 'name' => 'Bush');
$city_data[] = array('accid' => 'USLA0067', 'name' => 'Cade');
$city_data[] = array('accid' => 'USLA0068', 'name' => 'Calhoun');
$city_data[] = array('accid' => 'USLA0069', 'name' => 'Calvin');
$city_data[] = array('accid' => 'USLA0070', 'name' => 'Cameron');
$city_data[] = array('accid' => 'USLA0071', 'name' => 'Campti');
$city_data[] = array('accid' => 'USLA0072', 'name' => 'Carencro');
$city_data[] = array('accid' => 'USLA0073', 'name' => 'Carlisle');
$city_data[] = array('accid' => 'USLA0074', 'name' => 'Carville');
$city_data[] = array('accid' => 'USLA0075', 'name' => 'Castor');
$city_data[] = array('accid' => 'USLA0076', 'name' => 'Cecilia');
$city_data[] = array('accid' => 'USLA0077', 'name' => 'Center Point');
$city_data[] = array('accid' => 'USLA0078', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USLA0079', 'name' => 'Chalmette');
$city_data[] = array('accid' => 'USLA0080', 'name' => 'Charenton');
$city_data[] = array('accid' => 'USLA0081', 'name' => 'Chase');
$city_data[] = array('accid' => 'USLA0082', 'name' => 'Chataignier');
$city_data[] = array('accid' => 'USLA0083', 'name' => 'Chatham');
$city_data[] = array('accid' => 'USLA0084', 'name' => 'Chauvin');
$city_data[] = array('accid' => 'USLA0085', 'name' => 'Cheneyville');
$city_data[] = array('accid' => 'USLA0086', 'name' => 'Choudrant');
$city_data[] = array('accid' => 'USLA0087', 'name' => 'Church Point');
$city_data[] = array('accid' => 'USLA0088', 'name' => 'Clarence');
$city_data[] = array('accid' => 'USLA0089', 'name' => 'Clarks');
$city_data[] = array('accid' => 'USLA0090', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USLA0091', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USLA0092', 'name' => 'Cloutierville');
$city_data[] = array('accid' => 'USLA0093', 'name' => 'Colfax');
$city_data[] = array('accid' => 'USLA0094', 'name' => 'Collinston');
$city_data[] = array('accid' => 'USLA0095', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USLA0096', 'name' => 'Convent');
$city_data[] = array('accid' => 'USLA0097', 'name' => 'Converse');
$city_data[] = array('accid' => 'USLA0098', 'name' => 'Cotton Valley');
$city_data[] = array('accid' => 'USLA0099', 'name' => 'Cottonport');
$city_data[] = array('accid' => 'USLA0100', 'name' => 'Coushatta');
$city_data[] = array('accid' => 'USLA0101', 'name' => 'Covington');
$city_data[] = array('accid' => 'USLA0102', 'name' => 'Creole');
$city_data[] = array('accid' => 'USLA0103', 'name' => 'Crowley');
$city_data[] = array('accid' => 'USLA0104', 'name' => 'Crowville');
$city_data[] = array('accid' => 'USLA0105', 'name' => 'Cullen');
$city_data[] = array('accid' => 'USLA0106', 'name' => 'Cut Off');
$city_data[] = array('accid' => 'USLA0107', 'name' => 'Darrow');
$city_data[] = array('accid' => 'USLA0108', 'name' => 'Davant');
$city_data[] = array('accid' => 'USLA0109', 'name' => 'Delcambre');
$city_data[] = array('accid' => 'USLA0110', 'name' => 'Delhi');
$city_data[] = array('accid' => 'USLA0111', 'name' => 'Delta');
$city_data[] = array('accid' => 'USLA0112', 'name' => 'Denham Springs');
$city_data[] = array('accid' => 'USLA0113', 'name' => 'Dequincy');
$city_data[] = array('accid' => 'USLA0114', 'name' => 'Deridder');
$city_data[] = array('accid' => 'USLA0115', 'name' => 'Des Allemands');
$city_data[] = array('accid' => 'USLA0116', 'name' => 'Destrehan');
$city_data[] = array('accid' => 'USLA0117', 'name' => 'Deville');
$city_data[] = array('accid' => 'USLA0118', 'name' => 'Dodson');
$city_data[] = array('accid' => 'USLA0119', 'name' => 'Donaldsonville');
$city_data[] = array('accid' => 'USLA0120', 'name' => 'Donner');
$city_data[] = array('accid' => 'USLA0121', 'name' => 'Downsville');
$city_data[] = array('accid' => 'USLA0122', 'name' => 'Doyline');
$city_data[] = array('accid' => 'USLA0123', 'name' => 'Dry Creek');
$city_data[] = array('accid' => 'USLA0124', 'name' => 'Dry Prong');
$city_data[] = array('accid' => 'USLA0125', 'name' => 'Dubach');
$city_data[] = array('accid' => 'USLA0126', 'name' => 'Dubberly');
$city_data[] = array('accid' => 'USLA0127', 'name' => 'Dulac');
$city_data[] = array('accid' => 'USLA0128', 'name' => 'Duplessis');
$city_data[] = array('accid' => 'USLA0129', 'name' => 'Dupont');
$city_data[] = array('accid' => 'USLA0130', 'name' => 'Duson');
$city_data[] = array('accid' => 'USLA0131', 'name' => 'East Point');
$city_data[] = array('accid' => 'USLA0132', 'name' => 'Echo');
$city_data[] = array('accid' => 'USLA0133', 'name' => 'Edgard');
$city_data[] = array('accid' => 'USLA0134', 'name' => 'Effie');
$city_data[] = array('accid' => 'USLA0135', 'name' => 'Egan');
$city_data[] = array('accid' => 'USLA0136', 'name' => 'Elizabeth');
$city_data[] = array('accid' => 'USLA0137', 'name' => 'Elm Grove');
$city_data[] = array('accid' => 'USLA0138', 'name' => 'Elmer');
$city_data[] = array('accid' => 'USLA0139', 'name' => 'Elton');
$city_data[] = array('accid' => 'USLA0140', 'name' => 'Empire');
$city_data[] = array('accid' => 'USLA0141', 'name' => 'Enterprise');
$city_data[] = array('accid' => 'USLA0142', 'name' => 'Epps');
$city_data[] = array('accid' => 'USLA0143', 'name' => 'Erath');
$city_data[] = array('accid' => 'USLA0144', 'name' => 'Eros');
$city_data[] = array('accid' => 'USLA0145', 'name' => 'Erwinville');
$city_data[] = array('accid' => 'USLA0146', 'name' => 'Estherwood');
$city_data[] = array('accid' => 'USLA0147', 'name' => 'Ethel');
$city_data[] = array('accid' => 'USLA0148', 'name' => 'Eunice');
$city_data[] = array('accid' => 'USLA0149', 'name' => 'Evangeline');
$city_data[] = array('accid' => 'USLA0150', 'name' => 'Evans');
$city_data[] = array('accid' => 'USLA0151', 'name' => 'Evergreen');
$city_data[] = array('accid' => 'USLA0152', 'name' => 'Fairbanks');
$city_data[] = array('accid' => 'USLA0153', 'name' => 'Farmerville');
$city_data[] = array('accid' => 'USLA0154', 'name' => 'Fenton');
$city_data[] = array('accid' => 'USLA0155', 'name' => 'Ferriday');
$city_data[] = array('accid' => 'USLA0156', 'name' => 'Fisher');
$city_data[] = array('accid' => 'USLA0157', 'name' => 'Flatwoods');
$city_data[] = array('accid' => 'USLA0158', 'name' => 'Flora');
$city_data[] = array('accid' => 'USLA0159', 'name' => 'Florien');
$city_data[] = array('accid' => 'USLA0160', 'name' => 'Fluker');
$city_data[] = array('accid' => 'USLA0161', 'name' => 'Folsom');
$city_data[] = array('accid' => 'USLA0162', 'name' => 'Fordoche');
$city_data[] = array('accid' => 'USLA0163', 'name' => 'Forest');
$city_data[] = array('accid' => 'USLA0164', 'name' => 'Forest Hill');
$city_data[] = array('accid' => 'USLA0165', 'name' => 'Fort Necessity');
$city_data[] = array('accid' => 'USLA0166', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USLA0167', 'name' => 'Franklinton');
$city_data[] = array('accid' => 'USLA0168', 'name' => 'French Settlement');
$city_data[] = array('accid' => 'USLA0169', 'name' => 'Frierson');
$city_data[] = array('accid' => 'USLA0170', 'name' => 'Fullerton');
$city_data[] = array('accid' => 'USLA0171', 'name' => 'Galliano');
$city_data[] = array('accid' => 'USLA0172', 'name' => 'Garden City');
$city_data[] = array('accid' => 'USLA0173', 'name' => 'Gardner');
$city_data[] = array('accid' => 'USLA0174', 'name' => 'Garyville');
$city_data[] = array('accid' => 'USLA0175', 'name' => 'Geismar');
$city_data[] = array('accid' => 'USLA0176', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USLA0177', 'name' => 'Gheens');
$city_data[] = array('accid' => 'USLA0178', 'name' => 'Gibsland');
$city_data[] = array('accid' => 'USLA0179', 'name' => 'Gibson');
$city_data[] = array('accid' => 'USLA0180', 'name' => 'Gilbert');
$city_data[] = array('accid' => 'USLA0181', 'name' => 'Gilliam');
$city_data[] = array('accid' => 'USLA0182', 'name' => 'Glenmora');
$city_data[] = array('accid' => 'USLA0183', 'name' => 'Gloster');
$city_data[] = array('accid' => 'USLA0184', 'name' => 'Glynn');
$city_data[] = array('accid' => 'USLA0185', 'name' => 'Golden Meadow');
$city_data[] = array('accid' => 'USLA0186', 'name' => 'Goldonna');
$city_data[] = array('accid' => 'USLA0187', 'name' => 'Gonzales');
$city_data[] = array('accid' => 'USLA0188', 'name' => 'Gorum');
$city_data[] = array('accid' => 'USLA0189', 'name' => 'Grambling');
$city_data[] = array('accid' => 'USLA0190', 'name' => 'Gramercy');
$city_data[] = array('accid' => 'USLA0191', 'name' => 'Grand Cane');
$city_data[] = array('accid' => 'USLA0192', 'name' => 'Grand Chenier');
$city_data[] = array('accid' => 'USLA0193', 'name' => 'Grand Coteau');
$city_data[] = array('accid' => 'USLA0194', 'name' => 'Grand Isle');
$city_data[] = array('accid' => 'USLA0195', 'name' => 'Grant');
$city_data[] = array('accid' => 'USLA0196', 'name' => 'Gray');
$city_data[] = array('accid' => 'USLA0197', 'name' => 'Grayson');
$city_data[] = array('accid' => 'USLA0198', 'name' => 'Greensburg');
$city_data[] = array('accid' => 'USLA0199', 'name' => 'Greenwell Springs');
$city_data[] = array('accid' => 'USLA0200', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USLA0201', 'name' => 'Gretna');
$city_data[] = array('accid' => 'USLA0202', 'name' => 'Grosse Tete');
$city_data[] = array('accid' => 'USLA0203', 'name' => 'Gueydan');
$city_data[] = array('accid' => 'USLA0204', 'name' => 'Hackberry');
$city_data[] = array('accid' => 'USLA0205', 'name' => 'Hahnville');
$city_data[] = array('accid' => 'USLA0206', 'name' => 'Hall Summit');
$city_data[] = array('accid' => 'USLA0207', 'name' => 'Hamburg');
$city_data[] = array('accid' => 'USLA0208', 'name' => 'Hammond');
$city_data[] = array('accid' => 'USLA0209', 'name' => 'Harmon');
$city_data[] = array('accid' => 'USLA0210', 'name' => 'Harrisonburg');
$city_data[] = array('accid' => 'USLA0211', 'name' => 'Harvey');
$city_data[] = array('accid' => 'USLA0212', 'name' => 'Haughton');
$city_data[] = array('accid' => 'USLA0213', 'name' => 'Hayes');
$city_data[] = array('accid' => 'USLA0214', 'name' => 'Haynesville');
$city_data[] = array('accid' => 'USLA0215', 'name' => 'Heflin');
$city_data[] = array('accid' => 'USLA0216', 'name' => 'Hessmer');
$city_data[] = array('accid' => 'USLA0217', 'name' => 'Hester');
$city_data[] = array('accid' => 'USLA0218', 'name' => 'Hineston');
$city_data[] = array('accid' => 'USLA0219', 'name' => 'Hodge');
$city_data[] = array('accid' => 'USLA0220', 'name' => 'Holden');
$city_data[] = array('accid' => 'USLA0221', 'name' => 'Homer');
$city_data[] = array('accid' => 'USLA0222', 'name' => 'Hornbeck');
$city_data[] = array('accid' => 'USLA0223', 'name' => 'Hosston');
$city_data[] = array('accid' => 'USLA0224', 'name' => 'Houma');
$city_data[] = array('accid' => 'USLA0225', 'name' => 'Husser');
$city_data[] = array('accid' => 'USLA0226', 'name' => 'Ida');
$city_data[] = array('accid' => 'USLA0227', 'name' => 'Independence');
$city_data[] = array('accid' => 'USLA0228', 'name' => 'Innis');
$city_data[] = array('accid' => 'USLA0230', 'name' => 'Iota');
$city_data[] = array('accid' => 'USLA0231', 'name' => 'Iowa');
$city_data[] = array('accid' => 'USLA0232', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USLA0233', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USLA0234', 'name' => 'Jarreau');
$city_data[] = array('accid' => 'USLA0235', 'name' => 'Jeanerette');
$city_data[] = array('accid' => 'USLA0236', 'name' => 'Jena');
$city_data[] = array('accid' => 'USLA0237', 'name' => 'Jennings');
$city_data[] = array('accid' => 'USLA0238', 'name' => 'Jigger');
$city_data[] = array('accid' => 'USLA0239', 'name' => 'Jones');
$city_data[] = array('accid' => 'USLA0240', 'name' => 'Jonesboro');
$city_data[] = array('accid' => 'USLA0241', 'name' => 'Jonesville');
$city_data[] = array('accid' => 'USLA0242', 'name' => 'Joyce');
$city_data[] = array('accid' => 'USLA0243', 'name' => 'Kaplan');
$city_data[] = array('accid' => 'USLA0244', 'name' => 'Keatchie');
$city_data[] = array('accid' => 'USLA0245', 'name' => 'Keithville');
$city_data[] = array('accid' => 'USLA0246', 'name' => 'Kelly');
$city_data[] = array('accid' => 'USLA0247', 'name' => 'Kenner');
$city_data[] = array('accid' => 'USLA0248', 'name' => 'Kentwood');
$city_data[] = array('accid' => 'USLA0249', 'name' => 'Kilbourne');
$city_data[] = array('accid' => 'USLA0250', 'name' => 'Killona');
$city_data[] = array('accid' => 'USLA0251', 'name' => 'Kinder');
$city_data[] = array('accid' => 'USLA0252', 'name' => 'Kraemer');
$city_data[] = array('accid' => 'USLA0253', 'name' => 'Krotz Springs');
$city_data[] = array('accid' => 'USLA0254', 'name' => 'Kurthwood');
$city_data[] = array('accid' => 'USLA0255', 'name' => 'La Place');
$city_data[] = array('accid' => 'USLA0256', 'name' => 'Labadieville');
$city_data[] = array('accid' => 'USLA0257', 'name' => 'Labarre');
$city_data[] = array('accid' => 'USLA0258', 'name' => 'Lacamp');
$city_data[] = array('accid' => 'USLA0259', 'name' => 'Lacassine');
$city_data[] = array('accid' => 'USLA0260', 'name' => 'Lacombe');
$city_data[] = array('accid' => 'USLA0261', 'name' => 'Lafayette');
$city_data[] = array('accid' => 'USLA0262', 'name' => 'Lafitte');
$city_data[] = array('accid' => 'USLA0263', 'name' => 'Lake Arthur');
$city_data[] = array('accid' => 'USLA0264', 'name' => 'Lake Charles');
$city_data[] = array('accid' => 'USLA0266', 'name' => 'Lake Providence');
$city_data[] = array('accid' => 'USLA0267', 'name' => 'Lakeland');
$city_data[] = array('accid' => 'USLA0268', 'name' => 'Larose');
$city_data[] = array('accid' => 'USLA0269', 'name' => 'Lawtell');
$city_data[] = array('accid' => 'USLA0270', 'name' => 'Lebeau');
$city_data[] = array('accid' => 'USLA0271', 'name' => 'Leblanc');
$city_data[] = array('accid' => 'USLA0272', 'name' => 'Lecompte');
$city_data[] = array('accid' => 'USLA0273', 'name' => 'Leesville');
$city_data[] = array('accid' => 'USLA0274', 'name' => 'Lena');
$city_data[] = array('accid' => 'USLA0275', 'name' => 'Leonville');
$city_data[] = array('accid' => 'USLA0276', 'name' => 'Lettsworth');
$city_data[] = array('accid' => 'USLA0277', 'name' => 'Libuse');
$city_data[] = array('accid' => 'USLA0278', 'name' => 'Lillie');
$city_data[] = array('accid' => 'USLA0279', 'name' => 'Lisbon');
$city_data[] = array('accid' => 'USLA0280', 'name' => 'Livingston');
$city_data[] = array('accid' => 'USLA0281', 'name' => 'Livonia');
$city_data[] = array('accid' => 'USLA0282', 'name' => 'Lockport');
$city_data[] = array('accid' => 'USLA0283', 'name' => 'Logansport');
$city_data[] = array('accid' => 'USLA0284', 'name' => 'Longleaf');
$city_data[] = array('accid' => 'USLA0285', 'name' => 'Longstreet');
$city_data[] = array('accid' => 'USLA0286', 'name' => 'Longville');
$city_data[] = array('accid' => 'USLA0287', 'name' => 'Loranger');
$city_data[] = array('accid' => 'USLA0288', 'name' => 'Loreauville');
$city_data[] = array('accid' => 'USLA0289', 'name' => 'Lottie');
$city_data[] = array('accid' => 'USLA0290', 'name' => 'Luling');
$city_data[] = array('accid' => 'USLA0291', 'name' => 'Lutcher');
$city_data[] = array('accid' => 'USLA0292', 'name' => 'Lydia');
$city_data[] = array('accid' => 'USLA0293', 'name' => 'Madisonville');
$city_data[] = array('accid' => 'USLA0294', 'name' => 'Mamou');
$city_data[] = array('accid' => 'USLA0295', 'name' => 'Mandeville');
$city_data[] = array('accid' => 'USLA0296', 'name' => 'Mangham');
$city_data[] = array('accid' => 'USLA0297', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'USLA0298', 'name' => 'Mansura');
$city_data[] = array('accid' => 'USLA0299', 'name' => 'Many');
$city_data[] = array('accid' => 'USLA0300', 'name' => 'Maringouin');
$city_data[] = array('accid' => 'USLA0301', 'name' => 'Marion');
$city_data[] = array('accid' => 'USLA0302', 'name' => 'Marksville');
$city_data[] = array('accid' => 'USLA0303', 'name' => 'Marrero');
$city_data[] = array('accid' => 'USLA0304', 'name' => 'Marthaville');
$city_data[] = array('accid' => 'USLA0305', 'name' => 'Mathews');
$city_data[] = array('accid' => 'USLA0306', 'name' => 'Maurepas');
$city_data[] = array('accid' => 'USLA0307', 'name' => 'Maurice');
$city_data[] = array('accid' => 'USLA0308', 'name' => 'Melrose');
$city_data[] = array('accid' => 'USLA0309', 'name' => 'Melville');
$city_data[] = array('accid' => 'USLA0310', 'name' => 'Mer Rouge');
$city_data[] = array('accid' => 'USLA0311', 'name' => 'Meraux');
$city_data[] = array('accid' => 'USLA0312', 'name' => 'Mermentau');
$city_data[] = array('accid' => 'USLA0313', 'name' => 'Merryville');
$city_data[] = array('accid' => 'USLA0314', 'name' => 'Metairie');
$city_data[] = array('accid' => 'USLA0315', 'name' => 'Milton');
$city_data[] = array('accid' => 'USLA0316', 'name' => 'Minden');
$city_data[] = array('accid' => 'USLA0317', 'name' => 'Mittie');
$city_data[] = array('accid' => 'USLA0318', 'name' => 'Modeste');
$city_data[] = array('accid' => 'USLA0319', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USLA0320', 'name' => 'Montegut');
$city_data[] = array('accid' => 'USLA0321', 'name' => 'Monterey');
$city_data[] = array('accid' => 'USLA0322', 'name' => 'Montgomery');
$city_data[] = array('accid' => 'USLA0323', 'name' => 'Mooringsport');
$city_data[] = array('accid' => 'USLA0324', 'name' => 'Mora');
$city_data[] = array('accid' => 'USLA0325', 'name' => 'Moreauville');
$city_data[] = array('accid' => 'USLA0326', 'name' => 'Morgan City');
$city_data[] = array('accid' => 'USLA0327', 'name' => 'Morganza');
$city_data[] = array('accid' => 'USLA0328', 'name' => 'Morrow');
$city_data[] = array('accid' => 'USLA0329', 'name' => 'Morse');
$city_data[] = array('accid' => 'USLA0330', 'name' => 'Mount Airy');
$city_data[] = array('accid' => 'USLA0331', 'name' => 'Mount Hermon');
$city_data[] = array('accid' => 'USLA0332', 'name' => 'Napoleonville');
$city_data[] = array('accid' => 'USLA0333', 'name' => 'Natalbany');
$city_data[] = array('accid' => 'USLA0334', 'name' => 'Natchez');
$city_data[] = array('accid' => 'USLA0335', 'name' => 'Natchitoches');
$city_data[] = array('accid' => 'USLA0336', 'name' => 'Negreet');
$city_data[] = array('accid' => 'USLA0337', 'name' => 'New Iberia');
$city_data[] = array('accid' => 'USLA0338', 'name' => 'New Orleans');
$city_data[] = array('accid' => 'USLA0341', 'name' => 'New Roads');
$city_data[] = array('accid' => 'USLA0342', 'name' => 'New Sarpy');
$city_data[] = array('accid' => 'USLA0343', 'name' => 'Newellton');
$city_data[] = array('accid' => 'USLA0344', 'name' => 'Newllano');
$city_data[] = array('accid' => 'USLA0345', 'name' => 'Noble');
$city_data[] = array('accid' => 'USLA0346', 'name' => 'Norco');
$city_data[] = array('accid' => 'USLA0347', 'name' => 'Norwood');
$city_data[] = array('accid' => 'USLA0348', 'name' => 'Oak Grove');
$city_data[] = array('accid' => 'USLA0349', 'name' => 'Oak Ridge');
$city_data[] = array('accid' => 'USLA0350', 'name' => 'Oakdale');
$city_data[] = array('accid' => 'USLA0351', 'name' => 'Oberlin');
$city_data[] = array('accid' => 'USLA0352', 'name' => 'Oil City');
$city_data[] = array('accid' => 'USLA0353', 'name' => 'Olla');
$city_data[] = array('accid' => 'USLA0354', 'name' => 'Opelousas');
$city_data[] = array('accid' => 'USLA0355', 'name' => 'Oscar');
$city_data[] = array('accid' => 'USLA0356', 'name' => 'Otis');
$city_data[] = array('accid' => 'USLA0357', 'name' => 'Paincourtville');
$city_data[] = array('accid' => 'USLA0358', 'name' => 'Palmetto');
$city_data[] = array('accid' => 'USLA0359', 'name' => 'Paradis');
$city_data[] = array('accid' => 'USLA0360', 'name' => 'Patterson');
$city_data[] = array('accid' => 'USLA0361', 'name' => 'Paulina');
$city_data[] = array('accid' => 'USLA0362', 'name' => 'Pearl River');
$city_data[] = array('accid' => 'USLA0363', 'name' => 'Pelican');
$city_data[] = array('accid' => 'USLA0364', 'name' => 'Perry');
$city_data[] = array('accid' => 'USLA0365', 'name' => 'Pierre Part');
$city_data[] = array('accid' => 'USLA0366', 'name' => 'Pilottown');
$city_data[] = array('accid' => 'USLA0367', 'name' => 'Pine Grove');
$city_data[] = array('accid' => 'USLA0368', 'name' => 'Pine Prairie');
$city_data[] = array('accid' => 'USLA0369', 'name' => 'Pineville');
$city_data[] = array('accid' => 'USLA0370', 'name' => 'Pioneer');
$city_data[] = array('accid' => 'USLA0371', 'name' => 'Pitkin');
$city_data[] = array('accid' => 'USLA0372', 'name' => 'Plain Dealing');
$city_data[] = array('accid' => 'USLA0373', 'name' => 'Plaquemine');
$city_data[] = array('accid' => 'USLA0374', 'name' => 'Plattenville');
$city_data[] = array('accid' => 'USLA0375', 'name' => 'Plaucheville');
$city_data[] = array('accid' => 'USLA0376', 'name' => 'Pleasant Hill');
$city_data[] = array('accid' => 'USLA0377', 'name' => 'Pointe A La Hache');
$city_data[] = array('accid' => 'USLA0378', 'name' => 'Pollock');
$city_data[] = array('accid' => 'USLA0379', 'name' => 'Ponchatoula');
$city_data[] = array('accid' => 'USLA0380', 'name' => 'Port Allen');
$city_data[] = array('accid' => 'USLA0381', 'name' => 'Port Barre');
$city_data[] = array('accid' => 'USLA0383', 'name' => 'Port Sulphur');
$city_data[] = array('accid' => 'USLA0384', 'name' => 'Powhatan');
$city_data[] = array('accid' => 'USLA0385', 'name' => 'Prairieville');
$city_data[] = array('accid' => 'USLA0386', 'name' => 'Pride');
$city_data[] = array('accid' => 'USLA0387', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USLA0388', 'name' => 'Provencal');
$city_data[] = array('accid' => 'USLA0389', 'name' => 'Quitman');
$city_data[] = array('accid' => 'USLA0390', 'name' => 'Raceland');
$city_data[] = array('accid' => 'USLA0391', 'name' => 'Ragley');
$city_data[] = array('accid' => 'USLA0392', 'name' => 'Rayne');
$city_data[] = array('accid' => 'USLA0393', 'name' => 'Rayville');
$city_data[] = array('accid' => 'USLA0394', 'name' => 'Reddell');
$city_data[] = array('accid' => 'USLA0395', 'name' => 'Reeves');
$city_data[] = array('accid' => 'USLA0396', 'name' => 'Reserve');
$city_data[] = array('accid' => 'USLA0397', 'name' => 'Rhinehart');
$city_data[] = array('accid' => 'USLA0398', 'name' => 'Ringgold');
$city_data[] = array('accid' => 'USLA0399', 'name' => 'Roanoke');
$city_data[] = array('accid' => 'USLA0400', 'name' => 'Robeline');
$city_data[] = array('accid' => 'USLA0401', 'name' => 'Robert');
$city_data[] = array('accid' => 'USLA0402', 'name' => 'Rodessa');
$city_data[] = array('accid' => 'USLA0403', 'name' => 'Rosedale');
$city_data[] = array('accid' => 'USLA0404', 'name' => 'Roseland');
$city_data[] = array('accid' => 'USLA0405', 'name' => 'Rosepine');
$city_data[] = array('accid' => 'USLA0406', 'name' => 'Rougon');
$city_data[] = array('accid' => 'USLA0407', 'name' => 'Ruby');
$city_data[] = array('accid' => 'USLA0408', 'name' => 'Ruston');
$city_data[] = array('accid' => 'USLA0409', 'name' => 'Saint Amant');
$city_data[] = array('accid' => 'USLA0410', 'name' => 'Saint Benedict');
$city_data[] = array('accid' => 'USLA0411', 'name' => 'Saint Bernard');
$city_data[] = array('accid' => 'USLA0412', 'name' => 'Saint Francisville');
$city_data[] = array('accid' => 'USLA0413', 'name' => 'Saint Gabriel');
$city_data[] = array('accid' => 'USLA0414', 'name' => 'Saint James');
$city_data[] = array('accid' => 'USLA0415', 'name' => 'Saint Joseph');
$city_data[] = array('accid' => 'USLA0416', 'name' => 'Saint Landry');
$city_data[] = array('accid' => 'USLA0417', 'name' => 'Saint Martinville');
$city_data[] = array('accid' => 'USLA0418', 'name' => 'Saint Maurice');
$city_data[] = array('accid' => 'USLA0419', 'name' => 'Saint Rose');
$city_data[] = array('accid' => 'USLA0420', 'name' => 'Saline');
$city_data[] = array('accid' => 'USLA0422', 'name' => 'Sarepta');
$city_data[] = array('accid' => 'USLA0423', 'name' => 'Schriever');
$city_data[] = array('accid' => 'USLA0424', 'name' => 'Scott');
$city_data[] = array('accid' => 'USLA0425', 'name' => 'Shongaloo');
$city_data[] = array('accid' => 'USLA0426', 'name' => 'Shreveport');
$city_data[] = array('accid' => 'USLA0428', 'name' => 'Sibley');
$city_data[] = array('accid' => 'USLA0429', 'name' => 'Sicily Island');
$city_data[] = array('accid' => 'USLA0430', 'name' => 'Sieper');
$city_data[] = array('accid' => 'USLA0431', 'name' => 'Sikes');
$city_data[] = array('accid' => 'USLA0432', 'name' => 'Simmesport');
$city_data[] = array('accid' => 'USLA0433', 'name' => 'Simpson');
$city_data[] = array('accid' => 'USLA0434', 'name' => 'Simsboro');
$city_data[] = array('accid' => 'USLA0435', 'name' => 'Singer');
$city_data[] = array('accid' => 'USLA0436', 'name' => 'Slagle');
$city_data[] = array('accid' => 'USLA0437', 'name' => 'Slaughter');
$city_data[] = array('accid' => 'USLA0438', 'name' => 'Slidell');
$city_data[] = array('accid' => 'USLA0439', 'name' => 'Sondheimer');
$city_data[] = array('accid' => 'USLA0440', 'name' => 'Sorrento');
$city_data[] = array('accid' => 'USLA0442', 'name' => 'Spearsville');
$city_data[] = array('accid' => 'USLA0443', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USLA0444', 'name' => 'Springhill');
$city_data[] = array('accid' => 'USLA0445', 'name' => 'Starks');
$city_data[] = array('accid' => 'USLA0446', 'name' => 'Start');
$city_data[] = array('accid' => 'USLA0447', 'name' => 'Sterlington');
$city_data[] = array('accid' => 'USLA0448', 'name' => 'Stonewall');
$city_data[] = array('accid' => 'USLA0449', 'name' => 'Sugartown');
$city_data[] = array('accid' => 'USLA0450', 'name' => 'Sulphur');
$city_data[] = array('accid' => 'USLA0451', 'name' => 'Summerfield');
$city_data[] = array('accid' => 'USLA0452', 'name' => 'Sun');
$city_data[] = array('accid' => 'USLA0453', 'name' => 'Sunset');
$city_data[] = array('accid' => 'USLA0454', 'name' => 'Sunshine');
$city_data[] = array('accid' => 'USLA0455', 'name' => 'Swartz');
$city_data[] = array('accid' => 'USLA0456', 'name' => 'Talisheek');
$city_data[] = array('accid' => 'USLA0457', 'name' => 'Tallulah');
$city_data[] = array('accid' => 'USLA0458', 'name' => 'Tangipahoa');
$city_data[] = array('accid' => 'USLA0459', 'name' => 'Taylor');
$city_data[] = array('accid' => 'USLA0460', 'name' => 'Theriot');
$city_data[] = array('accid' => 'USLA0461', 'name' => 'Thibodaux');
$city_data[] = array('accid' => 'USLA0462', 'name' => 'Tickfaw');
$city_data[] = array('accid' => 'USLA0463', 'name' => 'Tioga');
$city_data[] = array('accid' => 'USLA0464', 'name' => 'Torbert');
$city_data[] = array('accid' => 'USLA0465', 'name' => 'Transylvania');
$city_data[] = array('accid' => 'USLA0466', 'name' => 'Trout');
$city_data[] = array('accid' => 'USLA0467', 'name' => 'Tullos');
$city_data[] = array('accid' => 'USLA0468', 'name' => 'Tunica');
$city_data[] = array('accid' => 'USLA0469', 'name' => 'Turkey Creek');
$city_data[] = array('accid' => 'USLA0470', 'name' => 'Uncle Sam');
$city_data[] = array('accid' => 'USLA0471', 'name' => 'Urania');
$city_data[] = array('accid' => 'USLA0472', 'name' => 'Vacherie');
$city_data[] = array('accid' => 'USLA0473', 'name' => 'Venice');
$city_data[] = array('accid' => 'USLA0474', 'name' => 'Ventress');
$city_data[] = array('accid' => 'USLA0475', 'name' => 'Verda');
$city_data[] = array('accid' => 'USLA0476', 'name' => 'Vidalia');
$city_data[] = array('accid' => 'USLA0477', 'name' => 'Ville Platte');
$city_data[] = array('accid' => 'USLA0478', 'name' => 'Vinton');
$city_data[] = array('accid' => 'USLA0479', 'name' => 'Violet');
$city_data[] = array('accid' => 'USLA0480', 'name' => 'Vivian');
$city_data[] = array('accid' => 'USLA0481', 'name' => 'Wakefield');
$city_data[] = array('accid' => 'USLA0482', 'name' => 'Walker');
$city_data[] = array('accid' => 'USLA0483', 'name' => 'Washington');
$city_data[] = array('accid' => 'USLA0484', 'name' => 'Waterproof');
$city_data[] = array('accid' => 'USLA0485', 'name' => 'Watson');
$city_data[] = array('accid' => 'USLA0486', 'name' => 'Welsh');
$city_data[] = array('accid' => 'USLA0487', 'name' => 'West Monroe');
$city_data[] = array('accid' => 'USLA0488', 'name' => 'Westlake');
$city_data[] = array('accid' => 'USLA0489', 'name' => 'Westwego');
$city_data[] = array('accid' => 'USLA0490', 'name' => 'Weyanoke');
$city_data[] = array('accid' => 'USLA0491', 'name' => 'White Castle');
$city_data[] = array('accid' => 'USLA0492', 'name' => 'Wildsville');
$city_data[] = array('accid' => 'USLA0493', 'name' => 'Wilson');
$city_data[] = array('accid' => 'USLA0494', 'name' => 'Winnfield');
$city_data[] = array('accid' => 'USLA0495', 'name' => 'Winnsboro');
$city_data[] = array('accid' => 'USLA0496', 'name' => 'Wisner');
$city_data[] = array('accid' => 'USLA0497', 'name' => 'Woodworth');
$city_data[] = array('accid' => 'USLA0498', 'name' => 'Youngsville');
$city_data[] = array('accid' => 'USLA0499', 'name' => 'Zachary');
$city_data[] = array('accid' => 'USLA0500', 'name' => 'Zwolle');

?>
