<?php

// City package for USA: Massachusetts 

$city_name = 'USA: Massachusetts';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USMA0001', 'name' => 'Abington');
$city_data[] = array('accid' => 'USMA0002', 'name' => 'Accord');
$city_data[] = array('accid' => 'USMA0003', 'name' => 'Acton');
$city_data[] = array('accid' => 'USMA0004', 'name' => 'Acushnet');
$city_data[] = array('accid' => 'USMA0005', 'name' => 'Adams');
$city_data[] = array('accid' => 'USMA0006', 'name' => 'Agawam');
$city_data[] = array('accid' => 'USMA0007', 'name' => 'Allston');
$city_data[] = array('accid' => 'USMA0008', 'name' => 'Amesbury');
$city_data[] = array('accid' => 'USMA0009', 'name' => 'Amherst');
$city_data[] = array('accid' => 'USMA0010', 'name' => 'Andover');
$city_data[] = array('accid' => 'USMA0011', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USMA0012', 'name' => 'Arlington Heights');
$city_data[] = array('accid' => 'USMA0013', 'name' => 'Ashburnham');
$city_data[] = array('accid' => 'USMA0014', 'name' => 'Ashby');
$city_data[] = array('accid' => 'USMA0015', 'name' => 'Ashfield');
$city_data[] = array('accid' => 'USMA0016', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USMA0017', 'name' => 'Ashley Falls');
$city_data[] = array('accid' => 'USMA0018', 'name' => 'Assonet');
$city_data[] = array('accid' => 'USMA0019', 'name' => 'Athol');
$city_data[] = array('accid' => 'USMA0020', 'name' => 'Attleboro');
$city_data[] = array('accid' => 'USMA0021', 'name' => 'Attleboro Falls');
$city_data[] = array('accid' => 'USMA0022', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USMA0023', 'name' => 'Auburndale');
$city_data[] = array('accid' => 'USMA0024', 'name' => 'Avon');
$city_data[] = array('accid' => 'USMA0025', 'name' => 'Ayer');
$city_data[] = array('accid' => 'USMA0026', 'name' => 'Babson Park');
$city_data[] = array('accid' => 'USMA0027', 'name' => 'Baldwinville');
$city_data[] = array('accid' => 'USMA0028', 'name' => 'Barnstable');
$city_data[] = array('accid' => 'USMA0029', 'name' => 'Barre');
$city_data[] = array('accid' => 'USMA0030', 'name' => 'Becket');
$city_data[] = array('accid' => 'USMA0031', 'name' => 'Bedford');
$city_data[] = array('accid' => 'USMA0032', 'name' => 'Belchertown');
$city_data[] = array('accid' => 'USMA0033', 'name' => 'Bellingham');
$city_data[] = array('accid' => 'USMA0034', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USMA0035', 'name' => 'Berkley');
$city_data[] = array('accid' => 'USMA0036', 'name' => 'Berkshire');
$city_data[] = array('accid' => 'USMA0038', 'name' => 'Berlin');
$city_data[] = array('accid' => 'USMA0039', 'name' => 'Bernardston');
$city_data[] = array('accid' => 'USMA0040', 'name' => 'Beverly');
$city_data[] = array('accid' => 'USMA0041', 'name' => 'Billerica');
$city_data[] = array('accid' => 'USMA0042', 'name' => 'Blackstone');
$city_data[] = array('accid' => 'USMA0043', 'name' => 'Blandford');
$city_data[] = array('accid' => 'USMA0044', 'name' => 'Bolton');
$city_data[] = array('accid' => 'USMA0045', 'name' => 'Bondsville');
$city_data[] = array('accid' => 'USMA0046', 'name' => 'Boston');
$city_data[] = array('accid' => 'USMA0047', 'name' => 'Boxborough');
$city_data[] = array('accid' => 'USMA0048', 'name' => 'Boxford');
$city_data[] = array('accid' => 'USMA0049', 'name' => 'Boylston');
$city_data[] = array('accid' => 'USMA0050', 'name' => 'Braintree');
$city_data[] = array('accid' => 'USMA0052', 'name' => 'Brewster');
$city_data[] = array('accid' => 'USMA0053', 'name' => 'Bridgewater');
$city_data[] = array('accid' => 'USMA0054', 'name' => 'Brighton');
$city_data[] = array('accid' => 'USMA0055', 'name' => 'Brimfield');
$city_data[] = array('accid' => 'USMA0056', 'name' => 'Brockton');
$city_data[] = array('accid' => 'USMA0057', 'name' => 'Brookfield');
$city_data[] = array('accid' => 'USMA0058', 'name' => 'Brookline');
$city_data[] = array('accid' => 'USMA0059', 'name' => 'Brookline Village');
$city_data[] = array('accid' => 'USMA0060', 'name' => 'Bryantville');
$city_data[] = array('accid' => 'USMA0061', 'name' => 'Buckland');
$city_data[] = array('accid' => 'USMA0062', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USMA0064', 'name' => 'Buzzards Bay');
$city_data[] = array('accid' => 'USMA0065', 'name' => 'Byfield');
$city_data[] = array('accid' => 'USMA0066', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'USMA0067', 'name' => 'Canton');
$city_data[] = array('accid' => 'USMA0069', 'name' => 'Carlisle');
$city_data[] = array('accid' => 'USMA0070', 'name' => 'Carver');
$city_data[] = array('accid' => 'USMA0071', 'name' => 'Cataumet');
$city_data[] = array('accid' => 'USMA0072', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USMA0073', 'name' => 'Charlemont');
$city_data[] = array('accid' => 'USMA0074', 'name' => 'Charlestown');
$city_data[] = array('accid' => 'USMA0075', 'name' => 'Charlton');
$city_data[] = array('accid' => 'USMA0076', 'name' => 'Charlton City');
$city_data[] = array('accid' => 'USMA0077', 'name' => 'Charlton Depot');
$city_data[] = array('accid' => 'USMA0078', 'name' => 'Chartley');
$city_data[] = array('accid' => 'USMA0079', 'name' => 'Chatham');
$city_data[] = array('accid' => 'USMA0080', 'name' => 'Chelmsford');
$city_data[] = array('accid' => 'USMA0081', 'name' => 'Chelsea');
$city_data[] = array('accid' => 'USMA0082', 'name' => 'Cherry Valley');
$city_data[] = array('accid' => 'USMA0083', 'name' => 'Cheshire');
$city_data[] = array('accid' => 'USMA0084', 'name' => 'Chester');
$city_data[] = array('accid' => 'USMA0085', 'name' => 'Chesterfield');
$city_data[] = array('accid' => 'USMA0086', 'name' => 'Chestnut Hill');
$city_data[] = array('accid' => 'USMA0087', 'name' => 'Chicopee');
$city_data[] = array('accid' => 'USMA0088', 'name' => 'Chilmark');
$city_data[] = array('accid' => 'USMA0089', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USMA0090', 'name' => 'Cohasset');
$city_data[] = array('accid' => 'USMA0091', 'name' => 'Colrain');
$city_data[] = array('accid' => 'USMA0092', 'name' => 'Concord');
$city_data[] = array('accid' => 'USMA0093', 'name' => 'Conway');
$city_data[] = array('accid' => 'USMA0094', 'name' => 'Cotuit');
$city_data[] = array('accid' => 'USMA0095', 'name' => 'Cummaquid');
$city_data[] = array('accid' => 'USMA0096', 'name' => 'Cummington');
$city_data[] = array('accid' => 'USMA0097', 'name' => 'Cuttyhunk');
$city_data[] = array('accid' => 'USMA0098', 'name' => 'Dalton');
$city_data[] = array('accid' => 'USMA0099', 'name' => 'Danvers');
$city_data[] = array('accid' => 'USMA0100', 'name' => 'Dartmouth');
$city_data[] = array('accid' => 'USMA0101', 'name' => 'Dedham');
$city_data[] = array('accid' => 'USMA0102', 'name' => 'Deerfield');
$city_data[] = array('accid' => 'USMA0103', 'name' => 'Dennis');
$city_data[] = array('accid' => 'USMA0104', 'name' => 'Dennis Port');
$city_data[] = array('accid' => 'USMA0105', 'name' => 'Dighton');
$city_data[] = array('accid' => 'USMA0106', 'name' => 'Douglas');
$city_data[] = array('accid' => 'USMA0107', 'name' => 'Dover');
$city_data[] = array('accid' => 'USMA0108', 'name' => 'Dracut');
$city_data[] = array('accid' => 'USMA0109', 'name' => 'Drury');
$city_data[] = array('accid' => 'USMA0110', 'name' => 'Dudley');
$city_data[] = array('accid' => 'USMA0111', 'name' => 'Dunstable');
$city_data[] = array('accid' => 'USMA0112', 'name' => 'Duxbury');
$city_data[] = array('accid' => 'USMA0113', 'name' => 'East Bridgewater');
$city_data[] = array('accid' => 'USMA0114', 'name' => 'East Brookfield');
$city_data[] = array('accid' => 'USMA0115', 'name' => 'East Dennis');
$city_data[] = array('accid' => 'USMA0116', 'name' => 'East Falmouth');
$city_data[] = array('accid' => 'USMA0117', 'name' => 'East Freetown');
$city_data[] = array('accid' => 'USMA0118', 'name' => 'East Longmeadow');
$city_data[] = array('accid' => 'USMA0119', 'name' => 'East Mansfield');
$city_data[] = array('accid' => 'USMA0121', 'name' => 'East Orleans');
$city_data[] = array('accid' => 'USMA0122', 'name' => 'East Otis');
$city_data[] = array('accid' => 'USMA0123', 'name' => 'East Princeton');
$city_data[] = array('accid' => 'USMA0124', 'name' => 'East Sandwich');
$city_data[] = array('accid' => 'USMA0125', 'name' => 'East Taunton');
$city_data[] = array('accid' => 'USMA0126', 'name' => 'East Templeton');
$city_data[] = array('accid' => 'USMA0127', 'name' => 'East Walpole');
$city_data[] = array('accid' => 'USMA0128', 'name' => 'East Wareham');
$city_data[] = array('accid' => 'USMA0129', 'name' => 'Eastham');
$city_data[] = array('accid' => 'USMA0130', 'name' => 'Easthampton');
$city_data[] = array('accid' => 'USMA0131', 'name' => 'Easton');
$city_data[] = array('accid' => 'USMA0132', 'name' => 'Edgartown');
$city_data[] = array('accid' => 'USMA0133', 'name' => 'Elmwood');
$city_data[] = array('accid' => 'USMA0134', 'name' => 'Erving');
$city_data[] = array('accid' => 'USMA0135', 'name' => 'Essex');
$city_data[] = array('accid' => 'USMA0136', 'name' => 'Everett');
$city_data[] = array('accid' => 'USMA0137', 'name' => 'Fairhaven');
$city_data[] = array('accid' => 'USMA0138', 'name' => 'Fall River');
$city_data[] = array('accid' => 'USMA0139', 'name' => 'Falmouth');
$city_data[] = array('accid' => 'USMA0140', 'name' => 'Fayville');
$city_data[] = array('accid' => 'USMA0141', 'name' => 'Feeding Hills');
$city_data[] = array('accid' => 'USMA0142', 'name' => 'Fiskdale');
$city_data[] = array('accid' => 'USMA0143', 'name' => 'Fitchburg');
$city_data[] = array('accid' => 'USMA0144', 'name' => 'Florence');
$city_data[] = array('accid' => 'USMA0145', 'name' => 'Forestdale');
$city_data[] = array('accid' => 'USMA0146', 'name' => 'Foxboro');
$city_data[] = array('accid' => 'USMA0147', 'name' => 'Framingham');
$city_data[] = array('accid' => 'USMA0148', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USMA0149', 'name' => 'Gardner');
$city_data[] = array('accid' => 'USMA0150', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USMA0151', 'name' => 'Gilbertville');
$city_data[] = array('accid' => 'USMA0152', 'name' => 'Glendale');
$city_data[] = array('accid' => 'USMA0153', 'name' => 'Gloucester');
$city_data[] = array('accid' => 'USMA0154', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USMA0155', 'name' => 'Grafton');
$city_data[] = array('accid' => 'USMA0156', 'name' => 'Granby');
$city_data[] = array('accid' => 'USMA0157', 'name' => 'Granville');
$city_data[] = array('accid' => 'USMA0158', 'name' => 'Great Barrington');
$city_data[] = array('accid' => 'USMA0159', 'name' => 'Green Harbor');
$city_data[] = array('accid' => 'USMA0160', 'name' => 'Greenbush');
$city_data[] = array('accid' => 'USMA0161', 'name' => 'Greenfield');
$city_data[] = array('accid' => 'USMA0162', 'name' => 'Groton');
$city_data[] = array('accid' => 'USMA0163', 'name' => 'Groveland');
$city_data[] = array('accid' => 'USMA0164', 'name' => 'Hadley');
$city_data[] = array('accid' => 'USMA0165', 'name' => 'Halifax');
$city_data[] = array('accid' => 'USMA0166', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USMA0167', 'name' => 'Hampden');
$city_data[] = array('accid' => 'USMA0168', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USMA0169', 'name' => 'Hanscom AFB');
$city_data[] = array('accid' => 'USMA0170', 'name' => 'Hanson');
$city_data[] = array('accid' => 'USMA0171', 'name' => 'Hardwick');
$city_data[] = array('accid' => 'USMA0172', 'name' => 'Harvard');
$city_data[] = array('accid' => 'USMA0173', 'name' => 'Harwich');
$city_data[] = array('accid' => 'USMA0174', 'name' => 'Harwich Port');
$city_data[] = array('accid' => 'USMA0175', 'name' => 'Hatfield');
$city_data[] = array('accid' => 'USMA0176', 'name' => 'Hathorne');
$city_data[] = array('accid' => 'USMA0177', 'name' => 'Haverhill');
$city_data[] = array('accid' => 'USMA0178', 'name' => 'Haydenville');
$city_data[] = array('accid' => 'USMA0179', 'name' => 'Heath');
$city_data[] = array('accid' => 'USMA0180', 'name' => 'Hingham');
$city_data[] = array('accid' => 'USMA0181', 'name' => 'Hinsdale');
$city_data[] = array('accid' => 'USMA0182', 'name' => 'Holbrook');
$city_data[] = array('accid' => 'USMA0183', 'name' => 'Holden');
$city_data[] = array('accid' => 'USMA0184', 'name' => 'Holland');
$city_data[] = array('accid' => 'USMA0185', 'name' => 'Holliston');
$city_data[] = array('accid' => 'USMA0186', 'name' => 'Holyoke');
$city_data[] = array('accid' => 'USMA0187', 'name' => 'Hopedale');
$city_data[] = array('accid' => 'USMA0188', 'name' => 'Hopkinton');
$city_data[] = array('accid' => 'USMA0189', 'name' => 'Housatonic');
$city_data[] = array('accid' => 'USMA0190', 'name' => 'Hubbardston');
$city_data[] = array('accid' => 'USMA0191', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USMA0192', 'name' => 'Hull');
$city_data[] = array('accid' => 'USMA0193', 'name' => 'Humarock');
$city_data[] = array('accid' => 'USMA0194', 'name' => 'Huntington');
$city_data[] = array('accid' => 'USMA0195', 'name' => 'Hyannis');
$city_data[] = array('accid' => 'USMA0196', 'name' => 'Hyannis Port');
$city_data[] = array('accid' => 'USMA0197', 'name' => 'Hyde Park');
$city_data[] = array('accid' => 'USMA0198', 'name' => 'Indian Orchard');
$city_data[] = array('accid' => 'USMA0199', 'name' => 'Ipswich');
$city_data[] = array('accid' => 'USMA0200', 'name' => 'Jamaica Plain');
$city_data[] = array('accid' => 'USMA0201', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USMA0203', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USMA0206', 'name' => 'Lake Pleasant');
$city_data[] = array('accid' => 'USMA0207', 'name' => 'Lakeville');
$city_data[] = array('accid' => 'USMA0208', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USMA0209', 'name' => 'Lanesboro');
$city_data[] = array('accid' => 'USMA0210', 'name' => 'Lawrence');
$city_data[] = array('accid' => 'USMA0211', 'name' => 'Lee');
$city_data[] = array('accid' => 'USMA0212', 'name' => 'Leeds');
$city_data[] = array('accid' => 'USMA0213', 'name' => 'Leicester');
$city_data[] = array('accid' => 'USMA0214', 'name' => 'Lenox');
$city_data[] = array('accid' => 'USMA0215', 'name' => 'Lenox Dale');
$city_data[] = array('accid' => 'USMA0216', 'name' => 'Leominster');
$city_data[] = array('accid' => 'USMA0217', 'name' => 'Leverett');
$city_data[] = array('accid' => 'USMA0218', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USMA0219', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USMA0220', 'name' => 'Linwood');
$city_data[] = array('accid' => 'USMA0221', 'name' => 'Littleton');
$city_data[] = array('accid' => 'USMA0222', 'name' => 'Longmeadow');
$city_data[] = array('accid' => 'USMA0223', 'name' => 'Lowell');
$city_data[] = array('accid' => 'USMA0224', 'name' => 'Ludlow');
$city_data[] = array('accid' => 'USMA0225', 'name' => 'Lunenburg');
$city_data[] = array('accid' => 'USMA0226', 'name' => 'Lynn');
$city_data[] = array('accid' => 'USMA0227', 'name' => 'Lynnfield');
$city_data[] = array('accid' => 'USMA0228', 'name' => 'Malden');
$city_data[] = array('accid' => 'USMA0229', 'name' => 'Manchaug');
$city_data[] = array('accid' => 'USMA0230', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USMA0231', 'name' => 'Manomet');
$city_data[] = array('accid' => 'USMA0232', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'USMA0233', 'name' => 'Marblehead');
$city_data[] = array('accid' => 'USMA0234', 'name' => 'Marion');
$city_data[] = array('accid' => 'USMA0235', 'name' => 'Marlborough');
$city_data[] = array('accid' => 'USMA0236', 'name' => 'Marshfield');
$city_data[] = array('accid' => 'USMA0237', 'name' => 'Marshfield Hills');
$city_data[] = array('accid' => 'USMA0238', 'name' => 'Marstons Mills');
$city_data[] = array('accid' => 'USMA0240', 'name' => 'Mashpee');
$city_data[] = array('accid' => 'USMA0241', 'name' => 'Mattapan');
$city_data[] = array('accid' => 'USMA0242', 'name' => 'Mattapoisett');
$city_data[] = array('accid' => 'USMA0243', 'name' => 'Maynard');
$city_data[] = array('accid' => 'USMA0244', 'name' => 'Medfield');
$city_data[] = array('accid' => 'USMA0245', 'name' => 'Medford');
$city_data[] = array('accid' => 'USMA0246', 'name' => 'Medway');
$city_data[] = array('accid' => 'USMA0247', 'name' => 'Melrose');
$city_data[] = array('accid' => 'USMA0248', 'name' => 'Mendon');
$city_data[] = array('accid' => 'USMA0249', 'name' => 'Menemsha');
$city_data[] = array('accid' => 'USMA0250', 'name' => 'Merrimac');
$city_data[] = array('accid' => 'USMA0251', 'name' => 'Methuen');
$city_data[] = array('accid' => 'USMA0252', 'name' => 'Middleboro');
$city_data[] = array('accid' => 'USMA0253', 'name' => 'Middlefield');
$city_data[] = array('accid' => 'USMA0254', 'name' => 'Middleton');
$city_data[] = array('accid' => 'USMA0255', 'name' => 'Milford');
$city_data[] = array('accid' => 'USMA0256', 'name' => 'Mill River');
$city_data[] = array('accid' => 'USMA0257', 'name' => 'Millbury');
$city_data[] = array('accid' => 'USMA0258', 'name' => 'Millis');
$city_data[] = array('accid' => 'USMA0259', 'name' => 'Millville');
$city_data[] = array('accid' => 'USMA0260', 'name' => 'Milton');
$city_data[] = array('accid' => 'USMA0261', 'name' => 'Milton Village');
$city_data[] = array('accid' => 'USMA0262', 'name' => 'Minot');
$city_data[] = array('accid' => 'USMA0263', 'name' => 'Monponsett');
$city_data[] = array('accid' => 'USMA0264', 'name' => 'Monroe Bridge');
$city_data[] = array('accid' => 'USMA0265', 'name' => 'Monson');
$city_data[] = array('accid' => 'USMA0266', 'name' => 'Montague');
$city_data[] = array('accid' => 'USMA0267', 'name' => 'Monterey');
$city_data[] = array('accid' => 'USMA0268', 'name' => 'Monument Beach');
$city_data[] = array('accid' => 'USMA0270', 'name' => 'Nahant');
$city_data[] = array('accid' => 'USMA0271', 'name' => 'Nantucket');
$city_data[] = array('accid' => 'USMA0273', 'name' => 'Natick');
$city_data[] = array('accid' => 'USMA0274', 'name' => 'Needham');
$city_data[] = array('accid' => 'USMA0275', 'name' => 'New Bedford');
$city_data[] = array('accid' => 'USMA0276', 'name' => 'New Braintree');
$city_data[] = array('accid' => 'USMA0277', 'name' => 'New Salem');
$city_data[] = array('accid' => 'USMA0278', 'name' => 'Newbury');
$city_data[] = array('accid' => 'USMA0279', 'name' => 'Newburyport');
$city_data[] = array('accid' => 'USMA0280', 'name' => 'Newton');
$city_data[] = array('accid' => 'USMA0281', 'name' => 'Norfolk');
$city_data[] = array('accid' => 'USMA0282', 'name' => 'North Adams');
$city_data[] = array('accid' => 'USMA0283', 'name' => 'North Amherst');
$city_data[] = array('accid' => 'USMA0284', 'name' => 'North Andover');
$city_data[] = array('accid' => 'USMA0285', 'name' => 'North Attleboro');
$city_data[] = array('accid' => 'USMA0286', 'name' => 'North Billerica');
$city_data[] = array('accid' => 'USMA0287', 'name' => 'North Brookfield');
$city_data[] = array('accid' => 'USMA0288', 'name' => 'North Carver');
$city_data[] = array('accid' => 'USMA0289', 'name' => 'North Chatham');
$city_data[] = array('accid' => 'USMA0290', 'name' => 'North Chelmsford');
$city_data[] = array('accid' => 'USMA0291', 'name' => 'North Dartmouth');
$city_data[] = array('accid' => 'USMA0292', 'name' => 'North Dighton');
$city_data[] = array('accid' => 'USMA0293', 'name' => 'North Eastham');
$city_data[] = array('accid' => 'USMA0294', 'name' => 'North Easton');
$city_data[] = array('accid' => 'USMA0295', 'name' => 'North Egremont');
$city_data[] = array('accid' => 'USMA0296', 'name' => 'North Falmouth');
$city_data[] = array('accid' => 'USMA0297', 'name' => 'North Grafton');
$city_data[] = array('accid' => 'USMA0298', 'name' => 'North Hatfield');
$city_data[] = array('accid' => 'USMA0299', 'name' => 'North Marshfield');
$city_data[] = array('accid' => 'USMA0300', 'name' => 'North Oxford');
$city_data[] = array('accid' => 'USMA0301', 'name' => 'North Pembroke');
$city_data[] = array('accid' => 'USMA0302', 'name' => 'North Reading');
$city_data[] = array('accid' => 'USMA0303', 'name' => 'North Scituate');
$city_data[] = array('accid' => 'USMA0304', 'name' => 'North Truro');
$city_data[] = array('accid' => 'USMA0305', 'name' => 'North Uxbridge');
$city_data[] = array('accid' => 'USMA0306', 'name' => 'Northampton');
$city_data[] = array('accid' => 'USMA0307', 'name' => 'Northborough');
$city_data[] = array('accid' => 'USMA0308', 'name' => 'Northbridge');
$city_data[] = array('accid' => 'USMA0309', 'name' => 'Northfield');
$city_data[] = array('accid' => 'USMA0310', 'name' => 'Norton');
$city_data[] = array('accid' => 'USMA0311', 'name' => 'Norwell');
$city_data[] = array('accid' => 'USMA0312', 'name' => 'Norwood');
$city_data[] = array('accid' => 'USMA0313', 'name' => 'Nutting Lake');
$city_data[] = array('accid' => 'USMA0314', 'name' => 'Oak Bluffs');
$city_data[] = array('accid' => 'USMA0315', 'name' => 'Oakham');
$city_data[] = array('accid' => 'USMA0316', 'name' => 'Ocean Bluff');
$city_data[] = array('accid' => 'USMA0317', 'name' => 'Onset');
$city_data[] = array('accid' => 'USMA0318', 'name' => 'Orange');
$city_data[] = array('accid' => 'USMA0319', 'name' => 'Orleans');
$city_data[] = array('accid' => 'USMA0320', 'name' => 'Osterville');
$city_data[] = array('accid' => 'USMA0321', 'name' => 'Otis');
$city_data[] = array('accid' => 'USMA0322', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USMA0323', 'name' => 'Palmer');
$city_data[] = array('accid' => 'USMA0324', 'name' => 'Paxton');
$city_data[] = array('accid' => 'USMA0325', 'name' => 'Peabody');
$city_data[] = array('accid' => 'USMA0326', 'name' => 'Pembroke');
$city_data[] = array('accid' => 'USMA0327', 'name' => 'Pepperell');
$city_data[] = array('accid' => 'USMA0328', 'name' => 'Petersham');
$city_data[] = array('accid' => 'USMA0329', 'name' => 'Pinehurst');
$city_data[] = array('accid' => 'USMA0330', 'name' => 'Pittsfield');
$city_data[] = array('accid' => 'USMA0331', 'name' => 'Plainfield');
$city_data[] = array('accid' => 'USMA0332', 'name' => 'Plainville');
$city_data[] = array('accid' => 'USMA0333', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USMA0334', 'name' => 'Plympton');
$city_data[] = array('accid' => 'USMA0335', 'name' => 'Pocasset');
$city_data[] = array('accid' => 'USMA0336', 'name' => 'Prides Crossing');
$city_data[] = array('accid' => 'USMA0337', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USMA0338', 'name' => 'Provincetown');
$city_data[] = array('accid' => 'USMA0339', 'name' => 'Quincy');
$city_data[] = array('accid' => 'USMA0340', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USMA0341', 'name' => 'Raynham');
$city_data[] = array('accid' => 'USMA0342', 'name' => 'Raynham Center');
$city_data[] = array('accid' => 'USMA0343', 'name' => 'Reading');
$city_data[] = array('accid' => 'USMA0344', 'name' => 'Readville');
$city_data[] = array('accid' => 'USMA0345', 'name' => 'Rehoboth');
$city_data[] = array('accid' => 'USMA0346', 'name' => 'Revere');
$city_data[] = array('accid' => 'USMA0347', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USMA0348', 'name' => 'Rochdale');
$city_data[] = array('accid' => 'USMA0349', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USMA0350', 'name' => 'Rockland');
$city_data[] = array('accid' => 'USMA0351', 'name' => 'Rockport');
$city_data[] = array('accid' => 'USMA0352', 'name' => 'Roslindale');
$city_data[] = array('accid' => 'USMA0353', 'name' => 'Rowe');
$city_data[] = array('accid' => 'USMA0354', 'name' => 'Rowley');
$city_data[] = array('accid' => 'USMA0355', 'name' => 'Royalston');
$city_data[] = array('accid' => 'USMA0356', 'name' => 'Russell');
$city_data[] = array('accid' => 'USMA0357', 'name' => 'Rutland');
$city_data[] = array('accid' => 'USMA0358', 'name' => 'Sagamore');
$city_data[] = array('accid' => 'USMA0359', 'name' => 'Sagamore Beach');
$city_data[] = array('accid' => 'USMA0360', 'name' => 'Salem');
$city_data[] = array('accid' => 'USMA0361', 'name' => 'Salisbury');
$city_data[] = array('accid' => 'USMA0362', 'name' => 'Sandisfield');
$city_data[] = array('accid' => 'USMA0363', 'name' => 'Sandwich');
$city_data[] = array('accid' => 'USMA0364', 'name' => 'Saugus');
$city_data[] = array('accid' => 'USMA0365', 'name' => 'Savoy');
$city_data[] = array('accid' => 'USMA0366', 'name' => 'Scituate');
$city_data[] = array('accid' => 'USMA0367', 'name' => 'Seekonk');
$city_data[] = array('accid' => 'USMA0368', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USMA0369', 'name' => 'Shattuckville');
$city_data[] = array('accid' => 'USMA0370', 'name' => 'Sheffield');
$city_data[] = array('accid' => 'USMA0371', 'name' => 'Shelburne Falls');
$city_data[] = array('accid' => 'USMA0372', 'name' => 'Sheldonville');
$city_data[] = array('accid' => 'USMA0373', 'name' => 'Sherborn');
$city_data[] = array('accid' => 'USMA0374', 'name' => 'Shirley');
$city_data[] = array('accid' => 'USMA0375', 'name' => 'Shrewsbury');
$city_data[] = array('accid' => 'USMA0376', 'name' => 'Shutesbury');
$city_data[] = array('accid' => 'USMA0377', 'name' => 'Siasconset');
$city_data[] = array('accid' => 'USMA0378', 'name' => 'Silver Beach');
$city_data[] = array('accid' => 'USMA0379', 'name' => 'Somerset');
$city_data[] = array('accid' => 'USMA0380', 'name' => 'Somerville');
$city_data[] = array('accid' => 'USMA0381', 'name' => 'South Barre');
$city_data[] = array('accid' => 'USMA0382', 'name' => 'South Carver');
$city_data[] = array('accid' => 'USMA0383', 'name' => 'South Chatham');
$city_data[] = array('accid' => 'USMA0384', 'name' => 'South Dartmouth');
$city_data[] = array('accid' => 'USMA0385', 'name' => 'South Deerfield');
$city_data[] = array('accid' => 'USMA0386', 'name' => 'South Dennis');
$city_data[] = array('accid' => 'USMA0387', 'name' => 'South Easton');
$city_data[] = array('accid' => 'USMA0388', 'name' => 'South Egremont');
$city_data[] = array('accid' => 'USMA0389', 'name' => 'South Grafton');
$city_data[] = array('accid' => 'USMA0390', 'name' => 'South Hadley');
$city_data[] = array('accid' => 'USMA0391', 'name' => 'South Hamilton');
$city_data[] = array('accid' => 'USMA0392', 'name' => 'South Harwich');
$city_data[] = array('accid' => 'USMA0393', 'name' => 'South Lancaster');
$city_data[] = array('accid' => 'USMA0394', 'name' => 'South Lee');
$city_data[] = array('accid' => 'USMA0395', 'name' => 'South Orleans');
$city_data[] = array('accid' => 'USMA0396', 'name' => 'South Walpole');
$city_data[] = array('accid' => 'USMA0397', 'name' => 'South Wellfleet');
$city_data[] = array('accid' => 'USMA0398', 'name' => 'South Yarmouth');
$city_data[] = array('accid' => 'USMA0399', 'name' => 'Southampton');
$city_data[] = array('accid' => 'USMA0400', 'name' => 'Southborough');
$city_data[] = array('accid' => 'USMA0401', 'name' => 'Southbridge');
$city_data[] = array('accid' => 'USMA0402', 'name' => 'Southfield');
$city_data[] = array('accid' => 'USMA0403', 'name' => 'Southwick');
$city_data[] = array('accid' => 'USMA0404', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USMA0405', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USMA0406', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USMA0407', 'name' => 'Still River');
$city_data[] = array('accid' => 'USMA0408', 'name' => 'Stockbridge');
$city_data[] = array('accid' => 'USMA0409', 'name' => 'Stoneham');
$city_data[] = array('accid' => 'USMA0410', 'name' => 'Stoughton');
$city_data[] = array('accid' => 'USMA0411', 'name' => 'Stow');
$city_data[] = array('accid' => 'USMA0412', 'name' => 'Sturbridge');
$city_data[] = array('accid' => 'USMA0413', 'name' => 'Sudbury');
$city_data[] = array('accid' => 'USMA0414', 'name' => 'Sunderland');
$city_data[] = array('accid' => 'USMA0415', 'name' => 'Sutton');
$city_data[] = array('accid' => 'USMA0416', 'name' => 'Swampscott');
$city_data[] = array('accid' => 'USMA0417', 'name' => 'Swansea');
$city_data[] = array('accid' => 'USMA0418', 'name' => 'Taunton');
$city_data[] = array('accid' => 'USMA0419', 'name' => 'Templeton');
$city_data[] = array('accid' => 'USMA0420', 'name' => 'Tewksbury');
$city_data[] = array('accid' => 'USMA0421', 'name' => 'Thorndike');
$city_data[] = array('accid' => 'USMA0422', 'name' => 'Three Rivers');
$city_data[] = array('accid' => 'USMA0423', 'name' => 'Topsfield');
$city_data[] = array('accid' => 'USMA0424', 'name' => 'Townsend');
$city_data[] = array('accid' => 'USMA0425', 'name' => 'Truro');
$city_data[] = array('accid' => 'USMA0426', 'name' => 'Turners Falls');
$city_data[] = array('accid' => 'USMA0427', 'name' => 'Tyngsboro');
$city_data[] = array('accid' => 'USMA0428', 'name' => 'Tyringham');
$city_data[] = array('accid' => 'USMA0429', 'name' => 'Upton');
$city_data[] = array('accid' => 'USMA0430', 'name' => 'Uxbridge');
$city_data[] = array('accid' => 'USMA0431', 'name' => 'Village Of Nagog Woods');
$city_data[] = array('accid' => 'USMA0432', 'name' => 'Vineyard Haven');
$city_data[] = array('accid' => 'USMA0433', 'name' => 'Waban');
$city_data[] = array('accid' => 'USMA0435', 'name' => 'Wakefield');
$city_data[] = array('accid' => 'USMA0436', 'name' => 'Wales');
$city_data[] = array('accid' => 'USMA0437', 'name' => 'Walpole');
$city_data[] = array('accid' => 'USMA0438', 'name' => 'Waltham');
$city_data[] = array('accid' => 'USMA0439', 'name' => 'Ware');
$city_data[] = array('accid' => 'USMA0440', 'name' => 'Wareham');
$city_data[] = array('accid' => 'USMA0441', 'name' => 'Warren');
$city_data[] = array('accid' => 'USMA0442', 'name' => 'Warwick');
$city_data[] = array('accid' => 'USMA0443', 'name' => 'Watertown');
$city_data[] = array('accid' => 'USMA0444', 'name' => 'Waverley');
$city_data[] = array('accid' => 'USMA0445', 'name' => 'Wayland');
$city_data[] = array('accid' => 'USMA0446', 'name' => 'Webster');
$city_data[] = array('accid' => 'USMA0447', 'name' => 'Wellesley');
$city_data[] = array('accid' => 'USMA0448', 'name' => 'Wellfleet');
$city_data[] = array('accid' => 'USMA0449', 'name' => 'Wendell');
$city_data[] = array('accid' => 'USMA0450', 'name' => 'Wendell Depot');
$city_data[] = array('accid' => 'USMA0451', 'name' => 'Wenham');
$city_data[] = array('accid' => 'USMA0452', 'name' => 'West Barnstable');
$city_data[] = array('accid' => 'USMA0453', 'name' => 'West Boxford');
$city_data[] = array('accid' => 'USMA0454', 'name' => 'West Boylston');
$city_data[] = array('accid' => 'USMA0455', 'name' => 'West Bridgewater');
$city_data[] = array('accid' => 'USMA0456', 'name' => 'West Brookfield');
$city_data[] = array('accid' => 'USMA0457', 'name' => 'West Chatham');
$city_data[] = array('accid' => 'USMA0458', 'name' => 'West Chesterfield');
$city_data[] = array('accid' => 'USMA0459', 'name' => 'West Dennis');
$city_data[] = array('accid' => 'USMA0460', 'name' => 'West Falmouth');
$city_data[] = array('accid' => 'USMA0461', 'name' => 'West Groton');
$city_data[] = array('accid' => 'USMA0462', 'name' => 'West Harwich');
$city_data[] = array('accid' => 'USMA0463', 'name' => 'West Hatfield');
$city_data[] = array('accid' => 'USMA0464', 'name' => 'West Hyannisport');
$city_data[] = array('accid' => 'USMA0465', 'name' => 'West Medford');
$city_data[] = array('accid' => 'USMA0466', 'name' => 'West Millbury');
$city_data[] = array('accid' => 'USMA0467', 'name' => 'West Newbury');
$city_data[] = array('accid' => 'USMA0468', 'name' => 'West Roxbury');
$city_data[] = array('accid' => 'USMA0469', 'name' => 'West Springfield');
$city_data[] = array('accid' => 'USMA0470', 'name' => 'West Stockbridge');
$city_data[] = array('accid' => 'USMA0471', 'name' => 'West Tisbury');
$city_data[] = array('accid' => 'USMA0472', 'name' => 'West Townsend');
$city_data[] = array('accid' => 'USMA0473', 'name' => 'West Wareham');
$city_data[] = array('accid' => 'USMA0474', 'name' => 'West Warren');
$city_data[] = array('accid' => 'USMA0475', 'name' => 'West Yarmouth');
$city_data[] = array('accid' => 'USMA0476', 'name' => 'Westborough');
$city_data[] = array('accid' => 'USMA0477', 'name' => 'Westfield');
$city_data[] = array('accid' => 'USMA0478', 'name' => 'Westford');
$city_data[] = array('accid' => 'USMA0479', 'name' => 'Westminster');
$city_data[] = array('accid' => 'USMA0480', 'name' => 'Weston');
$city_data[] = array('accid' => 'USMA0481', 'name' => 'Westport');
$city_data[] = array('accid' => 'USMA0482', 'name' => 'Westport Point');
$city_data[] = array('accid' => 'USMA0483', 'name' => 'Westwood');
$city_data[] = array('accid' => 'USMA0484', 'name' => 'Weymouth');
$city_data[] = array('accid' => 'USMA0485', 'name' => 'Whately');
$city_data[] = array('accid' => 'USMA0486', 'name' => 'Wheelwright');
$city_data[] = array('accid' => 'USMA0487', 'name' => 'White Horse Beach');
$city_data[] = array('accid' => 'USMA0488', 'name' => 'Whitinsville');
$city_data[] = array('accid' => 'USMA0489', 'name' => 'Whitman');
$city_data[] = array('accid' => 'USMA0490', 'name' => 'Wilbraham');
$city_data[] = array('accid' => 'USMA0491', 'name' => 'Williamsburg');
$city_data[] = array('accid' => 'USMA0492', 'name' => 'Williamstown');
$city_data[] = array('accid' => 'USMA0493', 'name' => 'Wilmington');
$city_data[] = array('accid' => 'USMA0494', 'name' => 'Winchendon');
$city_data[] = array('accid' => 'USMA0495', 'name' => 'Winchendon Springs');
$city_data[] = array('accid' => 'USMA0496', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USMA0497', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USMA0498', 'name' => 'Winthrop');
$city_data[] = array('accid' => 'USMA0499', 'name' => 'Woburn');
$city_data[] = array('accid' => 'USMA0500', 'name' => 'Woods Hole');
$city_data[] = array('accid' => 'USMA0501', 'name' => 'Woodville');
$city_data[] = array('accid' => 'USMA0502', 'name' => 'Worcester');
$city_data[] = array('accid' => 'USMA0503', 'name' => 'Woronoco');
$city_data[] = array('accid' => 'USMA0504', 'name' => 'Worthington');
$city_data[] = array('accid' => 'USMA0505', 'name' => 'Wrentham');
$city_data[] = array('accid' => 'USMA0506', 'name' => 'Yarmouth Port');

?>
