<?php

// City package for USA: Maryland 

$city_name = 'USA: Maryland';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USMD0001', 'name' => 'Abell');
$city_data[] = array('accid' => 'USMD0002', 'name' => 'Aberdeen');
$city_data[] = array('accid' => 'USMD0003', 'name' => 'Aberdeen Proving Ground');
$city_data[] = array('accid' => 'USMD0004', 'name' => 'Abingdon');
$city_data[] = array('accid' => 'USMD0005', 'name' => 'Accident');
$city_data[] = array('accid' => 'USMD0006', 'name' => 'Accokeek');
$city_data[] = array('accid' => 'USMD0007', 'name' => 'Adamstown');
$city_data[] = array('accid' => 'USMD0008', 'name' => 'Allen');
$city_data[] = array('accid' => 'USMD0009', 'name' => 'Andrews AFB');
$city_data[] = array('accid' => 'USMD0010', 'name' => 'Annapolis');
$city_data[] = array('accid' => 'USMD0011', 'name' => 'Annapolis Junction');
$city_data[] = array('accid' => 'USMD0012', 'name' => 'Aquasco');
$city_data[] = array('accid' => 'USMD0013', 'name' => 'Arnold');
$city_data[] = array('accid' => 'USMD0014', 'name' => 'Ashton');
$city_data[] = array('accid' => 'USMD0016', 'name' => 'Avenue');
$city_data[] = array('accid' => 'USMD0017', 'name' => 'Baldwin');
$city_data[] = array('accid' => 'USMD0018', 'name' => 'Baltimore');
$city_data[] = array('accid' => 'USMD0020', 'name' => 'Baltimore$city_data[]Inner Harbor');
$city_data[] = array('accid' => 'USMD0022', 'name' => 'Barclay');
$city_data[] = array('accid' => 'USMD0023', 'name' => 'Barnesville');
$city_data[] = array('accid' => 'USMD0024', 'name' => 'Barstow');
$city_data[] = array('accid' => 'USMD0025', 'name' => 'Barton');
$city_data[] = array('accid' => 'USMD0026', 'name' => 'Beallsville');
$city_data[] = array('accid' => 'USMD0027', 'name' => 'Bel Air');
$city_data[] = array('accid' => 'USMD0028', 'name' => 'Bel Alton');
$city_data[] = array('accid' => 'USMD0029', 'name' => 'Belcamp');
$city_data[] = array('accid' => 'USMD0030', 'name' => 'Beltsville');
$city_data[] = array('accid' => 'USMD0031', 'name' => 'Benedict');
$city_data[] = array('accid' => 'USMD0032', 'name' => 'Benson');
$city_data[] = array('accid' => 'USMD0033', 'name' => 'Berlin');
$city_data[] = array('accid' => 'USMD0034', 'name' => 'Bethesda');
$city_data[] = array('accid' => 'USMD0035', 'name' => 'Bethlehem');
$city_data[] = array('accid' => 'USMD0036', 'name' => 'Betterton');
$city_data[] = array('accid' => 'USMD0037', 'name' => 'Big Pool');
$city_data[] = array('accid' => 'USMD0038', 'name' => 'Bishopville');
$city_data[] = array('accid' => 'USMD0039', 'name' => 'Bittinger');
$city_data[] = array('accid' => 'USMD0040', 'name' => 'Bivalve');
$city_data[] = array('accid' => 'USMD0041', 'name' => 'Bladensburg');
$city_data[] = array('accid' => 'USMD0042', 'name' => 'Bloomington');
$city_data[] = array('accid' => 'USMD0043', 'name' => 'Boonsboro');
$city_data[] = array('accid' => 'USMD0044', 'name' => 'Boring');
$city_data[] = array('accid' => 'USMD0045', 'name' => 'Bowie');
$city_data[] = array('accid' => 'USMD0046', 'name' => 'Boyds');
$city_data[] = array('accid' => 'USMD0047', 'name' => 'Bozman');
$city_data[] = array('accid' => 'USMD0048', 'name' => 'Braddock Heights');
$city_data[] = array('accid' => 'USMD0049', 'name' => 'Brandywine');
$city_data[] = array('accid' => 'USMD0050', 'name' => 'Brentwood');
$city_data[] = array('accid' => 'USMD0051', 'name' => 'Brinklow');
$city_data[] = array('accid' => 'USMD0052', 'name' => 'Brookeville');
$city_data[] = array('accid' => 'USMD0053', 'name' => 'Brooklandville');
$city_data[] = array('accid' => 'USMD0054', 'name' => 'Brooklyn');
$city_data[] = array('accid' => 'USMD0055', 'name' => 'Broomes Island');
$city_data[] = array('accid' => 'USMD0056', 'name' => 'Brownsville');
$city_data[] = array('accid' => 'USMD0057', 'name' => 'Brunswick');
$city_data[] = array('accid' => 'USMD0058', 'name' => 'Bryans Road');
$city_data[] = array('accid' => 'USMD0059', 'name' => 'Bryantown');
$city_data[] = array('accid' => 'USMD0060', 'name' => 'Buckeystown');
$city_data[] = array('accid' => 'USMD0061', 'name' => 'Burkittsville');
$city_data[] = array('accid' => 'USMD0062', 'name' => 'Burtonsville');
$city_data[] = array('accid' => 'USMD0063', 'name' => 'Bushwood');
$city_data[] = array('accid' => 'USMD0064', 'name' => 'Butler');
$city_data[] = array('accid' => 'USMD0065', 'name' => 'Cabin John');
$city_data[] = array('accid' => 'USMD0066', 'name' => 'California');
$city_data[] = array('accid' => 'USMD0067', 'name' => 'Callaway');
$city_data[] = array('accid' => 'USMD0068', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'USMD0069', 'name' => 'Capitol Heights');
$city_data[] = array('accid' => 'USMD0070', 'name' => 'Cascade');
$city_data[] = array('accid' => 'USMD0071', 'name' => 'Catonsville');
$city_data[] = array('accid' => 'USMD0072', 'name' => 'Cavetown');
$city_data[] = array('accid' => 'USMD0073', 'name' => 'Cecilton');
$city_data[] = array('accid' => 'USMD0074', 'name' => 'Centreville');
$city_data[] = array('accid' => 'USMD0075', 'name' => 'Chance');
$city_data[] = array('accid' => 'USMD0076', 'name' => 'Chaptico');
$city_data[] = array('accid' => 'USMD0077', 'name' => 'Charlestown');
$city_data[] = array('accid' => 'USMD0078', 'name' => 'Charlotte Hall');
$city_data[] = array('accid' => 'USMD0079', 'name' => 'Chase');
$city_data[] = array('accid' => 'USMD0080', 'name' => 'Cheltenham');
$city_data[] = array('accid' => 'USMD0081', 'name' => 'Chesapeake Beach');
$city_data[] = array('accid' => 'USMD0082', 'name' => 'Chesapeake City');
$city_data[] = array('accid' => 'USMD0083', 'name' => 'Chester');
$city_data[] = array('accid' => 'USMD0084', 'name' => 'Chestertown');
$city_data[] = array('accid' => 'USMD0085', 'name' => 'Chevy Chase');
$city_data[] = array('accid' => 'USMD0086', 'name' => 'Chewsville');
$city_data[] = array('accid' => 'USMD0087', 'name' => 'Childs');
$city_data[] = array('accid' => 'USMD0088', 'name' => 'Church Creek');
$city_data[] = array('accid' => 'USMD0089', 'name' => 'Church Hill');
$city_data[] = array('accid' => 'USMD0090', 'name' => 'Churchton');
$city_data[] = array('accid' => 'USMD0091', 'name' => 'Churchville');
$city_data[] = array('accid' => 'USMD0092', 'name' => 'Claiborne');
$city_data[] = array('accid' => 'USMD0093', 'name' => 'Clarksburg');
$city_data[] = array('accid' => 'USMD0094', 'name' => 'Clarksville');
$city_data[] = array('accid' => 'USMD0095', 'name' => 'Clear Spring');
$city_data[] = array('accid' => 'USMD0096', 'name' => 'Clements');
$city_data[] = array('accid' => 'USMD0097', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USMD0098', 'name' => 'Cobb Island');
$city_data[] = array('accid' => 'USMD0099', 'name' => 'Cockeysville');
$city_data[] = array('accid' => 'USMD0100', 'name' => 'College Park');
$city_data[] = array('accid' => 'USMD0101', 'name' => 'Colora');
$city_data[] = array('accid' => 'USMD0102', 'name' => 'Coltons Point');
$city_data[] = array('accid' => 'USMD0103', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USMD0104', 'name' => 'Compton');
$city_data[] = array('accid' => 'USMD0105', 'name' => 'Conowingo');
$city_data[] = array('accid' => 'USMD0106', 'name' => 'Cooksville');
$city_data[] = array('accid' => 'USMD0107', 'name' => 'Cordova');
$city_data[] = array('accid' => 'USMD0108', 'name' => 'Corriganville');
$city_data[] = array('accid' => 'USMD0109', 'name' => 'Crapo');
$city_data[] = array('accid' => 'USMD0110', 'name' => 'Crisfield');
$city_data[] = array('accid' => 'USMD0111', 'name' => 'Crocheron');
$city_data[] = array('accid' => 'USMD0112', 'name' => 'Crofton');
$city_data[] = array('accid' => 'USMD0113', 'name' => 'Crownsville');
$city_data[] = array('accid' => 'USMD0114', 'name' => 'Crumpton');
$city_data[] = array('accid' => 'USMD0115', 'name' => 'Cumberland');
$city_data[] = array('accid' => 'USMD0116', 'name' => 'Curtis Bay');
$city_data[] = array('accid' => 'USMD0117', 'name' => 'Damascus');
$city_data[] = array('accid' => 'USMD0118', 'name' => 'Dameron');
$city_data[] = array('accid' => 'USMD0119', 'name' => 'Dames Quarter');
$city_data[] = array('accid' => 'USMD0120', 'name' => 'Darlington');
$city_data[] = array('accid' => 'USMD0121', 'name' => 'Davidsonville');
$city_data[] = array('accid' => 'USMD0122', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USMD0123', 'name' => 'Deal Island');
$city_data[] = array('accid' => 'USMD0124', 'name' => 'Deale');
$city_data[] = array('accid' => 'USMD0125', 'name' => 'Delmar');
$city_data[] = array('accid' => 'USMD0126', 'name' => 'Denton');
$city_data[] = array('accid' => 'USMD0127', 'name' => 'Derwood');
$city_data[] = array('accid' => 'USMD0128', 'name' => 'Dickerson');
$city_data[] = array('accid' => 'USMD0129', 'name' => 'District Heights');
$city_data[] = array('accid' => 'USMD0130', 'name' => 'Dowell');
$city_data[] = array('accid' => 'USMD0131', 'name' => 'Drayden');
$city_data[] = array('accid' => 'USMD0132', 'name' => 'Dundalk');
$city_data[] = array('accid' => 'USMD0133', 'name' => 'Dunkirk');
$city_data[] = array('accid' => 'USMD0134', 'name' => 'Earleville');
$city_data[] = array('accid' => 'USMD0135', 'name' => 'East New Market');
$city_data[] = array('accid' => 'USMD0136', 'name' => 'Easton');
$city_data[] = array('accid' => 'USMD0137', 'name' => 'Eckhart Mines');
$city_data[] = array('accid' => 'USMD0138', 'name' => 'Eden');
$city_data[] = array('accid' => 'USMD0139', 'name' => 'Edgewater');
$city_data[] = array('accid' => 'USMD0140', 'name' => 'Edgewood');
$city_data[] = array('accid' => 'USMD0141', 'name' => 'Elk Mills');
$city_data[] = array('accid' => 'USMD0142', 'name' => 'Elkridge');
$city_data[] = array('accid' => 'USMD0143', 'name' => 'Elkton');
$city_data[] = array('accid' => 'USMD0144', 'name' => 'Ellerslie');
$city_data[] = array('accid' => 'USMD0145', 'name' => 'Ellicott City');
$city_data[] = array('accid' => 'USMD0146', 'name' => 'Emmitsburg');
$city_data[] = array('accid' => 'USMD0147', 'name' => 'Essex');
$city_data[] = array('accid' => 'USMD0148', 'name' => 'Ewell');
$city_data[] = array('accid' => 'USMD0149', 'name' => 'Fairplay');
$city_data[] = array('accid' => 'USMD0150', 'name' => 'Fallston');
$city_data[] = array('accid' => 'USMD0151', 'name' => 'Faulkner');
$city_data[] = array('accid' => 'USMD0152', 'name' => 'Federalsburg');
$city_data[] = array('accid' => 'USMD0153', 'name' => 'Finksburg');
$city_data[] = array('accid' => 'USMD0154', 'name' => 'Fishing Creek');
$city_data[] = array('accid' => 'USMD0155', 'name' => 'Flintstone');
$city_data[] = array('accid' => 'USMD0156', 'name' => 'Forest Hill');
$city_data[] = array('accid' => 'USMD0157', 'name' => 'Fork');
$city_data[] = array('accid' => 'USMD0158', 'name' => 'Fort George G Meade');
$city_data[] = array('accid' => 'USMD0159', 'name' => 'Fort Howard');
$city_data[] = array('accid' => 'USMD0160', 'name' => 'Fort Washington');
$city_data[] = array('accid' => 'USMD0161', 'name' => 'Frederick');
$city_data[] = array('accid' => 'USMD0162', 'name' => 'Freeland');
$city_data[] = array('accid' => 'USMD0163', 'name' => 'Friendship');
$city_data[] = array('accid' => 'USMD0164', 'name' => 'Friendsville');
$city_data[] = array('accid' => 'USMD0165', 'name' => 'Frostburg');
$city_data[] = array('accid' => 'USMD0166', 'name' => 'Fruitland');
$city_data[] = array('accid' => 'USMD0167', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USMD0168', 'name' => 'Funkstown');
$city_data[] = array('accid' => 'USMD0169', 'name' => 'Gaithersburg');
$city_data[] = array('accid' => 'USMD0170', 'name' => 'Galena');
$city_data[] = array('accid' => 'USMD0171', 'name' => 'Galesville');
$city_data[] = array('accid' => 'USMD0172', 'name' => 'Gambrills');
$city_data[] = array('accid' => 'USMD0173', 'name' => 'Gapland');
$city_data[] = array('accid' => 'USMD0174', 'name' => 'Garrett Park');
$city_data[] = array('accid' => 'USMD0175', 'name' => 'Garrison');
$city_data[] = array('accid' => 'USMD0176', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USMD0177', 'name' => 'Germantown');
$city_data[] = array('accid' => 'USMD0178', 'name' => 'Gibson Island');
$city_data[] = array('accid' => 'USMD0179', 'name' => 'Girdletree');
$city_data[] = array('accid' => 'USMD0180', 'name' => 'Glen Arm');
$city_data[] = array('accid' => 'USMD0181', 'name' => 'Glen Burnie');
$city_data[] = array('accid' => 'USMD0182', 'name' => 'Glen Echo');
$city_data[] = array('accid' => 'USMD0183', 'name' => 'Glenelg');
$city_data[] = array('accid' => 'USMD0184', 'name' => 'Glenn Dale');
$city_data[] = array('accid' => 'USMD0185', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USMD0186', 'name' => 'Glyndon');
$city_data[] = array('accid' => 'USMD0187', 'name' => 'Goldsboro');
$city_data[] = array('accid' => 'USMD0188', 'name' => 'Grantsville');
$city_data[] = array('accid' => 'USMD0189', 'name' => 'Grasonville');
$city_data[] = array('accid' => 'USMD0190', 'name' => 'Great Mills');
$city_data[] = array('accid' => 'USMD0191', 'name' => 'Greenbelt');
$city_data[] = array('accid' => 'USMD0192', 'name' => 'Greensboro');
$city_data[] = array('accid' => 'USMD0193', 'name' => 'Gunpowder');
$city_data[] = array('accid' => 'USMD0194', 'name' => 'Gwynn Oak');
$city_data[] = array('accid' => 'USMD0195', 'name' => 'Hagerstown');
$city_data[] = array('accid' => 'USMD0196', 'name' => 'Halethorpe');
$city_data[] = array('accid' => 'USMD0197', 'name' => 'Hampstead');
$city_data[] = array('accid' => 'USMD0198', 'name' => 'Hancock');
$city_data[] = array('accid' => 'USMD0199', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USMD0200', 'name' => 'Harmans');
$city_data[] = array('accid' => 'USMD0201', 'name' => 'Harwood');
$city_data[] = array('accid' => 'USMD0202', 'name' => 'Havre de Grace');
$city_data[] = array('accid' => 'USMD0203', 'name' => 'Hebron');
$city_data[] = array('accid' => 'USMD0204', 'name' => 'Helen');
$city_data[] = array('accid' => 'USMD0205', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USMD0206', 'name' => 'Henryton');
$city_data[] = array('accid' => 'USMD0207', 'name' => 'Highland');
$city_data[] = array('accid' => 'USMD0208', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USMD0209', 'name' => 'Hollywood');
$city_data[] = array('accid' => 'USMD0210', 'name' => 'Hughesville');
$city_data[] = array('accid' => 'USMD0211', 'name' => 'Hunt Valley');
$city_data[] = array('accid' => 'USMD0212', 'name' => 'Huntingtown');
$city_data[] = array('accid' => 'USMD0213', 'name' => 'Hurlock');
$city_data[] = array('accid' => 'USMD0214', 'name' => 'Hyattsville');
$city_data[] = array('accid' => 'USMD0215', 'name' => 'Hydes');
$city_data[] = array('accid' => 'USMD0216', 'name' => 'Ijamsville');
$city_data[] = array('accid' => 'USMD0217', 'name' => 'Indian Head');
$city_data[] = array('accid' => 'USMD0218', 'name' => 'Ingleside');
$city_data[] = array('accid' => 'USMD0219', 'name' => 'Ironsides');
$city_data[] = array('accid' => 'USMD0220', 'name' => 'Issue');
$city_data[] = array('accid' => 'USMD0221', 'name' => 'Jarrettsville');
$city_data[] = array('accid' => 'USMD0222', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USMD0223', 'name' => 'Jessup');
$city_data[] = array('accid' => 'USMD0224', 'name' => 'Joppa');
$city_data[] = array('accid' => 'USMD0225', 'name' => 'Keedysville');
$city_data[] = array('accid' => 'USMD0226', 'name' => 'Kennedyville');
$city_data[] = array('accid' => 'USMD0227', 'name' => 'Kensington');
$city_data[] = array('accid' => 'USMD0228', 'name' => 'Keymar');
$city_data[] = array('accid' => 'USMD0229', 'name' => 'Kingsville');
$city_data[] = array('accid' => 'USMD0230', 'name' => 'Kitzmiller');
$city_data[] = array('accid' => 'USMD0231', 'name' => 'Knoxville');
$city_data[] = array('accid' => 'USMD0232', 'name' => 'La Plata');
$city_data[] = array('accid' => 'USMD0233', 'name' => 'Ladiesburg');
$city_data[] = array('accid' => 'USMD0234', 'name' => 'Lanham');
$city_data[] = array('accid' => 'USMD0235', 'name' => 'Laurel');
$city_data[] = array('accid' => 'USMD0236', 'name' => 'Leonardtown');
$city_data[] = array('accid' => 'USMD0237', 'name' => 'Lexington Park');
$city_data[] = array('accid' => 'USMD0238', 'name' => 'Libertytown');
$city_data[] = array('accid' => 'USMD0239', 'name' => 'Lineboro');
$city_data[] = array('accid' => 'USMD0240', 'name' => 'Linkwood');
$city_data[] = array('accid' => 'USMD0241', 'name' => 'Linthicum Heights');
$city_data[] = array('accid' => 'USMD0242', 'name' => 'Linwood');
$city_data[] = array('accid' => 'USMD0243', 'name' => 'Lisbon');
$city_data[] = array('accid' => 'USMD0244', 'name' => 'Little Orleans');
$city_data[] = array('accid' => 'USMD0245', 'name' => 'Lonaconing');
$city_data[] = array('accid' => 'USMD0246', 'name' => 'Long Green');
$city_data[] = array('accid' => 'USMD0247', 'name' => 'Lothian');
$city_data[] = array('accid' => 'USMD0248', 'name' => 'Loveville');
$city_data[] = array('accid' => 'USMD0249', 'name' => 'Luke');
$city_data[] = array('accid' => 'USMD0250', 'name' => 'Lusby');
$city_data[] = array('accid' => 'USMD0251', 'name' => 'Lutherville-Timonium');
$city_data[] = array('accid' => 'USMD0252', 'name' => 'Madison');
$city_data[] = array('accid' => 'USMD0253', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USMD0254', 'name' => 'Manokin');
$city_data[] = array('accid' => 'USMD0255', 'name' => 'Marbury');
$city_data[] = array('accid' => 'USMD0256', 'name' => 'Mardela Springs');
$city_data[] = array('accid' => 'USMD0257', 'name' => 'Marion Station');
$city_data[] = array('accid' => 'USMD0258', 'name' => 'Marriottsville');
$city_data[] = array('accid' => 'USMD0259', 'name' => 'Marydel');
$city_data[] = array('accid' => 'USMD0260', 'name' => 'Maryland Line');
$city_data[] = array('accid' => 'USMD0261', 'name' => 'Massey');
$city_data[] = array('accid' => 'USMD0262', 'name' => 'Maugansville');
$city_data[] = array('accid' => 'USMD0263', 'name' => 'Mayo');
$city_data[] = array('accid' => 'USMD0264', 'name' => 'McDaniel');
$city_data[] = array('accid' => 'USMD0265', 'name' => 'McHenry');
$city_data[] = array('accid' => 'USMD0266', 'name' => 'Mechanicsville');
$city_data[] = array('accid' => 'USMD0267', 'name' => 'Middle River');
$city_data[] = array('accid' => 'USMD0268', 'name' => 'Middletown');
$city_data[] = array('accid' => 'USMD0269', 'name' => 'Midland');
$city_data[] = array('accid' => 'USMD0270', 'name' => 'Midlothian');
$city_data[] = array('accid' => 'USMD0271', 'name' => 'Millersville');
$city_data[] = array('accid' => 'USMD0272', 'name' => 'Millington');
$city_data[] = array('accid' => 'USMD0273', 'name' => 'Monkton');
$city_data[] = array('accid' => 'USMD0274', 'name' => 'Monrovia');
$city_data[] = array('accid' => 'USMD0275', 'name' => 'Montgomery Village');
$city_data[] = array('accid' => 'USMD0276', 'name' => 'Morganza');
$city_data[] = array('accid' => 'USMD0277', 'name' => 'Mount Airy');
$city_data[] = array('accid' => 'USMD0278', 'name' => 'Mount Rainier');
$city_data[] = array('accid' => 'USMD0279', 'name' => 'Mount Savage');
$city_data[] = array('accid' => 'USMD0280', 'name' => 'Mount Victoria');
$city_data[] = array('accid' => 'USMD0281', 'name' => 'Myersville');
$city_data[] = array('accid' => 'USMD0282', 'name' => 'Nanjemoy');
$city_data[] = array('accid' => 'USMD0283', 'name' => 'Nanticoke');
$city_data[] = array('accid' => 'USMD0284', 'name' => 'Neavitt');
$city_data[] = array('accid' => 'USMD0285', 'name' => 'New Market');
$city_data[] = array('accid' => 'USMD0286', 'name' => 'New Midway');
$city_data[] = array('accid' => 'USMD0287', 'name' => 'New Windsor');
$city_data[] = array('accid' => 'USMD0288', 'name' => 'Newark');
$city_data[] = array('accid' => 'USMD0289', 'name' => 'Newburg');
$city_data[] = array('accid' => 'USMD0290', 'name' => 'Newcomb');
$city_data[] = array('accid' => 'USMD0291', 'name' => 'North Beach');
$city_data[] = array('accid' => 'USMD0292', 'name' => 'North East');
$city_data[] = array('accid' => 'USMD0293', 'name' => 'Nottingham');
$city_data[] = array('accid' => 'USMD0294', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USMD0295', 'name' => 'Ocean City');
$city_data[] = array('accid' => 'USMD0296', 'name' => 'Odenton');
$city_data[] = array('accid' => 'USMD0297', 'name' => 'Oldtown');
$city_data[] = array('accid' => 'USMD0298', 'name' => 'Olney');
$city_data[] = array('accid' => 'USMD0299', 'name' => 'Owings');
$city_data[] = array('accid' => 'USMD0300', 'name' => 'Owings Mills');
$city_data[] = array('accid' => 'USMD0301', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USMD0302', 'name' => 'Oxon Hill');
$city_data[] = array('accid' => 'USMD0303', 'name' => 'Park Hall');
$city_data[] = array('accid' => 'USMD0304', 'name' => 'Parkton');
$city_data[] = array('accid' => 'USMD0305', 'name' => 'Parkville');
$city_data[] = array('accid' => 'USMD0306', 'name' => 'Parsonsburg');
$city_data[] = array('accid' => 'USMD0307', 'name' => 'Pasadena');
$city_data[] = array('accid' => 'USMD0308', 'name' => 'Patuxent River');
$city_data[] = array('accid' => 'USMD0309', 'name' => 'Perry Hall');
$city_data[] = array('accid' => 'USMD0310', 'name' => 'Perry Point');
$city_data[] = array('accid' => 'USMD0311', 'name' => 'Perryman');
$city_data[] = array('accid' => 'USMD0312', 'name' => 'Perryville');
$city_data[] = array('accid' => 'USMD0313', 'name' => 'Phoenix');
$city_data[] = array('accid' => 'USMD0314', 'name' => 'Pikesville');
$city_data[] = array('accid' => 'USMD0315', 'name' => 'Piney Point');
$city_data[] = array('accid' => 'USMD0316', 'name' => 'Pinto');
$city_data[] = array('accid' => 'USMD0317', 'name' => 'Pittsville');
$city_data[] = array('accid' => 'USMD0318', 'name' => 'Pocomoke City');
$city_data[] = array('accid' => 'USMD0319', 'name' => 'Point Of Rocks');
$city_data[] = array('accid' => 'USMD0320', 'name' => 'Pomfret');
$city_data[] = array('accid' => 'USMD0321', 'name' => 'Poolesville');
$city_data[] = array('accid' => 'USMD0322', 'name' => 'Port Deposit');
$city_data[] = array('accid' => 'USMD0323', 'name' => 'Port Republic');
$city_data[] = array('accid' => 'USMD0324', 'name' => 'Port Tobacco');
$city_data[] = array('accid' => 'USMD0325', 'name' => 'Potomac');
$city_data[] = array('accid' => 'USMD0326', 'name' => 'Powellville');
$city_data[] = array('accid' => 'USMD0327', 'name' => 'Preston');
$city_data[] = array('accid' => 'USMD0328', 'name' => 'Prince Frederick');
$city_data[] = array('accid' => 'USMD0329', 'name' => 'Princess Anne');
$city_data[] = array('accid' => 'USMD0330', 'name' => 'Pylesville');
$city_data[] = array('accid' => 'USMD0331', 'name' => 'Quantico');
$city_data[] = array('accid' => 'USMD0332', 'name' => 'Queen Anne');
$city_data[] = array('accid' => 'USMD0333', 'name' => 'Queenstown');
$city_data[] = array('accid' => 'USMD0334', 'name' => 'Randallstown');
$city_data[] = array('accid' => 'USMD0335', 'name' => 'Rawlings');
$city_data[] = array('accid' => 'USMD0336', 'name' => 'Rehobeth');
$city_data[] = array('accid' => 'USMD0337', 'name' => 'Reisterstown');
$city_data[] = array('accid' => 'USMD0338', 'name' => 'Rhodesdale');
$city_data[] = array('accid' => 'USMD0339', 'name' => 'Riderwood');
$city_data[] = array('accid' => 'USMD0340', 'name' => 'Ridge');
$city_data[] = array('accid' => 'USMD0341', 'name' => 'Ridgely');
$city_data[] = array('accid' => 'USMD0342', 'name' => 'Rising Sun');
$city_data[] = array('accid' => 'USMD0343', 'name' => 'Riva');
$city_data[] = array('accid' => 'USMD0344', 'name' => 'Riverdale');
$city_data[] = array('accid' => 'USMD0345', 'name' => 'Rock Hall');
$city_data[] = array('accid' => 'USMD0346', 'name' => 'Rock Point');
$city_data[] = array('accid' => 'USMD0347', 'name' => 'Rockville');
$city_data[] = array('accid' => 'USMD0348', 'name' => 'Rocky Ridge');
$city_data[] = array('accid' => 'USMD0349', 'name' => 'Rohrersville');
$city_data[] = array('accid' => 'USMD0350', 'name' => 'Rosedale');
$city_data[] = array('accid' => 'USMD0351', 'name' => 'Royal Oak');
$city_data[] = array('accid' => 'USMD0352', 'name' => 'Sabillasville');
$city_data[] = array('accid' => 'USMD0353', 'name' => 'Saint Inigoes');
$city_data[] = array('accid' => 'USMD0354', 'name' => 'Saint James');
$city_data[] = array('accid' => 'USMD0355', 'name' => 'Saint Leonard');
$city_data[] = array('accid' => 'USMD0356', 'name' => 'Saint Marys City');
$city_data[] = array('accid' => 'USMD0357', 'name' => 'Saint Michaels');
$city_data[] = array('accid' => 'USMD0358', 'name' => 'Salisbury');
$city_data[] = array('accid' => 'USMD0359', 'name' => 'Sandy Spring');
$city_data[] = array('accid' => 'USMD0360', 'name' => 'Savage');
$city_data[] = array('accid' => 'USMD0361', 'name' => 'Scotland');
$city_data[] = array('accid' => 'USMD0362', 'name' => 'Secretary');
$city_data[] = array('accid' => 'USMD0363', 'name' => 'Severn');
$city_data[] = array('accid' => 'USMD0364', 'name' => 'Severna Park');
$city_data[] = array('accid' => 'USMD0365', 'name' => 'Shady Side');
$city_data[] = array('accid' => 'USMD0366', 'name' => 'Sharpsburg');
$city_data[] = array('accid' => 'USMD0367', 'name' => 'Sharptown');
$city_data[] = array('accid' => 'USMD0368', 'name' => 'Sherwood');
$city_data[] = array('accid' => 'USMD0369', 'name' => 'Showell');
$city_data[] = array('accid' => 'USMD0370', 'name' => 'Silver Spring');
$city_data[] = array('accid' => 'USMD0371', 'name' => 'Simpsonville');
$city_data[] = array('accid' => 'USMD0372', 'name' => 'Smithsburg');
$city_data[] = array('accid' => 'USMD0373', 'name' => 'Snow Hill');
$city_data[] = array('accid' => 'USMD0374', 'name' => 'Solomons');
$city_data[] = array('accid' => 'USMD0375', 'name' => 'Southern MD Facility');
$city_data[] = array('accid' => 'USMD0376', 'name' => 'Sparks Glencoe');
$city_data[] = array('accid' => 'USMD0377', 'name' => 'Sparrows Point');
$city_data[] = array('accid' => 'USMD0378', 'name' => 'Spencerville');
$city_data[] = array('accid' => 'USMD0379', 'name' => 'Spring Gap');
$city_data[] = array('accid' => 'USMD0380', 'name' => 'Stevenson');
$city_data[] = array('accid' => 'USMD0381', 'name' => 'Stevensville');
$city_data[] = array('accid' => 'USMD0382', 'name' => 'Still Pond');
$city_data[] = array('accid' => 'USMD0383', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USMD0384', 'name' => 'Street');
$city_data[] = array('accid' => 'USMD0386', 'name' => 'Sudlersville');
$city_data[] = array('accid' => 'USMD0387', 'name' => 'Suitland');
$city_data[] = array('accid' => 'USMD0388', 'name' => 'Sunderland');
$city_data[] = array('accid' => 'USMD0389', 'name' => 'Swanton');
$city_data[] = array('accid' => 'USMD0390', 'name' => 'Sykesville');
$city_data[] = array('accid' => 'USMD0391', 'name' => 'Takoma Park');
$city_data[] = array('accid' => 'USMD0392', 'name' => 'Tall Timbers');
$city_data[] = array('accid' => 'USMD0393', 'name' => 'Taneytown');
$city_data[] = array('accid' => 'USMD0394', 'name' => 'Taylors Island');
$city_data[] = array('accid' => 'USMD0395', 'name' => 'Temple Hills');
$city_data[] = array('accid' => 'USMD0396', 'name' => 'Templeville');
$city_data[] = array('accid' => 'USMD0397', 'name' => 'Thurmont');
$city_data[] = array('accid' => 'USMD0398', 'name' => 'Tilghman');
$city_data[] = array('accid' => 'USMD0399', 'name' => 'Toddville');
$city_data[] = array('accid' => 'USMD0400', 'name' => 'Towson');
$city_data[] = array('accid' => 'USMD0401', 'name' => 'Tracys Landing');
$city_data[] = array('accid' => 'USMD0402', 'name' => 'Trappe');
$city_data[] = array('accid' => 'USMD0403', 'name' => 'Tuscarora');
$city_data[] = array('accid' => 'USMD0404', 'name' => 'Tyaskin');
$city_data[] = array('accid' => 'USMD0405', 'name' => 'Tylerton');
$city_data[] = array('accid' => 'USMD0406', 'name' => 'Union Bridge');
$city_data[] = array('accid' => 'USMD0407', 'name' => 'Unionville');
$city_data[] = array('accid' => 'USMD0408', 'name' => 'Upper Fairmount');
$city_data[] = array('accid' => 'USMD0409', 'name' => 'Upper Falls');
$city_data[] = array('accid' => 'USMD0410', 'name' => 'Upper Marlboro');
$city_data[] = array('accid' => 'USMD0411', 'name' => 'Upperco');
$city_data[] = array('accid' => 'USMD0412', 'name' => 'Valley Lee');
$city_data[] = array('accid' => 'USMD0413', 'name' => 'Vienna');
$city_data[] = array('accid' => 'USMD0414', 'name' => 'Waldorf');
$city_data[] = array('accid' => 'USMD0415', 'name' => 'Walkersville');
$city_data[] = array('accid' => 'USMD0416', 'name' => 'Warwick');
$city_data[] = array('accid' => 'USMD0417', 'name' => 'Washington Grove');
$city_data[] = array('accid' => 'USMD0418', 'name' => 'Welcome');
$city_data[] = array('accid' => 'USMD0419', 'name' => 'Wenona');
$city_data[] = array('accid' => 'USMD0420', 'name' => 'West Friendship');
$city_data[] = array('accid' => 'USMD0421', 'name' => 'West River');
$city_data[] = array('accid' => 'USMD0422', 'name' => 'Westernport');
$city_data[] = array('accid' => 'USMD0423', 'name' => 'Westminster');
$city_data[] = array('accid' => 'USMD0424', 'name' => 'Westover');
$city_data[] = array('accid' => 'USMD0425', 'name' => 'Whaleyville');
$city_data[] = array('accid' => 'USMD0426', 'name' => 'White Hall');
$city_data[] = array('accid' => 'USMD0427', 'name' => 'White Marsh');
$city_data[] = array('accid' => 'USMD0428', 'name' => 'White Plains');
$city_data[] = array('accid' => 'USMD0429', 'name' => 'Whiteford');
$city_data[] = array('accid' => 'USMD0430', 'name' => 'Willards');
$city_data[] = array('accid' => 'USMD0431', 'name' => 'Williamsport');
$city_data[] = array('accid' => 'USMD0432', 'name' => 'Wingate');
$city_data[] = array('accid' => 'USMD0434', 'name' => 'Wittman');
$city_data[] = array('accid' => 'USMD0435', 'name' => 'Woodbine');
$city_data[] = array('accid' => 'USMD0436', 'name' => 'Woodsboro');
$city_data[] = array('accid' => 'USMD0437', 'name' => 'Woodstock');
$city_data[] = array('accid' => 'USMD0438', 'name' => 'Woolford');
$city_data[] = array('accid' => 'USMD0439', 'name' => 'Worton');
$city_data[] = array('accid' => 'USMD0440', 'name' => 'Wye Mills');

?>
