<?php

// City package for USA: Michigan 

$city_name = 'USA: Michigan';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USMI0001', 'name' => 'Acme');
$city_data[] = array('accid' => 'USMI0002', 'name' => 'Ada');
$city_data[] = array('accid' => 'USMI0003', 'name' => 'Addison');
$city_data[] = array('accid' => 'USMI0004', 'name' => 'Adrian');
$city_data[] = array('accid' => 'USMI0005', 'name' => 'Afton');
$city_data[] = array('accid' => 'USMI0006', 'name' => 'Ahmeek');
$city_data[] = array('accid' => 'USMI0007', 'name' => 'Akron');
$city_data[] = array('accid' => 'USMI0008', 'name' => 'Alanson');
$city_data[] = array('accid' => 'USMI0009', 'name' => 'Alba');
$city_data[] = array('accid' => 'USMI0010', 'name' => 'Albion');
$city_data[] = array('accid' => 'USMI0011', 'name' => 'Alden');
$city_data[] = array('accid' => 'USMI0012', 'name' => 'Alger');
$city_data[] = array('accid' => 'USMI0013', 'name' => 'Algonac');
$city_data[] = array('accid' => 'USMI0014', 'name' => 'Allegan');
$city_data[] = array('accid' => 'USMI0015', 'name' => 'Allen');
$city_data[] = array('accid' => 'USMI0016', 'name' => 'Allen Park');
$city_data[] = array('accid' => 'USMI0017', 'name' => 'Allendale');
$city_data[] = array('accid' => 'USMI0018', 'name' => 'Allenton');
$city_data[] = array('accid' => 'USMI0019', 'name' => 'Allouez');
$city_data[] = array('accid' => 'USMI0020', 'name' => 'Alma');
$city_data[] = array('accid' => 'USMI0021', 'name' => 'Almont');
$city_data[] = array('accid' => 'USMI0022', 'name' => 'Alpena');
$city_data[] = array('accid' => 'USMI0023', 'name' => 'Alpha');
$city_data[] = array('accid' => 'USMI0025', 'name' => 'Alto');
$city_data[] = array('accid' => 'USMI0026', 'name' => 'Amasa');
$city_data[] = array('accid' => 'USMI0027', 'name' => 'Anchorville');
$city_data[] = array('accid' => 'USMI0028', 'name' => 'Ann Arbor');
$city_data[] = array('accid' => 'USMI0029', 'name' => 'Applegate');
$city_data[] = array('accid' => 'USMI0030', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USMI0031', 'name' => 'Argyle');
$city_data[] = array('accid' => 'USMI0032', 'name' => 'Armada');
$city_data[] = array('accid' => 'USMI0033', 'name' => 'Arnold');
$city_data[] = array('accid' => 'USMI0034', 'name' => 'Ashley');
$city_data[] = array('accid' => 'USMI0035', 'name' => 'Athens');
$city_data[] = array('accid' => 'USMI0036', 'name' => 'Atlanta');
$city_data[] = array('accid' => 'USMI0037', 'name' => 'Atlantic Mine');
$city_data[] = array('accid' => 'USMI0038', 'name' => 'Atlas');
$city_data[] = array('accid' => 'USMI0039', 'name' => 'Attica');
$city_data[] = array('accid' => 'USMI0040', 'name' => 'Au Gres');
$city_data[] = array('accid' => 'USMI0041', 'name' => 'Au Train');
$city_data[] = array('accid' => 'USMI0042', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USMI0043', 'name' => 'Auburn Hills');
$city_data[] = array('accid' => 'USMI0044', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USMI0045', 'name' => 'Avoca');
$city_data[] = array('accid' => 'USMI0046', 'name' => 'Azalia');
$city_data[] = array('accid' => 'USMI0047', 'name' => 'Bad Axe');
$city_data[] = array('accid' => 'USMI0048', 'name' => 'Bailey');
$city_data[] = array('accid' => 'USMI0049', 'name' => 'Baldwin');
$city_data[] = array('accid' => 'USMI0050', 'name' => 'Bancroft');
$city_data[] = array('accid' => 'USMI0051', 'name' => 'Bangor');
$city_data[] = array('accid' => 'USMI0052', 'name' => 'Bannister');
$city_data[] = array('accid' => 'USMI0053', 'name' => 'Baraga');
$city_data[] = array('accid' => 'USMI0054', 'name' => 'Barbeau');
$city_data[] = array('accid' => 'USMI0055', 'name' => 'Bark River');
$city_data[] = array('accid' => 'USMI0056', 'name' => 'Baroda');
$city_data[] = array('accid' => 'USMI0057', 'name' => 'Barryton');
$city_data[] = array('accid' => 'USMI0058', 'name' => 'Barton City');
$city_data[] = array('accid' => 'USMI0059', 'name' => 'Bath');
$city_data[] = array('accid' => 'USMI0060', 'name' => 'Battle Creek');
$city_data[] = array('accid' => 'USMI0061', 'name' => 'Bay City');
$city_data[] = array('accid' => 'USMI0062', 'name' => 'Bay Port');
$city_data[] = array('accid' => 'USMI0063', 'name' => 'Bay Shore');
$city_data[] = array('accid' => 'USMI0064', 'name' => 'Bear Lake');
$city_data[] = array('accid' => 'USMI0065', 'name' => 'Beaver Island');
$city_data[] = array('accid' => 'USMI0066', 'name' => 'Beaverton');
$city_data[] = array('accid' => 'USMI0067', 'name' => 'Bedford');
$city_data[] = array('accid' => 'USMI0068', 'name' => 'Belding');
$city_data[] = array('accid' => 'USMI0069', 'name' => 'Bellaire');
$city_data[] = array('accid' => 'USMI0070', 'name' => 'Belleville');
$city_data[] = array('accid' => 'USMI0071', 'name' => 'Bellevue');
$city_data[] = array('accid' => 'USMI0072', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USMI0073', 'name' => 'Bentley');
$city_data[] = array('accid' => 'USMI0074', 'name' => 'Benton Harbor');
$city_data[] = array('accid' => 'USMI0075', 'name' => 'Benzonia');
$city_data[] = array('accid' => 'USMI0076', 'name' => 'Bergland');
$city_data[] = array('accid' => 'USMI0077', 'name' => 'Berkley');
$city_data[] = array('accid' => 'USMI0078', 'name' => 'Berrien Center');
$city_data[] = array('accid' => 'USMI0079', 'name' => 'Berrien Springs');
$city_data[] = array('accid' => 'USMI0080', 'name' => 'Bessemer');
$city_data[] = array('accid' => 'USMI0081', 'name' => 'Beulah');
$city_data[] = array('accid' => 'USMI0082', 'name' => 'Big Bay');
$city_data[] = array('accid' => 'USMI0084', 'name' => 'Big Rapids');
$city_data[] = array('accid' => 'USMI0085', 'name' => 'Birch Run');
$city_data[] = array('accid' => 'USMI0086', 'name' => 'Birmingham');
$city_data[] = array('accid' => 'USMI0087', 'name' => 'Bitely');
$city_data[] = array('accid' => 'USMI0088', 'name' => 'Black River');
$city_data[] = array('accid' => 'USMI0090', 'name' => 'Blanchard');
$city_data[] = array('accid' => 'USMI0091', 'name' => 'Blissfield');
$city_data[] = array('accid' => 'USMI0092', 'name' => 'Bloomfield Hills');
$city_data[] = array('accid' => 'USMI0093', 'name' => 'Bloomingdale');
$city_data[] = array('accid' => 'USMI0094', 'name' => 'Boon');
$city_data[] = array('accid' => 'USMI0095', 'name' => 'Boyne City');
$city_data[] = array('accid' => 'USMI0096', 'name' => 'Boyne Falls');
$city_data[] = array('accid' => 'USMI0099', 'name' => 'Bradley');
$city_data[] = array('accid' => 'USMI0100', 'name' => 'Branch');
$city_data[] = array('accid' => 'USMI0101', 'name' => 'Brant');
$city_data[] = array('accid' => 'USMI0102', 'name' => 'Breckenridge');
$city_data[] = array('accid' => 'USMI0103', 'name' => 'Breedsville');
$city_data[] = array('accid' => 'USMI0104', 'name' => 'Brethren');
$city_data[] = array('accid' => 'USMI0105', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USMI0106', 'name' => 'Bridgewater');
$city_data[] = array('accid' => 'USMI0107', 'name' => 'Bridgman');
$city_data[] = array('accid' => 'USMI0108', 'name' => 'Brighton');
$city_data[] = array('accid' => 'USMI0109', 'name' => 'Brimley');
$city_data[] = array('accid' => 'USMI0110', 'name' => 'Britton');
$city_data[] = array('accid' => 'USMI0111', 'name' => 'Brohman');
$city_data[] = array('accid' => 'USMI0112', 'name' => 'Bronson');
$city_data[] = array('accid' => 'USMI0113', 'name' => 'Brooklyn');
$city_data[] = array('accid' => 'USMI0114', 'name' => 'Brown City');
$city_data[] = array('accid' => 'USMI0115', 'name' => 'Bruce Crossing');
$city_data[] = array('accid' => 'USMI0116', 'name' => 'Brutus');
$city_data[] = array('accid' => 'USMI0117', 'name' => 'Buchanan');
$city_data[] = array('accid' => 'USMI0118', 'name' => 'Buckley');
$city_data[] = array('accid' => 'USMI0119', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USMI0120', 'name' => 'Burnips');
$city_data[] = array('accid' => 'USMI0121', 'name' => 'Burr Oak');
$city_data[] = array('accid' => 'USMI0122', 'name' => 'Burt');
$city_data[] = array('accid' => 'USMI0123', 'name' => 'Burt Lake');
$city_data[] = array('accid' => 'USMI0124', 'name' => 'Burton');
$city_data[] = array('accid' => 'USMI0125', 'name' => 'Byron');
$city_data[] = array('accid' => 'USMI0126', 'name' => 'Byron Center');
$city_data[] = array('accid' => 'USMI0127', 'name' => 'Cadillac');
$city_data[] = array('accid' => 'USMI0128', 'name' => 'Caledonia');
$city_data[] = array('accid' => 'USMI0129', 'name' => 'Calumet');
$city_data[] = array('accid' => 'USMI0130', 'name' => 'Camden');
$city_data[] = array('accid' => 'USMI0131', 'name' => 'Cannonsburg');
$city_data[] = array('accid' => 'USMI0133', 'name' => 'Canton');
$city_data[] = array('accid' => 'USMI0134', 'name' => 'Capac');
$city_data[] = array('accid' => 'USMI0135', 'name' => 'Carleton');
$city_data[] = array('accid' => 'USMI0136', 'name' => 'Carney');
$city_data[] = array('accid' => 'USMI0137', 'name' => 'Caro');
$city_data[] = array('accid' => 'USMI0138', 'name' => 'Carp Lake');
$city_data[] = array('accid' => 'USMI0139', 'name' => 'Carrollton');
$city_data[] = array('accid' => 'USMI0140', 'name' => 'Carson City');
$city_data[] = array('accid' => 'USMI0141', 'name' => 'Carsonville');
$city_data[] = array('accid' => 'USMI0142', 'name' => 'Casco');
$city_data[] = array('accid' => 'USMI0143', 'name' => 'Caseville');
$city_data[] = array('accid' => 'USMI0144', 'name' => 'Casnovia');
$city_data[] = array('accid' => 'USMI0145', 'name' => 'Caspian');
$city_data[] = array('accid' => 'USMI0146', 'name' => 'Cass City');
$city_data[] = array('accid' => 'USMI0147', 'name' => 'Cassopolis');
$city_data[] = array('accid' => 'USMI0148', 'name' => 'Cedar');
$city_data[] = array('accid' => 'USMI0149', 'name' => 'Cedar Lake');
$city_data[] = array('accid' => 'USMI0150', 'name' => 'Cedar River');
$city_data[] = array('accid' => 'USMI0151', 'name' => 'Cedar Springs');
$city_data[] = array('accid' => 'USMI0152', 'name' => 'Cedarville');
$city_data[] = array('accid' => 'USMI0153', 'name' => 'Cement City');
$city_data[] = array('accid' => 'USMI0154', 'name' => 'Center Line');
$city_data[] = array('accid' => 'USMI0155', 'name' => 'Central Lake');
$city_data[] = array('accid' => 'USMI0156', 'name' => 'Centreville');
$city_data[] = array('accid' => 'USMI0157', 'name' => 'Ceresco');
$city_data[] = array('accid' => 'USMI0158', 'name' => 'Champion');
$city_data[] = array('accid' => 'USMI0159', 'name' => 'Channing');
$city_data[] = array('accid' => 'USMI0160', 'name' => 'Charlevoix');
$city_data[] = array('accid' => 'USMI0161', 'name' => 'Charlotte');
$city_data[] = array('accid' => 'USMI0162', 'name' => 'Chase');
$city_data[] = array('accid' => 'USMI0163', 'name' => 'Chassell');
$city_data[] = array('accid' => 'USMI0164', 'name' => 'Chatham');
$city_data[] = array('accid' => 'USMI0165', 'name' => 'Cheboygan');
$city_data[] = array('accid' => 'USMI0166', 'name' => 'Chelsea');
$city_data[] = array('accid' => 'USMI0167', 'name' => 'Chesaning');
$city_data[] = array('accid' => 'USMI0168', 'name' => 'Chippewa Lake');
$city_data[] = array('accid' => 'USMI0169', 'name' => 'Clare');
$city_data[] = array('accid' => 'USMI0170', 'name' => 'Clarklake');
$city_data[] = array('accid' => 'USMI0171', 'name' => 'Clarkston');
$city_data[] = array('accid' => 'USMI0172', 'name' => 'Clarksville');
$city_data[] = array('accid' => 'USMI0173', 'name' => 'Clawson');
$city_data[] = array('accid' => 'USMI0174', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USMI0175', 'name' => 'Clifford');
$city_data[] = array('accid' => 'USMI0176', 'name' => 'Climax');
$city_data[] = array('accid' => 'USMI0177', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USMI0178', 'name' => 'Clinton Township');
$city_data[] = array('accid' => 'USMI0179', 'name' => 'Clio');
$city_data[] = array('accid' => 'USMI0180', 'name' => 'Cloverdale');
$city_data[] = array('accid' => 'USMI0181', 'name' => 'Cohoctah');
$city_data[] = array('accid' => 'USMI0182', 'name' => 'Coldwater');
$city_data[] = array('accid' => 'USMI0183', 'name' => 'Coleman');
$city_data[] = array('accid' => 'USMI0184', 'name' => 'Coloma');
$city_data[] = array('accid' => 'USMI0185', 'name' => 'Colon');
$city_data[] = array('accid' => 'USMI0186', 'name' => 'Columbiaville');
$city_data[] = array('accid' => 'USMI0187', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USMI0188', 'name' => 'Comins');
$city_data[] = array('accid' => 'USMI0189', 'name' => 'Commerce Township');
$city_data[] = array('accid' => 'USMI0190', 'name' => 'Comstock');
$city_data[] = array('accid' => 'USMI0191', 'name' => 'Comstock Park');
$city_data[] = array('accid' => 'USMI0192', 'name' => 'Concord');
$city_data[] = array('accid' => 'USMI0193', 'name' => 'Conklin');
$city_data[] = array('accid' => 'USMI0194', 'name' => 'Constantine');
$city_data[] = array('accid' => 'USMI0195', 'name' => 'Conway');
$city_data[] = array('accid' => 'USMI0196', 'name' => 'Cooks');
$city_data[] = array('accid' => 'USMI0197', 'name' => 'Coopersville');
$city_data[] = array('accid' => 'USMI0198', 'name' => 'Copemish');
$city_data[] = array('accid' => 'USMI0199', 'name' => 'Copper City');
$city_data[] = array('accid' => 'USMI0200', 'name' => 'Copper Harbor');
$city_data[] = array('accid' => 'USMI0201', 'name' => 'Coral');
$city_data[] = array('accid' => 'USMI0202', 'name' => 'Cornell');
$city_data[] = array('accid' => 'USMI0203', 'name' => 'Corunna');
$city_data[] = array('accid' => 'USMI0204', 'name' => 'Covert');
$city_data[] = array('accid' => 'USMI0205', 'name' => 'Covington');
$city_data[] = array('accid' => 'USMI0206', 'name' => 'Cross Village');
$city_data[] = array('accid' => 'USMI0207', 'name' => 'Croswell');
$city_data[] = array('accid' => 'USMI0208', 'name' => 'Crystal');
$city_data[] = array('accid' => 'USMI0209', 'name' => 'Crystal Falls');
$city_data[] = array('accid' => 'USMI0211', 'name' => 'Curran');
$city_data[] = array('accid' => 'USMI0212', 'name' => 'Curtis');
$city_data[] = array('accid' => 'USMI0213', 'name' => 'Custer');
$city_data[] = array('accid' => 'USMI0214', 'name' => 'Dafter');
$city_data[] = array('accid' => 'USMI0215', 'name' => 'Daggett');
$city_data[] = array('accid' => 'USMI0216', 'name' => 'Dansville');
$city_data[] = array('accid' => 'USMI0217', 'name' => 'Davisburg');
$city_data[] = array('accid' => 'USMI0218', 'name' => 'Davison');
$city_data[] = array('accid' => 'USMI0219', 'name' => 'De Tour Village');
$city_data[] = array('accid' => 'USMI0220', 'name' => 'Dearborn');
$city_data[] = array('accid' => 'USMI0221', 'name' => 'Dearborn Heights');
$city_data[] = array('accid' => 'USMI0222', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USMI0223', 'name' => 'Decker');
$city_data[] = array('accid' => 'USMI0224', 'name' => 'Deckerville');
$city_data[] = array('accid' => 'USMI0225', 'name' => 'Deerfield');
$city_data[] = array('accid' => 'USMI0226', 'name' => 'Deerton');
$city_data[] = array('accid' => 'USMI0227', 'name' => 'Deford');
$city_data[] = array('accid' => 'USMI0228', 'name' => 'Delton');
$city_data[] = array('accid' => 'USMI0229', 'name' => 'Detroit');
$city_data[] = array('accid' => 'USMI0231', 'name' => 'Dewitt');
$city_data[] = array('accid' => 'USMI0232', 'name' => 'Dexter');
$city_data[] = array('accid' => 'USMI0233', 'name' => 'Dimondale');
$city_data[] = array('accid' => 'USMI0234', 'name' => 'Dodgeville');
$city_data[] = array('accid' => 'USMI0235', 'name' => 'Dollar Bay');
$city_data[] = array('accid' => 'USMI0236', 'name' => 'Dorr');
$city_data[] = array('accid' => 'USMI0237', 'name' => 'Douglas');
$city_data[] = array('accid' => 'USMI0238', 'name' => 'Dowagiac');
$city_data[] = array('accid' => 'USMI0239', 'name' => 'Dowling');
$city_data[] = array('accid' => 'USMI0240', 'name' => 'Drayton Plains');
$city_data[] = array('accid' => 'USMI0241', 'name' => 'Drummond Island');
$city_data[] = array('accid' => 'USMI0242', 'name' => 'Dryden');
$city_data[] = array('accid' => 'USMI0243', 'name' => 'Dundee');
$city_data[] = array('accid' => 'USMI0244', 'name' => 'Durand');
$city_data[] = array('accid' => 'USMI0245', 'name' => 'Eagle');
$city_data[] = array('accid' => 'USMI0246', 'name' => 'East China');
$city_data[] = array('accid' => 'USMI0247', 'name' => 'East Jordan');
$city_data[] = array('accid' => 'USMI0248', 'name' => 'East Lansing');
$city_data[] = array('accid' => 'USMI0249', 'name' => 'East Leroy');
$city_data[] = array('accid' => 'USMI0250', 'name' => 'East Tawas');
$city_data[] = array('accid' => 'USMI0251', 'name' => 'Eastlake');
$city_data[] = array('accid' => 'USMI0252', 'name' => 'Eastpointe');
$city_data[] = array('accid' => 'USMI0253', 'name' => 'Eastport');
$city_data[] = array('accid' => 'USMI0254', 'name' => 'Eaton Rapids');
$city_data[] = array('accid' => 'USMI0255', 'name' => 'Eau Claire');
$city_data[] = array('accid' => 'USMI0256', 'name' => 'Eben Junction');
$city_data[] = array('accid' => 'USMI0257', 'name' => 'Eckerman');
$city_data[] = array('accid' => 'USMI0258', 'name' => 'Ecorse');
$city_data[] = array('accid' => 'USMI0259', 'name' => 'Edenville');
$city_data[] = array('accid' => 'USMI0260', 'name' => 'Edmore');
$city_data[] = array('accid' => 'USMI0261', 'name' => 'Edwardsburg');
$city_data[] = array('accid' => 'USMI0262', 'name' => 'Elberta');
$city_data[] = array('accid' => 'USMI0263', 'name' => 'Elk Rapids');
$city_data[] = array('accid' => 'USMI0264', 'name' => 'Elkton');
$city_data[] = array('accid' => 'USMI0265', 'name' => 'Ellsworth');
$city_data[] = array('accid' => 'USMI0266', 'name' => 'Elm Hall');
$city_data[] = array('accid' => 'USMI0267', 'name' => 'Elmira');
$city_data[] = array('accid' => 'USMI0268', 'name' => 'Elsie');
$city_data[] = array('accid' => 'USMI0269', 'name' => 'Elwell');
$city_data[] = array('accid' => 'USMI0270', 'name' => 'Emmett');
$city_data[] = array('accid' => 'USMI0271', 'name' => 'Empire');
$city_data[] = array('accid' => 'USMI0272', 'name' => 'Engadine');
$city_data[] = array('accid' => 'USMI0273', 'name' => 'Erie');
$city_data[] = array('accid' => 'USMI0274', 'name' => 'Escanaba');
$city_data[] = array('accid' => 'USMI0275', 'name' => 'Essexville');
$city_data[] = array('accid' => 'USMI0276', 'name' => 'Eureka');
$city_data[] = array('accid' => 'USMI0277', 'name' => 'Evart');
$city_data[] = array('accid' => 'USMI0278', 'name' => 'Ewen');
$city_data[] = array('accid' => 'USMI0279', 'name' => 'Fair Haven');
$city_data[] = array('accid' => 'USMI0280', 'name' => 'Fairgrove');
$city_data[] = array('accid' => 'USMI0281', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USMI0282', 'name' => 'Falmouth');
$city_data[] = array('accid' => 'USMI0283', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USMI0284', 'name' => 'Farwell');
$city_data[] = array('accid' => 'USMI0285', 'name' => 'Felch');
$city_data[] = array('accid' => 'USMI0286', 'name' => 'Fennville');
$city_data[] = array('accid' => 'USMI0287', 'name' => 'Fenton');
$city_data[] = array('accid' => 'USMI0288', 'name' => 'Fenwick');
$city_data[] = array('accid' => 'USMI0289', 'name' => 'Ferndale');
$city_data[] = array('accid' => 'USMI0290', 'name' => 'Ferrysburg');
$city_data[] = array('accid' => 'USMI0291', 'name' => 'Fife Lake');
$city_data[] = array('accid' => 'USMI0292', 'name' => 'Filer City');
$city_data[] = array('accid' => 'USMI0293', 'name' => 'Filion');
$city_data[] = array('accid' => 'USMI0294', 'name' => 'Flat Rock');
$city_data[] = array('accid' => 'USMI0295', 'name' => 'Flint');
$city_data[] = array('accid' => 'USMI0296', 'name' => 'Flushing');
$city_data[] = array('accid' => 'USMI0297', 'name' => 'Forestville');
$city_data[] = array('accid' => 'USMI0298', 'name' => 'Fort Gratiot');
$city_data[] = array('accid' => 'USMI0299', 'name' => 'Foster City');
$city_data[] = array('accid' => 'USMI0300', 'name' => 'Fostoria');
$city_data[] = array('accid' => 'USMI0301', 'name' => 'Fountain');
$city_data[] = array('accid' => 'USMI0302', 'name' => 'Fowler');
$city_data[] = array('accid' => 'USMI0303', 'name' => 'Fowlerville');
$city_data[] = array('accid' => 'USMI0304', 'name' => 'Frankenmuth');
$city_data[] = array('accid' => 'USMI0305', 'name' => 'Frankfort');
$city_data[] = array('accid' => 'USMI0306', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USMI0307', 'name' => 'Fraser');
$city_data[] = array('accid' => 'USMI0308', 'name' => 'Frederic');
$city_data[] = array('accid' => 'USMI0309', 'name' => 'Free Soil');
$city_data[] = array('accid' => 'USMI0310', 'name' => 'Freeland');
$city_data[] = array('accid' => 'USMI0311', 'name' => 'Freeport');
$city_data[] = array('accid' => 'USMI0312', 'name' => 'Fremont');
$city_data[] = array('accid' => 'USMI0313', 'name' => 'Frontier');
$city_data[] = array('accid' => 'USMI0314', 'name' => 'Fruitport');
$city_data[] = array('accid' => 'USMI0315', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USMI0316', 'name' => 'Gaastra');
$city_data[] = array('accid' => 'USMI0317', 'name' => 'Gagetown');
$city_data[] = array('accid' => 'USMI0318', 'name' => 'Gaines');
$city_data[] = array('accid' => 'USMI0319', 'name' => 'Galesburg');
$city_data[] = array('accid' => 'USMI0320', 'name' => 'Galien');
$city_data[] = array('accid' => 'USMI0321', 'name' => 'Garden');
$city_data[] = array('accid' => 'USMI0322', 'name' => 'Garden City');
$city_data[] = array('accid' => 'USMI0323', 'name' => 'Gaylord');
$city_data[] = array('accid' => 'USMI0324', 'name' => 'Genesee');
$city_data[] = array('accid' => 'USMI0325', 'name' => 'Germfask');
$city_data[] = array('accid' => 'USMI0326', 'name' => 'Gilford');
$city_data[] = array('accid' => 'USMI0327', 'name' => 'Gladstone');
$city_data[] = array('accid' => 'USMI0328', 'name' => 'Gladwin');
$city_data[] = array('accid' => 'USMI0329', 'name' => 'Glen Arbor');
$city_data[] = array('accid' => 'USMI0330', 'name' => 'Glenn');
$city_data[] = array('accid' => 'USMI0331', 'name' => 'Glennie');
$city_data[] = array('accid' => 'USMI0332', 'name' => 'Gobles');
$city_data[] = array('accid' => 'USMI0333', 'name' => 'Goetzville');
$city_data[] = array('accid' => 'USMI0334', 'name' => 'Good Hart');
$city_data[] = array('accid' => 'USMI0335', 'name' => 'Goodells');
$city_data[] = array('accid' => 'USMI0336', 'name' => 'Goodrich');
$city_data[] = array('accid' => 'USMI0337', 'name' => 'Gould City');
$city_data[] = array('accid' => 'USMI0338', 'name' => 'Gowen');
$city_data[] = array('accid' => 'USMI0339', 'name' => 'Grand Blanc');
$city_data[] = array('accid' => 'USMI0340', 'name' => 'Grand Haven');
$city_data[] = array('accid' => 'USMI0341', 'name' => 'Grand Junction');
$city_data[] = array('accid' => 'USMI0342', 'name' => 'Grand Ledge');
$city_data[] = array('accid' => 'USMI0343', 'name' => 'Grand Marais');
$city_data[] = array('accid' => 'USMI0344', 'name' => 'Grand Rapids');
$city_data[] = array('accid' => 'USMI0345', 'name' => 'Grandville');
$city_data[] = array('accid' => 'USMI0346', 'name' => 'Grant');
$city_data[] = array('accid' => 'USMI0347', 'name' => 'Grass Lake');
$city_data[] = array('accid' => 'USMI0348', 'name' => 'Grawn');
$city_data[] = array('accid' => 'USMI0349', 'name' => 'Grayling');
$city_data[] = array('accid' => 'USMI0350', 'name' => 'Greenbush');
$city_data[] = array('accid' => 'USMI0351', 'name' => 'Greenland');
$city_data[] = array('accid' => 'USMI0352', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USMI0353', 'name' => 'Gregory');
$city_data[] = array('accid' => 'USMI0354', 'name' => 'Grosse Isle');
$city_data[] = array('accid' => 'USMI0355', 'name' => 'Grosse Pointe');
$city_data[] = array('accid' => 'USMI0356', 'name' => 'Gulliver');
$city_data[] = array('accid' => 'USMI0357', 'name' => 'Gwinn');
$city_data[] = array('accid' => 'USMI0358', 'name' => 'Hadley');
$city_data[] = array('accid' => 'USMI0359', 'name' => 'Hagar Shores');
$city_data[] = array('accid' => 'USMI0360', 'name' => 'Hale');
$city_data[] = array('accid' => 'USMI0361', 'name' => 'Hamburg');
$city_data[] = array('accid' => 'USMI0362', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USMI0363', 'name' => 'Hamtramck');
$city_data[] = array('accid' => 'USMI0364', 'name' => 'Hancock');
$city_data[] = array('accid' => 'USMI0365', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USMI0366', 'name' => 'Harbert');
$city_data[] = array('accid' => 'USMI0367', 'name' => 'Harbor Beach');
$city_data[] = array('accid' => 'USMI0368', 'name' => 'Harbor Springs');
$city_data[] = array('accid' => 'USMI0369', 'name' => 'Harper Woods');
$city_data[] = array('accid' => 'USMI0370', 'name' => 'Harrietta');
$city_data[] = array('accid' => 'USMI0371', 'name' => 'Harris');
$city_data[] = array('accid' => 'USMI0372', 'name' => 'Harrison');
$city_data[] = array('accid' => 'USMI0373', 'name' => 'Harrison Township');
$city_data[] = array('accid' => 'USMI0374', 'name' => 'Harrisville');
$city_data[] = array('accid' => 'USMI0375', 'name' => 'Harsens Island');
$city_data[] = array('accid' => 'USMI0376', 'name' => 'Hart');
$city_data[] = array('accid' => 'USMI0377', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USMI0378', 'name' => 'Hartland');
$city_data[] = array('accid' => 'USMI0379', 'name' => 'Haslett');
$city_data[] = array('accid' => 'USMI0380', 'name' => 'Hastings');
$city_data[] = array('accid' => 'USMI0381', 'name' => 'Hawks');
$city_data[] = array('accid' => 'USMI0382', 'name' => 'Hazel Park');
$city_data[] = array('accid' => 'USMI0383', 'name' => 'Hemlock');
$city_data[] = array('accid' => 'USMI0384', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USMI0385', 'name' => 'Hermansville');
$city_data[] = array('accid' => 'USMI0386', 'name' => 'Herron');
$city_data[] = array('accid' => 'USMI0387', 'name' => 'Hersey');
$city_data[] = array('accid' => 'USMI0388', 'name' => 'Hesperia');
$city_data[] = array('accid' => 'USMI0389', 'name' => 'Hessel');
$city_data[] = array('accid' => 'USMI0390', 'name' => 'Hickory Corners');
$city_data[] = array('accid' => 'USMI0391', 'name' => 'Higgins Lake');
$city_data[] = array('accid' => 'USMI0392', 'name' => 'Highland');
$city_data[] = array('accid' => 'USMI0393', 'name' => 'Highland Park');
$city_data[] = array('accid' => 'USMI0394', 'name' => 'Hillman');
$city_data[] = array('accid' => 'USMI0395', 'name' => 'Hillsdale');
$city_data[] = array('accid' => 'USMI0396', 'name' => 'Holland');
$city_data[] = array('accid' => 'USMI0397', 'name' => 'Holly');
$city_data[] = array('accid' => 'USMI0398', 'name' => 'Holt');
$city_data[] = array('accid' => 'USMI0399', 'name' => 'Holton');
$city_data[] = array('accid' => 'USMI0400', 'name' => 'Homer');
$city_data[] = array('accid' => 'USMI0401', 'name' => 'Honor');
$city_data[] = array('accid' => 'USMI0402', 'name' => 'Hope');
$city_data[] = array('accid' => 'USMI0403', 'name' => 'Hopkins');
$city_data[] = array('accid' => 'USMI0404', 'name' => 'Horton');
$city_data[] = array('accid' => 'USMI0405', 'name' => 'Houghton');
$city_data[] = array('accid' => 'USMI0406', 'name' => 'Houghton Lake');
$city_data[] = array('accid' => 'USMI0407', 'name' => 'Houghton Lake Heights');
$city_data[] = array('accid' => 'USMI0408', 'name' => 'Howard City');
$city_data[] = array('accid' => 'USMI0409', 'name' => 'Howell');
$city_data[] = array('accid' => 'USMI0410', 'name' => 'Hubbard Lake');
$city_data[] = array('accid' => 'USMI0411', 'name' => 'Hubbardston');
$city_data[] = array('accid' => 'USMI0412', 'name' => 'Hubbell');
$city_data[] = array('accid' => 'USMI0413', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USMI0414', 'name' => 'Hudsonville');
$city_data[] = array('accid' => 'USMI0415', 'name' => 'Hulbert');
$city_data[] = array('accid' => 'USMI0416', 'name' => 'Huntington Woods');
$city_data[] = array('accid' => 'USMI0417', 'name' => 'Ida');
$city_data[] = array('accid' => 'USMI0418', 'name' => 'Idlewild');
$city_data[] = array('accid' => 'USMI0419', 'name' => 'Imlay City');
$city_data[] = array('accid' => 'USMI0420', 'name' => 'Indian River');
$city_data[] = array('accid' => 'USMI0422', 'name' => 'Ingalls');
$city_data[] = array('accid' => 'USMI0423', 'name' => 'Inkster');
$city_data[] = array('accid' => 'USMI0424', 'name' => 'Interlochen');
$city_data[] = array('accid' => 'USMI0425', 'name' => 'Ionia');
$city_data[] = array('accid' => 'USMI0426', 'name' => 'Iron Mountain');
$city_data[] = array('accid' => 'USMI0427', 'name' => 'Iron River');
$city_data[] = array('accid' => 'USMI0428', 'name' => 'Irons');
$city_data[] = array('accid' => 'USMI0429', 'name' => 'Ironwood');
$city_data[] = array('accid' => 'USMI0430', 'name' => 'Ishpeming');
$city_data[] = array('accid' => 'USMI0432', 'name' => 'Ithaca');
$city_data[] = array('accid' => 'USMI0433', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USMI0434', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USMI0435', 'name' => 'Jasper');
$city_data[] = array('accid' => 'USMI0436', 'name' => 'Jeddo');
$city_data[] = array('accid' => 'USMI0437', 'name' => 'Jenison');
$city_data[] = array('accid' => 'USMI0438', 'name' => 'Jerome');
$city_data[] = array('accid' => 'USMI0439', 'name' => 'Johannesburg');
$city_data[] = array('accid' => 'USMI0440', 'name' => 'Jones');
$city_data[] = array('accid' => 'USMI0441', 'name' => 'Jonesville');
$city_data[] = array('accid' => 'USMI0442', 'name' => 'Kalamazoo');
$city_data[] = array('accid' => 'USMI0443', 'name' => 'Kaleva');
$city_data[] = array('accid' => 'USMI0444', 'name' => 'Kalkaska');
$city_data[] = array('accid' => 'USMI0445', 'name' => 'Kawkawlin');
$city_data[] = array('accid' => 'USMI0446', 'name' => 'Kearsarge');
$city_data[] = array('accid' => 'USMI0447', 'name' => 'Keego Harbor');
$city_data[] = array('accid' => 'USMI0448', 'name' => 'Kendall');
$city_data[] = array('accid' => 'USMI0449', 'name' => 'Kent City');
$city_data[] = array('accid' => 'USMI0451', 'name' => 'Kewadin');
$city_data[] = array('accid' => 'USMI0452', 'name' => 'Kincheloe');
$city_data[] = array('accid' => 'USMI0453', 'name' => 'Kinde');
$city_data[] = array('accid' => 'USMI0454', 'name' => 'Kingsford');
$city_data[] = array('accid' => 'USMI0455', 'name' => 'Kingsley');
$city_data[] = array('accid' => 'USMI0456', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USMI0457', 'name' => 'Kinross');
$city_data[] = array('accid' => 'USMI0458', 'name' => 'La Salle');
$city_data[] = array('accid' => 'USMI0459', 'name' => 'Lachine');
$city_data[] = array('accid' => 'USMI0460', 'name' => 'Lacota');
$city_data[] = array('accid' => 'USMI0461', 'name' => 'Laingsburg');
$city_data[] = array('accid' => 'USMI0462', 'name' => 'Lake');
$city_data[] = array('accid' => 'USMI0463', 'name' => 'Lake Ann');
$city_data[] = array('accid' => 'USMI0464', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USMI0465', 'name' => 'Lake George');
$city_data[] = array('accid' => 'USMI0466', 'name' => 'Lake Leelanau');
$city_data[] = array('accid' => 'USMI0467', 'name' => 'Lake Linden');
$city_data[] = array('accid' => 'USMI0468', 'name' => 'Lake Odessa');
$city_data[] = array('accid' => 'USMI0469', 'name' => 'Lake Orion');
$city_data[] = array('accid' => 'USMI0470', 'name' => 'Lakeland');
$city_data[] = array('accid' => 'USMI0471', 'name' => 'Lakeside');
$city_data[] = array('accid' => 'USMI0472', 'name' => 'Lakeview');
$city_data[] = array('accid' => 'USMI0473', 'name' => 'Lakeville');
$city_data[] = array('accid' => 'USMI0474', 'name' => 'Lambertville');
$city_data[] = array('accid' => 'USMI0475', 'name' => 'Lamont');
$city_data[] = array('accid' => 'USMI0476', 'name' => 'Lanse');
$city_data[] = array('accid' => 'USMI0477', 'name' => 'Lansing');
$city_data[] = array('accid' => 'USMI0478', 'name' => 'Lapeer');
$city_data[] = array('accid' => 'USMI0479', 'name' => 'Lawrence');
$city_data[] = array('accid' => 'USMI0480', 'name' => 'Lawton');
$city_data[] = array('accid' => 'USMI0481', 'name' => 'Leland');
$city_data[] = array('accid' => 'USMI0482', 'name' => 'Lennon');
$city_data[] = array('accid' => 'USMI0483', 'name' => 'Leonard');
$city_data[] = array('accid' => 'USMI0484', 'name' => 'Leonidas');
$city_data[] = array('accid' => 'USMI0485', 'name' => 'Leroy');
$city_data[] = array('accid' => 'USMI0486', 'name' => 'Leslie');
$city_data[] = array('accid' => 'USMI0487', 'name' => 'Levering');
$city_data[] = array('accid' => 'USMI0488', 'name' => 'Lewiston');
$city_data[] = array('accid' => 'USMI0489', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USMI0490', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USMI0491', 'name' => 'Lincoln Park');
$city_data[] = array('accid' => 'USMI0492', 'name' => 'Linden');
$city_data[] = array('accid' => 'USMI0493', 'name' => 'Linwood');
$city_data[] = array('accid' => 'USMI0494', 'name' => 'Litchfield');
$city_data[] = array('accid' => 'USMI0495', 'name' => 'Little Lake');
$city_data[] = array('accid' => 'USMI0496', 'name' => 'Livonia');
$city_data[] = array('accid' => 'USMI0497', 'name' => 'Long Lake');
$city_data[] = array('accid' => 'USMI0498', 'name' => 'Loretto');
$city_data[] = array('accid' => 'USMI0499', 'name' => 'Lowell');
$city_data[] = array('accid' => 'USMI0500', 'name' => 'Ludington');
$city_data[] = array('accid' => 'USMI0501', 'name' => 'Luna Pier');
$city_data[] = array('accid' => 'USMI0502', 'name' => 'Lupton');
$city_data[] = array('accid' => 'USMI0503', 'name' => 'Luther');
$city_data[] = array('accid' => 'USMI0504', 'name' => 'Luzerne');
$city_data[] = array('accid' => 'USMI0505', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USMI0506', 'name' => 'Macatawa');
$city_data[] = array('accid' => 'USMI0507', 'name' => 'Mackinac Island');
$city_data[] = array('accid' => 'USMI0508', 'name' => 'Mackinaw City');
$city_data[] = array('accid' => 'USMI0509', 'name' => 'Macomb');
$city_data[] = array('accid' => 'USMI0510', 'name' => 'Madison Heights');
$city_data[] = array('accid' => 'USMI0511', 'name' => 'Mancelona');
$city_data[] = array('accid' => 'USMI0512', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USMI0513', 'name' => 'Manistee');
$city_data[] = array('accid' => 'USMI0514', 'name' => 'Manistique');
$city_data[] = array('accid' => 'USMI0515', 'name' => 'Manitou Beach');
$city_data[] = array('accid' => 'USMI0516', 'name' => 'Manton');
$city_data[] = array('accid' => 'USMI0517', 'name' => 'Maple City');
$city_data[] = array('accid' => 'USMI0518', 'name' => 'Maple Rapids');
$city_data[] = array('accid' => 'USMI0519', 'name' => 'Marcellus');
$city_data[] = array('accid' => 'USMI0520', 'name' => 'Marenisco');
$city_data[] = array('accid' => 'USMI0521', 'name' => 'Marine City');
$city_data[] = array('accid' => 'USMI0522', 'name' => 'Marion');
$city_data[] = array('accid' => 'USMI0523', 'name' => 'Marlette');
$city_data[] = array('accid' => 'USMI0524', 'name' => 'Marne');
$city_data[] = array('accid' => 'USMI0526', 'name' => 'Marquette Mountain Ski Area');
$city_data[] = array('accid' => 'USMI0527', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USMI0528', 'name' => 'Martin');
$city_data[] = array('accid' => 'USMI0529', 'name' => 'Marysville');
$city_data[] = array('accid' => 'USMI0530', 'name' => 'Mason');
$city_data[] = array('accid' => 'USMI0531', 'name' => 'Mass City');
$city_data[] = array('accid' => 'USMI0532', 'name' => 'Mattawan');
$city_data[] = array('accid' => 'USMI0533', 'name' => 'Maybee');
$city_data[] = array('accid' => 'USMI0534', 'name' => 'Mayfield');
$city_data[] = array('accid' => 'USMI0535', 'name' => 'Mayville');
$city_data[] = array('accid' => 'USMI0536', 'name' => 'McBain');
$city_data[] = array('accid' => 'USMI0537', 'name' => 'McBrides');
$city_data[] = array('accid' => 'USMI0538', 'name' => 'McMillan');
$city_data[] = array('accid' => 'USMI0539', 'name' => 'Mears');
$city_data[] = array('accid' => 'USMI0540', 'name' => 'Mecosta');
$city_data[] = array('accid' => 'USMI0541', 'name' => 'Melvin');
$city_data[] = array('accid' => 'USMI0542', 'name' => 'Melvindale');
$city_data[] = array('accid' => 'USMI0543', 'name' => 'Memphis');
$city_data[] = array('accid' => 'USMI0544', 'name' => 'Mendon');
$city_data[] = array('accid' => 'USMI0545', 'name' => 'Menominee');
$city_data[] = array('accid' => 'USMI0546', 'name' => 'Merrill');
$city_data[] = array('accid' => 'USMI0547', 'name' => 'Merritt');
$city_data[] = array('accid' => 'USMI0548', 'name' => 'Mesick');
$city_data[] = array('accid' => 'USMI0549', 'name' => 'Metamora');
$city_data[] = array('accid' => 'USMI0550', 'name' => 'Michigamme');
$city_data[] = array('accid' => 'USMI0551', 'name' => 'Michigan Center');
$city_data[] = array('accid' => 'USMI0552', 'name' => 'Middleton');
$city_data[] = array('accid' => 'USMI0553', 'name' => 'Middleville');
$city_data[] = array('accid' => 'USMI0554', 'name' => 'Midland');
$city_data[] = array('accid' => 'USMI0555', 'name' => 'Mikado');
$city_data[] = array('accid' => 'USMI0556', 'name' => 'Milan');
$city_data[] = array('accid' => 'USMI0557', 'name' => 'Milford');
$city_data[] = array('accid' => 'USMI0558', 'name' => 'Millersburg');
$city_data[] = array('accid' => 'USMI0559', 'name' => 'Millington');
$city_data[] = array('accid' => 'USMI0560', 'name' => 'Minden City');
$city_data[] = array('accid' => 'USMI0561', 'name' => 'Mio');
$city_data[] = array('accid' => 'USMI0562', 'name' => 'Mohawk');
$city_data[] = array('accid' => 'USMI0563', 'name' => 'Moline');
$city_data[] = array('accid' => 'USMI0564', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USMI0565', 'name' => 'Montague');
$city_data[] = array('accid' => 'USMI0566', 'name' => 'Montgomery');
$city_data[] = array('accid' => 'USMI0567', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USMI0568', 'name' => 'Moran');
$city_data[] = array('accid' => 'USMI0569', 'name' => 'Morenci');
$city_data[] = array('accid' => 'USMI0570', 'name' => 'Morley');
$city_data[] = array('accid' => 'USMI0571', 'name' => 'Morrice');
$city_data[] = array('accid' => 'USMI0572', 'name' => 'Moscow');
$city_data[] = array('accid' => 'USMI0573', 'name' => 'Mosherville');
$city_data[] = array('accid' => 'USMI0575', 'name' => 'Mount Clemens');
$city_data[] = array('accid' => 'USMI0576', 'name' => 'Mount Morris');
$city_data[] = array('accid' => 'USMI0577', 'name' => 'Mount Pleasant');
$city_data[] = array('accid' => 'USMI0578', 'name' => 'Muir');
$city_data[] = array('accid' => 'USMI0579', 'name' => 'Mullett Lake');
$city_data[] = array('accid' => 'USMI0580', 'name' => 'Mulliken');
$city_data[] = array('accid' => 'USMI0581', 'name' => 'Munger');
$city_data[] = array('accid' => 'USMI0582', 'name' => 'Munising');
$city_data[] = array('accid' => 'USMI0583', 'name' => 'Munith');
$city_data[] = array('accid' => 'USMI0584', 'name' => 'Muskegon');
$city_data[] = array('accid' => 'USMI0585', 'name' => 'Nadeau');
$city_data[] = array('accid' => 'USMI0586', 'name' => 'Nahma');
$city_data[] = array('accid' => 'USMI0587', 'name' => 'Napoleon');
$city_data[] = array('accid' => 'USMI0588', 'name' => 'Nashville');
$city_data[] = array('accid' => 'USMI0589', 'name' => 'National City');
$city_data[] = array('accid' => 'USMI0590', 'name' => 'National Mine');
$city_data[] = array('accid' => 'USMI0591', 'name' => 'Naubinway');
$city_data[] = array('accid' => 'USMI0592', 'name' => 'Nazareth');
$city_data[] = array('accid' => 'USMI0593', 'name' => 'Negaunee');
$city_data[] = array('accid' => 'USMI0594', 'name' => 'New Baltimore');
$city_data[] = array('accid' => 'USMI0595', 'name' => 'New Boston');
$city_data[] = array('accid' => 'USMI0596', 'name' => 'New Buffalo');
$city_data[] = array('accid' => 'USMI0597', 'name' => 'New Era');
$city_data[] = array('accid' => 'USMI0598', 'name' => 'New Haven');
$city_data[] = array('accid' => 'USMI0599', 'name' => 'New Hudson');
$city_data[] = array('accid' => 'USMI0600', 'name' => 'New Lothrop');
$city_data[] = array('accid' => 'USMI0601', 'name' => 'New Troy');
$city_data[] = array('accid' => 'USMI0602', 'name' => 'Newaygo');
$city_data[] = array('accid' => 'USMI0603', 'name' => 'Newberry');
$city_data[] = array('accid' => 'USMI0604', 'name' => 'Newport');
$city_data[] = array('accid' => 'USMI0605', 'name' => 'Niles');
$city_data[] = array('accid' => 'USMI0606', 'name' => 'Nisula');
$city_data[] = array('accid' => 'USMI0607', 'name' => 'North Adams');
$city_data[] = array('accid' => 'USMI0608', 'name' => 'North Branch');
$city_data[] = array('accid' => 'USMI0609', 'name' => 'North Star');
$city_data[] = array('accid' => 'USMI0610', 'name' => 'North Street');
$city_data[] = array('accid' => 'USMI0612', 'name' => 'Northport');
$city_data[] = array('accid' => 'USMI0613', 'name' => 'Northville');
$city_data[] = array('accid' => 'USMI0614', 'name' => 'Norvell');
$city_data[] = array('accid' => 'USMI0615', 'name' => 'Norway');
$city_data[] = array('accid' => 'USMI0616', 'name' => 'Nottawa');
$city_data[] = array('accid' => 'USMI0617', 'name' => 'Novi');
$city_data[] = array('accid' => 'USMI0619', 'name' => 'Nunica');
$city_data[] = array('accid' => 'USMI0620', 'name' => 'Oak Grove');
$city_data[] = array('accid' => 'USMI0621', 'name' => 'Oak Park');
$city_data[] = array('accid' => 'USMI0623', 'name' => 'Oakley');
$city_data[] = array('accid' => 'USMI0624', 'name' => 'Oden');
$city_data[] = array('accid' => 'USMI0625', 'name' => 'Okemos');
$city_data[] = array('accid' => 'USMI0626', 'name' => 'Old Mission');
$city_data[] = array('accid' => 'USMI0627', 'name' => 'Olivet');
$city_data[] = array('accid' => 'USMI0628', 'name' => 'Omena');
$city_data[] = array('accid' => 'USMI0629', 'name' => 'Omer');
$city_data[] = array('accid' => 'USMI0630', 'name' => 'Onaway');
$city_data[] = array('accid' => 'USMI0631', 'name' => 'Onekama');
$city_data[] = array('accid' => 'USMI0632', 'name' => 'Onondaga');
$city_data[] = array('accid' => 'USMI0633', 'name' => 'Onsted');
$city_data[] = array('accid' => 'USMI0634', 'name' => 'Ontonagon');
$city_data[] = array('accid' => 'USMI0635', 'name' => 'Orleans');
$city_data[] = array('accid' => 'USMI0636', 'name' => 'Ortonville');
$city_data[] = array('accid' => 'USMI0637', 'name' => 'Oscoda');
$city_data[] = array('accid' => 'USMI0638', 'name' => 'Oshtemo');
$city_data[] = array('accid' => 'USMI0639', 'name' => 'Osseo');
$city_data[] = array('accid' => 'USMI0640', 'name' => 'Ossineke');
$city_data[] = array('accid' => 'USMI0641', 'name' => 'Otisville');
$city_data[] = array('accid' => 'USMI0642', 'name' => 'Otsego');
$city_data[] = array('accid' => 'USMI0643', 'name' => 'Ottawa Lake');
$city_data[] = array('accid' => 'USMI0644', 'name' => 'Otter Lake');
$city_data[] = array('accid' => 'USMI0645', 'name' => 'Ovid');
$city_data[] = array('accid' => 'USMI0646', 'name' => 'Owendale');
$city_data[] = array('accid' => 'USMI0647', 'name' => 'Owosso');
$city_data[] = array('accid' => 'USMI0648', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USMI0649', 'name' => 'Painesdale');
$city_data[] = array('accid' => 'USMI0650', 'name' => 'Palmer');
$city_data[] = array('accid' => 'USMI0651', 'name' => 'Palms');
$city_data[] = array('accid' => 'USMI0652', 'name' => 'Palmyra');
$city_data[] = array('accid' => 'USMI0653', 'name' => 'Palo');
$city_data[] = array('accid' => 'USMI0654', 'name' => 'Paradise');
$city_data[] = array('accid' => 'USMI0655', 'name' => 'Paris');
$city_data[] = array('accid' => 'USMI0656', 'name' => 'Parma');
$city_data[] = array('accid' => 'USMI0657', 'name' => 'Paw Paw');
$city_data[] = array('accid' => 'USMI0658', 'name' => 'Peck');
$city_data[] = array('accid' => 'USMI0659', 'name' => 'Pelkie');
$city_data[] = array('accid' => 'USMI0660', 'name' => 'Pellston');
$city_data[] = array('accid' => 'USMI0661', 'name' => 'Pentwater');
$city_data[] = array('accid' => 'USMI0662', 'name' => 'Perkins');
$city_data[] = array('accid' => 'USMI0663', 'name' => 'Perrinton');
$city_data[] = array('accid' => 'USMI0664', 'name' => 'Perronville');
$city_data[] = array('accid' => 'USMI0665', 'name' => 'Perry');
$city_data[] = array('accid' => 'USMI0666', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USMI0667', 'name' => 'Petoskey');
$city_data[] = array('accid' => 'USMI0668', 'name' => 'Pewamo');
$city_data[] = array('accid' => 'USMI0669', 'name' => 'Pickford');
$city_data[] = array('accid' => 'USMI0670', 'name' => 'Pierson');
$city_data[] = array('accid' => 'USMI0671', 'name' => 'Pigeon');
$city_data[] = array('accid' => 'USMI0672', 'name' => 'Pinckney');
$city_data[] = array('accid' => 'USMI0673', 'name' => 'Pinconning');
$city_data[] = array('accid' => 'USMI0674', 'name' => 'Pittsford');
$city_data[] = array('accid' => 'USMI0675', 'name' => 'Plainwell');
$city_data[] = array('accid' => 'USMI0676', 'name' => 'Pleasant Lake');
$city_data[] = array('accid' => 'USMI0677', 'name' => 'Pleasant Ridge');
$city_data[] = array('accid' => 'USMI0678', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USMI0679', 'name' => 'Pointe Aux Pins');
$city_data[] = array('accid' => 'USMI0680', 'name' => 'Pompeii');
$city_data[] = array('accid' => 'USMI0681', 'name' => 'Pontiac');
$city_data[] = array('accid' => 'USMI0682', 'name' => 'Port Austin');
$city_data[] = array('accid' => 'USMI0683', 'name' => 'Port Hope');
$city_data[] = array('accid' => 'USMI0684', 'name' => 'Port Huron');
$city_data[] = array('accid' => 'USMI0685', 'name' => 'Port Sanilac');
$city_data[] = array('accid' => 'USMI0686', 'name' => 'Portage');
$city_data[] = array('accid' => 'USMI0687', 'name' => 'Portland');
$city_data[] = array('accid' => 'USMI0688', 'name' => 'Posen');
$city_data[] = array('accid' => 'USMI0689', 'name' => 'Potterville');
$city_data[] = array('accid' => 'USMI0690', 'name' => 'Powers');
$city_data[] = array('accid' => 'USMI0691', 'name' => 'Prescott');
$city_data[] = array('accid' => 'USMI0692', 'name' => 'Presque Isle');
$city_data[] = array('accid' => 'USMI0693', 'name' => 'Prudenville');
$city_data[] = array('accid' => 'USMI0694', 'name' => 'Pullman');
$city_data[] = array('accid' => 'USMI0695', 'name' => 'Quincy');
$city_data[] = array('accid' => 'USMI0696', 'name' => 'Quinnesec');
$city_data[] = array('accid' => 'USMI0697', 'name' => 'Ralph');
$city_data[] = array('accid' => 'USMI0698', 'name' => 'Ramsay');
$city_data[] = array('accid' => 'USMI0699', 'name' => 'Rapid City');
$city_data[] = array('accid' => 'USMI0700', 'name' => 'Rapid River');
$city_data[] = array('accid' => 'USMI0701', 'name' => 'Ravenna');
$city_data[] = array('accid' => 'USMI0702', 'name' => 'Ray');
$city_data[] = array('accid' => 'USMI0703', 'name' => 'Reading');
$city_data[] = array('accid' => 'USMI0704', 'name' => 'Redford');
$city_data[] = array('accid' => 'USMI0705', 'name' => 'Reed City');
$city_data[] = array('accid' => 'USMI0706', 'name' => 'Reese');
$city_data[] = array('accid' => 'USMI0707', 'name' => 'Remus');
$city_data[] = array('accid' => 'USMI0708', 'name' => 'Republic');
$city_data[] = array('accid' => 'USMI0709', 'name' => 'Rhodes');
$city_data[] = array('accid' => 'USMI0710', 'name' => 'Richland');
$city_data[] = array('accid' => 'USMI0711', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USMI0712', 'name' => 'Richville');
$city_data[] = array('accid' => 'USMI0713', 'name' => 'Ridgeway');
$city_data[] = array('accid' => 'USMI0714', 'name' => 'Riga');
$city_data[] = array('accid' => 'USMI0715', 'name' => 'River Rouge');
$city_data[] = array('accid' => 'USMI0716', 'name' => 'Riverdale');
$city_data[] = array('accid' => 'USMI0717', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USMI0719', 'name' => 'Rives Junction');
$city_data[] = array('accid' => 'USMI0720', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USMI0721', 'name' => 'Rock');
$city_data[] = array('accid' => 'USMI0722', 'name' => 'Rockford');
$city_data[] = array('accid' => 'USMI0723', 'name' => 'Rockland');
$city_data[] = array('accid' => 'USMI0724', 'name' => 'Rockwood');
$city_data[] = array('accid' => 'USMI0725', 'name' => 'Rodney');
$city_data[] = array('accid' => 'USMI0726', 'name' => 'Rogers City');
$city_data[] = array('accid' => 'USMI0727', 'name' => 'Rollin');
$city_data[] = array('accid' => 'USMI0728', 'name' => 'Romeo');
$city_data[] = array('accid' => 'USMI0729', 'name' => 'Romulus');
$city_data[] = array('accid' => 'USMI0730', 'name' => 'Roscommon');
$city_data[] = array('accid' => 'USMI0731', 'name' => 'Rose City');
$city_data[] = array('accid' => 'USMI0732', 'name' => 'Rosebush');
$city_data[] = array('accid' => 'USMI0733', 'name' => 'Roseville');
$city_data[] = array('accid' => 'USMI0734', 'name' => 'Rothbury');
$city_data[] = array('accid' => 'USMI0735', 'name' => 'Royal Oak');
$city_data[] = array('accid' => 'USMI0736', 'name' => 'Rudyard');
$city_data[] = array('accid' => 'USMI0737', 'name' => 'Rumely');
$city_data[] = array('accid' => 'USMI0738', 'name' => 'Ruth');
$city_data[] = array('accid' => 'USMI0739', 'name' => 'Saginaw');
$city_data[] = array('accid' => 'USMI0740', 'name' => 'Sagola');
$city_data[] = array('accid' => 'USMI0741', 'name' => 'Saint Charles');
$city_data[] = array('accid' => 'USMI0742', 'name' => 'Saint Clair');
$city_data[] = array('accid' => 'USMI0743', 'name' => 'Saint Clair Shores');
$city_data[] = array('accid' => 'USMI0744', 'name' => 'Saint Helen');
$city_data[] = array('accid' => 'USMI0745', 'name' => 'Saint Ignace');
$city_data[] = array('accid' => 'USMI0746', 'name' => 'Saint Johns');
$city_data[] = array('accid' => 'USMI0747', 'name' => 'Saint Joseph');
$city_data[] = array('accid' => 'USMI0748', 'name' => 'Saint Louis');
$city_data[] = array('accid' => 'USMI0749', 'name' => 'Salem');
$city_data[] = array('accid' => 'USMI0750', 'name' => 'Saline');
$city_data[] = array('accid' => 'USMI0751', 'name' => 'Samaria');
$city_data[] = array('accid' => 'USMI0752', 'name' => 'Sand Creek');
$city_data[] = array('accid' => 'USMI0753', 'name' => 'Sand Lake');
$city_data[] = array('accid' => 'USMI0754', 'name' => 'Sandusky');
$city_data[] = array('accid' => 'USMI0755', 'name' => 'Sanford');
$city_data[] = array('accid' => 'USMI0756', 'name' => 'Saranac');
$city_data[] = array('accid' => 'USMI0757', 'name' => 'Saugatuck');
$city_data[] = array('accid' => 'USMI0758', 'name' => 'Sault Ste Marie');
$city_data[] = array('accid' => 'USMI0759', 'name' => 'Sawyer');
$city_data[] = array('accid' => 'USMI0760', 'name' => 'Schoolcraft');
$city_data[] = array('accid' => 'USMI0761', 'name' => 'Scotts');
$city_data[] = array('accid' => 'USMI0762', 'name' => 'Scottville');
$city_data[] = array('accid' => 'USMI0763', 'name' => 'Sears');
$city_data[] = array('accid' => 'USMI0764', 'name' => 'Sebewaing');
$city_data[] = array('accid' => 'USMI0765', 'name' => 'Seneca');
$city_data[] = array('accid' => 'USMI0766', 'name' => 'Seney');
$city_data[] = array('accid' => 'USMI0768', 'name' => 'Shaftsburg');
$city_data[] = array('accid' => 'USMI0770', 'name' => 'Shelby');
$city_data[] = array('accid' => 'USMI0771', 'name' => 'Shelbyville');
$city_data[] = array('accid' => 'USMI0772', 'name' => 'Shepherd');
$city_data[] = array('accid' => 'USMI0773', 'name' => 'Sheridan');
$city_data[] = array('accid' => 'USMI0774', 'name' => 'Sherwood');
$city_data[] = array('accid' => 'USMI0775', 'name' => 'Shingleton');
$city_data[] = array('accid' => 'USMI0776', 'name' => 'Sidnaw');
$city_data[] = array('accid' => 'USMI0777', 'name' => 'Sidney');
$city_data[] = array('accid' => 'USMI0778', 'name' => 'Silverwood');
$city_data[] = array('accid' => 'USMI0779', 'name' => 'Six Lakes');
$city_data[] = array('accid' => 'USMI0780', 'name' => 'Skandia');
$city_data[] = array('accid' => 'USMI0781', 'name' => 'Skanee');
$city_data[] = array('accid' => 'USMI0782', 'name' => 'Smiths Creek');
$city_data[] = array('accid' => 'USMI0783', 'name' => 'Smyrna');
$city_data[] = array('accid' => 'USMI0784', 'name' => 'Snover');
$city_data[] = array('accid' => 'USMI0785', 'name' => 'Sodus');
$city_data[] = array('accid' => 'USMI0786', 'name' => 'Somerset');
$city_data[] = array('accid' => 'USMI0787', 'name' => 'Somerset Center');
$city_data[] = array('accid' => 'USMI0788', 'name' => 'South Boardman');
$city_data[] = array('accid' => 'USMI0789', 'name' => 'South Branch');
$city_data[] = array('accid' => 'USMI0790', 'name' => 'South Haven');
$city_data[] = array('accid' => 'USMI0791', 'name' => 'South Lyon');
$city_data[] = array('accid' => 'USMI0792', 'name' => 'South Range');
$city_data[] = array('accid' => 'USMI0793', 'name' => 'South Rockwood');
$city_data[] = array('accid' => 'USMI0794', 'name' => 'Southfield');
$city_data[] = array('accid' => 'USMI0795', 'name' => 'Southgate');
$city_data[] = array('accid' => 'USMI0796', 'name' => 'Spalding');
$city_data[] = array('accid' => 'USMI0797', 'name' => 'Sparta');
$city_data[] = array('accid' => 'USMI0798', 'name' => 'Spring Arbor');
$city_data[] = array('accid' => 'USMI0799', 'name' => 'Spring Lake');
$city_data[] = array('accid' => 'USMI0800', 'name' => 'Springport');
$city_data[] = array('accid' => 'USMI0801', 'name' => 'Spruce');
$city_data[] = array('accid' => 'USMI0802', 'name' => 'Stambaugh');
$city_data[] = array('accid' => 'USMI0803', 'name' => 'Standish');
$city_data[] = array('accid' => 'USMI0804', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USMI0805', 'name' => 'Stanwood');
$city_data[] = array('accid' => 'USMI0806', 'name' => 'Stephenson');
$city_data[] = array('accid' => 'USMI0807', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USMI0808', 'name' => 'Sterling Heights');
$city_data[] = array('accid' => 'USMI0809', 'name' => 'Stevensville');
$city_data[] = array('accid' => 'USMI0810', 'name' => 'Stockbridge');
$city_data[] = array('accid' => 'USMI0811', 'name' => 'Strongs');
$city_data[] = array('accid' => 'USMI0812', 'name' => 'Sturgis');
$city_data[] = array('accid' => 'USMI0813', 'name' => 'Sumner');
$city_data[] = array('accid' => 'USMI0814', 'name' => 'Sunfield');
$city_data[] = array('accid' => 'USMI0815', 'name' => 'Suttons Bay');
$city_data[] = array('accid' => 'USMI0816', 'name' => 'Swartz Creek');
$city_data[] = array('accid' => 'USMI0817', 'name' => 'Tawas City');
$city_data[] = array('accid' => 'USMI0818', 'name' => 'Taylor');
$city_data[] = array('accid' => 'USMI0819', 'name' => 'Tecumseh');
$city_data[] = array('accid' => 'USMI0820', 'name' => 'Tekonsha');
$city_data[] = array('accid' => 'USMI0821', 'name' => 'Temperance');
$city_data[] = array('accid' => 'USMI0822', 'name' => 'Thompsonville');
$city_data[] = array('accid' => 'USMI0823', 'name' => 'Three Oaks');
$city_data[] = array('accid' => 'USMI0824', 'name' => 'Three Rivers');
$city_data[] = array('accid' => 'USMI0825', 'name' => 'Tipton');
$city_data[] = array('accid' => 'USMI0826', 'name' => 'Toivola');
$city_data[] = array('accid' => 'USMI0827', 'name' => 'Topinabee');
$city_data[] = array('accid' => 'USMI0828', 'name' => 'Tower');
$city_data[] = array('accid' => 'USMI0829', 'name' => 'Traverse City');
$city_data[] = array('accid' => 'USMI0830', 'name' => 'Trenary');
$city_data[] = array('accid' => 'USMI0831', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USMI0832', 'name' => 'Trout Creek');
$city_data[] = array('accid' => 'USMI0833', 'name' => 'Trout Lake');
$city_data[] = array('accid' => 'USMI0834', 'name' => 'Troy');
$city_data[] = array('accid' => 'USMI0835', 'name' => 'Trufant');
$city_data[] = array('accid' => 'USMI0836', 'name' => 'Turner');
$city_data[] = array('accid' => 'USMI0837', 'name' => 'Tuscola');
$city_data[] = array('accid' => 'USMI0838', 'name' => 'Tustin');
$city_data[] = array('accid' => 'USMI0839', 'name' => 'Twin Lake');
$city_data[] = array('accid' => 'USMI0840', 'name' => 'Twining');
$city_data[] = array('accid' => 'USMI0841', 'name' => 'Ubly');
$city_data[] = array('accid' => 'USMI0842', 'name' => 'Union');
$city_data[] = array('accid' => 'USMI0843', 'name' => 'Union City');
$city_data[] = array('accid' => 'USMI0844', 'name' => 'Union Lake');
$city_data[] = array('accid' => 'USMI0845', 'name' => 'Union Pier');
$city_data[] = array('accid' => 'USMI0846', 'name' => 'Unionville');
$city_data[] = array('accid' => 'USMI0847', 'name' => 'University Center');
$city_data[] = array('accid' => 'USMI0848', 'name' => 'Utica');
$city_data[] = array('accid' => 'USMI0849', 'name' => 'Vandalia');
$city_data[] = array('accid' => 'USMI0850', 'name' => 'Vanderbilt');
$city_data[] = array('accid' => 'USMI0851', 'name' => 'Vassar');
$city_data[] = array('accid' => 'USMI0852', 'name' => 'Vermontville');
$city_data[] = array('accid' => 'USMI0853', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USMI0854', 'name' => 'Vestaburg');
$city_data[] = array('accid' => 'USMI0855', 'name' => 'Vicksburg');
$city_data[] = array('accid' => 'USMI0856', 'name' => 'Vulcan');
$city_data[] = array('accid' => 'USMI0857', 'name' => 'Wabaningo');
$city_data[] = array('accid' => 'USMI0858', 'name' => 'Wakefield');
$city_data[] = array('accid' => 'USMI0859', 'name' => 'Waldron');
$city_data[] = array('accid' => 'USMI0860', 'name' => 'Walhalla');
$city_data[] = array('accid' => 'USMI0861', 'name' => 'Walkerville');
$city_data[] = array('accid' => 'USMI0862', 'name' => 'Wallace');
$city_data[] = array('accid' => 'USMI0863', 'name' => 'Walled Lake');
$city_data[] = array('accid' => 'USMI0864', 'name' => 'Walloon Lake');
$city_data[] = array('accid' => 'USMI0865', 'name' => 'Warren');
$city_data[] = array('accid' => 'USMI0866', 'name' => 'Washington');
$city_data[] = array('accid' => 'USMI0867', 'name' => 'Waterford');
$city_data[] = array('accid' => 'USMI0868', 'name' => 'Waters');
$city_data[] = array('accid' => 'USMI0869', 'name' => 'Watersmeet');
$city_data[] = array('accid' => 'USMI0870', 'name' => 'Watervliet');
$city_data[] = array('accid' => 'USMI0871', 'name' => 'Watton');
$city_data[] = array('accid' => 'USMI0872', 'name' => 'Wayland');
$city_data[] = array('accid' => 'USMI0873', 'name' => 'Wayne');
$city_data[] = array('accid' => 'USMI0874', 'name' => 'Webberville');
$city_data[] = array('accid' => 'USMI0875', 'name' => 'Weidman');
$city_data[] = array('accid' => 'USMI0876', 'name' => 'Wells');
$city_data[] = array('accid' => 'USMI0877', 'name' => 'Wellston');
$city_data[] = array('accid' => 'USMI0878', 'name' => 'West Bloomfield');
$city_data[] = array('accid' => 'USMI0879', 'name' => 'West Branch');
$city_data[] = array('accid' => 'USMI0880', 'name' => 'West Olive');
$city_data[] = array('accid' => 'USMI0881', 'name' => 'Westland');
$city_data[] = array('accid' => 'USMI0882', 'name' => 'Weston');
$city_data[] = array('accid' => 'USMI0883', 'name' => 'Westphalia');
$city_data[] = array('accid' => 'USMI0884', 'name' => 'Wetmore');
$city_data[] = array('accid' => 'USMI0885', 'name' => 'Wheeler');
$city_data[] = array('accid' => 'USMI0886', 'name' => 'White Cloud');
$city_data[] = array('accid' => 'USMI0887', 'name' => 'White Lake');
$city_data[] = array('accid' => 'USMI0888', 'name' => 'White Pigeon');
$city_data[] = array('accid' => 'USMI0889', 'name' => 'White Pine');
$city_data[] = array('accid' => 'USMI0890', 'name' => 'Whitehall');
$city_data[] = array('accid' => 'USMI0891', 'name' => 'Whitmore Lake');
$city_data[] = array('accid' => 'USMI0892', 'name' => 'Whittaker');
$city_data[] = array('accid' => 'USMI0893', 'name' => 'Whittemore');
$city_data[] = array('accid' => 'USMI0894', 'name' => 'Williamsburg');
$city_data[] = array('accid' => 'USMI0895', 'name' => 'Williamston');
$city_data[] = array('accid' => 'USMI0896', 'name' => 'Willis');
$city_data[] = array('accid' => 'USMI0897', 'name' => 'Wilson');
$city_data[] = array('accid' => 'USMI0898', 'name' => 'Winn');
$city_data[] = array('accid' => 'USMI0899', 'name' => 'Wixom');
$city_data[] = array('accid' => 'USMI0900', 'name' => 'Wolverine');
$city_data[] = array('accid' => 'USMI0901', 'name' => 'Woodland');
$city_data[] = array('accid' => 'USMI0902', 'name' => 'Wyandotte');
$city_data[] = array('accid' => 'USMI0903', 'name' => 'Yale');
$city_data[] = array('accid' => 'USMI0904', 'name' => 'Ypsilanti');
$city_data[] = array('accid' => 'USMI0905', 'name' => 'Zeeland');

?>
