<?php

// City package for USA: Minnesota 

$city_name = 'USA: Minnesota';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USMN0001', 'name' => 'Ada');
$city_data[] = array('accid' => 'USMN0002', 'name' => 'Adams');
$city_data[] = array('accid' => 'USMN0003', 'name' => 'Adolph');
$city_data[] = array('accid' => 'USMN0004', 'name' => 'Adrian');
$city_data[] = array('accid' => 'USMN0005', 'name' => 'Afton');
$city_data[] = array('accid' => 'USMN0007', 'name' => 'Ah Gwah Ching');
$city_data[] = array('accid' => 'USMN0008', 'name' => 'Aitkin');
$city_data[] = array('accid' => 'USMN0009', 'name' => 'Akeley');
$city_data[] = array('accid' => 'USMN0010', 'name' => 'Albany');
$city_data[] = array('accid' => 'USMN0011', 'name' => 'Albert Lea');
$city_data[] = array('accid' => 'USMN0012', 'name' => 'Alberta');
$city_data[] = array('accid' => 'USMN0013', 'name' => 'Albertville');
$city_data[] = array('accid' => 'USMN0014', 'name' => 'Alborn');
$city_data[] = array('accid' => 'USMN0015', 'name' => 'Alden');
$city_data[] = array('accid' => 'USMN0016', 'name' => 'Aldrich');
$city_data[] = array('accid' => 'USMN0017', 'name' => 'Alexandria');
$city_data[] = array('accid' => 'USMN0018', 'name' => 'Almelund');
$city_data[] = array('accid' => 'USMN0019', 'name' => 'Alpha');
$city_data[] = array('accid' => 'USMN0020', 'name' => 'Altura');
$city_data[] = array('accid' => 'USMN0021', 'name' => 'Alvarado');
$city_data[] = array('accid' => 'USMN0022', 'name' => 'Amboy');
$city_data[] = array('accid' => 'USMN0023', 'name' => 'Angle Inlet');
$city_data[] = array('accid' => 'USMN0024', 'name' => 'Angora');
$city_data[] = array('accid' => 'USMN0025', 'name' => 'Angus');
$city_data[] = array('accid' => 'USMN0026', 'name' => 'Annandale');
$city_data[] = array('accid' => 'USMN0027', 'name' => 'Anoka');
$city_data[] = array('accid' => 'USMN0028', 'name' => 'Appleton');
$city_data[] = array('accid' => 'USMN0029', 'name' => 'Arco');
$city_data[] = array('accid' => 'USMN0030', 'name' => 'Argyle');
$city_data[] = array('accid' => 'USMN0031', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USMN0032', 'name' => 'Ashby');
$city_data[] = array('accid' => 'USMN0033', 'name' => 'Askov');
$city_data[] = array('accid' => 'USMN0034', 'name' => 'Atwater');
$city_data[] = array('accid' => 'USMN0035', 'name' => 'Audubon');
$city_data[] = array('accid' => 'USMN0036', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USMN0037', 'name' => 'Austin');
$city_data[] = array('accid' => 'USMN0038', 'name' => 'Avoca');
$city_data[] = array('accid' => 'USMN0039', 'name' => 'Avon');
$city_data[] = array('accid' => 'USMN0040', 'name' => 'Babbitt');
$city_data[] = array('accid' => 'USMN0041', 'name' => 'Backus');
$city_data[] = array('accid' => 'USMN0042', 'name' => 'Badger');
$city_data[] = array('accid' => 'USMN0043', 'name' => 'Bagley');
$city_data[] = array('accid' => 'USMN0044', 'name' => 'Baker');
$city_data[] = array('accid' => 'USMN0045', 'name' => 'Balaton');
$city_data[] = array('accid' => 'USMN0046', 'name' => 'Barnesville');
$city_data[] = array('accid' => 'USMN0047', 'name' => 'Barnum');
$city_data[] = array('accid' => 'USMN0048', 'name' => 'Barrett');
$city_data[] = array('accid' => 'USMN0049', 'name' => 'Barry');
$city_data[] = array('accid' => 'USMN0050', 'name' => 'Battle Lake');
$city_data[] = array('accid' => 'USMN0051', 'name' => 'Baudette');
$city_data[] = array('accid' => 'USMN0052', 'name' => 'Baxter');
$city_data[] = array('accid' => 'USMN0053', 'name' => 'Bayport');
$city_data[] = array('accid' => 'USMN0054', 'name' => 'Beardsley');
$city_data[] = array('accid' => 'USMN0055', 'name' => 'Beaver Bay');
$city_data[] = array('accid' => 'USMN0056', 'name' => 'Beaver Creek');
$city_data[] = array('accid' => 'USMN0057', 'name' => 'Becker');
$city_data[] = array('accid' => 'USMN0058', 'name' => 'Bejou');
$city_data[] = array('accid' => 'USMN0059', 'name' => 'Belgrade');
$city_data[] = array('accid' => 'USMN0060', 'name' => 'Belle Plaine');
$city_data[] = array('accid' => 'USMN0061', 'name' => 'Bellingham');
$city_data[] = array('accid' => 'USMN0062', 'name' => 'Beltrami');
$city_data[] = array('accid' => 'USMN0063', 'name' => 'Belview');
$city_data[] = array('accid' => 'USMN0064', 'name' => 'Bemidji');
$city_data[] = array('accid' => 'USMN0065', 'name' => 'Bena');
$city_data[] = array('accid' => 'USMN0066', 'name' => 'Benedict');
$city_data[] = array('accid' => 'USMN0067', 'name' => 'Benson');
$city_data[] = array('accid' => 'USMN0068', 'name' => 'Bertha');
$city_data[] = array('accid' => 'USMN0069', 'name' => 'Bethel');
$city_data[] = array('accid' => 'USMN0070', 'name' => 'Big Falls');
$city_data[] = array('accid' => 'USMN0071', 'name' => 'Big Lake');
$city_data[] = array('accid' => 'USMN0072', 'name' => 'Bigelow');
$city_data[] = array('accid' => 'USMN0073', 'name' => 'Bigfork');
$city_data[] = array('accid' => 'USMN0074', 'name' => 'Bingham Lake');
$city_data[] = array('accid' => 'USMN0075', 'name' => 'Birchdale');
$city_data[] = array('accid' => 'USMN0076', 'name' => 'Bird Island');
$city_data[] = array('accid' => 'USMN0077', 'name' => 'Biwabik');
$city_data[] = array('accid' => 'USMN0078', 'name' => 'Blackduck');
$city_data[] = array('accid' => 'USMN0080', 'name' => 'Blomkest');
$city_data[] = array('accid' => 'USMN0081', 'name' => 'Blooming Prairie');
$city_data[] = array('accid' => 'USMN0082', 'name' => 'Blue Earth');
$city_data[] = array('accid' => 'USMN0083', 'name' => 'Bluffton');
$city_data[] = array('accid' => 'USMN0084', 'name' => 'Bock');
$city_data[] = array('accid' => 'USMN0085', 'name' => 'Borup');
$city_data[] = array('accid' => 'USMN0086', 'name' => 'Bovey');
$city_data[] = array('accid' => 'USMN0087', 'name' => 'Bowlus');
$city_data[] = array('accid' => 'USMN0088', 'name' => 'Bowstring');
$city_data[] = array('accid' => 'USMN0089', 'name' => 'Boyd');
$city_data[] = array('accid' => 'USMN0090', 'name' => 'Braham');
$city_data[] = array('accid' => 'USMN0091', 'name' => 'Brainerd');
$city_data[] = array('accid' => 'USMN0092', 'name' => 'Brandon');
$city_data[] = array('accid' => 'USMN0093', 'name' => 'Breckenridge');
$city_data[] = array('accid' => 'USMN0094', 'name' => 'Brewster');
$city_data[] = array('accid' => 'USMN0095', 'name' => 'Bricelyn');
$city_data[] = array('accid' => 'USMN0096', 'name' => 'Brimson');
$city_data[] = array('accid' => 'USMN0097', 'name' => 'Britt');
$city_data[] = array('accid' => 'USMN0098', 'name' => 'Brook Park');
$city_data[] = array('accid' => 'USMN0099', 'name' => 'Brooks');
$city_data[] = array('accid' => 'USMN0100', 'name' => 'Brookston');
$city_data[] = array('accid' => 'USMN0101', 'name' => 'Brooten');
$city_data[] = array('accid' => 'USMN0102', 'name' => 'Browerville');
$city_data[] = array('accid' => 'USMN0103', 'name' => 'Browns Valley');
$city_data[] = array('accid' => 'USMN0104', 'name' => 'Brownsdale');
$city_data[] = array('accid' => 'USMN0105', 'name' => 'Brownsville');
$city_data[] = array('accid' => 'USMN0106', 'name' => 'Brownton');
$city_data[] = array('accid' => 'USMN0107', 'name' => 'Bruno');
$city_data[] = array('accid' => 'USMN0108', 'name' => 'Buckman');
$city_data[] = array('accid' => 'USMN0109', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USMN0110', 'name' => 'Buffalo Lake');
$city_data[] = array('accid' => 'USMN0111', 'name' => 'Buhl');
$city_data[] = array('accid' => 'USMN0112', 'name' => 'Burnsville');
$city_data[] = array('accid' => 'USMN0113', 'name' => 'Burtrum');
$city_data[] = array('accid' => 'USMN0114', 'name' => 'Butterfield');
$city_data[] = array('accid' => 'USMN0115', 'name' => 'Byron');
$city_data[] = array('accid' => 'USMN0116', 'name' => 'Caledonia');
$city_data[] = array('accid' => 'USMN0117', 'name' => 'Callaway');
$city_data[] = array('accid' => 'USMN0118', 'name' => 'Calumet');
$city_data[] = array('accid' => 'USMN0119', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'USMN0120', 'name' => 'Campbell');
$city_data[] = array('accid' => 'USMN0121', 'name' => 'Canby');
$city_data[] = array('accid' => 'USMN0122', 'name' => 'Cannon Falls');
$city_data[] = array('accid' => 'USMN0123', 'name' => 'Canton');
$city_data[] = array('accid' => 'USMN0124', 'name' => 'Canyon');
$city_data[] = array('accid' => 'USMN0125', 'name' => 'Carlos');
$city_data[] = array('accid' => 'USMN0126', 'name' => 'Carlton');
$city_data[] = array('accid' => 'USMN0127', 'name' => 'Carver');
$city_data[] = array('accid' => 'USMN0128', 'name' => 'Cass Lake');
$city_data[] = array('accid' => 'USMN0129', 'name' => 'Castle Rock');
$city_data[] = array('accid' => 'USMN0130', 'name' => 'Cedar');
$city_data[] = array('accid' => 'USMN0131', 'name' => 'Center City');
$city_data[] = array('accid' => 'USMN0132', 'name' => 'Ceylon');
$city_data[] = array('accid' => 'USMN0133', 'name' => 'Champlin');
$city_data[] = array('accid' => 'USMN0134', 'name' => 'Chandler');
$city_data[] = array('accid' => 'USMN0135', 'name' => 'Chanhassen');
$city_data[] = array('accid' => 'USMN0136', 'name' => 'Chaska');
$city_data[] = array('accid' => 'USMN0137', 'name' => 'Chatfield');
$city_data[] = array('accid' => 'USMN0138', 'name' => 'Chisago City');
$city_data[] = array('accid' => 'USMN0139', 'name' => 'Chisholm');
$city_data[] = array('accid' => 'USMN0140', 'name' => 'Chokio');
$city_data[] = array('accid' => 'USMN0141', 'name' => 'Circle Pines');
$city_data[] = array('accid' => 'USMN0142', 'name' => 'Clara City');
$city_data[] = array('accid' => 'USMN0143', 'name' => 'Claremont');
$city_data[] = array('accid' => 'USMN0144', 'name' => 'Clarissa');
$city_data[] = array('accid' => 'USMN0145', 'name' => 'Clarkfield');
$city_data[] = array('accid' => 'USMN0146', 'name' => 'Clarks Grove');
$city_data[] = array('accid' => 'USMN0147', 'name' => 'Clear Lake');
$city_data[] = array('accid' => 'USMN0148', 'name' => 'Clearbrook');
$city_data[] = array('accid' => 'USMN0149', 'name' => 'Clearwater');
$city_data[] = array('accid' => 'USMN0150', 'name' => 'Clements');
$city_data[] = array('accid' => 'USMN0151', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USMN0152', 'name' => 'Climax');
$city_data[] = array('accid' => 'USMN0153', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USMN0154', 'name' => 'Clitherall');
$city_data[] = array('accid' => 'USMN0155', 'name' => 'Clontarf');
$city_data[] = array('accid' => 'USMN0156', 'name' => 'Cloquet');
$city_data[] = array('accid' => 'USMN0157', 'name' => 'Cohasset');
$city_data[] = array('accid' => 'USMN0158', 'name' => 'Cokato');
$city_data[] = array('accid' => 'USMN0159', 'name' => 'Cold Spring');
$city_data[] = array('accid' => 'USMN0160', 'name' => 'Coleraine');
$city_data[] = array('accid' => 'USMN0161', 'name' => 'Collegeville');
$city_data[] = array('accid' => 'USMN0162', 'name' => 'Cologne');
$city_data[] = array('accid' => 'USMN0163', 'name' => 'Comfrey');
$city_data[] = array('accid' => 'USMN0164', 'name' => 'Comstock');
$city_data[] = array('accid' => 'USMN0165', 'name' => 'Conger');
$city_data[] = array('accid' => 'USMN0166', 'name' => 'Cook');
$city_data[] = array('accid' => 'USMN0167', 'name' => 'Correll');
$city_data[] = array('accid' => 'USMN0168', 'name' => 'Cosmos');
$city_data[] = array('accid' => 'USMN0169', 'name' => 'Cottage Grove');
$city_data[] = array('accid' => 'USMN0170', 'name' => 'Cotton');
$city_data[] = array('accid' => 'USMN0171', 'name' => 'Cottonwood');
$city_data[] = array('accid' => 'USMN0172', 'name' => 'Courtland');
$city_data[] = array('accid' => 'USMN0173', 'name' => 'Crane Lake');
$city_data[] = array('accid' => 'USMN0174', 'name' => 'Cromwell');
$city_data[] = array('accid' => 'USMN0175', 'name' => 'Crookston');
$city_data[] = array('accid' => 'USMN0176', 'name' => 'Crosby');
$city_data[] = array('accid' => 'USMN0177', 'name' => 'Crosslake');
$city_data[] = array('accid' => 'USMN0179', 'name' => 'Crystal Bay');
$city_data[] = array('accid' => 'USMN0180', 'name' => 'Currie');
$city_data[] = array('accid' => 'USMN0181', 'name' => 'Cushing');
$city_data[] = array('accid' => 'USMN0182', 'name' => 'Cyrus');
$city_data[] = array('accid' => 'USMN0183', 'name' => 'Dakota');
$city_data[] = array('accid' => 'USMN0184', 'name' => 'Dalbo');
$city_data[] = array('accid' => 'USMN0185', 'name' => 'Dalton');
$city_data[] = array('accid' => 'USMN0186', 'name' => 'Danube');
$city_data[] = array('accid' => 'USMN0187', 'name' => 'Danvers');
$city_data[] = array('accid' => 'USMN0188', 'name' => 'Darfur');
$city_data[] = array('accid' => 'USMN0189', 'name' => 'Darwin');
$city_data[] = array('accid' => 'USMN0190', 'name' => 'Dassel');
$city_data[] = array('accid' => 'USMN0191', 'name' => 'Dawson');
$city_data[] = array('accid' => 'USMN0192', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USMN0193', 'name' => 'Deer Creek');
$city_data[] = array('accid' => 'USMN0194', 'name' => 'Deer River');
$city_data[] = array('accid' => 'USMN0195', 'name' => 'Deerwood');
$city_data[] = array('accid' => 'USMN0196', 'name' => 'Delano');
$city_data[] = array('accid' => 'USMN0197', 'name' => 'Delavan');
$city_data[] = array('accid' => 'USMN0198', 'name' => 'Dennison');
$city_data[] = array('accid' => 'USMN0199', 'name' => 'Dent');
$city_data[] = array('accid' => 'USMN0200', 'name' => 'Detroit Lakes');
$city_data[] = array('accid' => 'USMN0201', 'name' => 'Dexter');
$city_data[] = array('accid' => 'USMN0202', 'name' => 'Dilworth');
$city_data[] = array('accid' => 'USMN0203', 'name' => 'Dodge Center');
$city_data[] = array('accid' => 'USMN0204', 'name' => 'Donaldson');
$city_data[] = array('accid' => 'USMN0205', 'name' => 'Donnelly');
$city_data[] = array('accid' => 'USMN0206', 'name' => 'Dover');
$city_data[] = array('accid' => 'USMN0207', 'name' => 'Dovray');
$city_data[] = array('accid' => 'USMN0208', 'name' => 'Duluth');
$city_data[] = array('accid' => 'USMN0210', 'name' => 'Dumont');
$city_data[] = array('accid' => 'USMN0211', 'name' => 'Dundas');
$city_data[] = array('accid' => 'USMN0212', 'name' => 'Dunnell');
$city_data[] = array('accid' => 'USMN0213', 'name' => 'Duquette');
$city_data[] = array('accid' => 'USMN0215', 'name' => 'Eagle Bend');
$city_data[] = array('accid' => 'USMN0216', 'name' => 'Eagle Lake');
$city_data[] = array('accid' => 'USMN0217', 'name' => 'East Grand Forks');
$city_data[] = array('accid' => 'USMN0218', 'name' => 'Easton');
$city_data[] = array('accid' => 'USMN0219', 'name' => 'Echo');
$city_data[] = array('accid' => 'USMN0220', 'name' => 'Eden Prairie');
$city_data[] = array('accid' => 'USMN0221', 'name' => 'Eden Valley');
$city_data[] = array('accid' => 'USMN0222', 'name' => 'Edgerton');
$city_data[] = array('accid' => 'USMN0223', 'name' => 'Effie');
$city_data[] = array('accid' => 'USMN0224', 'name' => 'Eitzen');
$city_data[] = array('accid' => 'USMN0225', 'name' => 'Elbow Lake');
$city_data[] = array('accid' => 'USMN0226', 'name' => 'Elgin');
$city_data[] = array('accid' => 'USMN0227', 'name' => 'Elizabeth');
$city_data[] = array('accid' => 'USMN0228', 'name' => 'Elk River');
$city_data[] = array('accid' => 'USMN0229', 'name' => 'Elko');
$city_data[] = array('accid' => 'USMN0230', 'name' => 'Elkton');
$city_data[] = array('accid' => 'USMN0231', 'name' => 'Ellendale');
$city_data[] = array('accid' => 'USMN0232', 'name' => 'Ellsworth');
$city_data[] = array('accid' => 'USMN0233', 'name' => 'Elmore');
$city_data[] = array('accid' => 'USMN0234', 'name' => 'Elrosa');
$city_data[] = array('accid' => 'USMN0235', 'name' => 'Ely');
$city_data[] = array('accid' => 'USMN0236', 'name' => 'Elysian');
$city_data[] = array('accid' => 'USMN0237', 'name' => 'Embarrass');
$city_data[] = array('accid' => 'USMN0238', 'name' => 'Emily');
$city_data[] = array('accid' => 'USMN0239', 'name' => 'Emmons');
$city_data[] = array('accid' => 'USMN0240', 'name' => 'Erhard');
$city_data[] = array('accid' => 'USMN0241', 'name' => 'Erskine');
$city_data[] = array('accid' => 'USMN0242', 'name' => 'Esko');
$city_data[] = array('accid' => 'USMN0243', 'name' => 'Essig');
$city_data[] = array('accid' => 'USMN0244', 'name' => 'Euclid');
$city_data[] = array('accid' => 'USMN0245', 'name' => 'Evansville');
$city_data[] = array('accid' => 'USMN0246', 'name' => 'Eveleth');
$city_data[] = array('accid' => 'USMN0247', 'name' => 'Excelsior');
$city_data[] = array('accid' => 'USMN0248', 'name' => 'Eyota');
$city_data[] = array('accid' => 'USMN0249', 'name' => 'Fairfax');
$city_data[] = array('accid' => 'USMN0250', 'name' => 'Fairmont');
$city_data[] = array('accid' => 'USMN0251', 'name' => 'Faribault');
$city_data[] = array('accid' => 'USMN0252', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USMN0253', 'name' => 'Farwell');
$city_data[] = array('accid' => 'USMN0254', 'name' => 'Federal Dam');
$city_data[] = array('accid' => 'USMN0255', 'name' => 'Felton');
$city_data[] = array('accid' => 'USMN0256', 'name' => 'Fergus Falls');
$city_data[] = array('accid' => 'USMN0257', 'name' => 'Fertile');
$city_data[] = array('accid' => 'USMN0258', 'name' => 'Fifty Lakes');
$city_data[] = array('accid' => 'USMN0259', 'name' => 'Finland');
$city_data[] = array('accid' => 'USMN0260', 'name' => 'Finlayson');
$city_data[] = array('accid' => 'USMN0261', 'name' => 'Fisher');
$city_data[] = array('accid' => 'USMN0263', 'name' => 'Flensburg');
$city_data[] = array('accid' => 'USMN0264', 'name' => 'Flom');
$city_data[] = array('accid' => 'USMN0265', 'name' => 'Floodwood');
$city_data[] = array('accid' => 'USMN0266', 'name' => 'Foley');
$city_data[] = array('accid' => 'USMN0267', 'name' => 'Forbes');
$city_data[] = array('accid' => 'USMN0268', 'name' => 'Forest Lake');
$city_data[] = array('accid' => 'USMN0269', 'name' => 'Foreston');
$city_data[] = array('accid' => 'USMN0270', 'name' => 'Fort Ripley');
$city_data[] = array('accid' => 'USMN0271', 'name' => 'Fosston');
$city_data[] = array('accid' => 'USMN0272', 'name' => 'Fountain');
$city_data[] = array('accid' => 'USMN0273', 'name' => 'Foxhome');
$city_data[] = array('accid' => 'USMN0274', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USMN0275', 'name' => 'Frazee');
$city_data[] = array('accid' => 'USMN0276', 'name' => 'Freeborn');
$city_data[] = array('accid' => 'USMN0277', 'name' => 'Freeport');
$city_data[] = array('accid' => 'USMN0278', 'name' => 'Frontenac');
$city_data[] = array('accid' => 'USMN0279', 'name' => 'Frost');
$city_data[] = array('accid' => 'USMN0280', 'name' => 'Fulda');
$city_data[] = array('accid' => 'USMN0281', 'name' => 'Garden City');
$city_data[] = array('accid' => 'USMN0282', 'name' => 'Garfield');
$city_data[] = array('accid' => 'USMN0283', 'name' => 'Garrison');
$city_data[] = array('accid' => 'USMN0284', 'name' => 'Garvin');
$city_data[] = array('accid' => 'USMN0285', 'name' => 'Gary');
$city_data[] = array('accid' => 'USMN0286', 'name' => 'Gatzke');
$city_data[] = array('accid' => 'USMN0287', 'name' => 'Gaylord');
$city_data[] = array('accid' => 'USMN0288', 'name' => 'Geneva');
$city_data[] = array('accid' => 'USMN0289', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USMN0290', 'name' => 'Ghent');
$city_data[] = array('accid' => 'USMN0291', 'name' => 'Gibbon');
$city_data[] = array('accid' => 'USMN0292', 'name' => 'Gilbert');
$city_data[] = array('accid' => 'USMN0293', 'name' => 'Gilman');
$city_data[] = array('accid' => 'USMN0294', 'name' => 'Glencoe');
$city_data[] = array('accid' => 'USMN0295', 'name' => 'Glenville');
$city_data[] = array('accid' => 'USMN0296', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USMN0297', 'name' => 'Glyndon');
$city_data[] = array('accid' => 'USMN0298', 'name' => 'Gonvick');
$city_data[] = array('accid' => 'USMN0299', 'name' => 'Good Thunder');
$city_data[] = array('accid' => 'USMN0300', 'name' => 'Goodhue');
$city_data[] = array('accid' => 'USMN0301', 'name' => 'Goodland');
$city_data[] = array('accid' => 'USMN0302', 'name' => 'Goodridge');
$city_data[] = array('accid' => 'USMN0303', 'name' => 'Graceville');
$city_data[] = array('accid' => 'USMN0304', 'name' => 'Granada');
$city_data[] = array('accid' => 'USMN0305', 'name' => 'Grand Marais');
$city_data[] = array('accid' => 'USMN0307', 'name' => 'Grand Meadow');
$city_data[] = array('accid' => 'USMN0308', 'name' => 'Grand Portage');
$city_data[] = array('accid' => 'USMN0309', 'name' => 'Grand Rapids');
$city_data[] = array('accid' => 'USMN0310', 'name' => 'Grandy');
$city_data[] = array('accid' => 'USMN0311', 'name' => 'Granite Falls');
$city_data[] = array('accid' => 'USMN0312', 'name' => 'Grasston');
$city_data[] = array('accid' => 'USMN0313', 'name' => 'Green Isle');
$city_data[] = array('accid' => 'USMN0314', 'name' => 'Greenbush');
$city_data[] = array('accid' => 'USMN0315', 'name' => 'Greenwald');
$city_data[] = array('accid' => 'USMN0316', 'name' => 'Grey Eagle');
$city_data[] = array('accid' => 'USMN0317', 'name' => 'Grove City');
$city_data[] = array('accid' => 'USMN0318', 'name' => 'Grygla');
$city_data[] = array('accid' => 'USMN0319', 'name' => 'Gully');
$city_data[] = array('accid' => 'USMN0320', 'name' => 'Hackensack');
$city_data[] = array('accid' => 'USMN0321', 'name' => 'Hallock');
$city_data[] = array('accid' => 'USMN0322', 'name' => 'Halma');
$city_data[] = array('accid' => 'USMN0323', 'name' => 'Halstad');
$city_data[] = array('accid' => 'USMN0324', 'name' => 'Hamburg');
$city_data[] = array('accid' => 'USMN0325', 'name' => 'Hamel');
$city_data[] = array('accid' => 'USMN0326', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USMN0327', 'name' => 'Hancock');
$city_data[] = array('accid' => 'USMN0328', 'name' => 'Hanley Falls');
$city_data[] = array('accid' => 'USMN0329', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USMN0330', 'name' => 'Hanska');
$city_data[] = array('accid' => 'USMN0331', 'name' => 'Hardwick');
$city_data[] = array('accid' => 'USMN0332', 'name' => 'Harmony');
$city_data[] = array('accid' => 'USMN0333', 'name' => 'Harris');
$city_data[] = array('accid' => 'USMN0334', 'name' => 'Hartland');
$city_data[] = array('accid' => 'USMN0335', 'name' => 'Hastings');
$city_data[] = array('accid' => 'USMN0336', 'name' => 'Hawick');
$city_data[] = array('accid' => 'USMN0337', 'name' => 'Hawley');
$city_data[] = array('accid' => 'USMN0338', 'name' => 'Hayfield');
$city_data[] = array('accid' => 'USMN0339', 'name' => 'Hayward');
$city_data[] = array('accid' => 'USMN0340', 'name' => 'Hector');
$city_data[] = array('accid' => 'USMN0341', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USMN0342', 'name' => 'Hendricks');
$city_data[] = array('accid' => 'USMN0343', 'name' => 'Hendrum');
$city_data[] = array('accid' => 'USMN0344', 'name' => 'Henning');
$city_data[] = array('accid' => 'USMN0345', 'name' => 'Henriette');
$city_data[] = array('accid' => 'USMN0346', 'name' => 'Herman');
$city_data[] = array('accid' => 'USMN0347', 'name' => 'Heron Lake');
$city_data[] = array('accid' => 'USMN0348', 'name' => 'Hewitt');
$city_data[] = array('accid' => 'USMN0349', 'name' => 'Hibbing');
$city_data[] = array('accid' => 'USMN0350', 'name' => 'Hill City');
$city_data[] = array('accid' => 'USMN0351', 'name' => 'Hillman');
$city_data[] = array('accid' => 'USMN0352', 'name' => 'Hills');
$city_data[] = array('accid' => 'USMN0353', 'name' => 'Hinckley');
$city_data[] = array('accid' => 'USMN0354', 'name' => 'Hines');
$city_data[] = array('accid' => 'USMN0355', 'name' => 'Hitterdal');
$city_data[] = array('accid' => 'USMN0356', 'name' => 'Hoffman');
$city_data[] = array('accid' => 'USMN0357', 'name' => 'Hokah');
$city_data[] = array('accid' => 'USMN0358', 'name' => 'Holdingford');
$city_data[] = array('accid' => 'USMN0359', 'name' => 'Holland');
$city_data[] = array('accid' => 'USMN0360', 'name' => 'Hollandale');
$city_data[] = array('accid' => 'USMN0361', 'name' => 'Holloway');
$city_data[] = array('accid' => 'USMN0362', 'name' => 'Holmes City');
$city_data[] = array('accid' => 'USMN0363', 'name' => 'Holyoke');
$city_data[] = array('accid' => 'USMN0364', 'name' => 'Homer');
$city_data[] = array('accid' => 'USMN0365', 'name' => 'Hope');
$city_data[] = array('accid' => 'USMN0366', 'name' => 'Hopkins');
$city_data[] = array('accid' => 'USMN0367', 'name' => 'Houston');
$city_data[] = array('accid' => 'USMN0368', 'name' => 'Hovland');
$city_data[] = array('accid' => 'USMN0369', 'name' => 'Howard Lake');
$city_data[] = array('accid' => 'USMN0370', 'name' => 'Hoyt Lakes');
$city_data[] = array('accid' => 'USMN0371', 'name' => 'Hugo');
$city_data[] = array('accid' => 'USMN0372', 'name' => 'Humboldt');
$city_data[] = array('accid' => 'USMN0373', 'name' => 'Huntley');
$city_data[] = array('accid' => 'USMN0374', 'name' => 'Hutchinson');
$city_data[] = array('accid' => 'USMN0375', 'name' => 'Ihlen');
$city_data[] = array('accid' => 'USMN0376', 'name' => 'International Falls');
$city_data[] = array('accid' => 'USMN0377', 'name' => 'Inver Grove Heights');
$city_data[] = array('accid' => 'USMN0378', 'name' => 'Iona');
$city_data[] = array('accid' => 'USMN0379', 'name' => 'Iron');
$city_data[] = array('accid' => 'USMN0380', 'name' => 'Ironton');
$city_data[] = array('accid' => 'USMN0381', 'name' => 'Isabella');
$city_data[] = array('accid' => 'USMN0382', 'name' => 'Isanti');
$city_data[] = array('accid' => 'USMN0383', 'name' => 'Isle');
$city_data[] = array('accid' => 'USMN0384', 'name' => 'Ivanhoe');
$city_data[] = array('accid' => 'USMN0385', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USMN0386', 'name' => 'Jacobson');
$city_data[] = array('accid' => 'USMN0387', 'name' => 'Janesville');
$city_data[] = array('accid' => 'USMN0388', 'name' => 'Jasper');
$city_data[] = array('accid' => 'USMN0389', 'name' => 'Jeffers');
$city_data[] = array('accid' => 'USMN0390', 'name' => 'Jenkins');
$city_data[] = array('accid' => 'USMN0391', 'name' => 'Jordan');
$city_data[] = array('accid' => 'USMN0392', 'name' => 'Kanaranzi');
$city_data[] = array('accid' => 'USMN0393', 'name' => 'Kandiyohi');
$city_data[] = array('accid' => 'USMN0394', 'name' => 'Karlstad');
$city_data[] = array('accid' => 'USMN0395', 'name' => 'Kasota');
$city_data[] = array('accid' => 'USMN0396', 'name' => 'Kasson');
$city_data[] = array('accid' => 'USMN0397', 'name' => 'Keewatin');
$city_data[] = array('accid' => 'USMN0398', 'name' => 'Kelliher');
$city_data[] = array('accid' => 'USMN0399', 'name' => 'Kellogg');
$city_data[] = array('accid' => 'USMN0400', 'name' => 'Kennedy');
$city_data[] = array('accid' => 'USMN0401', 'name' => 'Kenneth');
$city_data[] = array('accid' => 'USMN0402', 'name' => 'Kensington');
$city_data[] = array('accid' => 'USMN0403', 'name' => 'Kent');
$city_data[] = array('accid' => 'USMN0404', 'name' => 'Kenyon');
$city_data[] = array('accid' => 'USMN0405', 'name' => 'Kerkhoven');
$city_data[] = array('accid' => 'USMN0406', 'name' => 'Kerrick');
$city_data[] = array('accid' => 'USMN0407', 'name' => 'Kettle River');
$city_data[] = array('accid' => 'USMN0408', 'name' => 'Kiester');
$city_data[] = array('accid' => 'USMN0409', 'name' => 'Kilkenny');
$city_data[] = array('accid' => 'USMN0410', 'name' => 'Kimball');
$city_data[] = array('accid' => 'USMN0411', 'name' => 'Kinney');
$city_data[] = array('accid' => 'USMN0412', 'name' => 'Knife River');
$city_data[] = array('accid' => 'USMN0413', 'name' => 'La Crescent');
$city_data[] = array('accid' => 'USMN0414', 'name' => 'La Salle');
$city_data[] = array('accid' => 'USMN0415', 'name' => 'Lafayette');
$city_data[] = array('accid' => 'USMN0416', 'name' => 'Lake Benton');
$city_data[] = array('accid' => 'USMN0417', 'name' => 'Lake Bronson');
$city_data[] = array('accid' => 'USMN0418', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USMN0419', 'name' => 'Lake Crystal');
$city_data[] = array('accid' => 'USMN0420', 'name' => 'Lake Elmo');
$city_data[] = array('accid' => 'USMN0421', 'name' => 'Lake George');
$city_data[] = array('accid' => 'USMN0422', 'name' => 'Lake Hubert');
$city_data[] = array('accid' => 'USMN0424', 'name' => 'Lake Lillian');
$city_data[] = array('accid' => 'USMN0425', 'name' => 'Lake Park');
$city_data[] = array('accid' => 'USMN0426', 'name' => 'Lake Wilson');
$city_data[] = array('accid' => 'USMN0427', 'name' => 'Lakefield');
$city_data[] = array('accid' => 'USMN0428', 'name' => 'Lakeland');
$city_data[] = array('accid' => 'USMN0429', 'name' => 'Lakeville');
$city_data[] = array('accid' => 'USMN0430', 'name' => 'Lamberton');
$city_data[] = array('accid' => 'USMN0431', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USMN0432', 'name' => 'Lanesboro');
$city_data[] = array('accid' => 'USMN0433', 'name' => 'Lansing');
$city_data[] = array('accid' => 'USMN0434', 'name' => 'Laporte');
$city_data[] = array('accid' => 'USMN0435', 'name' => 'Lastrup');
$city_data[] = array('accid' => 'USMN0436', 'name' => 'Le Center');
$city_data[] = array('accid' => 'USMN0437', 'name' => 'Le Roy');
$city_data[] = array('accid' => 'USMN0438', 'name' => 'Le Sueur');
$city_data[] = array('accid' => 'USMN0439', 'name' => 'Lengby');
$city_data[] = array('accid' => 'USMN0440', 'name' => 'Leonard');
$city_data[] = array('accid' => 'USMN0441', 'name' => 'Leota');
$city_data[] = array('accid' => 'USMN0442', 'name' => 'Lester Prairie');
$city_data[] = array('accid' => 'USMN0443', 'name' => 'Lewiston');
$city_data[] = array('accid' => 'USMN0444', 'name' => 'Lewisville');
$city_data[] = array('accid' => 'USMN0445', 'name' => 'Lindstrom');
$city_data[] = array('accid' => 'USMN0446', 'name' => 'Lismore');
$city_data[] = array('accid' => 'USMN0447', 'name' => 'Litchfield');
$city_data[] = array('accid' => 'USMN0448', 'name' => 'Little Falls');
$city_data[] = array('accid' => 'USMN0449', 'name' => 'Littlefork');
$city_data[] = array('accid' => 'USMN0450', 'name' => 'Loman');
$city_data[] = array('accid' => 'USMN0451', 'name' => 'Long Lake');
$city_data[] = array('accid' => 'USMN0452', 'name' => 'Long Prairie');
$city_data[] = array('accid' => 'USMN0453', 'name' => 'Longville');
$city_data[] = array('accid' => 'USMN0454', 'name' => 'Lonsdale');
$city_data[] = array('accid' => 'USMN0455', 'name' => 'Loretto');
$city_data[] = array('accid' => 'USMN0456', 'name' => 'Lowry');
$city_data[] = array('accid' => 'USMN0457', 'name' => 'Lucan');
$city_data[] = array('accid' => 'USMN0458', 'name' => 'Lutsen');
$city_data[] = array('accid' => 'USMN0460', 'name' => 'Luverne');
$city_data[] = array('accid' => 'USMN0461', 'name' => 'Lyle');
$city_data[] = array('accid' => 'USMN0462', 'name' => 'Lynd');
$city_data[] = array('accid' => 'USMN0463', 'name' => 'Mabel');
$city_data[] = array('accid' => 'USMN0464', 'name' => 'Madelia');
$city_data[] = array('accid' => 'USMN0465', 'name' => 'Madison');
$city_data[] = array('accid' => 'USMN0466', 'name' => 'Madison Lake');
$city_data[] = array('accid' => 'USMN0467', 'name' => 'Magnolia');
$city_data[] = array('accid' => 'USMN0468', 'name' => 'Mahnomen');
$city_data[] = array('accid' => 'USMN0469', 'name' => 'Makinen');
$city_data[] = array('accid' => 'USMN0470', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USMN0471', 'name' => 'Mankato');
$city_data[] = array('accid' => 'USMN0472', 'name' => 'Mantorville');
$city_data[] = array('accid' => 'USMN0473', 'name' => 'Maple Lake');
$city_data[] = array('accid' => 'USMN0474', 'name' => 'Maple Plain');
$city_data[] = array('accid' => 'USMN0475', 'name' => 'Mapleton');
$city_data[] = array('accid' => 'USMN0476', 'name' => 'Marble');
$city_data[] = array('accid' => 'USMN0477', 'name' => 'Marcell');
$city_data[] = array('accid' => 'USMN0478', 'name' => 'Margie');
$city_data[] = array('accid' => 'USMN0479', 'name' => 'Marietta');
$city_data[] = array('accid' => 'USMN0480', 'name' => 'Marine On Saint Croix');
$city_data[] = array('accid' => 'USMN0481', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USMN0482', 'name' => 'Max');
$city_data[] = array('accid' => 'USMN0483', 'name' => 'Mayer');
$city_data[] = array('accid' => 'USMN0484', 'name' => 'Maynard');
$city_data[] = array('accid' => 'USMN0485', 'name' => 'Mazeppa');
$city_data[] = array('accid' => 'USMN0486', 'name' => 'McGrath');
$city_data[] = array('accid' => 'USMN0487', 'name' => 'McGregor');
$city_data[] = array('accid' => 'USMN0488', 'name' => 'McIntosh');
$city_data[] = array('accid' => 'USMN0489', 'name' => 'Meadowlands');
$city_data[] = array('accid' => 'USMN0490', 'name' => 'Medford');
$city_data[] = array('accid' => 'USMN0491', 'name' => 'Melrose');
$city_data[] = array('accid' => 'USMN0492', 'name' => 'Melrude');
$city_data[] = array('accid' => 'USMN0493', 'name' => 'Menahga');
$city_data[] = array('accid' => 'USMN0494', 'name' => 'Mendota');
$city_data[] = array('accid' => 'USMN0495', 'name' => 'Mentor');
$city_data[] = array('accid' => 'USMN0496', 'name' => 'Merrifield');
$city_data[] = array('accid' => 'USMN0497', 'name' => 'Middle River');
$city_data[] = array('accid' => 'USMN0498', 'name' => 'Milaca');
$city_data[] = array('accid' => 'USMN0499', 'name' => 'Milan');
$city_data[] = array('accid' => 'USMN0500', 'name' => 'Millville');
$city_data[] = array('accid' => 'USMN0501', 'name' => 'Milroy');
$city_data[] = array('accid' => 'USMN0502', 'name' => 'Miltona');
$city_data[] = array('accid' => 'USMN0503', 'name' => 'Minneapolis');
$city_data[] = array('accid' => 'USMN0504', 'name' => 'Minneota');
$city_data[] = array('accid' => 'USMN0505', 'name' => 'Minnesota City');
$city_data[] = array('accid' => 'USMN0506', 'name' => 'Minnesota Lake');
$city_data[] = array('accid' => 'USMN0507', 'name' => 'Minnetonka');
$city_data[] = array('accid' => 'USMN0508', 'name' => 'Minnetonka Beach');
$city_data[] = array('accid' => 'USMN0509', 'name' => 'Mizpah');
$city_data[] = array('accid' => 'USMN0510', 'name' => 'Montevideo');
$city_data[] = array('accid' => 'USMN0511', 'name' => 'Montgomery');
$city_data[] = array('accid' => 'USMN0512', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USMN0513', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USMN0514', 'name' => 'Moorhead');
$city_data[] = array('accid' => 'USMN0515', 'name' => 'Moose Lake');
$city_data[] = array('accid' => 'USMN0516', 'name' => 'Mora');
$city_data[] = array('accid' => 'USMN0517', 'name' => 'Morgan');
$city_data[] = array('accid' => 'USMN0518', 'name' => 'Morris');
$city_data[] = array('accid' => 'USMN0519', 'name' => 'Morristown');
$city_data[] = array('accid' => 'USMN0520', 'name' => 'Morton');
$city_data[] = array('accid' => 'USMN0521', 'name' => 'Motley');
$city_data[] = array('accid' => 'USMN0522', 'name' => 'Mound');
$city_data[] = array('accid' => 'USMN0523', 'name' => 'Mountain Iron');
$city_data[] = array('accid' => 'USMN0524', 'name' => 'Mountain Lake');
$city_data[] = array('accid' => 'USMN0525', 'name' => 'Murdock');
$city_data[] = array('accid' => 'USMN0526', 'name' => 'Nashua');
$city_data[] = array('accid' => 'USMN0527', 'name' => 'Nashwauk');
$city_data[] = array('accid' => 'USMN0528', 'name' => 'Nassau');
$city_data[] = array('accid' => 'USMN0529', 'name' => 'Navarre');
$city_data[] = array('accid' => 'USMN0530', 'name' => 'Naytahwaush');
$city_data[] = array('accid' => 'USMN0531', 'name' => 'Nelson');
$city_data[] = array('accid' => 'USMN0532', 'name' => 'Nerstrand');
$city_data[] = array('accid' => 'USMN0533', 'name' => 'Nett Lake');
$city_data[] = array('accid' => 'USMN0534', 'name' => 'Nevis');
$city_data[] = array('accid' => 'USMN0535', 'name' => 'New Auburn');
$city_data[] = array('accid' => 'USMN0536', 'name' => 'New Germany');
$city_data[] = array('accid' => 'USMN0537', 'name' => 'New London');
$city_data[] = array('accid' => 'USMN0538', 'name' => 'New Market');
$city_data[] = array('accid' => 'USMN0539', 'name' => 'New Munich');
$city_data[] = array('accid' => 'USMN0540', 'name' => 'New Prague');
$city_data[] = array('accid' => 'USMN0541', 'name' => 'New Richland');
$city_data[] = array('accid' => 'USMN0542', 'name' => 'New Ulm');
$city_data[] = array('accid' => 'USMN0543', 'name' => 'New York Mills');
$city_data[] = array('accid' => 'USMN0544', 'name' => 'Newfolden');
$city_data[] = array('accid' => 'USMN0545', 'name' => 'Newport');
$city_data[] = array('accid' => 'USMN0546', 'name' => 'Nicollet');
$city_data[] = array('accid' => 'USMN0547', 'name' => 'Nielsville');
$city_data[] = array('accid' => 'USMN0548', 'name' => 'Nimrod');
$city_data[] = array('accid' => 'USMN0549', 'name' => 'Nisswa');
$city_data[] = array('accid' => 'USMN0550', 'name' => 'Norcross');
$city_data[] = array('accid' => 'USMN0551', 'name' => 'North Branch');
$city_data[] = array('accid' => 'USMN0552', 'name' => 'Northfield');
$city_data[] = array('accid' => 'USMN0553', 'name' => 'Northome');
$city_data[] = array('accid' => 'USMN0554', 'name' => 'Northrop');
$city_data[] = array('accid' => 'USMN0555', 'name' => 'Norwood');
$city_data[] = array('accid' => 'USMN0556', 'name' => 'Noyes');
$city_data[] = array('accid' => 'USMN0557', 'name' => 'Oak Island');
$city_data[] = array('accid' => 'USMN0558', 'name' => 'Oak Park');
$city_data[] = array('accid' => 'USMN0559', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USMN0560', 'name' => 'Odessa');
$city_data[] = array('accid' => 'USMN0561', 'name' => 'Odin');
$city_data[] = array('accid' => 'USMN0562', 'name' => 'Ogema');
$city_data[] = array('accid' => 'USMN0563', 'name' => 'Ogilvie');
$city_data[] = array('accid' => 'USMN0564', 'name' => 'Okabena');
$city_data[] = array('accid' => 'USMN0565', 'name' => 'Oklee');
$city_data[] = array('accid' => 'USMN0566', 'name' => 'Olivia');
$city_data[] = array('accid' => 'USMN0567', 'name' => 'Onamia');
$city_data[] = array('accid' => 'USMN0568', 'name' => 'Ormsby');
$city_data[] = array('accid' => 'USMN0569', 'name' => 'Oronoco');
$city_data[] = array('accid' => 'USMN0570', 'name' => 'Orr');
$city_data[] = array('accid' => 'USMN0571', 'name' => 'Ortonville');
$city_data[] = array('accid' => 'USMN0572', 'name' => 'Osage');
$city_data[] = array('accid' => 'USMN0573', 'name' => 'Osakis');
$city_data[] = array('accid' => 'USMN0574', 'name' => 'Oslo');
$city_data[] = array('accid' => 'USMN0575', 'name' => 'Osseo');
$city_data[] = array('accid' => 'USMN0576', 'name' => 'Ostrander');
$city_data[] = array('accid' => 'USMN0577', 'name' => 'Ottertail');
$city_data[] = array('accid' => 'USMN0578', 'name' => 'Outing');
$city_data[] = array('accid' => 'USMN0579', 'name' => 'Owatonna');
$city_data[] = array('accid' => 'USMN0580', 'name' => 'Palisade');
$city_data[] = array('accid' => 'USMN0581', 'name' => 'Park Rapids');
$city_data[] = array('accid' => 'USMN0582', 'name' => 'Parkers Prairie');
$city_data[] = array('accid' => 'USMN0583', 'name' => 'Paynesville');
$city_data[] = array('accid' => 'USMN0584', 'name' => 'Pease');
$city_data[] = array('accid' => 'USMN0585', 'name' => 'Pelican Rapids');
$city_data[] = array('accid' => 'USMN0586', 'name' => 'Pemberton');
$city_data[] = array('accid' => 'USMN0587', 'name' => 'Pengilly');
$city_data[] = array('accid' => 'USMN0588', 'name' => 'Pennington');
$city_data[] = array('accid' => 'USMN0589', 'name' => 'Pennock');
$city_data[] = array('accid' => 'USMN0590', 'name' => 'Pequot Lakes');
$city_data[] = array('accid' => 'USMN0591', 'name' => 'Perham');
$city_data[] = array('accid' => 'USMN0592', 'name' => 'Perley');
$city_data[] = array('accid' => 'USMN0593', 'name' => 'Peterson');
$city_data[] = array('accid' => 'USMN0594', 'name' => 'Pierz');
$city_data[] = array('accid' => 'USMN0595', 'name' => 'Pillager');
$city_data[] = array('accid' => 'USMN0596', 'name' => 'Pine City');
$city_data[] = array('accid' => 'USMN0597', 'name' => 'Pine Island');
$city_data[] = array('accid' => 'USMN0598', 'name' => 'Pine River');
$city_data[] = array('accid' => 'USMN0599', 'name' => 'Pipestone');
$city_data[] = array('accid' => 'USMN0600', 'name' => 'Plainview');
$city_data[] = array('accid' => 'USMN0601', 'name' => 'Plato');
$city_data[] = array('accid' => 'USMN0602', 'name' => 'Plummer');
$city_data[] = array('accid' => 'USMN0603', 'name' => 'Ponemah');
$city_data[] = array('accid' => 'USMN0604', 'name' => 'Ponsford');
$city_data[] = array('accid' => 'USMN0605', 'name' => 'Porter');
$city_data[] = array('accid' => 'USMN0606', 'name' => 'Preston');
$city_data[] = array('accid' => 'USMN0607', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USMN0608', 'name' => 'Prinsburg');
$city_data[] = array('accid' => 'USMN0609', 'name' => 'Prior Lake');
$city_data[] = array('accid' => 'USMN0610', 'name' => 'Puposky');
$city_data[] = array('accid' => 'USMN0611', 'name' => 'Racine');
$city_data[] = array('accid' => 'USMN0612', 'name' => 'Randall');
$city_data[] = array('accid' => 'USMN0613', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USMN0614', 'name' => 'Ranier');
$city_data[] = array('accid' => 'USMN0615', 'name' => 'Ray');
$city_data[] = array('accid' => 'USMN0616', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USMN0617', 'name' => 'Reading');
$city_data[] = array('accid' => 'USMN0618', 'name' => 'Reads Landing');
$city_data[] = array('accid' => 'USMN0619', 'name' => 'Red Lake Falls');
$city_data[] = array('accid' => 'USMN0620', 'name' => 'Red Wing');
$city_data[] = array('accid' => 'USMN0621', 'name' => 'Redby');
$city_data[] = array('accid' => 'USMN0622', 'name' => 'Redlake');
$city_data[] = array('accid' => 'USMN0623', 'name' => 'Redwood Falls');
$city_data[] = array('accid' => 'USMN0624', 'name' => 'Remer');
$city_data[] = array('accid' => 'USMN0625', 'name' => 'Renville');
$city_data[] = array('accid' => 'USMN0626', 'name' => 'Revere');
$city_data[] = array('accid' => 'USMN0627', 'name' => 'Rice');
$city_data[] = array('accid' => 'USMN0628', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USMN0629', 'name' => 'Richville');
$city_data[] = array('accid' => 'USMN0630', 'name' => 'Richwood');
$city_data[] = array('accid' => 'USMN0631', 'name' => 'Rochert');
$city_data[] = array('accid' => 'USMN0632', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USMN0633', 'name' => 'Rock Creek');
$city_data[] = array('accid' => 'USMN0634', 'name' => 'Rockford');
$city_data[] = array('accid' => 'USMN0635', 'name' => 'Rockville');
$city_data[] = array('accid' => 'USMN0636', 'name' => 'Rogers');
$city_data[] = array('accid' => 'USMN0637', 'name' => 'Rollingstone');
$city_data[] = array('accid' => 'USMN0638', 'name' => 'Roosevelt');
$city_data[] = array('accid' => 'USMN0639', 'name' => 'Roscoe');
$city_data[] = array('accid' => 'USMN0640', 'name' => 'Rose Creek');
$city_data[] = array('accid' => 'USMN0641', 'name' => 'Roseau');
$city_data[] = array('accid' => 'USMN0642', 'name' => 'Rosemount');
$city_data[] = array('accid' => 'USMN0643', 'name' => 'Rothsay');
$city_data[] = array('accid' => 'USMN0644', 'name' => 'Round Lake');
$city_data[] = array('accid' => 'USMN0645', 'name' => 'Royalton');
$city_data[] = array('accid' => 'USMN0646', 'name' => 'Rush City');
$city_data[] = array('accid' => 'USMN0647', 'name' => 'Rushford');
$city_data[] = array('accid' => 'USMN0648', 'name' => 'Rushmore');
$city_data[] = array('accid' => 'USMN0649', 'name' => 'Russell');
$city_data[] = array('accid' => 'USMN0650', 'name' => 'Ruthton');
$city_data[] = array('accid' => 'USMN0651', 'name' => 'Sabin');
$city_data[] = array('accid' => 'USMN0652', 'name' => 'Sacred Heart');
$city_data[] = array('accid' => 'USMN0653', 'name' => 'Saginaw');
$city_data[] = array('accid' => 'USMN0654', 'name' => 'Saint Bonifacius');
$city_data[] = array('accid' => 'USMN0655', 'name' => 'Saint Charles');
$city_data[] = array('accid' => 'USMN0656', 'name' => 'Saint Clair');
$city_data[] = array('accid' => 'USMN0657', 'name' => 'Saint Cloud');
$city_data[] = array('accid' => 'USMN0658', 'name' => 'Saint Francis');
$city_data[] = array('accid' => 'USMN0659', 'name' => 'Saint Hilaire');
$city_data[] = array('accid' => 'USMN0660', 'name' => 'Saint James');
$city_data[] = array('accid' => 'USMN0661', 'name' => 'Saint Joseph');
$city_data[] = array('accid' => 'USMN0662', 'name' => 'Saint Martin');
$city_data[] = array('accid' => 'USMN0663', 'name' => 'Saint Michael');
$city_data[] = array('accid' => 'USMN0664', 'name' => 'Saint Paul');
$city_data[] = array('accid' => 'USMN0665', 'name' => 'Saint Paul Park');
$city_data[] = array('accid' => 'USMN0666', 'name' => 'Saint Peter');
$city_data[] = array('accid' => 'USMN0667', 'name' => 'Saint Stephen');
$city_data[] = array('accid' => 'USMN0668', 'name' => 'Saint Vincent');
$city_data[] = array('accid' => 'USMN0669', 'name' => 'Salol');
$city_data[] = array('accid' => 'USMN0670', 'name' => 'Sanborn');
$city_data[] = array('accid' => 'USMN0671', 'name' => 'Sandstone');
$city_data[] = array('accid' => 'USMN0672', 'name' => 'Santiago');
$city_data[] = array('accid' => 'USMN0673', 'name' => 'Sargeant');
$city_data[] = array('accid' => 'USMN0674', 'name' => 'Sartell');
$city_data[] = array('accid' => 'USMN0675', 'name' => 'Sauk Centre');
$city_data[] = array('accid' => 'USMN0676', 'name' => 'Sauk Rapids');
$city_data[] = array('accid' => 'USMN0677', 'name' => 'Savage');
$city_data[] = array('accid' => 'USMN0678', 'name' => 'Sawyer');
$city_data[] = array('accid' => 'USMN0679', 'name' => 'Scandia');
$city_data[] = array('accid' => 'USMN0680', 'name' => 'Schroeder');
$city_data[] = array('accid' => 'USMN0681', 'name' => 'Seaforth');
$city_data[] = array('accid' => 'USMN0682', 'name' => 'Searles');
$city_data[] = array('accid' => 'USMN0683', 'name' => 'Sebeka');
$city_data[] = array('accid' => 'USMN0684', 'name' => 'Shafer');
$city_data[] = array('accid' => 'USMN0685', 'name' => 'Shakopee');
$city_data[] = array('accid' => 'USMN0686', 'name' => 'Shelly');
$city_data[] = array('accid' => 'USMN0687', 'name' => 'Sherburn');
$city_data[] = array('accid' => 'USMN0688', 'name' => 'Shevlin');
$city_data[] = array('accid' => 'USMN0689', 'name' => 'Side Lake');
$city_data[] = array('accid' => 'USMN0690', 'name' => 'Silver Bay');
$city_data[] = array('accid' => 'USMN0691', 'name' => 'Silver Creek');
$city_data[] = array('accid' => 'USMN0692', 'name' => 'Silver Lake');
$city_data[] = array('accid' => 'USMN0693', 'name' => 'Slayton');
$city_data[] = array('accid' => 'USMN0694', 'name' => 'Sleepy Eye');
$city_data[] = array('accid' => 'USMN0695', 'name' => 'Solway');
$city_data[] = array('accid' => 'USMN0696', 'name' => 'Soudan');
$city_data[] = array('accid' => 'USMN0697', 'name' => 'South Haven');
$city_data[] = array('accid' => 'USMN0698', 'name' => 'South International Falls');
$city_data[] = array('accid' => 'USMN0699', 'name' => 'South Saint Paul');
$city_data[] = array('accid' => 'USMN0700', 'name' => 'Spicer');
$city_data[] = array('accid' => 'USMN0701', 'name' => 'Spring Grove');
$city_data[] = array('accid' => 'USMN0702', 'name' => 'Spring Lake');
$city_data[] = array('accid' => 'USMN0703', 'name' => 'Spring Park');
$city_data[] = array('accid' => 'USMN0704', 'name' => 'Spring Valley');
$city_data[] = array('accid' => 'USMN0705', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USMN0706', 'name' => 'Squaw Lake');
$city_data[] = array('accid' => 'USMN0707', 'name' => 'Stacy');
$city_data[] = array('accid' => 'USMN0708', 'name' => 'Stanchfield');
$city_data[] = array('accid' => 'USMN0709', 'name' => 'Staples');
$city_data[] = array('accid' => 'USMN0710', 'name' => 'Starbuck');
$city_data[] = array('accid' => 'USMN0711', 'name' => 'Steen');
$city_data[] = array('accid' => 'USMN0712', 'name' => 'Stephen');
$city_data[] = array('accid' => 'USMN0713', 'name' => 'Stewart');
$city_data[] = array('accid' => 'USMN0714', 'name' => 'Stewartville');
$city_data[] = array('accid' => 'USMN0715', 'name' => 'Stillwater');
$city_data[] = array('accid' => 'USMN0716', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USMN0717', 'name' => 'Storden');
$city_data[] = array('accid' => 'USMN0718', 'name' => 'Strandquist');
$city_data[] = array('accid' => 'USMN0719', 'name' => 'Strathcona');
$city_data[] = array('accid' => 'USMN0720', 'name' => 'Sturgeon Lake');
$city_data[] = array('accid' => 'USMN0721', 'name' => 'Sunburg');
$city_data[] = array('accid' => 'USMN0722', 'name' => 'Swan River');
$city_data[] = array('accid' => 'USMN0723', 'name' => 'Swanville');
$city_data[] = array('accid' => 'USMN0724', 'name' => 'Swatara');
$city_data[] = array('accid' => 'USMN0725', 'name' => 'Swift');
$city_data[] = array('accid' => 'USMN0726', 'name' => 'Taconite');
$city_data[] = array('accid' => 'USMN0727', 'name' => 'Talmoon');
$city_data[] = array('accid' => 'USMN0728', 'name' => 'Tamarack');
$city_data[] = array('accid' => 'USMN0729', 'name' => 'Taopi');
$city_data[] = array('accid' => 'USMN0730', 'name' => 'Taunton');
$city_data[] = array('accid' => 'USMN0731', 'name' => 'Taylors Falls');
$city_data[] = array('accid' => 'USMN0732', 'name' => 'Tenstrike');
$city_data[] = array('accid' => 'USMN0733', 'name' => 'Thief River Falls');
$city_data[] = array('accid' => 'USMN0734', 'name' => 'Tintah');
$city_data[] = array('accid' => 'USMN0735', 'name' => 'Tofte');
$city_data[] = array('accid' => 'USMN0736', 'name' => 'Tower');
$city_data[] = array('accid' => 'USMN0737', 'name' => 'Tracy');
$city_data[] = array('accid' => 'USMN0738', 'name' => 'Trail');
$city_data[] = array('accid' => 'USMN0739', 'name' => 'Trimont');
$city_data[] = array('accid' => 'USMN0740', 'name' => 'Trosky');
$city_data[] = array('accid' => 'USMN0741', 'name' => 'Truman');
$city_data[] = array('accid' => 'USMN0742', 'name' => 'Twig');
$city_data[] = array('accid' => 'USMN0743', 'name' => 'Twin Lakes');
$city_data[] = array('accid' => 'USMN0744', 'name' => 'Twin Valley');
$city_data[] = array('accid' => 'USMN0745', 'name' => 'Two Harbors');
$city_data[] = array('accid' => 'USMN0746', 'name' => 'Tyler');
$city_data[] = array('accid' => 'USMN0747', 'name' => 'Ulen');
$city_data[] = array('accid' => 'USMN0748', 'name' => 'Underwood');
$city_data[] = array('accid' => 'USMN0749', 'name' => 'Upsala');
$city_data[] = array('accid' => 'USMN0750', 'name' => 'Utica');
$city_data[] = array('accid' => 'USMN0751', 'name' => 'Vergas');
$city_data[] = array('accid' => 'USMN0752', 'name' => 'Vermillion');
$city_data[] = array('accid' => 'USMN0753', 'name' => 'Verndale');
$city_data[] = array('accid' => 'USMN0754', 'name' => 'Vernon Center');
$city_data[] = array('accid' => 'USMN0755', 'name' => 'Vesta');
$city_data[] = array('accid' => 'USMN0756', 'name' => 'Victoria');
$city_data[] = array('accid' => 'USMN0757', 'name' => 'Viking');
$city_data[] = array('accid' => 'USMN0758', 'name' => 'Villard');
$city_data[] = array('accid' => 'USMN0759', 'name' => 'Vining');
$city_data[] = array('accid' => 'USMN0760', 'name' => 'Virginia');
$city_data[] = array('accid' => 'USMN0762', 'name' => 'Wabasha');
$city_data[] = array('accid' => 'USMN0763', 'name' => 'Wabasso');
$city_data[] = array('accid' => 'USMN0764', 'name' => 'Waconia');
$city_data[] = array('accid' => 'USMN0765', 'name' => 'Wadena');
$city_data[] = array('accid' => 'USMN0766', 'name' => 'Wahkon');
$city_data[] = array('accid' => 'USMN0767', 'name' => 'Waite Park');
$city_data[] = array('accid' => 'USMN0768', 'name' => 'Waldorf');
$city_data[] = array('accid' => 'USMN0769', 'name' => 'Walker');
$city_data[] = array('accid' => 'USMN0770', 'name' => 'Walnut Grove');
$city_data[] = array('accid' => 'USMN0771', 'name' => 'Waltham');
$city_data[] = array('accid' => 'USMN0772', 'name' => 'Wanamingo');
$city_data[] = array('accid' => 'USMN0773', 'name' => 'Wanda');
$city_data[] = array('accid' => 'USMN0774', 'name' => 'Wannaska');
$city_data[] = array('accid' => 'USMN0775', 'name' => 'Warba');
$city_data[] = array('accid' => 'USMN0776', 'name' => 'Warren');
$city_data[] = array('accid' => 'USMN0777', 'name' => 'Warroad');
$city_data[] = array('accid' => 'USMN0778', 'name' => 'Warsaw');
$city_data[] = array('accid' => 'USMN0779', 'name' => 'Waseca');
$city_data[] = array('accid' => 'USMN0780', 'name' => 'Waskish');
$city_data[] = array('accid' => 'USMN0781', 'name' => 'Watertown');
$city_data[] = array('accid' => 'USMN0782', 'name' => 'Waterville');
$city_data[] = array('accid' => 'USMN0783', 'name' => 'Watkins');
$city_data[] = array('accid' => 'USMN0784', 'name' => 'Watson');
$city_data[] = array('accid' => 'USMN0785', 'name' => 'Waubun');
$city_data[] = array('accid' => 'USMN0786', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USMN0787', 'name' => 'Wayzata');
$city_data[] = array('accid' => 'USMN0788', 'name' => 'Webster');
$city_data[] = array('accid' => 'USMN0789', 'name' => 'Welch');
$city_data[] = array('accid' => 'USMN0790', 'name' => 'Welcome');
$city_data[] = array('accid' => 'USMN0791', 'name' => 'Wells');
$city_data[] = array('accid' => 'USMN0792', 'name' => 'Wendell');
$city_data[] = array('accid' => 'USMN0793', 'name' => 'West Concord');
$city_data[] = array('accid' => 'USMN0794', 'name' => 'West Union');
$city_data[] = array('accid' => 'USMN0795', 'name' => 'Westbrook');
$city_data[] = array('accid' => 'USMN0796', 'name' => 'Wheaton');
$city_data[] = array('accid' => 'USMN0797', 'name' => 'White Earth');
$city_data[] = array('accid' => 'USMN0798', 'name' => 'Willernie');
$city_data[] = array('accid' => 'USMN0799', 'name' => 'Williams');
$city_data[] = array('accid' => 'USMN0800', 'name' => 'Willmar');
$city_data[] = array('accid' => 'USMN0801', 'name' => 'Willow River');
$city_data[] = array('accid' => 'USMN0802', 'name' => 'Wilmont');
$city_data[] = array('accid' => 'USMN0803', 'name' => 'Wilton');
$city_data[] = array('accid' => 'USMN0804', 'name' => 'Windom');
$city_data[] = array('accid' => 'USMN0805', 'name' => 'Winger');
$city_data[] = array('accid' => 'USMN0806', 'name' => 'Winnebago');
$city_data[] = array('accid' => 'USMN0807', 'name' => 'Winona');
$city_data[] = array('accid' => 'USMN0808', 'name' => 'Winsted');
$city_data[] = array('accid' => 'USMN0809', 'name' => 'Winthrop');
$city_data[] = array('accid' => 'USMN0810', 'name' => 'Winton');
$city_data[] = array('accid' => 'USMN0811', 'name' => 'Wirt');
$city_data[] = array('accid' => 'USMN0812', 'name' => 'Wolf Lake');
$city_data[] = array('accid' => 'USMN0813', 'name' => 'Wolverton');
$city_data[] = array('accid' => 'USMN0814', 'name' => 'Wood Lake');
$city_data[] = array('accid' => 'USMN0815', 'name' => 'Woodstock');
$city_data[] = array('accid' => 'USMN0816', 'name' => 'Worthington');
$city_data[] = array('accid' => 'USMN0817', 'name' => 'Wrenshall');
$city_data[] = array('accid' => 'USMN0818', 'name' => 'Wright');
$city_data[] = array('accid' => 'USMN0819', 'name' => 'Wykoff');
$city_data[] = array('accid' => 'USMN0820', 'name' => 'Wyoming');
$city_data[] = array('accid' => 'USMN0821', 'name' => 'Young America');
$city_data[] = array('accid' => 'USMN0822', 'name' => 'Zimmerman');
$city_data[] = array('accid' => 'USMN0823', 'name' => 'Zumbro Falls');
$city_data[] = array('accid' => 'USMN0824', 'name' => 'Zumbrota');

?>
