<?php

// City package for USA: Missouri

$city_name = 'USA: Missouri';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USMO0001', 'name' => 'Adrian');
$city_data[] = array('accid' => 'USMO0002', 'name' => 'Advance');
$city_data[] = array('accid' => 'USMO0003', 'name' => 'Agency');
$city_data[] = array('accid' => 'USMO0004', 'name' => 'Alba');
$city_data[] = array('accid' => 'USMO0005', 'name' => 'Albany');
$city_data[] = array('accid' => 'USMO0006', 'name' => 'Aldrich');
$city_data[] = array('accid' => 'USMO0007', 'name' => 'Alexandria');
$city_data[] = array('accid' => 'USMO0008', 'name' => 'Allendale');
$city_data[] = array('accid' => 'USMO0009', 'name' => 'Allenton');
$city_data[] = array('accid' => 'USMO0010', 'name' => 'Alma');
$city_data[] = array('accid' => 'USMO0011', 'name' => 'Altamont');
$city_data[] = array('accid' => 'USMO0012', 'name' => 'Altenburg');
$city_data[] = array('accid' => 'USMO0013', 'name' => 'Alton');
$city_data[] = array('accid' => 'USMO0014', 'name' => 'Amazonia');
$city_data[] = array('accid' => 'USMO0015', 'name' => 'Amity');
$city_data[] = array('accid' => 'USMO0016', 'name' => 'Amoret');
$city_data[] = array('accid' => 'USMO0017', 'name' => 'Amsterdam');
$city_data[] = array('accid' => 'USMO0018', 'name' => 'Anabel');
$city_data[] = array('accid' => 'USMO0019', 'name' => 'Anderson');
$city_data[] = array('accid' => 'USMO0020', 'name' => 'Annada');
$city_data[] = array('accid' => 'USMO0021', 'name' => 'Annapolis');
$city_data[] = array('accid' => 'USMO0022', 'name' => 'Anniston');
$city_data[] = array('accid' => 'USMO0023', 'name' => 'Appleton City');
$city_data[] = array('accid' => 'USMO0024', 'name' => 'Arbela');
$city_data[] = array('accid' => 'USMO0025', 'name' => 'Arbyrd');
$city_data[] = array('accid' => 'USMO0026', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USMO0027', 'name' => 'Archie');
$city_data[] = array('accid' => 'USMO0028', 'name' => 'Arcola');
$city_data[] = array('accid' => 'USMO0029', 'name' => 'Argyle');
$city_data[] = array('accid' => 'USMO0030', 'name' => 'Armstrong');
$city_data[] = array('accid' => 'USMO0031', 'name' => 'Arnold');
$city_data[] = array('accid' => 'USMO0032', 'name' => 'Arrow Rock');
$city_data[] = array('accid' => 'USMO0033', 'name' => 'Asbury');
$city_data[] = array('accid' => 'USMO0034', 'name' => 'Ash Grove');
$city_data[] = array('accid' => 'USMO0035', 'name' => 'Ashburn');
$city_data[] = array('accid' => 'USMO0036', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USMO0037', 'name' => 'Atlanta');
$city_data[] = array('accid' => 'USMO0038', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USMO0039', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USMO0040', 'name' => 'Auxvasse');
$city_data[] = array('accid' => 'USMO0041', 'name' => 'Ava');
$city_data[] = array('accid' => 'USMO0043', 'name' => 'Avilla');
$city_data[] = array('accid' => 'USMO0044', 'name' => 'Bakersfield');
$city_data[] = array('accid' => 'USMO0045', 'name' => 'Ballwin');
$city_data[] = array('accid' => 'USMO0046', 'name' => 'Baring');
$city_data[] = array('accid' => 'USMO0047', 'name' => 'Barnard');
$city_data[] = array('accid' => 'USMO0048', 'name' => 'Barnett');
$city_data[] = array('accid' => 'USMO0049', 'name' => 'Barnhart');
$city_data[] = array('accid' => 'USMO0050', 'name' => 'Bates City');
$city_data[] = array('accid' => 'USMO0051', 'name' => 'Beaufort');
$city_data[] = array('accid' => 'USMO0052', 'name' => 'Belgrade');
$city_data[] = array('accid' => 'USMO0053', 'name' => 'Bell City');
$city_data[] = array('accid' => 'USMO0054', 'name' => 'Belle');
$city_data[] = array('accid' => 'USMO0055', 'name' => 'Belleview');
$city_data[] = array('accid' => 'USMO0056', 'name' => 'Bellflower');
$city_data[] = array('accid' => 'USMO0057', 'name' => 'Belton');
$city_data[] = array('accid' => 'USMO0058', 'name' => 'Bendavis');
$city_data[] = array('accid' => 'USMO0059', 'name' => 'Benton');
$city_data[] = array('accid' => 'USMO0060', 'name' => 'Benton City');
$city_data[] = array('accid' => 'USMO0061', 'name' => 'Berger');
$city_data[] = array('accid' => 'USMO0062', 'name' => 'Bernie');
$city_data[] = array('accid' => 'USMO0063', 'name' => 'Bertrand');
$city_data[] = array('accid' => 'USMO0064', 'name' => 'Bethany');
$city_data[] = array('accid' => 'USMO0065', 'name' => 'Bethel');
$city_data[] = array('accid' => 'USMO0066', 'name' => 'Beulah');
$city_data[] = array('accid' => 'USMO0067', 'name' => 'Bevier');
$city_data[] = array('accid' => 'USMO0068', 'name' => 'Billings');
$city_data[] = array('accid' => 'USMO0069', 'name' => 'Birch Tree');
$city_data[] = array('accid' => 'USMO0070', 'name' => 'Bismarck');
$city_data[] = array('accid' => 'USMO0071', 'name' => 'Bixby');
$city_data[] = array('accid' => 'USMO0072', 'name' => 'Black');
$city_data[] = array('accid' => 'USMO0073', 'name' => 'Blackburn');
$city_data[] = array('accid' => 'USMO0074', 'name' => 'Blackwater');
$city_data[] = array('accid' => 'USMO0075', 'name' => 'Blackwell');
$city_data[] = array('accid' => 'USMO0076', 'name' => 'Blairstown');
$city_data[] = array('accid' => 'USMO0077', 'name' => 'Bland');
$city_data[] = array('accid' => 'USMO0078', 'name' => 'Blodgett');
$city_data[] = array('accid' => 'USMO0079', 'name' => 'Bloomfield');
$city_data[] = array('accid' => 'USMO0080', 'name' => 'Bloomsdale');
$city_data[] = array('accid' => 'USMO0081', 'name' => 'Blue Eye');
$city_data[] = array('accid' => 'USMO0082', 'name' => 'Blue Springs');
$city_data[] = array('accid' => 'USMO0083', 'name' => 'Blythedale');
$city_data[] = array('accid' => 'USMO0084', 'name' => 'Bogard');
$city_data[] = array('accid' => 'USMO0086', 'name' => 'Bolckow');
$city_data[] = array('accid' => 'USMO0087', 'name' => 'Bolivar');
$city_data[] = array('accid' => 'USMO0088', 'name' => 'Bonne Terre');
$city_data[] = array('accid' => 'USMO0089', 'name' => 'Bonnots Mill');
$city_data[] = array('accid' => 'USMO0090', 'name' => 'Boonville');
$city_data[] = array('accid' => 'USMO0091', 'name' => 'Boss');
$city_data[] = array('accid' => 'USMO0092', 'name' => 'Bosworth');
$city_data[] = array('accid' => 'USMO0093', 'name' => 'Bourbon');
$city_data[] = array('accid' => 'USMO0094', 'name' => 'Bowling Green');
$city_data[] = array('accid' => 'USMO0095', 'name' => 'Bradleyville');
$city_data[] = array('accid' => 'USMO0096', 'name' => 'Bragg City');
$city_data[] = array('accid' => 'USMO0097', 'name' => 'Braggadocio');
$city_data[] = array('accid' => 'USMO0098', 'name' => 'Brandsville');
$city_data[] = array('accid' => 'USMO0099', 'name' => 'Branson');
$city_data[] = array('accid' => 'USMO0100', 'name' => 'Brashear');
$city_data[] = array('accid' => 'USMO0101', 'name' => 'Braymer');
$city_data[] = array('accid' => 'USMO0102', 'name' => 'Brazeau');
$city_data[] = array('accid' => 'USMO0103', 'name' => 'Breckenridge');
$city_data[] = array('accid' => 'USMO0104', 'name' => 'Briar');
$city_data[] = array('accid' => 'USMO0105', 'name' => 'Bridgeton');
$city_data[] = array('accid' => 'USMO0106', 'name' => 'Brighton');
$city_data[] = array('accid' => 'USMO0107', 'name' => 'Brinktown');
$city_data[] = array('accid' => 'USMO0108', 'name' => 'Brixey');
$city_data[] = array('accid' => 'USMO0109', 'name' => 'Bronaugh');
$city_data[] = array('accid' => 'USMO0110', 'name' => 'Brookfield');
$city_data[] = array('accid' => 'USMO0111', 'name' => 'Brookline Station');
$city_data[] = array('accid' => 'USMO0112', 'name' => 'Broseley');
$city_data[] = array('accid' => 'USMO0113', 'name' => 'Browning');
$city_data[] = array('accid' => 'USMO0114', 'name' => 'Brownwood');
$city_data[] = array('accid' => 'USMO0115', 'name' => 'Brumley');
$city_data[] = array('accid' => 'USMO0116', 'name' => 'Bruner');
$city_data[] = array('accid' => 'USMO0117', 'name' => 'Brunswick');
$city_data[] = array('accid' => 'USMO0118', 'name' => 'Bucklin');
$city_data[] = array('accid' => 'USMO0119', 'name' => 'Buckner');
$city_data[] = array('accid' => 'USMO0120', 'name' => 'Bucyrus');
$city_data[] = array('accid' => 'USMO0121', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USMO0122', 'name' => 'Bunceton');
$city_data[] = array('accid' => 'USMO0123', 'name' => 'Bunker');
$city_data[] = array('accid' => 'USMO0124', 'name' => 'Burfordville');
$city_data[] = array('accid' => 'USMO0125', 'name' => 'Burlington Junction');
$city_data[] = array('accid' => 'USMO0126', 'name' => 'Butler');
$city_data[] = array('accid' => 'USMO0127', 'name' => 'Butterfield');
$city_data[] = array('accid' => 'USMO0128', 'name' => 'Cabool');
$city_data[] = array('accid' => 'USMO0129', 'name' => 'Cadet');
$city_data[] = array('accid' => 'USMO0130', 'name' => 'Cainsville');
$city_data[] = array('accid' => 'USMO0131', 'name' => 'Cairo');
$city_data[] = array('accid' => 'USMO0132', 'name' => 'Caledonia');
$city_data[] = array('accid' => 'USMO0133', 'name' => 'Calhoun');
$city_data[] = array('accid' => 'USMO0134', 'name' => 'California');
$city_data[] = array('accid' => 'USMO0135', 'name' => 'Callao');
$city_data[] = array('accid' => 'USMO0136', 'name' => 'Camden');
$city_data[] = array('accid' => 'USMO0137', 'name' => 'Camden Point');
$city_data[] = array('accid' => 'USMO0138', 'name' => 'Camdenton');
$city_data[] = array('accid' => 'USMO0139', 'name' => 'Cameron');
$city_data[] = array('accid' => 'USMO0140', 'name' => 'Campbell');
$city_data[] = array('accid' => 'USMO0141', 'name' => 'Canalou');
$city_data[] = array('accid' => 'USMO0142', 'name' => 'Canton');
$city_data[] = array('accid' => 'USMO0143', 'name' => 'Cape Fair');
$city_data[] = array('accid' => 'USMO0144', 'name' => 'Cape Girardeau');
$city_data[] = array('accid' => 'USMO0145', 'name' => 'Caplinger Mills');
$city_data[] = array('accid' => 'USMO0146', 'name' => 'Cardwell');
$city_data[] = array('accid' => 'USMO0147', 'name' => 'Carl Junction');
$city_data[] = array('accid' => 'USMO0148', 'name' => 'Carrollton');
$city_data[] = array('accid' => 'USMO0149', 'name' => 'Carterville');
$city_data[] = array('accid' => 'USMO0150', 'name' => 'Carthage');
$city_data[] = array('accid' => 'USMO0151', 'name' => 'Caruthersville');
$city_data[] = array('accid' => 'USMO0152', 'name' => 'Cascade');
$city_data[] = array('accid' => 'USMO0153', 'name' => 'Cassville');
$city_data[] = array('accid' => 'USMO0154', 'name' => 'Catawissa');
$city_data[] = array('accid' => 'USMO0155', 'name' => 'Catron');
$city_data[] = array('accid' => 'USMO0156', 'name' => 'Caulfield');
$city_data[] = array('accid' => 'USMO0157', 'name' => 'Cedar City');
$city_data[] = array('accid' => 'USMO0158', 'name' => 'Cedar Hill');
$city_data[] = array('accid' => 'USMO0159', 'name' => 'Cedarcreek');
$city_data[] = array('accid' => 'USMO0160', 'name' => 'Center');
$city_data[] = array('accid' => 'USMO0161', 'name' => 'Centertown');
$city_data[] = array('accid' => 'USMO0162', 'name' => 'Centerview');
$city_data[] = array('accid' => 'USMO0163', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USMO0164', 'name' => 'Centralia');
$city_data[] = array('accid' => 'USMO0165', 'name' => 'Chadwick');
$city_data[] = array('accid' => 'USMO0166', 'name' => 'Chaffee');
$city_data[] = array('accid' => 'USMO0167', 'name' => 'Chamois');
$city_data[] = array('accid' => 'USMO0168', 'name' => 'Charleston');
$city_data[] = array('accid' => 'USMO0169', 'name' => 'Cherryville');
$city_data[] = array('accid' => 'USMO0170', 'name' => 'Chesterfield');
$city_data[] = array('accid' => 'USMO0171', 'name' => 'Chestnutridge');
$city_data[] = array('accid' => 'USMO0172', 'name' => 'Chilhowee');
$city_data[] = array('accid' => 'USMO0173', 'name' => 'Chillicothe');
$city_data[] = array('accid' => 'USMO0174', 'name' => 'Chula');
$city_data[] = array('accid' => 'USMO0175', 'name' => 'Clarence');
$city_data[] = array('accid' => 'USMO0176', 'name' => 'Clark');
$city_data[] = array('accid' => 'USMO0177', 'name' => 'Clarksburg');
$city_data[] = array('accid' => 'USMO0178', 'name' => 'Clarksdale');
$city_data[] = array('accid' => 'USMO0179', 'name' => 'Clarksville');
$city_data[] = array('accid' => 'USMO0180', 'name' => 'Clarkton');
$city_data[] = array('accid' => 'USMO0181', 'name' => 'Clearmont');
$city_data[] = array('accid' => 'USMO0182', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USMO0183', 'name' => 'Clever');
$city_data[] = array('accid' => 'USMO0184', 'name' => 'Clifton Hill');
$city_data[] = array('accid' => 'USMO0185', 'name' => 'Climax Springs');
$city_data[] = array('accid' => 'USMO0186', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USMO0187', 'name' => 'Clubb');
$city_data[] = array('accid' => 'USMO0188', 'name' => 'Clyde');
$city_data[] = array('accid' => 'USMO0189', 'name' => 'Coatsville');
$city_data[] = array('accid' => 'USMO0190', 'name' => 'Coffey');
$city_data[] = array('accid' => 'USMO0191', 'name' => 'Cole Camp');
$city_data[] = array('accid' => 'USMO0192', 'name' => 'Collins');
$city_data[] = array('accid' => 'USMO0193', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USMO0194', 'name' => 'Commerce');
$city_data[] = array('accid' => 'USMO0195', 'name' => 'Conception');
$city_data[] = array('accid' => 'USMO0196', 'name' => 'Conception Junction');
$city_data[] = array('accid' => 'USMO0197', 'name' => 'Concordia');
$city_data[] = array('accid' => 'USMO0198', 'name' => 'Conran');
$city_data[] = array('accid' => 'USMO0199', 'name' => 'Conway');
$city_data[] = array('accid' => 'USMO0200', 'name' => 'Cook Station');
$city_data[] = array('accid' => 'USMO0201', 'name' => 'Cooter');
$city_data[] = array('accid' => 'USMO0202', 'name' => 'Corder');
$city_data[] = array('accid' => 'USMO0203', 'name' => 'Cosby');
$city_data[] = array('accid' => 'USMO0204', 'name' => 'Cottleville');
$city_data[] = array('accid' => 'USMO0205', 'name' => 'Couch');
$city_data[] = array('accid' => 'USMO0206', 'name' => 'Cowgill');
$city_data[] = array('accid' => 'USMO0207', 'name' => 'Craig');
$city_data[] = array('accid' => 'USMO0208', 'name' => 'Crane');
$city_data[] = array('accid' => 'USMO0209', 'name' => 'Creighton');
$city_data[] = array('accid' => 'USMO0210', 'name' => 'Crocker');
$city_data[] = array('accid' => 'USMO0211', 'name' => 'Cross Timbers');
$city_data[] = array('accid' => 'USMO0212', 'name' => 'Crystal City');
$city_data[] = array('accid' => 'USMO0213', 'name' => 'Cuba');
$city_data[] = array('accid' => 'USMO0214', 'name' => 'Curryville');
$city_data[] = array('accid' => 'USMO0215', 'name' => 'Dadeville');
$city_data[] = array('accid' => 'USMO0216', 'name' => 'Daisy');
$city_data[] = array('accid' => 'USMO0217', 'name' => 'Dalton');
$city_data[] = array('accid' => 'USMO0218', 'name' => 'Darlington');
$city_data[] = array('accid' => 'USMO0219', 'name' => 'Davisville');
$city_data[] = array('accid' => 'USMO0220', 'name' => 'Dawn');
$city_data[] = array('accid' => 'USMO0221', 'name' => 'De Kalb');
$city_data[] = array('accid' => 'USMO0222', 'name' => 'De Soto');
$city_data[] = array('accid' => 'USMO0223', 'name' => 'De Witt');
$city_data[] = array('accid' => 'USMO0224', 'name' => 'Dearborn');
$city_data[] = array('accid' => 'USMO0225', 'name' => 'Deepwater');
$city_data[] = array('accid' => 'USMO0226', 'name' => 'Deerfield');
$city_data[] = array('accid' => 'USMO0227', 'name' => 'Deering');
$city_data[] = array('accid' => 'USMO0228', 'name' => 'Defiance');
$city_data[] = array('accid' => 'USMO0229', 'name' => 'Delta');
$city_data[] = array('accid' => 'USMO0230', 'name' => 'Denver');
$city_data[] = array('accid' => 'USMO0231', 'name' => 'Des Arc');
$city_data[] = array('accid' => 'USMO0232', 'name' => 'Devils Elbow');
$city_data[] = array('accid' => 'USMO0233', 'name' => 'Dexter');
$city_data[] = array('accid' => 'USMO0234', 'name' => 'Diamond');
$city_data[] = array('accid' => 'USMO0235', 'name' => 'Diggins');
$city_data[] = array('accid' => 'USMO0236', 'name' => 'Dittmer');
$city_data[] = array('accid' => 'USMO0237', 'name' => 'Dixon');
$city_data[] = array('accid' => 'USMO0238', 'name' => 'Doe Run');
$city_data[] = array('accid' => 'USMO0239', 'name' => 'Doniphan');
$city_data[] = array('accid' => 'USMO0240', 'name' => 'Dora');
$city_data[] = array('accid' => 'USMO0241', 'name' => 'Dover');
$city_data[] = array('accid' => 'USMO0242', 'name' => 'Downing');
$city_data[] = array('accid' => 'USMO0243', 'name' => 'Drexel');
$city_data[] = array('accid' => 'USMO0244', 'name' => 'Drury');
$city_data[] = array('accid' => 'USMO0245', 'name' => 'Dudley');
$city_data[] = array('accid' => 'USMO0246', 'name' => 'Duenweg');
$city_data[] = array('accid' => 'USMO0247', 'name' => 'Duke');
$city_data[] = array('accid' => 'USMO0248', 'name' => 'Dunnegan');
$city_data[] = array('accid' => 'USMO0249', 'name' => 'Durham');
$city_data[] = array('accid' => 'USMO0250', 'name' => 'Dutchtown');
$city_data[] = array('accid' => 'USMO0251', 'name' => 'Dutzow');
$city_data[] = array('accid' => 'USMO0252', 'name' => 'Eagle Rock');
$city_data[] = array('accid' => 'USMO0253', 'name' => 'Eagleville');
$city_data[] = array('accid' => 'USMO0254', 'name' => 'Earth City');
$city_data[] = array('accid' => 'USMO0255', 'name' => 'East Lynne');
$city_data[] = array('accid' => 'USMO0256', 'name' => 'East Prairie');
$city_data[] = array('accid' => 'USMO0257', 'name' => 'Easton');
$city_data[] = array('accid' => 'USMO0258', 'name' => 'Edgar Springs');
$city_data[] = array('accid' => 'USMO0259', 'name' => 'Edgerton');
$city_data[] = array('accid' => 'USMO0260', 'name' => 'Edina');
$city_data[] = array('accid' => 'USMO0261', 'name' => 'Edwards');
$city_data[] = array('accid' => 'USMO0262', 'name' => 'El Dorado Springs');
$city_data[] = array('accid' => 'USMO0263', 'name' => 'Eldon');
$city_data[] = array('accid' => 'USMO0264', 'name' => 'Eldridge');
$city_data[] = array('accid' => 'USMO0265', 'name' => 'Elk Creek');
$city_data[] = array('accid' => 'USMO0266', 'name' => 'Elkland');
$city_data[] = array('accid' => 'USMO0267', 'name' => 'Ellington');
$city_data[] = array('accid' => 'USMO0268', 'name' => 'Ellsinore');
$city_data[] = array('accid' => 'USMO0269', 'name' => 'Elmer');
$city_data[] = array('accid' => 'USMO0270', 'name' => 'Elmo');
$city_data[] = array('accid' => 'USMO0271', 'name' => 'Elsberry');
$city_data[] = array('accid' => 'USMO0272', 'name' => 'Emden');
$city_data[] = array('accid' => 'USMO0273', 'name' => 'Eminence');
$city_data[] = array('accid' => 'USMO0274', 'name' => 'Emma');
$city_data[] = array('accid' => 'USMO0275', 'name' => 'Eolia');
$city_data[] = array('accid' => 'USMO0276', 'name' => 'Essex');
$city_data[] = array('accid' => 'USMO0277', 'name' => 'Ethel');
$city_data[] = array('accid' => 'USMO0278', 'name' => 'Etterville');
$city_data[] = array('accid' => 'USMO0279', 'name' => 'Eudora');
$city_data[] = array('accid' => 'USMO0280', 'name' => 'Eugene');
$city_data[] = array('accid' => 'USMO0281', 'name' => 'Eunice');
$city_data[] = array('accid' => 'USMO0282', 'name' => 'Eureka');
$city_data[] = array('accid' => 'USMO0283', 'name' => 'Everton');
$city_data[] = array('accid' => 'USMO0284', 'name' => 'Ewing');
$city_data[] = array('accid' => 'USMO0285', 'name' => 'Excello');
$city_data[] = array('accid' => 'USMO0286', 'name' => 'Excelsior Springs');
$city_data[] = array('accid' => 'USMO0287', 'name' => 'Exeter');
$city_data[] = array('accid' => 'USMO0288', 'name' => 'Fagus');
$city_data[] = array('accid' => 'USMO0289', 'name' => 'Fair Grove');
$city_data[] = array('accid' => 'USMO0290', 'name' => 'Fair Play');
$city_data[] = array('accid' => 'USMO0291', 'name' => 'Fairdealing');
$city_data[] = array('accid' => 'USMO0292', 'name' => 'Fairfax');
$city_data[] = array('accid' => 'USMO0293', 'name' => 'Fairport');
$city_data[] = array('accid' => 'USMO0294', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USMO0295', 'name' => 'Falcon');
$city_data[] = array('accid' => 'USMO0296', 'name' => 'Farber');
$city_data[] = array('accid' => 'USMO0297', 'name' => 'Farley');
$city_data[] = array('accid' => 'USMO0298', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USMO0299', 'name' => 'Farrar');
$city_data[] = array('accid' => 'USMO0300', 'name' => 'Faucett');
$city_data[] = array('accid' => 'USMO0301', 'name' => 'Fayette');
$city_data[] = array('accid' => 'USMO0302', 'name' => 'Fenton');
$city_data[] = array('accid' => 'USMO0303', 'name' => 'Festus');
$city_data[] = array('accid' => 'USMO0304', 'name' => 'Fillmore');
$city_data[] = array('accid' => 'USMO0305', 'name' => 'Fisk');
$city_data[] = array('accid' => 'USMO0306', 'name' => 'Flemington');
$city_data[] = array('accid' => 'USMO0307', 'name' => 'Fletcher');
$city_data[] = array('accid' => 'USMO0308', 'name' => 'Flinthill');
$city_data[] = array('accid' => 'USMO0309', 'name' => 'Florence');
$city_data[] = array('accid' => 'USMO0310', 'name' => 'Florissant');
$city_data[] = array('accid' => 'USMO0311', 'name' => 'Foley');
$city_data[] = array('accid' => 'USMO0312', 'name' => 'Fordland');
$city_data[] = array('accid' => 'USMO0313', 'name' => 'Forest City');
$city_data[] = array('accid' => 'USMO0314', 'name' => 'Foristell');
$city_data[] = array('accid' => 'USMO0315', 'name' => 'Forsyth');
$city_data[] = array('accid' => 'USMO0316', 'name' => 'Fort Leonard Wood');
$city_data[] = array('accid' => 'USMO0317', 'name' => 'Fortuna');
$city_data[] = array('accid' => 'USMO0318', 'name' => 'Foster');
$city_data[] = array('accid' => 'USMO0319', 'name' => 'Frankford');
$city_data[] = array('accid' => 'USMO0320', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USMO0321', 'name' => 'Fredericktown');
$city_data[] = array('accid' => 'USMO0322', 'name' => 'Freeburg');
$city_data[] = array('accid' => 'USMO0323', 'name' => 'Freeman');
$city_data[] = array('accid' => 'USMO0324', 'name' => 'Freistatt');
$city_data[] = array('accid' => 'USMO0325', 'name' => 'Fremont');
$city_data[] = array('accid' => 'USMO0326', 'name' => 'French Village');
$city_data[] = array('accid' => 'USMO0327', 'name' => 'Friedheim');
$city_data[] = array('accid' => 'USMO0328', 'name' => 'Frohna');
$city_data[] = array('accid' => 'USMO0329', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USMO0330', 'name' => 'Gainesville');
$city_data[] = array('accid' => 'USMO0331', 'name' => 'Galena');
$city_data[] = array('accid' => 'USMO0332', 'name' => 'Gallatin');
$city_data[] = array('accid' => 'USMO0333', 'name' => 'Galt');
$city_data[] = array('accid' => 'USMO0334', 'name' => 'Garden City');
$city_data[] = array('accid' => 'USMO0335', 'name' => 'Garrison');
$city_data[] = array('accid' => 'USMO0336', 'name' => 'Gasconade');
$city_data[] = array('accid' => 'USMO0337', 'name' => 'Gatewood');
$city_data[] = array('accid' => 'USMO0338', 'name' => 'Gentry');
$city_data[] = array('accid' => 'USMO0339', 'name' => 'Gerald');
$city_data[] = array('accid' => 'USMO0340', 'name' => 'Gibbs');
$city_data[] = array('accid' => 'USMO0341', 'name' => 'Gibson');
$city_data[] = array('accid' => 'USMO0342', 'name' => 'Gideon');
$city_data[] = array('accid' => 'USMO0343', 'name' => 'Gilliam');
$city_data[] = array('accid' => 'USMO0344', 'name' => 'Gilman City');
$city_data[] = array('accid' => 'USMO0345', 'name' => 'Gipsy');
$city_data[] = array('accid' => 'USMO0346', 'name' => 'Glasgow');
$city_data[] = array('accid' => 'USMO0347', 'name' => 'Glenallen');
$city_data[] = array('accid' => 'USMO0348', 'name' => 'Glencoe');
$city_data[] = array('accid' => 'USMO0349', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USMO0350', 'name' => 'Glover');
$city_data[] = array('accid' => 'USMO0351', 'name' => 'Gobler');
$city_data[] = array('accid' => 'USMO0352', 'name' => 'Golden');
$city_data[] = array('accid' => 'USMO0353', 'name' => 'Golden City');
$city_data[] = array('accid' => 'USMO0354', 'name' => 'Goodman');
$city_data[] = array('accid' => 'USMO0355', 'name' => 'Goodson');
$city_data[] = array('accid' => 'USMO0356', 'name' => 'Gordonville');
$city_data[] = array('accid' => 'USMO0357', 'name' => 'Gorin');
$city_data[] = array('accid' => 'USMO0358', 'name' => 'Gower');
$city_data[] = array('accid' => 'USMO0359', 'name' => 'Graff');
$city_data[] = array('accid' => 'USMO0360', 'name' => 'Graham');
$city_data[] = array('accid' => 'USMO0361', 'name' => 'Grain Valley');
$city_data[] = array('accid' => 'USMO0362', 'name' => 'Granby');
$city_data[] = array('accid' => 'USMO0363', 'name' => 'Grandin');
$city_data[] = array('accid' => 'USMO0364', 'name' => 'Grandview');
$city_data[] = array('accid' => 'USMO0365', 'name' => 'Granger');
$city_data[] = array('accid' => 'USMO0366', 'name' => 'Grant City');
$city_data[] = array('accid' => 'USMO0367', 'name' => 'Grassy');
$city_data[] = array('accid' => 'USMO0368', 'name' => 'Gravois Mills');
$city_data[] = array('accid' => 'USMO0369', 'name' => 'Gray Summit');
$city_data[] = array('accid' => 'USMO0370', 'name' => 'Grayridge');
$city_data[] = array('accid' => 'USMO0371', 'name' => 'Green Castle');
$city_data[] = array('accid' => 'USMO0372', 'name' => 'Green City');
$city_data[] = array('accid' => 'USMO0373', 'name' => 'Green Ridge');
$city_data[] = array('accid' => 'USMO0374', 'name' => 'Greenfield');
$city_data[] = array('accid' => 'USMO0375', 'name' => 'Greentop');
$city_data[] = array('accid' => 'USMO0376', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USMO0377', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USMO0378', 'name' => 'Grover');
$city_data[] = array('accid' => 'USMO0379', 'name' => 'Grovespring');
$city_data[] = array('accid' => 'USMO0380', 'name' => 'Grubville');
$city_data[] = array('accid' => 'USMO0381', 'name' => 'Guilford');
$city_data[] = array('accid' => 'USMO0382', 'name' => 'Hale');
$city_data[] = array('accid' => 'USMO0383', 'name' => 'Half Way');
$city_data[] = array('accid' => 'USMO0384', 'name' => 'Hallsville');
$city_data[] = array('accid' => 'USMO0385', 'name' => 'Halltown');
$city_data[] = array('accid' => 'USMO0386', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USMO0387', 'name' => 'Hannibal');
$city_data[] = array('accid' => 'USMO0388', 'name' => 'Hardenville');
$city_data[] = array('accid' => 'USMO0389', 'name' => 'Hardin');
$city_data[] = array('accid' => 'USMO0390', 'name' => 'Harris');
$city_data[] = array('accid' => 'USMO0391', 'name' => 'Harrisburg');
$city_data[] = array('accid' => 'USMO0392', 'name' => 'Harrisonville');
$city_data[] = array('accid' => 'USMO0393', 'name' => 'Hartsburg');
$city_data[] = array('accid' => 'USMO0394', 'name' => 'Hartshorn');
$city_data[] = array('accid' => 'USMO0395', 'name' => 'Hartville');
$city_data[] = array('accid' => 'USMO0396', 'name' => 'Harviell');
$city_data[] = array('accid' => 'USMO0397', 'name' => 'Harwood');
$city_data[] = array('accid' => 'USMO0398', 'name' => 'Hatfield');
$city_data[] = array('accid' => 'USMO0399', 'name' => 'Hawk Point');
$city_data[] = array('accid' => 'USMO0400', 'name' => 'Hayti');
$city_data[] = array('accid' => 'USMO0401', 'name' => 'Hazelwood');
$city_data[] = array('accid' => 'USMO0402', 'name' => 'Helena');
$city_data[] = array('accid' => 'USMO0403', 'name' => 'Hematite');
$city_data[] = array('accid' => 'USMO0404', 'name' => 'Henley');
$city_data[] = array('accid' => 'USMO0405', 'name' => 'Henrietta');
$city_data[] = array('accid' => 'USMO0406', 'name' => 'Herculaneum');
$city_data[] = array('accid' => 'USMO0407', 'name' => 'Hermann');
$city_data[] = array('accid' => 'USMO0408', 'name' => 'Hermitage');
$city_data[] = array('accid' => 'USMO0409', 'name' => 'Higbee');
$city_data[] = array('accid' => 'USMO0410', 'name' => 'Higginsville');
$city_data[] = array('accid' => 'USMO0411', 'name' => 'High Hill');
$city_data[] = array('accid' => 'USMO0412', 'name' => 'High Point');
$city_data[] = array('accid' => 'USMO0413', 'name' => 'High Ridge');
$city_data[] = array('accid' => 'USMO0414', 'name' => 'Highlandville');
$city_data[] = array('accid' => 'USMO0415', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USMO0416', 'name' => 'Hiram');
$city_data[] = array('accid' => 'USMO0417', 'name' => 'Holcomb');
$city_data[] = array('accid' => 'USMO0418', 'name' => 'Holden');
$city_data[] = array('accid' => 'USMO0419', 'name' => 'Holland');
$city_data[] = array('accid' => 'USMO0420', 'name' => 'Holliday');
$city_data[] = array('accid' => 'USMO0421', 'name' => 'Hollister');
$city_data[] = array('accid' => 'USMO0422', 'name' => 'Holt');
$city_data[] = array('accid' => 'USMO0423', 'name' => 'Holts Summit');
$city_data[] = array('accid' => 'USMO0424', 'name' => 'Hopkins');
$city_data[] = array('accid' => 'USMO0425', 'name' => 'Hornersville');
$city_data[] = array('accid' => 'USMO0426', 'name' => 'Horton');
$city_data[] = array('accid' => 'USMO0427', 'name' => 'House Springs');
$city_data[] = array('accid' => 'USMO0428', 'name' => 'Houston');
$city_data[] = array('accid' => 'USMO0429', 'name' => 'Houstonia');
$city_data[] = array('accid' => 'USMO0430', 'name' => 'Huggins');
$city_data[] = array('accid' => 'USMO0431', 'name' => 'Hughesville');
$city_data[] = array('accid' => 'USMO0432', 'name' => 'Humansville');
$city_data[] = array('accid' => 'USMO0433', 'name' => 'Hume');
$city_data[] = array('accid' => 'USMO0434', 'name' => 'Humphreys');
$city_data[] = array('accid' => 'USMO0435', 'name' => 'Hunnewell');
$city_data[] = array('accid' => 'USMO0436', 'name' => 'Huntsville');
$city_data[] = array('accid' => 'USMO0437', 'name' => 'Hurdland');
$city_data[] = array('accid' => 'USMO0438', 'name' => 'Hurley');
$city_data[] = array('accid' => 'USMO0439', 'name' => 'Iberia');
$city_data[] = array('accid' => 'USMO0440', 'name' => 'Imperial');
$city_data[] = array('accid' => 'USMO0441', 'name' => 'Independence');
$city_data[] = array('accid' => 'USMO0442', 'name' => 'Ionia');
$city_data[] = array('accid' => 'USMO0443', 'name' => 'Irondale');
$city_data[] = array('accid' => 'USMO0444', 'name' => 'Ironton');
$city_data[] = array('accid' => 'USMO0445', 'name' => 'Isabella');
$city_data[] = array('accid' => 'USMO0446', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USMO0447', 'name' => 'Jacksonville');
$city_data[] = array('accid' => 'USMO0448', 'name' => 'Jadwin');
$city_data[] = array('accid' => 'USMO0449', 'name' => 'Jameson');
$city_data[] = array('accid' => 'USMO0450', 'name' => 'Jamesport');
$city_data[] = array('accid' => 'USMO0451', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USMO0452', 'name' => 'Jasper');
$city_data[] = array('accid' => 'USMO0453', 'name' => 'Jefferson City');
$city_data[] = array('accid' => 'USMO0454', 'name' => 'Jerico Springs');
$city_data[] = array('accid' => 'USMO0455', 'name' => 'Jerome');
$city_data[] = array('accid' => 'USMO0456', 'name' => 'Jonesburg');
$city_data[] = array('accid' => 'USMO0457', 'name' => 'Joplin');
$city_data[] = array('accid' => 'USMO0458', 'name' => 'Kahoka');
$city_data[] = array('accid' => 'USMO0459', 'name' => 'Kaiser');
$city_data[] = array('accid' => 'USMO0460', 'name' => 'Kansas City');
$city_data[] = array('accid' => 'USMO0462', 'name' => 'Kearney');
$city_data[] = array('accid' => 'USMO0463', 'name' => 'Kelso');
$city_data[] = array('accid' => 'USMO0464', 'name' => 'Kennett');
$city_data[] = array('accid' => 'USMO0465', 'name' => 'Kewanee');
$city_data[] = array('accid' => 'USMO0466', 'name' => 'Keytesville');
$city_data[] = array('accid' => 'USMO0467', 'name' => 'Kidder');
$city_data[] = array('accid' => 'USMO0468', 'name' => 'Kimberling City');
$city_data[] = array('accid' => 'USMO0469', 'name' => 'Kimmswick');
$city_data[] = array('accid' => 'USMO0470', 'name' => 'King City');
$city_data[] = array('accid' => 'USMO0471', 'name' => 'Kingdom City');
$city_data[] = array('accid' => 'USMO0472', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USMO0473', 'name' => 'Kingsville');
$city_data[] = array('accid' => 'USMO0474', 'name' => 'Kirbyville');
$city_data[] = array('accid' => 'USMO0475', 'name' => 'Kirksville');
$city_data[] = array('accid' => 'USMO0476', 'name' => 'Kissee Mills');
$city_data[] = array('accid' => 'USMO0477', 'name' => 'Knob Lick');
$city_data[] = array('accid' => 'USMO0478', 'name' => 'Knob Noster');
$city_data[] = array('accid' => 'USMO0479', 'name' => 'Knox City');
$city_data[] = array('accid' => 'USMO0480', 'name' => 'Koeltztown');
$city_data[] = array('accid' => 'USMO0481', 'name' => 'Koshkonong');
$city_data[] = array('accid' => 'USMO0482', 'name' => 'La Belle');
$city_data[] = array('accid' => 'USMO0483', 'name' => 'La Grange');
$city_data[] = array('accid' => 'USMO0484', 'name' => 'La Monte');
$city_data[] = array('accid' => 'USMO0485', 'name' => 'La Plata');
$city_data[] = array('accid' => 'USMO0486', 'name' => 'La Russell');
$city_data[] = array('accid' => 'USMO0487', 'name' => 'Labadie');
$city_data[] = array('accid' => 'USMO0488', 'name' => 'Laclede');
$city_data[] = array('accid' => 'USMO0489', 'name' => 'Laddonia');
$city_data[] = array('accid' => 'USMO0490', 'name' => 'Lake Ozark');
$city_data[] = array('accid' => 'USMO0491', 'name' => 'Lake Saint Louis');
$city_data[] = array('accid' => 'USMO0492', 'name' => 'Lake Spring');
$city_data[] = array('accid' => 'USMO0493', 'name' => 'Lamar');
$city_data[] = array('accid' => 'USMO0494', 'name' => 'Lampe');
$city_data[] = array('accid' => 'USMO0495', 'name' => 'Lanagan');
$city_data[] = array('accid' => 'USMO0496', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USMO0497', 'name' => 'Laquey');
$city_data[] = array('accid' => 'USMO0498', 'name' => 'Laredo');
$city_data[] = array('accid' => 'USMO0499', 'name' => 'Latham');
$city_data[] = array('accid' => 'USMO0500', 'name' => 'Lathrop');
$city_data[] = array('accid' => 'USMO0501', 'name' => 'Laurie');
$city_data[] = array('accid' => 'USMO0502', 'name' => 'Lawson');
$city_data[] = array('accid' => 'USMO0503', 'name' => 'Leadwood');
$city_data[] = array('accid' => 'USMO0504', 'name' => 'Leasburg');
$city_data[] = array('accid' => 'USMO0505', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USMO0506', 'name' => 'Lecoma');
$city_data[] = array('accid' => 'USMO0507', 'name' => 'Lees Summit MPO');
$city_data[] = array('accid' => 'USMO0508', 'name' => 'Leeton');
$city_data[] = array('accid' => 'USMO0509', 'name' => 'Lenox');
$city_data[] = array('accid' => 'USMO0510', 'name' => 'Lentner');
$city_data[] = array('accid' => 'USMO0511', 'name' => 'Leonard');
$city_data[] = array('accid' => 'USMO0512', 'name' => 'Leopold');
$city_data[] = array('accid' => 'USMO0513', 'name' => 'Leslie');
$city_data[] = array('accid' => 'USMO0514', 'name' => 'Lesterville');
$city_data[] = array('accid' => 'USMO0515', 'name' => 'Levasy');
$city_data[] = array('accid' => 'USMO0516', 'name' => 'Lewistown');
$city_data[] = array('accid' => 'USMO0517', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USMO0518', 'name' => 'Liberal');
$city_data[] = array('accid' => 'USMO0519', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USMO0520', 'name' => 'Licking');
$city_data[] = array('accid' => 'USMO0521', 'name' => 'Liguori');
$city_data[] = array('accid' => 'USMO0522', 'name' => 'Lilbourn');
$city_data[] = array('accid' => 'USMO0523', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USMO0524', 'name' => 'Linn');
$city_data[] = array('accid' => 'USMO0525', 'name' => 'Linn Creek');
$city_data[] = array('accid' => 'USMO0526', 'name' => 'Linneus');
$city_data[] = array('accid' => 'USMO0527', 'name' => 'Livonia');
$city_data[] = array('accid' => 'USMO0528', 'name' => 'Lock Springs');
$city_data[] = array('accid' => 'USMO0529', 'name' => 'Lockwood');
$city_data[] = array('accid' => 'USMO0530', 'name' => 'Lodi');
$city_data[] = array('accid' => 'USMO0531', 'name' => 'Lohman');
$city_data[] = array('accid' => 'USMO0532', 'name' => 'Lone Jack');
$city_data[] = array('accid' => 'USMO0533', 'name' => 'Lonedell');
$city_data[] = array('accid' => 'USMO0534', 'name' => 'Long Lane');
$city_data[] = array('accid' => 'USMO0535', 'name' => 'Loose Creek');
$city_data[] = array('accid' => 'USMO0536', 'name' => 'Louisburg');
$city_data[] = array('accid' => 'USMO0537', 'name' => 'Louisiana');
$city_data[] = array('accid' => 'USMO0538', 'name' => 'Lowndes');
$city_data[] = array('accid' => 'USMO0539', 'name' => 'Lowry City');
$city_data[] = array('accid' => 'USMO0540', 'name' => 'Lucerne');
$city_data[] = array('accid' => 'USMO0541', 'name' => 'Ludlow');
$city_data[] = array('accid' => 'USMO0542', 'name' => 'Luebbering');
$city_data[] = array('accid' => 'USMO0543', 'name' => 'Luray');
$city_data[] = array('accid' => 'USMO0544', 'name' => 'Lynchburg');
$city_data[] = array('accid' => 'USMO0545', 'name' => 'Macks Creek');
$city_data[] = array('accid' => 'USMO0546', 'name' => 'Macomb');
$city_data[] = array('accid' => 'USMO0547', 'name' => 'Macon');
$city_data[] = array('accid' => 'USMO0548', 'name' => 'Madison');
$city_data[] = array('accid' => 'USMO0549', 'name' => 'Maitland');
$city_data[] = array('accid' => 'USMO0550', 'name' => 'Malden');
$city_data[] = array('accid' => 'USMO0551', 'name' => 'Malta Bend');
$city_data[] = array('accid' => 'USMO0552', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'USMO0553', 'name' => 'Mapaville');
$city_data[] = array('accid' => 'USMO0554', 'name' => 'Marble Hill');
$city_data[] = array('accid' => 'USMO0555', 'name' => 'Marceline');
$city_data[] = array('accid' => 'USMO0556', 'name' => 'Marionville');
$city_data[] = array('accid' => 'USMO0557', 'name' => 'Marquand');
$city_data[] = array('accid' => 'USMO0558', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USMO0559', 'name' => 'Marshfield');
$city_data[] = array('accid' => 'USMO0560', 'name' => 'Marston');
$city_data[] = array('accid' => 'USMO0561', 'name' => 'Marthasville');
$city_data[] = array('accid' => 'USMO0562', 'name' => 'Martinsburg');
$city_data[] = array('accid' => 'USMO0563', 'name' => 'Martinsville');
$city_data[] = array('accid' => 'USMO0564', 'name' => 'Maryland Heights');
$city_data[] = array('accid' => 'USMO0565', 'name' => 'Maryville');
$city_data[] = array('accid' => 'USMO0566', 'name' => 'Matthews');
$city_data[] = array('accid' => 'USMO0567', 'name' => 'Maysville');
$city_data[] = array('accid' => 'USMO0568', 'name' => 'Mayview');
$city_data[] = array('accid' => 'USMO0569', 'name' => 'Maywood');
$city_data[] = array('accid' => 'USMO0570', 'name' => 'McBride');
$city_data[] = array('accid' => 'USMO0571', 'name' => 'McClurg');
$city_data[] = array('accid' => 'USMO0572', 'name' => 'McFall');
$city_data[] = array('accid' => 'USMO0573', 'name' => 'McGee');
$city_data[] = array('accid' => 'USMO0574', 'name' => 'McGirk');
$city_data[] = array('accid' => 'USMO0575', 'name' => 'Meadville');
$city_data[] = array('accid' => 'USMO0576', 'name' => 'Memphis');
$city_data[] = array('accid' => 'USMO0577', 'name' => 'Mendon');
$city_data[] = array('accid' => 'USMO0578', 'name' => 'Mercer');
$city_data[] = array('accid' => 'USMO0579', 'name' => 'Meta');
$city_data[] = array('accid' => 'USMO0580', 'name' => 'Metz');
$city_data[] = array('accid' => 'USMO0581', 'name' => 'Mexico');
$city_data[] = array('accid' => 'USMO0582', 'name' => 'Miami');
$city_data[] = array('accid' => 'USMO0583', 'name' => 'Mid Missouri');
$city_data[] = array('accid' => 'USMO0584', 'name' => 'Middle Brook');
$city_data[] = array('accid' => 'USMO0585', 'name' => 'Middletown');
$city_data[] = array('accid' => 'USMO0586', 'name' => 'Milan');
$city_data[] = array('accid' => 'USMO0587', 'name' => 'Milford');
$city_data[] = array('accid' => 'USMO0588', 'name' => 'Mill Spring');
$city_data[] = array('accid' => 'USMO0589', 'name' => 'Miller');
$city_data[] = array('accid' => 'USMO0590', 'name' => 'Millersville');
$city_data[] = array('accid' => 'USMO0591', 'name' => 'Milo');
$city_data[] = array('accid' => 'USMO0592', 'name' => 'Mindenmines');
$city_data[] = array('accid' => 'USMO0593', 'name' => 'Mineral Point');
$city_data[] = array('accid' => 'USMO0594', 'name' => 'Missouri City');
$city_data[] = array('accid' => 'USMO0595', 'name' => 'Moberly');
$city_data[] = array('accid' => 'USMO0596', 'name' => 'Mokane');
$city_data[] = array('accid' => 'USMO0597', 'name' => 'Monett');
$city_data[] = array('accid' => 'USMO0598', 'name' => 'Monroe City');
$city_data[] = array('accid' => 'USMO0599', 'name' => 'Montgomery City');
$city_data[] = array('accid' => 'USMO0600', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USMO0601', 'name' => 'Montier');
$city_data[] = array('accid' => 'USMO0602', 'name' => 'Montreal');
$city_data[] = array('accid' => 'USMO0603', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USMO0604', 'name' => 'Moody');
$city_data[] = array('accid' => 'USMO0605', 'name' => 'Mooresville');
$city_data[] = array('accid' => 'USMO0606', 'name' => 'Mora');
$city_data[] = array('accid' => 'USMO0607', 'name' => 'Morehouse');
$city_data[] = array('accid' => 'USMO0608', 'name' => 'Morley');
$city_data[] = array('accid' => 'USMO0609', 'name' => 'Morrison');
$city_data[] = array('accid' => 'USMO0610', 'name' => 'Morrisville');
$city_data[] = array('accid' => 'USMO0611', 'name' => 'Morse Mill');
$city_data[] = array('accid' => 'USMO0612', 'name' => 'Mosby');
$city_data[] = array('accid' => 'USMO0613', 'name' => 'Moscow Mills');
$city_data[] = array('accid' => 'USMO0614', 'name' => 'Mound City');
$city_data[] = array('accid' => 'USMO0615', 'name' => 'Moundville');
$city_data[] = array('accid' => 'USMO0616', 'name' => 'Mount Moriah');
$city_data[] = array('accid' => 'USMO0617', 'name' => 'Mount Sterling');
$city_data[] = array('accid' => 'USMO0618', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USMO0619', 'name' => 'Mountain Grove');
$city_data[] = array('accid' => 'USMO0620', 'name' => 'Mountain View');
$city_data[] = array('accid' => 'USMO0621', 'name' => 'Myrtle');
$city_data[] = array('accid' => 'USMO0622', 'name' => 'Napoleon');
$city_data[] = array('accid' => 'USMO0623', 'name' => 'Naylor');
$city_data[] = array('accid' => 'USMO0624', 'name' => 'Neck City');
$city_data[] = array('accid' => 'USMO0625', 'name' => 'Neelyville');
$city_data[] = array('accid' => 'USMO0626', 'name' => 'Nelson');
$city_data[] = array('accid' => 'USMO0627', 'name' => 'Neosho');
$city_data[] = array('accid' => 'USMO0628', 'name' => 'Nevada');
$city_data[] = array('accid' => 'USMO0629', 'name' => 'New Bloomfield');
$city_data[] = array('accid' => 'USMO0630', 'name' => 'New Boston');
$city_data[] = array('accid' => 'USMO0631', 'name' => 'New Cambria');
$city_data[] = array('accid' => 'USMO0632', 'name' => 'New Florence');
$city_data[] = array('accid' => 'USMO0633', 'name' => 'New Franklin');
$city_data[] = array('accid' => 'USMO0634', 'name' => 'New Hampton');
$city_data[] = array('accid' => 'USMO0635', 'name' => 'New Haven');
$city_data[] = array('accid' => 'USMO0636', 'name' => 'New London');
$city_data[] = array('accid' => 'USMO0637', 'name' => 'New Madrid');
$city_data[] = array('accid' => 'USMO0638', 'name' => 'New Melle');
$city_data[] = array('accid' => 'USMO0639', 'name' => 'New Offenburg');
$city_data[] = array('accid' => 'USMO0640', 'name' => 'Newark');
$city_data[] = array('accid' => 'USMO0641', 'name' => 'Newburg');
$city_data[] = array('accid' => 'USMO0642', 'name' => 'Newtonia');
$city_data[] = array('accid' => 'USMO0643', 'name' => 'Newtown');
$city_data[] = array('accid' => 'USMO0644', 'name' => 'Niangua');
$city_data[] = array('accid' => 'USMO0645', 'name' => 'Nixa');
$city_data[] = array('accid' => 'USMO0646', 'name' => 'Noble');
$city_data[] = array('accid' => 'USMO0647', 'name' => 'Noel');
$city_data[] = array('accid' => 'USMO0648', 'name' => 'Norborne');
$city_data[] = array('accid' => 'USMO0649', 'name' => 'Norwood');
$city_data[] = array('accid' => 'USMO0650', 'name' => 'Novelty');
$city_data[] = array('accid' => 'USMO0651', 'name' => 'Novinger');
$city_data[] = array('accid' => 'USMO0655', 'name' => 'O\'fallon');
$city_data[] = array('accid' => 'USMO0652', 'name' => 'Oak Grove');
$city_data[] = array('accid' => 'USMO0653', 'name' => 'Oak Ridge');
$city_data[] = array('accid' => 'USMO0654', 'name' => 'Odessa');
$city_data[] = array('accid' => 'USMO0656', 'name' => 'Old Appleton');
$city_data[] = array('accid' => 'USMO0657', 'name' => 'Old Monroe');
$city_data[] = array('accid' => 'USMO0658', 'name' => 'Oldfield');
$city_data[] = array('accid' => 'USMO0659', 'name' => 'Olean');
$city_data[] = array('accid' => 'USMO0660', 'name' => 'Olney');
$city_data[] = array('accid' => 'USMO0661', 'name' => 'Oran');
$city_data[] = array('accid' => 'USMO0662', 'name' => 'Oregon');
$city_data[] = array('accid' => 'USMO0663', 'name' => 'Oronogo');
$city_data[] = array('accid' => 'USMO0664', 'name' => 'Orrick');
$city_data[] = array('accid' => 'USMO0665', 'name' => 'Osage Beach');
$city_data[] = array('accid' => 'USMO0666', 'name' => 'Osborn');
$city_data[] = array('accid' => 'USMO0667', 'name' => 'Osceola');
$city_data[] = array('accid' => 'USMO0668', 'name' => 'Otterville');
$city_data[] = array('accid' => 'USMO0669', 'name' => 'Owensville');
$city_data[] = array('accid' => 'USMO0670', 'name' => 'Oxly');
$city_data[] = array('accid' => 'USMO0671', 'name' => 'Ozark');
$city_data[] = array('accid' => 'USMO0672', 'name' => 'Pacific');
$city_data[] = array('accid' => 'USMO0673', 'name' => 'Painton');
$city_data[] = array('accid' => 'USMO0674', 'name' => 'Palmyra');
$city_data[] = array('accid' => 'USMO0675', 'name' => 'Paris');
$city_data[] = array('accid' => 'USMO0676', 'name' => 'Park Hills');
$city_data[] = array('accid' => 'USMO0677', 'name' => 'Parma');
$city_data[] = array('accid' => 'USMO0678', 'name' => 'Parnell');
$city_data[] = array('accid' => 'USMO0679', 'name' => 'Pascola');
$city_data[] = array('accid' => 'USMO0680', 'name' => 'Passaic');
$city_data[] = array('accid' => 'USMO0681', 'name' => 'Patterson');
$city_data[] = array('accid' => 'USMO0682', 'name' => 'Patton');
$city_data[] = array('accid' => 'USMO0683', 'name' => 'Pattonsburg');
$city_data[] = array('accid' => 'USMO0684', 'name' => 'Peace Valley');
$city_data[] = array('accid' => 'USMO0685', 'name' => 'Peculiar');
$city_data[] = array('accid' => 'USMO0686', 'name' => 'Perkins');
$city_data[] = array('accid' => 'USMO0687', 'name' => 'Perry');
$city_data[] = array('accid' => 'USMO0688', 'name' => 'Perryville');
$city_data[] = array('accid' => 'USMO0689', 'name' => 'Pevely');
$city_data[] = array('accid' => 'USMO0690', 'name' => 'Philadelphia');
$city_data[] = array('accid' => 'USMO0691', 'name' => 'Phillipsburg');
$city_data[] = array('accid' => 'USMO0692', 'name' => 'Pickering');
$city_data[] = array('accid' => 'USMO0693', 'name' => 'Piedmont');
$city_data[] = array('accid' => 'USMO0694', 'name' => 'Pierce City');
$city_data[] = array('accid' => 'USMO0695', 'name' => 'Pilot Grove');
$city_data[] = array('accid' => 'USMO0696', 'name' => 'Pilot Knob');
$city_data[] = array('accid' => 'USMO0697', 'name' => 'Pineville');
$city_data[] = array('accid' => 'USMO0698', 'name' => 'Pittsburg');
$city_data[] = array('accid' => 'USMO0699', 'name' => 'Plato');
$city_data[] = array('accid' => 'USMO0700', 'name' => 'Platte City');
$city_data[] = array('accid' => 'USMO0701', 'name' => 'Plattsburg');
$city_data[] = array('accid' => 'USMO0702', 'name' => 'Pleasant Hill');
$city_data[] = array('accid' => 'USMO0703', 'name' => 'Pleasant Hope');
$city_data[] = array('accid' => 'USMO0704', 'name' => 'Plevna');
$city_data[] = array('accid' => 'USMO0705', 'name' => 'Pocahontas');
$city_data[] = array('accid' => 'USMO0706', 'name' => 'Point Lookout');
$city_data[] = array('accid' => 'USMO0707', 'name' => 'Polk');
$city_data[] = array('accid' => 'USMO0708', 'name' => 'Pollock');
$city_data[] = array('accid' => 'USMO0709', 'name' => 'Polo');
$city_data[] = array('accid' => 'USMO0710', 'name' => 'Pomona');
$city_data[] = array('accid' => 'USMO0711', 'name' => 'Ponce De Leon');
$city_data[] = array('accid' => 'USMO0712', 'name' => 'Pontiac');
$city_data[] = array('accid' => 'USMO0713', 'name' => 'Poplar Bluff');
$city_data[] = array('accid' => 'USMO0714', 'name' => 'Portage Des Sioux');
$city_data[] = array('accid' => 'USMO0715', 'name' => 'Portageville');
$city_data[] = array('accid' => 'USMO0716', 'name' => 'Portland');
$city_data[] = array('accid' => 'USMO0717', 'name' => 'Potosi');
$city_data[] = array('accid' => 'USMO0718', 'name' => 'Pottersville');
$city_data[] = array('accid' => 'USMO0719', 'name' => 'Powell');
$city_data[] = array('accid' => 'USMO0720', 'name' => 'Powersite');
$city_data[] = array('accid' => 'USMO0721', 'name' => 'Powersville');
$city_data[] = array('accid' => 'USMO0722', 'name' => 'Prairie Home');
$city_data[] = array('accid' => 'USMO0723', 'name' => 'Preston');
$city_data[] = array('accid' => 'USMO0724', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USMO0725', 'name' => 'Protem');
$city_data[] = array('accid' => 'USMO0726', 'name' => 'Purcell');
$city_data[] = array('accid' => 'USMO0727', 'name' => 'Purdin');
$city_data[] = array('accid' => 'USMO0728', 'name' => 'Purdy');
$city_data[] = array('accid' => 'USMO0729', 'name' => 'Puxico');
$city_data[] = array('accid' => 'USMO0730', 'name' => 'Queen City');
$city_data[] = array('accid' => 'USMO0731', 'name' => 'Quincy');
$city_data[] = array('accid' => 'USMO0732', 'name' => 'Quitman');
$city_data[] = array('accid' => 'USMO0733', 'name' => 'Qulin');
$city_data[] = array('accid' => 'USMO0734', 'name' => 'Racine');
$city_data[] = array('accid' => 'USMO0735', 'name' => 'Ravenwood');
$city_data[] = array('accid' => 'USMO0736', 'name' => 'Raymondville');
$city_data[] = array('accid' => 'USMO0737', 'name' => 'Raymore');
$city_data[] = array('accid' => 'USMO0738', 'name' => 'Rayville');
$city_data[] = array('accid' => 'USMO0739', 'name' => 'Rea');
$city_data[] = array('accid' => 'USMO0740', 'name' => 'Redford');
$city_data[] = array('accid' => 'USMO0741', 'name' => 'Reeds');
$city_data[] = array('accid' => 'USMO0742', 'name' => 'Reeds Spring');
$city_data[] = array('accid' => 'USMO0743', 'name' => 'Renick');
$city_data[] = array('accid' => 'USMO0744', 'name' => 'Republic');
$city_data[] = array('accid' => 'USMO0745', 'name' => 'Revere');
$city_data[] = array('accid' => 'USMO0746', 'name' => 'Reynolds');
$city_data[] = array('accid' => 'USMO0747', 'name' => 'Rhineland');
$city_data[] = array('accid' => 'USMO0748', 'name' => 'Rich Hill');
$city_data[] = array('accid' => 'USMO0749', 'name' => 'Richards');
$city_data[] = array('accid' => 'USMO0750', 'name' => 'Richland');
$city_data[] = array('accid' => 'USMO0751', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USMO0752', 'name' => 'Richwoods');
$city_data[] = array('accid' => 'USMO0753', 'name' => 'Ridgedale');
$city_data[] = array('accid' => 'USMO0754', 'name' => 'Ridgeway');
$city_data[] = array('accid' => 'USMO0755', 'name' => 'Risco');
$city_data[] = array('accid' => 'USMO0756', 'name' => 'Rives');
$city_data[] = array('accid' => 'USMO0757', 'name' => 'Roach');
$city_data[] = array('accid' => 'USMO0758', 'name' => 'Robertsville');
$city_data[] = array('accid' => 'USMO0759', 'name' => 'Roby');
$city_data[] = array('accid' => 'USMO0760', 'name' => 'Rocheport');
$city_data[] = array('accid' => 'USMO0761', 'name' => 'Rock Port');
$city_data[] = array('accid' => 'USMO0762', 'name' => 'Rockaway Beach');
$city_data[] = array('accid' => 'USMO0763', 'name' => 'Rockbridge');
$city_data[] = array('accid' => 'USMO0764', 'name' => 'Rockville');
$city_data[] = array('accid' => 'USMO0765', 'name' => 'Rocky Comfort');
$city_data[] = array('accid' => 'USMO0766', 'name' => 'Rocky Mount');
$city_data[] = array('accid' => 'USMO0767', 'name' => 'Rogersville');
$city_data[] = array('accid' => 'USMO0768', 'name' => 'Rolla');
$city_data[] = array('accid' => 'USMO0769', 'name' => 'Rombauer');
$city_data[] = array('accid' => 'USMO0770', 'name' => 'Roscoe');
$city_data[] = array('accid' => 'USMO0771', 'name' => 'Rosebud');
$city_data[] = array('accid' => 'USMO0772', 'name' => 'Rosendale');
$city_data[] = array('accid' => 'USMO0773', 'name' => 'Rothville');
$city_data[] = array('accid' => 'USMO0774', 'name' => 'Rueter');
$city_data[] = array('accid' => 'USMO0775', 'name' => 'Rush Hill');
$city_data[] = array('accid' => 'USMO0776', 'name' => 'Rushville');
$city_data[] = array('accid' => 'USMO0777', 'name' => 'Russellville');
$city_data[] = array('accid' => 'USMO0778', 'name' => 'Rutledge');
$city_data[] = array('accid' => 'USMO0779', 'name' => 'Saginaw');
$city_data[] = array('accid' => 'USMO0780', 'name' => 'Saint Albans');
$city_data[] = array('accid' => 'USMO0781', 'name' => 'Saint Ann');
$city_data[] = array('accid' => 'USMO0782', 'name' => 'Saint Charles');
$city_data[] = array('accid' => 'USMO0783', 'name' => 'Saint Clair');
$city_data[] = array('accid' => 'USMO0784', 'name' => 'Saint Elizabeth');
$city_data[] = array('accid' => 'USMO0785', 'name' => 'Saint James');
$city_data[] = array('accid' => 'USMO0786', 'name' => 'Saint Joseph');
$city_data[] = array('accid' => 'USMO0787', 'name' => 'Saint Louis');
$city_data[] = array('accid' => 'USMO0788', 'name' => 'Saint Mary');
$city_data[] = array('accid' => 'USMO0789', 'name' => 'Saint Patrick');
$city_data[] = array('accid' => 'USMO0790', 'name' => 'Saint Peters');
$city_data[] = array('accid' => 'USMO0970', 'name' => 'Saint Robert');
$city_data[] = array('accid' => 'USMO0791', 'name' => 'Saint Thomas');
$city_data[] = array('accid' => 'USMO0792', 'name' => 'Sainte Genevieve');
$city_data[] = array('accid' => 'USMO0793', 'name' => 'Salem');
$city_data[] = array('accid' => 'USMO0794', 'name' => 'Salisbury');
$city_data[] = array('accid' => 'USMO0795', 'name' => 'Santa Fe');
$city_data[] = array('accid' => 'USMO0796', 'name' => 'Sarcoxie');
$city_data[] = array('accid' => 'USMO0797', 'name' => 'Savannah');
$city_data[] = array('accid' => 'USMO0798', 'name' => 'Saverton');
$city_data[] = array('accid' => 'USMO0799', 'name' => 'Schell City');
$city_data[] = array('accid' => 'USMO0800', 'name' => 'Scott City');
$city_data[] = array('accid' => 'USMO0801', 'name' => 'Sedalia');
$city_data[] = array('accid' => 'USMO0802', 'name' => 'Sedgewickville');
$city_data[] = array('accid' => 'USMO0803', 'name' => 'Seligman');
$city_data[] = array('accid' => 'USMO0804', 'name' => 'Senath');
$city_data[] = array('accid' => 'USMO0805', 'name' => 'Seneca');
$city_data[] = array('accid' => 'USMO0806', 'name' => 'Seymour');
$city_data[] = array('accid' => 'USMO0807', 'name' => 'Shelbina');
$city_data[] = array('accid' => 'USMO0808', 'name' => 'Shelbyville');
$city_data[] = array('accid' => 'USMO0809', 'name' => 'Sheldon');
$city_data[] = array('accid' => 'USMO0810', 'name' => 'Shell Knob');
$city_data[] = array('accid' => 'USMO0811', 'name' => 'Sheridan');
$city_data[] = array('accid' => 'USMO0812', 'name' => 'Shook');
$city_data[] = array('accid' => 'USMO0813', 'name' => 'Sibley');
$city_data[] = array('accid' => 'USMO0814', 'name' => 'Sikeston');
$city_data[] = array('accid' => 'USMO0815', 'name' => 'Silex');
$city_data[] = array('accid' => 'USMO0816', 'name' => 'Silva');
$city_data[] = array('accid' => 'USMO0817', 'name' => 'Skidmore');
$city_data[] = array('accid' => 'USMO0818', 'name' => 'Slater');
$city_data[] = array('accid' => 'USMO0819', 'name' => 'Smithton');
$city_data[] = array('accid' => 'USMO0820', 'name' => 'Smithville');
$city_data[] = array('accid' => 'USMO0821', 'name' => 'Solo');
$city_data[] = array('accid' => 'USMO0822', 'name' => 'South Fork');
$city_data[] = array('accid' => 'USMO0823', 'name' => 'South Greenfield');
$city_data[] = array('accid' => 'USMO0824', 'name' => 'South West City');
$city_data[] = array('accid' => 'USMO0825', 'name' => 'Sparta');
$city_data[] = array('accid' => 'USMO0826', 'name' => 'Spickard');
$city_data[] = array('accid' => 'USMO0827', 'name' => 'Spokane');
$city_data[] = array('accid' => 'USMO0828', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USMO0829', 'name' => 'Squires');
$city_data[] = array('accid' => 'USMO0830', 'name' => 'Stanberry');
$city_data[] = array('accid' => 'USMO0831', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USMO0832', 'name' => 'Stark City');
$city_data[] = array('accid' => 'USMO0833', 'name' => 'Steedman');
$city_data[] = array('accid' => 'USMO0834', 'name' => 'Steele');
$city_data[] = array('accid' => 'USMO0835', 'name' => 'Steelville');
$city_data[] = array('accid' => 'USMO0836', 'name' => 'Stella');
$city_data[] = array('accid' => 'USMO0837', 'name' => 'Stet');
$city_data[] = array('accid' => 'USMO0838', 'name' => 'Stewartsville');
$city_data[] = array('accid' => 'USMO0839', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USMO0840', 'name' => 'Stotts City');
$city_data[] = array('accid' => 'USMO0841', 'name' => 'Stoutland');
$city_data[] = array('accid' => 'USMO0842', 'name' => 'Stoutsville');
$city_data[] = array('accid' => 'USMO0843', 'name' => 'Stover');
$city_data[] = array('accid' => 'USMO0844', 'name' => 'Strafford');
$city_data[] = array('accid' => 'USMO0845', 'name' => 'Strasburg');
$city_data[] = array('accid' => 'USMO0846', 'name' => 'Sturdivant');
$city_data[] = array('accid' => 'USMO0847', 'name' => 'Sturgeon');
$city_data[] = array('accid' => 'USMO0848', 'name' => 'Success');
$city_data[] = array('accid' => 'USMO0849', 'name' => 'Sullivan');
$city_data[] = array('accid' => 'USMO0850', 'name' => 'Summersville');
$city_data[] = array('accid' => 'USMO0851', 'name' => 'Sumner');
$city_data[] = array('accid' => 'USMO0852', 'name' => 'Sunrise Beach');
$city_data[] = array('accid' => 'USMO0853', 'name' => 'Swedeborg');
$city_data[] = array('accid' => 'USMO0854', 'name' => 'Sweet Springs');
$city_data[] = array('accid' => 'USMO0855', 'name' => 'Syracuse');
$city_data[] = array('accid' => 'USMO0856', 'name' => 'Tallapoosa');
$city_data[] = array('accid' => 'USMO0857', 'name' => 'Taneyville');
$city_data[] = array('accid' => 'USMO0858', 'name' => 'Tarkio');
$city_data[] = array('accid' => 'USMO0859', 'name' => 'Taylor');
$city_data[] = array('accid' => 'USMO0860', 'name' => 'Tebbetts');
$city_data[] = array('accid' => 'USMO0861', 'name' => 'Tecumseh');
$city_data[] = array('accid' => 'USMO0862', 'name' => 'Teresita');
$city_data[] = array('accid' => 'USMO0863', 'name' => 'Thayer');
$city_data[] = array('accid' => 'USMO0864', 'name' => 'Theodosia');
$city_data[] = array('accid' => 'USMO0865', 'name' => 'Thompson');
$city_data[] = array('accid' => 'USMO0866', 'name' => 'Thornfield');
$city_data[] = array('accid' => 'USMO0867', 'name' => 'Tiff');
$city_data[] = array('accid' => 'USMO0868', 'name' => 'Tiff City');
$city_data[] = array('accid' => 'USMO0869', 'name' => 'Tina');
$city_data[] = array('accid' => 'USMO0870', 'name' => 'Tipton');
$city_data[] = array('accid' => 'USMO0871', 'name' => 'Treloar');
$city_data[] = array('accid' => 'USMO0872', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USMO0873', 'name' => 'Trimble');
$city_data[] = array('accid' => 'USMO0874', 'name' => 'Triplett');
$city_data[] = array('accid' => 'USMO0875', 'name' => 'Troy');
$city_data[] = array('accid' => 'USMO0876', 'name' => 'Truxton');
$city_data[] = array('accid' => 'USMO0877', 'name' => 'Tunas');
$city_data[] = array('accid' => 'USMO0878', 'name' => 'Turners');
$city_data[] = array('accid' => 'USMO0879', 'name' => 'Turney');
$city_data[] = array('accid' => 'USMO0880', 'name' => 'Tuscumbia');
$city_data[] = array('accid' => 'USMO0881', 'name' => 'Udall');
$city_data[] = array('accid' => 'USMO0882', 'name' => 'Ulman');
$city_data[] = array('accid' => 'USMO0883', 'name' => 'Union');
$city_data[] = array('accid' => 'USMO0884', 'name' => 'Union Star');
$city_data[] = array('accid' => 'USMO0885', 'name' => 'Uniontown');
$city_data[] = array('accid' => 'USMO0886', 'name' => 'Unionville');
$city_data[] = array('accid' => 'USMO0887', 'name' => 'Urbana');
$city_data[] = array('accid' => 'USMO0888', 'name' => 'Urich');
$city_data[] = array('accid' => 'USMO0889', 'name' => 'Utica');
$city_data[] = array('accid' => 'USMO0890', 'name' => 'Valles Mines');
$city_data[] = array('accid' => 'USMO0891', 'name' => 'Valley Park');
$city_data[] = array('accid' => 'USMO0892', 'name' => 'Van Buren');
$city_data[] = array('accid' => 'USMO0893', 'name' => 'Vandalia');
$city_data[] = array('accid' => 'USMO0894', 'name' => 'Vanduser');
$city_data[] = array('accid' => 'USMO0895', 'name' => 'Vanzant');
$city_data[] = array('accid' => 'USMO0896', 'name' => 'Verona');
$city_data[] = array('accid' => 'USMO0897', 'name' => 'Versailles');
$city_data[] = array('accid' => 'USMO0898', 'name' => 'Viburnum');
$city_data[] = array('accid' => 'USMO0899', 'name' => 'Vichy');
$city_data[] = array('accid' => 'USMO0901', 'name' => 'Vienna');
$city_data[] = array('accid' => 'USMO0902', 'name' => 'Villa Ridge');
$city_data[] = array('accid' => 'USMO0903', 'name' => 'Vista');
$city_data[] = array('accid' => 'USMO0904', 'name' => 'Vulcan');
$city_data[] = array('accid' => 'USMO0905', 'name' => 'Waco');
$city_data[] = array('accid' => 'USMO0906', 'name' => 'Wakenda');
$city_data[] = array('accid' => 'USMO0907', 'name' => 'Waldron');
$city_data[] = array('accid' => 'USMO0908', 'name' => 'Walker');
$city_data[] = array('accid' => 'USMO0909', 'name' => 'Walnut Grove');
$city_data[] = array('accid' => 'USMO0910', 'name' => 'Walnut Shade');
$city_data[] = array('accid' => 'USMO0911', 'name' => 'Wappapello');
$city_data[] = array('accid' => 'USMO0912', 'name' => 'Wardell');
$city_data[] = array('accid' => 'USMO0913', 'name' => 'Warrensburg');
$city_data[] = array('accid' => 'USMO0914', 'name' => 'Warrenton');
$city_data[] = array('accid' => 'USMO0915', 'name' => 'Warsaw');
$city_data[] = array('accid' => 'USMO0916', 'name' => 'Washburn');
$city_data[] = array('accid' => 'USMO0917', 'name' => 'Washington');
$city_data[] = array('accid' => 'USMO0918', 'name' => 'Wasola');
$city_data[] = array('accid' => 'USMO0919', 'name' => 'Watson');
$city_data[] = array('accid' => 'USMO0920', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USMO0921', 'name' => 'Wayland');
$city_data[] = array('accid' => 'USMO0922', 'name' => 'Waynesville');
$city_data[] = array('accid' => 'USMO0923', 'name' => 'Weatherby');
$city_data[] = array('accid' => 'USMO0924', 'name' => 'Weaubleau');
$city_data[] = array('accid' => 'USMO0925', 'name' => 'Webb City');
$city_data[] = array('accid' => 'USMO0926', 'name' => 'Wellington');
$city_data[] = array('accid' => 'USMO0927', 'name' => 'Wellsville');
$city_data[] = array('accid' => 'USMO0928', 'name' => 'Wentworth');
$city_data[] = array('accid' => 'USMO0929', 'name' => 'Wentzville');
$city_data[] = array('accid' => 'USMO0930', 'name' => 'Wesco');
$city_data[] = array('accid' => 'USMO0931', 'name' => 'West Alton');
$city_data[] = array('accid' => 'USMO0932', 'name' => 'West Plains');
$city_data[] = array('accid' => 'USMO0933', 'name' => 'Westboro');
$city_data[] = array('accid' => 'USMO0934', 'name' => 'Weston');
$city_data[] = array('accid' => 'USMO0935', 'name' => 'Westphalia');
$city_data[] = array('accid' => 'USMO0936', 'name' => 'Wheatland');
$city_data[] = array('accid' => 'USMO0937', 'name' => 'Wheaton');
$city_data[] = array('accid' => 'USMO0938', 'name' => 'Wheeling');
$city_data[] = array('accid' => 'USMO0939', 'name' => 'Whiteman AFB');
$city_data[] = array('accid' => 'USMO0940', 'name' => 'Whiteoak');
$city_data[] = array('accid' => 'USMO0941', 'name' => 'Whiteside');
$city_data[] = array('accid' => 'USMO0942', 'name' => 'Whitewater');
$city_data[] = array('accid' => 'USMO0943', 'name' => 'Willard');
$city_data[] = array('accid' => 'USMO0944', 'name' => 'Williamsburg');
$city_data[] = array('accid' => 'USMO0945', 'name' => 'Williamstown');
$city_data[] = array('accid' => 'USMO0946', 'name' => 'Williamsville');
$city_data[] = array('accid' => 'USMO0947', 'name' => 'Willow Springs');
$city_data[] = array('accid' => 'USMO0948', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USMO0949', 'name' => 'Windyville');
$city_data[] = array('accid' => 'USMO0950', 'name' => 'Winfield');
$city_data[] = array('accid' => 'USMO0951', 'name' => 'Winigan');
$city_data[] = array('accid' => 'USMO0952', 'name' => 'Winona');
$city_data[] = array('accid' => 'USMO0953', 'name' => 'Winston');
$city_data[] = array('accid' => 'USMO0954', 'name' => 'Wolf Island');
$city_data[] = array('accid' => 'USMO0955', 'name' => 'Wooldridge');
$city_data[] = array('accid' => 'USMO0956', 'name' => 'Worth');
$city_data[] = array('accid' => 'USMO0957', 'name' => 'Worthington');
$city_data[] = array('accid' => 'USMO0958', 'name' => 'Wright City');
$city_data[] = array('accid' => 'USMO0959', 'name' => 'Wyaconda');
$city_data[] = array('accid' => 'USMO0960', 'name' => 'Wyatt');
$city_data[] = array('accid' => 'USMO0961', 'name' => 'Yukon');
$city_data[] = array('accid' => 'USMO0962', 'name' => 'Zalma');
$city_data[] = array('accid' => 'USMO0963', 'name' => 'Zanoni');

?>