<?php

// City package for USA: Mississippi 

$city_name = 'USA: Mississippi';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USMS0001', 'name' => 'Abbeville');
$city_data[] = array('accid' => 'USMS0002', 'name' => 'Aberdeen');
$city_data[] = array('accid' => 'USMS0003', 'name' => 'Ackerman');
$city_data[] = array('accid' => 'USMS0004', 'name' => 'Algoma');
$city_data[] = array('accid' => 'USMS0005', 'name' => 'Alligator');
$city_data[] = array('accid' => 'USMS0006', 'name' => 'Amory');
$city_data[] = array('accid' => 'USMS0007', 'name' => 'Anguilla');
$city_data[] = array('accid' => 'USMS0008', 'name' => 'Arcola');
$city_data[] = array('accid' => 'USMS0009', 'name' => 'Arkabutla');
$city_data[] = array('accid' => 'USMS0010', 'name' => 'Artesia');
$city_data[] = array('accid' => 'USMS0011', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USMS0012', 'name' => 'Avalon');
$city_data[] = array('accid' => 'USMS0013', 'name' => 'Avon');
$city_data[] = array('accid' => 'USMS0014', 'name' => 'Bailey');
$city_data[] = array('accid' => 'USMS0015', 'name' => 'Baldwyn');
$city_data[] = array('accid' => 'USMS0016', 'name' => 'Banner');
$city_data[] = array('accid' => 'USMS0017', 'name' => 'Bassfield');
$city_data[] = array('accid' => 'USMS0018', 'name' => 'Batesville');
$city_data[] = array('accid' => 'USMS0019', 'name' => 'Bay Saint Louis');
$city_data[] = array('accid' => 'USMS0020', 'name' => 'Bay Springs');
$city_data[] = array('accid' => 'USMS0021', 'name' => 'Beaumont');
$city_data[] = array('accid' => 'USMS0022', 'name' => 'Becker');
$city_data[] = array('accid' => 'USMS0023', 'name' => 'Belden');
$city_data[] = array('accid' => 'USMS0024', 'name' => 'Belen');
$city_data[] = array('accid' => 'USMS0025', 'name' => 'Bellefontaine');
$city_data[] = array('accid' => 'USMS0026', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USMS0027', 'name' => 'Belzoni');
$city_data[] = array('accid' => 'USMS0028', 'name' => 'Benoit');
$city_data[] = array('accid' => 'USMS0029', 'name' => 'Benton');
$city_data[] = array('accid' => 'USMS0030', 'name' => 'Bentonia');
$city_data[] = array('accid' => 'USMS0031', 'name' => 'Beulah');
$city_data[] = array('accid' => 'USMS0032', 'name' => 'Big Creek');
$city_data[] = array('accid' => 'USMS0033', 'name' => 'Biloxi');
$city_data[] = array('accid' => 'USMS0034', 'name' => 'Blue Mountain');
$city_data[] = array('accid' => 'USMS0035', 'name' => 'Blue Springs');
$city_data[] = array('accid' => 'USMS0036', 'name' => 'Bogue Chitto');
$city_data[] = array('accid' => 'USMS0037', 'name' => 'Bolton');
$city_data[] = array('accid' => 'USMS0038', 'name' => 'Booneville');
$city_data[] = array('accid' => 'USMS0039', 'name' => 'Boyle');
$city_data[] = array('accid' => 'USMS0040', 'name' => 'Brandon');
$city_data[] = array('accid' => 'USMS0041', 'name' => 'Braxton');
$city_data[] = array('accid' => 'USMS0042', 'name' => 'Brookhaven');
$city_data[] = array('accid' => 'USMS0043', 'name' => 'Brooklyn');
$city_data[] = array('accid' => 'USMS0044', 'name' => 'Brooksville');
$city_data[] = array('accid' => 'USMS0045', 'name' => 'Bruce');
$city_data[] = array('accid' => 'USMS0046', 'name' => 'Buckatunna');
$city_data[] = array('accid' => 'USMS0047', 'name' => 'Bude');
$city_data[] = array('accid' => 'USMS0048', 'name' => 'Burnsville');
$city_data[] = array('accid' => 'USMS0049', 'name' => 'Byhalia');
$city_data[] = array('accid' => 'USMS0050', 'name' => 'Caledonia');
$city_data[] = array('accid' => 'USMS0051', 'name' => 'Calhoun City');
$city_data[] = array('accid' => 'USMS0052', 'name' => 'Camden');
$city_data[] = array('accid' => 'USMS0053', 'name' => 'Canton');
$city_data[] = array('accid' => 'USMS0054', 'name' => 'Carriere');
$city_data[] = array('accid' => 'USMS0055', 'name' => 'Carrollton');
$city_data[] = array('accid' => 'USMS0056', 'name' => 'Carson');
$city_data[] = array('accid' => 'USMS0057', 'name' => 'Carthage');
$city_data[] = array('accid' => 'USMS0058', 'name' => 'Cary');
$city_data[] = array('accid' => 'USMS0059', 'name' => 'Cascilla');
$city_data[] = array('accid' => 'USMS0060', 'name' => 'Cedarbluff');
$city_data[] = array('accid' => 'USMS0061', 'name' => 'Centreville');
$city_data[] = array('accid' => 'USMS0062', 'name' => 'Charleston');
$city_data[] = array('accid' => 'USMS0063', 'name' => 'Chatawa');
$city_data[] = array('accid' => 'USMS0064', 'name' => 'Chatham');
$city_data[] = array('accid' => 'USMS0065', 'name' => 'Chunky');
$city_data[] = array('accid' => 'USMS0066', 'name' => 'Clara');
$city_data[] = array('accid' => 'USMS0067', 'name' => 'Clarksdale');
$city_data[] = array('accid' => 'USMS0068', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USMS0069', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USMS0070', 'name' => 'Coahoma');
$city_data[] = array('accid' => 'USMS0071', 'name' => 'Coffeeville');
$city_data[] = array('accid' => 'USMS0072', 'name' => 'Coila');
$city_data[] = array('accid' => 'USMS0073', 'name' => 'Coldwater');
$city_data[] = array('accid' => 'USMS0074', 'name' => 'Collins');
$city_data[] = array('accid' => 'USMS0075', 'name' => 'Collinsville');
$city_data[] = array('accid' => 'USMS0076', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USMS0077', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USMS0079', 'name' => 'Como');
$city_data[] = array('accid' => 'USMS0080', 'name' => 'Conehatta');
$city_data[] = array('accid' => 'USMS0081', 'name' => 'Corinth');
$city_data[] = array('accid' => 'USMS0082', 'name' => 'Courtland');
$city_data[] = array('accid' => 'USMS0083', 'name' => 'Crawford');
$city_data[] = array('accid' => 'USMS0084', 'name' => 'Crenshaw');
$city_data[] = array('accid' => 'USMS0085', 'name' => 'Crosby');
$city_data[] = array('accid' => 'USMS0086', 'name' => 'Crowder');
$city_data[] = array('accid' => 'USMS0087', 'name' => 'Cruger');
$city_data[] = array('accid' => 'USMS0088', 'name' => 'Crystal Springs');
$city_data[] = array('accid' => 'USMS0089', 'name' => 'D Lo');
$city_data[] = array('accid' => 'USMS0090', 'name' => 'Daleville');
$city_data[] = array('accid' => 'USMS0091', 'name' => 'Darling');
$city_data[] = array('accid' => 'USMS0092', 'name' => 'De Kalb');
$city_data[] = array('accid' => 'USMS0093', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USMS0094', 'name' => 'Delta City');
$city_data[] = array('accid' => 'USMS0095', 'name' => 'Dennis');
$city_data[] = array('accid' => 'USMS0096', 'name' => 'Derma');
$city_data[] = array('accid' => 'USMS0097', 'name' => 'Diamondhead');
$city_data[] = array('accid' => 'USMS0441', 'name' => 'Diberville');
$city_data[] = array('accid' => 'USMS0098', 'name' => 'Doddsville');
$city_data[] = array('accid' => 'USMS0099', 'name' => 'Drew');
$city_data[] = array('accid' => 'USMS0100', 'name' => 'Dublin');
$city_data[] = array('accid' => 'USMS0101', 'name' => 'Duck Hill');
$city_data[] = array('accid' => 'USMS0102', 'name' => 'Dumas');
$city_data[] = array('accid' => 'USMS0103', 'name' => 'Duncan');
$city_data[] = array('accid' => 'USMS0104', 'name' => 'Dundee');
$city_data[] = array('accid' => 'USMS0105', 'name' => 'Durant');
$city_data[] = array('accid' => 'USMS0106', 'name' => 'Eastabuchie');
$city_data[] = array('accid' => 'USMS0107', 'name' => 'Ecru');
$city_data[] = array('accid' => 'USMS0108', 'name' => 'Edwards');
$city_data[] = array('accid' => 'USMS0109', 'name' => 'Elliott');
$city_data[] = array('accid' => 'USMS0110', 'name' => 'Ellisville');
$city_data[] = array('accid' => 'USMS0111', 'name' => 'Enid');
$city_data[] = array('accid' => 'USMS0112', 'name' => 'Enterprise');
$city_data[] = array('accid' => 'USMS0113', 'name' => 'Escatawpa');
$city_data[] = array('accid' => 'USMS0114', 'name' => 'Ethel');
$city_data[] = array('accid' => 'USMS0115', 'name' => 'Etta');
$city_data[] = array('accid' => 'USMS0116', 'name' => 'Eupora');
$city_data[] = array('accid' => 'USMS0117', 'name' => 'Falcon');
$city_data[] = array('accid' => 'USMS0118', 'name' => 'Falkner');
$city_data[] = array('accid' => 'USMS0119', 'name' => 'Farrell');
$city_data[] = array('accid' => 'USMS0120', 'name' => 'Fayette');
$city_data[] = array('accid' => 'USMS0121', 'name' => 'Fernwood');
$city_data[] = array('accid' => 'USMS0122', 'name' => 'Flora');
$city_data[] = array('accid' => 'USMS0123', 'name' => 'Florence');
$city_data[] = array('accid' => 'USMS0124', 'name' => 'Forest');
$city_data[] = array('accid' => 'USMS0125', 'name' => 'Foxworth');
$city_data[] = array('accid' => 'USMS0126', 'name' => 'French Camp');
$city_data[] = array('accid' => 'USMS0127', 'name' => 'Friars Point');
$city_data[] = array('accid' => 'USMS0128', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USMS0129', 'name' => 'Gallman');
$city_data[] = array('accid' => 'USMS0130', 'name' => 'Gattman');
$city_data[] = array('accid' => 'USMS0131', 'name' => 'Gautier');
$city_data[] = array('accid' => 'USMS0132', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USMS0133', 'name' => 'Glen');
$city_data[] = array('accid' => 'USMS0134', 'name' => 'Glen Allan');
$city_data[] = array('accid' => 'USMS0135', 'name' => 'Glendora');
$city_data[] = array('accid' => 'USMS0136', 'name' => 'Gloster');
$city_data[] = array('accid' => 'USMS0137', 'name' => 'Golden');
$city_data[] = array('accid' => 'USMS0138', 'name' => 'Goodman');
$city_data[] = array('accid' => 'USMS0139', 'name' => 'Gore Springs');
$city_data[] = array('accid' => 'USMS0140', 'name' => 'Grace');
$city_data[] = array('accid' => 'USMS0141', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USMS0142', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USMS0143', 'name' => 'Greenwood Springs');
$city_data[] = array('accid' => 'USMS0144', 'name' => 'Grenada');
$city_data[] = array('accid' => 'USMS0145', 'name' => 'Gulfport');
$city_data[] = array('accid' => 'USMS0146', 'name' => 'Gunnison');
$city_data[] = array('accid' => 'USMS0147', 'name' => 'Guntown');
$city_data[] = array('accid' => 'USMS0148', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USMS0149', 'name' => 'Harperville');
$city_data[] = array('accid' => 'USMS0150', 'name' => 'Harriston');
$city_data[] = array('accid' => 'USMS0151', 'name' => 'Harrisville');
$city_data[] = array('accid' => 'USMS0152', 'name' => 'Hattiesburg');
$city_data[] = array('accid' => 'USMS0153', 'name' => 'Hazlehurst');
$city_data[] = array('accid' => 'USMS0154', 'name' => 'Heidelberg');
$city_data[] = array('accid' => 'USMS0155', 'name' => 'Hermanville');
$city_data[] = array('accid' => 'USMS0156', 'name' => 'Hernando');
$city_data[] = array('accid' => 'USMS0157', 'name' => 'Hickory');
$city_data[] = array('accid' => 'USMS0158', 'name' => 'Hickory Flat');
$city_data[] = array('accid' => 'USMS0159', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USMS0160', 'name' => 'Holcomb');
$city_data[] = array('accid' => 'USMS0161', 'name' => 'Hollandale');
$city_data[] = array('accid' => 'USMS0162', 'name' => 'Holly Bluff');
$city_data[] = array('accid' => 'USMS0163', 'name' => 'Holly Ridge');
$city_data[] = array('accid' => 'USMS0164', 'name' => 'Holly Springs');
$city_data[] = array('accid' => 'USMS0165', 'name' => 'Horn Lake');
$city_data[] = array('accid' => 'USMS0166', 'name' => 'Houlka');
$city_data[] = array('accid' => 'USMS0167', 'name' => 'Houston');
$city_data[] = array('accid' => 'USMS0168', 'name' => 'Hurley');
$city_data[] = array('accid' => 'USMS0169', 'name' => 'Independence');
$city_data[] = array('accid' => 'USMS0170', 'name' => 'Indianola');
$city_data[] = array('accid' => 'USMS0171', 'name' => 'Inverness');
$city_data[] = array('accid' => 'USMS0172', 'name' => 'Isola');
$city_data[] = array('accid' => 'USMS0173', 'name' => 'Itta Bena');
$city_data[] = array('accid' => 'USMS0174', 'name' => 'Iuka');
$city_data[] = array('accid' => 'USMS0175', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USMS0176', 'name' => 'Jayess');
$city_data[] = array('accid' => 'USMS0177', 'name' => 'Jonestown');
$city_data[] = array('accid' => 'USMS0178', 'name' => 'Kilmichael');
$city_data[] = array('accid' => 'USMS0179', 'name' => 'Kiln');
$city_data[] = array('accid' => 'USMS0180', 'name' => 'Kokomo');
$city_data[] = array('accid' => 'USMS0181', 'name' => 'Kosciusko');
$city_data[] = array('accid' => 'USMS0182', 'name' => 'Lake');
$city_data[] = array('accid' => 'USMS0183', 'name' => 'Lake Cormorant');
$city_data[] = array('accid' => 'USMS0184', 'name' => 'Lakeshore');
$city_data[] = array('accid' => 'USMS0185', 'name' => 'Lamar');
$city_data[] = array('accid' => 'USMS0186', 'name' => 'Lambert');
$city_data[] = array('accid' => 'USMS0187', 'name' => 'Lauderdale');
$city_data[] = array('accid' => 'USMS0188', 'name' => 'Laurel');
$city_data[] = array('accid' => 'USMS0189', 'name' => 'Lawrence');
$city_data[] = array('accid' => 'USMS0190', 'name' => 'Leakesville');
$city_data[] = array('accid' => 'USMS0191', 'name' => 'Leland');
$city_data[] = array('accid' => 'USMS0192', 'name' => 'Lena');
$city_data[] = array('accid' => 'USMS0193', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USMS0194', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USMS0195', 'name' => 'Little Rock');
$city_data[] = array('accid' => 'USMS0196', 'name' => 'Long Beach');
$city_data[] = array('accid' => 'USMS0197', 'name' => 'Lorman');
$city_data[] = array('accid' => 'USMS0198', 'name' => 'Louin');
$city_data[] = array('accid' => 'USMS0199', 'name' => 'Louise');
$city_data[] = array('accid' => 'USMS0200', 'name' => 'Louisville');
$city_data[] = array('accid' => 'USMS0201', 'name' => 'Lucedale');
$city_data[] = array('accid' => 'USMS0202', 'name' => 'Ludlow');
$city_data[] = array('accid' => 'USMS0203', 'name' => 'Lula');
$city_data[] = array('accid' => 'USMS0204', 'name' => 'Lumberton');
$city_data[] = array('accid' => 'USMS0205', 'name' => 'Lyon');
$city_data[] = array('accid' => 'USMS0206', 'name' => 'Maben');
$city_data[] = array('accid' => 'USMS0207', 'name' => 'Macon');
$city_data[] = array('accid' => 'USMS0208', 'name' => 'Madden');
$city_data[] = array('accid' => 'USMS0209', 'name' => 'Madison');
$city_data[] = array('accid' => 'USMS0210', 'name' => 'Magee');
$city_data[] = array('accid' => 'USMS0211', 'name' => 'Magnolia');
$city_data[] = array('accid' => 'USMS0212', 'name' => 'Mantachie');
$city_data[] = array('accid' => 'USMS0213', 'name' => 'Mantee');
$city_data[] = array('accid' => 'USMS0214', 'name' => 'Marietta');
$city_data[] = array('accid' => 'USMS0215', 'name' => 'Marion');
$city_data[] = array('accid' => 'USMS0216', 'name' => 'Marks');
$city_data[] = array('accid' => 'USMS0217', 'name' => 'Mathiston');
$city_data[] = array('accid' => 'USMS0218', 'name' => 'Mattson');
$city_data[] = array('accid' => 'USMS0219', 'name' => 'Mayersville');
$city_data[] = array('accid' => 'USMS0220', 'name' => 'Mayhew');
$city_data[] = array('accid' => 'USMS0221', 'name' => 'McAdams');
$city_data[] = array('accid' => 'USMS0222', 'name' => 'McCall Creek');
$city_data[] = array('accid' => 'USMS0223', 'name' => 'McCarley');
$city_data[] = array('accid' => 'USMS0224', 'name' => 'McComb');
$city_data[] = array('accid' => 'USMS0225', 'name' => 'McCondy');
$city_data[] = array('accid' => 'USMS0226', 'name' => 'McCool');
$city_data[] = array('accid' => 'USMS0227', 'name' => 'McHenry');
$city_data[] = array('accid' => 'USMS0228', 'name' => 'McLain');
$city_data[] = array('accid' => 'USMS0229', 'name' => 'McNeill');
$city_data[] = array('accid' => 'USMS0230', 'name' => 'Meadville');
$city_data[] = array('accid' => 'USMS0231', 'name' => 'Mendenhall');
$city_data[] = array('accid' => 'USMS0232', 'name' => 'Meridian');
$city_data[] = array('accid' => 'USMS0234', 'name' => 'Merigold');
$city_data[] = array('accid' => 'USMS0235', 'name' => 'Metcalfe');
$city_data[] = array('accid' => 'USMS0236', 'name' => 'Michigan City');
$city_data[] = array('accid' => 'USMS0237', 'name' => 'Midnight');
$city_data[] = array('accid' => 'USMS0238', 'name' => 'Minter City');
$city_data[] = array('accid' => 'USMS0239', 'name' => 'Mississippi State');
$city_data[] = array('accid' => 'USMS0240', 'name' => 'Mize');
$city_data[] = array('accid' => 'USMS0241', 'name' => 'Money');
$city_data[] = array('accid' => 'USMS0242', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USMS0243', 'name' => 'Montpelier');
$city_data[] = array('accid' => 'USMS0244', 'name' => 'Mooreville');
$city_data[] = array('accid' => 'USMS0245', 'name' => 'Moorhead');
$city_data[] = array('accid' => 'USMS0246', 'name' => 'Morgan City');
$city_data[] = array('accid' => 'USMS0247', 'name' => 'Morton');
$city_data[] = array('accid' => 'USMS0248', 'name' => 'Moselle');
$city_data[] = array('accid' => 'USMS0249', 'name' => 'Moss');
$city_data[] = array('accid' => 'USMS0250', 'name' => 'Moss Point');
$city_data[] = array('accid' => 'USMS0251', 'name' => 'Mound Bayou');
$city_data[] = array('accid' => 'USMS0252', 'name' => 'Mount Olive');
$city_data[] = array('accid' => 'USMS0253', 'name' => 'Mount Pleasant');
$city_data[] = array('accid' => 'USMS0254', 'name' => 'Myrtle');
$city_data[] = array('accid' => 'USMS0255', 'name' => 'Natchez');
$city_data[] = array('accid' => 'USMS0256', 'name' => 'Neely');
$city_data[] = array('accid' => 'USMS0257', 'name' => 'Nesbit');
$city_data[] = array('accid' => 'USMS0258', 'name' => 'Nettleton');
$city_data[] = array('accid' => 'USMS0259', 'name' => 'New Albany');
$city_data[] = array('accid' => 'USMS0260', 'name' => 'New Augusta');
$city_data[] = array('accid' => 'USMS0261', 'name' => 'New Site');
$city_data[] = array('accid' => 'USMS0262', 'name' => 'Newhebron');
$city_data[] = array('accid' => 'USMS0263', 'name' => 'Newton');
$city_data[] = array('accid' => 'USMS0264', 'name' => 'Nicholson');
$city_data[] = array('accid' => 'USMS0265', 'name' => 'Nitta Yuma');
$city_data[] = array('accid' => 'USMS0266', 'name' => 'North Carrollton');
$city_data[] = array('accid' => 'USMS0267', 'name' => 'Noxapater');
$city_data[] = array('accid' => 'USMS0268', 'name' => 'Oak Vale');
$city_data[] = array('accid' => 'USMS0269', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USMS0270', 'name' => 'Ocean Springs');
$city_data[] = array('accid' => 'USMS0271', 'name' => 'Okolona');
$city_data[] = array('accid' => 'USMS0272', 'name' => 'Olive Branch');
$city_data[] = array('accid' => 'USMS0273', 'name' => 'Osyka');
$city_data[] = array('accid' => 'USMS0274', 'name' => 'Ovett');
$city_data[] = array('accid' => 'USMS0275', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USMS0276', 'name' => 'Pace');
$city_data[] = array('accid' => 'USMS0277', 'name' => 'Pachuta');
$city_data[] = array('accid' => 'USMS0278', 'name' => 'Panther Burn');
$city_data[] = array('accid' => 'USMS0279', 'name' => 'Parchman');
$city_data[] = array('accid' => 'USMS0280', 'name' => 'Paris');
$city_data[] = array('accid' => 'USMS0281', 'name' => 'Pascagoula');
$city_data[] = array('accid' => 'USMS0282', 'name' => 'Pass Christian');
$city_data[] = array('accid' => 'USMS0283', 'name' => 'Pattison');
$city_data[] = array('accid' => 'USMS0284', 'name' => 'Paulding');
$city_data[] = array('accid' => 'USMS0285', 'name' => 'Pearlington');
$city_data[] = array('accid' => 'USMS0286', 'name' => 'Pelahatchie');
$city_data[] = array('accid' => 'USMS0287', 'name' => 'Perkinston');
$city_data[] = array('accid' => 'USMS0288', 'name' => 'Petal');
$city_data[] = array('accid' => 'USMS0289', 'name' => 'Pheba');
$city_data[] = array('accid' => 'USMS0290', 'name' => 'Philadelphia');
$city_data[] = array('accid' => 'USMS0291', 'name' => 'Philipp');
$city_data[] = array('accid' => 'USMS0292', 'name' => 'Picayune');
$city_data[] = array('accid' => 'USMS0293', 'name' => 'Pickens');
$city_data[] = array('accid' => 'USMS0294', 'name' => 'Piney Woods');
$city_data[] = array('accid' => 'USMS0295', 'name' => 'Pinola');
$city_data[] = array('accid' => 'USMS0296', 'name' => 'Pittsboro');
$city_data[] = array('accid' => 'USMS0297', 'name' => 'Plantersville');
$city_data[] = array('accid' => 'USMS0298', 'name' => 'Pocahontas');
$city_data[] = array('accid' => 'USMS0299', 'name' => 'Pontotoc');
$city_data[] = array('accid' => 'USMS0300', 'name' => 'Pope');
$city_data[] = array('accid' => 'USMS0301', 'name' => 'Poplarville');
$city_data[] = array('accid' => 'USMS0302', 'name' => 'Port Gibson');
$city_data[] = array('accid' => 'USMS0303', 'name' => 'Porterville');
$city_data[] = array('accid' => 'USMS0304', 'name' => 'Potts Camp');
$city_data[] = array('accid' => 'USMS0305', 'name' => 'Prairie');
$city_data[] = array('accid' => 'USMS0306', 'name' => 'Prentiss');
$city_data[] = array('accid' => 'USMS0307', 'name' => 'Preston');
$city_data[] = array('accid' => 'USMS0308', 'name' => 'Puckett');
$city_data[] = array('accid' => 'USMS0309', 'name' => 'Pulaski');
$city_data[] = array('accid' => 'USMS0310', 'name' => 'Purvis');
$city_data[] = array('accid' => 'USMS0311', 'name' => 'Quitman');
$city_data[] = array('accid' => 'USMS0312', 'name' => 'Raleigh');
$city_data[] = array('accid' => 'USMS0313', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USMS0314', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USMS0315', 'name' => 'Red Banks');
$city_data[] = array('accid' => 'USMS0316', 'name' => 'Redwood');
$city_data[] = array('accid' => 'USMS0317', 'name' => 'Rena Lara');
$city_data[] = array('accid' => 'USMS0318', 'name' => 'Richton');
$city_data[] = array('accid' => 'USMS0319', 'name' => 'Ridgeland');
$city_data[] = array('accid' => 'USMS0320', 'name' => 'Rienzi');
$city_data[] = array('accid' => 'USMS0321', 'name' => 'Ripley');
$city_data[] = array('accid' => 'USMS0322', 'name' => 'Robinsonville');
$city_data[] = array('accid' => 'USMS0323', 'name' => 'Rolling Fork');
$city_data[] = array('accid' => 'USMS0324', 'name' => 'Rome');
$city_data[] = array('accid' => 'USMS0325', 'name' => 'Rose Hill');
$city_data[] = array('accid' => 'USMS0326', 'name' => 'Rosedale');
$city_data[] = array('accid' => 'USMS0327', 'name' => 'Roxie');
$city_data[] = array('accid' => 'USMS0328', 'name' => 'Ruleville');
$city_data[] = array('accid' => 'USMS0329', 'name' => 'Ruth');
$city_data[] = array('accid' => 'USMS0330', 'name' => 'Sallis');
$city_data[] = array('accid' => 'USMS0331', 'name' => 'Saltillo');
$city_data[] = array('accid' => 'USMS0332', 'name' => 'Sanatorium');
$city_data[] = array('accid' => 'USMS0333', 'name' => 'Sandersville');
$city_data[] = array('accid' => 'USMS0334', 'name' => 'Sandhill');
$city_data[] = array('accid' => 'USMS0335', 'name' => 'Sandy Hook');
$city_data[] = array('accid' => 'USMS0336', 'name' => 'Sarah');
$city_data[] = array('accid' => 'USMS0337', 'name' => 'Sardis');
$city_data[] = array('accid' => 'USMS0338', 'name' => 'Satartia');
$city_data[] = array('accid' => 'USMS0339', 'name' => 'Saucier');
$city_data[] = array('accid' => 'USMS0340', 'name' => 'Schlater');
$city_data[] = array('accid' => 'USMS0341', 'name' => 'Scobey');
$city_data[] = array('accid' => 'USMS0342', 'name' => 'Scooba');
$city_data[] = array('accid' => 'USMS0343', 'name' => 'Scott');
$city_data[] = array('accid' => 'USMS0344', 'name' => 'Sebastopol');
$city_data[] = array('accid' => 'USMS0345', 'name' => 'Seminary');
$city_data[] = array('accid' => 'USMS0346', 'name' => 'Senatobia');
$city_data[] = array('accid' => 'USMS0347', 'name' => 'Shannon');
$city_data[] = array('accid' => 'USMS0348', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USMS0349', 'name' => 'Shaw');
$city_data[] = array('accid' => 'USMS0350', 'name' => 'Shelby');
$city_data[] = array('accid' => 'USMS0351', 'name' => 'Sherard');
$city_data[] = array('accid' => 'USMS0352', 'name' => 'Sherman');
$city_data[] = array('accid' => 'USMS0353', 'name' => 'Shubuta');
$city_data[] = array('accid' => 'USMS0354', 'name' => 'Shuqualak');
$city_data[] = array('accid' => 'USMS0355', 'name' => 'Sibley');
$city_data[] = array('accid' => 'USMS0356', 'name' => 'Sidon');
$city_data[] = array('accid' => 'USMS0357', 'name' => 'Silver City');
$city_data[] = array('accid' => 'USMS0358', 'name' => 'Silver Creek');
$city_data[] = array('accid' => 'USMS0359', 'name' => 'Slate Spring');
$city_data[] = array('accid' => 'USMS0360', 'name' => 'Sledge');
$city_data[] = array('accid' => 'USMS0361', 'name' => 'Smithdale');
$city_data[] = array('accid' => 'USMS0362', 'name' => 'Smithville');
$city_data[] = array('accid' => 'USMS0363', 'name' => 'Sontag');
$city_data[] = array('accid' => 'USMS0364', 'name' => 'Soso');
$city_data[] = array('accid' => 'USMS0365', 'name' => 'Southaven');
$city_data[] = array('accid' => 'USMS0366', 'name' => 'Star');
$city_data[] = array('accid' => 'USMS0367', 'name' => 'Starkville');
$city_data[] = array('accid' => 'USMS0368', 'name' => 'State Line');
$city_data[] = array('accid' => 'USMS0369', 'name' => 'Steens');
$city_data[] = array('accid' => 'USMS0370', 'name' => 'Stewart');
$city_data[] = array('accid' => 'USMS0371', 'name' => 'Stoneville');
$city_data[] = array('accid' => 'USMS0372', 'name' => 'Stonewall');
$city_data[] = array('accid' => 'USMS0373', 'name' => 'Stringer');
$city_data[] = array('accid' => 'USMS0374', 'name' => 'Sturgis');
$city_data[] = array('accid' => 'USMS0375', 'name' => 'Summit');
$city_data[] = array('accid' => 'USMS0376', 'name' => 'Sumner');
$city_data[] = array('accid' => 'USMS0377', 'name' => 'Sumrall');
$city_data[] = array('accid' => 'USMS0378', 'name' => 'Sunflower');
$city_data[] = array('accid' => 'USMS0379', 'name' => 'Swan Lake');
$city_data[] = array('accid' => 'USMS0380', 'name' => 'Swiftown');
$city_data[] = array('accid' => 'USMS0381', 'name' => 'Taylor');
$city_data[] = array('accid' => 'USMS0382', 'name' => 'Taylorsville');
$city_data[] = array('accid' => 'USMS0383', 'name' => 'Tchula');
$city_data[] = array('accid' => 'USMS0384', 'name' => 'Terry');
$city_data[] = array('accid' => 'USMS0385', 'name' => 'Thaxton');
$city_data[] = array('accid' => 'USMS0386', 'name' => 'Thomastown');
$city_data[] = array('accid' => 'USMS0387', 'name' => 'Tie Plant');
$city_data[] = array('accid' => 'USMS0388', 'name' => 'Tillatoba');
$city_data[] = array('accid' => 'USMS0389', 'name' => 'Tinsley');
$city_data[] = array('accid' => 'USMS0390', 'name' => 'Tiplersville');
$city_data[] = array('accid' => 'USMS0391', 'name' => 'Tippo');
$city_data[] = array('accid' => 'USMS0392', 'name' => 'Tishomingo');
$city_data[] = array('accid' => 'USMS0393', 'name' => 'Toccopola');
$city_data[] = array('accid' => 'USMS0394', 'name' => 'Toomsuba');
$city_data[] = array('accid' => 'USMS0395', 'name' => 'Tougaloo');
$city_data[] = array('accid' => 'USMS0396', 'name' => 'Trebloc');
$city_data[] = array('accid' => 'USMS0397', 'name' => 'Tremont');
$city_data[] = array('accid' => 'USMS0398', 'name' => 'Tula');
$city_data[] = array('accid' => 'USMS0399', 'name' => 'Tunica');
$city_data[] = array('accid' => 'USMS0400', 'name' => 'Tupelo');
$city_data[] = array('accid' => 'USMS0401', 'name' => 'Tutwiler');
$city_data[] = array('accid' => 'USMS0402', 'name' => 'Tylertown');
$city_data[] = array('accid' => 'USMS0403', 'name' => 'Union');
$city_data[] = array('accid' => 'USMS0404', 'name' => 'Union Church');
$city_data[] = array('accid' => 'USMS0405', 'name' => 'University');
$city_data[] = array('accid' => 'USMS0406', 'name' => 'Utica');
$city_data[] = array('accid' => 'USMS0407', 'name' => 'Vaiden');
$city_data[] = array('accid' => 'USMS0408', 'name' => 'Valley Park');
$city_data[] = array('accid' => 'USMS0409', 'name' => 'Van Vleet');
$city_data[] = array('accid' => 'USMS0410', 'name' => 'Vance');
$city_data[] = array('accid' => 'USMS0411', 'name' => 'Vardaman');
$city_data[] = array('accid' => 'USMS0412', 'name' => 'Vaughan');
$city_data[] = array('accid' => 'USMS0413', 'name' => 'Verona');
$city_data[] = array('accid' => 'USMS0414', 'name' => 'Vicksburg');
$city_data[] = array('accid' => 'USMS0415', 'name' => 'Victoria');
$city_data[] = array('accid' => 'USMS0416', 'name' => 'Vossburg');
$city_data[] = array('accid' => 'USMS0417', 'name' => 'Walls');
$city_data[] = array('accid' => 'USMS0418', 'name' => 'Walnut');
$city_data[] = array('accid' => 'USMS0419', 'name' => 'Walnut Grove');
$city_data[] = array('accid' => 'USMS0420', 'name' => 'Walthall');
$city_data[] = array('accid' => 'USMS0421', 'name' => 'Washington');
$city_data[] = array('accid' => 'USMS0422', 'name' => 'Water Valley');
$city_data[] = array('accid' => 'USMS0423', 'name' => 'Waterford');
$city_data[] = array('accid' => 'USMS0424', 'name' => 'Waveland');
$city_data[] = array('accid' => 'USMS0425', 'name' => 'Waynesboro');
$city_data[] = array('accid' => 'USMS0426', 'name' => 'Wayside');
$city_data[] = array('accid' => 'USMS0427', 'name' => 'Webb');
$city_data[] = array('accid' => 'USMS0428', 'name' => 'Weir');
$city_data[] = array('accid' => 'USMS0429', 'name' => 'Wesson');
$city_data[] = array('accid' => 'USMS0430', 'name' => 'West');
$city_data[] = array('accid' => 'USMS0431', 'name' => 'West Point');
$city_data[] = array('accid' => 'USMS0432', 'name' => 'Wheeler');
$city_data[] = array('accid' => 'USMS0433', 'name' => 'Whitfield');
$city_data[] = array('accid' => 'USMS0434', 'name' => 'Wiggins');
$city_data[] = array('accid' => 'USMS0435', 'name' => 'Winona');
$city_data[] = array('accid' => 'USMS0436', 'name' => 'Winstonville');
$city_data[] = array('accid' => 'USMS0437', 'name' => 'Winterville');
$city_data[] = array('accid' => 'USMS0438', 'name' => 'Woodland');
$city_data[] = array('accid' => 'USMS0439', 'name' => 'Woodville');
$city_data[] = array('accid' => 'USMS0440', 'name' => 'Yazoo City');

?>
