<?php

// City package for USA: Montana 

$city_name = 'USA: Montana';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USMT0001', 'name' => 'Absarokee');
$city_data[] = array('accid' => 'USMT0002', 'name' => 'Acton');
$city_data[] = array('accid' => 'USMT0003', 'name' => 'Alberton');
$city_data[] = array('accid' => 'USMT0004', 'name' => 'Alder');
$city_data[] = array('accid' => 'USMT0005', 'name' => 'Alzada');
$city_data[] = array('accid' => 'USMT0006', 'name' => 'Anaconda');
$city_data[] = array('accid' => 'USMT0007', 'name' => 'Angela');
$city_data[] = array('accid' => 'USMT0008', 'name' => 'Antelope');
$city_data[] = array('accid' => 'USMT0009', 'name' => 'Arlee');
$city_data[] = array('accid' => 'USMT0010', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USMT0011', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USMT0012', 'name' => 'Avon');
$city_data[] = array('accid' => 'USMT0013', 'name' => 'Babb');
$city_data[] = array('accid' => 'USMT0014', 'name' => 'Bainville');
$city_data[] = array('accid' => 'USMT0015', 'name' => 'Baker');
$city_data[] = array('accid' => 'USMT0016', 'name' => 'Ballantine');
$city_data[] = array('accid' => 'USMT0017', 'name' => 'Basin');
$city_data[] = array('accid' => 'USMT0018', 'name' => 'Bearcreek');
$city_data[] = array('accid' => 'USMT0019', 'name' => 'Belfry');
$city_data[] = array('accid' => 'USMT0020', 'name' => 'Belgrade');
$city_data[] = array('accid' => 'USMT0021', 'name' => 'Belt');
$city_data[] = array('accid' => 'USMT0022', 'name' => 'Biddle');
$city_data[] = array('accid' => 'USMT0023', 'name' => 'Big Arm');
$city_data[] = array('accid' => 'USMT0025', 'name' => 'Big Sandy');
$city_data[] = array('accid' => 'USMT0026', 'name' => 'Big Sky');
$city_data[] = array('accid' => 'USMT0028', 'name' => 'Big Timber');
$city_data[] = array('accid' => 'USMT0029', 'name' => 'Bigfork');
$city_data[] = array('accid' => 'USMT0030', 'name' => 'Bighorn');
$city_data[] = array('accid' => 'USMT0031', 'name' => 'Billings');
$city_data[] = array('accid' => 'USMT0032', 'name' => 'Birney');
$city_data[] = array('accid' => 'USMT0033', 'name' => 'Black Eagle');
$city_data[] = array('accid' => 'USMT0034', 'name' => 'Bloomfield');
$city_data[] = array('accid' => 'USMT0035', 'name' => 'Bonner');
$city_data[] = array('accid' => 'USMT0036', 'name' => 'Boulder');
$city_data[] = array('accid' => 'USMT0037', 'name' => 'Box Elder');
$city_data[] = array('accid' => 'USMT0038', 'name' => 'Boyd');
$city_data[] = array('accid' => 'USMT0039', 'name' => 'Boyes');
$city_data[] = array('accid' => 'USMT0040', 'name' => 'Bozeman');
$city_data[] = array('accid' => 'USMT0041', 'name' => 'Brady');
$city_data[] = array('accid' => 'USMT0042', 'name' => 'Bridger');
$city_data[] = array('accid' => 'USMT0044', 'name' => 'Broadus');
$city_data[] = array('accid' => 'USMT0045', 'name' => 'Broadview');
$city_data[] = array('accid' => 'USMT0046', 'name' => 'Brockton');
$city_data[] = array('accid' => 'USMT0047', 'name' => 'Brockway');
$city_data[] = array('accid' => 'USMT0048', 'name' => 'Browning');
$city_data[] = array('accid' => 'USMT0049', 'name' => 'Brusett');
$city_data[] = array('accid' => 'USMT0050', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USMT0051', 'name' => 'Busby');
$city_data[] = array('accid' => 'USMT0052', 'name' => 'Butte');
$city_data[] = array('accid' => 'USMT0053', 'name' => 'Bynum');
$city_data[] = array('accid' => 'USMT0054', 'name' => 'Cameron');
$city_data[] = array('accid' => 'USMT0055', 'name' => 'Canyon Creek');
$city_data[] = array('accid' => 'USMT0056', 'name' => 'Capitol');
$city_data[] = array('accid' => 'USMT0057', 'name' => 'Cardwell');
$city_data[] = array('accid' => 'USMT0058', 'name' => 'Carter');
$city_data[] = array('accid' => 'USMT0059', 'name' => 'Cascade');
$city_data[] = array('accid' => 'USMT0060', 'name' => 'Charlo');
$city_data[] = array('accid' => 'USMT0061', 'name' => 'Chester');
$city_data[] = array('accid' => 'USMT0062', 'name' => 'Chinook');
$city_data[] = array('accid' => 'USMT0063', 'name' => 'Choteau');
$city_data[] = array('accid' => 'USMT0064', 'name' => 'Circle');
$city_data[] = array('accid' => 'USMT0065', 'name' => 'Clancy');
$city_data[] = array('accid' => 'USMT0066', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USMT0067', 'name' => 'Clyde Park');
$city_data[] = array('accid' => 'USMT0068', 'name' => 'Coffee Creek');
$city_data[] = array('accid' => 'USMT0069', 'name' => 'Cohagen');
$city_data[] = array('accid' => 'USMT0070', 'name' => 'Colstrip');
$city_data[] = array('accid' => 'USMT0071', 'name' => 'Columbia Falls');
$city_data[] = array('accid' => 'USMT0072', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USMT0073', 'name' => 'Condon');
$city_data[] = array('accid' => 'USMT0074', 'name' => 'Conner');
$city_data[] = array('accid' => 'USMT0075', 'name' => 'Conrad');
$city_data[] = array('accid' => 'USMT0076', 'name' => 'Cooke City');
$city_data[] = array('accid' => 'USMT0077', 'name' => 'Coram');
$city_data[] = array('accid' => 'USMT0078', 'name' => 'Corvallis');
$city_data[] = array('accid' => 'USMT0079', 'name' => 'Crane');
$city_data[] = array('accid' => 'USMT0080', 'name' => 'Crow Agency');
$city_data[] = array('accid' => 'USMT0081', 'name' => 'Culbertson');
$city_data[] = array('accid' => 'USMT0082', 'name' => 'Custer');
$city_data[] = array('accid' => 'USMT0083', 'name' => 'Cut Bank');
$city_data[] = array('accid' => 'USMT0084', 'name' => 'Dagmar');
$city_data[] = array('accid' => 'USMT0085', 'name' => 'Darby');
$city_data[] = array('accid' => 'USMT0086', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USMT0087', 'name' => 'De Borgia');
$city_data[] = array('accid' => 'USMT0088', 'name' => 'Decker');
$city_data[] = array('accid' => 'USMT0089', 'name' => 'Deer Lodge');
$city_data[] = array('accid' => 'USMT0090', 'name' => 'Dell');
$city_data[] = array('accid' => 'USMT0091', 'name' => 'Denton');
$city_data[] = array('accid' => 'USMT0092', 'name' => 'Dillon');
$city_data[] = array('accid' => 'USMT0094', 'name' => 'Divide');
$city_data[] = array('accid' => 'USMT0095', 'name' => 'Dixon');
$city_data[] = array('accid' => 'USMT0096', 'name' => 'Dodson');
$city_data[] = array('accid' => 'USMT0097', 'name' => 'Drummond');
$city_data[] = array('accid' => 'USMT0098', 'name' => 'Dupuyer');
$city_data[] = array('accid' => 'USMT0099', 'name' => 'Dutton');
$city_data[] = array('accid' => 'USMT0100', 'name' => 'East Glacier Park');
$city_data[] = array('accid' => 'USMT0101', 'name' => 'East Helena');
$city_data[] = array('accid' => 'USMT0102', 'name' => 'Edgar');
$city_data[] = array('accid' => 'USMT0103', 'name' => 'Ekalaka');
$city_data[] = array('accid' => 'USMT0104', 'name' => 'Elliston');
$city_data[] = array('accid' => 'USMT0105', 'name' => 'Elmo');
$city_data[] = array('accid' => 'USMT0106', 'name' => 'Emigrant');
$city_data[] = array('accid' => 'USMT0107', 'name' => 'Ennis');
$city_data[] = array('accid' => 'USMT0108', 'name' => 'Essex');
$city_data[] = array('accid' => 'USMT0109', 'name' => 'Ethridge');
$city_data[] = array('accid' => 'USMT0110', 'name' => 'Eureka');
$city_data[] = array('accid' => 'USMT0111', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USMT0112', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USMT0113', 'name' => 'Fallon');
$city_data[] = array('accid' => 'USMT0114', 'name' => 'Fishtail');
$city_data[] = array('accid' => 'USMT0115', 'name' => 'Flaxville');
$city_data[] = array('accid' => 'USMT0116', 'name' => 'Florence');
$city_data[] = array('accid' => 'USMT0117', 'name' => 'Floweree');
$city_data[] = array('accid' => 'USMT0118', 'name' => 'Forestgrove');
$city_data[] = array('accid' => 'USMT0119', 'name' => 'Forsyth');
$city_data[] = array('accid' => 'USMT0120', 'name' => 'Fort Benton');
$city_data[] = array('accid' => 'USMT0121', 'name' => 'Fort Harrison');
$city_data[] = array('accid' => 'USMT0122', 'name' => 'Fort Peck');
$city_data[] = array('accid' => 'USMT0123', 'name' => 'Fort Shaw');
$city_data[] = array('accid' => 'USMT0124', 'name' => 'Fortine');
$city_data[] = array('accid' => 'USMT0125', 'name' => 'Frazer');
$city_data[] = array('accid' => 'USMT0126', 'name' => 'Frenchtown');
$city_data[] = array('accid' => 'USMT0127', 'name' => 'Froid');
$city_data[] = array('accid' => 'USMT0128', 'name' => 'Fromberg');
$city_data[] = array('accid' => 'USMT0129', 'name' => 'Galata');
$city_data[] = array('accid' => 'USMT0130', 'name' => 'Gallatin Gateway');
$city_data[] = array('accid' => 'USMT0131', 'name' => 'Gardiner');
$city_data[] = array('accid' => 'USMT0132', 'name' => 'Garneill');
$city_data[] = array('accid' => 'USMT0133', 'name' => 'Garrison');
$city_data[] = array('accid' => 'USMT0134', 'name' => 'Garryowen');
$city_data[] = array('accid' => 'USMT0135', 'name' => 'Geraldine');
$city_data[] = array('accid' => 'USMT0136', 'name' => 'Geyser');
$city_data[] = array('accid' => 'USMT0137', 'name' => 'Gildford');
$city_data[] = array('accid' => 'USMT0139', 'name' => 'Glasgow');
$city_data[] = array('accid' => 'USMT0140', 'name' => 'Glen');
$city_data[] = array('accid' => 'USMT0141', 'name' => 'Glendive');
$city_data[] = array('accid' => 'USMT0142', 'name' => 'Glentana');
$city_data[] = array('accid' => 'USMT0143', 'name' => 'Gold Creek');
$city_data[] = array('accid' => 'USMT0144', 'name' => 'Grantsdale');
$city_data[] = array('accid' => 'USMT0145', 'name' => 'Grass Range');
$city_data[] = array('accid' => 'USMT0146', 'name' => 'Great Falls');
$city_data[] = array('accid' => 'USMT0148', 'name' => 'Greenough');
$city_data[] = array('accid' => 'USMT0149', 'name' => 'Greycliff');
$city_data[] = array('accid' => 'USMT0150', 'name' => 'Hall');
$city_data[] = array('accid' => 'USMT0151', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USMT0152', 'name' => 'Hammond');
$city_data[] = array('accid' => 'USMT0153', 'name' => 'Hardin');
$city_data[] = array('accid' => 'USMT0154', 'name' => 'Harlem');
$city_data[] = array('accid' => 'USMT0155', 'name' => 'Harlowton');
$city_data[] = array('accid' => 'USMT0156', 'name' => 'Harrison');
$city_data[] = array('accid' => 'USMT0157', 'name' => 'Hathaway');
$city_data[] = array('accid' => 'USMT0158', 'name' => 'Haugan');
$city_data[] = array('accid' => 'USMT0159', 'name' => 'Havre');
$city_data[] = array('accid' => 'USMT0160', 'name' => 'Hays');
$city_data[] = array('accid' => 'USMT0161', 'name' => 'Heart Butte');
$city_data[] = array('accid' => 'USMT0163', 'name' => 'Helena');
$city_data[] = array('accid' => 'USMT0164', 'name' => 'Helmville');
$city_data[] = array('accid' => 'USMT0165', 'name' => 'Heron');
$city_data[] = array('accid' => 'USMT0166', 'name' => 'Highwood');
$city_data[] = array('accid' => 'USMT0167', 'name' => 'Hilger');
$city_data[] = array('accid' => 'USMT0168', 'name' => 'Hingham');
$city_data[] = array('accid' => 'USMT0169', 'name' => 'Hinsdale');
$city_data[] = array('accid' => 'USMT0170', 'name' => 'Hobson');
$city_data[] = array('accid' => 'USMT0171', 'name' => 'Hogeland');
$city_data[] = array('accid' => 'USMT0172', 'name' => 'Homestead');
$city_data[] = array('accid' => 'USMT0173', 'name' => 'Hot Springs');
$city_data[] = array('accid' => 'USMT0175', 'name' => 'Hungry Horse');
$city_data[] = array('accid' => 'USMT0176', 'name' => 'Huntley');
$city_data[] = array('accid' => 'USMT0177', 'name' => 'Huson');
$city_data[] = array('accid' => 'USMT0178', 'name' => 'Hysham');
$city_data[] = array('accid' => 'USMT0179', 'name' => 'Ingomar');
$city_data[] = array('accid' => 'USMT0180', 'name' => 'Inverness');
$city_data[] = array('accid' => 'USMT0181', 'name' => 'Ismay');
$city_data[] = array('accid' => 'USMT0182', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USMT0183', 'name' => 'Jefferson City');
$city_data[] = array('accid' => 'USMT0184', 'name' => 'Joliet');
$city_data[] = array('accid' => 'USMT0185', 'name' => 'Joplin');
$city_data[] = array('accid' => 'USMT0186', 'name' => 'Jordan');
$city_data[] = array('accid' => 'USMT0187', 'name' => 'Judith Gap');
$city_data[] = array('accid' => 'USMT0188', 'name' => 'Kalispell');
$city_data[] = array('accid' => 'USMT0189', 'name' => 'Kevin');
$city_data[] = array('accid' => 'USMT0190', 'name' => 'Kila');
$city_data[] = array('accid' => 'USMT0191', 'name' => 'Kinsey');
$city_data[] = array('accid' => 'USMT0192', 'name' => 'Kremlin');
$city_data[] = array('accid' => 'USMT0193', 'name' => 'Lake McDonald');
$city_data[] = array('accid' => 'USMT0194', 'name' => 'Lakeside');
$city_data[] = array('accid' => 'USMT0195', 'name' => 'Lambert');
$city_data[] = array('accid' => 'USMT0196', 'name' => 'Lame Deer');
$city_data[] = array('accid' => 'USMT0197', 'name' => 'Larslan');
$city_data[] = array('accid' => 'USMT0198', 'name' => 'Laurel');
$city_data[] = array('accid' => 'USMT0199', 'name' => 'Lavina');
$city_data[] = array('accid' => 'USMT0200', 'name' => 'Ledger');
$city_data[] = array('accid' => 'USMT0201', 'name' => 'Lewistown');
$city_data[] = array('accid' => 'USMT0202', 'name' => 'Libby');
$city_data[] = array('accid' => 'USMT0203', 'name' => 'Lima');
$city_data[] = array('accid' => 'USMT0204', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USMT0205', 'name' => 'Lindsay');
$city_data[] = array('accid' => 'USMT0206', 'name' => 'Livingston');
$city_data[] = array('accid' => 'USMT0207', 'name' => 'Lloyd');
$city_data[] = array('accid' => 'USMT0208', 'name' => 'Lodge Grass');
$city_data[] = array('accid' => 'USMT0209', 'name' => 'Lolo');
$city_data[] = array('accid' => 'USMT0210', 'name' => 'Loma');
$city_data[] = array('accid' => 'USMT0211', 'name' => 'Lonepine');
$city_data[] = array('accid' => 'USMT0212', 'name' => 'Loring');
$city_data[] = array('accid' => 'USMT0213', 'name' => 'Lothair');
$city_data[] = array('accid' => 'USMT0214', 'name' => 'Malmstrom AFB');
$city_data[] = array('accid' => 'USMT0215', 'name' => 'Malta');
$city_data[] = array('accid' => 'USMT0216', 'name' => 'Manhattan');
$city_data[] = array('accid' => 'USMT0217', 'name' => 'Marion');
$city_data[] = array('accid' => 'USMT0218', 'name' => 'Martin City');
$city_data[] = array('accid' => 'USMT0219', 'name' => 'Martinsdale');
$city_data[] = array('accid' => 'USMT0220', 'name' => 'Marysville');
$city_data[] = array('accid' => 'USMT0221', 'name' => 'McAllister');
$city_data[] = array('accid' => 'USMT0222', 'name' => 'McCabe');
$city_data[] = array('accid' => 'USMT0223', 'name' => 'McLeod');
$city_data[] = array('accid' => 'USMT0224', 'name' => 'Medicine Lake');
$city_data[] = array('accid' => 'USMT0225', 'name' => 'Melrose');
$city_data[] = array('accid' => 'USMT0226', 'name' => 'Melstone');
$city_data[] = array('accid' => 'USMT0227', 'name' => 'Melville');
$city_data[] = array('accid' => 'USMT0228', 'name' => 'Mildred');
$city_data[] = array('accid' => 'USMT0229', 'name' => 'Miles City');
$city_data[] = array('accid' => 'USMT0230', 'name' => 'Milltown');
$city_data[] = array('accid' => 'USMT0231', 'name' => 'Missoula');
$city_data[] = array('accid' => 'USMT0232', 'name' => 'Moccasin');
$city_data[] = array('accid' => 'USMT0233', 'name' => 'Molt');
$city_data[] = array('accid' => 'USMT0234', 'name' => 'Monarch');
$city_data[] = array('accid' => 'USMT0235', 'name' => 'Moore');
$city_data[] = array('accid' => 'USMT0236', 'name' => 'Mosby');
$city_data[] = array('accid' => 'USMT0237', 'name' => 'Musselshell');
$city_data[] = array('accid' => 'USMT0238', 'name' => 'Nashua');
$city_data[] = array('accid' => 'USMT0239', 'name' => 'Neihart');
$city_data[] = array('accid' => 'USMT0240', 'name' => 'Norris');
$city_data[] = array('accid' => 'USMT0242', 'name' => 'Noxon');
$city_data[] = array('accid' => 'USMT0243', 'name' => 'Nye');
$city_data[] = array('accid' => 'USMT0244', 'name' => 'Oilmont');
$city_data[] = array('accid' => 'USMT0245', 'name' => 'Olive');
$city_data[] = array('accid' => 'USMT0246', 'name' => 'Olney');
$city_data[] = array('accid' => 'USMT0247', 'name' => 'Opheim');
$city_data[] = array('accid' => 'USMT0248', 'name' => 'Otter');
$city_data[] = array('accid' => 'USMT0249', 'name' => 'Outlook');
$city_data[] = array('accid' => 'USMT0250', 'name' => 'Ovando');
$city_data[] = array('accid' => 'USMT0251', 'name' => 'Pablo');
$city_data[] = array('accid' => 'USMT0252', 'name' => 'Paradise');
$city_data[] = array('accid' => 'USMT0253', 'name' => 'Park City');
$city_data[] = array('accid' => 'USMT0254', 'name' => 'Peerless');
$city_data[] = array('accid' => 'USMT0255', 'name' => 'Pendroy');
$city_data[] = array('accid' => 'USMT0256', 'name' => 'Philipsburg');
$city_data[] = array('accid' => 'USMT0257', 'name' => 'Pinesdale');
$city_data[] = array('accid' => 'USMT0258', 'name' => 'Plains');
$city_data[] = array('accid' => 'USMT0259', 'name' => 'Plentywood');
$city_data[] = array('accid' => 'USMT0260', 'name' => 'Plevna');
$city_data[] = array('accid' => 'USMT0261', 'name' => 'Polaris');
$city_data[] = array('accid' => 'USMT0262', 'name' => 'Polebridge');
$city_data[] = array('accid' => 'USMT0263', 'name' => 'Polson');
$city_data[] = array('accid' => 'USMT0264', 'name' => 'Pompeys Pillar');
$city_data[] = array('accid' => 'USMT0265', 'name' => 'Pony');
$city_data[] = array('accid' => 'USMT0266', 'name' => 'Poplar');
$city_data[] = array('accid' => 'USMT0267', 'name' => 'Powderville');
$city_data[] = array('accid' => 'USMT0268', 'name' => 'Power');
$city_data[] = array('accid' => 'USMT0269', 'name' => 'Pray');
$city_data[] = array('accid' => 'USMT0270', 'name' => 'Proctor');
$city_data[] = array('accid' => 'USMT0271', 'name' => 'Pryor');
$city_data[] = array('accid' => 'USMT0272', 'name' => 'Radersburg');
$city_data[] = array('accid' => 'USMT0273', 'name' => 'Ramsay');
$city_data[] = array('accid' => 'USMT0274', 'name' => 'Rapelje');
$city_data[] = array('accid' => 'USMT0275', 'name' => 'Ravalli');
$city_data[] = array('accid' => 'USMT0276', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USMT0277', 'name' => 'Raynesford');
$city_data[] = array('accid' => 'USMT0278', 'name' => 'Red Lodge');
$city_data[] = array('accid' => 'USMT0279', 'name' => 'Redstone');
$city_data[] = array('accid' => 'USMT0280', 'name' => 'Reedpoint');
$city_data[] = array('accid' => 'USMT0281', 'name' => 'Reserve');
$city_data[] = array('accid' => 'USMT0282', 'name' => 'Rexford');
$city_data[] = array('accid' => 'USMT0283', 'name' => 'Richey');
$city_data[] = array('accid' => 'USMT0284', 'name' => 'Richland');
$city_data[] = array('accid' => 'USMT0285', 'name' => 'Ringling');
$city_data[] = array('accid' => 'USMT0286', 'name' => 'Roberts');
$city_data[] = array('accid' => 'USMT0287', 'name' => 'Rollins');
$city_data[] = array('accid' => 'USMT0288', 'name' => 'Ronan');
$city_data[] = array('accid' => 'USMT0289', 'name' => 'Roscoe');
$city_data[] = array('accid' => 'USMT0290', 'name' => 'Rosebud');
$city_data[] = array('accid' => 'USMT0292', 'name' => 'Roundup');
$city_data[] = array('accid' => 'USMT0293', 'name' => 'Roy');
$city_data[] = array('accid' => 'USMT0294', 'name' => 'Rudyard');
$city_data[] = array('accid' => 'USMT0295', 'name' => 'Ryegate');
$city_data[] = array('accid' => 'USMT0296', 'name' => 'Saco');
$city_data[] = array('accid' => 'USMT0297', 'name' => 'Saint Ignatius');
$city_data[] = array('accid' => 'USMT0298', 'name' => 'Saint Marie');
$city_data[] = array('accid' => 'USMT0299', 'name' => 'Saint Regis');
$city_data[] = array('accid' => 'USMT0300', 'name' => 'Saint Xavier');
$city_data[] = array('accid' => 'USMT0301', 'name' => 'Saltese');
$city_data[] = array('accid' => 'USMT0302', 'name' => 'Sand Coulee');
$city_data[] = array('accid' => 'USMT0303', 'name' => 'Sand Springs');
$city_data[] = array('accid' => 'USMT0304', 'name' => 'Sanders');
$city_data[] = array('accid' => 'USMT0305', 'name' => 'Santa Rita');
$city_data[] = array('accid' => 'USMT0306', 'name' => 'Savage');
$city_data[] = array('accid' => 'USMT0307', 'name' => 'Scobey');
$city_data[] = array('accid' => 'USMT0308', 'name' => 'Seeley Lake');
$city_data[] = array('accid' => 'USMT0309', 'name' => 'Shawmut');
$city_data[] = array('accid' => 'USMT0310', 'name' => 'Shelby');
$city_data[] = array('accid' => 'USMT0311', 'name' => 'Shepherd');
$city_data[] = array('accid' => 'USMT0312', 'name' => 'Sheridan');
$city_data[] = array('accid' => 'USMT0313', 'name' => 'Sidney');
$city_data[] = array('accid' => 'USMT0314', 'name' => 'Silver Gate');
$city_data[] = array('accid' => 'USMT0315', 'name' => 'Silver Star');
$city_data[] = array('accid' => 'USMT0316', 'name' => 'Simms');
$city_data[] = array('accid' => 'USMT0317', 'name' => 'Somers');
$city_data[] = array('accid' => 'USMT0318', 'name' => 'Sonnette');
$city_data[] = array('accid' => 'USMT0319', 'name' => 'Springdale');
$city_data[] = array('accid' => 'USMT0320', 'name' => 'Stanford');
$city_data[] = array('accid' => 'USMT0321', 'name' => 'Stevensville');
$city_data[] = array('accid' => 'USMT0322', 'name' => 'Stockett');
$city_data[] = array('accid' => 'USMT0323', 'name' => 'Stryker');
$city_data[] = array('accid' => 'USMT0324', 'name' => 'Sula');
$city_data[] = array('accid' => 'USMT0325', 'name' => 'Sumatra');
$city_data[] = array('accid' => 'USMT0326', 'name' => 'Sun River');
$city_data[] = array('accid' => 'USMT0327', 'name' => 'Sunburst');
$city_data[] = array('accid' => 'USMT0328', 'name' => 'Superior');
$city_data[] = array('accid' => 'USMT0330', 'name' => 'Teigen');
$city_data[] = array('accid' => 'USMT0331', 'name' => 'Terry');
$city_data[] = array('accid' => 'USMT0333', 'name' => 'Thompson Falls');
$city_data[] = array('accid' => 'USMT0334', 'name' => 'Three Forks');
$city_data[] = array('accid' => 'USMT0335', 'name' => 'Toston');
$city_data[] = array('accid' => 'USMT0336', 'name' => 'Townsend');
$city_data[] = array('accid' => 'USMT0337', 'name' => 'Trego');
$city_data[] = array('accid' => 'USMT0338', 'name' => 'Trout Creek');
$city_data[] = array('accid' => 'USMT0339', 'name' => 'Troy');
$city_data[] = array('accid' => 'USMT0340', 'name' => 'Turner');
$city_data[] = array('accid' => 'USMT0341', 'name' => 'Twin Bridges');
$city_data[] = array('accid' => 'USMT0342', 'name' => 'Twodot');
$city_data[] = array('accid' => 'USMT0343', 'name' => 'Ulm');
$city_data[] = array('accid' => 'USMT0344', 'name' => 'Valier');
$city_data[] = array('accid' => 'USMT0345', 'name' => 'Vandalia');
$city_data[] = array('accid' => 'USMT0346', 'name' => 'Vaughn');
$city_data[] = array('accid' => 'USMT0347', 'name' => 'Victor');
$city_data[] = array('accid' => 'USMT0348', 'name' => 'Vida');
$city_data[] = array('accid' => 'USMT0349', 'name' => 'Virginia City');
$city_data[] = array('accid' => 'USMT0350', 'name' => 'Volborg');
$city_data[] = array('accid' => 'USMT0351', 'name' => 'Warm Springs');
$city_data[] = array('accid' => 'USMT0352', 'name' => 'West Glacier');
$city_data[] = array('accid' => 'USMT0353', 'name' => 'West Yellowstone');
$city_data[] = array('accid' => 'USMT0354', 'name' => 'Westby');
$city_data[] = array('accid' => 'USMT0355', 'name' => 'White Sulphur Springs');
$city_data[] = array('accid' => 'USMT0356', 'name' => 'Whitefish');
$city_data[] = array('accid' => 'USMT0357', 'name' => 'Whitehall');
$city_data[] = array('accid' => 'USMT0358', 'name' => 'Whitetail');
$city_data[] = array('accid' => 'USMT0359', 'name' => 'Whitewater');
$city_data[] = array('accid' => 'USMT0360', 'name' => 'Whitlash');
$city_data[] = array('accid' => 'USMT0361', 'name' => 'Wibaux');
$city_data[] = array('accid' => 'USMT0362', 'name' => 'Willard');
$city_data[] = array('accid' => 'USMT0363', 'name' => 'Willow Creek');
$city_data[] = array('accid' => 'USMT0364', 'name' => 'Wilsall');
$city_data[] = array('accid' => 'USMT0365', 'name' => 'Winifred');
$city_data[] = array('accid' => 'USMT0366', 'name' => 'Winnett');
$city_data[] = array('accid' => 'USMT0367', 'name' => 'Winston');
$city_data[] = array('accid' => 'USMT0368', 'name' => 'Wisdom');
$city_data[] = array('accid' => 'USMT0369', 'name' => 'Wise River');
$city_data[] = array('accid' => 'USMT0370', 'name' => 'Wolf Creek');
$city_data[] = array('accid' => 'USMT0371', 'name' => 'Wolf Point');
$city_data[] = array('accid' => 'USMT0372', 'name' => 'Worden');
$city_data[] = array('accid' => 'USMT0373', 'name' => 'Wyola');
$city_data[] = array('accid' => 'USMT0374', 'name' => 'Yellowtail');
$city_data[] = array('accid' => 'USMT0375', 'name' => 'Zortman');
$city_data[] = array('accid' => 'USMT0376', 'name' => 'Zurich');

?>
