<?php

// City package for USA: North Carolina 

$city_name = 'USA: North Carolina';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USNC0001', 'name' => 'Aberdeen');
$city_data[] = array('accid' => 'USNC0002', 'name' => 'Advance');
$city_data[] = array('accid' => 'USNC0003', 'name' => 'Ahoskie');
$city_data[] = array('accid' => 'USNC0004', 'name' => 'Alamance');
$city_data[] = array('accid' => 'USNC0005', 'name' => 'Albemarle');
$city_data[] = array('accid' => 'USNC0006', 'name' => 'Albertson');
$city_data[] = array('accid' => 'USNC0007', 'name' => 'Alexander');
$city_data[] = array('accid' => 'USNC0008', 'name' => 'Alexis');
$city_data[] = array('accid' => 'USNC0009', 'name' => 'Alliance');
$city_data[] = array('accid' => 'USNC0010', 'name' => 'Almond');
$city_data[] = array('accid' => 'USNC0011', 'name' => 'Altamahaw');
$city_data[] = array('accid' => 'USNC0012', 'name' => 'Andrews');
$city_data[] = array('accid' => 'USNC0013', 'name' => 'Angier');
$city_data[] = array('accid' => 'USNC0014', 'name' => 'Ansonville');
$city_data[] = array('accid' => 'USNC0015', 'name' => 'Apex');
$city_data[] = array('accid' => 'USNC0017', 'name' => 'Arapahoe');
$city_data[] = array('accid' => 'USNC0018', 'name' => 'Ararat');
$city_data[] = array('accid' => 'USNC0019', 'name' => 'Arden');
$city_data[] = array('accid' => 'USNC0020', 'name' => 'Ash');
$city_data[] = array('accid' => 'USNC0021', 'name' => 'Asheboro');
$city_data[] = array('accid' => 'USNC0022', 'name' => 'Asheville');
$city_data[] = array('accid' => 'USNC0023', 'name' => 'Atkinson');
$city_data[] = array('accid' => 'USNC0024', 'name' => 'Atlantic');
$city_data[] = array('accid' => 'USNC0025', 'name' => 'Atlantic Beach');
$city_data[] = array('accid' => 'USNC0026', 'name' => 'Aulander');
$city_data[] = array('accid' => 'USNC0027', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USNC0028', 'name' => 'Autryville');
$city_data[] = array('accid' => 'USNC0029', 'name' => 'Avon');
$city_data[] = array('accid' => 'USNC0030', 'name' => 'Ayden');
$city_data[] = array('accid' => 'USNC0031', 'name' => 'Aydlett');
$city_data[] = array('accid' => 'USNC0032', 'name' => 'Badin');
$city_data[] = array('accid' => 'USNC0033', 'name' => 'Bahama');
$city_data[] = array('accid' => 'USNC0034', 'name' => 'Bailey');
$city_data[] = array('accid' => 'USNC0035', 'name' => 'Bakersville');
$city_data[] = array('accid' => 'USNC0036', 'name' => 'Balsam');
$city_data[] = array('accid' => 'USNC0037', 'name' => 'Balsam Grove');
$city_data[] = array('accid' => 'USNC0038', 'name' => 'Banner Elk');
$city_data[] = array('accid' => 'USNC0039', 'name' => 'Barco');
$city_data[] = array('accid' => 'USNC0040', 'name' => 'Barium Springs');
$city_data[] = array('accid' => 'USNC0041', 'name' => 'Barnardsville');
$city_data[] = array('accid' => 'USNC0042', 'name' => 'Barnesville');
$city_data[] = array('accid' => 'USNC0043', 'name' => 'Bat Cave');
$city_data[] = array('accid' => 'USNC0044', 'name' => 'Bath');
$city_data[] = array('accid' => 'USNC0045', 'name' => 'Battleboro');
$city_data[] = array('accid' => 'USNC0046', 'name' => 'Bayboro');
$city_data[] = array('accid' => 'USNC0047', 'name' => 'Bear Creek');
$city_data[] = array('accid' => 'USNC0048', 'name' => 'Beaufort');
$city_data[] = array('accid' => 'USNC0049', 'name' => 'Belews Creek');
$city_data[] = array('accid' => 'USNC0050', 'name' => 'Belhaven');
$city_data[] = array('accid' => 'USNC0051', 'name' => 'Bellarthur');
$city_data[] = array('accid' => 'USNC0052', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USNC0053', 'name' => 'Belvidere');
$city_data[] = array('accid' => 'USNC0054', 'name' => 'Bennett');
$city_data[] = array('accid' => 'USNC0055', 'name' => 'Benson');
$city_data[] = array('accid' => 'USNC0056', 'name' => 'Bessemer City');
$city_data[] = array('accid' => 'USNC0057', 'name' => 'Bethania');
$city_data[] = array('accid' => 'USNC0058', 'name' => 'Bethel');
$city_data[] = array('accid' => 'USNC0059', 'name' => 'Beulaville');
$city_data[] = array('accid' => 'USNC0060', 'name' => 'Biscoe');
$city_data[] = array('accid' => 'USNC0061', 'name' => 'Black Creek');
$city_data[] = array('accid' => 'USNC0062', 'name' => 'Black Mountain');
$city_data[] = array('accid' => 'USNC0063', 'name' => 'Bladenboro');
$city_data[] = array('accid' => 'USNC0064', 'name' => 'Blanch');
$city_data[] = array('accid' => 'USNC0065', 'name' => 'Blounts Creek');
$city_data[] = array('accid' => 'USNC0066', 'name' => 'Blowing Rock');
$city_data[] = array('accid' => 'USNC0067', 'name' => 'Boiling Springs');
$city_data[] = array('accid' => 'USNC0068', 'name' => 'Bolivia');
$city_data[] = array('accid' => 'USNC0069', 'name' => 'Bolton');
$city_data[] = array('accid' => 'USNC0070', 'name' => 'Bonlee');
$city_data[] = array('accid' => 'USNC0071', 'name' => 'Boomer');
$city_data[] = array('accid' => 'USNC0072', 'name' => 'Boone');
$city_data[] = array('accid' => 'USNC0073', 'name' => 'Boonville');
$city_data[] = array('accid' => 'USNC0074', 'name' => 'Bostic');
$city_data[] = array('accid' => 'USNC0075', 'name' => 'Brasstown');
$city_data[] = array('accid' => 'USNC0076', 'name' => 'Brevard');
$city_data[] = array('accid' => 'USNC0077', 'name' => 'Bridgeton');
$city_data[] = array('accid' => 'USNC0078', 'name' => 'Broadway');
$city_data[] = array('accid' => 'USNC0079', 'name' => 'Browns Summit');
$city_data[] = array('accid' => 'USNC0080', 'name' => 'Brunswick');
$city_data[] = array('accid' => 'USNC0081', 'name' => 'Bryson City');
$city_data[] = array('accid' => 'USNC0082', 'name' => 'Buies Creek');
$city_data[] = array('accid' => 'USNC0083', 'name' => 'Bullock');
$city_data[] = array('accid' => 'USNC0084', 'name' => 'Bunn');
$city_data[] = array('accid' => 'USNC0085', 'name' => 'Bunnlevel');
$city_data[] = array('accid' => 'USNC0086', 'name' => 'Burgaw');
$city_data[] = array('accid' => 'USNC0087', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USNC0088', 'name' => 'Burnsville');
$city_data[] = array('accid' => 'USNC0089', 'name' => 'Butner');
$city_data[] = array('accid' => 'USNC0090', 'name' => 'Buxton');
$city_data[] = array('accid' => 'USNC0091', 'name' => 'Bynum');
$city_data[] = array('accid' => 'USNC0092', 'name' => 'Calabash');
$city_data[] = array('accid' => 'USNC0093', 'name' => 'Calypso');
$city_data[] = array('accid' => 'USNC0094', 'name' => 'Camden');
$city_data[] = array('accid' => 'USNC0095', 'name' => 'Cameron');
$city_data[] = array('accid' => 'USNC0096', 'name' => 'Camp Lejeune');
$city_data[] = array('accid' => 'USNC0097', 'name' => 'Candler');
$city_data[] = array('accid' => 'USNC0098', 'name' => 'Candor');
$city_data[] = array('accid' => 'USNC0099', 'name' => 'Canton');
$city_data[] = array('accid' => 'USNC0103', 'name' => 'Caroleen');
$city_data[] = array('accid' => 'USNC0104', 'name' => 'Carolina Beach');
$city_data[] = array('accid' => 'USNC0105', 'name' => 'Carrboro');
$city_data[] = array('accid' => 'USNC0106', 'name' => 'Carthage');
$city_data[] = array('accid' => 'USNC0107', 'name' => 'Cary');
$city_data[] = array('accid' => 'USNC0108', 'name' => 'Casar');
$city_data[] = array('accid' => 'USNC0109', 'name' => 'Cashiers');
$city_data[] = array('accid' => 'USNC0110', 'name' => 'Castalia');
$city_data[] = array('accid' => 'USNC0111', 'name' => 'Castle Hayne');
$city_data[] = array('accid' => 'USNC0112', 'name' => 'Cataloochee Ski Area');
$city_data[] = array('accid' => 'USNC0113', 'name' => 'Catawba');
$city_data[] = array('accid' => 'USNC0114', 'name' => 'Cedar Falls');
$city_data[] = array('accid' => 'USNC0115', 'name' => 'Cedar Grove');
$city_data[] = array('accid' => 'USNC0116', 'name' => 'Cedar Island');
$city_data[] = array('accid' => 'USNC0117', 'name' => 'Cedar Mountain');
$city_data[] = array('accid' => 'USNC0118', 'name' => 'Cerro Gordo');
$city_data[] = array('accid' => 'USNC0119', 'name' => 'Chadbourn');
$city_data[] = array('accid' => 'USNC0120', 'name' => 'Chapel Hill');
$city_data[] = array('accid' => 'USNC0121', 'name' => 'Charlotte');
$city_data[] = array('accid' => 'USNC0122', 'name' => 'Cherokee');
$city_data[] = array('accid' => 'USNC0123', 'name' => 'Cherry Point');
$city_data[] = array('accid' => 'USNC0124', 'name' => 'Cherryville');
$city_data[] = array('accid' => 'USNC0125', 'name' => 'Chimney Rock');
$city_data[] = array('accid' => 'USNC0126', 'name' => 'China Grove');
$city_data[] = array('accid' => 'USNC0127', 'name' => 'Chinquapin');
$city_data[] = array('accid' => 'USNC0128', 'name' => 'Chocowinity');
$city_data[] = array('accid' => 'USNC0129', 'name' => 'Claremont');
$city_data[] = array('accid' => 'USNC0130', 'name' => 'Clarendon');
$city_data[] = array('accid' => 'USNC0131', 'name' => 'Clarkton');
$city_data[] = array('accid' => 'USNC0132', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USNC0133', 'name' => 'Clemmons');
$city_data[] = array('accid' => 'USNC0134', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USNC0135', 'name' => 'Cliffside');
$city_data[] = array('accid' => 'USNC0136', 'name' => 'Climax');
$city_data[] = array('accid' => 'USNC0137', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USNC0138', 'name' => 'Clyde');
$city_data[] = array('accid' => 'USNC0139', 'name' => 'Coats');
$city_data[] = array('accid' => 'USNC0140', 'name' => 'Cofield');
$city_data[] = array('accid' => 'USNC0141', 'name' => 'Coinjock');
$city_data[] = array('accid' => 'USNC0142', 'name' => 'Colerain');
$city_data[] = array('accid' => 'USNC0143', 'name' => 'Colfax');
$city_data[] = array('accid' => 'USNC0144', 'name' => 'Collettsville');
$city_data[] = array('accid' => 'USNC0145', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USNC0146', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USNC0147', 'name' => 'Comfort');
$city_data[] = array('accid' => 'USNC0148', 'name' => 'Como');
$city_data[] = array('accid' => 'USNC0149', 'name' => 'Concord');
$city_data[] = array('accid' => 'USNC0150', 'name' => 'Conetoe');
$city_data[] = array('accid' => 'USNC0151', 'name' => 'Connellys Springs');
$city_data[] = array('accid' => 'USNC0152', 'name' => 'Conover');
$city_data[] = array('accid' => 'USNC0153', 'name' => 'Conway');
$city_data[] = array('accid' => 'USNC0154', 'name' => 'Cooleemee');
$city_data[] = array('accid' => 'USNC0155', 'name' => 'Corapeake');
$city_data[] = array('accid' => 'USNC0156', 'name' => 'Cordova');
$city_data[] = array('accid' => 'USNC0157', 'name' => 'Cornelius');
$city_data[] = array('accid' => 'USNC0158', 'name' => 'Corolla');
$city_data[] = array('accid' => 'USNC0159', 'name' => 'Council');
$city_data[] = array('accid' => 'USNC0160', 'name' => 'Cove City');
$city_data[] = array('accid' => 'USNC0161', 'name' => 'Cramerton');
$city_data[] = array('accid' => 'USNC0162', 'name' => 'Creedmoor');
$city_data[] = array('accid' => 'USNC0163', 'name' => 'Creston');
$city_data[] = array('accid' => 'USNC0164', 'name' => 'Creswell');
$city_data[] = array('accid' => 'USNC0165', 'name' => 'Crossnore');
$city_data[] = array('accid' => 'USNC0166', 'name' => 'Crouse');
$city_data[] = array('accid' => 'USNC0167', 'name' => 'Crumpler');
$city_data[] = array('accid' => 'USNC0168', 'name' => 'Culberson');
$city_data[] = array('accid' => 'USNC0169', 'name' => 'Cullowhee');
$city_data[] = array('accid' => 'USNC0170', 'name' => 'Cumberland');
$city_data[] = array('accid' => 'USNC0171', 'name' => 'Cumnock');
$city_data[] = array('accid' => 'USNC0172', 'name' => 'Currie');
$city_data[] = array('accid' => 'USNC0173', 'name' => 'Currituck');
$city_data[] = array('accid' => 'USNC0174', 'name' => 'Dallas');
$city_data[] = array('accid' => 'USNC0175', 'name' => 'Dana');
$city_data[] = array('accid' => 'USNC0176', 'name' => 'Danbury');
$city_data[] = array('accid' => 'USNC0177', 'name' => 'Davidson');
$city_data[] = array('accid' => 'USNC0178', 'name' => 'Davis');
$city_data[] = array('accid' => 'USNC0179', 'name' => 'Deep Gap');
$city_data[] = array('accid' => 'USNC0180', 'name' => 'Deep Run');
$city_data[] = array('accid' => 'USNC0181', 'name' => 'Delco');
$city_data[] = array('accid' => 'USNC0182', 'name' => 'Denton');
$city_data[] = array('accid' => 'USNC0183', 'name' => 'Denver');
$city_data[] = array('accid' => 'USNC0184', 'name' => 'Dillsboro');
$city_data[] = array('accid' => 'USNC0185', 'name' => 'Dobson');
$city_data[] = array('accid' => 'USNC0186', 'name' => 'Dover');
$city_data[] = array('accid' => 'USNC0187', 'name' => 'Drexel');
$city_data[] = array('accid' => 'USNC0188', 'name' => 'Dublin');
$city_data[] = array('accid' => 'USNC0189', 'name' => 'Dudley');
$city_data[] = array('accid' => 'USNC0190', 'name' => 'Dunn');
$city_data[] = array('accid' => 'USNC0191', 'name' => 'Durants Neck');
$city_data[] = array('accid' => 'USNC0192', 'name' => 'Durham');
$city_data[] = array('accid' => 'USNC0193', 'name' => 'Eagle Rock');
$city_data[] = array('accid' => 'USNC0194', 'name' => 'Eagle Springs');
$city_data[] = array('accid' => 'USNC0195', 'name' => 'Earl');
$city_data[] = array('accid' => 'USNC0196', 'name' => 'East Bend');
$city_data[] = array('accid' => 'USNC0197', 'name' => 'East Flat Rock');
$city_data[] = array('accid' => 'USNC0198', 'name' => 'East Spencer');
$city_data[] = array('accid' => 'USNC0199', 'name' => 'Eden');
$city_data[] = array('accid' => 'USNC0200', 'name' => 'Edenton');
$city_data[] = array('accid' => 'USNC0201', 'name' => 'Edneyville');
$city_data[] = array('accid' => 'USNC0202', 'name' => 'Edward');
$city_data[] = array('accid' => 'USNC0203', 'name' => 'Efland');
$city_data[] = array('accid' => 'USNC0204', 'name' => 'Elizabeth City');
$city_data[] = array('accid' => 'USNC0205', 'name' => 'Elizabethtown');
$city_data[] = array('accid' => 'USNC0206', 'name' => 'Elk Park');
$city_data[] = array('accid' => 'USNC0207', 'name' => 'Elkin');
$city_data[] = array('accid' => 'USNC0208', 'name' => 'Ellenboro');
$city_data[] = array('accid' => 'USNC0209', 'name' => 'Ellerbe');
$city_data[] = array('accid' => 'USNC0210', 'name' => 'Elm City');
$city_data[] = array('accid' => 'USNC0211', 'name' => 'Elon');
$city_data[] = array('accid' => 'USNC0212', 'name' => 'Emerald Isle');
$city_data[] = array('accid' => 'USNC0213', 'name' => 'Enfield');
$city_data[] = array('accid' => 'USNC0214', 'name' => 'Engelhard');
$city_data[] = array('accid' => 'USNC0215', 'name' => 'Enka');
$city_data[] = array('accid' => 'USNC0216', 'name' => 'Ennice');
$city_data[] = array('accid' => 'USNC0217', 'name' => 'Ernul');
$city_data[] = array('accid' => 'USNC0218', 'name' => 'Erwin');
$city_data[] = array('accid' => 'USNC0219', 'name' => 'Ether');
$city_data[] = array('accid' => 'USNC0220', 'name' => 'Etowah');
$city_data[] = array('accid' => 'USNC0221', 'name' => 'Eure');
$city_data[] = array('accid' => 'USNC0222', 'name' => 'Everetts');
$city_data[] = array('accid' => 'USNC0223', 'name' => 'Evergreen');
$city_data[] = array('accid' => 'USNC0224', 'name' => 'Fair Bluff');
$city_data[] = array('accid' => 'USNC0225', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USNC0226', 'name' => 'Fairmont');
$city_data[] = array('accid' => 'USNC0227', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USNC0228', 'name' => 'Faison');
$city_data[] = array('accid' => 'USNC0229', 'name' => 'Faith');
$city_data[] = array('accid' => 'USNC0230', 'name' => 'Falcon');
$city_data[] = array('accid' => 'USNC0231', 'name' => 'Falkland');
$city_data[] = array('accid' => 'USNC0232', 'name' => 'Fallston');
$city_data[] = array('accid' => 'USNC0233', 'name' => 'Farmville');
$city_data[] = array('accid' => 'USNC0234', 'name' => 'Fayetteville');
$city_data[] = array('accid' => 'USNC0236', 'name' => 'Ferguson');
$city_data[] = array('accid' => 'USNC0237', 'name' => 'Flat Rock');
$city_data[] = array('accid' => 'USNC0238', 'name' => 'Fleetwood');
$city_data[] = array('accid' => 'USNC0239', 'name' => 'Fletcher');
$city_data[] = array('accid' => 'USNC0240', 'name' => 'Fontana Dam');
$city_data[] = array('accid' => 'USNC0241', 'name' => 'Forest City');
$city_data[] = array('accid' => 'USNC0242', 'name' => 'Fort Bragg');
$city_data[] = array('accid' => 'USNC0244', 'name' => 'Fountain');
$city_data[] = array('accid' => 'USNC0245', 'name' => 'Four Oaks');
$city_data[] = array('accid' => 'USNC0246', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USNC0247', 'name' => 'Franklinton');
$city_data[] = array('accid' => 'USNC0248', 'name' => 'Franklinville');
$city_data[] = array('accid' => 'USNC0249', 'name' => 'Fremont');
$city_data[] = array('accid' => 'USNC0250', 'name' => 'Frisco');
$city_data[] = array('accid' => 'USNC0251', 'name' => 'Fuquay Varina');
$city_data[] = array('accid' => 'USNC0252', 'name' => 'Garland');
$city_data[] = array('accid' => 'USNC0253', 'name' => 'Garner');
$city_data[] = array('accid' => 'USNC0254', 'name' => 'Garysburg');
$city_data[] = array('accid' => 'USNC0255', 'name' => 'Gaston');
$city_data[] = array('accid' => 'USNC0256', 'name' => 'Gastonia');
$city_data[] = array('accid' => 'USNC0257', 'name' => 'Gates');
$city_data[] = array('accid' => 'USNC0258', 'name' => 'Gatesville');
$city_data[] = array('accid' => 'USNC0259', 'name' => 'Germanton');
$city_data[] = array('accid' => 'USNC0260', 'name' => 'Gerton');
$city_data[] = array('accid' => 'USNC0261', 'name' => 'Gibson');
$city_data[] = array('accid' => 'USNC0262', 'name' => 'Gibsonville');
$city_data[] = array('accid' => 'USNC0263', 'name' => 'Glade Valley');
$city_data[] = array('accid' => 'USNC0264', 'name' => 'Glen Alpine');
$city_data[] = array('accid' => 'USNC0265', 'name' => 'Glendale Springs');
$city_data[] = array('accid' => 'USNC0266', 'name' => 'Glenville');
$city_data[] = array('accid' => 'USNC0267', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USNC0268', 'name' => 'Gloucester');
$city_data[] = array('accid' => 'USNC0269', 'name' => 'Godwin');
$city_data[] = array('accid' => 'USNC0270', 'name' => 'Gold Hill');
$city_data[] = array('accid' => 'USNC0271', 'name' => 'Goldsboro');
$city_data[] = array('accid' => 'USNC0272', 'name' => 'Goldston');
$city_data[] = array('accid' => 'USNC0273', 'name' => 'Graham');
$city_data[] = array('accid' => 'USNC0274', 'name' => 'Grandy');
$city_data[] = array('accid' => 'USNC0275', 'name' => 'Granite Falls');
$city_data[] = array('accid' => 'USNC0276', 'name' => 'Granite Quarry');
$city_data[] = array('accid' => 'USNC0277', 'name' => 'Grantsboro');
$city_data[] = array('accid' => 'USNC0278', 'name' => 'Grassy Creek');
$city_data[] = array('accid' => 'USNC0279', 'name' => 'Greenmountain');
$city_data[] = array('accid' => 'USNC0280', 'name' => 'Greensboro');
$city_data[] = array('accid' => 'USNC0281', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USNC0282', 'name' => 'Grifton');
$city_data[] = array('accid' => 'USNC0283', 'name' => 'Grimesland');
$city_data[] = array('accid' => 'USNC0284', 'name' => 'Grover');
$city_data[] = array('accid' => 'USNC0285', 'name' => 'Gulf');
$city_data[] = array('accid' => 'USNC0286', 'name' => 'Gumberry');
$city_data[] = array('accid' => 'USNC0287', 'name' => 'Halifax');
$city_data[] = array('accid' => 'USNC0288', 'name' => 'Hallsboro');
$city_data[] = array('accid' => 'USNC0289', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USNC0290', 'name' => 'Hamlet');
$city_data[] = array('accid' => 'USNC0291', 'name' => 'Hampstead');
$city_data[] = array('accid' => 'USNC0292', 'name' => 'Hamptonville');
$city_data[] = array('accid' => 'USNC0293', 'name' => 'Harbinger');
$city_data[] = array('accid' => 'USNC0294', 'name' => 'Harkers Island');
$city_data[] = array('accid' => 'USNC0295', 'name' => 'Harmony');
$city_data[] = array('accid' => 'USNC0296', 'name' => 'Harrells');
$city_data[] = array('accid' => 'USNC0297', 'name' => 'Harrellsville');
$city_data[] = array('accid' => 'USNC0298', 'name' => 'Harris');
$city_data[] = array('accid' => 'USNC0299', 'name' => 'Harrisburg');
$city_data[] = array('accid' => 'USNC0300', 'name' => 'Hassell');
$city_data[] = array('accid' => 'USNC0301', 'name' => 'Hatteras');
$city_data[] = array('accid' => 'USNC0302', 'name' => 'Havelock');
$city_data[] = array('accid' => 'USNC0303', 'name' => 'Haw River');
$city_data[] = array('accid' => 'USNC0304', 'name' => 'Hayesville');
$city_data[] = array('accid' => 'USNC0305', 'name' => 'Hays');
$city_data[] = array('accid' => 'USNC0306', 'name' => 'Hazelwood');
$city_data[] = array('accid' => 'USNC0307', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USNC0308', 'name' => 'Hendersonville');
$city_data[] = array('accid' => 'USNC0309', 'name' => 'Henrico');
$city_data[] = array('accid' => 'USNC0310', 'name' => 'Henrietta');
$city_data[] = array('accid' => 'USNC0311', 'name' => 'Hertford');
$city_data[] = array('accid' => 'USNC0312', 'name' => 'Hickory');
$city_data[] = array('accid' => 'USNC0313', 'name' => 'Hiddenite');
$city_data[] = array('accid' => 'USNC0314', 'name' => 'High Point');
$city_data[] = array('accid' => 'USNC0315', 'name' => 'High Shoals');
$city_data[] = array('accid' => 'USNC0316', 'name' => 'Highfalls');
$city_data[] = array('accid' => 'USNC0317', 'name' => 'Highlands');
$city_data[] = array('accid' => 'USNC0318', 'name' => 'Hildebran');
$city_data[] = array('accid' => 'USNC0319', 'name' => 'Hillsborough');
$city_data[] = array('accid' => 'USNC0320', 'name' => 'Hobbsville');
$city_data[] = array('accid' => 'USNC0321', 'name' => 'Hobgood');
$city_data[] = array('accid' => 'USNC0322', 'name' => 'Hobucken');
$city_data[] = array('accid' => 'USNC0323', 'name' => 'Hoffman');
$city_data[] = array('accid' => 'USNC0324', 'name' => 'Hollister');
$city_data[] = array('accid' => 'USNC0325', 'name' => 'Holly Ridge');
$city_data[] = array('accid' => 'USNC0326', 'name' => 'Holly Springs');
$city_data[] = array('accid' => 'USNC0327', 'name' => 'Hookerton');
$city_data[] = array('accid' => 'USNC0328', 'name' => 'Hope Mills');
$city_data[] = array('accid' => 'USNC0329', 'name' => 'Horse Shoe');
$city_data[] = array('accid' => 'USNC0330', 'name' => 'Hot Springs');
$city_data[] = array('accid' => 'USNC0331', 'name' => 'Hubert');
$city_data[] = array('accid' => 'USNC0332', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USNC0333', 'name' => 'Huntersville');
$city_data[] = array('accid' => 'USNC0334', 'name' => 'Hurdle Mills');
$city_data[] = array('accid' => 'USNC0335', 'name' => 'Icard');
$city_data[] = array('accid' => 'USNC0336', 'name' => 'Indian Trail');
$city_data[] = array('accid' => 'USNC0337', 'name' => 'Ingold');
$city_data[] = array('accid' => 'USNC0338', 'name' => 'Iron Station');
$city_data[] = array('accid' => 'USNC0339', 'name' => 'Ivanhoe');
$city_data[] = array('accid' => 'USNC0340', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USNC0341', 'name' => 'Jackson Springs');
$city_data[] = array('accid' => 'USNC0342', 'name' => 'Jacksonville');
$city_data[] = array('accid' => 'USNC0343', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USNC0344', 'name' => 'Jamesville');
$city_data[] = array('accid' => 'USNC0345', 'name' => 'Jarvisburg');
$city_data[] = array('accid' => 'USNC0346', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USNC0347', 'name' => 'Jonas Ridge');
$city_data[] = array('accid' => 'USNC0348', 'name' => 'Jonesville');
$city_data[] = array('accid' => 'USNC0349', 'name' => 'Julian');
$city_data[] = array('accid' => 'USNC0350', 'name' => 'Kannapolis');
$city_data[] = array('accid' => 'USNC0351', 'name' => 'Kelford');
$city_data[] = array('accid' => 'USNC0352', 'name' => 'Kelly');
$city_data[] = array('accid' => 'USNC0353', 'name' => 'Kenansville');
$city_data[] = array('accid' => 'USNC0354', 'name' => 'Kenly');
$city_data[] = array('accid' => 'USNC0355', 'name' => 'Kernersville');
$city_data[] = array('accid' => 'USNC0356', 'name' => 'Kill Devil Hills');
$city_data[] = array('accid' => 'USNC0357', 'name' => 'King');
$city_data[] = array('accid' => 'USNC0358', 'name' => 'Kings Mountain');
$city_data[] = array('accid' => 'USNC0359', 'name' => 'Kinston');
$city_data[] = array('accid' => 'USNC0360', 'name' => 'Kipling');
$city_data[] = array('accid' => 'USNC0361', 'name' => 'Kittrell');
$city_data[] = array('accid' => 'USNC0362', 'name' => 'Kitty Hawk');
$city_data[] = array('accid' => 'USNC0363', 'name' => 'Knightdale');
$city_data[] = array('accid' => 'USNC0364', 'name' => 'Knotts Island');
$city_data[] = array('accid' => 'USNC0365', 'name' => 'Kure Beach');
$city_data[] = array('accid' => 'USNC0366', 'name' => 'La Grange');
$city_data[] = array('accid' => 'USNC0367', 'name' => 'Lake Junaluska');
$city_data[] = array('accid' => 'USNC0368', 'name' => 'Lake Lure');
$city_data[] = array('accid' => 'USNC0369', 'name' => 'Lake Toxaway');
$city_data[] = array('accid' => 'USNC0370', 'name' => 'Lake Waccamaw');
$city_data[] = array('accid' => 'USNC0371', 'name' => 'Lakeview');
$city_data[] = array('accid' => 'USNC0372', 'name' => 'Landis');
$city_data[] = array('accid' => 'USNC0373', 'name' => 'Lansing');
$city_data[] = array('accid' => 'USNC0374', 'name' => 'Lattimore');
$city_data[] = array('accid' => 'USNC0375', 'name' => 'Laurel Hill');
$city_data[] = array('accid' => 'USNC0376', 'name' => 'Laurel Springs');
$city_data[] = array('accid' => 'USNC0377', 'name' => 'Laurinburg');
$city_data[] = array('accid' => 'USNC0378', 'name' => 'Lawndale');
$city_data[] = array('accid' => 'USNC0379', 'name' => 'Lawsonville');
$city_data[] = array('accid' => 'USNC0380', 'name' => 'Leasburg');
$city_data[] = array('accid' => 'USNC0381', 'name' => 'Leicester');
$city_data[] = array('accid' => 'USNC0382', 'name' => 'Leland');
$city_data[] = array('accid' => 'USNC0383', 'name' => 'Lemon Springs');
$city_data[] = array('accid' => 'USNC0384', 'name' => 'Lenoir');
$city_data[] = array('accid' => 'USNC0386', 'name' => 'Lewisville');
$city_data[] = array('accid' => 'USNC0387', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USNC0388', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USNC0389', 'name' => 'Lilesville');
$city_data[] = array('accid' => 'USNC0390', 'name' => 'Lillington');
$city_data[] = array('accid' => 'USNC0391', 'name' => 'Lincolnton');
$city_data[] = array('accid' => 'USNC0392', 'name' => 'Linden');
$city_data[] = array('accid' => 'USNC0393', 'name' => 'Linville');
$city_data[] = array('accid' => 'USNC0394', 'name' => 'Linville Falls');
$city_data[] = array('accid' => 'USNC0395', 'name' => 'Linwood');
$city_data[] = array('accid' => 'USNC0396', 'name' => 'Little Switzerland');
$city_data[] = array('accid' => 'USNC0397', 'name' => 'Littleton');
$city_data[] = array('accid' => 'USNC0398', 'name' => 'Locust');
$city_data[] = array('accid' => 'USNC0399', 'name' => 'Longwood');
$city_data[] = array('accid' => 'USNC0400', 'name' => 'Louisburg');
$city_data[] = array('accid' => 'USNC0401', 'name' => 'Lowell');
$city_data[] = array('accid' => 'USNC0402', 'name' => 'Lowgap');
$city_data[] = array('accid' => 'USNC0403', 'name' => 'Lowland');
$city_data[] = array('accid' => 'USNC0404', 'name' => 'Lucama');
$city_data[] = array('accid' => 'USNC0405', 'name' => 'Lumber Bridge');
$city_data[] = array('accid' => 'USNC0406', 'name' => 'Lumberton');
$city_data[] = array('accid' => 'USNC0407', 'name' => 'Lynn');
$city_data[] = array('accid' => 'USNC0408', 'name' => 'MacClesfield');
$city_data[] = array('accid' => 'USNC0409', 'name' => 'Macon');
$city_data[] = array('accid' => 'USNC0410', 'name' => 'Madison');
$city_data[] = array('accid' => 'USNC0411', 'name' => 'Maggie Valley');
$city_data[] = array('accid' => 'USNC0412', 'name' => 'Magnolia');
$city_data[] = array('accid' => 'USNC0413', 'name' => 'Maiden');
$city_data[] = array('accid' => 'USNC0414', 'name' => 'Mamers');
$city_data[] = array('accid' => 'USNC0415', 'name' => 'Manns Harbor');
$city_data[] = array('accid' => 'USNC0416', 'name' => 'Manson');
$city_data[] = array('accid' => 'USNC0417', 'name' => 'Manteo');
$city_data[] = array('accid' => 'USNC0418', 'name' => 'Maple');
$city_data[] = array('accid' => 'USNC0419', 'name' => 'Maple Hill');
$city_data[] = array('accid' => 'USNC0420', 'name' => 'Marble');
$city_data[] = array('accid' => 'USNC0421', 'name' => 'Margarettsville');
$city_data[] = array('accid' => 'USNC0422', 'name' => 'Marietta');
$city_data[] = array('accid' => 'USNC0423', 'name' => 'Marion');
$city_data[] = array('accid' => 'USNC0424', 'name' => 'Mars Hill');
$city_data[] = array('accid' => 'USNC0425', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USNC0426', 'name' => 'Marshallberg');
$city_data[] = array('accid' => 'USNC0427', 'name' => 'Marshville');
$city_data[] = array('accid' => 'USNC0428', 'name' => 'Marston');
$city_data[] = array('accid' => 'USNC0429', 'name' => 'Matthews');
$city_data[] = array('accid' => 'USNC0430', 'name' => 'Maury');
$city_data[] = array('accid' => 'USNC0431', 'name' => 'Maxton');
$city_data[] = array('accid' => 'USNC0432', 'name' => 'Mayodan');
$city_data[] = array('accid' => 'USNC0433', 'name' => 'Maysville');
$city_data[] = array('accid' => 'USNC0434', 'name' => 'McAdenville');
$city_data[] = array('accid' => 'USNC0435', 'name' => 'McCain');
$city_data[] = array('accid' => 'USNC0436', 'name' => 'McCutcheon Field');
$city_data[] = array('accid' => 'USNC0437', 'name' => 'McFarlan');
$city_data[] = array('accid' => 'USNC0438', 'name' => 'McGrady');
$city_data[] = array('accid' => 'USNC0439', 'name' => 'McLeansville');
$city_data[] = array('accid' => 'USNC0440', 'name' => 'Mebane');
$city_data[] = array('accid' => 'USNC0441', 'name' => 'Merritt');
$city_data[] = array('accid' => 'USNC0442', 'name' => 'Merry Hill');
$city_data[] = array('accid' => 'USNC0443', 'name' => 'Micaville');
$city_data[] = array('accid' => 'USNC0444', 'name' => 'Micro');
$city_data[] = array('accid' => 'USNC0445', 'name' => 'Middleburg');
$city_data[] = array('accid' => 'USNC0446', 'name' => 'Middlesex');
$city_data[] = array('accid' => 'USNC0447', 'name' => 'Midland');
$city_data[] = array('accid' => 'USNC0448', 'name' => 'Midway Park');
$city_data[] = array('accid' => 'USNC0449', 'name' => 'Mill Spring');
$city_data[] = array('accid' => 'USNC0450', 'name' => 'Millers Creek');
$city_data[] = array('accid' => 'USNC0451', 'name' => 'Milton');
$city_data[] = array('accid' => 'USNC0452', 'name' => 'Milwaukee');
$city_data[] = array('accid' => 'USNC0453', 'name' => 'Mineral Springs');
$city_data[] = array('accid' => 'USNC0454', 'name' => 'Minneapolis');
$city_data[] = array('accid' => 'USNC0455', 'name' => 'Misenheimer');
$city_data[] = array('accid' => 'USNC0456', 'name' => 'Mocksville');
$city_data[] = array('accid' => 'USNC0457', 'name' => 'Moncure');
$city_data[] = array('accid' => 'USNC0458', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USNC0459', 'name' => 'Montezuma');
$city_data[] = array('accid' => 'USNC0460', 'name' => 'Montreat');
$city_data[] = array('accid' => 'USNC0461', 'name' => 'Mooresboro');
$city_data[] = array('accid' => 'USNC0462', 'name' => 'Mooresville');
$city_data[] = array('accid' => 'USNC0463', 'name' => 'Moravian Falls');
$city_data[] = array('accid' => 'USNC0464', 'name' => 'Morehead City');
$city_data[] = array('accid' => 'USNC0465', 'name' => 'Morganton');
$city_data[] = array('accid' => 'USNC0466', 'name' => 'Morrisville');
$city_data[] = array('accid' => 'USNC0467', 'name' => 'Morven');
$city_data[] = array('accid' => 'USNC0468', 'name' => 'Mount Airy');
$city_data[] = array('accid' => 'USNC0469', 'name' => 'Mount Gilead');
$city_data[] = array('accid' => 'USNC0470', 'name' => 'Mount Holly');
$city_data[] = array('accid' => 'USNC0471', 'name' => 'Mount Mourne');
$city_data[] = array('accid' => 'USNC0472', 'name' => 'Mount Olive');
$city_data[] = array('accid' => 'USNC0473', 'name' => 'Mount Pleasant');
$city_data[] = array('accid' => 'USNC0474', 'name' => 'Mount Ulla');
$city_data[] = array('accid' => 'USNC0475', 'name' => 'Mountain Home');
$city_data[] = array('accid' => 'USNC0476', 'name' => 'Moyock');
$city_data[] = array('accid' => 'USNC0477', 'name' => 'Murfreesboro');
$city_data[] = array('accid' => 'USNC0478', 'name' => 'Murphy');
$city_data[] = array('accid' => 'USNC0479', 'name' => 'Nags Head');
$city_data[] = array('accid' => 'USNC0480', 'name' => 'Nakina');
$city_data[] = array('accid' => 'USNC0481', 'name' => 'Naples');
$city_data[] = array('accid' => 'USNC0482', 'name' => 'Nashville');
$city_data[] = array('accid' => 'USNC0483', 'name' => 'Nebo');
$city_data[] = array('accid' => 'USNC0484', 'name' => 'New Bern');
$city_data[] = array('accid' => 'USNC0485', 'name' => 'New Hill');
$city_data[] = array('accid' => 'USNC0486', 'name' => 'New London');
$city_data[] = array('accid' => 'USNC0488', 'name' => 'Newell');
$city_data[] = array('accid' => 'USNC0489', 'name' => 'Newland');
$city_data[] = array('accid' => 'USNC0490', 'name' => 'Newport');
$city_data[] = array('accid' => 'USNC0491', 'name' => 'Newton');
$city_data[] = array('accid' => 'USNC0492', 'name' => 'Newton Grove');
$city_data[] = array('accid' => 'USNC0493', 'name' => 'Norlina');
$city_data[] = array('accid' => 'USNC0494', 'name' => 'Norman');
$city_data[] = array('accid' => 'USNC0495', 'name' => 'North Wilkesboro');
$city_data[] = array('accid' => 'USNC0497', 'name' => 'Norwood');
$city_data[] = array('accid' => 'USNC0498', 'name' => 'Oak City');
$city_data[] = array('accid' => 'USNC0499', 'name' => 'Oak Island');
$city_data[] = array('accid' => 'USNC0500', 'name' => 'Oak Ridge');
$city_data[] = array('accid' => 'USNC0501', 'name' => 'Oakboro');
$city_data[] = array('accid' => 'USNC0502', 'name' => 'Ocean Isle Beach');
$city_data[] = array('accid' => 'USNC0503', 'name' => 'Ocracoke');
$city_data[] = array('accid' => 'USNC0504', 'name' => 'Old Fort');
$city_data[] = array('accid' => 'USNC0505', 'name' => 'Olin');
$city_data[] = array('accid' => 'USNC0506', 'name' => 'Olivia');
$city_data[] = array('accid' => 'USNC0507', 'name' => 'Oriental');
$city_data[] = array('accid' => 'USNC0508', 'name' => 'Orrum');
$city_data[] = array('accid' => 'USNC0509', 'name' => 'Otto');
$city_data[] = array('accid' => 'USNC0510', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USNC0511', 'name' => 'Palmyra');
$city_data[] = array('accid' => 'USNC0512', 'name' => 'Pantego');
$city_data[] = array('accid' => 'USNC0513', 'name' => 'Parkton');
$city_data[] = array('accid' => 'USNC0514', 'name' => 'Parmele');
$city_data[] = array('accid' => 'USNC0515', 'name' => 'Patterson');
$city_data[] = array('accid' => 'USNC0516', 'name' => 'Paw Creek');
$city_data[] = array('accid' => 'USNC0517', 'name' => 'Peachland');
$city_data[] = array('accid' => 'USNC0518', 'name' => 'Pelham');
$city_data[] = array('accid' => 'USNC0519', 'name' => 'Pembroke');
$city_data[] = array('accid' => 'USNC0520', 'name' => 'Pendleton');
$city_data[] = array('accid' => 'USNC0521', 'name' => 'Penland');
$city_data[] = array('accid' => 'USNC0522', 'name' => 'Penrose');
$city_data[] = array('accid' => 'USNC0523', 'name' => 'Pfafftown');
$city_data[] = array('accid' => 'USNC0524', 'name' => 'Pikeville');
$city_data[] = array('accid' => 'USNC0525', 'name' => 'Pilot Mountain');
$city_data[] = array('accid' => 'USNC0526', 'name' => 'Pine Hall');
$city_data[] = array('accid' => 'USNC0527', 'name' => 'Pine Level');
$city_data[] = array('accid' => 'USNC0528', 'name' => 'Pinebluff');
$city_data[] = array('accid' => 'USNC0529', 'name' => 'Pinehurst');
$city_data[] = array('accid' => 'USNC0530', 'name' => 'Pineola');
$city_data[] = array('accid' => 'USNC0531', 'name' => 'Pinetops');
$city_data[] = array('accid' => 'USNC0532', 'name' => 'Pinetown');
$city_data[] = array('accid' => 'USNC0533', 'name' => 'Pineville');
$city_data[] = array('accid' => 'USNC0534', 'name' => 'Piney Creek');
$city_data[] = array('accid' => 'USNC0535', 'name' => 'Pink Hill');
$city_data[] = array('accid' => 'USNC0536', 'name' => 'Pinnacle');
$city_data[] = array('accid' => 'USNC0537', 'name' => 'Pisgah Forest');
$city_data[] = array('accid' => 'USNC0538', 'name' => 'Pittsboro');
$city_data[] = array('accid' => 'USNC0539', 'name' => 'Pleasant Garden');
$city_data[] = array('accid' => 'USNC0540', 'name' => 'Pleasant Hill');
$city_data[] = array('accid' => 'USNC0541', 'name' => 'Plumtree');
$city_data[] = array('accid' => 'USNC0542', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USNC0543', 'name' => 'Point Harbor');
$city_data[] = array('accid' => 'USNC0544', 'name' => 'Polkton');
$city_data[] = array('accid' => 'USNC0545', 'name' => 'Polkville');
$city_data[] = array('accid' => 'USNC0546', 'name' => 'Pollocksville');
$city_data[] = array('accid' => 'USNC0547', 'name' => 'Pope AFB');
$city_data[] = array('accid' => 'USNC0548', 'name' => 'Poplar Branch');
$city_data[] = array('accid' => 'USNC0549', 'name' => 'Potecasi');
$city_data[] = array('accid' => 'USNC0550', 'name' => 'Powells Point');
$city_data[] = array('accid' => 'USNC0551', 'name' => 'Powellsville');
$city_data[] = array('accid' => 'USNC0552', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USNC0553', 'name' => 'Proctorville');
$city_data[] = array('accid' => 'USNC0554', 'name' => 'Prospect Hill');
$city_data[] = array('accid' => 'USNC0555', 'name' => 'Providence');
$city_data[] = array('accid' => 'USNC0556', 'name' => 'Purlear');
$city_data[] = array('accid' => 'USNC0557', 'name' => 'Raeford');
$city_data[] = array('accid' => 'USNC0558', 'name' => 'Raleigh');
$city_data[] = array('accid' => 'USNC0559', 'name' => 'Raleigh$city_data[]Durham International Arpt');
$city_data[] = array('accid' => 'USNC0560', 'name' => 'Ramseur');
$city_data[] = array('accid' => 'USNC0561', 'name' => 'Randleman');
$city_data[] = array('accid' => 'USNC0562', 'name' => 'Red Oak');
$city_data[] = array('accid' => 'USNC0563', 'name' => 'Red Springs');
$city_data[] = array('accid' => 'USNC0564', 'name' => 'Reidsville');
$city_data[] = array('accid' => 'USNC0565', 'name' => 'Rex');
$city_data[] = array('accid' => 'USNC0566', 'name' => 'Rhodhiss');
$city_data[] = array('accid' => 'USNC0567', 'name' => 'Rich Square');
$city_data[] = array('accid' => 'USNC0568', 'name' => 'Richfield');
$city_data[] = array('accid' => 'USNC0569', 'name' => 'Richlands');
$city_data[] = array('accid' => 'USNC0570', 'name' => 'Ridgecrest');
$city_data[] = array('accid' => 'USNC0571', 'name' => 'Ridgeway');
$city_data[] = array('accid' => 'USNC0572', 'name' => 'Riegelwood');
$city_data[] = array('accid' => 'USNC0573', 'name' => 'Roanoke Rapids');
$city_data[] = array('accid' => 'USNC0574', 'name' => 'Roaring Gap');
$city_data[] = array('accid' => 'USNC0575', 'name' => 'Roaring River');
$city_data[] = array('accid' => 'USNC0576', 'name' => 'Robbins');
$city_data[] = array('accid' => 'USNC0577', 'name' => 'Robbinsville');
$city_data[] = array('accid' => 'USNC0578', 'name' => 'Robersonville');
$city_data[] = array('accid' => 'USNC0579', 'name' => 'Rockingham');
$city_data[] = array('accid' => 'USNC0580', 'name' => 'Rockwell');
$city_data[] = array('accid' => 'USNC0581', 'name' => 'Rocky Mount');
$city_data[] = array('accid' => 'USNC0582', 'name' => 'Rocky Point');
$city_data[] = array('accid' => 'USNC0583', 'name' => 'Rodanthe');
$city_data[] = array('accid' => 'USNC0584', 'name' => 'Roduco');
$city_data[] = array('accid' => 'USNC0585', 'name' => 'Rolesville');
$city_data[] = array('accid' => 'USNC0586', 'name' => 'Ronda');
$city_data[] = array('accid' => 'USNC0587', 'name' => 'Roper');
$city_data[] = array('accid' => 'USNC0588', 'name' => 'Rose Hill');
$city_data[] = array('accid' => 'USNC0589', 'name' => 'Roseboro');
$city_data[] = array('accid' => 'USNC0590', 'name' => 'Rosman');
$city_data[] = array('accid' => 'USNC0591', 'name' => 'Rougemont');
$city_data[] = array('accid' => 'USNC0592', 'name' => 'Rowland');
$city_data[] = array('accid' => 'USNC0593', 'name' => 'Roxboro');
$city_data[] = array('accid' => 'USNC0594', 'name' => 'Roxobel');
$city_data[] = array('accid' => 'USNC0595', 'name' => 'Ruffin');
$city_data[] = array('accid' => 'USNC0596', 'name' => 'Rural Hall');
$city_data[] = array('accid' => 'USNC0597', 'name' => 'Rutherford College');
$city_data[] = array('accid' => 'USNC0598', 'name' => 'Rutherfordton');
$city_data[] = array('accid' => 'USNC0599', 'name' => 'Saint Pauls');
$city_data[] = array('accid' => 'USNC0600', 'name' => 'Salemburg');
$city_data[] = array('accid' => 'USNC0601', 'name' => 'Salisbury');
$city_data[] = array('accid' => 'USNC0602', 'name' => 'Salter Path');
$city_data[] = array('accid' => 'USNC0603', 'name' => 'Saluda');
$city_data[] = array('accid' => 'USNC0604', 'name' => 'Salvo');
$city_data[] = array('accid' => 'USNC0605', 'name' => 'Sandy Ridge');
$city_data[] = array('accid' => 'USNC0606', 'name' => 'Sanford');
$city_data[] = array('accid' => 'USNC0607', 'name' => 'Sapphire');
$city_data[] = array('accid' => 'USNC0608', 'name' => 'Saratoga');
$city_data[] = array('accid' => 'USNC0609', 'name' => 'Saxapahaw');
$city_data[] = array('accid' => 'USNC0610', 'name' => 'Scaly Mountain');
$city_data[] = array('accid' => 'USNC0611', 'name' => 'Scotland Neck');
$city_data[] = array('accid' => 'USNC0612', 'name' => 'Scotts');
$city_data[] = array('accid' => 'USNC0613', 'name' => 'Scottville');
$city_data[] = array('accid' => 'USNC0614', 'name' => 'Scranton');
$city_data[] = array('accid' => 'USNC0615', 'name' => 'Seaboard');
$city_data[] = array('accid' => 'USNC0616', 'name' => 'Seagrove');
$city_data[] = array('accid' => 'USNC0617', 'name' => 'Sealevel');
$city_data[] = array('accid' => 'USNC0618', 'name' => 'Sedalia');
$city_data[] = array('accid' => 'USNC0619', 'name' => 'Selma');
$city_data[] = array('accid' => 'USNC0620', 'name' => 'Semora');
$city_data[] = array('accid' => 'USNC0621', 'name' => 'Seven Springs');
$city_data[] = array('accid' => 'USNC0622', 'name' => 'Severn');
$city_data[] = array('accid' => 'USNC0623', 'name' => 'Shallotte');
$city_data[] = array('accid' => 'USNC0624', 'name' => 'Shannon');
$city_data[] = array('accid' => 'USNC0625', 'name' => 'Sharpsburg');
$city_data[] = array('accid' => 'USNC0626', 'name' => 'Shawboro');
$city_data[] = array('accid' => 'USNC0627', 'name' => 'Shelby');
$city_data[] = array('accid' => 'USNC0628', 'name' => 'Sherrills Ford');
$city_data[] = array('accid' => 'USNC0629', 'name' => 'Shiloh');
$city_data[] = array('accid' => 'USNC0630', 'name' => 'Siler City');
$city_data[] = array('accid' => 'USNC0631', 'name' => 'Siloam');
$city_data[] = array('accid' => 'USNC0632', 'name' => 'Simpson');
$city_data[] = array('accid' => 'USNC0633', 'name' => 'Sims');
$city_data[] = array('accid' => 'USNC0635', 'name' => 'Skyland');
$city_data[] = array('accid' => 'USNC0636', 'name' => 'Smithfield');
$city_data[] = array('accid' => 'USNC0637', 'name' => 'Smyrna');
$city_data[] = array('accid' => 'USNC0638', 'name' => 'Sneads Ferry');
$city_data[] = array('accid' => 'USNC0639', 'name' => 'Snow Camp');
$city_data[] = array('accid' => 'USNC0640', 'name' => 'Snow Hill');
$city_data[] = array('accid' => 'USNC0641', 'name' => 'Sophia');
$city_data[] = array('accid' => 'USNC0642', 'name' => 'South Brunswick');
$city_data[] = array('accid' => 'USNC0643', 'name' => 'South Mills');
$city_data[] = array('accid' => 'USNC0644', 'name' => 'Southern Pines');
$city_data[] = array('accid' => 'USNC0645', 'name' => 'Southmont');
$city_data[] = array('accid' => 'USNC0646', 'name' => 'Southport');
$city_data[] = array('accid' => 'USNC0647', 'name' => 'Sparta');
$city_data[] = array('accid' => 'USNC0648', 'name' => 'Speed');
$city_data[] = array('accid' => 'USNC0649', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USNC0650', 'name' => 'Spindale');
$city_data[] = array('accid' => 'USNC0651', 'name' => 'Spring Hope');
$city_data[] = array('accid' => 'USNC0652', 'name' => 'Spring Lake');
$city_data[] = array('accid' => 'USNC0653', 'name' => 'Spruce Pine');
$city_data[] = array('accid' => 'USNC0654', 'name' => 'Stacy');
$city_data[] = array('accid' => 'USNC0655', 'name' => 'Staley');
$city_data[] = array('accid' => 'USNC0656', 'name' => 'Stanfield');
$city_data[] = array('accid' => 'USNC0657', 'name' => 'Stanley');
$city_data[] = array('accid' => 'USNC0658', 'name' => 'Stantonsburg');
$city_data[] = array('accid' => 'USNC0659', 'name' => 'Star');
$city_data[] = array('accid' => 'USNC0660', 'name' => 'State Road');
$city_data[] = array('accid' => 'USNC0661', 'name' => 'Statesville');
$city_data[] = array('accid' => 'USNC0662', 'name' => 'Stedman');
$city_data[] = array('accid' => 'USNC0663', 'name' => 'Stella');
$city_data[] = array('accid' => 'USNC0664', 'name' => 'Stem');
$city_data[] = array('accid' => 'USNC0665', 'name' => 'Stokes');
$city_data[] = array('accid' => 'USNC0666', 'name' => 'Stokesdale');
$city_data[] = array('accid' => 'USNC0667', 'name' => 'Stoneville');
$city_data[] = array('accid' => 'USNC0668', 'name' => 'Stonewall');
$city_data[] = array('accid' => 'USNC0669', 'name' => 'Stony Point');
$city_data[] = array('accid' => 'USNC0670', 'name' => 'Stovall');
$city_data[] = array('accid' => 'USNC0671', 'name' => 'Stumpy Point');
$city_data[] = array('accid' => 'USNC0672', 'name' => 'Sugar Grove');
$city_data[] = array('accid' => 'USNC0674', 'name' => 'Summerfield');
$city_data[] = array('accid' => 'USNC0675', 'name' => 'Sunbury');
$city_data[] = array('accid' => 'USNC0676', 'name' => 'Sunset Beach');
$city_data[] = array('accid' => 'USNC0677', 'name' => 'Supply');
$city_data[] = array('accid' => 'USNC0678', 'name' => 'Swannanoa');
$city_data[] = array('accid' => 'USNC0679', 'name' => 'Swanquarter');
$city_data[] = array('accid' => 'USNC0681', 'name' => 'Swepsonville');
$city_data[] = array('accid' => 'USNC0682', 'name' => 'Sylva');
$city_data[] = array('accid' => 'USNC0683', 'name' => 'Tabor City');
$city_data[] = array('accid' => 'USNC0684', 'name' => 'Tar Heel');
$city_data[] = array('accid' => 'USNC0685', 'name' => 'Tarawa Terrace');
$city_data[] = array('accid' => 'USNC0686', 'name' => 'Tarboro');
$city_data[] = array('accid' => 'USNC0687', 'name' => 'Taylorsville');
$city_data[] = array('accid' => 'USNC0688', 'name' => 'Teachey');
$city_data[] = array('accid' => 'USNC0689', 'name' => 'Terrell');
$city_data[] = array('accid' => 'USNC0690', 'name' => 'Thomasville');
$city_data[] = array('accid' => 'USNC0691', 'name' => 'Thurmond');
$city_data[] = array('accid' => 'USNC0692', 'name' => 'Tillery');
$city_data[] = array('accid' => 'USNC0693', 'name' => 'Timberlake');
$city_data[] = array('accid' => 'USNC0694', 'name' => 'Toast');
$city_data[] = array('accid' => 'USNC0695', 'name' => 'Tobaccoville');
$city_data[] = array('accid' => 'USNC0696', 'name' => 'Todd');
$city_data[] = array('accid' => 'USNC0697', 'name' => 'Topton');
$city_data[] = array('accid' => 'USNC0698', 'name' => 'Townsville');
$city_data[] = array('accid' => 'USNC0699', 'name' => 'Traphill');
$city_data[] = array('accid' => 'USNC0700', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USNC0701', 'name' => 'Trinity');
$city_data[] = array('accid' => 'USNC0702', 'name' => 'Troutman');
$city_data[] = array('accid' => 'USNC0703', 'name' => 'Troy');
$city_data[] = array('accid' => 'USNC0704', 'name' => 'Tryon');
$city_data[] = array('accid' => 'USNC0705', 'name' => 'Tuckasegee');
$city_data[] = array('accid' => 'USNC0706', 'name' => 'Turkey');
$city_data[] = array('accid' => 'USNC0707', 'name' => 'Turnersburg');
$city_data[] = array('accid' => 'USNC0708', 'name' => 'Tuxedo');
$city_data[] = array('accid' => 'USNC0709', 'name' => 'Tyner');
$city_data[] = array('accid' => 'USNC0710', 'name' => 'Union Grove');
$city_data[] = array('accid' => 'USNC0711', 'name' => 'Union Mills');
$city_data[] = array('accid' => 'USNC0712', 'name' => 'Valdese');
$city_data[] = array('accid' => 'USNC0713', 'name' => 'Vale');
$city_data[] = array('accid' => 'USNC0714', 'name' => 'Valle Crucis');
$city_data[] = array('accid' => 'USNC0715', 'name' => 'Vanceboro');
$city_data[] = array('accid' => 'USNC0716', 'name' => 'Vandemere');
$city_data[] = array('accid' => 'USNC0717', 'name' => 'Vass');
$city_data[] = array('accid' => 'USNC0718', 'name' => 'Vaughan');
$city_data[] = array('accid' => 'USNC0719', 'name' => 'Vilas');
$city_data[] = array('accid' => 'USNC0720', 'name' => 'Waco');
$city_data[] = array('accid' => 'USNC0721', 'name' => 'Wade');
$city_data[] = array('accid' => 'USNC0722', 'name' => 'Wadesboro');
$city_data[] = array('accid' => 'USNC0723', 'name' => 'Wagram');
$city_data[] = array('accid' => 'USNC0724', 'name' => 'Wake Forest');
$city_data[] = array('accid' => 'USNC0725', 'name' => 'Walkertown');
$city_data[] = array('accid' => 'USNC0726', 'name' => 'Wallace');
$city_data[] = array('accid' => 'USNC0727', 'name' => 'Wallburg');
$city_data[] = array('accid' => 'USNC0728', 'name' => 'Walnut Cove');
$city_data[] = array('accid' => 'USNC0729', 'name' => 'Walstonburg');
$city_data[] = array('accid' => 'USNC0730', 'name' => 'Wanchese');
$city_data[] = array('accid' => 'USNC0731', 'name' => 'Warne');
$city_data[] = array('accid' => 'USNC0732', 'name' => 'Warrensville');
$city_data[] = array('accid' => 'USNC0733', 'name' => 'Warrenton');
$city_data[] = array('accid' => 'USNC0734', 'name' => 'Warsaw');
$city_data[] = array('accid' => 'USNC0735', 'name' => 'Washington');
$city_data[] = array('accid' => 'USNC0736', 'name' => 'Watha');
$city_data[] = array('accid' => 'USNC0737', 'name' => 'Waves');
$city_data[] = array('accid' => 'USNC0738', 'name' => 'Waxhaw');
$city_data[] = array('accid' => 'USNC0739', 'name' => 'Waynesville');
$city_data[] = array('accid' => 'USNC0740', 'name' => 'Weaverville');
$city_data[] = array('accid' => 'USNC0741', 'name' => 'Webster');
$city_data[] = array('accid' => 'USNC0742', 'name' => 'Welcome');
$city_data[] = array('accid' => 'USNC0743', 'name' => 'Weldon');
$city_data[] = array('accid' => 'USNC0744', 'name' => 'Wendell');
$city_data[] = array('accid' => 'USNC0745', 'name' => 'Wentworth');
$city_data[] = array('accid' => 'USNC0746', 'name' => 'West End');
$city_data[] = array('accid' => 'USNC0747', 'name' => 'West Jefferson');
$city_data[] = array('accid' => 'USNC0748', 'name' => 'Westfield');
$city_data[] = array('accid' => 'USNC0749', 'name' => 'Whitakers');
$city_data[] = array('accid' => 'USNC0750', 'name' => 'White Oak');
$city_data[] = array('accid' => 'USNC0751', 'name' => 'White Plains');
$city_data[] = array('accid' => 'USNC0752', 'name' => 'Whiteville');
$city_data[] = array('accid' => 'USNC0753', 'name' => 'Whitsett');
$city_data[] = array('accid' => 'USNC0754', 'name' => 'Whittier');
$city_data[] = array('accid' => 'USNC0755', 'name' => 'Wilkesboro');
$city_data[] = array('accid' => 'USNC0756', 'name' => 'Willard');
$city_data[] = array('accid' => 'USNC0757', 'name' => 'Williamston');
$city_data[] = array('accid' => 'USNC0758', 'name' => 'Williston');
$city_data[] = array('accid' => 'USNC0759', 'name' => 'Willow Spring');
$city_data[] = array('accid' => 'USNC0760', 'name' => 'Wilmington');
$city_data[] = array('accid' => 'USNC0761', 'name' => 'Wilson');
$city_data[] = array('accid' => 'USNC0762', 'name' => 'Wilsons Mills');
$city_data[] = array('accid' => 'USNC0763', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USNC0764', 'name' => 'Winfall');
$city_data[] = array('accid' => 'USNC0765', 'name' => 'Wingate');
$city_data[] = array('accid' => 'USNC0766', 'name' => 'Winnabow');
$city_data[] = array('accid' => 'USNC0767', 'name' => 'Winston-Salem');
$city_data[] = array('accid' => 'USNC0768', 'name' => 'Winterville');
$city_data[] = array('accid' => 'USNC0769', 'name' => 'Winton');
$city_data[] = array('accid' => 'USNC0770', 'name' => 'Wise');
$city_data[] = array('accid' => 'USNC0771', 'name' => 'Woodland');
$city_data[] = array('accid' => 'USNC0772', 'name' => 'Woodleaf');
$city_data[] = array('accid' => 'USNC0773', 'name' => 'Wrightsville Beach');
$city_data[] = array('accid' => 'USNC0774', 'name' => 'Yadkinville');
$city_data[] = array('accid' => 'USNC0775', 'name' => 'Yanceyville');
$city_data[] = array('accid' => 'USNC0776', 'name' => 'Youngsville');
$city_data[] = array('accid' => 'USNC0777', 'name' => 'Zebulon');
$city_data[] = array('accid' => 'USNC0778', 'name' => 'Zionville');
$city_data[] = array('accid' => 'USNC0779', 'name' => 'Zirconia');

?>
