<?php

// City package for USA: North Dakota 

$city_name = 'USA: North Dakota';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USND0001', 'name' => 'Abercrombie');
$city_data[] = array('accid' => 'USND0002', 'name' => 'Absaraka');
$city_data[] = array('accid' => 'USND0003', 'name' => 'Adams');
$city_data[] = array('accid' => 'USND0004', 'name' => 'Agate');
$city_data[] = array('accid' => 'USND0005', 'name' => 'Alamo');
$city_data[] = array('accid' => 'USND0006', 'name' => 'Alexander');
$city_data[] = array('accid' => 'USND0007', 'name' => 'Almont');
$city_data[] = array('accid' => 'USND0008', 'name' => 'Alsen');
$city_data[] = array('accid' => 'USND0009', 'name' => 'Ambrose');
$city_data[] = array('accid' => 'USND0010', 'name' => 'Amenia');
$city_data[] = array('accid' => 'USND0011', 'name' => 'Amidon');
$city_data[] = array('accid' => 'USND0012', 'name' => 'Anamoose');
$city_data[] = array('accid' => 'USND0013', 'name' => 'Aneta');
$city_data[] = array('accid' => 'USND0014', 'name' => 'Antler');
$city_data[] = array('accid' => 'USND0015', 'name' => 'Ardoch');
$city_data[] = array('accid' => 'USND0016', 'name' => 'Argusville');
$city_data[] = array('accid' => 'USND0017', 'name' => 'Arnegard');
$city_data[] = array('accid' => 'USND0018', 'name' => 'Arthur');
$city_data[] = array('accid' => 'USND0019', 'name' => 'Arvilla');
$city_data[] = array('accid' => 'USND0020', 'name' => 'Ashley');
$city_data[] = array('accid' => 'USND0021', 'name' => 'Ayr');
$city_data[] = array('accid' => 'USND0022', 'name' => 'Baldwin');
$city_data[] = array('accid' => 'USND0023', 'name' => 'Balfour');
$city_data[] = array('accid' => 'USND0024', 'name' => 'Balta');
$city_data[] = array('accid' => 'USND0025', 'name' => 'Bantry');
$city_data[] = array('accid' => 'USND0026', 'name' => 'Barney');
$city_data[] = array('accid' => 'USND0027', 'name' => 'Bathgate');
$city_data[] = array('accid' => 'USND0028', 'name' => 'Beach');
$city_data[] = array('accid' => 'USND0029', 'name' => 'Belcourt');
$city_data[] = array('accid' => 'USND0030', 'name' => 'Belfield');
$city_data[] = array('accid' => 'USND0031', 'name' => 'Benedict');
$city_data[] = array('accid' => 'USND0032', 'name' => 'Berlin');
$city_data[] = array('accid' => 'USND0033', 'name' => 'Berthold');
$city_data[] = array('accid' => 'USND0034', 'name' => 'Beulah');
$city_data[] = array('accid' => 'USND0035', 'name' => 'Binford');
$city_data[] = array('accid' => 'USND0036', 'name' => 'Bisbee');
$city_data[] = array('accid' => 'USND0037', 'name' => 'Bismarck');
$city_data[] = array('accid' => 'USND0038', 'name' => 'Blanchard');
$city_data[] = array('accid' => 'USND0039', 'name' => 'Bottineau');
$city_data[] = array('accid' => 'USND0040', 'name' => 'Bowbells');
$city_data[] = array('accid' => 'USND0041', 'name' => 'Bowdon');
$city_data[] = array('accid' => 'USND0042', 'name' => 'Bowman');
$city_data[] = array('accid' => 'USND0043', 'name' => 'Braddock');
$city_data[] = array('accid' => 'USND0044', 'name' => 'Bremen');
$city_data[] = array('accid' => 'USND0045', 'name' => 'Brinsmade');
$city_data[] = array('accid' => 'USND0046', 'name' => 'Brocket');
$city_data[] = array('accid' => 'USND0047', 'name' => 'Buchanan');
$city_data[] = array('accid' => 'USND0048', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USND0049', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USND0050', 'name' => 'Butte');
$city_data[] = array('accid' => 'USND0051', 'name' => 'Buxton');
$city_data[] = array('accid' => 'USND0052', 'name' => 'Caledonia');
$city_data[] = array('accid' => 'USND0053', 'name' => 'Calvin');
$city_data[] = array('accid' => 'USND0054', 'name' => 'Cando');
$city_data[] = array('accid' => 'USND0055', 'name' => 'Cannon Ball');
$city_data[] = array('accid' => 'USND0056', 'name' => 'Carpio');
$city_data[] = array('accid' => 'USND0057', 'name' => 'Carrington');
$city_data[] = array('accid' => 'USND0058', 'name' => 'Carson');
$city_data[] = array('accid' => 'USND0059', 'name' => 'Cartwright');
$city_data[] = array('accid' => 'USND0060', 'name' => 'Casselton');
$city_data[] = array('accid' => 'USND0061', 'name' => 'Cathay');
$city_data[] = array('accid' => 'USND0062', 'name' => 'Cavalier');
$city_data[] = array('accid' => 'USND0063', 'name' => 'Cayuga');
$city_data[] = array('accid' => 'USND0064', 'name' => 'Center');
$city_data[] = array('accid' => 'USND0065', 'name' => 'Chaffee');
$city_data[] = array('accid' => 'USND0066', 'name' => 'Chaseley');
$city_data[] = array('accid' => 'USND0067', 'name' => 'Christine');
$city_data[] = array('accid' => 'USND0068', 'name' => 'Churchs Ferry');
$city_data[] = array('accid' => 'USND0069', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USND0070', 'name' => 'Clifford');
$city_data[] = array('accid' => 'USND0071', 'name' => 'Cogswell');
$city_data[] = array('accid' => 'USND0072', 'name' => 'Coleharbor');
$city_data[] = array('accid' => 'USND0073', 'name' => 'Colfax');
$city_data[] = array('accid' => 'USND0074', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USND0075', 'name' => 'Cooperstown');
$city_data[] = array('accid' => 'USND0076', 'name' => 'Courtenay');
$city_data[] = array('accid' => 'USND0077', 'name' => 'Crary');
$city_data[] = array('accid' => 'USND0078', 'name' => 'Crosby');
$city_data[] = array('accid' => 'USND0079', 'name' => 'Crystal');
$city_data[] = array('accid' => 'USND0080', 'name' => 'Cummings');
$city_data[] = array('accid' => 'USND0081', 'name' => 'Dahlen');
$city_data[] = array('accid' => 'USND0082', 'name' => 'Davenport');
$city_data[] = array('accid' => 'USND0083', 'name' => 'Dawson');
$city_data[] = array('accid' => 'USND0084', 'name' => 'Dazey');
$city_data[] = array('accid' => 'USND0085', 'name' => 'Deering');
$city_data[] = array('accid' => 'USND0086', 'name' => 'Denhoff');
$city_data[] = array('accid' => 'USND0087', 'name' => 'Des Lacs');
$city_data[] = array('accid' => 'USND0088', 'name' => 'Devils Lake');
$city_data[] = array('accid' => 'USND0089', 'name' => 'Dickey');
$city_data[] = array('accid' => 'USND0090', 'name' => 'Dickinson');
$city_data[] = array('accid' => 'USND0091', 'name' => 'Dodge');
$city_data[] = array('accid' => 'USND0092', 'name' => 'Donnybrook');
$city_data[] = array('accid' => 'USND0093', 'name' => 'Douglas');
$city_data[] = array('accid' => 'USND0094', 'name' => 'Drake');
$city_data[] = array('accid' => 'USND0095', 'name' => 'Drayton');
$city_data[] = array('accid' => 'USND0096', 'name' => 'Driscoll');
$city_data[] = array('accid' => 'USND0097', 'name' => 'Dunn Center');
$city_data[] = array('accid' => 'USND0098', 'name' => 'Dunseith');
$city_data[] = array('accid' => 'USND0099', 'name' => 'Eckelson');
$city_data[] = array('accid' => 'USND0100', 'name' => 'Edgeley');
$city_data[] = array('accid' => 'USND0101', 'name' => 'Edinburg');
$city_data[] = array('accid' => 'USND0102', 'name' => 'Edmore');
$city_data[] = array('accid' => 'USND0103', 'name' => 'Egeland');
$city_data[] = array('accid' => 'USND0104', 'name' => 'Elgin');
$city_data[] = array('accid' => 'USND0105', 'name' => 'Ellendale');
$city_data[] = array('accid' => 'USND0106', 'name' => 'Emerado');
$city_data[] = array('accid' => 'USND0108', 'name' => 'Enderlin');
$city_data[] = array('accid' => 'USND0109', 'name' => 'Epping');
$city_data[] = array('accid' => 'USND0110', 'name' => 'Erie');
$city_data[] = array('accid' => 'USND0111', 'name' => 'Esmond');
$city_data[] = array('accid' => 'USND0112', 'name' => 'Fairdale');
$city_data[] = array('accid' => 'USND0113', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USND0114', 'name' => 'Fairmount');
$city_data[] = array('accid' => 'USND0115', 'name' => 'Fargo');
$city_data[] = array('accid' => 'USND0116', 'name' => 'Fessenden');
$city_data[] = array('accid' => 'USND0117', 'name' => 'Fingal');
$city_data[] = array('accid' => 'USND0118', 'name' => 'Finley');
$city_data[] = array('accid' => 'USND0119', 'name' => 'Flasher');
$city_data[] = array('accid' => 'USND0120', 'name' => 'Flaxton');
$city_data[] = array('accid' => 'USND0121', 'name' => 'Forbes');
$city_data[] = array('accid' => 'USND0122', 'name' => 'Fordville');
$city_data[] = array('accid' => 'USND0123', 'name' => 'Forest River');
$city_data[] = array('accid' => 'USND0124', 'name' => 'Forman');
$city_data[] = array('accid' => 'USND0125', 'name' => 'Fort Ransom');
$city_data[] = array('accid' => 'USND0126', 'name' => 'Fort Totten');
$city_data[] = array('accid' => 'USND0127', 'name' => 'Fort Yates');
$city_data[] = array('accid' => 'USND0128', 'name' => 'Fortuna');
$city_data[] = array('accid' => 'USND0129', 'name' => 'Fredonia');
$city_data[] = array('accid' => 'USND0130', 'name' => 'Fullerton');
$city_data[] = array('accid' => 'USND0131', 'name' => 'Gackle');
$city_data[] = array('accid' => 'USND0132', 'name' => 'Galesburg');
$city_data[] = array('accid' => 'USND0133', 'name' => 'Gardner');
$city_data[] = array('accid' => 'USND0134', 'name' => 'Garrison');
$city_data[] = array('accid' => 'USND0135', 'name' => 'Gilby');
$city_data[] = array('accid' => 'USND0136', 'name' => 'Gladstone');
$city_data[] = array('accid' => 'USND0137', 'name' => 'Glasston');
$city_data[] = array('accid' => 'USND0138', 'name' => 'Glen Ullin');
$city_data[] = array('accid' => 'USND0139', 'name' => 'Glenburn');
$city_data[] = array('accid' => 'USND0140', 'name' => 'Glenfield');
$city_data[] = array('accid' => 'USND0141', 'name' => 'Golden Valley');
$city_data[] = array('accid' => 'USND0142', 'name' => 'Golva');
$city_data[] = array('accid' => 'USND0143', 'name' => 'Goodrich');
$city_data[] = array('accid' => 'USND0144', 'name' => 'Grace City');
$city_data[] = array('accid' => 'USND0145', 'name' => 'Grafton');
$city_data[] = array('accid' => 'USND0146', 'name' => 'Grand Forks');
$city_data[] = array('accid' => 'USND0147', 'name' => 'Grand Forks AFB');
$city_data[] = array('accid' => 'USND0148', 'name' => 'Grandin');
$city_data[] = array('accid' => 'USND0149', 'name' => 'Granville');
$city_data[] = array('accid' => 'USND0150', 'name' => 'Grassy Butte');
$city_data[] = array('accid' => 'USND0151', 'name' => 'Great Bend');
$city_data[] = array('accid' => 'USND0152', 'name' => 'Grenora');
$city_data[] = array('accid' => 'USND0153', 'name' => 'Gwinner');
$city_data[] = array('accid' => 'USND0154', 'name' => 'Hague');
$city_data[] = array('accid' => 'USND0155', 'name' => 'Halliday');
$city_data[] = array('accid' => 'USND0156', 'name' => 'Hamberg');
$city_data[] = array('accid' => 'USND0157', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USND0158', 'name' => 'Hampden');
$city_data[] = array('accid' => 'USND0159', 'name' => 'Hankinson');
$city_data[] = array('accid' => 'USND0160', 'name' => 'Hannaford');
$city_data[] = array('accid' => 'USND0161', 'name' => 'Hannah');
$city_data[] = array('accid' => 'USND0162', 'name' => 'Hansboro');
$city_data[] = array('accid' => 'USND0163', 'name' => 'Harvey');
$city_data[] = array('accid' => 'USND0164', 'name' => 'Harwood');
$city_data[] = array('accid' => 'USND0165', 'name' => 'Hatton');
$city_data[] = array('accid' => 'USND0166', 'name' => 'Havana');
$city_data[] = array('accid' => 'USND0167', 'name' => 'Hazelton');
$city_data[] = array('accid' => 'USND0168', 'name' => 'Hazen');
$city_data[] = array('accid' => 'USND0169', 'name' => 'Hebron');
$city_data[] = array('accid' => 'USND0170', 'name' => 'Hensel');
$city_data[] = array('accid' => 'USND0171', 'name' => 'Hettinger');
$city_data[] = array('accid' => 'USND0172', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USND0173', 'name' => 'Hoople');
$city_data[] = array('accid' => 'USND0174', 'name' => 'Hope');
$city_data[] = array('accid' => 'USND0175', 'name' => 'Horace');
$city_data[] = array('accid' => 'USND0176', 'name' => 'Hunter');
$city_data[] = array('accid' => 'USND0177', 'name' => 'Hurdsfield');
$city_data[] = array('accid' => 'USND0178', 'name' => 'Inkster');
$city_data[] = array('accid' => 'USND0179', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USND0180', 'name' => 'Jessie');
$city_data[] = array('accid' => 'USND0181', 'name' => 'Jud');
$city_data[] = array('accid' => 'USND0182', 'name' => 'Karlsruhe');
$city_data[] = array('accid' => 'USND0183', 'name' => 'Kathryn');
$city_data[] = array('accid' => 'USND0184', 'name' => 'Keene');
$city_data[] = array('accid' => 'USND0185', 'name' => 'Kenmare');
$city_data[] = array('accid' => 'USND0186', 'name' => 'Kensal');
$city_data[] = array('accid' => 'USND0187', 'name' => 'Kief');
$city_data[] = array('accid' => 'USND0188', 'name' => 'Killdeer');
$city_data[] = array('accid' => 'USND0189', 'name' => 'Kindred');
$city_data[] = array('accid' => 'USND0190', 'name' => 'Kintyre');
$city_data[] = array('accid' => 'USND0191', 'name' => 'Knox');
$city_data[] = array('accid' => 'USND0192', 'name' => 'Kramer');
$city_data[] = array('accid' => 'USND0193', 'name' => 'Kulm');
$city_data[] = array('accid' => 'USND0194', 'name' => 'Lakota');
$city_data[] = array('accid' => 'USND0195', 'name' => 'Lamoure');
$city_data[] = array('accid' => 'USND0196', 'name' => 'Langdon');
$city_data[] = array('accid' => 'USND0197', 'name' => 'Lankin');
$city_data[] = array('accid' => 'USND0198', 'name' => 'Lansford');
$city_data[] = array('accid' => 'USND0199', 'name' => 'Larimore');
$city_data[] = array('accid' => 'USND0200', 'name' => 'Lawton');
$city_data[] = array('accid' => 'USND0201', 'name' => 'Leeds');
$city_data[] = array('accid' => 'USND0202', 'name' => 'Lefor');
$city_data[] = array('accid' => 'USND0203', 'name' => 'Lehr');
$city_data[] = array('accid' => 'USND0204', 'name' => 'Leonard');
$city_data[] = array('accid' => 'USND0205', 'name' => 'Lidgerwood');
$city_data[] = array('accid' => 'USND0206', 'name' => 'Lignite');
$city_data[] = array('accid' => 'USND0207', 'name' => 'Linton');
$city_data[] = array('accid' => 'USND0208', 'name' => 'Lisbon');
$city_data[] = array('accid' => 'USND0209', 'name' => 'Litchville');
$city_data[] = array('accid' => 'USND0210', 'name' => 'Luverne');
$city_data[] = array('accid' => 'USND0211', 'name' => 'Maddock');
$city_data[] = array('accid' => 'USND0212', 'name' => 'Maida');
$city_data[] = array('accid' => 'USND0213', 'name' => 'Makoti');
$city_data[] = array('accid' => 'USND0214', 'name' => 'Mandan');
$city_data[] = array('accid' => 'USND0215', 'name' => 'Mandaree');
$city_data[] = array('accid' => 'USND0216', 'name' => 'Manning');
$city_data[] = array('accid' => 'USND0217', 'name' => 'Mantador');
$city_data[] = array('accid' => 'USND0218', 'name' => 'Manvel');
$city_data[] = array('accid' => 'USND0219', 'name' => 'Mapleton');
$city_data[] = array('accid' => 'USND0220', 'name' => 'Marion');
$city_data[] = array('accid' => 'USND0221', 'name' => 'Marmarth');
$city_data[] = array('accid' => 'USND0222', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USND0223', 'name' => 'Martin');
$city_data[] = array('accid' => 'USND0224', 'name' => 'Max');
$city_data[] = array('accid' => 'USND0225', 'name' => 'Maxbass');
$city_data[] = array('accid' => 'USND0226', 'name' => 'Mayville');
$city_data[] = array('accid' => 'USND0227', 'name' => 'McClusky');
$city_data[] = array('accid' => 'USND0228', 'name' => 'McGregor');
$city_data[] = array('accid' => 'USND0229', 'name' => 'McHenry');
$city_data[] = array('accid' => 'USND0230', 'name' => 'McKenzie');
$city_data[] = array('accid' => 'USND0231', 'name' => 'McLeod');
$city_data[] = array('accid' => 'USND0232', 'name' => 'McVille');
$city_data[] = array('accid' => 'USND0233', 'name' => 'Medina');
$city_data[] = array('accid' => 'USND0234', 'name' => 'Medora');
$city_data[] = array('accid' => 'USND0235', 'name' => 'Mekinock');
$city_data[] = array('accid' => 'USND0236', 'name' => 'Menoken');
$city_data[] = array('accid' => 'USND0237', 'name' => 'Mercer');
$city_data[] = array('accid' => 'USND0238', 'name' => 'Michigan');
$city_data[] = array('accid' => 'USND0239', 'name' => 'Milnor');
$city_data[] = array('accid' => 'USND0240', 'name' => 'Milton');
$city_data[] = array('accid' => 'USND0241', 'name' => 'Minnewaukan');
$city_data[] = array('accid' => 'USND0242', 'name' => 'Minot');
$city_data[] = array('accid' => 'USND0243', 'name' => 'Minot AFB');
$city_data[] = array('accid' => 'USND0244', 'name' => 'Minto');
$city_data[] = array('accid' => 'USND0245', 'name' => 'Moffit');
$city_data[] = array('accid' => 'USND0246', 'name' => 'Mohall');
$city_data[] = array('accid' => 'USND0247', 'name' => 'Montpelier');
$city_data[] = array('accid' => 'USND0248', 'name' => 'Mooreton');
$city_data[] = array('accid' => 'USND0249', 'name' => 'Mott');
$city_data[] = array('accid' => 'USND0250', 'name' => 'Mountain');
$city_data[] = array('accid' => 'USND0251', 'name' => 'Munich');
$city_data[] = array('accid' => 'USND0252', 'name' => 'Mylo');
$city_data[] = array('accid' => 'USND0253', 'name' => 'Napoleon');
$city_data[] = array('accid' => 'USND0254', 'name' => 'Neche');
$city_data[] = array('accid' => 'USND0255', 'name' => 'Nekoma');
$city_data[] = array('accid' => 'USND0256', 'name' => 'New England');
$city_data[] = array('accid' => 'USND0257', 'name' => 'New Leipzig');
$city_data[] = array('accid' => 'USND0258', 'name' => 'New Rockford');
$city_data[] = array('accid' => 'USND0259', 'name' => 'New Salem');
$city_data[] = array('accid' => 'USND0260', 'name' => 'New Town');
$city_data[] = array('accid' => 'USND0261', 'name' => 'Newburg');
$city_data[] = array('accid' => 'USND0262', 'name' => 'Niagara');
$city_data[] = array('accid' => 'USND0263', 'name' => 'Nome');
$city_data[] = array('accid' => 'USND0264', 'name' => 'Noonan');
$city_data[] = array('accid' => 'USND0265', 'name' => 'Northwood');
$city_data[] = array('accid' => 'USND0266', 'name' => 'Norwich');
$city_data[] = array('accid' => 'USND0267', 'name' => 'Oakes');
$city_data[] = array('accid' => 'USND0268', 'name' => 'Oberon');
$city_data[] = array('accid' => 'USND0269', 'name' => 'Oriska');
$city_data[] = array('accid' => 'USND0270', 'name' => 'Orrin');
$city_data[] = array('accid' => 'USND0271', 'name' => 'Osnabrock');
$city_data[] = array('accid' => 'USND0272', 'name' => 'Page');
$city_data[] = array('accid' => 'USND0273', 'name' => 'Palermo');
$city_data[] = array('accid' => 'USND0274', 'name' => 'Park River');
$city_data[] = array('accid' => 'USND0275', 'name' => 'Parshall');
$city_data[] = array('accid' => 'USND0276', 'name' => 'Pekin');
$city_data[] = array('accid' => 'USND0277', 'name' => 'Pembina');
$city_data[] = array('accid' => 'USND0278', 'name' => 'Penn');
$city_data[] = array('accid' => 'USND0279', 'name' => 'Perth');
$city_data[] = array('accid' => 'USND0280', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USND0281', 'name' => 'Pettibone');
$city_data[] = array('accid' => 'USND0282', 'name' => 'Pillsbury');
$city_data[] = array('accid' => 'USND0283', 'name' => 'Pingree');
$city_data[] = array('accid' => 'USND0284', 'name' => 'Pisek');
$city_data[] = array('accid' => 'USND0285', 'name' => 'Plaza');
$city_data[] = array('accid' => 'USND0286', 'name' => 'Portal');
$city_data[] = array('accid' => 'USND0287', 'name' => 'Portland');
$city_data[] = array('accid' => 'USND0288', 'name' => 'Powers Lake');
$city_data[] = array('accid' => 'USND0289', 'name' => 'Raleigh');
$city_data[] = array('accid' => 'USND0290', 'name' => 'Ray');
$city_data[] = array('accid' => 'USND0291', 'name' => 'Reeder');
$city_data[] = array('accid' => 'USND0292', 'name' => 'Regan');
$city_data[] = array('accid' => 'USND0293', 'name' => 'Regent');
$city_data[] = array('accid' => 'USND0294', 'name' => 'Reynolds');
$city_data[] = array('accid' => 'USND0295', 'name' => 'Rhame');
$city_data[] = array('accid' => 'USND0296', 'name' => 'Richardton');
$city_data[] = array('accid' => 'USND0297', 'name' => 'Riverdale');
$city_data[] = array('accid' => 'USND0298', 'name' => 'Robinson');
$city_data[] = array('accid' => 'USND0299', 'name' => 'Rocklake');
$city_data[] = array('accid' => 'USND0300', 'name' => 'Rogers');
$city_data[] = array('accid' => 'USND0301', 'name' => 'Rolette');
$city_data[] = array('accid' => 'USND0302', 'name' => 'Rolla');
$city_data[] = array('accid' => 'USND0303', 'name' => 'Roseglen');
$city_data[] = array('accid' => 'USND0304', 'name' => 'Ross');
$city_data[] = array('accid' => 'USND0305', 'name' => 'Rugby');
$city_data[] = array('accid' => 'USND0306', 'name' => 'Ruso');
$city_data[] = array('accid' => 'USND0307', 'name' => 'Rutland');
$city_data[] = array('accid' => 'USND0308', 'name' => 'Ryder');
$city_data[] = array('accid' => 'USND0309', 'name' => 'Saint Anthony');
$city_data[] = array('accid' => 'USND0310', 'name' => 'Saint John');
$city_data[] = array('accid' => 'USND0311', 'name' => 'Saint Michael');
$city_data[] = array('accid' => 'USND0312', 'name' => 'Saint Thomas');
$city_data[] = array('accid' => 'USND0313', 'name' => 'Sanborn');
$city_data[] = array('accid' => 'USND0314', 'name' => 'Sarles');
$city_data[] = array('accid' => 'USND0315', 'name' => 'Sawyer');
$city_data[] = array('accid' => 'USND0316', 'name' => 'Scranton');
$city_data[] = array('accid' => 'USND0317', 'name' => 'Selfridge');
$city_data[] = array('accid' => 'USND0318', 'name' => 'Sentinel Butte');
$city_data[] = array('accid' => 'USND0319', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USND0320', 'name' => 'Sheldon');
$city_data[] = array('accid' => 'USND0321', 'name' => 'Sherwood');
$city_data[] = array('accid' => 'USND0322', 'name' => 'Sheyenne');
$city_data[] = array('accid' => 'USND0323', 'name' => 'Shields');
$city_data[] = array('accid' => 'USND0324', 'name' => 'Solen');
$city_data[] = array('accid' => 'USND0325', 'name' => 'Souris');
$city_data[] = array('accid' => 'USND0326', 'name' => 'South Heart');
$city_data[] = array('accid' => 'USND0327', 'name' => 'Spiritwood');
$city_data[] = array('accid' => 'USND0328', 'name' => 'Stanley');
$city_data[] = array('accid' => 'USND0329', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USND0330', 'name' => 'Starkweather');
$city_data[] = array('accid' => 'USND0331', 'name' => 'Steele');
$city_data[] = array('accid' => 'USND0332', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USND0333', 'name' => 'Stirum');
$city_data[] = array('accid' => 'USND0334', 'name' => 'Strasburg');
$city_data[] = array('accid' => 'USND0335', 'name' => 'Streeter');
$city_data[] = array('accid' => 'USND0336', 'name' => 'Surrey');
$city_data[] = array('accid' => 'USND0337', 'name' => 'Sutton');
$city_data[] = array('accid' => 'USND0338', 'name' => 'Sykeston');
$city_data[] = array('accid' => 'USND0339', 'name' => 'Tappen');
$city_data[] = array('accid' => 'USND0340', 'name' => 'Taylor');
$city_data[] = array('accid' => 'USND0341', 'name' => 'Thompson');
$city_data[] = array('accid' => 'USND0342', 'name' => 'Tioga');
$city_data[] = array('accid' => 'USND0343', 'name' => 'Tokio');
$city_data[] = array('accid' => 'USND0344', 'name' => 'Tolley');
$city_data[] = array('accid' => 'USND0345', 'name' => 'Tolna');
$city_data[] = array('accid' => 'USND0346', 'name' => 'Tower City');
$city_data[] = array('accid' => 'USND0347', 'name' => 'Towner');
$city_data[] = array('accid' => 'USND0348', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USND0349', 'name' => 'Turtle Lake');
$city_data[] = array('accid' => 'USND0350', 'name' => 'Tuttle');
$city_data[] = array('accid' => 'USND0351', 'name' => 'Underwood');
$city_data[] = array('accid' => 'USND0352', 'name' => 'Upham');
$city_data[] = array('accid' => 'USND0353', 'name' => 'Valley City');
$city_data[] = array('accid' => 'USND0354', 'name' => 'Velva');
$city_data[] = array('accid' => 'USND0355', 'name' => 'Venturia');
$city_data[] = array('accid' => 'USND0356', 'name' => 'Verona');
$city_data[] = array('accid' => 'USND0357', 'name' => 'Voltaire');
$city_data[] = array('accid' => 'USND0358', 'name' => 'Wahpeton');
$city_data[] = array('accid' => 'USND0359', 'name' => 'Walcott');
$city_data[] = array('accid' => 'USND0360', 'name' => 'Wales');
$city_data[] = array('accid' => 'USND0361', 'name' => 'Walhalla');
$city_data[] = array('accid' => 'USND0363', 'name' => 'Warwick');
$city_data[] = array('accid' => 'USND0364', 'name' => 'Washburn');
$city_data[] = array('accid' => 'USND0365', 'name' => 'Watford City');
$city_data[] = array('accid' => 'USND0366', 'name' => 'Webster');
$city_data[] = array('accid' => 'USND0367', 'name' => 'West Fargo');
$city_data[] = array('accid' => 'USND0368', 'name' => 'Westhope');
$city_data[] = array('accid' => 'USND0369', 'name' => 'Wheatland');
$city_data[] = array('accid' => 'USND0370', 'name' => 'White Earth');
$city_data[] = array('accid' => 'USND0371', 'name' => 'Wildrose');
$city_data[] = array('accid' => 'USND0372', 'name' => 'Williston');
$city_data[] = array('accid' => 'USND0373', 'name' => 'Willow City');
$city_data[] = array('accid' => 'USND0374', 'name' => 'Wilton');
$city_data[] = array('accid' => 'USND0375', 'name' => 'Wimbledon');
$city_data[] = array('accid' => 'USND0376', 'name' => 'Wing');
$city_data[] = array('accid' => 'USND0377', 'name' => 'Wishek');
$city_data[] = array('accid' => 'USND0378', 'name' => 'Wolford');
$city_data[] = array('accid' => 'USND0379', 'name' => 'Woodworth');
$city_data[] = array('accid' => 'USND0380', 'name' => 'Wyndmere');
$city_data[] = array('accid' => 'USND0381', 'name' => 'York');
$city_data[] = array('accid' => 'USND0382', 'name' => 'Ypsilanti');
$city_data[] = array('accid' => 'USND0383', 'name' => 'Zahl');
$city_data[] = array('accid' => 'USND0384', 'name' => 'Zap');
$city_data[] = array('accid' => 'USND0385', 'name' => 'Zeeland');

?>
