<?php

// City package for USA: Nebraska 

$city_name = 'USA: Nebraska';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USNE0001', 'name' => 'Abie');
$city_data[] = array('accid' => 'USNE0002', 'name' => 'Adams');
$city_data[] = array('accid' => 'USNE0003', 'name' => 'Ainsworth');
$city_data[] = array('accid' => 'USNE0004', 'name' => 'Albion');
$city_data[] = array('accid' => 'USNE0005', 'name' => 'Alda');
$city_data[] = array('accid' => 'USNE0006', 'name' => 'Alexandria');
$city_data[] = array('accid' => 'USNE0007', 'name' => 'Allen');
$city_data[] = array('accid' => 'USNE0008', 'name' => 'Alliance');
$city_data[] = array('accid' => 'USNE0009', 'name' => 'Alma');
$city_data[] = array('accid' => 'USNE0010', 'name' => 'Alvo');
$city_data[] = array('accid' => 'USNE0011', 'name' => 'Amelia');
$city_data[] = array('accid' => 'USNE0012', 'name' => 'Ames');
$city_data[] = array('accid' => 'USNE0013', 'name' => 'Amherst');
$city_data[] = array('accid' => 'USNE0014', 'name' => 'Angora');
$city_data[] = array('accid' => 'USNE0015', 'name' => 'Anselmo');
$city_data[] = array('accid' => 'USNE0016', 'name' => 'Ansley');
$city_data[] = array('accid' => 'USNE0017', 'name' => 'Arapahoe');
$city_data[] = array('accid' => 'USNE0018', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USNE0019', 'name' => 'Archer');
$city_data[] = array('accid' => 'USNE0020', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USNE0021', 'name' => 'Arnold');
$city_data[] = array('accid' => 'USNE0022', 'name' => 'Arthur');
$city_data[] = array('accid' => 'USNE0023', 'name' => 'Ashby');
$city_data[] = array('accid' => 'USNE0024', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USNE0025', 'name' => 'Ashton');
$city_data[] = array('accid' => 'USNE0026', 'name' => 'Atkinson');
$city_data[] = array('accid' => 'USNE0027', 'name' => 'Atlanta');
$city_data[] = array('accid' => 'USNE0028', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USNE0029', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USNE0030', 'name' => 'Avoca');
$city_data[] = array('accid' => 'USNE0031', 'name' => 'Axtell');
$city_data[] = array('accid' => 'USNE0032', 'name' => 'Ayr');
$city_data[] = array('accid' => 'USNE0033', 'name' => 'Bancroft');
$city_data[] = array('accid' => 'USNE0034', 'name' => 'Barneston');
$city_data[] = array('accid' => 'USNE0035', 'name' => 'Bartlett');
$city_data[] = array('accid' => 'USNE0036', 'name' => 'Bartley');
$city_data[] = array('accid' => 'USNE0037', 'name' => 'Bassett');
$city_data[] = array('accid' => 'USNE0038', 'name' => 'Battle Creek');
$city_data[] = array('accid' => 'USNE0039', 'name' => 'Bayard');
$city_data[] = array('accid' => 'USNE0040', 'name' => 'Beatrice');
$city_data[] = array('accid' => 'USNE0041', 'name' => 'Beaver City');
$city_data[] = array('accid' => 'USNE0042', 'name' => 'Beaver Crossing');
$city_data[] = array('accid' => 'USNE0043', 'name' => 'Bee');
$city_data[] = array('accid' => 'USNE0044', 'name' => 'Beemer');
$city_data[] = array('accid' => 'USNE0045', 'name' => 'Belden');
$city_data[] = array('accid' => 'USNE0046', 'name' => 'Belgrade');
$city_data[] = array('accid' => 'USNE0047', 'name' => 'Bellevue');
$city_data[] = array('accid' => 'USNE0048', 'name' => 'Bellwood');
$city_data[] = array('accid' => 'USNE0049', 'name' => 'Belvidere');
$city_data[] = array('accid' => 'USNE0050', 'name' => 'Benedict');
$city_data[] = array('accid' => 'USNE0051', 'name' => 'Benkelman');
$city_data[] = array('accid' => 'USNE0052', 'name' => 'Bennet');
$city_data[] = array('accid' => 'USNE0053', 'name' => 'Bennington');
$city_data[] = array('accid' => 'USNE0054', 'name' => 'Bertrand');
$city_data[] = array('accid' => 'USNE0055', 'name' => 'Berwyn');
$city_data[] = array('accid' => 'USNE0056', 'name' => 'Big Springs');
$city_data[] = array('accid' => 'USNE0057', 'name' => 'Bingham');
$city_data[] = array('accid' => 'USNE0058', 'name' => 'Bladen');
$city_data[] = array('accid' => 'USNE0059', 'name' => 'Blair');
$city_data[] = array('accid' => 'USNE0060', 'name' => 'Bloomfield');
$city_data[] = array('accid' => 'USNE0061', 'name' => 'Bloomington');
$city_data[] = array('accid' => 'USNE0062', 'name' => 'Blue Hill');
$city_data[] = array('accid' => 'USNE0063', 'name' => 'Blue Springs');
$city_data[] = array('accid' => 'USNE0064', 'name' => 'Boelus');
$city_data[] = array('accid' => 'USNE0065', 'name' => 'Boys Town');
$city_data[] = array('accid' => 'USNE0066', 'name' => 'Bradshaw');
$city_data[] = array('accid' => 'USNE0067', 'name' => 'Brady');
$city_data[] = array('accid' => 'USNE0068', 'name' => 'Brainard');
$city_data[] = array('accid' => 'USNE0069', 'name' => 'Brewster');
$city_data[] = array('accid' => 'USNE0070', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USNE0071', 'name' => 'Bristow');
$city_data[] = array('accid' => 'USNE0072', 'name' => 'Broadwater');
$city_data[] = array('accid' => 'USNE0073', 'name' => 'Brock');
$city_data[] = array('accid' => 'USNE0074', 'name' => 'Broken Bow');
$city_data[] = array('accid' => 'USNE0075', 'name' => 'Brownville');
$city_data[] = array('accid' => 'USNE0076', 'name' => 'Brule');
$city_data[] = array('accid' => 'USNE0077', 'name' => 'Bruning');
$city_data[] = array('accid' => 'USNE0078', 'name' => 'Bruno');
$city_data[] = array('accid' => 'USNE0079', 'name' => 'Brunswick');
$city_data[] = array('accid' => 'USNE0080', 'name' => 'Burchard');
$city_data[] = array('accid' => 'USNE0081', 'name' => 'Burr');
$city_data[] = array('accid' => 'USNE0082', 'name' => 'Burwell');
$city_data[] = array('accid' => 'USNE0083', 'name' => 'Bushnell');
$city_data[] = array('accid' => 'USNE0084', 'name' => 'Butte');
$city_data[] = array('accid' => 'USNE0085', 'name' => 'Byron');
$city_data[] = array('accid' => 'USNE0086', 'name' => 'Cairo');
$city_data[] = array('accid' => 'USNE0087', 'name' => 'Callaway');
$city_data[] = array('accid' => 'USNE0088', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'USNE0089', 'name' => 'Campbell');
$city_data[] = array('accid' => 'USNE0090', 'name' => 'Carleton');
$city_data[] = array('accid' => 'USNE0091', 'name' => 'Carroll');
$city_data[] = array('accid' => 'USNE0092', 'name' => 'Cedar Bluffs');
$city_data[] = array('accid' => 'USNE0093', 'name' => 'Cedar Creek');
$city_data[] = array('accid' => 'USNE0094', 'name' => 'Cedar Rapids');
$city_data[] = array('accid' => 'USNE0095', 'name' => 'Center');
$city_data[] = array('accid' => 'USNE0096', 'name' => 'Central City');
$city_data[] = array('accid' => 'USNE0097', 'name' => 'Ceresco');
$city_data[] = array('accid' => 'USNE0098', 'name' => 'Chadron');
$city_data[] = array('accid' => 'USNE0099', 'name' => 'Chambers');
$city_data[] = array('accid' => 'USNE0100', 'name' => 'Champion');
$city_data[] = array('accid' => 'USNE0101', 'name' => 'Chapman');
$city_data[] = array('accid' => 'USNE0102', 'name' => 'Chappell');
$city_data[] = array('accid' => 'USNE0103', 'name' => 'Chester');
$city_data[] = array('accid' => 'USNE0104', 'name' => 'Clarks');
$city_data[] = array('accid' => 'USNE0105', 'name' => 'Clarkson');
$city_data[] = array('accid' => 'USNE0106', 'name' => 'Clatonia');
$city_data[] = array('accid' => 'USNE0107', 'name' => 'Clay Center');
$city_data[] = array('accid' => 'USNE0108', 'name' => 'Clearwater');
$city_data[] = array('accid' => 'USNE0109', 'name' => 'Cody');
$city_data[] = array('accid' => 'USNE0110', 'name' => 'Coleridge');
$city_data[] = array('accid' => 'USNE0111', 'name' => 'Colon');
$city_data[] = array('accid' => 'USNE0112', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USNE0113', 'name' => 'Comstock');
$city_data[] = array('accid' => 'USNE0114', 'name' => 'Concord');
$city_data[] = array('accid' => 'USNE0115', 'name' => 'Cook');
$city_data[] = array('accid' => 'USNE0116', 'name' => 'Cordova');
$city_data[] = array('accid' => 'USNE0117', 'name' => 'Cortland');
$city_data[] = array('accid' => 'USNE0118', 'name' => 'Cozad');
$city_data[] = array('accid' => 'USNE0119', 'name' => 'Crab Orchard');
$city_data[] = array('accid' => 'USNE0120', 'name' => 'Craig');
$city_data[] = array('accid' => 'USNE0121', 'name' => 'Crawford');
$city_data[] = array('accid' => 'USNE0122', 'name' => 'Creighton');
$city_data[] = array('accid' => 'USNE0123', 'name' => 'Creston');
$city_data[] = array('accid' => 'USNE0124', 'name' => 'Crete');
$city_data[] = array('accid' => 'USNE0125', 'name' => 'Crofton');
$city_data[] = array('accid' => 'USNE0126', 'name' => 'Crookston');
$city_data[] = array('accid' => 'USNE0127', 'name' => 'Culbertson');
$city_data[] = array('accid' => 'USNE0128', 'name' => 'Curtis');
$city_data[] = array('accid' => 'USNE0129', 'name' => 'Dakota City');
$city_data[] = array('accid' => 'USNE0130', 'name' => 'Dalton');
$city_data[] = array('accid' => 'USNE0131', 'name' => 'Danbury');
$city_data[] = array('accid' => 'USNE0132', 'name' => 'Dannebrog');
$city_data[] = array('accid' => 'USNE0133', 'name' => 'Davenport');
$city_data[] = array('accid' => 'USNE0134', 'name' => 'Davey');
$city_data[] = array('accid' => 'USNE0135', 'name' => 'David City');
$city_data[] = array('accid' => 'USNE0136', 'name' => 'Dawson');
$city_data[] = array('accid' => 'USNE0137', 'name' => 'Daykin');
$city_data[] = array('accid' => 'USNE0138', 'name' => 'De Witt');
$city_data[] = array('accid' => 'USNE0139', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USNE0140', 'name' => 'Denton');
$city_data[] = array('accid' => 'USNE0141', 'name' => 'Deshler');
$city_data[] = array('accid' => 'USNE0142', 'name' => 'Deweese');
$city_data[] = array('accid' => 'USNE0143', 'name' => 'Dickens');
$city_data[] = array('accid' => 'USNE0144', 'name' => 'Diller');
$city_data[] = array('accid' => 'USNE0145', 'name' => 'Dix');
$city_data[] = array('accid' => 'USNE0146', 'name' => 'Dixon');
$city_data[] = array('accid' => 'USNE0147', 'name' => 'Dodge');
$city_data[] = array('accid' => 'USNE0148', 'name' => 'Doniphan');
$city_data[] = array('accid' => 'USNE0149', 'name' => 'Dorchester');
$city_data[] = array('accid' => 'USNE0150', 'name' => 'Douglas');
$city_data[] = array('accid' => 'USNE0151', 'name' => 'Du Bois');
$city_data[] = array('accid' => 'USNE0152', 'name' => 'Dunbar');
$city_data[] = array('accid' => 'USNE0153', 'name' => 'Duncan');
$city_data[] = array('accid' => 'USNE0154', 'name' => 'Dunning');
$city_data[] = array('accid' => 'USNE0155', 'name' => 'Dwight');
$city_data[] = array('accid' => 'USNE0156', 'name' => 'Eagle');
$city_data[] = array('accid' => 'USNE0157', 'name' => 'Eddyville');
$city_data[] = array('accid' => 'USNE0158', 'name' => 'Edgar');
$city_data[] = array('accid' => 'USNE0159', 'name' => 'Edison');
$city_data[] = array('accid' => 'USNE0160', 'name' => 'Elba');
$city_data[] = array('accid' => 'USNE0161', 'name' => 'Elgin');
$city_data[] = array('accid' => 'USNE0162', 'name' => 'Elk Creek');
$city_data[] = array('accid' => 'USNE0163', 'name' => 'Elkhorn');
$city_data[] = array('accid' => 'USNE0164', 'name' => 'Ellsworth');
$city_data[] = array('accid' => 'USNE0165', 'name' => 'Elm Creek');
$city_data[] = array('accid' => 'USNE0166', 'name' => 'Elmwood');
$city_data[] = array('accid' => 'USNE0167', 'name' => 'Elsie');
$city_data[] = array('accid' => 'USNE0168', 'name' => 'Elsmere');
$city_data[] = array('accid' => 'USNE0169', 'name' => 'Elwood');
$city_data[] = array('accid' => 'USNE0170', 'name' => 'Elyria');
$city_data[] = array('accid' => 'USNE0171', 'name' => 'Emerson');
$city_data[] = array('accid' => 'USNE0172', 'name' => 'Emmet');
$city_data[] = array('accid' => 'USNE0173', 'name' => 'Enders');
$city_data[] = array('accid' => 'USNE0174', 'name' => 'Endicott');
$city_data[] = array('accid' => 'USNE0175', 'name' => 'Ericson');
$city_data[] = array('accid' => 'USNE0176', 'name' => 'Eustis');
$city_data[] = array('accid' => 'USNE0177', 'name' => 'Ewing');
$city_data[] = array('accid' => 'USNE0178', 'name' => 'Exeter');
$city_data[] = array('accid' => 'USNE0179', 'name' => 'Fairbury');
$city_data[] = array('accid' => 'USNE0180', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USNE0181', 'name' => 'Fairmont');
$city_data[] = array('accid' => 'USNE0182', 'name' => 'Falls City');
$city_data[] = array('accid' => 'USNE0183', 'name' => 'Farnam');
$city_data[] = array('accid' => 'USNE0184', 'name' => 'Farwell');
$city_data[] = array('accid' => 'USNE0185', 'name' => 'Filley');
$city_data[] = array('accid' => 'USNE0186', 'name' => 'Firth');
$city_data[] = array('accid' => 'USNE0187', 'name' => 'Fordyce');
$city_data[] = array('accid' => 'USNE0188', 'name' => 'Fort Calhoun');
$city_data[] = array('accid' => 'USNE0189', 'name' => 'Foster');
$city_data[] = array('accid' => 'USNE0190', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USNE0191', 'name' => 'Fremont');
$city_data[] = array('accid' => 'USNE0192', 'name' => 'Friend');
$city_data[] = array('accid' => 'USNE0193', 'name' => 'Fullerton');
$city_data[] = array('accid' => 'USNE0194', 'name' => 'Funk');
$city_data[] = array('accid' => 'USNE0195', 'name' => 'Garland');
$city_data[] = array('accid' => 'USNE0196', 'name' => 'Geneva');
$city_data[] = array('accid' => 'USNE0197', 'name' => 'Genoa');
$city_data[] = array('accid' => 'USNE0198', 'name' => 'Gering');
$city_data[] = array('accid' => 'USNE0199', 'name' => 'Gibbon');
$city_data[] = array('accid' => 'USNE0200', 'name' => 'Gilead');
$city_data[] = array('accid' => 'USNE0201', 'name' => 'Giltner');
$city_data[] = array('accid' => 'USNE0202', 'name' => 'Glenvil');
$city_data[] = array('accid' => 'USNE0203', 'name' => 'Goehner');
$city_data[] = array('accid' => 'USNE0204', 'name' => 'Gordon');
$city_data[] = array('accid' => 'USNE0205', 'name' => 'Gothenburg');
$city_data[] = array('accid' => 'USNE0206', 'name' => 'Grafton');
$city_data[] = array('accid' => 'USNE0207', 'name' => 'Grand Island');
$city_data[] = array('accid' => 'USNE0208', 'name' => 'Grant');
$city_data[] = array('accid' => 'USNE0209', 'name' => 'Greeley');
$city_data[] = array('accid' => 'USNE0210', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USNE0211', 'name' => 'Gresham');
$city_data[] = array('accid' => 'USNE0212', 'name' => 'Gretna');
$city_data[] = array('accid' => 'USNE0213', 'name' => 'Guide Rock');
$city_data[] = array('accid' => 'USNE0214', 'name' => 'Gurley');
$city_data[] = array('accid' => 'USNE0215', 'name' => 'Hadar');
$city_data[] = array('accid' => 'USNE0216', 'name' => 'Haigler');
$city_data[] = array('accid' => 'USNE0217', 'name' => 'Hallam');
$city_data[] = array('accid' => 'USNE0218', 'name' => 'Halsey');
$city_data[] = array('accid' => 'USNE0219', 'name' => 'Hamlet');
$city_data[] = array('accid' => 'USNE0220', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USNE0221', 'name' => 'Hardy');
$city_data[] = array('accid' => 'USNE0222', 'name' => 'Harrisburg');
$city_data[] = array('accid' => 'USNE0223', 'name' => 'Harrison');
$city_data[] = array('accid' => 'USNE0224', 'name' => 'Hartington');
$city_data[] = array('accid' => 'USNE0225', 'name' => 'Harvard');
$city_data[] = array('accid' => 'USNE0226', 'name' => 'Hastings');
$city_data[] = array('accid' => 'USNE0227', 'name' => 'Hay Springs');
$city_data[] = array('accid' => 'USNE0228', 'name' => 'Hayes Center');
$city_data[] = array('accid' => 'USNE0229', 'name' => 'Hazard');
$city_data[] = array('accid' => 'USNE0230', 'name' => 'Heartwell');
$city_data[] = array('accid' => 'USNE0231', 'name' => 'Hebron');
$city_data[] = array('accid' => 'USNE0232', 'name' => 'Hemingford');
$city_data[] = array('accid' => 'USNE0233', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USNE0234', 'name' => 'Hendley');
$city_data[] = array('accid' => 'USNE0235', 'name' => 'Henry');
$city_data[] = array('accid' => 'USNE0236', 'name' => 'Herman');
$city_data[] = array('accid' => 'USNE0237', 'name' => 'Hershey');
$city_data[] = array('accid' => 'USNE0238', 'name' => 'Hickman');
$city_data[] = array('accid' => 'USNE0239', 'name' => 'Hildreth');
$city_data[] = array('accid' => 'USNE0240', 'name' => 'Holbrook');
$city_data[] = array('accid' => 'USNE0241', 'name' => 'Holdrege');
$city_data[] = array('accid' => 'USNE0242', 'name' => 'Holmesville');
$city_data[] = array('accid' => 'USNE0243', 'name' => 'Holstein');
$city_data[] = array('accid' => 'USNE0244', 'name' => 'Homer');
$city_data[] = array('accid' => 'USNE0245', 'name' => 'Hooper');
$city_data[] = array('accid' => 'USNE0246', 'name' => 'Hordville');
$city_data[] = array('accid' => 'USNE0247', 'name' => 'Hoskins');
$city_data[] = array('accid' => 'USNE0248', 'name' => 'Howells');
$city_data[] = array('accid' => 'USNE0249', 'name' => 'Hubbard');
$city_data[] = array('accid' => 'USNE0250', 'name' => 'Hubbell');
$city_data[] = array('accid' => 'USNE0251', 'name' => 'Humboldt');
$city_data[] = array('accid' => 'USNE0252', 'name' => 'Humphrey');
$city_data[] = array('accid' => 'USNE0253', 'name' => 'Hyannis');
$city_data[] = array('accid' => 'USNE0254', 'name' => 'Imperial');
$city_data[] = array('accid' => 'USNE0255', 'name' => 'Inavale');
$city_data[] = array('accid' => 'USNE0256', 'name' => 'Indianola');
$city_data[] = array('accid' => 'USNE0257', 'name' => 'Inland');
$city_data[] = array('accid' => 'USNE0258', 'name' => 'Inman');
$city_data[] = array('accid' => 'USNE0259', 'name' => 'Ithaca');
$city_data[] = array('accid' => 'USNE0260', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USNE0261', 'name' => 'Jansen');
$city_data[] = array('accid' => 'USNE0262', 'name' => 'Johnson');
$city_data[] = array('accid' => 'USNE0263', 'name' => 'Johnstown');
$city_data[] = array('accid' => 'USNE0264', 'name' => 'Juniata');
$city_data[] = array('accid' => 'USNE0265', 'name' => 'Kearney');
$city_data[] = array('accid' => 'USNE0266', 'name' => 'Kenesaw');
$city_data[] = array('accid' => 'USNE0267', 'name' => 'Kennard');
$city_data[] = array('accid' => 'USNE0268', 'name' => 'Keystone');
$city_data[] = array('accid' => 'USNE0269', 'name' => 'Kilgore');
$city_data[] = array('accid' => 'USNE0270', 'name' => 'Kimball');
$city_data[] = array('accid' => 'USNE0271', 'name' => 'La Vista');
$city_data[] = array('accid' => 'USNE0272', 'name' => 'Lakeside');
$city_data[] = array('accid' => 'USNE0273', 'name' => 'Laurel');
$city_data[] = array('accid' => 'USNE0274', 'name' => 'Lawrence');
$city_data[] = array('accid' => 'USNE0275', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USNE0276', 'name' => 'Leigh');
$city_data[] = array('accid' => 'USNE0277', 'name' => 'Lemoyne');
$city_data[] = array('accid' => 'USNE0278', 'name' => 'Leshara');
$city_data[] = array('accid' => 'USNE0279', 'name' => 'Lewellen');
$city_data[] = array('accid' => 'USNE0280', 'name' => 'Lewiston');
$city_data[] = array('accid' => 'USNE0281', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USNE0282', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USNE0283', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USNE0284', 'name' => 'Lindsay');
$city_data[] = array('accid' => 'USNE0285', 'name' => 'Linwood');
$city_data[] = array('accid' => 'USNE0286', 'name' => 'Lisco');
$city_data[] = array('accid' => 'USNE0287', 'name' => 'Litchfield');
$city_data[] = array('accid' => 'USNE0288', 'name' => 'Lodgepole');
$city_data[] = array('accid' => 'USNE0289', 'name' => 'Long Pine');
$city_data[] = array('accid' => 'USNE0290', 'name' => 'Loomis');
$city_data[] = array('accid' => 'USNE0291', 'name' => 'Lorton');
$city_data[] = array('accid' => 'USNE0292', 'name' => 'Louisville');
$city_data[] = array('accid' => 'USNE0293', 'name' => 'Loup City');
$city_data[] = array('accid' => 'USNE0294', 'name' => 'Lyman');
$city_data[] = array('accid' => 'USNE0295', 'name' => 'Lynch');
$city_data[] = array('accid' => 'USNE0296', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USNE0297', 'name' => 'Macy');
$city_data[] = array('accid' => 'USNE0298', 'name' => 'Madison');
$city_data[] = array('accid' => 'USNE0299', 'name' => 'Madrid');
$city_data[] = array('accid' => 'USNE0300', 'name' => 'Magnet');
$city_data[] = array('accid' => 'USNE0301', 'name' => 'Malcolm');
$city_data[] = array('accid' => 'USNE0302', 'name' => 'Malmo');
$city_data[] = array('accid' => 'USNE0303', 'name' => 'Manley');
$city_data[] = array('accid' => 'USNE0304', 'name' => 'Marquette');
$city_data[] = array('accid' => 'USNE0305', 'name' => 'Marsland');
$city_data[] = array('accid' => 'USNE0306', 'name' => 'Martell');
$city_data[] = array('accid' => 'USNE0307', 'name' => 'Maskell');
$city_data[] = array('accid' => 'USNE0308', 'name' => 'Mason City');
$city_data[] = array('accid' => 'USNE0309', 'name' => 'Max');
$city_data[] = array('accid' => 'USNE0310', 'name' => 'Maxwell');
$city_data[] = array('accid' => 'USNE0311', 'name' => 'Maywood');
$city_data[] = array('accid' => 'USNE0312', 'name' => 'McCook');
$city_data[] = array('accid' => 'USNE0313', 'name' => 'McCool Junction');
$city_data[] = array('accid' => 'USNE0314', 'name' => 'McGrew');
$city_data[] = array('accid' => 'USNE0315', 'name' => 'McLean');
$city_data[] = array('accid' => 'USNE0316', 'name' => 'Mead');
$city_data[] = array('accid' => 'USNE0317', 'name' => 'Meadow Grove');
$city_data[] = array('accid' => 'USNE0318', 'name' => 'Melbeta');
$city_data[] = array('accid' => 'USNE0319', 'name' => 'Memphis');
$city_data[] = array('accid' => 'USNE0320', 'name' => 'Merna');
$city_data[] = array('accid' => 'USNE0321', 'name' => 'Merriman');
$city_data[] = array('accid' => 'USNE0322', 'name' => 'Milford');
$city_data[] = array('accid' => 'USNE0323', 'name' => 'Miller');
$city_data[] = array('accid' => 'USNE0324', 'name' => 'Milligan');
$city_data[] = array('accid' => 'USNE0325', 'name' => 'Mills');
$city_data[] = array('accid' => 'USNE0326', 'name' => 'Minatare');
$city_data[] = array('accid' => 'USNE0327', 'name' => 'Minden');
$city_data[] = array('accid' => 'USNE0328', 'name' => 'Mitchell');
$city_data[] = array('accid' => 'USNE0329', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USNE0330', 'name' => 'Moorefield');
$city_data[] = array('accid' => 'USNE0331', 'name' => 'Morrill');
$city_data[] = array('accid' => 'USNE0332', 'name' => 'Morse Bluff');
$city_data[] = array('accid' => 'USNE0333', 'name' => 'Mullen');
$city_data[] = array('accid' => 'USNE0334', 'name' => 'Murdock');
$city_data[] = array('accid' => 'USNE0335', 'name' => 'Murray');
$city_data[] = array('accid' => 'USNE0336', 'name' => 'Naper');
$city_data[] = array('accid' => 'USNE0337', 'name' => 'Naponee');
$city_data[] = array('accid' => 'USNE0338', 'name' => 'Nebraska City');
$city_data[] = array('accid' => 'USNE0339', 'name' => 'Nehawka');
$city_data[] = array('accid' => 'USNE0340', 'name' => 'Neligh');
$city_data[] = array('accid' => 'USNE0341', 'name' => 'Nelson');
$city_data[] = array('accid' => 'USNE0342', 'name' => 'Nemaha');
$city_data[] = array('accid' => 'USNE0343', 'name' => 'Nenzel');
$city_data[] = array('accid' => 'USNE0344', 'name' => 'Newcastle');
$city_data[] = array('accid' => 'USNE0345', 'name' => 'Newman Grove');
$city_data[] = array('accid' => 'USNE0346', 'name' => 'Newport');
$city_data[] = array('accid' => 'USNE0347', 'name' => 'Nickerson');
$city_data[] = array('accid' => 'USNE0348', 'name' => 'Niobrara');
$city_data[] = array('accid' => 'USNE0349', 'name' => 'Norfolk');
$city_data[] = array('accid' => 'USNE0350', 'name' => 'Norman');
$city_data[] = array('accid' => 'USNE0351', 'name' => 'North Bend');
$city_data[] = array('accid' => 'USNE0352', 'name' => 'North Loup');
$city_data[] = array('accid' => 'USNE0353', 'name' => 'North Platte');
$city_data[] = array('accid' => 'USNE0354', 'name' => 'Oak');
$city_data[] = array('accid' => 'USNE0355', 'name' => 'Oakdale');
$city_data[] = array('accid' => 'USNE0356', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USNE0357', 'name' => 'Oconto');
$city_data[] = array('accid' => 'USNE0358', 'name' => 'Odell');
$city_data[] = array('accid' => 'USNE0359', 'name' => 'Odessa');
$city_data[] = array('accid' => 'USNE0360', 'name' => 'Offutt AFB');
$city_data[] = array('accid' => 'USNE0361', 'name' => 'Ogallala');
$city_data[] = array('accid' => 'USNE0362', 'name' => 'Ohiowa');
$city_data[] = array('accid' => 'USNE0363', 'name' => 'Omaha');
$city_data[] = array('accid' => 'USNE0364', 'name' => 'Omaha$city_data[]Offutt AFB');
$city_data[] = array('accid' => 'USNE0365', 'name' => 'Oneill');
$city_data[] = array('accid' => 'USNE0367', 'name' => 'Ong');
$city_data[] = array('accid' => 'USNE0368', 'name' => 'Orchard');
$city_data[] = array('accid' => 'USNE0369', 'name' => 'Ord');
$city_data[] = array('accid' => 'USNE0370', 'name' => 'Orleans');
$city_data[] = array('accid' => 'USNE0371', 'name' => 'Osceola');
$city_data[] = array('accid' => 'USNE0372', 'name' => 'Oshkosh');
$city_data[] = array('accid' => 'USNE0373', 'name' => 'Osmond');
$city_data[] = array('accid' => 'USNE0374', 'name' => 'Otoe');
$city_data[] = array('accid' => 'USNE0375', 'name' => 'Overton');
$city_data[] = array('accid' => 'USNE0376', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USNE0377', 'name' => 'Page');
$city_data[] = array('accid' => 'USNE0378', 'name' => 'Palisade');
$city_data[] = array('accid' => 'USNE0379', 'name' => 'Palmer');
$city_data[] = array('accid' => 'USNE0380', 'name' => 'Palmyra');
$city_data[] = array('accid' => 'USNE0381', 'name' => 'Panama');
$city_data[] = array('accid' => 'USNE0382', 'name' => 'Papillion');
$city_data[] = array('accid' => 'USNE0383', 'name' => 'Parks');
$city_data[] = array('accid' => 'USNE0384', 'name' => 'Pawnee City');
$city_data[] = array('accid' => 'USNE0385', 'name' => 'Paxton');
$city_data[] = array('accid' => 'USNE0386', 'name' => 'Pender');
$city_data[] = array('accid' => 'USNE0387', 'name' => 'Peru');
$city_data[] = array('accid' => 'USNE0388', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USNE0389', 'name' => 'Phillips');
$city_data[] = array('accid' => 'USNE0390', 'name' => 'Pickrell');
$city_data[] = array('accid' => 'USNE0391', 'name' => 'Pierce');
$city_data[] = array('accid' => 'USNE0392', 'name' => 'Pilger');
$city_data[] = array('accid' => 'USNE0393', 'name' => 'Plainview');
$city_data[] = array('accid' => 'USNE0394', 'name' => 'Platte Center');
$city_data[] = array('accid' => 'USNE0395', 'name' => 'Plattsmouth');
$city_data[] = array('accid' => 'USNE0396', 'name' => 'Pleasant Dale');
$city_data[] = array('accid' => 'USNE0397', 'name' => 'Pleasanton');
$city_data[] = array('accid' => 'USNE0398', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USNE0399', 'name' => 'Polk');
$city_data[] = array('accid' => 'USNE0400', 'name' => 'Ponca');
$city_data[] = array('accid' => 'USNE0401', 'name' => 'Potter');
$city_data[] = array('accid' => 'USNE0402', 'name' => 'Prague');
$city_data[] = array('accid' => 'USNE0403', 'name' => 'Primrose');
$city_data[] = array('accid' => 'USNE0404', 'name' => 'Purdum');
$city_data[] = array('accid' => 'USNE0405', 'name' => 'Ragan');
$city_data[] = array('accid' => 'USNE0406', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USNE0407', 'name' => 'Ravenna');
$city_data[] = array('accid' => 'USNE0408', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USNE0409', 'name' => 'Red Cloud');
$city_data[] = array('accid' => 'USNE0410', 'name' => 'Republican City');
$city_data[] = array('accid' => 'USNE0411', 'name' => 'Reynolds');
$city_data[] = array('accid' => 'USNE0412', 'name' => 'Richfield');
$city_data[] = array('accid' => 'USNE0413', 'name' => 'Rising City');
$city_data[] = array('accid' => 'USNE0414', 'name' => 'Riverdale');
$city_data[] = array('accid' => 'USNE0415', 'name' => 'Riverton');
$city_data[] = array('accid' => 'USNE0416', 'name' => 'Roca');
$city_data[] = array('accid' => 'USNE0417', 'name' => 'Rockville');
$city_data[] = array('accid' => 'USNE0418', 'name' => 'Rogers');
$city_data[] = array('accid' => 'USNE0419', 'name' => 'Rosalie');
$city_data[] = array('accid' => 'USNE0420', 'name' => 'Rose');
$city_data[] = array('accid' => 'USNE0421', 'name' => 'Roseland');
$city_data[] = array('accid' => 'USNE0422', 'name' => 'Royal');
$city_data[] = array('accid' => 'USNE0423', 'name' => 'Rulo');
$city_data[] = array('accid' => 'USNE0424', 'name' => 'Rushville');
$city_data[] = array('accid' => 'USNE0425', 'name' => 'Ruskin');
$city_data[] = array('accid' => 'USNE0427', 'name' => 'Saint Edward');
$city_data[] = array('accid' => 'USNE0428', 'name' => 'Saint Helena');
$city_data[] = array('accid' => 'USNE0429', 'name' => 'Saint Libory');
$city_data[] = array('accid' => 'USNE0430', 'name' => 'Saint Paul');
$city_data[] = array('accid' => 'USNE0431', 'name' => 'Salem');
$city_data[] = array('accid' => 'USNE0432', 'name' => 'Sargent');
$city_data[] = array('accid' => 'USNE0433', 'name' => 'Saronville');
$city_data[] = array('accid' => 'USNE0434', 'name' => 'Schuyler');
$city_data[] = array('accid' => 'USNE0435', 'name' => 'Scotia');
$city_data[] = array('accid' => 'USNE0436', 'name' => 'Scottsbluff');
$city_data[] = array('accid' => 'USNE0437', 'name' => 'Scribner');
$city_data[] = array('accid' => 'USNE0438', 'name' => 'Seneca');
$city_data[] = array('accid' => 'USNE0439', 'name' => 'Seward');
$city_data[] = array('accid' => 'USNE0440', 'name' => 'Shelby');
$city_data[] = array('accid' => 'USNE0441', 'name' => 'Shelton');
$city_data[] = array('accid' => 'USNE0442', 'name' => 'Shickley');
$city_data[] = array('accid' => 'USNE0443', 'name' => 'Shubert');
$city_data[] = array('accid' => 'USNE0444', 'name' => 'Sidney');
$city_data[] = array('accid' => 'USNE0445', 'name' => 'Silver Creek');
$city_data[] = array('accid' => 'USNE0446', 'name' => 'Smithfield');
$city_data[] = array('accid' => 'USNE0447', 'name' => 'Snyder');
$city_data[] = array('accid' => 'USNE0448', 'name' => 'South Bend');
$city_data[] = array('accid' => 'USNE0449', 'name' => 'South Sioux City');
$city_data[] = array('accid' => 'USNE0450', 'name' => 'Spalding');
$city_data[] = array('accid' => 'USNE0451', 'name' => 'Sparks');
$city_data[] = array('accid' => 'USNE0452', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USNE0453', 'name' => 'Sprague');
$city_data[] = array('accid' => 'USNE0454', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USNE0455', 'name' => 'Springview');
$city_data[] = array('accid' => 'USNE0456', 'name' => 'Stamford');
$city_data[] = array('accid' => 'USNE0457', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USNE0458', 'name' => 'Staplehurst');
$city_data[] = array('accid' => 'USNE0459', 'name' => 'Stapleton');
$city_data[] = array('accid' => 'USNE0460', 'name' => 'Steele City');
$city_data[] = array('accid' => 'USNE0461', 'name' => 'Steinauer');
$city_data[] = array('accid' => 'USNE0462', 'name' => 'Stella');
$city_data[] = array('accid' => 'USNE0463', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USNE0464', 'name' => 'Stockville');
$city_data[] = array('accid' => 'USNE0465', 'name' => 'Strang');
$city_data[] = array('accid' => 'USNE0466', 'name' => 'Stratton');
$city_data[] = array('accid' => 'USNE0467', 'name' => 'Stromsburg');
$city_data[] = array('accid' => 'USNE0468', 'name' => 'Stuart');
$city_data[] = array('accid' => 'USNE0469', 'name' => 'Sumner');
$city_data[] = array('accid' => 'USNE0470', 'name' => 'Superior');
$city_data[] = array('accid' => 'USNE0471', 'name' => 'Surprise');
$city_data[] = array('accid' => 'USNE0472', 'name' => 'Sutherland');
$city_data[] = array('accid' => 'USNE0473', 'name' => 'Sutton');
$city_data[] = array('accid' => 'USNE0474', 'name' => 'Swanton');
$city_data[] = array('accid' => 'USNE0475', 'name' => 'Syracuse');
$city_data[] = array('accid' => 'USNE0476', 'name' => 'Table Rock');
$city_data[] = array('accid' => 'USNE0477', 'name' => 'Talmage');
$city_data[] = array('accid' => 'USNE0478', 'name' => 'Taylor');
$city_data[] = array('accid' => 'USNE0479', 'name' => 'Tecumseh');
$city_data[] = array('accid' => 'USNE0480', 'name' => 'Tekamah');
$city_data[] = array('accid' => 'USNE0481', 'name' => 'Thedford');
$city_data[] = array('accid' => 'USNE0482', 'name' => 'Thurston');
$city_data[] = array('accid' => 'USNE0483', 'name' => 'Tilden');
$city_data[] = array('accid' => 'USNE0484', 'name' => 'Tobias');
$city_data[] = array('accid' => 'USNE0485', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USNE0486', 'name' => 'Trumbull');
$city_data[] = array('accid' => 'USNE0487', 'name' => 'Tryon');
$city_data[] = array('accid' => 'USNE0488', 'name' => 'Uehling');
$city_data[] = array('accid' => 'USNE0489', 'name' => 'Ulysses');
$city_data[] = array('accid' => 'USNE0490', 'name' => 'Unadilla');
$city_data[] = array('accid' => 'USNE0491', 'name' => 'Union');
$city_data[] = array('accid' => 'USNE0492', 'name' => 'Upland');
$city_data[] = array('accid' => 'USNE0493', 'name' => 'Utica');
$city_data[] = array('accid' => 'USNE0494', 'name' => 'Valentine');
$city_data[] = array('accid' => 'USNE0495', 'name' => 'Valley');
$city_data[] = array('accid' => 'USNE0496', 'name' => 'Valparaiso');
$city_data[] = array('accid' => 'USNE0497', 'name' => 'Venango');
$city_data[] = array('accid' => 'USNE0498', 'name' => 'Verdigre');
$city_data[] = array('accid' => 'USNE0499', 'name' => 'Verdon');
$city_data[] = array('accid' => 'USNE0500', 'name' => 'Virginia');
$city_data[] = array('accid' => 'USNE0501', 'name' => 'Waco');
$city_data[] = array('accid' => 'USNE0502', 'name' => 'Wahoo');
$city_data[] = array('accid' => 'USNE0503', 'name' => 'Wakefield');
$city_data[] = array('accid' => 'USNE0504', 'name' => 'Wallace');
$city_data[] = array('accid' => 'USNE0505', 'name' => 'Walthill');
$city_data[] = array('accid' => 'USNE0506', 'name' => 'Walton');
$city_data[] = array('accid' => 'USNE0507', 'name' => 'Washington');
$city_data[] = array('accid' => 'USNE0508', 'name' => 'Waterbury');
$city_data[] = array('accid' => 'USNE0509', 'name' => 'Waterloo');
$city_data[] = array('accid' => 'USNE0510', 'name' => 'Wauneta');
$city_data[] = array('accid' => 'USNE0511', 'name' => 'Wausa');
$city_data[] = array('accid' => 'USNE0512', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USNE0513', 'name' => 'Wayne');
$city_data[] = array('accid' => 'USNE0514', 'name' => 'Weeping Water');
$city_data[] = array('accid' => 'USNE0515', 'name' => 'Weissert');
$city_data[] = array('accid' => 'USNE0516', 'name' => 'Wellfleet');
$city_data[] = array('accid' => 'USNE0517', 'name' => 'West Point');
$city_data[] = array('accid' => 'USNE0518', 'name' => 'Western');
$city_data[] = array('accid' => 'USNE0519', 'name' => 'Westerville');
$city_data[] = array('accid' => 'USNE0520', 'name' => 'Weston');
$city_data[] = array('accid' => 'USNE0521', 'name' => 'Whiteclay');
$city_data[] = array('accid' => 'USNE0522', 'name' => 'Whitman');
$city_data[] = array('accid' => 'USNE0523', 'name' => 'Whitney');
$city_data[] = array('accid' => 'USNE0524', 'name' => 'Wilber');
$city_data[] = array('accid' => 'USNE0525', 'name' => 'Wilcox');
$city_data[] = array('accid' => 'USNE0526', 'name' => 'Willow Island');
$city_data[] = array('accid' => 'USNE0527', 'name' => 'Wilsonville');
$city_data[] = array('accid' => 'USNE0528', 'name' => 'Winnebago');
$city_data[] = array('accid' => 'USNE0529', 'name' => 'Winnetoon');
$city_data[] = array('accid' => 'USNE0530', 'name' => 'Winside');
$city_data[] = array('accid' => 'USNE0531', 'name' => 'Winslow');
$city_data[] = array('accid' => 'USNE0532', 'name' => 'Wisner');
$city_data[] = array('accid' => 'USNE0533', 'name' => 'Wolbach');
$city_data[] = array('accid' => 'USNE0534', 'name' => 'Wood Lake');
$city_data[] = array('accid' => 'USNE0535', 'name' => 'Wood River');
$city_data[] = array('accid' => 'USNE0536', 'name' => 'Wymore');
$city_data[] = array('accid' => 'USNE0537', 'name' => 'Wynot');
$city_data[] = array('accid' => 'USNE0538', 'name' => 'York');
$city_data[] = array('accid' => 'USNE0539', 'name' => 'Yutan');

?>
