<?php

// City package for USA: New Hampshire 

$city_name = 'USA: New Hampshire';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USNH0001', 'name' => 'Acworth');
$city_data[] = array('accid' => 'USNH0002', 'name' => 'Alstead');
$city_data[] = array('accid' => 'USNH0003', 'name' => 'Alton');
$city_data[] = array('accid' => 'USNH0004', 'name' => 'Alton Bay');
$city_data[] = array('accid' => 'USNH0005', 'name' => 'Amherst');
$city_data[] = array('accid' => 'USNH0006', 'name' => 'Andover');
$city_data[] = array('accid' => 'USNH0007', 'name' => 'Antrim');
$city_data[] = array('accid' => 'USNH0008', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USNH0009', 'name' => 'Ashuelot');
$city_data[] = array('accid' => 'USNH0010', 'name' => 'Atkinson');
$city_data[] = array('accid' => 'USNH0012', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USNH0013', 'name' => 'Barnstead');
$city_data[] = array('accid' => 'USNH0014', 'name' => 'Barrington');
$city_data[] = array('accid' => 'USNH0015', 'name' => 'Bartlett');
$city_data[] = array('accid' => 'USNH0016', 'name' => 'Bath');
$city_data[] = array('accid' => 'USNH0017', 'name' => 'Bedford');
$city_data[] = array('accid' => 'USNH0018', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USNH0019', 'name' => 'Bennington');
$city_data[] = array('accid' => 'USNH0020', 'name' => 'Berlin');
$city_data[] = array('accid' => 'USNH0021', 'name' => 'Bethlehem');
$city_data[] = array('accid' => 'USNH0022', 'name' => 'Bow');
$city_data[] = array('accid' => 'USNH0023', 'name' => 'Bradford');
$city_data[] = array('accid' => 'USNH0024', 'name' => 'Bretton Woods');
$city_data[] = array('accid' => 'USNH0025', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USNH0026', 'name' => 'Brookline');
$city_data[] = array('accid' => 'USNH0027', 'name' => 'Campton');
$city_data[] = array('accid' => 'USNH0028', 'name' => 'Canaan');
$city_data[] = array('accid' => 'USNH0029', 'name' => 'Candia');
$city_data[] = array('accid' => 'USNH0031', 'name' => 'Canterbury');
$city_data[] = array('accid' => 'USNH0032', 'name' => 'Center Barnstead');
$city_data[] = array('accid' => 'USNH0033', 'name' => 'Center Conway');
$city_data[] = array('accid' => 'USNH0034', 'name' => 'Center Harbor');
$city_data[] = array('accid' => 'USNH0035', 'name' => 'Center Ossipee');
$city_data[] = array('accid' => 'USNH0036', 'name' => 'Center Sandwich');
$city_data[] = array('accid' => 'USNH0037', 'name' => 'Center Strafford');
$city_data[] = array('accid' => 'USNH0038', 'name' => 'Center Tuftonboro');
$city_data[] = array('accid' => 'USNH0039', 'name' => 'Charlestown');
$city_data[] = array('accid' => 'USNH0040', 'name' => 'Chester');
$city_data[] = array('accid' => 'USNH0041', 'name' => 'Chesterfield');
$city_data[] = array('accid' => 'USNH0263', 'name' => 'Chichester');
$city_data[] = array('accid' => 'USNH0042', 'name' => 'Chocorua');
$city_data[] = array('accid' => 'USNH0043', 'name' => 'Claremont');
$city_data[] = array('accid' => 'USNH0044', 'name' => 'Colebrook');
$city_data[] = array('accid' => 'USNH0045', 'name' => 'Concord');
$city_data[] = array('accid' => 'USNH0046', 'name' => 'Contoocook');
$city_data[] = array('accid' => 'USNH0047', 'name' => 'Conway');
$city_data[] = array('accid' => 'USNH0048', 'name' => 'Cornish');
$city_data[] = array('accid' => 'USNH0049', 'name' => 'Cornish Flat');
$city_data[] = array('accid' => 'USNH0050', 'name' => 'Danbury');
$city_data[] = array('accid' => 'USNH0051', 'name' => 'Danville');
$city_data[] = array('accid' => 'USNH0052', 'name' => 'Deerfield');
$city_data[] = array('accid' => 'USNH0053', 'name' => 'Derry');
$city_data[] = array('accid' => 'USNH0054', 'name' => 'Dover');
$city_data[] = array('accid' => 'USNH0055', 'name' => 'Drewsville');
$city_data[] = array('accid' => 'USNH0056', 'name' => 'Dublin');
$city_data[] = array('accid' => 'USNH0260', 'name' => 'Dunbarton');
$city_data[] = array('accid' => 'USNH0057', 'name' => 'Durham');
$city_data[] = array('accid' => 'USNH0058', 'name' => 'East Andover');
$city_data[] = array('accid' => 'USNH0059', 'name' => 'East Candia');
$city_data[] = array('accid' => 'USNH0060', 'name' => 'East Derry');
$city_data[] = array('accid' => 'USNH0061', 'name' => 'East Hampstead');
$city_data[] = array('accid' => 'USNH0062', 'name' => 'East Hebron');
$city_data[] = array('accid' => 'USNH0063', 'name' => 'East Kingston');
$city_data[] = array('accid' => 'USNH0064', 'name' => 'East Wakefield');
$city_data[] = array('accid' => 'USNH0065', 'name' => 'Eaton Center');
$city_data[] = array('accid' => 'USNH0066', 'name' => 'Elkins');
$city_data[] = array('accid' => 'USNH0067', 'name' => 'Enfield');
$city_data[] = array('accid' => 'USNH0068', 'name' => 'Enfield Center');
$city_data[] = array('accid' => 'USNH0069', 'name' => 'Epping');
$city_data[] = array('accid' => 'USNH0070', 'name' => 'Epsom');
$city_data[] = array('accid' => 'USNH0071', 'name' => 'Errol');
$city_data[] = array('accid' => 'USNH0072', 'name' => 'Etna');
$city_data[] = array('accid' => 'USNH0073', 'name' => 'Exeter');
$city_data[] = array('accid' => 'USNH0074', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USNH0075', 'name' => 'Fitzwilliam');
$city_data[] = array('accid' => 'USNH0076', 'name' => 'Francestown');
$city_data[] = array('accid' => 'USNH0077', 'name' => 'Franconia');
$city_data[] = array('accid' => 'USNH0078', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USNH0079', 'name' => 'Freedom');
$city_data[] = array('accid' => 'USNH0080', 'name' => 'Fremont');
$city_data[] = array('accid' => 'USNH0081', 'name' => 'Georges Mills');
$city_data[] = array('accid' => 'USNH0261', 'name' => 'Gilford');
$city_data[] = array('accid' => 'USNH0082', 'name' => 'Gilmanton');
$city_data[] = array('accid' => 'USNH0083', 'name' => 'Gilmanton Iron Works');
$city_data[] = array('accid' => 'USNH0084', 'name' => 'Gilsum');
$city_data[] = array('accid' => 'USNH0085', 'name' => 'Glen');
$city_data[] = array('accid' => 'USNH0086', 'name' => 'Glencliff');
$city_data[] = array('accid' => 'USNH0087', 'name' => 'Goffstown');
$city_data[] = array('accid' => 'USNH0088', 'name' => 'Gorham');
$city_data[] = array('accid' => 'USNH0089', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USNH0090', 'name' => 'Grafton');
$city_data[] = array('accid' => 'USNH0091', 'name' => 'Grantham');
$city_data[] = array('accid' => 'USNH0092', 'name' => 'Greenfield');
$city_data[] = array('accid' => 'USNH0093', 'name' => 'Greenland');
$city_data[] = array('accid' => 'USNH0094', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USNH0095', 'name' => 'Groveton');
$city_data[] = array('accid' => 'USNH0096', 'name' => 'Guild');
$city_data[] = array('accid' => 'USNH0098', 'name' => 'Hampstead');
$city_data[] = array('accid' => 'USNH0099', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USNH0100', 'name' => 'Hampton Falls');
$city_data[] = array('accid' => 'USNH0101', 'name' => 'Hancock');
$city_data[] = array('accid' => 'USNH0102', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USNH0103', 'name' => 'Harrisville');
$city_data[] = array('accid' => 'USNH0104', 'name' => 'Haverhill');
$city_data[] = array('accid' => 'USNH0105', 'name' => 'Hebron');
$city_data[] = array('accid' => 'USNH0106', 'name' => 'Henniker');
$city_data[] = array('accid' => 'USNH0107', 'name' => 'Hill');
$city_data[] = array('accid' => 'USNH0108', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USNH0109', 'name' => 'Hinsdale');
$city_data[] = array('accid' => 'USNH0110', 'name' => 'Holderness');
$city_data[] = array('accid' => 'USNH0111', 'name' => 'Hollis');
$city_data[] = array('accid' => 'USNH0112', 'name' => 'Hooksett');
$city_data[] = array('accid' => 'USNH0113', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USNH0114', 'name' => 'Intervale');
$city_data[] = array('accid' => 'USNH0115', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USNH0116', 'name' => 'Jaffrey');
$city_data[] = array('accid' => 'USNH0117', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USNH0118', 'name' => 'Kearsarge');
$city_data[] = array('accid' => 'USNH0119', 'name' => 'Keene');
$city_data[] = array('accid' => 'USNH0120', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USNH0121', 'name' => 'Laconia');
$city_data[] = array('accid' => 'USNH0122', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USNH0123', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USNH0124', 'name' => 'Lempster');
$city_data[] = array('accid' => 'USNH0125', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USNH0126', 'name' => 'Lisbon');
$city_data[] = array('accid' => 'USNH0127', 'name' => 'Litchfield');
$city_data[] = array('accid' => 'USNH0128', 'name' => 'Littleton');
$city_data[] = array('accid' => 'USNH0129', 'name' => 'Lochmere');
$city_data[] = array('accid' => 'USNH0130', 'name' => 'Londonderry');
$city_data[] = array('accid' => 'USNH0132', 'name' => 'Lyme');
$city_data[] = array('accid' => 'USNH0133', 'name' => 'Lyme Center');
$city_data[] = array('accid' => 'USNH0134', 'name' => 'Lyndeborough');
$city_data[] = array('accid' => 'USNH0135', 'name' => 'Madison');
$city_data[] = array('accid' => 'USNH0136', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USNH0137', 'name' => 'Marlborough');
$city_data[] = array('accid' => 'USNH0138', 'name' => 'Marlow');
$city_data[] = array('accid' => 'USNH0139', 'name' => 'Meadows');
$city_data[] = array('accid' => 'USNH0140', 'name' => 'Melvin Village');
$city_data[] = array('accid' => 'USNH0141', 'name' => 'Meredith');
$city_data[] = array('accid' => 'USNH0142', 'name' => 'Meriden');
$city_data[] = array('accid' => 'USNH0143', 'name' => 'Merrimack');
$city_data[] = array('accid' => 'USNH0144', 'name' => 'Milan');
$city_data[] = array('accid' => 'USNH0145', 'name' => 'Milford');
$city_data[] = array('accid' => 'USNH0146', 'name' => 'Milton');
$city_data[] = array('accid' => 'USNH0147', 'name' => 'Milton Mills');
$city_data[] = array('accid' => 'USNH0148', 'name' => 'Mirror Lake');
$city_data[] = array('accid' => 'USNH0149', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USNH0150', 'name' => 'Mont Vernon');
$city_data[] = array('accid' => 'USNH0151', 'name' => 'Moultonborough');
$city_data[] = array('accid' => 'USNH0154', 'name' => 'Mount Washington');
$city_data[] = array('accid' => 'USNH0155', 'name' => 'Munsonville');
$city_data[] = array('accid' => 'USNH0156', 'name' => 'Nashua');
$city_data[] = array('accid' => 'USNH0157', 'name' => 'New Boston');
$city_data[] = array('accid' => 'USNH0158', 'name' => 'New Castle');
$city_data[] = array('accid' => 'USNH0159', 'name' => 'New Durham');
$city_data[] = array('accid' => 'USNH0160', 'name' => 'New Hampton');
$city_data[] = array('accid' => 'USNH0161', 'name' => 'New Ipswich');
$city_data[] = array('accid' => 'USNH0162', 'name' => 'New London');
$city_data[] = array('accid' => 'USNH0163', 'name' => 'Newbury');
$city_data[] = array('accid' => 'USNH0164', 'name' => 'Newfields');
$city_data[] = array('accid' => 'USNH0165', 'name' => 'Newmarket');
$city_data[] = array('accid' => 'USNH0166', 'name' => 'Newport');
$city_data[] = array('accid' => 'USNH0167', 'name' => 'Newton');
$city_data[] = array('accid' => 'USNH0168', 'name' => 'Newton Junction');
$city_data[] = array('accid' => 'USNH0169', 'name' => 'North Conway');
$city_data[] = array('accid' => 'USNH0170', 'name' => 'North Hampton');
$city_data[] = array('accid' => 'USNH0171', 'name' => 'North Haverhill');
$city_data[] = array('accid' => 'USNH0172', 'name' => 'North Salem');
$city_data[] = array('accid' => 'USNH0173', 'name' => 'North Sandwich');
$city_data[] = array('accid' => 'USNH0174', 'name' => 'North Stratford');
$city_data[] = array('accid' => 'USNH0175', 'name' => 'North Sutton');
$city_data[] = array('accid' => 'USNH0176', 'name' => 'North Walpole');
$city_data[] = array('accid' => 'USNH0177', 'name' => 'North Woodstock');
$city_data[] = array('accid' => 'USNH0178', 'name' => 'Northwood');
$city_data[] = array('accid' => 'USNH0179', 'name' => 'Nottingham');
$city_data[] = array('accid' => 'USNH0180', 'name' => 'Orford');
$city_data[] = array('accid' => 'USNH0181', 'name' => 'Ossipee');
$city_data[] = array('accid' => 'USNH0182', 'name' => 'Pelham');
$city_data[] = array('accid' => 'USNH0183', 'name' => 'Peterborough');
$city_data[] = array('accid' => 'USNH0184', 'name' => 'Piermont');
$city_data[] = array('accid' => 'USNH0185', 'name' => 'Pike');
$city_data[] = array('accid' => 'USNH0186', 'name' => 'Pittsburg');
$city_data[] = array('accid' => 'USNH0187', 'name' => 'Pittsfield');
$city_data[] = array('accid' => 'USNH0188', 'name' => 'Plainfield');
$city_data[] = array('accid' => 'USNH0189', 'name' => 'Plaistow');
$city_data[] = array('accid' => 'USNH0190', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USNH0191', 'name' => 'Portsmouth');
$city_data[] = array('accid' => 'USNH0192', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USNH0193', 'name' => 'Rindge');
$city_data[] = array('accid' => 'USNH0194', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USNH0195', 'name' => 'Rollinsford');
$city_data[] = array('accid' => 'USNH0196', 'name' => 'Rumney');
$city_data[] = array('accid' => 'USNH0197', 'name' => 'Rye');
$city_data[] = array('accid' => 'USNH0198', 'name' => 'Rye Beach');
$city_data[] = array('accid' => 'USNH0199', 'name' => 'Salem');
$city_data[] = array('accid' => 'USNH0200', 'name' => 'Salisbury');
$city_data[] = array('accid' => 'USNH0201', 'name' => 'Sanbornton');
$city_data[] = array('accid' => 'USNH0202', 'name' => 'Sanbornville');
$city_data[] = array('accid' => 'USNH0203', 'name' => 'Sandown');
$city_data[] = array('accid' => 'USNH0204', 'name' => 'Seabrook');
$city_data[] = array('accid' => 'USNH0205', 'name' => 'Silver Lake');
$city_data[] = array('accid' => 'USNH0206', 'name' => 'Somersworth');
$city_data[] = array('accid' => 'USNH0207', 'name' => 'South Acworth');
$city_data[] = array('accid' => 'USNH0208', 'name' => 'South Effingham');
$city_data[] = array('accid' => 'USNH0209', 'name' => 'South Newbury');
$city_data[] = array('accid' => 'USNH0210', 'name' => 'South Sutton');
$city_data[] = array('accid' => 'USNH0211', 'name' => 'South Tamworth');
$city_data[] = array('accid' => 'USNH0212', 'name' => 'Spofford');
$city_data[] = array('accid' => 'USNH0213', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USNH0214', 'name' => 'Stinson Lake');
$city_data[] = array('accid' => 'USNH0215', 'name' => 'Stoddard');
$city_data[] = array('accid' => 'USNH0216', 'name' => 'Strafford');
$city_data[] = array('accid' => 'USNH0217', 'name' => 'Stratham');
$city_data[] = array('accid' => 'USNH0218', 'name' => 'Sullivan');
$city_data[] = array('accid' => 'USNH0219', 'name' => 'Sunapee');
$city_data[] = array('accid' => 'USNH0220', 'name' => 'Suncook');
$city_data[] = array('accid' => 'USNH0221', 'name' => 'Swanzey');
$city_data[] = array('accid' => 'USNH0222', 'name' => 'Tamworth');
$city_data[] = array('accid' => 'USNH0223', 'name' => 'Temple');
$city_data[] = array('accid' => 'USNH0224', 'name' => 'Tilton');
$city_data[] = array('accid' => 'USNH0225', 'name' => 'Troy');
$city_data[] = array('accid' => 'USNH0226', 'name' => 'Twin Mountain');
$city_data[] = array('accid' => 'USNH0227', 'name' => 'Union');
$city_data[] = array('accid' => 'USNH0228', 'name' => 'Walpole');
$city_data[] = array('accid' => 'USNH0229', 'name' => 'Warner');
$city_data[] = array('accid' => 'USNH0230', 'name' => 'Warren');
$city_data[] = array('accid' => 'USNH0231', 'name' => 'Washington');
$city_data[] = array('accid' => 'USNH0232', 'name' => 'Waterville Valley');
$city_data[] = array('accid' => 'USNH0234', 'name' => 'Weare');
$city_data[] = array('accid' => 'USNH0235', 'name' => 'Wentworth');
$city_data[] = array('accid' => 'USNH0236', 'name' => 'West Chesterfield');
$city_data[] = array('accid' => 'USNH0237', 'name' => 'West Lebanon');
$city_data[] = array('accid' => 'USNH0238', 'name' => 'West Nottingham');
$city_data[] = array('accid' => 'USNH0239', 'name' => 'West Ossipee');
$city_data[] = array('accid' => 'USNH0240', 'name' => 'West Peterborough');
$city_data[] = array('accid' => 'USNH0241', 'name' => 'West Stewartstown');
$city_data[] = array('accid' => 'USNH0242', 'name' => 'West Swanzey');
$city_data[] = array('accid' => 'USNH0243', 'name' => 'Westmoreland');
$city_data[] = array('accid' => 'USNH0244', 'name' => 'Whitefield');
$city_data[] = array('accid' => 'USNH0246', 'name' => 'Wilmot');
$city_data[] = array('accid' => 'USNH0247', 'name' => 'Wilton');
$city_data[] = array('accid' => 'USNH0248', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USNH0249', 'name' => 'Windham');
$city_data[] = array('accid' => 'USNH0250', 'name' => 'Winnisquam');
$city_data[] = array('accid' => 'USNH0251', 'name' => 'Wolfeboro');
$city_data[] = array('accid' => 'USNH0252', 'name' => 'Wolfeboro Falls');
$city_data[] = array('accid' => 'USNH0253', 'name' => 'Wonalancet');
$city_data[] = array('accid' => 'USNH0254', 'name' => 'Woodstock');
$city_data[] = array('accid' => 'USNH0255', 'name' => 'Woodsville');

?>
