<?php

// City package for USA: New Jersey 

$city_name = 'USA: New Jersey';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USNJ0001', 'name' => 'Absecon');
$city_data[] = array('accid' => 'USNJ0002', 'name' => 'Adelphia');
$city_data[] = array('accid' => 'USNJ0003', 'name' => 'Allamuchy');
$city_data[] = array('accid' => 'USNJ0004', 'name' => 'Allendale');
$city_data[] = array('accid' => 'USNJ0005', 'name' => 'Allenhurst');
$city_data[] = array('accid' => 'USNJ0006', 'name' => 'Allentown');
$city_data[] = array('accid' => 'USNJ0007', 'name' => 'Allenwood');
$city_data[] = array('accid' => 'USNJ0008', 'name' => 'Alloway');
$city_data[] = array('accid' => 'USNJ0009', 'name' => 'Alpine');
$city_data[] = array('accid' => 'USNJ0010', 'name' => 'Andover');
$city_data[] = array('accid' => 'USNJ0011', 'name' => 'Annandale');
$city_data[] = array('accid' => 'USNJ0012', 'name' => 'Asbury');
$city_data[] = array('accid' => 'USNJ0013', 'name' => 'Asbury Park');
$city_data[] = array('accid' => 'USNJ0014', 'name' => 'Atco');
$city_data[] = array('accid' => 'USNJ0015', 'name' => 'Atlantic City');
$city_data[] = array('accid' => 'USNJ0017', 'name' => 'Atlantic Highlands');
$city_data[] = array('accid' => 'USNJ0018', 'name' => 'Audubon');
$city_data[] = array('accid' => 'USNJ0019', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USNJ0020', 'name' => 'Avalon');
$city_data[] = array('accid' => 'USNJ0021', 'name' => 'Avenel');
$city_data[] = array('accid' => 'USNJ0022', 'name' => 'Avon By The Sea');
$city_data[] = array('accid' => 'USNJ0023', 'name' => 'Baptistown');
$city_data[] = array('accid' => 'USNJ0024', 'name' => 'Barnegat');
$city_data[] = array('accid' => 'USNJ0025', 'name' => 'Barnegat Light');
$city_data[] = array('accid' => 'USNJ0026', 'name' => 'Barrington');
$city_data[] = array('accid' => 'USNJ0027', 'name' => 'Basking Ridge');
$city_data[] = array('accid' => 'USNJ0028', 'name' => 'Bayonne');
$city_data[] = array('accid' => 'USNJ0029', 'name' => 'Bayville');
$city_data[] = array('accid' => 'USNJ0030', 'name' => 'Beach Haven');
$city_data[] = array('accid' => 'USNJ0031', 'name' => 'Beachwood');
$city_data[] = array('accid' => 'USNJ0032', 'name' => 'Bedminster');
$city_data[] = array('accid' => 'USNJ0033', 'name' => 'Belford');
$city_data[] = array('accid' => 'USNJ0034', 'name' => 'Belle Mead');
$city_data[] = array('accid' => 'USNJ0035', 'name' => 'Belleville');
$city_data[] = array('accid' => 'USNJ0036', 'name' => 'Bellmawr');
$city_data[] = array('accid' => 'USNJ0037', 'name' => 'Belmar');
$city_data[] = array('accid' => 'USNJ0038', 'name' => 'Belvidere');
$city_data[] = array('accid' => 'USNJ0039', 'name' => 'Bergenfield');
$city_data[] = array('accid' => 'USNJ0040', 'name' => 'Berkeley Heights');
$city_data[] = array('accid' => 'USNJ0041', 'name' => 'Berlin');
$city_data[] = array('accid' => 'USNJ0042', 'name' => 'Bernardsville');
$city_data[] = array('accid' => 'USNJ0043', 'name' => 'Beverly');
$city_data[] = array('accid' => 'USNJ0044', 'name' => 'Birmingham');
$city_data[] = array('accid' => 'USNJ0045', 'name' => 'Blackwood');
$city_data[] = array('accid' => 'USNJ0046', 'name' => 'Blairstown');
$city_data[] = array('accid' => 'USNJ0047', 'name' => 'Blawenburg');
$city_data[] = array('accid' => 'USNJ0048', 'name' => 'Bloomfield');
$city_data[] = array('accid' => 'USNJ0049', 'name' => 'Bloomingdale');
$city_data[] = array('accid' => 'USNJ0050', 'name' => 'Bloomsbury');
$city_data[] = array('accid' => 'USNJ0051', 'name' => 'Bogota');
$city_data[] = array('accid' => 'USNJ0052', 'name' => 'Boonton');
$city_data[] = array('accid' => 'USNJ0053', 'name' => 'Bordentown');
$city_data[] = array('accid' => 'USNJ0054', 'name' => 'Bound Brook');
$city_data[] = array('accid' => 'USNJ0055', 'name' => 'Bradley Beach');
$city_data[] = array('accid' => 'USNJ0056', 'name' => 'Branchville');
$city_data[] = array('accid' => 'USNJ0057', 'name' => 'Bricktown');
$city_data[] = array('accid' => 'USNJ0058', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USNJ0059', 'name' => 'Bridgeton');
$city_data[] = array('accid' => 'USNJ0060', 'name' => 'Bridgewater');
$city_data[] = array('accid' => 'USNJ0061', 'name' => 'Brielle');
$city_data[] = array('accid' => 'USNJ0062', 'name' => 'Brigantine');
$city_data[] = array('accid' => 'USNJ0063', 'name' => 'Broadway');
$city_data[] = array('accid' => 'USNJ0064', 'name' => 'Brookside');
$city_data[] = array('accid' => 'USNJ0065', 'name' => 'Browns Mills');
$city_data[] = array('accid' => 'USNJ0066', 'name' => 'Budd Lake');
$city_data[] = array('accid' => 'USNJ0067', 'name' => 'Buena');
$city_data[] = array('accid' => 'USNJ0068', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USNJ0069', 'name' => 'Butler');
$city_data[] = array('accid' => 'USNJ0070', 'name' => 'Buttzville');
$city_data[] = array('accid' => 'USNJ0071', 'name' => 'Caldwell');
$city_data[] = array('accid' => 'USNJ0072', 'name' => 'Califon');
$city_data[] = array('accid' => 'USNJ0073', 'name' => 'Camden');
$city_data[] = array('accid' => 'USNJ0074', 'name' => 'Cape May');
$city_data[] = array('accid' => 'USNJ0075', 'name' => 'Cape May Court House');
$city_data[] = array('accid' => 'USNJ0076', 'name' => 'Cape May Point');
$city_data[] = array('accid' => 'USNJ0077', 'name' => 'Carlstadt');
$city_data[] = array('accid' => 'USNJ0078', 'name' => 'Carteret');
$city_data[] = array('accid' => 'USNJ0079', 'name' => 'Cedar Brook');
$city_data[] = array('accid' => 'USNJ0080', 'name' => 'Cedar Grove');
$city_data[] = array('accid' => 'USNJ0081', 'name' => 'Cedar Knolls');
$city_data[] = array('accid' => 'USNJ0082', 'name' => 'Cedarville');
$city_data[] = array('accid' => 'USNJ0083', 'name' => 'Changewater');
$city_data[] = array('accid' => 'USNJ0084', 'name' => 'Chatham');
$city_data[] = array('accid' => 'USNJ0085', 'name' => 'Chatsworth');
$city_data[] = array('accid' => 'USNJ0086', 'name' => 'Cherry Hill');
$city_data[] = array('accid' => 'USNJ0087', 'name' => 'Chester');
$city_data[] = array('accid' => 'USNJ0088', 'name' => 'Clark');
$city_data[] = array('accid' => 'USNJ0089', 'name' => 'Clarksboro');
$city_data[] = array('accid' => 'USNJ0090', 'name' => 'Clarksburg');
$city_data[] = array('accid' => 'USNJ0091', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USNJ0092', 'name' => 'Clementon');
$city_data[] = array('accid' => 'USNJ0093', 'name' => 'Cliffside Park');
$city_data[] = array('accid' => 'USNJ0094', 'name' => 'Cliffwood');
$city_data[] = array('accid' => 'USNJ0095', 'name' => 'Clifton');
$city_data[] = array('accid' => 'USNJ0096', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USNJ0097', 'name' => 'Closter');
$city_data[] = array('accid' => 'USNJ0098', 'name' => 'Collingswood');
$city_data[] = array('accid' => 'USNJ0099', 'name' => 'Cologne');
$city_data[] = array('accid' => 'USNJ0100', 'name' => 'Colonia');
$city_data[] = array('accid' => 'USNJ0101', 'name' => 'Colts Neck');
$city_data[] = array('accid' => 'USNJ0102', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USNJ0103', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USNJ0104', 'name' => 'Cookstown');
$city_data[] = array('accid' => 'USNJ0105', 'name' => 'Cranbury');
$city_data[] = array('accid' => 'USNJ0106', 'name' => 'Cranford');
$city_data[] = array('accid' => 'USNJ0107', 'name' => 'Cream Ridge');
$city_data[] = array('accid' => 'USNJ0108', 'name' => 'Cresskill');
$city_data[] = array('accid' => 'USNJ0109', 'name' => 'Crosswicks');
$city_data[] = array('accid' => 'USNJ0110', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USNJ0111', 'name' => 'Deal');
$city_data[] = array('accid' => 'USNJ0112', 'name' => 'Deepwater');
$city_data[] = array('accid' => 'USNJ0113', 'name' => 'Deerfield Street');
$city_data[] = array('accid' => 'USNJ0114', 'name' => 'Delaware');
$city_data[] = array('accid' => 'USNJ0115', 'name' => 'Delmont');
$city_data[] = array('accid' => 'USNJ0116', 'name' => 'Demarest');
$city_data[] = array('accid' => 'USNJ0117', 'name' => 'Dennisville');
$city_data[] = array('accid' => 'USNJ0118', 'name' => 'Denville');
$city_data[] = array('accid' => 'USNJ0119', 'name' => 'Dividing Creek');
$city_data[] = array('accid' => 'USNJ0120', 'name' => 'Dorchester');
$city_data[] = array('accid' => 'USNJ0121', 'name' => 'Dorothy');
$city_data[] = array('accid' => 'USNJ0122', 'name' => 'Dover');
$city_data[] = array('accid' => 'USNJ0123', 'name' => 'Dumont');
$city_data[] = array('accid' => 'USNJ0124', 'name' => 'Dunellen');
$city_data[] = array('accid' => 'USNJ0125', 'name' => 'East Brunswick');
$city_data[] = array('accid' => 'USNJ0126', 'name' => 'East Hanover');
$city_data[] = array('accid' => 'USNJ0127', 'name' => 'East Orange');
$city_data[] = array('accid' => 'USNJ0128', 'name' => 'East Rutherford');
$city_data[] = array('accid' => 'USNJ0129', 'name' => 'Eatontown');
$city_data[] = array('accid' => 'USNJ0130', 'name' => 'Edgewater');
$city_data[] = array('accid' => 'USNJ0131', 'name' => 'Edison');
$city_data[] = array('accid' => 'USNJ0132', 'name' => 'Egg Harbor City');
$city_data[] = array('accid' => 'USNJ0133', 'name' => 'Egg Harbor Township');
$city_data[] = array('accid' => 'USNJ0134', 'name' => 'Elizabeth');
$city_data[] = array('accid' => 'USNJ0135', 'name' => 'Elmer');
$city_data[] = array('accid' => 'USNJ0136', 'name' => 'Elmwood Park');
$city_data[] = array('accid' => 'USNJ0137', 'name' => 'Elwood');
$city_data[] = array('accid' => 'USNJ0138', 'name' => 'Emerson');
$city_data[] = array('accid' => 'USNJ0139', 'name' => 'Englewood');
$city_data[] = array('accid' => 'USNJ0140', 'name' => 'Englewood Cliffs');
$city_data[] = array('accid' => 'USNJ0141', 'name' => 'Englishtown');
$city_data[] = array('accid' => 'USNJ0142', 'name' => 'Essex Fells');
$city_data[] = array('accid' => 'USNJ0143', 'name' => 'Estell Manor');
$city_data[] = array('accid' => 'USNJ0144', 'name' => 'Ewan');
$city_data[] = array('accid' => 'USNJ0145', 'name' => 'Fair Haven');
$city_data[] = array('accid' => 'USNJ0146', 'name' => 'Fair Lawn');
$city_data[] = array('accid' => 'USNJ0147', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USNJ0148', 'name' => 'Fairton');
$city_data[] = array('accid' => 'USNJ0149', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USNJ0150', 'name' => 'Fanwood');
$city_data[] = array('accid' => 'USNJ0151', 'name' => 'Far Hills');
$city_data[] = array('accid' => 'USNJ0152', 'name' => 'Farmingdale');
$city_data[] = array('accid' => 'USNJ0153', 'name' => 'Flagtown');
$city_data[] = array('accid' => 'USNJ0154', 'name' => 'Flanders');
$city_data[] = array('accid' => 'USNJ0155', 'name' => 'Flemington');
$city_data[] = array('accid' => 'USNJ0156', 'name' => 'Florence');
$city_data[] = array('accid' => 'USNJ0157', 'name' => 'Florham Park');
$city_data[] = array('accid' => 'USNJ0158', 'name' => 'Fords');
$city_data[] = array('accid' => 'USNJ0159', 'name' => 'Forked River');
$city_data[] = array('accid' => 'USNJ0160', 'name' => 'Fort Lee');
$city_data[] = array('accid' => 'USNJ0161', 'name' => 'Fort Monmouth');
$city_data[] = array('accid' => 'USNJ0162', 'name' => 'Fortescue');
$city_data[] = array('accid' => 'USNJ0163', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USNJ0164', 'name' => 'Franklin Lakes');
$city_data[] = array('accid' => 'USNJ0165', 'name' => 'Franklin Park');
$city_data[] = array('accid' => 'USNJ0166', 'name' => 'Franklinville');
$city_data[] = array('accid' => 'USNJ0167', 'name' => 'Freehold');
$city_data[] = array('accid' => 'USNJ0168', 'name' => 'Frenchtown');
$city_data[] = array('accid' => 'USNJ0169', 'name' => 'Garfield');
$city_data[] = array('accid' => 'USNJ0170', 'name' => 'Garwood');
$city_data[] = array('accid' => 'USNJ0171', 'name' => 'Gibbsboro');
$city_data[] = array('accid' => 'USNJ0172', 'name' => 'Gibbstown');
$city_data[] = array('accid' => 'USNJ0173', 'name' => 'Gillette');
$city_data[] = array('accid' => 'USNJ0174', 'name' => 'Gladstone');
$city_data[] = array('accid' => 'USNJ0175', 'name' => 'Glassboro');
$city_data[] = array('accid' => 'USNJ0176', 'name' => 'Glasser');
$city_data[] = array('accid' => 'USNJ0177', 'name' => 'Glen Gardner');
$city_data[] = array('accid' => 'USNJ0178', 'name' => 'Glen Ridge');
$city_data[] = array('accid' => 'USNJ0179', 'name' => 'Glen Rock');
$city_data[] = array('accid' => 'USNJ0180', 'name' => 'Glendora');
$city_data[] = array('accid' => 'USNJ0181', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USNJ0182', 'name' => 'Gloucester City');
$city_data[] = array('accid' => 'USNJ0183', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USNJ0184', 'name' => 'Great Meadows');
$city_data[] = array('accid' => 'USNJ0185', 'name' => 'Green Creek');
$city_data[] = array('accid' => 'USNJ0186', 'name' => 'Green Village');
$city_data[] = array('accid' => 'USNJ0187', 'name' => 'Greendell');
$city_data[] = array('accid' => 'USNJ0188', 'name' => 'Greenwich');
$city_data[] = array('accid' => 'USNJ0189', 'name' => 'Grenloch');
$city_data[] = array('accid' => 'USNJ0190', 'name' => 'Hackensack');
$city_data[] = array('accid' => 'USNJ0191', 'name' => 'Hackettstown');
$city_data[] = array('accid' => 'USNJ0192', 'name' => 'Haddon Heights');
$city_data[] = array('accid' => 'USNJ0193', 'name' => 'Haddonfield');
$city_data[] = array('accid' => 'USNJ0194', 'name' => 'Hainesport');
$city_data[] = array('accid' => 'USNJ0195', 'name' => 'Haledon');
$city_data[] = array('accid' => 'USNJ0196', 'name' => 'Hamburg');
$city_data[] = array('accid' => 'USNJ0197', 'name' => 'Hammonton');
$city_data[] = array('accid' => 'USNJ0198', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USNJ0199', 'name' => 'Hancocks Bridge');
$city_data[] = array('accid' => 'USNJ0200', 'name' => 'Harrington Park');
$city_data[] = array('accid' => 'USNJ0201', 'name' => 'Harrison');
$city_data[] = array('accid' => 'USNJ0202', 'name' => 'Harrisonville');
$city_data[] = array('accid' => 'USNJ0203', 'name' => 'Hasbrouck Heights');
$city_data[] = array('accid' => 'USNJ0204', 'name' => 'Haskell');
$city_data[] = array('accid' => 'USNJ0205', 'name' => 'Haworth');
$city_data[] = array('accid' => 'USNJ0206', 'name' => 'Hawthorne');
$city_data[] = array('accid' => 'USNJ0207', 'name' => 'Hazlet');
$city_data[] = array('accid' => 'USNJ0208', 'name' => 'Heislerville');
$city_data[] = array('accid' => 'USNJ0209', 'name' => 'Helmetta');
$city_data[] = array('accid' => 'USNJ0210', 'name' => 'Hewitt');
$city_data[] = array('accid' => 'USNJ0211', 'name' => 'Hibernia');
$city_data[] = array('accid' => 'USNJ0213', 'name' => 'High Bridge');
$city_data[] = array('accid' => 'USNJ0214', 'name' => 'Highland Lakes');
$city_data[] = array('accid' => 'USNJ0215', 'name' => 'Highland Park');
$city_data[] = array('accid' => 'USNJ0216', 'name' => 'Highlands');
$city_data[] = array('accid' => 'USNJ0217', 'name' => 'Hightstown');
$city_data[] = array('accid' => 'USNJ0590', 'name' => 'Hillsborough');
$city_data[] = array('accid' => 'USNJ0218', 'name' => 'Hillsdale');
$city_data[] = array('accid' => 'USNJ0219', 'name' => 'Hillside');
$city_data[] = array('accid' => 'USNJ0220', 'name' => 'Ho Ho Kus');
$city_data[] = array('accid' => 'USNJ0221', 'name' => 'Hoboken');
$city_data[] = array('accid' => 'USNJ0222', 'name' => 'Holmdel');
$city_data[] = array('accid' => 'USNJ0223', 'name' => 'Hopatcong');
$city_data[] = array('accid' => 'USNJ0224', 'name' => 'Hope');
$city_data[] = array('accid' => 'USNJ0225', 'name' => 'Hopewell');
$city_data[] = array('accid' => 'USNJ0226', 'name' => 'Howell');
$city_data[] = array('accid' => 'USNJ0227', 'name' => 'Imlaystown');
$city_data[] = array('accid' => 'USNJ0228', 'name' => 'Ironia');
$city_data[] = array('accid' => 'USNJ0229', 'name' => 'Irvington');
$city_data[] = array('accid' => 'USNJ0230', 'name' => 'Iselin');
$city_data[] = array('accid' => 'USNJ0231', 'name' => 'Island Heights');
$city_data[] = array('accid' => 'USNJ0232', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USNJ0233', 'name' => 'Jamesburg');
$city_data[] = array('accid' => 'USNJ0234', 'name' => 'Jersey City');
$city_data[] = array('accid' => 'USNJ0235', 'name' => 'Jobstown');
$city_data[] = array('accid' => 'USNJ0236', 'name' => 'Johnsonburg');
$city_data[] = array('accid' => 'USNJ0237', 'name' => 'Juliustown');
$city_data[] = array('accid' => 'USNJ0238', 'name' => 'Keansburg');
$city_data[] = array('accid' => 'USNJ0239', 'name' => 'Kearny');
$city_data[] = array('accid' => 'USNJ0240', 'name' => 'Keasbey');
$city_data[] = array('accid' => 'USNJ0241', 'name' => 'Kendall Park');
$city_data[] = array('accid' => 'USNJ0242', 'name' => 'Kenilworth');
$city_data[] = array('accid' => 'USNJ0243', 'name' => 'Kenvil');
$city_data[] = array('accid' => 'USNJ0244', 'name' => 'Keyport');
$city_data[] = array('accid' => 'USNJ0245', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USNJ0246', 'name' => 'Lafayette');
$city_data[] = array('accid' => 'USNJ0247', 'name' => 'Lake Hiawatha');
$city_data[] = array('accid' => 'USNJ0248', 'name' => 'Lake Hopatcong');
$city_data[] = array('accid' => 'USNJ0249', 'name' => 'Lakehurst');
$city_data[] = array('accid' => 'USNJ0250', 'name' => 'Lakewood');
$city_data[] = array('accid' => 'USNJ0251', 'name' => 'Lambertville');
$city_data[] = array('accid' => 'USNJ0252', 'name' => 'Landing');
$city_data[] = array('accid' => 'USNJ0253', 'name' => 'Landisville');
$city_data[] = array('accid' => 'USNJ0254', 'name' => 'Lanoka Harbor');
$city_data[] = array('accid' => 'USNJ0255', 'name' => 'Lavallette');
$city_data[] = array('accid' => 'USNJ0256', 'name' => 'Lawnside');
$city_data[] = array('accid' => 'USNJ0257', 'name' => 'Layton');
$city_data[] = array('accid' => 'USNJ0258', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USNJ0259', 'name' => 'Ledgewood');
$city_data[] = array('accid' => 'USNJ0260', 'name' => 'Leeds Point');
$city_data[] = array('accid' => 'USNJ0261', 'name' => 'Leesburg');
$city_data[] = array('accid' => 'USNJ0262', 'name' => 'Leonardo');
$city_data[] = array('accid' => 'USNJ0263', 'name' => 'Leonia');
$city_data[] = array('accid' => 'USNJ0264', 'name' => 'Liberty Corner');
$city_data[] = array('accid' => 'USNJ0265', 'name' => 'Lincoln Park');
$city_data[] = array('accid' => 'USNJ0266', 'name' => 'Lincroft');
$city_data[] = array('accid' => 'USNJ0267', 'name' => 'Linden');
$city_data[] = array('accid' => 'USNJ0268', 'name' => 'Linwood');
$city_data[] = array('accid' => 'USNJ0269', 'name' => 'Little Falls');
$city_data[] = array('accid' => 'USNJ0270', 'name' => 'Little Ferry');
$city_data[] = array('accid' => 'USNJ0271', 'name' => 'Little Silver');
$city_data[] = array('accid' => 'USNJ0272', 'name' => 'Little York');
$city_data[] = array('accid' => 'USNJ0273', 'name' => 'Livingston');
$city_data[] = array('accid' => 'USNJ0274', 'name' => 'Lodi');
$city_data[] = array('accid' => 'USNJ0275', 'name' => 'Long Branch');
$city_data[] = array('accid' => 'USNJ0276', 'name' => 'Long Valley');
$city_data[] = array('accid' => 'USNJ0277', 'name' => 'Longport');
$city_data[] = array('accid' => 'USNJ0278', 'name' => 'Lumberton');
$city_data[] = array('accid' => 'USNJ0279', 'name' => 'Lyndhurst');
$city_data[] = array('accid' => 'USNJ0280', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USNJ0281', 'name' => 'Madison');
$city_data[] = array('accid' => 'USNJ0282', 'name' => 'Magnolia');
$city_data[] = array('accid' => 'USNJ0283', 'name' => 'Mahwah');
$city_data[] = array('accid' => 'USNJ0284', 'name' => 'Malaga');
$city_data[] = array('accid' => 'USNJ0285', 'name' => 'Manahawkin');
$city_data[] = array('accid' => 'USNJ0286', 'name' => 'Manasquan');
$city_data[] = array('accid' => 'USNJ0287', 'name' => 'Mantoloking');
$city_data[] = array('accid' => 'USNJ0288', 'name' => 'Mantua');
$city_data[] = array('accid' => 'USNJ0289', 'name' => 'Manville');
$city_data[] = array('accid' => 'USNJ0290', 'name' => 'Maple Shade');
$city_data[] = array('accid' => 'USNJ0291', 'name' => 'Maplewood');
$city_data[] = array('accid' => 'USNJ0292', 'name' => 'Margate City');
$city_data[] = array('accid' => 'USNJ0293', 'name' => 'Marlboro');
$city_data[] = array('accid' => 'USNJ0294', 'name' => 'Marlton');
$city_data[] = array('accid' => 'USNJ0295', 'name' => 'Marmora');
$city_data[] = array('accid' => 'USNJ0296', 'name' => 'Martinsville');
$city_data[] = array('accid' => 'USNJ0297', 'name' => 'Matawan');
$city_data[] = array('accid' => 'USNJ0298', 'name' => 'Mauricetown');
$city_data[] = array('accid' => 'USNJ0299', 'name' => 'Mays Landing');
$city_data[] = array('accid' => 'USNJ0300', 'name' => 'Maywood');
$city_data[] = array('accid' => 'USNJ0301', 'name' => 'McAfee');
$city_data[] = array('accid' => 'USNJ0302', 'name' => 'Medford');
$city_data[] = array('accid' => 'USNJ0303', 'name' => 'Mendham');
$city_data[] = array('accid' => 'USNJ0304', 'name' => 'Merchantville');
$city_data[] = array('accid' => 'USNJ0305', 'name' => 'Metuchen');
$city_data[] = array('accid' => 'USNJ0306', 'name' => 'Mickleton');
$city_data[] = array('accid' => 'USNJ0307', 'name' => 'Middlesex');
$city_data[] = array('accid' => 'USNJ0308', 'name' => 'Middletown');
$city_data[] = array('accid' => 'USNJ0309', 'name' => 'Middleville');
$city_data[] = array('accid' => 'USNJ0310', 'name' => 'Midland Park');
$city_data[] = array('accid' => 'USNJ0311', 'name' => 'Milford');
$city_data[] = array('accid' => 'USNJ0312', 'name' => 'Millburn');
$city_data[] = array('accid' => 'USNJ0313', 'name' => 'Millington');
$city_data[] = array('accid' => 'USNJ0314', 'name' => 'Milltown');
$city_data[] = array('accid' => 'USNJ0315', 'name' => 'Millville');
$city_data[] = array('accid' => 'USNJ0316', 'name' => 'Milmay');
$city_data[] = array('accid' => 'USNJ0317', 'name' => 'Mine Hill');
$city_data[] = array('accid' => 'USNJ0318', 'name' => 'Minotola');
$city_data[] = array('accid' => 'USNJ0319', 'name' => 'Mizpah');
$city_data[] = array('accid' => 'USNJ0320', 'name' => 'Monmouth Beach');
$city_data[] = array('accid' => 'USNJ0321', 'name' => 'Monmouth Junction');
$city_data[] = array('accid' => 'USNJ0322', 'name' => 'Monroeville');
$city_data[] = array('accid' => 'USNJ0323', 'name' => 'Montague');
$city_data[] = array('accid' => 'USNJ0324', 'name' => 'Montclair');
$city_data[] = array('accid' => 'USNJ0325', 'name' => 'Montvale');
$city_data[] = array('accid' => 'USNJ0326', 'name' => 'Montville');
$city_data[] = array('accid' => 'USNJ0327', 'name' => 'Moonachie');
$city_data[] = array('accid' => 'USNJ0328', 'name' => 'Moorestown');
$city_data[] = array('accid' => 'USNJ0329', 'name' => 'Morganville');
$city_data[] = array('accid' => 'USNJ0330', 'name' => 'Morris Plains');
$city_data[] = array('accid' => 'USNJ0331', 'name' => 'Morristown');
$city_data[] = array('accid' => 'USNJ0332', 'name' => 'Mount Arlington');
$city_data[] = array('accid' => 'USNJ0333', 'name' => 'Mount Ephraim');
$city_data[] = array('accid' => 'USNJ0334', 'name' => 'Mount Freedom');
$city_data[] = array('accid' => 'USNJ0335', 'name' => 'Mount Holly');
$city_data[] = array('accid' => 'USNJ0336', 'name' => 'Mount Laurel');
$city_data[] = array('accid' => 'USNJ0337', 'name' => 'Mount Royal');
$city_data[] = array('accid' => 'USNJ0338', 'name' => 'Mount Tabor');
$city_data[] = array('accid' => 'USNJ0340', 'name' => 'Mountain Lakes');
$city_data[] = array('accid' => 'USNJ0341', 'name' => 'Mountainside');
$city_data[] = array('accid' => 'USNJ0342', 'name' => 'Mullica Hill');
$city_data[] = array('accid' => 'USNJ0597', 'name' => 'National Park');
$city_data[] = array('accid' => 'USNJ0344', 'name' => 'Navesink');
$city_data[] = array('accid' => 'USNJ0345', 'name' => 'Neptune');
$city_data[] = array('accid' => 'USNJ0346', 'name' => 'Neshanic Station');
$city_data[] = array('accid' => 'USNJ0347', 'name' => 'Netcong');
$city_data[] = array('accid' => 'USNJ0348', 'name' => 'New Brunswick');
$city_data[] = array('accid' => 'USNJ0349', 'name' => 'New Egypt');
$city_data[] = array('accid' => 'USNJ0350', 'name' => 'New Gretna');
$city_data[] = array('accid' => 'USNJ0351', 'name' => 'New Lisbon');
$city_data[] = array('accid' => 'USNJ0352', 'name' => 'New Milford');
$city_data[] = array('accid' => 'USNJ0353', 'name' => 'New Providence');
$city_data[] = array('accid' => 'USNJ0354', 'name' => 'New Vernon');
$city_data[] = array('accid' => 'USNJ0355', 'name' => 'Newark');
$city_data[] = array('accid' => 'USNJ0356', 'name' => 'Newfield');
$city_data[] = array('accid' => 'USNJ0357', 'name' => 'Newfoundland');
$city_data[] = array('accid' => 'USNJ0358', 'name' => 'Newport');
$city_data[] = array('accid' => 'USNJ0359', 'name' => 'Newton');
$city_data[] = array('accid' => 'USNJ0360', 'name' => 'Newtonville');
$city_data[] = array('accid' => 'USNJ0361', 'name' => 'Norma');
$city_data[] = array('accid' => 'USNJ0362', 'name' => 'Normandy Beach');
$city_data[] = array('accid' => 'USNJ0363', 'name' => 'North Arlington');
$city_data[] = array('accid' => 'USNJ0364', 'name' => 'North Bergen');
$city_data[] = array('accid' => 'USNJ0365', 'name' => 'North Brunswick');
$city_data[] = array('accid' => 'USNJ0366', 'name' => 'Northfield');
$city_data[] = array('accid' => 'USNJ0367', 'name' => 'Northvale');
$city_data[] = array('accid' => 'USNJ0368', 'name' => 'Norwood');
$city_data[] = array('accid' => 'USNJ0369', 'name' => 'Nutley');
$city_data[] = array('accid' => 'USNJ0370', 'name' => 'Oak Ridge');
$city_data[] = array('accid' => 'USNJ0371', 'name' => 'Oakhurst');
$city_data[] = array('accid' => 'USNJ0372', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USNJ0373', 'name' => 'Oaklyn');
$city_data[] = array('accid' => 'USNJ0374', 'name' => 'Ocean City');
$city_data[] = array('accid' => 'USNJ0375', 'name' => 'Ocean Gate');
$city_data[] = array('accid' => 'USNJ0376', 'name' => 'Ocean Grove');
$city_data[] = array('accid' => 'USNJ0377', 'name' => 'Ocean View');
$city_data[] = array('accid' => 'USNJ0378', 'name' => 'Oceanport');
$city_data[] = array('accid' => 'USNJ0379', 'name' => 'Oceanville');
$city_data[] = array('accid' => 'USNJ0380', 'name' => 'Ogdensburg');
$city_data[] = array('accid' => 'USNJ0381', 'name' => 'Old Bridge');
$city_data[] = array('accid' => 'USNJ0382', 'name' => 'Oldwick');
$city_data[] = array('accid' => 'USNJ0383', 'name' => 'Oradell');
$city_data[] = array('accid' => 'USNJ0384', 'name' => 'Orange');
$city_data[] = array('accid' => 'USNJ0385', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USNJ0386', 'name' => 'Palisades Park');
$city_data[] = array('accid' => 'USNJ0387', 'name' => 'Palmyra');
$city_data[] = array('accid' => 'USNJ0388', 'name' => 'Paramus');
$city_data[] = array('accid' => 'USNJ0389', 'name' => 'Park Ridge');
$city_data[] = array('accid' => 'USNJ0390', 'name' => 'Parlin');
$city_data[] = array('accid' => 'USNJ0391', 'name' => 'Parsippany');
$city_data[] = array('accid' => 'USNJ0392', 'name' => 'Passaic');
$city_data[] = array('accid' => 'USNJ0393', 'name' => 'Paterson');
$city_data[] = array('accid' => 'USNJ0394', 'name' => 'Paulsboro');
$city_data[] = array('accid' => 'USNJ0395', 'name' => 'Peapack');
$city_data[] = array('accid' => 'USNJ0396', 'name' => 'Pedricktown');
$city_data[] = array('accid' => 'USNJ0397', 'name' => 'Pemberton');
$city_data[] = array('accid' => 'USNJ0398', 'name' => 'Pennington');
$city_data[] = array('accid' => 'USNJ0399', 'name' => 'Penns Grove');
$city_data[] = array('accid' => 'USNJ0400', 'name' => 'Pennsauken');
$city_data[] = array('accid' => 'USNJ0401', 'name' => 'Pennsville');
$city_data[] = array('accid' => 'USNJ0402', 'name' => 'Pequannock');
$city_data[] = array('accid' => 'USNJ0403', 'name' => 'Perrineville');
$city_data[] = array('accid' => 'USNJ0404', 'name' => 'Perth Amboy');
$city_data[] = array('accid' => 'USNJ0405', 'name' => 'Phillipsburg');
$city_data[] = array('accid' => 'USNJ0406', 'name' => 'Picatinny Arsenal');
$city_data[] = array('accid' => 'USNJ0407', 'name' => 'Pine Beach');
$city_data[] = array('accid' => 'USNJ0408', 'name' => 'Pine Brook');
$city_data[] = array('accid' => 'USNJ0409', 'name' => 'Piscataway');
$city_data[] = array('accid' => 'USNJ0410', 'name' => 'Pitman');
$city_data[] = array('accid' => 'USNJ0411', 'name' => 'Pittstown');
$city_data[] = array('accid' => 'USNJ0412', 'name' => 'Plainfield');
$city_data[] = array('accid' => 'USNJ0413', 'name' => 'Plainsboro');
$city_data[] = array('accid' => 'USNJ0414', 'name' => 'Pleasantville');
$city_data[] = array('accid' => 'USNJ0415', 'name' => 'Pluckemin');
$city_data[] = array('accid' => 'USNJ0416', 'name' => 'Point Pleasant Beach');
$city_data[] = array('accid' => 'USNJ0417', 'name' => 'Pomona');
$city_data[] = array('accid' => 'USNJ0418', 'name' => 'Pompton Lakes');
$city_data[] = array('accid' => 'USNJ0419', 'name' => 'Pompton Plains');
$city_data[] = array('accid' => 'USNJ0420', 'name' => 'Port Elizabeth');
$city_data[] = array('accid' => 'USNJ0421', 'name' => 'Port Monmouth');
$city_data[] = array('accid' => 'USNJ0422', 'name' => 'Port Murray');
$city_data[] = array('accid' => 'USNJ0423', 'name' => 'Port Norris');
$city_data[] = array('accid' => 'USNJ0424', 'name' => 'Port Reading');
$city_data[] = array('accid' => 'USNJ0425', 'name' => 'Port Republic');
$city_data[] = array('accid' => 'USNJ0426', 'name' => 'Pottersville');
$city_data[] = array('accid' => 'USNJ0427', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USNJ0428', 'name' => 'Princeton Junction');
$city_data[] = array('accid' => 'USNJ0429', 'name' => 'Quakertown');
$city_data[] = array('accid' => 'USNJ0430', 'name' => 'Quinton');
$city_data[] = array('accid' => 'USNJ0431', 'name' => 'Rahway');
$city_data[] = array('accid' => 'USNJ0432', 'name' => 'Ramsey');
$city_data[] = array('accid' => 'USNJ0433', 'name' => 'Rancocas');
$city_data[] = array('accid' => 'USNJ0434', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USNJ0435', 'name' => 'Raritan');
$city_data[] = array('accid' => 'USNJ0436', 'name' => 'Readington');
$city_data[] = array('accid' => 'USNJ0437', 'name' => 'Red Bank');
$city_data[] = array('accid' => 'USNJ0438', 'name' => 'Richland');
$city_data[] = array('accid' => 'USNJ0439', 'name' => 'Richwood');
$city_data[] = array('accid' => 'USNJ0440', 'name' => 'Ridgefield');
$city_data[] = array('accid' => 'USNJ0441', 'name' => 'Ridgefield Park');
$city_data[] = array('accid' => 'USNJ0442', 'name' => 'Ridgewood');
$city_data[] = array('accid' => 'USNJ0443', 'name' => 'Ringoes');
$city_data[] = array('accid' => 'USNJ0444', 'name' => 'Ringwood');
$city_data[] = array('accid' => 'USNJ0445', 'name' => 'Rio Grande');
$city_data[] = array('accid' => 'USNJ0446', 'name' => 'River Edge');
$city_data[] = array('accid' => 'USNJ0447', 'name' => 'Riverdale');
$city_data[] = array('accid' => 'USNJ0448', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USNJ0449', 'name' => 'Riverton');
$city_data[] = array('accid' => 'USNJ0450', 'name' => 'Rochelle Park');
$city_data[] = array('accid' => 'USNJ0451', 'name' => 'Rockaway');
$city_data[] = array('accid' => 'USNJ0452', 'name' => 'Rocky Hill');
$city_data[] = array('accid' => 'USNJ0453', 'name' => 'Roebling');
$city_data[] = array('accid' => 'USNJ0454', 'name' => 'Roosevelt');
$city_data[] = array('accid' => 'USNJ0455', 'name' => 'Roseland');
$city_data[] = array('accid' => 'USNJ0456', 'name' => 'Roselle');
$city_data[] = array('accid' => 'USNJ0457', 'name' => 'Roselle Park');
$city_data[] = array('accid' => 'USNJ0458', 'name' => 'Rosemont');
$city_data[] = array('accid' => 'USNJ0459', 'name' => 'Rosenhayn');
$city_data[] = array('accid' => 'USNJ0460', 'name' => 'Rumson');
$city_data[] = array('accid' => 'USNJ0461', 'name' => 'Runnemede');
$city_data[] = array('accid' => 'USNJ0462', 'name' => 'Rutherford');
$city_data[] = array('accid' => 'USNJ0463', 'name' => 'Saddle Brook');
$city_data[] = array('accid' => 'USNJ0464', 'name' => 'Saddle River');
$city_data[] = array('accid' => 'USNJ0465', 'name' => 'Salem');
$city_data[] = array('accid' => 'USNJ0466', 'name' => 'Sayreville');
$city_data[] = array('accid' => 'USNJ0467', 'name' => 'Schooleys Mountain');
$city_data[] = array('accid' => 'USNJ0468', 'name' => 'Scotch Plains');
$city_data[] = array('accid' => 'USNJ0469', 'name' => 'Sea Girt');
$city_data[] = array('accid' => 'USNJ0470', 'name' => 'Sea Isle City');
$city_data[] = array('accid' => 'USNJ0471', 'name' => 'Seaside Heights');
$city_data[] = array('accid' => 'USNJ0472', 'name' => 'Seaside Park');
$city_data[] = array('accid' => 'USNJ0473', 'name' => 'Secaucus');
$city_data[] = array('accid' => 'USNJ0474', 'name' => 'Sergeantsville');
$city_data[] = array('accid' => 'USNJ0475', 'name' => 'Sewaren');
$city_data[] = array('accid' => 'USNJ0476', 'name' => 'Sewell');
$city_data[] = array('accid' => 'USNJ0477', 'name' => 'Shiloh');
$city_data[] = array('accid' => 'USNJ0478', 'name' => 'Short Hills');
$city_data[] = array('accid' => 'USNJ0479', 'name' => 'Shrewsbury');
$city_data[] = array('accid' => 'USNJ0480', 'name' => 'Sicklerville');
$city_data[] = array('accid' => 'USNJ0481', 'name' => 'Skillman');
$city_data[] = array('accid' => 'USNJ0482', 'name' => 'Somerdale');
$city_data[] = array('accid' => 'USNJ0483', 'name' => 'Somers Point');
$city_data[] = array('accid' => 'USNJ0484', 'name' => 'Somerset');
$city_data[] = array('accid' => 'USNJ0485', 'name' => 'Somerville');
$city_data[] = array('accid' => 'USNJ0486', 'name' => 'South Amboy');
$city_data[] = array('accid' => 'USNJ0487', 'name' => 'South Bound Brook');
$city_data[] = array('accid' => 'USNJ0488', 'name' => 'South Dennis');
$city_data[] = array('accid' => 'USNJ0489', 'name' => 'South Hackensack');
$city_data[] = array('accid' => 'USNJ0490', 'name' => 'South Orange');
$city_data[] = array('accid' => 'USNJ0491', 'name' => 'South Plainfield');
$city_data[] = array('accid' => 'USNJ0492', 'name' => 'South River');
$city_data[] = array('accid' => 'USNJ0493', 'name' => 'South Seaville');
$city_data[] = array('accid' => 'USNJ0494', 'name' => 'Sparta');
$city_data[] = array('accid' => 'USNJ0495', 'name' => 'Spotswood');
$city_data[] = array('accid' => 'USNJ0496', 'name' => 'Spring Lake');
$city_data[] = array('accid' => 'USNJ0497', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USNJ0498', 'name' => 'Stanhope');
$city_data[] = array('accid' => 'USNJ0499', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USNJ0500', 'name' => 'Stewartsville');
$city_data[] = array('accid' => 'USNJ0501', 'name' => 'Stillwater');
$city_data[] = array('accid' => 'USNJ0502', 'name' => 'Stirling');
$city_data[] = array('accid' => 'USNJ0503', 'name' => 'Stockholm');
$city_data[] = array('accid' => 'USNJ0504', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USNJ0505', 'name' => 'Stone Harbor');
$city_data[] = array('accid' => 'USNJ0506', 'name' => 'Stratford');
$city_data[] = array('accid' => 'USNJ0507', 'name' => 'Strathmere');
$city_data[] = array('accid' => 'USNJ0508', 'name' => 'Succasunna');
$city_data[] = array('accid' => 'USNJ0509', 'name' => 'Summit');
$city_data[] = array('accid' => 'USNJ0510', 'name' => 'Sussex');
$city_data[] = array('accid' => 'USNJ0511', 'name' => 'Swartswood');
$city_data[] = array('accid' => 'USNJ0512', 'name' => 'Swedesboro');
$city_data[] = array('accid' => 'USNJ0513', 'name' => 'Teaneck');
$city_data[] = array('accid' => 'USNJ0514', 'name' => 'Tenafly');
$city_data[] = array('accid' => 'USNJ0515', 'name' => 'Tennent');
$city_data[] = array('accid' => 'USNJ0516', 'name' => 'Teterboro');
$city_data[] = array('accid' => 'USNJ0517', 'name' => 'Thorofare');
$city_data[] = array('accid' => 'USNJ0518', 'name' => 'Three Bridges');
$city_data[] = array('accid' => 'USNJ0519', 'name' => 'Titusville');
$city_data[] = array('accid' => 'USNJ0520', 'name' => 'Toms River');
$city_data[] = array('accid' => 'USNJ0521', 'name' => 'Totowa');
$city_data[] = array('accid' => 'USNJ0522', 'name' => 'Towaco');
$city_data[] = array('accid' => 'USNJ0523', 'name' => 'Tranquility');
$city_data[] = array('accid' => 'USNJ0524', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USNJ0525', 'name' => 'Tuckahoe');
$city_data[] = array('accid' => 'USNJ0526', 'name' => 'Tuckerton');
$city_data[] = array('accid' => 'USNJ0527', 'name' => 'Union');
$city_data[] = array('accid' => 'USNJ0528', 'name' => 'Union City');
$city_data[] = array('accid' => 'USNJ0529', 'name' => 'Vauxhall');
$city_data[] = array('accid' => 'USNJ0530', 'name' => 'Ventnor City');
$city_data[] = array('accid' => 'USNJ0531', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USNJ0532', 'name' => 'Verona');
$city_data[] = array('accid' => 'USNJ0533', 'name' => 'Vienna');
$city_data[] = array('accid' => 'USNJ0534', 'name' => 'Villas');
$city_data[] = array('accid' => 'USNJ0535', 'name' => 'Vincentown');
$city_data[] = array('accid' => 'USNJ0536', 'name' => 'Vineland');
$city_data[] = array('accid' => 'USNJ0537', 'name' => 'Voorhees');
$city_data[] = array('accid' => 'USNJ0538', 'name' => 'Waldwick');
$city_data[] = array('accid' => 'USNJ0539', 'name' => 'Wallington');
$city_data[] = array('accid' => 'USNJ0540', 'name' => 'Wallpack Center');
$city_data[] = array('accid' => 'USNJ0541', 'name' => 'Wanaque');
$city_data[] = array('accid' => 'USNJ0542', 'name' => 'Waretown');
$city_data[] = array('accid' => 'USNJ0543', 'name' => 'Warren');
$city_data[] = array('accid' => 'USNJ0544', 'name' => 'Washington');
$city_data[] = array('accid' => 'USNJ0587', 'name' => 'Washington Township');
$city_data[] = array('accid' => 'USNJ0588', 'name' => 'Watchung');
$city_data[] = array('accid' => 'USNJ0545', 'name' => 'Waterford Works');
$city_data[] = array('accid' => 'USNJ0546', 'name' => 'Wayne');
$city_data[] = array('accid' => 'USNJ0589', 'name' => 'Weehawken');
$city_data[] = array('accid' => 'USNJ0547', 'name' => 'Wenonah');
$city_data[] = array('accid' => 'USNJ0548', 'name' => 'West Berlin');
$city_data[] = array('accid' => 'USNJ0549', 'name' => 'West Creek');
$city_data[] = array('accid' => 'USNJ0550', 'name' => 'West Long Branch');
$city_data[] = array('accid' => 'USNJ0551', 'name' => 'West Milford');
$city_data[] = array('accid' => 'USNJ0552', 'name' => 'West New York');
$city_data[] = array('accid' => 'USNJ0553', 'name' => 'West Orange');
$city_data[] = array('accid' => 'USNJ0554', 'name' => 'Westfield');
$city_data[] = array('accid' => 'USNJ0555', 'name' => 'Westville');
$city_data[] = array('accid' => 'USNJ0556', 'name' => 'Westwood');
$city_data[] = array('accid' => 'USNJ0557', 'name' => 'Wharton');
$city_data[] = array('accid' => 'USNJ0558', 'name' => 'Whippany');
$city_data[] = array('accid' => 'USNJ0559', 'name' => 'Whitehouse');
$city_data[] = array('accid' => 'USNJ0560', 'name' => 'Whitehouse Station');
$city_data[] = array('accid' => 'USNJ0561', 'name' => 'Whitesboro');
$city_data[] = array('accid' => 'USNJ0562', 'name' => 'Whiting');
$city_data[] = array('accid' => 'USNJ0563', 'name' => 'Wickatunk');
$city_data[] = array('accid' => 'USNJ0564', 'name' => 'Wildwood');
$city_data[] = array('accid' => 'USNJ0565', 'name' => 'Williamstown');
$city_data[] = array('accid' => 'USNJ0566', 'name' => 'Willingboro');
$city_data[] = array('accid' => 'USNJ0567', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USNJ0568', 'name' => 'Winslow');
$city_data[] = array('accid' => 'USNJ0569', 'name' => 'Wood Ridge');
$city_data[] = array('accid' => 'USNJ0570', 'name' => 'Woodbine');
$city_data[] = array('accid' => 'USNJ0571', 'name' => 'Woodbridge');
$city_data[] = array('accid' => 'USNJ0572', 'name' => 'Woodbury');
$city_data[] = array('accid' => 'USNJ0573', 'name' => 'Woodbury Heights');
$city_data[] = array('accid' => 'USNJ0586', 'name' => 'Woodcliff Lake');
$city_data[] = array('accid' => 'USNJ0574', 'name' => 'Woodstown');
$city_data[] = array('accid' => 'USNJ0575', 'name' => 'Wrightstown');
$city_data[] = array('accid' => 'USNJ0576', 'name' => 'Wyckoff');
$city_data[] = array('accid' => 'USNJ0577', 'name' => 'Zarephath');

?>
