<?php

// City package for USA: New Mexico 

$city_name = 'USA: New Mexico';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USNM0001', 'name' => 'Abiquiu');
$city_data[] = array('accid' => 'USNM0002', 'name' => 'Alamogordo');
$city_data[] = array('accid' => 'USNM0004', 'name' => 'Albuquerque');
$city_data[] = array('accid' => 'USNM0006', 'name' => 'Alcalde');
$city_data[] = array('accid' => 'USNM0007', 'name' => 'Algodones');
$city_data[] = array('accid' => 'USNM0008', 'name' => 'Alto');
$city_data[] = array('accid' => 'USNM0009', 'name' => 'Amalia');
$city_data[] = array('accid' => 'USNM0010', 'name' => 'Amistad');
$city_data[] = array('accid' => 'USNM0011', 'name' => 'Angel Fire');
$city_data[] = array('accid' => 'USNM0013', 'name' => 'Animas');
$city_data[] = array('accid' => 'USNM0014', 'name' => 'Anthony');
$city_data[] = array('accid' => 'USNM0015', 'name' => 'Anton Chico');
$city_data[] = array('accid' => 'USNM0016', 'name' => 'Aragon');
$city_data[] = array('accid' => 'USNM0017', 'name' => 'Arenas Valley');
$city_data[] = array('accid' => 'USNM0018', 'name' => 'Arrey');
$city_data[] = array('accid' => 'USNM0019', 'name' => 'Arroyo Hondo');
$city_data[] = array('accid' => 'USNM0020', 'name' => 'Arroyo Seco');
$city_data[] = array('accid' => 'USNM0021', 'name' => 'Artesia');
$city_data[] = array('accid' => 'USNM0022', 'name' => 'Aztec');
$city_data[] = array('accid' => 'USNM0023', 'name' => 'Bard');
$city_data[] = array('accid' => 'USNM0024', 'name' => 'Bayard');
$city_data[] = array('accid' => 'USNM0025', 'name' => 'Belen');
$city_data[] = array('accid' => 'USNM0026', 'name' => 'Bell Ranch');
$city_data[] = array('accid' => 'USNM0027', 'name' => 'Bent');
$city_data[] = array('accid' => 'USNM0028', 'name' => 'Berino');
$city_data[] = array('accid' => 'USNM0029', 'name' => 'Bernalillo');
$city_data[] = array('accid' => 'USNM0030', 'name' => 'Blanco');
$city_data[] = array('accid' => 'USNM0031', 'name' => 'Bloomfield');
$city_data[] = array('accid' => 'USNM0032', 'name' => 'Bluewater');
$city_data[] = array('accid' => 'USNM0033', 'name' => 'Bosque');
$city_data[] = array('accid' => 'USNM0034', 'name' => 'Bosque Farms');
$city_data[] = array('accid' => 'USNM0035', 'name' => 'Brimhall');
$city_data[] = array('accid' => 'USNM0036', 'name' => 'Broadview');
$city_data[] = array('accid' => 'USNM0037', 'name' => 'Buckhorn');
$city_data[] = array('accid' => 'USNM0038', 'name' => 'Buena Vista');
$city_data[] = array('accid' => 'USNM0039', 'name' => 'Caballo');
$city_data[] = array('accid' => 'USNM0040', 'name' => 'Canjilon');
$city_data[] = array('accid' => 'USNM0041', 'name' => 'Cannon AFB');
$city_data[] = array('accid' => 'USNM0042', 'name' => 'Canones');
$city_data[] = array('accid' => 'USNM0043', 'name' => 'Capitan');
$city_data[] = array('accid' => 'USNM0044', 'name' => 'Caprock');
$city_data[] = array('accid' => 'USNM0045', 'name' => 'Capulin');
$city_data[] = array('accid' => 'USNM0046', 'name' => 'Carlsbad');
$city_data[] = array('accid' => 'USNM0048', 'name' => 'Carrizozo');
$city_data[] = array('accid' => 'USNM0049', 'name' => 'Carson');
$city_data[] = array('accid' => 'USNM0050', 'name' => 'Casa Blanca');
$city_data[] = array('accid' => 'USNM0051', 'name' => 'Causey');
$city_data[] = array('accid' => 'USNM0052', 'name' => 'Cebolla');
$city_data[] = array('accid' => 'USNM0053', 'name' => 'Cedar Crest');
$city_data[] = array('accid' => 'USNM0054', 'name' => 'Cedarvale');
$city_data[] = array('accid' => 'USNM0055', 'name' => 'Cerrillos');
$city_data[] = array('accid' => 'USNM0056', 'name' => 'Cerro');
$city_data[] = array('accid' => 'USNM0057', 'name' => 'Chacon');
$city_data[] = array('accid' => 'USNM0058', 'name' => 'Chama');
$city_data[] = array('accid' => 'USNM0059', 'name' => 'Chamberino');
$city_data[] = array('accid' => 'USNM0060', 'name' => 'Chamisal');
$city_data[] = array('accid' => 'USNM0361', 'name' => 'Chaparral');
$city_data[] = array('accid' => 'USNM0061', 'name' => 'Chimayo');
$city_data[] = array('accid' => 'USNM0062', 'name' => 'Church Rock');
$city_data[] = array('accid' => 'USNM0063', 'name' => 'Cimarron');
$city_data[] = array('accid' => 'USNM0064', 'name' => 'Claunch');
$city_data[] = array('accid' => 'USNM0065', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USNM0066', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USNM0067', 'name' => 'Cliff');
$city_data[] = array('accid' => 'USNM0068', 'name' => 'Clines Corners');
$city_data[] = array('accid' => 'USNM0069', 'name' => 'Cloudcroft');
$city_data[] = array('accid' => 'USNM0070', 'name' => 'Clovis');
$city_data[] = array('accid' => 'USNM0072', 'name' => 'Cochiti Lake');
$city_data[] = array('accid' => 'USNM0073', 'name' => 'Cochiti Pueblo');
$city_data[] = array('accid' => 'USNM0074', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USNM0075', 'name' => 'Conchas Dam');
$city_data[] = array('accid' => 'USNM0076', 'name' => 'Continental Divide');
$city_data[] = array('accid' => 'USNM0077', 'name' => 'Cordova');
$city_data[] = array('accid' => 'USNM0078', 'name' => 'Corona');
$city_data[] = array('accid' => 'USNM0079', 'name' => 'Corrales');
$city_data[] = array('accid' => 'USNM0080', 'name' => 'Costilla');
$city_data[] = array('accid' => 'USNM0081', 'name' => 'Counselor');
$city_data[] = array('accid' => 'USNM0082', 'name' => 'Coyote');
$city_data[] = array('accid' => 'USNM0083', 'name' => 'Crossroads');
$city_data[] = array('accid' => 'USNM0084', 'name' => 'Crownpoint');
$city_data[] = array('accid' => 'USNM0085', 'name' => 'Cuba');
$city_data[] = array('accid' => 'USNM0086', 'name' => 'Cubero');
$city_data[] = array('accid' => 'USNM0087', 'name' => 'Cuervo');
$city_data[] = array('accid' => 'USNM0088', 'name' => 'Datil');
$city_data[] = array('accid' => 'USNM0089', 'name' => 'Deming');
$city_data[] = array('accid' => 'USNM0090', 'name' => 'Derry');
$city_data[] = array('accid' => 'USNM0091', 'name' => 'Des Moines');
$city_data[] = array('accid' => 'USNM0092', 'name' => 'Dexter');
$city_data[] = array('accid' => 'USNM0093', 'name' => 'Dixon');
$city_data[] = array('accid' => 'USNM0094', 'name' => 'Dona Ana');
$city_data[] = array('accid' => 'USNM0095', 'name' => 'Dora');
$city_data[] = array('accid' => 'USNM0096', 'name' => 'Dulce');
$city_data[] = array('accid' => 'USNM0097', 'name' => 'Eagle Nest');
$city_data[] = array('accid' => 'USNM0098', 'name' => 'Edgewood');
$city_data[] = array('accid' => 'USNM0099', 'name' => 'El Prado');
$city_data[] = array('accid' => 'USNM0100', 'name' => 'El Rito');
$city_data[] = array('accid' => 'USNM0101', 'name' => 'Elephant Butte');
$city_data[] = array('accid' => 'USNM0102', 'name' => 'Elida');
$city_data[] = array('accid' => 'USNM0103', 'name' => 'Embudo');
$city_data[] = array('accid' => 'USNM0104', 'name' => 'Encino');
$city_data[] = array('accid' => 'USNM0105', 'name' => 'Espanola');
$city_data[] = array('accid' => 'USNM0106', 'name' => 'Estancia');
$city_data[] = array('accid' => 'USNM0107', 'name' => 'Eunice');
$city_data[] = array('accid' => 'USNM0108', 'name' => 'Fairacres');
$city_data[] = array('accid' => 'USNM0109', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USNM0110', 'name' => 'Faywood');
$city_data[] = array('accid' => 'USNM0111', 'name' => 'Fence Lake');
$city_data[] = array('accid' => 'USNM0112', 'name' => 'Flora Vista');
$city_data[] = array('accid' => 'USNM0113', 'name' => 'Floyd');
$city_data[] = array('accid' => 'USNM0114', 'name' => 'Folsom');
$city_data[] = array('accid' => 'USNM0115', 'name' => 'Fort Bayard');
$city_data[] = array('accid' => 'USNM0116', 'name' => 'Fort Stanton');
$city_data[] = array('accid' => 'USNM0117', 'name' => 'Fort Sumner');
$city_data[] = array('accid' => 'USNM0118', 'name' => 'Fort Wingate');
$city_data[] = array('accid' => 'USNM0119', 'name' => 'Fruitland');
$city_data[] = array('accid' => 'USNM0120', 'name' => 'Gallina');
$city_data[] = array('accid' => 'USNM0121', 'name' => 'Gallup');
$city_data[] = array('accid' => 'USNM0122', 'name' => 'Gamerco');
$city_data[] = array('accid' => 'USNM0123', 'name' => 'Garfield');
$city_data[] = array('accid' => 'USNM0124', 'name' => 'Garita');
$city_data[] = array('accid' => 'USNM0125', 'name' => 'Gila');
$city_data[] = array('accid' => 'USNM0126', 'name' => 'Gladstone');
$city_data[] = array('accid' => 'USNM0127', 'name' => 'Glencoe');
$city_data[] = array('accid' => 'USNM0128', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USNM0129', 'name' => 'Glorieta');
$city_data[] = array('accid' => 'USNM0130', 'name' => 'Grady');
$city_data[] = array('accid' => 'USNM0131', 'name' => 'Grants');
$city_data[] = array('accid' => 'USNM0132', 'name' => 'Grenville');
$city_data[] = array('accid' => 'USNM0133', 'name' => 'Guadalupita');
$city_data[] = array('accid' => 'USNM0134', 'name' => 'Hachita');
$city_data[] = array('accid' => 'USNM0135', 'name' => 'Hagerman');
$city_data[] = array('accid' => 'USNM0136', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USNM0137', 'name' => 'Hatch');
$city_data[] = array('accid' => 'USNM0138', 'name' => 'Hernandez');
$city_data[] = array('accid' => 'USNM0139', 'name' => 'High Rolls Mountain Park');
$city_data[] = array('accid' => 'USNM0140', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USNM0141', 'name' => 'Hobbs');
$city_data[] = array('accid' => 'USNM0142', 'name' => 'Holloman AFB');
$city_data[] = array('accid' => 'USNM0143', 'name' => 'Holman');
$city_data[] = array('accid' => 'USNM0144', 'name' => 'Hondo');
$city_data[] = array('accid' => 'USNM0145', 'name' => 'Hope');
$city_data[] = array('accid' => 'USNM0146', 'name' => 'House');
$city_data[] = array('accid' => 'USNM0147', 'name' => 'Hurley');
$city_data[] = array('accid' => 'USNM0148', 'name' => 'Ilfeld');
$city_data[] = array('accid' => 'USNM0149', 'name' => 'Isleta');
$city_data[] = array('accid' => 'USNM0150', 'name' => 'Jal');
$city_data[] = array('accid' => 'USNM0151', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USNM0152', 'name' => 'Jarales');
$city_data[] = array('accid' => 'USNM0153', 'name' => 'Jemez Pueblo');
$city_data[] = array('accid' => 'USNM0154', 'name' => 'Jemez Springs');
$city_data[] = array('accid' => 'USNM0155', 'name' => 'Kenna');
$city_data[] = array('accid' => 'USNM0156', 'name' => 'Kirtland');
$city_data[] = array('accid' => 'USNM0157', 'name' => 'Kirtland AFB');
$city_data[] = array('accid' => 'USNM0158', 'name' => 'La Jara');
$city_data[] = array('accid' => 'USNM0159', 'name' => 'La Joya');
$city_data[] = array('accid' => 'USNM0160', 'name' => 'La Loma');
$city_data[] = array('accid' => 'USNM0161', 'name' => 'La Luz');
$city_data[] = array('accid' => 'USNM0162', 'name' => 'La Madera');
$city_data[] = array('accid' => 'USNM0163', 'name' => 'La Mesa');
$city_data[] = array('accid' => 'USNM0164', 'name' => 'La Plata');
$city_data[] = array('accid' => 'USNM0165', 'name' => 'Laguna');
$city_data[] = array('accid' => 'USNM0166', 'name' => 'Lake Arthur');
$city_data[] = array('accid' => 'USNM0167', 'name' => 'Lakewood');
$city_data[] = array('accid' => 'USNM0168', 'name' => 'Lamy');
$city_data[] = array('accid' => 'USNM0169', 'name' => 'Las Cruces');
$city_data[] = array('accid' => 'USNM0170', 'name' => 'Las Vegas');
$city_data[] = array('accid' => 'USNM0171', 'name' => 'Lemitar');
$city_data[] = array('accid' => 'USNM0172', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USNM0173', 'name' => 'Lindrith');
$city_data[] = array('accid' => 'USNM0174', 'name' => 'Lingo');
$city_data[] = array('accid' => 'USNM0175', 'name' => 'Llano');
$city_data[] = array('accid' => 'USNM0176', 'name' => 'Loco Hills');
$city_data[] = array('accid' => 'USNM0177', 'name' => 'Logan');
$city_data[] = array('accid' => 'USNM0178', 'name' => 'Lordsburg');
$city_data[] = array('accid' => 'USNM0179', 'name' => 'Los Alamos');
$city_data[] = array('accid' => 'USNM0180', 'name' => 'Los Lunas');
$city_data[] = array('accid' => 'USNM0181', 'name' => 'Los Ojos');
$city_data[] = array('accid' => 'USNM0182', 'name' => 'Loving');
$city_data[] = array('accid' => 'USNM0183', 'name' => 'Lovington');
$city_data[] = array('accid' => 'USNM0184', 'name' => 'Luna');
$city_data[] = array('accid' => 'USNM0185', 'name' => 'Magdalena');
$city_data[] = array('accid' => 'USNM0186', 'name' => 'Malaga');
$city_data[] = array('accid' => 'USNM0187', 'name' => 'Maljamar');
$city_data[] = array('accid' => 'USNM0188', 'name' => 'Maxwell');
$city_data[] = array('accid' => 'USNM0189', 'name' => 'Mayhill');
$city_data[] = array('accid' => 'USNM0190', 'name' => 'McAlister');
$city_data[] = array('accid' => 'USNM0191', 'name' => 'McDonald');
$city_data[] = array('accid' => 'USNM0192', 'name' => 'McIntosh');
$city_data[] = array('accid' => 'USNM0193', 'name' => 'Medanales');
$city_data[] = array('accid' => 'USNM0194', 'name' => 'Melrose');
$city_data[] = array('accid' => 'USNM0195', 'name' => 'Mentmore');
$city_data[] = array('accid' => 'USNM0196', 'name' => 'Mescalero');
$city_data[] = array('accid' => 'USNM0197', 'name' => 'Mesilla');
$city_data[] = array('accid' => 'USNM0198', 'name' => 'Mesilla Park');
$city_data[] = array('accid' => 'USNM0199', 'name' => 'Mesquite');
$city_data[] = array('accid' => 'USNM0200', 'name' => 'Mexican Springs');
$city_data[] = array('accid' => 'USNM0201', 'name' => 'Miami');
$city_data[] = array('accid' => 'USNM0202', 'name' => 'Milan');
$city_data[] = array('accid' => 'USNM0203', 'name' => 'Mills');
$city_data[] = array('accid' => 'USNM0204', 'name' => 'Milnesand');
$city_data[] = array('accid' => 'USNM0205', 'name' => 'Mimbres');
$city_data[] = array('accid' => 'USNM0206', 'name' => 'Montezuma');
$city_data[] = array('accid' => 'USNM0207', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USNM0208', 'name' => 'Monument');
$city_data[] = array('accid' => 'USNM0209', 'name' => 'Mora');
$city_data[] = array('accid' => 'USNM0210', 'name' => 'Moriarty');
$city_data[] = array('accid' => 'USNM0211', 'name' => 'Mosquero');
$city_data[] = array('accid' => 'USNM0212', 'name' => 'Mount Dora');
$city_data[] = array('accid' => 'USNM0213', 'name' => 'Mountainair');
$city_data[] = array('accid' => 'USNM0214', 'name' => 'Mule Creek');
$city_data[] = array('accid' => 'USNM0215', 'name' => 'Nageezi');
$city_data[] = array('accid' => 'USNM0216', 'name' => 'Nara Visa');
$city_data[] = array('accid' => 'USNM0217', 'name' => 'Navajo');
$city_data[] = array('accid' => 'USNM0218', 'name' => 'Navajo Dam');
$city_data[] = array('accid' => 'USNM0219', 'name' => 'New Laguna');
$city_data[] = array('accid' => 'USNM0220', 'name' => 'Newcomb');
$city_data[] = array('accid' => 'USNM0221', 'name' => 'Newkirk');
$city_data[] = array('accid' => 'USNM0222', 'name' => 'Nogal');
$city_data[] = array('accid' => 'USNM0223', 'name' => 'Ocate');
$city_data[] = array('accid' => 'USNM0224', 'name' => 'Ojo Caliente');
$city_data[] = array('accid' => 'USNM0225', 'name' => 'Ojo Feliz');
$city_data[] = array('accid' => 'USNM0226', 'name' => 'Organ');
$city_data[] = array('accid' => 'USNM0227', 'name' => 'Orogrande');
$city_data[] = array('accid' => 'USNM0228', 'name' => 'Paguate');
$city_data[] = array('accid' => 'USNM0229', 'name' => 'Pecos');
$city_data[] = array('accid' => 'USNM0230', 'name' => 'Pena Blanca');
$city_data[] = array('accid' => 'USNM0231', 'name' => 'Penasco');
$city_data[] = array('accid' => 'USNM0232', 'name' => 'Pep');
$city_data[] = array('accid' => 'USNM0233', 'name' => 'Peralta');
$city_data[] = array('accid' => 'USNM0234', 'name' => 'Petaca');
$city_data[] = array('accid' => 'USNM0235', 'name' => 'Picacho');
$city_data[] = array('accid' => 'USNM0236', 'name' => 'Pie Town');
$city_data[] = array('accid' => 'USNM0237', 'name' => 'Pinehill');
$city_data[] = array('accid' => 'USNM0238', 'name' => 'Pinon');
$city_data[] = array('accid' => 'USNM0239', 'name' => 'Pinos Altos');
$city_data[] = array('accid' => 'USNM0240', 'name' => 'Placitas');
$city_data[] = array('accid' => 'USNM0241', 'name' => 'Playas');
$city_data[] = array('accid' => 'USNM0242', 'name' => 'Polvadera');
$city_data[] = array('accid' => 'USNM0243', 'name' => 'Ponderosa');
$city_data[] = array('accid' => 'USNM0244', 'name' => 'Portales');
$city_data[] = array('accid' => 'USNM0245', 'name' => 'Prewitt');
$city_data[] = array('accid' => 'USNM0246', 'name' => 'Pueblo Of Acoma');
$city_data[] = array('accid' => 'USNM0247', 'name' => 'Quay');
$city_data[] = array('accid' => 'USNM0248', 'name' => 'Quemado');
$city_data[] = array('accid' => 'USNM0249', 'name' => 'Questa');
$city_data[] = array('accid' => 'USNM0250', 'name' => 'Radium Springs');
$city_data[] = array('accid' => 'USNM0251', 'name' => 'Rainsville');
$city_data[] = array('accid' => 'USNM0252', 'name' => 'Ramah');
$city_data[] = array('accid' => 'USNM0253', 'name' => 'Ranchos de Taos');
$city_data[] = array('accid' => 'USNM0254', 'name' => 'Raton');
$city_data[] = array('accid' => 'USNM0255', 'name' => 'Red River');
$city_data[] = array('accid' => 'USNM0257', 'name' => 'Redrock');
$city_data[] = array('accid' => 'USNM0258', 'name' => 'Regina');
$city_data[] = array('accid' => 'USNM0259', 'name' => 'Rehoboth');
$city_data[] = array('accid' => 'USNM0260', 'name' => 'Reserve');
$city_data[] = array('accid' => 'USNM0261', 'name' => 'Ribera');
$city_data[] = array('accid' => 'USNM0262', 'name' => 'Rincon');
$city_data[] = array('accid' => 'USNM0263', 'name' => 'Rio Rancho');
$city_data[] = array('accid' => 'USNM0264', 'name' => 'Rociada');
$city_data[] = array('accid' => 'USNM0265', 'name' => 'Rodeo');
$city_data[] = array('accid' => 'USNM0266', 'name' => 'Rogers');
$city_data[] = array('accid' => 'USNM0267', 'name' => 'Roswell');
$city_data[] = array('accid' => 'USNM0268', 'name' => 'Rowe');
$city_data[] = array('accid' => 'USNM0269', 'name' => 'Roy');
$city_data[] = array('accid' => 'USNM0270', 'name' => 'Ruidoso');
$city_data[] = array('accid' => 'USNM0271', 'name' => 'Ruidoso Downs');
$city_data[] = array('accid' => 'USNM0272', 'name' => 'Sacramento');
$city_data[] = array('accid' => 'USNM0273', 'name' => 'Saint Vrain');
$city_data[] = array('accid' => 'USNM0274', 'name' => 'Salem');
$city_data[] = array('accid' => 'USNM0275', 'name' => 'San Acacia');
$city_data[] = array('accid' => 'USNM0276', 'name' => 'San Antonio');
$city_data[] = array('accid' => 'USNM0277', 'name' => 'San Cristobal');
$city_data[] = array('accid' => 'USNM0278', 'name' => 'San Fidel');
$city_data[] = array('accid' => 'USNM0279', 'name' => 'San Jon');
$city_data[] = array('accid' => 'USNM0280', 'name' => 'San Jose');
$city_data[] = array('accid' => 'USNM0281', 'name' => 'San Juan Pueblo');
$city_data[] = array('accid' => 'USNM0282', 'name' => 'San Miguel');
$city_data[] = array('accid' => 'USNM0283', 'name' => 'San Patricio');
$city_data[] = array('accid' => 'USNM0284', 'name' => 'San Rafael');
$city_data[] = array('accid' => 'USNM0285', 'name' => 'San Ysidro');
$city_data[] = array('accid' => 'USNM0286', 'name' => 'Sandia Park');
$city_data[] = array('accid' => 'USNM0288', 'name' => 'Sanostee');
$city_data[] = array('accid' => 'USNM0289', 'name' => 'Santa Clara');
$city_data[] = array('accid' => 'USNM0290', 'name' => 'Santa Cruz');
$city_data[] = array('accid' => 'USNM0292', 'name' => 'Santa Fe');
$city_data[] = array('accid' => 'USNM0293', 'name' => 'Santa Rosa');
$city_data[] = array('accid' => 'USNM0294', 'name' => 'Santa Teresa');
$city_data[] = array('accid' => 'USNM0295', 'name' => 'Santo Domingo Pueblo');
$city_data[] = array('accid' => 'USNM0296', 'name' => 'Sapello');
$city_data[] = array('accid' => 'USNM0297', 'name' => 'Sedan');
$city_data[] = array('accid' => 'USNM0298', 'name' => 'Seneca');
$city_data[] = array('accid' => 'USNM0299', 'name' => 'Serafina');
$city_data[] = array('accid' => 'USNM0300', 'name' => 'Sheep Springs');
$city_data[] = array('accid' => 'USNM0301', 'name' => 'Shiprock');
$city_data[] = array('accid' => 'USNM0302', 'name' => 'Silver City');
$city_data[] = array('accid' => 'USNM0305', 'name' => 'Smith Lake');
$city_data[] = array('accid' => 'USNM0306', 'name' => 'Socorro');
$city_data[] = array('accid' => 'USNM0307', 'name' => 'Solano');
$city_data[] = array('accid' => 'USNM0308', 'name' => 'Springer');
$city_data[] = array('accid' => 'USNM0309', 'name' => 'Stanley');
$city_data[] = array('accid' => 'USNM0310', 'name' => 'Sunland Park');
$city_data[] = array('accid' => 'USNM0311', 'name' => 'Sunspot');
$city_data[] = array('accid' => 'USNM0312', 'name' => 'Taiban');
$city_data[] = array('accid' => 'USNM0313', 'name' => 'Tajique');
$city_data[] = array('accid' => 'USNM0314', 'name' => 'Taos');
$city_data[] = array('accid' => 'USNM0315', 'name' => 'Taos Ski Valley');
$city_data[] = array('accid' => 'USNM0316', 'name' => 'Tatum');
$city_data[] = array('accid' => 'USNM0317', 'name' => 'Tererro');
$city_data[] = array('accid' => 'USNM0318', 'name' => 'Tesuque');
$city_data[] = array('accid' => 'USNM0319', 'name' => 'Texico');
$city_data[] = array('accid' => 'USNM0320', 'name' => 'Thoreau');
$city_data[] = array('accid' => 'USNM0321', 'name' => 'Tierra Amarilla');
$city_data[] = array('accid' => 'USNM0322', 'name' => 'Tijeras');
$city_data[] = array('accid' => 'USNM0323', 'name' => 'Timberon');
$city_data[] = array('accid' => 'USNM0324', 'name' => 'Tinnie');
$city_data[] = array('accid' => 'USNM0325', 'name' => 'Tohatchi');
$city_data[] = array('accid' => 'USNM0326', 'name' => 'Tome');
$city_data[] = array('accid' => 'USNM0327', 'name' => 'Torreon');
$city_data[] = array('accid' => 'USNM0328', 'name' => 'Trampas');
$city_data[] = array('accid' => 'USNM0329', 'name' => 'Trementina');
$city_data[] = array('accid' => 'USNM0330', 'name' => 'Tres Piedras');
$city_data[] = array('accid' => 'USNM0331', 'name' => 'Truchas');
$city_data[] = array('accid' => 'USNM0332', 'name' => 'Truth Or Consequences');
$city_data[] = array('accid' => 'USNM0333', 'name' => 'Tucumcari');
$city_data[] = array('accid' => 'USNM0334', 'name' => 'Tularosa');
$city_data[] = array('accid' => 'USNM0335', 'name' => 'Tyrone');
$city_data[] = array('accid' => 'USNM0336', 'name' => 'Ute Park');
$city_data[] = array('accid' => 'USNM0337', 'name' => 'Vadito');
$city_data[] = array('accid' => 'USNM0338', 'name' => 'Vado');
$city_data[] = array('accid' => 'USNM0339', 'name' => 'Valdez');
$city_data[] = array('accid' => 'USNM0340', 'name' => 'Vallecitos');
$city_data[] = array('accid' => 'USNM0341', 'name' => 'Valmora');
$city_data[] = array('accid' => 'USNM0342', 'name' => 'Vanderwagen');
$city_data[] = array('accid' => 'USNM0343', 'name' => 'Vaughn');
$city_data[] = array('accid' => 'USNM0344', 'name' => 'Veguita');
$city_data[] = array('accid' => 'USNM0345', 'name' => 'Velarde');
$city_data[] = array('accid' => 'USNM0346', 'name' => 'Villanueva');
$city_data[] = array('accid' => 'USNM0347', 'name' => 'Wagon Mound');
$city_data[] = array('accid' => 'USNM0348', 'name' => 'Waterflow');
$city_data[] = array('accid' => 'USNM0349', 'name' => 'Watrous');
$city_data[] = array('accid' => 'USNM0350', 'name' => 'Weed');
$city_data[] = array('accid' => 'USNM0351', 'name' => 'White Sands Missile Range');
$city_data[] = array('accid' => 'USNM0353', 'name' => 'Whites City');
$city_data[] = array('accid' => 'USNM0354', 'name' => 'Willard');
$city_data[] = array('accid' => 'USNM0355', 'name' => 'Williamsburg');
$city_data[] = array('accid' => 'USNM0356', 'name' => 'Winston');
$city_data[] = array('accid' => 'USNM0357', 'name' => 'Yatahey');
$city_data[] = array('accid' => 'USNM0358', 'name' => 'Yeso');
$city_data[] = array('accid' => 'USNM0359', 'name' => 'Youngsville');
$city_data[] = array('accid' => 'USNM0360', 'name' => 'Zuni');

?>
