<?php

// City package for USA: Nevada 

$city_name = 'USA: Nevada';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USNV0001', 'name' => 'Alamo');
$city_data[] = array('accid' => 'USNV0002', 'name' => 'Amargosa Valley');
$city_data[] = array('accid' => 'USNV0004', 'name' => 'Austin');
$city_data[] = array('accid' => 'USNV0005', 'name' => 'Baker');
$city_data[] = array('accid' => 'USNV0006', 'name' => 'Battle Mountain');
$city_data[] = array('accid' => 'USNV0007', 'name' => 'Beatty');
$city_data[] = array('accid' => 'USNV0008', 'name' => 'Blue Diamond');
$city_data[] = array('accid' => 'USNV0009', 'name' => 'Boulder City');
$city_data[] = array('accid' => 'USNV0010', 'name' => 'Bunkerville');
$city_data[] = array('accid' => 'USNV0011', 'name' => 'Cal Nev Ari');
$city_data[] = array('accid' => 'USNV0012', 'name' => 'Caliente');
$city_data[] = array('accid' => 'USNV0013', 'name' => 'Carlin');
$city_data[] = array('accid' => 'USNV0014', 'name' => 'Carson City');
$city_data[] = array('accid' => 'USNV0015', 'name' => 'Crescent Valley');
$city_data[] = array('accid' => 'USNV0016', 'name' => 'Crystal Bay');
$city_data[] = array('accid' => 'USNV0017', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USNV0018', 'name' => 'Deeth');
$city_data[] = array('accid' => 'USNV0019', 'name' => 'Denio');
$city_data[] = array('accid' => 'USNV0021', 'name' => 'Duckwater');
$city_data[] = array('accid' => 'USNV0022', 'name' => 'Dyer');
$city_data[] = array('accid' => 'USNV0024', 'name' => 'Elko');
$city_data[] = array('accid' => 'USNV0025', 'name' => 'Ely');
$city_data[] = array('accid' => 'USNV0026', 'name' => 'Empire');
$city_data[] = array('accid' => 'USNV0027', 'name' => 'Eureka');
$city_data[] = array('accid' => 'USNV0028', 'name' => 'Fallon');
$city_data[] = array('accid' => 'USNV0029', 'name' => 'Fernley');
$city_data[] = array('accid' => 'USNV0030', 'name' => 'Gabbs');
$city_data[] = array('accid' => 'USNV0031', 'name' => 'Gardnerville');
$city_data[] = array('accid' => 'USNV0032', 'name' => 'Genoa');
$city_data[] = array('accid' => 'USNV0033', 'name' => 'Gerlach');
$city_data[] = array('accid' => 'USNV0034', 'name' => 'Glenbrook');
$city_data[] = array('accid' => 'USNV0035', 'name' => 'Golconda');
$city_data[] = array('accid' => 'USNV0036', 'name' => 'Goldfield');
$city_data[] = array('accid' => 'USNV0038', 'name' => 'Halleck');
$city_data[] = array('accid' => 'USNV0039', 'name' => 'Hawthorne');
$city_data[] = array('accid' => 'USNV0040', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USNV0041', 'name' => 'Hiko');
$city_data[] = array('accid' => 'USNV0042', 'name' => 'Imlay');
$city_data[] = array('accid' => 'USNV0043', 'name' => 'Incline Village');
$city_data[] = array('accid' => 'USNV0044', 'name' => 'Indian Springs');
$city_data[] = array('accid' => 'USNV0045', 'name' => 'Jackpot');
$city_data[] = array('accid' => 'USNV0046', 'name' => 'Jarbidge');
$city_data[] = array('accid' => 'USNV0047', 'name' => 'Jean');
$city_data[] = array('accid' => 'USNV0048', 'name' => 'Lamoille');
$city_data[] = array('accid' => 'USNV0049', 'name' => 'Las Vegas');
$city_data[] = array('accid' => 'USNV0051', 'name' => 'Laughlin');
$city_data[] = array('accid' => 'USNV0052', 'name' => 'Logandale');
$city_data[] = array('accid' => 'USNV0053', 'name' => 'Lovelock');
$city_data[] = array('accid' => 'USNV0054', 'name' => 'Lund');
$city_data[] = array('accid' => 'USNV0055', 'name' => 'Luning');
$city_data[] = array('accid' => 'USNV0056', 'name' => 'Manhattan');
$city_data[] = array('accid' => 'USNV0057', 'name' => 'McDermitt');
$city_data[] = array('accid' => 'USNV0058', 'name' => 'McGill');
$city_data[] = array('accid' => 'USNV0059', 'name' => 'Mercury');
$city_data[] = array('accid' => 'USNV0060', 'name' => 'Mesquite');
$city_data[] = array('accid' => 'USNV0061', 'name' => 'Mina');
$city_data[] = array('accid' => 'USNV0062', 'name' => 'Minden');
$city_data[] = array('accid' => 'USNV0063', 'name' => 'Moapa');
$city_data[] = array('accid' => 'USNV0064', 'name' => 'Montello');
$city_data[] = array('accid' => 'USNV0065', 'name' => 'Mountain City');
$city_data[] = array('accid' => 'USNV0066', 'name' => 'Nellis AFB');
$city_data[] = array('accid' => 'USNV0067', 'name' => 'Nixon');
$city_data[] = array('accid' => 'USNV0068', 'name' => 'North Las Vegas');
$city_data[] = array('accid' => 'USNV0069', 'name' => 'Orovada');
$city_data[] = array('accid' => 'USNV0070', 'name' => 'Overton');
$city_data[] = array('accid' => 'USNV0071', 'name' => 'Owyhee');
$city_data[] = array('accid' => 'USNV0072', 'name' => 'Pahrump');
$city_data[] = array('accid' => 'USNV0073', 'name' => 'Panaca');
$city_data[] = array('accid' => 'USNV0074', 'name' => 'Paradise Valley');
$city_data[] = array('accid' => 'USNV0075', 'name' => 'Pioche');
$city_data[] = array('accid' => 'USNV0076', 'name' => 'Reno');
$city_data[] = array('accid' => 'USNV0077', 'name' => 'Round Mountain');
$city_data[] = array('accid' => 'USNV0078', 'name' => 'Ruby Valley');
$city_data[] = array('accid' => 'USNV0079', 'name' => 'Ruth');
$city_data[] = array('accid' => 'USNV0080', 'name' => 'Schurz');
$city_data[] = array('accid' => 'USNV0081', 'name' => 'Searchlight');
$city_data[] = array('accid' => 'USNV0082', 'name' => 'Silver City');
$city_data[] = array('accid' => 'USNV0083', 'name' => 'Silver Springs');
$city_data[] = array('accid' => 'USNV0084', 'name' => 'Silverpeak');
$city_data[] = array('accid' => 'USNV0085', 'name' => 'Smith');
$city_data[] = array('accid' => 'USNV0086', 'name' => 'Sparks');
$city_data[] = array('accid' => 'USNV0087', 'name' => 'Spring Creek');
$city_data[] = array('accid' => 'USNV0088', 'name' => 'Stateline');
$city_data[] = array('accid' => 'USNV0089', 'name' => 'Sun Valley');
$city_data[] = array('accid' => 'USNV0090', 'name' => 'The Lakes');
$city_data[] = array('accid' => 'USNV0091', 'name' => 'Tonopah');
$city_data[] = array('accid' => 'USNV0092', 'name' => 'Tuscarora');
$city_data[] = array('accid' => 'USNV0093', 'name' => 'Valmy');
$city_data[] = array('accid' => 'USNV0094', 'name' => 'Verdi');
$city_data[] = array('accid' => 'USNV0095', 'name' => 'Virginia City');
$city_data[] = array('accid' => 'USNV0096', 'name' => 'Wadsworth');
$city_data[] = array('accid' => 'USNV0097', 'name' => 'Washoe Valley');
$city_data[] = array('accid' => 'USNV0098', 'name' => 'Wellington');
$city_data[] = array('accid' => 'USNV0099', 'name' => 'Wells');
$city_data[] = array('accid' => 'USNV0100', 'name' => 'West Wendover');
$city_data[] = array('accid' => 'USNV0101', 'name' => 'Winnemucca');
$city_data[] = array('accid' => 'USNV0102', 'name' => 'Yerington');
$city_data[] = array('accid' => 'USNV0103', 'name' => 'Zephyr Cove');

?>
