<?php

// City package for USA: Oregon

$city_name = 'USA: Oregon';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USOR0001', 'name' => 'Adams');
$city_data[] = array('accid' => 'USOR0002', 'name' => 'Adel');
$city_data[] = array('accid' => 'USOR0003', 'name' => 'Adrian');
$city_data[] = array('accid' => 'USOR0004', 'name' => 'Agness');
$city_data[] = array('accid' => 'USOR0005', 'name' => 'Albany');
$city_data[] = array('accid' => 'USOR0006', 'name' => 'Allegany');
$city_data[] = array('accid' => 'USOR0007', 'name' => 'Alsea');
$city_data[] = array('accid' => 'USOR0008', 'name' => 'Alvadore');
$city_data[] = array('accid' => 'USOR0009', 'name' => 'Amity');
$city_data[] = array('accid' => 'USOR0010', 'name' => 'Antelope');
$city_data[] = array('accid' => 'USOR0012', 'name' => 'Arch Cape');
$city_data[] = array('accid' => 'USOR0013', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USOR0014', 'name' => 'Arock');
$city_data[] = array('accid' => 'USOR0015', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USOR0016', 'name' => 'Ashwood');
$city_data[] = array('accid' => 'USOR0017', 'name' => 'Astoria');
$city_data[] = array('accid' => 'USOR0018', 'name' => 'Athena');
$city_data[] = array('accid' => 'USOR0019', 'name' => 'Aumsville');
$city_data[] = array('accid' => 'USOR0020', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USOR0021', 'name' => 'Azalea');
$city_data[] = array('accid' => 'USOR0022', 'name' => 'Baker City');
$city_data[] = array('accid' => 'USOR0023', 'name' => 'Bandon');
$city_data[] = array('accid' => 'USOR0024', 'name' => 'Banks');
$city_data[] = array('accid' => 'USOR0025', 'name' => 'Bates');
$city_data[] = array('accid' => 'USOR0026', 'name' => 'Bay City');
$city_data[] = array('accid' => 'USOR0027', 'name' => 'Beatty');
$city_data[] = array('accid' => 'USOR0028', 'name' => 'Beaver');
$city_data[] = array('accid' => 'USOR0029', 'name' => 'Beavercreek');
$city_data[] = array('accid' => 'USOR0030', 'name' => 'Beaverton');
$city_data[] = array('accid' => 'USOR0031', 'name' => 'Bend');
$city_data[] = array('accid' => 'USOR0032', 'name' => 'Blachly');
$city_data[] = array('accid' => 'USOR0033', 'name' => 'Blodgett');
$city_data[] = array('accid' => 'USOR0034', 'name' => 'Blue River');
$city_data[] = array('accid' => 'USOR0035', 'name' => 'Bly');
$city_data[] = array('accid' => 'USOR0036', 'name' => 'Boardman');
$city_data[] = array('accid' => 'USOR0037', 'name' => 'Bonanza');
$city_data[] = array('accid' => 'USOR0038', 'name' => 'Boring');
$city_data[] = array('accid' => 'USOR0039', 'name' => 'Bridal Veil');
$city_data[] = array('accid' => 'USOR0040', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USOR0041', 'name' => 'Brightwood');
$city_data[] = array('accid' => 'USOR0042', 'name' => 'Broadbent');
$city_data[] = array('accid' => 'USOR0043', 'name' => 'Brogan');
$city_data[] = array('accid' => 'USOR0044', 'name' => 'Brookings');
$city_data[] = array('accid' => 'USOR0045', 'name' => 'Brothers');
$city_data[] = array('accid' => 'USOR0046', 'name' => 'Brownsville');
$city_data[] = array('accid' => 'USOR0047', 'name' => 'Burns');
$city_data[] = array('accid' => 'USOR0048', 'name' => 'Butte Falls');
$city_data[] = array('accid' => 'USOR0049', 'name' => 'Buxton');
$city_data[] = array('accid' => 'USOR0050', 'name' => 'Camas Valley');
$city_data[] = array('accid' => 'USOR0051', 'name' => 'Camp Sherman');
$city_data[] = array('accid' => 'USOR0052', 'name' => 'Canby');
$city_data[] = array('accid' => 'USOR0053', 'name' => 'Cannon Beach');
$city_data[] = array('accid' => 'USOR0054', 'name' => 'Canyon City');
$city_data[] = array('accid' => 'USOR0055', 'name' => 'Canyonville');
$city_data[] = array('accid' => 'USOR0056', 'name' => 'Carlton');
$city_data[] = array('accid' => 'USOR0057', 'name' => 'Cascade Locks');
$city_data[] = array('accid' => 'USOR0058', 'name' => 'Cascadia');
$city_data[] = array('accid' => 'USOR0059', 'name' => 'Cave Junction');
$city_data[] = array('accid' => 'USOR0060', 'name' => 'Cayuse');
$city_data[] = array('accid' => 'USOR0061', 'name' => 'Central Point');
$city_data[] = array('accid' => 'USOR0062', 'name' => 'Chemult');
$city_data[] = array('accid' => 'USOR0063', 'name' => 'Cheshire');
$city_data[] = array('accid' => 'USOR0064', 'name' => 'Chiloquin');
$city_data[] = array('accid' => 'USOR0065', 'name' => 'Christmas Valley');
$city_data[] = array('accid' => 'USOR0066', 'name' => 'Clackamas');
$city_data[] = array('accid' => 'USOR0067', 'name' => 'Clatskanie');
$city_data[] = array('accid' => 'USOR0068', 'name' => 'Cloverdale');
$city_data[] = array('accid' => 'USOR0069', 'name' => 'Colton');
$city_data[] = array('accid' => 'USOR0070', 'name' => 'Columbia City');
$city_data[] = array('accid' => 'USOR0071', 'name' => 'Condon');
$city_data[] = array('accid' => 'USOR0072', 'name' => 'Coos Bay');
$city_data[] = array('accid' => 'USOR0073', 'name' => 'Coquille');
$city_data[] = array('accid' => 'USOR0074', 'name' => 'Corbett');
$city_data[] = array('accid' => 'USOR0075', 'name' => 'Cornelius');
$city_data[] = array('accid' => 'USOR0076', 'name' => 'Corvallis');
$city_data[] = array('accid' => 'USOR0077', 'name' => 'Cottage Grove');
$city_data[] = array('accid' => 'USOR0078', 'name' => 'Cove');
$city_data[] = array('accid' => 'USOR0079', 'name' => 'Crabtree');
$city_data[] = array('accid' => 'USOR0080', 'name' => 'Crane');
$city_data[] = array('accid' => 'USOR0081', 'name' => 'Crater Lake');
$city_data[] = array('accid' => 'USOR0083', 'name' => 'Crawfordsville');
$city_data[] = array('accid' => 'USOR0084', 'name' => 'Crescent');
$city_data[] = array('accid' => 'USOR0085', 'name' => 'Crescent Lake');
$city_data[] = array('accid' => 'USOR0086', 'name' => 'Creswell');
$city_data[] = array('accid' => 'USOR0087', 'name' => 'Culp Creek');
$city_data[] = array('accid' => 'USOR0088', 'name' => 'Culver');
$city_data[] = array('accid' => 'USOR0089', 'name' => 'Curtin');
$city_data[] = array('accid' => 'USOR0090', 'name' => 'Dairy');
$city_data[] = array('accid' => 'USOR0091', 'name' => 'Dallas');
$city_data[] = array('accid' => 'USOR0092', 'name' => 'Days Creek');
$city_data[] = array('accid' => 'USOR0093', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USOR0094', 'name' => 'Dayville');
$city_data[] = array('accid' => 'USOR0095', 'name' => 'Deadwood');
$city_data[] = array('accid' => 'USOR0096', 'name' => 'Deer Island');
$city_data[] = array('accid' => 'USOR0097', 'name' => 'Depoe Bay');
$city_data[] = array('accid' => 'USOR0098', 'name' => 'Detroit');
$city_data[] = array('accid' => 'USOR0099', 'name' => 'Dexter');
$city_data[] = array('accid' => 'USOR0100', 'name' => 'Diamond');
$city_data[] = array('accid' => 'USOR0101', 'name' => 'Dillard');
$city_data[] = array('accid' => 'USOR0102', 'name' => 'Donald');
$city_data[] = array('accid' => 'USOR0103', 'name' => 'Dorena');
$city_data[] = array('accid' => 'USOR0104', 'name' => 'Drain');
$city_data[] = array('accid' => 'USOR0105', 'name' => 'Drewsey');
$city_data[] = array('accid' => 'USOR0106', 'name' => 'Dufur');
$city_data[] = array('accid' => 'USOR0107', 'name' => 'Dundee');
$city_data[] = array('accid' => 'USOR0108', 'name' => 'Durkee');
$city_data[] = array('accid' => 'USOR0109', 'name' => 'Eagle Creek');
$city_data[] = array('accid' => 'USOR0110', 'name' => 'Eagle Point');
$city_data[] = array('accid' => 'USOR0111', 'name' => 'Echo');
$city_data[] = array('accid' => 'USOR0112', 'name' => 'Eddyville');
$city_data[] = array('accid' => 'USOR0113', 'name' => 'Elgin');
$city_data[] = array('accid' => 'USOR0114', 'name' => 'Elkton');
$city_data[] = array('accid' => 'USOR0115', 'name' => 'Elmira');
$city_data[] = array('accid' => 'USOR0116', 'name' => 'Enterprise');
$city_data[] = array('accid' => 'USOR0117', 'name' => 'Estacada');
$city_data[] = array('accid' => 'USOR0118', 'name' => 'Eugene');
$city_data[] = array('accid' => 'USOR0119', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USOR0120', 'name' => 'Fall Creek');
$city_data[] = array('accid' => 'USOR0121', 'name' => 'Falls City');
$city_data[] = array('accid' => 'USOR0122', 'name' => 'Fields');
$city_data[] = array('accid' => 'USOR0123', 'name' => 'Florence');
$city_data[] = array('accid' => 'USOR0124', 'name' => 'Forest Grove');
$city_data[] = array('accid' => 'USOR0125', 'name' => 'Fort Klamath');
$city_data[] = array('accid' => 'USOR0126', 'name' => 'Fort Rock');
$city_data[] = array('accid' => 'USOR0127', 'name' => 'Fossil');
$city_data[] = array('accid' => 'USOR0128', 'name' => 'Foster');
$city_data[] = array('accid' => 'USOR0129', 'name' => 'Fox');
$city_data[] = array('accid' => 'USOR0130', 'name' => 'Frenchglen');
$city_data[] = array('accid' => 'USOR0131', 'name' => 'Gales Creek');
$city_data[] = array('accid' => 'USOR0132', 'name' => 'Gardiner');
$city_data[] = array('accid' => 'USOR0133', 'name' => 'Garibaldi');
$city_data[] = array('accid' => 'USOR0134', 'name' => 'Gaston');
$city_data[] = array('accid' => 'USOR0135', 'name' => 'Gates');
$city_data[] = array('accid' => 'USOR0136', 'name' => 'Gervais');
$city_data[] = array('accid' => 'USOR0137', 'name' => 'Gilchrist');
$city_data[] = array('accid' => 'USOR0138', 'name' => 'Gladstone');
$city_data[] = array('accid' => 'USOR0139', 'name' => 'Glendale');
$city_data[] = array('accid' => 'USOR0140', 'name' => 'Gleneden Beach');
$city_data[] = array('accid' => 'USOR0141', 'name' => 'Glide');
$city_data[] = array('accid' => 'USOR0142', 'name' => 'Gold Beach');
$city_data[] = array('accid' => 'USOR0143', 'name' => 'Gold Hill');
$city_data[] = array('accid' => 'USOR0144', 'name' => 'Government Camp');
$city_data[] = array('accid' => 'USOR0145', 'name' => 'Grand Ronde');
$city_data[] = array('accid' => 'USOR0146', 'name' => 'Grants Pass');
$city_data[] = array('accid' => 'USOR0147', 'name' => 'Grass Valley');
$city_data[] = array('accid' => 'USOR0148', 'name' => 'Gresham');
$city_data[] = array('accid' => 'USOR0149', 'name' => 'Haines');
$city_data[] = array('accid' => 'USOR0150', 'name' => 'Halfway');
$city_data[] = array('accid' => 'USOR0151', 'name' => 'Halsey');
$city_data[] = array('accid' => 'USOR0152', 'name' => 'Hammond');
$city_data[] = array('accid' => 'USOR0153', 'name' => 'Harper');
$city_data[] = array('accid' => 'USOR0154', 'name' => 'Harrisburg');
$city_data[] = array('accid' => 'USOR0155', 'name' => 'Hebo');
$city_data[] = array('accid' => 'USOR0156', 'name' => 'Helix');
$city_data[] = array('accid' => 'USOR0157', 'name' => 'Heppner');
$city_data[] = array('accid' => 'USOR0158', 'name' => 'Hereford');
$city_data[] = array('accid' => 'USOR0159', 'name' => 'Hermiston');
$city_data[] = array('accid' => 'USOR0160', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USOR0161', 'name' => 'Hines');
$city_data[] = array('accid' => 'USOR0162', 'name' => 'Hood River');
$city_data[] = array('accid' => 'USOR0163', 'name' => 'Hubbard');
$city_data[] = array('accid' => 'USOR0164', 'name' => 'Huntington');
$city_data[] = array('accid' => 'USOR0165', 'name' => 'Idanha');
$city_data[] = array('accid' => 'USOR0166', 'name' => 'Idleyld Park');
$city_data[] = array('accid' => 'USOR0167', 'name' => 'Imbler');
$city_data[] = array('accid' => 'USOR0168', 'name' => 'Imnaha');
$city_data[] = array('accid' => 'USOR0169', 'name' => 'Independence');
$city_data[] = array('accid' => 'USOR0170', 'name' => 'Ione');
$city_data[] = array('accid' => 'USOR0171', 'name' => 'Ironside');
$city_data[] = array('accid' => 'USOR0172', 'name' => 'Irrigon');
$city_data[] = array('accid' => 'USOR0173', 'name' => 'Jacksonville');
$city_data[] = array('accid' => 'USOR0174', 'name' => 'Jamieson');
$city_data[] = array('accid' => 'USOR0175', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USOR0176', 'name' => 'John Day');
$city_data[] = array('accid' => 'USOR0177', 'name' => 'Jordan Valley');
$city_data[] = array('accid' => 'USOR0178', 'name' => 'Joseph');
$city_data[] = array('accid' => 'USOR0179', 'name' => 'Junction City');
$city_data[] = array('accid' => 'USOR0180', 'name' => 'Juntura');
$city_data[] = array('accid' => 'USOR0181', 'name' => 'Keizer');
$city_data[] = array('accid' => 'USOR0182', 'name' => 'Keno');
$city_data[] = array('accid' => 'USOR0183', 'name' => 'Kent');
$city_data[] = array('accid' => 'USOR0184', 'name' => 'Kerby');
$city_data[] = array('accid' => 'USOR0185', 'name' => 'Kimberly');
$city_data[] = array('accid' => 'USOR0186', 'name' => 'Klamath Falls');
$city_data[] = array('accid' => 'USOR0187', 'name' => 'La Grande');
$city_data[] = array('accid' => 'USOR0188', 'name' => 'La Pine');
$city_data[] = array('accid' => 'USOR0189', 'name' => 'Lafayette');
$city_data[] = array('accid' => 'USOR0190', 'name' => 'Lake Oswego');
$city_data[] = array('accid' => 'USOR0191', 'name' => 'Lakeside');
$city_data[] = array('accid' => 'USOR0192', 'name' => 'Lakeview');
$city_data[] = array('accid' => 'USOR0193', 'name' => 'Langlois');
$city_data[] = array('accid' => 'USOR0194', 'name' => 'Lawen');
$city_data[] = array('accid' => 'USOR0195', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USOR0196', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USOR0197', 'name' => 'Lincoln City');
$city_data[] = array('accid' => 'USOR0198', 'name' => 'Logsden');
$city_data[] = array('accid' => 'USOR0199', 'name' => 'Long Creek');
$city_data[] = array('accid' => 'USOR0200', 'name' => 'Lorane');
$city_data[] = array('accid' => 'USOR0201', 'name' => 'Lostine');
$city_data[] = array('accid' => 'USOR0202', 'name' => 'Lowell');
$city_data[] = array('accid' => 'USOR0203', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USOR0204', 'name' => 'Madras');
$city_data[] = array('accid' => 'USOR0205', 'name' => 'Malin');
$city_data[] = array('accid' => 'USOR0206', 'name' => 'Manning');
$city_data[] = array('accid' => 'USOR0207', 'name' => 'Manzanita');
$city_data[] = array('accid' => 'USOR0208', 'name' => 'Mapleton');
$city_data[] = array('accid' => 'USOR0209', 'name' => 'Marcola');
$city_data[] = array('accid' => 'USOR0210', 'name' => 'Marion');
$city_data[] = array('accid' => 'USOR0211', 'name' => 'Marylhurst');
$city_data[] = array('accid' => 'USOR0212', 'name' => 'Maupin');
$city_data[] = array('accid' => 'USOR0213', 'name' => 'McMinnville');
$city_data[] = array('accid' => 'USOR0214', 'name' => 'Meacham');
$city_data[] = array('accid' => 'USOR0215', 'name' => 'Medford');
$city_data[] = array('accid' => 'USOR0216', 'name' => 'Mehama');
$city_data[] = array('accid' => 'USOR0217', 'name' => 'Merlin');
$city_data[] = array('accid' => 'USOR0218', 'name' => 'Merrill');
$city_data[] = array('accid' => 'USOR0219', 'name' => 'Midland');
$city_data[] = array('accid' => 'USOR0220', 'name' => 'Mikkalo');
$city_data[] = array('accid' => 'USOR0221', 'name' => 'Mill City');
$city_data[] = array('accid' => 'USOR0222', 'name' => 'Milton Freewater');
$city_data[] = array('accid' => 'USOR0223', 'name' => 'Mitchell');
$city_data[] = array('accid' => 'USOR0224', 'name' => 'Molalla');
$city_data[] = array('accid' => 'USOR0225', 'name' => 'Monmouth');
$city_data[] = array('accid' => 'USOR0226', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USOR0227', 'name' => 'Monument');
$city_data[] = array('accid' => 'USOR0228', 'name' => 'Moro');
$city_data[] = array('accid' => 'USOR0229', 'name' => 'Mosier');
$city_data[] = array('accid' => 'USOR0230', 'name' => 'Mount Angel');
$city_data[] = array('accid' => 'USOR0233', 'name' => 'Mount Hood Parkdale');
$city_data[] = array('accid' => 'USOR0234', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USOR0235', 'name' => 'Mulino');
$city_data[] = array('accid' => 'USOR0236', 'name' => 'Murphy');
$city_data[] = array('accid' => 'USOR0237', 'name' => 'Myrtle Creek');
$city_data[] = array('accid' => 'USOR0238', 'name' => 'Myrtle Point');
$city_data[] = array('accid' => 'USOR0239', 'name' => 'Nehalem');
$city_data[] = array('accid' => 'USOR0240', 'name' => 'Neotsu');
$city_data[] = array('accid' => 'USOR0241', 'name' => 'Neskowin');
$city_data[] = array('accid' => 'USOR0242', 'name' => 'Netarts');
$city_data[] = array('accid' => 'USOR0243', 'name' => 'New Pine Creek');
$city_data[] = array('accid' => 'USOR0244', 'name' => 'Newberg');
$city_data[] = array('accid' => 'USOR0245', 'name' => 'Newport');
$city_data[] = array('accid' => 'USOR0247', 'name' => 'North Bend');
$city_data[] = array('accid' => 'USOR0248', 'name' => 'North Plains');
$city_data[] = array('accid' => 'USOR0249', 'name' => 'North Powder');
$city_data[] = array('accid' => 'USOR0250', 'name' => 'Norway');
$city_data[] = array('accid' => 'USOR0251', 'name' => 'Noti');
$city_data[] = array('accid' => 'USOR0252', 'name' => 'Nyssa');
$city_data[] = array('accid' => 'USOR0255', 'name' => 'O\'brien');
$city_data[] = array('accid' => 'USOR0253', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USOR0254', 'name' => 'Oakridge');
$city_data[] = array('accid' => 'USOR0256', 'name' => 'Oceanside');
$city_data[] = array('accid' => 'USOR0257', 'name' => 'Odell');
$city_data[] = array('accid' => 'USOR0258', 'name' => 'Ontario');
$city_data[] = array('accid' => 'USOR0259', 'name' => 'Ophir');
$city_data[] = array('accid' => 'USOR0260', 'name' => 'Oregon City');
$city_data[] = array('accid' => 'USOR0261', 'name' => 'Otis');
$city_data[] = array('accid' => 'USOR0262', 'name' => 'Otter Rock');
$city_data[] = array('accid' => 'USOR0263', 'name' => 'Oxbow');
$city_data[] = array('accid' => 'USOR0264', 'name' => 'Pacific City');
$city_data[] = array('accid' => 'USOR0265', 'name' => 'Paisley');
$city_data[] = array('accid' => 'USOR0266', 'name' => 'Paulina');
$city_data[] = array('accid' => 'USOR0267', 'name' => 'Pendleton');
$city_data[] = array('accid' => 'USOR0268', 'name' => 'Philomath');
$city_data[] = array('accid' => 'USOR0269', 'name' => 'Phoenix');
$city_data[] = array('accid' => 'USOR0270', 'name' => 'Pilot Rock');
$city_data[] = array('accid' => 'USOR0272', 'name' => 'Pleasant Hill');
$city_data[] = array('accid' => 'USOR0273', 'name' => 'Plush');
$city_data[] = array('accid' => 'USOR0274', 'name' => 'Port Orford');
$city_data[] = array('accid' => 'USOR0275', 'name' => 'Portland');
$city_data[] = array('accid' => 'USOR0276', 'name' => 'Post');
$city_data[] = array('accid' => 'USOR0277', 'name' => 'Powell Butte');
$city_data[] = array('accid' => 'USOR0278', 'name' => 'Powers');
$city_data[] = array('accid' => 'USOR0279', 'name' => 'Prairie City');
$city_data[] = array('accid' => 'USOR0280', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USOR0281', 'name' => 'Prineville');
$city_data[] = array('accid' => 'USOR0282', 'name' => 'Prospect');
$city_data[] = array('accid' => 'USOR0283', 'name' => 'Rainier');
$city_data[] = array('accid' => 'USOR0284', 'name' => 'Redmond');
$city_data[] = array('accid' => 'USOR0285', 'name' => 'Reedsport');
$city_data[] = array('accid' => 'USOR0286', 'name' => 'Remote');
$city_data[] = array('accid' => 'USOR0287', 'name' => 'Rhododendron');
$city_data[] = array('accid' => 'USOR0288', 'name' => 'Richland');
$city_data[] = array('accid' => 'USOR0289', 'name' => 'Rickreall');
$city_data[] = array('accid' => 'USOR0290', 'name' => 'Riddle');
$city_data[] = array('accid' => 'USOR0291', 'name' => 'Riley');
$city_data[] = array('accid' => 'USOR0292', 'name' => 'Ritter');
$city_data[] = array('accid' => 'USOR0293', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USOR0294', 'name' => 'Rockaway Beach');
$city_data[] = array('accid' => 'USOR0295', 'name' => 'Rogue River');
$city_data[] = array('accid' => 'USOR0297', 'name' => 'Rose Lodge');
$city_data[] = array('accid' => 'USOR0298', 'name' => 'Roseburg');
$city_data[] = array('accid' => 'USOR0299', 'name' => 'Rufus');
$city_data[] = array('accid' => 'USOR0300', 'name' => 'Saginaw');
$city_data[] = array('accid' => 'USOR0301', 'name' => 'Saint Benedict');
$city_data[] = array('accid' => 'USOR0302', 'name' => 'Saint Helens');
$city_data[] = array('accid' => 'USOR0303', 'name' => 'Saint Paul');
$city_data[] = array('accid' => 'USOR0304', 'name' => 'Salem');
$city_data[] = array('accid' => 'USOR0305', 'name' => 'Sandy');
$city_data[] = array('accid' => 'USOR0307', 'name' => 'Scappoose');
$city_data[] = array('accid' => 'USOR0308', 'name' => 'Scio');
$city_data[] = array('accid' => 'USOR0309', 'name' => 'Scotts Mills');
$city_data[] = array('accid' => 'USOR0310', 'name' => 'Scottsburg');
$city_data[] = array('accid' => 'USOR0311', 'name' => 'Seal Rock');
$city_data[] = array('accid' => 'USOR0312', 'name' => 'Seaside');
$city_data[] = array('accid' => 'USOR0313', 'name' => 'Selma');
$city_data[] = array('accid' => 'USOR0314', 'name' => 'Seneca');
$city_data[] = array('accid' => 'USOR0316', 'name' => 'Shady Cove');
$city_data[] = array('accid' => 'USOR0317', 'name' => 'Shaniko');
$city_data[] = array('accid' => 'USOR0318', 'name' => 'Shedd');
$city_data[] = array('accid' => 'USOR0319', 'name' => 'Sheridan');
$city_data[] = array('accid' => 'USOR0320', 'name' => 'Sherwood');
$city_data[] = array('accid' => 'USOR0321', 'name' => 'Siletz');
$city_data[] = array('accid' => 'USOR0322', 'name' => 'Silver Lake');
$city_data[] = array('accid' => 'USOR0323', 'name' => 'Silverton');
$city_data[] = array('accid' => 'USOR0324', 'name' => 'Sisters');
$city_data[] = array('accid' => 'USOR0325', 'name' => 'Sixes');
$city_data[] = array('accid' => 'USOR0326', 'name' => 'South Beach');
$city_data[] = array('accid' => 'USOR0328', 'name' => 'Sprague River');
$city_data[] = array('accid' => 'USOR0329', 'name' => 'Spray');
$city_data[] = array('accid' => 'USOR0330', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USOR0331', 'name' => 'Stanfield');
$city_data[] = array('accid' => 'USOR0332', 'name' => 'Stayton');
$city_data[] = array('accid' => 'USOR0333', 'name' => 'Sublimity');
$city_data[] = array('accid' => 'USOR0334', 'name' => 'Summer Lake');
$city_data[] = array('accid' => 'USOR0335', 'name' => 'Summerville');
$city_data[] = array('accid' => 'USOR0336', 'name' => 'Sumpter');
$city_data[] = array('accid' => 'USOR0337', 'name' => 'Sutherlin');
$city_data[] = array('accid' => 'USOR0338', 'name' => 'Sweet Home');
$city_data[] = array('accid' => 'USOR0339', 'name' => 'Swisshome');
$city_data[] = array('accid' => 'USOR0340', 'name' => 'Talent');
$city_data[] = array('accid' => 'USOR0341', 'name' => 'Tangent');
$city_data[] = array('accid' => 'USOR0342', 'name' => 'Tenmile');
$city_data[] = array('accid' => 'USOR0343', 'name' => 'Terrebonne');
$city_data[] = array('accid' => 'USOR0344', 'name' => 'The Dalles');
$city_data[] = array('accid' => 'USOR0345', 'name' => 'Thurston');
$city_data[] = array('accid' => 'USOR0346', 'name' => 'Tidewater');
$city_data[] = array('accid' => 'USOR0347', 'name' => 'Tillamook');
$city_data[] = array('accid' => 'USOR0348', 'name' => 'Tiller');
$city_data[] = array('accid' => 'USOR0349', 'name' => 'Timber');
$city_data[] = array('accid' => 'USOR0350', 'name' => 'Toledo');
$city_data[] = array('accid' => 'USOR0351', 'name' => 'Tolovana Park');
$city_data[] = array('accid' => 'USOR0352', 'name' => 'Trail');
$city_data[] = array('accid' => 'USOR0353', 'name' => 'Troutdale');
$city_data[] = array('accid' => 'USOR0354', 'name' => 'Tualatin');
$city_data[] = array('accid' => 'USOR0355', 'name' => 'Turner');
$city_data[] = array('accid' => 'USOR0356', 'name' => 'Tygh Valley');
$city_data[] = array('accid' => 'USOR0357', 'name' => 'Ukiah');
$city_data[] = array('accid' => 'USOR0358', 'name' => 'Umatilla');
$city_data[] = array('accid' => 'USOR0359', 'name' => 'Umpqua');
$city_data[] = array('accid' => 'USOR0360', 'name' => 'Union');
$city_data[] = array('accid' => 'USOR0361', 'name' => 'Unity');
$city_data[] = array('accid' => 'USOR0362', 'name' => 'Vale');
$city_data[] = array('accid' => 'USOR0363', 'name' => 'Veneta');
$city_data[] = array('accid' => 'USOR0364', 'name' => 'Vernonia');
$city_data[] = array('accid' => 'USOR0365', 'name' => 'Vida');
$city_data[] = array('accid' => 'USOR0366', 'name' => 'Waldport');
$city_data[] = array('accid' => 'USOR0367', 'name' => 'Wallowa');
$city_data[] = array('accid' => 'USOR0368', 'name' => 'Walterville');
$city_data[] = array('accid' => 'USOR0369', 'name' => 'Walton');
$city_data[] = array('accid' => 'USOR0370', 'name' => 'Warm Springs');
$city_data[] = array('accid' => 'USOR0371', 'name' => 'Warren');
$city_data[] = array('accid' => 'USOR0372', 'name' => 'Warrenton');
$city_data[] = array('accid' => 'USOR0373', 'name' => 'Wasco');
$city_data[] = array('accid' => 'USOR0374', 'name' => 'Wedderburn');
$city_data[] = array('accid' => 'USOR0375', 'name' => 'Welches');
$city_data[] = array('accid' => 'USOR0376', 'name' => 'West Linn');
$city_data[] = array('accid' => 'USOR0377', 'name' => 'Westfall');
$city_data[] = array('accid' => 'USOR0378', 'name' => 'Westfir');
$city_data[] = array('accid' => 'USOR0379', 'name' => 'Westlake');
$city_data[] = array('accid' => 'USOR0380', 'name' => 'Weston');
$city_data[] = array('accid' => 'USOR0381', 'name' => 'Wheeler');
$city_data[] = array('accid' => 'USOR0382', 'name' => 'White City');
$city_data[] = array('accid' => 'USOR0383', 'name' => 'Wilbur');
$city_data[] = array('accid' => 'USOR0384', 'name' => 'Wilderville');
$city_data[] = array('accid' => 'USOR0385', 'name' => 'Willamina');
$city_data[] = array('accid' => 'USOR0386', 'name' => 'Williams');
$city_data[] = array('accid' => 'USOR0387', 'name' => 'Wilsonville');
$city_data[] = array('accid' => 'USOR0388', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USOR0389', 'name' => 'Winston');
$city_data[] = array('accid' => 'USOR0390', 'name' => 'Wolf Creek');
$city_data[] = array('accid' => 'USOR0391', 'name' => 'Woodburn');
$city_data[] = array('accid' => 'USOR0392', 'name' => 'Yachats');
$city_data[] = array('accid' => 'USOR0393', 'name' => 'Yamhill');
$city_data[] = array('accid' => 'USOR0394', 'name' => 'Yoncalla');

?>