<?php

// City package for USA: South Carolina

$city_name = 'USA: South Carolina';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USSC0001', 'name' => 'Abbeville');
$city_data[] = array('accid' => 'USSC0002', 'name' => 'Adams Run');
$city_data[] = array('accid' => 'USSC0003', 'name' => 'Aiken');
$city_data[] = array('accid' => 'USSC0004', 'name' => 'Alcolu');
$city_data[] = array('accid' => 'USSC0005', 'name' => 'Allendale');
$city_data[] = array('accid' => 'USSC0006', 'name' => 'Anderson');
$city_data[] = array('accid' => 'USSC0007', 'name' => 'Andrews');
$city_data[] = array('accid' => 'USSC0008', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USSC0009', 'name' => 'Awendaw');
$city_data[] = array('accid' => 'USSC0010', 'name' => 'Aynor');
$city_data[] = array('accid' => 'USSC0011', 'name' => 'Ballentine');
$city_data[] = array('accid' => 'USSC0012', 'name' => 'Bamberg');
$city_data[] = array('accid' => 'USSC0013', 'name' => 'Barnwell');
$city_data[] = array('accid' => 'USSC0014', 'name' => 'Batesburg');
$city_data[] = array('accid' => 'USSC0015', 'name' => 'Bath');
$city_data[] = array('accid' => 'USSC0016', 'name' => 'Beaufort');
$city_data[] = array('accid' => 'USSC0017', 'name' => 'Beech Island');
$city_data[] = array('accid' => 'USSC0018', 'name' => 'Belton');
$city_data[] = array('accid' => 'USSC0019', 'name' => 'Bennettsville');
$city_data[] = array('accid' => 'USSC0020', 'name' => 'Bethera');
$city_data[] = array('accid' => 'USSC0021', 'name' => 'Bethune');
$city_data[] = array('accid' => 'USSC0022', 'name' => 'Bishopville');
$city_data[] = array('accid' => 'USSC0023', 'name' => 'Blacksburg');
$city_data[] = array('accid' => 'USSC0024', 'name' => 'Blackstock');
$city_data[] = array('accid' => 'USSC0025', 'name' => 'Blackville');
$city_data[] = array('accid' => 'USSC0026', 'name' => 'Blair');
$city_data[] = array('accid' => 'USSC0027', 'name' => 'Blenheim');
$city_data[] = array('accid' => 'USSC0028', 'name' => 'Bluffton');
$city_data[] = array('accid' => 'USSC0029', 'name' => 'Blythewood');
$city_data[] = array('accid' => 'USSC0030', 'name' => 'Bonneau');
$city_data[] = array('accid' => 'USSC0031', 'name' => 'Bowling Green');
$city_data[] = array('accid' => 'USSC0032', 'name' => 'Bowman');
$city_data[] = array('accid' => 'USSC0033', 'name' => 'Bradley');
$city_data[] = array('accid' => 'USSC0034', 'name' => 'Branchville');
$city_data[] = array('accid' => 'USSC0035', 'name' => 'Brunson');
$city_data[] = array('accid' => 'USSC0036', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USSC0037', 'name' => 'Cades');
$city_data[] = array('accid' => 'USSC0038', 'name' => 'Calhoun Falls');
$city_data[] = array('accid' => 'USSC0039', 'name' => 'Camden');
$city_data[] = array('accid' => 'USSC0040', 'name' => 'Cameron');
$city_data[] = array('accid' => 'USSC0041', 'name' => 'Campobello');
$city_data[] = array('accid' => 'USSC0042', 'name' => 'Canadys');
$city_data[] = array('accid' => 'USSC0043', 'name' => 'Carlisle');
$city_data[] = array('accid' => 'USSC0044', 'name' => 'Cassatt');
$city_data[] = array('accid' => 'USSC0045', 'name' => 'Catawba');
$city_data[] = array('accid' => 'USSC0046', 'name' => 'Cayce');
$city_data[] = array('accid' => 'USSC0047', 'name' => 'Centenary');
$city_data[] = array('accid' => 'USSC0048', 'name' => 'Central');
$city_data[] = array('accid' => 'USSC0049', 'name' => 'Chapin');
$city_data[] = array('accid' => 'USSC0050', 'name' => 'Chappells');
$city_data[] = array('accid' => 'USSC0051', 'name' => 'Charleston');
$city_data[] = array('accid' => 'USSC0052', 'name' => 'Charleston AFB');
$city_data[] = array('accid' => 'USSC0053', 'name' => 'Cheraw');
$city_data[] = array('accid' => 'USSC0054', 'name' => 'Chesnee');
$city_data[] = array('accid' => 'USSC0055', 'name' => 'Chester');
$city_data[] = array('accid' => 'USSC0056', 'name' => 'Chesterfield');
$city_data[] = array('accid' => 'USSC0057', 'name' => 'Clarks Hill');
$city_data[] = array('accid' => 'USSC0058', 'name' => 'Clearwater');
$city_data[] = array('accid' => 'USSC0059', 'name' => 'Clemson');
$city_data[] = array('accid' => 'USSC0060', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USSC0061', 'name' => 'Clifton');
$city_data[] = array('accid' => 'USSC0062', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USSC0063', 'name' => 'Clio');
$city_data[] = array('accid' => 'USSC0064', 'name' => 'Clover');
$city_data[] = array('accid' => 'USSC0065', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USSC0067', 'name' => 'Columbia$city_data[]Owens Field');
$city_data[] = array('accid' => 'USSC0068', 'name' => 'Conestee');
$city_data[] = array('accid' => 'USSC0069', 'name' => 'Converse');
$city_data[] = array('accid' => 'USSC0070', 'name' => 'Conway');
$city_data[] = array('accid' => 'USSC0382', 'name' => 'Coosawatchie');
$city_data[] = array('accid' => 'USSC0072', 'name' => 'Cope');
$city_data[] = array('accid' => 'USSC0073', 'name' => 'Cordesville');
$city_data[] = array('accid' => 'USSC0074', 'name' => 'Cordova');
$city_data[] = array('accid' => 'USSC0075', 'name' => 'Cottageville');
$city_data[] = array('accid' => 'USSC0076', 'name' => 'Coward');
$city_data[] = array('accid' => 'USSC0077', 'name' => 'Cowpens');
$city_data[] = array('accid' => 'USSC0078', 'name' => 'Crocketville');
$city_data[] = array('accid' => 'USSC0079', 'name' => 'Cross');
$city_data[] = array('accid' => 'USSC0080', 'name' => 'Cross Anchor');
$city_data[] = array('accid' => 'USSC0081', 'name' => 'Cross Hill');
$city_data[] = array('accid' => 'USSC0082', 'name' => 'Dale');
$city_data[] = array('accid' => 'USSC0083', 'name' => 'Dalzell');
$city_data[] = array('accid' => 'USSC0084', 'name' => 'Darlington');
$city_data[] = array('accid' => 'USSC0085', 'name' => 'Daufuskie Island');
$city_data[] = array('accid' => 'USSC0086', 'name' => 'Davis Station');
$city_data[] = array('accid' => 'USSC0087', 'name' => 'Denmark');
$city_data[] = array('accid' => 'USSC0088', 'name' => 'Dillon');
$city_data[] = array('accid' => 'USSC0089', 'name' => 'Donalds');
$city_data[] = array('accid' => 'USSC0090', 'name' => 'Dorchester');
$city_data[] = array('accid' => 'USSC0091', 'name' => 'Drayton');
$city_data[] = array('accid' => 'USSC0092', 'name' => 'Due West');
$city_data[] = array('accid' => 'USSC0093', 'name' => 'Duncan');
$city_data[] = array('accid' => 'USSC0094', 'name' => 'Early Branch');
$city_data[] = array('accid' => 'USSC0095', 'name' => 'Easley');
$city_data[] = array('accid' => 'USSC0096', 'name' => 'Eastover');
$city_data[] = array('accid' => 'USSC0097', 'name' => 'Edgefield');
$city_data[] = array('accid' => 'USSC0098', 'name' => 'Edgemoor');
$city_data[] = array('accid' => 'USSC0099', 'name' => 'Edisto Island');
$city_data[] = array('accid' => 'USSC0100', 'name' => 'Effingham');
$city_data[] = array('accid' => 'USSC0101', 'name' => 'Ehrhardt');
$city_data[] = array('accid' => 'USSC0102', 'name' => 'Elgin');
$city_data[] = array('accid' => 'USSC0103', 'name' => 'Elko');
$city_data[] = array('accid' => 'USSC0104', 'name' => 'Elliott');
$city_data[] = array('accid' => 'USSC0105', 'name' => 'Elloree');
$city_data[] = array('accid' => 'USSC0106', 'name' => 'Enoree');
$city_data[] = array('accid' => 'USSC0107', 'name' => 'Estill');
$city_data[] = array('accid' => 'USSC0108', 'name' => 'Eutawville');
$city_data[] = array('accid' => 'USSC0109', 'name' => 'Fair Play');
$city_data[] = array('accid' => 'USSC0110', 'name' => 'Fairfax');
$city_data[] = array('accid' => 'USSC0111', 'name' => 'Fairforest');
$city_data[] = array('accid' => 'USSC0112', 'name' => 'Fingerville');
$city_data[] = array('accid' => 'USSC0113', 'name' => 'Florence');
$city_data[] = array('accid' => 'USSC0114', 'name' => 'Floyd Dale');
$city_data[] = array('accid' => 'USSC0115', 'name' => 'Folly Beach');
$city_data[] = array('accid' => 'USSC0116', 'name' => 'Fork');
$city_data[] = array('accid' => 'USSC0117', 'name' => 'Fort Lawn');
$city_data[] = array('accid' => 'USSC0118', 'name' => 'Fort Mill');
$city_data[] = array('accid' => 'USSC0119', 'name' => 'Fountain Inn');
$city_data[] = array('accid' => 'USSC0120', 'name' => 'Furman');
$city_data[] = array('accid' => 'USSC0121', 'name' => 'Gable');
$city_data[] = array('accid' => 'USSC0122', 'name' => 'Gadsden');
$city_data[] = array('accid' => 'USSC0123', 'name' => 'Gaffney');
$city_data[] = array('accid' => 'USSC0124', 'name' => 'Galivants Ferry');
$city_data[] = array('accid' => 'USSC0125', 'name' => 'Garnett');
$city_data[] = array('accid' => 'USSC0126', 'name' => 'Gaston');
$city_data[] = array('accid' => 'USSC0127', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USSC0128', 'name' => 'Gifford');
$city_data[] = array('accid' => 'USSC0129', 'name' => 'Gilbert');
$city_data[] = array('accid' => 'USSC0130', 'name' => 'Glendale');
$city_data[] = array('accid' => 'USSC0131', 'name' => 'Gloverville');
$city_data[] = array('accid' => 'USSC0132', 'name' => 'Goose Creek');
$city_data[] = array('accid' => 'USSC0133', 'name' => 'Gramling');
$city_data[] = array('accid' => 'USSC0134', 'name' => 'Graniteville');
$city_data[] = array('accid' => 'USSC0135', 'name' => 'Gray Court');
$city_data[] = array('accid' => 'USSC0136', 'name' => 'Great Falls');
$city_data[] = array('accid' => 'USSC0137', 'name' => 'Greeleyville');
$city_data[] = array('accid' => 'USSC0138', 'name' => 'Green Pond');
$city_data[] = array('accid' => 'USSC0139', 'name' => 'Green Sea');
$city_data[] = array('accid' => 'USSC0140', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USSC0142', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USSC0143', 'name' => 'Greer');
$city_data[] = array('accid' => 'USSC0144', 'name' => 'Gresham');
$city_data[] = array('accid' => 'USSC0145', 'name' => 'Grover');
$city_data[] = array('accid' => 'USSC0146', 'name' => 'Hamer');
$city_data[] = array('accid' => 'USSC0147', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USSC0148', 'name' => 'Hardeeville');
$city_data[] = array('accid' => 'USSC0149', 'name' => 'Harleyville');
$city_data[] = array('accid' => 'USSC0150', 'name' => 'Hartsville');
$city_data[] = array('accid' => 'USSC0151', 'name' => 'Heath Springs');
$city_data[] = array('accid' => 'USSC0152', 'name' => 'Hemingway');
$city_data[] = array('accid' => 'USSC0153', 'name' => 'Hickory Grove');
$city_data[] = array('accid' => 'USSC0154', 'name' => 'Hilda');
$city_data[] = array('accid' => 'USSC0155', 'name' => 'Hilton Head Island');
$city_data[] = array('accid' => 'USSC0156', 'name' => 'Hodges');
$city_data[] = array('accid' => 'USSC0157', 'name' => 'Holly Hill');
$city_data[] = array('accid' => 'USSC0158', 'name' => 'Hollywood');
$city_data[] = array('accid' => 'USSC0159', 'name' => 'Honea Path');
$city_data[] = array('accid' => 'USSC0160', 'name' => 'Hopkins');
$city_data[] = array('accid' => 'USSC0161', 'name' => 'Horatio');
$city_data[] = array('accid' => 'USSC0162', 'name' => 'Huger');
$city_data[] = array('accid' => 'USSC0163', 'name' => 'Inman');
$city_data[] = array('accid' => 'USSC0164', 'name' => 'Irmo');
$city_data[] = array('accid' => 'USSC0165', 'name' => 'Islandton');
$city_data[] = array('accid' => 'USSC0166', 'name' => 'Isle Of Palms');
$city_data[] = array('accid' => 'USSC0167', 'name' => 'Iva');
$city_data[] = array('accid' => 'USSC0168', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USSC0169', 'name' => 'Jacksonboro');
$city_data[] = array('accid' => 'USSC0170', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USSC0171', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USSC0172', 'name' => 'Jenkinsville');
$city_data[] = array('accid' => 'USSC0173', 'name' => 'Joanna');
$city_data[] = array('accid' => 'USSC0174', 'name' => 'Johns Island');
$city_data[] = array('accid' => 'USSC0175', 'name' => 'Johnsonville');
$city_data[] = array('accid' => 'USSC0176', 'name' => 'Johnston');
$city_data[] = array('accid' => 'USSC0177', 'name' => 'Jonesville');
$city_data[] = array('accid' => 'USSC0178', 'name' => 'Kershaw');
$city_data[] = array('accid' => 'USSC0179', 'name' => 'Kinards');
$city_data[] = array('accid' => 'USSC0180', 'name' => 'Kingstree');
$city_data[] = array('accid' => 'USSC0181', 'name' => 'La France');
$city_data[] = array('accid' => 'USSC0182', 'name' => 'Ladson');
$city_data[] = array('accid' => 'USSC0386', 'name' => 'Lady\'s Island');
$city_data[] = array('accid' => 'USSC0183', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USSC0184', 'name' => 'Lake View');
$city_data[] = array('accid' => 'USSC0185', 'name' => 'Lamar');
$city_data[] = array('accid' => 'USSC0186', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USSC0187', 'name' => 'Lando');
$city_data[] = array('accid' => 'USSC0188', 'name' => 'Landrum');
$city_data[] = array('accid' => 'USSC0189', 'name' => 'Lane');
$city_data[] = array('accid' => 'USSC0190', 'name' => 'Langley');
$city_data[] = array('accid' => 'USSC0191', 'name' => 'Latta');
$city_data[] = array('accid' => 'USSC0192', 'name' => 'Laurens');
$city_data[] = array('accid' => 'USSC0193', 'name' => 'Leesville');
$city_data[] = array('accid' => 'USSC0194', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USSC0195', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USSC0196', 'name' => 'Liberty Hill');
$city_data[] = array('accid' => 'USSC0197', 'name' => 'Little Mountain');
$city_data[] = array('accid' => 'USSC0198', 'name' => 'Little River');
$city_data[] = array('accid' => 'USSC0199', 'name' => 'Little Rock');
$city_data[] = array('accid' => 'USSC0200', 'name' => 'Lobeco');
$city_data[] = array('accid' => 'USSC0201', 'name' => 'Lockhart');
$city_data[] = array('accid' => 'USSC0202', 'name' => 'Lodge');
$city_data[] = array('accid' => 'USSC0203', 'name' => 'Long Creek');
$city_data[] = array('accid' => 'USSC0204', 'name' => 'Longs');
$city_data[] = array('accid' => 'USSC0205', 'name' => 'Loris');
$city_data[] = array('accid' => 'USSC0206', 'name' => 'Lowndesville');
$city_data[] = array('accid' => 'USSC0207', 'name' => 'Lugoff');
$city_data[] = array('accid' => 'USSC0208', 'name' => 'Luray');
$city_data[] = array('accid' => 'USSC0209', 'name' => 'Lydia');
$city_data[] = array('accid' => 'USSC0210', 'name' => 'Lyman');
$city_data[] = array('accid' => 'USSC0211', 'name' => 'Lynchburg');
$city_data[] = array('accid' => 'USSC0212', 'name' => 'Manning');
$city_data[] = array('accid' => 'USSC0213', 'name' => 'Marietta');
$city_data[] = array('accid' => 'USSC0214', 'name' => 'Marion');
$city_data[] = array('accid' => 'USSC0215', 'name' => 'Martin');
$city_data[] = array('accid' => 'USSC0216', 'name' => 'Mauldin');
$city_data[] = array('accid' => 'USSC0217', 'name' => 'Mayesville');
$city_data[] = array('accid' => 'USSC0218', 'name' => 'Mayo');
$city_data[] = array('accid' => 'USSC0219', 'name' => 'McBee');
$city_data[] = array('accid' => 'USSC0220', 'name' => 'McClellanville');
$city_data[] = array('accid' => 'USSC0221', 'name' => 'McColl');
$city_data[] = array('accid' => 'USSC0222', 'name' => 'McConnells');
$city_data[] = array('accid' => 'USSC0223', 'name' => 'McCormick');
$city_data[] = array('accid' => 'USSC0224', 'name' => 'Miley');
$city_data[] = array('accid' => 'USSC0225', 'name' => 'Minturn');
$city_data[] = array('accid' => 'USSC0226', 'name' => 'Modoc');
$city_data[] = array('accid' => 'USSC0227', 'name' => 'Moncks Corner');
$city_data[] = array('accid' => 'USSC0228', 'name' => 'Monetta');
$city_data[] = array('accid' => 'USSC0229', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USSC0230', 'name' => 'Montmorenci');
$city_data[] = array('accid' => 'USSC0231', 'name' => 'Moore');
$city_data[] = array('accid' => 'USSC0232', 'name' => 'Mount Carmel');
$city_data[] = array('accid' => 'USSC0233', 'name' => 'Mount Croghan');
$city_data[] = array('accid' => 'USSC0234', 'name' => 'Mount Pleasant');
$city_data[] = array('accid' => 'USSC0235', 'name' => 'Mountain Rest');
$city_data[] = array('accid' => 'USSC0236', 'name' => 'Mountville');
$city_data[] = array('accid' => 'USSC0237', 'name' => 'Mullins');
$city_data[] = array('accid' => 'USSC0238', 'name' => 'Murrells Inlet');
$city_data[] = array('accid' => 'USSC0239', 'name' => 'Myrtle Beach');
$city_data[] = array('accid' => 'USSC0241', 'name' => 'Neeses');
$city_data[] = array('accid' => 'USSC0242', 'name' => 'Nesmith');
$city_data[] = array('accid' => 'USSC0243', 'name' => 'New Ellenton');
$city_data[] = array('accid' => 'USSC0244', 'name' => 'New Zion');
$city_data[] = array('accid' => 'USSC0245', 'name' => 'Newberry');
$city_data[] = array('accid' => 'USSC0246', 'name' => 'Newry');
$city_data[] = array('accid' => 'USSC0247', 'name' => 'Nichols');
$city_data[] = array('accid' => 'USSC0248', 'name' => 'Ninety Six');
$city_data[] = array('accid' => 'USSC0249', 'name' => 'Norris');
$city_data[] = array('accid' => 'USSC0250', 'name' => 'North');
$city_data[] = array('accid' => 'USSC0251', 'name' => 'North Augusta');
$city_data[] = array('accid' => 'USSC0252', 'name' => 'North Myrtle Beach');
$city_data[] = array('accid' => 'USSC0253', 'name' => 'Norway');
$city_data[] = array('accid' => 'USSC0385', 'name' => 'Okatie');
$city_data[] = array('accid' => 'USSC0254', 'name' => 'Olanta');
$city_data[] = array('accid' => 'USSC0255', 'name' => 'Olar');
$city_data[] = array('accid' => 'USSC0256', 'name' => 'Orangeburg');
$city_data[] = array('accid' => 'USSC0257', 'name' => 'Pacolet');
$city_data[] = array('accid' => 'USSC0258', 'name' => 'Pacolet Mills');
$city_data[] = array('accid' => 'USSC0259', 'name' => 'Pageland');
$city_data[] = array('accid' => 'USSC0260', 'name' => 'Pamplico');
$city_data[] = array('accid' => 'USSC0261', 'name' => 'Parksville');
$city_data[] = array('accid' => 'USSC0262', 'name' => 'Patrick');
$city_data[] = array('accid' => 'USSC0263', 'name' => 'Pauline');
$city_data[] = array('accid' => 'USSC0264', 'name' => 'Pawleys Island');
$city_data[] = array('accid' => 'USSC0265', 'name' => 'Peak');
$city_data[] = array('accid' => 'USSC0266', 'name' => 'Pelion');
$city_data[] = array('accid' => 'USSC0267', 'name' => 'Pelzer');
$city_data[] = array('accid' => 'USSC0268', 'name' => 'Pendleton');
$city_data[] = array('accid' => 'USSC0269', 'name' => 'Perry');
$city_data[] = array('accid' => 'USSC0270', 'name' => 'Pickens');
$city_data[] = array('accid' => 'USSC0271', 'name' => 'Piedmont');
$city_data[] = array('accid' => 'USSC0272', 'name' => 'Pineland');
$city_data[] = array('accid' => 'USSC0273', 'name' => 'Pineville');
$city_data[] = array('accid' => 'USSC0274', 'name' => 'Pinewood');
$city_data[] = array('accid' => 'USSC0275', 'name' => 'Pinopolis');
$city_data[] = array('accid' => 'USSC0276', 'name' => 'Plum Branch');
$city_data[] = array('accid' => 'USSC0277', 'name' => 'Pomaria');
$city_data[] = array('accid' => 'USSC0278', 'name' => 'Port Royal');
$city_data[] = array('accid' => 'USSC0279', 'name' => 'Prosperity');
$city_data[] = array('accid' => 'USSC0280', 'name' => 'Rains');
$city_data[] = array('accid' => 'USSC0281', 'name' => 'Ravenel');
$city_data[] = array('accid' => 'USSC0282', 'name' => 'Reevesville');
$city_data[] = array('accid' => 'USSC0283', 'name' => 'Reidville');
$city_data[] = array('accid' => 'USSC0284', 'name' => 'Rembert');
$city_data[] = array('accid' => 'USSC0285', 'name' => 'Richburg');
$city_data[] = array('accid' => 'USSC0286', 'name' => 'Richland');
$city_data[] = array('accid' => 'USSC0287', 'name' => 'Ridge Spring');
$city_data[] = array('accid' => 'USSC0288', 'name' => 'Ridgeland');
$city_data[] = array('accid' => 'USSC0289', 'name' => 'Ridgeville');
$city_data[] = array('accid' => 'USSC0290', 'name' => 'Ridgeway');
$city_data[] = array('accid' => 'USSC0291', 'name' => 'Rion');
$city_data[] = array('accid' => 'USSC0292', 'name' => 'Rock Hill');
$city_data[] = array('accid' => 'USSC0293', 'name' => 'Roebuck');
$city_data[] = array('accid' => 'USSC0294', 'name' => 'Round O');
$city_data[] = array('accid' => 'USSC0295', 'name' => 'Rowesville');
$city_data[] = array('accid' => 'USSC0296', 'name' => 'Ruby');
$city_data[] = array('accid' => 'USSC0297', 'name' => 'Ruffin');
$city_data[] = array('accid' => 'USSC0298', 'name' => 'Russellville');
$city_data[] = array('accid' => 'USSC0299', 'name' => 'Saint George');
$city_data[] = array('accid' => 'USSC0300', 'name' => 'Saint Helena Island');
$city_data[] = array('accid' => 'USSC0301', 'name' => 'Saint Matthews');
$city_data[] = array('accid' => 'USSC0302', 'name' => 'Saint Stephen');
$city_data[] = array('accid' => 'USSC0303', 'name' => 'Salem');
$city_data[] = array('accid' => 'USSC0304', 'name' => 'Salley');
$city_data[] = array('accid' => 'USSC0305', 'name' => 'Salters');
$city_data[] = array('accid' => 'USSC0306', 'name' => 'Saluda');
$city_data[] = array('accid' => 'USSC0307', 'name' => 'Sandy Springs');
$city_data[] = array('accid' => 'USSC0308', 'name' => 'Santee');
$city_data[] = array('accid' => 'USSC0309', 'name' => 'Sardinia');
$city_data[] = array('accid' => 'USSC0310', 'name' => 'Scotia');
$city_data[] = array('accid' => 'USSC0311', 'name' => 'Scranton');
$city_data[] = array('accid' => 'USSC0312', 'name' => 'Seabrook');
$city_data[] = array('accid' => 'USSC0313', 'name' => 'Sellers');
$city_data[] = array('accid' => 'USSC0314', 'name' => 'Seneca');
$city_data[] = array('accid' => 'USSC0315', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USSC0316', 'name' => 'Shaw AFB');
$city_data[] = array('accid' => 'USSC0317', 'name' => 'Sheldon');
$city_data[] = array('accid' => 'USSC0318', 'name' => 'Silverstreet');
$city_data[] = array('accid' => 'USSC0319', 'name' => 'Simpsonville');
$city_data[] = array('accid' => 'USSC0320', 'name' => 'Six Mile');
$city_data[] = array('accid' => 'USSC0321', 'name' => 'Slater');
$city_data[] = array('accid' => 'USSC0322', 'name' => 'Smoaks');
$city_data[] = array('accid' => 'USSC0323', 'name' => 'Smyrna');
$city_data[] = array('accid' => 'USSC0324', 'name' => 'Society Hill');
$city_data[] = array('accid' => 'USSC0325', 'name' => 'Spartanburg');
$city_data[] = array('accid' => 'USSC0326', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USSC0327', 'name' => 'Starr');
$city_data[] = array('accid' => 'USSC0328', 'name' => 'Startex');
$city_data[] = array('accid' => 'USSC0329', 'name' => 'State Park');
$city_data[] = array('accid' => 'USSC0330', 'name' => 'Sullivans Island');
$city_data[] = array('accid' => 'USSC0331', 'name' => 'Summerton');
$city_data[] = array('accid' => 'USSC0332', 'name' => 'Summerville');
$city_data[] = array('accid' => 'USSC0333', 'name' => 'Sumter');
$city_data[] = array('accid' => 'USSC0334', 'name' => 'Sunset');
$city_data[] = array('accid' => 'USSC0335', 'name' => 'Swansea');
$city_data[] = array('accid' => 'USSC0336', 'name' => 'Sycamore');
$city_data[] = array('accid' => 'USSC0337', 'name' => 'Tamassee');
$city_data[] = array('accid' => 'USSC0338', 'name' => 'Tatum');
$city_data[] = array('accid' => 'USSC0339', 'name' => 'Taylors');
$city_data[] = array('accid' => 'USSC0340', 'name' => 'Tigerville');
$city_data[] = array('accid' => 'USSC0341', 'name' => 'Tillman');
$city_data[] = array('accid' => 'USSC0342', 'name' => 'Timmonsville');
$city_data[] = array('accid' => 'USSC0343', 'name' => 'Townville');
$city_data[] = array('accid' => 'USSC0344', 'name' => 'Travelers Rest');
$city_data[] = array('accid' => 'USSC0345', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USSC0346', 'name' => 'Troy');
$city_data[] = array('accid' => 'USSC0347', 'name' => 'Turbeville');
$city_data[] = array('accid' => 'USSC0348', 'name' => 'Ulmer');
$city_data[] = array('accid' => 'USSC0349', 'name' => 'Una');
$city_data[] = array('accid' => 'USSC0350', 'name' => 'Union');
$city_data[] = array('accid' => 'USSC0351', 'name' => 'Van Wyck');
$city_data[] = array('accid' => 'USSC0352', 'name' => 'Vance');
$city_data[] = array('accid' => 'USSC0353', 'name' => 'Varnville');
$city_data[] = array('accid' => 'USSC0354', 'name' => 'Vaucluse');
$city_data[] = array('accid' => 'USSC0355', 'name' => 'Wadmalaw Island');
$city_data[] = array('accid' => 'USSC0356', 'name' => 'Wagener');
$city_data[] = array('accid' => 'USSC0357', 'name' => 'Walhalla');
$city_data[] = array('accid' => 'USSC0358', 'name' => 'Wallace');
$city_data[] = array('accid' => 'USSC0359', 'name' => 'Walterboro');
$city_data[] = array('accid' => 'USSC0360', 'name' => 'Ward');
$city_data[] = array('accid' => 'USSC0361', 'name' => 'Ware Shoals');
$city_data[] = array('accid' => 'USSC0362', 'name' => 'Warrenville');
$city_data[] = array('accid' => 'USSC0363', 'name' => 'Waterloo');
$city_data[] = array('accid' => 'USSC0364', 'name' => 'Wedgefield');
$city_data[] = array('accid' => 'USSC0365', 'name' => 'Wellford');
$city_data[] = array('accid' => 'USSC0366', 'name' => 'West Columbia');
$city_data[] = array('accid' => 'USSC0367', 'name' => 'West Union');
$city_data[] = array('accid' => 'USSC0368', 'name' => 'Westminster');
$city_data[] = array('accid' => 'USSC0369', 'name' => 'Westville');
$city_data[] = array('accid' => 'USSC0370', 'name' => 'White Oak');
$city_data[] = array('accid' => 'USSC0371', 'name' => 'White Rock');
$city_data[] = array('accid' => 'USSC0372', 'name' => 'White Stone');
$city_data[] = array('accid' => 'USSC0373', 'name' => 'Whitmire');
$city_data[] = array('accid' => 'USSC0374', 'name' => 'Williams');
$city_data[] = array('accid' => 'USSC0375', 'name' => 'Williamston');
$city_data[] = array('accid' => 'USSC0376', 'name' => 'Williston');
$city_data[] = array('accid' => 'USSC0377', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USSC0378', 'name' => 'Winnsboro');
$city_data[] = array('accid' => 'USSC0379', 'name' => 'Woodruff');
$city_data[] = array('accid' => 'USSC0380', 'name' => 'Yemassee');
$city_data[] = array('accid' => 'USSC0381', 'name' => 'York');

?>