<?php

// City package for USA: South Dakota 

$city_name = 'USA: South Dakota';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USSD0001', 'name' => 'Aberdeen');
$city_data[] = array('accid' => 'USSD0002', 'name' => 'Agar');
$city_data[] = array('accid' => 'USSD0003', 'name' => 'Akaska');
$city_data[] = array('accid' => 'USSD0004', 'name' => 'Alcester');
$city_data[] = array('accid' => 'USSD0005', 'name' => 'Alexandria');
$city_data[] = array('accid' => 'USSD0006', 'name' => 'Allen');
$city_data[] = array('accid' => 'USSD0007', 'name' => 'Alpena');
$city_data[] = array('accid' => 'USSD0008', 'name' => 'Amherst');
$city_data[] = array('accid' => 'USSD0009', 'name' => 'Andover');
$city_data[] = array('accid' => 'USSD0010', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USSD0011', 'name' => 'Armour');
$city_data[] = array('accid' => 'USSD0012', 'name' => 'Artesian');
$city_data[] = array('accid' => 'USSD0013', 'name' => 'Ashton');
$city_data[] = array('accid' => 'USSD0014', 'name' => 'Astoria');
$city_data[] = array('accid' => 'USSD0015', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USSD0016', 'name' => 'Avon');
$city_data[] = array('accid' => 'USSD0017', 'name' => 'Badger');
$city_data[] = array('accid' => 'USSD0019', 'name' => 'Baltic');
$city_data[] = array('accid' => 'USSD0020', 'name' => 'Barnard');
$city_data[] = array('accid' => 'USSD0021', 'name' => 'Batesland');
$city_data[] = array('accid' => 'USSD0022', 'name' => 'Bath');
$city_data[] = array('accid' => 'USSD0023', 'name' => 'Belle Fourche');
$city_data[] = array('accid' => 'USSD0024', 'name' => 'Belvidere');
$city_data[] = array('accid' => 'USSD0025', 'name' => 'Beresford');
$city_data[] = array('accid' => 'USSD0026', 'name' => 'Bethlehem');
$city_data[] = array('accid' => 'USSD0027', 'name' => 'Big Stone City');
$city_data[] = array('accid' => 'USSD0028', 'name' => 'Bison');
$city_data[] = array('accid' => 'USSD0029', 'name' => 'Black Hawk');
$city_data[] = array('accid' => 'USSD0030', 'name' => 'Blunt');
$city_data[] = array('accid' => 'USSD0031', 'name' => 'Bonesteel');
$city_data[] = array('accid' => 'USSD0032', 'name' => 'Bowdle');
$city_data[] = array('accid' => 'USSD0033', 'name' => 'Box Elder');
$city_data[] = array('accid' => 'USSD0034', 'name' => 'Bradley');
$city_data[] = array('accid' => 'USSD0035', 'name' => 'Brandon');
$city_data[] = array('accid' => 'USSD0036', 'name' => 'Brandt');
$city_data[] = array('accid' => 'USSD0037', 'name' => 'Brentford');
$city_data[] = array('accid' => 'USSD0038', 'name' => 'Bridgewater');
$city_data[] = array('accid' => 'USSD0039', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USSD0040', 'name' => 'Britton');
$city_data[] = array('accid' => 'USSD0041', 'name' => 'Brookings');
$city_data[] = array('accid' => 'USSD0042', 'name' => 'Bruce');
$city_data[] = array('accid' => 'USSD0043', 'name' => 'Bryant');
$city_data[] = array('accid' => 'USSD0044', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USSD0045', 'name' => 'Buffalo Gap');
$city_data[] = array('accid' => 'USSD0046', 'name' => 'Buffalo Ridge');
$city_data[] = array('accid' => 'USSD0047', 'name' => 'Bullhead');
$city_data[] = array('accid' => 'USSD0048', 'name' => 'Burbank');
$city_data[] = array('accid' => 'USSD0049', 'name' => 'Burke');
$city_data[] = array('accid' => 'USSD0050', 'name' => 'Camp Crook');
$city_data[] = array('accid' => 'USSD0051', 'name' => 'Canistota');
$city_data[] = array('accid' => 'USSD0052', 'name' => 'Canova');
$city_data[] = array('accid' => 'USSD0053', 'name' => 'Canton');
$city_data[] = array('accid' => 'USSD0054', 'name' => 'Caputa');
$city_data[] = array('accid' => 'USSD0055', 'name' => 'Carpenter');
$city_data[] = array('accid' => 'USSD0056', 'name' => 'Carter');
$city_data[] = array('accid' => 'USSD0057', 'name' => 'Carthage');
$city_data[] = array('accid' => 'USSD0058', 'name' => 'Castlewood');
$city_data[] = array('accid' => 'USSD0059', 'name' => 'Cavour');
$city_data[] = array('accid' => 'USSD0060', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USSD0061', 'name' => 'Chamberlain');
$city_data[] = array('accid' => 'USSD0062', 'name' => 'Chancellor');
$city_data[] = array('accid' => 'USSD0063', 'name' => 'Cherry Creek');
$city_data[] = array('accid' => 'USSD0064', 'name' => 'Chester');
$city_data[] = array('accid' => 'USSD0065', 'name' => 'Claire City');
$city_data[] = array('accid' => 'USSD0066', 'name' => 'Claremont');
$city_data[] = array('accid' => 'USSD0067', 'name' => 'Clark');
$city_data[] = array('accid' => 'USSD0068', 'name' => 'Clear Lake');
$city_data[] = array('accid' => 'USSD0069', 'name' => 'Colman');
$city_data[] = array('accid' => 'USSD0070', 'name' => 'Colome');
$city_data[] = array('accid' => 'USSD0071', 'name' => 'Colton');
$city_data[] = array('accid' => 'USSD0072', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USSD0073', 'name' => 'Conde');
$city_data[] = array('accid' => 'USSD0074', 'name' => 'Corona');
$city_data[] = array('accid' => 'USSD0075', 'name' => 'Corsica');
$city_data[] = array('accid' => 'USSD0076', 'name' => 'Creighton');
$city_data[] = array('accid' => 'USSD0077', 'name' => 'Cresbard');
$city_data[] = array('accid' => 'USSD0078', 'name' => 'Crooks');
$city_data[] = array('accid' => 'USSD0079', 'name' => 'Custer');
$city_data[] = array('accid' => 'USSD0080', 'name' => 'Dallas');
$city_data[] = array('accid' => 'USSD0081', 'name' => 'Dante');
$city_data[] = array('accid' => 'USSD0082', 'name' => 'Davis');
$city_data[] = array('accid' => 'USSD0083', 'name' => 'De Smet');
$city_data[] = array('accid' => 'USSD0084', 'name' => 'Deadwood');
$city_data[] = array('accid' => 'USSD0085', 'name' => 'Dell Rapids');
$city_data[] = array('accid' => 'USSD0086', 'name' => 'Delmont');
$city_data[] = array('accid' => 'USSD0087', 'name' => 'Dimock');
$city_data[] = array('accid' => 'USSD0088', 'name' => 'Doland');
$city_data[] = array('accid' => 'USSD0089', 'name' => 'Draper');
$city_data[] = array('accid' => 'USSD0090', 'name' => 'Dupree');
$city_data[] = array('accid' => 'USSD0091', 'name' => 'Eagle Butte');
$city_data[] = array('accid' => 'USSD0092', 'name' => 'Eden');
$city_data[] = array('accid' => 'USSD0093', 'name' => 'Edgemont');
$city_data[] = array('accid' => 'USSD0094', 'name' => 'Egan');
$city_data[] = array('accid' => 'USSD0095', 'name' => 'Elk Point');
$city_data[] = array('accid' => 'USSD0096', 'name' => 'Elkton');
$city_data[] = array('accid' => 'USSD0097', 'name' => 'Ellsworth AFB');
$city_data[] = array('accid' => 'USSD0098', 'name' => 'Elm Springs');
$city_data[] = array('accid' => 'USSD0099', 'name' => 'Emery');
$city_data[] = array('accid' => 'USSD0100', 'name' => 'Enning');
$city_data[] = array('accid' => 'USSD0101', 'name' => 'Erwin');
$city_data[] = array('accid' => 'USSD0102', 'name' => 'Estelline');
$city_data[] = array('accid' => 'USSD0103', 'name' => 'Ethan');
$city_data[] = array('accid' => 'USSD0104', 'name' => 'Eureka');
$city_data[] = array('accid' => 'USSD0105', 'name' => 'Fairburn');
$city_data[] = array('accid' => 'USSD0106', 'name' => 'Fairfax');
$city_data[] = array('accid' => 'USSD0107', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USSD0108', 'name' => 'Faith');
$city_data[] = array('accid' => 'USSD0109', 'name' => 'Faulkton');
$city_data[] = array('accid' => 'USSD0110', 'name' => 'Fedora');
$city_data[] = array('accid' => 'USSD0111', 'name' => 'Ferney');
$city_data[] = array('accid' => 'USSD0112', 'name' => 'Firesteel');
$city_data[] = array('accid' => 'USSD0113', 'name' => 'Flandreau');
$city_data[] = array('accid' => 'USSD0114', 'name' => 'Florence');
$city_data[] = array('accid' => 'USSD0115', 'name' => 'Fort Meade');
$city_data[] = array('accid' => 'USSD0116', 'name' => 'Fort Pierre');
$city_data[] = array('accid' => 'USSD0117', 'name' => 'Fort Thompson');
$city_data[] = array('accid' => 'USSD0118', 'name' => 'Frankfort');
$city_data[] = array('accid' => 'USSD0119', 'name' => 'Frederick');
$city_data[] = array('accid' => 'USSD0120', 'name' => 'Freeman');
$city_data[] = array('accid' => 'USSD0121', 'name' => 'Fruitdale');
$city_data[] = array('accid' => 'USSD0122', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USSD0123', 'name' => 'Gann Valley');
$city_data[] = array('accid' => 'USSD0124', 'name' => 'Garden City');
$city_data[] = array('accid' => 'USSD0125', 'name' => 'Garretson');
$city_data[] = array('accid' => 'USSD0126', 'name' => 'Gary');
$city_data[] = array('accid' => 'USSD0127', 'name' => 'Gayville');
$city_data[] = array('accid' => 'USSD0128', 'name' => 'Geddes');
$city_data[] = array('accid' => 'USSD0129', 'name' => 'Gettysburg');
$city_data[] = array('accid' => 'USSD0130', 'name' => 'Glad Valley');
$city_data[] = array('accid' => 'USSD0131', 'name' => 'Glencross');
$city_data[] = array('accid' => 'USSD0132', 'name' => 'Glenham');
$city_data[] = array('accid' => 'USSD0133', 'name' => 'Goodwin');
$city_data[] = array('accid' => 'USSD0134', 'name' => 'Gregory');
$city_data[] = array('accid' => 'USSD0135', 'name' => 'Grenville');
$city_data[] = array('accid' => 'USSD0136', 'name' => 'Groton');
$city_data[] = array('accid' => 'USSD0137', 'name' => 'Hamill');
$city_data[] = array('accid' => 'USSD0138', 'name' => 'Harrisburg');
$city_data[] = array('accid' => 'USSD0139', 'name' => 'Harrison');
$city_data[] = array('accid' => 'USSD0140', 'name' => 'Harrold');
$city_data[] = array('accid' => 'USSD0141', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USSD0142', 'name' => 'Hayes');
$city_data[] = array('accid' => 'USSD0143', 'name' => 'Hayti');
$city_data[] = array('accid' => 'USSD0144', 'name' => 'Hazel');
$city_data[] = array('accid' => 'USSD0145', 'name' => 'Hecla');
$city_data[] = array('accid' => 'USSD0146', 'name' => 'Henry');
$city_data[] = array('accid' => 'USSD0147', 'name' => 'Hermosa');
$city_data[] = array('accid' => 'USSD0148', 'name' => 'Herreid');
$city_data[] = array('accid' => 'USSD0149', 'name' => 'Herrick');
$city_data[] = array('accid' => 'USSD0150', 'name' => 'Hetland');
$city_data[] = array('accid' => 'USSD0151', 'name' => 'Highmore');
$city_data[] = array('accid' => 'USSD0152', 'name' => 'Hill City');
$city_data[] = array('accid' => 'USSD0153', 'name' => 'Hitchcock');
$city_data[] = array('accid' => 'USSD0154', 'name' => 'Holabird');
$city_data[] = array('accid' => 'USSD0155', 'name' => 'Hosmer');
$city_data[] = array('accid' => 'USSD0156', 'name' => 'Hot Springs');
$city_data[] = array('accid' => 'USSD0157', 'name' => 'Houghton');
$city_data[] = array('accid' => 'USSD0158', 'name' => 'Hoven');
$city_data[] = array('accid' => 'USSD0159', 'name' => 'Howard');
$city_data[] = array('accid' => 'USSD0160', 'name' => 'Howes');
$city_data[] = array('accid' => 'USSD0161', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USSD0162', 'name' => 'Humboldt');
$city_data[] = array('accid' => 'USSD0163', 'name' => 'Hurley');
$city_data[] = array('accid' => 'USSD0164', 'name' => 'Huron');
$city_data[] = array('accid' => 'USSD0165', 'name' => 'Ideal');
$city_data[] = array('accid' => 'USSD0166', 'name' => 'Interior');
$city_data[] = array('accid' => 'USSD0167', 'name' => 'Iona');
$city_data[] = array('accid' => 'USSD0168', 'name' => 'Ipswich');
$city_data[] = array('accid' => 'USSD0169', 'name' => 'Irene');
$city_data[] = array('accid' => 'USSD0170', 'name' => 'Iroquois');
$city_data[] = array('accid' => 'USSD0171', 'name' => 'Isabel');
$city_data[] = array('accid' => 'USSD0172', 'name' => 'Java');
$city_data[] = array('accid' => 'USSD0173', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USSD0174', 'name' => 'Kadoka');
$city_data[] = array('accid' => 'USSD0175', 'name' => 'Kaylor');
$city_data[] = array('accid' => 'USSD0176', 'name' => 'Keldron');
$city_data[] = array('accid' => 'USSD0177', 'name' => 'Kennebec');
$city_data[] = array('accid' => 'USSD0178', 'name' => 'Keystone');
$city_data[] = array('accid' => 'USSD0179', 'name' => 'Kimball');
$city_data[] = array('accid' => 'USSD0180', 'name' => 'Kranzburg');
$city_data[] = array('accid' => 'USSD0181', 'name' => 'Kyle');
$city_data[] = array('accid' => 'USSD0182', 'name' => 'Labolt');
$city_data[] = array('accid' => 'USSD0183', 'name' => 'Lake Andes');
$city_data[] = array('accid' => 'USSD0184', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USSD0185', 'name' => 'Lake Norden');
$city_data[] = array('accid' => 'USSD0186', 'name' => 'Lake Preston');
$city_data[] = array('accid' => 'USSD0187', 'name' => 'Lane');
$city_data[] = array('accid' => 'USSD0188', 'name' => 'Langford');
$city_data[] = array('accid' => 'USSD0189', 'name' => 'Lantry');
$city_data[] = array('accid' => 'USSD0190', 'name' => 'Lead');
$city_data[] = array('accid' => 'USSD0191', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USSD0192', 'name' => 'Lemmon');
$city_data[] = array('accid' => 'USSD0193', 'name' => 'Lennox');
$city_data[] = array('accid' => 'USSD0194', 'name' => 'Leola');
$city_data[] = array('accid' => 'USSD0195', 'name' => 'Lesterville');
$city_data[] = array('accid' => 'USSD0196', 'name' => 'Letcher');
$city_data[] = array('accid' => 'USSD0197', 'name' => 'Little Eagle');
$city_data[] = array('accid' => 'USSD0198', 'name' => 'Lodgepole');
$city_data[] = array('accid' => 'USSD0199', 'name' => 'Long Valley');
$city_data[] = array('accid' => 'USSD0200', 'name' => 'Longlake');
$city_data[] = array('accid' => 'USSD0201', 'name' => 'Lower Brule');
$city_data[] = array('accid' => 'USSD0202', 'name' => 'Ludlow');
$city_data[] = array('accid' => 'USSD0203', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USSD0204', 'name' => 'Madison');
$city_data[] = array('accid' => 'USSD0205', 'name' => 'Mahto');
$city_data[] = array('accid' => 'USSD0206', 'name' => 'Manderson');
$city_data[] = array('accid' => 'USSD0207', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'USSD0208', 'name' => 'Marion');
$city_data[] = array('accid' => 'USSD0209', 'name' => 'Martin');
$city_data[] = array('accid' => 'USSD0210', 'name' => 'Marty');
$city_data[] = array('accid' => 'USSD0211', 'name' => 'Marvin');
$city_data[] = array('accid' => 'USSD0212', 'name' => 'McIntosh');
$city_data[] = array('accid' => 'USSD0213', 'name' => 'McLaughlin');
$city_data[] = array('accid' => 'USSD0214', 'name' => 'Meadow');
$city_data[] = array('accid' => 'USSD0215', 'name' => 'Meckling');
$city_data[] = array('accid' => 'USSD0216', 'name' => 'Mellette');
$city_data[] = array('accid' => 'USSD0217', 'name' => 'Menno');
$city_data[] = array('accid' => 'USSD0218', 'name' => 'Midland');
$city_data[] = array('accid' => 'USSD0219', 'name' => 'Milbank');
$city_data[] = array('accid' => 'USSD0220', 'name' => 'Milesville');
$city_data[] = array('accid' => 'USSD0221', 'name' => 'Miller');
$city_data[] = array('accid' => 'USSD0222', 'name' => 'Mina');
$city_data[] = array('accid' => 'USSD0223', 'name' => 'Mission');
$city_data[] = array('accid' => 'USSD0224', 'name' => 'Mission Hill');
$city_data[] = array('accid' => 'USSD0225', 'name' => 'Mission Ridge');
$city_data[] = array('accid' => 'USSD0226', 'name' => 'Mitchell');
$city_data[] = array('accid' => 'USSD0227', 'name' => 'Mobridge');
$city_data[] = array('accid' => 'USSD0228', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USSD0229', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USSD0230', 'name' => 'Morristown');
$city_data[] = array('accid' => 'USSD0231', 'name' => 'Mound City');
$city_data[] = array('accid' => 'USSD0233', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USSD0234', 'name' => 'Mud Butte');
$city_data[] = array('accid' => 'USSD0235', 'name' => 'Murdo');
$city_data[] = array('accid' => 'USSD0236', 'name' => 'Nemo');
$city_data[] = array('accid' => 'USSD0237', 'name' => 'New Effington');
$city_data[] = array('accid' => 'USSD0238', 'name' => 'New Holland');
$city_data[] = array('accid' => 'USSD0239', 'name' => 'New Underwood');
$city_data[] = array('accid' => 'USSD0240', 'name' => 'Newell');
$city_data[] = array('accid' => 'USSD0241', 'name' => 'Nisland');
$city_data[] = array('accid' => 'USSD0242', 'name' => 'Norris');
$city_data[] = array('accid' => 'USSD0243', 'name' => 'North Sioux City');
$city_data[] = array('accid' => 'USSD0244', 'name' => 'Northville');
$city_data[] = array('accid' => 'USSD0245', 'name' => 'Nunda');
$city_data[] = array('accid' => 'USSD0246', 'name' => 'Oacoma');
$city_data[] = array('accid' => 'USSD0247', 'name' => 'Oelrichs');
$city_data[] = array('accid' => 'USSD0248', 'name' => 'Oglala');
$city_data[] = array('accid' => 'USSD0249', 'name' => 'Okaton');
$city_data[] = array('accid' => 'USSD0250', 'name' => 'Okreek');
$city_data[] = array('accid' => 'USSD0251', 'name' => 'Oldham');
$city_data[] = array('accid' => 'USSD0252', 'name' => 'Olivet');
$city_data[] = array('accid' => 'USSD0253', 'name' => 'Onaka');
$city_data[] = array('accid' => 'USSD0254', 'name' => 'Onida');
$city_data[] = array('accid' => 'USSD0255', 'name' => 'Opal');
$city_data[] = array('accid' => 'USSD0256', 'name' => 'Oral');
$city_data[] = array('accid' => 'USSD0257', 'name' => 'Orient');
$city_data[] = array('accid' => 'USSD0258', 'name' => 'Ortley');
$city_data[] = array('accid' => 'USSD0259', 'name' => 'Owanka');
$city_data[] = array('accid' => 'USSD0260', 'name' => 'Parade');
$city_data[] = array('accid' => 'USSD0261', 'name' => 'Parker');
$city_data[] = array('accid' => 'USSD0262', 'name' => 'Parkston');
$city_data[] = array('accid' => 'USSD0263', 'name' => 'Parmelee');
$city_data[] = array('accid' => 'USSD0264', 'name' => 'Peever');
$city_data[] = array('accid' => 'USSD0265', 'name' => 'Philip');
$city_data[] = array('accid' => 'USSD0266', 'name' => 'Pickstown');
$city_data[] = array('accid' => 'USSD0267', 'name' => 'Piedmont');
$city_data[] = array('accid' => 'USSD0268', 'name' => 'Pierpont');
$city_data[] = array('accid' => 'USSD0269', 'name' => 'Pierre');
$city_data[] = array('accid' => 'USSD0270', 'name' => 'Pine Ridge');
$city_data[] = array('accid' => 'USSD0271', 'name' => 'Plankinton');
$city_data[] = array('accid' => 'USSD0272', 'name' => 'Platte');
$city_data[] = array('accid' => 'USSD0273', 'name' => 'Pollock');
$city_data[] = array('accid' => 'USSD0274', 'name' => 'Porcupine');
$city_data[] = array('accid' => 'USSD0275', 'name' => 'Prairie City');
$city_data[] = array('accid' => 'USSD0276', 'name' => 'Presho');
$city_data[] = array('accid' => 'USSD0277', 'name' => 'Pringle');
$city_data[] = array('accid' => 'USSD0278', 'name' => 'Provo');
$city_data[] = array('accid' => 'USSD0279', 'name' => 'Pukwana');
$city_data[] = array('accid' => 'USSD0280', 'name' => 'Quinn');
$city_data[] = array('accid' => 'USSD0281', 'name' => 'Ralph');
$city_data[] = array('accid' => 'USSD0282', 'name' => 'Ramona');
$city_data[] = array('accid' => 'USSD0283', 'name' => 'Rapid City');
$city_data[] = array('accid' => 'USSD0285', 'name' => 'Ravinia');
$city_data[] = array('accid' => 'USSD0286', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USSD0287', 'name' => 'Red Owl');
$city_data[] = array('accid' => 'USSD0288', 'name' => 'Redfield');
$city_data[] = array('accid' => 'USSD0289', 'name' => 'Redig');
$city_data[] = array('accid' => 'USSD0290', 'name' => 'Ree Heights');
$city_data[] = array('accid' => 'USSD0291', 'name' => 'Reliance');
$city_data[] = array('accid' => 'USSD0292', 'name' => 'Renner');
$city_data[] = array('accid' => 'USSD0293', 'name' => 'Reva');
$city_data[] = array('accid' => 'USSD0294', 'name' => 'Revillo');
$city_data[] = array('accid' => 'USSD0295', 'name' => 'Ridgeview');
$city_data[] = array('accid' => 'USSD0296', 'name' => 'Rochford');
$city_data[] = array('accid' => 'USSD0297', 'name' => 'Rockham');
$city_data[] = array('accid' => 'USSD0298', 'name' => 'Roscoe');
$city_data[] = array('accid' => 'USSD0299', 'name' => 'Rosebud');
$city_data[] = array('accid' => 'USSD0300', 'name' => 'Rosholt');
$city_data[] = array('accid' => 'USSD0301', 'name' => 'Roslyn');
$city_data[] = array('accid' => 'USSD0302', 'name' => 'Rowena');
$city_data[] = array('accid' => 'USSD0303', 'name' => 'Rutland');
$city_data[] = array('accid' => 'USSD0304', 'name' => 'Saint Charles');
$city_data[] = array('accid' => 'USSD0305', 'name' => 'Saint Francis');
$city_data[] = array('accid' => 'USSD0306', 'name' => 'Saint Lawrence');
$city_data[] = array('accid' => 'USSD0307', 'name' => 'Saint Onge');
$city_data[] = array('accid' => 'USSD0308', 'name' => 'Salem');
$city_data[] = array('accid' => 'USSD0309', 'name' => 'Scenic');
$city_data[] = array('accid' => 'USSD0310', 'name' => 'Scotland');
$city_data[] = array('accid' => 'USSD0311', 'name' => 'Selby');
$city_data[] = array('accid' => 'USSD0312', 'name' => 'Seneca');
$city_data[] = array('accid' => 'USSD0313', 'name' => 'Shadehill');
$city_data[] = array('accid' => 'USSD0314', 'name' => 'Sinai');
$city_data[] = array('accid' => 'USSD0315', 'name' => 'Sioux Falls');
$city_data[] = array('accid' => 'USSD0316', 'name' => 'Sisseton');
$city_data[] = array('accid' => 'USSD0317', 'name' => 'Smithwick');
$city_data[] = array('accid' => 'USSD0318', 'name' => 'South Shore');
$city_data[] = array('accid' => 'USSD0319', 'name' => 'Spearfish');
$city_data[] = array('accid' => 'USSD0320', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USSD0321', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USSD0322', 'name' => 'Stephan');
$city_data[] = array('accid' => 'USSD0323', 'name' => 'Stickney');
$city_data[] = array('accid' => 'USSD0324', 'name' => 'Stockholm');
$city_data[] = array('accid' => 'USSD0325', 'name' => 'Strandburg');
$city_data[] = array('accid' => 'USSD0326', 'name' => 'Stratford');
$city_data[] = array('accid' => 'USSD0327', 'name' => 'Sturgis');
$city_data[] = array('accid' => 'USSD0328', 'name' => 'Summit');
$city_data[] = array('accid' => 'USSD0329', 'name' => 'Tabor');
$city_data[] = array('accid' => 'USSD0330', 'name' => 'Tea');
$city_data[] = array('accid' => 'USSD0331', 'name' => 'Timber Lake');
$city_data[] = array('accid' => 'USSD0332', 'name' => 'Tolstoy');
$city_data[] = array('accid' => 'USSD0333', 'name' => 'Toronto');
$city_data[] = array('accid' => 'USSD0334', 'name' => 'Trail City');
$city_data[] = array('accid' => 'USSD0335', 'name' => 'Trent');
$city_data[] = array('accid' => 'USSD0336', 'name' => 'Tripp');
$city_data[] = array('accid' => 'USSD0337', 'name' => 'Tulare');
$city_data[] = array('accid' => 'USSD0338', 'name' => 'Turton');
$city_data[] = array('accid' => 'USSD0339', 'name' => 'Tuthill');
$city_data[] = array('accid' => 'USSD0340', 'name' => 'Twin Brooks');
$city_data[] = array('accid' => 'USSD0341', 'name' => 'Tyndall');
$city_data[] = array('accid' => 'USSD0342', 'name' => 'Union Center');
$city_data[] = array('accid' => 'USSD0343', 'name' => 'Utica');
$city_data[] = array('accid' => 'USSD0344', 'name' => 'Vale');
$city_data[] = array('accid' => 'USSD0345', 'name' => 'Valley Springs');
$city_data[] = array('accid' => 'USSD0346', 'name' => 'Veblen');
$city_data[] = array('accid' => 'USSD0347', 'name' => 'Vermillion');
$city_data[] = array('accid' => 'USSD0348', 'name' => 'Viborg');
$city_data[] = array('accid' => 'USSD0349', 'name' => 'Vienna');
$city_data[] = array('accid' => 'USSD0350', 'name' => 'Virgil');
$city_data[] = array('accid' => 'USSD0351', 'name' => 'Vivian');
$city_data[] = array('accid' => 'USSD0352', 'name' => 'Volga');
$city_data[] = array('accid' => 'USSD0353', 'name' => 'Volin');
$city_data[] = array('accid' => 'USSD0354', 'name' => 'Wagner');
$city_data[] = array('accid' => 'USSD0355', 'name' => 'Wakonda');
$city_data[] = array('accid' => 'USSD0356', 'name' => 'Wakpala');
$city_data[] = array('accid' => 'USSD0357', 'name' => 'Walker');
$city_data[] = array('accid' => 'USSD0358', 'name' => 'Wall');
$city_data[] = array('accid' => 'USSD0359', 'name' => 'Wallace');
$city_data[] = array('accid' => 'USSD0360', 'name' => 'Wanblee');
$city_data[] = array('accid' => 'USSD0361', 'name' => 'Ward');
$city_data[] = array('accid' => 'USSD0362', 'name' => 'Warner');
$city_data[] = array('accid' => 'USSD0363', 'name' => 'Wasta');
$city_data[] = array('accid' => 'USSD0364', 'name' => 'Watauga');
$city_data[] = array('accid' => 'USSD0365', 'name' => 'Watertown');
$city_data[] = array('accid' => 'USSD0366', 'name' => 'Waubay');
$city_data[] = array('accid' => 'USSD0367', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USSD0368', 'name' => 'Webster');
$city_data[] = array('accid' => 'USSD0369', 'name' => 'Wentworth');
$city_data[] = array('accid' => 'USSD0370', 'name' => 'Wessington');
$city_data[] = array('accid' => 'USSD0371', 'name' => 'Wessington Springs');
$city_data[] = array('accid' => 'USSD0372', 'name' => 'Westport');
$city_data[] = array('accid' => 'USSD0373', 'name' => 'Wewela');
$city_data[] = array('accid' => 'USSD0374', 'name' => 'White');
$city_data[] = array('accid' => 'USSD0375', 'name' => 'White Lake');
$city_data[] = array('accid' => 'USSD0376', 'name' => 'White Owl');
$city_data[] = array('accid' => 'USSD0377', 'name' => 'White River');
$city_data[] = array('accid' => 'USSD0378', 'name' => 'Whitehorse');
$city_data[] = array('accid' => 'USSD0379', 'name' => 'Whitewood');
$city_data[] = array('accid' => 'USSD0380', 'name' => 'Willow Lake');
$city_data[] = array('accid' => 'USSD0381', 'name' => 'Wilmot');
$city_data[] = array('accid' => 'USSD0383', 'name' => 'Winfred');
$city_data[] = array('accid' => 'USSD0384', 'name' => 'Winner');
$city_data[] = array('accid' => 'USSD0385', 'name' => 'Witten');
$city_data[] = array('accid' => 'USSD0386', 'name' => 'Wolsey');
$city_data[] = array('accid' => 'USSD0387', 'name' => 'Wood');
$city_data[] = array('accid' => 'USSD0388', 'name' => 'Woonsocket');
$city_data[] = array('accid' => 'USSD0389', 'name' => 'Worthing');
$city_data[] = array('accid' => 'USSD0390', 'name' => 'Wounded Knee');
$city_data[] = array('accid' => 'USSD0391', 'name' => 'Yale');
$city_data[] = array('accid' => 'USSD0392', 'name' => 'Yankton');

?>
