<?php

// City package for USA: Tennessee 

$city_name = 'USA: Tennessee';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USTN0001', 'name' => 'Adams');
$city_data[] = array('accid' => 'USTN0002', 'name' => 'Adamsville');
$city_data[] = array('accid' => 'USTN0003', 'name' => 'Afton');
$city_data[] = array('accid' => 'USTN0004', 'name' => 'Alamo');
$city_data[] = array('accid' => 'USTN0005', 'name' => 'Alcoa');
$city_data[] = array('accid' => 'USTN0006', 'name' => 'Alexandria');
$city_data[] = array('accid' => 'USTN0007', 'name' => 'Allardt');
$city_data[] = array('accid' => 'USTN0008', 'name' => 'Allons');
$city_data[] = array('accid' => 'USTN0009', 'name' => 'Allred');
$city_data[] = array('accid' => 'USTN0010', 'name' => 'Alpine');
$city_data[] = array('accid' => 'USTN0011', 'name' => 'Altamont');
$city_data[] = array('accid' => 'USTN0012', 'name' => 'Andersonville');
$city_data[] = array('accid' => 'USTN0013', 'name' => 'Antioch');
$city_data[] = array('accid' => 'USTN0014', 'name' => 'Apison');
$city_data[] = array('accid' => 'USTN0015', 'name' => 'Ardmore');
$city_data[] = array('accid' => 'USTN0016', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USTN0017', 'name' => 'Arnold AFB');
$city_data[] = array('accid' => 'USTN0018', 'name' => 'Arrington');
$city_data[] = array('accid' => 'USTN0019', 'name' => 'Arthur');
$city_data[] = array('accid' => 'USTN0020', 'name' => 'Ashland City');
$city_data[] = array('accid' => 'USTN0021', 'name' => 'Athens');
$city_data[] = array('accid' => 'USTN0022', 'name' => 'Atoka');
$city_data[] = array('accid' => 'USTN0023', 'name' => 'Atwood');
$city_data[] = array('accid' => 'USTN0024', 'name' => 'Auburntown');
$city_data[] = array('accid' => 'USTN0025', 'name' => 'Bakewell');
$city_data[] = array('accid' => 'USTN0026', 'name' => 'Bath Springs');
$city_data[] = array('accid' => 'USTN0027', 'name' => 'Baxter');
$city_data[] = array('accid' => 'USTN0028', 'name' => 'Bean Station');
$city_data[] = array('accid' => 'USTN0029', 'name' => 'Beech Bluff');
$city_data[] = array('accid' => 'USTN0030', 'name' => 'Beechgrove');
$city_data[] = array('accid' => 'USTN0031', 'name' => 'Beersheba Springs');
$city_data[] = array('accid' => 'USTN0032', 'name' => 'Belfast');
$city_data[] = array('accid' => 'USTN0033', 'name' => 'Bell Buckle');
$city_data[] = array('accid' => 'USTN0034', 'name' => 'Bells');
$city_data[] = array('accid' => 'USTN0035', 'name' => 'Belvidere');
$city_data[] = array('accid' => 'USTN0036', 'name' => 'Benton');
$city_data[] = array('accid' => 'USTN0037', 'name' => 'Bethel Springs');
$city_data[] = array('accid' => 'USTN0038', 'name' => 'Bethpage');
$city_data[] = array('accid' => 'USTN0039', 'name' => 'Big Rock');
$city_data[] = array('accid' => 'USTN0040', 'name' => 'Big Sandy');
$city_data[] = array('accid' => 'USTN0041', 'name' => 'Birchwood');
$city_data[] = array('accid' => 'USTN0042', 'name' => 'Blaine');
$city_data[] = array('accid' => 'USTN0043', 'name' => 'Bloomington Springs');
$city_data[] = array('accid' => 'USTN0044', 'name' => 'Blountville');
$city_data[] = array('accid' => 'USTN0045', 'name' => 'Bluff City');
$city_data[] = array('accid' => 'USTN0046', 'name' => 'Bogota');
$city_data[] = array('accid' => 'USTN0047', 'name' => 'Bolivar');
$city_data[] = array('accid' => 'USTN0048', 'name' => 'Bon Aqua');
$city_data[] = array('accid' => 'USTN0049', 'name' => 'Braden');
$city_data[] = array('accid' => 'USTN0050', 'name' => 'Bradford');
$city_data[] = array('accid' => 'USTN0051', 'name' => 'Bradyville');
$city_data[] = array('accid' => 'USTN0052', 'name' => 'Brentwood');
$city_data[] = array('accid' => 'USTN0053', 'name' => 'Briceville');
$city_data[] = array('accid' => 'USTN0054', 'name' => 'Brighton');
$city_data[] = array('accid' => 'USTN0055', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USTN0056', 'name' => 'Brownsville');
$city_data[] = array('accid' => 'USTN0057', 'name' => 'Bruceton');
$city_data[] = array('accid' => 'USTN0058', 'name' => 'Brunswick');
$city_data[] = array('accid' => 'USTN0059', 'name' => 'Brush Creek');
$city_data[] = array('accid' => 'USTN0060', 'name' => 'Buchanan');
$city_data[] = array('accid' => 'USTN0061', 'name' => 'Buena Vista');
$city_data[] = array('accid' => 'USTN0062', 'name' => 'Buffalo Valley');
$city_data[] = array('accid' => 'USTN0063', 'name' => 'Bulls Gap');
$city_data[] = array('accid' => 'USTN0064', 'name' => 'Bumpus Mills');
$city_data[] = array('accid' => 'USTN0065', 'name' => 'Burlison');
$city_data[] = array('accid' => 'USTN0066', 'name' => 'Burns');
$city_data[] = array('accid' => 'USTN0067', 'name' => 'Butler');
$city_data[] = array('accid' => 'USTN0068', 'name' => 'Bybee');
$city_data[] = array('accid' => 'USTN0069', 'name' => 'Byrdstown');
$city_data[] = array('accid' => 'USTN0070', 'name' => 'Calhoun');
$city_data[] = array('accid' => 'USTN0071', 'name' => 'Camden');
$city_data[] = array('accid' => 'USTN0072', 'name' => 'Campaign');
$city_data[] = array('accid' => 'USTN0073', 'name' => 'Carthage');
$city_data[] = array('accid' => 'USTN0074', 'name' => 'Caryville');
$city_data[] = array('accid' => 'USTN0075', 'name' => 'Castalian Springs');
$city_data[] = array('accid' => 'USTN0076', 'name' => 'Cedar Grove');
$city_data[] = array('accid' => 'USTN0077', 'name' => 'Cedar Hill');
$city_data[] = array('accid' => 'USTN0078', 'name' => 'Celina');
$city_data[] = array('accid' => 'USTN0079', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USTN0080', 'name' => 'Chapel Hill');
$city_data[] = array('accid' => 'USTN0081', 'name' => 'Chapmansboro');
$city_data[] = array('accid' => 'USTN0082', 'name' => 'Charleston');
$city_data[] = array('accid' => 'USTN0083', 'name' => 'Charlotte');
$city_data[] = array('accid' => 'USTN0084', 'name' => 'Chattanooga');
$city_data[] = array('accid' => 'USTN0085', 'name' => 'Chestnut Mound');
$city_data[] = array('accid' => 'USTN0086', 'name' => 'Chewalla');
$city_data[] = array('accid' => 'USTN0087', 'name' => 'Christiana');
$city_data[] = array('accid' => 'USTN0088', 'name' => 'Chuckey');
$city_data[] = array('accid' => 'USTN0089', 'name' => 'Church Hill');
$city_data[] = array('accid' => 'USTN0090', 'name' => 'Clairfield');
$city_data[] = array('accid' => 'USTN0091', 'name' => 'Clarkrange');
$city_data[] = array('accid' => 'USTN0092', 'name' => 'Clarksburg');
$city_data[] = array('accid' => 'USTN0093', 'name' => 'Clarksville');
$city_data[] = array('accid' => 'USTN0094', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USTN0095', 'name' => 'Clifton');
$city_data[] = array('accid' => 'USTN0096', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USTN0097', 'name' => 'Coalfield');
$city_data[] = array('accid' => 'USTN0098', 'name' => 'Coalmont');
$city_data[] = array('accid' => 'USTN0099', 'name' => 'Cokercreek');
$city_data[] = array('accid' => 'USTN0100', 'name' => 'College Grove');
$city_data[] = array('accid' => 'USTN0101', 'name' => 'Collegedale');
$city_data[] = array('accid' => 'USTN0102', 'name' => 'Collierville');
$city_data[] = array('accid' => 'USTN0103', 'name' => 'Collinwood');
$city_data[] = array('accid' => 'USTN0104', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USTN0105', 'name' => 'Como');
$city_data[] = array('accid' => 'USTN0106', 'name' => 'Conasauga');
$city_data[] = array('accid' => 'USTN0107', 'name' => 'Cookeville');
$city_data[] = array('accid' => 'USTN0108', 'name' => 'Copperhill');
$city_data[] = array('accid' => 'USTN0109', 'name' => 'Cordova');
$city_data[] = array('accid' => 'USTN0110', 'name' => 'Cornersville');
$city_data[] = array('accid' => 'USTN0111', 'name' => 'Corryton');
$city_data[] = array('accid' => 'USTN0112', 'name' => 'Cosby');
$city_data[] = array('accid' => 'USTN0113', 'name' => 'Cottage Grove');
$city_data[] = array('accid' => 'USTN0114', 'name' => 'Cottontown');
$city_data[] = array('accid' => 'USTN0115', 'name' => 'Counce');
$city_data[] = array('accid' => 'USTN0116', 'name' => 'Covington');
$city_data[] = array('accid' => 'USTN0117', 'name' => 'Cowan');
$city_data[] = array('accid' => 'USTN0118', 'name' => 'Crab Orchard');
$city_data[] = array('accid' => 'USTN0119', 'name' => 'Crawford');
$city_data[] = array('accid' => 'USTN0120', 'name' => 'Crockett Mills');
$city_data[] = array('accid' => 'USTN0121', 'name' => 'Cross Plains');
$city_data[] = array('accid' => 'USTN0122', 'name' => 'Crossville');
$city_data[] = array('accid' => 'USTN0123', 'name' => 'Crump');
$city_data[] = array('accid' => 'USTN0124', 'name' => 'Culleoka');
$city_data[] = array('accid' => 'USTN0125', 'name' => 'Cumberland City');
$city_data[] = array('accid' => 'USTN0126', 'name' => 'Cumberland Furnace');
$city_data[] = array('accid' => 'USTN0127', 'name' => 'Cumberland Gap');
$city_data[] = array('accid' => 'USTN0128', 'name' => 'Cunningham');
$city_data[] = array('accid' => 'USTN0129', 'name' => 'Cypress Inn');
$city_data[] = array('accid' => 'USTN0130', 'name' => 'Dandridge');
$city_data[] = array('accid' => 'USTN0131', 'name' => 'Darden');
$city_data[] = array('accid' => 'USTN0132', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USTN0133', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USTN0134', 'name' => 'Decaturville');
$city_data[] = array('accid' => 'USTN0135', 'name' => 'Decherd');
$city_data[] = array('accid' => 'USTN0136', 'name' => 'Deer Lodge');
$city_data[] = array('accid' => 'USTN0137', 'name' => 'Del Rio');
$city_data[] = array('accid' => 'USTN0138', 'name' => 'Delano');
$city_data[] = array('accid' => 'USTN0139', 'name' => 'Dellrose');
$city_data[] = array('accid' => 'USTN0140', 'name' => 'Denmark');
$city_data[] = array('accid' => 'USTN0141', 'name' => 'Dickson');
$city_data[] = array('accid' => 'USTN0142', 'name' => 'Dixon Springs');
$city_data[] = array('accid' => 'USTN0143', 'name' => 'Dover');
$city_data[] = array('accid' => 'USTN0144', 'name' => 'Dowelltown');
$city_data[] = array('accid' => 'USTN0145', 'name' => 'Doyle');
$city_data[] = array('accid' => 'USTN0146', 'name' => 'Dresden');
$city_data[] = array('accid' => 'USTN0147', 'name' => 'Drummonds');
$city_data[] = array('accid' => 'USTN0148', 'name' => 'Duck River');
$city_data[] = array('accid' => 'USTN0149', 'name' => 'Ducktown');
$city_data[] = array('accid' => 'USTN0150', 'name' => 'Duff');
$city_data[] = array('accid' => 'USTN0151', 'name' => 'Dukedom');
$city_data[] = array('accid' => 'USTN0152', 'name' => 'Dunlap');
$city_data[] = array('accid' => 'USTN0153', 'name' => 'Dyer');
$city_data[] = array('accid' => 'USTN0154', 'name' => 'Dyersburg');
$city_data[] = array('accid' => 'USTN0155', 'name' => 'Eads');
$city_data[] = array('accid' => 'USTN0156', 'name' => 'Eagan');
$city_data[] = array('accid' => 'USTN0157', 'name' => 'Eagleville');
$city_data[] = array('accid' => 'USTN0158', 'name' => 'Eaton');
$city_data[] = array('accid' => 'USTN0159', 'name' => 'Eidson');
$city_data[] = array('accid' => 'USTN0160', 'name' => 'Elgin');
$city_data[] = array('accid' => 'USTN0161', 'name' => 'Elizabethton');
$city_data[] = array('accid' => 'USTN0162', 'name' => 'Elkton');
$city_data[] = array('accid' => 'USTN0163', 'name' => 'Ellendale');
$city_data[] = array('accid' => 'USTN0164', 'name' => 'Elmwood');
$city_data[] = array('accid' => 'USTN0165', 'name' => 'Elora');
$city_data[] = array('accid' => 'USTN0166', 'name' => 'Englewood');
$city_data[] = array('accid' => 'USTN0167', 'name' => 'Enville');
$city_data[] = array('accid' => 'USTN0168', 'name' => 'Erin');
$city_data[] = array('accid' => 'USTN0169', 'name' => 'Erwin');
$city_data[] = array('accid' => 'USTN0170', 'name' => 'Estill Springs');
$city_data[] = array('accid' => 'USTN0171', 'name' => 'Ethridge');
$city_data[] = array('accid' => 'USTN0172', 'name' => 'Etowah');
$city_data[] = array('accid' => 'USTN0173', 'name' => 'Eva');
$city_data[] = array('accid' => 'USTN0174', 'name' => 'Evensville');
$city_data[] = array('accid' => 'USTN0175', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USTN0176', 'name' => 'Fall Branch');
$city_data[] = array('accid' => 'USTN0177', 'name' => 'Farner');
$city_data[] = array('accid' => 'USTN0178', 'name' => 'Fayetteville');
$city_data[] = array('accid' => 'USTN0179', 'name' => 'Finger');
$city_data[] = array('accid' => 'USTN0180', 'name' => 'Finley');
$city_data[] = array('accid' => 'USTN0181', 'name' => 'Five Points');
$city_data[] = array('accid' => 'USTN0182', 'name' => 'Flag Pond');
$city_data[] = array('accid' => 'USTN0183', 'name' => 'Flintville');
$city_data[] = array('accid' => 'USTN0184', 'name' => 'Fosterville');
$city_data[] = array('accid' => 'USTN0185', 'name' => 'Fowlkes');
$city_data[] = array('accid' => 'USTN0186', 'name' => 'Frankewing');
$city_data[] = array('accid' => 'USTN0187', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USTN0188', 'name' => 'Friendship');
$city_data[] = array('accid' => 'USTN0189', 'name' => 'Friendsville');
$city_data[] = array('accid' => 'USTN0190', 'name' => 'Fruitvale');
$city_data[] = array('accid' => 'USTN0191', 'name' => 'Gadsden');
$city_data[] = array('accid' => 'USTN0192', 'name' => 'Gainesboro');
$city_data[] = array('accid' => 'USTN0193', 'name' => 'Gallatin');
$city_data[] = array('accid' => 'USTN0194', 'name' => 'Gallaway');
$city_data[] = array('accid' => 'USTN0195', 'name' => 'Gates');
$city_data[] = array('accid' => 'USTN0196', 'name' => 'Gatlinburg');
$city_data[] = array('accid' => 'USTN0197', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USTN0198', 'name' => 'Germantown');
$city_data[] = array('accid' => 'USTN0199', 'name' => 'Gibson');
$city_data[] = array('accid' => 'USTN0200', 'name' => 'Gladeville');
$city_data[] = array('accid' => 'USTN0201', 'name' => 'Gleason');
$city_data[] = array('accid' => 'USTN0202', 'name' => 'Goodlettsville');
$city_data[] = array('accid' => 'USTN0203', 'name' => 'Goodspring');
$city_data[] = array('accid' => 'USTN0204', 'name' => 'Gordonsville');
$city_data[] = array('accid' => 'USTN0205', 'name' => 'Grand Junction');
$city_data[] = array('accid' => 'USTN0206', 'name' => 'Grandview');
$city_data[] = array('accid' => 'USTN0207', 'name' => 'Granville');
$city_data[] = array('accid' => 'USTN0208', 'name' => 'Graysville');
$city_data[] = array('accid' => 'USTN0210', 'name' => 'Greenback');
$city_data[] = array('accid' => 'USTN0211', 'name' => 'Greenbrier');
$city_data[] = array('accid' => 'USTN0212', 'name' => 'Greeneville');
$city_data[] = array('accid' => 'USTN0213', 'name' => 'Greenfield');
$city_data[] = array('accid' => 'USTN0214', 'name' => 'Grimsley');
$city_data[] = array('accid' => 'USTN0215', 'name' => 'Gruetli Laager');
$city_data[] = array('accid' => 'USTN0216', 'name' => 'Guild');
$city_data[] = array('accid' => 'USTN0217', 'name' => 'Guys');
$city_data[] = array('accid' => 'USTN0218', 'name' => 'Halls');
$city_data[] = array('accid' => 'USTN0219', 'name' => 'Hampshire');
$city_data[] = array('accid' => 'USTN0220', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USTN0221', 'name' => 'Harriman');
$city_data[] = array('accid' => 'USTN0222', 'name' => 'Harrison');
$city_data[] = array('accid' => 'USTN0223', 'name' => 'Harrogate');
$city_data[] = array('accid' => 'USTN0224', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USTN0225', 'name' => 'Hartsville');
$city_data[] = array('accid' => 'USTN0226', 'name' => 'Heiskell');
$city_data[] = array('accid' => 'USTN0227', 'name' => 'Helenwood');
$city_data[] = array('accid' => 'USTN0228', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USTN0229', 'name' => 'Hendersonville');
$city_data[] = array('accid' => 'USTN0230', 'name' => 'Henning');
$city_data[] = array('accid' => 'USTN0231', 'name' => 'Henry');
$city_data[] = array('accid' => 'USTN0232', 'name' => 'Hermitage');
$city_data[] = array('accid' => 'USTN0233', 'name' => 'Hickman');
$city_data[] = array('accid' => 'USTN0234', 'name' => 'Hickory Valley');
$city_data[] = array('accid' => 'USTN0235', 'name' => 'Hickory Withe');
$city_data[] = array('accid' => 'USTN0236', 'name' => 'Hilham');
$city_data[] = array('accid' => 'USTN0237', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USTN0238', 'name' => 'Hixson');
$city_data[] = array('accid' => 'USTN0239', 'name' => 'Hohenwald');
$city_data[] = array('accid' => 'USTN0240', 'name' => 'Holladay');
$city_data[] = array('accid' => 'USTN0241', 'name' => 'Hollow Rock');
$city_data[] = array('accid' => 'USTN0242', 'name' => 'Hornbeak');
$city_data[] = array('accid' => 'USTN0243', 'name' => 'Hornsby');
$city_data[] = array('accid' => 'USTN0244', 'name' => 'Humboldt');
$city_data[] = array('accid' => 'USTN0245', 'name' => 'Huntingdon');
$city_data[] = array('accid' => 'USTN0246', 'name' => 'Huntland');
$city_data[] = array('accid' => 'USTN0247', 'name' => 'Huntsville');
$city_data[] = array('accid' => 'USTN0248', 'name' => 'Huron');
$city_data[] = array('accid' => 'USTN0249', 'name' => 'Hurricane Mills');
$city_data[] = array('accid' => 'USTN0250', 'name' => 'Idlewild');
$city_data[] = array('accid' => 'USTN0251', 'name' => 'Indian Mound');
$city_data[] = array('accid' => 'USTN0252', 'name' => 'Iron City');
$city_data[] = array('accid' => 'USTN0253', 'name' => 'Jacks Creek');
$city_data[] = array('accid' => 'USTN0254', 'name' => 'Jacksboro');
$city_data[] = array('accid' => 'USTN0255', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USTN0256', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USTN0257', 'name' => 'Jasper');
$city_data[] = array('accid' => 'USTN0258', 'name' => 'Jefferson City');
$city_data[] = array('accid' => 'USTN0259', 'name' => 'Jellico');
$city_data[] = array('accid' => 'USTN0260', 'name' => 'Joelton');
$city_data[] = array('accid' => 'USTN0261', 'name' => 'Johnson City');
$city_data[] = array('accid' => 'USTN0262', 'name' => 'Jonesborough');
$city_data[] = array('accid' => 'USTN0263', 'name' => 'Kelso');
$city_data[] = array('accid' => 'USTN0264', 'name' => 'Kenton');
$city_data[] = array('accid' => 'USTN0265', 'name' => 'Kingsport');
$city_data[] = array('accid' => 'USTN0266', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USTN0267', 'name' => 'Kingston Springs');
$city_data[] = array('accid' => 'USTN0268', 'name' => 'Knoxville');
$city_data[] = array('accid' => 'USTN0269', 'name' => 'Kodak');
$city_data[] = array('accid' => 'USTN0270', 'name' => 'Kyles Ford');
$city_data[] = array('accid' => 'USTN0271', 'name' => 'La Follette');
$city_data[] = array('accid' => 'USTN0272', 'name' => 'La Grange');
$city_data[] = array('accid' => 'USTN0273', 'name' => 'La Vergne');
$city_data[] = array('accid' => 'USTN0274', 'name' => 'Laconia');
$city_data[] = array('accid' => 'USTN0275', 'name' => 'Lafayette');
$city_data[] = array('accid' => 'USTN0276', 'name' => 'Lake City');
$city_data[] = array('accid' => 'USTN0277', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USTN0278', 'name' => 'Lancing');
$city_data[] = array('accid' => 'USTN0279', 'name' => 'Lascassas');
$city_data[] = array('accid' => 'USTN0280', 'name' => 'Laurel Bloomery');
$city_data[] = array('accid' => 'USTN0281', 'name' => 'Lavinia');
$city_data[] = array('accid' => 'USTN0282', 'name' => 'Lawrenceburg');
$city_data[] = array('accid' => 'USTN0283', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USTN0284', 'name' => 'Lenoir City');
$city_data[] = array('accid' => 'USTN0285', 'name' => 'Lenox');
$city_data[] = array('accid' => 'USTN0286', 'name' => 'Leoma');
$city_data[] = array('accid' => 'USTN0287', 'name' => 'Lewisburg');
$city_data[] = array('accid' => 'USTN0288', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USTN0289', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USTN0290', 'name' => 'Limestone');
$city_data[] = array('accid' => 'USTN0291', 'name' => 'Linden');
$city_data[] = array('accid' => 'USTN0292', 'name' => 'Livingston');
$city_data[] = array('accid' => 'USTN0293', 'name' => 'Lobelville');
$city_data[] = array('accid' => 'USTN0294', 'name' => 'Lone Mountain');
$city_data[] = array('accid' => 'USTN0295', 'name' => 'Lookout Mountain');
$city_data[] = array('accid' => 'USTN0296', 'name' => 'Loretto');
$city_data[] = array('accid' => 'USTN0297', 'name' => 'Loudon');
$city_data[] = array('accid' => 'USTN0298', 'name' => 'Louisville');
$city_data[] = array('accid' => 'USTN0299', 'name' => 'Lowland');
$city_data[] = array('accid' => 'USTN0300', 'name' => 'Lupton City');
$city_data[] = array('accid' => 'USTN0301', 'name' => 'Luray');
$city_data[] = array('accid' => 'USTN0302', 'name' => 'Luttrell');
$city_data[] = array('accid' => 'USTN0303', 'name' => 'Lutts');
$city_data[] = array('accid' => 'USTN0304', 'name' => 'Lyles');
$city_data[] = array('accid' => 'USTN0305', 'name' => 'Lynchburg');
$city_data[] = array('accid' => 'USTN0306', 'name' => 'Lynnville');
$city_data[] = array('accid' => 'USTN0307', 'name' => 'Macon');
$city_data[] = array('accid' => 'USTN0308', 'name' => 'Madison');
$city_data[] = array('accid' => 'USTN0309', 'name' => 'Madisonville');
$city_data[] = array('accid' => 'USTN0310', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USTN0311', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'USTN0312', 'name' => 'Martin');
$city_data[] = array('accid' => 'USTN0313', 'name' => 'Maryville');
$city_data[] = array('accid' => 'USTN0314', 'name' => 'Mascot');
$city_data[] = array('accid' => 'USTN0315', 'name' => 'Mason');
$city_data[] = array('accid' => 'USTN0316', 'name' => 'Maury City');
$city_data[] = array('accid' => 'USTN0317', 'name' => 'Maynardville');
$city_data[] = array('accid' => 'USTN0318', 'name' => 'McDonald');
$city_data[] = array('accid' => 'USTN0319', 'name' => 'McEwen');
$city_data[] = array('accid' => 'USTN0320', 'name' => 'McKenzie');
$city_data[] = array('accid' => 'USTN0321', 'name' => 'McLemoresville');
$city_data[] = array('accid' => 'USTN0322', 'name' => 'McMinnville');
$city_data[] = array('accid' => 'USTN0323', 'name' => 'Medina');
$city_data[] = array('accid' => 'USTN0324', 'name' => 'Medon');
$city_data[] = array('accid' => 'USTN0325', 'name' => 'Memphis');
$city_data[] = array('accid' => 'USTN0326', 'name' => 'Mercer');
$city_data[] = array('accid' => 'USTN0327', 'name' => 'Michie');
$city_data[] = array('accid' => 'USTN0328', 'name' => 'Middleton');
$city_data[] = array('accid' => 'USTN0329', 'name' => 'Midway');
$city_data[] = array('accid' => 'USTN0330', 'name' => 'Milan');
$city_data[] = array('accid' => 'USTN0331', 'name' => 'Milledgeville');
$city_data[] = array('accid' => 'USTN0332', 'name' => 'Milligan College');
$city_data[] = array('accid' => 'USTN0333', 'name' => 'Millington');
$city_data[] = array('accid' => 'USTN0334', 'name' => 'Milton');
$city_data[] = array('accid' => 'USTN0335', 'name' => 'Minor Hill');
$city_data[] = array('accid' => 'USTN0336', 'name' => 'Miston');
$city_data[] = array('accid' => 'USTN0337', 'name' => 'Mitchellville');
$city_data[] = array('accid' => 'USTN0338', 'name' => 'Mohawk');
$city_data[] = array('accid' => 'USTN0339', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USTN0340', 'name' => 'Monteagle');
$city_data[] = array('accid' => 'USTN0341', 'name' => 'Monterey');
$city_data[] = array('accid' => 'USTN0342', 'name' => 'Mooresburg');
$city_data[] = array('accid' => 'USTN0343', 'name' => 'Morris Chapel');
$city_data[] = array('accid' => 'USTN0344', 'name' => 'Morrison');
$city_data[] = array('accid' => 'USTN0345', 'name' => 'Morristown');
$city_data[] = array('accid' => 'USTN0346', 'name' => 'Moscow');
$city_data[] = array('accid' => 'USTN0347', 'name' => 'Mosheim');
$city_data[] = array('accid' => 'USTN0348', 'name' => 'Moss');
$city_data[] = array('accid' => 'USTN0349', 'name' => 'Mount Carmel');
$city_data[] = array('accid' => 'USTN0350', 'name' => 'Mount Juliet');
$city_data[] = array('accid' => 'USTN0351', 'name' => 'Mount Pleasant');
$city_data[] = array('accid' => 'USTN0352', 'name' => 'Mountain City');
$city_data[] = array('accid' => 'USTN0353', 'name' => 'Mountain Home');
$city_data[] = array('accid' => 'USTN0354', 'name' => 'Mulberry');
$city_data[] = array('accid' => 'USTN0355', 'name' => 'Munford');
$city_data[] = array('accid' => 'USTN0356', 'name' => 'Murfreesboro');
$city_data[] = array('accid' => 'USTN0357', 'name' => 'Nashville');
$city_data[] = array('accid' => 'USTN0358', 'name' => 'New Johnsonville');
$city_data[] = array('accid' => 'USTN0359', 'name' => 'New Market');
$city_data[] = array('accid' => 'USTN0360', 'name' => 'New Tazewell');
$city_data[] = array('accid' => 'USTN0361', 'name' => 'Newbern');
$city_data[] = array('accid' => 'USTN0362', 'name' => 'Newcomb');
$city_data[] = array('accid' => 'USTN0363', 'name' => 'Newport');
$city_data[] = array('accid' => 'USTN0364', 'name' => 'Niota');
$city_data[] = array('accid' => 'USTN0365', 'name' => 'Nolensville');
$city_data[] = array('accid' => 'USTN0366', 'name' => 'Norene');
$city_data[] = array('accid' => 'USTN0367', 'name' => 'Normandy');
$city_data[] = array('accid' => 'USTN0368', 'name' => 'Norris');
$city_data[] = array('accid' => 'USTN0369', 'name' => 'Nunnelly');
$city_data[] = array('accid' => 'USTN0370', 'name' => 'Oak Ridge');
$city_data[] = array('accid' => 'USTN0371', 'name' => 'Oakdale');
$city_data[] = array('accid' => 'USTN0372', 'name' => 'Oakfield');
$city_data[] = array('accid' => 'USTN0373', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USTN0374', 'name' => 'Obion');
$city_data[] = array('accid' => 'USTN0375', 'name' => 'Ocoee');
$city_data[] = array('accid' => 'USTN0376', 'name' => 'Old Hickory');
$city_data[] = array('accid' => 'USTN0377', 'name' => 'Oldfort');
$city_data[] = array('accid' => 'USTN0378', 'name' => 'Olivehill');
$city_data[] = array('accid' => 'USTN0379', 'name' => 'Oliver Springs');
$city_data[] = array('accid' => 'USTN0380', 'name' => 'Oneida');
$city_data[] = array('accid' => 'USTN0381', 'name' => 'Only');
$city_data[] = array('accid' => 'USTN0382', 'name' => 'Ooltewah');
$city_data[] = array('accid' => 'USTN0383', 'name' => 'Orlinda');
$city_data[] = array('accid' => 'USTN0384', 'name' => 'Ozone');
$city_data[] = array('accid' => 'USTN0385', 'name' => 'Pall Mall');
$city_data[] = array('accid' => 'USTN0386', 'name' => 'Palmer');
$city_data[] = array('accid' => 'USTN0387', 'name' => 'Palmersville');
$city_data[] = array('accid' => 'USTN0388', 'name' => 'Palmyra');
$city_data[] = array('accid' => 'USTN0389', 'name' => 'Paris');
$city_data[] = array('accid' => 'USTN0390', 'name' => 'Parrottsville');
$city_data[] = array('accid' => 'USTN0391', 'name' => 'Parsons');
$city_data[] = array('accid' => 'USTN0392', 'name' => 'Pegram');
$city_data[] = array('accid' => 'USTN0393', 'name' => 'Pelham');
$city_data[] = array('accid' => 'USTN0394', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USTN0395', 'name' => 'Petros');
$city_data[] = array('accid' => 'USTN0396', 'name' => 'Philadelphia');
$city_data[] = array('accid' => 'USTN0397', 'name' => 'Pickwick Dam');
$city_data[] = array('accid' => 'USTN0398', 'name' => 'Pigeon Forge');
$city_data[] = array('accid' => 'USTN0399', 'name' => 'Pikeville');
$city_data[] = array('accid' => 'USTN0400', 'name' => 'Piney Flats');
$city_data[] = array('accid' => 'USTN0401', 'name' => 'Pinson');
$city_data[] = array('accid' => 'USTN0402', 'name' => 'Pioneer');
$city_data[] = array('accid' => 'USTN0403', 'name' => 'Pleasant Hill');
$city_data[] = array('accid' => 'USTN0404', 'name' => 'Pleasant Shade');
$city_data[] = array('accid' => 'USTN0405', 'name' => 'Pleasant View');
$city_data[] = array('accid' => 'USTN0406', 'name' => 'Pleasantville');
$city_data[] = array('accid' => 'USTN0407', 'name' => 'Pocahontas');
$city_data[] = array('accid' => 'USTN0408', 'name' => 'Portland');
$city_data[] = array('accid' => 'USTN0409', 'name' => 'Powder Springs');
$city_data[] = array('accid' => 'USTN0410', 'name' => 'Powell');
$city_data[] = array('accid' => 'USTN0411', 'name' => 'Primm Springs');
$city_data[] = array('accid' => 'USTN0412', 'name' => 'Prospect');
$city_data[] = array('accid' => 'USTN0413', 'name' => 'Pruden');
$city_data[] = array('accid' => 'USTN0414', 'name' => 'Pulaski');
$city_data[] = array('accid' => 'USTN0415', 'name' => 'Puryear');
$city_data[] = array('accid' => 'USTN0416', 'name' => 'Quebeck');
$city_data[] = array('accid' => 'USTN0417', 'name' => 'Ramer');
$city_data[] = array('accid' => 'USTN0418', 'name' => 'Readyville');
$city_data[] = array('accid' => 'USTN0419', 'name' => 'Reagan');
$city_data[] = array('accid' => 'USTN0420', 'name' => 'Red Boiling Springs');
$city_data[] = array('accid' => 'USTN0421', 'name' => 'Reliance');
$city_data[] = array('accid' => 'USTN0422', 'name' => 'Riceville');
$city_data[] = array('accid' => 'USTN0423', 'name' => 'Rickman');
$city_data[] = array('accid' => 'USTN0424', 'name' => 'Riddleton');
$city_data[] = array('accid' => 'USTN0425', 'name' => 'Ridgely');
$city_data[] = array('accid' => 'USTN0426', 'name' => 'Ridgetop');
$city_data[] = array('accid' => 'USTN0427', 'name' => 'Ripley');
$city_data[] = array('accid' => 'USTN0428', 'name' => 'Rives');
$city_data[] = array('accid' => 'USTN0429', 'name' => 'Roan Mountain');
$city_data[] = array('accid' => 'USTN0430', 'name' => 'Robbins');
$city_data[] = array('accid' => 'USTN0431', 'name' => 'Rock Island');
$city_data[] = array('accid' => 'USTN0432', 'name' => 'Rockford');
$city_data[] = array('accid' => 'USTN0433', 'name' => 'Rockvale');
$city_data[] = array('accid' => 'USTN0434', 'name' => 'Rockwood');
$city_data[] = array('accid' => 'USTN0435', 'name' => 'Rogersville');
$city_data[] = array('accid' => 'USTN0436', 'name' => 'Rossville');
$city_data[] = array('accid' => 'USTN0437', 'name' => 'Rugby');
$city_data[] = array('accid' => 'USTN0438', 'name' => 'Russellville');
$city_data[] = array('accid' => 'USTN0439', 'name' => 'Rutherford');
$city_data[] = array('accid' => 'USTN0440', 'name' => 'Rutledge');
$city_data[] = array('accid' => 'USTN0441', 'name' => 'Saint Andrews');
$city_data[] = array('accid' => 'USTN0442', 'name' => 'Saint Bethlehem');
$city_data[] = array('accid' => 'USTN0443', 'name' => 'Saint Joseph');
$city_data[] = array('accid' => 'USTN0444', 'name' => 'Sale Creek');
$city_data[] = array('accid' => 'USTN0445', 'name' => 'Saltillo');
$city_data[] = array('accid' => 'USTN0446', 'name' => 'Samburg');
$city_data[] = array('accid' => 'USTN0447', 'name' => 'Santa Fe');
$city_data[] = array('accid' => 'USTN0448', 'name' => 'Sardis');
$city_data[] = array('accid' => 'USTN0449', 'name' => 'Saulsbury');
$city_data[] = array('accid' => 'USTN0450', 'name' => 'Savannah');
$city_data[] = array('accid' => 'USTN0451', 'name' => 'Scotts Hill');
$city_data[] = array('accid' => 'USTN0452', 'name' => 'Selmer');
$city_data[] = array('accid' => 'USTN0453', 'name' => 'Sequatchie');
$city_data[] = array('accid' => 'USTN0454', 'name' => 'Sevierville');
$city_data[] = array('accid' => 'USTN0455', 'name' => 'Sewanee');
$city_data[] = array('accid' => 'USTN0456', 'name' => 'Seymour');
$city_data[] = array('accid' => 'USTN0457', 'name' => 'Shady Valley');
$city_data[] = array('accid' => 'USTN0458', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USTN0459', 'name' => 'Sharps Chapel');
$city_data[] = array('accid' => 'USTN0460', 'name' => 'Shawanee');
$city_data[] = array('accid' => 'USTN0461', 'name' => 'Shelbyville');
$city_data[] = array('accid' => 'USTN0462', 'name' => 'Sherwood');
$city_data[] = array('accid' => 'USTN0463', 'name' => 'Shiloh');
$city_data[] = array('accid' => 'USTN0464', 'name' => 'Signal Mountain');
$city_data[] = array('accid' => 'USTN0465', 'name' => 'Silerton');
$city_data[] = array('accid' => 'USTN0466', 'name' => 'Silver Point');
$city_data[] = array('accid' => 'USTN0467', 'name' => 'Slayden');
$city_data[] = array('accid' => 'USTN0468', 'name' => 'Smartt');
$city_data[] = array('accid' => 'USTN0469', 'name' => 'Smithville');
$city_data[] = array('accid' => 'USTN0470', 'name' => 'Smyrna');
$city_data[] = array('accid' => 'USTN0471', 'name' => 'Sneedville');
$city_data[] = array('accid' => 'USTN0472', 'name' => 'Soddy Daisy');
$city_data[] = array('accid' => 'USTN0473', 'name' => 'Somerville');
$city_data[] = array('accid' => 'USTN0474', 'name' => 'South Fulton');
$city_data[] = array('accid' => 'USTN0475', 'name' => 'South Pittsburg');
$city_data[] = array('accid' => 'USTN0476', 'name' => 'Southside');
$city_data[] = array('accid' => 'USTN0477', 'name' => 'Sparta');
$city_data[] = array('accid' => 'USTN0478', 'name' => 'Speedwell');
$city_data[] = array('accid' => 'USTN0479', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USTN0480', 'name' => 'Spring City');
$city_data[] = array('accid' => 'USTN0481', 'name' => 'Spring Creek');
$city_data[] = array('accid' => 'USTN0482', 'name' => 'Spring Hill');
$city_data[] = array('accid' => 'USTN0483', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USTN0484', 'name' => 'Springville');
$city_data[] = array('accid' => 'USTN0485', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USTN0486', 'name' => 'Stantonville');
$city_data[] = array('accid' => 'USTN0487', 'name' => 'Stewart');
$city_data[] = array('accid' => 'USTN0488', 'name' => 'Strawberry Plains');
$city_data[] = array('accid' => 'USTN0489', 'name' => 'Sugar Tree');
$city_data[] = array('accid' => 'USTN0490', 'name' => 'Summertown');
$city_data[] = array('accid' => 'USTN0491', 'name' => 'Summitville');
$city_data[] = array('accid' => 'USTN0492', 'name' => 'Sunbright');
$city_data[] = array('accid' => 'USTN0493', 'name' => 'Surgoinsville');
$city_data[] = array('accid' => 'USTN0494', 'name' => 'Sweetwater');
$city_data[] = array('accid' => 'USTN0495', 'name' => 'Taft');
$city_data[] = array('accid' => 'USTN0496', 'name' => 'Talbott');
$city_data[] = array('accid' => 'USTN0497', 'name' => 'Tallassee');
$city_data[] = array('accid' => 'USTN0498', 'name' => 'Tazewell');
$city_data[] = array('accid' => 'USTN0499', 'name' => 'Telford');
$city_data[] = array('accid' => 'USTN0500', 'name' => 'Tellico Plains');
$city_data[] = array('accid' => 'USTN0501', 'name' => 'Ten Mile');
$city_data[] = array('accid' => 'USTN0502', 'name' => 'Tennessee Ridge');
$city_data[] = array('accid' => 'USTN0503', 'name' => 'Thompsons Station');
$city_data[] = array('accid' => 'USTN0504', 'name' => 'Thorn Hill');
$city_data[] = array('accid' => 'USTN0505', 'name' => 'Tigrett');
$city_data[] = array('accid' => 'USTN0506', 'name' => 'Tipton');
$city_data[] = array('accid' => 'USTN0507', 'name' => 'Tiptonville');
$city_data[] = array('accid' => 'USTN0508', 'name' => 'Toone');
$city_data[] = array('accid' => 'USTN0509', 'name' => 'Townsend');
$city_data[] = array('accid' => 'USTN0510', 'name' => 'Tracy City');
$city_data[] = array('accid' => 'USTN0511', 'name' => 'Trade');
$city_data[] = array('accid' => 'USTN0512', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USTN0513', 'name' => 'Trezevant');
$city_data[] = array('accid' => 'USTN0514', 'name' => 'Trimble');
$city_data[] = array('accid' => 'USTN0515', 'name' => 'Troy');
$city_data[] = array('accid' => 'USTN0516', 'name' => 'Tullahoma');
$city_data[] = array('accid' => 'USTN0517', 'name' => 'Turtletown');
$city_data[] = array('accid' => 'USTN0518', 'name' => 'Unicoi');
$city_data[] = array('accid' => 'USTN0519', 'name' => 'Union City');
$city_data[] = array('accid' => 'USTN0520', 'name' => 'Unionville');
$city_data[] = array('accid' => 'USTN0521', 'name' => 'Vanleer');
$city_data[] = array('accid' => 'USTN0522', 'name' => 'Viola');
$city_data[] = array('accid' => 'USTN0523', 'name' => 'Vonore');
$city_data[] = array('accid' => 'USTN0524', 'name' => 'Walland');
$city_data[] = array('accid' => 'USTN0525', 'name' => 'Walling');
$city_data[] = array('accid' => 'USTN0526', 'name' => 'Wartburg');
$city_data[] = array('accid' => 'USTN0527', 'name' => 'Wartrace');
$city_data[] = array('accid' => 'USTN0528', 'name' => 'Washburn');
$city_data[] = array('accid' => 'USTN0529', 'name' => 'Watauga');
$city_data[] = array('accid' => 'USTN0530', 'name' => 'Watertown');
$city_data[] = array('accid' => 'USTN0531', 'name' => 'Watts Bar Dam');
$city_data[] = array('accid' => 'USTN0532', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USTN0533', 'name' => 'Waynesboro');
$city_data[] = array('accid' => 'USTN0534', 'name' => 'Westmoreland');
$city_data[] = array('accid' => 'USTN0535', 'name' => 'Westpoint');
$city_data[] = array('accid' => 'USTN0536', 'name' => 'Westport');
$city_data[] = array('accid' => 'USTN0537', 'name' => 'White Bluff');
$city_data[] = array('accid' => 'USTN0538', 'name' => 'White House');
$city_data[] = array('accid' => 'USTN0539', 'name' => 'White Pine');
$city_data[] = array('accid' => 'USTN0540', 'name' => 'Whites Creek');
$city_data[] = array('accid' => 'USTN0541', 'name' => 'Whitesburg');
$city_data[] = array('accid' => 'USTN0542', 'name' => 'Whiteside');
$city_data[] = array('accid' => 'USTN0543', 'name' => 'Whiteville');
$city_data[] = array('accid' => 'USTN0544', 'name' => 'Whitleyville');
$city_data[] = array('accid' => 'USTN0545', 'name' => 'Whitwell');
$city_data[] = array('accid' => 'USTN0546', 'name' => 'Wilder');
$city_data[] = array('accid' => 'USTN0547', 'name' => 'Wildersville');
$city_data[] = array('accid' => 'USTN0548', 'name' => 'Williamsport');
$city_data[] = array('accid' => 'USTN0549', 'name' => 'Williston');
$city_data[] = array('accid' => 'USTN0550', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USTN0551', 'name' => 'Winfield');
$city_data[] = array('accid' => 'USTN0552', 'name' => 'Winona');
$city_data[] = array('accid' => 'USTN0553', 'name' => 'Woodbury');
$city_data[] = array('accid' => 'USTN0554', 'name' => 'Woodland Mills');
$city_data[] = array('accid' => 'USTN0555', 'name' => 'Woodlawn');
$city_data[] = array('accid' => 'USTN0556', 'name' => 'Wynnburg');
$city_data[] = array('accid' => 'USTN0557', 'name' => 'Yorkville');
$city_data[] = array('accid' => 'USTN0558', 'name' => 'Yuma');

?>
