<?php

// City package for USA: Texas

$city_name = 'USA: Texas';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USTX0001', 'name' => 'Abbott');
$city_data[] = array('accid' => 'USTX0002', 'name' => 'Abernathy');
$city_data[] = array('accid' => 'USTX0003', 'name' => 'Abilene');
$city_data[] = array('accid' => 'USTX0005', 'name' => 'Ace');
$city_data[] = array('accid' => 'USTX0006', 'name' => 'Ackerly');
$city_data[] = array('accid' => 'USTX0007', 'name' => 'Addison');
$city_data[] = array('accid' => 'USTX0008', 'name' => 'Adkins');
$city_data[] = array('accid' => 'USTX0009', 'name' => 'Adrian');
$city_data[] = array('accid' => 'USTX0010', 'name' => 'Afton');
$city_data[] = array('accid' => 'USTX0011', 'name' => 'Agua Dulce');
$city_data[] = array('accid' => 'USTX0012', 'name' => 'Aiken');
$city_data[] = array('accid' => 'USTX0013', 'name' => 'Alamo');
$city_data[] = array('accid' => 'USTX0014', 'name' => 'Alanreed');
$city_data[] = array('accid' => 'USTX0015', 'name' => 'Alba');
$city_data[] = array('accid' => 'USTX0016', 'name' => 'Albany');
$city_data[] = array('accid' => 'USTX0017', 'name' => 'Aledo');
$city_data[] = array('accid' => 'USTX0018', 'name' => 'Alice');
$city_data[] = array('accid' => 'USTX0019', 'name' => 'Alief');
$city_data[] = array('accid' => 'USTX0020', 'name' => 'Allen');
$city_data[] = array('accid' => 'USTX0021', 'name' => 'Alleyton');
$city_data[] = array('accid' => 'USTX0022', 'name' => 'Allison');
$city_data[] = array('accid' => 'USTX0023', 'name' => 'Alpine');
$city_data[] = array('accid' => 'USTX0024', 'name' => 'Altair');
$city_data[] = array('accid' => 'USTX0025', 'name' => 'Alto');
$city_data[] = array('accid' => 'USTX0026', 'name' => 'Alvarado');
$city_data[] = array('accid' => 'USTX0027', 'name' => 'Alvin');
$city_data[] = array('accid' => 'USTX0028', 'name' => 'Alvord');
$city_data[] = array('accid' => 'USTX0029', 'name' => 'Amarillo');
$city_data[] = array('accid' => 'USTX0030', 'name' => 'Amherst');
$city_data[] = array('accid' => 'USTX0031', 'name' => 'Anahuac');
$city_data[] = array('accid' => 'USTX0032', 'name' => 'Anderson');
$city_data[] = array('accid' => 'USTX0033', 'name' => 'Andrews');
$city_data[] = array('accid' => 'USTX0034', 'name' => 'Angleton');
$city_data[] = array('accid' => 'USTX0035', 'name' => 'Anna');
$city_data[] = array('accid' => 'USTX0036', 'name' => 'Annona');
$city_data[] = array('accid' => 'USTX0037', 'name' => 'Anson');
$city_data[] = array('accid' => 'USTX0038', 'name' => 'Anthony');
$city_data[] = array('accid' => 'USTX0039', 'name' => 'Anton');
$city_data[] = array('accid' => 'USTX0040', 'name' => 'Apple Springs');
$city_data[] = array('accid' => 'USTX0041', 'name' => 'Aquilla');
$city_data[] = array('accid' => 'USTX0042', 'name' => 'Aransas Pass');
$city_data[] = array('accid' => 'USTX0043', 'name' => 'Archer City');
$city_data[] = array('accid' => 'USTX0044', 'name' => 'Argyle');
$city_data[] = array('accid' => 'USTX0045', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USTX0046', 'name' => 'Armstrong');
$city_data[] = array('accid' => 'USTX0047', 'name' => 'Arp');
$city_data[] = array('accid' => 'USTX0048', 'name' => 'Art');
$city_data[] = array('accid' => 'USTX0049', 'name' => 'Artesia Wells');
$city_data[] = array('accid' => 'USTX0050', 'name' => 'Arthur City');
$city_data[] = array('accid' => 'USTX0051', 'name' => 'Asherton');
$city_data[] = array('accid' => 'USTX0052', 'name' => 'Aspermont');
$city_data[] = array('accid' => 'USTX0053', 'name' => 'Atascosa');
$city_data[] = array('accid' => 'USTX0054', 'name' => 'Athens');
$city_data[] = array('accid' => 'USTX0055', 'name' => 'Atlanta');
$city_data[] = array('accid' => 'USTX0056', 'name' => 'Aubrey');
$city_data[] = array('accid' => 'USTX0057', 'name' => 'Austin');
$city_data[] = array('accid' => 'USTX0059', 'name' => 'Austwell');
$city_data[] = array('accid' => 'USTX0060', 'name' => 'Avalon');
$city_data[] = array('accid' => 'USTX0061', 'name' => 'Avery');
$city_data[] = array('accid' => 'USTX0062', 'name' => 'Avinger');
$city_data[] = array('accid' => 'USTX0063', 'name' => 'Avoca');
$city_data[] = array('accid' => 'USTX0064', 'name' => 'Axtell');
$city_data[] = array('accid' => 'USTX0065', 'name' => 'Azle');
$city_data[] = array('accid' => 'USTX0066', 'name' => 'Bacliff');
$city_data[] = array('accid' => 'USTX0067', 'name' => 'Bagwell');
$city_data[] = array('accid' => 'USTX0068', 'name' => 'Bailey');
$city_data[] = array('accid' => 'USTX0069', 'name' => 'Baird');
$city_data[] = array('accid' => 'USTX0070', 'name' => 'Ballinger');
$city_data[] = array('accid' => 'USTX0071', 'name' => 'Balmorhea');
$city_data[] = array('accid' => 'USTX0072', 'name' => 'Bandera');
$city_data[] = array('accid' => 'USTX0073', 'name' => 'Bangs');
$city_data[] = array('accid' => 'USTX0074', 'name' => 'Banquete');
$city_data[] = array('accid' => 'USTX0075', 'name' => 'Bardwell');
$city_data[] = array('accid' => 'USTX0076', 'name' => 'Barker');
$city_data[] = array('accid' => 'USTX0077', 'name' => 'Barksdale');
$city_data[] = array('accid' => 'USTX0078', 'name' => 'Barnhart');
$city_data[] = array('accid' => 'USTX0079', 'name' => 'Barry');
$city_data[] = array('accid' => 'USTX0080', 'name' => 'Barstow');
$city_data[] = array('accid' => 'USTX0081', 'name' => 'Bartlett');
$city_data[] = array('accid' => 'USTX0082', 'name' => 'Bastrop');
$city_data[] = array('accid' => 'USTX0083', 'name' => 'Batesville');
$city_data[] = array('accid' => 'USTX0084', 'name' => 'Batson');
$city_data[] = array('accid' => 'USTX0085', 'name' => 'Bay City');
$city_data[] = array('accid' => 'USTX0086', 'name' => 'Bayside');
$city_data[] = array('accid' => 'USTX0087', 'name' => 'Baytown');
$city_data[] = array('accid' => 'USTX0088', 'name' => 'Beasley');
$city_data[] = array('accid' => 'USTX0089', 'name' => 'Beaumont');
$city_data[] = array('accid' => 'USTX0091', 'name' => 'Bebe');
$city_data[] = array('accid' => 'USTX0092', 'name' => 'Beckville');
$city_data[] = array('accid' => 'USTX0093', 'name' => 'Bedford');
$city_data[] = array('accid' => 'USTX0094', 'name' => 'Bedias');
$city_data[] = array('accid' => 'USTX0095', 'name' => 'Beeville');
$city_data[] = array('accid' => 'USTX0096', 'name' => 'Bellaire');
$city_data[] = array('accid' => 'USTX0097', 'name' => 'Bellevue');
$city_data[] = array('accid' => 'USTX0098', 'name' => 'Bells');
$city_data[] = array('accid' => 'USTX0099', 'name' => 'Bellville');
$city_data[] = array('accid' => 'USTX0100', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USTX0101', 'name' => 'Belton');
$city_data[] = array('accid' => 'USTX0102', 'name' => 'Ben Bolt');
$city_data[] = array('accid' => 'USTX0103', 'name' => 'Ben Franklin');
$city_data[] = array('accid' => 'USTX0104', 'name' => 'Ben Wheeler');
$city_data[] = array('accid' => 'USTX0105', 'name' => 'Benavides');
$city_data[] = array('accid' => 'USTX0106', 'name' => 'Bend');
$city_data[] = array('accid' => 'USTX0107', 'name' => 'Benjamin');
$city_data[] = array('accid' => 'USTX0108', 'name' => 'Berclair');
$city_data[] = array('accid' => 'USTX0109', 'name' => 'Bergheim');
$city_data[] = array('accid' => 'USTX0110', 'name' => 'Bertram');
$city_data[] = array('accid' => 'USTX0111', 'name' => 'Big Bend Natl Park');
$city_data[] = array('accid' => 'USTX0112', 'name' => 'Big Lake');
$city_data[] = array('accid' => 'USTX0113', 'name' => 'Big Sandy');
$city_data[] = array('accid' => 'USTX0114', 'name' => 'Big Spring');
$city_data[] = array('accid' => 'USTX0115', 'name' => 'Big Wells');
$city_data[] = array('accid' => 'USTX0116', 'name' => 'Bigfoot');
$city_data[] = array('accid' => 'USTX0117', 'name' => 'Bishop');
$city_data[] = array('accid' => 'USTX0118', 'name' => 'Bivins');
$city_data[] = array('accid' => 'USTX0119', 'name' => 'Blackwell');
$city_data[] = array('accid' => 'USTX0120', 'name' => 'Blanco');
$city_data[] = array('accid' => 'USTX0121', 'name' => 'Blanket');
$city_data[] = array('accid' => 'USTX0122', 'name' => 'Bledsoe');
$city_data[] = array('accid' => 'USTX0123', 'name' => 'Bleiblerville');
$city_data[] = array('accid' => 'USTX0124', 'name' => 'Blessing');
$city_data[] = array('accid' => 'USTX0125', 'name' => 'Bloomburg');
$city_data[] = array('accid' => 'USTX0126', 'name' => 'Blooming Grove');
$city_data[] = array('accid' => 'USTX0127', 'name' => 'Bloomington');
$city_data[] = array('accid' => 'USTX0128', 'name' => 'Blossom');
$city_data[] = array('accid' => 'USTX0129', 'name' => 'Blue Ridge');
$city_data[] = array('accid' => 'USTX0130', 'name' => 'Bluegrove');
$city_data[] = array('accid' => 'USTX0131', 'name' => 'Bluff Dale');
$city_data[] = array('accid' => 'USTX0132', 'name' => 'Bluffton');
$city_data[] = array('accid' => 'USTX0133', 'name' => 'Blum');
$city_data[] = array('accid' => 'USTX0134', 'name' => 'Boerne');
$city_data[] = array('accid' => 'USTX0135', 'name' => 'Bogata');
$city_data[] = array('accid' => 'USTX0136', 'name' => 'Boling');
$city_data[] = array('accid' => 'USTX0137', 'name' => 'Bon Wier');
$city_data[] = array('accid' => 'USTX0138', 'name' => 'Bonham');
$city_data[] = array('accid' => 'USTX0139', 'name' => 'Booker');
$city_data[] = array('accid' => 'USTX0140', 'name' => 'Borger');
$city_data[] = array('accid' => 'USTX0141', 'name' => 'Bovina');
$city_data[] = array('accid' => 'USTX0142', 'name' => 'Bowie');
$city_data[] = array('accid' => 'USTX0143', 'name' => 'Boyd');
$city_data[] = array('accid' => 'USTX0144', 'name' => 'Boys Ranch');
$city_data[] = array('accid' => 'USTX0145', 'name' => 'Brackettville');
$city_data[] = array('accid' => 'USTX0146', 'name' => 'Brady');
$city_data[] = array('accid' => 'USTX0147', 'name' => 'Brandon');
$city_data[] = array('accid' => 'USTX0148', 'name' => 'Brashear');
$city_data[] = array('accid' => 'USTX0149', 'name' => 'Brazoria');
$city_data[] = array('accid' => 'USTX0150', 'name' => 'Breckenridge');
$city_data[] = array('accid' => 'USTX0151', 'name' => 'Bremond');
$city_data[] = array('accid' => 'USTX0152', 'name' => 'Brenham');
$city_data[] = array('accid' => 'USTX0153', 'name' => 'Bridge City');
$city_data[] = array('accid' => 'USTX0154', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USTX0155', 'name' => 'Briggs');
$city_data[] = array('accid' => 'USTX0156', 'name' => 'Briscoe');
$city_data[] = array('accid' => 'USTX0157', 'name' => 'Broaddus');
$city_data[] = array('accid' => 'USTX0158', 'name' => 'Bronson');
$city_data[] = array('accid' => 'USTX0159', 'name' => 'Bronte');
$city_data[] = array('accid' => 'USTX0160', 'name' => 'Brookeland');
$city_data[] = array('accid' => 'USTX0161', 'name' => 'Brookesmith');
$city_data[] = array('accid' => 'USTX0162', 'name' => 'Brookshire');
$city_data[] = array('accid' => 'USTX0163', 'name' => 'Brookston');
$city_data[] = array('accid' => 'USTX0164', 'name' => 'Brownfield');
$city_data[] = array('accid' => 'USTX0165', 'name' => 'Brownsboro');
$city_data[] = array('accid' => 'USTX0166', 'name' => 'Brownsville');
$city_data[] = array('accid' => 'USTX0167', 'name' => 'Brownwood');
$city_data[] = array('accid' => 'USTX0168', 'name' => 'Bruceville');
$city_data[] = array('accid' => 'USTX0169', 'name' => 'Bruni');
$city_data[] = array('accid' => 'USTX0170', 'name' => 'Bryan');
$city_data[] = array('accid' => 'USTX0171', 'name' => 'Bryson');
$city_data[] = array('accid' => 'USTX0172', 'name' => 'Buchanan Dam');
$city_data[] = array('accid' => 'USTX0173', 'name' => 'Buckholts');
$city_data[] = array('accid' => 'USTX0174', 'name' => 'Buda');
$city_data[] = array('accid' => 'USTX0175', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USTX0176', 'name' => 'Buffalo Gap');
$city_data[] = array('accid' => 'USTX0177', 'name' => 'Bula');
$city_data[] = array('accid' => 'USTX0178', 'name' => 'Bullard');
$city_data[] = array('accid' => 'USTX0179', 'name' => 'Bulverde');
$city_data[] = array('accid' => 'USTX0180', 'name' => 'Buna');
$city_data[] = array('accid' => 'USTX0181', 'name' => 'Burkburnett');
$city_data[] = array('accid' => 'USTX0182', 'name' => 'Burkett');
$city_data[] = array('accid' => 'USTX0183', 'name' => 'Burkeville');
$city_data[] = array('accid' => 'USTX0184', 'name' => 'Burleson');
$city_data[] = array('accid' => 'USTX0185', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USTX0186', 'name' => 'Burnet');
$city_data[] = array('accid' => 'USTX0187', 'name' => 'Burton');
$city_data[] = array('accid' => 'USTX0188', 'name' => 'Bushland');
$city_data[] = array('accid' => 'USTX0189', 'name' => 'Byers');
$city_data[] = array('accid' => 'USTX0190', 'name' => 'Bynum');
$city_data[] = array('accid' => 'USTX0191', 'name' => 'Cactus');
$city_data[] = array('accid' => 'USTX0192', 'name' => 'Caddo');
$city_data[] = array('accid' => 'USTX0193', 'name' => 'Caddo Mills');
$city_data[] = array('accid' => 'USTX0194', 'name' => 'Caldwell');
$city_data[] = array('accid' => 'USTX0195', 'name' => 'Call');
$city_data[] = array('accid' => 'USTX0196', 'name' => 'Calliham');
$city_data[] = array('accid' => 'USTX0197', 'name' => 'Calvert');
$city_data[] = array('accid' => 'USTX0198', 'name' => 'Camden');
$city_data[] = array('accid' => 'USTX0199', 'name' => 'Cameron');
$city_data[] = array('accid' => 'USTX0200', 'name' => 'Camp Wood');
$city_data[] = array('accid' => 'USTX0201', 'name' => 'Campbell');
$city_data[] = array('accid' => 'USTX0202', 'name' => 'Campbellton');
$city_data[] = array('accid' => 'USTX0203', 'name' => 'Canadian');
$city_data[] = array('accid' => 'USTX0204', 'name' => 'Canton');
$city_data[] = array('accid' => 'USTX0205', 'name' => 'Canutillo');
$city_data[] = array('accid' => 'USTX0206', 'name' => 'Canyon');
$city_data[] = array('accid' => 'USTX0207', 'name' => 'Canyon Lake');
$city_data[] = array('accid' => 'USTX0208', 'name' => 'Carbon');
$city_data[] = array('accid' => 'USTX0209', 'name' => 'Carey');
$city_data[] = array('accid' => 'USTX0210', 'name' => 'Carlsbad');
$city_data[] = array('accid' => 'USTX0211', 'name' => 'Carlton');
$city_data[] = array('accid' => 'USTX0212', 'name' => 'Carmine');
$city_data[] = array('accid' => 'USTX0213', 'name' => 'Carrizo Springs');
$city_data[] = array('accid' => 'USTX0214', 'name' => 'Carrollton');
$city_data[] = array('accid' => 'USTX0215', 'name' => 'Carthage');
$city_data[] = array('accid' => 'USTX0216', 'name' => 'Cason');
$city_data[] = array('accid' => 'USTX0217', 'name' => 'Castell');
$city_data[] = array('accid' => 'USTX0218', 'name' => 'Castroville');
$city_data[] = array('accid' => 'USTX0219', 'name' => 'Cat Spring');
$city_data[] = array('accid' => 'USTX0220', 'name' => 'Catarina');
$city_data[] = array('accid' => 'USTX0221', 'name' => 'Cayuga');
$city_data[] = array('accid' => 'USTX0222', 'name' => 'Cedar Creek');
$city_data[] = array('accid' => 'USTX0223', 'name' => 'Cedar Hill');
$city_data[] = array('accid' => 'USTX0224', 'name' => 'Cedar Lane');
$city_data[] = array('accid' => 'USTX0225', 'name' => 'Cedar Park');
$city_data[] = array('accid' => 'USTX0226', 'name' => 'Cee Vee');
$city_data[] = array('accid' => 'USTX0227', 'name' => 'Celeste');
$city_data[] = array('accid' => 'USTX0228', 'name' => 'Celina');
$city_data[] = array('accid' => 'USTX0229', 'name' => 'Center');
$city_data[] = array('accid' => 'USTX0230', 'name' => 'Center Point');
$city_data[] = array('accid' => 'USTX0231', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USTX0232', 'name' => 'Centralia');
$city_data[] = array('accid' => 'USTX0233', 'name' => 'Chalk');
$city_data[] = array('accid' => 'USTX0234', 'name' => 'Chandler');
$city_data[] = array('accid' => 'USTX0235', 'name' => 'Channelview');
$city_data[] = array('accid' => 'USTX0236', 'name' => 'Channing');
$city_data[] = array('accid' => 'USTX0237', 'name' => 'Chapman Ranch');
$city_data[] = array('accid' => 'USTX0238', 'name' => 'Chappell Hill');
$city_data[] = array('accid' => 'USTX0239', 'name' => 'Charlotte');
$city_data[] = array('accid' => 'USTX0240', 'name' => 'Chatfield');
$city_data[] = array('accid' => 'USTX0241', 'name' => 'Cherokee');
$city_data[] = array('accid' => 'USTX0242', 'name' => 'Chester');
$city_data[] = array('accid' => 'USTX0243', 'name' => 'Chico');
$city_data[] = array('accid' => 'USTX0244', 'name' => 'Chicota');
$city_data[] = array('accid' => 'USTX0245', 'name' => 'Childress');
$city_data[] = array('accid' => 'USTX0246', 'name' => 'Chillicothe');
$city_data[] = array('accid' => 'USTX0247', 'name' => 'Chilton');
$city_data[] = array('accid' => 'USTX0248', 'name' => 'China');
$city_data[] = array('accid' => 'USTX0249', 'name' => 'China Spring');
$city_data[] = array('accid' => 'USTX0250', 'name' => 'Chireno');
$city_data[] = array('accid' => 'USTX0251', 'name' => 'Chriesman');
$city_data[] = array('accid' => 'USTX0252', 'name' => 'Christine');
$city_data[] = array('accid' => 'USTX0253', 'name' => 'Christoval');
$city_data[] = array('accid' => 'USTX0254', 'name' => 'Cibolo');
$city_data[] = array('accid' => 'USTX0255', 'name' => 'Cisco');
$city_data[] = array('accid' => 'USTX0256', 'name' => 'Clarendon');
$city_data[] = array('accid' => 'USTX0257', 'name' => 'Clarksville');
$city_data[] = array('accid' => 'USTX0258', 'name' => 'Claude');
$city_data[] = array('accid' => 'USTX0259', 'name' => 'Clay');
$city_data[] = array('accid' => 'USTX0260', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USTX0261', 'name' => 'Cleburne');
$city_data[] = array('accid' => 'USTX0262', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USTX0263', 'name' => 'Clifton');
$city_data[] = array('accid' => 'USTX0264', 'name' => 'Clint');
$city_data[] = array('accid' => 'USTX0265', 'name' => 'Clute');
$city_data[] = array('accid' => 'USTX0266', 'name' => 'Clyde');
$city_data[] = array('accid' => 'USTX0267', 'name' => 'Coahoma');
$city_data[] = array('accid' => 'USTX0268', 'name' => 'Coldspring');
$city_data[] = array('accid' => 'USTX0269', 'name' => 'Coleman');
$city_data[] = array('accid' => 'USTX0270', 'name' => 'College Station');
$city_data[] = array('accid' => 'USTX0271', 'name' => 'Collegeport');
$city_data[] = array('accid' => 'USTX0272', 'name' => 'Colleyville');
$city_data[] = array('accid' => 'USTX0273', 'name' => 'Collinsville');
$city_data[] = array('accid' => 'USTX0274', 'name' => 'Colmesneil');
$city_data[] = array('accid' => 'USTX0275', 'name' => 'Colorado City');
$city_data[] = array('accid' => 'USTX0276', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USTX0277', 'name' => 'Comanche');
$city_data[] = array('accid' => 'USTX0278', 'name' => 'Combes');
$city_data[] = array('accid' => 'USTX0279', 'name' => 'Comfort');
$city_data[] = array('accid' => 'USTX0280', 'name' => 'Commerce');
$city_data[] = array('accid' => 'USTX0281', 'name' => 'Como');
$city_data[] = array('accid' => 'USTX0282', 'name' => 'Comstock');
$city_data[] = array('accid' => 'USTX0283', 'name' => 'Concan');
$city_data[] = array('accid' => 'USTX0284', 'name' => 'Concepcion');
$city_data[] = array('accid' => 'USTX0285', 'name' => 'Concord');
$city_data[] = array('accid' => 'USTX0286', 'name' => 'Conroe');
$city_data[] = array('accid' => 'USTX0287', 'name' => 'Converse');
$city_data[] = array('accid' => 'USTX0288', 'name' => 'Cookville');
$city_data[] = array('accid' => 'USTX0289', 'name' => 'Coolidge');
$city_data[] = array('accid' => 'USTX0290', 'name' => 'Cooper');
$city_data[] = array('accid' => 'USTX0291', 'name' => 'Copeville');
$city_data[] = array('accid' => 'USTX0292', 'name' => 'Coppell');
$city_data[] = array('accid' => 'USTX0293', 'name' => 'Copperas Cove');
$city_data[] = array('accid' => 'USTX0294', 'name' => 'Corpus Christi');
$city_data[] = array('accid' => 'USTX0295', 'name' => 'Corpus Christi NAS');
$city_data[] = array('accid' => 'USTX0296', 'name' => 'Corrigan');
$city_data[] = array('accid' => 'USTX0297', 'name' => 'Corsicana');
$city_data[] = array('accid' => 'USTX0298', 'name' => 'Cost');
$city_data[] = array('accid' => 'USTX0299', 'name' => 'Cotton Center');
$city_data[] = array('accid' => 'USTX0300', 'name' => 'Cotulla');
$city_data[] = array('accid' => 'USTX0301', 'name' => 'Coupland');
$city_data[] = array('accid' => 'USTX0302', 'name' => 'Covington');
$city_data[] = array('accid' => 'USTX0303', 'name' => 'Coyanosa');
$city_data[] = array('accid' => 'USTX0304', 'name' => 'Crandall');
$city_data[] = array('accid' => 'USTX0305', 'name' => 'Crane');
$city_data[] = array('accid' => 'USTX0306', 'name' => 'Cranfills Gap');
$city_data[] = array('accid' => 'USTX0307', 'name' => 'Crawford');
$city_data[] = array('accid' => 'USTX0308', 'name' => 'Cresson');
$city_data[] = array('accid' => 'USTX0309', 'name' => 'Crockett');
$city_data[] = array('accid' => 'USTX0310', 'name' => 'Crosby');
$city_data[] = array('accid' => 'USTX0311', 'name' => 'Crosbyton');
$city_data[] = array('accid' => 'USTX0312', 'name' => 'Cross Plains');
$city_data[] = array('accid' => 'USTX0313', 'name' => 'Crowell');
$city_data[] = array('accid' => 'USTX0314', 'name' => 'Crowley');
$city_data[] = array('accid' => 'USTX0315', 'name' => 'Crystal City');
$city_data[] = array('accid' => 'USTX0316', 'name' => 'Cuero');
$city_data[] = array('accid' => 'USTX0317', 'name' => 'Cumby');
$city_data[] = array('accid' => 'USTX0318', 'name' => 'Cuney');
$city_data[] = array('accid' => 'USTX0319', 'name' => 'Cunningham');
$city_data[] = array('accid' => 'USTX0320', 'name' => 'Cushing');
$city_data[] = array('accid' => 'USTX0321', 'name' => 'Cypress');
$city_data[] = array('accid' => 'USTX0361', 'name' => 'D\'hanis');
$city_data[] = array('accid' => 'USTX0322', 'name' => 'Daingerfield');
$city_data[] = array('accid' => 'USTX0323', 'name' => 'Daisetta');
$city_data[] = array('accid' => 'USTX0324', 'name' => 'Dale');
$city_data[] = array('accid' => 'USTX0325', 'name' => 'Dalhart');
$city_data[] = array('accid' => 'USTX0326', 'name' => 'Dallardsville');
$city_data[] = array('accid' => 'USTX0327', 'name' => 'Dallas');
$city_data[] = array('accid' => 'USTX0330', 'name' => 'Damon');
$city_data[] = array('accid' => 'USTX0331', 'name' => 'Danbury');
$city_data[] = array('accid' => 'USTX0332', 'name' => 'Danciger');
$city_data[] = array('accid' => 'USTX0333', 'name' => 'Danevang');
$city_data[] = array('accid' => 'USTX0334', 'name' => 'Darrouzett');
$city_data[] = array('accid' => 'USTX0335', 'name' => 'Davilla');
$city_data[] = array('accid' => 'USTX0336', 'name' => 'Dawn');
$city_data[] = array('accid' => 'USTX0337', 'name' => 'Dawson');
$city_data[] = array('accid' => 'USTX0338', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USTX0339', 'name' => 'De Berry');
$city_data[] = array('accid' => 'USTX0340', 'name' => 'De Kalb');
$city_data[] = array('accid' => 'USTX0341', 'name' => 'De Leon');
$city_data[] = array('accid' => 'USTX0343', 'name' => 'Deanville');
$city_data[] = array('accid' => 'USTX0344', 'name' => 'Decatur');
$city_data[] = array('accid' => 'USTX0345', 'name' => 'Deer Park');
$city_data[] = array('accid' => 'USTX0346', 'name' => 'Del Rio');
$city_data[] = array('accid' => 'USTX0348', 'name' => 'Del Valle');
$city_data[] = array('accid' => 'USTX0349', 'name' => 'Dell City');
$city_data[] = array('accid' => 'USTX0350', 'name' => 'Delmita');
$city_data[] = array('accid' => 'USTX0351', 'name' => 'Denison');
$city_data[] = array('accid' => 'USTX0352', 'name' => 'Dennis');
$city_data[] = array('accid' => 'USTX0353', 'name' => 'Denton');
$city_data[] = array('accid' => 'USTX0354', 'name' => 'Denver City');
$city_data[] = array('accid' => 'USTX0355', 'name' => 'Deport');
$city_data[] = array('accid' => 'USTX0356', 'name' => 'Desdemona');
$city_data[] = array('accid' => 'USTX0342', 'name' => 'Desoto');
$city_data[] = array('accid' => 'USTX0357', 'name' => 'Detroit');
$city_data[] = array('accid' => 'USTX0358', 'name' => 'Devers');
$city_data[] = array('accid' => 'USTX0359', 'name' => 'Devine');
$city_data[] = array('accid' => 'USTX0360', 'name' => 'Deweyville');
$city_data[] = array('accid' => 'USTX0362', 'name' => 'Diana');
$city_data[] = array('accid' => 'USTX0363', 'name' => 'Diboll');
$city_data[] = array('accid' => 'USTX0364', 'name' => 'Dickens');
$city_data[] = array('accid' => 'USTX0365', 'name' => 'Dickinson');
$city_data[] = array('accid' => 'USTX0366', 'name' => 'Dike');
$city_data[] = array('accid' => 'USTX0367', 'name' => 'Dilley');
$city_data[] = array('accid' => 'USTX0368', 'name' => 'Dime Box');
$city_data[] = array('accid' => 'USTX0369', 'name' => 'Dimmitt');
$city_data[] = array('accid' => 'USTX0370', 'name' => 'Dinero');
$city_data[] = array('accid' => 'USTX0371', 'name' => 'Dobbin');
$city_data[] = array('accid' => 'USTX0372', 'name' => 'Dodd City');
$city_data[] = array('accid' => 'USTX0373', 'name' => 'Dodge');
$city_data[] = array('accid' => 'USTX0374', 'name' => 'Dodson');
$city_data[] = array('accid' => 'USTX0375', 'name' => 'Donie');
$city_data[] = array('accid' => 'USTX0376', 'name' => 'Donna');
$city_data[] = array('accid' => 'USTX0377', 'name' => 'Doole');
$city_data[] = array('accid' => 'USTX0378', 'name' => 'Doss');
$city_data[] = array('accid' => 'USTX0379', 'name' => 'Doucette');
$city_data[] = array('accid' => 'USTX0380', 'name' => 'Dougherty');
$city_data[] = array('accid' => 'USTX0381', 'name' => 'Douglass');
$city_data[] = array('accid' => 'USTX0382', 'name' => 'Douglassville');
$city_data[] = array('accid' => 'USTX0383', 'name' => 'Driftwood');
$city_data[] = array('accid' => 'USTX0384', 'name' => 'Dripping Springs');
$city_data[] = array('accid' => 'USTX0385', 'name' => 'Driscoll');
$city_data[] = array('accid' => 'USTX0386', 'name' => 'Dryden');
$city_data[] = array('accid' => 'USTX0387', 'name' => 'Dublin');
$city_data[] = array('accid' => 'USTX0388', 'name' => 'Dumas');
$city_data[] = array('accid' => 'USTX0389', 'name' => 'Dumont');
$city_data[] = array('accid' => 'USTX0390', 'name' => 'Duncanville');
$city_data[] = array('accid' => 'USTX0391', 'name' => 'Dunn');
$city_data[] = array('accid' => 'USTX0392', 'name' => 'Dyess AFB');
$city_data[] = array('accid' => 'USTX0393', 'name' => 'Eagle Lake');
$city_data[] = array('accid' => 'USTX0394', 'name' => 'Eagle Pass');
$city_data[] = array('accid' => 'USTX0395', 'name' => 'Early');
$city_data[] = array('accid' => 'USTX0396', 'name' => 'Earth');
$city_data[] = array('accid' => 'USTX0397', 'name' => 'East Bernard');
$city_data[] = array('accid' => 'USTX0398', 'name' => 'Eastland');
$city_data[] = array('accid' => 'USTX0399', 'name' => 'Easton');
$city_data[] = array('accid' => 'USTX0400', 'name' => 'Ecleto');
$city_data[] = array('accid' => 'USTX0401', 'name' => 'Ector');
$city_data[] = array('accid' => 'USTX0402', 'name' => 'Edcouch');
$city_data[] = array('accid' => 'USTX0403', 'name' => 'Eddy');
$city_data[] = array('accid' => 'USTX0404', 'name' => 'Eden');
$city_data[] = array('accid' => 'USTX0405', 'name' => 'Edgewood');
$city_data[] = array('accid' => 'USTX0406', 'name' => 'Edinburg');
$city_data[] = array('accid' => 'USTX0407', 'name' => 'Edmonson');
$city_data[] = array('accid' => 'USTX0408', 'name' => 'Edna');
$city_data[] = array('accid' => 'USTX0409', 'name' => 'Edroy');
$city_data[] = array('accid' => 'USTX0410', 'name' => 'Egypt');
$city_data[] = array('accid' => 'USTX0411', 'name' => 'El Campo');
$city_data[] = array('accid' => 'USTX0412', 'name' => 'El Indio');
$city_data[] = array('accid' => 'USTX0413', 'name' => 'El Paso');
$city_data[] = array('accid' => 'USTX0414', 'name' => 'Eldorado');
$city_data[] = array('accid' => 'USTX0415', 'name' => 'Electra');
$city_data[] = array('accid' => 'USTX0416', 'name' => 'Elgin');
$city_data[] = array('accid' => 'USTX0417', 'name' => 'Elkhart');
$city_data[] = array('accid' => 'USTX0418', 'name' => 'Ellinger');
$city_data[] = array('accid' => 'USTX0419', 'name' => 'Elm Mott');
$city_data[] = array('accid' => 'USTX0420', 'name' => 'Elmaton');
$city_data[] = array('accid' => 'USTX0421', 'name' => 'Elmendorf');
$city_data[] = array('accid' => 'USTX0422', 'name' => 'Elmo');
$city_data[] = array('accid' => 'USTX0423', 'name' => 'Elsa');
$city_data[] = array('accid' => 'USTX0424', 'name' => 'Elysian Fields');
$city_data[] = array('accid' => 'USTX0425', 'name' => 'Emory');
$city_data[] = array('accid' => 'USTX0426', 'name' => 'Encinal');
$city_data[] = array('accid' => 'USTX0427', 'name' => 'Encino');
$city_data[] = array('accid' => 'USTX0428', 'name' => 'Energy');
$city_data[] = array('accid' => 'USTX0429', 'name' => 'Enloe');
$city_data[] = array('accid' => 'USTX0430', 'name' => 'Ennis');
$city_data[] = array('accid' => 'USTX0431', 'name' => 'Enochs');
$city_data[] = array('accid' => 'USTX0432', 'name' => 'Eola');
$city_data[] = array('accid' => 'USTX0433', 'name' => 'Era');
$city_data[] = array('accid' => 'USTX0434', 'name' => 'Estelline');
$city_data[] = array('accid' => 'USTX0435', 'name' => 'Etoile');
$city_data[] = array('accid' => 'USTX0436', 'name' => 'Euless');
$city_data[] = array('accid' => 'USTX0437', 'name' => 'Eustace');
$city_data[] = array('accid' => 'USTX0438', 'name' => 'Evadale');
$city_data[] = array('accid' => 'USTX0439', 'name' => 'Evant');
$city_data[] = array('accid' => 'USTX0440', 'name' => 'Fabens');
$city_data[] = array('accid' => 'USTX0441', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USTX0442', 'name' => 'Falcon Heights');
$city_data[] = array('accid' => 'USTX0443', 'name' => 'Falfurrias');
$city_data[] = array('accid' => 'USTX0444', 'name' => 'Falls City');
$city_data[] = array('accid' => 'USTX0445', 'name' => 'Fannin');
$city_data[] = array('accid' => 'USTX0446', 'name' => 'Farmersville');
$city_data[] = array('accid' => 'USTX0447', 'name' => 'Farnsworth');
$city_data[] = array('accid' => 'USTX0448', 'name' => 'Farwell');
$city_data[] = array('accid' => 'USTX0449', 'name' => 'Fate');
$city_data[] = array('accid' => 'USTX0450', 'name' => 'Fayetteville');
$city_data[] = array('accid' => 'USTX0451', 'name' => 'Fentress');
$city_data[] = array('accid' => 'USTX0452', 'name' => 'Ferris');
$city_data[] = array('accid' => 'USTX0453', 'name' => 'Fieldton');
$city_data[] = array('accid' => 'USTX0454', 'name' => 'Fischer');
$city_data[] = array('accid' => 'USTX0455', 'name' => 'Flat');
$city_data[] = array('accid' => 'USTX0456', 'name' => 'Flatonia');
$city_data[] = array('accid' => 'USTX0457', 'name' => 'Flint');
$city_data[] = array('accid' => 'USTX0458', 'name' => 'Flomot');
$city_data[] = array('accid' => 'USTX0459', 'name' => 'Florence');
$city_data[] = array('accid' => 'USTX0460', 'name' => 'Floresville');
$city_data[] = array('accid' => 'USTX0461', 'name' => 'Flower Mound');
$city_data[] = array('accid' => 'USTX0462', 'name' => 'Floydada');
$city_data[] = array('accid' => 'USTX0463', 'name' => 'Fluvanna');
$city_data[] = array('accid' => 'USTX0464', 'name' => 'Flynn');
$city_data[] = array('accid' => 'USTX0465', 'name' => 'Follett');
$city_data[] = array('accid' => 'USTX0466', 'name' => 'Forestburg');
$city_data[] = array('accid' => 'USTX0467', 'name' => 'Forney');
$city_data[] = array('accid' => 'USTX0468', 'name' => 'Forreston');
$city_data[] = array('accid' => 'USTX0469', 'name' => 'Forsan');
$city_data[] = array('accid' => 'USTX0470', 'name' => 'Fort Davis');
$city_data[] = array('accid' => 'USTX0471', 'name' => 'Fort Hancock');
$city_data[] = array('accid' => 'USTX0472', 'name' => 'Fort McKavett');
$city_data[] = array('accid' => 'USTX0473', 'name' => 'Fort Stockton');
$city_data[] = array('accid' => 'USTX0474', 'name' => 'Fort Worth');
$city_data[] = array('accid' => 'USTX0476', 'name' => 'Fort Worth NAS');
$city_data[] = array('accid' => 'USTX0477', 'name' => 'Fowlerton');
$city_data[] = array('accid' => 'USTX0478', 'name' => 'Francitas');
$city_data[] = array('accid' => 'USTX0479', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USTX0480', 'name' => 'Frankston');
$city_data[] = array('accid' => 'USTX0481', 'name' => 'Fred');
$city_data[] = array('accid' => 'USTX0482', 'name' => 'Fredericksburg');
$city_data[] = array('accid' => 'USTX0483', 'name' => 'Fredonia');
$city_data[] = array('accid' => 'USTX0484', 'name' => 'Freeport');
$city_data[] = array('accid' => 'USTX0485', 'name' => 'Freer');
$city_data[] = array('accid' => 'USTX0486', 'name' => 'Fresno');
$city_data[] = array('accid' => 'USTX0487', 'name' => 'Friendswood');
$city_data[] = array('accid' => 'USTX0488', 'name' => 'Friona');
$city_data[] = array('accid' => 'USTX0489', 'name' => 'Frisco');
$city_data[] = array('accid' => 'USTX0490', 'name' => 'Fritch');
$city_data[] = array('accid' => 'USTX0491', 'name' => 'Frost');
$city_data[] = array('accid' => 'USTX0492', 'name' => 'Fruitvale');
$city_data[] = array('accid' => 'USTX0493', 'name' => 'Fulshear');
$city_data[] = array('accid' => 'USTX0494', 'name' => 'Fulton');
$city_data[] = array('accid' => 'USTX0495', 'name' => 'Gail');
$city_data[] = array('accid' => 'USTX0496', 'name' => 'Gainesville');
$city_data[] = array('accid' => 'USTX0497', 'name' => 'Galena Park');
$city_data[] = array('accid' => 'USTX0498', 'name' => 'Gallatin');
$city_data[] = array('accid' => 'USTX0499', 'name' => 'Galveston');
$city_data[] = array('accid' => 'USTX0500', 'name' => 'Ganado');
$city_data[] = array('accid' => 'USTX0501', 'name' => 'Garciasville');
$city_data[] = array('accid' => 'USTX0502', 'name' => 'Garden City');
$city_data[] = array('accid' => 'USTX0503', 'name' => 'Gardendale');
$city_data[] = array('accid' => 'USTX0504', 'name' => 'Garland');
$city_data[] = array('accid' => 'USTX0505', 'name' => 'Garrison');
$city_data[] = array('accid' => 'USTX0506', 'name' => 'Garwood');
$city_data[] = array('accid' => 'USTX0507', 'name' => 'Gary');
$city_data[] = array('accid' => 'USTX0508', 'name' => 'Gatesville');
$city_data[] = array('accid' => 'USTX0509', 'name' => 'Gause');
$city_data[] = array('accid' => 'USTX0510', 'name' => 'Geneva');
$city_data[] = array('accid' => 'USTX0511', 'name' => 'George West');
$city_data[] = array('accid' => 'USTX0512', 'name' => 'Georgetown');
$city_data[] = array('accid' => 'USTX0513', 'name' => 'Geronimo');
$city_data[] = array('accid' => 'USTX0514', 'name' => 'Giddings');
$city_data[] = array('accid' => 'USTX0515', 'name' => 'Gilchrist');
$city_data[] = array('accid' => 'USTX0516', 'name' => 'Gillett');
$city_data[] = array('accid' => 'USTX0517', 'name' => 'Gilmer');
$city_data[] = array('accid' => 'USTX0518', 'name' => 'Girard');
$city_data[] = array('accid' => 'USTX0519', 'name' => 'Girvin');
$city_data[] = array('accid' => 'USTX0520', 'name' => 'Gladewater');
$city_data[] = array('accid' => 'USTX0521', 'name' => 'Glen Flora');
$city_data[] = array('accid' => 'USTX0522', 'name' => 'Glen Rose');
$city_data[] = array('accid' => 'USTX0523', 'name' => 'Glidden');
$city_data[] = array('accid' => 'USTX0524', 'name' => 'Gober');
$city_data[] = array('accid' => 'USTX0525', 'name' => 'Godley');
$city_data[] = array('accid' => 'USTX0526', 'name' => 'Golden');
$city_data[] = array('accid' => 'USTX0527', 'name' => 'Goldsboro');
$city_data[] = array('accid' => 'USTX0528', 'name' => 'Goldsmith');
$city_data[] = array('accid' => 'USTX0529', 'name' => 'Goldthwaite');
$city_data[] = array('accid' => 'USTX0530', 'name' => 'Goliad');
$city_data[] = array('accid' => 'USTX0531', 'name' => 'Gonzales');
$city_data[] = array('accid' => 'USTX0532', 'name' => 'Goodfellow AFB');
$city_data[] = array('accid' => 'USTX0533', 'name' => 'Goodrich');
$city_data[] = array('accid' => 'USTX0534', 'name' => 'Gordon');
$city_data[] = array('accid' => 'USTX0535', 'name' => 'Gordonville');
$city_data[] = array('accid' => 'USTX0536', 'name' => 'Goree');
$city_data[] = array('accid' => 'USTX0537', 'name' => 'Gorman');
$city_data[] = array('accid' => 'USTX0538', 'name' => 'Gouldbusk');
$city_data[] = array('accid' => 'USTX0539', 'name' => 'Graford');
$city_data[] = array('accid' => 'USTX0540', 'name' => 'Graham');
$city_data[] = array('accid' => 'USTX0541', 'name' => 'Granbury');
$city_data[] = array('accid' => 'USTX0542', 'name' => 'Grand Prairie');
$city_data[] = array('accid' => 'USTX0543', 'name' => 'Grand Saline');
$city_data[] = array('accid' => 'USTX0544', 'name' => 'Grandfalls');
$city_data[] = array('accid' => 'USTX0545', 'name' => 'Grandview');
$city_data[] = array('accid' => 'USTX0546', 'name' => 'Granger');
$city_data[] = array('accid' => 'USTX0547', 'name' => 'Grapeland');
$city_data[] = array('accid' => 'USTX0548', 'name' => 'Grapevine');
$city_data[] = array('accid' => 'USTX0549', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USTX0550', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USTX0551', 'name' => 'Gregory');
$city_data[] = array('accid' => 'USTX0552', 'name' => 'Groesbeck');
$city_data[] = array('accid' => 'USTX0553', 'name' => 'Groom');
$city_data[] = array('accid' => 'USTX0554', 'name' => 'Groves');
$city_data[] = array('accid' => 'USTX0555', 'name' => 'Groveton');
$city_data[] = array('accid' => 'USTX0556', 'name' => 'Grulla');
$city_data[] = array('accid' => 'USTX0557', 'name' => 'Gruver');
$city_data[] = array('accid' => 'USTX0560', 'name' => 'Guerra');
$city_data[] = array('accid' => 'USTX0561', 'name' => 'Gunter');
$city_data[] = array('accid' => 'USTX0562', 'name' => 'Gustine');
$city_data[] = array('accid' => 'USTX0563', 'name' => 'Guthrie');
$city_data[] = array('accid' => 'USTX0564', 'name' => 'Guy');
$city_data[] = array('accid' => 'USTX0565', 'name' => 'Hale Center');
$city_data[] = array('accid' => 'USTX0566', 'name' => 'Hallettsville');
$city_data[] = array('accid' => 'USTX0567', 'name' => 'Hallsville');
$city_data[] = array('accid' => 'USTX0568', 'name' => 'Haltom City');
$city_data[] = array('accid' => 'USTX0569', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USTX0570', 'name' => 'Hamlin');
$city_data[] = array('accid' => 'USTX0571', 'name' => 'Hamshire');
$city_data[] = array('accid' => 'USTX0572', 'name' => 'Hankamer');
$city_data[] = array('accid' => 'USTX0573', 'name' => 'Happy');
$city_data[] = array('accid' => 'USTX0574', 'name' => 'Hardin');
$city_data[] = array('accid' => 'USTX0575', 'name' => 'Hargill');
$city_data[] = array('accid' => 'USTX0576', 'name' => 'Harker Heights');
$city_data[] = array('accid' => 'USTX0577', 'name' => 'Harleton');
$city_data[] = array('accid' => 'USTX0578', 'name' => 'Harlingen');
$city_data[] = array('accid' => 'USTX0579', 'name' => 'Harper');
$city_data[] = array('accid' => 'USTX0580', 'name' => 'Harrold');
$city_data[] = array('accid' => 'USTX0581', 'name' => 'Hart');
$city_data[] = array('accid' => 'USTX0582', 'name' => 'Hartley');
$city_data[] = array('accid' => 'USTX0583', 'name' => 'Harwood');
$city_data[] = array('accid' => 'USTX0584', 'name' => 'Haskell');
$city_data[] = array('accid' => 'USTX0585', 'name' => 'Haslet');
$city_data[] = array('accid' => 'USTX0586', 'name' => 'Hawkins');
$city_data[] = array('accid' => 'USTX0587', 'name' => 'Hawley');
$city_data[] = array('accid' => 'USTX0588', 'name' => 'Hearne');
$city_data[] = array('accid' => 'USTX0589', 'name' => 'Hebbronville');
$city_data[] = array('accid' => 'USTX0590', 'name' => 'Hedley');
$city_data[] = array('accid' => 'USTX0591', 'name' => 'Heidenheimer');
$city_data[] = array('accid' => 'USTX0592', 'name' => 'Helotes');
$city_data[] = array('accid' => 'USTX0593', 'name' => 'Hemphill');
$city_data[] = array('accid' => 'USTX0594', 'name' => 'Hempstead');
$city_data[] = array('accid' => 'USTX0595', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USTX0596', 'name' => 'Henrietta');
$city_data[] = array('accid' => 'USTX0597', 'name' => 'Hereford');
$city_data[] = array('accid' => 'USTX0598', 'name' => 'Hermleigh');
$city_data[] = array('accid' => 'USTX0599', 'name' => 'Hewitt');
$city_data[] = array('accid' => 'USTX0600', 'name' => 'Hext');
$city_data[] = array('accid' => 'USTX0601', 'name' => 'Hico');
$city_data[] = array('accid' => 'USTX0602', 'name' => 'Hidalgo');
$city_data[] = array('accid' => 'USTX0603', 'name' => 'Higgins');
$city_data[] = array('accid' => 'USTX0604', 'name' => 'High Island');
$city_data[] = array('accid' => 'USTX0605', 'name' => 'Highlands');
$city_data[] = array('accid' => 'USTX0606', 'name' => 'Hillister');
$city_data[] = array('accid' => 'USTX0607', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USTX0608', 'name' => 'Hitchcock');
$city_data[] = array('accid' => 'USTX0609', 'name' => 'Hobson');
$city_data[] = array('accid' => 'USTX0610', 'name' => 'Hochheim');
$city_data[] = array('accid' => 'USTX0611', 'name' => 'Hockley');
$city_data[] = array('accid' => 'USTX0612', 'name' => 'Holland');
$city_data[] = array('accid' => 'USTX0613', 'name' => 'Holliday');
$city_data[] = array('accid' => 'USTX0614', 'name' => 'Hondo');
$city_data[] = array('accid' => 'USTX0615', 'name' => 'Honey Grove');
$city_data[] = array('accid' => 'USTX0616', 'name' => 'Hooks');
$city_data[] = array('accid' => 'USTX0617', 'name' => 'Houston');
$city_data[] = array('accid' => 'USTX0619', 'name' => 'Howe');
$city_data[] = array('accid' => 'USTX0620', 'name' => 'Hubbard');
$city_data[] = array('accid' => 'USTX0621', 'name' => 'Huffman');
$city_data[] = array('accid' => 'USTX0622', 'name' => 'Hufsmith');
$city_data[] = array('accid' => 'USTX0623', 'name' => 'Hughes Springs');
$city_data[] = array('accid' => 'USTX0624', 'name' => 'Hull');
$city_data[] = array('accid' => 'USTX0625', 'name' => 'Humble');
$city_data[] = array('accid' => 'USTX0626', 'name' => 'Hungerford');
$city_data[] = array('accid' => 'USTX0627', 'name' => 'Hunt');
$city_data[] = array('accid' => 'USTX0628', 'name' => 'Huntington');
$city_data[] = array('accid' => 'USTX0629', 'name' => 'Huntsville');
$city_data[] = array('accid' => 'USTX0630', 'name' => 'Hurst');
$city_data[] = array('accid' => 'USTX0631', 'name' => 'Hutchins');
$city_data[] = array('accid' => 'USTX0632', 'name' => 'Hutto');
$city_data[] = array('accid' => 'USTX0633', 'name' => 'Hye');
$city_data[] = array('accid' => 'USTX0634', 'name' => 'Idalou');
$city_data[] = array('accid' => 'USTX0635', 'name' => 'Imperial');
$city_data[] = array('accid' => 'USTX0636', 'name' => 'Industry');
$city_data[] = array('accid' => 'USTX0637', 'name' => 'Inez');
$city_data[] = array('accid' => 'USTX0638', 'name' => 'Ingleside');
$city_data[] = array('accid' => 'USTX0639', 'name' => 'Ingram');
$city_data[] = array('accid' => 'USTX0640', 'name' => 'Iola');
$city_data[] = array('accid' => 'USTX0641', 'name' => 'Iowa Park');
$city_data[] = array('accid' => 'USTX0642', 'name' => 'Ira');
$city_data[] = array('accid' => 'USTX0643', 'name' => 'Iraan');
$city_data[] = array('accid' => 'USTX0644', 'name' => 'Iredell');
$city_data[] = array('accid' => 'USTX0645', 'name' => 'Irene');
$city_data[] = array('accid' => 'USTX0646', 'name' => 'Irving');
$city_data[] = array('accid' => 'USTX0647', 'name' => 'Italy');
$city_data[] = array('accid' => 'USTX0648', 'name' => 'Itasca');
$city_data[] = array('accid' => 'USTX0649', 'name' => 'Ivanhoe');
$city_data[] = array('accid' => 'USTX0650', 'name' => 'Jacksboro');
$city_data[] = array('accid' => 'USTX0651', 'name' => 'Jacksonville');
$city_data[] = array('accid' => 'USTX0652', 'name' => 'Jarrell');
$city_data[] = array('accid' => 'USTX0653', 'name' => 'Jasper');
$city_data[] = array('accid' => 'USTX0654', 'name' => 'Jayton');
$city_data[] = array('accid' => 'USTX0655', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USTX0656', 'name' => 'Jermyn');
$city_data[] = array('accid' => 'USTX0657', 'name' => 'Jewett');
$city_data[] = array('accid' => 'USTX0658', 'name' => 'Joaquin');
$city_data[] = array('accid' => 'USTX0659', 'name' => 'Johnson City');
$city_data[] = array('accid' => 'USTX0660', 'name' => 'Joinerville');
$city_data[] = array('accid' => 'USTX0661', 'name' => 'Jonesboro');
$city_data[] = array('accid' => 'USTX0662', 'name' => 'Jonesville');
$city_data[] = array('accid' => 'USTX0663', 'name' => 'Josephine');
$city_data[] = array('accid' => 'USTX0664', 'name' => 'Joshua');
$city_data[] = array('accid' => 'USTX0665', 'name' => 'Jourdanton');
$city_data[] = array('accid' => 'USTX0666', 'name' => 'Judson');
$city_data[] = array('accid' => 'USTX0667', 'name' => 'Junction');
$city_data[] = array('accid' => 'USTX0668', 'name' => 'Justiceburg');
$city_data[] = array('accid' => 'USTX0669', 'name' => 'Justin');
$city_data[] = array('accid' => 'USTX0670', 'name' => 'Kamay');
$city_data[] = array('accid' => 'USTX0671', 'name' => 'Karnack');
$city_data[] = array('accid' => 'USTX0672', 'name' => 'Karnes City');
$city_data[] = array('accid' => 'USTX0673', 'name' => 'Katy');
$city_data[] = array('accid' => 'USTX0674', 'name' => 'Kaufman');
$city_data[] = array('accid' => 'USTX0675', 'name' => 'Keene');
$city_data[] = array('accid' => 'USTX0676', 'name' => 'Keller');
$city_data[] = array('accid' => 'USTX0677', 'name' => 'Kemah');
$city_data[] = array('accid' => 'USTX0678', 'name' => 'Kemp');
$city_data[] = array('accid' => 'USTX0679', 'name' => 'Kempner');
$city_data[] = array('accid' => 'USTX0680', 'name' => 'Kendalia');
$city_data[] = array('accid' => 'USTX0681', 'name' => 'Kendleton');
$city_data[] = array('accid' => 'USTX0682', 'name' => 'Kenedy');
$city_data[] = array('accid' => 'USTX0683', 'name' => 'Kennard');
$city_data[] = array('accid' => 'USTX0684', 'name' => 'Kennedale');
$city_data[] = array('accid' => 'USTX0685', 'name' => 'Kenney');
$city_data[] = array('accid' => 'USTX0686', 'name' => 'Kerens');
$city_data[] = array('accid' => 'USTX0687', 'name' => 'Kermit');
$city_data[] = array('accid' => 'USTX0688', 'name' => 'Kerrick');
$city_data[] = array('accid' => 'USTX0689', 'name' => 'Kerrville');
$city_data[] = array('accid' => 'USTX0690', 'name' => 'Kildare');
$city_data[] = array('accid' => 'USTX0691', 'name' => 'Kilgore');
$city_data[] = array('accid' => 'USTX0692', 'name' => 'Killeen');
$city_data[] = array('accid' => 'USTX0695', 'name' => 'Kingsbury');
$city_data[] = array('accid' => 'USTX0696', 'name' => 'Kingsland');
$city_data[] = array('accid' => 'USTX0697', 'name' => 'Kingsville');
$city_data[] = array('accid' => 'USTX0698', 'name' => 'Kirbyville');
$city_data[] = array('accid' => 'USTX0699', 'name' => 'Kirkland');
$city_data[] = array('accid' => 'USTX0700', 'name' => 'Kirvin');
$city_data[] = array('accid' => 'USTX0701', 'name' => 'Klondike');
$city_data[] = array('accid' => 'USTX0702', 'name' => 'Knickerbocker');
$city_data[] = array('accid' => 'USTX0703', 'name' => 'Knippa');
$city_data[] = array('accid' => 'USTX0704', 'name' => 'Knott');
$city_data[] = array('accid' => 'USTX0705', 'name' => 'Knox City');
$city_data[] = array('accid' => 'USTX0706', 'name' => 'Kopperl');
$city_data[] = array('accid' => 'USTX0707', 'name' => 'Kosse');
$city_data[] = array('accid' => 'USTX0708', 'name' => 'Kountze');
$city_data[] = array('accid' => 'USTX0709', 'name' => 'Kress');
$city_data[] = array('accid' => 'USTX0710', 'name' => 'Krum');
$city_data[] = array('accid' => 'USTX0711', 'name' => 'Kurten');
$city_data[] = array('accid' => 'USTX0712', 'name' => 'Kyle');
$city_data[] = array('accid' => 'USTX0713', 'name' => 'La Blanca');
$city_data[] = array('accid' => 'USTX0714', 'name' => 'La Coste');
$city_data[] = array('accid' => 'USTX0715', 'name' => 'La Feria');
$city_data[] = array('accid' => 'USTX0716', 'name' => 'La Grange');
$city_data[] = array('accid' => 'USTX0717', 'name' => 'La Joya');
$city_data[] = array('accid' => 'USTX0718', 'name' => 'La Marque');
$city_data[] = array('accid' => 'USTX0719', 'name' => 'La Porte');
$city_data[] = array('accid' => 'USTX0720', 'name' => 'La Pryor');
$city_data[] = array('accid' => 'USTX0721', 'name' => 'La Salle');
$city_data[] = array('accid' => 'USTX0722', 'name' => 'La Vernia');
$city_data[] = array('accid' => 'USTX0723', 'name' => 'La Villa');
$city_data[] = array('accid' => 'USTX0724', 'name' => 'La Ward');
$city_data[] = array('accid' => 'USTX0725', 'name' => 'Ladonia');
$city_data[] = array('accid' => 'USTX0726', 'name' => 'Laird Hill');
$city_data[] = array('accid' => 'USTX0727', 'name' => 'Lake Creek');
$city_data[] = array('accid' => 'USTX0728', 'name' => 'Lake Dallas');
$city_data[] = array('accid' => 'USTX0729', 'name' => 'Lake Jackson');
$city_data[] = array('accid' => 'USTX0730', 'name' => 'Lakeview');
$city_data[] = array('accid' => 'USTX0731', 'name' => 'Lamesa');
$city_data[] = array('accid' => 'USTX0732', 'name' => 'Lampasas');
$city_data[] = array('accid' => 'USTX0733', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USTX0734', 'name' => 'Lane City');
$city_data[] = array('accid' => 'USTX0735', 'name' => 'Laneville');
$city_data[] = array('accid' => 'USTX0736', 'name' => 'Langtry');
$city_data[] = array('accid' => 'USTX0737', 'name' => 'Laredo');
$city_data[] = array('accid' => 'USTX0738', 'name' => 'Larue');
$city_data[] = array('accid' => 'USTX0739', 'name' => 'Lasara');
$city_data[] = array('accid' => 'USTX0740', 'name' => 'Latexo');
$city_data[] = array('accid' => 'USTX0742', 'name' => 'Lavon');
$city_data[] = array('accid' => 'USTX0743', 'name' => 'Lawn');
$city_data[] = array('accid' => 'USTX0744', 'name' => 'Lazbuddie');
$city_data[] = array('accid' => 'USTX0745', 'name' => 'League City');
$city_data[] = array('accid' => 'USTX0746', 'name' => 'Leakey');
$city_data[] = array('accid' => 'USTX0747', 'name' => 'Leander');
$city_data[] = array('accid' => 'USTX0748', 'name' => 'Ledbetter');
$city_data[] = array('accid' => 'USTX0749', 'name' => 'Leesburg');
$city_data[] = array('accid' => 'USTX0750', 'name' => 'Leesville');
$city_data[] = array('accid' => 'USTX0751', 'name' => 'Lefors');
$city_data[] = array('accid' => 'USTX0752', 'name' => 'Leggett');
$city_data[] = array('accid' => 'USTX0753', 'name' => 'Lelia Lake');
$city_data[] = array('accid' => 'USTX0754', 'name' => 'Leming');
$city_data[] = array('accid' => 'USTX0755', 'name' => 'Lenorah');
$city_data[] = array('accid' => 'USTX0756', 'name' => 'Leon Junction');
$city_data[] = array('accid' => 'USTX0757', 'name' => 'Leona');
$city_data[] = array('accid' => 'USTX0758', 'name' => 'Leonard');
$city_data[] = array('accid' => 'USTX0759', 'name' => 'Leroy');
$city_data[] = array('accid' => 'USTX0760', 'name' => 'Levelland');
$city_data[] = array('accid' => 'USTX0761', 'name' => 'Lewisville');
$city_data[] = array('accid' => 'USTX0762', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USTX0763', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USTX0764', 'name' => 'Liberty Hill');
$city_data[] = array('accid' => 'USTX0765', 'name' => 'Lillian');
$city_data[] = array('accid' => 'USTX0766', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USTX0767', 'name' => 'Lindale');
$city_data[] = array('accid' => 'USTX0768', 'name' => 'Linden');
$city_data[] = array('accid' => 'USTX0769', 'name' => 'Lindsay');
$city_data[] = array('accid' => 'USTX0770', 'name' => 'Lingleville');
$city_data[] = array('accid' => 'USTX0771', 'name' => 'Linn');
$city_data[] = array('accid' => 'USTX0772', 'name' => 'Lipan');
$city_data[] = array('accid' => 'USTX0773', 'name' => 'Lipscomb');
$city_data[] = array('accid' => 'USTX0774', 'name' => 'Lissie');
$city_data[] = array('accid' => 'USTX0775', 'name' => 'Little Elm');
$city_data[] = array('accid' => 'USTX0776', 'name' => 'Little River');
$city_data[] = array('accid' => 'USTX0777', 'name' => 'Littlefield');
$city_data[] = array('accid' => 'USTX0778', 'name' => 'Liverpool');
$city_data[] = array('accid' => 'USTX0779', 'name' => 'Livingston');
$city_data[] = array('accid' => 'USTX0780', 'name' => 'Llano');
$city_data[] = array('accid' => 'USTX0781', 'name' => 'Lockhart');
$city_data[] = array('accid' => 'USTX0782', 'name' => 'Lockney');
$city_data[] = array('accid' => 'USTX0783', 'name' => 'Lodi');
$city_data[] = array('accid' => 'USTX0784', 'name' => 'Lohn');
$city_data[] = array('accid' => 'USTX0785', 'name' => 'Lolita');
$city_data[] = array('accid' => 'USTX0787', 'name' => 'Lometa');
$city_data[] = array('accid' => 'USTX0788', 'name' => 'London');
$city_data[] = array('accid' => 'USTX0789', 'name' => 'Lone Oak');
$city_data[] = array('accid' => 'USTX0790', 'name' => 'Lone Star');
$city_data[] = array('accid' => 'USTX0791', 'name' => 'Long Branch');
$city_data[] = array('accid' => 'USTX0792', 'name' => 'Long Mott');
$city_data[] = array('accid' => 'USTX0793', 'name' => 'Longview');
$city_data[] = array('accid' => 'USTX0794', 'name' => 'Loop');
$city_data[] = array('accid' => 'USTX0795', 'name' => 'Lopeno');
$city_data[] = array('accid' => 'USTX0796', 'name' => 'Loraine');
$city_data[] = array('accid' => 'USTX0797', 'name' => 'Lorena');
$city_data[] = array('accid' => 'USTX0798', 'name' => 'Lorenzo');
$city_data[] = array('accid' => 'USTX0799', 'name' => 'Los Ebanos');
$city_data[] = array('accid' => 'USTX0800', 'name' => 'Los Fresnos');
$city_data[] = array('accid' => 'USTX0801', 'name' => 'Los Indios');
$city_data[] = array('accid' => 'USTX0802', 'name' => 'Lott');
$city_data[] = array('accid' => 'USTX0803', 'name' => 'Louise');
$city_data[] = array('accid' => 'USTX0804', 'name' => 'Lovelady');
$city_data[] = array('accid' => 'USTX0805', 'name' => 'Loving');
$city_data[] = array('accid' => 'USTX0806', 'name' => 'Lowake');
$city_data[] = array('accid' => 'USTX0807', 'name' => 'Lozano');
$city_data[] = array('accid' => 'USTX0808', 'name' => 'Lubbock');
$city_data[] = array('accid' => 'USTX0810', 'name' => 'Lueders');
$city_data[] = array('accid' => 'USTX0811', 'name' => 'Lufkin');
$city_data[] = array('accid' => 'USTX0812', 'name' => 'Luling');
$city_data[] = array('accid' => 'USTX0813', 'name' => 'Lumberton');
$city_data[] = array('accid' => 'USTX0814', 'name' => 'Lyford');
$city_data[] = array('accid' => 'USTX0815', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USTX0816', 'name' => 'Lytle');
$city_data[] = array('accid' => 'USTX0817', 'name' => 'Mabank');
$city_data[] = array('accid' => 'USTX0818', 'name' => 'Macdona');
$city_data[] = array('accid' => 'USTX0819', 'name' => 'Madisonville');
$city_data[] = array('accid' => 'USTX0820', 'name' => 'Magnolia');
$city_data[] = array('accid' => 'USTX0821', 'name' => 'Malakoff');
$city_data[] = array('accid' => 'USTX0822', 'name' => 'Malone');
$city_data[] = array('accid' => 'USTX0823', 'name' => 'Manchaca');
$city_data[] = array('accid' => 'USTX0824', 'name' => 'Manor');
$city_data[] = array('accid' => 'USTX0825', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'USTX0826', 'name' => 'Manvel');
$city_data[] = array('accid' => 'USTX0827', 'name' => 'Maple');
$city_data[] = array('accid' => 'USTX0828', 'name' => 'Marathon');
$city_data[] = array('accid' => 'USTX0829', 'name' => 'Marble Falls');
$city_data[] = array('accid' => 'USTX0830', 'name' => 'Marfa');
$city_data[] = array('accid' => 'USTX0831', 'name' => 'Marietta');
$city_data[] = array('accid' => 'USTX0832', 'name' => 'Marion');
$city_data[] = array('accid' => 'USTX0833', 'name' => 'Markham');
$city_data[] = array('accid' => 'USTX0834', 'name' => 'Marlin');
$city_data[] = array('accid' => 'USTX0835', 'name' => 'Marquez');
$city_data[] = array('accid' => 'USTX0836', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USTX0837', 'name' => 'Mart');
$city_data[] = array('accid' => 'USTX0838', 'name' => 'Martindale');
$city_data[] = array('accid' => 'USTX0839', 'name' => 'Martinsville');
$city_data[] = array('accid' => 'USTX0840', 'name' => 'Maryneal');
$city_data[] = array('accid' => 'USTX0841', 'name' => 'Mason');
$city_data[] = array('accid' => 'USTX0842', 'name' => 'Masterson');
$city_data[] = array('accid' => 'USTX0843', 'name' => 'Matador');
$city_data[] = array('accid' => 'USTX0844', 'name' => 'Matagorda');
$city_data[] = array('accid' => 'USTX0845', 'name' => 'Mathis');
$city_data[] = array('accid' => 'USTX0846', 'name' => 'Maud');
$city_data[] = array('accid' => 'USTX0847', 'name' => 'Mauriceville');
$city_data[] = array('accid' => 'USTX0848', 'name' => 'Maxwell');
$city_data[] = array('accid' => 'USTX0849', 'name' => 'May');
$city_data[] = array('accid' => 'USTX0850', 'name' => 'Maydelle');
$city_data[] = array('accid' => 'USTX0851', 'name' => 'Maypearl');
$city_data[] = array('accid' => 'USTX0852', 'name' => 'Maysfield');
$city_data[] = array('accid' => 'USTX0853', 'name' => 'McAdoo');
$city_data[] = array('accid' => 'USTX0854', 'name' => 'McAllen');
$city_data[] = array('accid' => 'USTX0855', 'name' => 'McCamey');
$city_data[] = array('accid' => 'USTX0856', 'name' => 'McCaulley');
$city_data[] = array('accid' => 'USTX0858', 'name' => 'McDade');
$city_data[] = array('accid' => 'USTX0859', 'name' => 'McFaddin');
$city_data[] = array('accid' => 'USTX0860', 'name' => 'McGregor');
$city_data[] = array('accid' => 'USTX0861', 'name' => 'McKinney');
$city_data[] = array('accid' => 'USTX0862', 'name' => 'McLean');
$city_data[] = array('accid' => 'USTX0863', 'name' => 'McLeod');
$city_data[] = array('accid' => 'USTX0864', 'name' => 'McNeil');
$city_data[] = array('accid' => 'USTX0865', 'name' => 'McQueeney');
$city_data[] = array('accid' => 'USTX0866', 'name' => 'Meadow');
$city_data[] = array('accid' => 'USTX0867', 'name' => 'Medina');
$city_data[] = array('accid' => 'USTX0868', 'name' => 'Megargel');
$city_data[] = array('accid' => 'USTX0869', 'name' => 'Melissa');
$city_data[] = array('accid' => 'USTX0870', 'name' => 'Melvin');
$city_data[] = array('accid' => 'USTX0871', 'name' => 'Memphis');
$city_data[] = array('accid' => 'USTX0872', 'name' => 'Menard');
$city_data[] = array('accid' => 'USTX0873', 'name' => 'Mentone');
$city_data[] = array('accid' => 'USTX0874', 'name' => 'Mercedes');
$city_data[] = array('accid' => 'USTX0875', 'name' => 'Mereta');
$city_data[] = array('accid' => 'USTX0876', 'name' => 'Meridian');
$city_data[] = array('accid' => 'USTX0877', 'name' => 'Merit');
$city_data[] = array('accid' => 'USTX0878', 'name' => 'Merkel');
$city_data[] = array('accid' => 'USTX0879', 'name' => 'Mertens');
$city_data[] = array('accid' => 'USTX0880', 'name' => 'Mertzon');
$city_data[] = array('accid' => 'USTX0881', 'name' => 'Mesquite');
$city_data[] = array('accid' => 'USTX0882', 'name' => 'Mexia');
$city_data[] = array('accid' => 'USTX0883', 'name' => 'Meyersville');
$city_data[] = array('accid' => 'USTX0884', 'name' => 'Miami');
$city_data[] = array('accid' => 'USTX0885', 'name' => 'Mico');
$city_data[] = array('accid' => 'USTX0886', 'name' => 'Midfield');
$city_data[] = array('accid' => 'USTX0887', 'name' => 'Midkiff');
$city_data[] = array('accid' => 'USTX0888', 'name' => 'Midland');
$city_data[] = array('accid' => 'USTX0889', 'name' => 'Midlothian');
$city_data[] = array('accid' => 'USTX0890', 'name' => 'Midway');
$city_data[] = array('accid' => 'USTX0891', 'name' => 'Milam');
$city_data[] = array('accid' => 'USTX0892', 'name' => 'Milano');
$city_data[] = array('accid' => 'USTX0893', 'name' => 'Miles');
$city_data[] = array('accid' => 'USTX0894', 'name' => 'Milford');
$city_data[] = array('accid' => 'USTX0895', 'name' => 'Millersview');
$city_data[] = array('accid' => 'USTX0896', 'name' => 'Millican');
$city_data[] = array('accid' => 'USTX0897', 'name' => 'Millsap');
$city_data[] = array('accid' => 'USTX0898', 'name' => 'Minden');
$city_data[] = array('accid' => 'USTX0899', 'name' => 'Mineola');
$city_data[] = array('accid' => 'USTX0900', 'name' => 'Mineral');
$city_data[] = array('accid' => 'USTX0901', 'name' => 'Mineral Wells');
$city_data[] = array('accid' => 'USTX0902', 'name' => 'Mingus');
$city_data[] = array('accid' => 'USTX0903', 'name' => 'Mirando City');
$city_data[] = array('accid' => 'USTX0904', 'name' => 'Mission');
$city_data[] = array('accid' => 'USTX0905', 'name' => 'Missouri City');
$city_data[] = array('accid' => 'USTX0906', 'name' => 'Mobeetie');
$city_data[] = array('accid' => 'USTX0907', 'name' => 'Monahans');
$city_data[] = array('accid' => 'USTX0908', 'name' => 'Mont Belvieu');
$city_data[] = array('accid' => 'USTX0909', 'name' => 'Montague');
$city_data[] = array('accid' => 'USTX0910', 'name' => 'Montalba');
$city_data[] = array('accid' => 'USTX0911', 'name' => 'Montgomery');
$city_data[] = array('accid' => 'USTX0912', 'name' => 'Moody');
$city_data[] = array('accid' => 'USTX0913', 'name' => 'Moore');
$city_data[] = array('accid' => 'USTX0914', 'name' => 'Moran');
$city_data[] = array('accid' => 'USTX0915', 'name' => 'Morgan');
$city_data[] = array('accid' => 'USTX0916', 'name' => 'Morgan Mill');
$city_data[] = array('accid' => 'USTX0917', 'name' => 'Morse');
$city_data[] = array('accid' => 'USTX0918', 'name' => 'Morton');
$city_data[] = array('accid' => 'USTX0919', 'name' => 'Moscow');
$city_data[] = array('accid' => 'USTX0920', 'name' => 'Moulton');
$city_data[] = array('accid' => 'USTX0921', 'name' => 'Mound');
$city_data[] = array('accid' => 'USTX0922', 'name' => 'Mount Calm');
$city_data[] = array('accid' => 'USTX0923', 'name' => 'Mount Enterprise');
$city_data[] = array('accid' => 'USTX0924', 'name' => 'Mount Pleasant');
$city_data[] = array('accid' => 'USTX0925', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USTX0926', 'name' => 'Mountain Home');
$city_data[] = array('accid' => 'USTX0927', 'name' => 'Muenster');
$city_data[] = array('accid' => 'USTX0928', 'name' => 'Muldoon');
$city_data[] = array('accid' => 'USTX0929', 'name' => 'Muleshoe');
$city_data[] = array('accid' => 'USTX0930', 'name' => 'Mullin');
$city_data[] = array('accid' => 'USTX0931', 'name' => 'Mumford');
$city_data[] = array('accid' => 'USTX0932', 'name' => 'Munday');
$city_data[] = array('accid' => 'USTX0933', 'name' => 'Murchison');
$city_data[] = array('accid' => 'USTX0934', 'name' => 'Myra');
$city_data[] = array('accid' => 'USTX0935', 'name' => 'Nacogdoches');
$city_data[] = array('accid' => 'USTX0936', 'name' => 'Nada');
$city_data[] = array('accid' => 'USTX0937', 'name' => 'Naples');
$city_data[] = array('accid' => 'USTX0938', 'name' => 'Nash');
$city_data[] = array('accid' => 'USTX0939', 'name' => 'Natalia');
$city_data[] = array('accid' => 'USTX0941', 'name' => 'Navasota');
$city_data[] = array('accid' => 'USTX0942', 'name' => 'Nazareth');
$city_data[] = array('accid' => 'USTX0943', 'name' => 'Neches');
$city_data[] = array('accid' => 'USTX0944', 'name' => 'Nederland');
$city_data[] = array('accid' => 'USTX0945', 'name' => 'Needville');
$city_data[] = array('accid' => 'USTX0946', 'name' => 'Nemo');
$city_data[] = array('accid' => 'USTX0947', 'name' => 'Nevada');
$city_data[] = array('accid' => 'USTX0948', 'name' => 'New Baden');
$city_data[] = array('accid' => 'USTX0949', 'name' => 'New Boston');
$city_data[] = array('accid' => 'USTX0950', 'name' => 'New Braunfels');
$city_data[] = array('accid' => 'USTX0951', 'name' => 'New Caney');
$city_data[] = array('accid' => 'USTX0952', 'name' => 'New Deal');
$city_data[] = array('accid' => 'USTX0953', 'name' => 'New Home');
$city_data[] = array('accid' => 'USTX0954', 'name' => 'New London');
$city_data[] = array('accid' => 'USTX0955', 'name' => 'New Summerfield');
$city_data[] = array('accid' => 'USTX0956', 'name' => 'New Ulm');
$city_data[] = array('accid' => 'USTX0957', 'name' => 'New Waverly');
$city_data[] = array('accid' => 'USTX0958', 'name' => 'Newark');
$city_data[] = array('accid' => 'USTX0959', 'name' => 'Newcastle');
$city_data[] = array('accid' => 'USTX0960', 'name' => 'Newgulf');
$city_data[] = array('accid' => 'USTX0961', 'name' => 'Newton');
$city_data[] = array('accid' => 'USTX0962', 'name' => 'Nixon');
$city_data[] = array('accid' => 'USTX0963', 'name' => 'Nocona');
$city_data[] = array('accid' => 'USTX0964', 'name' => 'Nolan');
$city_data[] = array('accid' => 'USTX0965', 'name' => 'Nolanville');
$city_data[] = array('accid' => 'USTX0966', 'name' => 'Nome');
$city_data[] = array('accid' => 'USTX0967', 'name' => 'Nordheim');
$city_data[] = array('accid' => 'USTX0968', 'name' => 'Normangee');
$city_data[] = array('accid' => 'USTX0969', 'name' => 'Normanna');
$city_data[] = array('accid' => 'USTX0970', 'name' => 'North Houston');
$city_data[] = array('accid' => 'USTX0971', 'name' => 'North Richland Hills');
$city_data[] = array('accid' => 'USTX0972', 'name' => 'North Zulch');
$city_data[] = array('accid' => 'USTX0973', 'name' => 'Norton');
$city_data[] = array('accid' => 'USTX0974', 'name' => 'Notrees');
$city_data[] = array('accid' => 'USTX0975', 'name' => 'Novice');
$city_data[] = array('accid' => 'USTX0976', 'name' => 'Nursery');
$city_data[] = array('accid' => 'USTX0981', 'name' => 'O\'brien');
$city_data[] = array('accid' => 'USTX0977', 'name' => 'Oakhurst');
$city_data[] = array('accid' => 'USTX0978', 'name' => 'Oakland');
$city_data[] = array('accid' => 'USTX0979', 'name' => 'Oakville');
$city_data[] = array('accid' => 'USTX0980', 'name' => 'Oakwood');
$city_data[] = array('accid' => 'USTX0982', 'name' => 'Odell');
$city_data[] = array('accid' => 'USTX0983', 'name' => 'Odem');
$city_data[] = array('accid' => 'USTX0984', 'name' => 'Odessa');
$city_data[] = array('accid' => 'USTX0985', 'name' => 'Odonnell');
$city_data[] = array('accid' => 'USTX0986', 'name' => 'Oglesby');
$city_data[] = array('accid' => 'USTX0987', 'name' => 'Oilton');
$city_data[] = array('accid' => 'USTX0988', 'name' => 'Oklaunion');
$city_data[] = array('accid' => 'USTX0989', 'name' => 'Old Glory');
$city_data[] = array('accid' => 'USTX0990', 'name' => 'Old Ocean');
$city_data[] = array('accid' => 'USTX0991', 'name' => 'Olden');
$city_data[] = array('accid' => 'USTX0992', 'name' => 'Olmito');
$city_data[] = array('accid' => 'USTX0993', 'name' => 'Olney');
$city_data[] = array('accid' => 'USTX0994', 'name' => 'Olton');
$city_data[] = array('accid' => 'USTX0995', 'name' => 'Omaha');
$city_data[] = array('accid' => 'USTX0996', 'name' => 'Onalaska');
$city_data[] = array('accid' => 'USTX0997', 'name' => 'Orange');
$city_data[] = array('accid' => 'USTX0998', 'name' => 'Orange Grove');
$city_data[] = array('accid' => 'USTX0999', 'name' => 'Orangefield');
$city_data[] = array('accid' => 'USTX1000', 'name' => 'Orchard');
$city_data[] = array('accid' => 'USTX1001', 'name' => 'Ore City');
$city_data[] = array('accid' => 'USTX1002', 'name' => 'Orla');
$city_data[] = array('accid' => 'USTX1003', 'name' => 'Ottine');
$city_data[] = array('accid' => 'USTX1004', 'name' => 'Otto');
$city_data[] = array('accid' => 'USTX1005', 'name' => 'Ovalo');
$city_data[] = array('accid' => 'USTX1006', 'name' => 'Overton');
$city_data[] = array('accid' => 'USTX1007', 'name' => 'Ozona');
$city_data[] = array('accid' => 'USTX1009', 'name' => 'Paducah');
$city_data[] = array('accid' => 'USTX1010', 'name' => 'Paige');
$city_data[] = array('accid' => 'USTX1011', 'name' => 'Paint Rock');
$city_data[] = array('accid' => 'USTX1012', 'name' => 'Palacios');
$city_data[] = array('accid' => 'USTX1013', 'name' => 'Palestine');
$city_data[] = array('accid' => 'USTX1014', 'name' => 'Palmer');
$city_data[] = array('accid' => 'USTX1015', 'name' => 'Palo Pinto');
$city_data[] = array('accid' => 'USTX1016', 'name' => 'Paluxy');
$city_data[] = array('accid' => 'USTX1017', 'name' => 'Pampa');
$city_data[] = array('accid' => 'USTX1018', 'name' => 'Pandora');
$city_data[] = array('accid' => 'USTX1019', 'name' => 'Panhandle');
$city_data[] = array('accid' => 'USTX1020', 'name' => 'Panna Maria');
$city_data[] = array('accid' => 'USTX1021', 'name' => 'Panola');
$city_data[] = array('accid' => 'USTX1022', 'name' => 'Paradise');
$city_data[] = array('accid' => 'USTX1023', 'name' => 'Paris');
$city_data[] = array('accid' => 'USTX1024', 'name' => 'Pasadena');
$city_data[] = array('accid' => 'USTX1025', 'name' => 'Pattison');
$city_data[] = array('accid' => 'USTX1026', 'name' => 'Pattonville');
$city_data[] = array('accid' => 'USTX1027', 'name' => 'Pawnee');
$city_data[] = array('accid' => 'USTX1028', 'name' => 'Pear Valley');
$city_data[] = array('accid' => 'USTX1029', 'name' => 'Pearland');
$city_data[] = array('accid' => 'USTX1030', 'name' => 'Pearsall');
$city_data[] = array('accid' => 'USTX1031', 'name' => 'Peaster');
$city_data[] = array('accid' => 'USTX1032', 'name' => 'Pecan Gap');
$city_data[] = array('accid' => 'USTX1033', 'name' => 'Pecos');
$city_data[] = array('accid' => 'USTX1034', 'name' => 'Peggy');
$city_data[] = array('accid' => 'USTX1035', 'name' => 'Pendleton');
$city_data[] = array('accid' => 'USTX1036', 'name' => 'Penelope');
$city_data[] = array('accid' => 'USTX1037', 'name' => 'Penitas');
$city_data[] = array('accid' => 'USTX1038', 'name' => 'Pennington');
$city_data[] = array('accid' => 'USTX1039', 'name' => 'Penwell');
$city_data[] = array('accid' => 'USTX1040', 'name' => 'Pep');
$city_data[] = array('accid' => 'USTX1041', 'name' => 'Perrin');
$city_data[] = array('accid' => 'USTX1042', 'name' => 'Perry');
$city_data[] = array('accid' => 'USTX1043', 'name' => 'Perryton');
$city_data[] = array('accid' => 'USTX1044', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USTX1045', 'name' => 'Petrolia');
$city_data[] = array('accid' => 'USTX1046', 'name' => 'Pettus');
$city_data[] = array('accid' => 'USTX1047', 'name' => 'Petty');
$city_data[] = array('accid' => 'USTX1048', 'name' => 'Pflugerville');
$city_data[] = array('accid' => 'USTX1049', 'name' => 'Pharr');
$city_data[] = array('accid' => 'USTX1050', 'name' => 'Pickton');
$city_data[] = array('accid' => 'USTX1051', 'name' => 'Pierce');
$city_data[] = array('accid' => 'USTX1052', 'name' => 'Pilot Point');
$city_data[] = array('accid' => 'USTX1053', 'name' => 'Pinehurst');
$city_data[] = array('accid' => 'USTX1054', 'name' => 'Pineland');
$city_data[] = array('accid' => 'USTX1055', 'name' => 'Pipe Creek');
$city_data[] = array('accid' => 'USTX1056', 'name' => 'Pittsburg');
$city_data[] = array('accid' => 'USTX1057', 'name' => 'Placedo');
$city_data[] = array('accid' => 'USTX1058', 'name' => 'Plains');
$city_data[] = array('accid' => 'USTX1059', 'name' => 'Plainview');
$city_data[] = array('accid' => 'USTX1060', 'name' => 'Plano');
$city_data[] = array('accid' => 'USTX1061', 'name' => 'Plantersville');
$city_data[] = array('accid' => 'USTX1062', 'name' => 'Pleasanton');
$city_data[] = array('accid' => 'USTX1063', 'name' => 'Pledger');
$city_data[] = array('accid' => 'USTX1064', 'name' => 'Plum');
$city_data[] = array('accid' => 'USTX1065', 'name' => 'Point');
$city_data[] = array('accid' => 'USTX1066', 'name' => 'Point Comfort');
$city_data[] = array('accid' => 'USTX1067', 'name' => 'Pointblank');
$city_data[] = array('accid' => 'USTX1068', 'name' => 'Pollok');
$city_data[] = array('accid' => 'USTX1069', 'name' => 'Ponder');
$city_data[] = array('accid' => 'USTX1070', 'name' => 'Pontotoc');
$city_data[] = array('accid' => 'USTX1071', 'name' => 'Poolville');
$city_data[] = array('accid' => 'USTX1072', 'name' => 'Port Aransas');
$city_data[] = array('accid' => 'USTX1073', 'name' => 'Port Arthur');
$city_data[] = array('accid' => 'USTX1074', 'name' => 'Port Bolivar');
$city_data[] = array('accid' => 'USTX1075', 'name' => 'Port Isabel');
$city_data[] = array('accid' => 'USTX1076', 'name' => 'Port Lavaca');
$city_data[] = array('accid' => 'USTX1077', 'name' => 'Port Mansfield');
$city_data[] = array('accid' => 'USTX1078', 'name' => 'Port Neches');
$city_data[] = array('accid' => 'USTX1079', 'name' => 'Port O\'connor');
$city_data[] = array('accid' => 'USTX1080', 'name' => 'Porter');
$city_data[] = array('accid' => 'USTX1081', 'name' => 'Portland');
$city_data[] = array('accid' => 'USTX1082', 'name' => 'Post');
$city_data[] = array('accid' => 'USTX1083', 'name' => 'Poteet');
$city_data[] = array('accid' => 'USTX1084', 'name' => 'Poth');
$city_data[] = array('accid' => 'USTX1085', 'name' => 'Pottsboro');
$city_data[] = array('accid' => 'USTX1086', 'name' => 'Pottsville');
$city_data[] = array('accid' => 'USTX1087', 'name' => 'Powderly');
$city_data[] = array('accid' => 'USTX1088', 'name' => 'Powell');
$city_data[] = array('accid' => 'USTX1089', 'name' => 'Poynor');
$city_data[] = array('accid' => 'USTX1090', 'name' => 'Prairie Hill');
$city_data[] = array('accid' => 'USTX1091', 'name' => 'Prairie Lea');
$city_data[] = array('accid' => 'USTX1092', 'name' => 'Prairie View');
$city_data[] = array('accid' => 'USTX1093', 'name' => 'Premont');
$city_data[] = array('accid' => 'USTX1094', 'name' => 'Presidio');
$city_data[] = array('accid' => 'USTX1095', 'name' => 'Price');
$city_data[] = array('accid' => 'USTX1096', 'name' => 'Priddy');
$city_data[] = array('accid' => 'USTX1097', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USTX1098', 'name' => 'Proctor');
$city_data[] = array('accid' => 'USTX1099', 'name' => 'Progreso');
$city_data[] = array('accid' => 'USTX1100', 'name' => 'Prosper');
$city_data[] = array('accid' => 'USTX1101', 'name' => 'Purdon');
$city_data[] = array('accid' => 'USTX1102', 'name' => 'Purmela');
$city_data[] = array('accid' => 'USTX1103', 'name' => 'Putnam');
$city_data[] = array('accid' => 'USTX1104', 'name' => 'Pyote');
$city_data[] = array('accid' => 'USTX1105', 'name' => 'Quail');
$city_data[] = array('accid' => 'USTX1106', 'name' => 'Quanah');
$city_data[] = array('accid' => 'USTX1107', 'name' => 'Queen City');
$city_data[] = array('accid' => 'USTX1108', 'name' => 'Quemado');
$city_data[] = array('accid' => 'USTX1109', 'name' => 'Quinlan');
$city_data[] = array('accid' => 'USTX1110', 'name' => 'Quitaque');
$city_data[] = array('accid' => 'USTX1111', 'name' => 'Quitman');
$city_data[] = array('accid' => 'USTX1112', 'name' => 'Rainbow');
$city_data[] = array('accid' => 'USTX1113', 'name' => 'Ralls');
$city_data[] = array('accid' => 'USTX1114', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USTX1115', 'name' => 'Ranger');
$city_data[] = array('accid' => 'USTX1116', 'name' => 'Rankin');
$city_data[] = array('accid' => 'USTX1117', 'name' => 'Ransom Canyon');
$city_data[] = array('accid' => 'USTX1118', 'name' => 'Ratcliff');
$city_data[] = array('accid' => 'USTX1119', 'name' => 'Ravenna');
$city_data[] = array('accid' => 'USTX1120', 'name' => 'Raymondville');
$city_data[] = array('accid' => 'USTX1121', 'name' => 'Raywood');
$city_data[] = array('accid' => 'USTX1122', 'name' => 'Reagan');
$city_data[] = array('accid' => 'USTX1123', 'name' => 'Realitos');
$city_data[] = array('accid' => 'USTX1124', 'name' => 'Red Oak');
$city_data[] = array('accid' => 'USTX1125', 'name' => 'Red Rock');
$city_data[] = array('accid' => 'USTX1126', 'name' => 'Redford');
$city_data[] = array('accid' => 'USTX1127', 'name' => 'Redwater');
$city_data[] = array('accid' => 'USTX1128', 'name' => 'Reese AFB');
$city_data[] = array('accid' => 'USTX1129', 'name' => 'Refugio');
$city_data[] = array('accid' => 'USTX1130', 'name' => 'Reklaw');
$city_data[] = array('accid' => 'USTX1131', 'name' => 'Rhome');
$city_data[] = array('accid' => 'USTX1132', 'name' => 'Rice');
$city_data[] = array('accid' => 'USTX1133', 'name' => 'Richards');
$city_data[] = array('accid' => 'USTX1134', 'name' => 'Richardson');
$city_data[] = array('accid' => 'USTX1135', 'name' => 'Richland');
$city_data[] = array('accid' => 'USTX1136', 'name' => 'Richland Springs');
$city_data[] = array('accid' => 'USTX1137', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USTX1138', 'name' => 'Riesel');
$city_data[] = array('accid' => 'USTX1139', 'name' => 'Ringgold');
$city_data[] = array('accid' => 'USTX1140', 'name' => 'Rio Frio');
$city_data[] = array('accid' => 'USTX1141', 'name' => 'Rio Grande City');
$city_data[] = array('accid' => 'USTX1142', 'name' => 'Rio Hondo');
$city_data[] = array('accid' => 'USTX1143', 'name' => 'Rio Medina');
$city_data[] = array('accid' => 'USTX1144', 'name' => 'Rio Vista');
$city_data[] = array('accid' => 'USTX1145', 'name' => 'Rising Star');
$city_data[] = array('accid' => 'USTX1146', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USTX1147', 'name' => 'Riviera');
$city_data[] = array('accid' => 'USTX1148', 'name' => 'Roanoke');
$city_data[] = array('accid' => 'USTX1149', 'name' => 'Roans Prairie');
$city_data[] = array('accid' => 'USTX1150', 'name' => 'Roaring Springs');
$city_data[] = array('accid' => 'USTX1151', 'name' => 'Robert Lee');
$city_data[] = array('accid' => 'USTX1152', 'name' => 'Robstown');
$city_data[] = array('accid' => 'USTX1153', 'name' => 'Roby');
$city_data[] = array('accid' => 'USTX1154', 'name' => 'Rochelle');
$city_data[] = array('accid' => 'USTX1155', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USTX1156', 'name' => 'Rock Island');
$city_data[] = array('accid' => 'USTX1157', 'name' => 'Rockdale');
$city_data[] = array('accid' => 'USTX1158', 'name' => 'Rockport');
$city_data[] = array('accid' => 'USTX1159', 'name' => 'Rocksprings');
$city_data[] = array('accid' => 'USTX1160', 'name' => 'Rockwall');
$city_data[] = array('accid' => 'USTX1161', 'name' => 'Rockwood');
$city_data[] = array('accid' => 'USTX1162', 'name' => 'Rogers');
$city_data[] = array('accid' => 'USTX1163', 'name' => 'Roma');
$city_data[] = array('accid' => 'USTX1164', 'name' => 'Romayor');
$city_data[] = array('accid' => 'USTX1165', 'name' => 'Roosevelt');
$city_data[] = array('accid' => 'USTX1166', 'name' => 'Ropesville');
$city_data[] = array('accid' => 'USTX1167', 'name' => 'Rosanky');
$city_data[] = array('accid' => 'USTX1168', 'name' => 'Roscoe');
$city_data[] = array('accid' => 'USTX1169', 'name' => 'Rosebud');
$city_data[] = array('accid' => 'USTX1170', 'name' => 'Rosenberg');
$city_data[] = array('accid' => 'USTX1171', 'name' => 'Rosharon');
$city_data[] = array('accid' => 'USTX1172', 'name' => 'Ross');
$city_data[] = array('accid' => 'USTX1173', 'name' => 'Rosser');
$city_data[] = array('accid' => 'USTX1174', 'name' => 'Rosston');
$city_data[] = array('accid' => 'USTX1175', 'name' => 'Rotan');
$city_data[] = array('accid' => 'USTX1176', 'name' => 'Round Mountain');
$city_data[] = array('accid' => 'USTX1177', 'name' => 'Round Rock');
$city_data[] = array('accid' => 'USTX1178', 'name' => 'Round Top');
$city_data[] = array('accid' => 'USTX1179', 'name' => 'Rowena');
$city_data[] = array('accid' => 'USTX1180', 'name' => 'Rowlett');
$city_data[] = array('accid' => 'USTX1181', 'name' => 'Roxton');
$city_data[] = array('accid' => 'USTX1182', 'name' => 'Royalty');
$city_data[] = array('accid' => 'USTX1183', 'name' => 'Royse City');
$city_data[] = array('accid' => 'USTX1184', 'name' => 'Rule');
$city_data[] = array('accid' => 'USTX1185', 'name' => 'Runge');
$city_data[] = array('accid' => 'USTX1186', 'name' => 'Rusk');
$city_data[] = array('accid' => 'USTX1187', 'name' => 'Rye');
$city_data[] = array('accid' => 'USTX1188', 'name' => 'Sabinal');
$city_data[] = array('accid' => 'USTX1189', 'name' => 'Sabine Pass');
$city_data[] = array('accid' => 'USTX1190', 'name' => 'Sacul');
$city_data[] = array('accid' => 'USTX1191', 'name' => 'Sadler');
$city_data[] = array('accid' => 'USTX1192', 'name' => 'Saint Hedwig');
$city_data[] = array('accid' => 'USTX1193', 'name' => 'Saint Jo');
$city_data[] = array('accid' => 'USTX1194', 'name' => 'Salado');
$city_data[] = array('accid' => 'USTX1195', 'name' => 'Salineno');
$city_data[] = array('accid' => 'USTX1196', 'name' => 'Salt Flat');
$city_data[] = array('accid' => 'USTX1197', 'name' => 'Saltillo');
$city_data[] = array('accid' => 'USTX1198', 'name' => 'Samnorwood');
$city_data[] = array('accid' => 'USTX1199', 'name' => 'San Angelo');
$city_data[] = array('accid' => 'USTX1200', 'name' => 'San Antonio');
$city_data[] = array('accid' => 'USTX1203', 'name' => 'San Augustine');
$city_data[] = array('accid' => 'USTX1204', 'name' => 'San Benito');
$city_data[] = array('accid' => 'USTX1205', 'name' => 'San Diego');
$city_data[] = array('accid' => 'USTX1206', 'name' => 'San Elizario');
$city_data[] = array('accid' => 'USTX1207', 'name' => 'San Felipe');
$city_data[] = array('accid' => 'USTX1208', 'name' => 'San Isidro');
$city_data[] = array('accid' => 'USTX1209', 'name' => 'San Juan');
$city_data[] = array('accid' => 'USTX1210', 'name' => 'San Marcos');
$city_data[] = array('accid' => 'USTX1211', 'name' => 'San Perlita');
$city_data[] = array('accid' => 'USTX1212', 'name' => 'San Saba');
$city_data[] = array('accid' => 'USTX1213', 'name' => 'San Ygnacio');
$city_data[] = array('accid' => 'USTX1214', 'name' => 'Sanderson');
$city_data[] = array('accid' => 'USTX1215', 'name' => 'Sandia');
$city_data[] = array('accid' => 'USTX1216', 'name' => 'Sandy');
$city_data[] = array('accid' => 'USTX1217', 'name' => 'Sanford');
$city_data[] = array('accid' => 'USTX1218', 'name' => 'Sanger');
$city_data[] = array('accid' => 'USTX1219', 'name' => 'Santa Anna');
$city_data[] = array('accid' => 'USTX1220', 'name' => 'Santa Elena');
$city_data[] = array('accid' => 'USTX1221', 'name' => 'Santa Fe');
$city_data[] = array('accid' => 'USTX1222', 'name' => 'Santa Maria');
$city_data[] = array('accid' => 'USTX1223', 'name' => 'Santa Rosa');
$city_data[] = array('accid' => 'USTX1224', 'name' => 'Santo');
$city_data[] = array('accid' => 'USTX1225', 'name' => 'Saragosa');
$city_data[] = array('accid' => 'USTX1226', 'name' => 'Saratoga');
$city_data[] = array('accid' => 'USTX1227', 'name' => 'Sarita');
$city_data[] = array('accid' => 'USTX1228', 'name' => 'Satin');
$city_data[] = array('accid' => 'USTX1229', 'name' => 'Savoy');
$city_data[] = array('accid' => 'USTX1230', 'name' => 'Schertz');
$city_data[] = array('accid' => 'USTX1231', 'name' => 'Schulenburg');
$city_data[] = array('accid' => 'USTX1232', 'name' => 'Schwertner');
$city_data[] = array('accid' => 'USTX1233', 'name' => 'Scotland');
$city_data[] = array('accid' => 'USTX1234', 'name' => 'Scottsville');
$city_data[] = array('accid' => 'USTX1235', 'name' => 'Scroggins');
$city_data[] = array('accid' => 'USTX1236', 'name' => 'Scurry');
$city_data[] = array('accid' => 'USTX1237', 'name' => 'Seabrook');
$city_data[] = array('accid' => 'USTX1238', 'name' => 'Seadrift');
$city_data[] = array('accid' => 'USTX1239', 'name' => 'Seagoville');
$city_data[] = array('accid' => 'USTX1240', 'name' => 'Seagraves');
$city_data[] = array('accid' => 'USTX1241', 'name' => 'Sealy');
$city_data[] = array('accid' => 'USTX1242', 'name' => 'Sebastian');
$city_data[] = array('accid' => 'USTX1243', 'name' => 'Seguin');
$city_data[] = array('accid' => 'USTX1244', 'name' => 'Selman City');
$city_data[] = array('accid' => 'USTX1245', 'name' => 'Seminole');
$city_data[] = array('accid' => 'USTX1246', 'name' => 'Seymour');
$city_data[] = array('accid' => 'USTX1247', 'name' => 'Shafter');
$city_data[] = array('accid' => 'USTX1248', 'name' => 'Shallowater');
$city_data[] = array('accid' => 'USTX1249', 'name' => 'Shamrock');
$city_data[] = array('accid' => 'USTX1250', 'name' => 'Sheffield');
$city_data[] = array('accid' => 'USTX1251', 'name' => 'Shelbyville');
$city_data[] = array('accid' => 'USTX1252', 'name' => 'Shepherd');
$city_data[] = array('accid' => 'USTX1253', 'name' => 'Sheppard AFB');
$city_data[] = array('accid' => 'USTX1254', 'name' => 'Sheridan');
$city_data[] = array('accid' => 'USTX1255', 'name' => 'Sherman');
$city_data[] = array('accid' => 'USTX1256', 'name' => 'Shiner');
$city_data[] = array('accid' => 'USTX1257', 'name' => 'Shiro');
$city_data[] = array('accid' => 'USTX1258', 'name' => 'Sidney');
$city_data[] = array('accid' => 'USTX1259', 'name' => 'Sierra Blanca');
$city_data[] = array('accid' => 'USTX1260', 'name' => 'Silsbee');
$city_data[] = array('accid' => 'USTX1261', 'name' => 'Silver');
$city_data[] = array('accid' => 'USTX1262', 'name' => 'Silverton');
$city_data[] = array('accid' => 'USTX1263', 'name' => 'Simms');
$city_data[] = array('accid' => 'USTX1264', 'name' => 'Simonton');
$city_data[] = array('accid' => 'USTX1265', 'name' => 'Sinton');
$city_data[] = array('accid' => 'USTX1266', 'name' => 'Skellytown');
$city_data[] = array('accid' => 'USTX1267', 'name' => 'Skidmore');
$city_data[] = array('accid' => 'USTX1268', 'name' => 'Slaton');
$city_data[] = array('accid' => 'USTX1269', 'name' => 'Slidell');
$city_data[] = array('accid' => 'USTX1270', 'name' => 'Smiley');
$city_data[] = array('accid' => 'USTX1271', 'name' => 'Smithville');
$city_data[] = array('accid' => 'USTX1272', 'name' => 'Smyer');
$city_data[] = array('accid' => 'USTX1273', 'name' => 'Snook');
$city_data[] = array('accid' => 'USTX1274', 'name' => 'Snyder');
$city_data[] = array('accid' => 'USTX1275', 'name' => 'Somerset');
$city_data[] = array('accid' => 'USTX1276', 'name' => 'Somerville');
$city_data[] = array('accid' => 'USTX1277', 'name' => 'Sonora');
$city_data[] = array('accid' => 'USTX1278', 'name' => 'Sour Lake');
$city_data[] = array('accid' => 'USTX1279', 'name' => 'South Bend');
$city_data[] = array('accid' => 'USTX1280', 'name' => 'South Houston');
$city_data[] = array('accid' => 'USTX1281', 'name' => 'South Padre Island');
$city_data[] = array('accid' => 'USTX1282', 'name' => 'South Plains');
$city_data[] = array('accid' => 'USTX1283', 'name' => 'Southlake');
$city_data[] = array('accid' => 'USTX1284', 'name' => 'Southmayd');
$city_data[] = array('accid' => 'USTX1285', 'name' => 'Spade');
$city_data[] = array('accid' => 'USTX1286', 'name' => 'Speaks');
$city_data[] = array('accid' => 'USTX1287', 'name' => 'Spearman');
$city_data[] = array('accid' => 'USTX1288', 'name' => 'Spicewood');
$city_data[] = array('accid' => 'USTX1289', 'name' => 'Splendora');
$city_data[] = array('accid' => 'USTX1290', 'name' => 'Spring');
$city_data[] = array('accid' => 'USTX1291', 'name' => 'Spring Branch');
$city_data[] = array('accid' => 'USTX1292', 'name' => 'Springlake');
$city_data[] = array('accid' => 'USTX1293', 'name' => 'Springtown');
$city_data[] = array('accid' => 'USTX1294', 'name' => 'Spur');
$city_data[] = array('accid' => 'USTX1295', 'name' => 'Spurger');
$city_data[] = array('accid' => 'USTX1296', 'name' => 'Stafford');
$city_data[] = array('accid' => 'USTX1297', 'name' => 'Stamford');
$city_data[] = array('accid' => 'USTX1298', 'name' => 'Stanton');
$city_data[] = array('accid' => 'USTX1299', 'name' => 'Staples');
$city_data[] = array('accid' => 'USTX1300', 'name' => 'Star');
$city_data[] = array('accid' => 'USTX1301', 'name' => 'Stephenville');
$city_data[] = array('accid' => 'USTX1302', 'name' => 'Sterling City');
$city_data[] = array('accid' => 'USTX1303', 'name' => 'Stinnett');
$city_data[] = array('accid' => 'USTX1304', 'name' => 'Stockdale');
$city_data[] = array('accid' => 'USTX1305', 'name' => 'Stonewall');
$city_data[] = array('accid' => 'USTX1306', 'name' => 'Stowell');
$city_data[] = array('accid' => 'USTX1307', 'name' => 'Stratford');
$city_data[] = array('accid' => 'USTX1308', 'name' => 'Strawn');
$city_data[] = array('accid' => 'USTX1309', 'name' => 'Streetman');
$city_data[] = array('accid' => 'USTX1310', 'name' => 'Sublime');
$city_data[] = array('accid' => 'USTX1311', 'name' => 'Sudan');
$city_data[] = array('accid' => 'USTX1312', 'name' => 'Sugar Land');
$city_data[] = array('accid' => 'USTX1313', 'name' => 'Sullivan City');
$city_data[] = array('accid' => 'USTX1314', 'name' => 'Sulphur Bluff');
$city_data[] = array('accid' => 'USTX1315', 'name' => 'Sulphur Springs');
$city_data[] = array('accid' => 'USTX1316', 'name' => 'Summerfield');
$city_data[] = array('accid' => 'USTX1317', 'name' => 'Sumner');
$city_data[] = array('accid' => 'USTX1318', 'name' => 'Sundown');
$city_data[] = array('accid' => 'USTX1319', 'name' => 'Sunnyvale');
$city_data[] = array('accid' => 'USTX1320', 'name' => 'Sunray');
$city_data[] = array('accid' => 'USTX1321', 'name' => 'Sunset');
$city_data[] = array('accid' => 'USTX1322', 'name' => 'Sutherland Springs');
$city_data[] = array('accid' => 'USTX1323', 'name' => 'Sweeny');
$city_data[] = array('accid' => 'USTX1324', 'name' => 'Sweet Home');
$city_data[] = array('accid' => 'USTX1325', 'name' => 'Sweetwater');
$city_data[] = array('accid' => 'USTX1326', 'name' => 'Sylvester');
$city_data[] = array('accid' => 'USTX1327', 'name' => 'Taft');
$city_data[] = array('accid' => 'USTX1328', 'name' => 'Tahoka');
$city_data[] = array('accid' => 'USTX1329', 'name' => 'Talco');
$city_data[] = array('accid' => 'USTX1330', 'name' => 'Talpa');
$city_data[] = array('accid' => 'USTX1331', 'name' => 'Tarpley');
$city_data[] = array('accid' => 'USTX1332', 'name' => 'Tarzan');
$city_data[] = array('accid' => 'USTX1333', 'name' => 'Tatum');
$city_data[] = array('accid' => 'USTX1334', 'name' => 'Taylor');
$city_data[] = array('accid' => 'USTX1335', 'name' => 'Teague');
$city_data[] = array('accid' => 'USTX1336', 'name' => 'Tehuacana');
$city_data[] = array('accid' => 'USTX1337', 'name' => 'Telegraph');
$city_data[] = array('accid' => 'USTX1338', 'name' => 'Telephone');
$city_data[] = array('accid' => 'USTX1339', 'name' => 'Telferner');
$city_data[] = array('accid' => 'USTX1340', 'name' => 'Tell');
$city_data[] = array('accid' => 'USTX1341', 'name' => 'Temple');
$city_data[] = array('accid' => 'USTX1342', 'name' => 'Tenaha');
$city_data[] = array('accid' => 'USTX1343', 'name' => 'Tennessee Colony');
$city_data[] = array('accid' => 'USTX1344', 'name' => 'Tennyson');
$city_data[] = array('accid' => 'USTX1345', 'name' => 'Terlingua');
$city_data[] = array('accid' => 'USTX1346', 'name' => 'Terrell');
$city_data[] = array('accid' => 'USTX1347', 'name' => 'Texarkana');
$city_data[] = array('accid' => 'USTX1348', 'name' => 'Texas City');
$city_data[] = array('accid' => 'USTX1349', 'name' => 'Texline');
$city_data[] = array('accid' => 'USTX1350', 'name' => 'The Colony');
$city_data[] = array('accid' => 'USTX1352', 'name' => 'Thicket');
$city_data[] = array('accid' => 'USTX1353', 'name' => 'Thomaston');
$city_data[] = array('accid' => 'USTX1354', 'name' => 'Thompsons');
$city_data[] = array('accid' => 'USTX1355', 'name' => 'Thorndale');
$city_data[] = array('accid' => 'USTX1356', 'name' => 'Thornton');
$city_data[] = array('accid' => 'USTX1357', 'name' => 'Thrall');
$city_data[] = array('accid' => 'USTX1358', 'name' => 'Three Rivers');
$city_data[] = array('accid' => 'USTX1359', 'name' => 'Throckmorton');
$city_data[] = array('accid' => 'USTX1360', 'name' => 'Tilden');
$city_data[] = array('accid' => 'USTX1361', 'name' => 'Timpson');
$city_data[] = array('accid' => 'USTX1362', 'name' => 'Tioga');
$city_data[] = array('accid' => 'USTX1363', 'name' => 'Tivoli');
$city_data[] = array('accid' => 'USTX1364', 'name' => 'Tokio');
$city_data[] = array('accid' => 'USTX1365', 'name' => 'Tolar');
$city_data[] = array('accid' => 'USTX1366', 'name' => 'Tom Bean');
$city_data[] = array('accid' => 'USTX1367', 'name' => 'Tomball');
$city_data[] = array('accid' => 'USTX1368', 'name' => 'Tornillo');
$city_data[] = array('accid' => 'USTX1369', 'name' => 'Tow');
$city_data[] = array('accid' => 'USTX1370', 'name' => 'Toyah');
$city_data[] = array('accid' => 'USTX1371', 'name' => 'Toyahvale');
$city_data[] = array('accid' => 'USTX1372', 'name' => 'Trent');
$city_data[] = array('accid' => 'USTX1373', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USTX1374', 'name' => 'Trinidad');
$city_data[] = array('accid' => 'USTX1375', 'name' => 'Trinity');
$city_data[] = array('accid' => 'USTX1376', 'name' => 'Troup');
$city_data[] = array('accid' => 'USTX1377', 'name' => 'Troy');
$city_data[] = array('accid' => 'USTX1378', 'name' => 'Tuleta');
$city_data[] = array('accid' => 'USTX1379', 'name' => 'Tulia');
$city_data[] = array('accid' => 'USTX1380', 'name' => 'Turkey');
$city_data[] = array('accid' => 'USTX1381', 'name' => 'Tuscola');
$city_data[] = array('accid' => 'USTX1382', 'name' => 'Tye');
$city_data[] = array('accid' => 'USTX1383', 'name' => 'Tyler');
$city_data[] = array('accid' => 'USTX1384', 'name' => 'Tynan');
$city_data[] = array('accid' => 'USTX1385', 'name' => 'Umbarger');
$city_data[] = array('accid' => 'USTX1386', 'name' => 'Universal City');
$city_data[] = array('accid' => 'USTX1387', 'name' => 'Utopia');
$city_data[] = array('accid' => 'USTX1388', 'name' => 'Uvalde');
$city_data[] = array('accid' => 'USTX1389', 'name' => 'Valentine');
$city_data[] = array('accid' => 'USTX1390', 'name' => 'Valera');
$city_data[] = array('accid' => 'USTX1391', 'name' => 'Valley Mills');
$city_data[] = array('accid' => 'USTX1392', 'name' => 'Valley Spring');
$city_data[] = array('accid' => 'USTX1393', 'name' => 'Valley View');
$city_data[] = array('accid' => 'USTX1394', 'name' => 'Van');
$city_data[] = array('accid' => 'USTX1395', 'name' => 'Van Alstyne');
$city_data[] = array('accid' => 'USTX1396', 'name' => 'Van Horn');
$city_data[] = array('accid' => 'USTX1397', 'name' => 'Van Vleck');
$city_data[] = array('accid' => 'USTX1398', 'name' => 'Vancourt');
$city_data[] = array('accid' => 'USTX1399', 'name' => 'Vanderbilt');
$city_data[] = array('accid' => 'USTX1400', 'name' => 'Vanderpool');
$city_data[] = array('accid' => 'USTX1401', 'name' => 'Vega');
$city_data[] = array('accid' => 'USTX1402', 'name' => 'Venus');
$city_data[] = array('accid' => 'USTX1403', 'name' => 'Veribest');
$city_data[] = array('accid' => 'USTX1404', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USTX1405', 'name' => 'Victoria');
$city_data[] = array('accid' => 'USTX1406', 'name' => 'Vidor');
$city_data[] = array('accid' => 'USTX1407', 'name' => 'Village Mills');
$city_data[] = array('accid' => 'USTX1408', 'name' => 'Voca');
$city_data[] = array('accid' => 'USTX1409', 'name' => 'Von Ormy');
$city_data[] = array('accid' => 'USTX1410', 'name' => 'Voss');
$city_data[] = array('accid' => 'USTX1411', 'name' => 'Votaw');
$city_data[] = array('accid' => 'USTX1412', 'name' => 'Voth');
$city_data[] = array('accid' => 'USTX1413', 'name' => 'Waco');
$city_data[] = array('accid' => 'USTX1415', 'name' => 'Wadsworth');
$city_data[] = array('accid' => 'USTX1416', 'name' => 'Waelder');
$city_data[] = array('accid' => 'USTX1417', 'name' => 'Waka');
$city_data[] = array('accid' => 'USTX1418', 'name' => 'Walburg');
$city_data[] = array('accid' => 'USTX1419', 'name' => 'Wall');
$city_data[] = array('accid' => 'USTX1420', 'name' => 'Waller');
$city_data[] = array('accid' => 'USTX1421', 'name' => 'Wallis');
$city_data[] = array('accid' => 'USTX1422', 'name' => 'Wallisville');
$city_data[] = array('accid' => 'USTX1423', 'name' => 'Walnut Springs');
$city_data[] = array('accid' => 'USTX1424', 'name' => 'Warda');
$city_data[] = array('accid' => 'USTX1425', 'name' => 'Waring');
$city_data[] = array('accid' => 'USTX1426', 'name' => 'Warren');
$city_data[] = array('accid' => 'USTX1427', 'name' => 'Washington');
$city_data[] = array('accid' => 'USTX1428', 'name' => 'Waskom');
$city_data[] = array('accid' => 'USTX1429', 'name' => 'Water Valley');
$city_data[] = array('accid' => 'USTX1430', 'name' => 'Waxahachie');
$city_data[] = array('accid' => 'USTX1431', 'name' => 'Wayside');
$city_data[] = array('accid' => 'USTX1432', 'name' => 'Weatherford');
$city_data[] = array('accid' => 'USTX1433', 'name' => 'Webster');
$city_data[] = array('accid' => 'USTX1434', 'name' => 'Weesatche');
$city_data[] = array('accid' => 'USTX1435', 'name' => 'Weimar');
$city_data[] = array('accid' => 'USTX1436', 'name' => 'Weinert');
$city_data[] = array('accid' => 'USTX1437', 'name' => 'Weir');
$city_data[] = array('accid' => 'USTX1438', 'name' => 'Welch');
$city_data[] = array('accid' => 'USTX1439', 'name' => 'Wellborn');
$city_data[] = array('accid' => 'USTX1440', 'name' => 'Wellington');
$city_data[] = array('accid' => 'USTX1441', 'name' => 'Wellman');
$city_data[] = array('accid' => 'USTX1442', 'name' => 'Wells');
$city_data[] = array('accid' => 'USTX1443', 'name' => 'Weslaco');
$city_data[] = array('accid' => 'USTX1444', 'name' => 'West');
$city_data[] = array('accid' => 'USTX1445', 'name' => 'West Columbia');
$city_data[] = array('accid' => 'USTX1446', 'name' => 'West Point');
$city_data[] = array('accid' => 'USTX1447', 'name' => 'Westbrook');
$city_data[] = array('accid' => 'USTX1448', 'name' => 'Westhoff');
$city_data[] = array('accid' => 'USTX1449', 'name' => 'Westminster');
$city_data[] = array('accid' => 'USTX1450', 'name' => 'Weston');
$city_data[] = array('accid' => 'USTX1451', 'name' => 'Wharton');
$city_data[] = array('accid' => 'USTX1452', 'name' => 'Wheeler');
$city_data[] = array('accid' => 'USTX1453', 'name' => 'Wheelock');
$city_data[] = array('accid' => 'USTX1454', 'name' => 'White Deer');
$city_data[] = array('accid' => 'USTX1455', 'name' => 'White Oak');
$city_data[] = array('accid' => 'USTX1456', 'name' => 'Whiteface');
$city_data[] = array('accid' => 'USTX1457', 'name' => 'Whitehouse');
$city_data[] = array('accid' => 'USTX1458', 'name' => 'Whitesboro');
$city_data[] = array('accid' => 'USTX1459', 'name' => 'Whitewright');
$city_data[] = array('accid' => 'USTX1460', 'name' => 'Whitharral');
$city_data[] = array('accid' => 'USTX1461', 'name' => 'Whitney');
$city_data[] = array('accid' => 'USTX1462', 'name' => 'Whitsett');
$city_data[] = array('accid' => 'USTX1463', 'name' => 'Whitt');
$city_data[] = array('accid' => 'USTX1464', 'name' => 'Wichita Falls');
$city_data[] = array('accid' => 'USTX1465', 'name' => 'Wickett');
$city_data[] = array('accid' => 'USTX1466', 'name' => 'Wiergate');
$city_data[] = array('accid' => 'USTX1467', 'name' => 'Wildorado');
$city_data[] = array('accid' => 'USTX1468', 'name' => 'Willis');
$city_data[] = array('accid' => 'USTX1469', 'name' => 'Willow City');
$city_data[] = array('accid' => 'USTX1470', 'name' => 'Wills Point');
$city_data[] = array('accid' => 'USTX1471', 'name' => 'Wilmer');
$city_data[] = array('accid' => 'USTX1472', 'name' => 'Wilson');
$city_data[] = array('accid' => 'USTX1473', 'name' => 'Wimberley');
$city_data[] = array('accid' => 'USTX1474', 'name' => 'Windom');
$city_data[] = array('accid' => 'USTX1475', 'name' => 'Windthorst');
$city_data[] = array('accid' => 'USTX1476', 'name' => 'Winfield');
$city_data[] = array('accid' => 'USTX1477', 'name' => 'Wingate');
$city_data[] = array('accid' => 'USTX1478', 'name' => 'Wink');
$city_data[] = array('accid' => 'USTX1479', 'name' => 'Winnie');
$city_data[] = array('accid' => 'USTX1480', 'name' => 'Winnsboro');
$city_data[] = array('accid' => 'USTX1481', 'name' => 'Winona');
$city_data[] = array('accid' => 'USTX1482', 'name' => 'Winters');
$city_data[] = array('accid' => 'USTX1483', 'name' => 'Woden');
$city_data[] = array('accid' => 'USTX1484', 'name' => 'Wolfe City');
$city_data[] = array('accid' => 'USTX1485', 'name' => 'Wolfforth');
$city_data[] = array('accid' => 'USTX1486', 'name' => 'Woodlake');
$city_data[] = array('accid' => 'USTX1487', 'name' => 'Woodlawn');
$city_data[] = array('accid' => 'USTX1488', 'name' => 'Woodsboro');
$city_data[] = array('accid' => 'USTX1489', 'name' => 'Woodson');
$city_data[] = array('accid' => 'USTX1490', 'name' => 'Woodville');
$city_data[] = array('accid' => 'USTX1491', 'name' => 'Woodway');
$city_data[] = array('accid' => 'USTX1492', 'name' => 'Wortham');
$city_data[] = array('accid' => 'USTX1493', 'name' => 'Wrightsboro');
$city_data[] = array('accid' => 'USTX1494', 'name' => 'Wylie');
$city_data[] = array('accid' => 'USTX1495', 'name' => 'Yancey');
$city_data[] = array('accid' => 'USTX1496', 'name' => 'Yantis');
$city_data[] = array('accid' => 'USTX1497', 'name' => 'Yoakum');
$city_data[] = array('accid' => 'USTX1498', 'name' => 'Yorktown');
$city_data[] = array('accid' => 'USTX1499', 'name' => 'Zapata');
$city_data[] = array('accid' => 'USTX1500', 'name' => 'Zavalla');
$city_data[] = array('accid' => 'USTX1501', 'name' => 'Zephyr');

?>