<?php

// City package for USA: Utah 

$city_name = 'USA: Utah';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USUT0001', 'name' => 'Alpine');
$city_data[] = array('accid' => 'USUT0003', 'name' => 'Altamont');
$city_data[] = array('accid' => 'USUT0004', 'name' => 'Alton');
$city_data[] = array('accid' => 'USUT0005', 'name' => 'Altonah');
$city_data[] = array('accid' => 'USUT0006', 'name' => 'American Fork');
$city_data[] = array('accid' => 'USUT0007', 'name' => 'Aneth');
$city_data[] = array('accid' => 'USUT0008', 'name' => 'Annabella');
$city_data[] = array('accid' => 'USUT0009', 'name' => 'Antimony');
$city_data[] = array('accid' => 'USUT0011', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USUT0012', 'name' => 'Axtell');
$city_data[] = array('accid' => 'USUT0013', 'name' => 'Bear River City');
$city_data[] = array('accid' => 'USUT0014', 'name' => 'Beaver');
$city_data[] = array('accid' => 'USUT0016', 'name' => 'Beryl');
$city_data[] = array('accid' => 'USUT0017', 'name' => 'Bicknell');
$city_data[] = array('accid' => 'USUT0018', 'name' => 'Bingham Canyon');
$city_data[] = array('accid' => 'USUT0019', 'name' => 'Blanding');
$city_data[] = array('accid' => 'USUT0020', 'name' => 'Bluebell');
$city_data[] = array('accid' => 'USUT0021', 'name' => 'Bluff');
$city_data[] = array('accid' => 'USUT0022', 'name' => 'Bonanza');
$city_data[] = array('accid' => 'USUT0023', 'name' => 'Boulder');
$city_data[] = array('accid' => 'USUT0024', 'name' => 'Bountiful');
$city_data[] = array('accid' => 'USUT0025', 'name' => 'Brian Head');
$city_data[] = array('accid' => 'USUT0027', 'name' => 'Brigham City');
$city_data[] = array('accid' => 'USUT0029', 'name' => 'Bryce');
$city_data[] = array('accid' => 'USUT0030', 'name' => 'Bryce Canyon');
$city_data[] = array('accid' => 'USUT0033', 'name' => 'Cache Junction');
$city_data[] = array('accid' => 'USUT0034', 'name' => 'Cannonville');
$city_data[] = array('accid' => 'USUT0037', 'name' => 'Castle Dale');
$city_data[] = array('accid' => 'USUT0038', 'name' => 'Cedar City');
$city_data[] = array('accid' => 'USUT0039', 'name' => 'Cedar Valley');
$city_data[] = array('accid' => 'USUT0040', 'name' => 'Centerfield');
$city_data[] = array('accid' => 'USUT0041', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USUT0042', 'name' => 'Central');
$city_data[] = array('accid' => 'USUT0043', 'name' => 'Chester');
$city_data[] = array('accid' => 'USUT0044', 'name' => 'Circleville');
$city_data[] = array('accid' => 'USUT0045', 'name' => 'Cisco');
$city_data[] = array('accid' => 'USUT0046', 'name' => 'Clarkston');
$city_data[] = array('accid' => 'USUT0047', 'name' => 'Clawson');
$city_data[] = array('accid' => 'USUT0048', 'name' => 'Clearfield');
$city_data[] = array('accid' => 'USUT0049', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USUT0050', 'name' => 'Coalville');
$city_data[] = array('accid' => 'USUT0051', 'name' => 'Collinston');
$city_data[] = array('accid' => 'USUT0052', 'name' => 'Corinne');
$city_data[] = array('accid' => 'USUT0053', 'name' => 'Cornish');
$city_data[] = array('accid' => 'USUT0054', 'name' => 'Croydon');
$city_data[] = array('accid' => 'USUT0055', 'name' => 'Dammeron Valley');
$city_data[] = array('accid' => 'USUT0057', 'name' => 'Delta');
$city_data[] = array('accid' => 'USUT0058', 'name' => 'Deweyville');
$city_data[] = array('accid' => 'USUT0059', 'name' => 'Draper');
$city_data[] = array('accid' => 'USUT0060', 'name' => 'Duchesne');
$city_data[] = array('accid' => 'USUT0061', 'name' => 'Duck Creek Village');
$city_data[] = array('accid' => 'USUT0062', 'name' => 'Dugway');
$city_data[] = array('accid' => 'USUT0064', 'name' => 'Dutch John');
$city_data[] = array('accid' => 'USUT0065', 'name' => 'East Carbon');
$city_data[] = array('accid' => 'USUT0066', 'name' => 'Echo');
$city_data[] = array('accid' => 'USUT0067', 'name' => 'Eden');
$city_data[] = array('accid' => 'USUT0068', 'name' => 'Elberta');
$city_data[] = array('accid' => 'USUT0070', 'name' => 'Elmo');
$city_data[] = array('accid' => 'USUT0071', 'name' => 'Elsinore');
$city_data[] = array('accid' => 'USUT0072', 'name' => 'Emery');
$city_data[] = array('accid' => 'USUT0073', 'name' => 'Enterprise');
$city_data[] = array('accid' => 'USUT0074', 'name' => 'Ephraim');
$city_data[] = array('accid' => 'USUT0075', 'name' => 'Escalante');
$city_data[] = array('accid' => 'USUT0076', 'name' => 'Eureka');
$city_data[] = array('accid' => 'USUT0077', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USUT0078', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USUT0079', 'name' => 'Fayette');
$city_data[] = array('accid' => 'USUT0080', 'name' => 'Ferron');
$city_data[] = array('accid' => 'USUT0081', 'name' => 'Fielding');
$city_data[] = array('accid' => 'USUT0082', 'name' => 'Fillmore');
$city_data[] = array('accid' => 'USUT0083', 'name' => 'Fort Duchesne');
$city_data[] = array('accid' => 'USUT0084', 'name' => 'Fountain Green');
$city_data[] = array('accid' => 'USUT0085', 'name' => 'Fruitland');
$city_data[] = array('accid' => 'USUT0086', 'name' => 'Garden City');
$city_data[] = array('accid' => 'USUT0087', 'name' => 'Garland');
$city_data[] = array('accid' => 'USUT0088', 'name' => 'Garrison');
$city_data[] = array('accid' => 'USUT0089', 'name' => 'Glendale');
$city_data[] = array('accid' => 'USUT0090', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USUT0092', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USUT0093', 'name' => 'Grantsville');
$city_data[] = array('accid' => 'USUT0094', 'name' => 'Green River');
$city_data[] = array('accid' => 'USUT0095', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USUT0096', 'name' => 'Greenwich');
$city_data[] = array('accid' => 'USUT0097', 'name' => 'Grouse Creek');
$city_data[] = array('accid' => 'USUT0098', 'name' => 'Gunlock');
$city_data[] = array('accid' => 'USUT0099', 'name' => 'Gunnison');
$city_data[] = array('accid' => 'USUT0100', 'name' => 'Gusher');
$city_data[] = array('accid' => 'USUT0101', 'name' => 'Hanksville');
$city_data[] = array('accid' => 'USUT0102', 'name' => 'Hanna');
$city_data[] = array('accid' => 'USUT0103', 'name' => 'Hatch');
$city_data[] = array('accid' => 'USUT0104', 'name' => 'Heber City');
$city_data[] = array('accid' => 'USUT0105', 'name' => 'Helper');
$city_data[] = array('accid' => 'USUT0106', 'name' => 'Henefer');
$city_data[] = array('accid' => 'USUT0107', 'name' => 'Henrieville');
$city_data[] = array('accid' => 'USUT0108', 'name' => 'Hiawatha');
$city_data[] = array('accid' => 'USUT0109', 'name' => 'Hildale');
$city_data[] = array('accid' => 'USUT0110', 'name' => 'Hill AFB');
$city_data[] = array('accid' => 'USUT0111', 'name' => 'Hinckley');
$city_data[] = array('accid' => 'USUT0112', 'name' => 'Holden');
$city_data[] = array('accid' => 'USUT0113', 'name' => 'Honeyville');
$city_data[] = array('accid' => 'USUT0114', 'name' => 'Hooper');
$city_data[] = array('accid' => 'USUT0115', 'name' => 'Howell');
$city_data[] = array('accid' => 'USUT0116', 'name' => 'Huntington');
$city_data[] = array('accid' => 'USUT0117', 'name' => 'Huntsville');
$city_data[] = array('accid' => 'USUT0118', 'name' => 'Hurricane');
$city_data[] = array('accid' => 'USUT0119', 'name' => 'Hyde Park');
$city_data[] = array('accid' => 'USUT0120', 'name' => 'Hyrum');
$city_data[] = array('accid' => 'USUT0121', 'name' => 'Ibapah');
$city_data[] = array('accid' => 'USUT0122', 'name' => 'Ivins');
$city_data[] = array('accid' => 'USUT0123', 'name' => 'Jensen');
$city_data[] = array('accid' => 'USUT0124', 'name' => 'Joseph');
$city_data[] = array('accid' => 'USUT0125', 'name' => 'Junction');
$city_data[] = array('accid' => 'USUT0126', 'name' => 'Kamas');
$city_data[] = array('accid' => 'USUT0127', 'name' => 'Kanab');
$city_data[] = array('accid' => 'USUT0128', 'name' => 'Kanarraville');
$city_data[] = array('accid' => 'USUT0129', 'name' => 'Kanosh');
$city_data[] = array('accid' => 'USUT0130', 'name' => 'Kaysville');
$city_data[] = array('accid' => 'USUT0131', 'name' => 'Kenilworth');
$city_data[] = array('accid' => 'USUT0132', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USUT0133', 'name' => 'Koosharem');
$city_data[] = array('accid' => 'USUT0134', 'name' => 'La Sal');
$city_data[] = array('accid' => 'USUT0135', 'name' => 'La Verkin');
$city_data[] = array('accid' => 'USUT0136', 'name' => 'Lake Powell');
$city_data[] = array('accid' => 'USUT0137', 'name' => 'Laketown');
$city_data[] = array('accid' => 'USUT0138', 'name' => 'Lapoint');
$city_data[] = array('accid' => 'USUT0139', 'name' => 'Layton');
$city_data[] = array('accid' => 'USUT0140', 'name' => 'Leamington');
$city_data[] = array('accid' => 'USUT0141', 'name' => 'Leeds');
$city_data[] = array('accid' => 'USUT0142', 'name' => 'Lehi');
$city_data[] = array('accid' => 'USUT0143', 'name' => 'Levan');
$city_data[] = array('accid' => 'USUT0144', 'name' => 'Lewiston');
$city_data[] = array('accid' => 'USUT0145', 'name' => 'Lindon');
$city_data[] = array('accid' => 'USUT0146', 'name' => 'Loa');
$city_data[] = array('accid' => 'USUT0147', 'name' => 'Logan');
$city_data[] = array('accid' => 'USUT0148', 'name' => 'Lyman');
$city_data[] = array('accid' => 'USUT0149', 'name' => 'Lynndyl');
$city_data[] = array('accid' => 'USUT0150', 'name' => 'Magna');
$city_data[] = array('accid' => 'USUT0151', 'name' => 'Manila');
$city_data[] = array('accid' => 'USUT0152', 'name' => 'Manti');
$city_data[] = array('accid' => 'USUT0153', 'name' => 'Mantua');
$city_data[] = array('accid' => 'USUT0154', 'name' => 'Mapleton');
$city_data[] = array('accid' => 'USUT0155', 'name' => 'Marysvale');
$city_data[] = array('accid' => 'USUT0156', 'name' => 'Mayfield');
$city_data[] = array('accid' => 'USUT0157', 'name' => 'Meadow');
$city_data[] = array('accid' => 'USUT0158', 'name' => 'Mendon');
$city_data[] = array('accid' => 'USUT0159', 'name' => 'Mexican Hat');
$city_data[] = array('accid' => 'USUT0160', 'name' => 'Midvale');
$city_data[] = array('accid' => 'USUT0161', 'name' => 'Midway');
$city_data[] = array('accid' => 'USUT0162', 'name' => 'Milford');
$city_data[] = array('accid' => 'USUT0163', 'name' => 'Millville');
$city_data[] = array('accid' => 'USUT0164', 'name' => 'Minersville');
$city_data[] = array('accid' => 'USUT0165', 'name' => 'Moab');
$city_data[] = array('accid' => 'USUT0166', 'name' => 'Modena');
$city_data[] = array('accid' => 'USUT0167', 'name' => 'Mona');
$city_data[] = array('accid' => 'USUT0168', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USUT0169', 'name' => 'Montezuma Creek');
$city_data[] = array('accid' => 'USUT0170', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USUT0171', 'name' => 'Monument Valley');
$city_data[] = array('accid' => 'USUT0172', 'name' => 'Morgan');
$city_data[] = array('accid' => 'USUT0173', 'name' => 'Moroni');
$city_data[] = array('accid' => 'USUT0174', 'name' => 'Mount Carmel');
$city_data[] = array('accid' => 'USUT0175', 'name' => 'Mount Pleasant');
$city_data[] = array('accid' => 'USUT0176', 'name' => 'Mountain Home');
$city_data[] = array('accid' => 'USUT0177', 'name' => 'Myton');
$city_data[] = array('accid' => 'USUT0178', 'name' => 'Neola');
$city_data[] = array('accid' => 'USUT0179', 'name' => 'Nephi');
$city_data[] = array('accid' => 'USUT0180', 'name' => 'New Harmony');
$city_data[] = array('accid' => 'USUT0181', 'name' => 'Newcastle');
$city_data[] = array('accid' => 'USUT0182', 'name' => 'Newton');
$city_data[] = array('accid' => 'USUT0183', 'name' => 'North Salt Lake');
$city_data[] = array('accid' => 'USUT0184', 'name' => 'Oak City');
$city_data[] = array('accid' => 'USUT0185', 'name' => 'Oakley');
$city_data[] = array('accid' => 'USUT0186', 'name' => 'Oasis');
$city_data[] = array('accid' => 'USUT0187', 'name' => 'Ogden');
$city_data[] = array('accid' => 'USUT0189', 'name' => 'Orangeville');
$city_data[] = array('accid' => 'USUT0190', 'name' => 'Orderville');
$city_data[] = array('accid' => 'USUT0191', 'name' => 'Orem');
$city_data[] = array('accid' => 'USUT0192', 'name' => 'Panguitch');
$city_data[] = array('accid' => 'USUT0193', 'name' => 'Paradise');
$city_data[] = array('accid' => 'USUT0194', 'name' => 'Paragonah');
$city_data[] = array('accid' => 'USUT0195', 'name' => 'Park City');
$city_data[] = array('accid' => 'USUT0197', 'name' => 'Park Valley');
$city_data[] = array('accid' => 'USUT0198', 'name' => 'Parowan');
$city_data[] = array('accid' => 'USUT0199', 'name' => 'Payson');
$city_data[] = array('accid' => 'USUT0200', 'name' => 'Peoa');
$city_data[] = array('accid' => 'USUT0201', 'name' => 'Pine Valley');
$city_data[] = array('accid' => 'USUT0202', 'name' => 'Pleasant Grove');
$city_data[] = array('accid' => 'USUT0203', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USUT0204', 'name' => 'Portage');
$city_data[] = array('accid' => 'USUT0206', 'name' => 'Price');
$city_data[] = array('accid' => 'USUT0207', 'name' => 'Providence');
$city_data[] = array('accid' => 'USUT0208', 'name' => 'Provo');
$city_data[] = array('accid' => 'USUT0209', 'name' => 'Randlett');
$city_data[] = array('accid' => 'USUT0210', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USUT0212', 'name' => 'Redmond');
$city_data[] = array('accid' => 'USUT0213', 'name' => 'Richfield');
$city_data[] = array('accid' => 'USUT0214', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USUT0215', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USUT0216', 'name' => 'Riverton');
$city_data[] = array('accid' => 'USUT0218', 'name' => 'Rockville');
$city_data[] = array('accid' => 'USUT0219', 'name' => 'Roosevelt');
$city_data[] = array('accid' => 'USUT0220', 'name' => 'Roy');
$city_data[] = array('accid' => 'USUT0221', 'name' => 'Rush Valley');
$city_data[] = array('accid' => 'USUT0222', 'name' => 'Saint George');
$city_data[] = array('accid' => 'USUT0223', 'name' => 'Salem');
$city_data[] = array('accid' => 'USUT0224', 'name' => 'Salina');
$city_data[] = array('accid' => 'USUT0225', 'name' => 'Salt Lake City');
$city_data[] = array('accid' => 'USUT0226', 'name' => 'Sandy');
$city_data[] = array('accid' => 'USUT0227', 'name' => 'Santa Clara');
$city_data[] = array('accid' => 'USUT0228', 'name' => 'Santaquin');
$city_data[] = array('accid' => 'USUT0229', 'name' => 'Scipio');
$city_data[] = array('accid' => 'USUT0231', 'name' => 'Sevier');
$city_data[] = array('accid' => 'USUT0232', 'name' => 'Sigurd');
$city_data[] = array('accid' => 'USUT0233', 'name' => 'Smithfield');
$city_data[] = array('accid' => 'USUT0236', 'name' => 'Snowville');
$city_data[] = array('accid' => 'USUT0238', 'name' => 'South Jordan');
$city_data[] = array('accid' => 'USUT0239', 'name' => 'Spanish Fork');
$city_data[] = array('accid' => 'USUT0240', 'name' => 'Spring City');
$city_data[] = array('accid' => 'USUT0241', 'name' => 'Springdale');
$city_data[] = array('accid' => 'USUT0242', 'name' => 'Springville');
$city_data[] = array('accid' => 'USUT0243', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USUT0244', 'name' => 'Stockton');
$city_data[] = array('accid' => 'USUT0245', 'name' => 'Summit');
$city_data[] = array('accid' => 'USUT0247', 'name' => 'Sunnyside');
$city_data[] = array('accid' => 'USUT0248', 'name' => 'Syracuse');
$city_data[] = array('accid' => 'USUT0249', 'name' => 'Tabiona');
$city_data[] = array('accid' => 'USUT0250', 'name' => 'Talmage');
$city_data[] = array('accid' => 'USUT0251', 'name' => 'Teasdale');
$city_data[] = array('accid' => 'USUT0253', 'name' => 'Thompson');
$city_data[] = array('accid' => 'USUT0254', 'name' => 'Tooele');
$city_data[] = array('accid' => 'USUT0255', 'name' => 'Toquerville');
$city_data[] = array('accid' => 'USUT0256', 'name' => 'Torrey');
$city_data[] = array('accid' => 'USUT0257', 'name' => 'Tremonton');
$city_data[] = array('accid' => 'USUT0258', 'name' => 'Trenton');
$city_data[] = array('accid' => 'USUT0259', 'name' => 'Tridell');
$city_data[] = array('accid' => 'USUT0260', 'name' => 'Tropic');
$city_data[] = array('accid' => 'USUT0261', 'name' => 'Vernal');
$city_data[] = array('accid' => 'USUT0262', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USUT0263', 'name' => 'Veyo');
$city_data[] = array('accid' => 'USUT0264', 'name' => 'Virgin');
$city_data[] = array('accid' => 'USUT0265', 'name' => 'Wales');
$city_data[] = array('accid' => 'USUT0266', 'name' => 'Wallsburg');
$city_data[] = array('accid' => 'USUT0267', 'name' => 'Washington');
$city_data[] = array('accid' => 'USUT0268', 'name' => 'Wellington');
$city_data[] = array('accid' => 'USUT0269', 'name' => 'Wellsville');
$city_data[] = array('accid' => 'USUT0270', 'name' => 'Wendover');
$city_data[] = array('accid' => 'USUT0271', 'name' => 'West Jordan');
$city_data[] = array('accid' => 'USUT0272', 'name' => 'Whiterocks');
$city_data[] = array('accid' => 'USUT0273', 'name' => 'Willard');
$city_data[] = array('accid' => 'USUT0274', 'name' => 'Woodruff');
$city_data[] = array('accid' => 'USUT0275', 'name' => 'Woods Cross');

?>
