<?php

// City package for USA: Virginia 

$city_name = 'USA: Virginia';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USVA0001', 'name' => 'Abingdon');
$city_data[] = array('accid' => 'USVA0002', 'name' => 'Accomac');
$city_data[] = array('accid' => 'USVA0003', 'name' => 'Achilles');
$city_data[] = array('accid' => 'USVA0004', 'name' => 'Afton');
$city_data[] = array('accid' => 'USVA0005', 'name' => 'Alberta');
$city_data[] = array('accid' => 'USVA0006', 'name' => 'Aldie');
$city_data[] = array('accid' => 'USVA0007', 'name' => 'Alexandria');
$city_data[] = array('accid' => 'USVA0008', 'name' => 'Altavista');
$city_data[] = array('accid' => 'USVA0009', 'name' => 'Alton');
$city_data[] = array('accid' => 'USVA0010', 'name' => 'Amelia Court House');
$city_data[] = array('accid' => 'USVA0011', 'name' => 'Amherst');
$city_data[] = array('accid' => 'USVA0012', 'name' => 'Amissville');
$city_data[] = array('accid' => 'USVA0013', 'name' => 'Ammon');
$city_data[] = array('accid' => 'USVA0014', 'name' => 'Amonate');
$city_data[] = array('accid' => 'USVA0015', 'name' => 'Andersonville');
$city_data[] = array('accid' => 'USVA0016', 'name' => 'Andover');
$city_data[] = array('accid' => 'USVA0017', 'name' => 'Annandale');
$city_data[] = array('accid' => 'USVA0018', 'name' => 'Appalachia');
$city_data[] = array('accid' => 'USVA0019', 'name' => 'Appomattox');
$city_data[] = array('accid' => 'USVA0020', 'name' => 'Ararat');
$city_data[] = array('accid' => 'USVA0021', 'name' => 'Arcola');
$city_data[] = array('accid' => 'USVA0022', 'name' => 'Ark');
$city_data[] = array('accid' => 'USVA0023', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USVA0024', 'name' => 'Aroda');
$city_data[] = array('accid' => 'USVA0025', 'name' => 'Arrington');
$city_data[] = array('accid' => 'USVA0026', 'name' => 'Arvonia');
$city_data[] = array('accid' => 'USVA0027', 'name' => 'Ashburn');
$city_data[] = array('accid' => 'USVA0028', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USVA0029', 'name' => 'Assawoman');
$city_data[] = array('accid' => 'USVA0030', 'name' => 'Atkins');
$city_data[] = array('accid' => 'USVA0031', 'name' => 'Atlantic');
$city_data[] = array('accid' => 'USVA0032', 'name' => 'Augusta Springs');
$city_data[] = array('accid' => 'USVA0033', 'name' => 'Austinville');
$city_data[] = array('accid' => 'USVA0034', 'name' => 'Axton');
$city_data[] = array('accid' => 'USVA0035', 'name' => 'Aylett');
$city_data[] = array('accid' => 'USVA0036', 'name' => 'Bacova');
$city_data[] = array('accid' => 'USVA0037', 'name' => 'Banco');
$city_data[] = array('accid' => 'USVA0038', 'name' => 'Bandy');
$city_data[] = array('accid' => 'USVA0039', 'name' => 'Barboursville');
$city_data[] = array('accid' => 'USVA0040', 'name' => 'Barhamsville');
$city_data[] = array('accid' => 'USVA0041', 'name' => 'Barren Springs');
$city_data[] = array('accid' => 'USVA0042', 'name' => 'Baskerville');
$city_data[] = array('accid' => 'USVA0043', 'name' => 'Bassett');
$city_data[] = array('accid' => 'USVA0044', 'name' => 'Bastian');
$city_data[] = array('accid' => 'USVA0045', 'name' => 'Basye');
$city_data[] = array('accid' => 'USVA0046', 'name' => 'Batesville');
$city_data[] = array('accid' => 'USVA0047', 'name' => 'Battery Park');
$city_data[] = array('accid' => 'USVA0048', 'name' => 'Bealeton');
$city_data[] = array('accid' => 'USVA0049', 'name' => 'Beaumont');
$city_data[] = array('accid' => 'USVA0050', 'name' => 'Beaverdam');
$city_data[] = array('accid' => 'USVA0051', 'name' => 'Bedford');
$city_data[] = array('accid' => 'USVA0052', 'name' => 'Bee');
$city_data[] = array('accid' => 'USVA0053', 'name' => 'Bellamy');
$city_data[] = array('accid' => 'USVA0054', 'name' => 'Belle Haven');
$city_data[] = array('accid' => 'USVA0055', 'name' => 'Belspring');
$city_data[] = array('accid' => 'USVA0056', 'name' => 'Ben Hur');
$city_data[] = array('accid' => 'USVA0057', 'name' => 'Bena');
$city_data[] = array('accid' => 'USVA0058', 'name' => 'Bent Mountain');
$city_data[] = array('accid' => 'USVA0059', 'name' => 'Bentonville');
$city_data[] = array('accid' => 'USVA0060', 'name' => 'Bergton');
$city_data[] = array('accid' => 'USVA0061', 'name' => 'Berryville');
$city_data[] = array('accid' => 'USVA0062', 'name' => 'Big Island');
$city_data[] = array('accid' => 'USVA0063', 'name' => 'Big Rock');
$city_data[] = array('accid' => 'USVA0064', 'name' => 'Big Stone Gap');
$city_data[] = array('accid' => 'USVA0065', 'name' => 'Birchleaf');
$city_data[] = array('accid' => 'USVA0066', 'name' => 'Birdsnest');
$city_data[] = array('accid' => 'USVA0067', 'name' => 'Bishop');
$city_data[] = array('accid' => 'USVA0068', 'name' => 'Blacksburg');
$city_data[] = array('accid' => 'USVA0069', 'name' => 'Blackstone');
$city_data[] = array('accid' => 'USVA0070', 'name' => 'Blackwater');
$city_data[] = array('accid' => 'USVA0071', 'name' => 'Blairs');
$city_data[] = array('accid' => 'USVA0072', 'name' => 'Bland');
$city_data[] = array('accid' => 'USVA0073', 'name' => 'Bloxom');
$city_data[] = array('accid' => 'USVA0074', 'name' => 'Blue Grass');
$city_data[] = array('accid' => 'USVA0075', 'name' => 'Blue Ridge');
$city_data[] = array('accid' => 'USVA0076', 'name' => 'Bluefield');
$city_data[] = array('accid' => 'USVA0077', 'name' => 'Bluemont');
$city_data[] = array('accid' => 'USVA0078', 'name' => 'Bohannon');
$city_data[] = array('accid' => 'USVA0079', 'name' => 'Boissevain');
$city_data[] = array('accid' => 'USVA0080', 'name' => 'Boones Mill');
$city_data[] = array('accid' => 'USVA0081', 'name' => 'Boston');
$city_data[] = array('accid' => 'USVA0082', 'name' => 'Bowling Green');
$city_data[] = array('accid' => 'USVA0083', 'name' => 'Boyce');
$city_data[] = array('accid' => 'USVA0084', 'name' => 'Boydton');
$city_data[] = array('accid' => 'USVA0085', 'name' => 'Boykins');
$city_data[] = array('accid' => 'USVA0086', 'name' => 'Bracey');
$city_data[] = array('accid' => 'USVA0087', 'name' => 'Branchville');
$city_data[] = array('accid' => 'USVA0088', 'name' => 'Brandy Station');
$city_data[] = array('accid' => 'USVA0089', 'name' => 'Breaks');
$city_data[] = array('accid' => 'USVA0090', 'name' => 'Bremo Bluff');
$city_data[] = array('accid' => 'USVA0091', 'name' => 'Bridgewater');
$city_data[] = array('accid' => 'USVA0092', 'name' => 'Brightwood');
$city_data[] = array('accid' => 'USVA0093', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USVA0094', 'name' => 'Bristow');
$city_data[] = array('accid' => 'USVA0095', 'name' => 'Broad Run');
$city_data[] = array('accid' => 'USVA0096', 'name' => 'Broadford');
$city_data[] = array('accid' => 'USVA0097', 'name' => 'Broadway');
$city_data[] = array('accid' => 'USVA0098', 'name' => 'Brodnax');
$city_data[] = array('accid' => 'USVA0099', 'name' => 'Brooke');
$city_data[] = array('accid' => 'USVA0100', 'name' => 'Brookneal');
$city_data[] = array('accid' => 'USVA0101', 'name' => 'Brownsburg');
$city_data[] = array('accid' => 'USVA0102', 'name' => 'Brucetown');
$city_data[] = array('accid' => 'USVA0103', 'name' => 'Bruington');
$city_data[] = array('accid' => 'USVA0104', 'name' => 'Buchanan');
$city_data[] = array('accid' => 'USVA0105', 'name' => 'Buckingham');
$city_data[] = array('accid' => 'USVA0106', 'name' => 'Buena Vista');
$city_data[] = array('accid' => 'USVA0107', 'name' => 'Buffalo Junction');
$city_data[] = array('accid' => 'USVA0108', 'name' => 'Bumpass');
$city_data[] = array('accid' => 'USVA0109', 'name' => 'Burgess');
$city_data[] = array('accid' => 'USVA0110', 'name' => 'Burke');
$city_data[] = array('accid' => 'USVA0111', 'name' => 'Burkes Garden');
$city_data[] = array('accid' => 'USVA0112', 'name' => 'Burkeville');
$city_data[] = array('accid' => 'USVA0113', 'name' => 'Burr Hill');
$city_data[] = array('accid' => 'USVA0114', 'name' => 'Callands');
$city_data[] = array('accid' => 'USVA0115', 'name' => 'Callao');
$city_data[] = array('accid' => 'USVA0116', 'name' => 'Callaway');
$city_data[] = array('accid' => 'USVA0117', 'name' => 'Calverton');
$city_data[] = array('accid' => 'USVA0118', 'name' => 'Cana');
$city_data[] = array('accid' => 'USVA0119', 'name' => 'Cape Charles');
$city_data[] = array('accid' => 'USVA0120', 'name' => 'Capeville');
$city_data[] = array('accid' => 'USVA0121', 'name' => 'Capron');
$city_data[] = array('accid' => 'USVA0122', 'name' => 'Cardinal');
$city_data[] = array('accid' => 'USVA0123', 'name' => 'Caret');
$city_data[] = array('accid' => 'USVA0124', 'name' => 'Carrollton');
$city_data[] = array('accid' => 'USVA0125', 'name' => 'Carrsville');
$city_data[] = array('accid' => 'USVA0126', 'name' => 'Carson');
$city_data[] = array('accid' => 'USVA0127', 'name' => 'Cartersville');
$city_data[] = array('accid' => 'USVA0128', 'name' => 'Casanova');
$city_data[] = array('accid' => 'USVA0129', 'name' => 'Cascade');
$city_data[] = array('accid' => 'USVA0130', 'name' => 'Castleton');
$city_data[] = array('accid' => 'USVA0131', 'name' => 'Castlewood');
$city_data[] = array('accid' => 'USVA0132', 'name' => 'Catawba');
$city_data[] = array('accid' => 'USVA0133', 'name' => 'Catharpin');
$city_data[] = array('accid' => 'USVA0134', 'name' => 'Catlett');
$city_data[] = array('accid' => 'USVA0135', 'name' => 'Cedar Bluff');
$city_data[] = array('accid' => 'USVA0136', 'name' => 'Center Cross');
$city_data[] = array('accid' => 'USVA0137', 'name' => 'Centreville');
$city_data[] = array('accid' => 'USVA0138', 'name' => 'Ceres');
$city_data[] = array('accid' => 'USVA0139', 'name' => 'Champlain');
$city_data[] = array('accid' => 'USVA0140', 'name' => 'Chantilly');
$city_data[] = array('accid' => 'USVA0141', 'name' => 'Charles City');
$city_data[] = array('accid' => 'USVA0142', 'name' => 'Charlotte Court House');
$city_data[] = array('accid' => 'USVA0143', 'name' => 'Charlottesville');
$city_data[] = array('accid' => 'USVA0144', 'name' => 'Chase City');
$city_data[] = array('accid' => 'USVA0145', 'name' => 'Chatham');
$city_data[] = array('accid' => 'USVA0146', 'name' => 'Check');
$city_data[] = array('accid' => 'USVA0147', 'name' => 'Cheriton');
$city_data[] = array('accid' => 'USVA0148', 'name' => 'Chesapeake');
$city_data[] = array('accid' => 'USVA0149', 'name' => 'Chester');
$city_data[] = array('accid' => 'USVA0150', 'name' => 'Chester Gap');
$city_data[] = array('accid' => 'USVA0151', 'name' => 'Chesterfield');
$city_data[] = array('accid' => 'USVA0152', 'name' => 'Chilhowie');
$city_data[] = array('accid' => 'USVA0153', 'name' => 'Chincoteague Island');
$city_data[] = array('accid' => 'USVA0154', 'name' => 'Christchurch');
$city_data[] = array('accid' => 'USVA0155', 'name' => 'Christiansburg');
$city_data[] = array('accid' => 'USVA0156', 'name' => 'Church Road');
$city_data[] = array('accid' => 'USVA0157', 'name' => 'Church View');
$city_data[] = array('accid' => 'USVA0158', 'name' => 'Churchville');
$city_data[] = array('accid' => 'USVA0159', 'name' => 'Claremont');
$city_data[] = array('accid' => 'USVA0160', 'name' => 'Clarksville');
$city_data[] = array('accid' => 'USVA0161', 'name' => 'Claudville');
$city_data[] = array('accid' => 'USVA0162', 'name' => 'Clear Brook');
$city_data[] = array('accid' => 'USVA0163', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USVA0164', 'name' => 'Clifford');
$city_data[] = array('accid' => 'USVA0165', 'name' => 'Clifton');
$city_data[] = array('accid' => 'USVA0166', 'name' => 'Clifton Forge');
$city_data[] = array('accid' => 'USVA0167', 'name' => 'Clinchco');
$city_data[] = array('accid' => 'USVA0168', 'name' => 'Clintwood');
$city_data[] = array('accid' => 'USVA0169', 'name' => 'Clover');
$city_data[] = array('accid' => 'USVA0170', 'name' => 'Cloverdale');
$city_data[] = array('accid' => 'USVA0171', 'name' => 'Cluster Springs');
$city_data[] = array('accid' => 'USVA0172', 'name' => 'Cobbs Creek');
$city_data[] = array('accid' => 'USVA0173', 'name' => 'Cobham');
$city_data[] = array('accid' => 'USVA0174', 'name' => 'Coeburn');
$city_data[] = array('accid' => 'USVA0175', 'name' => 'Coleman Falls');
$city_data[] = array('accid' => 'USVA0176', 'name' => 'Coles Point');
$city_data[] = array('accid' => 'USVA0177', 'name' => 'Collinsville');
$city_data[] = array('accid' => 'USVA0178', 'name' => 'Colonial Beach');
$city_data[] = array('accid' => 'USVA0179', 'name' => 'Colonial Heights');
$city_data[] = array('accid' => 'USVA0180', 'name' => 'Columbia');
$city_data[] = array('accid' => 'USVA0181', 'name' => 'Concord');
$city_data[] = array('accid' => 'USVA0182', 'name' => 'Copper Hill');
$city_data[] = array('accid' => 'USVA0183', 'name' => 'Corbin');
$city_data[] = array('accid' => 'USVA0184', 'name' => 'Courtland');
$city_data[] = array('accid' => 'USVA0185', 'name' => 'Covesville');
$city_data[] = array('accid' => 'USVA0186', 'name' => 'Covington');
$city_data[] = array('accid' => 'USVA0187', 'name' => 'Craddockville');
$city_data[] = array('accid' => 'USVA0188', 'name' => 'Craigsville');
$city_data[] = array('accid' => 'USVA0189', 'name' => 'Crewe');
$city_data[] = array('accid' => 'USVA0190', 'name' => 'Criders');
$city_data[] = array('accid' => 'USVA0191', 'name' => 'Crimora');
$city_data[] = array('accid' => 'USVA0192', 'name' => 'Cripple Creek');
$city_data[] = array('accid' => 'USVA0193', 'name' => 'Critz');
$city_data[] = array('accid' => 'USVA0194', 'name' => 'Crockett');
$city_data[] = array('accid' => 'USVA0195', 'name' => 'Cross Junction');
$city_data[] = array('accid' => 'USVA0196', 'name' => 'Crozet');
$city_data[] = array('accid' => 'USVA0197', 'name' => 'Crozier');
$city_data[] = array('accid' => 'USVA0198', 'name' => 'Crystal Hill');
$city_data[] = array('accid' => 'USVA0199', 'name' => 'Cullen');
$city_data[] = array('accid' => 'USVA0200', 'name' => 'Culpeper');
$city_data[] = array('accid' => 'USVA0201', 'name' => 'Cumberland');
$city_data[] = array('accid' => 'USVA0202', 'name' => 'Dahlgren');
$city_data[] = array('accid' => 'USVA0203', 'name' => 'Daleville');
$city_data[] = array('accid' => 'USVA0204', 'name' => 'Damascus');
$city_data[] = array('accid' => 'USVA0205', 'name' => 'Dante');
$city_data[] = array('accid' => 'USVA0206', 'name' => 'Danville');
$city_data[] = array('accid' => 'USVA0207', 'name' => 'Davenport');
$city_data[] = array('accid' => 'USVA0208', 'name' => 'Davis Wharf');
$city_data[] = array('accid' => 'USVA0209', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USVA0210', 'name' => 'Deerfield');
$city_data[] = array('accid' => 'USVA0211', 'name' => 'Delaplane');
$city_data[] = array('accid' => 'USVA0212', 'name' => 'Deltaville');
$city_data[] = array('accid' => 'USVA0213', 'name' => 'Dendron');
$city_data[] = array('accid' => 'USVA0214', 'name' => 'Dewitt');
$city_data[] = array('accid' => 'USVA0215', 'name' => 'Diggs');
$city_data[] = array('accid' => 'USVA0216', 'name' => 'Dillwyn');
$city_data[] = array('accid' => 'USVA0217', 'name' => 'Dinwiddie');
$city_data[] = array('accid' => 'USVA0218', 'name' => 'Disputanta');
$city_data[] = array('accid' => 'USVA0219', 'name' => 'Doe Hill');
$city_data[] = array('accid' => 'USVA0220', 'name' => 'Dogue');
$city_data[] = array('accid' => 'USVA0221', 'name' => 'Dolphin');
$city_data[] = array('accid' => 'USVA0222', 'name' => 'Doran');
$city_data[] = array('accid' => 'USVA0223', 'name' => 'Doswell');
$city_data[] = array('accid' => 'USVA0224', 'name' => 'Drakes Branch');
$city_data[] = array('accid' => 'USVA0225', 'name' => 'Draper');
$city_data[] = array('accid' => 'USVA0226', 'name' => 'Drewryville');
$city_data[] = array('accid' => 'USVA0227', 'name' => 'Dry Fork');
$city_data[] = array('accid' => 'USVA0228', 'name' => 'Dryden');
$city_data[] = array('accid' => 'USVA0229', 'name' => 'Dublin');
$city_data[] = array('accid' => 'USVA0230', 'name' => 'Duffield');
$city_data[] = array('accid' => 'USVA0231', 'name' => 'Dugspur');
$city_data[] = array('accid' => 'USVA0232', 'name' => 'Dulles');
$city_data[] = array('accid' => 'USVA0233', 'name' => 'Dumfries');
$city_data[] = array('accid' => 'USVA0234', 'name' => 'Dundas');
$city_data[] = array('accid' => 'USVA0235', 'name' => 'Dungannon');
$city_data[] = array('accid' => 'USVA0236', 'name' => 'Dunn Loring');
$city_data[] = array('accid' => 'USVA0237', 'name' => 'Dunnsville');
$city_data[] = array('accid' => 'USVA0238', 'name' => 'Dutton');
$city_data[] = array('accid' => 'USVA0239', 'name' => 'Dyke');
$city_data[] = array('accid' => 'USVA0240', 'name' => 'Eagle Rock');
$city_data[] = array('accid' => 'USVA0241', 'name' => 'Earlysville');
$city_data[] = array('accid' => 'USVA0242', 'name' => 'East Stone Gap');
$city_data[] = array('accid' => 'USVA0243', 'name' => 'Eastville');
$city_data[] = array('accid' => 'USVA0244', 'name' => 'Ebony');
$city_data[] = array('accid' => 'USVA0245', 'name' => 'Edinburg');
$city_data[] = array('accid' => 'USVA0246', 'name' => 'Edwardsville');
$city_data[] = array('accid' => 'USVA0247', 'name' => 'Eggleston');
$city_data[] = array('accid' => 'USVA0248', 'name' => 'Elberon');
$city_data[] = array('accid' => 'USVA0249', 'name' => 'Elk Creek');
$city_data[] = array('accid' => 'USVA0250', 'name' => 'Elkton');
$city_data[] = array('accid' => 'USVA0251', 'name' => 'Elkwood');
$city_data[] = array('accid' => 'USVA0252', 'name' => 'Elliston');
$city_data[] = array('accid' => 'USVA0253', 'name' => 'Emory');
$city_data[] = array('accid' => 'USVA0254', 'name' => 'Emporia');
$city_data[] = array('accid' => 'USVA0255', 'name' => 'Esmont');
$city_data[] = array('accid' => 'USVA0256', 'name' => 'Etlan');
$city_data[] = array('accid' => 'USVA0257', 'name' => 'Evergreen');
$city_data[] = array('accid' => 'USVA0258', 'name' => 'Evington');
$city_data[] = array('accid' => 'USVA0259', 'name' => 'Ewing');
$city_data[] = array('accid' => 'USVA0260', 'name' => 'Exmore');
$city_data[] = array('accid' => 'USVA0261', 'name' => 'Faber');
$city_data[] = array('accid' => 'USVA0262', 'name' => 'Fairfax');
$city_data[] = array('accid' => 'USVA0263', 'name' => 'Fairfax Station');
$city_data[] = array('accid' => 'USVA0264', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USVA0265', 'name' => 'Falls Church');
$city_data[] = array('accid' => 'USVA0266', 'name' => 'Falls Mills');
$city_data[] = array('accid' => 'USVA0267', 'name' => 'Fancy Gap');
$city_data[] = array('accid' => 'USVA0268', 'name' => 'Farmville');
$city_data[] = array('accid' => 'USVA0269', 'name' => 'Farnham');
$city_data[] = array('accid' => 'USVA0270', 'name' => 'Ferrum');
$city_data[] = array('accid' => 'USVA0271', 'name' => 'Fieldale');
$city_data[] = array('accid' => 'USVA0272', 'name' => 'Fife');
$city_data[] = array('accid' => 'USVA0273', 'name' => 'Fincastle');
$city_data[] = array('accid' => 'USVA0274', 'name' => 'Fishers Hill');
$city_data[] = array('accid' => 'USVA0275', 'name' => 'Fishersville');
$city_data[] = array('accid' => 'USVA0276', 'name' => 'Flint Hill');
$city_data[] = array('accid' => 'USVA0277', 'name' => 'Floyd');
$city_data[] = array('accid' => 'USVA0278', 'name' => 'Foneswood');
$city_data[] = array('accid' => 'USVA0279', 'name' => 'Ford');
$city_data[] = array('accid' => 'USVA0280', 'name' => 'Forest');
$city_data[] = array('accid' => 'USVA0281', 'name' => 'Fork Union');
$city_data[] = array('accid' => 'USVA0282', 'name' => 'Fort Belvoir');
$city_data[] = array('accid' => 'USVA0283', 'name' => 'Fort Blackmore');
$city_data[] = array('accid' => 'USVA0284', 'name' => 'Fort Defiance');
$city_data[] = array('accid' => 'USVA0285', 'name' => 'Fort Eustis');
$city_data[] = array('accid' => 'USVA0286', 'name' => 'Fort Lee');
$city_data[] = array('accid' => 'USVA0287', 'name' => 'Fort Mitchell');
$city_data[] = array('accid' => 'USVA0288', 'name' => 'Fort Monroe');
$city_data[] = array('accid' => 'USVA0289', 'name' => 'Fort Myer');
$city_data[] = array('accid' => 'USVA0290', 'name' => 'Fort Valley');
$city_data[] = array('accid' => 'USVA0291', 'name' => 'Foster');
$city_data[] = array('accid' => 'USVA0292', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USVA0293', 'name' => 'Franktown');
$city_data[] = array('accid' => 'USVA0294', 'name' => 'Fredericksburg');
$city_data[] = array('accid' => 'USVA0295', 'name' => 'Free Union');
$city_data[] = array('accid' => 'USVA0296', 'name' => 'Freeman');
$city_data[] = array('accid' => 'USVA0297', 'name' => 'Fries');
$city_data[] = array('accid' => 'USVA0298', 'name' => 'Front Royal');
$city_data[] = array('accid' => 'USVA0299', 'name' => 'Fulks Run');
$city_data[] = array('accid' => 'USVA0300', 'name' => 'Gainesville');
$city_data[] = array('accid' => 'USVA0301', 'name' => 'Galax');
$city_data[] = array('accid' => 'USVA0302', 'name' => 'Garrisonville');
$city_data[] = array('accid' => 'USVA0303', 'name' => 'Gasburg');
$city_data[] = array('accid' => 'USVA0304', 'name' => 'Gate City');
$city_data[] = array('accid' => 'USVA0305', 'name' => 'Glade Spring');
$city_data[] = array('accid' => 'USVA0306', 'name' => 'Gladehill');
$city_data[] = array('accid' => 'USVA0307', 'name' => 'Gladstone');
$city_data[] = array('accid' => 'USVA0308', 'name' => 'Gladys');
$city_data[] = array('accid' => 'USVA0309', 'name' => 'Glasgow');
$city_data[] = array('accid' => 'USVA0310', 'name' => 'Glen Allen');
$city_data[] = array('accid' => 'USVA0311', 'name' => 'Glen Lyn');
$city_data[] = array('accid' => 'USVA0312', 'name' => 'Glen Wilton');
$city_data[] = array('accid' => 'USVA0313', 'name' => 'Gloucester');
$city_data[] = array('accid' => 'USVA0314', 'name' => 'Gloucester Point');
$city_data[] = array('accid' => 'USVA0315', 'name' => 'Goldbond');
$city_data[] = array('accid' => 'USVA0316', 'name' => 'Goldvein');
$city_data[] = array('accid' => 'USVA0317', 'name' => 'Goochland');
$city_data[] = array('accid' => 'USVA0318', 'name' => 'Goode');
$city_data[] = array('accid' => 'USVA0319', 'name' => 'Goodview');
$city_data[] = array('accid' => 'USVA0320', 'name' => 'Gordonsville');
$city_data[] = array('accid' => 'USVA0321', 'name' => 'Gore');
$city_data[] = array('accid' => 'USVA0322', 'name' => 'Goshen');
$city_data[] = array('accid' => 'USVA0323', 'name' => 'Graves Mill');
$city_data[] = array('accid' => 'USVA0324', 'name' => 'Great Falls');
$city_data[] = array('accid' => 'USVA0325', 'name' => 'Green Bay');
$city_data[] = array('accid' => 'USVA0326', 'name' => 'Greenbackville');
$city_data[] = array('accid' => 'USVA0327', 'name' => 'Greenbush');
$city_data[] = array('accid' => 'USVA0328', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USVA0329', 'name' => 'Greenway');
$city_data[] = array('accid' => 'USVA0330', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USVA0331', 'name' => 'Gretna');
$city_data[] = array('accid' => 'USVA0332', 'name' => 'Grimstead');
$city_data[] = array('accid' => 'USVA0333', 'name' => 'Grottoes');
$city_data[] = array('accid' => 'USVA0334', 'name' => 'Grundy');
$city_data[] = array('accid' => 'USVA0335', 'name' => 'Gum Spring');
$city_data[] = array('accid' => 'USVA0336', 'name' => 'Gwynn');
$city_data[] = array('accid' => 'USVA0337', 'name' => 'Hacksneck');
$city_data[] = array('accid' => 'USVA0338', 'name' => 'Hadensville');
$city_data[] = array('accid' => 'USVA0339', 'name' => 'Hague');
$city_data[] = array('accid' => 'USVA0340', 'name' => 'Halifax');
$city_data[] = array('accid' => 'USVA0341', 'name' => 'Hallieford');
$city_data[] = array('accid' => 'USVA0342', 'name' => 'Hallwood');
$city_data[] = array('accid' => 'USVA0343', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USVA0344', 'name' => 'Hampden Sydney');
$city_data[] = array('accid' => 'USVA0345', 'name' => 'Hampton');
$city_data[] = array('accid' => 'USVA0346', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USVA0347', 'name' => 'Harborton');
$city_data[] = array('accid' => 'USVA0348', 'name' => 'Hardy');
$city_data[] = array('accid' => 'USVA0349', 'name' => 'Hardyville');
$city_data[] = array('accid' => 'USVA0350', 'name' => 'Harman');
$city_data[] = array('accid' => 'USVA0351', 'name' => 'Harrisonburg');
$city_data[] = array('accid' => 'USVA0352', 'name' => 'Hartfield');
$city_data[] = array('accid' => 'USVA0353', 'name' => 'Hartwood');
$city_data[] = array('accid' => 'USVA0354', 'name' => 'Hayes');
$city_data[] = array('accid' => 'USVA0355', 'name' => 'Haymarket');
$city_data[] = array('accid' => 'USVA0356', 'name' => 'Haynesville');
$city_data[] = array('accid' => 'USVA0357', 'name' => 'Haysi');
$city_data[] = array('accid' => 'USVA0358', 'name' => 'Haywood');
$city_data[] = array('accid' => 'USVA0359', 'name' => 'Head Waters');
$city_data[] = array('accid' => 'USVA0360', 'name' => 'Heathsville');
$city_data[] = array('accid' => 'USVA0361', 'name' => 'Henry');
$city_data[] = array('accid' => 'USVA0362', 'name' => 'Herndon');
$city_data[] = array('accid' => 'USVA0363', 'name' => 'Highland Springs');
$city_data[] = array('accid' => 'USVA0364', 'name' => 'Hillsville');
$city_data[] = array('accid' => 'USVA0365', 'name' => 'Hiltons');
$city_data[] = array('accid' => 'USVA0366', 'name' => 'Hinton');
$city_data[] = array('accid' => 'USVA0367', 'name' => 'Hiwassee');
$city_data[] = array('accid' => 'USVA0368', 'name' => 'Honaker');
$city_data[] = array('accid' => 'USVA0369', 'name' => 'Hood');
$city_data[] = array('accid' => 'USVA0370', 'name' => 'Hopewell');
$city_data[] = array('accid' => 'USVA0371', 'name' => 'Horntown');
$city_data[] = array('accid' => 'USVA0372', 'name' => 'Horsepen');
$city_data[] = array('accid' => 'USVA0373', 'name' => 'Hot Springs');
$city_data[] = array('accid' => 'USVA0374', 'name' => 'Howardsville');
$city_data[] = array('accid' => 'USVA0375', 'name' => 'Huddleston');
$city_data[] = array('accid' => 'USVA0376', 'name' => 'Hudgins');
$city_data[] = array('accid' => 'USVA0377', 'name' => 'Hume');
$city_data[] = array('accid' => 'USVA0378', 'name' => 'Huntly');
$city_data[] = array('accid' => 'USVA0379', 'name' => 'Hurley');
$city_data[] = array('accid' => 'USVA0380', 'name' => 'Hurt');
$city_data[] = array('accid' => 'USVA0381', 'name' => 'Hustle');
$city_data[] = array('accid' => 'USVA0382', 'name' => 'Independence');
$city_data[] = array('accid' => 'USVA0383', 'name' => 'Indian Valley');
$city_data[] = array('accid' => 'USVA0384', 'name' => 'Iron Gate');
$city_data[] = array('accid' => 'USVA0385', 'name' => 'Irvington');
$city_data[] = array('accid' => 'USVA0386', 'name' => 'Isle Of Wight');
$city_data[] = array('accid' => 'USVA0387', 'name' => 'Ivanhoe');
$city_data[] = array('accid' => 'USVA0388', 'name' => 'Ivor');
$city_data[] = array('accid' => 'USVA0389', 'name' => 'Ivy');
$city_data[] = array('accid' => 'USVA0390', 'name' => 'Jamaica');
$city_data[] = array('accid' => 'USVA0391', 'name' => 'Jamestown');
$city_data[] = array('accid' => 'USVA0392', 'name' => 'Jamesville');
$city_data[] = array('accid' => 'USVA0393', 'name' => 'Jarratt');
$city_data[] = array('accid' => 'USVA0394', 'name' => 'Java');
$city_data[] = array('accid' => 'USVA0395', 'name' => 'Jeffersonton');
$city_data[] = array('accid' => 'USVA0396', 'name' => 'Jenkins Bridge');
$city_data[] = array('accid' => 'USVA0397', 'name' => 'Jersey');
$city_data[] = array('accid' => 'USVA0398', 'name' => 'Jetersville');
$city_data[] = array('accid' => 'USVA0399', 'name' => 'Jewell Ridge');
$city_data[] = array('accid' => 'USVA0400', 'name' => 'Jonesville');
$city_data[] = array('accid' => 'USVA0401', 'name' => 'Keeling');
$city_data[] = array('accid' => 'USVA0402', 'name' => 'Keen Mountain');
$city_data[] = array('accid' => 'USVA0403', 'name' => 'Keene');
$city_data[] = array('accid' => 'USVA0404', 'name' => 'Keezletown');
$city_data[] = array('accid' => 'USVA0405', 'name' => 'Keller');
$city_data[] = array('accid' => 'USVA0406', 'name' => 'Kenbridge');
$city_data[] = array('accid' => 'USVA0407', 'name' => 'Kents Store');
$city_data[] = array('accid' => 'USVA0408', 'name' => 'Keokee');
$city_data[] = array('accid' => 'USVA0409', 'name' => 'Keswick');
$city_data[] = array('accid' => 'USVA0410', 'name' => 'Keysville');
$city_data[] = array('accid' => 'USVA0411', 'name' => 'Kilmarnock');
$city_data[] = array('accid' => 'USVA0412', 'name' => 'King And Queen Court House');
$city_data[] = array('accid' => 'USVA0413', 'name' => 'King George');
$city_data[] = array('accid' => 'USVA0414', 'name' => 'King William');
$city_data[] = array('accid' => 'USVA0415', 'name' => 'Kinsale');
$city_data[] = array('accid' => 'USVA0416', 'name' => 'La Crosse');
$city_data[] = array('accid' => 'USVA0417', 'name' => 'Lacey Spring');
$city_data[] = array('accid' => 'USVA0418', 'name' => 'Lackey');
$city_data[] = array('accid' => 'USVA0419', 'name' => 'Ladysmith');
$city_data[] = array('accid' => 'USVA0420', 'name' => 'Lambsburg');
$city_data[] = array('accid' => 'USVA0421', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USVA0422', 'name' => 'Laneview');
$city_data[] = array('accid' => 'USVA0423', 'name' => 'Lanexa');
$city_data[] = array('accid' => 'USVA0424', 'name' => 'Laurel Fork');
$city_data[] = array('accid' => 'USVA0425', 'name' => 'Lawrenceville');
$city_data[] = array('accid' => 'USVA0426', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USVA0427', 'name' => 'Leesburg');
$city_data[] = array('accid' => 'USVA0428', 'name' => 'Leon');
$city_data[] = array('accid' => 'USVA0429', 'name' => 'Lexington');
$city_data[] = array('accid' => 'USVA0430', 'name' => 'Lightfoot');
$city_data[] = array('accid' => 'USVA0431', 'name' => 'Lignum');
$city_data[] = array('accid' => 'USVA0432', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USVA0433', 'name' => 'Linden');
$city_data[] = array('accid' => 'USVA0434', 'name' => 'Linville');
$city_data[] = array('accid' => 'USVA0435', 'name' => 'Little Plymouth');
$city_data[] = array('accid' => 'USVA0436', 'name' => 'Lively');
$city_data[] = array('accid' => 'USVA0437', 'name' => 'Locust Dale');
$city_data[] = array('accid' => 'USVA0438', 'name' => 'Locust Grove');
$city_data[] = array('accid' => 'USVA0439', 'name' => 'Locust Hill');
$city_data[] = array('accid' => 'USVA0440', 'name' => 'Locustville');
$city_data[] = array('accid' => 'USVA0441', 'name' => 'Long Island');
$city_data[] = array('accid' => 'USVA0442', 'name' => 'Loretto');
$city_data[] = array('accid' => 'USVA0443', 'name' => 'Lorton');
$city_data[] = array('accid' => 'USVA0444', 'name' => 'Lottsburg');
$city_data[] = array('accid' => 'USVA0445', 'name' => 'Louisa');
$city_data[] = array('accid' => 'USVA0446', 'name' => 'Lovettsville');
$city_data[] = array('accid' => 'USVA0447', 'name' => 'Lovingston');
$city_data[] = array('accid' => 'USVA0448', 'name' => 'Low Moor');
$city_data[] = array('accid' => 'USVA0449', 'name' => 'Lowry');
$city_data[] = array('accid' => 'USVA0450', 'name' => 'Lunenburg');
$city_data[] = array('accid' => 'USVA0451', 'name' => 'Luray');
$city_data[] = array('accid' => 'USVA0452', 'name' => 'Lynch Station');
$city_data[] = array('accid' => 'USVA0453', 'name' => 'Lynchburg');
$city_data[] = array('accid' => 'USVA0454', 'name' => 'Lyndhurst');
$city_data[] = array('accid' => 'USVA0455', 'name' => 'Machipongo');
$city_data[] = array('accid' => 'USVA0456', 'name' => 'Macon');
$city_data[] = array('accid' => 'USVA0457', 'name' => 'Madison');
$city_data[] = array('accid' => 'USVA0458', 'name' => 'Madison Heights');
$city_data[] = array('accid' => 'USVA0459', 'name' => 'Madison Mills');
$city_data[] = array('accid' => 'USVA0460', 'name' => 'Maidens');
$city_data[] = array('accid' => 'USVA0461', 'name' => 'Manakin Sabot');
$city_data[] = array('accid' => 'USVA0462', 'name' => 'Manassas');
$city_data[] = array('accid' => 'USVA0463', 'name' => 'Mannboro');
$city_data[] = array('accid' => 'USVA0464', 'name' => 'Manquin');
$city_data[] = array('accid' => 'USVA0465', 'name' => 'Mappsville');
$city_data[] = array('accid' => 'USVA0466', 'name' => 'Marion');
$city_data[] = array('accid' => 'USVA0467', 'name' => 'Marionville');
$city_data[] = array('accid' => 'USVA0468', 'name' => 'Markham');
$city_data[] = array('accid' => 'USVA0469', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USVA0470', 'name' => 'Martinsville');
$city_data[] = array('accid' => 'USVA0471', 'name' => 'Maryus');
$city_data[] = array('accid' => 'USVA0472', 'name' => 'Mascot');
$city_data[] = array('accid' => 'USVA0473', 'name' => 'Massies Mill');
$city_data[] = array('accid' => 'USVA0474', 'name' => 'Mathews');
$city_data[] = array('accid' => 'USVA0475', 'name' => 'Mattaponi');
$city_data[] = array('accid' => 'USVA0476', 'name' => 'Maurertown');
$city_data[] = array('accid' => 'USVA0477', 'name' => 'Mavisdale');
$city_data[] = array('accid' => 'USVA0478', 'name' => 'Max Meadows');
$city_data[] = array('accid' => 'USVA0479', 'name' => 'Maxie');
$city_data[] = array('accid' => 'USVA0480', 'name' => 'McClure');
$city_data[] = array('accid' => 'USVA0481', 'name' => 'McCoy');
$city_data[] = array('accid' => 'USVA0482', 'name' => 'McDowell');
$city_data[] = array('accid' => 'USVA0483', 'name' => 'McGaheysville');
$city_data[] = array('accid' => 'USVA0484', 'name' => 'McKenney');
$city_data[] = array('accid' => 'USVA0485', 'name' => 'McLean');
$city_data[] = array('accid' => 'USVA0486', 'name' => 'Meadows Of Dan');
$city_data[] = array('accid' => 'USVA0487', 'name' => 'Meadowview');
$city_data[] = array('accid' => 'USVA0488', 'name' => 'Mears');
$city_data[] = array('accid' => 'USVA0489', 'name' => 'Mechanicsville');
$city_data[] = array('accid' => 'USVA0490', 'name' => 'Meherrin');
$city_data[] = array('accid' => 'USVA0491', 'name' => 'Melfa');
$city_data[] = array('accid' => 'USVA0492', 'name' => 'Mendota');
$city_data[] = array('accid' => 'USVA0493', 'name' => 'Meredithville');
$city_data[] = array('accid' => 'USVA0494', 'name' => 'Merrifield');
$city_data[] = array('accid' => 'USVA0495', 'name' => 'Merry Point');
$city_data[] = array('accid' => 'USVA0496', 'name' => 'Middlebrook');
$city_data[] = array('accid' => 'USVA0497', 'name' => 'Middleburg');
$city_data[] = array('accid' => 'USVA0498', 'name' => 'Middletown');
$city_data[] = array('accid' => 'USVA0499', 'name' => 'Midland');
$city_data[] = array('accid' => 'USVA0500', 'name' => 'Midlothian');
$city_data[] = array('accid' => 'USVA0501', 'name' => 'Milford');
$city_data[] = array('accid' => 'USVA0502', 'name' => 'Millboro');
$city_data[] = array('accid' => 'USVA0503', 'name' => 'Millers Tavern');
$city_data[] = array('accid' => 'USVA0504', 'name' => 'Millwood');
$city_data[] = array('accid' => 'USVA0506', 'name' => 'Mineral');
$city_data[] = array('accid' => 'USVA0507', 'name' => 'Mint Spring');
$city_data[] = array('accid' => 'USVA0508', 'name' => 'Mitchells');
$city_data[] = array('accid' => 'USVA0509', 'name' => 'Modest Town');
$city_data[] = array('accid' => 'USVA0510', 'name' => 'Mollusk');
$city_data[] = array('accid' => 'USVA0511', 'name' => 'Moneta');
$city_data[] = array('accid' => 'USVA0512', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USVA0513', 'name' => 'Montebello');
$city_data[] = array('accid' => 'USVA0514', 'name' => 'Monterey');
$city_data[] = array('accid' => 'USVA0515', 'name' => 'Montpelier');
$city_data[] = array('accid' => 'USVA0516', 'name' => 'Montpelier Station');
$city_data[] = array('accid' => 'USVA0517', 'name' => 'Montross');
$city_data[] = array('accid' => 'USVA0518', 'name' => 'Montvale');
$city_data[] = array('accid' => 'USVA0519', 'name' => 'Moon');
$city_data[] = array('accid' => 'USVA0520', 'name' => 'Morattico');
$city_data[] = array('accid' => 'USVA0521', 'name' => 'Moseley');
$city_data[] = array('accid' => 'USVA0522', 'name' => 'Mount Crawford');
$city_data[] = array('accid' => 'USVA0523', 'name' => 'Mount Holly');
$city_data[] = array('accid' => 'USVA0524', 'name' => 'Mount Jackson');
$city_data[] = array('accid' => 'USVA0525', 'name' => 'Mount Sidney');
$city_data[] = array('accid' => 'USVA0526', 'name' => 'Mount Solon');
$city_data[] = array('accid' => 'USVA0527', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USVA0528', 'name' => 'Mouth Of Wilson');
$city_data[] = array('accid' => 'USVA0529', 'name' => 'Mustoe');
$city_data[] = array('accid' => 'USVA0530', 'name' => 'Narrows');
$city_data[] = array('accid' => 'USVA0531', 'name' => 'Naruna');
$city_data[] = array('accid' => 'USVA0532', 'name' => 'Nassawadox');
$city_data[] = array('accid' => 'USVA0533', 'name' => 'Nathalie');
$city_data[] = array('accid' => 'USVA0534', 'name' => 'Natural Bridge');
$city_data[] = array('accid' => 'USVA0535', 'name' => 'Natural Bridge Station');
$city_data[] = array('accid' => 'USVA0536', 'name' => 'Nellysford');
$city_data[] = array('accid' => 'USVA0537', 'name' => 'Nelson');
$city_data[] = array('accid' => 'USVA0538', 'name' => 'Nelsonia');
$city_data[] = array('accid' => 'USVA0539', 'name' => 'New Canton');
$city_data[] = array('accid' => 'USVA0540', 'name' => 'New Castle');
$city_data[] = array('accid' => 'USVA0541', 'name' => 'New Church');
$city_data[] = array('accid' => 'USVA0542', 'name' => 'New Hope');
$city_data[] = array('accid' => 'USVA0543', 'name' => 'New Kent');
$city_data[] = array('accid' => 'USVA0544', 'name' => 'New Market');
$city_data[] = array('accid' => 'USVA0545', 'name' => 'New Point');
$city_data[] = array('accid' => 'USVA0546', 'name' => 'New River');
$city_data[] = array('accid' => 'USVA0547', 'name' => 'Newbern');
$city_data[] = array('accid' => 'USVA0548', 'name' => 'Newington');
$city_data[] = array('accid' => 'USVA0549', 'name' => 'Newport');
$city_data[] = array('accid' => 'USVA0550', 'name' => 'Newport News');
$city_data[] = array('accid' => 'USVA0551', 'name' => 'Newsoms');
$city_data[] = array('accid' => 'USVA0552', 'name' => 'Newtown');
$city_data[] = array('accid' => 'USVA0553', 'name' => 'Nickelsville');
$city_data[] = array('accid' => 'USVA0554', 'name' => 'Ninde');
$city_data[] = array('accid' => 'USVA0555', 'name' => 'Nokesville');
$city_data[] = array('accid' => 'USVA0556', 'name' => 'Nora');
$city_data[] = array('accid' => 'USVA0557', 'name' => 'Norfolk');
$city_data[] = array('accid' => 'USVA0559', 'name' => 'Norge');
$city_data[] = array('accid' => 'USVA0560', 'name' => 'North');
$city_data[] = array('accid' => 'USVA0561', 'name' => 'North Garden');
$city_data[] = array('accid' => 'USVA0562', 'name' => 'North Tazewell');
$city_data[] = array('accid' => 'USVA0563', 'name' => 'Norton');
$city_data[] = array('accid' => 'USVA0564', 'name' => 'Norwood');
$city_data[] = array('accid' => 'USVA0565', 'name' => 'Nottoway');
$city_data[] = array('accid' => 'USVA0566', 'name' => 'Nuttsville');
$city_data[] = array('accid' => 'USVA0567', 'name' => 'Oak Hall');
$city_data[] = array('accid' => 'USVA0568', 'name' => 'Oakpark');
$city_data[] = array('accid' => 'USVA0569', 'name' => 'Oakton');
$city_data[] = array('accid' => 'USVA0570', 'name' => 'Oakwood');
$city_data[] = array('accid' => 'USVA0571', 'name' => 'Occoquan');
$city_data[] = array('accid' => 'USVA0572', 'name' => 'Oilville');
$city_data[] = array('accid' => 'USVA0573', 'name' => 'Oldhams');
$city_data[] = array('accid' => 'USVA0574', 'name' => 'Onancock');
$city_data[] = array('accid' => 'USVA0575', 'name' => 'Onemo');
$city_data[] = array('accid' => 'USVA0576', 'name' => 'Onley');
$city_data[] = array('accid' => 'USVA0577', 'name' => 'Ophelia');
$city_data[] = array('accid' => 'USVA0578', 'name' => 'Orange');
$city_data[] = array('accid' => 'USVA0579', 'name' => 'Ordinary');
$city_data[] = array('accid' => 'USVA0580', 'name' => 'Oriskany');
$city_data[] = array('accid' => 'USVA0581', 'name' => 'Orkney Springs');
$city_data[] = array('accid' => 'USVA0582', 'name' => 'Orlean');
$city_data[] = array('accid' => 'USVA0583', 'name' => 'Oyster');
$city_data[] = array('accid' => 'USVA0584', 'name' => 'Paeonian Springs');
$city_data[] = array('accid' => 'USVA0585', 'name' => 'Paint Bank');
$city_data[] = array('accid' => 'USVA0586', 'name' => 'Painter');
$city_data[] = array('accid' => 'USVA0587', 'name' => 'Palmyra');
$city_data[] = array('accid' => 'USVA0588', 'name' => 'Pamplin');
$city_data[] = array('accid' => 'USVA0589', 'name' => 'Paris');
$city_data[] = array('accid' => 'USVA0590', 'name' => 'Parksley');
$city_data[] = array('accid' => 'USVA0591', 'name' => 'Parrott');
$city_data[] = array('accid' => 'USVA0592', 'name' => 'Partlow');
$city_data[] = array('accid' => 'USVA0593', 'name' => 'Patrick Springs');
$city_data[] = array('accid' => 'USVA0594', 'name' => 'Pearisburg');
$city_data[] = array('accid' => 'USVA0595', 'name' => 'Pembroke');
$city_data[] = array('accid' => 'USVA0596', 'name' => 'Penhook');
$city_data[] = array('accid' => 'USVA0597', 'name' => 'Penn Laird');
$city_data[] = array('accid' => 'USVA0598', 'name' => 'Pennington Gap');
$city_data[] = array('accid' => 'USVA0599', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USVA0600', 'name' => 'Phenix');
$city_data[] = array('accid' => 'USVA0601', 'name' => 'Philomont');
$city_data[] = array('accid' => 'USVA0602', 'name' => 'Pilgrims Knob');
$city_data[] = array('accid' => 'USVA0603', 'name' => 'Pilot');
$city_data[] = array('accid' => 'USVA0604', 'name' => 'Piney River');
$city_data[] = array('accid' => 'USVA0605', 'name' => 'Pittsville');
$city_data[] = array('accid' => 'USVA0606', 'name' => 'Pleasant Valley');
$city_data[] = array('accid' => 'USVA0607', 'name' => 'Pocahontas');
$city_data[] = array('accid' => 'USVA0608', 'name' => 'Poquoson');
$city_data[] = array('accid' => 'USVA0609', 'name' => 'Port Haywood');
$city_data[] = array('accid' => 'USVA0610', 'name' => 'Port Republic');
$city_data[] = array('accid' => 'USVA0611', 'name' => 'Port Royal');
$city_data[] = array('accid' => 'USVA0612', 'name' => 'Portsmouth');
$city_data[] = array('accid' => 'USVA0613', 'name' => 'Pound');
$city_data[] = array('accid' => 'USVA0614', 'name' => 'Pounding Mill');
$city_data[] = array('accid' => 'USVA0615', 'name' => 'Powhatan');
$city_data[] = array('accid' => 'USVA0616', 'name' => 'Pratts');
$city_data[] = array('accid' => 'USVA0617', 'name' => 'Prince George');
$city_data[] = array('accid' => 'USVA0618', 'name' => 'Prospect');
$city_data[] = array('accid' => 'USVA0619', 'name' => 'Providence Forge');
$city_data[] = array('accid' => 'USVA0620', 'name' => 'Pulaski');
$city_data[] = array('accid' => 'USVA0621', 'name' => 'Pungoteague');
$city_data[] = array('accid' => 'USVA0622', 'name' => 'Purcellville');
$city_data[] = array('accid' => 'USVA0623', 'name' => 'Quantico');
$city_data[] = array('accid' => 'USVA0624', 'name' => 'Quicksburg');
$city_data[] = array('accid' => 'USVA0625', 'name' => 'Quinby');
$city_data[] = array('accid' => 'USVA0626', 'name' => 'Quinque');
$city_data[] = array('accid' => 'USVA0627', 'name' => 'Quinton');
$city_data[] = array('accid' => 'USVA0628', 'name' => 'Radford');
$city_data[] = array('accid' => 'USVA0629', 'name' => 'Radiant');
$city_data[] = array('accid' => 'USVA0630', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USVA0631', 'name' => 'Raphine');
$city_data[] = array('accid' => 'USVA0632', 'name' => 'Rapidan');
$city_data[] = array('accid' => 'USVA0633', 'name' => 'Rappahannock Academy');
$city_data[] = array('accid' => 'USVA0634', 'name' => 'Raven');
$city_data[] = array('accid' => 'USVA0635', 'name' => 'Rawlings');
$city_data[] = array('accid' => 'USVA0636', 'name' => 'Rectortown');
$city_data[] = array('accid' => 'USVA0637', 'name' => 'Red Ash');
$city_data[] = array('accid' => 'USVA0638', 'name' => 'Red House');
$city_data[] = array('accid' => 'USVA0639', 'name' => 'Red Oak');
$city_data[] = array('accid' => 'USVA0640', 'name' => 'Redwood');
$city_data[] = array('accid' => 'USVA0641', 'name' => 'Reedville');
$city_data[] = array('accid' => 'USVA0642', 'name' => 'Remington');
$city_data[] = array('accid' => 'USVA0643', 'name' => 'Republican Grove');
$city_data[] = array('accid' => 'USVA0644', 'name' => 'Rescue');
$city_data[] = array('accid' => 'USVA0645', 'name' => 'Reston');
$city_data[] = array('accid' => 'USVA0646', 'name' => 'Reva');
$city_data[] = array('accid' => 'USVA0647', 'name' => 'Rhoadesville');
$city_data[] = array('accid' => 'USVA0648', 'name' => 'Rice');
$city_data[] = array('accid' => 'USVA0649', 'name' => 'Rich Creek');
$city_data[] = array('accid' => 'USVA0650', 'name' => 'Richardsville');
$city_data[] = array('accid' => 'USVA0651', 'name' => 'Richlands');
$city_data[] = array('accid' => 'USVA0652', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USVA0653', 'name' => 'Ridgeway');
$city_data[] = array('accid' => 'USVA0654', 'name' => 'Rileyville');
$city_data[] = array('accid' => 'USVA0655', 'name' => 'Riner');
$city_data[] = array('accid' => 'USVA0656', 'name' => 'Ringgold');
$city_data[] = array('accid' => 'USVA0657', 'name' => 'Ripplemead');
$city_data[] = array('accid' => 'USVA0658', 'name' => 'Rixeyville');
$city_data[] = array('accid' => 'USVA0659', 'name' => 'Roanoke');
$city_data[] = array('accid' => 'USVA0660', 'name' => 'Rochelle');
$city_data[] = array('accid' => 'USVA0661', 'name' => 'Rockbridge Baths');
$city_data[] = array('accid' => 'USVA0662', 'name' => 'Rockville');
$city_data[] = array('accid' => 'USVA0663', 'name' => 'Rocky Gap');
$city_data[] = array('accid' => 'USVA0664', 'name' => 'Rocky Mount');
$city_data[] = array('accid' => 'USVA0665', 'name' => 'Rollins Fork');
$city_data[] = array('accid' => 'USVA0666', 'name' => 'Rose Hill');
$city_data[] = array('accid' => 'USVA0667', 'name' => 'Rosedale');
$city_data[] = array('accid' => 'USVA0668', 'name' => 'Roseland');
$city_data[] = array('accid' => 'USVA0669', 'name' => 'Round Hill');
$city_data[] = array('accid' => 'USVA0670', 'name' => 'Rowe');
$city_data[] = array('accid' => 'USVA0671', 'name' => 'Ruby');
$city_data[] = array('accid' => 'USVA0672', 'name' => 'Ruckersville');
$city_data[] = array('accid' => 'USVA0673', 'name' => 'Rural Retreat');
$city_data[] = array('accid' => 'USVA0674', 'name' => 'Rustburg');
$city_data[] = array('accid' => 'USVA0675', 'name' => 'Ruther Glen');
$city_data[] = array('accid' => 'USVA0676', 'name' => 'Ruthville');
$city_data[] = array('accid' => 'USVA0677', 'name' => 'Saint Charles');
$city_data[] = array('accid' => 'USVA0678', 'name' => 'Saint Paul');
$city_data[] = array('accid' => 'USVA0679', 'name' => 'Saint Stephens Church');
$city_data[] = array('accid' => 'USVA0680', 'name' => 'Salem');
$city_data[] = array('accid' => 'USVA0681', 'name' => 'Saltville');
$city_data[] = array('accid' => 'USVA0682', 'name' => 'Saluda');
$city_data[] = array('accid' => 'USVA0683', 'name' => 'Sandston');
$city_data[] = array('accid' => 'USVA0684', 'name' => 'Sandy Hook');
$city_data[] = array('accid' => 'USVA0685', 'name' => 'Sandy Level');
$city_data[] = array('accid' => 'USVA0686', 'name' => 'Sanford');
$city_data[] = array('accid' => 'USVA0687', 'name' => 'Saxe');
$city_data[] = array('accid' => 'USVA0688', 'name' => 'Saxis');
$city_data[] = array('accid' => 'USVA0689', 'name' => 'Schley');
$city_data[] = array('accid' => 'USVA0690', 'name' => 'Schuyler');
$city_data[] = array('accid' => 'USVA0691', 'name' => 'Scottsburg');
$city_data[] = array('accid' => 'USVA0692', 'name' => 'Scottsville');
$city_data[] = array('accid' => 'USVA0693', 'name' => 'Seaford');
$city_data[] = array('accid' => 'USVA0694', 'name' => 'Sealston');
$city_data[] = array('accid' => 'USVA0695', 'name' => 'Seaview');
$city_data[] = array('accid' => 'USVA0696', 'name' => 'Sedley');
$city_data[] = array('accid' => 'USVA0697', 'name' => 'Selma');
$city_data[] = array('accid' => 'USVA0698', 'name' => 'Seven Mile Ford');
$city_data[] = array('accid' => 'USVA0699', 'name' => 'Severn');
$city_data[] = array('accid' => 'USVA0700', 'name' => 'Shacklefords');
$city_data[] = array('accid' => 'USVA0701', 'name' => 'Sharps');
$city_data[] = array('accid' => 'USVA0702', 'name' => 'Shawsville');
$city_data[] = array('accid' => 'USVA0703', 'name' => 'Shenandoah');
$city_data[] = array('accid' => 'USVA0705', 'name' => 'Shipman');
$city_data[] = array('accid' => 'USVA0706', 'name' => 'Shortt Gap');
$city_data[] = array('accid' => 'USVA0707', 'name' => 'Singers Glen');
$city_data[] = array('accid' => 'USVA0708', 'name' => 'Skippers');
$city_data[] = array('accid' => 'USVA0709', 'name' => 'Skipwith');
$city_data[] = array('accid' => 'USVA0710', 'name' => 'Smithfield');
$city_data[] = array('accid' => 'USVA0711', 'name' => 'Somerset');
$city_data[] = array('accid' => 'USVA0712', 'name' => 'Somerville');
$city_data[] = array('accid' => 'USVA0713', 'name' => 'South Boston');
$city_data[] = array('accid' => 'USVA0714', 'name' => 'South Hill');
$city_data[] = array('accid' => 'USVA0715', 'name' => 'Sparta');
$city_data[] = array('accid' => 'USVA0716', 'name' => 'Speedwell');
$city_data[] = array('accid' => 'USVA0717', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USVA0718', 'name' => 'Sperryville');
$city_data[] = array('accid' => 'USVA0719', 'name' => 'Spotsylvania');
$city_data[] = array('accid' => 'USVA0720', 'name' => 'Spottswood');
$city_data[] = array('accid' => 'USVA0721', 'name' => 'Spout Spring');
$city_data[] = array('accid' => 'USVA0722', 'name' => 'Spring Grove');
$city_data[] = array('accid' => 'USVA0723', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USVA0724', 'name' => 'Stafford');
$city_data[] = array('accid' => 'USVA0725', 'name' => 'Staffordsville');
$city_data[] = array('accid' => 'USVA0726', 'name' => 'Stanardsville');
$city_data[] = array('accid' => 'USVA0727', 'name' => 'Stanley');
$city_data[] = array('accid' => 'USVA0728', 'name' => 'Stanleytown');
$city_data[] = array('accid' => 'USVA0729', 'name' => 'Star Tannery');
$city_data[] = array('accid' => 'USVA0730', 'name' => 'State Farm');
$city_data[] = array('accid' => 'USVA0731', 'name' => 'Staunton');
$city_data[] = array('accid' => 'USVA0732', 'name' => 'Steeles Tavern');
$city_data[] = array('accid' => 'USVA0733', 'name' => 'Stephens City');
$city_data[] = array('accid' => 'USVA0734', 'name' => 'Stephenson');
$city_data[] = array('accid' => 'USVA0735', 'name' => 'Sterling');
$city_data[] = array('accid' => 'USVA0736', 'name' => 'Stevensburg');
$city_data[] = array('accid' => 'USVA0737', 'name' => 'Stevensville');
$city_data[] = array('accid' => 'USVA0738', 'name' => 'Stonega');
$city_data[] = array('accid' => 'USVA0739', 'name' => 'Stony Creek');
$city_data[] = array('accid' => 'USVA0740', 'name' => 'Strasburg');
$city_data[] = array('accid' => 'USVA0741', 'name' => 'Stratford');
$city_data[] = array('accid' => 'USVA0742', 'name' => 'Stuart');
$city_data[] = array('accid' => 'USVA0743', 'name' => 'Stuarts Draft');
$city_data[] = array('accid' => 'USVA0744', 'name' => 'Studley');
$city_data[] = array('accid' => 'USVA0745', 'name' => 'Suffolk');
$city_data[] = array('accid' => 'USVA0746', 'name' => 'Sugar Grove');
$city_data[] = array('accid' => 'USVA0747', 'name' => 'Sumerduck');
$city_data[] = array('accid' => 'USVA0748', 'name' => 'Surry');
$city_data[] = array('accid' => 'USVA0749', 'name' => 'Susan');
$city_data[] = array('accid' => 'USVA0750', 'name' => 'Sussex');
$city_data[] = array('accid' => 'USVA0751', 'name' => 'Sutherland');
$city_data[] = array('accid' => 'USVA0752', 'name' => 'Sutherlin');
$city_data[] = array('accid' => 'USVA0753', 'name' => 'Sweet Briar');
$city_data[] = array('accid' => 'USVA0754', 'name' => 'Swoope');
$city_data[] = array('accid' => 'USVA0755', 'name' => 'Swords Creek');
$city_data[] = array('accid' => 'USVA0756', 'name' => 'Syria');
$city_data[] = array('accid' => 'USVA0757', 'name' => 'Tangier');
$city_data[] = array('accid' => 'USVA0758', 'name' => 'Tannersville');
$city_data[] = array('accid' => 'USVA0759', 'name' => 'Tappahannock');
$city_data[] = array('accid' => 'USVA0760', 'name' => 'Tasley');
$city_data[] = array('accid' => 'USVA0761', 'name' => 'Tazewell');
$city_data[] = array('accid' => 'USVA0762', 'name' => 'Temperanceville');
$city_data[] = array('accid' => 'USVA0763', 'name' => 'Thaxton');
$city_data[] = array('accid' => 'USVA0765', 'name' => 'The Plains');
$city_data[] = array('accid' => 'USVA0766', 'name' => 'Thornburg');
$city_data[] = array('accid' => 'USVA0767', 'name' => 'Timberville');
$city_data[] = array('accid' => 'USVA0768', 'name' => 'Toano');
$city_data[] = array('accid' => 'USVA0769', 'name' => 'Toms Brook');
$city_data[] = array('accid' => 'USVA0770', 'name' => 'Topping');
$city_data[] = array('accid' => 'USVA0771', 'name' => 'Townsend');
$city_data[] = array('accid' => 'USVA0772', 'name' => 'Trammel');
$city_data[] = array('accid' => 'USVA0773', 'name' => 'Trevilians');
$city_data[] = array('accid' => 'USVA0774', 'name' => 'Triangle');
$city_data[] = array('accid' => 'USVA0775', 'name' => 'Trout Dale');
$city_data[] = array('accid' => 'USVA0776', 'name' => 'Troutville');
$city_data[] = array('accid' => 'USVA0777', 'name' => 'Troy');
$city_data[] = array('accid' => 'USVA0778', 'name' => 'Tyro');
$city_data[] = array('accid' => 'USVA0779', 'name' => 'Union Hall');
$city_data[] = array('accid' => 'USVA0780', 'name' => 'Unionville');
$city_data[] = array('accid' => 'USVA0781', 'name' => 'University Of Richmond');
$city_data[] = array('accid' => 'USVA0782', 'name' => 'Upperville');
$city_data[] = array('accid' => 'USVA0783', 'name' => 'Urbanna');
$city_data[] = array('accid' => 'USVA0784', 'name' => 'Valentines');
$city_data[] = array('accid' => 'USVA0785', 'name' => 'Vansant');
$city_data[] = array('accid' => 'USVA0786', 'name' => 'Vernon Hill');
$city_data[] = array('accid' => 'USVA0787', 'name' => 'Verona');
$city_data[] = array('accid' => 'USVA0788', 'name' => 'Vesta');
$city_data[] = array('accid' => 'USVA0789', 'name' => 'Vesuvius');
$city_data[] = array('accid' => 'USVA0790', 'name' => 'Victoria');
$city_data[] = array('accid' => 'USVA0791', 'name' => 'Vienna');
$city_data[] = array('accid' => 'USVA0792', 'name' => 'Viewtown');
$city_data[] = array('accid' => 'USVA0793', 'name' => 'Village');
$city_data[] = array('accid' => 'USVA0794', 'name' => 'Villamont');
$city_data[] = array('accid' => 'USVA0795', 'name' => 'Vinton');
$city_data[] = array('accid' => 'USVA0796', 'name' => 'Virgilina');
$city_data[] = array('accid' => 'USVA0797', 'name' => 'Virginia Beach');
$city_data[] = array('accid' => 'USVA0798', 'name' => 'Volney');
$city_data[] = array('accid' => 'USVA0799', 'name' => 'Wachapreague');
$city_data[] = array('accid' => 'USVA0800', 'name' => 'Wake');
$city_data[] = array('accid' => 'USVA0801', 'name' => 'Wakefield');
$city_data[] = array('accid' => 'USVA0802', 'name' => 'Walkerton');
$city_data[] = array('accid' => 'USVA0803', 'name' => 'Wallops Island');
$city_data[] = array('accid' => 'USVA0804', 'name' => 'Wardtown');
$city_data[] = array('accid' => 'USVA0805', 'name' => 'Ware Neck');
$city_data[] = array('accid' => 'USVA0806', 'name' => 'Warfield');
$city_data[] = array('accid' => 'USVA0807', 'name' => 'Warm Springs');
$city_data[] = array('accid' => 'USVA0808', 'name' => 'Warrenton');
$city_data[] = array('accid' => 'USVA0809', 'name' => 'Warsaw');
$city_data[] = array('accid' => 'USVA0810', 'name' => 'Washington');
$city_data[] = array('accid' => 'USVA0811', 'name' => 'Water View');
$city_data[] = array('accid' => 'USVA0812', 'name' => 'Waterford');
$city_data[] = array('accid' => 'USVA0813', 'name' => 'Wattsville');
$city_data[] = array('accid' => 'USVA0814', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USVA0815', 'name' => 'Waynesboro');
$city_data[] = array('accid' => 'USVA0816', 'name' => 'Weber City');
$city_data[] = array('accid' => 'USVA0817', 'name' => 'Weems');
$city_data[] = array('accid' => 'USVA0818', 'name' => 'West Augusta');
$city_data[] = array('accid' => 'USVA0819', 'name' => 'West McLean');
$city_data[] = array('accid' => 'USVA0820', 'name' => 'West Point');
$city_data[] = array('accid' => 'USVA0821', 'name' => 'Westmoreland');
$city_data[] = array('accid' => 'USVA0822', 'name' => 'Weyers Cave');
$city_data[] = array('accid' => 'USVA0823', 'name' => 'White Hall');
$city_data[] = array('accid' => 'USVA0824', 'name' => 'White Marsh');
$city_data[] = array('accid' => 'USVA0825', 'name' => 'White Plains');
$city_data[] = array('accid' => 'USVA0826', 'name' => 'White Post');
$city_data[] = array('accid' => 'USVA0827', 'name' => 'White Stone');
$city_data[] = array('accid' => 'USVA0828', 'name' => 'Whitetop');
$city_data[] = array('accid' => 'USVA0829', 'name' => 'Whitewood');
$city_data[] = array('accid' => 'USVA0830', 'name' => 'Wicomico');
$city_data[] = array('accid' => 'USVA0831', 'name' => 'Wicomico Church');
$city_data[] = array('accid' => 'USVA0832', 'name' => 'Williamsburg');
$city_data[] = array('accid' => 'USVA0833', 'name' => 'Williamsville');
$city_data[] = array('accid' => 'USVA0834', 'name' => 'Willis');
$city_data[] = array('accid' => 'USVA0835', 'name' => 'Willis Wharf');
$city_data[] = array('accid' => 'USVA0836', 'name' => 'Wilsons');
$city_data[] = array('accid' => 'USVA0837', 'name' => 'Winchester');
$city_data[] = array('accid' => 'USVA0838', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USVA0839', 'name' => 'Wingina');
$city_data[] = array('accid' => 'USVA0840', 'name' => 'Wirtz');
$city_data[] = array('accid' => 'USVA0841', 'name' => 'Wise');
$city_data[] = array('accid' => 'USVA0842', 'name' => 'Withams');
$city_data[] = array('accid' => 'USVA0843', 'name' => 'Wolford');
$city_data[] = array('accid' => 'USVA0844', 'name' => 'Wolftown');
$city_data[] = array('accid' => 'USVA0845', 'name' => 'Woodberry Forest');
$city_data[] = array('accid' => 'USVA0846', 'name' => 'Woodbridge');
$city_data[] = array('accid' => 'USVA0847', 'name' => 'Woodford');
$city_data[] = array('accid' => 'USVA0848', 'name' => 'Woodlawn');
$city_data[] = array('accid' => 'USVA0849', 'name' => 'Woods Cross Roads');
$city_data[] = array('accid' => 'USVA0850', 'name' => 'Woodstock');
$city_data[] = array('accid' => 'USVA0851', 'name' => 'Woodville');
$city_data[] = array('accid' => 'USVA0852', 'name' => 'Woolwine');
$city_data[] = array('accid' => 'USVA0853', 'name' => 'Wylliesburg');
$city_data[] = array('accid' => 'USVA0854', 'name' => 'Wytheville');
$city_data[] = array('accid' => 'USVA0855', 'name' => 'Yale');
$city_data[] = array('accid' => 'USVA0856', 'name' => 'Yorktown');
$city_data[] = array('accid' => 'USVA0857', 'name' => 'Zacata');
$city_data[] = array('accid' => 'USVA0858', 'name' => 'Zanoni');
$city_data[] = array('accid' => 'USVA0859', 'name' => 'Zuni');

?>
