<?php

// City package for USA: Vermont 

$city_name = 'USA: Vermont';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USVT0001', 'name' => 'Adamant');
$city_data[] = array('accid' => 'USVT0002', 'name' => 'Albany');
$city_data[] = array('accid' => 'USVT0003', 'name' => 'Alburg');
$city_data[] = array('accid' => 'USVT0004', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USVT0005', 'name' => 'Ascutney');
$city_data[] = array('accid' => 'USVT0006', 'name' => 'Averill');
$city_data[] = array('accid' => 'USVT0007', 'name' => 'Bakersfield');
$city_data[] = array('accid' => 'USVT0008', 'name' => 'Barnard');
$city_data[] = array('accid' => 'USVT0009', 'name' => 'Barnet');
$city_data[] = array('accid' => 'USVT0010', 'name' => 'Barre');
$city_data[] = array('accid' => 'USVT0011', 'name' => 'Barton');
$city_data[] = array('accid' => 'USVT0012', 'name' => 'Beebe Plain');
$city_data[] = array('accid' => 'USVT0013', 'name' => 'Beecher Falls');
$city_data[] = array('accid' => 'USVT0014', 'name' => 'Bellows Falls');
$city_data[] = array('accid' => 'USVT0015', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USVT0016', 'name' => 'Belvidere Center');
$city_data[] = array('accid' => 'USVT0017', 'name' => 'Bennington');
$city_data[] = array('accid' => 'USVT0018', 'name' => 'Benson');
$city_data[] = array('accid' => 'USVT0019', 'name' => 'Bethel');
$city_data[] = array('accid' => 'USVT0021', 'name' => 'Bomoseen');
$city_data[] = array('accid' => 'USVT0022', 'name' => 'Bondville');
$city_data[] = array('accid' => 'USVT0023', 'name' => 'Bradford');
$city_data[] = array('accid' => 'USVT0024', 'name' => 'Brandon');
$city_data[] = array('accid' => 'USVT0025', 'name' => 'Brattleboro');
$city_data[] = array('accid' => 'USVT0026', 'name' => 'Bridgewater');
$city_data[] = array('accid' => 'USVT0027', 'name' => 'Bridgewater Corners');
$city_data[] = array('accid' => 'USVT0028', 'name' => 'Bridport');
$city_data[] = array('accid' => 'USVT0029', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USVT0031', 'name' => 'Brookfield');
$city_data[] = array('accid' => 'USVT0032', 'name' => 'Brownsville');
$city_data[] = array('accid' => 'USVT0033', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USVT0034', 'name' => 'Cabot');
$city_data[] = array('accid' => 'USVT0035', 'name' => 'Calais');
$city_data[] = array('accid' => 'USVT0036', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'USVT0037', 'name' => 'Cambridgeport');
$city_data[] = array('accid' => 'USVT0038', 'name' => 'Canaan');
$city_data[] = array('accid' => 'USVT0039', 'name' => 'Castleton');
$city_data[] = array('accid' => 'USVT0040', 'name' => 'Cavendish');
$city_data[] = array('accid' => 'USVT0041', 'name' => 'Center Rutland');
$city_data[] = array('accid' => 'USVT0042', 'name' => 'Charlotte');
$city_data[] = array('accid' => 'USVT0043', 'name' => 'Chelsea');
$city_data[] = array('accid' => 'USVT0044', 'name' => 'Chester');
$city_data[] = array('accid' => 'USVT0045', 'name' => 'Chester Depot');
$city_data[] = array('accid' => 'USVT0046', 'name' => 'Chittenden');
$city_data[] = array('accid' => 'USVT0047', 'name' => 'Colchester');
$city_data[] = array('accid' => 'USVT0048', 'name' => 'Concord');
$city_data[] = array('accid' => 'USVT0049', 'name' => 'Corinth');
$city_data[] = array('accid' => 'USVT0050', 'name' => 'Coventry');
$city_data[] = array('accid' => 'USVT0051', 'name' => 'Craftsbury');
$city_data[] = array('accid' => 'USVT0052', 'name' => 'Craftsbury Common');
$city_data[] = array('accid' => 'USVT0053', 'name' => 'Cuttingsville');
$city_data[] = array('accid' => 'USVT0054', 'name' => 'Danby');
$city_data[] = array('accid' => 'USVT0055', 'name' => 'Danville');
$city_data[] = array('accid' => 'USVT0056', 'name' => 'Derby');
$city_data[] = array('accid' => 'USVT0057', 'name' => 'Derby Line');
$city_data[] = array('accid' => 'USVT0058', 'name' => 'Dorset');
$city_data[] = array('accid' => 'USVT0059', 'name' => 'East Arlington');
$city_data[] = array('accid' => 'USVT0060', 'name' => 'East Barre');
$city_data[] = array('accid' => 'USVT0061', 'name' => 'East Berkshire');
$city_data[] = array('accid' => 'USVT0062', 'name' => 'East Burke');
$city_data[] = array('accid' => 'USVT0063', 'name' => 'East Calais');
$city_data[] = array('accid' => 'USVT0064', 'name' => 'East Charleston');
$city_data[] = array('accid' => 'USVT0065', 'name' => 'East Corinth');
$city_data[] = array('accid' => 'USVT0066', 'name' => 'East Dorset');
$city_data[] = array('accid' => 'USVT0067', 'name' => 'East Dover');
$city_data[] = array('accid' => 'USVT0068', 'name' => 'East Fairfield');
$city_data[] = array('accid' => 'USVT0069', 'name' => 'East Hardwick');
$city_data[] = array('accid' => 'USVT0070', 'name' => 'East Haven');
$city_data[] = array('accid' => 'USVT0071', 'name' => 'East Middlebury');
$city_data[] = array('accid' => 'USVT0072', 'name' => 'East Montpelier');
$city_data[] = array('accid' => 'USVT0073', 'name' => 'East Poultney');
$city_data[] = array('accid' => 'USVT0074', 'name' => 'East Randolph');
$city_data[] = array('accid' => 'USVT0075', 'name' => 'East Ryegate');
$city_data[] = array('accid' => 'USVT0076', 'name' => 'East Saint Johnsbury');
$city_data[] = array('accid' => 'USVT0077', 'name' => 'East Thetford');
$city_data[] = array('accid' => 'USVT0078', 'name' => 'East Wallingford');
$city_data[] = array('accid' => 'USVT0079', 'name' => 'Eden');
$city_data[] = array('accid' => 'USVT0080', 'name' => 'Eden Mills');
$city_data[] = array('accid' => 'USVT0081', 'name' => 'Enosburg Falls');
$city_data[] = array('accid' => 'USVT0082', 'name' => 'Essex');
$city_data[] = array('accid' => 'USVT0083', 'name' => 'Essex Junction');
$city_data[] = array('accid' => 'USVT0084', 'name' => 'Fair Haven');
$city_data[] = array('accid' => 'USVT0085', 'name' => 'Fairfax');
$city_data[] = array('accid' => 'USVT0086', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USVT0087', 'name' => 'Fairlee');
$city_data[] = array('accid' => 'USVT0088', 'name' => 'Ferrisburg');
$city_data[] = array('accid' => 'USVT0089', 'name' => 'Florence');
$city_data[] = array('accid' => 'USVT0090', 'name' => 'Forest Dale');
$city_data[] = array('accid' => 'USVT0091', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USVT0092', 'name' => 'Gaysville');
$city_data[] = array('accid' => 'USVT0093', 'name' => 'Gilman');
$city_data[] = array('accid' => 'USVT0094', 'name' => 'Glover');
$city_data[] = array('accid' => 'USVT0095', 'name' => 'Grafton');
$city_data[] = array('accid' => 'USVT0096', 'name' => 'Granby');
$city_data[] = array('accid' => 'USVT0097', 'name' => 'Grand Isle');
$city_data[] = array('accid' => 'USVT0098', 'name' => 'Graniteville');
$city_data[] = array('accid' => 'USVT0099', 'name' => 'Granville');
$city_data[] = array('accid' => 'USVT0100', 'name' => 'Greensboro');
$city_data[] = array('accid' => 'USVT0101', 'name' => 'Greensboro Bend');
$city_data[] = array('accid' => 'USVT0102', 'name' => 'Groton');
$city_data[] = array('accid' => 'USVT0103', 'name' => 'Guildhall');
$city_data[] = array('accid' => 'USVT0104', 'name' => 'Hancock');
$city_data[] = array('accid' => 'USVT0105', 'name' => 'Hardwick');
$city_data[] = array('accid' => 'USVT0106', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USVT0107', 'name' => 'Hartland');
$city_data[] = array('accid' => 'USVT0108', 'name' => 'Hartland Four Corners');
$city_data[] = array('accid' => 'USVT0109', 'name' => 'Highgate Center');
$city_data[] = array('accid' => 'USVT0110', 'name' => 'Highgate Springs');
$city_data[] = array('accid' => 'USVT0111', 'name' => 'Hinesburg');
$city_data[] = array('accid' => 'USVT0112', 'name' => 'Huntington');
$city_data[] = array('accid' => 'USVT0113', 'name' => 'Hyde Park');
$city_data[] = array('accid' => 'USVT0114', 'name' => 'Hydeville');
$city_data[] = array('accid' => 'USVT0115', 'name' => 'Irasburg');
$city_data[] = array('accid' => 'USVT0116', 'name' => 'Island Pond');
$city_data[] = array('accid' => 'USVT0117', 'name' => 'Isle la Motte');
$city_data[] = array('accid' => 'USVT0118', 'name' => 'Jacksonville');
$city_data[] = array('accid' => 'USVT0119', 'name' => 'Jamaica');
$city_data[] = array('accid' => 'USVT0121', 'name' => 'Jeffersonville');
$city_data[] = array('accid' => 'USVT0122', 'name' => 'Jericho');
$city_data[] = array('accid' => 'USVT0123', 'name' => 'Johnson');
$city_data[] = array('accid' => 'USVT0124', 'name' => 'Jonesville');
$city_data[] = array('accid' => 'USVT0125', 'name' => 'Killington');
$city_data[] = array('accid' => 'USVT0127', 'name' => 'Lake Elmore');
$city_data[] = array('accid' => 'USVT0128', 'name' => 'Londonderry');
$city_data[] = array('accid' => 'USVT0129', 'name' => 'Lowell');
$city_data[] = array('accid' => 'USVT0130', 'name' => 'Lower Waterford');
$city_data[] = array('accid' => 'USVT0131', 'name' => 'Ludlow');
$city_data[] = array('accid' => 'USVT0132', 'name' => 'Lunenburg');
$city_data[] = array('accid' => 'USVT0133', 'name' => 'Lyndon');
$city_data[] = array('accid' => 'USVT0134', 'name' => 'Lyndon Center');
$city_data[] = array('accid' => 'USVT0135', 'name' => 'Lyndonville');
$city_data[] = array('accid' => 'USVT0136', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USVT0137', 'name' => 'Manchester Center');
$city_data[] = array('accid' => 'USVT0138', 'name' => 'Marlboro');
$city_data[] = array('accid' => 'USVT0139', 'name' => 'Marshfield');
$city_data[] = array('accid' => 'USVT0140', 'name' => 'McIndoe Falls');
$city_data[] = array('accid' => 'USVT0141', 'name' => 'Middlebury');
$city_data[] = array('accid' => 'USVT0142', 'name' => 'Middletown Springs');
$city_data[] = array('accid' => 'USVT0143', 'name' => 'Milton');
$city_data[] = array('accid' => 'USVT0144', 'name' => 'Monkton');
$city_data[] = array('accid' => 'USVT0145', 'name' => 'Montgomery');
$city_data[] = array('accid' => 'USVT0146', 'name' => 'Montgomery Center');
$city_data[] = array('accid' => 'USVT0147', 'name' => 'Montpelier');
$city_data[] = array('accid' => 'USVT0148', 'name' => 'Moretown');
$city_data[] = array('accid' => 'USVT0149', 'name' => 'Morgan');
$city_data[] = array('accid' => 'USVT0150', 'name' => 'Morrisville');
$city_data[] = array('accid' => 'USVT0151', 'name' => 'Moscow');
$city_data[] = array('accid' => 'USVT0152', 'name' => 'Mount Holly');
$city_data[] = array('accid' => 'USVT0154', 'name' => 'New Haven');
$city_data[] = array('accid' => 'USVT0155', 'name' => 'Newbury');
$city_data[] = array('accid' => 'USVT0156', 'name' => 'Newfane');
$city_data[] = array('accid' => 'USVT0157', 'name' => 'Newport');
$city_data[] = array('accid' => 'USVT0158', 'name' => 'Newport Center');
$city_data[] = array('accid' => 'USVT0159', 'name' => 'North Bennington');
$city_data[] = array('accid' => 'USVT0160', 'name' => 'North Clarendon');
$city_data[] = array('accid' => 'USVT0161', 'name' => 'North Concord');
$city_data[] = array('accid' => 'USVT0162', 'name' => 'North Ferrisburg');
$city_data[] = array('accid' => 'USVT0163', 'name' => 'North Hartland');
$city_data[] = array('accid' => 'USVT0164', 'name' => 'North Hero');
$city_data[] = array('accid' => 'USVT0165', 'name' => 'North Hyde Park');
$city_data[] = array('accid' => 'USVT0166', 'name' => 'North Montpelier');
$city_data[] = array('accid' => 'USVT0167', 'name' => 'North Pomfret');
$city_data[] = array('accid' => 'USVT0168', 'name' => 'North Pownal');
$city_data[] = array('accid' => 'USVT0169', 'name' => 'North Springfield');
$city_data[] = array('accid' => 'USVT0170', 'name' => 'North Thetford');
$city_data[] = array('accid' => 'USVT0171', 'name' => 'North Troy');
$city_data[] = array('accid' => 'USVT0172', 'name' => 'Northfield');
$city_data[] = array('accid' => 'USVT0173', 'name' => 'Northfield Falls');
$city_data[] = array('accid' => 'USVT0174', 'name' => 'Norton');
$city_data[] = array('accid' => 'USVT0175', 'name' => 'Norwich');
$city_data[] = array('accid' => 'USVT0177', 'name' => 'Orleans');
$city_data[] = array('accid' => 'USVT0178', 'name' => 'Orwell');
$city_data[] = array('accid' => 'USVT0179', 'name' => 'Passumpsic');
$city_data[] = array('accid' => 'USVT0180', 'name' => 'Pawlet');
$city_data[] = array('accid' => 'USVT0181', 'name' => 'Peacham');
$city_data[] = array('accid' => 'USVT0182', 'name' => 'Perkinsville');
$city_data[] = array('accid' => 'USVT0183', 'name' => 'Peru');
$city_data[] = array('accid' => 'USVT0185', 'name' => 'Pittsfield');
$city_data[] = array('accid' => 'USVT0186', 'name' => 'Pittsford');
$city_data[] = array('accid' => 'USVT0187', 'name' => 'Plainfield');
$city_data[] = array('accid' => 'USVT0188', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USVT0189', 'name' => 'Post Mills');
$city_data[] = array('accid' => 'USVT0190', 'name' => 'Poultney');
$city_data[] = array('accid' => 'USVT0191', 'name' => 'Pownal');
$city_data[] = array('accid' => 'USVT0192', 'name' => 'Proctor');
$city_data[] = array('accid' => 'USVT0193', 'name' => 'Proctorsville');
$city_data[] = array('accid' => 'USVT0194', 'name' => 'Putney');
$city_data[] = array('accid' => 'USVT0195', 'name' => 'Quechee');
$city_data[] = array('accid' => 'USVT0196', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USVT0197', 'name' => 'Randolph Center');
$city_data[] = array('accid' => 'USVT0198', 'name' => 'Reading');
$city_data[] = array('accid' => 'USVT0199', 'name' => 'Readsboro');
$city_data[] = array('accid' => 'USVT0200', 'name' => 'Richford');
$city_data[] = array('accid' => 'USVT0201', 'name' => 'Richmond');
$city_data[] = array('accid' => 'USVT0202', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USVT0203', 'name' => 'Roxbury');
$city_data[] = array('accid' => 'USVT0204', 'name' => 'Rupert');
$city_data[] = array('accid' => 'USVT0205', 'name' => 'Rutland');
$city_data[] = array('accid' => 'USVT0206', 'name' => 'Saint Albans');
$city_data[] = array('accid' => 'USVT0207', 'name' => 'Saint Albans Bay');
$city_data[] = array('accid' => 'USVT0208', 'name' => 'Saint Johnsbury');
$city_data[] = array('accid' => 'USVT0209', 'name' => 'Saint Johnsbury Center');
$city_data[] = array('accid' => 'USVT0210', 'name' => 'Salisbury');
$city_data[] = array('accid' => 'USVT0211', 'name' => 'Saxtons River');
$city_data[] = array('accid' => 'USVT0212', 'name' => 'Shaftsbury');
$city_data[] = array('accid' => 'USVT0213', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USVT0214', 'name' => 'Sheffield');
$city_data[] = array('accid' => 'USVT0215', 'name' => 'Shelburne');
$city_data[] = array('accid' => 'USVT0216', 'name' => 'Sheldon');
$city_data[] = array('accid' => 'USVT0217', 'name' => 'Sheldon Springs');
$city_data[] = array('accid' => 'USVT0218', 'name' => 'Shoreham');
$city_data[] = array('accid' => 'USVT0220', 'name' => 'South Barre');
$city_data[] = array('accid' => 'USVT0221', 'name' => 'South Burlington');
$city_data[] = array('accid' => 'USVT0222', 'name' => 'South Hero');
$city_data[] = array('accid' => 'USVT0223', 'name' => 'South Londonderry');
$city_data[] = array('accid' => 'USVT0224', 'name' => 'South Newfane');
$city_data[] = array('accid' => 'USVT0225', 'name' => 'South Pomfret');
$city_data[] = array('accid' => 'USVT0226', 'name' => 'South Royalton');
$city_data[] = array('accid' => 'USVT0227', 'name' => 'South Ryegate');
$city_data[] = array('accid' => 'USVT0228', 'name' => 'South Strafford');
$city_data[] = array('accid' => 'USVT0229', 'name' => 'South Woodstock');
$city_data[] = array('accid' => 'USVT0230', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USVT0231', 'name' => 'Starksboro');
$city_data[] = array('accid' => 'USVT0232', 'name' => 'Stockbridge');
$city_data[] = array('accid' => 'USVT0233', 'name' => 'Stowe');
$city_data[] = array('accid' => 'USVT0235', 'name' => 'Strafford');
$city_data[] = array('accid' => 'USVT0238', 'name' => 'Sutton');
$city_data[] = array('accid' => 'USVT0239', 'name' => 'Swanton');
$city_data[] = array('accid' => 'USVT0240', 'name' => 'Taftsville');
$city_data[] = array('accid' => 'USVT0241', 'name' => 'Thetford');
$city_data[] = array('accid' => 'USVT0242', 'name' => 'Thetford Center');
$city_data[] = array('accid' => 'USVT0243', 'name' => 'Townshend');
$city_data[] = array('accid' => 'USVT0244', 'name' => 'Troy');
$city_data[] = array('accid' => 'USVT0245', 'name' => 'Tunbridge');
$city_data[] = array('accid' => 'USVT0246', 'name' => 'Underhill');
$city_data[] = array('accid' => 'USVT0247', 'name' => 'Underhill Center');
$city_data[] = array('accid' => 'USVT0248', 'name' => 'Vergennes');
$city_data[] = array('accid' => 'USVT0249', 'name' => 'Vernon');
$city_data[] = array('accid' => 'USVT0250', 'name' => 'Vershire');
$city_data[] = array('accid' => 'USVT0251', 'name' => 'Waitsfield');
$city_data[] = array('accid' => 'USVT0252', 'name' => 'Wallingford');
$city_data[] = array('accid' => 'USVT0253', 'name' => 'Wardsboro');
$city_data[] = array('accid' => 'USVT0254', 'name' => 'Warren');
$city_data[] = array('accid' => 'USVT0255', 'name' => 'Washington');
$city_data[] = array('accid' => 'USVT0256', 'name' => 'Waterbury');
$city_data[] = array('accid' => 'USVT0257', 'name' => 'Waterbury Center');
$city_data[] = array('accid' => 'USVT0258', 'name' => 'Waterville');
$city_data[] = array('accid' => 'USVT0259', 'name' => 'Websterville');
$city_data[] = array('accid' => 'USVT0260', 'name' => 'Wells');
$city_data[] = array('accid' => 'USVT0261', 'name' => 'Wells River');
$city_data[] = array('accid' => 'USVT0262', 'name' => 'West Burke');
$city_data[] = array('accid' => 'USVT0263', 'name' => 'West Charleston');
$city_data[] = array('accid' => 'USVT0264', 'name' => 'West Danville');
$city_data[] = array('accid' => 'USVT0265', 'name' => 'West Dover');
$city_data[] = array('accid' => 'USVT0266', 'name' => 'West Dummerston');
$city_data[] = array('accid' => 'USVT0267', 'name' => 'West Fairlee');
$city_data[] = array('accid' => 'USVT0268', 'name' => 'West Glover');
$city_data[] = array('accid' => 'USVT0269', 'name' => 'West Halifax');
$city_data[] = array('accid' => 'USVT0270', 'name' => 'West Hartford');
$city_data[] = array('accid' => 'USVT0271', 'name' => 'West Newbury');
$city_data[] = array('accid' => 'USVT0272', 'name' => 'West Pawlet');
$city_data[] = array('accid' => 'USVT0273', 'name' => 'West Rupert');
$city_data[] = array('accid' => 'USVT0274', 'name' => 'West Rutland');
$city_data[] = array('accid' => 'USVT0275', 'name' => 'West Topsham');
$city_data[] = array('accid' => 'USVT0276', 'name' => 'West Townshend');
$city_data[] = array('accid' => 'USVT0277', 'name' => 'West Wardsboro');
$city_data[] = array('accid' => 'USVT0278', 'name' => 'Westfield');
$city_data[] = array('accid' => 'USVT0279', 'name' => 'Westford');
$city_data[] = array('accid' => 'USVT0280', 'name' => 'Westminster');
$city_data[] = array('accid' => 'USVT0281', 'name' => 'Westminster Station');
$city_data[] = array('accid' => 'USVT0282', 'name' => 'Weston');
$city_data[] = array('accid' => 'USVT0283', 'name' => 'White River Junction');
$city_data[] = array('accid' => 'USVT0284', 'name' => 'Whiting');
$city_data[] = array('accid' => 'USVT0285', 'name' => 'Whitingham');
$city_data[] = array('accid' => 'USVT0286', 'name' => 'Wilder');
$city_data[] = array('accid' => 'USVT0287', 'name' => 'Williamstown');
$city_data[] = array('accid' => 'USVT0288', 'name' => 'Williamsville');
$city_data[] = array('accid' => 'USVT0289', 'name' => 'Williston');
$city_data[] = array('accid' => 'USVT0290', 'name' => 'Wilmington');
$city_data[] = array('accid' => 'USVT0291', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USVT0292', 'name' => 'Winooski');
$city_data[] = array('accid' => 'USVT0293', 'name' => 'Wolcott');
$city_data[] = array('accid' => 'USVT0294', 'name' => 'Woodbury');
$city_data[] = array('accid' => 'USVT0295', 'name' => 'Woodstock');
$city_data[] = array('accid' => 'USVT0296', 'name' => 'Worcester');

?>
