<?php

// City package for USA: Washington 

$city_name = 'USA: Washington';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USWA0001', 'name' => 'Aberdeen');
$city_data[] = array('accid' => 'USWA0002', 'name' => 'Acme');
$city_data[] = array('accid' => 'USWA0003', 'name' => 'Addy');
$city_data[] = array('accid' => 'USWA0004', 'name' => 'Adna');
$city_data[] = array('accid' => 'USWA0005', 'name' => 'Airway Heights');
$city_data[] = array('accid' => 'USWA0006', 'name' => 'Albion');
$city_data[] = array('accid' => 'USWA0007', 'name' => 'Allyn');
$city_data[] = array('accid' => 'USWA0008', 'name' => 'Almira');
$city_data[] = array('accid' => 'USWA0009', 'name' => 'Amanda Park');
$city_data[] = array('accid' => 'USWA0010', 'name' => 'Amboy');
$city_data[] = array('accid' => 'USWA0011', 'name' => 'Anacortes');
$city_data[] = array('accid' => 'USWA0012', 'name' => 'Anatone');
$city_data[] = array('accid' => 'USWA0013', 'name' => 'Anderson Island');
$city_data[] = array('accid' => 'USWA0014', 'name' => 'Appleton');
$city_data[] = array('accid' => 'USWA0015', 'name' => 'Ardenvoir');
$city_data[] = array('accid' => 'USWA0016', 'name' => 'Ariel');
$city_data[] = array('accid' => 'USWA0017', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USWA0018', 'name' => 'Ashford');
$city_data[] = array('accid' => 'USWA0019', 'name' => 'Asotin');
$city_data[] = array('accid' => 'USWA0020', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USWA0021', 'name' => 'Bainbridge Island');
$city_data[] = array('accid' => 'USWA0022', 'name' => 'Baring');
$city_data[] = array('accid' => 'USWA0023', 'name' => 'Battle Ground');
$city_data[] = array('accid' => 'USWA0024', 'name' => 'Bay Center');
$city_data[] = array('accid' => 'USWA0025', 'name' => 'Beaver');
$city_data[] = array('accid' => 'USWA0026', 'name' => 'Belfair');
$city_data[] = array('accid' => 'USWA0027', 'name' => 'Bellevue');
$city_data[] = array('accid' => 'USWA0028', 'name' => 'Bellingham');
$city_data[] = array('accid' => 'USWA0029', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USWA0030', 'name' => 'Benge');
$city_data[] = array('accid' => 'USWA0031', 'name' => 'Benton City');
$city_data[] = array('accid' => 'USWA0032', 'name' => 'Beverly');
$city_data[] = array('accid' => 'USWA0033', 'name' => 'Bickleton');
$city_data[] = array('accid' => 'USWA0034', 'name' => 'Bingen');
$city_data[] = array('accid' => 'USWA0035', 'name' => 'Black Diamond');
$city_data[] = array('accid' => 'USWA0036', 'name' => 'Blaine');
$city_data[] = array('accid' => 'USWA0037', 'name' => 'Blakely Island');
$city_data[] = array('accid' => 'USWA0038', 'name' => 'Bothell');
$city_data[] = array('accid' => 'USWA0039', 'name' => 'Bow');
$city_data[] = array('accid' => 'USWA0040', 'name' => 'Boyds');
$city_data[] = array('accid' => 'USWA0041', 'name' => 'Bremerton');
$city_data[] = array('accid' => 'USWA0042', 'name' => 'Brewster');
$city_data[] = array('accid' => 'USWA0043', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USWA0044', 'name' => 'Brinnon');
$city_data[] = array('accid' => 'USWA0045', 'name' => 'Brownstown');
$city_data[] = array('accid' => 'USWA0046', 'name' => 'Brush Prairie');
$city_data[] = array('accid' => 'USWA0047', 'name' => 'Buckley');
$city_data[] = array('accid' => 'USWA0048', 'name' => 'Bucoda');
$city_data[] = array('accid' => 'USWA0049', 'name' => 'Buena');
$city_data[] = array('accid' => 'USWA0050', 'name' => 'Burbank');
$city_data[] = array('accid' => 'USWA0051', 'name' => 'Burley');
$city_data[] = array('accid' => 'USWA0052', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USWA0053', 'name' => 'Burton');
$city_data[] = array('accid' => 'USWA0510', 'name' => 'Camano Island');
$city_data[] = array('accid' => 'USWA0054', 'name' => 'Camas');
$city_data[] = array('accid' => 'USWA0055', 'name' => 'Camp Murray');
$city_data[] = array('accid' => 'USWA0056', 'name' => 'Carbonado');
$city_data[] = array('accid' => 'USWA0057', 'name' => 'Carlsborg');
$city_data[] = array('accid' => 'USWA0058', 'name' => 'Carlton');
$city_data[] = array('accid' => 'USWA0059', 'name' => 'Carnation');
$city_data[] = array('accid' => 'USWA0060', 'name' => 'Carrolls');
$city_data[] = array('accid' => 'USWA0061', 'name' => 'Carson');
$city_data[] = array('accid' => 'USWA0063', 'name' => 'Cashmere');
$city_data[] = array('accid' => 'USWA0064', 'name' => 'Castle Rock');
$city_data[] = array('accid' => 'USWA0065', 'name' => 'Cathlamet');
$city_data[] = array('accid' => 'USWA0066', 'name' => 'Centerville');
$city_data[] = array('accid' => 'USWA0067', 'name' => 'Centralia');
$city_data[] = array('accid' => 'USWA0068', 'name' => 'Chattaroy');
$city_data[] = array('accid' => 'USWA0069', 'name' => 'Chehalis');
$city_data[] = array('accid' => 'USWA0071', 'name' => 'Chelan');
$city_data[] = array('accid' => 'USWA0072', 'name' => 'Chelan Falls');
$city_data[] = array('accid' => 'USWA0073', 'name' => 'Cheney');
$city_data[] = array('accid' => 'USWA0074', 'name' => 'Chewelah');
$city_data[] = array('accid' => 'USWA0075', 'name' => 'Chimacum');
$city_data[] = array('accid' => 'USWA0076', 'name' => 'Chinook');
$city_data[] = array('accid' => 'USWA0077', 'name' => 'Cinebar');
$city_data[] = array('accid' => 'USWA0078', 'name' => 'Clallam Bay');
$city_data[] = array('accid' => 'USWA0079', 'name' => 'Clarkston');
$city_data[] = array('accid' => 'USWA0080', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USWA0081', 'name' => 'Cle Elum');
$city_data[] = array('accid' => 'USWA0082', 'name' => 'Clearlake');
$city_data[] = array('accid' => 'USWA0083', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USWA0084', 'name' => 'Colbert');
$city_data[] = array('accid' => 'USWA0085', 'name' => 'Colfax');
$city_data[] = array('accid' => 'USWA0086', 'name' => 'College Place');
$city_data[] = array('accid' => 'USWA0087', 'name' => 'Colton');
$city_data[] = array('accid' => 'USWA0088', 'name' => 'Colville');
$city_data[] = array('accid' => 'USWA0089', 'name' => 'Conconully');
$city_data[] = array('accid' => 'USWA0090', 'name' => 'Concrete');
$city_data[] = array('accid' => 'USWA0091', 'name' => 'Connell');
$city_data[] = array('accid' => 'USWA0092', 'name' => 'Conway');
$city_data[] = array('accid' => 'USWA0093', 'name' => 'Copalis Beach');
$city_data[] = array('accid' => 'USWA0094', 'name' => 'Copalis Crossing');
$city_data[] = array('accid' => 'USWA0095', 'name' => 'Cosmopolis');
$city_data[] = array('accid' => 'USWA0096', 'name' => 'Cougar');
$city_data[] = array('accid' => 'USWA0097', 'name' => 'Coulee City');
$city_data[] = array('accid' => 'USWA0098', 'name' => 'Coulee Dam');
$city_data[] = array('accid' => 'USWA0099', 'name' => 'Coupeville');
$city_data[] = array('accid' => 'USWA0100', 'name' => 'Cowiche');
$city_data[] = array('accid' => 'USWA0101', 'name' => 'Creston');
$city_data[] = array('accid' => 'USWA0102', 'name' => 'Cunningham');
$city_data[] = array('accid' => 'USWA0103', 'name' => 'Curlew');
$city_data[] = array('accid' => 'USWA0104', 'name' => 'Curtis');
$city_data[] = array('accid' => 'USWA0105', 'name' => 'Cusick');
$city_data[] = array('accid' => 'USWA0106', 'name' => 'Custer');
$city_data[] = array('accid' => 'USWA0107', 'name' => 'Dallesport');
$city_data[] = array('accid' => 'USWA0108', 'name' => 'Danville');
$city_data[] = array('accid' => 'USWA0109', 'name' => 'Darrington');
$city_data[] = array('accid' => 'USWA0110', 'name' => 'Davenport');
$city_data[] = array('accid' => 'USWA0111', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USWA0112', 'name' => 'Deer Harbor');
$city_data[] = array('accid' => 'USWA0113', 'name' => 'Deer Park');
$city_data[] = array('accid' => 'USWA0114', 'name' => 'Deming');
$city_data[] = array('accid' => 'USWA0115', 'name' => 'Dixie');
$city_data[] = array('accid' => 'USWA0116', 'name' => 'Doty');
$city_data[] = array('accid' => 'USWA0117', 'name' => 'Dryden');
$city_data[] = array('accid' => 'USWA0118', 'name' => 'Dupont');
$city_data[] = array('accid' => 'USWA0119', 'name' => 'Duvall');
$city_data[] = array('accid' => 'USWA0120', 'name' => 'East Olympia');
$city_data[] = array('accid' => 'USWA0121', 'name' => 'East Wenatchee');
$city_data[] = array('accid' => 'USWA0122', 'name' => 'Easton');
$city_data[] = array('accid' => 'USWA0123', 'name' => 'Eastsound');
$city_data[] = array('accid' => 'USWA0124', 'name' => 'Eatonville');
$city_data[] = array('accid' => 'USWA0125', 'name' => 'Edmonds');
$city_data[] = array('accid' => 'USWA0126', 'name' => 'Edwall');
$city_data[] = array('accid' => 'USWA0127', 'name' => 'Elbe');
$city_data[] = array('accid' => 'USWA0128', 'name' => 'Electric City');
$city_data[] = array('accid' => 'USWA0129', 'name' => 'Elk');
$city_data[] = array('accid' => 'USWA0130', 'name' => 'Ellensburg');
$city_data[] = array('accid' => 'USWA0131', 'name' => 'Elma');
$city_data[] = array('accid' => 'USWA0132', 'name' => 'Elmer City');
$city_data[] = array('accid' => 'USWA0133', 'name' => 'Eltopia');
$city_data[] = array('accid' => 'USWA0134', 'name' => 'Endicott');
$city_data[] = array('accid' => 'USWA0135', 'name' => 'Entiat');
$city_data[] = array('accid' => 'USWA0136', 'name' => 'Enumclaw');
$city_data[] = array('accid' => 'USWA0137', 'name' => 'Ephrata');
$city_data[] = array('accid' => 'USWA0138', 'name' => 'Ethel');
$city_data[] = array('accid' => 'USWA0139', 'name' => 'Evans');
$city_data[] = array('accid' => 'USWA0140', 'name' => 'Everett');
$city_data[] = array('accid' => 'USWA0141', 'name' => 'Everson');
$city_data[] = array('accid' => 'USWA0142', 'name' => 'Fairchild AFB');
$city_data[] = array('accid' => 'USWA0143', 'name' => 'Fairfield');
$city_data[] = array('accid' => 'USWA0144', 'name' => 'Fall City');
$city_data[] = array('accid' => 'USWA0145', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USWA0146', 'name' => 'Federal Way');
$city_data[] = array('accid' => 'USWA0147', 'name' => 'Ferndale');
$city_data[] = array('accid' => 'USWA0148', 'name' => 'Ford');
$city_data[] = array('accid' => 'USWA0149', 'name' => 'Forks');
$city_data[] = array('accid' => 'USWA0151', 'name' => 'Four Lakes');
$city_data[] = array('accid' => 'USWA0152', 'name' => 'Fox Island');
$city_data[] = array('accid' => 'USWA0153', 'name' => 'Freeland');
$city_data[] = array('accid' => 'USWA0154', 'name' => 'Freeman');
$city_data[] = array('accid' => 'USWA0155', 'name' => 'Friday Harbor');
$city_data[] = array('accid' => 'USWA0156', 'name' => 'Fruitland');
$city_data[] = array('accid' => 'USWA0157', 'name' => 'Galvin');
$city_data[] = array('accid' => 'USWA0158', 'name' => 'Garfield');
$city_data[] = array('accid' => 'USWA0159', 'name' => 'George');
$city_data[] = array('accid' => 'USWA0160', 'name' => 'Gifford');
$city_data[] = array('accid' => 'USWA0161', 'name' => 'Gig Harbor');
$city_data[] = array('accid' => 'USWA0162', 'name' => 'Glenoma');
$city_data[] = array('accid' => 'USWA0163', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USWA0164', 'name' => 'Gold Bar');
$city_data[] = array('accid' => 'USWA0165', 'name' => 'Goldendale');
$city_data[] = array('accid' => 'USWA0166', 'name' => 'Goose Prairie');
$city_data[] = array('accid' => 'USWA0167', 'name' => 'Graham');
$city_data[] = array('accid' => 'USWA0168', 'name' => 'Grand Coulee');
$city_data[] = array('accid' => 'USWA0169', 'name' => 'Grandview');
$city_data[] = array('accid' => 'USWA0170', 'name' => 'Granger');
$city_data[] = array('accid' => 'USWA0171', 'name' => 'Granite Falls');
$city_data[] = array('accid' => 'USWA0172', 'name' => 'Grapeview');
$city_data[] = array('accid' => 'USWA0173', 'name' => 'Grayland');
$city_data[] = array('accid' => 'USWA0174', 'name' => 'Grays River');
$city_data[] = array('accid' => 'USWA0175', 'name' => 'Greenacres');
$city_data[] = array('accid' => 'USWA0176', 'name' => 'Greenbank');
$city_data[] = array('accid' => 'USWA0177', 'name' => 'Hamilton');
$city_data[] = array('accid' => 'USWA0178', 'name' => 'Hansville');
$city_data[] = array('accid' => 'USWA0179', 'name' => 'Harrah');
$city_data[] = array('accid' => 'USWA0180', 'name' => 'Harrington');
$city_data[] = array('accid' => 'USWA0181', 'name' => 'Hartline');
$city_data[] = array('accid' => 'USWA0182', 'name' => 'Hatton');
$city_data[] = array('accid' => 'USWA0183', 'name' => 'Hay');
$city_data[] = array('accid' => 'USWA0184', 'name' => 'Heisson');
$city_data[] = array('accid' => 'USWA0185', 'name' => 'Hobart');
$city_data[] = array('accid' => 'USWA0186', 'name' => 'Hoodsport');
$city_data[] = array('accid' => 'USWA0187', 'name' => 'Hooper');
$city_data[] = array('accid' => 'USWA0188', 'name' => 'Hoquiam');
$city_data[] = array('accid' => 'USWA0189', 'name' => 'Humptulips');
$city_data[] = array('accid' => 'USWA0190', 'name' => 'Hunters');
$city_data[] = array('accid' => 'USWA0191', 'name' => 'Husum');
$city_data[] = array('accid' => 'USWA0192', 'name' => 'Ilwaco');
$city_data[] = array('accid' => 'USWA0193', 'name' => 'Inchelium');
$city_data[] = array('accid' => 'USWA0194', 'name' => 'Index');
$city_data[] = array('accid' => 'USWA0195', 'name' => 'Indianola');
$city_data[] = array('accid' => 'USWA0196', 'name' => 'Ione');
$city_data[] = array('accid' => 'USWA0197', 'name' => 'Issaquah');
$city_data[] = array('accid' => 'USWA0198', 'name' => 'Joyce');
$city_data[] = array('accid' => 'USWA0199', 'name' => 'Kahlotus');
$city_data[] = array('accid' => 'USWA0200', 'name' => 'Kalama');
$city_data[] = array('accid' => 'USWA0201', 'name' => 'Kapowsin');
$city_data[] = array('accid' => 'USWA0202', 'name' => 'Keller');
$city_data[] = array('accid' => 'USWA0203', 'name' => 'Kelso');
$city_data[] = array('accid' => 'USWA0204', 'name' => 'Kenmore');
$city_data[] = array('accid' => 'USWA0205', 'name' => 'Kennewick');
$city_data[] = array('accid' => 'USWA0206', 'name' => 'Kent');
$city_data[] = array('accid' => 'USWA0207', 'name' => 'Kettle Falls');
$city_data[] = array('accid' => 'USWA0208', 'name' => 'Keyport');
$city_data[] = array('accid' => 'USWA0209', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USWA0210', 'name' => 'Kirkland');
$city_data[] = array('accid' => 'USWA0211', 'name' => 'Kittitas');
$city_data[] = array('accid' => 'USWA0212', 'name' => 'Klickitat');
$city_data[] = array('accid' => 'USWA0213', 'name' => 'La Center');
$city_data[] = array('accid' => 'USWA0214', 'name' => 'La Conner');
$city_data[] = array('accid' => 'USWA0218', 'name' => 'La Crosse');
$city_data[] = array('accid' => 'USWA0215', 'name' => 'La Grande');
$city_data[] = array('accid' => 'USWA0216', 'name' => 'La Push');
$city_data[] = array('accid' => 'USWA0217', 'name' => 'Lacey');
$city_data[] = array('accid' => 'USWA0219', 'name' => 'Lake Stevens');
$city_data[] = array('accid' => 'USWA0220', 'name' => 'Lakebay');
$city_data[] = array('accid' => 'USWA0221', 'name' => 'Lakewood');
$city_data[] = array('accid' => 'USWA0222', 'name' => 'Lamona');
$city_data[] = array('accid' => 'USWA0223', 'name' => 'Lamont');
$city_data[] = array('accid' => 'USWA0224', 'name' => 'Langley');
$city_data[] = array('accid' => 'USWA0225', 'name' => 'Latah');
$city_data[] = array('accid' => 'USWA0226', 'name' => 'Laurier');
$city_data[] = array('accid' => 'USWA0227', 'name' => 'Leavenworth');
$city_data[] = array('accid' => 'USWA0228', 'name' => 'Lebam');
$city_data[] = array('accid' => 'USWA0229', 'name' => 'Liberty Lake');
$city_data[] = array('accid' => 'USWA0230', 'name' => 'Lilliwaup');
$city_data[] = array('accid' => 'USWA0231', 'name' => 'Lincoln');
$city_data[] = array('accid' => 'USWA0232', 'name' => 'Lind');
$city_data[] = array('accid' => 'USWA0233', 'name' => 'Littlerock');
$city_data[] = array('accid' => 'USWA0234', 'name' => 'Long Beach');
$city_data[] = array('accid' => 'USWA0235', 'name' => 'Longbranch');
$city_data[] = array('accid' => 'USWA0236', 'name' => 'Longmire');
$city_data[] = array('accid' => 'USWA0237', 'name' => 'Longview');
$city_data[] = array('accid' => 'USWA0238', 'name' => 'Loomis');
$city_data[] = array('accid' => 'USWA0239', 'name' => 'Loon Lake');
$city_data[] = array('accid' => 'USWA0240', 'name' => 'Lopez Island');
$city_data[] = array('accid' => 'USWA0241', 'name' => 'Lummi Island');
$city_data[] = array('accid' => 'USWA0242', 'name' => 'Lyle');
$city_data[] = array('accid' => 'USWA0243', 'name' => 'Lyman');
$city_data[] = array('accid' => 'USWA0244', 'name' => 'Lynden');
$city_data[] = array('accid' => 'USWA0245', 'name' => 'Lynnwood');
$city_data[] = array('accid' => 'USWA0246', 'name' => 'Mabton');
$city_data[] = array('accid' => 'USWA0247', 'name' => 'Malaga');
$city_data[] = array('accid' => 'USWA0248', 'name' => 'Malden');
$city_data[] = array('accid' => 'USWA0249', 'name' => 'Malo');
$city_data[] = array('accid' => 'USWA0250', 'name' => 'Malone');
$city_data[] = array('accid' => 'USWA0251', 'name' => 'Malott');
$city_data[] = array('accid' => 'USWA0252', 'name' => 'Manchester');
$city_data[] = array('accid' => 'USWA0253', 'name' => 'Mansfield');
$city_data[] = array('accid' => 'USWA0254', 'name' => 'Manson');
$city_data[] = array('accid' => 'USWA0255', 'name' => 'Maple Falls');
$city_data[] = array('accid' => 'USWA0256', 'name' => 'Maple Valley');
$city_data[] = array('accid' => 'USWA0257', 'name' => 'Marblemount');
$city_data[] = array('accid' => 'USWA0258', 'name' => 'Marcus');
$city_data[] = array('accid' => 'USWA0259', 'name' => 'Marlin');
$city_data[] = array('accid' => 'USWA0260', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USWA0261', 'name' => 'Marysville');
$city_data[] = array('accid' => 'USWA0262', 'name' => 'Matlock');
$city_data[] = array('accid' => 'USWA0263', 'name' => 'Mattawa');
$city_data[] = array('accid' => 'USWA0264', 'name' => 'Mazama');
$city_data[] = array('accid' => 'USWA0265', 'name' => 'McCleary');
$city_data[] = array('accid' => 'USWA0266', 'name' => 'McKenna');
$city_data[] = array('accid' => 'USWA0267', 'name' => 'Mead');
$city_data[] = array('accid' => 'USWA0268', 'name' => 'Medical Lake');
$city_data[] = array('accid' => 'USWA0269', 'name' => 'Medina');
$city_data[] = array('accid' => 'USWA0270', 'name' => 'Menlo');
$city_data[] = array('accid' => 'USWA0271', 'name' => 'Mercer Island');
$city_data[] = array('accid' => 'USWA0272', 'name' => 'Mesa');
$city_data[] = array('accid' => 'USWA0273', 'name' => 'Metaline');
$city_data[] = array('accid' => 'USWA0274', 'name' => 'Metaline Falls');
$city_data[] = array('accid' => 'USWA0275', 'name' => 'Methow');
$city_data[] = array('accid' => 'USWA0276', 'name' => 'Mica');
$city_data[] = array('accid' => 'USWA0277', 'name' => 'Milton');
$city_data[] = array('accid' => 'USWA0278', 'name' => 'Mineral');
$city_data[] = array('accid' => 'USWA0279', 'name' => 'Moclips');
$city_data[] = array('accid' => 'USWA0280', 'name' => 'Mohler');
$city_data[] = array('accid' => 'USWA0281', 'name' => 'Monitor');
$city_data[] = array('accid' => 'USWA0282', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USWA0283', 'name' => 'Montesano');
$city_data[] = array('accid' => 'USWA0284', 'name' => 'Morton');
$city_data[] = array('accid' => 'USWA0285', 'name' => 'Moses Lake');
$city_data[] = array('accid' => 'USWA0286', 'name' => 'Mossyrock');
$city_data[] = array('accid' => 'USWA0288', 'name' => 'Mount Vernon');
$city_data[] = array('accid' => 'USWA0289', 'name' => 'Mountlake Terrace');
$city_data[] = array('accid' => 'USWA0290', 'name' => 'Moxee');
$city_data[] = array('accid' => 'USWA0291', 'name' => 'Mukilteo');
$city_data[] = array('accid' => 'USWA0292', 'name' => 'Naches');
$city_data[] = array('accid' => 'USWA0293', 'name' => 'Nahcotta');
$city_data[] = array('accid' => 'USWA0294', 'name' => 'Napavine');
$city_data[] = array('accid' => 'USWA0295', 'name' => 'Naselle');
$city_data[] = array('accid' => 'USWA0296', 'name' => 'Neah Bay');
$city_data[] = array('accid' => 'USWA0297', 'name' => 'Neilton');
$city_data[] = array('accid' => 'USWA0298', 'name' => 'Nespelem');
$city_data[] = array('accid' => 'USWA0299', 'name' => 'Newman Lake');
$city_data[] = array('accid' => 'USWA0300', 'name' => 'Newport');
$city_data[] = array('accid' => 'USWA0301', 'name' => 'Nine Mile Falls');
$city_data[] = array('accid' => 'USWA0302', 'name' => 'Nooksack');
$city_data[] = array('accid' => 'USWA0303', 'name' => 'Nordland');
$city_data[] = array('accid' => 'USWA0304', 'name' => 'North Bend');
$city_data[] = array('accid' => 'USWA0305', 'name' => 'North Bonneville');
$city_data[] = array('accid' => 'USWA0307', 'name' => 'North Lakewood');
$city_data[] = array('accid' => 'USWA0308', 'name' => 'Northport');
$city_data[] = array('accid' => 'USWA0309', 'name' => 'Oak Harbor');
$city_data[] = array('accid' => 'USWA0310', 'name' => 'Oakesdale');
$city_data[] = array('accid' => 'USWA0311', 'name' => 'Oakville');
$city_data[] = array('accid' => 'USWA0312', 'name' => 'Ocean Park');
$city_data[] = array('accid' => 'USWA0313', 'name' => 'Ocean Shores');
$city_data[] = array('accid' => 'USWA0314', 'name' => 'Odessa');
$city_data[] = array('accid' => 'USWA0315', 'name' => 'Okanogan');
$city_data[] = array('accid' => 'USWA0316', 'name' => 'Olalla');
$city_data[] = array('accid' => 'USWA0317', 'name' => 'Olga');
$city_data[] = array('accid' => 'USWA0318', 'name' => 'Olympia');
$city_data[] = array('accid' => 'USWA0320', 'name' => 'Omak');
$city_data[] = array('accid' => 'USWA0321', 'name' => 'Onalaska');
$city_data[] = array('accid' => 'USWA0322', 'name' => 'Orcas');
$city_data[] = array('accid' => 'USWA0323', 'name' => 'Orient');
$city_data[] = array('accid' => 'USWA0324', 'name' => 'Orondo');
$city_data[] = array('accid' => 'USWA0325', 'name' => 'Oroville');
$city_data[] = array('accid' => 'USWA0326', 'name' => 'Orting');
$city_data[] = array('accid' => 'USWA0327', 'name' => 'Othello');
$city_data[] = array('accid' => 'USWA0328', 'name' => 'Otis Orchards');
$city_data[] = array('accid' => 'USWA0329', 'name' => 'Outlook');
$city_data[] = array('accid' => 'USWA0330', 'name' => 'Oysterville');
$city_data[] = array('accid' => 'USWA0331', 'name' => 'Pacific');
$city_data[] = array('accid' => 'USWA0332', 'name' => 'Pacific Beach');
$city_data[] = array('accid' => 'USWA0333', 'name' => 'Packwood');
$city_data[] = array('accid' => 'USWA0334', 'name' => 'Palisades');
$city_data[] = array('accid' => 'USWA0335', 'name' => 'Palouse');
$city_data[] = array('accid' => 'USWA0336', 'name' => 'Paradise Inn');
$city_data[] = array('accid' => 'USWA0337', 'name' => 'Parker');
$city_data[] = array('accid' => 'USWA0338', 'name' => 'Pasco');
$city_data[] = array('accid' => 'USWA0339', 'name' => 'Pateros');
$city_data[] = array('accid' => 'USWA0340', 'name' => 'Paterson');
$city_data[] = array('accid' => 'USWA0341', 'name' => 'Pe Ell');
$city_data[] = array('accid' => 'USWA0342', 'name' => 'Peshastin');
$city_data[] = array('accid' => 'USWA0343', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USWA0344', 'name' => 'Point Roberts');
$city_data[] = array('accid' => 'USWA0345', 'name' => 'Pomeroy');
$city_data[] = array('accid' => 'USWA0346', 'name' => 'Port Angeles');
$city_data[] = array('accid' => 'USWA0347', 'name' => 'Port Gamble');
$city_data[] = array('accid' => 'USWA0348', 'name' => 'Port Hadlock');
$city_data[] = array('accid' => 'USWA0349', 'name' => 'Port Ludlow');
$city_data[] = array('accid' => 'USWA0350', 'name' => 'Port Orchard');
$city_data[] = array('accid' => 'USWA0351', 'name' => 'Port Townsend');
$city_data[] = array('accid' => 'USWA0352', 'name' => 'Poulsbo');
$city_data[] = array('accid' => 'USWA0353', 'name' => 'Prescott');
$city_data[] = array('accid' => 'USWA0354', 'name' => 'Preston');
$city_data[] = array('accid' => 'USWA0355', 'name' => 'Prosser');
$city_data[] = array('accid' => 'USWA0356', 'name' => 'Pullman');
$city_data[] = array('accid' => 'USWA0357', 'name' => 'Puyallup');
$city_data[] = array('accid' => 'USWA0358', 'name' => 'Quilcene');
$city_data[] = array('accid' => 'USWA0360', 'name' => 'Quinault');
$city_data[] = array('accid' => 'USWA0361', 'name' => 'Quincy');
$city_data[] = array('accid' => 'USWA0362', 'name' => 'Rainier');
$city_data[] = array('accid' => 'USWA0363', 'name' => 'Randle');
$city_data[] = array('accid' => 'USWA0364', 'name' => 'Ravensdale');
$city_data[] = array('accid' => 'USWA0365', 'name' => 'Raymond');
$city_data[] = array('accid' => 'USWA0366', 'name' => 'Reardan');
$city_data[] = array('accid' => 'USWA0367', 'name' => 'Redmond');
$city_data[] = array('accid' => 'USWA0368', 'name' => 'Redondo');
$city_data[] = array('accid' => 'USWA0369', 'name' => 'Renton');
$city_data[] = array('accid' => 'USWA0370', 'name' => 'Republic');
$city_data[] = array('accid' => 'USWA0371', 'name' => 'Retsil');
$city_data[] = array('accid' => 'USWA0372', 'name' => 'Rice');
$city_data[] = array('accid' => 'USWA0373', 'name' => 'Richland');
$city_data[] = array('accid' => 'USWA0374', 'name' => 'Ridgefield');
$city_data[] = array('accid' => 'USWA0375', 'name' => 'Ritzville');
$city_data[] = array('accid' => 'USWA0376', 'name' => 'Riverside');
$city_data[] = array('accid' => 'USWA0377', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USWA0378', 'name' => 'Rock Island');
$city_data[] = array('accid' => 'USWA0379', 'name' => 'Rockford');
$city_data[] = array('accid' => 'USWA0380', 'name' => 'Rockport');
$city_data[] = array('accid' => 'USWA0381', 'name' => 'Rollingbay');
$city_data[] = array('accid' => 'USWA0382', 'name' => 'Ronald');
$city_data[] = array('accid' => 'USWA0383', 'name' => 'Roosevelt');
$city_data[] = array('accid' => 'USWA0384', 'name' => 'Rosalia');
$city_data[] = array('accid' => 'USWA0385', 'name' => 'Rosburg');
$city_data[] = array('accid' => 'USWA0386', 'name' => 'Roslyn');
$city_data[] = array('accid' => 'USWA0387', 'name' => 'Roy');
$city_data[] = array('accid' => 'USWA0388', 'name' => 'Royal City');
$city_data[] = array('accid' => 'USWA0389', 'name' => 'Ryderwood');
$city_data[] = array('accid' => 'USWA0390', 'name' => 'Saint John');
$city_data[] = array('accid' => 'USWA0391', 'name' => 'Salkum');
$city_data[] = array('accid' => 'USWA0511', 'name' => 'Sammamish');
$city_data[] = array('accid' => 'USWA0392', 'name' => 'Satsop');
$city_data[] = array('accid' => 'USWA0393', 'name' => 'Seabeck');
$city_data[] = array('accid' => 'USWA0394', 'name' => 'Seahurst');
$city_data[] = array('accid' => 'USWA0395', 'name' => 'Seattle');
$city_data[] = array('accid' => 'USWA0396', 'name' => 'Seattle$city_data[]Boeing Field');
$city_data[] = array('accid' => 'USWA0397', 'name' => 'Seaview');
$city_data[] = array('accid' => 'USWA0398', 'name' => 'Sedro Woolley');
$city_data[] = array('accid' => 'USWA0399', 'name' => 'Sekiu');
$city_data[] = array('accid' => 'USWA0400', 'name' => 'Selah');
$city_data[] = array('accid' => 'USWA0401', 'name' => 'Sequim');
$city_data[] = array('accid' => 'USWA0402', 'name' => 'Shaw Island');
$city_data[] = array('accid' => 'USWA0403', 'name' => 'Shelton');
$city_data[] = array('accid' => 'USWA0404', 'name' => 'Silvana');
$city_data[] = array('accid' => 'USWA0405', 'name' => 'Silver Creek');
$city_data[] = array('accid' => 'USWA0406', 'name' => 'Silverdale');
$city_data[] = array('accid' => 'USWA0407', 'name' => 'Silverlake');
$city_data[] = array('accid' => 'USWA0408', 'name' => 'Skamokawa');
$city_data[] = array('accid' => 'USWA0410', 'name' => 'Skykomish');
$city_data[] = array('accid' => 'USWA0411', 'name' => 'Snohomish');
$city_data[] = array('accid' => 'USWA0412', 'name' => 'Snoqualmie');
$city_data[] = array('accid' => 'USWA0413', 'name' => 'Snoqualmie Pass');
$city_data[] = array('accid' => 'USWA0414', 'name' => 'Soap Lake');
$city_data[] = array('accid' => 'USWA0415', 'name' => 'South Bend');
$city_data[] = array('accid' => 'USWA0416', 'name' => 'South Cle Elum');
$city_data[] = array('accid' => 'USWA0417', 'name' => 'South Colby');
$city_data[] = array('accid' => 'USWA0418', 'name' => 'South Prairie');
$city_data[] = array('accid' => 'USWA0419', 'name' => 'Southworth');
$city_data[] = array('accid' => 'USWA0420', 'name' => 'Spanaway');
$city_data[] = array('accid' => 'USWA0421', 'name' => 'Spangle');
$city_data[] = array('accid' => 'USWA0422', 'name' => 'Spokane');
$city_data[] = array('accid' => 'USWA0425', 'name' => 'Sprague');
$city_data[] = array('accid' => 'USWA0426', 'name' => 'Springdale');
$city_data[] = array('accid' => 'USWA0428', 'name' => 'Stanwood');
$city_data[] = array('accid' => 'USWA0429', 'name' => 'Starbuck');
$city_data[] = array('accid' => 'USWA0430', 'name' => 'Startup');
$city_data[] = array('accid' => 'USWA0431', 'name' => 'Stehekin');
$city_data[] = array('accid' => 'USWA0432', 'name' => 'Steilacoom');
$city_data[] = array('accid' => 'USWA0433', 'name' => 'Steptoe');
$city_data[] = array('accid' => 'USWA0434', 'name' => 'Stevenson');
$city_data[] = array('accid' => 'USWA0435', 'name' => 'Stratford');
$city_data[] = array('accid' => 'USWA0436', 'name' => 'Sultan');
$city_data[] = array('accid' => 'USWA0437', 'name' => 'Sumas');
$city_data[] = array('accid' => 'USWA0438', 'name' => 'Sumner');
$city_data[] = array('accid' => 'USWA0439', 'name' => 'Sunnyside');
$city_data[] = array('accid' => 'USWA0440', 'name' => 'Suquamish');
$city_data[] = array('accid' => 'USWA0441', 'name' => 'Tacoma');
$city_data[] = array('accid' => 'USWA0443', 'name' => 'Taholah');
$city_data[] = array('accid' => 'USWA0444', 'name' => 'Tahuya');
$city_data[] = array('accid' => 'USWA0445', 'name' => 'Tekoa');
$city_data[] = array('accid' => 'USWA0446', 'name' => 'Tenino');
$city_data[] = array('accid' => 'USWA0447', 'name' => 'Thornton');
$city_data[] = array('accid' => 'USWA0448', 'name' => 'Thorp');
$city_data[] = array('accid' => 'USWA0449', 'name' => 'Tieton');
$city_data[] = array('accid' => 'USWA0450', 'name' => 'Tokeland');
$city_data[] = array('accid' => 'USWA0451', 'name' => 'Toledo');
$city_data[] = array('accid' => 'USWA0452', 'name' => 'Tonasket');
$city_data[] = array('accid' => 'USWA0453', 'name' => 'Toppenish');
$city_data[] = array('accid' => 'USWA0454', 'name' => 'Touchet');
$city_data[] = array('accid' => 'USWA0455', 'name' => 'Toutle');
$city_data[] = array('accid' => 'USWA0456', 'name' => 'Tracyton');
$city_data[] = array('accid' => 'USWA0457', 'name' => 'Trout Lake');
$city_data[] = array('accid' => 'USWA0458', 'name' => 'Tumtum');
$city_data[] = array('accid' => 'USWA0459', 'name' => 'Twisp');
$city_data[] = array('accid' => 'USWA0460', 'name' => 'Underwood');
$city_data[] = array('accid' => 'USWA0461', 'name' => 'Union');
$city_data[] = array('accid' => 'USWA0462', 'name' => 'Uniontown');
$city_data[] = array('accid' => 'USWA0463', 'name' => 'University Place');
$city_data[] = array('accid' => 'USWA0464', 'name' => 'Usk');
$city_data[] = array('accid' => 'USWA0465', 'name' => 'Vader');
$city_data[] = array('accid' => 'USWA0466', 'name' => 'Valley');
$city_data[] = array('accid' => 'USWA0467', 'name' => 'Valleyford');
$city_data[] = array('accid' => 'USWA0468', 'name' => 'Vancouver');
$city_data[] = array('accid' => 'USWA0469', 'name' => 'Vantage');
$city_data[] = array('accid' => 'USWA0470', 'name' => 'Vashon');
$city_data[] = array('accid' => 'USWA0471', 'name' => 'Vaughn');
$city_data[] = array('accid' => 'USWA0472', 'name' => 'Veradale');
$city_data[] = array('accid' => 'USWA0473', 'name' => 'Wahkiacus');
$city_data[] = array('accid' => 'USWA0474', 'name' => 'Waitsburg');
$city_data[] = array('accid' => 'USWA0475', 'name' => 'Waldron');
$city_data[] = array('accid' => 'USWA0476', 'name' => 'Walla Walla');
$city_data[] = array('accid' => 'USWA0477', 'name' => 'Wallula');
$city_data[] = array('accid' => 'USWA0478', 'name' => 'Wapato');
$city_data[] = array('accid' => 'USWA0479', 'name' => 'Warden');
$city_data[] = array('accid' => 'USWA0480', 'name' => 'Washougal');
$city_data[] = array('accid' => 'USWA0481', 'name' => 'Washtucna');
$city_data[] = array('accid' => 'USWA0482', 'name' => 'Waterville');
$city_data[] = array('accid' => 'USWA0483', 'name' => 'Wauconda');
$city_data[] = array('accid' => 'USWA0484', 'name' => 'Wauna');
$city_data[] = array('accid' => 'USWA0485', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USWA0486', 'name' => 'Wellpinit');
$city_data[] = array('accid' => 'USWA0487', 'name' => 'Wenatchee');
$city_data[] = array('accid' => 'USWA0488', 'name' => 'West Richland');
$city_data[] = array('accid' => 'USWA0489', 'name' => 'Westport');
$city_data[] = array('accid' => 'USWA0491', 'name' => 'White Salmon');
$city_data[] = array('accid' => 'USWA0492', 'name' => 'White Swan');
$city_data[] = array('accid' => 'USWA0493', 'name' => 'Wilbur');
$city_data[] = array('accid' => 'USWA0494', 'name' => 'Wilkeson');
$city_data[] = array('accid' => 'USWA0495', 'name' => 'Wilson Creek');
$city_data[] = array('accid' => 'USWA0496', 'name' => 'Winlock');
$city_data[] = array('accid' => 'USWA0497', 'name' => 'Winthrop');
$city_data[] = array('accid' => 'USWA0498', 'name' => 'Wishram');
$city_data[] = array('accid' => 'USWA0499', 'name' => 'Woodinville');
$city_data[] = array('accid' => 'USWA0500', 'name' => 'Woodland');
$city_data[] = array('accid' => 'USWA0501', 'name' => 'Yacolt');
$city_data[] = array('accid' => 'USWA0502', 'name' => 'Yakima');
$city_data[] = array('accid' => 'USWA0503', 'name' => 'Yelm');
$city_data[] = array('accid' => 'USWA0504', 'name' => 'Zillah');

?>
