<?php

// City package for USA: Wisconsin 

$city_name = 'USA: Wisconsin';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USWI0001', 'name' => 'Abbotsford');
$city_data[] = array('accid' => 'USWI0002', 'name' => 'Abrams');
$city_data[] = array('accid' => 'USWI0003', 'name' => 'Adams');
$city_data[] = array('accid' => 'USWI0004', 'name' => 'Adell');
$city_data[] = array('accid' => 'USWI0005', 'name' => 'Afton');
$city_data[] = array('accid' => 'USWI0006', 'name' => 'Albany');
$city_data[] = array('accid' => 'USWI0007', 'name' => 'Algoma');
$city_data[] = array('accid' => 'USWI0008', 'name' => 'Allenton');
$city_data[] = array('accid' => 'USWI0009', 'name' => 'Alma');
$city_data[] = array('accid' => 'USWI0010', 'name' => 'Alma Center');
$city_data[] = array('accid' => 'USWI0011', 'name' => 'Almena');
$city_data[] = array('accid' => 'USWI0012', 'name' => 'Almond');
$city_data[] = array('accid' => 'USWI0013', 'name' => 'Altoona');
$city_data[] = array('accid' => 'USWI0014', 'name' => 'Amberg');
$city_data[] = array('accid' => 'USWI0015', 'name' => 'Amery');
$city_data[] = array('accid' => 'USWI0016', 'name' => 'Amherst');
$city_data[] = array('accid' => 'USWI0017', 'name' => 'Amherst Junction');
$city_data[] = array('accid' => 'USWI0018', 'name' => 'Aniwa');
$city_data[] = array('accid' => 'USWI0019', 'name' => 'Antigo');
$city_data[] = array('accid' => 'USWI0020', 'name' => 'Appleton');
$city_data[] = array('accid' => 'USWI0021', 'name' => 'Arcadia');
$city_data[] = array('accid' => 'USWI0022', 'name' => 'Arena');
$city_data[] = array('accid' => 'USWI0023', 'name' => 'Argonne');
$city_data[] = array('accid' => 'USWI0024', 'name' => 'Argyle');
$city_data[] = array('accid' => 'USWI0025', 'name' => 'Arkansaw');
$city_data[] = array('accid' => 'USWI0026', 'name' => 'Arkdale');
$city_data[] = array('accid' => 'USWI0027', 'name' => 'Arlington');
$city_data[] = array('accid' => 'USWI0028', 'name' => 'Armstrong Creek');
$city_data[] = array('accid' => 'USWI0029', 'name' => 'Arpin');
$city_data[] = array('accid' => 'USWI0030', 'name' => 'Ashippun');
$city_data[] = array('accid' => 'USWI0031', 'name' => 'Ashland');
$city_data[] = array('accid' => 'USWI0032', 'name' => 'Athelstane');
$city_data[] = array('accid' => 'USWI0033', 'name' => 'Athens');
$city_data[] = array('accid' => 'USWI0034', 'name' => 'Auburndale');
$city_data[] = array('accid' => 'USWI0035', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USWI0036', 'name' => 'Avalon');
$city_data[] = array('accid' => 'USWI0037', 'name' => 'Avoca');
$city_data[] = array('accid' => 'USWI0038', 'name' => 'Babcock');
$city_data[] = array('accid' => 'USWI0039', 'name' => 'Bagley');
$city_data[] = array('accid' => 'USWI0040', 'name' => 'Baileys Harbor');
$city_data[] = array('accid' => 'USWI0041', 'name' => 'Baldwin');
$city_data[] = array('accid' => 'USWI0042', 'name' => 'Balsam Lake');
$city_data[] = array('accid' => 'USWI0043', 'name' => 'Bancroft');
$city_data[] = array('accid' => 'USWI0044', 'name' => 'Bangor');
$city_data[] = array('accid' => 'USWI0045', 'name' => 'Baraboo');
$city_data[] = array('accid' => 'USWI0047', 'name' => 'Barneveld');
$city_data[] = array('accid' => 'USWI0048', 'name' => 'Barron');
$city_data[] = array('accid' => 'USWI0049', 'name' => 'Barronett');
$city_data[] = array('accid' => 'USWI0050', 'name' => 'Bassett');
$city_data[] = array('accid' => 'USWI0051', 'name' => 'Bay City');
$city_data[] = array('accid' => 'USWI0052', 'name' => 'Bayfield');
$city_data[] = array('accid' => 'USWI0053', 'name' => 'Bear Creek');
$city_data[] = array('accid' => 'USWI0054', 'name' => 'Beaver Dam');
$city_data[] = array('accid' => 'USWI0055', 'name' => 'Beetown');
$city_data[] = array('accid' => 'USWI0056', 'name' => 'Beldenville');
$city_data[] = array('accid' => 'USWI0057', 'name' => 'Belgium');
$city_data[] = array('accid' => 'USWI0058', 'name' => 'Belleville');
$city_data[] = array('accid' => 'USWI0059', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USWI0060', 'name' => 'Beloit');
$city_data[] = array('accid' => 'USWI0061', 'name' => 'Benet Lake');
$city_data[] = array('accid' => 'USWI0062', 'name' => 'Benoit');
$city_data[] = array('accid' => 'USWI0063', 'name' => 'Benton');
$city_data[] = array('accid' => 'USWI0064', 'name' => 'Berlin');
$city_data[] = array('accid' => 'USWI0065', 'name' => 'Big Bend');
$city_data[] = array('accid' => 'USWI0066', 'name' => 'Big Falls');
$city_data[] = array('accid' => 'USWI0067', 'name' => 'Birchwood');
$city_data[] = array('accid' => 'USWI0068', 'name' => 'Birnamwood');
$city_data[] = array('accid' => 'USWI0069', 'name' => 'Black Creek');
$city_data[] = array('accid' => 'USWI0070', 'name' => 'Black Earth');
$city_data[] = array('accid' => 'USWI0071', 'name' => 'Black River Falls');
$city_data[] = array('accid' => 'USWI0072', 'name' => 'Blair');
$city_data[] = array('accid' => 'USWI0073', 'name' => 'Blanchardville');
$city_data[] = array('accid' => 'USWI0074', 'name' => 'Blenker');
$city_data[] = array('accid' => 'USWI0075', 'name' => 'Bloomer');
$city_data[] = array('accid' => 'USWI0076', 'name' => 'Bloomington');
$city_data[] = array('accid' => 'USWI0077', 'name' => 'Blue Mounds');
$city_data[] = array('accid' => 'USWI0078', 'name' => 'Blue River');
$city_data[] = array('accid' => 'USWI0079', 'name' => 'Bonduel');
$city_data[] = array('accid' => 'USWI0080', 'name' => 'Boscobel');
$city_data[] = array('accid' => 'USWI0081', 'name' => 'Boulder Junction');
$city_data[] = array('accid' => 'USWI0082', 'name' => 'Bowler');
$city_data[] = array('accid' => 'USWI0083', 'name' => 'Boyceville');
$city_data[] = array('accid' => 'USWI0084', 'name' => 'Boyd');
$city_data[] = array('accid' => 'USWI0085', 'name' => 'Branch');
$city_data[] = array('accid' => 'USWI0086', 'name' => 'Brandon');
$city_data[] = array('accid' => 'USWI0087', 'name' => 'Brantwood');
$city_data[] = array('accid' => 'USWI0088', 'name' => 'Briggsville');
$city_data[] = array('accid' => 'USWI0089', 'name' => 'Brill');
$city_data[] = array('accid' => 'USWI0090', 'name' => 'Brillion');
$city_data[] = array('accid' => 'USWI0091', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USWI0092', 'name' => 'Brodhead');
$city_data[] = array('accid' => 'USWI0093', 'name' => 'Brokaw');
$city_data[] = array('accid' => 'USWI0094', 'name' => 'Brookfield');
$city_data[] = array('accid' => 'USWI0095', 'name' => 'Brooklyn');
$city_data[] = array('accid' => 'USWI0096', 'name' => 'Brownsville');
$city_data[] = array('accid' => 'USWI0097', 'name' => 'Browntown');
$city_data[] = array('accid' => 'USWI0098', 'name' => 'Bruce');
$city_data[] = array('accid' => 'USWI0099', 'name' => 'Brule');
$city_data[] = array('accid' => 'USWI0100', 'name' => 'Brussels');
$city_data[] = array('accid' => 'USWI0101', 'name' => 'Bryant');
$city_data[] = array('accid' => 'USWI0102', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USWI0103', 'name' => 'Burnett');
$city_data[] = array('accid' => 'USWI0104', 'name' => 'Butler');
$city_data[] = array('accid' => 'USWI0105', 'name' => 'Butte Des Morts');
$city_data[] = array('accid' => 'USWI0106', 'name' => 'Butternut');
$city_data[] = array('accid' => 'USWI0107', 'name' => 'Byron');
$city_data[] = array('accid' => 'USWI0108', 'name' => 'Cable');
$city_data[] = array('accid' => 'USWI0109', 'name' => 'Cadott');
$city_data[] = array('accid' => 'USWI0110', 'name' => 'Caledonia');
$city_data[] = array('accid' => 'USWI0111', 'name' => 'Cambria');
$city_data[] = array('accid' => 'USWI0112', 'name' => 'Cambridge');
$city_data[] = array('accid' => 'USWI0113', 'name' => 'Cameron');
$city_data[] = array('accid' => 'USWI0114', 'name' => 'Camp Douglas');
$city_data[] = array('accid' => 'USWI0115', 'name' => 'Camp Lake');
$city_data[] = array('accid' => 'USWI0116', 'name' => 'Campbellsport');
$city_data[] = array('accid' => 'USWI0117', 'name' => 'Caroline');
$city_data[] = array('accid' => 'USWI0118', 'name' => 'Cascade');
$city_data[] = array('accid' => 'USWI0120', 'name' => 'Casco');
$city_data[] = array('accid' => 'USWI0121', 'name' => 'Cashton');
$city_data[] = array('accid' => 'USWI0122', 'name' => 'Cassville');
$city_data[] = array('accid' => 'USWI0123', 'name' => 'Cataract');
$city_data[] = array('accid' => 'USWI0124', 'name' => 'Catawba');
$city_data[] = array('accid' => 'USWI0125', 'name' => 'Cazenovia');
$city_data[] = array('accid' => 'USWI0126', 'name' => 'Cecil');
$city_data[] = array('accid' => 'USWI0127', 'name' => 'Cedar Grove');
$city_data[] = array('accid' => 'USWI0128', 'name' => 'Cedarburg');
$city_data[] = array('accid' => 'USWI0129', 'name' => 'Centuria');
$city_data[] = array('accid' => 'USWI0130', 'name' => 'Chaseburg');
$city_data[] = array('accid' => 'USWI0131', 'name' => 'Chetek');
$city_data[] = array('accid' => 'USWI0132', 'name' => 'Chili');
$city_data[] = array('accid' => 'USWI0133', 'name' => 'Chilton');
$city_data[] = array('accid' => 'USWI0134', 'name' => 'Chippewa Falls');
$city_data[] = array('accid' => 'USWI0135', 'name' => 'Clam Lake');
$city_data[] = array('accid' => 'USWI0136', 'name' => 'Clayton');
$city_data[] = array('accid' => 'USWI0137', 'name' => 'Clear Lake');
$city_data[] = array('accid' => 'USWI0138', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USWI0139', 'name' => 'Clinton');
$city_data[] = array('accid' => 'USWI0140', 'name' => 'Clintonville');
$city_data[] = array('accid' => 'USWI0141', 'name' => 'Clyman');
$city_data[] = array('accid' => 'USWI0142', 'name' => 'Cobb');
$city_data[] = array('accid' => 'USWI0143', 'name' => 'Cochrane');
$city_data[] = array('accid' => 'USWI0144', 'name' => 'Colby');
$city_data[] = array('accid' => 'USWI0145', 'name' => 'Coleman');
$city_data[] = array('accid' => 'USWI0146', 'name' => 'Colfax');
$city_data[] = array('accid' => 'USWI0147', 'name' => 'Colgate');
$city_data[] = array('accid' => 'USWI0148', 'name' => 'Collins');
$city_data[] = array('accid' => 'USWI0149', 'name' => 'Coloma');
$city_data[] = array('accid' => 'USWI0150', 'name' => 'Columbus');
$city_data[] = array('accid' => 'USWI0151', 'name' => 'Combined Locks');
$city_data[] = array('accid' => 'USWI0152', 'name' => 'Comstock');
$city_data[] = array('accid' => 'USWI0153', 'name' => 'Conover');
$city_data[] = array('accid' => 'USWI0154', 'name' => 'Conrath');
$city_data[] = array('accid' => 'USWI0155', 'name' => 'Coon Valley');
$city_data[] = array('accid' => 'USWI0156', 'name' => 'Cornell');
$city_data[] = array('accid' => 'USWI0157', 'name' => 'Cornucopia');
$city_data[] = array('accid' => 'USWI0158', 'name' => 'Cottage Grove');
$city_data[] = array('accid' => 'USWI0159', 'name' => 'Couderay');
$city_data[] = array('accid' => 'USWI0160', 'name' => 'Crandon');
$city_data[] = array('accid' => 'USWI0161', 'name' => 'Crivitz');
$city_data[] = array('accid' => 'USWI0162', 'name' => 'Cross Plains');
$city_data[] = array('accid' => 'USWI0163', 'name' => 'Cuba City');
$city_data[] = array('accid' => 'USWI0164', 'name' => 'Cudahy');
$city_data[] = array('accid' => 'USWI0165', 'name' => 'Cumberland');
$city_data[] = array('accid' => 'USWI0166', 'name' => 'Curtiss');
$city_data[] = array('accid' => 'USWI0167', 'name' => 'Cushing');
$city_data[] = array('accid' => 'USWI0168', 'name' => 'Custer');
$city_data[] = array('accid' => 'USWI0169', 'name' => 'Dale');
$city_data[] = array('accid' => 'USWI0170', 'name' => 'Dallas');
$city_data[] = array('accid' => 'USWI0171', 'name' => 'Dalton');
$city_data[] = array('accid' => 'USWI0172', 'name' => 'Danbury');
$city_data[] = array('accid' => 'USWI0173', 'name' => 'Dane');
$city_data[] = array('accid' => 'USWI0174', 'name' => 'Darien');
$city_data[] = array('accid' => 'USWI0175', 'name' => 'Darlington');
$city_data[] = array('accid' => 'USWI0176', 'name' => 'De Forest');
$city_data[] = array('accid' => 'USWI0177', 'name' => 'De Pere');
$city_data[] = array('accid' => 'USWI0178', 'name' => 'De Soto');
$city_data[] = array('accid' => 'USWI0179', 'name' => 'Deer Park');
$city_data[] = array('accid' => 'USWI0180', 'name' => 'Deerbrook');
$city_data[] = array('accid' => 'USWI0181', 'name' => 'Deerfield');
$city_data[] = array('accid' => 'USWI0182', 'name' => 'Delafield');
$city_data[] = array('accid' => 'USWI0183', 'name' => 'Delavan');
$city_data[] = array('accid' => 'USWI0184', 'name' => 'Dellwood');
$city_data[] = array('accid' => 'USWI0185', 'name' => 'Denmark');
$city_data[] = array('accid' => 'USWI0187', 'name' => 'Dickeyville');
$city_data[] = array('accid' => 'USWI0188', 'name' => 'Dodge');
$city_data[] = array('accid' => 'USWI0189', 'name' => 'Dodgeville');
$city_data[] = array('accid' => 'USWI0190', 'name' => 'Dorchester');
$city_data[] = array('accid' => 'USWI0191', 'name' => 'Dousman');
$city_data[] = array('accid' => 'USWI0192', 'name' => 'Downing');
$city_data[] = array('accid' => 'USWI0193', 'name' => 'Downsville');
$city_data[] = array('accid' => 'USWI0194', 'name' => 'Doylestown');
$city_data[] = array('accid' => 'USWI0195', 'name' => 'Dresser');
$city_data[] = array('accid' => 'USWI0196', 'name' => 'Drummond');
$city_data[] = array('accid' => 'USWI0197', 'name' => 'Dunbar');
$city_data[] = array('accid' => 'USWI0198', 'name' => 'Durand');
$city_data[] = array('accid' => 'USWI0199', 'name' => 'Eagle');
$city_data[] = array('accid' => 'USWI0200', 'name' => 'Eagle River');
$city_data[] = array('accid' => 'USWI0201', 'name' => 'East Ellsworth');
$city_data[] = array('accid' => 'USWI0202', 'name' => 'East Troy');
$city_data[] = array('accid' => 'USWI0203', 'name' => 'Eastman');
$city_data[] = array('accid' => 'USWI0204', 'name' => 'Eau Claire');
$city_data[] = array('accid' => 'USWI0205', 'name' => 'Eau Galle');
$city_data[] = array('accid' => 'USWI0206', 'name' => 'Eden');
$city_data[] = array('accid' => 'USWI0207', 'name' => 'Edgar');
$city_data[] = array('accid' => 'USWI0208', 'name' => 'Edgerton');
$city_data[] = array('accid' => 'USWI0209', 'name' => 'Edgewater');
$city_data[] = array('accid' => 'USWI0210', 'name' => 'Edmund');
$city_data[] = array('accid' => 'USWI0211', 'name' => 'Egg Harbor');
$city_data[] = array('accid' => 'USWI0212', 'name' => 'Eland');
$city_data[] = array('accid' => 'USWI0213', 'name' => 'Elcho');
$city_data[] = array('accid' => 'USWI0214', 'name' => 'Elderon');
$city_data[] = array('accid' => 'USWI0215', 'name' => 'Eldorado');
$city_data[] = array('accid' => 'USWI0216', 'name' => 'Eleva');
$city_data[] = array('accid' => 'USWI0217', 'name' => 'Elk Mound');
$city_data[] = array('accid' => 'USWI0218', 'name' => 'Elkhart Lake');
$city_data[] = array('accid' => 'USWI0219', 'name' => 'Elkhorn');
$city_data[] = array('accid' => 'USWI0220', 'name' => 'Ellison Bay');
$city_data[] = array('accid' => 'USWI0221', 'name' => 'Ellsworth');
$city_data[] = array('accid' => 'USWI0222', 'name' => 'Elm Grove');
$city_data[] = array('accid' => 'USWI0223', 'name' => 'Elmwood');
$city_data[] = array('accid' => 'USWI0224', 'name' => 'Elroy');
$city_data[] = array('accid' => 'USWI0225', 'name' => 'Elton');
$city_data[] = array('accid' => 'USWI0226', 'name' => 'Embarrass');
$city_data[] = array('accid' => 'USWI0227', 'name' => 'Emerald');
$city_data[] = array('accid' => 'USWI0228', 'name' => 'Endeavor');
$city_data[] = array('accid' => 'USWI0229', 'name' => 'Ephraim');
$city_data[] = array('accid' => 'USWI0230', 'name' => 'Ettrick');
$city_data[] = array('accid' => 'USWI0231', 'name' => 'Eureka');
$city_data[] = array('accid' => 'USWI0232', 'name' => 'Evansville');
$city_data[] = array('accid' => 'USWI0233', 'name' => 'Exeland');
$city_data[] = array('accid' => 'USWI0234', 'name' => 'Fairchild');
$city_data[] = array('accid' => 'USWI0235', 'name' => 'Fairwater');
$city_data[] = array('accid' => 'USWI0236', 'name' => 'Fall Creek');
$city_data[] = array('accid' => 'USWI0237', 'name' => 'Fall River');
$city_data[] = array('accid' => 'USWI0238', 'name' => 'Fence');
$city_data[] = array('accid' => 'USWI0239', 'name' => 'Fennimore');
$city_data[] = array('accid' => 'USWI0240', 'name' => 'Ferryville');
$city_data[] = array('accid' => 'USWI0241', 'name' => 'Fifield');
$city_data[] = array('accid' => 'USWI0242', 'name' => 'Fish Creek');
$city_data[] = array('accid' => 'USWI0243', 'name' => 'Florence');
$city_data[] = array('accid' => 'USWI0244', 'name' => 'Fond Du Lac');
$city_data[] = array('accid' => 'USWI0245', 'name' => 'Fontana');
$city_data[] = array('accid' => 'USWI0246', 'name' => 'Footville');
$city_data[] = array('accid' => 'USWI0247', 'name' => 'Forest Junction');
$city_data[] = array('accid' => 'USWI0248', 'name' => 'Forestville');
$city_data[] = array('accid' => 'USWI0249', 'name' => 'Fort Atkinson');
$city_data[] = array('accid' => 'USWI0250', 'name' => 'Fountain City');
$city_data[] = array('accid' => 'USWI0251', 'name' => 'Fox Lake');
$city_data[] = array('accid' => 'USWI0252', 'name' => 'Foxboro');
$city_data[] = array('accid' => 'USWI0253', 'name' => 'Francis Creek');
$city_data[] = array('accid' => 'USWI0254', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USWI0255', 'name' => 'Franksville');
$city_data[] = array('accid' => 'USWI0256', 'name' => 'Frederic');
$city_data[] = array('accid' => 'USWI0257', 'name' => 'Fredonia');
$city_data[] = array('accid' => 'USWI0258', 'name' => 'Freedom');
$city_data[] = array('accid' => 'USWI0259', 'name' => 'Fremont');
$city_data[] = array('accid' => 'USWI0260', 'name' => 'Friendship');
$city_data[] = array('accid' => 'USWI0261', 'name' => 'Friesland');
$city_data[] = array('accid' => 'USWI0262', 'name' => 'Galesville');
$city_data[] = array('accid' => 'USWI0263', 'name' => 'Galloway');
$city_data[] = array('accid' => 'USWI0264', 'name' => 'Gays Mills');
$city_data[] = array('accid' => 'USWI0265', 'name' => 'Genesee Depot');
$city_data[] = array('accid' => 'USWI0266', 'name' => 'Genoa');
$city_data[] = array('accid' => 'USWI0267', 'name' => 'Genoa City');
$city_data[] = array('accid' => 'USWI0268', 'name' => 'Germantown');
$city_data[] = array('accid' => 'USWI0269', 'name' => 'Gile');
$city_data[] = array('accid' => 'USWI0270', 'name' => 'Gillett');
$city_data[] = array('accid' => 'USWI0271', 'name' => 'Gilman');
$city_data[] = array('accid' => 'USWI0272', 'name' => 'Gilmanton');
$city_data[] = array('accid' => 'USWI0273', 'name' => 'Gleason');
$city_data[] = array('accid' => 'USWI0274', 'name' => 'Glen Flora');
$city_data[] = array('accid' => 'USWI0275', 'name' => 'Glen Haven');
$city_data[] = array('accid' => 'USWI0276', 'name' => 'Glenbeulah');
$city_data[] = array('accid' => 'USWI0277', 'name' => 'Glenwood City');
$city_data[] = array('accid' => 'USWI0278', 'name' => 'Glidden');
$city_data[] = array('accid' => 'USWI0279', 'name' => 'Goodman');
$city_data[] = array('accid' => 'USWI0280', 'name' => 'Gordon');
$city_data[] = array('accid' => 'USWI0281', 'name' => 'Gotham');
$city_data[] = array('accid' => 'USWI0282', 'name' => 'Grafton');
$city_data[] = array('accid' => 'USWI0283', 'name' => 'Grand Marsh');
$city_data[] = array('accid' => 'USWI0284', 'name' => 'Grand View');
$city_data[] = array('accid' => 'USWI0285', 'name' => 'Granton');
$city_data[] = array('accid' => 'USWI0286', 'name' => 'Grantsburg');
$city_data[] = array('accid' => 'USWI0287', 'name' => 'Gratiot');
$city_data[] = array('accid' => 'USWI0288', 'name' => 'Green Bay');
$city_data[] = array('accid' => 'USWI0289', 'name' => 'Green Lake');
$city_data[] = array('accid' => 'USWI0290', 'name' => 'Green Valley');
$city_data[] = array('accid' => 'USWI0291', 'name' => 'Greenbush');
$city_data[] = array('accid' => 'USWI0292', 'name' => 'Greendale');
$city_data[] = array('accid' => 'USWI0293', 'name' => 'Greenleaf');
$city_data[] = array('accid' => 'USWI0294', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USWI0295', 'name' => 'Greenwood');
$city_data[] = array('accid' => 'USWI0296', 'name' => 'Gresham');
$city_data[] = array('accid' => 'USWI0297', 'name' => 'Hager City');
$city_data[] = array('accid' => 'USWI0298', 'name' => 'Hales Corners');
$city_data[] = array('accid' => 'USWI0299', 'name' => 'Hammond');
$city_data[] = array('accid' => 'USWI0300', 'name' => 'Hancock');
$city_data[] = array('accid' => 'USWI0301', 'name' => 'Hannibal');
$city_data[] = array('accid' => 'USWI0302', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USWI0303', 'name' => 'Harshaw');
$city_data[] = array('accid' => 'USWI0304', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USWI0305', 'name' => 'Hartland');
$city_data[] = array('accid' => 'USWI0306', 'name' => 'Hatley');
$city_data[] = array('accid' => 'USWI0307', 'name' => 'Haugen');
$city_data[] = array('accid' => 'USWI0308', 'name' => 'Hawkins');
$city_data[] = array('accid' => 'USWI0309', 'name' => 'Hawthorne');
$city_data[] = array('accid' => 'USWI0310', 'name' => 'Hayward');
$city_data[] = array('accid' => 'USWI0311', 'name' => 'Hazel Green');
$city_data[] = array('accid' => 'USWI0312', 'name' => 'Hazelhurst');
$city_data[] = array('accid' => 'USWI0313', 'name' => 'Heafford Junction');
$city_data[] = array('accid' => 'USWI0314', 'name' => 'Helenville');
$city_data[] = array('accid' => 'USWI0315', 'name' => 'Herbster');
$city_data[] = array('accid' => 'USWI0316', 'name' => 'Hertel');
$city_data[] = array('accid' => 'USWI0317', 'name' => 'Hewitt');
$city_data[] = array('accid' => 'USWI0318', 'name' => 'High Bridge');
$city_data[] = array('accid' => 'USWI0319', 'name' => 'Highland');
$city_data[] = array('accid' => 'USWI0320', 'name' => 'Hilbert');
$city_data[] = array('accid' => 'USWI0321', 'name' => 'Hillpoint');
$city_data[] = array('accid' => 'USWI0322', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USWI0323', 'name' => 'Hillsdale');
$city_data[] = array('accid' => 'USWI0324', 'name' => 'Hingham');
$city_data[] = array('accid' => 'USWI0325', 'name' => 'Hixton');
$city_data[] = array('accid' => 'USWI0326', 'name' => 'Holcombe');
$city_data[] = array('accid' => 'USWI0327', 'name' => 'Hollandale');
$city_data[] = array('accid' => 'USWI0328', 'name' => 'Holmen');
$city_data[] = array('accid' => 'USWI0329', 'name' => 'Honey Creek');
$city_data[] = array('accid' => 'USWI0330', 'name' => 'Horicon');
$city_data[] = array('accid' => 'USWI0331', 'name' => 'Hortonville');
$city_data[] = array('accid' => 'USWI0332', 'name' => 'Hubertus');
$city_data[] = array('accid' => 'USWI0333', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USWI0334', 'name' => 'Humbird');
$city_data[] = array('accid' => 'USWI0335', 'name' => 'Hurley');
$city_data[] = array('accid' => 'USWI0336', 'name' => 'Hustisford');
$city_data[] = array('accid' => 'USWI0337', 'name' => 'Hustler');
$city_data[] = array('accid' => 'USWI0338', 'name' => 'Independence');
$city_data[] = array('accid' => 'USWI0339', 'name' => 'Iola');
$city_data[] = array('accid' => 'USWI0340', 'name' => 'Irma');
$city_data[] = array('accid' => 'USWI0341', 'name' => 'Iron Belt');
$city_data[] = array('accid' => 'USWI0342', 'name' => 'Iron Ridge');
$city_data[] = array('accid' => 'USWI0343', 'name' => 'Iron River');
$city_data[] = array('accid' => 'USWI0344', 'name' => 'Ixonia');
$city_data[] = array('accid' => 'USWI0345', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USWI0346', 'name' => 'Janesville');
$city_data[] = array('accid' => 'USWI0347', 'name' => 'Jefferson');
$city_data[] = array('accid' => 'USWI0348', 'name' => 'Jim Falls');
$city_data[] = array('accid' => 'USWI0349', 'name' => 'Johnson Creek');
$city_data[] = array('accid' => 'USWI0350', 'name' => 'Juda');
$city_data[] = array('accid' => 'USWI0351', 'name' => 'Jump River');
$city_data[] = array('accid' => 'USWI0352', 'name' => 'Junction City');
$city_data[] = array('accid' => 'USWI0353', 'name' => 'Juneau');
$city_data[] = array('accid' => 'USWI0354', 'name' => 'Kansasville');
$city_data[] = array('accid' => 'USWI0355', 'name' => 'Kaukauna');
$city_data[] = array('accid' => 'USWI0356', 'name' => 'Kellnersville');
$city_data[] = array('accid' => 'USWI0357', 'name' => 'Kempster');
$city_data[] = array('accid' => 'USWI0358', 'name' => 'Kendall');
$city_data[] = array('accid' => 'USWI0359', 'name' => 'Kennan');
$city_data[] = array('accid' => 'USWI0360', 'name' => 'Kenosha');
$city_data[] = array('accid' => 'USWI0361', 'name' => 'Keshena');
$city_data[] = array('accid' => 'USWI0362', 'name' => 'Kewaskum');
$city_data[] = array('accid' => 'USWI0363', 'name' => 'Kewaunee');
$city_data[] = array('accid' => 'USWI0364', 'name' => 'Kiel');
$city_data[] = array('accid' => 'USWI0365', 'name' => 'Kieler');
$city_data[] = array('accid' => 'USWI0366', 'name' => 'Kimberly');
$city_data[] = array('accid' => 'USWI0367', 'name' => 'King');
$city_data[] = array('accid' => 'USWI0368', 'name' => 'Kingston');
$city_data[] = array('accid' => 'USWI0369', 'name' => 'Knapp');
$city_data[] = array('accid' => 'USWI0370', 'name' => 'Kohler');
$city_data[] = array('accid' => 'USWI0371', 'name' => 'Krakow');
$city_data[] = array('accid' => 'USWI0372', 'name' => 'La Crosse');
$city_data[] = array('accid' => 'USWI0373', 'name' => 'La Farge');
$city_data[] = array('accid' => 'USWI0374', 'name' => 'La Pointe');
$city_data[] = array('accid' => 'USWI0375', 'name' => 'La Valle');
$city_data[] = array('accid' => 'USWI0376', 'name' => 'Lac Du Flambeau');
$city_data[] = array('accid' => 'USWI0377', 'name' => 'Ladysmith');
$city_data[] = array('accid' => 'USWI0378', 'name' => 'Lake Delton');
$city_data[] = array('accid' => 'USWI0379', 'name' => 'Lake Geneva');
$city_data[] = array('accid' => 'USWI0380', 'name' => 'Lake Mills');
$city_data[] = array('accid' => 'USWI0381', 'name' => 'Lake Nebagamon');
$city_data[] = array('accid' => 'USWI0382', 'name' => 'Lake Tomahawk');
$city_data[] = array('accid' => 'USWI0383', 'name' => 'Lakewood');
$city_data[] = array('accid' => 'USWI0384', 'name' => 'Lancaster');
$city_data[] = array('accid' => 'USWI0386', 'name' => 'Lannon');
$city_data[] = array('accid' => 'USWI0387', 'name' => 'Laona');
$city_data[] = array('accid' => 'USWI0388', 'name' => 'Larsen');
$city_data[] = array('accid' => 'USWI0389', 'name' => 'Lebanon');
$city_data[] = array('accid' => 'USWI0390', 'name' => 'Lena');
$city_data[] = array('accid' => 'USWI0391', 'name' => 'Leopolis');
$city_data[] = array('accid' => 'USWI0392', 'name' => 'Lewis');
$city_data[] = array('accid' => 'USWI0393', 'name' => 'Lime Ridge');
$city_data[] = array('accid' => 'USWI0394', 'name' => 'Linden');
$city_data[] = array('accid' => 'USWI0395', 'name' => 'Little Chute');
$city_data[] = array('accid' => 'USWI0396', 'name' => 'Little Suamico');
$city_data[] = array('accid' => 'USWI0397', 'name' => 'Livingston');
$city_data[] = array('accid' => 'USWI0398', 'name' => 'Lodi');
$city_data[] = array('accid' => 'USWI0399', 'name' => 'Loganville');
$city_data[] = array('accid' => 'USWI0400', 'name' => 'Lomira');
$city_data[] = array('accid' => 'USWI0401', 'name' => 'Lone Rock');
$city_data[] = array('accid' => 'USWI0402', 'name' => 'Long Lake');
$city_data[] = array('accid' => 'USWI0403', 'name' => 'Lowell');
$city_data[] = array('accid' => 'USWI0404', 'name' => 'Loyal');
$city_data[] = array('accid' => 'USWI0405', 'name' => 'Lublin');
$city_data[] = array('accid' => 'USWI0406', 'name' => 'Luck');
$city_data[] = array('accid' => 'USWI0407', 'name' => 'Luxemburg');
$city_data[] = array('accid' => 'USWI0408', 'name' => 'Lyndon Station');
$city_data[] = array('accid' => 'USWI0409', 'name' => 'Lynxville');
$city_data[] = array('accid' => 'USWI0410', 'name' => 'Lyons');
$city_data[] = array('accid' => 'USWI0411', 'name' => 'Madison');
$city_data[] = array('accid' => 'USWI0412', 'name' => 'Maiden Rock');
$city_data[] = array('accid' => 'USWI0413', 'name' => 'Malone');
$city_data[] = array('accid' => 'USWI0414', 'name' => 'Manawa');
$city_data[] = array('accid' => 'USWI0415', 'name' => 'Manitowish Waters');
$city_data[] = array('accid' => 'USWI0416', 'name' => 'Manitowoc');
$city_data[] = array('accid' => 'USWI0417', 'name' => 'Maple');
$city_data[] = array('accid' => 'USWI0418', 'name' => 'Maplewood');
$city_data[] = array('accid' => 'USWI0419', 'name' => 'Marathon');
$city_data[] = array('accid' => 'USWI0420', 'name' => 'Marengo');
$city_data[] = array('accid' => 'USWI0421', 'name' => 'Maribel');
$city_data[] = array('accid' => 'USWI0422', 'name' => 'Marinette');
$city_data[] = array('accid' => 'USWI0423', 'name' => 'Marion');
$city_data[] = array('accid' => 'USWI0424', 'name' => 'Markesan');
$city_data[] = array('accid' => 'USWI0425', 'name' => 'Marquette');
$city_data[] = array('accid' => 'USWI0426', 'name' => 'Marshall');
$city_data[] = array('accid' => 'USWI0427', 'name' => 'Marshfield');
$city_data[] = array('accid' => 'USWI0428', 'name' => 'Mason');
$city_data[] = array('accid' => 'USWI0429', 'name' => 'Mather');
$city_data[] = array('accid' => 'USWI0430', 'name' => 'Mattoon');
$city_data[] = array('accid' => 'USWI0431', 'name' => 'Mauston');
$city_data[] = array('accid' => 'USWI0432', 'name' => 'Mayville');
$city_data[] = array('accid' => 'USWI0433', 'name' => 'Mazomanie');
$city_data[] = array('accid' => 'USWI0434', 'name' => 'McFarland');
$city_data[] = array('accid' => 'USWI0435', 'name' => 'McNaughton');
$city_data[] = array('accid' => 'USWI0436', 'name' => 'Medford');
$city_data[] = array('accid' => 'USWI0437', 'name' => 'Medina');
$city_data[] = array('accid' => 'USWI0438', 'name' => 'Mellen');
$city_data[] = array('accid' => 'USWI0439', 'name' => 'Melrose');
$city_data[] = array('accid' => 'USWI0440', 'name' => 'Menasha');
$city_data[] = array('accid' => 'USWI0441', 'name' => 'Menomonee Falls');
$city_data[] = array('accid' => 'USWI0442', 'name' => 'Menomonie');
$city_data[] = array('accid' => 'USWI0443', 'name' => 'Mequon');
$city_data[] = array('accid' => 'USWI0444', 'name' => 'Mercer');
$city_data[] = array('accid' => 'USWI0445', 'name' => 'Merrill');
$city_data[] = array('accid' => 'USWI0446', 'name' => 'Merrillan');
$city_data[] = array('accid' => 'USWI0447', 'name' => 'Merrimac');
$city_data[] = array('accid' => 'USWI0448', 'name' => 'Merton');
$city_data[] = array('accid' => 'USWI0449', 'name' => 'Middleton');
$city_data[] = array('accid' => 'USWI0450', 'name' => 'Mikana');
$city_data[] = array('accid' => 'USWI0451', 'name' => 'Milladore');
$city_data[] = array('accid' => 'USWI0452', 'name' => 'Millston');
$city_data[] = array('accid' => 'USWI0453', 'name' => 'Milltown');
$city_data[] = array('accid' => 'USWI0454', 'name' => 'Milton');
$city_data[] = array('accid' => 'USWI0455', 'name' => 'Milwaukee');
$city_data[] = array('accid' => 'USWI0456', 'name' => 'Mindoro');
$city_data[] = array('accid' => 'USWI0457', 'name' => 'Mineral Point');
$city_data[] = array('accid' => 'USWI0458', 'name' => 'Minocqua');
$city_data[] = array('accid' => 'USWI0459', 'name' => 'Minong');
$city_data[] = array('accid' => 'USWI0460', 'name' => 'Mishicot');
$city_data[] = array('accid' => 'USWI0461', 'name' => 'Mondovi');
$city_data[] = array('accid' => 'USWI0462', 'name' => 'Monroe');
$city_data[] = array('accid' => 'USWI0463', 'name' => 'Montello');
$city_data[] = array('accid' => 'USWI0464', 'name' => 'Montfort');
$city_data[] = array('accid' => 'USWI0465', 'name' => 'Monticello');
$city_data[] = array('accid' => 'USWI0466', 'name' => 'Montreal');
$city_data[] = array('accid' => 'USWI0467', 'name' => 'Morrisonville');
$city_data[] = array('accid' => 'USWI0468', 'name' => 'Mosinee');
$city_data[] = array('accid' => 'USWI0469', 'name' => 'Mount Calvary');
$city_data[] = array('accid' => 'USWI0470', 'name' => 'Mount Hope');
$city_data[] = array('accid' => 'USWI0471', 'name' => 'Mount Horeb');
$city_data[] = array('accid' => 'USWI0473', 'name' => 'Mount Sterling');
$city_data[] = array('accid' => 'USWI0474', 'name' => 'Mountain');
$city_data[] = array('accid' => 'USWI0475', 'name' => 'Mukwonago');
$city_data[] = array('accid' => 'USWI0476', 'name' => 'Muscoda');
$city_data[] = array('accid' => 'USWI0477', 'name' => 'Muskego');
$city_data[] = array('accid' => 'USWI0478', 'name' => 'Nashotah');
$city_data[] = array('accid' => 'USWI0479', 'name' => 'Necedah');
$city_data[] = array('accid' => 'USWI0480', 'name' => 'Neenah');
$city_data[] = array('accid' => 'USWI0481', 'name' => 'Neillsville');
$city_data[] = array('accid' => 'USWI0482', 'name' => 'Nekoosa');
$city_data[] = array('accid' => 'USWI0483', 'name' => 'Nelson');
$city_data[] = array('accid' => 'USWI0484', 'name' => 'Nelsonville');
$city_data[] = array('accid' => 'USWI0485', 'name' => 'Neopit');
$city_data[] = array('accid' => 'USWI0486', 'name' => 'Neosho');
$city_data[] = array('accid' => 'USWI0487', 'name' => 'Neshkoro');
$city_data[] = array('accid' => 'USWI0488', 'name' => 'New Auburn');
$city_data[] = array('accid' => 'USWI0489', 'name' => 'New Berlin');
$city_data[] = array('accid' => 'USWI0490', 'name' => 'New Franken');
$city_data[] = array('accid' => 'USWI0491', 'name' => 'New Glarus');
$city_data[] = array('accid' => 'USWI0492', 'name' => 'New Holstein');
$city_data[] = array('accid' => 'USWI0493', 'name' => 'New Lisbon');
$city_data[] = array('accid' => 'USWI0494', 'name' => 'New London');
$city_data[] = array('accid' => 'USWI0495', 'name' => 'New Munster');
$city_data[] = array('accid' => 'USWI0496', 'name' => 'New Richmond');
$city_data[] = array('accid' => 'USWI0497', 'name' => 'Newburg');
$city_data[] = array('accid' => 'USWI0498', 'name' => 'Newton');
$city_data[] = array('accid' => 'USWI0499', 'name' => 'Niagara');
$city_data[] = array('accid' => 'USWI0500', 'name' => 'Nichols');
$city_data[] = array('accid' => 'USWI0501', 'name' => 'North Freedom');
$city_data[] = array('accid' => 'USWI0502', 'name' => 'North Lake');
$city_data[] = array('accid' => 'USWI0503', 'name' => 'North Prairie');
$city_data[] = array('accid' => 'USWI0504', 'name' => 'Norwalk');
$city_data[] = array('accid' => 'USWI0505', 'name' => 'Oak Creek');
$city_data[] = array('accid' => 'USWI0506', 'name' => 'Oakdale');
$city_data[] = array('accid' => 'USWI0507', 'name' => 'Oakfield');
$city_data[] = array('accid' => 'USWI0508', 'name' => 'Oconomowoc');
$city_data[] = array('accid' => 'USWI0509', 'name' => 'Oconto');
$city_data[] = array('accid' => 'USWI0510', 'name' => 'Oconto Falls');
$city_data[] = array('accid' => 'USWI0511', 'name' => 'Odanah');
$city_data[] = array('accid' => 'USWI0512', 'name' => 'Ogdensburg');
$city_data[] = array('accid' => 'USWI0513', 'name' => 'Ogema');
$city_data[] = array('accid' => 'USWI0514', 'name' => 'Ojibwa');
$city_data[] = array('accid' => 'USWI0515', 'name' => 'Okauchee');
$city_data[] = array('accid' => 'USWI0516', 'name' => 'Omro');
$city_data[] = array('accid' => 'USWI0517', 'name' => 'Onalaska');
$city_data[] = array('accid' => 'USWI0518', 'name' => 'Oneida');
$city_data[] = array('accid' => 'USWI0519', 'name' => 'Ontario');
$city_data[] = array('accid' => 'USWI0520', 'name' => 'Oostburg');
$city_data[] = array('accid' => 'USWI0521', 'name' => 'Oregon');
$city_data[] = array('accid' => 'USWI0522', 'name' => 'Orfordville');
$city_data[] = array('accid' => 'USWI0523', 'name' => 'Osceola');
$city_data[] = array('accid' => 'USWI0524', 'name' => 'Oshkosh');
$city_data[] = array('accid' => 'USWI0525', 'name' => 'Osseo');
$city_data[] = array('accid' => 'USWI0526', 'name' => 'Owen');
$city_data[] = array('accid' => 'USWI0527', 'name' => 'Oxford');
$city_data[] = array('accid' => 'USWI0528', 'name' => 'Packwaukee');
$city_data[] = array('accid' => 'USWI0529', 'name' => 'Palmyra');
$city_data[] = array('accid' => 'USWI0530', 'name' => 'Pardeeville');
$city_data[] = array('accid' => 'USWI0531', 'name' => 'Park Falls');
$city_data[] = array('accid' => 'USWI0532', 'name' => 'Patch Grove');
$city_data[] = array('accid' => 'USWI0533', 'name' => 'Pearson');
$city_data[] = array('accid' => 'USWI0534', 'name' => 'Pelican Lake');
$city_data[] = array('accid' => 'USWI0535', 'name' => 'Pell Lake');
$city_data[] = array('accid' => 'USWI0536', 'name' => 'Pembine');
$city_data[] = array('accid' => 'USWI0537', 'name' => 'Pepin');
$city_data[] = array('accid' => 'USWI0538', 'name' => 'Peshtigo');
$city_data[] = array('accid' => 'USWI0539', 'name' => 'Pewaukee');
$city_data[] = array('accid' => 'USWI0540', 'name' => 'Phelps');
$city_data[] = array('accid' => 'USWI0541', 'name' => 'Phillips');
$city_data[] = array('accid' => 'USWI0542', 'name' => 'Phlox');
$city_data[] = array('accid' => 'USWI0543', 'name' => 'Pickerel');
$city_data[] = array('accid' => 'USWI0544', 'name' => 'Pickett');
$city_data[] = array('accid' => 'USWI0545', 'name' => 'Pigeon Falls');
$city_data[] = array('accid' => 'USWI0546', 'name' => 'Pine River');
$city_data[] = array('accid' => 'USWI0547', 'name' => 'Pittsville');
$city_data[] = array('accid' => 'USWI0548', 'name' => 'Plain');
$city_data[] = array('accid' => 'USWI0549', 'name' => 'Plainfield');
$city_data[] = array('accid' => 'USWI0550', 'name' => 'Platteville');
$city_data[] = array('accid' => 'USWI0551', 'name' => 'Pleasant Prairie');
$city_data[] = array('accid' => 'USWI0552', 'name' => 'Plover');
$city_data[] = array('accid' => 'USWI0553', 'name' => 'Plum City');
$city_data[] = array('accid' => 'USWI0554', 'name' => 'Plymouth');
$city_data[] = array('accid' => 'USWI0555', 'name' => 'Poplar');
$city_data[] = array('accid' => 'USWI0556', 'name' => 'Port Edwards');
$city_data[] = array('accid' => 'USWI0557', 'name' => 'Port Washington');
$city_data[] = array('accid' => 'USWI0558', 'name' => 'Port Wing');
$city_data[] = array('accid' => 'USWI0559', 'name' => 'Portage');
$city_data[] = array('accid' => 'USWI0560', 'name' => 'Porterfield');
$city_data[] = array('accid' => 'USWI0561', 'name' => 'Potosi');
$city_data[] = array('accid' => 'USWI0562', 'name' => 'Potter');
$city_data[] = array('accid' => 'USWI0563', 'name' => 'Pound');
$city_data[] = array('accid' => 'USWI0564', 'name' => 'Powers Lake');
$city_data[] = array('accid' => 'USWI0565', 'name' => 'Poy Sippi');
$city_data[] = array('accid' => 'USWI0566', 'name' => 'Poynette');
$city_data[] = array('accid' => 'USWI0567', 'name' => 'Prairie Du Chien');
$city_data[] = array('accid' => 'USWI0568', 'name' => 'Prairie Du Sac');
$city_data[] = array('accid' => 'USWI0569', 'name' => 'Prairie Farm');
$city_data[] = array('accid' => 'USWI0570', 'name' => 'Prentice');
$city_data[] = array('accid' => 'USWI0571', 'name' => 'Prescott');
$city_data[] = array('accid' => 'USWI0572', 'name' => 'Presque Isle');
$city_data[] = array('accid' => 'USWI0573', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USWI0574', 'name' => 'Pulaski');
$city_data[] = array('accid' => 'USWI0575', 'name' => 'Racine');
$city_data[] = array('accid' => 'USWI0576', 'name' => 'Radisson');
$city_data[] = array('accid' => 'USWI0577', 'name' => 'Randolph');
$city_data[] = array('accid' => 'USWI0578', 'name' => 'Random Lake');
$city_data[] = array('accid' => 'USWI0579', 'name' => 'Readfield');
$city_data[] = array('accid' => 'USWI0580', 'name' => 'Readstown');
$city_data[] = array('accid' => 'USWI0581', 'name' => 'Redgranite');
$city_data[] = array('accid' => 'USWI0582', 'name' => 'Reedsburg');
$city_data[] = array('accid' => 'USWI0583', 'name' => 'Reedsville');
$city_data[] = array('accid' => 'USWI0584', 'name' => 'Reeseville');
$city_data[] = array('accid' => 'USWI0585', 'name' => 'Rewey');
$city_data[] = array('accid' => 'USWI0586', 'name' => 'Rhinelander');
$city_data[] = array('accid' => 'USWI0587', 'name' => 'Rib Lake');
$city_data[] = array('accid' => 'USWI0588', 'name' => 'Rice Lake');
$city_data[] = array('accid' => 'USWI0589', 'name' => 'Richfield');
$city_data[] = array('accid' => 'USWI0590', 'name' => 'Richland Center');
$city_data[] = array('accid' => 'USWI0591', 'name' => 'Ridgeland');
$city_data[] = array('accid' => 'USWI0592', 'name' => 'Ridgeway');
$city_data[] = array('accid' => 'USWI0593', 'name' => 'Ringle');
$city_data[] = array('accid' => 'USWI0594', 'name' => 'Rio');
$city_data[] = array('accid' => 'USWI0595', 'name' => 'Ripon');
$city_data[] = array('accid' => 'USWI0596', 'name' => 'River Falls');
$city_data[] = array('accid' => 'USWI0597', 'name' => 'Roberts');
$city_data[] = array('accid' => 'USWI0598', 'name' => 'Rochester');
$city_data[] = array('accid' => 'USWI0599', 'name' => 'Rock Falls');
$city_data[] = array('accid' => 'USWI0600', 'name' => 'Rock Springs');
$city_data[] = array('accid' => 'USWI0601', 'name' => 'Rockland');
$city_data[] = array('accid' => 'USWI0602', 'name' => 'Rosendale');
$city_data[] = array('accid' => 'USWI0603', 'name' => 'Rosholt');
$city_data[] = array('accid' => 'USWI0604', 'name' => 'Rothschild');
$city_data[] = array('accid' => 'USWI0605', 'name' => 'Royalton');
$city_data[] = array('accid' => 'USWI0606', 'name' => 'Rubicon');
$city_data[] = array('accid' => 'USWI0607', 'name' => 'Rudolph');
$city_data[] = array('accid' => 'USWI0608', 'name' => 'Saint Cloud');
$city_data[] = array('accid' => 'USWI0609', 'name' => 'Saint Croix Falls');
$city_data[] = array('accid' => 'USWI0610', 'name' => 'Saint Francis');
$city_data[] = array('accid' => 'USWI0611', 'name' => 'Saint Germain');
$city_data[] = array('accid' => 'USWI0612', 'name' => 'Saint Joseph');
$city_data[] = array('accid' => 'USWI0613', 'name' => 'Saint Nazianz');
$city_data[] = array('accid' => 'USWI0614', 'name' => 'Salem');
$city_data[] = array('accid' => 'USWI0615', 'name' => 'Sand Creek');
$city_data[] = array('accid' => 'USWI0616', 'name' => 'Sarona');
$city_data[] = array('accid' => 'USWI0617', 'name' => 'Sauk City');
$city_data[] = array('accid' => 'USWI0618', 'name' => 'Saukville');
$city_data[] = array('accid' => 'USWI0619', 'name' => 'Saxeville');
$city_data[] = array('accid' => 'USWI0620', 'name' => 'Saxon');
$city_data[] = array('accid' => 'USWI0621', 'name' => 'Sayner');
$city_data[] = array('accid' => 'USWI0622', 'name' => 'Scandinavia');
$city_data[] = array('accid' => 'USWI0623', 'name' => 'Schofield');
$city_data[] = array('accid' => 'USWI0624', 'name' => 'Seneca');
$city_data[] = array('accid' => 'USWI0625', 'name' => 'Sextonville');
$city_data[] = array('accid' => 'USWI0626', 'name' => 'Seymour');
$city_data[] = array('accid' => 'USWI0627', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USWI0628', 'name' => 'Shawano');
$city_data[] = array('accid' => 'USWI0629', 'name' => 'Sheboygan');
$city_data[] = array('accid' => 'USWI0630', 'name' => 'Sheboygan Falls');
$city_data[] = array('accid' => 'USWI0631', 'name' => 'Sheldon');
$city_data[] = array('accid' => 'USWI0632', 'name' => 'Shell Lake');
$city_data[] = array('accid' => 'USWI0633', 'name' => 'Sherwood');
$city_data[] = array('accid' => 'USWI0634', 'name' => 'Shiocton');
$city_data[] = array('accid' => 'USWI0635', 'name' => 'Shullsburg');
$city_data[] = array('accid' => 'USWI0636', 'name' => 'Silver Lake');
$city_data[] = array('accid' => 'USWI0637', 'name' => 'Sinsinawa');
$city_data[] = array('accid' => 'USWI0638', 'name' => 'Siren');
$city_data[] = array('accid' => 'USWI0639', 'name' => 'Sister Bay');
$city_data[] = array('accid' => 'USWI0640', 'name' => 'Slinger');
$city_data[] = array('accid' => 'USWI0641', 'name' => 'Sobieski');
$city_data[] = array('accid' => 'USWI0642', 'name' => 'Soldiers Grove');
$city_data[] = array('accid' => 'USWI0643', 'name' => 'Solon Springs');
$city_data[] = array('accid' => 'USWI0644', 'name' => 'Somers');
$city_data[] = array('accid' => 'USWI0645', 'name' => 'Somerset');
$city_data[] = array('accid' => 'USWI0646', 'name' => 'South Milwaukee');
$city_data[] = array('accid' => 'USWI0647', 'name' => 'South Range');
$city_data[] = array('accid' => 'USWI0648', 'name' => 'South Wayne');
$city_data[] = array('accid' => 'USWI0649', 'name' => 'Sparta');
$city_data[] = array('accid' => 'USWI0650', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USWI0651', 'name' => 'Spooner');
$city_data[] = array('accid' => 'USWI0652', 'name' => 'Spring Green');
$city_data[] = array('accid' => 'USWI0653', 'name' => 'Spring Valley');
$city_data[] = array('accid' => 'USWI0654', 'name' => 'Springbrook');
$city_data[] = array('accid' => 'USWI0655', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USWI0656', 'name' => 'Stanley');
$city_data[] = array('accid' => 'USWI0657', 'name' => 'Star Lake');
$city_data[] = array('accid' => 'USWI0658', 'name' => 'Star Prairie');
$city_data[] = array('accid' => 'USWI0659', 'name' => 'Stetsonville');
$city_data[] = array('accid' => 'USWI0660', 'name' => 'Steuben');
$city_data[] = array('accid' => 'USWI0661', 'name' => 'Stevens Point');
$city_data[] = array('accid' => 'USWI0662', 'name' => 'Stitzer');
$city_data[] = array('accid' => 'USWI0663', 'name' => 'Stockbridge');
$city_data[] = array('accid' => 'USWI0664', 'name' => 'Stockholm');
$city_data[] = array('accid' => 'USWI0665', 'name' => 'Stoddard');
$city_data[] = array('accid' => 'USWI0666', 'name' => 'Stone Lake');
$city_data[] = array('accid' => 'USWI0667', 'name' => 'Stoughton');
$city_data[] = array('accid' => 'USWI0668', 'name' => 'Stratford');
$city_data[] = array('accid' => 'USWI0669', 'name' => 'Strum');
$city_data[] = array('accid' => 'USWI0670', 'name' => 'Sturgeon Bay');
$city_data[] = array('accid' => 'USWI0671', 'name' => 'Sturtevant');
$city_data[] = array('accid' => 'USWI0672', 'name' => 'Suamico');
$city_data[] = array('accid' => 'USWI0673', 'name' => 'Sullivan');
$city_data[] = array('accid' => 'USWI0674', 'name' => 'Summit Lake');
$city_data[] = array('accid' => 'USWI0675', 'name' => 'Sun Prairie');
$city_data[] = array('accid' => 'USWI0676', 'name' => 'Superior');
$city_data[] = array('accid' => 'USWI0677', 'name' => 'Suring');
$city_data[] = array('accid' => 'USWI0678', 'name' => 'Sussex');
$city_data[] = array('accid' => 'USWI0679', 'name' => 'Taylor');
$city_data[] = array('accid' => 'USWI0681', 'name' => 'Theresa');
$city_data[] = array('accid' => 'USWI0682', 'name' => 'Thiensville');
$city_data[] = array('accid' => 'USWI0683', 'name' => 'Thorp');
$city_data[] = array('accid' => 'USWI0684', 'name' => 'Three Lakes');
$city_data[] = array('accid' => 'USWI0685', 'name' => 'Tigerton');
$city_data[] = array('accid' => 'USWI0686', 'name' => 'Tilleda');
$city_data[] = array('accid' => 'USWI0687', 'name' => 'Tisch Mills');
$city_data[] = array('accid' => 'USWI0688', 'name' => 'Tomah');
$city_data[] = array('accid' => 'USWI0689', 'name' => 'Tomahawk');
$city_data[] = array('accid' => 'USWI0690', 'name' => 'Tony');
$city_data[] = array('accid' => 'USWI0691', 'name' => 'Townsend');
$city_data[] = array('accid' => 'USWI0692', 'name' => 'Trego');
$city_data[] = array('accid' => 'USWI0693', 'name' => 'Trempealeau');
$city_data[] = array('accid' => 'USWI0694', 'name' => 'Trevor');
$city_data[] = array('accid' => 'USWI0695', 'name' => 'Tripoli');
$city_data[] = array('accid' => 'USWI0696', 'name' => 'Tunnel City');
$city_data[] = array('accid' => 'USWI0697', 'name' => 'Turtle Lake');
$city_data[] = array('accid' => 'USWI0698', 'name' => 'Twin Lakes');
$city_data[] = array('accid' => 'USWI0699', 'name' => 'Two Rivers');
$city_data[] = array('accid' => 'USWI0700', 'name' => 'Union Center');
$city_data[] = array('accid' => 'USWI0701', 'name' => 'Union Grove');
$city_data[] = array('accid' => 'USWI0702', 'name' => 'Unity');
$city_data[] = array('accid' => 'USWI0703', 'name' => 'Upson');
$city_data[] = array('accid' => 'USWI0704', 'name' => 'Valders');
$city_data[] = array('accid' => 'USWI0705', 'name' => 'Van Dyne');
$city_data[] = array('accid' => 'USWI0706', 'name' => 'Verona');
$city_data[] = array('accid' => 'USWI0707', 'name' => 'Vesper');
$city_data[] = array('accid' => 'USWI0708', 'name' => 'Viola');
$city_data[] = array('accid' => 'USWI0709', 'name' => 'Viroqua');
$city_data[] = array('accid' => 'USWI0711', 'name' => 'Wabeno');
$city_data[] = array('accid' => 'USWI0712', 'name' => 'Waldo');
$city_data[] = array('accid' => 'USWI0713', 'name' => 'Wales');
$city_data[] = array('accid' => 'USWI0714', 'name' => 'Walworth');
$city_data[] = array('accid' => 'USWI0715', 'name' => 'Warrens');
$city_data[] = array('accid' => 'USWI0716', 'name' => 'Wascott');
$city_data[] = array('accid' => 'USWI0717', 'name' => 'Washburn');
$city_data[] = array('accid' => 'USWI0718', 'name' => 'Washington Island');
$city_data[] = array('accid' => 'USWI0719', 'name' => 'Waterford');
$city_data[] = array('accid' => 'USWI0720', 'name' => 'Waterloo');
$city_data[] = array('accid' => 'USWI0721', 'name' => 'Watertown');
$city_data[] = array('accid' => 'USWI0722', 'name' => 'Waukau');
$city_data[] = array('accid' => 'USWI0723', 'name' => 'Waukesha');
$city_data[] = array('accid' => 'USWI0724', 'name' => 'Waunakee');
$city_data[] = array('accid' => 'USWI0725', 'name' => 'Waupaca');
$city_data[] = array('accid' => 'USWI0726', 'name' => 'Waupun');
$city_data[] = array('accid' => 'USWI0727', 'name' => 'Wausau');
$city_data[] = array('accid' => 'USWI0728', 'name' => 'Wausaukee');
$city_data[] = array('accid' => 'USWI0729', 'name' => 'Wautoma');
$city_data[] = array('accid' => 'USWI0731', 'name' => 'Wauzeka');
$city_data[] = array('accid' => 'USWI0732', 'name' => 'Webster');
$city_data[] = array('accid' => 'USWI0733', 'name' => 'West Bend');
$city_data[] = array('accid' => 'USWI0734', 'name' => 'West Salem');
$city_data[] = array('accid' => 'USWI0735', 'name' => 'Westboro');
$city_data[] = array('accid' => 'USWI0736', 'name' => 'Westby');
$city_data[] = array('accid' => 'USWI0737', 'name' => 'Westfield');
$city_data[] = array('accid' => 'USWI0738', 'name' => 'Weyauwega');
$city_data[] = array('accid' => 'USWI0739', 'name' => 'Weyerhaeuser');
$city_data[] = array('accid' => 'USWI0740', 'name' => 'Wheeler');
$city_data[] = array('accid' => 'USWI0741', 'name' => 'White Lake');
$city_data[] = array('accid' => 'USWI0743', 'name' => 'Whitehall');
$city_data[] = array('accid' => 'USWI0744', 'name' => 'Whitelaw');
$city_data[] = array('accid' => 'USWI0745', 'name' => 'Whitewater');
$city_data[] = array('accid' => 'USWI0746', 'name' => 'Wild Rose');
$city_data[] = array('accid' => 'USWI0747', 'name' => 'Willard');
$city_data[] = array('accid' => 'USWI0748', 'name' => 'Williams Bay');
$city_data[] = array('accid' => 'USWI0749', 'name' => 'Wilmot');
$city_data[] = array('accid' => 'USWI0750', 'name' => 'Wilson');
$city_data[] = array('accid' => 'USWI0751', 'name' => 'Wilton');
$city_data[] = array('accid' => 'USWI0752', 'name' => 'Windsor');
$city_data[] = array('accid' => 'USWI0753', 'name' => 'Winnebago');
$city_data[] = array('accid' => 'USWI0754', 'name' => 'Winneconne');
$city_data[] = array('accid' => 'USWI0755', 'name' => 'Winter');
$city_data[] = array('accid' => 'USWI0756', 'name' => 'Wisconsin Dells');
$city_data[] = array('accid' => 'USWI0757', 'name' => 'Wisconsin Rapids');
$city_data[] = array('accid' => 'USWI0758', 'name' => 'Withee');
$city_data[] = array('accid' => 'USWI0759', 'name' => 'Wittenberg');
$city_data[] = array('accid' => 'USWI0760', 'name' => 'Wonewoc');
$city_data[] = array('accid' => 'USWI0761', 'name' => 'Woodford');
$city_data[] = array('accid' => 'USWI0762', 'name' => 'Woodland');
$city_data[] = array('accid' => 'USWI0763', 'name' => 'Woodman');
$city_data[] = array('accid' => 'USWI0764', 'name' => 'Woodruff');
$city_data[] = array('accid' => 'USWI0765', 'name' => 'Woodville');
$city_data[] = array('accid' => 'USWI0766', 'name' => 'Woodworth');
$city_data[] = array('accid' => 'USWI0767', 'name' => 'Wrightstown');
$city_data[] = array('accid' => 'USWI0768', 'name' => 'Wyocena');
$city_data[] = array('accid' => 'USWI0769', 'name' => 'Zachow');
$city_data[] = array('accid' => 'USWI0770', 'name' => 'Zenda');

?>
