<?php

// City package for USA: West Virginia 

$city_name = 'USA: West Virginia';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USWV0001', 'name' => 'Accoville');
$city_data[] = array('accid' => 'USWV0002', 'name' => 'Adrian');
$city_data[] = array('accid' => 'USWV0003', 'name' => 'Advent');
$city_data[] = array('accid' => 'USWV0004', 'name' => 'Albright');
$city_data[] = array('accid' => 'USWV0005', 'name' => 'Alderson');
$city_data[] = array('accid' => 'USWV0006', 'name' => 'Alkol');
$city_data[] = array('accid' => 'USWV0007', 'name' => 'Allen Junction');
$city_data[] = array('accid' => 'USWV0008', 'name' => 'Alloy');
$city_data[] = array('accid' => 'USWV0009', 'name' => 'Alma');
$city_data[] = array('accid' => 'USWV0010', 'name' => 'Alpoca');
$city_data[] = array('accid' => 'USWV0011', 'name' => 'Alum Bridge');
$city_data[] = array('accid' => 'USWV0012', 'name' => 'Alum Creek');
$city_data[] = array('accid' => 'USWV0013', 'name' => 'Ameagle');
$city_data[] = array('accid' => 'USWV0014', 'name' => 'Amherstdale');
$city_data[] = array('accid' => 'USWV0015', 'name' => 'Amigo');
$city_data[] = array('accid' => 'USWV0016', 'name' => 'Amma');
$city_data[] = array('accid' => 'USWV0017', 'name' => 'Anawalt');
$city_data[] = array('accid' => 'USWV0018', 'name' => 'Anmoore');
$city_data[] = array('accid' => 'USWV0019', 'name' => 'Ansted');
$city_data[] = array('accid' => 'USWV0020', 'name' => 'Apple Grove');
$city_data[] = array('accid' => 'USWV0021', 'name' => 'Arbovale');
$city_data[] = array('accid' => 'USWV0022', 'name' => 'Arnett');
$city_data[] = array('accid' => 'USWV0023', 'name' => 'Arnoldsburg');
$city_data[] = array('accid' => 'USWV0024', 'name' => 'Arthurdale');
$city_data[] = array('accid' => 'USWV0025', 'name' => 'Artie');
$city_data[] = array('accid' => 'USWV0026', 'name' => 'Asbury');
$city_data[] = array('accid' => 'USWV0027', 'name' => 'Ashford');
$city_data[] = array('accid' => 'USWV0028', 'name' => 'Ashton');
$city_data[] = array('accid' => 'USWV0029', 'name' => 'Athens');
$city_data[] = array('accid' => 'USWV0030', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USWV0031', 'name' => 'Augusta');
$city_data[] = array('accid' => 'USWV0032', 'name' => 'Aurora');
$city_data[] = array('accid' => 'USWV0033', 'name' => 'Auto');
$city_data[] = array('accid' => 'USWV0034', 'name' => 'Avondale');
$city_data[] = array('accid' => 'USWV0035', 'name' => 'Baisden');
$city_data[] = array('accid' => 'USWV0036', 'name' => 'Baker');
$city_data[] = array('accid' => 'USWV0037', 'name' => 'Bakerton');
$city_data[] = array('accid' => 'USWV0038', 'name' => 'Bald Knob');
$city_data[] = array('accid' => 'USWV0039', 'name' => 'Ballard');
$city_data[] = array('accid' => 'USWV0040', 'name' => 'Ballengee');
$city_data[] = array('accid' => 'USWV0041', 'name' => 'Bancroft');
$city_data[] = array('accid' => 'USWV0042', 'name' => 'Barboursville');
$city_data[] = array('accid' => 'USWV0043', 'name' => 'Barrackville');
$city_data[] = array('accid' => 'USWV0044', 'name' => 'Bartley');
$city_data[] = array('accid' => 'USWV0045', 'name' => 'Bartow');
$city_data[] = array('accid' => 'USWV0046', 'name' => 'Baxter');
$city_data[] = array('accid' => 'USWV0047', 'name' => 'Bayard');
$city_data[] = array('accid' => 'USWV0048', 'name' => 'Beaver');
$city_data[] = array('accid' => 'USWV0049', 'name' => 'Beckley');
$city_data[] = array('accid' => 'USWV0050', 'name' => 'Beech Bottom');
$city_data[] = array('accid' => 'USWV0051', 'name' => 'Beeson');
$city_data[] = array('accid' => 'USWV0052', 'name' => 'Belington');
$city_data[] = array('accid' => 'USWV0053', 'name' => 'Belle');
$city_data[] = array('accid' => 'USWV0054', 'name' => 'Belleville');
$city_data[] = array('accid' => 'USWV0055', 'name' => 'Belmont');
$city_data[] = array('accid' => 'USWV0056', 'name' => 'Belva');
$city_data[] = array('accid' => 'USWV0057', 'name' => 'Bens Run');
$city_data[] = array('accid' => 'USWV0058', 'name' => 'Bentree');
$city_data[] = array('accid' => 'USWV0059', 'name' => 'Benwood');
$city_data[] = array('accid' => 'USWV0060', 'name' => 'Berea');
$city_data[] = array('accid' => 'USWV0061', 'name' => 'Bergoo');
$city_data[] = array('accid' => 'USWV0062', 'name' => 'Berkeley Springs');
$city_data[] = array('accid' => 'USWV0063', 'name' => 'Berwind');
$city_data[] = array('accid' => 'USWV0064', 'name' => 'Bethany');
$city_data[] = array('accid' => 'USWV0065', 'name' => 'Beverly');
$city_data[] = array('accid' => 'USWV0066', 'name' => 'Bickmore');
$city_data[] = array('accid' => 'USWV0067', 'name' => 'Big Bend');
$city_data[] = array('accid' => 'USWV0068', 'name' => 'Big Creek');
$city_data[] = array('accid' => 'USWV0069', 'name' => 'Big Run');
$city_data[] = array('accid' => 'USWV0070', 'name' => 'Big Sandy');
$city_data[] = array('accid' => 'USWV0071', 'name' => 'Big Springs');
$city_data[] = array('accid' => 'USWV0072', 'name' => 'Bim');
$city_data[] = array('accid' => 'USWV0073', 'name' => 'Birch River');
$city_data[] = array('accid' => 'USWV0074', 'name' => 'Blacksville');
$city_data[] = array('accid' => 'USWV0075', 'name' => 'Blair');
$city_data[] = array('accid' => 'USWV0076', 'name' => 'Blandville');
$city_data[] = array('accid' => 'USWV0077', 'name' => 'Bloomery');
$city_data[] = array('accid' => 'USWV0078', 'name' => 'Bloomingrose');
$city_data[] = array('accid' => 'USWV0079', 'name' => 'Blount');
$city_data[] = array('accid' => 'USWV0080', 'name' => 'Blue Creek');
$city_data[] = array('accid' => 'USWV0081', 'name' => 'Blue Jay');
$city_data[] = array('accid' => 'USWV0082', 'name' => 'Bluefield');
$city_data[] = array('accid' => 'USWV0083', 'name' => 'Bob White');
$city_data[] = array('accid' => 'USWV0084', 'name' => 'Bolt');
$city_data[] = array('accid' => 'USWV0085', 'name' => 'Bomont');
$city_data[] = array('accid' => 'USWV0086', 'name' => 'Boomer');
$city_data[] = array('accid' => 'USWV0087', 'name' => 'Booth');
$city_data[] = array('accid' => 'USWV0088', 'name' => 'Borderland');
$city_data[] = array('accid' => 'USWV0089', 'name' => 'Bowden');
$city_data[] = array('accid' => 'USWV0090', 'name' => 'Bradley');
$city_data[] = array('accid' => 'USWV0091', 'name' => 'Bradshaw');
$city_data[] = array('accid' => 'USWV0092', 'name' => 'Bramwell');
$city_data[] = array('accid' => 'USWV0093', 'name' => 'Branchland');
$city_data[] = array('accid' => 'USWV0094', 'name' => 'Brandywine');
$city_data[] = array('accid' => 'USWV0095', 'name' => 'Breeden');
$city_data[] = array('accid' => 'USWV0096', 'name' => 'Brenton');
$city_data[] = array('accid' => 'USWV0097', 'name' => 'Bretz');
$city_data[] = array('accid' => 'USWV0098', 'name' => 'Bridgeport');
$city_data[] = array('accid' => 'USWV0099', 'name' => 'Bristol');
$city_data[] = array('accid' => 'USWV0100', 'name' => 'Brohard');
$city_data[] = array('accid' => 'USWV0101', 'name' => 'Brownton');
$city_data[] = array('accid' => 'USWV0102', 'name' => 'Bruceton Mills');
$city_data[] = array('accid' => 'USWV0103', 'name' => 'Bruno');
$city_data[] = array('accid' => 'USWV0104', 'name' => 'Buckeye');
$city_data[] = array('accid' => 'USWV0105', 'name' => 'Buckhannon');
$city_data[] = array('accid' => 'USWV0106', 'name' => 'Bud');
$city_data[] = array('accid' => 'USWV0107', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USWV0108', 'name' => 'Bunker Hill');
$city_data[] = array('accid' => 'USWV0109', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USWV0110', 'name' => 'Burnsville');
$city_data[] = array('accid' => 'USWV0111', 'name' => 'Burton');
$city_data[] = array('accid' => 'USWV0112', 'name' => 'Cabin Creek');
$city_data[] = array('accid' => 'USWV0113', 'name' => 'Cabins');
$city_data[] = array('accid' => 'USWV0114', 'name' => 'Cairo');
$city_data[] = array('accid' => 'USWV0115', 'name' => 'Caldwell');
$city_data[] = array('accid' => 'USWV0116', 'name' => 'Calvin');
$city_data[] = array('accid' => 'USWV0117', 'name' => 'Camden');
$city_data[] = array('accid' => 'USWV0118', 'name' => 'Camden On Gauley');
$city_data[] = array('accid' => 'USWV0119', 'name' => 'Cameron');
$city_data[] = array('accid' => 'USWV0120', 'name' => 'Camp Creek');
$city_data[] = array('accid' => 'USWV0122', 'name' => 'Cannelton');
$city_data[] = array('accid' => 'USWV0123', 'name' => 'Canvas');
$city_data[] = array('accid' => 'USWV0124', 'name' => 'Capels');
$city_data[] = array('accid' => 'USWV0125', 'name' => 'Capon Bridge');
$city_data[] = array('accid' => 'USWV0126', 'name' => 'Capon Springs');
$city_data[] = array('accid' => 'USWV0127', 'name' => 'Caretta');
$city_data[] = array('accid' => 'USWV0128', 'name' => 'Carolina');
$city_data[] = array('accid' => 'USWV0129', 'name' => 'Cass');
$city_data[] = array('accid' => 'USWV0130', 'name' => 'Cassville');
$city_data[] = array('accid' => 'USWV0131', 'name' => 'Cedar Grove');
$city_data[] = array('accid' => 'USWV0132', 'name' => 'Cedarville');
$city_data[] = array('accid' => 'USWV0133', 'name' => 'Center Point');
$city_data[] = array('accid' => 'USWV0134', 'name' => 'Centralia');
$city_data[] = array('accid' => 'USWV0135', 'name' => 'Ceredo');
$city_data[] = array('accid' => 'USWV0136', 'name' => 'Chapmanville');
$city_data[] = array('accid' => 'USWV0137', 'name' => 'Charles Town');
$city_data[] = array('accid' => 'USWV0138', 'name' => 'Charleston');
$city_data[] = array('accid' => 'USWV0139', 'name' => 'Charlton Heights');
$city_data[] = array('accid' => 'USWV0140', 'name' => 'Charmco');
$city_data[] = array('accid' => 'USWV0141', 'name' => 'Chattaroy');
$city_data[] = array('accid' => 'USWV0142', 'name' => 'Chauncey');
$city_data[] = array('accid' => 'USWV0143', 'name' => 'Chester');
$city_data[] = array('accid' => 'USWV0144', 'name' => 'Chloe');
$city_data[] = array('accid' => 'USWV0145', 'name' => 'Circleville');
$city_data[] = array('accid' => 'USWV0146', 'name' => 'Clarksburg');
$city_data[] = array('accid' => 'USWV0147', 'name' => 'Clay');
$city_data[] = array('accid' => 'USWV0148', 'name' => 'Clear Creek');
$city_data[] = array('accid' => 'USWV0149', 'name' => 'Clear Fork');
$city_data[] = array('accid' => 'USWV0150', 'name' => 'Clendenin');
$city_data[] = array('accid' => 'USWV0151', 'name' => 'Cleveland');
$city_data[] = array('accid' => 'USWV0152', 'name' => 'Clio');
$city_data[] = array('accid' => 'USWV0153', 'name' => 'Clothier');
$city_data[] = array('accid' => 'USWV0154', 'name' => 'Coal City');
$city_data[] = array('accid' => 'USWV0155', 'name' => 'Coal Mountain');
$city_data[] = array('accid' => 'USWV0156', 'name' => 'Coalton');
$city_data[] = array('accid' => 'USWV0157', 'name' => 'Coalwood');
$city_data[] = array('accid' => 'USWV0158', 'name' => 'Colcord');
$city_data[] = array('accid' => 'USWV0159', 'name' => 'Colfax');
$city_data[] = array('accid' => 'USWV0160', 'name' => 'Colliers');
$city_data[] = array('accid' => 'USWV0161', 'name' => 'Comfort');
$city_data[] = array('accid' => 'USWV0162', 'name' => 'Cool Ridge');
$city_data[] = array('accid' => 'USWV0163', 'name' => 'Copen');
$city_data[] = array('accid' => 'USWV0164', 'name' => 'Cora');
$city_data[] = array('accid' => 'USWV0165', 'name' => 'Core');
$city_data[] = array('accid' => 'USWV0166', 'name' => 'Corinne');
$city_data[] = array('accid' => 'USWV0167', 'name' => 'Costa');
$city_data[] = array('accid' => 'USWV0168', 'name' => 'Cottageville');
$city_data[] = array('accid' => 'USWV0169', 'name' => 'Covel');
$city_data[] = array('accid' => 'USWV0170', 'name' => 'Cowen');
$city_data[] = array('accid' => 'USWV0171', 'name' => 'Coxs Mills');
$city_data[] = array('accid' => 'USWV0172', 'name' => 'Crab Orchard');
$city_data[] = array('accid' => 'USWV0173', 'name' => 'Craigsville');
$city_data[] = array('accid' => 'USWV0174', 'name' => 'Crawford');
$city_data[] = array('accid' => 'USWV0175', 'name' => 'Crawley');
$city_data[] = array('accid' => 'USWV0176', 'name' => 'Creston');
$city_data[] = array('accid' => 'USWV0177', 'name' => 'Crichton');
$city_data[] = array('accid' => 'USWV0178', 'name' => 'Crum');
$city_data[] = array('accid' => 'USWV0179', 'name' => 'Crumpler');
$city_data[] = array('accid' => 'USWV0180', 'name' => 'Cucumber');
$city_data[] = array('accid' => 'USWV0181', 'name' => 'Culloden');
$city_data[] = array('accid' => 'USWV0182', 'name' => 'Cyclone');
$city_data[] = array('accid' => 'USWV0183', 'name' => 'Dailey');
$city_data[] = array('accid' => 'USWV0184', 'name' => 'Dallas');
$city_data[] = array('accid' => 'USWV0185', 'name' => 'Danese');
$city_data[] = array('accid' => 'USWV0186', 'name' => 'Daniels');
$city_data[] = array('accid' => 'USWV0187', 'name' => 'Danville');
$city_data[] = array('accid' => 'USWV0188', 'name' => 'Davin');
$city_data[] = array('accid' => 'USWV0189', 'name' => 'Davis');
$city_data[] = array('accid' => 'USWV0190', 'name' => 'Davisville');
$city_data[] = array('accid' => 'USWV0191', 'name' => 'Davy');
$city_data[] = array('accid' => 'USWV0192', 'name' => 'Dawes');
$city_data[] = array('accid' => 'USWV0193', 'name' => 'Deep Water');
$city_data[] = array('accid' => 'USWV0194', 'name' => 'Delbarton');
$city_data[] = array('accid' => 'USWV0195', 'name' => 'Dellslow');
$city_data[] = array('accid' => 'USWV0196', 'name' => 'Delray');
$city_data[] = array('accid' => 'USWV0197', 'name' => 'Diana');
$city_data[] = array('accid' => 'USWV0198', 'name' => 'Dille');
$city_data[] = array('accid' => 'USWV0199', 'name' => 'Dingess');
$city_data[] = array('accid' => 'USWV0200', 'name' => 'Dixie');
$city_data[] = array('accid' => 'USWV0201', 'name' => 'Dorothy');
$city_data[] = array('accid' => 'USWV0202', 'name' => 'Dothan');
$city_data[] = array('accid' => 'USWV0203', 'name' => 'Drennen');
$city_data[] = array('accid' => 'USWV0204', 'name' => 'Dry Creek');
$city_data[] = array('accid' => 'USWV0205', 'name' => 'Drybranch');
$city_data[] = array('accid' => 'USWV0206', 'name' => 'Dryfork');
$city_data[] = array('accid' => 'USWV0207', 'name' => 'Duck');
$city_data[] = array('accid' => 'USWV0208', 'name' => 'Dunbar');
$city_data[] = array('accid' => 'USWV0209', 'name' => 'Dunlow');
$city_data[] = array('accid' => 'USWV0210', 'name' => 'Dunmore');
$city_data[] = array('accid' => 'USWV0211', 'name' => 'Durbin');
$city_data[] = array('accid' => 'USWV0212', 'name' => 'East Bank');
$city_data[] = array('accid' => 'USWV0213', 'name' => 'East Lynn');
$city_data[] = array('accid' => 'USWV0214', 'name' => 'Eccles');
$city_data[] = array('accid' => 'USWV0215', 'name' => 'Eckman');
$city_data[] = array('accid' => 'USWV0216', 'name' => 'Edgarton');
$city_data[] = array('accid' => 'USWV0217', 'name' => 'Edmond');
$city_data[] = array('accid' => 'USWV0218', 'name' => 'Eglon');
$city_data[] = array('accid' => 'USWV0219', 'name' => 'Elbert');
$city_data[] = array('accid' => 'USWV0220', 'name' => 'Eleanor');
$city_data[] = array('accid' => 'USWV0221', 'name' => 'Elizabeth');
$city_data[] = array('accid' => 'USWV0222', 'name' => 'Elk Garden');
$city_data[] = array('accid' => 'USWV0223', 'name' => 'Elkhorn');
$city_data[] = array('accid' => 'USWV0224', 'name' => 'Elkins');
$city_data[] = array('accid' => 'USWV0225', 'name' => 'Elkview');
$city_data[] = array('accid' => 'USWV0226', 'name' => 'Ellamore');
$city_data[] = array('accid' => 'USWV0227', 'name' => 'Ellenboro');
$city_data[] = array('accid' => 'USWV0228', 'name' => 'Elmira');
$city_data[] = array('accid' => 'USWV0229', 'name' => 'Elton');
$city_data[] = array('accid' => 'USWV0230', 'name' => 'English');
$city_data[] = array('accid' => 'USWV0231', 'name' => 'Enterprise');
$city_data[] = array('accid' => 'USWV0232', 'name' => 'Erbacon');
$city_data[] = array('accid' => 'USWV0233', 'name' => 'Eskdale');
$city_data[] = array('accid' => 'USWV0234', 'name' => 'Ethel');
$city_data[] = array('accid' => 'USWV0235', 'name' => 'Evans');
$city_data[] = array('accid' => 'USWV0236', 'name' => 'Everettville');
$city_data[] = array('accid' => 'USWV0237', 'name' => 'Exchange');
$city_data[] = array('accid' => 'USWV0238', 'name' => 'Fairdale');
$city_data[] = array('accid' => 'USWV0239', 'name' => 'Fairlea');
$city_data[] = array('accid' => 'USWV0240', 'name' => 'Fairmont');
$city_data[] = array('accid' => 'USWV0241', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USWV0242', 'name' => 'Falling Rock');
$city_data[] = array('accid' => 'USWV0243', 'name' => 'Falling Waters');
$city_data[] = array('accid' => 'USWV0244', 'name' => 'Fanrock');
$city_data[] = array('accid' => 'USWV0245', 'name' => 'Farmington');
$city_data[] = array('accid' => 'USWV0246', 'name' => 'Fayetteville');
$city_data[] = array('accid' => 'USWV0247', 'name' => 'Fenwick');
$city_data[] = array('accid' => 'USWV0248', 'name' => 'Fisher');
$city_data[] = array('accid' => 'USWV0249', 'name' => 'Flat Top');
$city_data[] = array('accid' => 'USWV0250', 'name' => 'Flatwoods');
$city_data[] = array('accid' => 'USWV0251', 'name' => 'Flemington');
$city_data[] = array('accid' => 'USWV0252', 'name' => 'Follansbee');
$city_data[] = array('accid' => 'USWV0253', 'name' => 'Folsom');
$city_data[] = array('accid' => 'USWV0254', 'name' => 'Forest Hill');
$city_data[] = array('accid' => 'USWV0255', 'name' => 'Fort Ashby');
$city_data[] = array('accid' => 'USWV0256', 'name' => 'Fort Gay');
$city_data[] = array('accid' => 'USWV0257', 'name' => 'Fort Spring');
$city_data[] = array('accid' => 'USWV0258', 'name' => 'Foster');
$city_data[] = array('accid' => 'USWV0259', 'name' => 'Four States');
$city_data[] = array('accid' => 'USWV0260', 'name' => 'Frametown');
$city_data[] = array('accid' => 'USWV0261', 'name' => 'Frankford');
$city_data[] = array('accid' => 'USWV0262', 'name' => 'Franklin');
$city_data[] = array('accid' => 'USWV0263', 'name' => 'Fraziers Bottom');
$city_data[] = array('accid' => 'USWV0264', 'name' => 'Freeman');
$city_data[] = array('accid' => 'USWV0265', 'name' => 'French Creek');
$city_data[] = array('accid' => 'USWV0266', 'name' => 'Frenchton');
$city_data[] = array('accid' => 'USWV0267', 'name' => 'Friendly');
$city_data[] = array('accid' => 'USWV0268', 'name' => 'Gallagher');
$city_data[] = array('accid' => 'USWV0269', 'name' => 'Gallipolis Ferry');
$city_data[] = array('accid' => 'USWV0270', 'name' => 'Galloway');
$city_data[] = array('accid' => 'USWV0271', 'name' => 'Gandeeville');
$city_data[] = array('accid' => 'USWV0272', 'name' => 'Gap Mills');
$city_data[] = array('accid' => 'USWV0273', 'name' => 'Gary');
$city_data[] = array('accid' => 'USWV0274', 'name' => 'Gassaway');
$city_data[] = array('accid' => 'USWV0275', 'name' => 'Gauley Bridge');
$city_data[] = array('accid' => 'USWV0276', 'name' => 'Gay');
$city_data[] = array('accid' => 'USWV0277', 'name' => 'Genoa');
$city_data[] = array('accid' => 'USWV0278', 'name' => 'Gerrardstown');
$city_data[] = array('accid' => 'USWV0279', 'name' => 'Ghent');
$city_data[] = array('accid' => 'USWV0280', 'name' => 'Gilbert');
$city_data[] = array('accid' => 'USWV0281', 'name' => 'Gilboa');
$city_data[] = array('accid' => 'USWV0282', 'name' => 'Gilmer');
$city_data[] = array('accid' => 'USWV0283', 'name' => 'Given');
$city_data[] = array('accid' => 'USWV0284', 'name' => 'Glace');
$city_data[] = array('accid' => 'USWV0285', 'name' => 'Glady');
$city_data[] = array('accid' => 'USWV0286', 'name' => 'Glasgow');
$city_data[] = array('accid' => 'USWV0287', 'name' => 'Glen');
$city_data[] = array('accid' => 'USWV0288', 'name' => 'Glen Dale');
$city_data[] = array('accid' => 'USWV0289', 'name' => 'Glen Daniel');
$city_data[] = array('accid' => 'USWV0290', 'name' => 'Glen Easton');
$city_data[] = array('accid' => 'USWV0291', 'name' => 'Glen Ferris');
$city_data[] = array('accid' => 'USWV0292', 'name' => 'Glen Fork');
$city_data[] = array('accid' => 'USWV0293', 'name' => 'Glen Jean');
$city_data[] = array('accid' => 'USWV0294', 'name' => 'Glen Morgan');
$city_data[] = array('accid' => 'USWV0295', 'name' => 'Glen Rogers');
$city_data[] = array('accid' => 'USWV0296', 'name' => 'Glen White');
$city_data[] = array('accid' => 'USWV0297', 'name' => 'Glengary');
$city_data[] = array('accid' => 'USWV0298', 'name' => 'Glenhayes');
$city_data[] = array('accid' => 'USWV0299', 'name' => 'Glenville');
$city_data[] = array('accid' => 'USWV0300', 'name' => 'Glenwood');
$city_data[] = array('accid' => 'USWV0301', 'name' => 'Gordon');
$city_data[] = array('accid' => 'USWV0302', 'name' => 'Gormania');
$city_data[] = array('accid' => 'USWV0303', 'name' => 'Grafton');
$city_data[] = array('accid' => 'USWV0304', 'name' => 'Grant Town');
$city_data[] = array('accid' => 'USWV0305', 'name' => 'Grantsville');
$city_data[] = array('accid' => 'USWV0306', 'name' => 'Granville');
$city_data[] = array('accid' => 'USWV0307', 'name' => 'Grassy Meadows');
$city_data[] = array('accid' => 'USWV0308', 'name' => 'Great Cacapon');
$city_data[] = array('accid' => 'USWV0309', 'name' => 'Green Bank');
$city_data[] = array('accid' => 'USWV0310', 'name' => 'Green Spring');
$city_data[] = array('accid' => 'USWV0311', 'name' => 'Green Sulphur Springs');
$city_data[] = array('accid' => 'USWV0312', 'name' => 'Greenville');
$city_data[] = array('accid' => 'USWV0313', 'name' => 'Griffithsville');
$city_data[] = array('accid' => 'USWV0314', 'name' => 'Grimms Landing');
$city_data[] = array('accid' => 'USWV0315', 'name' => 'Gypsy');
$city_data[] = array('accid' => 'USWV0316', 'name' => 'Hacker Valley');
$city_data[] = array('accid' => 'USWV0317', 'name' => 'Halltown');
$city_data[] = array('accid' => 'USWV0318', 'name' => 'Hambleton');
$city_data[] = array('accid' => 'USWV0319', 'name' => 'Hamlin');
$city_data[] = array('accid' => 'USWV0320', 'name' => 'Hampden');
$city_data[] = array('accid' => 'USWV0321', 'name' => 'Handley');
$city_data[] = array('accid' => 'USWV0322', 'name' => 'Hanover');
$city_data[] = array('accid' => 'USWV0323', 'name' => 'Hansford');
$city_data[] = array('accid' => 'USWV0324', 'name' => 'Harman');
$city_data[] = array('accid' => 'USWV0325', 'name' => 'Harper');
$city_data[] = array('accid' => 'USWV0326', 'name' => 'Harpers Ferry');
$city_data[] = array('accid' => 'USWV0327', 'name' => 'Harrisville');
$city_data[] = array('accid' => 'USWV0328', 'name' => 'Hartford');
$city_data[] = array('accid' => 'USWV0329', 'name' => 'Harts');
$city_data[] = array('accid' => 'USWV0330', 'name' => 'Havaco');
$city_data[] = array('accid' => 'USWV0331', 'name' => 'Haywood');
$city_data[] = array('accid' => 'USWV0332', 'name' => 'Hazelton');
$city_data[] = array('accid' => 'USWV0333', 'name' => 'Heaters');
$city_data[] = array('accid' => 'USWV0334', 'name' => 'Hedgesville');
$city_data[] = array('accid' => 'USWV0335', 'name' => 'Helen');
$city_data[] = array('accid' => 'USWV0336', 'name' => 'Helvetia');
$city_data[] = array('accid' => 'USWV0337', 'name' => 'Hemphill');
$city_data[] = array('accid' => 'USWV0338', 'name' => 'Henderson');
$city_data[] = array('accid' => 'USWV0339', 'name' => 'Hendricks');
$city_data[] = array('accid' => 'USWV0340', 'name' => 'Henlawson');
$city_data[] = array('accid' => 'USWV0341', 'name' => 'Hensley');
$city_data[] = array('accid' => 'USWV0342', 'name' => 'Hepzibah');
$city_data[] = array('accid' => 'USWV0343', 'name' => 'Herndon');
$city_data[] = array('accid' => 'USWV0344', 'name' => 'Hernshaw');
$city_data[] = array('accid' => 'USWV0345', 'name' => 'Hewett');
$city_data[] = array('accid' => 'USWV0346', 'name' => 'Hiawatha');
$city_data[] = array('accid' => 'USWV0347', 'name' => 'Hico');
$city_data[] = array('accid' => 'USWV0348', 'name' => 'High View');
$city_data[] = array('accid' => 'USWV0349', 'name' => 'Hillsboro');
$city_data[] = array('accid' => 'USWV0350', 'name' => 'Hilltop');
$city_data[] = array('accid' => 'USWV0351', 'name' => 'Hines');
$city_data[] = array('accid' => 'USWV0352', 'name' => 'Hinton');
$city_data[] = array('accid' => 'USWV0353', 'name' => 'Holden');
$city_data[] = array('accid' => 'USWV0354', 'name' => 'Hometown');
$city_data[] = array('accid' => 'USWV0355', 'name' => 'Horner');
$city_data[] = array('accid' => 'USWV0356', 'name' => 'Hugheston');
$city_data[] = array('accid' => 'USWV0357', 'name' => 'Hundred');
$city_data[] = array('accid' => 'USWV0358', 'name' => 'Huntington');
$city_data[] = array('accid' => 'USWV0359', 'name' => 'Hurricane');
$city_data[] = array('accid' => 'USWV0360', 'name' => 'Huttonsville');
$city_data[] = array('accid' => 'USWV0361', 'name' => 'Iaeger');
$city_data[] = array('accid' => 'USWV0362', 'name' => 'Idamay');
$city_data[] = array('accid' => 'USWV0363', 'name' => 'Ikes Fork');
$city_data[] = array('accid' => 'USWV0364', 'name' => 'Independence');
$city_data[] = array('accid' => 'USWV0365', 'name' => 'Indore');
$city_data[] = array('accid' => 'USWV0366', 'name' => 'Industrial');
$city_data[] = array('accid' => 'USWV0367', 'name' => 'Institute');
$city_data[] = array('accid' => 'USWV0368', 'name' => 'Inwood');
$city_data[] = array('accid' => 'USWV0369', 'name' => 'Ireland');
$city_data[] = array('accid' => 'USWV0370', 'name' => 'Isaban');
$city_data[] = array('accid' => 'USWV0371', 'name' => 'Itmann');
$city_data[] = array('accid' => 'USWV0372', 'name' => 'Ivydale');
$city_data[] = array('accid' => 'USWV0373', 'name' => 'Jacksonburg');
$city_data[] = array('accid' => 'USWV0374', 'name' => 'Jane Lew');
$city_data[] = array('accid' => 'USWV0375', 'name' => 'Jeffrey');
$city_data[] = array('accid' => 'USWV0376', 'name' => 'Jenkinjones');
$city_data[] = array('accid' => 'USWV0377', 'name' => 'Jesse');
$city_data[] = array('accid' => 'USWV0378', 'name' => 'Jodie');
$city_data[] = array('accid' => 'USWV0379', 'name' => 'Jolo');
$city_data[] = array('accid' => 'USWV0380', 'name' => 'Jonben');
$city_data[] = array('accid' => 'USWV0381', 'name' => 'Josephine');
$city_data[] = array('accid' => 'USWV0382', 'name' => 'Julian');
$city_data[] = array('accid' => 'USWV0383', 'name' => 'Jumping Branch');
$city_data[] = array('accid' => 'USWV0384', 'name' => 'Junction');
$city_data[] = array('accid' => 'USWV0385', 'name' => 'Junior');
$city_data[] = array('accid' => 'USWV0386', 'name' => 'Justice');
$city_data[] = array('accid' => 'USWV0387', 'name' => 'Kanawha Falls');
$city_data[] = array('accid' => 'USWV0388', 'name' => 'Kanawha Head');
$city_data[] = array('accid' => 'USWV0389', 'name' => 'Kearneysville');
$city_data[] = array('accid' => 'USWV0390', 'name' => 'Kegley');
$city_data[] = array('accid' => 'USWV0391', 'name' => 'Kellysville');
$city_data[] = array('accid' => 'USWV0392', 'name' => 'Kenna');
$city_data[] = array('accid' => 'USWV0393', 'name' => 'Kenova');
$city_data[] = array('accid' => 'USWV0394', 'name' => 'Kerens');
$city_data[] = array('accid' => 'USWV0395', 'name' => 'Kermit');
$city_data[] = array('accid' => 'USWV0396', 'name' => 'Keslers Cross Lanes');
$city_data[] = array('accid' => 'USWV0397', 'name' => 'Keyser');
$city_data[] = array('accid' => 'USWV0398', 'name' => 'Keystone');
$city_data[] = array('accid' => 'USWV0399', 'name' => 'Kiahsville');
$city_data[] = array('accid' => 'USWV0400', 'name' => 'Kieffer');
$city_data[] = array('accid' => 'USWV0401', 'name' => 'Kilsyth');
$city_data[] = array('accid' => 'USWV0402', 'name' => 'Kimball');
$city_data[] = array('accid' => 'USWV0403', 'name' => 'Kimberly');
$city_data[] = array('accid' => 'USWV0404', 'name' => 'Kincaid');
$city_data[] = array('accid' => 'USWV0405', 'name' => 'Kingmont');
$city_data[] = array('accid' => 'USWV0406', 'name' => 'Kingwood');
$city_data[] = array('accid' => 'USWV0408', 'name' => 'Kistler');
$city_data[] = array('accid' => 'USWV0409', 'name' => 'Kopperston');
$city_data[] = array('accid' => 'USWV0410', 'name' => 'Kyle');
$city_data[] = array('accid' => 'USWV0411', 'name' => 'Lahmansville');
$city_data[] = array('accid' => 'USWV0412', 'name' => 'Lake');
$city_data[] = array('accid' => 'USWV0413', 'name' => 'Lakin');
$city_data[] = array('accid' => 'USWV0414', 'name' => 'Lanark');
$city_data[] = array('accid' => 'USWV0415', 'name' => 'Lansing');
$city_data[] = array('accid' => 'USWV0416', 'name' => 'Lashmeet');
$city_data[] = array('accid' => 'USWV0417', 'name' => 'Lavalette');
$city_data[] = array('accid' => 'USWV0418', 'name' => 'Layland');
$city_data[] = array('accid' => 'USWV0419', 'name' => 'Le Roy');
$city_data[] = array('accid' => 'USWV0420', 'name' => 'Leckie');
$city_data[] = array('accid' => 'USWV0421', 'name' => 'Leewood');
$city_data[] = array('accid' => 'USWV0422', 'name' => 'Left Hand');
$city_data[] = array('accid' => 'USWV0423', 'name' => 'Leivasy');
$city_data[] = array('accid' => 'USWV0424', 'name' => 'Lenore');
$city_data[] = array('accid' => 'USWV0425', 'name' => 'Leon');
$city_data[] = array('accid' => 'USWV0426', 'name' => 'Lerona');
$city_data[] = array('accid' => 'USWV0427', 'name' => 'Lesage');
$city_data[] = array('accid' => 'USWV0428', 'name' => 'Leslie');
$city_data[] = array('accid' => 'USWV0429', 'name' => 'Lester');
$city_data[] = array('accid' => 'USWV0430', 'name' => 'Letart');
$city_data[] = array('accid' => 'USWV0431', 'name' => 'Levels');
$city_data[] = array('accid' => 'USWV0432', 'name' => 'Lewisburg');
$city_data[] = array('accid' => 'USWV0433', 'name' => 'Liberty');
$city_data[] = array('accid' => 'USWV0434', 'name' => 'Linden');
$city_data[] = array('accid' => 'USWV0435', 'name' => 'Lindside');
$city_data[] = array('accid' => 'USWV0436', 'name' => 'Linn');
$city_data[] = array('accid' => 'USWV0437', 'name' => 'Little Birch');
$city_data[] = array('accid' => 'USWV0438', 'name' => 'Littleton');
$city_data[] = array('accid' => 'USWV0439', 'name' => 'Lizemores');
$city_data[] = array('accid' => 'USWV0440', 'name' => 'Lochgelly');
$city_data[] = array('accid' => 'USWV0441', 'name' => 'Lockney');
$city_data[] = array('accid' => 'USWV0442', 'name' => 'Logan');
$city_data[] = array('accid' => 'USWV0443', 'name' => 'London');
$city_data[] = array('accid' => 'USWV0444', 'name' => 'Lookout');
$city_data[] = array('accid' => 'USWV0445', 'name' => 'Looneyville');
$city_data[] = array('accid' => 'USWV0446', 'name' => 'Lorado');
$city_data[] = array('accid' => 'USWV0447', 'name' => 'Lorentz');
$city_data[] = array('accid' => 'USWV0448', 'name' => 'Lost City');
$city_data[] = array('accid' => 'USWV0449', 'name' => 'Lost Creek');
$city_data[] = array('accid' => 'USWV0450', 'name' => 'Lumberport');
$city_data[] = array('accid' => 'USWV0451', 'name' => 'Lyburn');
$city_data[] = array('accid' => 'USWV0452', 'name' => 'Lynco');
$city_data[] = array('accid' => 'USWV0453', 'name' => 'Maben');
$city_data[] = array('accid' => 'USWV0454', 'name' => 'Mabie');
$city_data[] = array('accid' => 'USWV0455', 'name' => 'Mabscott');
$city_data[] = array('accid' => 'USWV0456', 'name' => 'Mac Arthur');
$city_data[] = array('accid' => 'USWV0457', 'name' => 'MacFarlan');
$city_data[] = array('accid' => 'USWV0458', 'name' => 'Madison');
$city_data[] = array('accid' => 'USWV0459', 'name' => 'Maidsville');
$city_data[] = array('accid' => 'USWV0460', 'name' => 'Mallory');
$city_data[] = array('accid' => 'USWV0461', 'name' => 'Mammoth');
$city_data[] = array('accid' => 'USWV0462', 'name' => 'Man');
$city_data[] = array('accid' => 'USWV0463', 'name' => 'Mannington');
$city_data[] = array('accid' => 'USWV0464', 'name' => 'Marianna');
$city_data[] = array('accid' => 'USWV0465', 'name' => 'Marlinton');
$city_data[] = array('accid' => 'USWV0466', 'name' => 'Martinsburg');
$city_data[] = array('accid' => 'USWV0467', 'name' => 'Mason');
$city_data[] = array('accid' => 'USWV0468', 'name' => 'Masontown');
$city_data[] = array('accid' => 'USWV0469', 'name' => 'Matewan');
$city_data[] = array('accid' => 'USWV0470', 'name' => 'Matheny');
$city_data[] = array('accid' => 'USWV0471', 'name' => 'Mathias');
$city_data[] = array('accid' => 'USWV0472', 'name' => 'Matoaka');
$city_data[] = array('accid' => 'USWV0473', 'name' => 'Maxwelton');
$city_data[] = array('accid' => 'USWV0474', 'name' => 'Maybeury');
$city_data[] = array('accid' => 'USWV0475', 'name' => 'Maysel');
$city_data[] = array('accid' => 'USWV0476', 'name' => 'Maysville');
$city_data[] = array('accid' => 'USWV0477', 'name' => 'McGraws');
$city_data[] = array('accid' => 'USWV0478', 'name' => 'McMechen');
$city_data[] = array('accid' => 'USWV0479', 'name' => 'Meador');
$city_data[] = array('accid' => 'USWV0480', 'name' => 'Meadow Bluff');
$city_data[] = array('accid' => 'USWV0481', 'name' => 'Meadow Bridge');
$city_data[] = array('accid' => 'USWV0482', 'name' => 'Meadow Creek');
$city_data[] = array('accid' => 'USWV0483', 'name' => 'Meadowbrook');
$city_data[] = array('accid' => 'USWV0484', 'name' => 'Medley');
$city_data[] = array('accid' => 'USWV0485', 'name' => 'Metz');
$city_data[] = array('accid' => 'USWV0486', 'name' => 'Miami');
$city_data[] = array('accid' => 'USWV0487', 'name' => 'Middlebourne');
$city_data[] = array('accid' => 'USWV0488', 'name' => 'Midkiff');
$city_data[] = array('accid' => 'USWV0489', 'name' => 'Midway');
$city_data[] = array('accid' => 'USWV0490', 'name' => 'Milam');
$city_data[] = array('accid' => 'USWV0491', 'name' => 'Mill Creek');
$city_data[] = array('accid' => 'USWV0492', 'name' => 'Millstone');
$city_data[] = array('accid' => 'USWV0493', 'name' => 'Millville');
$city_data[] = array('accid' => 'USWV0494', 'name' => 'Millwood');
$city_data[] = array('accid' => 'USWV0495', 'name' => 'Milton');
$city_data[] = array('accid' => 'USWV0496', 'name' => 'Minden');
$city_data[] = array('accid' => 'USWV0497', 'name' => 'Mineral Wells');
$city_data[] = array('accid' => 'USWV0498', 'name' => 'Moatsville');
$city_data[] = array('accid' => 'USWV0499', 'name' => 'Mohawk');
$city_data[] = array('accid' => 'USWV0500', 'name' => 'Monaville');
$city_data[] = array('accid' => 'USWV0501', 'name' => 'Montana Mines');
$city_data[] = array('accid' => 'USWV0502', 'name' => 'Montcalm');
$city_data[] = array('accid' => 'USWV0503', 'name' => 'Monterville');
$city_data[] = array('accid' => 'USWV0504', 'name' => 'Montgomery');
$city_data[] = array('accid' => 'USWV0505', 'name' => 'Montrose');
$city_data[] = array('accid' => 'USWV0506', 'name' => 'Moorefield');
$city_data[] = array('accid' => 'USWV0507', 'name' => 'Morgantown');
$city_data[] = array('accid' => 'USWV0508', 'name' => 'Moundsville');
$city_data[] = array('accid' => 'USWV0509', 'name' => 'Mount Alto');
$city_data[] = array('accid' => 'USWV0510', 'name' => 'Mount Carbon');
$city_data[] = array('accid' => 'USWV0511', 'name' => 'Mount Clare');
$city_data[] = array('accid' => 'USWV0512', 'name' => 'Mount Gay');
$city_data[] = array('accid' => 'USWV0513', 'name' => 'Mount Hope');
$city_data[] = array('accid' => 'USWV0514', 'name' => 'Mount Lookout');
$city_data[] = array('accid' => 'USWV0515', 'name' => 'Mount Nebo');
$city_data[] = array('accid' => 'USWV0516', 'name' => 'Mount Olive');
$city_data[] = array('accid' => 'USWV0517', 'name' => 'Mount Storm');
$city_data[] = array('accid' => 'USWV0518', 'name' => 'Mount Zion');
$city_data[] = array('accid' => 'USWV0519', 'name' => 'Mountain');
$city_data[] = array('accid' => 'USWV0520', 'name' => 'Mullens');
$city_data[] = array('accid' => 'USWV0521', 'name' => 'Munday');
$city_data[] = array('accid' => 'USWV0522', 'name' => 'Myra');
$city_data[] = array('accid' => 'USWV0523', 'name' => 'Nallen');
$city_data[] = array('accid' => 'USWV0524', 'name' => 'Naoma');
$city_data[] = array('accid' => 'USWV0525', 'name' => 'Napier');
$city_data[] = array('accid' => 'USWV0526', 'name' => 'Naugatuck');
$city_data[] = array('accid' => 'USWV0527', 'name' => 'Nebo');
$city_data[] = array('accid' => 'USWV0528', 'name' => 'Nellis');
$city_data[] = array('accid' => 'USWV0529', 'name' => 'Nemours');
$city_data[] = array('accid' => 'USWV0530', 'name' => 'Neola');
$city_data[] = array('accid' => 'USWV0531', 'name' => 'Nettie');
$city_data[] = array('accid' => 'USWV0532', 'name' => 'New Creek');
$city_data[] = array('accid' => 'USWV0533', 'name' => 'New Cumberland');
$city_data[] = array('accid' => 'USWV0534', 'name' => 'New Haven');
$city_data[] = array('accid' => 'USWV0535', 'name' => 'New Manchester');
$city_data[] = array('accid' => 'USWV0536', 'name' => 'New Martinsville');
$city_data[] = array('accid' => 'USWV0537', 'name' => 'New Milton');
$city_data[] = array('accid' => 'USWV0538', 'name' => 'New Richmond');
$city_data[] = array('accid' => 'USWV0539', 'name' => 'Newburg');
$city_data[] = array('accid' => 'USWV0540', 'name' => 'Newell');
$city_data[] = array('accid' => 'USWV0541', 'name' => 'Newhall');
$city_data[] = array('accid' => 'USWV0542', 'name' => 'Newton');
$city_data[] = array('accid' => 'USWV0543', 'name' => 'Newtown');
$city_data[] = array('accid' => 'USWV0544', 'name' => 'Nimitz');
$city_data[] = array('accid' => 'USWV0545', 'name' => 'Nitro');
$city_data[] = array('accid' => 'USWV0546', 'name' => 'Nolan');
$city_data[] = array('accid' => 'USWV0547', 'name' => 'Normantown');
$city_data[] = array('accid' => 'USWV0548', 'name' => 'North Matewan');
$city_data[] = array('accid' => 'USWV0549', 'name' => 'North Spring');
$city_data[] = array('accid' => 'USWV0550', 'name' => 'Northfork');
$city_data[] = array('accid' => 'USWV0551', 'name' => 'Norton');
$city_data[] = array('accid' => 'USWV0552', 'name' => 'Oak Hill');
$city_data[] = array('accid' => 'USWV0553', 'name' => 'Oakvale');
$city_data[] = array('accid' => 'USWV0554', 'name' => 'Oceana');
$city_data[] = array('accid' => 'USWV0555', 'name' => 'Odd');
$city_data[] = array('accid' => 'USWV0556', 'name' => 'Ohley');
$city_data[] = array('accid' => 'USWV0557', 'name' => 'Old Fields');
$city_data[] = array('accid' => 'USWV0558', 'name' => 'Omar');
$city_data[] = array('accid' => 'USWV0559', 'name' => 'Ona');
$city_data[] = array('accid' => 'USWV0560', 'name' => 'Onego');
$city_data[] = array('accid' => 'USWV0561', 'name' => 'Orgas');
$city_data[] = array('accid' => 'USWV0562', 'name' => 'Orlando');
$city_data[] = array('accid' => 'USWV0563', 'name' => 'Orma');
$city_data[] = array('accid' => 'USWV0564', 'name' => 'Osage');
$city_data[] = array('accid' => 'USWV0565', 'name' => 'Ottawa');
$city_data[] = array('accid' => 'USWV0566', 'name' => 'Ovapa');
$city_data[] = array('accid' => 'USWV0567', 'name' => 'Paden City');
$city_data[] = array('accid' => 'USWV0568', 'name' => 'Page');
$city_data[] = array('accid' => 'USWV0569', 'name' => 'Pageton');
$city_data[] = array('accid' => 'USWV0570', 'name' => 'Palestine');
$city_data[] = array('accid' => 'USWV0571', 'name' => 'Panther');
$city_data[] = array('accid' => 'USWV0572', 'name' => 'Parkersburg');
$city_data[] = array('accid' => 'USWV0573', 'name' => 'Parsons');
$city_data[] = array('accid' => 'USWV0574', 'name' => 'Paw Paw');
$city_data[] = array('accid' => 'USWV0575', 'name' => 'Pax');
$city_data[] = array('accid' => 'USWV0576', 'name' => 'Paynesville');
$city_data[] = array('accid' => 'USWV0577', 'name' => 'Peach Creek');
$city_data[] = array('accid' => 'USWV0578', 'name' => 'Pecks Mill');
$city_data[] = array('accid' => 'USWV0579', 'name' => 'Pence Springs');
$city_data[] = array('accid' => 'USWV0580', 'name' => 'Pennsboro');
$city_data[] = array('accid' => 'USWV0581', 'name' => 'Pentress');
$city_data[] = array('accid' => 'USWV0582', 'name' => 'Perkins');
$city_data[] = array('accid' => 'USWV0583', 'name' => 'Petersburg');
$city_data[] = array('accid' => 'USWV0584', 'name' => 'Peterstown');
$city_data[] = array('accid' => 'USWV0585', 'name' => 'Petroleum');
$city_data[] = array('accid' => 'USWV0586', 'name' => 'Peytona');
$city_data[] = array('accid' => 'USWV0587', 'name' => 'Philippi');
$city_data[] = array('accid' => 'USWV0588', 'name' => 'Pickens');
$city_data[] = array('accid' => 'USWV0589', 'name' => 'Piedmont');
$city_data[] = array('accid' => 'USWV0590', 'name' => 'Pinch');
$city_data[] = array('accid' => 'USWV0591', 'name' => 'Pine Grove');
$city_data[] = array('accid' => 'USWV0592', 'name' => 'Pineville');
$city_data[] = array('accid' => 'USWV0593', 'name' => 'Piney View');
$city_data[] = array('accid' => 'USWV0594', 'name' => 'Pipestem');
$city_data[] = array('accid' => 'USWV0595', 'name' => 'Poca');
$city_data[] = array('accid' => 'USWV0596', 'name' => 'Point Pleasant');
$city_data[] = array('accid' => 'USWV0597', 'name' => 'Points');
$city_data[] = array('accid' => 'USWV0598', 'name' => 'Pond Gap');
$city_data[] = array('accid' => 'USWV0599', 'name' => 'Pool');
$city_data[] = array('accid' => 'USWV0600', 'name' => 'Porters Falls');
$city_data[] = array('accid' => 'USWV0601', 'name' => 'Powellton');
$city_data[] = array('accid' => 'USWV0602', 'name' => 'Powhatan');
$city_data[] = array('accid' => 'USWV0603', 'name' => 'Pratt');
$city_data[] = array('accid' => 'USWV0604', 'name' => 'Premier');
$city_data[] = array('accid' => 'USWV0605', 'name' => 'Prichard');
$city_data[] = array('accid' => 'USWV0606', 'name' => 'Prince');
$city_data[] = array('accid' => 'USWV0607', 'name' => 'Princeton');
$city_data[] = array('accid' => 'USWV0608', 'name' => 'Princewick');
$city_data[] = array('accid' => 'USWV0609', 'name' => 'Procious');
$city_data[] = array('accid' => 'USWV0610', 'name' => 'Proctor');
$city_data[] = array('accid' => 'USWV0611', 'name' => 'Prosperity');
$city_data[] = array('accid' => 'USWV0612', 'name' => 'Pullman');
$city_data[] = array('accid' => 'USWV0613', 'name' => 'Purgitsville');
$city_data[] = array('accid' => 'USWV0614', 'name' => 'Pursglove');
$city_data[] = array('accid' => 'USWV0615', 'name' => 'Quinwood');
$city_data[] = array('accid' => 'USWV0616', 'name' => 'Rachel');
$city_data[] = array('accid' => 'USWV0617', 'name' => 'Racine');
$city_data[] = array('accid' => 'USWV0618', 'name' => 'Ragland');
$city_data[] = array('accid' => 'USWV0619', 'name' => 'Rainelle');
$city_data[] = array('accid' => 'USWV0620', 'name' => 'Raleigh');
$city_data[] = array('accid' => 'USWV0621', 'name' => 'Ramsey');
$city_data[] = array('accid' => 'USWV0622', 'name' => 'Ranger');
$city_data[] = array('accid' => 'USWV0623', 'name' => 'Ranson');
$city_data[] = array('accid' => 'USWV0624', 'name' => 'Ravencliff');
$city_data[] = array('accid' => 'USWV0625', 'name' => 'Ravenswood');
$city_data[] = array('accid' => 'USWV0626', 'name' => 'Rawl');
$city_data[] = array('accid' => 'USWV0627', 'name' => 'Raysal');
$city_data[] = array('accid' => 'USWV0628', 'name' => 'Reader');
$city_data[] = array('accid' => 'USWV0629', 'name' => 'Red Creek');
$city_data[] = array('accid' => 'USWV0630', 'name' => 'Red House');
$city_data[] = array('accid' => 'USWV0631', 'name' => 'Red Jacket');
$city_data[] = array('accid' => 'USWV0632', 'name' => 'Redstar');
$city_data[] = array('accid' => 'USWV0633', 'name' => 'Reedsville');
$city_data[] = array('accid' => 'USWV0634', 'name' => 'Reedy');
$city_data[] = array('accid' => 'USWV0635', 'name' => 'Renick');
$city_data[] = array('accid' => 'USWV0636', 'name' => 'Reynoldsville');
$city_data[] = array('accid' => 'USWV0637', 'name' => 'Rhodell');
$city_data[] = array('accid' => 'USWV0638', 'name' => 'Richwood');
$city_data[] = array('accid' => 'USWV0639', 'name' => 'Ridgeley');
$city_data[] = array('accid' => 'USWV0640', 'name' => 'Ridgeview');
$city_data[] = array('accid' => 'USWV0641', 'name' => 'Ridgeway');
$city_data[] = array('accid' => 'USWV0642', 'name' => 'Rio');
$city_data[] = array('accid' => 'USWV0643', 'name' => 'Ripley');
$city_data[] = array('accid' => 'USWV0644', 'name' => 'Rippon');
$city_data[] = array('accid' => 'USWV0645', 'name' => 'Riverton');
$city_data[] = array('accid' => 'USWV0646', 'name' => 'Rivesville');
$city_data[] = array('accid' => 'USWV0647', 'name' => 'Robson');
$city_data[] = array('accid' => 'USWV0648', 'name' => 'Rock');
$city_data[] = array('accid' => 'USWV0649', 'name' => 'Rock Cave');
$city_data[] = array('accid' => 'USWV0650', 'name' => 'Rock Creek');
$city_data[] = array('accid' => 'USWV0651', 'name' => 'Rock View');
$city_data[] = array('accid' => 'USWV0652', 'name' => 'Rockport');
$city_data[] = array('accid' => 'USWV0653', 'name' => 'Roderfield');
$city_data[] = array('accid' => 'USWV0654', 'name' => 'Romney');
$city_data[] = array('accid' => 'USWV0655', 'name' => 'Ronceverte');
$city_data[] = array('accid' => 'USWV0657', 'name' => 'Rosemont');
$city_data[] = array('accid' => 'USWV0658', 'name' => 'Rowlesburg');
$city_data[] = array('accid' => 'USWV0659', 'name' => 'Rupert');
$city_data[] = array('accid' => 'USWV0660', 'name' => 'Sabine');
$city_data[] = array('accid' => 'USWV0661', 'name' => 'Saint Albans');
$city_data[] = array('accid' => 'USWV0662', 'name' => 'Saint Marys');
$city_data[] = array('accid' => 'USWV0663', 'name' => 'Salem');
$city_data[] = array('accid' => 'USWV0664', 'name' => 'Salt Rock');
$city_data[] = array('accid' => 'USWV0665', 'name' => 'Sand Fork');
$city_data[] = array('accid' => 'USWV0666', 'name' => 'Sandstone');
$city_data[] = array('accid' => 'USWV0667', 'name' => 'Sandyville');
$city_data[] = array('accid' => 'USWV0668', 'name' => 'Sarah Ann');
$city_data[] = array('accid' => 'USWV0669', 'name' => 'Saulsville');
$city_data[] = array('accid' => 'USWV0670', 'name' => 'Saxon');
$city_data[] = array('accid' => 'USWV0671', 'name' => 'Scarbro');
$city_data[] = array('accid' => 'USWV0672', 'name' => 'Scott Depot');
$city_data[] = array('accid' => 'USWV0673', 'name' => 'Secondcreek');
$city_data[] = array('accid' => 'USWV0674', 'name' => 'Selbyville');
$city_data[] = array('accid' => 'USWV0675', 'name' => 'Seneca Rocks');
$city_data[] = array('accid' => 'USWV0676', 'name' => 'Seth');
$city_data[] = array('accid' => 'USWV0677', 'name' => 'Shady Spring');
$city_data[] = array('accid' => 'USWV0678', 'name' => 'Shanks');
$city_data[] = array('accid' => 'USWV0679', 'name' => 'Sharon');
$city_data[] = array('accid' => 'USWV0680', 'name' => 'Sharples');
$city_data[] = array('accid' => 'USWV0681', 'name' => 'Shenandoah Junction');
$city_data[] = array('accid' => 'USWV0682', 'name' => 'Shepherdstown');
$city_data[] = array('accid' => 'USWV0683', 'name' => 'Sherman');
$city_data[] = array('accid' => 'USWV0684', 'name' => 'Shinnston');
$city_data[] = array('accid' => 'USWV0685', 'name' => 'Shirley');
$city_data[] = array('accid' => 'USWV0686', 'name' => 'Shoals');
$city_data[] = array('accid' => 'USWV0687', 'name' => 'Shock');
$city_data[] = array('accid' => 'USWV0688', 'name' => 'Short Creek');
$city_data[] = array('accid' => 'USWV0689', 'name' => 'Simon');
$city_data[] = array('accid' => 'USWV0690', 'name' => 'Simpson');
$city_data[] = array('accid' => 'USWV0691', 'name' => 'Sinks Grove');
$city_data[] = array('accid' => 'USWV0692', 'name' => 'Sistersville');
$city_data[] = array('accid' => 'USWV0693', 'name' => 'Skelton');
$city_data[] = array('accid' => 'USWV0694', 'name' => 'Skygusty');
$city_data[] = array('accid' => 'USWV0695', 'name' => 'Slab Fork');
$city_data[] = array('accid' => 'USWV0696', 'name' => 'Slanesville');
$city_data[] = array('accid' => 'USWV0698', 'name' => 'Smithburg');
$city_data[] = array('accid' => 'USWV0699', 'name' => 'Smithers');
$city_data[] = array('accid' => 'USWV0700', 'name' => 'Smithfield');
$city_data[] = array('accid' => 'USWV0701', 'name' => 'Smithville');
$city_data[] = array('accid' => 'USWV0702', 'name' => 'Smoot');
$city_data[] = array('accid' => 'USWV0703', 'name' => 'Snowshoe');
$city_data[] = array('accid' => 'USWV0705', 'name' => 'Sod');
$city_data[] = array('accid' => 'USWV0706', 'name' => 'Sophia');
$city_data[] = array('accid' => 'USWV0707', 'name' => 'Southside');
$city_data[] = array('accid' => 'USWV0708', 'name' => 'Spanishburg');
$city_data[] = array('accid' => 'USWV0709', 'name' => 'Spelter');
$city_data[] = array('accid' => 'USWV0710', 'name' => 'Spencer');
$city_data[] = array('accid' => 'USWV0711', 'name' => 'Sprague');
$city_data[] = array('accid' => 'USWV0712', 'name' => 'Spring Dale');
$city_data[] = array('accid' => 'USWV0713', 'name' => 'Springfield');
$city_data[] = array('accid' => 'USWV0714', 'name' => 'Spurlockville');
$city_data[] = array('accid' => 'USWV0715', 'name' => 'Squire');
$city_data[] = array('accid' => 'USWV0716', 'name' => 'Stanaford');
$city_data[] = array('accid' => 'USWV0717', 'name' => 'Statts Mills');
$city_data[] = array('accid' => 'USWV0718', 'name' => 'Stephenson');
$city_data[] = array('accid' => 'USWV0719', 'name' => 'Stirrat');
$city_data[] = array('accid' => 'USWV0720', 'name' => 'Stollings');
$city_data[] = array('accid' => 'USWV0721', 'name' => 'Strange Creek');
$city_data[] = array('accid' => 'USWV0722', 'name' => 'Sugar Grove');
$city_data[] = array('accid' => 'USWV0723', 'name' => 'Sumerco');
$city_data[] = array('accid' => 'USWV0724', 'name' => 'Summerlee');
$city_data[] = array('accid' => 'USWV0725', 'name' => 'Summersville');
$city_data[] = array('accid' => 'USWV0726', 'name' => 'Summit Point');
$city_data[] = array('accid' => 'USWV0727', 'name' => 'Surveyor');
$city_data[] = array('accid' => 'USWV0728', 'name' => 'Sutton');
$city_data[] = array('accid' => 'USWV0729', 'name' => 'Swiss');
$city_data[] = array('accid' => 'USWV0730', 'name' => 'Switchback');
$city_data[] = array('accid' => 'USWV0731', 'name' => 'Switzer');
$city_data[] = array('accid' => 'USWV0732', 'name' => 'Sylvester');
$city_data[] = array('accid' => 'USWV0733', 'name' => 'Tad');
$city_data[] = array('accid' => 'USWV0734', 'name' => 'Talcott');
$city_data[] = array('accid' => 'USWV0735', 'name' => 'Tallmansville');
$city_data[] = array('accid' => 'USWV0736', 'name' => 'Taplin');
$city_data[] = array('accid' => 'USWV0737', 'name' => 'Tariff');
$city_data[] = array('accid' => 'USWV0738', 'name' => 'Teays');
$city_data[] = array('accid' => 'USWV0739', 'name' => 'Terra Alta');
$city_data[] = array('accid' => 'USWV0740', 'name' => 'Terry');
$city_data[] = array('accid' => 'USWV0741', 'name' => 'Thacker');
$city_data[] = array('accid' => 'USWV0742', 'name' => 'Thomas');
$city_data[] = array('accid' => 'USWV0743', 'name' => 'Thornton');
$city_data[] = array('accid' => 'USWV0744', 'name' => 'Thorpe');
$city_data[] = array('accid' => 'USWV0745', 'name' => 'Thurmond');
$city_data[] = array('accid' => 'USWV0747', 'name' => 'Tioga');
$city_data[] = array('accid' => 'USWV0748', 'name' => 'Tornado');
$city_data[] = array('accid' => 'USWV0749', 'name' => 'Triadelphia');
$city_data[] = array('accid' => 'USWV0750', 'name' => 'Troy');
$city_data[] = array('accid' => 'USWV0751', 'name' => 'TRUE');
$city_data[] = array('accid' => 'USWV0752', 'name' => 'Tunnelton');
$city_data[] = array('accid' => 'USWV0753', 'name' => 'Turtle Creek');
$city_data[] = array('accid' => 'USWV0754', 'name' => 'Twilight');
$city_data[] = array('accid' => 'USWV0755', 'name' => 'Twin Branch');
$city_data[] = array('accid' => 'USWV0756', 'name' => 'Uneeda');
$city_data[] = array('accid' => 'USWV0757', 'name' => 'Union');
$city_data[] = array('accid' => 'USWV0758', 'name' => 'Upper Tract');
$city_data[] = array('accid' => 'USWV0759', 'name' => 'Upperglade');
$city_data[] = array('accid' => 'USWV0760', 'name' => 'Valley Bend');
$city_data[] = array('accid' => 'USWV0761', 'name' => 'Valley Fork');
$city_data[] = array('accid' => 'USWV0762', 'name' => 'Valley Grove');
$city_data[] = array('accid' => 'USWV0763', 'name' => 'Valley Head');
$city_data[] = array('accid' => 'USWV0764', 'name' => 'Van');
$city_data[] = array('accid' => 'USWV0765', 'name' => 'Varney');
$city_data[] = array('accid' => 'USWV0766', 'name' => 'Verdunville');
$city_data[] = array('accid' => 'USWV0767', 'name' => 'Verner');
$city_data[] = array('accid' => 'USWV0768', 'name' => 'Victor');
$city_data[] = array('accid' => 'USWV0769', 'name' => 'Vienna');
$city_data[] = array('accid' => 'USWV0770', 'name' => 'Volga');
$city_data[] = array('accid' => 'USWV0771', 'name' => 'Vulcan');
$city_data[] = array('accid' => 'USWV0772', 'name' => 'Wadestown');
$city_data[] = array('accid' => 'USWV0773', 'name' => 'Waiteville');
$city_data[] = array('accid' => 'USWV0774', 'name' => 'Walker');
$city_data[] = array('accid' => 'USWV0775', 'name' => 'Walkersville');
$city_data[] = array('accid' => 'USWV0776', 'name' => 'Wallace');
$city_data[] = array('accid' => 'USWV0777', 'name' => 'Wallback');
$city_data[] = array('accid' => 'USWV0778', 'name' => 'Walton');
$city_data[] = array('accid' => 'USWV0779', 'name' => 'Wana');
$city_data[] = array('accid' => 'USWV0780', 'name' => 'War');
$city_data[] = array('accid' => 'USWV0781', 'name' => 'Wardensville');
$city_data[] = array('accid' => 'USWV0782', 'name' => 'Warriormine');
$city_data[] = array('accid' => 'USWV0783', 'name' => 'Washington');
$city_data[] = array('accid' => 'USWV0784', 'name' => 'Waverly');
$city_data[] = array('accid' => 'USWV0785', 'name' => 'Wayne');
$city_data[] = array('accid' => 'USWV0786', 'name' => 'Wayside');
$city_data[] = array('accid' => 'USWV0787', 'name' => 'Webster Springs');
$city_data[] = array('accid' => 'USWV0788', 'name' => 'Weirton');
$city_data[] = array('accid' => 'USWV0789', 'name' => 'Welch');
$city_data[] = array('accid' => 'USWV0790', 'name' => 'Wellsburg');
$city_data[] = array('accid' => 'USWV0791', 'name' => 'West Columbia');
$city_data[] = array('accid' => 'USWV0792', 'name' => 'West Hamlin');
$city_data[] = array('accid' => 'USWV0793', 'name' => 'West Liberty');
$city_data[] = array('accid' => 'USWV0794', 'name' => 'West Milford');
$city_data[] = array('accid' => 'USWV0795', 'name' => 'West Union');
$city_data[] = array('accid' => 'USWV0796', 'name' => 'Weston');
$city_data[] = array('accid' => 'USWV0797', 'name' => 'Wharncliffe');
$city_data[] = array('accid' => 'USWV0798', 'name' => 'Wharton');
$city_data[] = array('accid' => 'USWV0799', 'name' => 'Wheeling');
$city_data[] = array('accid' => 'USWV0800', 'name' => 'White Oak');
$city_data[] = array('accid' => 'USWV0801', 'name' => 'White Sulphur Springs');
$city_data[] = array('accid' => 'USWV0802', 'name' => 'Whitesville');
$city_data[] = array('accid' => 'USWV0803', 'name' => 'Whitman');
$city_data[] = array('accid' => 'USWV0804', 'name' => 'Whitmer');
$city_data[] = array('accid' => 'USWV0805', 'name' => 'Widen');
$city_data[] = array('accid' => 'USWV0806', 'name' => 'Wilcoe');
$city_data[] = array('accid' => 'USWV0807', 'name' => 'Wiley Ford');
$city_data[] = array('accid' => 'USWV0808', 'name' => 'Wileyville');
$city_data[] = array('accid' => 'USWV0809', 'name' => 'Wilkinson');
$city_data[] = array('accid' => 'USWV0810', 'name' => 'Williamsburg');
$city_data[] = array('accid' => 'USWV0811', 'name' => 'Williamson');
$city_data[] = array('accid' => 'USWV0812', 'name' => 'Williamstown');
$city_data[] = array('accid' => 'USWV0813', 'name' => 'Wilsie');
$city_data[] = array('accid' => 'USWV0814', 'name' => 'Wilsonburg');
$city_data[] = array('accid' => 'USWV0815', 'name' => 'Wilsondale');
$city_data[] = array('accid' => 'USWV0816', 'name' => 'Windsor Heights');
$city_data[] = array('accid' => 'USWV0817', 'name' => 'Winfield');
$city_data[] = array('accid' => 'USWV0818', 'name' => 'Winifrede');
$city_data[] = array('accid' => 'USWV0819', 'name' => 'Winona');
$city_data[] = array('accid' => 'USWV0821', 'name' => 'Wolf Pen');
$city_data[] = array('accid' => 'USWV0822', 'name' => 'Wolfcreek');
$city_data[] = array('accid' => 'USWV0823', 'name' => 'Wolfe');
$city_data[] = array('accid' => 'USWV0824', 'name' => 'Woodville');
$city_data[] = array('accid' => 'USWV0825', 'name' => 'Worth');
$city_data[] = array('accid' => 'USWV0826', 'name' => 'Worthington');
$city_data[] = array('accid' => 'USWV0827', 'name' => 'Wyatt');
$city_data[] = array('accid' => 'USWV0828', 'name' => 'Wyco');
$city_data[] = array('accid' => 'USWV0829', 'name' => 'Wyoming');
$city_data[] = array('accid' => 'USWV0830', 'name' => 'Yawkey');
$city_data[] = array('accid' => 'USWV0831', 'name' => 'Yellow Spring');
$city_data[] = array('accid' => 'USWV0832', 'name' => 'Yolyn');
$city_data[] = array('accid' => 'USWV0833', 'name' => 'Yukon');

?>
