<?php

// City package for USA: Wyoming 

$city_name = 'USA: Wyoming';
$city_version = '1.0.2';
$city_data = array();


$city_data[] = array('accid' => 'USWY0001', 'name' => 'Afton');
$city_data[] = array('accid' => 'USWY0002', 'name' => 'Aladdin');
$city_data[] = array('accid' => 'USWY0003', 'name' => 'Albin');
$city_data[] = array('accid' => 'USWY0004', 'name' => 'Alcova');
$city_data[] = array('accid' => 'USWY0005', 'name' => 'Alpine');
$city_data[] = array('accid' => 'USWY0185', 'name' => 'Alta');
$city_data[] = array('accid' => 'USWY0006', 'name' => 'Alva');
$city_data[] = array('accid' => 'USWY0007', 'name' => 'Arapahoe');
$city_data[] = array('accid' => 'USWY0008', 'name' => 'Arminto');
$city_data[] = array('accid' => 'USWY0009', 'name' => 'Arvada');
$city_data[] = array('accid' => 'USWY0010', 'name' => 'Auburn');
$city_data[] = array('accid' => 'USWY0011', 'name' => 'Baggs');
$city_data[] = array('accid' => 'USWY0012', 'name' => 'Bairoil');
$city_data[] = array('accid' => 'USWY0013', 'name' => 'Banner');
$city_data[] = array('accid' => 'USWY0014', 'name' => 'Basin');
$city_data[] = array('accid' => 'USWY0015', 'name' => 'Bedford');
$city_data[] = array('accid' => 'USWY0016', 'name' => 'Beulah');
$city_data[] = array('accid' => 'USWY0017', 'name' => 'Big Horn');
$city_data[] = array('accid' => 'USWY0018', 'name' => 'Big Piney');
$city_data[] = array('accid' => 'USWY0019', 'name' => 'Bill');
$city_data[] = array('accid' => 'USWY0020', 'name' => 'Bondurant');
$city_data[] = array('accid' => 'USWY0021', 'name' => 'Bosler');
$city_data[] = array('accid' => 'USWY0022', 'name' => 'Boulder');
$city_data[] = array('accid' => 'USWY0023', 'name' => 'Buffalo');
$city_data[] = array('accid' => 'USWY0024', 'name' => 'Buford');
$city_data[] = array('accid' => 'USWY0025', 'name' => 'Burlington');
$city_data[] = array('accid' => 'USWY0026', 'name' => 'Burns');
$city_data[] = array('accid' => 'USWY0027', 'name' => 'Byron');
$city_data[] = array('accid' => 'USWY0028', 'name' => 'Carlile');
$city_data[] = array('accid' => 'USWY0029', 'name' => 'Carpenter');
$city_data[] = array('accid' => 'USWY0030', 'name' => 'Casper');
$city_data[] = array('accid' => 'USWY0031', 'name' => 'Centennial');
$city_data[] = array('accid' => 'USWY0032', 'name' => 'Cheyenne');
$city_data[] = array('accid' => 'USWY0033', 'name' => 'Chugwater');
$city_data[] = array('accid' => 'USWY0034', 'name' => 'Clearmont');
$city_data[] = array('accid' => 'USWY0035', 'name' => 'Cody');
$city_data[] = array('accid' => 'USWY0036', 'name' => 'Cokeville');
$city_data[] = array('accid' => 'USWY0037', 'name' => 'Cora');
$city_data[] = array('accid' => 'USWY0038', 'name' => 'Cowley');
$city_data[] = array('accid' => 'USWY0039', 'name' => 'Crowheart');
$city_data[] = array('accid' => 'USWY0040', 'name' => 'Daniel');
$city_data[] = array('accid' => 'USWY0041', 'name' => 'Dayton');
$city_data[] = array('accid' => 'USWY0042', 'name' => 'Deaver');
$city_data[] = array('accid' => 'USWY0043', 'name' => 'Devils Tower');
$city_data[] = array('accid' => 'USWY0045', 'name' => 'Diamondville');
$city_data[] = array('accid' => 'USWY0046', 'name' => 'Dixon');
$city_data[] = array('accid' => 'USWY0047', 'name' => 'Douglas');
$city_data[] = array('accid' => 'USWY0048', 'name' => 'Dubois');
$city_data[] = array('accid' => 'USWY0049', 'name' => 'Edgerton');
$city_data[] = array('accid' => 'USWY0050', 'name' => 'Elk Mountain');
$city_data[] = array('accid' => 'USWY0051', 'name' => 'Emblem');
$city_data[] = array('accid' => 'USWY0052', 'name' => 'Encampment');
$city_data[] = array('accid' => 'USWY0053', 'name' => 'Etna');
$city_data[] = array('accid' => 'USWY0054', 'name' => 'Evanston');
$city_data[] = array('accid' => 'USWY0055', 'name' => 'Evansville');
$city_data[] = array('accid' => 'USWY0056', 'name' => 'F E Warren AFB');
$city_data[] = array('accid' => 'USWY0057', 'name' => 'Fairview');
$city_data[] = array('accid' => 'USWY0058', 'name' => 'Farson');
$city_data[] = array('accid' => 'USWY0059', 'name' => 'Fort Bridger');
$city_data[] = array('accid' => 'USWY0060', 'name' => 'Fort Laramie');
$city_data[] = array('accid' => 'USWY0061', 'name' => 'Fort Washakie');
$city_data[] = array('accid' => 'USWY0062', 'name' => 'Four Corners');
$city_data[] = array('accid' => 'USWY0063', 'name' => 'Frannie');
$city_data[] = array('accid' => 'USWY0064', 'name' => 'Freedom');
$city_data[] = array('accid' => 'USWY0065', 'name' => 'Frontier');
$city_data[] = array('accid' => 'USWY0066', 'name' => 'Garrett');
$city_data[] = array('accid' => 'USWY0067', 'name' => 'Gillette');
$city_data[] = array('accid' => 'USWY0068', 'name' => 'Glendo');
$city_data[] = array('accid' => 'USWY0069', 'name' => 'Glenrock');
$city_data[] = array('accid' => 'USWY0071', 'name' => 'Granger');
$city_data[] = array('accid' => 'USWY0072', 'name' => 'Granite Canon');
$city_data[] = array('accid' => 'USWY0073', 'name' => 'Green River');
$city_data[] = array('accid' => 'USWY0074', 'name' => 'Greybull');
$city_data[] = array('accid' => 'USWY0075', 'name' => 'Grover');
$city_data[] = array('accid' => 'USWY0076', 'name' => 'Guernsey');
$city_data[] = array('accid' => 'USWY0077', 'name' => 'Hamilton Dome');
$city_data[] = array('accid' => 'USWY0078', 'name' => 'Hanna');
$city_data[] = array('accid' => 'USWY0079', 'name' => 'Hartville');
$city_data[] = array('accid' => 'USWY0080', 'name' => 'Hawk Springs');
$city_data[] = array('accid' => 'USWY0081', 'name' => 'Hiland');
$city_data[] = array('accid' => 'USWY0082', 'name' => 'Hillsdale');
$city_data[] = array('accid' => 'USWY0083', 'name' => 'Horse Creek');
$city_data[] = array('accid' => 'USWY0084', 'name' => 'Hudson');
$city_data[] = array('accid' => 'USWY0085', 'name' => 'Hulett');
$city_data[] = array('accid' => 'USWY0086', 'name' => 'Huntley');
$city_data[] = array('accid' => 'USWY0087', 'name' => 'Hyattville');
$city_data[] = array('accid' => 'USWY0088', 'name' => 'Jackson');
$city_data[] = array('accid' => 'USWY0090', 'name' => 'Jay Em');
$city_data[] = array('accid' => 'USWY0091', 'name' => 'Jeffrey City');
$city_data[] = array('accid' => 'USWY0092', 'name' => 'Jelm');
$city_data[] = array('accid' => 'USWY0093', 'name' => 'Kaycee');
$city_data[] = array('accid' => 'USWY0094', 'name' => 'Kelly');
$city_data[] = array('accid' => 'USWY0095', 'name' => 'Kemmerer');
$city_data[] = array('accid' => 'USWY0096', 'name' => 'Kinnear');
$city_data[] = array('accid' => 'USWY0097', 'name' => 'Kirby');
$city_data[] = array('accid' => 'USWY0098', 'name' => 'La Barge');
$city_data[] = array('accid' => 'USWY0099', 'name' => 'Lagrange');
$city_data[] = array('accid' => 'USWY0100', 'name' => 'Lance Creek');
$city_data[] = array('accid' => 'USWY0101', 'name' => 'Lander');
$city_data[] = array('accid' => 'USWY0102', 'name' => 'Laramie');
$city_data[] = array('accid' => 'USWY0103', 'name' => 'Leiter');
$city_data[] = array('accid' => 'USWY0104', 'name' => 'Linch');
$city_data[] = array('accid' => 'USWY0105', 'name' => 'Lingle');
$city_data[] = array('accid' => 'USWY0106', 'name' => 'Little America');
$city_data[] = array('accid' => 'USWY0107', 'name' => 'Lontetree');
$city_data[] = array('accid' => 'USWY0108', 'name' => 'Lost Springs');
$city_data[] = array('accid' => 'USWY0109', 'name' => 'Lovell');
$city_data[] = array('accid' => 'USWY0110', 'name' => 'Lusk');
$city_data[] = array('accid' => 'USWY0111', 'name' => 'Lyman');
$city_data[] = array('accid' => 'USWY0112', 'name' => 'Lysite');
$city_data[] = array('accid' => 'USWY0113', 'name' => 'Manderson');
$city_data[] = array('accid' => 'USWY0114', 'name' => 'Manville');
$city_data[] = array('accid' => 'USWY0115', 'name' => 'McKinnon');
$city_data[] = array('accid' => 'USWY0116', 'name' => 'Medicine Bow');
$city_data[] = array('accid' => 'USWY0117', 'name' => 'Meeteetse');
$city_data[] = array('accid' => 'USWY0118', 'name' => 'Meriden');
$city_data[] = array('accid' => 'USWY0119', 'name' => 'Midwest');
$city_data[] = array('accid' => 'USWY0120', 'name' => 'Mills');
$city_data[] = array('accid' => 'USWY0121', 'name' => 'Moorcroft');
$city_data[] = array('accid' => 'USWY0122', 'name' => 'Moose');
$city_data[] = array('accid' => 'USWY0123', 'name' => 'Moran');
$city_data[] = array('accid' => 'USWY0124', 'name' => 'Mountain View');
$city_data[] = array('accid' => 'USWY0125', 'name' => 'Natrona');
$city_data[] = array('accid' => 'USWY0126', 'name' => 'Newcastle');
$city_data[] = array('accid' => 'USWY0127', 'name' => 'Opal');
$city_data[] = array('accid' => 'USWY0129', 'name' => 'Osage');
$city_data[] = array('accid' => 'USWY0130', 'name' => 'Otto');
$city_data[] = array('accid' => 'USWY0131', 'name' => 'Parkman');
$city_data[] = array('accid' => 'USWY0132', 'name' => 'Pavillion');
$city_data[] = array('accid' => 'USWY0133', 'name' => 'Pine Bluffs');
$city_data[] = array('accid' => 'USWY0134', 'name' => 'Pinedale');
$city_data[] = array('accid' => 'USWY0135', 'name' => 'Point Of Rocks');
$city_data[] = array('accid' => 'USWY0136', 'name' => 'Powder River');
$city_data[] = array('accid' => 'USWY0137', 'name' => 'Powell');
$city_data[] = array('accid' => 'USWY0138', 'name' => 'Ralston');
$city_data[] = array('accid' => 'USWY0139', 'name' => 'Ranchester');
$city_data[] = array('accid' => 'USWY0140', 'name' => 'Rawlins');
$city_data[] = array('accid' => 'USWY0141', 'name' => 'Recluse');
$city_data[] = array('accid' => 'USWY0142', 'name' => 'Reliance');
$city_data[] = array('accid' => 'USWY0143', 'name' => 'Riverton');
$city_data[] = array('accid' => 'USWY0144', 'name' => 'Robertson');
$city_data[] = array('accid' => 'USWY0145', 'name' => 'Rock River');
$city_data[] = array('accid' => 'USWY0146', 'name' => 'Rock Springs');
$city_data[] = array('accid' => 'USWY0147', 'name' => 'Rozet');
$city_data[] = array('accid' => 'USWY0148', 'name' => 'Saddlestring');
$city_data[] = array('accid' => 'USWY0149', 'name' => 'Saint Stephens');
$city_data[] = array('accid' => 'USWY0150', 'name' => 'Saratoga');
$city_data[] = array('accid' => 'USWY0151', 'name' => 'Savery');
$city_data[] = array('accid' => 'USWY0152', 'name' => 'Shawnee');
$city_data[] = array('accid' => 'USWY0153', 'name' => 'Shell');
$city_data[] = array('accid' => 'USWY0154', 'name' => 'Sheridan');
$city_data[] = array('accid' => 'USWY0155', 'name' => 'Shirley Basin');
$city_data[] = array('accid' => 'USWY0156', 'name' => 'Shoshoni');
$city_data[] = array('accid' => 'USWY0157', 'name' => 'Sinclair');
$city_data[] = array('accid' => 'USWY0158', 'name' => 'Smoot');
$city_data[] = array('accid' => 'USWY0160', 'name' => 'Story');
$city_data[] = array('accid' => 'USWY0161', 'name' => 'Sundance');
$city_data[] = array('accid' => 'USWY0162', 'name' => 'Superior');
$city_data[] = array('accid' => 'USWY0163', 'name' => 'Ten Sleep');
$city_data[] = array('accid' => 'USWY0164', 'name' => 'Teton Village');
$city_data[] = array('accid' => 'USWY0165', 'name' => 'Thayne');
$city_data[] = array('accid' => 'USWY0166', 'name' => 'Thermopolis');
$city_data[] = array('accid' => 'USWY0167', 'name' => 'Tie Siding');
$city_data[] = array('accid' => 'USWY0168', 'name' => 'Torrington');
$city_data[] = array('accid' => 'USWY0169', 'name' => 'Upton');
$city_data[] = array('accid' => 'USWY0170', 'name' => 'Van Tassell');
$city_data[] = array('accid' => 'USWY0171', 'name' => 'Veteran');
$city_data[] = array('accid' => 'USWY0172', 'name' => 'Walcott');
$city_data[] = array('accid' => 'USWY0173', 'name' => 'Wamsutter');
$city_data[] = array('accid' => 'USWY0174', 'name' => 'Wapiti');
$city_data[] = array('accid' => 'USWY0175', 'name' => 'Weston');
$city_data[] = array('accid' => 'USWY0176', 'name' => 'Wheatland');
$city_data[] = array('accid' => 'USWY0177', 'name' => 'Wilson');
$city_data[] = array('accid' => 'USWY0178', 'name' => 'Wolf');
$city_data[] = array('accid' => 'USWY0179', 'name' => 'Worland');
$city_data[] = array('accid' => 'USWY0180', 'name' => 'Wright');
$city_data[] = array('accid' => 'USWY0181', 'name' => 'Wyarno');
$city_data[] = array('accid' => 'USWY0183', 'name' => 'Yellowstone Natl Park');
$city_data[] = array('accid' => 'USWY0184', 'name' => 'Yoder');

?>
